### ISSUE TITLE
Mattermost down ?

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#1024]
Ah j'ai perdu mes accès mattermost ou bien il y a un petit soucis avec la plateforme ? Je n'arrive plus à me connecter et le renvoi du mdp de fonctionne pas ?

**Comment by lionelB** [comment]
non, çamarche™ !

**Comment by UnbearableBear** [comment]
J'arrive plus à me co, quelqu'un pourrait me dire quels sont mes identifiants ? Apparement ce n'est pas mon adresse mail !

**Comment by UnbearableBear** [comment]
Trouvé :D
