### ISSUE TITLE
Période d'asbence erratique dans le calculateur d'indemnité

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#1025]
Il semblerait que la période d'absence prolongée ne soit pas correctement calculée.

Dans le calculateur d'indemnités de licenciement, aller à l'étape 3 (ancienneté) et renseigner une période d'absence prolongée (plusieurs mois ou années, peu importe). L'ancienneté n'est pas calculée à jour correctement.

Il faudrait que cette absence soit retranchée de l'ancienneté.

Avant saisie de période:
<img width="932" alt="Screenshot 2019-07-12 at 12 38 04" src="https://user-images.githubusercontent.com/705453/61122418-09f1a780-a4a2-11e9-9b74-bce1724076bb.png">

Après saisie de période:
<img width="933" alt="Screenshot 2019-07-12 at 12 38 21" src="https://user-images.githubusercontent.com/705453/61122443-1413a600-a4a2-11e9-89a1-d703b7f72e3c.png">

**Comment by lionelB** [comment]
![oh-noes](https://user-images.githubusercontent.com/160320/61139169-20f7c000-a4c9-11e9-9e88-d440a1b01f53.gif)
