### ISSUE TITLE
Ferrer à gauche le contenu dans les outils

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1030]
### maintenant 
![Image collée à 2019-7-8 17-56](https://user-images.githubusercontent.com/5337489/61231124-b2ff0300-a72b-11e9-8a1c-227b1f62b13a.png)

### après
![Image collée à 2019-7-8 17-59](https://user-images.githubusercontent.com/5337489/61231136-bb573e00-a72b-11e9-9b0f-d4295296c939.png)

**Comment by UnbearableBear** [comment]
Aie aie aie, ca a codé pour faire le dernier screenshot :D 💃
