### ISSUE TITLE
[nouveaux parcours] Éléments globaux

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1035]
### Menu global

![header](https://user-images.githubusercontent.com/5337489/62029130-2ef45300-b1e2-11e9-9b3c-5d04ea4a3650.png)

pour l'instant on n'a pas les pages "boite à outils" et "catégories" donc on ne met que le lien vers la page à propos et la recherche.

### Footer global

![footer](https://user-images.githubusercontent.com/5337489/62029240-64993c00-b1e2-11e9-921d-896126d5d9a0.png)

**Comment by lionelB** [comment]
ca pointe vers quoi la page "votre réponse personnalisée" ?

**Comment by lionelB** [comment]
ca serait top d'avoir la version mobile  
De manière générale, à chaque fois qu'on doit intégrer une page, avoir la version mini ca aide bien et permet de gagner un peu de temps

**Comment by ClementChapalain** [comment]
outdated
