### ISSUE TITLE
[nouveaux parcours] Redesign fiche SP

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1036]
Nouveau design des fiches service-public.fr.

### Design global

Lien vers figma ("24 juillet gabarits") : https://www.figma.com/file/UxFXYDg1TszvYBgDYj4foB5q/CDTN-design-sprint?node-id=263%3A4284

#### desktop
![article](https://user-images.githubusercontent.com/5337489/62029424-d07ba480-b1e2-11e9-80da-f4141ce31626.png)

#### mobile
![iPhone 8 6](https://user-images.githubusercontent.com/5337489/62029503-015bd980-b1e3-11e9-9134-f04950f02d31.png)

### Non traité dans cette tâche

Header / Footer -> #1035 
Lien avec les outils
Lien avec les thèmes / collections
Articles associés sur la droite de l'écran
Module de recherche CCN

#### Bandeau principal
![image](https://user-images.githubusercontent.com/5337489/61379551-0dbd6980-a8a8-11e9-90c4-5b62eb223f9a.png)

----

#### Header sticky
![image](https://user-images.githubusercontent.com/5337489/61380439-ab656880-a8a9-11e9-8675-39bba2dcb592.png)

----

#### Tabs principales
Si on a des tabs principales dans une fiche SP.
![image](https://user-images.githubusercontent.com/5337489/61379651-3c3b4480-a8a8-11e9-8498-ee0f8c022913.png)

----

#### Menu sticky à gauche 
Ce menu reprend les actuels accordéons. En mobile on utilise des accordéons.
![image](https://user-images.githubusercontent.com/5337489/61379683-478e7000-a8a8-11e9-8ffa-307b214352e5.png)

----

#### Tabs secondaires
En mobile prévoir un scroll horizontal.
![image](https://user-images.githubusercontent.com/5337489/61379808-87edee00-a8a8-11e9-945d-c17037667696.png)

----

#### Sources juridiques
![image](https://user-images.githubusercontent.com/5337489/61379731-5ffe8a80-a8a8-11e9-8553-07b4840f5987.png)

**Comment by revolunet** [comment]
A quoi correspondent Onglet 1 / Onglet 2 dans une fiche SP ?

**Comment by ClementChapalain** [comment]
aux onglets de premier niveau quand il y en a, par exemple sur cette fiche :
https://www.service-public.fr/particuliers/vosdroits/F2883

**Comment by UnbearableBear** [comment]
Pour l'instant elle sont de facto transformées en accordéon ce qui a le mérite d'etre un peu plus mobile friendly mais rien d'impossible je pense. Il faudra juste "scroll" horizontalement les tabs sur mobile :'(

**Comment by UnbearableBear** [comment]
Et en plus je dis des bêtises, c'est déjà des tabs ceux là !

**Comment by ClementChapalain** [comment]
outdated
