### ISSUE TITLE
[nouveaux parcours] Redesign fiches MT

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1037]
Nouveau design des fiches du ministère du travail.

### Design global
![Préavis licenciement](https://user-images.githubusercontent.com/5337489/61379952-c97e9900-a8a8-11e9-96c5-87f15e029641.png)

### Non traité dans cette tâche

Header / Footer
Thèmes
Articles associés

#### Bandeau principal
![image](https://user-images.githubusercontent.com/5337489/61379971-d4d1c480-a8a8-11e9-8458-b7b9c0d7e4d3.png)

----

#### Header sticky
![image](https://user-images.githubusercontent.com/5337489/61380492-bd470b80-a8a9-11e9-99d3-5e2860049f7f.png)

----

#### Marges plus importantes entre 2 paragraphes
![image](https://user-images.githubusercontent.com/5337489/61380062-fdf25500-a8a8-11e9-9fc3-61ca57ff4ff4.png)

**Comment by lionelB** [comment]
est ce qu'on a des details sur le header sticky ? a partir de quand il se met ?
Apres je suis pas sur qu'on puisse faire ça san refaire le header de la page

**Comment by ClementChapalain** [comment]
outdated
