### ISSUE TITLE
Liens vers les thèmes depuis les fiches SP et MT

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1039]
Entre le contenu de la fiche SP ou MT et le footer, on ajoute un rebond vers les thèmes dans lesquels se trouve la fiche qu'on est en train de lire afin de faciliter la découvrabilité des contenus.

![image](https://user-images.githubusercontent.com/5337489/61382887-e073ba00-a8ad-11e9-9dd2-e4d615f16019.png)

Les fiches présentées peuvent être choisis au hasard dans un premier temps (en excluant la fiche sur laquelle se trouve l'utilisateur).

**Comment by lionelB** [comment]
pour l'instant, une fiche se trouve dans un seul theme. donc on aura qu'un bloc et pas trois.
on peut prendre des themes cousin de l'arborescence mais on a aucune metric qui permettent de choisir si les 3 themes auront un lien ou pas

**Comment by ClementChapalain** [comment]
je croyais qu'une fiche peut se trouver dans plusieurs thèmes (cf. ici thème CDTN 1, 2, 3, 4 : https://docs.google.com/spreadsheets/d/1CVRrR45QIlSzVeO_9V1TUXSqI1U9Bt5_KYWlcH9K2jI/edit#gid=830691529) ?

si chaque fiche n'a qu'un thème on va attendre pour cette fonctionnalité du coup

**Comment by lionelB** [comment]
pour l'instant c'est qu'une fiche
