### ISSUE TITLE
Form Feedback

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#104]
S'assurer que le message parte TOUJOURS :)

**Comment by jrduscher** [comment]
bouteille à la mer lancée

**Comment by revolunet** [comment]
- OK en prod
 - NOK en dev : les emails ne partent pas mais l'usager est informé

**Comment by lionelB** [comment]
on ferme ?

**Comment by ClementChapalain** [comment]
C'est ok ça non @jrduscher @revolunet ?

**Comment by lionelB** [comment]
yep !

**Comment by ClementChapalain** [comment]
🙌
