### ISSUE TITLE
Fiches DGT/SP : ancres paragraphes

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#105]
restaurer les ancres dans index + redirection

fonctionnait dans la v1.0

**Comment by jrduscher** [comment]
Afficher uniquement dans la page le paragraphe grace aux ancres posées ( voir version de marc?)
possibilité de voir la fiche ministère complète en lien externe ( onglet)

**Comment by revolunet** [comment]
En règle générale, pouvoir target un paragraphe particulier d'un document

**Comment by lionelB** [comment]
sur le site service public, le contenu n'est pas ciblable car presenté dans un "accordion" ou de base tout est caché

Est il possible d'avoir des infos sur la version qui fonctionné (url, version, ...)?

**Comment by revolunet** [comment]
A priori, nous indexions les paragraphes des fiches ministère du travail; mais elle n'étaient pas affichées directement sur notre site, on a avait des liens externes avec une ancre

**Comment by jrduscher** [comment]
Review 1.2:
test sur fiche ministère " en quoi consiste la rupture conventionnelle"
les intitulés de paragraphe apparaissent bien dans les requêtes. Le résulat pointe sur l'affichage globale de la fiche, au début de la fiche. l'idée est de rnevoyer à minima vers le résultat au niveau du paragraphe dans la fiche complète et l'idéal est ne n'afficher que le paragraphe en question+ url vers la fiche complète.

**Comment by revolunet** [comment]
Fonctionne maintenant chez moi avec cette question " en quoi consiste la rupture conventionnelle"

-> https://codedutravail-dev.num.social.gouv.fr/

**Comment by Loze-Faelens** [comment]
- Cela fonctionne en renvoi vers le paragraphe de la fiche complète. Est-ce que l'on va plus loin en ne proposant que le paragraphe ?
//JR: si mais dans une nouvelle issue à ce moment là.
