### ISSUE TITLE
Associer référence juridique aux outils

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1059]
L'objectif est de pouvoir simplifier la veille juridique sur les outils en étant alerté lorsque le droit évolue. Pour cela, il faut connaître la bonne référence juridique pour chaque outil, et chaque convention collective traitée.

To do :
- Lister les références pour les premiers outils créés : @ClementChapalain 
- Comment stocker ces références ? dans une interface séparée ? dans le data-filler ?

**Comment by revolunet** [comment]
(utiliser les urls Legifrance)

**Comment by jrduscher** [comment]
Tableau avec les références juridiques pour les outils:

https://docs.google.com/spreadsheets/d/1FVzGw_UdX_mMTdwq0RWeUjyo_YpdyyXJtQBgCkzH6Zs/edit#gid=0

**Comment by ClementChapalain** [comment]
on ferme cette tâche vu que le travail est fait côté métier, désormais discussion à avoir sur comment gérer ces références. je prends le sujet pour cadrage :).
