### ISSUE TITLE
Ordre d'affichage articles CDT

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#106]
L > R > D

 - groupés par les 4 premiers chiffres
 - dans l'ordre de la numérotation des articles

**Comment by revolunet** [comment]
quand plusieurs résultats sur le préfixe à 4 chiffres, faire en sorte :
 - d'afficher le L en premier
 - puis par ordre dans le CDT

**Comment by lionelB** [comment]
Est ce que c'est possible d'avoir plus de détail sur L > R > D ?
je pense qu'on doit pouvoir regler cela avec un paraméttrage d'elastic search ?

**Comment by revolunet** [comment]
- L: Législatif
 - R: Réglementaire
 - D: Décret

**Comment by revolunet** [comment]
pourrait être réglé côté ES ?

**Comment by revolunet** [comment]
@jrduscher est-ce que ce sujet à traiter ? je ne le vois pas dans Trello.
