### ISSUE TITLE
Utiliser le nouveau fichier idcc siret pour la recherche de ccn

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1060]

**Comment by ClementChapalain** [comment]
est-ce que le fichier est prêt à être utilisé @revolunet ?

**Comment by revolunet** [comment]
Oui. on va devoir le croiser avec http://files.data.gouv.fr/insee-sirene/ pour avoir aussi le nom d'établissement comme c'est le cas actuellement. J'essaie de finaliser cette semaine.

**Comment by revolunet** [comment]
nb: ce fichier ne liste pas les établissements fermés

**Comment by revolunet** [comment]
l'API SIRENE va évoluer dans les 15 jours qui viennent, on attend leur nouvelle version pour la partie "recherche par nom"

**Comment by revolunet** [comment]
- recherche par siret : https://entreprise.data.gouv.fr/api/sirene/v1/siret/21340172201787/
 - recherche fulltext: https://entreprise.data.gouv.fr/api/sirene/v1/full_text/boulangerie%20pain%20des%20copains

**Comment by revolunet** [comment]
Démo d'un widget avec API sirène : https://pmfxf.csb.app

 - permet de chercher par nom entreprise et CC, siret ou idcc
 - utilise les dernieres données siret2idcc
 - utilise l'[api sirene](https://entreprise.data.gouv.fr/api_doc_sirene) côté client ce qui permet de déléguer la recherche texte à nos amis de data.gouv

**Comment by UnbearableBear** [comment]
Propre !! Dommage que la recherche ne soit faite que sur des nom complets (pas d'auto complétion)

**Comment by revolunet** [comment]
Je propose qu'on intègre cette première version et qu'on refasse une passe UX

**Comment by revolunet** [comment]
- voir comment gérer le cas 9999 (code "balai")
 - revoir le wording "Aucune CC connue pour cette entreprise"
 - si pas de CC connue, fallback sur code NAF ?
 - gestion des SIREN

**Comment by revolunet** [comment]
incoming PR

**Comment by ClementChapalain** [comment]
on est en où sur cette tâche @revolunet ?

**Comment by revolunet** [comment]
Pour moi c'est prêt dans la PR #1077 - un déploiement de test arrive dans quelques minutes

**Comment by lionelB** [comment]
je close car la PR #1077 a été mergée
