### ISSUE TITLE
Créer un outil pour gérer les thèmes

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1061]
## Contexte et objectifs

Nous avions une première version des thèmes CDTN ici :
https://docs.google.com/spreadsheets/d/1CVRrR45QIlSzVeO_9V1TUXSqI1U9Bt5_KYWlcH9K2jI/edit#gid=1783422693

Nous en avons fait une deuxième ici en réduisant le nombre de thèmes (283->125), de niveaux dans l'arborescence (4->3) et en homogénéisant la précision des thèmes :
https://docs.google.com/spreadsheets/d/1BT5B9P8SFxEkdYXfuBM4ydvDWKW9gQTIQdrU7V0D9FA/edit#gid=2006001936

Afin d'améliorer le système de gestion des thèmes et ne plus passer par des spreadsheets, nous souhaitons construire un outil pour gérer ces thèmes.

## To do

thèmes :
- Pouvoir créer / modifier / supprimer un thème
- Pouvoir ajouter une description à un thème
- Pouvoir associer des contenus (SP, MT, QR, outils) à un thème et pouvoir supprimer des associations (un contenu ne peut être associé qu'à un seul thème)

collections (=thèmes éditorialisés) :
- Pouvoir créer / modifier / supprimer des collections
- Pouvoir ajouter une description à une collection
- Pouvoir associer des contenus (SP, MT, QR, outils) à une collection et pouvoir supprimer des associations (un contenu peut être associé à plusieurs collections)

**Comment by revolunet** [comment]
Faisable :
 - ajouter une liste "themes" au datafiller permettant de sélectionner les résultats à afficher et un texte édito
 - idem pour des collections

la seule différence serait qu'un contenu ne peut être référencé que dans un "thème" mais dans plusieurs "collections" ?

Une "collection" n'est-elle pas simplement là synthèse de plusieurs thèmes ?

J'ai peur que d'avoir deux notions soit confusing pour l'usager

**Comment by ClementChapalain** [comment]
En fait une collection c'est un regroupement d'articles qui sont liés par un sujet comme particulier employeur par exemple : c'est pas une catégorie du droit du travail, mais c'est quelque chose qu'on peut trouver dans plein de catégories (embauche, contrat, salaire, licenciement, etc.).

On peut aussi imaginer des collections : jeunes travailleurs, maternité, canicule, etc.

Je suis d'accord sur le fait que ce soit confus, p-e que dans le front on les appellera de la même manière.

**Comment by ClementChapalain** [comment]
Lien vers le figma :
https://www.figma.com/proto/kPX7UI7HcJ7l576ErfciGq/Administration?node-id=1%3A1213&viewport=42%2C-128%2C0.5230914950370789&scaling=min-zoom

Lien vers le tableau de classification des thèmes V2 :
https://docs.google.com/spreadsheets/d/1BT5B9P8SFxEkdYXfuBM4ydvDWKW9gQTIQdrU7V0D9FA/edit#gid=0

**Comment by lionelB** [comment]
je ne vois pas de différence entre theme et collection 
les 2 regroupes des articles. la seule différence est qu'on va utiliser les themes pour afficher une arborescence

**Comment by lionelB** [comment]
added to datafiller
