### ISSUE TITLE
Classification des CCNs dans les 13 thèmes

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1064]
Permettre de classifier le contenu des conventions collectives selon les 13 thèmes de la HDN qui indiquent la branche comme étant prioritaire pour les négociations.

Cela nous permettra d'afficher le contenu pertinent des conventions collectives aux utilisateurs.

Nouvelle fonctionnalité du data-filler.

On fait le point après avoir classifier quelques CCNs pour voir si la donnée obtenue est utilisable simplement.

**Comment by revolunet** [comment]
Une première version est dispo sur le [datafiller](https://datafiller.num.social.gouv.fr)

Permet de classer chaque article des 20 principales CCN (par effectif) dans un ou plusieurs des **17 blocs de la HDN**.

Objectifs :
 - pouvoir extraire les articles pertinents des CCNs en fonction de la question utilisateur (restera à classifier/lier la question dans un des 17 thèmes). ce qui permettra de lui afficher les articles pertinents de sa CC en fonction de sa question
 - pouvoir entrainer un algo à detecter à quel bloc appartient un article

**Comment by revolunet** [comment]
todo: remplir les données :)

**Comment by ClementChapalain** [comment]
:rocket:
