### ISSUE TITLE
Mise à jour calcul syntec

### ISSUE THREAD

**Issue by June-law** [SocialGouv/code-du-travail-numerique#1065]
Dans l'outil "Calculateur de l'indemnité de licenciement", il faut faire des modifications pour l'indemnité de licenciement dans la Syntec.
Pour le chargé d'enquête (intermittent et non intermittent), il ne faut plus demander l'ajustement de l'ancienneté.
Mais une fois que l'usager aura choisi la catégorie "chargé d'enquête intermittent" ou "chargé d'enquête non intermittent", faire apparaître un cadre avec le texte suivant "La convention collective prévoit que l'ancienneté des chargés d’enquête s'apprécie en tenant compte du temps d’activité « exclusive et régulière » pour le compte de l’institut et des années pendant lesquelles le salarié aura reçu 11 bulletins de salaire sur 12 en percevant au moins 3 fois la valeur du S.M.I.C. Le simulateur considère que le salarié remplit ces conditions pour le calcul de l'indemnité de licenciement."
Puis, on peut aller à l'écran suivant.
Il faut bien appliquer le coefficient spécifique pour chaque catégorie. Le taux est appliqué à l'ancienneté totale.
Donc, pour le chargé d'enquête intermittent, c'est le taux de 1/5ème du 12ème du montant des rémunérations perçues pendant les 12 mois précédant la notification de la rupture, par année de présence, et au maximum 7 mois.

**Comment by June-law** [comment]
Dans l'outil "Calculateur de l'indemnité de licenciement", il faut faire des modifications pour l'indemnité de licenciement dans la Syntec.
Pour le chargé d'enquête (intermittent et non intermittent), il ne faut plus demander l'ajustement de l'ancienneté. 
Mais une fois que l'usager aura choisi la catégorie "chargé d'enquête intermittent" ou "chargé d'enquête non intermittent", faire apparaître un cadre avec le texte suivant "La convention collective prévoit que l'ancienneté des chargés d’enquête s'apprécie en tenant compte du temps d’activité « exclusive et régulière » pour le compte de l’institut et des années pendant lesquelles le salarié aura reçu 11 bulletins de salaire sur 12 en percevant au moins 3 fois la valeur du S.M.I.C. Le simulateur considère que le salarié remplit ces conditions pour le calcul de l'indemnité de licenciement." 
Puis, on peut aller à l'écran suivant.
Il faut bien appliquer le coefficient spécifique pour chaque catégorie. Le taux est appliqué à l'ancienneté totale. 
Donc, pour le chargé d'enquête intermittent, c'est le taux de 1/5ème du 12ème du montant des rémunérations perçues pendant les 12 mois précédant la notification de la rupture, par année de présence, et au maximum 7 mois.

**Comment by June-law** [comment]
> 
> 
> Dans l'outil "Calculateur de l'indemnité de licenciement", il faut faire des modifications pour l'indemnité de licenciement dans la Syntec.
> Pour le chargé d'enquête (intermittent et non intermittent), il ne faut plus demander l'ajustement de l'ancienneté.
> Mais une fois que l'usager aura choisi la catégorie "chargé d'enquête intermittent" ou "chargé d'enquête non intermittent", faire apparaître un cadre avec le texte suivant "La convention collective prévoit que l'ancienneté des chargés d’enquête s'apprécie en tenant compte du temps d’activité « exclusive et régulière » pour le compte de l’institut et des années pendant lesquelles le salarié aura reçu 11 bulletins de salaire sur 12 en percevant au moins 3 fois la valeur du S.M.I.C. Le simulateur considère que le salarié remplit ces conditions pour le calcul de l'indemnité de licenciement."
> Puis, on peut aller à l'écran suivant.
> Il faut bien appliquer le coefficient spécifique pour chaque catégorie. Le taux est appliqué à l'ancienneté totale.
> Donc, pour le chargé d'enquête intermittent, c'est le taux de 1/5ème du 12ème du montant des rémunérations perçues pendant les 12 mois précédant la notification de la rupture, par année de présence, et au maximum 7 mois.

**Comment by June-law** [comment]
Il faudrait aussi faire les corrections suivantes, sur la page "Catégorie" :
- appeler la page "Catégorie professionnelle"
- mettre le texte : "Quelle est votre catégorie professionnelle d'après la convention collective ? Vous pouvez la trouver sur votre bulletin de paie" 
- écrire "Sélectionnez une catégorie professionnelle"

**Comment by ClementChapalain** [comment]
c'est fixé @UnbearableBear ?
