### ISSUE TITLE
[fiche MT] qualité du HTML

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#1073]
**Description**
Il semblerait que certains fiches aient un HTML douteux ou mal interprété de notre côté

ex: http://0233b48.code-du-travail-numerique.dev.factory.social.gouv.fr/fiche-ministere-travail/le-delegue-du-personnel-en-bref-les-attributions-des-delegues-du-personnel?q=Repr%C3%A9sentation%20du%20personnel%20et%20n%C3%A9gociation%20collective

<img width="765" alt="Capture d’écran 2019-07-31 à 12 05 09" src="https://user-images.githubusercontent.com/124937/62203505-9e597680-b38b-11e9-94ac-c164d586da2a.png">

**Comment by lionelB** [comment]
je pense que c'est parce qu'on affiche pas le "en bref"

**Comment by lionelB** [comment]
wrong button -_-
