### ISSUE TITLE
[wording] fiches MT

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#1076]
quand on ouvre une fiche ministère du travail sur le CDTN, la mention qui apparaît est "fiche ministère du travail". Il faudrait ajouter des majuscules ainsi "Fiche Ministère du Travail" .  

<img width="667" alt="Capture d’écran 2019-07-31 à 17 47 12" src="https://user-images.githubusercontent.com/124937/62227055-90bbe500-b3bb-11e9-9177-3606632324af.png">

**Comment by ClementChapalain** [comment]
pas de majuscule à Ministère en revanche :)
https://www.gouvernement.fr/le-ministere-du-travail
