### ISSUE TITLE
[refacto] data indexation

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#1083]
Avec l'utilisation de datasets npm versionnés et/ou du JSON, on devrait passer pour simplifier à une indexation des datas ES en JS.

Toutes les sources sont un simple dump des fichiers JSON dans `dataset`, sauf les fiches ministère travail qui ont un traitement particulier

Il faudra faire attention aux changements de slug et l'intégration dans la CI

**Comment by lionelB** [comment]
related https://github.com/SocialGouv/code-du-travail-numerique/issues/1090
