### ISSUE TITLE
Autosuggest include all indexed documents/tools in another box

### ISSUE THREAD

**Issue by ArmandGiraud** [SocialGouv/code-du-travail-numerique#1087]
**Fonctionnalité**
ajouter les questions du datafiller, fiches, et outil de contrib et articles dans les suggestions
sur le mode **"accès directs"** fourni par service public:
 ![image](https://i.imgur.com/IXNxXtu.png)

ajouter listes numéros articles CDTN dans différentes expressions style (Article )?[LRD][\.\s-](\d+) ?

**Problème**
les features principales du site ne sont pas suggérées..

**Solution**
les ajouter dans l'historique de suggestions, ou faire un shortcut.. (évite d'être dépendant des paramètres mais complexifie le code)

**Comment by ClementChapalain** [comment]
C'est à faire de votre côté ou par les devs front @ArmandGiraud ?

**Comment by ArmandGiraud** [comment]
Un peu des deux. De notre côté on doit inclure le contenu dans le module. Mais je pense qu’il y a un peu de travail niveau front pour qu’on puisse distinguer une suggestion normale d’un “accès direct” vers le  contenu suggéré.

**Comment by ArmandGiraud** [comment]
@rmelisson On peut fermer cette issue?

**Comment by rmelisson** [comment]
En l'état je pense que oui.
Après, ça reste une fonctionnalité intéressante à mon avis, ça permet d'éviter de passer pas la page résultats de recherche. Mais en même temps ça "encombre" le parcours utilisateur en mélangeant deux fonctionnalités (suggestion et recherche).
