### ISSUE TITLE
Page "A propos" : contenu

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#109]
contenu à remplir

source : https://github.com/SocialGouv/code-du-travail-explorer/blob/dev/pages/about.js

**Comment by jrduscher** [comment]
https://github.com/SocialGouv/code-du-travail-explorer/commit/50196d5dc6c7247ab39cda983ab26295f200ee4d#diff-c03863060661206245259b0485539bdd

**Comment by ClementChapalain** [comment]
traité dans #513
