### ISSUE TITLE
update slugs in datafiller

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#1090]
I'm working on a PR to migrate the python code to js. in order to do that I had to rewrite a custom slugify function that match the python one.
- some fiche-ministere have their title updated
- some themes had a wrong char in the slug (like a `,`)

So this issue is here to not forget to verify that we have corrects slugs

poke @ArmandGiraud @revolunet

**Comment by ClementChapalain** [comment]
je vois une PR closed, est-ce que cette tâche est terminée du coup @lionelB ?

**Comment by lionelB** [comment]
nope c'est un reminder pour qu'en on utilisera la meme fonction de slugification (pour l'instant c'est partagé entre une lib et une fonction maison) car il faudra vérifier qu'on a toujours les meme slugs

**Comment by lionelB** [comment]
done by #1105 , #1263
