### ISSUE TITLE
Outil sur la rupture conventionnelle

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1097]
wip par @j-r

**Comment by jrduscher** [comment]
dossier données métiers pour specs: https://docs.google.com/document/d/1TW8j2apn06OyKsJ30AFjFJ359ImNPupkwB_cbnfHzSo/edit#
synthèse destinée à entamer la phase design: https://docs.google.com/document/d/13IMqCQuJGMp46J9JXFiyh6Y-HT9oxQceHm8yNbQ6mYg/edit
modèle de courrier (droit de rétractation- rupture conventionnelle): https://docs.google.com/document/d/1UcbPqfuuwlGgFIe_VM1EZzsNeDWgGRsLWmNzhSWRkMY/edit

**Comment by m-maillot** [comment]
En cours de réalisation, l'issue a été découpée en plusieurs issues, je clôture cette dernière.
