### ISSUE TITLE
Gestion des synonymes : demi -> demission

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#110]
testé de mettre un synonyme dans https://github.com/SocialGouv/code-du-travail-data/commit/4184a1de4b32604298aa1dac48c94d09106deb07

**Comment by ClementChapalain** [comment]
on peut fermer @revolunet ?

**Comment by ClementChapalain** [comment]
plus pertinent suite au nouveau moteur de suggestion
