### ISSUE TITLE
Bug précision ES "sous-lisse" => "liste"

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#112]
![image](https://user-images.githubusercontent.com/37538697/45999999-9e238700-c0a7-11e8-92c6-d661227ea113.png)

**Comment by lionelB** [comment]
@jrduscher  c'est une vieille issue, le pb de depart sous-lisse qui matche liste à disparu par contre, je me demandais si on avait des contenu qui etati censé matcher `sous-lisse` ?

**Comment by ClementChapalain** [comment]
pas reproduisible avec la version actuelle :)
