### ISSUE TITLE
Navigation articles CDT

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#115]
quand je consulte un article du code du travail sur CDTN, je dois
* pouvoir voir le fil d'ariane structure CDT ou ePos relatif à l'article sur la page résultat
* pouvoir consulter si je le souhaite les autres articles concernant le thème de l'article en cours de lecture
* je dois pouvoir connaitre la date d'entrée en vigueur ou de dernière modification de l'article ( ce serait même top d'avoir le texte dont elle est issue) (ex: Article L1235-3 Modifié par LOI n°2018-217 du 29 mars 2018 - art. 11)
* je dois ensuite pouvoir poursuivre si je le désire mon exploration textuelle sur legifrance, en démarrant par la page legifrance de l'article que je viens de consulter sur le service CDTN

**Comment by revolunet** [comment]
1ere version : 
 - [ ] fil d'ariane + liens legifrance
 - [ ] lien vers l'article legifrance

**Comment by revolunet** [comment]
Sans réponse de la DILA on est un peu bloqués pour avancer sur tout ce qui est metadonnées autour du code du travail : navigation dans les sections, liens, dates... j'ai un plan B (attaquer les fichiers XML de la DILA) mais ca demanderait un petit effort avec un(e) dev dédié. Bref, il nous faut de la visiblité sur leur planning si on veut avoir ses fonctionnalités (= un navigateur du code du travail UX-friendly)

**Comment by revolunet** [comment]
attente RDV DILA pour faire le point là-dessus

**Comment by jrduscher** [comment]
review: ok pour mise en prod.
une nouvelle issue est créer avec les  points non traités
