### ISSUE TITLE
expression multi-mots (solde tout compte)

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#116]
certains expressions à plusieurs mots ne sont pas bien prises en compte dans la recherche.

**Comment by revolunet** [comment]
ex: "indemnité de licenciement mettalurgie"

**Comment by revolunet** [comment]
Exemple 1 : "solde de tout compte métallurgie"

Comme pas de résultats spécifiques mettalurgie, on devrait voir apparaitre le cas général "solde de tout compte"

**Comment by jrduscher** [comment]
#296

**Comment by revolunet** [comment]
#198

**Comment by lionelB** [comment]
piste suite à la venue du consultant elastic
- utilisation du should avec un match phrase plus 
- ajout une pourcentage de match 
- utilisation des min-term pour activer les clauses should

**Comment by lionelB** [comment]
cas de test `temps de travail effectif`
