### ISSUE TITLE
Qui du Préavis : 4 CCN

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#118]
- démission
- retraite
- licenciement.

integration des critères CCN (catégorie, ancienneté) et détermination de l'applicabilité au regard des règles de droit commun. voir CCn.xls

**Comment by jrduscher** [comment]
On peut également ajouter une option:  pouvez vous prétendre à des heures pour rechercher un travail en cours de préavis?

**Comment by jrduscher** [comment]
Ajout possible évolution à venir d'un critère droit local alsace moselle

**Comment by ClementChapalain** [comment]
repris ici : https://github.com/SocialGouv/code-du-travail-numerique/wiki/%5BOutils%5D-%5BCalculateur-pr%C3%A9avis%5D
