### ISSUE TITLE
Page glossaire

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1186]
### Objectif

Aider les usagers à comprendre les termes importants relatifs au droit du travail difficilement traduisible en français facile.

### Source

Voir la feuille export 2019.08.28 dans le fichier suivant :
https://docs.google.com/spreadsheets/d/1WrmotMiu4kBxRTKW47Q3CzNjxc0GycfAilSHcXH_hfA/edit#gid=2056936159

### Administration

- créer une nouvelle interface dans le data filler avec pour chaque terme :
  - son nom
  - ses abbréviations (optionnel)
  - ses synonymes (optionnel)
  - sa définition
  - ses références juridiques (optionnel)
- permettre l'ajout / la modif / la suppression d'un terme

ping @revolunet 

#### Page glossaire

Une page glossaire qui liste tous les termes du glossaire accessible depuis un lien dans le footer du site

#### Page par définition

Une page par terme avec :
- terme
- abbréviations
- synonymes
- définition
- sources

#### Highlight dans tout le site sur les termes

La définition devrait apparaître en popover avec un soulignement léger ([cf. ici par exemple](https://www.w3schools.com/cssref/playit.asp?filename=playcss_text-decoration-style&preval=dotted))

Le soulignement et la définition ne devrait être visible que lorsque le terme est dans un paragraphe de texte (pas dans un menu, un titre, etc.).

**Comment by ClementChapalain** [comment]
@revolunet @lionelB j'ai mis à jour les specs

**Comment by lionelB** [comment]
@ClementChapalain  l'interaction du popover se fait au click / focus / mouseHover ?

**Comment by ClementChapalain** [comment]
je suis pas sur de voir la différence entre focus et mousehover ? mais pour moi c'est "quand on passe la souris sur l'élément" :)

**Comment by lionelB** [comment]
focus c'est le rectangle bleu qui se déplace au click / tab

**Comment by ClementChapalain** [comment]
ok du coup mouse hover

**Comment by ClementChapalain** [comment]
quelques remarques sur le glossaire :
- indemnité de la sécurité sociale" > guillemets en trop
- ce mot ne devrait pas être dans le glossaire : Exemples des données présentes : emploi, rémunérations, conditions de travail, formation des salariés."

**Comment by UnbearableBear** [comment]
Mouse hover ça veut dire que si quelqu'un ne peut pas utiliser de souris et qu'il navigue au clavier (et donc via tabulation et donc focus uniquement), il n'aura jamais les tooltip ?

**Comment by ClementChapalain** [comment]
oui bien vu, vous pensez qu'il faut mettre au focus aussi ?

**Comment by virginielastisneres** [comment]
@lionelB Je commence à regarder le Glossaire :) Encore super comme travail. 
Première remarque : il y a un soucis dans l'ordre des mots dans les lettres alphabétiques. Ils sont de Z à A, il faudrait les mettre de A à Z. Est-ce possible Lionel ? :) :) 
![image](https://user-images.githubusercontent.com/48682104/65025610-5391bf00-d937-11e9-9d8d-e3752690e5d1.png)

**Comment by virginielastisneres** [comment]
autre petite remarque : Lionel pourrais-tu prendre en compte dans le markdown présent dans le datafiller ? :)
Exemple : Pour les exemples, cela serait bien qu'ils soient séparer un peu de la définition comme dans le datafiller (revenir à la ligne et saut de ligne) 
![image](https://user-images.githubusercontent.com/48682104/65027047-f64b3d00-d939-11e9-9928-d26ac025e4ab.png) 
![image](https://user-images.githubusercontent.com/48682104/65027106-0a8f3a00-d93a-11e9-907f-b50ef681cd8d.png)

**Comment by virginielastisneres** [comment]
@lionelB pourrais-tu supprimer les colonnes variantes et abréviations stp :).

**Comment by virginielastisneres** [comment]
pour les références est-il possible d'affiche la source et non son lien ? 
Je m'explique : 
- pour la référence dans accident du travail au lieu d'avoir le lien pourrait-on avoir "Source : Article L. 411-1 du Code de la sécurité sociale"
- pour la référence dans astreinte avoir "Source : Article L 3121-9 du Code du travail"

De plus, je vais devoir rajouter dans le datafiller les liens source des définitions qui viennent du glossaire de service public. Serait-il possible une fois que j'aurai rempli le datafiller d'avoir pareil pour toutes les définitions issues du glossaire service public "Source : Service-Public.fr". 
Un peu comme l'on a dans notre page résultat mais pas juste Source : Service Public mais vraiment "Source : Service-Public.fr" (on nous a rappelé que l'on devait l'écrire entier comme cela...)

![image](https://user-images.githubusercontent.com/48682104/65059129-bdc95480-d975-11e9-95d9-db9ef69adf7c.png)
