### ISSUE TITLE
Page CC : onglet résumé / synthèse de la CC

### ISSUE THREAD

**Issue by June-law** [SocialGouv/code-du-travail-numerique#1200]
**Fonctionnalité**
Il serait utile d'avoir pour les CC traitées dans les contributions un endroit qui présente ensemble les questions traitées dans les contributions. 

**Description**
L'idée serait de créer un onglet "L'essentiel" ou "Synthèse" dans la page dédiée à la CC. Cet onglet reprendrait les contributions qui ont des réponses pertinentes (ne pas reproduire les questions qui ont comme réponse "La convention collective ne prévoit rien sur ce point").

Ainsi, l'usager aura une vision, dans une rédaction / un français plus accessible, des points les plus importants de la CC, comme la durée de la période d'essai, la durée des préavis, la garantie d'emploi en cas d'arrêt maladie, etc. 

**Ressources**
Les contributions.

**Comment by revolunet** [comment]
On pourrait retrouver au même endroit les blocs extraits par Florent

**Comment by ClementChapalain** [comment]
done !
