### ISSUE TITLE
récupérer les fiches risques mintrav trouver le lien/penser tags

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#121]

**Comment by jrduscher** [comment]
exemple

https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/article/commande-bimanuelle

**Comment by lionelB** [comment]
@jrduscher est ce que c'est possible de faire une liste des url que l'on souhaite récupérer ?

**Comment by lionelB** [comment]
poke @jrduscher 


- [https://travail-emploi.gouv.fr/sante-au-travail/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/suivi-de-la-sante-au-travail-10727/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/suivi-de-la-sante-au-travail-10727/article/le-suivi-de-l-etat-de-sante-des-salaries]()
- [https://travail-emploi.gouv.fr/sante-au-travail/suivi-de-la-sante-au-travail-10727/article/la-reconnaissance-de-l-inaptitude-medicale-au-travail-et-ses-consequences]()
- [https://travail-emploi.gouv.fr/sante-au-travail/suivi-de-la-sante-au-travail-10727/article/reforme-de-la-medecine-du-travail-et-des-services-de-sante-au-travail-questions]()
- [https://travail-emploi.gouv.fr/sante-au-travail/statut-des-travailleurs-et-dispositions-particulieres/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/statut-des-travailleurs-et-dispositions-particulieres/article/la-protection-de-la-sante-des-jeunes-travailleurs]()
- [https://travail-emploi.gouv.fr/sante-au-travail/statut-des-travailleurs-et-dispositions-particulieres/article/femmes-enceintes]()
- [https://travail-emploi.gouv.fr/sante-au-travail/statut-des-travailleurs-et-dispositions-particulieres/article/liste-des-postes-a-risques]()
- [https://travail-emploi.gouv.fr/sante-au-travail/statut-des-travailleurs-et-dispositions-particulieres/article/interim-et-cdd]()
- [https://travail-emploi.gouv.fr/sante-au-travail/statut-des-travailleurs-et-dispositions-particulieres/article/l-interdiction-de-fumer-dans-les-lieux-de-travail]()
- [https://travail-emploi.gouv.fr/sante-au-travail/les-acteurs-et-interlocuteurs-de-la-sante-au-travail/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/les-acteurs-et-interlocuteurs-de-la-sante-au-travail/comite-d-hygiene-de-securite-et-des-conditions-de-travail/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/les-acteurs-et-interlocuteurs-de-la-sante-au-travail/comite-d-hygiene-de-securite-et-des-conditions-de-travail/qu-est-ce-qu-un-chsct/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/les-acteurs-et-interlocuteurs-de-la-sante-au-travail/comite-d-hygiene-de-securite-et-des-conditions-de-travail/developper-les-competences-des-chsct/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/les-acteurs-et-interlocuteurs-de-la-sante-au-travail/comite-d-hygiene-de-securite-et-des-conditions-de-travail/delegue-du-personnel/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/les-acteurs-et-interlocuteurs-de-la-sante-au-travail/autres-interlocuteurs/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/les-acteurs-et-interlocuteurs-de-la-sante-au-travail/autres-interlocuteurs/article/les-organismes-de-la-prevention-en-france]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/article/amiante]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/article/les-rps-c-est-quoi]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/article/troubles-musculo-squelettiques-de-quoi-parle-t-on]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/article/penibilite-referentiels-professionnels-de-branche-homologues]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/article/campagne-europeenne-2018-2019-lieux-de-travail-sains-maitriser-l-usage-des]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/autres-dangers-et-risques/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/article/autorisation-de-conduite-appareils-de-levage]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/article/cahier-des-charges-achat-machine]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/article/commande-bimanuelle]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/article/defibrillateur-cardiaque]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/article/filtres-de-protections-respiratoires]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/article/formation-du-coordonnateur-en-matiere-de-securite-et-de-protection-de-la-sante]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/article/gants-risques-chimiques]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/article/masques-de-protection-respiratoire]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/article/methodes-et-strategie-de-prelevements-atmospheriques-individuels]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/article/oppbtp-deux-outils-digitaux-innovants-dans-l-accompagnement-a-la-prevention-des]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/article/principes-generaux-de-ventilation]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/article/protocole-de-securite-pour-les-operations-de-chargement-et-de-dechargement-de]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/article/stockage-des-produits-chimiques]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/article/substitution-des-agents-chimiques-dangereux-et-des-agents-cancerogenes]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/article/tapis-roulants-de-montagne-mise-a-niveau]()
- [https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/article/valeurs-limites-d-exposition-professionnelle-risques-chimiques]()
- [https://travail-emploi.gouv.fr/sante-au-travail/10-plans-gouvernementaux-sante-au-travail/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/]()
- [https://travail-emploi.gouv.fr/sante-au-travail/10-plans-gouvernementaux-sante-au-travail/article/plans-de-sante-au-travail-pst]()
- [https://travail-emploi.gouv.fr/sante-au-travail/10-plans-gouvernementaux-sante-au-travail/article/plan-canicule-2017]()
- [https://travail-emploi.gouv.fr/sante-au-travail/10-plans-gouvernementaux-sante-au-travail/article/plan-national-d-action-pour-la-gestion-du-risque-lie-au-radon-2016-2019]()

**Comment by jrduscher** [comment]
ok c'est cool merci .

**Comment by lionelB** [comment]
@jrduscher pour la liste finalle > https://github.com/SocialGouv/code-du-travail-numerique/blob/80600de5dc13c58eae9f043d17aac46f9b32b976/packages/code-du-travail-data/dataset/fiches_ministere_travail/ministere-travail-liste-fiches.json#L199-L311
