### ISSUE TITLE
L'accès aux modèles ne fonctionne pas

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1232]
Dans la version prod du site, l'accès au modèles de courriers ne fonctionne pas ( fonctionne dans la dev):

![image](https://user-images.githubusercontent.com/37538697/64410122-9d9eb900-d08a-11e9-965b-7ffe02832a5c.png)

**Comment by revolunet** [comment]
Ok sur http://master.code-du-travail-numerique.dev.factory.social.gouv.fr

**Comment by jrduscher** [comment]
![image](https://user-images.githubusercontent.com/37538697/64802078-284f4e80-d58a-11e9-945b-e6977c5b52c4.png)

**Comment by revolunet** [comment]
refixed, instabilités sur notre plateforme cette semaine

http://master.code-du-travail-numerique.dev.factory.social.gouv.fr/modeles-de-courriers/modele-de-certificat-de-travail?q=modele
