### ISSUE TITLE
Intégrer le droit conventionnel dans le calculateur d'indemnités de précarité

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1241]

**Comment by virginielastisneres** [comment]
**Rappel du contexte** 
Nous avons à l'heure actuelle un outil de calcul de l'indemnité de précarité légale. 
Il peut arriver que des conventions collectives prévoient d'octroyer une indemnité de précarité, parfois dénommée autrement, à certains contrats qui n'y ont pas le droit selon le code du travail. 
A l'inverse, il pourrait arriver également qu'une convention collective étendue puisse réduire le taux de l'indemnité de précarité légale qui est de 10% à 6%. 

**Objectif** : Il faut donc rechercher les conventions collectives qui prévoient ces spécificités. 

**Specs** : les specs selon les conventions collectives sont à retrouver dans cet excel => https://docs.google.com/spreadsheets/d/1SCFHUDjsWWRdVhYP5cVz2Q3AqPa-ubOYsEc3C3kRKOA/edit?pli=1#gid=1991895535

**Comment by virginielastisneres** [comment]
**Comprendre les specs** 
Les specs se présentent ainsi : 
![image](https://user-images.githubusercontent.com/48682104/65028580-90ac8000-d93c-11e9-87f5-323a4d26b49b.png)

- colonne idcc et convention collective qui permet de savoir de quelle convention collective on parle 
- colonne disposition conventionnelle qui permet de savoir s'il existe ou non des dispositions conventionnelles qui traitent de l'indemnité de fin de contrat

Les colonnes suivantes sont le cœur des specs, c'est-à-dire les différents paramètres à intégrer et qui varient d'une convention collective à une autre. 
- colonne bénéficiaires qui permet de savoir quels sont les contrats de travail qui sont concernés par la spécificité. C'est donc une des premières conditions pour pouvoir bénéficier de la spécificité présente dans la convention collective. 
- colonne autres conditions d'attribution qui est assez générale et qui a pour but de lister d'autres spécificités qui pourraient entrer en compte. 
- colonne taux de l'indemnité qui a pour but de renseigner le taux de l'indemnité (pour rappel le legal c'est 10%) 
- colonne rémunération à prendre en compte qui indique quelle rémunération doit être prise en compte pour le calcul.  
- colonne dénomination de l'indemnité qui nous informe sur le nom donné par la convention collective à cette indemnité. il ne s'agit pas forcément du nom "indemnité de fin de contrat" 
- colonnes source juridique et lien Kali qui nous donnent la source juridique de la convention collective 
- dernière colonne "validée?" c'est pour nous les experts métier pour savoir si la donnée a été validée en interne. 

N.B. : ne pas tenir compte des couleurs de fond de certaines cases.

**Comment by virginielastisneres** [comment]
**SPEC PAGE D'ACCUEIL DE L'OUTILl** 

- Changer le wording

"Ce simulateur est un outil qui permet d’estimer le montant de l’indemnité de fin de contrat ou de fin de mission (dite “prime de précarité”) d’un salarié en CDD ou en contrat d’intérim.

Vous pourrez simuler simplement le montant de la prime de précarité définie par le Code du travail avec la prise en compte des particularités présentes dans certaines branches d’activité.

Cette simulation nécessite environ 5 minutes. Afin de pouvoir remplir les renseignements demandés, munissez-vous des informations relatives à votre contrat de travail (CDD ou contrat de travail temporaire (contrat d’intérim), derniers bulletins de salaire, etc.)."

**Comment by virginielastisneres** [comment]
### **PARCOURS IDCC 1486 (1)**
[parcours conventions-1.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/3646373/parcours.conventions-1.pdf)

### **PAGE DE FIN** 
![image](https://user-images.githubusercontent.com/48682104/65498888-fceb2e80-debc-11e9-94d6-7a22df141eea.png)

**Supprimer le paragraphe de fin** 
“Attention : l’estimation est basée sur le montant de la prime de précarité prévu par le code du travail qui est de 10% de la rémunération totale brute perçue par le salarié. Une convention ou un accord collectif de branche étendu ou une convention ou un accord d’entreprise ou d’établissement peut prévoir de limiter le montant de l’indemnité à hauteur de 6 %, dès lors que des contreparties sont offertes à ces salariés, notamment sous la forme d’un accès privilégié à la formation professionnelle.
En savoir plus sur la prime de précarité d’un salarié en CDD”

**Comment by virginielastisneres** [comment]
### **PARCOURS IDCC 1486 (2)**
[parcours conventions-2.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/3646407/parcours.conventions-2.pdf)

### **PAGE DE FIN** 
![image](https://user-images.githubusercontent.com/48682104/65499686-4daf5700-debe-11e9-97d8-82a899bbd7d2.png)

**Supprimer le paragraphe de fin**
“Attention : l’estimation est basée sur le montant de la prime de précarité prévu par le code du travail qui est de 10% de la rémunération totale brute perçue par le salarié. Une convention ou un accord collectif de branche étendu ou une convention ou un accord d’entreprise ou d’établissement peut prévoir de limiter le montant de l’indemnité à hauteur de 6 %, dès lors que des contreparties sont offertes à ces salariés, notamment sous la forme d’un accès privilégié à la formation professionnelle.
En savoir plus sur la prime de précarité d’un salarié en CDD”

**Comment by virginielastisneres** [comment]
### **PARCOURS IDCC 1516**
[parcours conventions-3.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/3646416/parcours.conventions-3.pdf)

### **PAGE DE FIN** 
![image](https://user-images.githubusercontent.com/48682104/65499853-9535e300-debe-11e9-8fdb-d5b657012f13.png)

**Supprimer le paragraphe de fin**
“Attention : l’estimation est basée sur le montant de la prime de précarité prévu par le code du travail qui est de 10% de la rémunération totale brute perçue par le salarié. Une convention ou un accord collectif de branche étendu ou une convention ou un accord d’entreprise ou d’établissement peut prévoir de limiter le montant de l’indemnité à hauteur de 6 %, dès lors que des contreparties sont offertes à ces salariés, notamment sous la forme d’un accès privilégié à la formation professionnelle.
En savoir plus sur la prime de précarité d’un salarié en CDD”

**Comment by virginielastisneres** [comment]
### **PARCOURS IDCC 2098 (1)**
[parcours conventions-4.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/3646422/parcours.conventions-4.pdf)

### **PAGE DE FIN** 
![image](https://user-images.githubusercontent.com/48682104/65499981-d62df780-debe-11e9-94fe-69ca77d6ca67.png)

**Supprimer le paragraphe de fin**
“Attention : l’estimation est basée sur le montant de la prime de précarité prévu par le code du travail qui est de 10% de la rémunération totale brute perçue par le salarié. Une convention ou un accord collectif de branche étendu ou une convention ou un accord d’entreprise ou d’établissement peut prévoir de limiter le montant de l’indemnité à hauteur de 6 %, dès lors que des contreparties sont offertes à ces salariés, notamment sous la forme d’un accès privilégié à la formation professionnelle.
En savoir plus sur la prime de précarité d’un salarié en CDD”

**Comment by virginielastisneres** [comment]
### **PARCOURS IDCC 2098 (2)**
[parcours conventions-5.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/3646426/parcours.conventions-5.pdf)

### **PAGE DE FIN** 
![image](https://user-images.githubusercontent.com/48682104/65500067-f78ee380-debe-11e9-9134-1afb8db9a79f.png)

**Supprimer le paragraphe de fin**
“Attention : l’estimation est basée sur le montant de la prime de précarité prévu par le code du travail qui est de 10% de la rémunération totale brute perçue par le salarié. Une convention ou un accord collectif de branche étendu ou une convention ou un accord d’entreprise ou d’établissement peut prévoir de limiter le montant de l’indemnité à hauteur de 6 %, dès lors que des contreparties sont offertes à ces salariés, notamment sous la forme d’un accès privilégié à la formation professionnelle.
En savoir plus sur la prime de précarité d’un salarié en CDD”

**Comment by virginielastisneres** [comment]
### **PARCOURS IDCC 2511**
[parcours conventions-6.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/3646433/parcours.conventions-6.pdf)

### **PAGE DE FIN** 
![image](https://user-images.githubusercontent.com/48682104/65500163-286f1880-debf-11e9-931f-f69888bbf2f8.png)

**Supprimer le paragraphe de fin**
“Attention : l’estimation est basée sur le montant de la prime de précarité prévu par le code du travail qui est de 10% de la rémunération totale brute perçue par le salarié. Une convention ou un accord collectif de branche étendu ou une convention ou un accord d’entreprise ou d’établissement peut prévoir de limiter le montant de l’indemnité à hauteur de 6 %, dès lors que des contreparties sont offertes à ces salariés, notamment sous la forme d’un accès privilégié à la formation professionnelle.
En savoir plus sur la prime de précarité d’un salarié en CDD”

**Comment by virginielastisneres** [comment]
### **PARCOURS IDCC 3127**
[parcours conventions-7.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/3646446/parcours.conventions-7.pdf)

### **PAGE DE FIN** 
![image](https://user-images.githubusercontent.com/48682104/65500257-505e7c00-debf-11e9-9ce7-9a53127541eb.png)

**Supprimer le paragraphe de fin**
“Attention : l’estimation est basée sur le montant de la prime de précarité prévu par le code du travail qui est de 10% de la rémunération totale brute perçue par le salarié. Une convention ou un accord collectif de branche étendu ou une convention ou un accord d’entreprise ou d’établissement peut prévoir de limiter le montant de l’indemnité à hauteur de 6 %, dès lors que des contreparties sont offertes à ces salariés, notamment sous la forme d’un accès privilégié à la formation professionnelle.
En savoir plus sur la prime de précarité d’un salarié en CDD”

**Comment by virginielastisneres** [comment]
new tableau @lionelB que l'on a revu avec Clément. Peux-tu nous dire si cela te convient ? 
https://docs.google.com/spreadsheets/d/1SCFHUDjsWWRdVhYP5cVz2Q3AqPa-ubOYsEc3C3kRKOA/edit#gid=1991895535

**Comment by virginielastisneres** [comment]
retours version 1 
![image](https://user-images.githubusercontent.com/48682104/66573497-0fc75980-eb73-11e9-8bea-afc900171683.png)
Peut-on remplacer "rechercher" par "sélectionnez" ? Cela incite plus je trouve à l'action

**Comment by virginielastisneres** [comment]
![image](https://user-images.githubusercontent.com/48682104/66573750-764c7780-eb73-11e9-8205-d28041fdba69.png)
remplacer "connaissais" par "connaissez"
Est-ce que c'est possible d'essayer de mettre le paragraphe d'en dessous un peu en avant comme un point info ? 
genre un peu comme ca 
![image](https://user-images.githubusercontent.com/48682104/66573993-c9bec580-eb73-11e9-8c73-2101d72b68c0.png)

**Comment by virginielastisneres** [comment]
![image](https://user-images.githubusercontent.com/48682104/66574294-481b6780-eb74-11e9-864c-dd9544296172.png)
Vu que l'on n'indique pas juste la liste des conventions collectives que l'on a traitées. Il faudrait que l'on trouve une bonne approche pour indiquer à l'utilisateur que cette sa CC n'est pas encore traitée mais qu'il peut continuer et regarder ce que prévoit le légal. En vrai les situations légales seront beaucoup plus fréquentes que les cas spécifiques des branches. 
@ClementChapalain une idée de rédaction ou autre solution ? (je n'arrive pas à tagger aurélie...)

**Comment by ClementChapalain** [comment]
> @ClementChapalain une idée de rédaction ou autre solution ? (je n'arrive pas à tagger aurélie...)

"Nous n'avons pas encore traité votre convention collective mais nous vous invitons à poursuivre la simulation afin d'obtenir le montant défini par le Code du travail."
Tu en penses quoi ?

**Comment by virginielastisneres** [comment]
c'est bizarre que quand tu sois dans une étape et que le numéro de l'étape ne s'affiche pas... 
![image](https://user-images.githubusercontent.com/48682104/66580998-9c781480-eb7f-11e9-96dc-bf4a0de023ab.png)

**Comment by virginielastisneres** [comment]
@ClementChapalain j'aime bien la formulation juste j'ai un souci avec "montant défini par le code du travail". je voudrais pas que l'utilisateur se dise c'est pas le montant auquel j'aurai droit alors qu'en fait dans 90% le légal s'applique... je sais pas si tu vois ce que je veux dire... on peut en discuter de vive voix demain.

**Comment by virginielastisneres** [comment]
### Comme on a dit Lionel, ca serait bien d'enlever cette alerte 
Cela risque de rendre l'utilisateur confus, cette info est juste nécessaire pour nous

![image](https://user-images.githubusercontent.com/48682104/66581882-2674ad00-eb81-11e9-962c-94b48596d117.png)

**Comment by virginielastisneres** [comment]
### **problème** détecté pour la CC 296 Plasturgie. 

Il est indiqué qu'elle n'est pas traitée alors que oui mais juste elle ne prévoit pas de dispositions particulières...
idem pour celle ci la CC 413... 

![image](https://user-images.githubusercontent.com/48682104/66582250-be729680-eb81-11e9-8e7e-9d9b430c9be2.png)

**Comment by virginielastisneres** [comment]
### **Problème** dans le parcours

j'ai testé le parcours de la CC 296. 
- 1ère étape : demande de la CC
- 2ème étape : demande sur le type de contrat 
- 3ème étape : demande de la rémunération 

Problème détecté : dans l'étape 2 il n'y a pas les situations spécifiques qui s'affichent. Je coche CDD et je dois passer direct à l'étape rémunération. 

Solution : il faut rajouter dans l'étape 2 toutes les questions sur les situations spécifiques 

![1](https://user-images.githubusercontent.com/48682104/66583273-5755e180-eb83-11e9-88ee-f9e3dfbf8b23.png)
![2](https://user-images.githubusercontent.com/48682104/66583293-5e7cef80-eb83-11e9-923a-cb487d82fcc0.png)
![4](https://user-images.githubusercontent.com/48682104/66583411-8f5d2480-eb83-11e9-93f0-780c9d6d860d.png)
![3](https://user-images.githubusercontent.com/48682104/66583312-65a3fd80-eb83-11e9-9585-f2b1b05f01b2.png)

**Comment by virginielastisneres** [comment]
@lionelB :) 


### Pour les CC 1486 (bureaux techniques), 1516 (organismes de formation), 2511 (Sport) et 3127 (Services à la personne)  

### **Problème**
Pour chacune d'elle, je clique sur le contrat qui a droit à l'indemnité alors qu'il ne devrait pas y avoir droit selon la loi, c'est à dire : 
- sur le contrat d'intervention pour CC 1486
- sur le CDD d'usage pour CC 1516
- sur le CDD d'usage appelé contrat «d'intervention» pour CC 2511
- sur le CDD dit de « mission ponctuelle ou occasionnelle » pour CC 3127

Apparaît alors la question sur la situation spécifique : 
- Proposition d'un CDI à l'issu du contrat 
- ou Poursuite du contrat en CDI
- ou Transformation du contrat de mission en CDI pour un poste et une durée équivalents

Si je clique sur "Oui" dans chacun des cas, je peux passer aux étapes suivantes et à la fin j'obtiens un montant de l’indemnité de précarité. 

Or normalement je ne devrais pas avoir droit à l'indemnité de précarité...

### **Solution**

Il faudrait quand l'utilisateur clique sur Oui apparaisse un paragraphe qui indique à l'utilisateur le fait qu'il n'a pas le droit à une indemnité de cette situation là :  

- pour le contrat d'intervention (CC 1486) : 
> "Selon votre convention collective, le salarié en contrat d'intervention qui, à l'issue de son contrat, a reçu une proposition d'un CDI, n’a pas le droit à une prime d'intervention".

- pour le CDD d'usage (CC 1516) : 
> "Selon votre convention collective, le salarié en contrat d'usage qui, à l'issu de son contrat, poursuit par un CDI, n’a pas le droit à une indemnité dite " d'usage "".

- pour le CDD d'usage appelé contrat «d'intervention» (CC 2511) :
> "Selon votre convention collective, lorsque le contrat d'intervention est transformé en CDI, le salarié n’a pas le droit à une prime d'intervention".

- pour le CDD dit de « mission ponctuelle ou occasionnelle » (CC 3127) :
> "Selon votre convention collective, lorsque le contrat de mission ponctuelle est transformé en CDI pour un poste et une durée équivalents, le salarié n’a pas le droit à une prime d'intervention".

=> Je peux te rajouter une colonne dans le tableau à droit de la colonne "droit à l'indemnité" concernant les textes de réponses dans ces situations là

**Comment by virginielastisneres** [comment]
### Pour la CC 1516 (organismes de formation)

**Problème**

j'ai dans ma liste de type de contrat 2 fois CDD d'usage.

![image](https://user-images.githubusercontent.com/48682104/66654052-a8c0a800-ec39-11e9-912e-fa596d05e38b.png)

**Solution**

Serait-il possible d'enlever le "CDD d'usage" dans l'option "CDD saisonnier ou CDD d'usage" ?

**Comment by lionelB** [comment]
> Serait-il possible d'enlever le "CDD d'usage" dans l'option "CDD saisonnier ou CDD d'usage" ?

CAY CMOPLIQUÉ !

_mais on voir comment faire ;)_

**Comment by virginielastisneres** [comment]
:( je m'en doutais vu que j'imagine que cela sort directement de la liste d'exclusion.... 
et si on change la liste d'exclusion et que l'on transforme l'option "CDD saisonnier ou CDD d'usage" en deux options distinctes "CDD saisonnier" et "CDD d'usage" ?

**Comment by lionelB** [comment]
> et si on change la liste d'exclusion et que l'on transforme l'option "CDD saisonnier ou CDD d'usage" en deux options distinctes "CDD saisonnier" et "CDD d'usage" ?

c'est pas mal ! parce que je peux virer les doublons :)  tu devrais faire du code ;)

**Comment by virginielastisneres** [comment]
Pour les colonnes J (Poursuite du contrat en CDI) et K (Transformation du contrat de mission en CDI pour un poste et une durée équivalents), j'ai oublié de te faire une proposition de rédaction de la question correspondante (désolée...) 

Du coup serait-il possible de changer les questions correspondants à chacune des colonnes ainsi : 
- colonne : Poursuite du contrat en CDI => question : votre contrat a-t-il été poursuivi en CDI ?
- colonne : Transformation du contrat de mission en CDI pour un poste et une durée équivalents => question : votre contrat de mission à durée déterminée a-t-il été transformé en CDI pour un poste et une durée équivalents ? 

je te rajoute un onglet question dans le tableau

**Comment by virginielastisneres** [comment]
> c'est pas mal ! parce que je peux virer les doublons :) tu devrais faire du code ;)

ahah ;D

**Comment by ClementChapalain** [comment]
quelques retours :
- on peut mettre des espaces insécables avant les "?", "!" et avant / après les ":" ? sinon ça fait des trucs moches comme ça : 
![image](https://user-images.githubusercontent.com/5337489/66814340-bb3b2a00-ef36-11e9-9ef4-f54367be17d4.png)
- plutôt que montant comme label devant les champs pour les montant mensuels, on pourrait avoir "mois 1", "mois 2", "mois 3", etc. ?
- convention HCR : quand je la choisis et que je choisis CDD, alors je n'ai pas les questions suivantes, mais je devrais les avoir (vérifié avec @virginielastisneres)

sinon c'est top :)
