### ISSUE TITLE
Nouvelle organisation de la page recherche

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1249]
3 sections :
- 1 section avec fiches + outils + contributions
- 1 section avec articles du CDT
- 1 section avec les thèmes

cartes :
- Les cartes pour les fiches, contributions et articles CDT doivent faire apparaitre les premiers mots du contenu
- Les cartes outil doivent être visuellement différentes des cartes contenu + contributions

**Comment by ClementChapalain** [comment]
c'est fait ça non @UnbearableBear ?

**Comment by UnbearableBear** [comment]
Yes c'est plié
