### ISSUE TITLE
Heures pour recherches d'emploi

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1252]
## Repasse métier nécessaire: // Edit 20/12/2019: .
L'issue est un peu ancienne. une passe métier est nécessaire:
1) sur les données du data_simulateur :
- [x] Liens articles,
- [x] Validation des données sachant que le fichier de paramètrage a changé, 
- [x] Validité juridique (par précaution): vérifier bons critères et  bonne réponse

2) sur l'issue en elle même:
-  [x] Revue du  parcours user dans la mesure ou les autres outils de préavis ont subi une harmonisation
- [x] Revue du wording 

- [ ] Intégration de l'issue #1560 (non: sur une V2 éventuelle)

## Contexte

**Données**
https://docs.google.com/spreadsheets/d/1zd_hShEui8BHK0349GpDUZRkCcQ9syIZ9gSrkYKRdo0/edit#gid=227376301

**Objectif**
ETQ salarié ou employeur, je veux savoir s'il est possible durant le préavis que le salarié puisse bénéficier d'heures pour rechercher un emploi (HR).

Il s'agit d'un droit qui n'est pas prévu par le code du travail. Les fiches de synthèse propose une explication générique de ce droit. L'usager ne peut pas connaître par ce biais :
- s'il a droit à des heures de recherche d'emploi
- le nombre d'heures auquel il a droit
- si ce nombre diffère en fonction de sa  CSP
- si ce nombre diffère s'il est en temps partiel ou temps complet
- si ces heures sont payées ou non
- si le droit à des heures, leur nombre et leurs rémunération est possible en fonction du type de rupture du contrat de travail.
- les conditions à remplir pour y avoir droit, ou les possibilités de répartition

**Titre de l'outil**
Heures pour recherche d'emploi

**Description de l'outil**
Calculez le nombre d'heures pour recherche d'emploi prévues pendant le préavis

## Introduction
> Ce simulateur vous permet de savoir si  votre convention collective a prévu la possibilité pour le salarié de s'absenter en fin de contrat, durant le préavis, pour rechercher un emploi.

> Le code du travail ne prévoit pas ce droit ( sauf cas particulier). En revanche, une majorité de conventions collective fixent pour ces heures d'absences: leur nombres et modalités de mise en oeuvre. Autant d'informations que vous trouverez sur cet outil.

> Afin de réaliser cette simulation, vous aurez besoin d'informations concernant la situation du salarié concerné, comme sa convention collective, sa catégorie, son ancienneté. La plupart de ces informations se trouvent sur le contrat de travail ou le bulletin de salaire.  
>Prévoyez deux à cinq minutes pour cette simulation.
> 
> Cliquez sur suivant pour commencer la simulation

## Parcours utilisateur

Le fonctionnement est le même que pour le simulateur de préavis de démission, on se base sur le tableau suivant (onglet `préavis_export`) : https://docs.google.com/spreadsheets/d/1zd_hShEui8BHK0349GpDUZRkCcQ9syIZ9gSrkYKRdo0/edit#gid=1891797356

Attention de bien sélectionner "heures pour recherche d'emploi" en A1.

Chaque colonne représente potentiellement une question à poser à l'utilisateur. Par exemple pour la CC 54, il faut demander la durée du préavis et en fonction de la réponse de l'utilisateur on affichera la réponse correspondant à la bonne ligne.

Les identifiants devant les réponses (le `1| ` dans `1| démission` par exemple) doivent être utilisés pour classer les réponses mais enlevés dans l'interface.

La formulation des questions est disponible dans l'onglet `questions` du spreadsheet.

**Important:**
Les critères proposés à l'usager doivent apparaître dans l'ordre suivant. 
Après demande de la CCN
- type de rupture ( licenciement ou démission)
- catégorie de salariés
- durée du travail
- durée du préavis
- période d'essai
- groupe
- ancienneté
- autre critère

### réponse 1 != 0

![image](https://user-images.githubusercontent.com/5337489/66412449-dc12f500-e9f5-11e9-9cb1-0fe0326cc4be.png)

### réponse 1 = 0

Si réponse 1 = 0 alors afficher le message suivant dans la première section :
"La convention collective ne prévoit pas cette possibilité. Il n'est donc pas possible de bénéficier d'heures de recherche d'emploi au regard de la situation renseignée."

 La possibilité de bénéficier d’heures de recherche d’emploi au cours du préavis peut également être prévue  par un accord de groupe, d'entreprise ou d'établissement, le contrat de travail, un usage dans la profession ou l'entreprise ou d’un commun accord entre l’employeur et le salarié  

### Si  CC non traitée

Si la convention collective n'a pas été traitée alors sauter les questions sur la situation du salarié et afficher le message suivant dans la première section de la page réponse :

Afficher: " Aucun résultat : la convention collective n'a pas encore été traitée par nos services."

Préciser "Le code du travail ne prévoit pas le droit pour le salarié  de s’absenter pendant son préavis pour pouvoir rechercher un nouvel emploi. Il existe une exception dans les départements de la Moselle, du Bas-Rhin et du Haut-Rhin où le salarié, qui en fait la demande, a droit à un « délai raisonnable » pour rechercher un emploi."

Disclaimer : "Une convention collective, un accord d’entreprise ou un usage dans la profession ou l’entreprise peuvent prévoir et encadrer des absences pour rechercher un emploi au cours du préavis."

Source: "Article L1234-17 du code du travail ( dispositions spécifiques Alsace Moselle)"

### Si  CC non renseignée

Si la convention collective n'a pas été traitée alors sauter les questions sur la situation du salarié et afficher le message suivant dans la première section de la page réponse :

Afficher: " Aucun résultat: La convention collective n'a pas été renseignée"

Préciser "Le code du travail ne prévoit pas le droit pour le salarié  de s’absenter pendant son préavis pour pouvoir rechercher un nouvel emploi. Il existe une exception dans les départements de la Moselle, du Bas-Rhin et du Haut-Rhin où le salarié, qui en fait la demande, a droit à un « délai raisonnable » pour rechercher un emploi."

Disclaimer : "Une convention collective, un accord d’entreprise ou un usage dans la profession ou l’entreprise peuvent prévoir et encadrer des absences pour rechercher un emploi au cours du préavis."

Source: "Article L1234-17 du code du travail ( dispositions spécifiques Alsace Moselle)"

**Comment by revolunet** [comment]
exemple d'implem du search CCN : https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-frontend/src/contributions/Contribution.js#L87

**Comment by ClementChapalain** [comment]
@lionelB j'ai créé un onglet "heure_recherche_emploi" dans le spreadsheet pour calquer le fonctionnement sur les autres simulateurs, dis moi si c'est ok !

**Comment by lionelB** [comment]
@ClementChapalain parfait 👍 

@jrduscher @virginielastisneres : j'aimerai bien étoffé les questions qui permettent de tomber sur cet outils, Est ce que vous voyez d'autre tournure / mot clé à completer ?
```json
questions: [
      "ai-je droit à des heures de recherche d'emploi",
      "quel est le nombre d'heures pour rechercher un emploi",
      "rechercher un emploi en période de préavis"
]
```

**Comment by virginielastisneres** [comment]
Voilà ce que j'ai trouvé en cherchant un peu sur google pour voir ce que les usagers demandent 

- comment prendre ses heures de recherche d'emploi
- ai-je le droit de bénéficier d'heures de recherche d'emploi 
- absence recherche emploi pendant préavis
- démission recherche emploi pendant préavis syntec
- heures de recherche d'emploi en cas de licenciement
- heures de recherche d'emploi en cas de démission
- Ai-je droit aux heures pour recherche d’emploi dans le cadre d'une démission 
- 2h pour recherche d'emploi
- 2 heures recherche d emploi
- 2h par jour pour recherche d'emploi
- autorisation d absence pour recherche d emploi
- chercher un emploi pendant son préavis
- licenciement recherche d emploi pendant préavis
- Recherche d'emploi pendant préavis	
- absence 2h pour recherche d'emploi pendant préavis

**Comment by lionelB** [comment]
@virginielastisneres  merci j'ai gardé 
- ai-je droit à des heures de recherche d'emploi
- quel est le nombre d'heures pour rechercher un emploi
- rechercher un emploi en période de préavis
- comment prendre ses heures de recherche d'emploi
- démission recherche emploi pendant préavis
- licenciement recherche d emploi pendant préavis
- heures de recherche d'emploi en cas de licenciement
- Ai-je droit aux heures pour recherche d’emploi dans le cadre d'une démission
- autorisation d absence pour recherche d emploi
- chercher un emploi pendant son préavis
- absence 2h pour recherche d'emploi pendant préavis
