### ISSUE TITLE
1.1: revue. SPRINT 1.1

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#126]
**Commentaires de JR:**
** **CLF = commentaires de Cat  - **
1) Navigation par thèmes: 
a) wording.
- titres: les titres sont à revoir : 
-sous titres: On ne peut pas mettre en ligne avec les sous titres actuels. le wording est à faire.

-proposition:
*  embauche et exécution du contrat de travail ou  contrat de travail et embauche
             
               sous titre proposition: obligations liés à l'embauche

  * Rupture du contrat de travail: 
                                 sous titre proposition : Licenciement, démission, rupture conventionnelle...
=> (contrat de travail, pas contrat simple)
* Rémunération:
                sous titre proposition: Salaire, primes, avantages, bulletin de salaire
* Santé et sécurité au travail: 
      
              sous titre proposition : conditions de travail, surveillance médicale, pénibilité
* Durée du travail et congés:
   
               sous titre proposition: heures supplémentaires, congés payés, durée maximale du travail
* maladie et inaptitudes: maladie et inaptitude.

                  sous titre proposition : l'inaptitude, procédure, contentieux, arrêts de travail...
*Formation: à supprimer  ( pas nécessaire pour le moment pour l'outil)
*Dialogue social: ( suppression possible. dans quelques sprints)

                   sous titre proposition : représentants du personnel et négociation

* proposition de thème : contentieux et coercitif
                   
                   sous titre proposition: prud’hommes, la prescription, volet pénal, l'inspection du travail

b) test de navigation: 
* embauche et rupture: /!\ ne matche pas du tout. ( renvoie sur le CUI-CAE/CUI-CIE) répond à 1/10 de la réponse

test: " dispense de préavis si je retrouve un emploi après un licenciement"

test des rubriques thématiques: pas de réponse. 
thèmes à compléter ( je crois que c'est prévu au cours du sprint...)
test champ: pas de réponse

/!\ bug: https://codedutravail-dev.num.social.gouv.fr/fiche-service-public/licenciement-economique-les-obligations-de-lemployeur

autre remarque: + 1 pour l'aspect de la page résultat thématique ( filtres + propositions)

TO review

1. https://trello.com/c/MnRD2NjX/12-cas-a-traiter : double problème:  ( Cas Claire Scotton)

-  nous n’avons pas la matière actuellement pour répondre
- En l'état il faut soit: 
    a) une réponse sur l'indemnité de licenciement ( fiche min)
    b) un message: nous n'avons pas votre réponse.
**3) TEST: réponse satisfaisante**

2. https://github.com/SocialGouv/code-du-travail-frontend/issues/80 : Disclaimer résultats
https://github.com/SocialGouv/code-du-travail-frontend/issues/103

 : le disclaimer doit être étendu à toutes les pages réponses du site, pas uniquement FAQ: pour couvrir les erreurs d'aiguillage  ( ex: la fiche CUI CIE que j'ouvre alors que je cherche d'autres éléments sur l’embauche du CDI par exemple)

3. https://github.com/SocialGouv/code-du-travail-frontend/issues/88 : IE MAS compliant, yeah !!!
   - tout fonctionne.
   - au niveau affichage, sur la partie navigation par thèmes, on a pas exactement la même chose
![image](https://user-images.githubusercontent.com/37538697/46290119-3b405d00-c58b-11e8-878c-9e6fe8880f54.png)
** CLF - OK pour moi

4. https://github.com/SocialGouv/code-du-travail-frontend/issues/110 demi=> démission
    big corrigé.
   problème: si je cherche demi ( pêche citron, journée ou heure), on me propose démission désormais en top.
** CLF j'ai cherché "demi portion", et j'ai bien 2 réponses avec demi dont la première concerne "demi année" , avant d'avoir une réponse en démission ( donc ca c'est OK) - mais par contre si je cherche " demi année" je tombe sur démission en premier  alors que demi année etait le premier choix dans le cas precedent ! ? bizarre

5. https://github.com/SocialGouv/code-du-travail-frontend/issues/98 : page FAQ
    je n'ai pas compris ce qui a été modifié

6. https://github.com/SocialGouv/code-du-travail-frontend/issues/103 : navigation par thème epos legagcy
  - ok avec la modif/ RAS
*** CLF  : OK pour moi 
7. https://github.com/SocialGouv/code-du-travail-frontend/issues/97
   - Intégration en tant que page résultat à part entière ok.
   -> affichage paragraphe par paragraphe du résultat en plus de l’affichage fiche ( une thématique générique peut avoir pour réponse une page entière, un réponse spécifique peut trouver sa réponse das un paragraphe d'une fiche ministère.)
** CLF Ok pour moi à ce stade, comme dit JR, il faudra voir pour le découpage des fiches

8. https://github.com/SocialGouv/code-du-travail-frontend/issues/96  : dont work /!\
 - toutes les fiches consultées sont 404 et aucun contenu
**CLF - j'ai bien les contenus pour de nombreuses pages servcie public sauf "Licenciement économique : les obligations de l'employeur" - ca n'affiche rien et ensuite le lien service public envoie une erreur 404
![image](https://user-images.githubusercontent.com/34278523/46361804-d6f6c980-c66e-11e8-938c-905cb4bfc53c.png)

9. https://github.com/SocialGouv/code-du-travail-frontend/issues/95 affichage art cdtl
 - fonctionne bien, le texte s’affiche dans une page résultat
 - voir propositions spécifiques en issue et sprint en cours
** CLF : le clic sur le lien Legifrance renvoi ne renvoie pas dans un autre onglet (du coup le site disparait) et j'ai une erreur DNS en cliquant sur legifrance.fr
10. https://github.com/SocialGouv/code-du-travail-frontend/issues/107 texte d'accueil : 
 - fonctionne ( voir rq) 
-remplacer site gouvernemental par au choix:
    site ministériel
   site du Ministère du Travail
**CLF : proposition " Ce service public" ou "ce service du ministère du travail" 
11. https://github.com/SocialGouv/code-du-travail-frontend/issues/92 
     RAS c'est beau - 
** CLF OK sur l'affichage, 
** CLF par contre les liens dans les contenu s'ouvrent à la place de la page en cours, est -il possible de l'ouvrir dans un autre onglet/page ?
12. https://github.com/SocialGouv/code-du-travail-frontend/issues/104: /!\ dont work!! ** CLF : Idem sur la DEV
![image](https://user-images.githubusercontent.com/34278523/46360671-37d0d280-c66c-11e8-9957-4928534fd544.png)
 
13. https://github.com/SocialGouv/code-du-travail-frontend/issues/108 : 
** CLF ce message doit s'afficher uniquement dans les contenus produits par les SR  ? Si oui OK
** CLF est il possible de diminuer l'interligne pour avoir un bloc plus petit ? Ou de mettre le texte en centré pour la deuxième phrase ?
![image](https://user-images.githubusercontent.com/34278523/46362024-77e58480-c66f-11e8-95d8-ce41138fad6b.png)
// JR: On devrait le mettre sur tous nos résultats à mon humble avis pour l'instant.

**Comment by Loze-Faelens** [comment]
Autre commentaire : quand je suis sur une page de réponse, j'aimerai pouvoir revenir sur une page "vierge" comme un accueil sans réponse 
//JR: signalé dans cet issue: https://github.com/SocialGouv/code-du-travail-frontend/issues/127

**Comment by Loze-Faelens** [comment]
GO prod pour moi

**Comment by revolunet** [comment]
**Navigation par thèmes**
Vous pouvez modifier ce fichier : https://github.com/SocialGouv/code-du-travail-frontend/blob/master/src/data/themes2.js
Dans ce fichier, pour chaque entrée, vous pouvez modifier les textes et ajouter une clé `query` pour modifier la requête qui sera utilisée pour afficher les résultats.
A ce propos, il faudra définir comment seront alimentées ces rubriques autre que la recherche elastic ?

///edit CLF+JR: cartes Trello faites https://trello.com/c/n5PaEI8k/238-alimentation-des-rubriques-de-navigation-par-th%C3%A8mes
**Disclaimer**
Corrigé
//edit CLF: étendre aux autres contenus ( fiches...)

**Cas demi/demission** 
Donc on garde ou pas pour l'instant ?
// edtit : on garde, on teste et on referas une passe

**Liens Legifrance**
en effet c'est https://www.legifrance.gouv.fr pas https://www.legifrance.fr -> corrigé
// c'est réglé!

**formulaire de support**
Il marche dans la version de prod uniquement actuellement https://codedutravail.num.social.gouv.fr
ok

**Cas "Claire xxxxx"**
A traiter

Pour la page "article du code" : cf #115 

Pour tout ce qui est "design", on fera des passes régulières avec Jeremie pour mettre ça au "carré" (interlignages..)

Si vous pouvez faire une issue pour les cas restants, ca permettra de les suivre :
 - BUG: fiche SP "Licenciement économique : les obligations de l'employeu
 - BUG: bug css categories Internet Explorer 11
 - FEAT: traiter le HTML des fiches en entrée pour gérer les liens externes en target=_blank

Note à propos des modifs sur GitHub, si vous pouvez faire des "Pull requests" plutôt que de modifier directement les fichiers dans une branche ce serait top. ca se fait au moment de la confirmation des changements.

Les modifs sont visibles sur https://codedutravail-sprint12.num.social.gouv.fr
