### ISSUE TITLE
Bug: Erreur 500, accès à page convention collective depuis accueil

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1277]
Erreur 500, quand on cherche sa convention collective depuis la tuile "Votre convention collective: erreur 500 après la modall. (dev et prod)
La recherche d'une CCN depuis le champ de recherche ne pose pas de soucis.

**Comment by lionelB** [comment]
resolu sur http://master.code-du-travail-numerique.dev.factory.social.gouv.fr/
