### ISSUE TITLE
Ajouter de la navigation depuis les pages contenus entre les contenus associés

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1280]
La page contenu doit montrer deux colonnes : une première avec le contenu et une deuxième avec les contenus associés.

![image](https://user-images.githubusercontent.com/5337489/65512649-edc6a980-ded9-11e9-8faa-d355bd37cece.png)

To do :
- colonne contenu
  - supprimer l'icone dans le contenu
  - réduire les marges
- colonne contenu associés
  - nouvelle colonne de min 1/4 de l'écran
  - cette colonne doit être sticky
  - dans un premier temps, cette colonne peut afficher les contenus du même thème (dans un second temps, travailler avec @mhavel sur une manière plus intelligente de remonter ces résultats)

**Comment by ClementChapalain** [comment]
version mobile

**Comment by ClementChapalain** [comment]
@auremie pour la version mobile on met la navigation vers les autres contenus en dessous du contenu ?

**Comment by UnbearableBear** [comment]
On affiche les articles "voisins", par rapport à l'arborescence de thèmes ? Que se passe-t-il si la réponse consultée n'est liée à aucun thème ? (C'est souvent le cas en ce moment) On n'affiche rien ?
Par exemple, si un monsieur tape "problème de vue" et arrive sur une fiche liée à un thème bien spécifique, doit-on faire une recherche dans le même theme avec "problème de vue", doit-on aller jusqu'au thème parent si il y en a un ? Ou bien doit-on simplement afficher les thèmes voisins sans faire de recherche liée à "problème de vue" ? Je ne sais pas si je suis bien clair dans mon questionnement

**Comment by ClementChapalain** [comment]
vu avec @auremie @UnbearableBear et @soulso on part sur le fait de faire la recherche sur le titre de l'article et d'afficher les 3 premiers contenus moins le contenu regardé actuellement évidemment :)
