### ISSUE TITLE
Enlever les "réponses" du CDTN

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1283]
et les exporter afin qu'on puisse les importer depuis l'outil de contribution

**Comment by revolunet** [comment]
reutiliser l'url `/question/` pour les contributions (en cours dans #1293)

**Comment by ClementChapalain** [comment]
@soulso peut-on avoir les exports des réponses dans des csv distincts stp ?

**Comment by lionelB** [comment]
Est ce que tu peux importer du json dans un spreadsheet ? car sinon les fichiers sont dispo ici > https://github.com/SocialGouv/code-du-travail-numerique/tree/v3.2.0/packages/code-du-travail-data/dataset

**Comment by ClementChapalain** [comment]
oui ça devrait le faire, vous pouvez me dire exactement quels sont les fichiers que je dois traiter svp ?

**Comment by lionelB** [comment]
- https://raw.githubusercontent.com/SocialGouv/code-du-travail-numerique/v3.2.0/packages/code-du-travail-data/dataset/faq.json
- https://raw.githubusercontent.com/SocialGouv/code-du-travail-numerique/v3.2.0/packages/code-du-travail-data/dataset/faq-contributions.json
- https://raw.githubusercontent.com/SocialGouv/code-du-travail-numerique/v3.2.0/packages/code-du-travail-data/dataset/faq-conventions-collectives.json

**Comment by ClementChapalain** [comment]
merci ! j'ai fait un fichier clean ici des réponses :
https://docs.google.com/spreadsheets/d/1FMSN6bns2vwUOwSAcQ9_JaI6lrv0bpfoKAqAg1o4nLk/edit#gid=549869221

ping @jrduscher pour info
