### ISSUE TITLE
Durée du préavis de licenciement

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1289]
## Contexte

**Données**
https://docs.google.com/spreadsheets/d/1zd_hShEui8BHK0349GpDUZRkCcQ9syIZ9gSrkYKRdo0/edit#gid=227376301

**Objectif**
Permet à l'user de connaitre la durée du préavis prévue par rapport à sa situation et au regard de ce que prévoit le code du travail d'une part et les données conventionnelles.

**Titre de l'outil**
Simulateur de durée de préavis de licenciement

**Description de l'outil**
Estimez simplement la durée du préavis dans le cadre d'un licenciement

## Introduction

> Le préavis est une période accordée au salarié entre la notification du licenciement et son départ effectif de l’entreprise (fin du contrat).
> 
> Afin de réaliser cette simulation, vous aurez besoin d'informations concernant la situation de l'employé concerné, comme sa convention collective, sa catégorie ou son coefficient. La plupart de ces informations se trouvent sur le bulletin de salaire ou le contrat de travail.  Prévoyez deux à cinq minutes pour cette simulation.
> 
> Vous pouvez trouver plus d'informations sur le préavis de licenciement sur [cette fiche](https://codedutravail.num.social.gouv.fr/fiche-service-public/preavis-de-licenciement?q=licenciement%20pr%C3%A9avis).
> 
> Cliquez sur suivant pour commencer la simulation

### Faute grave ou lourde

Première étape, demander à l'usager s'il a été licencié pour faute grave ou lourde :
"S'agit-il d'un licenciement pour faute grave ou lourde ?
- oui
- non"

Si l'utilisateur clique sur oui, alors on affiche directement la dernière étape en expliquant à l'utilisateur qu'un licenciement pour faute grave ou lourde ne donne pas accès au préavis de licenciement :

"Dans le cas d'un licenciement pour faute grave ou lourde, il n'y pas d'obligation de respecter un préavis.

Vous pouvez trouver plus d'informations sur le préavis de licenciement sur [cette fiche](https://codedutravail.num.social.gouv.fr/fiche-service-public/preavis-de-licenciement?q=licenciement%20pr%C3%A9avis)."

### Travailleur handicapé

"Le salarié concerné est-il reconnu en tant que travailleur handicapé ?
- oui
- non"

Si l'usager répond oui, nous doublerons la durée du préavis dans la limite de 3 mois (cf. étape de réponse).

## Parcours convention collective

Si l'utilisateur a cliqué sur non à la question faute grave ou lourde, alors on lance le parcours convention collective.

Le fonctionnement est le même que pour le simulateur de préavis de démission, on se base sur le tableau suivant (onglet `préavis_export`) : https://docs.google.com/spreadsheets/d/1zd_hShEui8BHK0349GpDUZRkCcQ9syIZ9gSrkYKRdo0/edit#gid=1891797356

Attention de bien sélectionner "préavis de licenciement" en A1.

Chaque colonne représente potentiellement une question à poser à l'utilisateur.

Les identifiants devant les réponses (le `1| ` dans `1| démission` par exemple) doivent être utilisés pour classer les réponses mais enlevés dans l'interface.

La formulation des questions est disponible dans l'onglet `questions` du spreadsheet.

Il faut dans tous les cas demander l'ancienneté car elle sera nécessaire au calcul de la durée de préavis par le CDT.

### Préparation des résultats

Récupérer la durée du préavis pour la CC et pour le code du travail.

- Si travailleur non-handicapé, la durée la plus longue s'applique
- Si travailleur handicapé, la durée la plus longue s'applique, en prenant en compte les durées suivantes :
  - durée CDT : 0, 2 mois et 3 mois
  - durée CC : 
    - si durée CC < 3 mois, la durée CC est doublée dans la limite de 3 mois
    - si durée CC >= 3 mois, la durée CC n'est pas doublée

Utiliser la colonne réponse 2 pour réaliser la comparaison.

### affichage de la réponse

Utiliser la colonne réponse 1 pour afficher les résultats.

![image](https://user-images.githubusercontent.com/5337489/66655490-706e9900-ec3c-11e9-963b-be67ad01fe21.png)

### Si  CC non traitée

Si la convention collective n'a pas été traitée alors sauter les questions sur la situation du salarié, afficher la réponse CDT dans la première section, et afficher le message suivant dans la section détails de la page réponse :
> Il s'agit de la durée la plus longue entre la durée légale prévue par le Code du travail et la durée conventionnelle prévue par la convention collective. Cependant nous n'avons pas encore de donnée pour votre branche. La convention collective applicable dans votre entreprise prévoit donc peut être une durée plus longue que le Code du travail.
> Les textes ci après peuvent également avoir prévu des dispositions plus favorables en la matière :
> - un accord de groupe, d'entreprise ou d'établissement
> - lorsque ce droit existe et est pratiqué dans l'entreprise, sans qu'il y ait forcement d'accord (un usage)
> - le contrat de travail

Ajouter un bouton "consulter la convention collective" qui renvoie vers la page de la CC chez nous

### Si IDCC=2395

afficher le résultat CCN uniquement et dans la section détails ne pas faire la comparaison entre les CDT et CC.

**Comment by nkrmr** [comment]
@ClementChapalain je voulais savoir ce qu'on fait concernant le choix de l'ancienneté du salarié entre le CDT et la CC?

**Comment by ClementChapalain** [comment]
On peut utiliser les formulations suivantes : 

CDT
> Quelle est l'ancienneté du salarié ?
> Choissisez parmi les catégories d'ancienneté telles que définies par le Code du travail

CC
> Quelle est l'ancienneté du salarié ?
> Choissisez parmi les catégories d'ancienneté telles que définies par la convention collective

La deuxième phrase devrait être plus petite si possible, à la manière d'un sous titre sous la question. On peut faire des tests ensemble si tu es là aujourd'hui ou demain au bureau :)

Il faudrait aussi modifier le fil d'ariane avec les intitulés suivants stp (merci @jrduscher pour la proposition !) : 
- Introduction
- Situation du salarié
- Convention collective
- Informations complémentaires
- Durée du préavis

**Comment by lionelB** [comment]
est ce qu'on peut pas merger les propositions cdt / ccn dans un seul select et qu'on demanderai à la dernière étape ? 
0-6mois / 6mois - 1an / 1an 2ans et on zappe 0- 1an dans les choix

**Comment by nkrmr** [comment]
@lionelB le problème est qu'aujourd'hui on peut difficilement faire de comparaison sur les intervalles d'ancienneté sachant qu'on a juste une réponse en texte. Il est prévu de mettre en place une colonne avec les différents intervalles dans un format nombre.

**Comment by nkrmr** [comment]
> On peut utiliser les formulations suivantes :
> 
> CDT
> 
> > Quelle est l'ancienneté du salarié ?
> > Choissisez parmi les catégories d'ancienneté telles que définies par le Code du travail
> 
> CC
> 
> > Quelle est l'ancienneté du salarié ?
> > Choissisez parmi les catégories d'ancienneté telles que définies par la convention collective
> 
> La deuxième phrase devrait être plus petite si possible, à la manière d'un sous titre sous la question. On peut faire des tests ensemble si tu es là aujourd'hui ou demain au bureau :)
> 
> Il faudrait aussi modifier le fil d'ariane avec les intitulés suivants stp (merci @jrduscher pour la proposition !) :
> 
> * Introduction
> * Situation du salarié
> * Convention collective
> * Informations complémentaires
> * Durée du préavis

@ClementChapalain Ok je vais faire comme ça, j'avais vu déjà avec Jean-René concernant les nouveaux intitulés, c'est bien mieux comme ça.

**Comment by ClementChapalain** [comment]
ok top ! merci 🙏 

Par rapport à ta question @lionelB, techniquement on pourrait je pense, mais ça nous oblige à faire un mapping entre les propositions (0-6, 6-12, 12-24, 24+) et les valeurs définies par la convention collective, ce qui ajoute de la complexité et de la maintenance. Comme dit Nico il faudrait qu'on fasse la comparaison avec des intervalles en format numérique, mais plus tard :)

**Comment by nkrmr** [comment]
Closed by #1656
