### ISSUE TITLE
Indemnité de départ à la retraite

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#129]
Une fois qu'on aura fini avec l’indemnité de licenciement... 
A construire. spec à fournir
D1237-2 du code du travail

Indemnité légale de départ à la retraite, ILR
récupérer ancienneté,a
récupérer branche
taux_ILR,
si a<10, ( "afficher, sauf disposition conventionnelle plus favorable dans l'entreprise ou la branche, vous n'avez pas le droit à une indemnité de départ en retraite")
si a>10, a<15, ILR=s/2
si a>15, a<20, ILR=s
si a>20, a<30, ILR=1,5s
si a>30, , ILR=2s

"calcul_salaire_ILR,s",
>3) Recueillir salaire brut mensuel**
>Afficher un formulaire comprenant 12 champs à remplir (4-10 caractères numériques type €)
>-> labelliser les champs mois 1 à 12
>-> détacher visuellement les 3 derniers et afficher " trois derniers mois de salaire"
>valider : si le nb de champs remplis <12; fin. afficher principe: "l'indemnité de licenciement est due au >delà d'un an d'ancienneté "

>Primes dont 13ème mois?
>recueillir "sommeprime": prévoir soit un champ global, soit plusieurs
>afficher: indiquer le montant des primes exceptionnelles, et/ou 13ème mois
>(Prime)= (somme primes/12)
>a) moyenne des douze derniers mois
>s'il n'y a pas de prime ; (a)=moyenne(montants mois 1 à 12)
>si prime: (a)=moyenne((mois1+prime)+(mois2+prime)... (mois 12+prime))
>b) moyenne des 3 derniers mois
>s'il n'y a pas de prime ; (b)=moyenne(montants mois 10 à 12)
>si prime: (b)=moyenne((mois10+prime)+(mois11+prime)... (mois 12+prime))
>c) - si b>a, (c)=(b) sinon (c)=a 

// le mode de calcul calcul_salaire_ILR,s , peut être défini dans la CCN, il conviendra de le nommer calcul_salaire_IR.si branche n'est pas null, et si IR>0, s=IR

récupérer branche
récupérer indemnité conventionnelle de départ en retraite, IR
si IR="null", ILR
si IR="O", ILR
si IR>0
Si indemnité conventionnelle de départ en retraite- indemnité légale de départ en retraite>0 Indemnité conventionnelle
Si indemnité conventionnelle de départ en retraite- indemnité légale de départ en retraite<0 Indemnité

**Comment by jrduscher** [comment]
Boulangerie artisanale
Article 34 CCN:
3. Indemnités de fin de carrière

3.1. Départ à l'initiative du salarié, indemnité de départ en retraite

Lorsque le salarié demande à partir à la retraite, il bénéficie d'une indemnité de départ à la retraite dont le montant varie selon l'ancienneté du salarié dans la profession :

- 1 mois de salaire après 10 ans d'ancienneté ;

- 1 mois et demi de salaire après 15 ans d'ancienneté ;

- 2 mois de salaire après 20 ans d'ancienneté ;

- 2 mois et demi de salaire après 25 ans d'ancienneté ;

- 3 mois de salaire après 30 ans d'ancienneté ;

- 3 mois et demi de salaire après 35 ans d'ancienneté ;

- 4 mois de salaire après 40 ans d'ancienneté.

Lorsqu'il prend sa retraite, le salarié qui a quitté la profession âgé d'au moins 55 ans et qui n'a pas bénéficié des dispositions du dernier alinéa de l'article 33 de la convention collective nationale, recevra une indemnité spéciale de départ à la retraite égale à la différence entre, d'une part, le montant de l'indemnité de départ en retraite calculé comme au présent point et, d'autre part, le montant de l'éventuelle indemnité de licenciement payée par son dernier employeur en boulangerie. Cette indemnité spéciale de départ en retraite est versée au salarié par ISICA Prévoyance.

3.2. Départ à l'initiative de l'employeur, indemnité de mise à la retraite

Si le salarié a moins de 10 ans d'ancienneté dans la profession et en cas de départ à l'initiative de l'employeur, le montant de l'indemnité de mise à la retraite est identique à celui de l'indemnité de licenciement prévue à l'article 33 de la convention collective nationale. Le montant de l'indemnité de licenciement est déterminé en appliquant les lois et décrets en vigueur.

Si le salarié a 10 ans ou plus d'ancienneté dans la profession, le montant de l'indemnité de mise à la retraite est identique à celui de l'indemnité de départ en retraite prévue au point 3.1 sans pouvoir être inférieur au montant de l'indemnité de licenciement en appliquant les lois et décrets en vigueur.

3.3. Salaire de référence

Le salaire de référence à prendre en considération pour le calcul de l'indemnité est le 1/12 de la rémunération des 12 derniers mois précédant le départ en retraite ou, selon la formule la plus avantageuse pour l'intéressé, le 1/3 des 3 derniers mois, étant entendu que, dans ce cas, toute prime ou gratification de caractère annuel ou exceptionnel, qui aurait été versée pendant cette période, ne serait prise en compte que pro rata temporis.

3.4. Modalité d'application du droit des salariés à une indemnité de départ en retraite en fonction de l'ancienneté dans la profession

Principes de base : le salarié devra avoir travaillé pendant une durée de 2 ans dans la période de 5 ans précédant le départ en retraite. L'employeur est seul responsable, envers son salarié, du versement de l'indemnité de départ en retraite, ISICA Prévoyance n'intervenant qu'en qualité de gestionnaire.

L'ancienneté dans la profession pour l'attribution de l'indemnité de départ à la retraite est établie et appréciée à partir de la reconstitution de carrière effectuée par le service retraite d'ISICA, et compte tenu des périodes validées en boulangerie artisanale.

Périodes validées pour la retraite et prises en compte pour le calcul de l'ancienneté :

- services cotisés à l'ISICA et dans la profession ;

- services effectués dans des entreprises de la profession, disparues avant adhésion à l'ISICA ;

- périodes de guerre, mobilisation ;

- périodes de chômage indemnisés par les ASSEDIC ;

(Pour les 2 derniers points ci-dessus, il est nécessaire que la période précédente ait été travaillée dans la boulangerie, boulangerie-pâtisserie) ;

- périodes de maladie, maternité, invalidité, accident du travail intervenant pour des salariés en cours d'activité dans la profession. (Périodes supérieures à 2 mois : prises en compte intégralement pour le calcul de l'ancienneté.)

**Comment by ClementChapalain** [comment]
repris ici : https://github.com/SocialGouv/code-du-travail-numerique/wiki/%5BOutil%5D-%5BCalculateur-d'indemnit%C3%A9s-retraite%5D
