### ISSUE TITLE
Fiches MT : splitter ou non ?

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1294]

**Comment by jrduscher** [comment]
décisions au cas par cas ici: [WIP]https://docs.google.com/spreadsheets/d/1PD_dOdbbmV_RoAaGbjjmiwe9pfEdwoutTnR4E5bCZSs/edit#gid=0

**Comment by jrduscher** [comment]
@ClementChapalain @revolunet @virginielastisneres
quelques suggestions:
en gardant le paragraphe, la poursuite du parcours  pour les utilisateurs qui veulent en savoir plus se fait en dehors du CDTN.
-L'idée serait de renvoyer à l’utilisateur la fiche complète, et quand le split par paragraphe est pertinent: renvoyer l'user sur la balise dans la fiche complète (signet). Ce qui lui permet de poursuivre à volonté sa navigation sur les autres points de  la fiche complète.

**Comment by ClementChapalain** [comment]
Merci beaucoup pour le travail sur toutes les fiches @jrduscher @virginielastisneres :)
