### ISSUE TITLE
Revoir le design de la homepage

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1295]
Revoir le design général de la homepage en organisant les blocs de la manière suivante :

### Titre

- Titre = "Bienvenue sur le Code du travail numérique"
- Promesse = "Vous cherchez une information sur le droit du travail ? Vous avez besoin d’accompagnement ? Nous vous proposons des réponses accessibles et personnalisées selon votre situation."
- Supprimer "le droit du travail c'est quoi ?"
- Recherche
  - introduction = "Recherchez par mots-clefs"
  - champs de recherche avec placeholder = "préavis démission"
  - bouton avec wording "rechercher"

Tout ferrer à gauche

Inspiration design (à adapter avec l'UI actuelle) :
![image](https://user-images.githubusercontent.com/5337489/65513221-2e72f280-dedb-11e9-9474-8ec24b82d02f.png)

### Outils

- ferrer à gauche les textes et l'en-tete
- Titre = "Boîte à outils"
- ajouter une description = "Trouvez des réponses personnalisées selon votre situation"
- supprimer les icônes dans les cartes
- réduire la carte
- cta action à ajouter pour chaque outil :
  - indemnité de licenciement, préavis de démission, indemnité de précarité, simulateur d'embauche = "simuler"
  - modèles de courrier = "consulter"
  - convention collective = "rechercher"

Mettre tous les outils

Inspiration design (à adapter avec l'UI actuelle) :
![image](https://user-images.githubusercontent.com/5337489/65519440-34ba9c00-dee6-11e9-8a1a-83d529a559a0.png)

### Thèmes

- Titre = "Thèmes"
- Description = "Retrouvez tous nos contenus autour de grands thèmes"
- Mettre les thèmes de niveau 1  dans des cartes en 
  - supprimant l'icone
  - rappeticant la carte
  - ajoutant l'icone dossier en haut à droite de la carte comme dans la capture ci-dessous (pour la télécharger, cf. le [figma](https://www.figma.com/file/GaFgBvFGhZ67fXlkR4EIcg/CDTN-to-dev)

![image](https://user-images.githubusercontent.com/5337489/65519864-f8d40680-dee6-11e9-83e3-d8bcb4214ba2.png)

### Footer

idem aujourd'hui

**Comment by ClementChapalain** [comment]
je me permets quelques retours : 
- enlever le chevron à côté de thèmes vu qu'on a pas de page thèmes, idem pour boite à outils, tant que #1485 n'est pas faite
- ajouter un peu de marge entre les titres (thèmes) et sous titres (retrouvez tous nos contenus [...])
- voir -> consulter pour les modèles de courrier
- la couleur du bouton "contacter les services de renseignement est différente des autres boutons de la page, on peut mettre des primary partout et un secondary sur le contact des services de renseignement svp ? cf. https://socialgouv-react-ui.netlify.com/?path=/story/components-button--base

ping @UnbearableBear @lionelB

**Comment by UnbearableBear** [comment]
Nous avons une page thèmes :) Par contre garder le lien vers la page themes une fois qu'on est sur la page thèmes ne me semble pas optimal.
La page boite à outil n'est pas encore mergée, ceci dit, le titre n'est pas cliquable et il n'y a pas de chrevon à côté pour le moment.
`ajouter un peu de marge entre les titres (thèmes) et sous titres (retrouvez tous nos contenus [...])` => je suis d'accord je dirais même qu'il faut augmenter un peu la taille de police du sous titre
couleur des boutons => je propose de ne pas trop perdre de temps là dessus, les nouvelles couleurs arrivent bientôt

**Comment by ClementChapalain** [comment]
> Nous avons une page thèmes :) Par contre garder le lien vers la page themes une fois qu'on est sur la page thèmes ne me semble pas optimal.

yes

> La page boite à outil n'est pas encore mergée, ceci dit, le titre n'est pas cliquable et il n'y a pas de chrevon à côté pour le moment.

effectivement désolé !

> ajouter un peu de marge entre les titres (thèmes) et sous titres (retrouvez tous nos contenus [...]) => je suis d'accord je dirais même qu'il faut augmenter un peu la taille de police du sous titre

ok !

> couleur des boutons => je propose de ne pas trop perdre de temps là dessus, les nouvelles couleurs arrivent bientôt

on a une démo devant le cabinet dans quelques semaines et on aura pas encore intégré la nouvelle UI, du coup ce serait quand même chouette d'avoir un truc clean d'ici là. je ne propose pas de changer les couleurs, juste d'utiliser des couleurs cohérentes dans la page parce que là quand on arrive au footer ça fait trop bizarre : 
![image](https://user-images.githubusercontent.com/5337489/66999333-17888000-f0d6-11e9-9f37-290d9c332be3.png)

**Comment by ClementChapalain** [comment]
Ah et un autre point qui n'était pas clair dans les specs désolé, il faudrait mettre le bloc boite à outils avant le bloc thèmes svp

**Comment by lionelB** [comment]
@ClementChapalain ca te va si je fais les modifs dans la #1484

**Comment by UnbearableBear** [comment]
Ah oui est-ce que ça serait possible de faire en sorte que le chevron soit cliquable aussi ?

**Comment by ClementChapalain** [comment]
@lionelB oui pas de pbs
@UnbearableBear +1
