### ISSUE TITLE
Bug sur fiche service public F40 expression manquante

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#1296]
Dans le code du travail numérique, sur la fiche service public suivante : https://codedutravail.num.social.gouv.fr/fiche-service-public/fin-dun-contrat-a-duree-determinee-cdd **l'expression "prime de précarité" est manquante**. 

Cf. la photo de la fiche service public sur le code du travail numérique VS la fiche sur service-public.fr 

![image](https://user-images.githubusercontent.com/48682104/65330403-c8286000-dbba-11e9-80a7-3887166dfa70.png)
CDTN

![image](https://user-images.githubusercontent.com/48682104/65330456-e2fad480-dbba-11e9-9d42-6f28437e39e3.png)
Service-Public.fr

**Comment by UnbearableBear** [comment]
Bien vu, surement un balise non prise en compte encore ou une typo de leur part

**Comment by UnbearableBear** [comment]
Note à moi même, cette structure là n'est pas parsée correctement:
```
{ 
    "type":"element",
    "name":"Expression",
    "$":[ 
    { 
        "type":"element",
        "name":"LienInterne",
        "_":{ 
            "LienPublication":"F803",
            "type":"Fiche Question-réponse",
            "audience":"Particuliers"
        },
        "$":[ 
            { 
                "type":"text",
                "$":"prime de précarité"
            }
        ]
    }
    ]
},
```
