### ISSUE TITLE
Ajouter le simulateur de durée de préavis de démission dans la HP

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1304]
Pour la homepage : ajouter le simulateur dans la liste des outils

**Comment by revolunet** [comment]
Dans la liste de résultats ne faudrait-il pas préciser "démission" ?

<img width="731" alt="Capture d’écran 2019-09-24 à 15 55 31" src="https://user-images.githubusercontent.com/124937/65518177-24a1bd00-dee4-11e9-9d29-49363a1f127e.png">

**Comment by ClementChapalain** [comment]
si !

**Comment by nkrmr** [comment]
Ok je m'en occupe

**Comment by soulso** [comment]
J'ai ajouté "de démission" dans la liste de résultat des outils
<img width="847" alt="Screenshot 2019-09-25 at 12 01 28" src="https://user-images.githubusercontent.com/686395/65591267-73a32d00-df8c-11e9-83c5-75e0e75bb183.png">

**Comment by nkrmr** [comment]
J'ai ajouté "de démission" dans la liste de résultat.
<img width="763" alt="Screenshot 2019-09-25 at 12 06 30" src="https://user-images.githubusercontent.com/686395/65591564-08a62600-df8d-11e9-804c-a81af62e1b85.png">

**Comment by nkrmr** [comment]
@ClementChapalain concernant le positionnement et le picto j'aurai besoin d'un peu plus d'information. 
Actuellement je l'ai positionné en juste après l'autre simulateur, est-ce que cela te convient?
J'ai réutilisé le même picto que sur le résultat de recherche, est-ce que je conserve celui-là ou bien j'utilise le même que l'autre simulateur?
<img width="1182" alt="Screenshot 2019-09-25 at 12 08 00" src="https://user-images.githubusercontent.com/686395/65591960-dc3ed980-df8d-11e9-8f31-42fcc531855a.png">

**Comment by ClementChapalain** [comment]
C'est top comme ça (le positionnement et le picto) :) on va modifier ça dans la tâche #1295 donc pas besoin de se prendre la tête

D'ailleurs si tu veux prendre la #1295 on peut faire un point.

**Comment by nkrmr** [comment]
Ok j'envoie la PR comme ça. 
Yes je peux prendre la #1295
