### ISSUE TITLE
Formaliser et appliquer un guide de durcissement pour les containers

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1307]

**Comment by revolunet** [comment]
Actions en cours :
 - ✅ ajout de références best practices [sur le wiki](https://github.com/SocialGouv/socialgouv.github.io/wiki/%5Bdev%5D-Security-Best-practices).
 - ✅ ajout d'un linter [hadolint](https://github.com/hadolint/hadolint) dans la CI
 - ✅ ajout du inter ShellCheck
 - ✅ ajout du scanner [SNYK](https://snyk.io)

**Comment by revolunet** [comment]
https://snyk.io/blog/10-docker-image-security-best-practices/

**Comment by ClementChapalain** [comment]
j'ai cru lire skyblog dans l'url au début..

**Comment by ClementChapalain** [comment]
on peut fermer cette tâche @revolunet ?

**Comment by revolunet** [comment]
oui merci. je rajoute des issues sur les autres sujets
