### ISSUE TITLE
Améliorations page de modèle de courrier

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1308]
Ces pages sont de loin les plus visitées du site, généralement par une entrée directe via les moteurs de recherche. Nous souhaitons les améliorer, notamment afin de permettre aux usagers de poursuivre leur navigation sur notre site pour consulter d'autres contenus.

To do : 
- Ajouter le module sur la droite avec les contenus associés
- Retirer la mention "Modèles de courrier fournis par vos services de renseignement des DIRECCTE en région" en bas de la page
- Retirer le wording "modèle de courrier" dans le titre du contenu

**Comment by UnbearableBear** [comment]
@ClementChapalain est-ce que ça doit aussi prendre en compte les amélioration prévues ici: https://github.com/SocialGouv/code-du-travail-numerique/issues/1519 ?

**Comment by ClementChapalain** [comment]
ça "doit" pas mais ça peut être fait dans la même PR si c'est plus simple pour vous :)

**Comment by jrduscher** [comment]
still here: 
![image](https://user-images.githubusercontent.com/37538697/68144580-4acf6980-ff34-11e9-972e-b0af139f2b50.png)

**Comment by ClementChapalain** [comment]
ping @UnbearableBear la mention "modele de courrier fournis par vos services [...]" est toujours là

**Comment by ClementChapalain** [comment]
et la mention modèle de courrier est aussi encore visible...

![image](https://user-images.githubusercontent.com/5337489/68485252-414d4680-023f-11ea-80f3-b7e1846bc005.png)

**Comment by ClementChapalain** [comment]
ping @UnbearableBear
