### ISSUE TITLE
cas à traiter de l’égalité de traitement temps partiel/ temps plein

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#131]
Article L3123-5 En savoir plus sur cet article...
Modifié par LOI n°2016-1088 du 8 août 2016 - art. 8 (V)
Le salarié à temps partiel bénéficie des droits reconnus au salarié à temps complet par la loi, les conventions et les accords d'entreprise ou d'établissement sous réserve, en ce qui concerne les droits conventionnels, de modalités spécifiques prévues par une convention ou un accord collectif.

La période d'essai d'un salarié à temps partiel ne peut avoir une durée calendaire supérieure à celle du salarié à temps complet.

Compte tenu de la durée de son travail et de son ancienneté dans l'entreprise, la rémunération du salarié à temps partiel est proportionnelle à celle du salarié qui, à qualification égale, occupe à temps complet un emploi équivalent dans l'établissement ou l'entreprise.

Pour la détermination des droits liés à l'ancienneté, la durée de celle-ci est décomptée pour le salarié à temps partiel comme s'il avait été occupé à temps complet, les périodes non travaillées étant prises en compte en totalité.

L'indemnité de licenciement et l'indemnité de départ à la retraite du salarié ayant été occupé à temps complet et à temps partiel dans la même entreprise sont calculées proportionnellement aux périodes d'emploi accomplies selon l'une et l'autre de ces deux modalités depuis son entrée dans l'entreprise.

**Comment by jrduscher** [comment]
Indemnité légale de licenciement: temps plein et temps partiel

1) détecter temps partiel.

Phase 1
Poser la question: attendu [oui/non] " travaillez vous ou avez vous travaillé à temps partiel dans l'entreprise?",

Si 'non', continuer [----> passer à l'étape suivante dans le calculateur]
Si oui, demander la précision ci-après:

**Vous avez toujours travaillé à temps partiel dans l'entreprise ?** 
wording des propositins oui/non [oui, j'ai toujours travaillé à temps partiel dans l'entreprise/ non, j'ai aussi travaillé à temps complet ]
Si 'oui', continuer [----> passer à l'étape suivante dans le calculateur]
```
notre plan de secours:
si non: [action 1]

[action 1]: FIN + afficher wording de renvoi aux services de renseignement "Eu égard aux particularités de votre situation, nous vous conseillons de consulter les services de renseignement de l'inspection du Travail"+ formulaire "trouver son SR"

```
[action 2]

Afficher formulaire remplissage période temps plein temps partiel et rémunération

**Période temps plein**
du " mois de début" au "mois de fin", rémunération 
afficher "mois + année",  rémunération mensuelle_mois"
pour chaque mois

récupérer:  nombre de mois_temps_plein, somme (rémunération_mensuelle_temps_plein)


**Période temps partiel**
du " mois de début" au "mois de fin", rémunération 
afficher "mois + année", rémunération mensuelle"

récupérer: somme_ nombre de mois_temps_partiel, somme (rémunération_mensuelle_temps_partiel)

 Ce schéma permet d'avoir autant de périodes que possible, il suffit d'incrémenter les compteurs : nombre de mois_temps_partiel, somme (rémunération_mensuelle_temps_partiel)
nombre de mois_temps_plein, somme (rémunération_mensuelle_temps_plein)

Récupérerer à l'issue:
**RMBM Temps plein**( on fait la moyenne sur tous les mois renseignés des différentes périodes de temps plein):**= somme_rémunération_mensuelle_temps_plein/somme nombre de mois temps plein
**RMBM Temps partiel**: =somme _rémunération_mensuelle_temps_partiel/ somme nombre de mois temps partiel ( on fait la moyenne sur tous les mois renseignés des différentes périodes de temps partiel)
**nombre de mois temps plein**: =somme_nombre_de_mois_temps_plein
**nombre de mois temps partiel**: =somme_nombre_de_mois_temps_plein

RMBM = = [(somme nombre de mois temps plein/ ancienneté totale en mois)x RMBM temps plein]+[(somme nombre de mois temps partiel/ ancienneté totale en mois)x RMBM temps partiel]

RMBM = = salaireRef dans les calculs de l'indemnité

wording résultats:
_//art_L3123-5 du code du travail. "L'indemnité de licenciement (....) du salarié, occupé à temps plein et à temps partiel
Afficher explication: " l'indemnité de rupture de licenciement tient compte des périodes à temps plein et à temps partiel, par nécessité d'égalité de traitement"

**permet d'obtenir le salaire de référence proratisé**

**Comment by jrduscher** [comment]
Période temps partiel
différence ( mois début, mois fin), moyenne rémunération)

**Comment by lionelB** [comment]
dans la cas ou il y a une prime, on ajoute la `prime / anciennete` ?
