### ISSUE TITLE
Faire une passe sur le repo github et enlever les élements sensibles

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1323]

**Comment by ClementChapalain** [comment]
@revolunet on peut commencer à lister les éléments sensibles ici stp ?

**Comment by revolunet** [comment]
Pour moi la seule chose ce serait les [configurations k8s](https://github.com/SocialGouv/code-du-travail-numerique/tree/master/.k8s) et encore

**Comment by ClementChapalain** [comment]
ok je te laisser gérer ? de mon côté j'ai fait une passe sur le wiki et enlevé un ou deux liens.

**Comment by revolunet** [comment]
RGS RAS
