### ISSUE TITLE
Bandeau pour prévenir de l'utilisation de cookies

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1331]
Depuis https://www.cnil.fr/fr/exemple-de-bandeau-cookie

Wording : "En poursuivant votre navigation sur ce site, vous acceptez l’utilisation de cookies pour établir des mesures de fréquentation et d’utilisation du site"

Lien "en savoir plus" redirigeant vers la page http://master.code-du-travail-numerique.dev.factory.social.gouv.fr/mentions-legales (si possible ouverte au niveau de `Utilisation de témoins de connexion (« cookies »)` mais pas obligatoire si trop compliqué)

Croix pour fermer le bandeau. Si l'utilisateur navigue sur le site (i.e. se rend sur une autre page) on ferme le bandeau.

En terme d'UI, je propose d'utiliser les toasts 🍞

**Comment by revolunet** [comment]
je pose ça là https://github.com/AmauriC/tarteaucitron.js

**Comment by nkrmr** [comment]
Pas mal je vais checker

**Comment by nkrmr** [comment]
> je pose ça là https://github.com/AmauriC/tarteaucitron.js

Pas mal je vais checker

**Comment by ClementChapalain** [comment]
> > je pose ça là https://github.com/AmauriC/tarteaucitron.js
> 
> Pas mal je vais checker

je trouve ça un peu envahissant comme ux.. ça met vraiment un frein à la navigation

**Comment by nkrmr** [comment]
On doit pouvoir le customiser

**Comment by nkrmr** [comment]
On a un design sur l'implémentation du bandeau?

**Comment by UnbearableBear** [comment]
Je crois qu'on a mentionné dans le planning que tu pouvais utiliser le composant "Toast"

**Comment by nkrmr** [comment]
Ok je vais tester

**Comment by ClementChapalain** [comment]
est-ce qu'il y a un pb sur cette tâche ? ce n'est pas encore mergé ?

**Comment by nkrmr** [comment]
En fait la version de gestion des cookies faites mais je suis en train de mettre en place pour améliorer l'affichage des Toasts qui pour le moment s'affiche les uns au-dessus des autres. Mais je peux déjà déployer les cookies dans la version actuelle et faire une autre PR pour les toasts.

**Comment by nkrmr** [comment]
C'est fait j'ai mis de côté la refacto des toasts je m'en occupe dès que j'ai terminé les outils

**Comment by ClementChapalain** [comment]
ok merci, du coup les toasts se superposent aujourd'hui ?

**Comment by nkrmr** [comment]
Dans les fiches oui pour le moment je vais m'occuper de fixer cela

**Comment by nkrmr** [comment]
Closed by #1588
