### ISSUE TITLE
Ouvrir les textes code du travail et CC dans un nouvel onglet (contributions)

### ISSUE THREAD

**Issue by June-law** [SocialGouv/code-du-travail-numerique#1337]
Sur la page des contributions, quand on clique sur un article du code du travail ou sur la CC, le nouvel écran ne s'ouvre pas dans un nouvel onglet. 
Il faudrait faire en sorte que dans ces cas, le texte du code du travail ou de la CC (ou un arrêt de la Cour de cassation) s'ouvre dans un nouvel onglet. 
Ce devrait être la même chose pour le site (outils, modèles, fiches, etc. ), et pas seulement pour les contributions.

**Comment by lionelB** [comment]
C'est plutôt une mauvaise pratique de forcer l'ouverture de liens dans une nouvel onglet. Si ca t'intéresse, il y a quelques liens à ce sujet 
- https://css-tricks.com/use-target_blank/ [en]
- http://www.laurentbourrelly.com/blog/628.php [fr]

pour les outils c'est par contre envisageable tant qu'on ne peux pas sauvegarder l'état du formulaire. vu que ca implique de perdre l'état d'avancement.

**Comment by UnbearableBear** [comment]
+1 pour le commentaire de Lionel
