### ISSUE TITLE
Récupérer du feedback

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#134]
Définir comment on stocke les feedbacks utilisateurs : message, ratings

**Comment by ClementChapalain** [comment]
cf. la discussion qu'on a eu la semaine dernière, globalement il y a deux choses :
- récupérer du feedback sur le produit : est-ce que notre produit est utilisable ? est-ce que tout le contenu est facilement accessible ? etc.
- récupérer du feedback sur le contenu : est-ce le contenu est correct et à jour ?

**Comment by lionelB** [comment]
ici le feedback allusion au retour utilisateur (fonctionnalité pouce Haut / Bas) 
Pour l'instant on ne stocke pas l'information pouces haut / bas autrement que sur le piwik. 
A terme, il pourrait être utile de remonter cette info pour pouvoir l'intégrer au calcul de la note de pertinence lors d'une recherche

**Comment by ClementChapalain** [comment]
done
