### ISSUE TITLE
Utiliser un service (ou graphQL) pour chaque endpoint de l'api afin de memoize les résultats

### ISSUE THREAD

**Issue by nkrmr** [SocialGouv/code-du-travail-numerique#1356]
A terme il faudrait un service pour chaque call à un endpoint de l'api (comme dans les conventions collectives) pour memoize les résultats. Ou mettre en place un graphQL :D 

Même si le besoin n'est pas du tout critique

Estimation pour les services: 2 -  3 jours de dev
Estimation pour graphQL: 5 jours, à voir en fonction du contexte

**Comment by lionelB** [comment]
Oui, il faudrait mettre un système de cache sur l'API. (et aussi sur l'api nlp)
mais j'aurais plutôt tendance à dé-corréler le cache et l'ajout de graphql. 

Au vu de l'agenda, j'ai un peu peur du refacto avec graphql qui va nécessité pas mal de retouche coté front / back et en terme d'archi (rajouter des container).

Est ce que tu peux développer un peu plus pour qu'on est une idée plus précise de ce qu'il faudrait faire ?

**Comment by lionelB** [comment]
je ferme. la tendance serait plutot de passer sur un site statique builder en amont
