### ISSUE TITLE
Amélioration du simulateur d'indemnités de licenciement

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1364]
## Contexte

Revoir l'UX de l'outil d'indemnité de licenciement (et des autres outils grâce aux points généraux) afin de le rendre plus compréhensible et adaptée aux conventions collectives pas encore traitées.

Les tâches listées ci-dessous sont issues du travail réalisé avec Aurélie et testé avec des utilisateurs.
- [x] Renomer l'outils en Simulateur
- [x] Changer le design  (Tab )
- [ ] Pas de droit à l'indemnité 
- [x] feeback suite à une erreur de saisie
-  Étapes
  - [ ] CC
  - [ ] Contrat
  - [x] Ancienneté
  - [x] Salaire et Rémunération
  - [x] Résultat
- Tech
  - [ ] merge Rules / StepReducer  
  - [ ] merge StepIndex / StepReducer
  - [x] migrer les composant générique dans UI

### titre simulateur

- [x] Calculateur -> Simulateur

### affichage tabs

Revoir l'affichage des étapes en les intégrant dans un panneau sur la gauche. En mobile ce panneau se réduit et se trouve au-dessus du contenu principal.

Objectif : optimiser la place disponible sur desktop et afficher directement le contenu important en mobile

*desktop*
![image](https://user-images.githubusercontent.com/5337489/65975463-f2a5d300-e46e-11e9-9ed9-267bd8c043e9.png)

*mobile*
![image](https://user-images.githubusercontent.com/5337489/65975485-f9344a80-e46e-11e9-8048-10aee65654b5.png)

### pas de droit à l'indemnité

Si l'usager n'a pas le droit à l'indemnité car il a été licencié pour faute grave ou lourde, il est en CDD, son ancienneté est de moins de 8 mois, etc. aujourd'hui nous affichons un message inline lui indiquant qu'il n'a pas le droit à une indemnité.

En test utilisateur, nous avons pu remarquer que malgré ce message les utilisateurs sont déstabilisés par le fait que le bouton suivant soit grisé et qu'ils ne peuvent pas finir le parcours, ils ont l'impression que ce n'est pas terminé.

Nous proposons donc d'homogénéiser le fonctionnement en envoyant l'utilisateur vers l'écran final avec un message approprié lorsqu'il n'a pas le droit à l'indemnité et qu'il a cliqué sur "suivant". Proposition de message : 
"Vous n'avez pas le droit à une indemnité de licenciement pour la(les) raisons suivantes : 
- bla 
- bla"

### feeback suite à une erreur de saisie

Si l'usager a réalisé une erreur de saisie (lettre à la place d'un nombre par exemple), il faudrait harmoniser les messages d'erreur en mettant un message en rouge en dessous du champs pour chaque message d'erreur.

### Étape 1 = introduction

Pas de changements

### Étape 2 = convention collective

Aujourd'hui nous demandons la convention collective après le calcul de l'indemnité légale, ce qui pose des soucis car parfois la convention collective autorise l'indemnité de licenciement pour des cas où le code du travail ne l'autorise pas (faute lourde par exemple).

Nous souhaitons donc changer le fonctionnement de l'outil en demandant la convention collective de l'usager en première étape après l'introduction. La demande de la convention collective est une étape en soi. Elle doit se faire via le champ de recherche permettant la recherche par entreprise. Il doit également y avoir une possibilité d'indiquer "je ne connais pas ma convention collective" qui dirige l'usager vers le calcul de l'indemnité légale.

### Étape 3 = votre contrat

Cette étape regroupe toutes les questions liées au contrat :
- type de contrat
- licenciement pour faute grave ou lourde
- licenciement pour inaptitude

Ainsi que toutes les questions spécifiques à la convention collective telles que la catégorie, l'échelon, etc.

### Étape 4 = ancienneté

Calcul de l'ancienneté avec les spécificités liés à la convention collective si besoin

To do :
- Correction d'un bug : dans safari le sélecteur de dates ne fonctionne pas
- Lorsque l'utilisateur veut sélectionner des périodes d'absence prolongée, il manque une question "Quelles ont été vos périodes d'absence prolongée" ?
![image](https://user-images.githubusercontent.com/5337489/65974807-e40aec00-e46d-11e9-9c34-c271d4c80eda.png)

### Étape 5 = salaires et rémunération

Calcul du salaire de référence avec les spécificités liés à la convention collective si besoin

To do :
-  Il est impossible de rentrer 0 dans les 12 derniers salaires mensuels bruts
- Formater la demande d'ajout de périodes temps plein / temps partiel comme une question
- Formater la demande de salaire de la même manière qu'une question : 
  - le texte doit être stylé comme une question (pas d'italique, taille de texte adéquate, ferrer à gauche)
  - wording = "Quel est votre salaire mensuel brut ? (prendre en compte les primes et avantages en nature)"

### Étape 6 = affichage de l'indemnité

Revoir la hiérarchie de l'information entre les différents composants (les tests utilisateurs ont révélé que cette page n'était pas claire et que les usagers ne savaient quelle était l'information la plus importante) : 
![image](https://user-images.githubusercontent.com/5337489/66312775-8b29d080-e911-11e9-877c-98e83c20b37d.png)

## Tâches techniques

repris depuis https://github.com/SocialGouv/code-du-travail-numerique/issues/1021

- Comment gérer les step dynamiques ? Pour le moment, nous donnons le dispatch aux steps. A méditer si une meilleur solution est possible

- Actuellement, nous fournissons plusieurs props au component Wizard, notamment Rules et stepReducer qui sont en fait intrinsèquement liées. On pourrait refléchir à un moyen de combiner les deux.

- A étudier aussi, la combinaison des reducers steps et stepIndex !

- Régler les problème de tailles différentes sur les labels (yes no / Label / currency) (e.g. ancienneté dans la syntec)

**Comment by ClementChapalain** [comment]
@lionelB j'ai terminé une première version des specs, on peut en discuter ensemble pour prioriser si besoin, il y a beaucoup de choses.

**Comment by revolunet** [comment]
beau et super bien documenté 😻

**Comment by jrduscher** [comment]
![image](https://user-images.githubusercontent.com/37538697/67681954-a034d500-f98e-11e9-9f8e-e7b94987f30d.png)


Vu dans le master en page Indemnité légale: : scroll horizontal, ce qui engendre du texte tronqué.

**Comment by jrduscher** [comment]
## Mauvaise fin de parcours: CCN banque, et CCN propreté. ( moins de un an et plus de 8 mois)
![image](https://user-images.githubusercontent.com/37538697/67683946-957c3f00-f992-11e9-811e-e3080c8ad354.png)

Ici la réponse affichée est une fin de parcours CCN. 
La réponse attendue  est la réponse Indemnité légale + message de fin de parcours.

![image](https://user-images.githubusercontent.com/37538697/67684344-484c9d00-f993-11e9-84c1-7c1aa460a022.png)

CCN Banque: Donc l’affichage ci dessus avec le montant de la légale et ajouteren 1] " La convention collective ne prévoit pas une indemnité pour les salariés ayant moins d'un an d'ancienneté" 

![image](https://user-images.githubusercontent.com/37538697/68231258-0064f000-fffb-11e9-95cc-395d3cd8e6ce.png)

CCN Propreté: Donc l’affichage ci dessus avec le montant de la légale et ajouter en 1] " La convention collective ne prévoit pas une indemnité pour les salariés ayant moins de 2 ans d'ancienneté"

**Comment by jrduscher** [comment]
![image](https://user-images.githubusercontent.com/37538697/67685065-b34aa380-f994-11e9-9d96-bbc30c3209fe.png)

Blocage dans le parcours: en ajoutant l'âge, "suivant" reste grisé
