### ISSUE TITLE
Bug champ de recherche avec sélection des caractères saisis décalée 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#1368]
**Description**
Quand je veux sélectionner un caractère ou un mot sur ce que j'ai écrit dans le champ de recherche du moteur de recherche (exemple : j'ai écrit licenceiment pour inaptitude et je voudrais mettre le curseur entre le e et le i pour supprimer mon e), j'ai un décalage avec le curseur qui se positionne quelques caractères plus loin (dans notre exemple entre le o et le u)... 

Une image sera plus parlante je pense.  
![Sans titre](https://user-images.githubusercontent.com/48682104/66063516-cf008c80-e543-11e9-8b9d-37a0721c0a79.jpg)

### **Info de JR : Cela ne le fait que sur GoogleChrome** 

P.S. cela peut devenir très chiant...

**Comment by UnbearableBear** [comment]
Aussi fou que cela puisse paraître, il s'agit bel et bien d'un bug dans chrome (version 77) j'ai testé sur la version à venir (canary 79) et le bug n'est plus. Je close donc l'issue.

**Comment by UnbearableBear** [comment]
<img width="1292" alt="Screenshot 2019-10-03 at 11 49 29" src="https://user-images.githubusercontent.com/705453/66116969-eedf9100-e5d3-11e9-9f92-e7937afcde5a.png">
