### ISSUE TITLE
Modèles de courrier : integration Elastic

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#137]
https://trello.com/c/sMtLOzq3/217-mod%C3%A8les-de-courrier-recensement-des-cas-gt-ys-et-de-lexistant

 - [x] créer un fichier de référence des modèles dans le dataset sur le projet `data`
 - [x] ajouter la liste des modèles à l'index dans le projet `data` (mais pas leur contenu)
 - [x] intégrer dans l'autocomplete `Suggester`
 - [x] intégrer dans la page de résultats
 - [x] ajouter une route dédiée `/modele-de-courierr/lettre-de-mise-en-demeure` avec preview et/ou lien de téléchargement
 - [ ] dans [themes2.csv](https://github.com/SocialGouv/code-du-travail-frontend/blob/master/src/data/themes2.js) pouvoir lier 
 - [ ] dans la page des thèmes, ajouter des liens vers les modèles en question

UX/UI à valider avec @jeremiecook

**Comment by jrduscher** [comment]
https://trello.com/c/sMtLOzq3/217-integrer-mod%C3%A8les-de-courrier-recensement-des-cas-gt-ys-et-de-lexistant
https://trello.com/c/M6tGR17R/218-ajouter-ici-les-outils-modeles-formulaires-calculateurs-utiles

**Comment by jrduscher** [comment]
RECETTE: erreur sur prod et dev , erreur 500

**Comment by lionelB** [comment]
closed by #261
