### ISSUE TITLE
Theme breadcrumb should scroll on mobile, otherwise it breaks on line and is too thick

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#1373]

**Comment by ClementChapalain** [comment]
je rouvre car on a une petite regression UI qui fait que le breadcrumb n'est pas aligné avec le reste de la page : 
![image](https://user-images.githubusercontent.com/5337489/67162413-140a2880-f364-11e9-98f9-12c19eea37af.png)
