### ISSUE TITLE
UX search CCN : prevent flickering

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#1374]
Actuellement lorsque l'on cherche une CC les résultats peuvent apparaitre/disparaitre en cours de saisie ce qui n'est pas très agréable

 - Le spinner devrait apparaitre a côté de l'input
 - La liste devrait rester affichée tant que les nouveaux résultats ne sont pas arrivés

![search1](https://user-images.githubusercontent.com/124937/66119578-2f8dd900-e5d9-11e9-8942-6fb6df98ccd1.gif)

**Comment by revolunet** [comment]
following #1371

**Comment by ClementChapalain** [comment]
corrigé pour moi
