### ISSUE TITLE
target="_blank" par défaut pour les liens externes

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#138]
https://github.com/SocialGouv/code-du-travail-frontend/issues/126

quand je consulte un document publié sur un site extérieur depuis une page résultat sur le CDTN: je veux pouvoir continuer ma navigation sur le CDTN par la suite, u consulter ce résulter un peu plus tard. ( ouvri les résults des sites extérieurs dans un nouvel onglet)

**Comment by revolunet** [comment]
https://trello.com/c/7wd22jeC/241-ouverture-du-contenu-ext%C3%A9rieur-dans-une-nouvelle-page-nouvel-onglet

**Comment by lionelB** [comment]
cf fiche https://www.service-public.fr/particuliers/vosdroits/F19030 - F19030

**Comment by lionelB** [comment]
pour tester une fois deployer 
- http://codedutravail-dev.num.social.gouv.fr/fiche-service-public/rupture-conventionnelle
- https://codedutravail-dev.num.social.gouv.fr/fiche-ministere-travail/pse-comment-est-etabli-un-plan-de-sauvegarde-de-lemploi?q=pse&search=0#Comment-est-etabli-un-plan-de-sauvegarde-de-l-emploi
-  https://codedutravail-dev.num.social.gouv.fr/fiche-ministere-travail/le-handicap-et-lemploi-quel-accompagnement-vers-lemploi?q=emploi%20et%20handicap&search=0#Question-2-Quel-accompagnement-vers-l-emploi

**Comment by lionelB** [comment]
closed by #263

**Comment by lionelB** [comment]
closed by #263
