### ISSUE TITLE
doc: Améliorer le readme du projet

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#1382]
- [x]  focus sur le démarrage du 
- [x] prévoir une section commande utile (docker, script maison...)
- [x] simplifier les docs des sous-projet 
- [x] update FAQ
- [x] explain conventional commit (type / scope) https://github.com/SocialGouv/emjpm#type

**Comment by lionelB** [comment]
poke @revolunet @UnbearableBear @nkrmr

**Comment by UnbearableBear** [comment]
Ca me va nickel ! Quitte à faire une partie "explain" On pourrait avoir une partie qui explique l'organisation / l'articulation des repos entre eux, les tests avec ses pitfalls, comment utiliser l'UI, etc.

**Comment by lionelB** [comment]
on ferme ?
