### ISSUE TITLE
fonctionnement de la CI

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#1383]
j'ouvre l'issue pour qu'on puisse discuter du fonctionnement que l'on souhaiterai avoir sur la CI

### general

- [ ] améliorer le caching

### branches

- [x] tirer partie des règles only / except avancé pour le rebuild / register / deploy des images
- [ ] register / deploy des branches à la demande (button manuel dans le pipeline)
- [ ] possibilité de deployer / redeployer via un commentaire dans la PR (à la Jenkins)

### master

- [x] register / deploy auto de master

### Release
- [ ] reutiliser l'image monorepo pour pas faire de yarn
- [x] Possibilité de release depuis master via un boutton via un bouton dans le pipeline

### Production
- 
- [x] Possibilité de Deploy depuis une version taggée via un bouton dans le pipeline 
- [x] Ne pas lancer les job prepare / tests / register pour les job de  deploys prod

A completer 
poke @revolunet @douglasduteil @nkrmr @UnbearableBear 
---- 

- la doc de référence pour la config des pipeline GitLab https://docs.gitlab.com/ee/ci/yaml/

**Comment by revolunet** [comment]
Pistes que je vois :
 - extraire ElasticSearch et utiliser une instance dédiée (ex: sur une VM) en attendant ES cloud
 - ne build/deploy frontend/api/data que si nécessaire

J'ai l'impression qu'on pourrait améliorer l'intégration dans GitLab, notamment la partie "environnements".

![](https://docs.gitlab.com/ee/ci/img/deployments_view.png)

**Comment by lionelB** [comment]
Je re-up l'issue
### Release depuis master 
Modifier la pipeline pour seulement 
- poser un tag sur le master 
- déclencher le lerna release
- rajouter un except pour que le commit sur master qui bump les version de nos monorepo ne déclenche aucun job

### Production
- démarrer les job de deploy

### feature branch
- rajouter le external_pull_request
- register / deploy manuel
- suppression des images liées à la branche du registre d'image docker (image-cleaner)
