### ISSUE TITLE
UI showcase is down

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#1386]
La page web présentant l'UI est HS. Docz n'est plus à jour, il faudrait fix tout ça, c'est important !
Intégrer la thématisation accessoirement ?

D'autre alternatives à docz prévues ici:
https://github.com/styleguidist/react-styleguidist
https://storybook.js.org/docs/basics/introduction/

**Comment by lionelB** [comment]
on a pas mal de soucis avec docz, je propose plutot qu'on essaie de trouver un alternative.
storybook est utilisé par emjpm ca me parait un bon candidat

**Comment by UnbearableBear** [comment]
+1000 je pars sur un storybook, j'ai perdu beaaaucoup trop de temps avec docz
