### ISSUE TITLE
Arrêter le split des fiches MT

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1394]
To do :
- regrouper les fiches actuelles
- afficher les anciennes fiches sous forme d'accordéons dans la nouvelle fiche regroupée
- les thémer grâce au data-filler
- impact sur la recherche : voir comment conserver une indexation correcte de tout le contenu

**Comment by UnbearableBear** [comment]
@revolunet Tu t'en charges ou je prends ?

**Comment by revolunet** [comment]
si tu insistes... :)

**Comment by ClementChapalain** [comment]
réunion à venir pour débroussailler le sujet mardi 22 à 10h

**Comment by ClementChapalain** [comment]
résumé de la réunion : 
- on  garde le split des fiches pour l'indexation (les sous-documents)
- on merge les sous-documents dans une seule et même page avec 1 accordéon par sous-document et un système d'ancre
- on affiches les sous-documents dans les résultats de recherche et ils redirigent vers la bonne ancre dans la page du document

à discuter : 
- ne devrait-on pas plutôt afficher les documents dans la recherche ? avec potentiellement un lien vers les sous-documents "à la google" : 
![image](https://user-images.githubusercontent.com/5337489/67498103-357a5580-f67f-11e9-8231-370d7c732ee0.png)
- quid des fiches SP et des contributions ? doit-on splitter leur indexation également ? 

ping @UnbearableBear @lionelB @virginielastisneres @ArmandGiraud @rmelisson

**Comment by ArmandGiraud** [comment]
concernant les liens vers les sous-documents je pensais plutôt au discret [aller à](https://docs.docker.com/compose/production/#running-compose-on-a-single-server) correspondant à un lien rapide vers la sous-section matchée par le moteur. 

--
![image](https://user-images.githubusercontent.com/22575341/68312871-fce16f80-00b3-11ea-868a-a1f0e80f96ec.png)

**Comment by ClementChapalain** [comment]
ah oui c'est cool comme fonctionnement effectivement, mais si qqun cherche "démission" on ne peut pas matcher des sous-documents

**Comment by UnbearableBear** [comment]
Alors juste pour être clair, si on split la fiche pour la recherche, on ne matchera jamais le document en "entier" !

**Comment by ClementChapalain** [comment]
oui, on dit juste qu'on pourrait faire en sorte que le front affiche le doc avec le lien vers le sous-doc comme l'exemple google que armand montre

**Comment by UnbearableBear** [comment]
Je fais une version minimaliste dans un premier temps et on en reparle mercredi jeudi vendredi de la semaine pro quand je suis dans les locaux ! Le split des fiches SP mérite une petite reflexion aussi !

**Comment by ClementChapalain** [comment]
ok, effectivement dans cette tâche on se concentre là dessus : 
> - on garde le split des fiches pour l'indexation (les sous-documents)
> - on merge les sous-documents dans une seule et même page avec 1 accordéon par sous-document et un système d'ancre
> - on affiches les sous-documents dans les résultats de recherche et ils redirigent vers la bonne ancre dans la page du document

**Comment by ClementChapalain** [comment]
vu avec @revolunet, to do pour le data filler : 
- [x] dans la partie contenus à thémer, on affiche les documents
- [ ] dans la partie thèmes, on (avec @jrduscher et @virginielastisneres) va repasser dessus pour faire en sorte d'afficher les urls des docs et pas des sous-docs
- [ ] dans le CDTN, on affiche dans les thèmes tous les sous-docs d'un doc avec le thème correspondant

**Comment by revolunet** [comment]
détail des corrections sur le datafiller : https://gist.github.com/revolunet/75adab4010ddc26a6c9951a2b7f464da
