### ISSUE TITLE
Source -> Thème dans les résultats de recherche

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1395]
À la place de "service-public", "ministère du travail", "outil", etc. dans les résultats de recherche, afficher le thème du contenu.

Ce thème doit être cliquable et renvoyer vers la page du thème.

Si le contenu n'a pas de thème, garder la source.

**Comment by revolunet** [comment]
On affiche juste le thème "de fin" ?

**Comment by lionelB** [comment]
ca me parait une bonne idée :)

**Comment by revolunet** [comment]
Fixed in #1479
