### ISSUE TITLE
[contributions] : références juridiques

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#1396]
Comment les references juridiques doivent-elle apparaitre dans la page contributions ?

Il y a plusieurs niveaux de references juridiques :
 - refs de la réponse générale
 - refs d'une situation (section) dans la réponse générale
 - refs d'une réponse CC

Les refs sont de plusieurs types : code, articles de CCns, liens externes

**Comment by lionelB** [comment]
a minima, une ref devrait avoir ces propriétés  `{ label, url, date }`

**Comment by ClementChapalain** [comment]
je ferme car nous avons vu avec Julien et Ivan comment le faire et pas de besoin d'adaptation front a priori

**Comment by revolunet** [comment]
Ce qui a été décidé : uniquement des références "inline", pas de bloc ui spécifique

**Comment by lionelB** [comment]
qui pointent vers légifrance ?

**Comment by ClementChapalain** [comment]
à décider, avec le lien legi on peut soit pointer vers chez eux, soit retrouver l'article et pointer vers chez nous
