### ISSUE TITLE
Migration data-filler -> outil de contrib

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1397]

**Comment by revolunet** [comment]
Idées pour le faire rapidement, à voir avec Ivan :

 - créer un `/datafiller` dans son app avec le datafiller tel quel
 - utiliser son auth
 - ajouter une DB dans la base postgres existante

**Comment by revolunet** [comment]
objectif 15 Novembre pour une premiere migration

**Comment by revolunet** [comment]
travail bien avancé ici : https://github.com/SocialGouv/code-du-travail-backoffice/pull/765/files

**Comment by revolunet** [comment]
Reste à faire :
 - ~~récupérer les derniers changes sur le datafiller (backport des commits)~~
 - trouver une solution pour https://github.com/SocialGouv/datafiller/issues/82
 - trouver une solution pour accéder aux données contributions et datafiller (suite aux restrictions d'IP prévues)

**Comment by virginielastisneres** [comment]
@revolunet @ivangabriele on en est où au niveau de cette tâche ?

**Comment by ivangabriele** [comment]
@virginielastisneres Il ne reste plus que 2 étapes pour que la migration soit complète :

- Pouvoir ajouter des références CDTN
- Migrer les données existantes

**Comment by revolunet** [comment]
Postponed
