### ISSUE TITLE
Pouvoir "thémer" un contenu sans passer par son thème depuis le data-filler

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1401]
Aujourd'hui beaucoup de contenus ne sont pas thémés car il faut passer par un thème pour pouvoir y ajouter des contenus.

Il faudrait une entrée dans le menu de gauche des thèmes du data filler qui liste les contenus sans thème et permette de leur ajouter un thème grâce à un dropdown ou mieux un champs de recherche.

Qu'en penses-tu @revolunet ?

**Comment by revolunet** [comment]
yes we can :)

du coup comment on choisira quelles fiches afficher dans un theme ?
on se basera toujours sur celles définies dans la gestion des thèmes ?

et le mapping fiche-> theme ne servira "que" pour le breadcrumb des fiches ?

un prérequis à mon avis est de unsplitter les fiches MT. (#1394)

**Comment by ClementChapalain** [comment]
> du coup comment on choisira quelles fiches afficher dans un theme ?
> on se basera toujours sur celles définies dans la gestion des thèmes ?

oui ce seront celles définies dans le data filler

> et le mapping fiche-> theme ne servira "que" pour le breadcrumb des fiches ?

je ne comprends pas 🤔 c'est quoi le mapping fiche theme ?

**Comment by revolunet** [comment]
Le mapping fiche-> theme c'est l'écran qui permet de définir un thème pour chaque fiche (cette issue)  ☎

**Comment by ClementChapalain** [comment]
ah ok, mais pour moi cette issue c'est juste une autre vue des mêmes données, mais qui nous permettrait de voir simplement quelles contenus n'ont pas de thème.

l'objectif c'est que chaque contenu (fiche, outil, contribution) ait un thème.

**Comment by revolunet** [comment]
Ok. la subtilité c'est que les themes permettent aussi de définir l'ordre des contenus. mais ok je crois avoir compris

**Comment by ClementChapalain** [comment]
ah oui j'avais pas pris ça en compte, mais on pourrait avoir une règle du style : lorsqu'un contenu est ajouté depuis ce nouvel onglet "contenu sans thème" elle part en dernière position.

**Comment by revolunet** [comment]
perfect

**Comment by UnbearableBear** [comment]
@virginielastisneres Et voilà !

**Comment by revolunet** [comment]
@ClementChapalain bon pour toi ?

**Comment by ClementChapalain** [comment]
oui !
