### ISSUE TITLE
Améliorations diverses champs de recherche CC

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1405]
To do :
- [ ] utiliser le champ de recherche dans tous les outils :
  - [ ] préavis démission (#1407)
  - [ ] indemnité licenciement (#1364)
  - [x] indemnité de précarité (#1241)
- [x] changer le placeholder : "nom d'entreprise, SIRET, nom de convention collective"
- [x] séparer les conventions collectives et les entreprises dans les résultats (par exemple lorsque l'on tape hotellerie)
- [x] plutôt que de mettre le numéro SIRET en haut à droite de l'entreprise, mettre "fiche entreprise"

**Comment by revolunet** [comment]
Pour la séparation CCns/entreprises, comment ca doit apparaitre ?

Deux "headers" pour séparer en deux sections de résultats ?

<img width="884" alt="Capture d’écran 2019-10-07 à 10 29 04" src="https://user-images.githubusercontent.com/124937/66296232-628fdf80-e8ed-11e9-9807-067cf220f28b.png">

**Comment by ClementChapalain** [comment]
je veux bien qu'on le voit ensemble mais oui j'imagine un truc comme ça

**Comment by revolunet** [comment]
Dans la meme issue, si on peut régler la question des noms courts/longs :)

**Comment by ClementChapalain** [comment]
ah yes ! tu as tout ce qu'il te faut sur le sujet ? a priori ça doit être dans l'api dila vu qu'ils l'ont sur legifrance

**Comment by revolunet** [comment]
oui j'ai la liste issue de legifrance : https://docs.google.com/spreadsheets/d/1bJJUCeMgvreDWH3vTx9F3Z13j8qNRGbYPbZZgGQy7uE/edit#gid=0

on utilise ce nom court partout ?

**Comment by ClementChapalain** [comment]
Super ! Je pense que sur la page de convention collective il vaut mieux utiliser le nom long car on a pas d'indication qu'il s'agit d'une convention collective sinon.

Mais dans le champ de sélection effectivement on peut utiliser le nom court.

**Comment by revolunet** [comment]
Cette issue peut être fermée au profit de #1241 #1364 #1407
