### ISSUE TITLE
Utiliser le champs de recherche CC dans le simulateur de préavis de démission

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1407]

**Comment by revolunet** [comment]
exemple d'implem du search CCN : https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-frontend/src/contributions/Contribution.js#L87

**Comment by ClementChapalain** [comment]
rappel suite à la démo : enlever la phrase qui indique que la convention collective est optionnelle pour le préavis de démission et ne pas permettre de passer à l'étape suivante si l'utilisateur n'a pas sélectionné de convention collective.

ping @nkrmr

**Comment by nkrmr** [comment]
Closed by : #1517

**Comment by nkrmr** [comment]
> rappel suite à la démo : enlever la phrase qui indique que la convention collective est optionnelle pour le préavis de démission et ne pas permettre de passer à l'étape suivante si l'utilisateur n'a pas sélectionné de convention collective.
> 
> ping @nkrmr

Done
