### ISSUE TITLE
accord de performance 

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#141]
source citée Direccte; source tagguée DGT. a corriger. 

https://github.com/SocialGouv/code-du-travail-data/blob/master/dataset/faq.json

    "branche": "",
    "question": "Comment s’applique un APC à un salarié en contrat à durée déterminée, notamment en matière de licenciement ?",
    "reponse": "Le licenciement d’un salarié protégé résultant de son refus de se voir appliquer un APC est, comme tout licenciement, subordonné à l’autorisation préalable de l’inspecteur du travail. Ce dernier doit être saisi de la demande après la mise en œuvre de la procédure interne à l’entreprise applicable à tout licenciement d’un salarié protégé (entretien préalable au licenciement ; le cas échéant, consultation du CSE en fonction du mandat détenu par le salarié protégé), et de la procédure conventionnelle prévue par l’accord APC.",
    "reponse": "<p>En ce qui concerne les salariés en CDD, il ne peut y avoir de licenciement en dehors des cas de rupture anticipée du contrat limitativement prévus par la loi (art. L. 1243-1 et L. 1243-2) :</p><p>-  en cas de faute grave,</p><p>-  de force majeure, </p><p>-  ou d'inaptitude constatée par le médecin du travail,</p><p>-  et à l'initiative du salarié, lorsque celui-ci justifie de la conclusion d'un contrat à durée indéterminée.</p><p>Dès lors, en cas de refus de modification du contrat de travail par un salarié en CDD, celui-ci ne peut pas être licencié.",
    "theme": "",
    "themes": [110000],
    **"source": "DGT",**
    "date": "07/09/2018",
    "profil": "employeur"
  }
]

**Comment by lionelB** [comment]
est ce que c'est possible d'avoir plus d'info. la clef `reponse` est en double, il faut garder la 2ieme ?
Normal que certaines soit en html et d'autre pas ?

**Comment by jrduscher** [comment]
Review 1.2: issue reopened

* la recherche "APC" renvoie sur une demand de filtres: "employeur", la validation ne donne rien renvoit : pas de résultat. 

Les contenus suggérés sur ces accords de performance collectives( ex avec une recherche sur: "heures") renvoient bien sur une réponse de la faq APC: les sources sont toujours notées DIRECCTE.

**Comment by lionelB** [comment]
@jrduscher  je pense que l'instance de dev etait pas à jour. La source est bien DGT ici => https://codedutravail-dev.num.social.gouv.fr/question/quest-ce-quun-accord-de-performance-collective-apc?q=apc&search=0

**Comment by jrduscher** [comment]
https://codedutravail-dev.num.social.gouv.fr/question/quest-ce-quun-accord-de-performance-collective-apc?q=apc&search=0

je note que ça bugge toujours: erreur 500.

**Comment by lionelB** [comment]
@jrduscher je viens de clicker sur ton lien ca fonctionne :/
