### ISSUE TITLE
Intégration thesaurus TESS

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#142]
Objectif : intégrer le thesaurus disponible ici :
https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-data/dataset/thesaurus/TESS_glossary.js

Besoin de specs fonctionnelles + ux pour voir comment on intègre ça au mieux.

https://trello.com/c/7lFIbSWo/186-pertinence-des-avec-le-tess-nouvelle-passe

**Comment by revolunet** [comment]
@jrduscher : On parle bien de ces fichiers ? https://github.com/SocialGouv/code-du-travail-numerique/tree/master/packages/code-du-travail-data/dataset/thesaurus

**Comment by revolunet** [comment]
Objectifs : synonymes, "hierarchie sémantique"...

**Comment by lionelB** [comment]
est ce qu'on retaggerai pas cette issue pour les EIG (poke @mhavel )

**Comment by ClementChapalain** [comment]
Est-ce que l'objectif est bien d'intégrer [ce contenu](https://github.com/SocialGouv/code-du-travail-numerique/tree/master/packages/code-du-travail-data/dataset/thesaurus) dans le moteur de recherche et faire en sorte que ce soir pertinent ?

**Comment by lionelB** [comment]
oui
