### ISSUE TITLE
Oups fautes d’orthographe/frappe dans la page qu'est ce que le droit du travail 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#1429]
**Description**
Il existe des fautes d'orthographe/frappe dans la page "qu'est ce que le droit du travail ?". 

Les mots concernés sont : 
- réglement intérieur qui doit être règlement intérieur; 
- et engagements unilatériaux qui doit être engagement unilatéraux. 

Où sont les fautes ? Je les ai repérées à 2 endroits : 
- au sein de la rubrique "Quels sont les textes à l’origine du droit du travail ?"
- au sein de la rubrique "Existe-t-il une hiérarchie entre les textes ?"
cf. les photos ci-dessous 

![image](https://user-images.githubusercontent.com/48682104/66474343-68262a80-ea91-11e9-9c10-db7ecb1a39db.png)
![image](https://user-images.githubusercontent.com/48682104/66474769-42e5ec00-ea92-11e9-8b49-98048e8a881f.png)

**Comment by jrduscher** [comment]
+ itoo sur la page à propos:
maîtrise
![image](https://user-images.githubusercontent.com/37538697/66479533-02d83680-ea9d-11e9-95fa-5735728e92bd.png)
