### ISSUE TITLE
contenu: afficher dates

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#143]
Toujours afficher dans les pages contenu : 

 - [ ] date de publication
 - [x] source
- [ ] s'assurer que ces modifs impactent également les contenus de la FAQ

**Comment by jrduscher** [comment]
> 1.4 dates sur fiches SP et fiches MinTrav

**Comment by lionelB** [comment]
PR #347  add date for article

**Comment by lionelB** [comment]
on peut fermer ?
