### ISSUE TITLE
[search-ccn]: utiliser les noms courts

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#1431]
Utiliser les noms courts dans le picker pour la recherche et l'affichage

(nécessite de modifier la query ES)

**Comment by ArmandGiraud** [comment]
Il faudrait également modifier les titres des conventions collectives à l'indexing de l'outil de recherche général.

**Comment by lionelB** [comment]
on peut le rajouter dans le mapping et avoir les 2 noms si on veut

**Comment by ClementChapalain** [comment]
avoir le nom long dans la recherche est synonyme de pbs aussi, comme taper "mars" dans la requete et avoir toutes les conventions signées en mars qui ressortent

**Comment by lionelB** [comment]
done in #2038
