### ISSUE TITLE
[search] datafiller fuzzy search

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#1437]
Actuellement la detection des requêtes du datafiller est faite de manière binaire avec un match parfait de la query. Il faudrait ajouter un peu de fuzzy côté API pour matcher les requêtes très approchantes, les memes mots dans un ordre différent.... peut-être voir [fuzzball](https://github.com/nol13/fuzzball.js#readme) pour une solution basique

**Comment by ArmandGiraud** [comment]
Un premier test avec fuzzball.token_sort_ratio et preprocessing:

pour chaque ligne le 
- 1: candidat (simulation d'une requête utilisateur
- 2: entrée du datafiller la plus proche
- 0: indique si la requête doit afficher les résultats pour l'entrée du datafiller.

⚠️ signale une erreur possiblement problématique
👍 signale un match difficile

9: Array[3]
0: "no"
1: "transfert de contrat"
2: "rupture de contrat"
11: Array[3]
0: "no"
1: "jour de repos"
2: "temps de pose"
12: Array[3]
0: "yes"
1: "fin de cdd"
2: "fin de cdd"
13: Array[3]
0: "no"
1: "cumul d'activité"
2: "calcul d'anciennete"
16: Array[3]
0: "yes"
1: "fiche de paie"
2: "fiche de paie"
17: Array[3]
0: "no"
1: "trop perçu"
2: "perco"
18: Array[3]
0: "no"
1: "ancienneté"
2: "prime anciennete"
19: Array[3]
0: "no"
1: "travail saisonnier"
2: "travail au noir"
22: Array[3]
0: "yes"
1: "harcèlement"
2: "harcelement"
23: Array[3]
0: "no"
1: "changement de poste"
2: "changement d horaire"
24: Array[3]
0: "yes"
1: "congé sabbatique"
2: "conge sabbatique"
25: Array[3]
0: "yes"
1: "solde de tout compte"
2: "solde de tout comptes"
26: Array[3]
0: "yes"
1: "démission préavis"
2: "demission preavis"
27: Array[3]
0: "no"
1: "repos hebdomadaire"
2: "travail le dimanche et repos hebdomadaire"
28: Array[3]
0: "yes"
1: "heures supplémentaires"
2: "heures supplementaires"
29: Array[3]
0: "yes"
1: "chômage"
2: "chomage"
30: Array[3]
0: "yes"
1: "préavis"
2: "preavis"
31: Array[3]
0: "yes"
1: "prime de précarité"
2: "prime de precarite"
32: Array[3]
0: "yes"
1: "rupture conventionnelle refusée"
2: "rupture conventionnelle refusee"
32: Array[3]
⚠️ 
0: "yes"
1: "preretraite"
2: "retraite"
33: Array[3]
0: "yes"
1: "attestation employeur"
2: "attestation pole emploi"
35: Array[3]
0: "no"
1: "quel salaire"
2: "bulletin salaire"
36: Array[3]
0: "yes"
1: "travail le samedi"
2: "travail le samedi"
37: Array[3]
0: "yes"
1: "durée préavis"
2: "duree du preavis"
38: Array[3]
0: "no"
1: "heures de nuit"
2: "heures supp"
39: Array[3]
0: "yes"
1: "licenciment"
2: "licenciement"
40: Array[3]
0: "yes"
1: "congé payé"
2: "conge paye"
⚠️ 
41: Array[3]
0: "yes"
1: "démission cdi"
2: "demission cdd"
42: Array[3]
0: "yes"
1: "licenciement pour inaptitude"
2: "licenciement pour inaptitude"
43: Array[3]
0: "no"
1: "maladie"
2: "arret maladie"
44: Array[3]
0: "yes"
1: "inaptitude"
2: "inaptitude"
45: Array[3]
0: "no"
1: "complément de salaire"
2: "complement salaire pole emploi"
46: Array[3]
0: "no"
1: "urgent"
2: "burn out"
47: Array[3]
0: "no"
1: "calcul des rtt"
2: "calcul stc"
48: Array[3]
0: "no"
1: "vehicule de service"
2: "grande reserve speciale"
👍 
49: Array[3]
0: "yes"
1: "indemnité fin de contrat"
2: "indemnite de fin de contrat cdd"
50: Array[3]
0: "no"
1: "avertissement"
2: "lettre avertissement"
51: Array[3]
0: "yes"
1: "indemnité de congés payés"
2: "decompte de conges payes"
53: Array[3]
0: "yes"
1: "inaptitude et licenciement"
2: "inaptitude et licenciement"
54: Array[3]
0: "yes"
1: "jour férié"
2: "jour ferie"
56: Array[3]
0: "no"
1: "licenciement salarié protégé"
2: "licenciement pour inaptitude salarie protege"
57: Array[3]
0: "no"
1: "conflit"
2: "delai conge"
58: Array[3]
0: "yes"
1: "mise à pieds"
2: "mise a pied"
60: Array[3]
0: "yes"
1: "licenciement rupture conventionnelle"
2: "licenciement rupture conventionnelle"
61: Array[3]
0: "yes"
1: "refus d'une rupture conventionnelle"
2: "refus de rupture conventionnelle"
63: Array[3]
0: "no"
1: "help"
2: "epl"
64: Array[3]
0: "no"
1: "discrimination"
2: "droits formation"
65: Array[3]
0: "no"
1: "rtt"
2: "tte"
66: Array[3]
0: "yes"
1: "démission pendant période d'essai"
2: "demissionner pendant sa periode d'essai"
67: Array[3]
0: "yes"
1: "fin de période d'essai"
2: "fin periode d' essai"
70: Array[3]
0: "no"
1: "allocations"
2: "allocations chomage"
71: Array[3]
0: "yes"
1: "heures complémentaires"
2: "heures complementaires"
72: Array[3]
👍 
0: "yes"
1: "renouvellement cdd"
2: "cdd renouvellement"
73: Array[3]
0: "yes"
1: "modification horaire de travail"
2: "modification horaires de travail"
74: Array[3]
0: "yes"
1: "démission et congés"
2: "demission et conges"
75: Array[3]
0: "yes"
1: "démission et chomage"
2: "demission et chomage"
76: Array[3]
0: "yes"
1: "indemnisation pôle emploi"
2: "indemnisation pole emploi"
77: Array[3]
0: "yes"
1: "droit au chomage"
2: "droit au chomage"
78: Array[3]
0: "no"
1: "prime"
2: "prudhommes"
79: Array[3]
0: "no"
1: "prime de vacances"
2: "cheque vacances"
80: Array[3]
0: "no"
1: "perte de salaire"
2: "date paiement salaire"
81: Array[3]
0: "yes"
1: "congé imposé"
2: "conge impose"
82: Array[3]
0: "yes"
1: "arrêt maladie"
2: "arret maladie"
83: Array[3]
0: "yes"
1: "temps de travail"
2: "temps de travail"
84: Array[3]
0: "no"
1: "pension d'invalidité"
2: "maladie professionnel"
85: Array[3]
0: "yes"
1: "accident de travail"
2: "accident de travail"
86: Array[3]
0: "yes"
1: "rupture de contrat"
2: "rupture de contrat"
87: Array[3]
0: "yes"
1: "cdd"
2: "cdd"
88: Array[3]
0: "yes"
1: "jours feries"
2: "jours feries"
89: Array[3]
0: "yes"
1: "harcelement moral"
2: "harcelement moral"
90: Array[3]
0: "yes"
1: "non renouvellement de contrat"
2: "non renouvellement de contrat"
91: Array[3]
0: "no"
1: "visite medicale d'embauche"
2: "promesse d' embauche"
92: Array[3]
0: "no"
1: "maintien de salaire"
2: "date paiement salaire"
93: Array[3]
0: "no"
1: "jours de fractionnement"
2: "fonctionnement des prud'hommes"
94: Array[3]
0: "no"
1: "invalidité"
2: "inaptitude"
6: Array[3]
0: "yes"
1: "congés payés"
2: "conges payes"
97: Array[3]
0: "yes"
1: "absence injustifié"
2: "absence injustifiee"
98: Array[3]
0: "no"
1: "chèque emploi service"
2: "cumul emploi retraite"
99: Array[3]
0: "yes"
1: "refus de conges"
2: "refus conges payes"

On valide? @ClementChapalain ?

**Comment by ClementChapalain** [comment]
hello, c'est pas hyper clair pour moi mais juste l'erreur "préretraire / retraite" suffit pour dire que ce nest pas suffisant.

de mon point de vue (de néophyte), le fuzzy est plus pour matcher les requêtes avec des fautes de frappe / orthographe style "retriate" -> "retraite" et non proposer des requêtes différentes.

pareil pour la requête : 
49: Array[3]
0: "yes"
1: "indemnité fin de contrat"
2: "indemnite de fin de contrat cdd"

le ctt (intérim) est également concerné donc je ne pense que ce soit pertinent de remplacer 1 par 2.

dispo pour en discuter !

**Comment by ArmandGiraud** [comment]
Ok il suffit de mettre un pourcentage de match plus élevé:
ici on était à match si > 80% 
distance("indemnité fin de contrat",  "indemnité de fin de contrat cdd") = 85

on peut passer à 90 voir 95% 
ce qui va limiter à une lettre de différence maximum.

@lionelB avait suggérer d'utiliser Elasticsearch plutôt qu'une librairie javascript. 
c'est toujours d'actualité?

**Comment by revolunet** [comment]
see #1731
