### ISSUE TITLE
Qualification juridique de la question

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#146]
Sur une question en language naturel, pouvoir identifier :

 - branche
 - theme
 - région

**Comment by jrduscher** [comment]
Qualifier juridiquement une réponse: le quotidien de l'agent de contrôle ou de renseignement : 
- identifier un problème
- rattacher ce problème à un texte
- permettre d'isoler la règle
- faire le lien avec les critères de l'infraction. 
- les faits relevés me paraissent il de nature à remplir tous les criètres qui constituent l'infraction?
( Les PV de l'inspection du travail sont construits comme cela: constat des faits, qualification juridique des faits, texte applicable, liens entre les faits et les textes autour des manquements et de l'infraction pénale, conclusion)

Exemple: dans un pv de l'inspection du travail, les faits aussi précis que possible sont rappelés


 L'usager a un problème et le formule
Partir des faits, de termes ou de  de critères pour isoler une règle de droit, c'est à dire retrouver la règle de droit applicable au cas de l'usager, les sources qui pemettent de lui répondre.



1) comprendre le sens de la question .
   Une démarche de filtres sémantiques peut être étudiée à l'image du prototype initial. Les termes de la question devant permettre d'isoler par élimination ou matchage les parties  du code concernées progressivement, jusqu'au niveau de l'article.

( La clause d'exclusivité de mon contrat de travail est elle légale?
I) 
-> Le contrat de travail est l'intitulé du Livre 2, de la première partie
-> La question ne porte pas sur la durée du travail ( Le sujet pourrait tendre vers là, mais pas la question), les conditions de travail, la négociation collective, les relations collectives, l’emploi, la formation ou les prud’hommes, ni l'inspection du travail...
II) dans ce livre II, isoler le ou les titres concernés, ici:  déterminer si la question porte sur la formation, l’exécution ou la rupture du contrat de travail, toujours en suivant la structure, la question porte t-elle sur le cdi, le cdd, ls autres formes de contrat d travail, le détachement, les chèques et titres simplifiés?
II) dans notre cas de figure, la clause d'exclusivité apparaît explicitement dans une série d'article portant 
sue le transfert d'entreprise. L'analyse de la structure doit permettre d’exclure ce cas pourtant pertinent ( on est dans la modification ou l’exécution du contrat avec les articles, la question évoque la formation du contrat)

Le CDT ne renverrait rien de bien probant: Cependant en affichant les généralités sur la fomration du contrat, le premier alinéa du prmeier article répond nous dit " le contrat de travail est soumis aux règles de droit commun" qui est une réponse, voire la réponse attendue. ( l'analyse des règles du contrat de droit commun doit répondre sur le plan de la légalité)
une recherche dans les sources ccn et le droit affiné sur la bse de ces isolations devrait affiner la pertinence et la compréhensbilité.

2) dans la multitude des réponses optimales proposées, il sera nécessaire a regard des sources qui matchent de discriminer par le type de branche d'activité ou la catégorie. A l'intérieur des sources branches, il ya des avenants,qui évoquent le sujet dans pluseurs textes du corpus des acords de branche applicable, déterminer leur différences pour cibler celle qui se rapproche de la situation du salarié

**Comment by ClementChapalain** [comment]
Cette tâche n'est pas vraiment actionnable, j'ai mis le contenu proposé par Jean-René dans le wiki sur le droit du travail : https://github.com/SocialGouv/code-du-travail-numerique/wiki/%5BDroit-du-travail%5D-Qualification-d'une-question
