### ISSUE TITLE
Gérer les changements de nom (et d'adresse) des contenus 

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#1477]
Pour l'instant aucune stratégie n'est en place pour gérer les changements d'adresse des contenus.
Cela est assez frequent sur les fiches-mt
Lorsqu'on met a jour les contenus, il faut pouvoir identifier les changements d'url pour pouvoir générer la liste des redirections 301 associés.

A voir comment cette liste peut ensuite être transmise au nginx

**Comment by revolunet** [comment]
(une RFC arrive côté Next.js sur ce sujet)

**Comment by m-maillot** [comment]
Ticket sur l'admin pour gérer les changements de nom et d'url en cours. Je clôture pour éviter les duplicats
