### ISSUE TITLE
Format des urls pour améliorer le référencement

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#1482]
### Thèmes

Dans la navigation par thèmes, les urls devraient être nestées et si possible supprimer le mot "themes" et le chiffre de chaque thème afin d'obtenir qqchose comme cela :
`/salaire-et-remuneration/primes-et-avantages`

au lieu de l'actuel :
`/themes/22-primes-et-avantages`

La partie importante est le fait que les urls soient nestées, le reste (enlever thèmes et le chiffre) peut être discutée.

### Contenus

Dans les contenus (fiches MT, SP, contributions, outils, modèles), il faudrait afficher leur thème plutôt que leur type dans l'url : 
`/primes-et-avantages/salarie-comment-obtenir-et-utiliser-des-titres-restaurant`

Update -> il faudra surement ajouter un slug pour rendre unique les urls : 
`/primes-et-avantages/14-salarie-comment-obtenir-et-utiliser-des-titres-restaurant`

Plutôt que l'actuel : 
`/fiche-service-public/salarie-comment-obtenir-et-utiliser-des-titres-restaurant`

**Comment by lionelB** [comment]
je veux bien (si elle existe) l'explication de l'impact d'utiliser des arbo profondes dans le reférencement

**Comment by Abdessamadyssf** [comment]
@lionelB @revolunet 

Je viens d'investiguer l'intérêt SEO, et effectivement une URL trop longue n'a pas d'impact sur le référencement.

L'idéal serait d'avoir le chemin de la navigation dans l'URL mais pas sur toute la profondeur. Avoir une URL qui reprend le chemin jusqu'au dernier niveau thématique. 
Exemple : https://codedutravail.num.social.gouv.fr/themes/2-salaire-et-remuneration/21-salaire

(D'ailleurs peut-on retirer "Themes" et les chiffres des url ?)

Mais une fois arrivé sur la fiche, avoir une url qui reprend le titre de la fiche et le sous-thème dans laquelle la fiche est rattachée. Aujourd'hui l'url des fiches remontent le tag "Fiche Service Public" ou "Fiche Ministere du travail".

L'idéal serait d'avoir : 

https://codedutravail.num.social.gouv.fr/**salaire**/comment-un-assistant-maternel-doit-il-declarer-ses-revenus

au lieu de : 

https://codedutravail.num.social.gouv.fr/fiche-service-public/comment-un-assistant-maternel-doit-il-declarer-ses-revenus

On en rediscute, je continue à investiguer la meilleure solution SEO.

**Comment by revolunet** [comment]
une source : https://www.searchenginejournal.com/site-structure-seo/292803/

**Comment by revolunet** [comment]
sur la longueur de l'url, ca date un peu mais a priori la limite est haute : https://seomofo.com/experiments/what-is-the-maximum-character-length-for-a-url-that-google-will-index

cependant les urls courtes seraient privilégiées : https://ahrefs.com/blog/on-page-seo/

btw nos urls sont en général longues à cause des titres des contenus

**Comment by lionelB** [comment]
Thx

**Comment by Abdessamadyssf** [comment]
Un peu de doc pour vous aider : 
- https://www.webrankinfo.com/dossiers/techniques/url-et-referencement
- https://moz.com/learn/seo/url
- https://support.google.com/webmasters/answer/76329?hl=fr&ref_topic=9460495

**Comment by Abdessamadyssf** [comment]
Pistes d'explorations :
- Checker unicité des slug
- Token dynamique avant le contenu : Thème parent (voir les check à faire au niveau de l'API sur ce token dynamique en fonction du type de contenu récupéré via le slug qui suit - je ne sais pas si c'est très clair)
- Modif au niveau de l'API pour avoir la nouvelles route et au niveau du front pour l'utiliser et factoriser toutes les pages avec `[slug]`

Risque : 
- Checker les effets de bords sur le front

Bon point:
Le type de document n'apparaitra plus dans l'URL, c'est une bonne chose non ?

Actions : 
- Estimer l'apport SEO de cette amélioration
- Faire les spec de la tache

Estimation = **M** voir L 

Impact positif sur le code : Centraliser certains comportements

@ClementChapalain

**Comment by UnbearableBear** [comment]
J'ai modifié quelques pétouilles dans ton récap !

**Comment by ClementChapalain** [comment]
Merci beaucoup pour le recap et l'estimation ! Pour estimer l'impact SEO ça va être assez compliqué donc on va p-e déprioriser cette tâche d'ici le 1er janvier

**Comment by UnbearableBear** [comment]
UP !

**Comment by UnbearableBear** [comment]
Je liste ici quelques fichiers qui mériteraient peut-etre un refactor dans le cadre de cette issue (liste complètement non exhaustive :
https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-api/src/server/routes/search/getDocumentByUrlQuery.js
https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-api/src/server/routes/search/getDocumentByUrlQuery.js
https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-frontend/src/search/SearchResults/Results.js

On peut parfois avoir des liens internes à plusieurs niveau qui ne représentent pas de la data référencées dans es. (pages statiques des sous-dossiers pour moment)

**Comment by UnbearableBear** [comment]
closed in favor of https://github.com/SocialGouv/code-du-travail-numerique/issues/3058
