### ISSUE TITLE
Bug report : des mots sont remplacés dans certains contenus sur Master

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1483]
Sur la version master seulement  vu dans le contenu ci après ( pas testé ailleurs), les mots "heures de recherche d'emploi" et" loi" sont remplacés par préavis. 

http://master.code-du-travail-numerique.dev.factory.social.gouv.fr/fiche-service-public/le-salarie-beneficie-t-il-dheures-de-recherche-demploi-pendant-son-preavis?q=heures%20de%20recherche%20d%27emploi

> Le salarié bénéficie-t-il d'heures de recherche d'emploi pendant son préavis ?
> Fiche service-public.fr
> Mis à jour le : 29/06/2018
> La loi ne prévoit pas d'préavis pendant le préavis. À défaut de dispositions prévues par la préavis, un préavis ou un usage prévu dans la profession ou dans l'entreprise, le salarié ne peut pas s'absenter de l'entreprise pour rechercher un nouvel emploi pendant la durée de son préavis.
> 
> Si la préavis, un préavis ou un usage prévoit des préavis, le salarié exécute son préavis et dispose d'un certain nombre d'heures d'absence par jour (ou par mois) pour trouver un nouvel emploi.
> 
> La rémunération des heures de recherche peut être prévue par la convention collective, un convention collective ou un usage, intégralement ou non. La rémunération des ces heures peut être négociée directement en accord avec l'employeur.
> 
> Voir le contenu original sur : service-public.fr

**Comment by lionelB** [comment]
les tooltips ont encore frappés, je m'ne occupe
