### ISSUE TITLE
autosuggest stops working after a first "enter"

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#1489]
Si on tape entrée sur une premiere recherche, le suggester le se re-déclenche plus ensuite

![autosuggest](https://user-images.githubusercontent.com/124937/67002503-54f00c00-f0dc-11e9-9f69-d691212136b3.gif)

**Comment by UnbearableBear** [comment]
Si c'est récent, mon petit doigt me dit que c'est lié à ça : https://github.com/SocialGouv/code-du-travail-numerique/pull/1467/files

**Comment by revolunet** [comment]
bien vu, je teste

**Comment by UnbearableBear** [comment]
hint, j'avais lu quelque part que le useRef restait malgré les mount/unmount alors que le callback de useEffect est appellé à chaque unmount

**Comment by revolunet** [comment]
confirmed, je propose un revert en attedant mieux
