### ISSUE TITLE
[SEO] Rendre administrable toutes les balises title et méta descriptions

### ISSUE THREAD

**Issue by Abdessamadyssf** [SocialGouv/code-du-travail-numerique#1492]
**Fonctionnalité**
Rendre administrable toutes les balises title et méta descriptions via le CMS

**Problème**
En tant qu'internaute, je tombe sur le site CDTN dans Google mais je ne suis pas attiré par celui-ci car je ne vois pas de titre cohérent ni de description, donc je ne clique pas.

Objectifs : 
- Augmenter le tx de clic du site CDTN lorsqu'il apparaît dans les résultats de recherches de Google.
- Améliorer le référencement

![image](https://user-images.githubusercontent.com/56535039/67014220-bd4ae780-f0f4-11e9-8cbb-97ff6653353b.png)

@revolunet

**Comment by lionelB** [comment]
la plupart des contenus ont une description mais effectivement, celle des courriers ne remontent pas. Est ce qu'avant de créer un outil pour mettre à  jour les titres / desc des contenus on peut deja essayer de mettre à jour les json ?

**Comment by revolunet** [comment]
Pour les courriers, la liste des modeles et leur description sont editables ici : https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-data/dataset/courrier-type/courriers.json

**Comment by revolunet** [comment]
Pour les courriers, on peut utiliser le champ "description" du json ? sinon rajouter un champ `metaDescription` qui sera utilisé

**Comment by revolunet** [comment]
ce qui est étrange c'est que la balise meta description est bien présente sur ce modèle. ca dit quoi @Abdessamadyssf dans "Découvrir pourquoi"?

```html
<meta name="description" content="Le salarié à temps partiel peut demander une durée du travail hebdomadaire inférieure à celle prévue soit par le code du travail ou par un accord de branche…"/>
```

**Comment by Abdessamadyssf** [comment]
C'est surement dû au robots.txt qui bloquait, attendons de voir suite à ta MAJ du fichier robots.txt

@revolunet

**Comment by lionelB** [comment]
Pour les contenus type fiches, j’avais repris le champs description existant (en général, plutôt bien fait) dans les cas où il n’y en pas (et pour les autres documents, je prenais le début du texte, tronqué à 150 caractères (+/- le mot en cours) si ça vous intéresse on peut sortir la liste des contenus sans description ?
