### ISSUE TITLE
Réinitialiser le filtre lors du clic sur le titre.

### ISSUE THREAD

**Issue by kemar** [SocialGouv/code-du-travail-numerique#15]
Pour reproduire :

- se rendre dans `Accueil > Contrat de travail`
- appliquer un filtre choisi dans `Quel est le type de votre contrat ?`
- cliquer sur le titre

Résultat : la liste est toujours filtrée.

Résultat attendu : la liste n'est plus filtrée.

**Comment by jrduscher** [comment]
https://orange-business.webex.com/orange-business/j.php?MTID=mb8ad57bb42275dc6f04fde61219a519c

**Comment by lionelB** [comment]
@jrduscher  ????

**Comment by kemar** [comment]
@jrduscher ????

**Comment by revolunet** [comment]
@kemar ????

**Comment by lionelB** [comment]
![lebowski](https://user-images.githubusercontent.com/160320/59683273-2a4a8100-91d8-11e9-952b-7ecb55e908c1.jpg)

**Comment by kemar** [comment]
![tumblr_n1ywviPye51r1d5rwo1_1280](https://user-images.githubusercontent.com/281139/59691048-b792d300-91e2-11e9-867d-530ff0da390e.jpg)

**Comment by revolunet** [comment]
![](https://media.giphy.com/media/3WmWdBzqveXaE/giphy.gif)
