### ISSUE TITLE
[datafiller]: nested themes selection

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#1505]
Dans le datafiller, le selecteur de thème est "flat", la hierarchie n'est pas représentée.

Il faudrait pouvoir visualiser la hierarchie dans le select

**Comment by ClementChapalain** [comment]
@virginielastisneres ajouter la fonctionnalité pour povoir supprimer un thème

**Comment by revolunet** [comment]
(intégré dans la dernière version du datafiller)

**Comment by lionelB** [comment]
done ? 
![image](https://user-images.githubusercontent.com/160320/72625175-9779ec80-3948-11ea-85fb-60f8d3d37d1c.png)

**Comment by revolunet** [comment]
yep
