### ISSUE TITLE
Réorganisation de la page de recherche

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1512]
## Problème

Aujourd'hui nous lançons une recherche dans tous les types de contenus et les affichons en les séparant en trois sections : français facile (fiches + outils + contributions), loi (cdt + cc), thèmes

Par exemple pour la recherche "test" :
![image](https://user-images.githubusercontent.com/5337489/67161911-69900680-f35f-11e9-8dd6-bf4898362827.png)

Cela pose un certain nombre de problèmes :
- conventions collectives
  - nous remontons parfois des conventions collectives dans des cas où cela n'a pas de sens, par exemple avec la requête "assurance voiture" qui remonte une convention collective
  - si l'utilisateur cherche spécifiquement une convention collective, alors nous lui montrons beaucoup de contenus non pertinents avant d'arriver à sa recherche
  - si l'utilisateur cherche une convention collective, nous avons tout intérêt à lui proposer d'utiliser le champ de recherche développé spécifiquement à cet égard qui est beaucoup plus performant
- thèmes et code du travail
  - nous ne renvoyons que rarement des thèmes, alors qu'ils pourraient être intéressants en rebond pour potentiellement toutes les recherches
  - certaines requêtes particulières ne renvoient au contraire que des thèmes ("bébé" par exemple) alors qu'elles ont des contenus associés pertinents
  - idem pour les articles du CDT, ils sont rarement retournés alors que c'est une de nos promesses initiales

### Toujours remonter des thèmes et des articles du CDT en faisant une recherche ad-hoc 

Les thèmes et les articles CDT devraient être une section à part lancées avec une recherche différente, de manière à toujours remonter des thèmes pour chaque requête. 

Les thèmes étant une forme de rebond, ils ne doivent pas être gérés dans la recherche primaire.

De cette manière, nous pouvons également gérer le nombre de thèmes / articles CDT qui apparait à chaque fois et analyser l'utilisation de cette section de manière spécifique.

![image](https://user-images.githubusercontent.com/5337489/67491536-62c20600-f675-11e9-9950-2de87bdedeb5.png)

### Conventions collectives accessibles dans un second temps

En regardant toutes les recherches réalisées sur la production depuis mai, on se rend compte que les recherches d'une convention collective sont très peu représentées : 
https://docs.google.com/spreadsheets/d/1hkmCT8ufRKRvx1v3c0xFqngA0ep7WVB_QLm0Ra7ryPI/edit#gid=547475705

La proposition est donc de les rendre possible mais dans un second temps si l'utilisateur souhaite réellement les rechercher.

- Le lien convention collective ouvre la popup avec le champ de recherche CC qu'on peut trouver sur la homepage
- Le lien consulter les thèmes renvoie vers la page des thèmes
- Le lien "découvrir le droit du travail renvoie vers la page d'intro au droit du travail

![image](https://user-images.githubusercontent.com/5337489/67491571-740b1280-f675-11e9-91e0-821b2aa39661.png)

### Vision d'ensemble de la nouvelle page de recherche

![search_results](https://user-images.githubusercontent.com/5337489/67491396-2db5b380-f675-11e9-8323-eda9f73113dc.png)

**Comment by ClementChapalain** [comment]
@lionelB @UnbearableBear c'est mis à jour avec les retours vus au planning !

**Comment by ClementChapalain** [comment]
quelques retours sur la pr : 
- il y a un scroll vertical dans les articles du CDT dans la description
- je pense qu'on devrait limiter le nombre de résultats de la première section à 5, là ça fait beaucoup de scroll je trouve
- pour info le dernier bouton "découvrir le droit du travail" on préfère ne pas le mettre, notamment car le contenu n'a pas été validé par la DGT encore

c'est trop cool en tout cas merci :)

**Comment by ClementChapalain** [comment]
autre remarque : pourquoi on a pas toujours 5 thèmes qui ressortent ? par exemple avec "démission" ou "13e mois" ou "test absurde" ?

**Comment by ClementChapalain** [comment]
aussi, les liens vers les thèmes ne fonctionnent pas mais c'est p-e lié à la version de test (j'ai un message "widget non disponible")

**Comment by virginielastisneres** [comment]
je rejoins clément sur les 2 premiers retours. Il faut limiter le nombre de résultats, quitte mettre une action "charger plus de résultats" ou quelque chose comme cela. 

Il y a une chose qui me chagrine un peu c'est le placement des articles du code du travail par rapport aux autres résultats. Je ne mets pas les thèmes dedans car c'est plutôt des rebonds. 
Du fait qu'il n'y a pas la même largeur pour le bloc contenus et le bloc articles du code du travail, on n'a pas l'impression que les articles du code du travail sont des résultats de la recherche effectuée. On dirait que c'est un autre truc non lié aux résultats... 

Je sais pas si c'est possible mais peut être qu'il faudrait les traiter pareil concernant la largeur de ces deux blocs. 

![image](https://user-images.githubusercontent.com/48682104/68484995-b2d8c500-023e-11ea-939f-9d6a5de8c90f.png)

**Comment by ClementChapalain** [comment]
Je suis d'accord le design est pas parfait @virginielastisneres (je suis coupable là dessus) mais concentrons plus plutôt sur le fonctionnel sachant que ça va être rechangé bientôt avec les nouvelles maquettes si c'est ok pour toi

**Comment by lionelB** [comment]
> autre remarque : pourquoi on a pas toujours 5 thèmes qui ressortent ? par exemple avec "démission" ou "13e mois" ou "test absurde" ?

la récupération des themes se base pour l'instant dans le titre du theme et les titre dans son fils d'ariane (ses parents)  je veux bien des exemples de theme à remonter pour voir comment orienté la recherche

**Comment by virginielastisneres** [comment]
Yes ;) Si c'est rechangé avec les nouvelles maquettes c'est good pour moi @ClementChapalain !

**Comment by virginielastisneres** [comment]
Petite question, s'il n'y a pas écrit de thème sur la fiche c'est que la fiche n'a pas été thémée ? 
![image](https://user-images.githubusercontent.com/48682104/68485948-7017ec80-0240-11ea-88c8-3fcdb82c4e45.png)

**Comment by lionelB** [comment]
oui

**Comment by virginielastisneres** [comment]
thanks @lionelB (déso d'avoir dérangé avec ca :) )

**Comment by ClementChapalain** [comment]
> la récupération des themes se base pour l'instant dans le titre du theme et les titre dans son fils d'ariane (ses parents) je veux bien des exemples de theme à remonter pour voir comment orienté la recherche

ah ok, du coup on peut pas faire de recherche sémantique dessus ? sinon on pourrait p-e faire des recherches dans les documents de ces thèmes mais bon ça parait compliqué, donc si c'est pas possible gardons comme ça c'est déjà une grosse avancée. et on pourra voir avec les eig pour faire mieux plus tard.
