### ISSUE TITLE
Récupération d'autres contenus dans les contributions

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1513]
Pour certaines contributions, la réponse générique est traitée dans une fiche service public ou ministère du travail.  Dans le markdown de la réponse générique, ceci est indiqué par une balise du type `<content href=""/>` avec l'url du contenu sur le site correspondant (service public ou ministère du travail).

Il faut donc faire en sorte que lorsqu'on détecte cette balise dans les réponses génériques des contributions on puisse récupérer et afficher le contenu de la fiche correspondante.

On affiche tout le contenu de la fiche avec les références juridiques s'il y en a.

Prévoir un point avec @revolunet avant de commencer pour voir comment la première version de l'intégration des contributions a été réalisée.

Exemple de contribution concernée : 
> 6) Arrêt maladie pendant la période d'essai : quelles sont les règles ?
> 
> https://contributions.codedutravail.num.social.gouv.fr/admin/generic-answers/ccac1236-f435-4869-87a6-220bbd558076

**Comment by revolunet** [comment]
Afficher le contenu complet de la fiche

**Comment by revolunet** [comment]
Lorsque l'on détecte une balise `<Content href="https://www.service-public.fr/particuliers/vosdroits/F1906"/>` dans le MDX de la contribution, il faudra :

 - "resolve" la fiche à recherche dans ES (qui est indéxée par slug)
 - récupérer le contenu de la fiche depuis ES et les fournir (via `getInitialProps`)
 - afficher avec le composant `FicheServicePublic` ou `FicheMT` selon le contenu

**Comment by revolunet** [comment]
cf également PR #1660

**Comment by revolunet** [comment]
Bonus point si tu arrives à faire marcher le mdx avec des composants html "custom" :) echec de mo côté

**Comment by nkrmr** [comment]
Si je comprends bien on va avoir plusieurs URL avec du contenu similaire entre les fiche service public ou ministère du travail et la fiche contribution qui va extraire le contenu de ces dernières. 
Il y a un risque de "duplicate content" sur le référencement

**Comment by ClementChapalain** [comment]
si  il faudra qu'on vire les fiches sp et mt car elles ne serviront plus en fait après, mais on fait ça dans un deuxième temps

**Comment by lionelB** [comment]
> si il faudra qu'on vire les fiches sp et mt car elles ne serviront plus en fait après, mais on fait ça dans un deuxième temps

est ce que tu peux préciser, tu parles des supprimer les d'ou ?

**Comment by ClementChapalain** [comment]
Si on récupère 100% de leur contenu pour la partie générique d'une page contribution, on aura plus besoin de les afficher en tant que telles. Si on continuait à les afficher ça nous ferait une page avec la fiche + les contributions en dessous, et une autre page avec uniquement la fiche.

Mais c'est pas essentiel vu que ça concerne que quelques fiches (moins de 10) et que ça ne crée pas réellement de bug.
