### ISSUE TITLE
Arrêter le référencement des dossiers service-public

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1515]
Nous référençons des dossiers service public qui redirigent vers service-public directement, ce qui nous empêche de proposer notre valeur à l'utilisateur (contenus associés, outils, glossaire, etc.).

Il faudrait arrêter de les référencer.

Exemple sur cette recherche sur le licenciement économique :
![image](https://user-images.githubusercontent.com/5337489/67162951-cd1f3180-f369-11e9-9f39-85101b2147c8.png)

**Comment by lionelB** [comment]
hello, je pense que c'est des résultats qui proviennent des requêtes pré-enregistrées car julien a laissé la possibilité de mettre des liens externes

**Comment by ClementChapalain** [comment]
ok merci pour l'info ! ça vous dit qqchose @jrduscher @virginielastisneres ?

**Comment by virginielastisneres** [comment]
oui @ClementChapalain en effet nous avions la possibilité de mettre des liens externes pour une raison que je me rappelle plus... peut être fiches non indexées à l'équope dans elasticsearch. 
Il faut que nous refassions une passe dessus pour les supprimer

**Comment by ClementChapalain** [comment]
ok je laisse cette tâche mais métier du coup

**Comment by lionelB** [comment]
@ClementChapalain on peut lister ces contenus aussi et les virer en meme temps que les faq

**Comment by ClementChapalain** [comment]
c'est fait ça non @virginielastisneres ?

**Comment by virginielastisneres** [comment]
yes il reste je crois juste les articles du code de la sécurité sociale.... est-ce que ca serait possible de les traiter différemment ou pas ?

**Comment by ClementChapalain** [comment]
différemment dans quel sens ?

**Comment by virginielastisneres** [comment]
éviter qu'ils soient affichés comme cela 
![image](https://user-images.githubusercontent.com/48682104/67788473-b2883f00-fa72-11e9-8dcf-0f3a900a76b4.png)

mais plutôt comme les articles du code du travail
![image](https://user-images.githubusercontent.com/48682104/67788534-cdf34a00-fa72-11e9-9e14-2f6a0c97614b.png)

Après si ce n'est pas possible, il faudra peut être les supprimer... j'ai pas encore d'avis trancher sur ce point là.

**Comment by ClementChapalain** [comment]
ok, il faudrait les avoir dans notre site je pense, en les récupérant via l'api dila (ping @revolunet) mais pour l'instant gardons les si c'est vraiment pertinent je pense
