### ISSUE TITLE
Mise en avant des outils et modèles de document dans la suggestion de contenus

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1519]
Nous souhaitons mettre l'accent sur les contenus les plus actionnables de notre site, i.e. les modèles de document et les outils, dans les suggestions de contenus qui apparaissent sur la droite d'un contenu.

To do :
- on garde le principe de la requête sur le nom du document pour récupérer cette liste, mais on prend désormais 5 contenus
- les outils doivent être affichés en dessous du bloc "les articles pouvant vous intéresser" avec le design qu'ils ont sur la homepage (leur titre + un bouton d'action dans une card)
- idem pour les modèles, on les affiche de la même manière que les outils (en dessous des articles mais au-dessus des outils).
- pour ne pas surcharger la page, on met au max 1 modèle et 1 outil en plus des 3 articles, si la requête remonte plus de 1 modèle et 1 outil, alors on affiche uniquement l'outil le plus pertinent et le modèle le plus pertinent

**Comment by lionelB** [comment]
c'est pour la page de recherche ? pourquoi pas dans #1512

**Comment by ClementChapalain** [comment]
"dans les suggestions de contenus qui apparaissent sur la droite d'un contenu." :)
