### ISSUE TITLE
Bug report: regressions UI navigateurs divers

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1520]
**Ascenseurs dans les tuiles qui appairassent dans: Chrome, firefox, edge et IE11**
![image](https://user-images.githubusercontent.com/37538697/67203633-de207f00-f40b-11e9-8ed7-23a46ebe5663.png)

![image](https://user-images.githubusercontent.com/37538697/67203646-e5e02380-f40b-11e9-9488-b2472ec48c35.png)
IE 11
![image](https://user-images.githubusercontent.com/37538697/67203674-03ad8880-f40c-11e9-92c0-c0cd5b03645d.png)

**Comment by UnbearableBear** [comment]
La fameuse tuile IE11 !

**Comment by lionelB** [comment]
rhooo la TUILE :(

**Comment by virginielastisneres** [comment]
pas beau sur IE11
![image](https://user-images.githubusercontent.com/48682104/67205584-4ec99a80-f410-11e9-962e-c6798f6f2466.png)

**Comment by jrduscher** [comment]
pas beau non plus : l'encart article ne suit pas la lecture.
![image](https://user-images.githubusercontent.com/37538697/67205873-efb85580-f410-11e9-9fea-65840eb16961.png)
