### ISSUE TITLE
Bug report: mise à jour des modèles de courrier ( métier)

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1524]
Vérifier et modifier:

fait | motif | title
-- | -- | --
- [x] | Les informations proposées ne sont pas à jour | 
**Modèle de courrier :  Rupture d’un commun accord d’un contrat d’apprentissage**

- [x]  | Les informations proposées ne sont pas à jour |
 **Modèle de courrier :  Réclamation des documents de fin de contrat**

- [x]  | Les informations proposées ne sont pas à jour |
**Modèle de courrier :  Convocation à entretien préalable**

- [x]  | Les informations proposées ne sont pas à jour | 
**Modèle de courrier :  Demande de dérogation pour un temps partiel**

- [x]  |  Les informations proposées ne sont pas à jour | 
**Modèle de courrier :  Demande de dérogation pour un temps partiel**

- [x]  |  Les informations proposées ne sont pas à jour |
**Modèle de courrier :  Demande de paiement de salaire**

- [x]  | Les informations proposées ne sont pas à jour |
 **Modèle de courrier :  Réclamation congés payés**

**Comment by jrduscher** [comment]
https://github.com/SocialGouv/code-du-travail-numerique/pull/1565

note: en l'état amélioration du wording introductif, qui semble justifier seul les remontées.

**Comment by lionelB** [comment]
@jrduscher on fermera l'issue une fois la PR mergée
