### ISSUE TITLE
Bug report : UI simulateur de licenciement

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#1526]
**Description**
Dans le nouvel UI du simulateur de l'indemnité de licenciement apparaît dans la page résultat une barre de scroll horizontale, on ne peut pas voir la page de résultat en entière...
J'ai cette barre sur chrome, firefox mais pas sur IE11.

**Screenshots**
![image](https://user-images.githubusercontent.com/48682104/67217163-99eda880-f424-11e9-8b2f-8b4577e48a2e.png)

**Comment by lionelB** [comment]
je m'en occupe !
