### ISSUE TITLE
Remove old faq from datafiller requests

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#1529]
Since we had removed faq / faq-contributions we should also remove their references from the datafiller.

```js 
const requests = require("@cdt/data...datafiller/prequalified.data.json");
const ids = requests
   .filter(({id, refs}) => refs.some(({url}) => url.startsWith("/question")))
   .map(({id}) => id)
```

**Comment by UnbearableBear** [comment]
Shouldn't we remove them from in the datafiller instead of filtering in the code ?

**Comment by lionelB** [comment]
yes. the code above return a list of id to remove / update

**Comment by ClementChapalain** [comment]
c'est fait ça d'après ce que tu disais hier @virginielastisneres ?

**Comment by virginielastisneres** [comment]
je parlais des liens externes hier plutôt que des anciennes FAQ mais il me semblait qu'elles avaient été enlevées, non ? @revolunet @lionelB

**Comment by revolunet** [comment]
le grand nettoyage n'a pas encore été fait :/ cependant cela ne doit pas "géner". les entrées qu'on ne trouve pas ne doivent simplement pas s'afficher

**Comment by ClementChapalain** [comment]
ok du coup c'est une tâche dev pour faire en sorte de ne pas prendre en compte ces résultats ?

**Comment by revolunet** [comment]
a verifier mais pour moi c'est deja le cas : les resultats nont trouvés ne s'affichent simplement pas

**Comment by ClementChapalain** [comment]
oui effectivement, je ferme en attendant de voir si on retombe sur ce bug
