### ISSUE TITLE
préavis de démission: bug affichage sélection de la CCN

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1537]
le champ de sélection des CCN dépasse le cadre, la sélection des boutons d'action nécessiter de scroller:

![image](https://user-images.githubusercontent.com/37538697/67265241-8aff0880-f4ad-11e9-9b50-e17f0ed83eff.png)

**Comment by nkrmr** [comment]
@jrduscher c'est possible de savoir sur quel navigateur cela se produit?

**Comment by lionelB** [comment]
le bug devrait disparaitre quand on passera utilisera InfoCCn dans ce simulateur

**Comment by lionelB** [comment]
cf #1526 et #1527

**Comment by lionelB** [comment]
closed by #1517
