### ISSUE TITLE
Questions hors scope

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#154]
- Identifier les questions hors scope
- proposer une réponse addapté pour dire qu'on ne peut pas répondre à la question

https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-data/dataset/fiches_service_public/fiches-sp-travail.json

issue originale:  https://github.com/SocialGouv/code-du-travail-data/issues/9

**Comment by jrduscher** [comment]
> contrat doctoral : décret 2009-464. contrat de droit public. hors scope

**Comment by ClementChapalain** [comment]
quelques idées en brèche pour aller au plus simple sur ce un sujet comme ça :
- configurer ES pour qu'une recherche avec un thème qui appartient à la blacklist ("contrat doctoral", "fonction publique", etc.) renvoie vers un disclaimer avec potentiellement les résultats classiques également
- mettre une page d'explications dans le footer ou dans la page à propos pour donner le cadre du code du travail et expliquer ce qui y est traité ou non

**Comment by ClementChapalain** [comment]
lié à #87
