### ISSUE TITLE
Clean de la base des suggestions

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1541]
Deduplicate / Disambiguation / Clean:
Il y a beaucoup de doublons et de suggestions qui sont dupliquées avec des orthographes différentes.

Dans un premier temps, il faudrait simplement créer un méchanisme de filtrage pour : 
- grouper les suggestions très semblables (clustering / near duplicate detection (LSH?)
- isoler la meilleure query via un check orthographe / syntaxe (hunspell?)
- enlever les suggestions qui ne renvoient aucun résultat dans la rechercher Elastic (on verra plus tard si on utilise un threshold pour la recherche sémantique)

On developpera plus tard un pipeline automatique qu'on pourra directement appliquer aux requetes issues des logs.

**Comment by ArmandGiraud** [comment]
> - grouper les suggestions très semblables (clustering / near duplicate detection (LSH?)

-  commençons par une simple edit distance.

> - isoler la meilleure query via un check orthographe / syntaxe (hunspell?)

- [pyspellchecker](https://pypi.org/project/pyspellchecker/) permet d'utiliser un des dico custom sur des frequences.

> - enlever les suggestions qui ne renvoient aucun résultat dans la rechercher Elastic (on verra plus tard si on utilise un threshold pour la recherche sémantique) 

- ok
