### ISSUE TITLE
Réponses FAQ qui ne devraient plus apparaitre dans la recherche

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1543]
http://master.code-du-travail-numerique.dev.factory.social.gouv.fr/recherche?q=poly-expos%C3%A9

la réponse sur les travailleurs poly exposés a normalement été enlevée via #1283

**Comment by lionelB** [comment]
le document a bien été enlevé ! c'est une requete pré-enregistré je ferme car on a deja #1529
