### ISSUE TITLE
Sigles et synonymes : mise à jour 1/2

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#155]
"agents chimiques dangereux, ACD",
"convention Collective Nationale, CCN",
"intérimaire, travailleur temporaire",
"Diagnostic technique Amiante, DTA",
"entreprise utilisatrice, EU",
"entreprise utilisatrice, entreprise d'accueil",
"Plan de retrait amiante, PRA",
"délai-congé, préavis",
"quadricycles, quad",
"très basse tension de sécurité,TBTS",
"protocole de chargement et déchargement, protocole de sécurité",
"surveillance médicale, suivi médical",
"garages, commerce et de la réparation de l'automobile", //CCN
"assmat, ass. mat., ass mat, ass.mat., ass-mat, assistant maternel",
"grossesse, maternité, enceinte",
"cancérigène, cancérogène",
'temps de travail effectif, TTE",

// à intégrer au mois de septembre

issue originale : https://github.com/SocialGouv/code-du-travail-data/issues/5

**Comment by ClementChapalain** [comment]
C'est ok j'ai l'impression @lionelB ?
![image](https://user-images.githubusercontent.com/5337489/52638265-e1a15500-2ed1-11e9-8db4-88508e5321f4.png)

**Comment by lionelB** [comment]
@ClementChapalain non, pas tous, meme si TBTS est déja présent
