### ISSUE TITLE
ignorer les espace quand on fait une recherche de ccn par siret

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#1563]
**Description**
Quand on cherche le SIRET d'une société sur internet, il est fréquent de tomber sur un numéro présenté avec des espaces entre les nombres : exemple 821 980 877 00020. 

Si je fais copier/coller du numéro tel quel sur notre moteur de recherche de convention collective, le moteur ne trouve pas de résultat... 
Alors que si j'enlève les espaces entre les numéros j'ai bien un résultat. 

Exemples **Screenshots**
![image](https://user-images.githubusercontent.com/48682104/67553392-59847800-f70d-11e9-8611-326631e2fcf9.png)
![image](https://user-images.githubusercontent.com/48682104/67553428-702acf00-f70d-11e9-8cb6-f016b58cc56a.png)

Existe-t-il un moyen de "neutraliser" les espaces afin que le moteur de recherche puisse obtenir un résultat que l'on écrive dans le moteur 821 980 877 00020 ou 82198087700020 ?

**Comment by UnbearableBear** [comment]
Ca ne doit pas etre bien compliqué à faire ça !

**Comment by lionelB** [comment]
je vais rajouter ca,  je suis dessus le widget

**Comment by UnbearableBear** [comment]
Juste attention à ne pas trimmer tout le temps mais uniquement lorsque le trim donne un résultat positif pour le siret ou lorsqu'il n'y a que des chiffres

**Comment by virginielastisneres** [comment]
@UnbearableBear @lionelB  Merciii :)
