### ISSUE TITLE
Bug report : recherche prime de précarité

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#1564]
**Contexte**

Quand je tape prime de précarité dans le moteur de recherche voilà ce qui apparaît :

![image](https://user-images.githubusercontent.com/48682104/67561307-dcf99580-f71c-11e9-9ab1-e81b3cce0ec5.png)

La première réponse est parfaite. Pour la deuxième le lien externe est une erreur j'ai rectifié le datafiller. 

**BUG**

**Pour la troisième réponse je comprends pas pourquoi nous avons "Icône réponse".**

**Comment by UnbearableBear** [comment]
Magique ce bug 😂

**Comment by lionelB** [comment]
ca vient des données du datafiller aussi
donnée ES 
http://api.master.code-du-travail-numerique.dev.factory.social.gouv.fr/api/v1/search/?q=prime%20pr%C3%A9carit%C3%A9&skipSavedResults
vs
donnée datafiller
http://api.master.code-du-travail-numerique.dev.factory.social.gouv.fr/api/v1/search/?q=prime%20pr%C3%A9carit%C3%A9

**Comment by virginielastisneres** [comment]
Du coup je dois faire quelque chose au niveau du datafiller pour corriger cela ?

**Comment by ClementChapalain** [comment]
fixé sur master et en prod
