### ISSUE TITLE
[SEO] Réaliser un sitemap pour faciliter l'exploration par les bots

### ISSUE THREAD

**Issue by Abdessamadyssf** [SocialGouv/code-du-travail-numerique#1569]
Réaliser un sitemap (dynamique) pour faciliter l'exploration par les bots.

Les pages à indiquer dans le sitemap : 

- thème
- modèle de courrier
- Fiche Service public
- Fiche Ministère du travail
- Outils
- Contribution

@lionelB

**Comment by ClementChapalain** [comment]
notre sitemap aujourd'hui : https://codedutravail.num.social.gouv.fr/sitemap.xml

Google nous indique qu'il contient beaucoup d'erreurs : 
![image](https://user-images.githubusercontent.com/5337489/68293228-d4467f00-008d-11ea-8f01-5c9f52b08c91.png)
https://search.google.com/search-console/sitemaps/info-drilldown?resource_id=https%3A%2F%2Fcodedutravail.num.social.gouv.fr%2F&sitemap=https%3A%2F%2Fcodedutravail.num.social.gouv.fr%2Fsitemap.xml&hl=en-GB

**Comment by ClementChapalain** [comment]
\+ @lionelB pour info

**Comment by lionelB** [comment]
localhost:3000 T_T mais naaan

**Comment by ClementChapalain** [comment]
Pour info ce serait vraiment bien de le faire rapidement, car google galere à explorer toutes les pages de code.travail.gouv.fr sinon j'ai l'impression. Je suis dispo si besoin de plus d'informations, ou pour en discuter si c'est trop long à faire.

**Comment by lionelB** [comment]
@ClementChapalain pas spécialement long :) je m'en occupe

**Comment by ClementChapalain** [comment]
merci beaucoup !

**Comment by UnbearableBear** [comment]
Ca va beaucoup changer avec le refacto des url, ne pas oublier de le mettre à jour après

**Comment by lionelB** [comment]
@manu_c dans l'idée, je pensais builder le sitemap.xml sur la ci est l'intégrer à l'image frontend en me basant sur la commande dump

**Comment by UnbearableBear** [comment]
Du coup le sitemap sera à l'image de la data (si je ne dis pas de bêtise) mais est-ce que ça refletera bien le "plan du site" tel que google l'attend probablement ? On ne devrait pas faire quelque chose de basé sur le dossier `pages`du front plutôt ?

**Comment by lionelB** [comment]
dans l'idée on build ca depuis le container front, et normalement à partir de data + les pages on a tout

**Comment by ClementChapalain** [comment]
merci !
