### ISSUE TITLE
Page en cas de non-disponibilité du simulateur d'embauche

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1576]
si le simulateur d'embauche n'est pas disponible afficher le message :
> Cet outil n'est pas disponible actuellement, veuillez-nous excuser pour la gêne occasionée.
> [Retrouvez nos réponses liées au salaire et à la rémunération](https://codedutravail.num.social.gouv.fr/themes/2-salaire-et-remuneration)

**Comment by lionelB** [comment]
+ gestion des cookie tiers

**Comment by ClementChapalain** [comment]
je viens de voir la page, on gagnerait à avoir un spinner quand le simulateur n'est pas encore visible aussi, sinon on a un peu l'impression que la page est vide pendant quelques secondes
