### ISSUE TITLE
Canonical urls

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1589]
aujourd'hui c'est une url au hasard qui est définie comme canonical par google et donc référencée sur le moteur de recherche

exemple avec la recherche : 
"code du travail numérique fiche service public paiement du salaire"

qui renvoit vers l'url https://code-du-travail.beta.gouv.fr/fiche-service-public/paiement-du-salaire?q=Astreintes alors qu'elle devrait renvoyer vers https://code-du-travail.beta.gouv.fr/fiche-service-public/paiement-du-salaire sans le paramètre de recherche

**Comment by Abdessamadyssf** [comment]
De la doc pour vous aider : https://support.google.com/webmasters/answer/139066?hl=fr

**Comment by ClementChapalain** [comment]
il y a 3 solutions a priori : 
- balise link rel = canonical dans l'en-tête (https://support.google.com/webmasters/answer/139066?hl=fr)
- sitemap (https://support.google.com/webmasters/answer/139066?hl=fr)
- bloquer l'indexation des urls avec paramètre de recherche (https://support.google.com/webmasters/answer/6080548?visit_id=637085475243056063-4210703339&rd=1)

pour la 3e je peux le faire tout seul dans les webmaster tools de google, il me propose de ne pas indexer les urls avec ces différents paramètres : 
![image](https://user-images.githubusercontent.com/5337489/68204165-b282c480-ffc7-11e9-9895-22a1dc05b636.png)

pour le sitemap il y a ce ticket là déjà #1569

**Comment by ClementChapalain** [comment]
j'ai activé la desindexation des urls avec le param `q`

**Comment by ClementChapalain** [comment]
du coup je close cette tâche mais j'ai ajouté la tâche sur le sitemap à ajouter, j'ai l'impression que c'est assez important pour le référencement d'avoir un sitemap bien fait et à jour
