### ISSUE TITLE
Outil Indemnité de licenciement: mise à jours des cas d'absences déductibles de plus d'un mois.

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1602]
### Absences de plus d'un mois ( Indemnité légale)

![image](https://user-images.githubusercontent.com/37538697/67937892-b03af780-fbce-11e9-90fe-5d3e2e031ddb.png)

Retirer de la liste déroulante:
congé de solidarité familiale
 (L3142-12
 https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000033021983&cidTexte=LEGITEXT000006072050&dateTexte=20160810)
explication: "La durée de ce congé ne peut être imputée sur celle du congé payé annuel.**Elle est prise en compte pour la détermination des avantages liés à l'ancienneté**."

congé de solidarité internationale
(L3142-68
 https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000033021810&cidTexte=LEGITEXT000006072050)
explication: "Elle est prise en compte pour la détermination des avantages liés à l'ancienneté."

conge de proche aidant :
 L3142-1 https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=880444C21B78BA5A7A4E01C35FBAD283.tplgfr38s_2?idArticle=LEGIARTI000033022052&cidTexte=LEGITEXT000006072050&dateTexte=20191031
 explication: "Elle est prise en compte pour la détermination des avantages liés à l'ancienneté"

Ajouter 
la maladie d'origine non professionnelle
le congé de paternité

(explication: "C’est le cas des suspensions liées à des arrêts maladie d’origine non professionnelle, au congé de paternité, au congé sabbatique. Ces différentes absences ne sont normalement pas comptabilisées dans le calcul de l’ancienneté. Il en est de même pour l’absence liée à un accident de trajet (Code du travail, art. L. 1226-7)".

**Comment by jrduscher** [comment]
Aujourd'hui, les cas signalés ne sont pas réglés: pour les cas qui ne sont pas à déduire le wording a été changé, mais ils sont également dans la liste des cas déductibles:
![image](https://user-images.githubusercontent.com/37538697/71622084-ca478500-2bd3-11ea-8c67-f97009c255e6.png)

## 1) Retirer du menu déroulant:
- [ ]   le congé de solidarité international
- [ ] le congé de proche aidant
- [ ]  le congé de solidarité familiale
## 2) Ajouter dans le menu déroulant
 - [ ] maladie d'origine non professionnelle
 - [ ] congé de paternité

## 3) Effectuer un changement du wording 

concernant les exclusions pour ajouté le congé de proche aidant:
Remplacer le wording existant:

"Les congés payés, le congé de maternité ou d'adoption, le congé de présence parental ,l'arrêt de travail lié à un accident du travail ou une maladie professionnelle, le congé individuel de formation (CIF), le congé de solidarité internationale, le congé de solidarité familiale et le stage de fin d'étude de plus de 2 mois sont déjà prises en compte dans l'ancienneté et ne sont pas des périodes à renseigner ci-après :"

par:

"Les congés payés, le congé de maternité ou d'adoption, le congé de présence parental ,l'arrêt de travail lié à un accident du travail ou une maladie professionnelle, le congé individuel de formation (CIF), le congé de solidarité internationale, le congé de solidarité familiale, le congé de proche aidant et le stage de fin d'étude de plus de 2 mois sont déjà prises en compte dans l'ancienneté et ne sont pas des périodes à renseigner ci-après :"

**Comment by revolunet** [comment]
ca a l'air d'être corrigé sur master ? https://master-code-travail.dev.fabrique.social.gouv.fr/outils/indemnite-licenciement

**Comment by lionelB** [comment]
c'est ma faute, pardon, cela a était fait dans la PR #2288 et j'avais oublié de référéncer l'issue
