### ISSUE TITLE
Amélioration Outil indemnité de précarité

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#1605]
### **Je suis dans la convention collective des bureaux techniques IDCC 1486.** 

A la question : "À la fin de votre CDD, vous a-t-on proposé un CDI ?" J'ai une liste déroulante pour répondre oui ou non. 
![RYK](https://user-images.githubusercontent.com/48682104/67940587-47567e00-fbd4-11e9-8a7d-0f1f6491367a.png)

Par souci de cohérence, serait-il possible d'avoir à la place d'une liste déroulante des **boutons radios** comme pour les autres questions qui appellent comme réponse "oui" ou "non". 
![image](https://user-images.githubusercontent.com/48682104/67940790-a2887080-fbd4-11e9-912f-17c2244e5371.png)

**Comment by virginielastisneres** [comment]
Même problème concernant la **CC Organismes de formation IDCC 1516**, à la question "À la fin de votre CDD, avez-vous été immédiatement embauché en CDI ?"
![de](https://user-images.githubusercontent.com/48682104/67941731-969dae00-fbd6-11e9-95fe-577adb967331.png)

**Comment by virginielastisneres** [comment]
Même problème concernant la **CC Sport IDCC 2511**, à la question "À la fin de votre CDD, avez-vous été immédiatement embauché en CDI ?"
![fr](https://user-images.githubusercontent.com/48682104/67942241-b84b6500-fbd7-11e9-8841-d20712f07c93.png)

**Comment by virginielastisneres** [comment]
idem concernant la **CC Services à la personne IDCC 3127**, à la question "À la fin de votre CDD, avez-vous été immédiatement embauché en CDI, sans interruption, sur un même poste ou sur un poste différent ?"
![fez](https://user-images.githubusercontent.com/48682104/67942535-56d7c600-fbd8-11e9-9b83-9e8da80091cc.png)

**Comment by m-maillot** [comment]
Aujourd'hui, nous n'avons plus de liste déroulante pour oui-non dans les outils.
