### ISSUE TITLE
Impression des pages de résultats des outils

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1618]
Sur tous les outils, il faudrait ajouter un bouton imprimer pour pouvoir imprimer simplement les résultats de la simulation.

Je propose de remplacer le bouton "recommencer une simulation" par un bouton "imprimer le résultat" en terme d'UI. En effet le bouton précédent permet déjà de revenir sur ses pas et de modifier les réponses que l'on a données. Et le cas de recommencer une simulation est en réalité plus un cas de démo ou de test qu'un réel cas usager qui va le plus souvent ne faire qu'une seule simulation avec sa situation.

Fonctionnellement :
- ce bouton imprime uniquement le dernier écran de l'outil et pas le reste de la page
- élément à faire figurer impérativement en plus du dernier écran : 
  - Code du travail numérique
  - l'url de la page
  - la date + heure
- les calculs situés dans des accordéons "détail du calcul" doivent être déroulés.

**Comment by ClementChapalain** [comment]
Autre possibilité évoquée durant le planning : avoir une bouton "exporter" et non "imprimer" qui créerait un PDF que l'usager pourrait ensuite imprimer.

De mon point de vue les deux sont ok, faisons le plus simple techniquement :)

**Comment by UnbearableBear** [comment]
Recap du RAF (reste à faire):

- Masquer tous les boutons et les champs de formulaires lors du print (à rajouter dans l'UI)
- Masquer la search
- Récupérer tous les `<summary>` dans "#main" qui n'ont pas l'attribut open et faire un `.click()` dessus pour les ouvrir.
- `window.print()`

**Comment by lionelB** [comment]
il existe un prop pour ouvrir / fermer les summary
```html 
<details open>...</details>
```

**Comment by nkrmr** [comment]
Il existe une lib pour imprimer des composants React :  https://github.com/gregnb/react-to-print#readme
Avec une démo super light ici : https://codesandbox.io/s/rzdhd

A tester mais ça a l'air pas mal

**Comment by nkrmr** [comment]
![Screenshot 2019-11-26 at 17 37 29](https://user-images.githubusercontent.com/686395/69655064-1acc3f80-1076-11ea-81cb-ec9b81cfc53b.png)
[Calculer une indemnité de licenciement (2).pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/3893057/Calculer.une.indemnite.de.licenciement.2.pdf)

**Comment by jrduscher** [comment]
Où est passé le bouton recommencer une simulation? @nkrmr cf @virginielastisneres

**Comment by nkrmr** [comment]
La demande était de le remplacer par l'impression car on peut cliquer sur le menu de gauche pour recommencer le process

**Comment by nkrmr** [comment]
cf: #1816

**Comment by virginielastisneres** [comment]
Dommage que l'on ne l'ait pas traité comme le téléchargement dans les modèles de courrier via un picto d'impression.

**Comment by nkrmr** [comment]
On peut toujours télécharger dans la fenêtre de print cela fait un export en PDF

**Comment by virginielastisneres** [comment]
Oui oui je parlais plutôt du traitement de la fonction "imprimer" via un picto comme cela
![image](https://user-images.githubusercontent.com/48682104/69742708-7f9e9d00-113d-11ea-9cf4-25393cb5fa59.png)

**Comment by nkrmr** [comment]
Ah ok c'est toujours faisable surtout si l'on doit remettre le bouton pour recommencer le parcours. 
À valider avec @ClementChapalain

**Comment by ClementChapalain** [comment]
Hello, on a essayé d'aller au plus simple en ne changeant pas l'UI et sans rajouter une troisième action sur la page. De mon point de vue recommencer une simulation n'est pas une action principale comme je l'expliquais dans la description de la tache : 
> Je propose de remplacer le bouton "recommencer une simulation" par un bouton "imprimer le résultat" en terme d'UI. En effet le bouton précédent permet déjà de revenir sur ses pas et de modifier les réponses que l'on a données. Et le cas de recommencer une simulation est en réalité plus un cas de démo ou de test qu'un réel cas usager qui va le plus souvent ne faire qu'une seule simulation avec sa situation.

Si on nous réclame cette possibilité on trouvera un moyen de le remettre :)

**Comment by virginielastisneres** [comment]
Je ne parle pas forcément du bouton recommencer en tant que tel mais plutôt du traitement de la fonctionnalité "impression" qui est différent de la fonctionnalité télécharger que l'on a sur les courriers via picto et également du fait qu'il n'y ait que cette option et qu'il n'y a pas l'option télécharger ou envoi par mail. 
Personnellement je n'imprime pas quand je suis sur mobile mais bon comme tu dis on verra les usages en effet.

**Comment by ClementChapalain** [comment]
OK je comprends. Après je pense qu'il faut différencier le téléchargement de l'impression. Dans les modèles de courriers on télécharge car il y a forcément une modif à apporter au modèle par l'utilisateur. Dans les simulateurs on imprime car c'est pour un usage direct.

Mais je suis d'accord que sur mobile le wording "imprimer" n'est pas très cool, car personne n'imprime à partir de son mobile (mais quand je clique dessus sur mon mobile, je tombe sur une interface qui me télécharge le fichier). Je suis d'accord sur le fait que sur mobile l'usage est plutôt de s'envoyer le résultat, c'est une fonctionnalité qu'on pourra ajouter par la suite (idem pour les modèles de courrier d'ailleurs).
