### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1619]
## Figma

https://www.figma.com/file/oph7JpLS74NJAiGbzyit95/CDTN-UI-BlueFinal

### Week 1 - Nov 18th

- [x] Couleurs
- [x] Effets
- [x] Pictos monochromes
- [x] Typos
  - [x] Titres
  - [x] Contenus
  - [x] Liens
  - [x] Spécifiques
- [x] Boutons

### Week 2 - Nov 25th

- [x] Headers
- [x] Picto utilitaires
- [x] Footer

### Week 3 - Dec 2nd

- [x] Cartes
- [x] Composants de bas de page
- [x] Personnalisation
- [x] Liste de liens
- [x] Liste de thèmes

### Week 4 - Dec 9th

Pages

**Comment by lionelB** [comment]
pic or it didn't happen

**Comment by ClementChapalain** [comment]
petite update de la part de Cécile : 
- on aura d'ici la semaine prochaine les versions mobiles (+ desktop) de la HP et de la page de contenu
- elle va également nous partager sous peu le fichier Figma avec la bibliothèque de composants créés

**Comment by UnbearableBear** [comment]
Et le set d'icones / couleurs ? Avec ça j'aurais largement de quoi commencer à travailler

**Comment by ClementChapalain** [comment]
pour les icônes pas sur qu'on les ait, elle bossera plutôt dessus à la fin de sa mission quand le reste sera validé. en attendant on mettra des placeholders si c'est ok pour toi. les couleurs seront dans le figma.

**Comment by ClementChapalain** [comment]
fermer pour #1995

**Comment by lionelB** [comment]
<img src=https://media.giphy.com/media/GStLeae4F7VIs/giphy-downsized.gif width=693>
