### ISSUE TITLE
Move new suggestor to production

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1623]
cf. #1549

**Comment by rmelisson** [comment]
Nous sommes en train de faire des changements sur le suggesteur, en vrac :

- Gestion de l’accentuation
- Fuzzy matching (fautes de frappe)
- Utilisation d’une pondération pour ordonner les résultats
- Cleaning des suggestions (déduplication, verification orthographique…)
- Infix suggestions (quand une suggestion match “au milieu”: ‘demi’ -> préavis demission)

Quelques limitations connues :
- Il reste des suggestions erronées (voir #1631 )
- L’ordre est assez naif pour le moment, il devrait bonifier avec le temps (grace aux logs)

**Comment by rmelisson** [comment]
Pour tester :
http://357c8ff.code-du-travail-numerique.dev.factory.social.gouv.fr/

**Comment by ClementChapalain** [comment]
c'est top ! quelques suggestions qui ne paraissent pas pertinentes / avec des fautes : 
- coiffeuse 76000
- 1 mois apres l'entretient disciplinaire-licenciment

**Comment by mhavel** [comment]
![image](https://user-images.githubusercontent.com/2303918/68215396-76f3f480-ffdf-11e9-91cb-8dfe63f0b358.png)

"belgique", "une personne" : pas top.

Mais sinon c'est rapide, très souvent pertinent et varié. Excellent

**Comment by rmelisson** [comment]
Je pense que domicile Belgique fait sens pour les personnes résidant en Belgique et travaillant en France.
Après ça concerne la liste initiale, on va corriger ça indépendamment :  #1631

**Comment by virginielastisneres** [comment]
Je n'ai pas le même résultat que je tape : 
- licencement
- licencment
- ou licenciement

**Comment by virginielastisneres** [comment]
![image](https://user-images.githubusercontent.com/48682104/68217121-58dbc380-ffe2-11e9-8600-a5a5ddde9d0c.png)
suggestion pas très pertinente

**Comment by virginielastisneres** [comment]
bizarre ahah
![image](https://user-images.githubusercontent.com/48682104/68217310-ae17d500-ffe2-11e9-9d17-69945b8d0a1d.png)

J'en profite pour vous demander s'il est possible de faire correspondre syntec à la convention collective des bureaux techniques ? :)

**Comment by lionelB** [comment]
> J'en profite pour vous demander s'il est possible de faire correspondre syntec à la convention collective des bureaux techniques ? :)

a voir si on introduit la gestion de synonyme

**Comment by virginielastisneres** [comment]
mise a pide ne donne pas la même chose que mise à pied

**Comment by virginielastisneres** [comment]
suggestion de mots avec des fautes d'orthographe
![j](https://user-images.githubusercontent.com/48682104/68219883-04871280-ffe7-11e9-9613-27896e65904e.png)

**Comment by rmelisson** [comment]
@virginielastisneres  merci pour les retours :
- pour le cas des suggestions différentes entre les requêtes avec ou sans faute, c'est normal car l'entrée est différente, licencment == licenciement pour toi, mais le suggester cherche tous les parcours "à distance de faute", par exemple _licence_, donc c'est normal de ne pas avoir _exactement_ la même réponse
- aussi, il faut prendre en compte le 'parcours' de requête, car les suggestions sont présentées au fur et à mesure (dans l'exemple licenciement, les suggestions sont cohérentes pour les 10 premiers caractères) 
- en qui concerne les suggestions erronées (fautes, truc bizarres...), ça sera traité dans #1631 mais on va déjà enlever ce qui a été remonté ici
- enfin pour ce qui est des synonymes, et plus généralement l'_interpretation_ des requêtes (genre mapping query => question en language naturel ou query => synonymes...), je crée un nouveau ticket  #1641 pour garder ça en tête, mais c'est pas dans le scope de cette update

**Comment by virginielastisneres** [comment]
super merci @rmelisson :)

**Comment by lionelB** [comment]
@ClementChapalain  on peut fermer puisque la PR #1549 à été mergé ?

**Comment by ClementChapalain** [comment]
oui !
