### ISSUE TITLE
Logs de navigation dans Matomo

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1624]
Y a-t-il toutes les informations nécessaires dans les logs des visites de matomo ?

**Comment by ArmandGiraud** [comment]
# Informations Importantes à collecter:
 
## Suggestion Logs:
Quels évènements à collecter sur les parcours utilisateur.
- [x] collecter un ou plusieurs prefix ayant généré des suggestions. (ex: dem - demi -démiss)
- [x] possibilité de logger les candidats 
- [ ] trouver un mapping la requête sélectionnée (ou non) parmi ces candidats

## Search Logs: 
- [x] search query en (text).
- [x] possibilité de logger les candidats 

selection parmi les candidats.
- [x] logger la pages liste de résultats?
- [ ] que se passe-t-il avant la sélection?
- [x] que se passe-t'il après la selection? (lien externe, retour home, close tab)
- [x] logger les retours utilisateur vers la liste de résultat?
- [ ] évenement explicit feeedback. 
- [ ] nouvelle recherche 

L'objectif est un format par requête "plat" suivant:

_filter | candidates_flat | iscandidate | keyword | next_url | secondSpent | sessionId | prefix | suggestions
 | -- | -- | -- | -- | -- | -- | -- | -- | -- |
None | [/fiche-service-public/medecine-du-travail, /f... | True | FDS médecin du travail | /fiche-ministere-travail/acd-methodes-et-outil... | 8.0 | 48788.0| FDS | None |
None | [/fiche-service-public/medecine-du-travail, /f... | True | FDS médecin du travail | /code-du-travail/r4513-10 | 24.0 | 48788.0| FDS | None |
None | [/fiche-ministere-travail/cet-de-quoi-sagit-il... | True | Cse | /fiche-ministere-travail/cse-quelles-sont-les-... | 27.0 | 48757.0| cse | [cse, cse préfinancé, ...] |
None | [/fiche-ministere-travail/cet-de-quoi-sagit-il... | True | Cse | /fiche-ministere-travail/cse-quel-est-le-proce... | 60.0 | 48757.0| None | None |
None | [/fiche-service-public/quelle-peut-etre-la-dur... | True  | 1580.0 | 48737|  durée | [durée travail, durée cdd, ...] |

- sessionId: Un identifiant de session. 
- _filter: les filtres éventuels appliqués à la recherche.
- candidates_flat: une liste des contenus proposés à l'utilisateur avec leurs sources (fiche sp, recherche sémantique)
- keyword: la query search tapée par l'utilisateur
- l'heure de la query search
- next_url: l'url suivant la recherche 
- secondSpent: le temps passé sur l'url suivant

---
- next_url_out: l'évènement suivant l'url suivant (sortie par un lien externe, retour aux résultats...)
- suggestion: suggestions 
- prefix

**Comment by lionelB** [comment]
@ArmandGiraud est ce que tu peux jeter un oeil et (dé)cocher les cases qui te paraissent ok, j'avais un doute sur certaines.
