### ISSUE TITLE
Log consolidation : JS script to transfer Matomo content to Elastic

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1625]

**Comment by rmelisson** [comment]
During the day, user logs are saved into Matomo automatically : #1624 
We then need to consolidate and store them into a specific Elastic instance.
It will require us to "redo" the ES request that were originally done by the user.
We propose to do that in JS, as a cron job.
On the long term, we'll need to ensure this ES logging instance is backed properly.

**Comment by revolunet** [comment]
there is a logstash plugin that could poll visitors log and push it to ES : https://www.elastic.co/guide/en/logstash/7.4/plugins-inputs-http_poller.html

**Comment by lionelB** [comment]
@rmelisson to avoid redoing the request we need to investigate a way to send to matomo the results source+slug when a site search is performed
same for the suggestion, we could try to send the suggest list  to matamo

**Comment by ArmandGiraud** [comment]
> This Logstash input plugin allows you to call an HTTP API, decode the output of it into event(s), and send them on their merry way. The idea behind this plugins came from a need to read springboot metrics endpoint, instead of configuring jmx to monitor my java application memory/gc/ etc.

Not sure what this functionality is doing 🤔

**Comment by rmelisson** [comment]
Logstash en place : 
https://github.com/SocialGouv/cdtn-elk
