### ISSUE TITLE
Analyse logs suggestions

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1626]

**Comment by ArmandGiraud** [comment]
Création d'un pipeline d'update des suggestions possibles grâce aux logs d'utilisation:

- depuis le fichier actuel. (insérer les titres de fiches)
- deduplication/spell-check
- call elastic pour éliminer les recherches sans résultats
- mise à jour des weights & nouvelle entrée si ça n'existe pas
- écrire quelques stats (nouvelles entrées) + url nouveau fichier.
- pousser le nouveau ficher sur azure Blob.
- updater la variable d'environment du SUGGEST_URL.

**Comment by rmelisson** [comment]
Publier métriques d'utilisation du suggester.
