### ISSUE TITLE
Convention collectives (cas particuliers)

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#164]
1)**Dans le volet: que faire quand une entreprise applique plusieurs conventions collectives ?**
( c'est marginal) et c'est le cas quand une distinction est possible dans les activités de l'entreprise au reagrd de sa structure ( deux établissements différents dans une entreprise avec des activités dissoiciées): Proposer une convention collective au regard d'un des IDCC, et surtout permettre au salarié de chercher la convention collective qui lui est applicable

2) l'entreprise n'applique pas de covention collective ( l'entrepris relève du droit commun)
 -  proposer autre
- on peut également préciser le tir en constituant une base des activités releavnt du droit commun( (donc code du travail " dispositions supplétives " quand elles sont précisées et, et accord d'entreprises)

3) **Etre certain de proposer la bonne convention collective à l'usager**
la proposition SIRET-IDCC-CCN doit rester indicative. L'information doit appariatre comme une siggestion à l'utilisateur, qui doit pouvoir faiclemnt corriger le tir de lui même. (même si nos infos seront fiables, il faudra laisser cette ouverte

**Comment by ClementChapalain** [comment]
pas actionnable, repris dans le wiki des outils ici : https://github.com/SocialGouv/code-du-travail-numerique/wiki/%5BOutil%5D-%5BRecherche-CCN%5D%C2%A0Cas
