### ISSUE TITLE
Nouvelle UI pour le contact des SR

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1652]
# Footer

## Titre 

Besoin de plus d'informations ?

## Wording bouton

Contacter nos services en région

## Wording description sous le bouton

Les services du ministère du Travail en région informent, conseillent et orientent les salariés et les employeurs du secteur privé sur leurs questions en droit du travail.

# Modale

### Titre

Contact téléphonique

### Numéro

0 806 000 126 Service gratuit + prix appel

Voir la partie "Service gratuit + prix appel" dans la charte : 
[201805_Charte-Graphique-_Signaletique-SVA.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/3912203/201805_Charte-Graphique-_Signaletique-SVA.pdf)

### Titre

Coordonnées du service de votre département

### Texte

Saisissez votre numéro de département :

placeholder du champ : `ex. 31, 35, 75`

Attention, ces services délivrent une information juridique, ils ne sont pas compétents pour :
- les demandes d'intervention en entreprise
- le règlement des litiges et la constitution des dossiers prud'homaux
- les calculs de droit au chômage
- vous renseigner sur les cotisations sociales

### Virer le jaune fluo sur le lien :)

![image](https://user-images.githubusercontent.com/5337489/69977124-7b51f580-152a-11ea-9496-e60bed5a48a2.png)

**Comment by virginielastisneres** [comment]
@jrduscher Il me semblait que l'on changeait "Besoin d'un accompagnement personnalisé ?" non ? 

Je me rappelle plus qu'est ce qui est obligatoire d'indiquer ?
"Les services du ministère du Travail en région peuvent vous donner des informations juridiques générales relatives au Code du travail, aux conventions collectives, à la jurisprudence. Ils peuvent également vous conseiller et vous orienter dans vos démarches."
et/ou 
"Attention, ces services délivrent une information juridique, ils ne sont pas compétents pour :
les demandes d'intervention en entreprise
le règlement des litiges et la constitution des dossiers prud'homaux
les calculs de droit au chômage
vous renseigner sur les cotisations sociales"

**Comment by ClementChapalain** [comment]
@virginielastisneres ok c'est édité dans la description !

**Comment by ClementChapalain** [comment]
fermé pour #1995
