### ISSUE TITLE
[search]: show description for contributions results too

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#1665]
Dans la liste des résultats de recherche, ajouter le début de la réponse (qui doit se trouver dans `_source.answers.generic.markdown`)

<img width="736" alt="Capture d’écran 2019-11-07 à 18 24 50" src="https://user-images.githubusercontent.com/124937/68412086-ee668700-018b-11ea-82bc-d46b7c240b5f.png">

**Comment by lionelB** [comment]
on pourrait remplir le champ description, utilisée aussi pour le meta description de la page.

**Comment by UnbearableBear** [comment]
Il faudrait même, dans les resultats de recherche c'est lui et exclusivement lui pour le moment qui est utilisé à cette fin !
