### ISSUE TITLE
Les modèles de courrier se proposent eux-mêmes en contenu annexe

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1672]
https://code.travail.gouv.fr/modeles-de-courriers/modele-demande-de-paiement-de-salaire

![image](https://user-images.githubusercontent.com/5337489/68485176-14992f00-023f-11ea-8ab4-9924a74d3900.png)

**Comment by lionelB** [comment]
should  fixed by #1671 http://08e1bff.code-du-travail-numerique.dev.factory.social.gouv.fr/modeles-de-courriers/modele-demande-de-paiement-de-salaire

**Comment by ClementChapalain** [comment]
👍

**Comment by ClementChapalain** [comment]
is not fixed :) d'ailleurs aujourd'hui on propose uniquement le modèle qui est en train d'être vu et rien d'autre

**Comment by UnbearableBear** [comment]
Je prends !

**Comment by UnbearableBear** [comment]
fixed

**Comment by lionelB** [comment]
par quelle PR ?

**Comment by UnbearableBear** [comment]
Ici https://github.com/SocialGouv/code-du-travail-numerique/pull/1867/files#diff-5e4ed9cb0ab57216a2de02327b83854aR45
Et là https://github.com/SocialGouv/code-du-travail-numerique/pull/1867/files#diff-5e4ed9cb0ab57216a2de02327b83854aL101

**Comment by lionelB** [comment]
ah ca devrait etre fait coté api normalement...

**Comment by UnbearableBear** [comment]
Il semblerait que c'était fait côté front mais pas complètement, j'ai juste corrigé la partie front mais si tu veux creuser côté back n'hésite pas !
Il y a une issue concernant les outils qui remontent pas, y a surement moyen de faire d'une pierre deux coups

**Comment by revolunet** [comment]
Du coup je fais une issue pour ne pas oublier de régler le problème à la source dans l'API : #1874

**Comment by revolunet** [comment]
Si possible 1 issue = 1 PR 🙏

**Comment by UnbearableBear** [comment]
@ClementChapalain  Du coup je revert les modifs front et on attend la modif côté back !
