### ISSUE TITLE
Proposition d'articles connexes : une page ne marche pas

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1687]
Pour reproduire, aller sur https://code.travail.gouv.fr/fiche-service-public/rupture-conventionnelle-dun-cdi et cliquer sur le premier article proposée dans la colonne de droite (Rupture conventionnelle d'un CDI) : 
![image](https://user-images.githubusercontent.com/5337489/68676373-3144a800-055a-11ea-8917-78e35864b0c0.png)

Autre cas référencé par @virginielastisneres : 
https://code.travail.gouv.fr/fiche-service-public/indemnite-compensatrice-de-conges-payes

Aussi, dans ce cas (widget non disponible) le back navigateur est cassé : l'url change mais pas le contenu de la page

**Comment by UnbearableBear** [comment]
Humm le bug bien obscure, je prends.

**Comment by ClementChapalain** [comment]
sprint 30 @UnbearableBear il reste d'autres trucs dans le 29 :)

**Comment by virginielastisneres** [comment]
j'ai eu pareil sur celui ci --> cliquer sur le contenu proposé appelé "congés payés" https://code.travail.gouv.fr/fiche-service-public/indemnite-compensatrice-de-conges-payes?q=indemnit%C3%A9%20compensatrice%20de%20cong%C3%A9s%20pay%C3%A9s

**Comment by virginielastisneres** [comment]
hum hum... j'ai trouvé un truc en commun sur les deux contenus qui ne fonctionnent pas... 
Les fiches SP ne sont pas à jour sur notre site... 
- http://master.code-du-travail-numerique.dev.factory.social.gouv.fr/fiche-service-public/conges-payes?q=cong%C3%A9s%20pay%C3%A9s 
- https://www.service-public.fr/particuliers/vosdroits/F2258
- https://code.travail.gouv.fr/fiche-service-public/rupture-conventionnelle-dun-cdi
- https://www.service-public.fr/professionnels-entreprises/vosdroits/F19030

**Comment by ClementChapalain** [comment]
nouveau cas : https://code.travail.gouv.fr/fiche-service-public/un-salarie-peut-il-refuser-de-travailler-dans-une-situation-dangereuse et cliquer sur le  premier lien `Un salarié peut-il être licencié à cause du retrait de son permis de conduire ?`

edit : les deuxième et troisième lien ne fonctionnent pas non plus sur ce contenu

**Comment by nkrmr** [comment]
Ok je m'en occupe

**Comment by UnbearableBear** [comment]
Hint: Si on désactive le glossaire, le lien marche à nouveau. Donc il y a probablement un conflit entre les fiches SP (et le package `react-fiche-service-public`) et le glossaire

**Comment by ClementChapalain** [comment]
hello ! @nkrmr tu as des news sur le sujet ? il faut absolument qu'on refasse le glossaire ou on peut trouver un autre fix sans changer l'implémentation actuelle du glossaire ?

**Comment by nkrmr** [comment]
@ClementChapalain je suis sur une solution je reviens vers toi rapidement et je te dis ça

**Comment by virginielastisneres** [comment]
@nkrmr tu en es où au niveau de la solution ?

**Comment by nkrmr** [comment]
@virginielastisneres Je suis dessus en ce moment je reviens vers toi rapidement

**Comment by nkrmr** [comment]
@virginielastisneres @ClementChapalain Le fixe est en PR j'attends qu'il soit validé.
