### ISSUE TITLE
Simulateurs : ouvrir les sources dans un nouvel onglet

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1688]
Les sources renvoient vers legifrance le plus souvent, il est donc plus logique de les ouvrir dans un nouvel onglet.

![image](https://user-images.githubusercontent.com/5337489/68676629-bd56cf80-055a-11ea-9c35-5d20ef9ac5cf.png)

**Comment by UnbearableBear** [comment]
Je suis d'accord parce que sinon il risque de perdre son résultat mais je serais plutôt d'avis de faire en sorte qu'on garde le resultat dans la sessions ou quelque chose dans le genre plutôt que d'ouvrir tous les liens dans un nouvel onglet. Ne serait-ce que sur mobile, ça peut-être assez contraignant d'avoir plusieurs onglets ouvert plutôt que de juste cliquer puis de faire retour

**Comment by lionelB** [comment]
@UnbearableBear je propose qu'on ouvre en nouvelle page, tant qu'on a pas gérer la persistance / back navigateur
