### ISSUE TITLE
Thémer les fiches MT unifiées

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1690]
## sprint 29

- [x] ajouter un espace avant les 2 points dans les résultats de recherche
![image](https://user-images.githubusercontent.com/5337489/68687507-93f36f00-056d-11ea-86ed-ebd96ac0617e.png)

- [x] ajouter les contenus recommandés sur la colonne de droite

## sprint 30

- [ ] thémer les fiches unifiées (en attente d'une amélioration du data filler par @revolunet)

**Comment by ClementChapalain** [comment]
ce qu'il faut faire pour le data-filler : 
https://github.com/SocialGouv/code-du-travail-numerique/issues/1394#issuecomment-554279411

**Comment by ClementChapalain** [comment]
suite à notre discussion : 
- [x] faire en sorte que thémer 1 sous-doc MT = thémer tous les sous-docs MT
- [x] reset les thèmes de toutes les fiches MT
- [x] passer par la partie contenus à thémer pour re-thémer toutes les fiches MT
- [x] faire une passe sur les thèmes via la partie thèmes pour s'assurer du tri et de la cohérence des thèmes

ping @revolunet @jrduscher @virginielastisneres

**Comment by UnbearableBear** [comment]
@nkrmr tu devrais suivre ça de près avant de faire la mise à jour des fiches !

**Comment by jrduscher** [comment]
+1

**Comment by ClementChapalain** [comment]
c'est fini ça du coup ?

**Comment by virginielastisneres** [comment]
manque juste le dernier point qui va être fini aujourd'hui ou demain !

**Comment by lionelB** [comment]
on peut prévoir un mise a jour des données en fin de journée si c'est ok de votre coté (et datafiller)

**Comment by virginielastisneres** [comment]
Désolé de pas avoir relancé la conversation... Les fiches MT sont toutes thémées. une mise à jour peut être faite @lionelB @ClementChapalain

**Comment by lionelB** [comment]
je ferme
