### ISSUE TITLE
Emploi et classifications

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#170]
Aide à domicile : services soin et accompagnemnet

ères / Catégories | Intervention | Administratif / Services généraux | Encadrement/ Direction
-- | -- | -- | --
A | Agent(e) à domicileAgent(e) polyvalent(e) | Agent(e) de bureauAgent(e) d'entretien |  
B | Employé(e) à domicile | Employé(e) de bureauEmployé(e) d'entretienCuisinier(e) |  
C | Auxiliaire de vie socialeAide médico-psychologiqueAide soignant(e)Auxiliaire de puériculture | SecrétaireAide comptableHôte(sse) d'accueilTechnicien(ne) télé-alarme |  
D | Technicien(ne) de l'intervention sociale et familiale | Secrétaire de directionAssistant(e) techniqueSecrétaire médicale |  
E | Infirmier(e)Chargé(e) d'évaluation et de suivi socialÉducateur(trice) de jeunes enfantsErgothérapeuteDélégué(e) à la tutelleMédiateur(trice) familial | Assistant(e) de directionChargé(e) de développementComptableFormateur(trice) | Responsable de secteurConseiller(e) techniqueMaître(sse) de maison
F |   | Cadre administratif ou technique | Cadre de secteur ou de proximitéCoordinateur(trice) de service de soinsResponsable de service
G | Psychologue |   | Responsable d'entitéChef de service
H |   | Médecin | Directeur(trice) de fédération départementaleDirecteur(trice) d'entitéDirecteur(trice) de service
I |   |   | Directeur(trice) général d'entité

**Comment by ClementChapalain** [comment]
Est-ce que tu pourrais détailler le besoin là-dessus stp @jrduscher ?
