### ISSUE TITLE
Feedbacks contributions

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1730]
2 feedbacks à traiter pour les contributions : 

1. Dans la contribution https://code.travail.gouv.fr/contribution/combien-de-fois-le-contrat-de-travail-peut-il-etre-renouvele le content devrait être dans le premier accordéon CDD, mais il apparait au début de la réponse

2. Dans les contributions, les content qui ont des accordéons, par exemple https://code.travail.gouv.fr/contribution/quelle-est-la-duree-de-preavis-en-cas-de-licenciement, présentent les titres d'accordéons comme des H2 alors que ce devrait être des H3 en réalité. Soit on les change carrément en H3 (solution idéale) soit on change leur style pour qu'ils ressemblent à des H3

1 est assez important, 2 un peu moins

**Comment by revolunet** [comment]
ping @nkrmr pour le bug de la fiche hors de l'accordeon. a voir ce que ca va donner niveau "ux" une fiche dans un accordeon

**Comment by nkrmr** [comment]
@revolunet  Ça marche bien il faut juste descendre la police des titres des sous-accordéons pour que ce soit plus lisible. Je suis en train de push une première version

**Comment by UnbearableBear** [comment]
Attention avec la taille de police de titre dans l'accordéon, bientôt elle ne sera plus aussi "libre" vu que l'on n'aura plus que trois niveaux de titres. Est-ce qu'un décalage vers la droite (une sorte de tabulation par niveau) pourrait avoir le même rôle ? On pourra affiner ça plus tard quoi qu'il en soit !

**Comment by revolunet** [comment]
aperçu ici : http://c7ebe4d.code-du-travail-numerique.dev.factory.social.gouv.fr/contribution/combien-de-fois-le-contrat-de-travail-peut-il-etre-renouvele

**Comment by nkrmr** [comment]
@UnbearableBear  Je l'ai baissé avec du styled pour le moment

**Comment by lionelB** [comment]
closed by #1793
