### ISSUE TITLE
[search] Datafiller : matching requête utilisateur / entrée Datafiller

### ISSUE THREAD

**Issue by rmelisson** [SocialGouv/code-du-travail-numerique#1731]
Le lien entre une requête utilisateur et une entrée dans le datafiller est pour le moment très rigide (exact match).
Ça serait utile de faire un match plus interessant : 
- avec un peu de fuzzy matching
- en utilisant Elastic (more like this / phrase matching...)
- en utilisant la proximité sémantique

Ce comportement pourrait être construit de manière à être étendu aux requêtes non datafiller (voir #1641 )

**Comment by rmelisson** [comment]
en JS directement, on pourrait utiliser ça : https://www.npmjs.com/package/fuzzball

**Comment by rmelisson** [comment]
250 queries datafiller avec +/- 10 declinaisons

**Comment by revolunet** [comment]
174 requetes déclinées en 2963 variantes

fichier dump ici : https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-data/dataset/datafiller/prequalified.data.json

**Comment by rmelisson** [comment]
version fuzzball pour le moment
