### ISSUE TITLE
Suppression d'un doublon fiche SP

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1732]
https://code.travail.gouv.fr/fiche-service-public/contrat-de-travail-temporaire-interimaire
https://code.travail.gouv.fr/fiche-service-public/contrat-de-travail-temporaire-interim

Le premier renvoie à une fiche qui ne semble plus sur service-public.fr.
le premier pargraphe copié collé sur google renvoie des matchs CDTN.
Fiche à supprimer ou màj des fiches S-P à faire?

Précisions: aujourd'hui l'affichage des contenus pouvant aussi vous intéresser lie ces deux contenus.

**Comment by lionelB** [comment]
les 2 contenus existent 
- le premier renvoi sur https://www.service-public.fr/professionnels-entreprises/vosdroits/F11215
- le deuxieme sur https://www.service-public.fr/particuliers/vosdroits/F11215

il font choisir qui l'on garde (ou si l'on garde les 2)

**Comment by ClementChapalain** [comment]
Les deux sont identiques en termes de contenu, on vire celui qui s'affiche mal chez nous : 
https://code.travail.gouv.fr/fiche-service-public/contrat-de-travail-temporaire-interimaire
