### ISSUE TITLE
Bug Fiche ministère du travail lien bizarre 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#1733]
**DESCRIPTION DU BUG**

Lien bizarre dans la fiche ministère du travail sur la rupture conventionnelle => 
https://code.travail.gouv.fr/fiche-ministere-travail/la-rupture-conventionnelle-du-contrat-de-travail-a-duree-indeterminee?q=puis-je%20travailler%20pendant%20une%20rupture%20conventionnelle#Un-recours-juridictionnel-est-il-possible
![image](https://user-images.githubusercontent.com/48682104/69074282-512f0c80-0a2f-11ea-9d83-111e1219b7e7.png)

Normalement voici la fiche originale => https://travail-emploi.gouv.fr/droit-du-travail/la-rupture-du-contrat-de-travail/article/la-rupture-conventionnelle-du-contrat-de-travail-a-duree-indeterminee

Il s'agit en fait d'un renvoi vers une autre fiche du ministère du travail 

![image](https://user-images.githubusercontent.com/48682104/69074433-a5d28780-0a2f-11ea-955d-c56857f252a6.png)

**Comment by ClementChapalain** [comment]
virer le JS associé ua lien (cf. l'erreur ATTag dans sentry)
