### ISSUE TITLE
ajout et suppression de fiches ministère et articles

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1742]
### fiches récentes
- https://travail-emploi.gouv.fr/actualites/l-actualite-du-ministere/article/5-questions-reponses-sur-le-passage-a-temps-partiel

 cette fiche enregistrée comme article a le format des fiches ministères. En outre elle apporte une réponse explicite à une question posée en tests avec les M2, sur le refus du temps partiel par l'employeur.

- https://travail-emploi.gouv.fr/droit-du-travail/egalite-professionnelle-discrimination-et-harcelement/article/l-egalite-professionnelle-femme-homme
- https://travail-emploi.gouv.fr/droit-du-travail/la-remuneration/article/l-egalite-de-remuneration-entre-les-femmes-et-les-hommes-et-les-obligations-des-374533

### articles récents (?)
- https://travail-emploi.gouv.fr/actualites/l-actualite-du-ministere/article/apprentissage-questions-reponses-sur-la-remuneration-des-apprentis-377397
- https://travail-emploi.gouv.fr/actualites/l-actualite-du-ministere/article/prevention-machines-un-guide-pour-modifier-vos-machines-en-toute-securite
- https://travail-emploi.gouv.fr/actualites/l-actualite-du-ministere/modalites-financement-CFA-contrats-apprentissage

**Comment by revolunet** [comment]
quelles suppressions @jrduscher ?

**Comment by revolunet** [comment]
NB : suppression de cette fiche qui n'existe plus : https://travail-emploi.gouv.fr/formation-professionnelle/droit-a-la-formation-et-orientation-professionnelle/article/moncompteactivite-gouv-fr
