### ISSUE TITLE
bugs d'affichage remontés par les M2 Droit Social

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1744]
### outil de recherche CCN.
Sur mobile: les intitulés de résultats , comme les nom des entreprises sont tronqués.  (ex : « Dassault » renvoie plusieurs occurrences « Dassault… » sans plus d’info). 
Ce qui amène une difficulté pour choisir un etablissement ou trouver sa ccn sur mobile.

### - outil d'indemnité de licenciement : 
 Avec Edge titres collés sur la page résultat,

> ![image](https://user-images.githubusercontent.com/37538697/69136316-ec20f880-0aba-11ea-8adb-67fe6b084599.png)

### -fiches SP: affichage dans EGDE; 
sur au moins une fiche ,  le contenu est absent de la fiche. ( accordéon seul)
 
![image](https://user-images.githubusercontent.com/37538697/69136597-6baec780-0abb-11ea-97a8-e1375ab99f42.png)

https://code.travail.gouv.fr/fiche-service-public/attestation-destinee-a-pole-emploi?q=emploi
https://code.travail.gouv.fr/fiche-service-public/rupture-conventionnelle?q=rpture%20conventionnelle

### - champ “salaires” dans l’outil de simulation de l’indemnité de licenciement :
 pour remplir le salaire il faut faire une actualisation de la page (moteur Opéra) sinon on ne peut pas indiquer le montant dans la case.  ( non retesté entre temps)

### Autres remarque
- Affichage des contenus en alignés gauche choque les étudiants et juristes

**Comment by ClementChapalain** [comment]
je ferme et je répartis dans les issues #1830 et #1831
