### ISSUE TITLE
Bug IE11 CCN picker

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#1749]
Exemple dans l'outil de précarité vu sur la prod : 

 - difficultés pour séléctionner la CC
 - une fois la CC séléctionnée, l'écran alterne de "pas de CC" à "réponse de la CC séléctionnée".

très bizarre 🤔

**Comment by revolunet** [comment]
Passage perfs timeline à prévoir

**Comment by lionelB** [comment]
le problème vient de la lib createPersistedState() qui crée une boucle de render infini dans IE11.
j'ai fait un test "rapide" avec une version très limité qui corrige le probleme

```js
const useLocalStorage = (key, defaultValue) => {
   // using function as initialValue for setState ensure function is call only on first render
  const initialValue = () =>
    JSON.parse(window.localStorage.getItem(key)) || defaultValue;
  const [value, setValue] = useState(initialValue);
  // useEffect with dependency so value is persisted only when updated
  useEffect(() => {
    window.localStorage.setItem(key, JSON.stringify(value));
  }, [key, value]);
  return [value, setValue];
};
``` 
Il faudrait faire des tests avec des lib + robuste pour gérer les cas ou le localStorage n'est pas dispo (navigation privée)

**Comment by revolunet** [comment]
Tests ok sur Firefox/Safari/Chrome en mode anonyme ou pas
