### ISSUE TITLE
[outils] Bug affichage IE11 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#1750]
**Description**
Sur IE11 dans la page résultat de l'outil de licenciement j'ai sur la même ligne "Voir le detail du calcul" et "Élements saisis :"
![image](https://user-images.githubusercontent.com/48682104/69155547-349fdc80-0ae2-11ea-8a82-e174748d0384.png)

Éléments saisis devrait apparaître en dessous de Voir le détail du calcul 
Comme cela 
![image](https://user-images.githubusercontent.com/48682104/69155767-9ceebe00-0ae2-11ea-8138-7b4f99c1328b.png)

J'en profite pour dire qu'il y a deux petites fautes d'orthographes : Voir le detail du calcul" et "Élements saisis :" il faut rajouter un accent sur le e de détail et le deuxième e de éléments

**Comment by jrduscher** [comment]
Avec Edge également #1744

**Comment by ClementChapalain** [comment]
mettre un display:block
