### ISSUE TITLE
Bug "Avez-vous trouvé la réponse à votre question ?"

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#1754]
**Description**
Sur IE11 : il est impossible pour l'utilisateur de cliquer sur Oui ou Non... 
Sur Chrome, Edge et Firefox, il est possible de cliquer sur Non. Toutefois, il n'est pas possible pour l'utilisateur de choisir autre chose que "les informations proposées ne sont pas à jour". J'ai beau cliquer ca me laisse "les informations proposées ne sont pas à jour". 

![1](https://user-images.githubusercontent.com/48682104/69172402-08925480-0afe-11ea-9a0c-3ee20d77d621.png)
![2](https://user-images.githubusercontent.com/48682104/69172401-08925480-0afe-11ea-88e0-8eefd5236dea.png)

**Comment by ClementChapalain** [comment]
Note : revoir complètement le module de feedback en passant par matomo

**Comment by ClementChapalain** [comment]
du coup je close pour #1832, ces bugs seront fixés avec le revamp de la fonctionnalité
