### ISSUE TITLE
navigation par thème: 

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1755]
bug d'affichage.

navigation par thème: C2P. 
problème suivant:
![image](https://user-images.githubusercontent.com/37538697/69173880-fa920300-0b00-11ea-9118-77ff1933486a.png)
https://code.travail.gouv.fr/themes/623-compte-professionnel-de-prevention-c2p

**Comment by ClementChapalain** [comment]
Ces blocs vides correspondent aux lien externes du type https://www.compteprofessionnelprevention.fr/ qui sont data-fillés.

Je ferme cette tâche pour qqchose de plus général : la gestion des outils externes #1833
