### ISSUE TITLE
Bug d'affichage fiche MT : toute la fiche est dans l'intro car pas de H3

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1761]
bug d'affichage sur une fiche MT: 

Le chapeau sur la fiche d'origine contient une phrase seule:
![image](https://user-images.githubusercontent.com/37538697/69241966-30d28f80-0ba0-11ea-924f-03c23c160eaf.png)

Sur le CDTN, il englobe une partie toute une partie de la fiche:
![image](https://user-images.githubusercontent.com/37538697/69242029-4e9ff480-0ba0-11ea-8ccc-c56c09ab4642.png)

Pour voir la fiche d'origine https://travail-emploi.gouv.fr/droit-du-travail/lutte-contre-le-travail-illegal-10802/article/qu-est-ce-que-le-travail-illegal

 notre fiche: https://code.travail.gouv.fr/fiche-ministere-travail/quest-ce-que-le-travail-illegal#Connaitre-la-reglementation

**Comment by UnbearableBear** [comment]
C'est embêtant parce que tant que l'on n'a pas de titre, on considère que l'on est encore à l'introduction (avec la manière dont on fonctionne aujourd'hui). @jrduscher Est-ce que tu pourrais faire une passe sur plus de fiches pour regarder le diff entre la manière dont on les affiche sur le CDTN et les originales ? Il pourrait y avoir bien plus de surprises que ce que tu as repéré !

**Comment by jrduscher** [comment]
https://code.travail.gouv.fr/fiche-ministere-travail/le-harcelement-sexuel?q=harc%C3%A8lement%20sexuel#Victime-ou-temoin-de-harcelement-sexuel-quel-recours : cas de figure similaire.

https://code.travail.gouv.fr/fiche-ministere-travail/hydrogene-sulfure?q=plomb#Quels-sont-les-risques: taille des titres incohérentes ( les sous titres sont plus grands que les titres)
