### ISSUE TITLE
Parser les fiches MT avec structure basique sans H3

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#1770]
Vu à la mise à jour des thèmes :

Certaines fiches MT ne sont pas récupérées donc pas indexées car elles ont une structure très basique (pas de H3)

C'est le cas pour plusieurs de celles-ci :

- [Conventions nationales de lutte contre le travail illégal](https://travail-emploi.gouv.fr/droit-du-travail/lutte-contre-le-travail-illegal-10802/article/conventions-nationales-de-lutte-contre-le-travail-illegal)
- [Groupement d’employeurs](https://travail-emploi.gouv.fr/emploi/accompagnement-des-tpe-pme/groupement-employeurs)
- [Accompagnement des personnes sans emploi pour la création et la reprise d’entreprise](https://travail-emploi.gouv.fr/emploi/creation-ou-reprise-d-activite/article/accompagnement-des-personnes-sans-emploi-pour-la-creation-et-la-reprise-d-376101)
- [Compte personnel de formation (CPF)](https://travail-emploi.gouv.fr/formation-professionnelle/droit-a-la-formation-et-orientation-professionnelle/compte-personnel-formation)
- [Être apprenti](https://travail-emploi.gouv.fr/formation-professionnelle/formation-en-alternance-10751/apprentissage/etre-apprenti/)
- [Les services proposés par le Portail de l’Alternance](https://travail-emploi.gouv.fr/formation-professionnelle/formation-en-alternance-10751/apprentissage/etre-apprenti/article/les-services-proposes-par-le-portail-de-l-alternance)
- [Les missions du CHSCT exercées par le délégué du personnel](https://travail-emploi.gouv.fr/sante-au-travail/les-acteurs-et-interlocuteurs-de-la-sante-au-travail/comite-d-hygiene-de-securite-et-des-conditions-de-travail/delegue-du-personnel/article/les-missions-du-chsct-exercees-par-le-delegue-du-personnel)
- [Calcul de l’effectif assujettissant à la mise en place d’un CHSCT.](https://travail-emploi.gouv.fr/sante-au-travail/les-acteurs-et-interlocuteurs-de-la-sante-au-travail/comite-d-hygiene-de-securite-et-des-conditions-de-travail/qu-est-ce-qu-un-chsct/article/calcul-de-l-effectif-assujettissant-a-la-mise-en-place-d-un-chsct)
- [CHSCT et entreprises extérieures](https://travail-emploi.gouv.fr/sante-au-travail/les-acteurs-et-interlocuteurs-de-la-sante-au-travail/comite-d-hygiene-de-securite-et-des-conditions-de-travail/qu-est-ce-qu-un-chsct/article/chsct-et-entreprises-exterieures)
- [Consultation - Exemples de décisions d’aménagement important modifiant les conditions d’hygiène et de sécurité ou les conditions de travail donnant lieu à la consultation du CHSCT](https://travail-emploi.gouv.fr/sante-au-travail/les-acteurs-et-interlocuteurs-de-la-sante-au-travail/comite-d-hygiene-de-securite-et-des-conditions-de-travail/qu-est-ce-qu-un-chsct/article/consultation-exemples-de-decisions-d-amenagement-important-modifiant-les)
- [Le CHSCT et le droit d’alerte particulier](https://travail-emploi.gouv.fr/sante-au-travail/les-acteurs-et-interlocuteurs-de-la-sante-au-travail/comite-d-hygiene-de-securite-et-des-conditions-de-travail/qu-est-ce-qu-un-chsct/article/le-chsct-et-le-droit-d-alerte-particulier)
- [Les moyens matériels du CHSCT](https://travail-emploi.gouv.fr/sante-au-travail/les-acteurs-et-interlocuteurs-de-la-sante-au-travail/comite-d-hygiene-de-securite-et-des-conditions-de-travail/qu-est-ce-qu-un-chsct/article/les-moyens-materiels-du-chsct)
- [Recours à un expert en risques technologiques](https://travail-emploi.gouv.fr/sante-au-travail/les-acteurs-et-interlocuteurs-de-la-sante-au-travail/comite-d-hygiene-de-securite-et-des-conditions-de-travail/qu-est-ce-qu-un-chsct/article/recours-a-un-expert-en-risques-technologiques)
- [Visites d’inspection](https://travail-emploi.gouv.fr/sante-au-travail/les-acteurs-et-interlocuteurs-de-la-sante-au-travail/comite-d-hygiene-de-securite-et-des-conditions-de-travail/qu-est-ce-qu-un-chsct/article/visites-d-inspection)
- [Plan national d’action Radon 2016-2019](https://travail-emploi.gouv.fr/sante-au-travail/plans-gouvernementaux-sante-au-travail/article/plan-national-d-action-pour-la-gestion-du-risque-lie-au-radon-2016-2019)
- [Pénibilité : référentiels professionnels de branche homologués](https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/article/penibilite-referentiels-professionnels-de-branche-homologues)
- [Bruit en milieu de travail](https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/autres-dangers-et-risques/article/bruit-en-milieu-de-travail)
- [Formation du coordonnateur en matière de sécurité et de protection de la santé (SPS)](https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/article/formation-du-coordonnateur-en-matiere-de-securite-et-de-protection-de-la-sante)
- [Tapis roulants de montagne : mise à niveau](https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/article/tapis-roulants-de-montagne-mise-a-niveau)
- [Valeurs limites d’exposition professionnelle (risques chimiques)](https://travail-emploi.gouv.fr/sante-au-travail/prevention-des-risques-pour-la-sante-au-travail/mesures-et-moyens-de-prevention/article/valeurs-limites-d-exposition-professionnelle-risques-chimiques)
- [Interim et CDD](https://travail-emploi.gouv.fr/sante-au-travail/statut-des-travailleurs-et-dispositions-particulieres/article/interim-et-cdd)

**Comment by UnbearableBear** [comment]
En corrélation avec #1761

**Comment by revolunet** [comment]
A discuter : doit-on indexer également la version "root" d'une fiche : par exemple quand on affiche un theme ce serait p-e mieux de n'avoir que la fiche principale plutôt que les 5 sous-categories de la même fiche

**Comment by UnbearableBear** [comment]
Ce devrait pas être top dur à régler, il suffit de prendre en compte aussi le contenu avant le premier H3 (et de ne pas en faire un accordéon).
En ce qui concerne la version "root" je ne pense pas que ce soit necessaire. @ClementChapalain Proposait d'avoir un truc à la google ou l'on aggrégerait les sous fiches dans un seul résultat qui laisse le choix à l'utilisateur si l'on a plusieurs sous fiches qui remontent, ca me semble un bon compromis.

**Comment by ClementChapalain** [comment]
Je suis d'accord, on règle dans cette tâche le pb des fiches non-récupérées et on en profite pour traiter #1761 aussi. On verra l'affichage des fiches dans la recherche ou les thèmes dans un deuxième temps.
