### ISSUE TITLE
[typo] fix trailing 0 in UI

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#1777]
![Image collée à 2019-11-21 10-29](https://user-images.githubusercontent.com/124937/69327131-48b41d00-0c4d-11ea-811c-b0f84b36df1e.png)

cc @June-law

**Comment by UnbearableBear** [comment]
Est-ce que c'est pas plutôt un check sur la length d'un tableau qui foire ça ?
