### ISSUE TITLE
[suggestion] periode d'essai

### ISSUE THREAD

**Issue by rmelisson** [SocialGouv/code-du-travail-numerique#1779]
Comportement bizarre observé dans les logs :
![Screenshot 2019-11-21 at 11 27 27](https://user-images.githubusercontent.com/752778/69329759-fa554d00-0c51-11ea-952f-a7d4febe1eea.png)
![Screenshot 2019-11-21 at 11 27 32](https://user-images.githubusercontent.com/752778/69329761-faede380-0c51-11ea-9dcb-1d3e58c1dfbf.png)

**Comment by rmelisson** [comment]
aussi la deduplication ne semble pas ok

**Comment by lionelB** [comment]
![image](https://user-images.githubusercontent.com/160320/72624144-b11a3480-3946-11ea-9a8a-2113acbd79b2.png)
