### ISSUE TITLE
Préavis de licenciement : bug lorsque la CC n'est pas traitée

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1781]
voir aussi ma #1792 qui évoque d'autres points de disclaimer

# element bloquant: erreur juridique avec CC non traitée.

Aujourd'hui l'user d'une CC non traitée n'est en possession d'aucune donnée, et pourrait en déduire qu'aucune durée de préavis de licenciement n'est prévue dans son cas. 

![image](https://user-images.githubusercontent.com/37538697/69354526-8c744a00-0c80-11ea-8748-bad7e0faa18e.png)

je cherche une CCN non traitée, je remplis les paramètres code du travail, la CCN n'est pas trouvée:
on me renvoie 
- Le message de la page résultat prévu pour l'outil de démission , et non celui du préavis de licenciment:  le préavis de licenciement est prévu par le code du travail.

- La page de  résultat bloque la suite du parcours: je n'ai pas la durée prévue par le code du travail

#### Paradise:
- Afficher la page résultat : 
* Le résultat code du travail: durée (pas de préavis/un mois/ deux mois)
- Afficher une information: (bold)
" Nous n'avons pas encore traité cette convention collective.  "

"Une durée  de préavis de licenciement plus favorable au salarié peut être prévue dans la convention collective, un accord d'entreprise, le contrat de travail ou un usage dans l'entreprise."

#### Si l'envoi du résultat du cdtl n'est pas techniquement possible:

" Nous n'avons pas encore traité cette convention collective.  "
"Nous ne sommes pas en mesure de répondre à votre requête:
Le code du travail peut avoir prévu une durée de préavis de licenciement dans votre cas.  La convention collective, un accord d'entreprise, un usage ou encore le contrat de travail peut avoir prévu une durée et des conditions plus favorable au salarié"

**Comment by revolunet** [comment]
cc @nkrmr

**Comment by jrduscher** [comment]
issue modifiée @lionelB
