### ISSUE TITLE
Bug responsive simulateur indemnité de licenciement

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#1782]
Petit bug responsive découvert sur le simulateur de l'indemnité de licenciement, pas très urgent mais à avoir en tête.

![image](https://user-images.githubusercontent.com/48682104/69357722-e4617f80-0c85-11ea-94fc-0d2a8fb5af70.png)

**Comment by lionelB** [comment]
ducplicate of #2121
