### ISSUE TITLE
Possibilité de voir plus de résultats de recherche avec une pagination

### ISSUE THREAD

**Issue by rmelisson** [SocialGouv/code-du-travail-numerique#1783]
Pour le moment, l'utilisateur n'a pas la possibilité d'aller au delà des 7 résultats proposés.
Il serait utile d'ajouter de la pagination ou un bouton `voir plus` afin de laisser la possibilité à un utilisateur d'aller voir plus loin. 
C'est surtout important pour l'algo d'ordering afin de faire remonter des résultats qui seraient corrects, mais mal positionnés.

**Comment by lionelB** [comment]
Problème:  gestion de la pagination sur 2 collections (fulltext et sémantiques) qui sont ensuite mergées et reduites (on demande 7 resultats en fulltext, 7resultats  semantiques et on renvoi les 7 premiers resultats en supprimant les doublons

piste: demander 5 résultat de chaque collections, merger les collections et renvoyée 10elements ou moins
- avantage: 
  - on peut gérer la pagination simplement (on utilise la meme valeur de pagination pour chaque collections
- inconvenient: 
  - on ne renvoie pas toujours le meme nombre de documents
  - on peut retomber sur le meme document d'un collection à l'autre sur des pages différentes

autre piste : Possibilité d'utiliser que la recherche sémantique pour simplifier la gestion de pagination

cc @rmelisson @revolunet

**Comment by lionelB** [comment]
@ClementChapalain voici la solution retenu. 
> Précharger 30 résultats dans la page et les afficher de manière progressive par tranche de 10. 

Tant qu'on a 2 recherches sur le même corpus, les solution de paginations pour faire qu'une seule solution relève du bricolage. De plus l'impact de la mise en place de la pagination a J-7 du lancement est un peu périlleux.
Sur du plus long terme, il faudra trouver un moyen de n'utiliser plus qu'une recherche (fulltext ou sem) tout en conservant l'avantage des 2 solutions.

**Comment by ClementChapalain** [comment]
ok pas de pbs pour moi, juste une question : ça veut dire quoi "de manière progressive" ? en chargeant automatiquement des résultats quand l'utilisateur arrive en base des 10 premiers, ou avec un système de pagination cliquable ?

je suis plus pour la deuxième solution car il y a du contenu potentiellement intéressant en dessous des résultats français facile (CDT et thèmes) donc ca risque d'être difficile pour l'utilisateur d'y accéder si on fait du chargement automatique.

**Comment by lionelB** [comment]
@ClementChapalain oui je pensais plutôt a un bouton "voir plus de résultats"

**Comment by ClementChapalain** [comment]
ah ok ça me va du coup, tant que le chargement des résultats supplémentaires n'est pas automatique quand on arrive en bas. il faudrait que ce bouton soit assez discret, soit un lien soit un bouton type "flat" je pense.

**Comment by ClementChapalain** [comment]
un truc comme ça ça pourrait être bien je pense : 
![image](https://user-images.githubusercontent.com/5337489/71170121-c5d9ae80-225a-11ea-9da1-fbba8ae586e5.png)

**Comment by lionelB** [comment]
oki je ferais une proposition. préalablement je voulais faire un petit benchmark pour savoir l'impact sur le temps / poids des requetes

**Comment by virginielastisneres** [comment]
@lionelB est ce que tu as une proposition à faire ?

**Comment by ClementChapalain** [comment]
@revolunet petit bug repéré : quand je clique sur "plus de résultats" sur une première recherche puis que je lance une deuxième recherche, j'ai dès le début une liste de résultats avec plus de résultats que prévu comme si j'avais déjà appuyé sur "plus de résultats" pour cette deuxième recherche. Lorsque je refresh la page j'ai bien le bon nombre de résultats. Si c'est pas clair dis- moi :) Je peux aussi faire une tâche séparée.

**Comment by UnbearableBear** [comment]
@ClementChapalain ça implique de changer l'emplacement du state (le placer plus haut dans la hierarchie) pour pouvoir le "rafraichir" au clic sur une nouvelle recherche ou d'autres cas si necessaire, je veux bien un tâche à part perso

**Comment by ClementChapalain** [comment]
#2329
