### ISSUE TITLE
Afficher les réponses dans l'ordre chronologique dans les simulateurs

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1784]
Dans tous les simulateurs, les réponses devraient s'afficher dans l'ordre chronologique tel que défini dans l'onglet paramètre ici : https://docs.google.com/spreadsheets/d/1zd_hShEui8BHK0349GpDUZRkCcQ9syIZ9gSrkYKRdo0/edit#gid=1483052046

A priori ce n'est pas le cas dans le simulateur de préavis de licenciement (voir tous les exemples en commentaire ci-dessous). À vérifier également dans le préavis de demission.

<details>
<summary>old description</summary>
- La saisie CCN est obligatoire, le parcours est bloqué.
  Prévoir un "je ne sais pas", poursuivre le parcours. Afficher le résultat Code du travail.
--> #1781 

- Affichage de l'ancienneté: les propositions ne se font pas dans l'ordre chronologique.
- CCN 275: on a le choix entre ouvrier et ouvriers, employés: solution afficher en premier l'option aéroport paris oui/non, puis catégorie

- afficher systématiquement  l'article du code du travail dans la page résultat : "Article L.1234-1 du code du travail", https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000006901112&cidTexte=LEGITEXT000006072050&dateTexte=20080501
--> #1836
</details>

**Comment by virginielastisneres** [comment]
Affichage de la catégorie professionnelle du salarié dans la CC 29 Hospitalisation : les catégories ne sont pas affichées dans l'ordre, il faudrait les indiquer comme cela : 

Non-cadres
Autres cadres
Cadres administratifs et de gestion
Biologistes
Pharmaciens
Médecins
Gestionnaires
Directeurs-adjoints
Directeurs
Directeurs généraux

**Comment by virginielastisneres** [comment]
Dans CC 44 catégorie techniciens, les groupes professionnels ne sont pas affichés dans le bon ordre. Le IV doit être mis à la fin 

Il faut que cela donne : 
- I
- II
- III
- IV

IDEM pour l'ancienneté demandée, il faut inverser "2 ans ou plus" et "moins de 2 ans" et mettre : 
- moins de 2 ans
- 2 ans ou plus

**Comment by virginielastisneres** [comment]
IDEM IDCC 86 PUBLICITE : les catégories professionnelles ne sont pas dans l'ordre

Il faut que cela donne : 
- Employés
- Agents de maîtrise et Techniciens 
- Cadres

idem pour l'ancienneté conventionnelle => il faut indiquer : 
- moins de 2 ans 
- plus de 2 ans
et non l'inverse

**Comment by virginielastisneres** [comment]
IDEM CC 292 Catégorie professionnelle =>
CI-dessous le bon ordre
- Collaborateurs 
- Cadres

**Comment by lionelB** [comment]
@virginie il faut faire comme pour les autres simulateurs, il faut préfixer les champs cc @ClementChapalain

**Comment by virginielastisneres** [comment]
ca y est mais pas dans l'ordre dans le data-simulateur...

**Comment by lionelB** [comment]
oups ! on va refaire une passe simulateur !

**Comment by virginielastisneres** [comment]
Parfait :D C'est très important car pour avoir pour le moment tester 30 CCs, il y a 80% des choix proposés qui sont pas dans l'ordre.

**Comment by ClementChapalain** [comment]
oui j'ai l'impression qu'on a bien fait les prefixes dans le data-simulateur, mais que ce n'est pas pris en compte

@nkrmr est-ce que tu avais fait en sorte que les réponses s'affichent dans le bon ordre en fonction des préfixes du style `1| bla bla bla` qu'on trouve dans les données ?

**Comment by nkrmr** [comment]
@ClementChapalain Il faut que je regarde je te dis ça

**Comment by lionelB** [comment]
donc la fonction de tri marche bien :) le pb vient des data

**Comment by ClementChapalain** [comment]
ok désolé de pas avoir bien vérifié ! je close pour #1794 du coup, qu'on pourra faire la semaine prochaine le temps qu'on recheck les param
