### ISSUE TITLE
Bug sur les outils lorsque qu'on revient sur une question déjà remplie

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#1790]
le changement d'une valeur parente  ne re-initialise pas correctement les valeurs précédemment saisies.
ex:  cc1090 catégorie: `ouvrier` puis remplir anciennete, echelon. Suivant.
faire précéddent puis sélectionner catégorie `cadre` puis faire suivant. 

 un message d'erreur apparait

**Comment by jrduscher** [comment]
Nouveau cas remonté par une OPE ou autre exemple: @lionelB @revolunet 

Dans les outils de préavis de licenciement et démission:
Quand on recherche par exemple la CC 573, au moins deux users ont eu le  message suivant: 


![image](https://user-images.githubusercontent.com/37538697/70227704-57252d00-1753-11ea-9e9f-195e6b6372c5.png)

**Comment by nkrmr** [comment]
@jrduscher Je vais voir ce que cela peut être

**Comment by lionelB** [comment]
@nkrmr le pb fixé va être fixé à la source

**Comment by nkrmr** [comment]
cf: #1888

**Comment by ClementChapalain** [comment]
le bug se répète encore sur master : 
- aller sur http://master.code-du-travail-numerique.dev.factory.social.gouv.fr/outils/preavis-demission
- sélectionner la convention "pharmacie d'officine" et le statut "cadre"
- voir le résultat
- cliquer sur précédent 2X
- changer pour la convention "télécommunications"
- page vide (alors que si on va direct sur "télécommunications" ça fonctionne bien) :
![image](https://user-images.githubusercontent.com/5337489/70701778-3ae23c80-1ccd-11ea-8689-0b970bb1161d.png)

Aussi, si je recharge la page du préavis de démission, plein d'erreurs pop dans la console et font planter mon navigateur, je suis obligé de fermer l'onglet : 
![image](https://user-images.githubusercontent.com/5337489/70701866-69601780-1ccd-11ea-9eb6-1d7f943335eb.png)

**Comment by ClementChapalain** [comment]
ping @nkrmr @lionelB

**Comment by lionelB** [comment]
je m'en occupe !

**Comment by ClementChapalain** [comment]
merci Lionel !
