### ISSUE TITLE
outils : pouvoir ordonnancer les questions (critere) pour affiner un situation

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#1791]
On souhaiterais pouvoir ordonnancer les questions posées à l'utilisateur pour affiner une situation
cc @jrduscher pour l'ordre

**Comment by lionelB** [comment]
aéroport paris
agents payés à l'heure
catégorie professionnelle
personnel de conduite
motif de rupture
durée du travail
durée du préavis
type de rupture
conclusion du contrat de travail
période essai
logement
niveau
classe
position
groupe
coefficient
échelon
ancienneté
âge

**Comment by jrduscher** [comment]
aéroport paris agents payés à l'heure catégorie professionnelle
personnel de conduite motif de rupture
durée du travail durée du préavis type de rupture conclusion du contrat de travail période essai logement niveau
classe position
groupe
coefficient
échelon ancienneté
âge

**Comment by ClementChapalain** [comment]
c'est réorganisé dans le data simulateurs
