### ISSUE TITLE
Disclaimer outils de préavis licenciement et démission

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#1792]
# préavis de licenciement

Afficher le disclaimer suivant en dessous du résultat dans la première section :

"Une durée de préavis de licenciement plus favorable au salarié peut aussi être prévue dans un accord d'entreprise, le contrat de travail ou un usage dans la localité ou la profession."

# préavis de démission

Dans le simulateur de préavis de démission, il faut bouger le bloc similaire dans la première section pour être cohérent : 
![image](https://user-images.githubusercontent.com/5337489/69870624-c1038980-12b0-11ea-8c8b-e7bbb7a22ebd.png)

<details>
<summary>old description</summary>
A l'écran de résultats, dans le cas où une convention collective à été choisie, lorsque qu'aucune situation n'est récupérée, on souhaiterait afficher un message d'erreur plutôt que d'afficher seulement la réponse conventionnel. 
A noter qu'on devrait avoir une réponse conventionnelle
cc @jrduscher pour les critères de reproduction
</details>

**Comment by jrduscher** [comment]
1) Ajouter **dans tous les cas** dans la page résultat: " Un accord collectif, le contrat de travail ou un usage peuvent prévoir:  une durée plus favorable pour le salarié ou des conditions d'ancienneté différentes".

2) Tester: si le choix CCN répond à une CCN existante et traitée, que le résultat n'aboutit pas: afficher "Erreur. nous ne parvenons pas  à trouver la durée de votre période de préavis de licenciement prévue pour cette branche"

3)La CCN n'est pas encore traitée: Nous n'avons pas traité votre convention collective.

**Comment by ClementChapalain** [comment]
on ne garde que la problématique du wording dans cette tâche car le reste est déjà traité dans #1790 et #1781

**Comment by lionelB** [comment]
c'est un autre bug je pense au vu du code en place
