### ISSUE TITLE
Métriques/indicateurs ★★★★★: Enrichir le prototype

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#18]
Il serait bien pour la démo, que le bouton envoyer déclenche une action: 
- soit simplement un retour en page d'accueil
-  soit un message factice d'accusé réception du commentaire " Merci de votre participation", avec un retour à l'accueil
- soit la prise en compte bien réelle de cet élément...

_"Aidez-nous à nous améliorer
Avons-nous répondu à votre question ?★★★★★

Vos commentaires constructifs nous permettront d'améliorer notre service
Envoyer"_

**Comment by revolunet** [comment]
envoyer un email à codedutravail@beta.gouv.fr ?

**Comment by revolunet** [comment]
Ajouter des infos lors de l'envoi d'email :
 - [x] navigateur
 - [x] parcours utilisateur
