### ISSUE TITLE
Bug report : simulateur prime de précarité 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#1808]
Dans le simulateur de la prime de précarité (contrat d'intérim), il y a un petit bug, un &nsbp; qui s'affiche après une question (cf. photo ci-dessous)
![image](https://user-images.githubusercontent.com/48682104/69549889-61e50280-0f9a-11ea-9f69-f4bedb43b1e4.png)

**Comment by UnbearableBear** [comment]
Ah c'est probablement une boulette de moi ça !
