### ISSUE TITLE
Bug report : page outils 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#1809]
Que je sois sur le master ou sur la prod, quand je vais sur une page outil, j'ai un petit trait qui s'affiche en bas de la page... J'ai pas l'impression qu'il soit sur les autres pages...

![image](https://user-images.githubusercontent.com/48682104/69552380-aa062400-0f9e-11ea-945c-baf9db445d7c.png)

![image](https://user-images.githubusercontent.com/48682104/69552470-cd30d380-0f9e-11ea-970d-9a1115f0bb7a.png)

**Comment by ClementChapalain** [comment]
🕵️‍♀️

**Comment by ClementChapalain** [comment]
c'est fixé sur master :)
