### ISSUE TITLE
Modèles de courrier : ajouter un disclaimer avant le bouton télécharger

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1810]
## Ajouter un disclaimer sur tous les modèles

"Attention, chaque modèle de document proposé est à personnaliser selon votre situation et est susceptible d’évoluer suite à des changements de règlementation. Assurez-vous d’avoir la dernière version mise à jour avant toute utilisation."

## Convention de nommage des documents

date du jour et pas date de mise à jour

"Titre du document - JJ.MM.AAAA". Convention de nommage des fichiers téléchargeable:
"JJMMAAA"+"Mot"+"-"+"Mot" (...).odt

**Comment by jrduscher** [comment]
// en attente de validation

**Comment by lionelB** [comment]
c'est quoi l'interet de mettre la date du jour du telechargement dans le nom du fichier ?

**Comment by ClementChapalain** [comment]
L'idée c'est que si le document est stocké sur un ordinateur ou transféré à qqun d'autre, il y a une référence de la data de téléchargement

**Comment by ClementChapalain** [comment]
wording de la description validé

**Comment by lionelB** [comment]
mais ce qui importe c'est que la date correspondent plutot au fichier qu'on a chez nous, non ?

**Comment by ClementChapalain** [comment]
oui notre réflexion c'est de dire que la date de téléchargement c'est la date à laquelle le fichier était valide donc c'est ça qui est important a priori, même si le fichier a pas été mis à jour depuis longtemps il est toujours en vigueur et valide
