### ISSUE TITLE
Compare Camembert vs. USEm QA using auto DCG in monolog

### ISSUE THREAD

**Issue by rmelisson** [SocialGouv/code-du-travail-numerique#1819]
- Ajouter à l'analyse de log un méchanisme pour calculer le DCG en utilisant les données du datafiller
- Comparer le score entre Camembert et le modele actuel, voir :
http://1f06025.code-du-travail-numerique.dev.factory.social.gouv.fr/
JS script actuel : 
https://codesandbox.io/s/quizzical-fast-bnnp9

**Comment by rmelisson** [comment]
#2261

**Comment by rmelisson** [comment]
no longer relevant

**Comment by lionelB** [comment]
@rmelisson should we close the camembert Pr ?

**Comment by rmelisson** [comment]
yep, je la ferme aussi, Camembert sera pê interessant pour d'autre usages mais pas pour remplacer le QA
