### ISSUE TITLE
L'outil de contribution remonte dans les résultats des moteurs de recherche

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1820]
L'outil de contribution remonte dans les résultats des moteurs de recherche
![image](https://user-images.githubusercontent.com/37538697/69737495-c2a84280-1134-11ea-9b46-bc45c8e19e8a.png)

Il n'y a  à minima aucune utilité à ce que ce soit le cas.

**Comment by revolunet** [comment]
in progress : https://github.com/SocialGouv/code-du-travail-backoffice/pull/768

**Comment by lionelB** [comment]
closed PR SocialGouv/code-du-travail-backoffice#768 had been merged
