### ISSUE TITLE
Aspect de la version mobile: outils et boutons

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1826]
![image](https://user-images.githubusercontent.com/37538697/69817878-d1a5f800-11fb-11ea-88ee-42861a1a11e3.png)

les boutons sortent de la page d'outils sur mon mobile.

**Comment by ClementChapalain** [comment]
solution proposée par Cécile en mobile : 
![image](https://user-images.githubusercontent.com/5337489/69871773-f78ed380-12b3-11ea-9dfc-2b09fe0ec44d.png)

**Comment by lionelB** [comment]
solution en place actuellement 
![image](https://user-images.githubusercontent.com/160320/72623615-c80c5700-3945-11ea-85d8-a1b3c3e60cb9.png)

on ferme ?

**Comment by ClementChapalain** [comment]
On peut garder ouvert mais ne pas la prioriser, comme ça on la garde en tête
