### ISSUE TITLE
Bug page introduction au droit du travail

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#1827]
**Description**
Dans la page droit du travail, la version responsibe des sources du droit se présente ainsi : 

![image](https://user-images.githubusercontent.com/48682104/69823585-8eeb1c80-1209-11ea-8c2e-a8f9bbbd1cee.png)

Or, cette présentation des sources n'est pas dans l'ordre. 
Il faudrait qu'elles sont présentées ainsi : 
- Les textes internationaux
- Les textes européens
- La Constitution française
- Lois, ordonnances, décrets et arrêtés
- Les conventions et accords collectifs
- Les usages et les engagements unilatéraux
- Le règlement intérieur de l’entreprise
- Le contrat de travail

**Comment by UnbearableBear** [comment]
Du coup la lecture dans la version non mobile devra se faire ainsi: colonne gauche -> jusqu'en bas puis colonne droite-> jusqu'en bas. Au lieu de se faire comme ça acutuellement: colonne gauche  -> colonne droite -> un cran plus bas -> colonne gauche -> colonne droite etc. Tu vois ce que je veux dire ? Ca ira quand même ?

**Comment by virginielastisneres** [comment]
:/ je suis pas sure que ca passera... Je vais réfléchir un peu plus du coup...

**Comment by UnbearableBear** [comment]
solved with new design
