### ISSUE TITLE
Bug chargement du contenu sur Edge

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1831]
Le contenu des fiches ne se charge pas sur edge lorsqu'on rafraichit la page.

Pour reproduire : 
- aller sur la fiche rupture conventionnelle par exemple : https://code.travail.gouv.fr/fiche-service-public/rupture-conventionnelle
- le contenu s'affiche bien
- rafraichir la page
- uniquement les titres des accordéons sont affichés, pas le contenu de la page

![image](https://user-images.githubusercontent.com/37538697/69136597-6baec780-0abb-11ea-97a8-e1375ab99f42.png)

**Comment by UnbearableBear** [comment]
A voir si ce n'est pas lié au script de polyfill qui coince parfois sous ie11

**Comment by revolunet** [comment]
Je propose qu'on extracte le polyfill pour le mettre en static, ca nous fera une dépendance en moins

**Comment by nkrmr** [comment]
Je vais faire des tests et voir ce que c'est je vous tiens au courant

**Comment by nkrmr** [comment]
Après investigation minutieuse, il semblerait que le problème vienne de l'utilisation de l'auto-prefix 
**-webkit-animation** qui fait planter l'affichage des contenus de l'accordéon.
Il est automatiquement généré pas styled-components, je vais voir comment on peut éviter de générer cet auto-prefix.

**Comment by lionelB** [comment]
GG @nkrmr

**Comment by lionelB** [comment]
il semblerait que le pb viennent plutôt d'un bug du moteur de rendu IE quand on met à jour le innerHTML.
une piste serait d'utiliser l'api DOM Node pour faire la modification du contenu du noeud plutot que de passer par innerHTML

**Comment by nkrmr** [comment]
Je suis dessus en train de tester les différentes méthodes évoquée lors de notre réunion

**Comment by nkrmr** [comment]
Après de nombreuses tentatives différentes pour élucider le problème je ne trouve pas de solution pour régler ce bug.

Le premier problème identifié semblait venir du fait de modifier le HTML à l'aide de l'innerHTML dans la méthode   ***useGlossary(children, html)*** ligne 74

```javascript
        patterns.forEach(pattern => {
          // we use an internal ref counter to track pattern replacement
          node.innerHTML = node.innerHTML.replace(pattern, function(_, term) {
            const internalRef = `__tt__${refCounter++}`;
            internalRefMap.set(internalRef, { slug: item.slug, term });
            return _.replace(
              new RegExp(term),
              `<span data-tooltip-ref="${internalRef}"></span>`
            );
          });
        });
```

Il semblait y avoir des problèmes identifiés sur internet de l'utilisation spécifique de ***innerHTML*** avec IE.
Après investigation et l'essai de l'utilisation de méthodes alternatives notamment ***appendChild*** ou le ***clonage de l'objet node*** le résultat fut le même.

En fait innerHTML rempli bien son rôle dans la transformation du HTML pour la mise en place du glossaire avec la methode ***useGlossary*** lorsqu'on visualise le rendu de la page à l'aide de Dev Tools .
Le problème vient du fait que pour une raison quelconque, spécifiquement dans le système d'accordéon du projet le fait de changer le HTML en passant par la méthode useGlossary semble bloquer le rendu du contenu lorsqu'on déplie un item de ce dernier.

Il semblerait que le moteur de rendu d'IE a des difficultés à rendre le contenu dans les accordéons lors du chargement de la page, car si l'on resize la page à ce moment-là le contenu apparait.

***Ecran au chargement de la page***
![Screenshot 2020-01-10 at 10 52 00](https://user-images.githubusercontent.com/686395/72143782-a59f9a00-3397-11ea-83d5-b35358b716da.png)

***Ecran après avoir resizé la page***
![Screenshot 2020-01-10 at 10 52 15](https://user-images.githubusercontent.com/686395/72143817-b6e8a680-3397-11ea-983a-8d292535e5f7.png)

J'ai fait une série de tests pour essayer de forcer le refresh du moteur de rendu, en passant par les l'***Event resize*** ou en modifiant le style des items de l'accordéon après la méthode ***useGlossary***, mais le résultat reste le même.  

***Les pistes envisageables :*** 

1. Trouver un moyen de refresh le moteur de rendu d'IE.
2. Faire le rendu HTML avec le glossaire côté back pour ne gérer que l'affichage côté Front

**Comment by ClementChapalain** [comment]
ok à reprioriser si on a beaucoup de retours sur le sujet

**Comment by lionelB** [comment]
closed by #2687
