### ISSUE TITLE
Gestion des liens vers des outils externes

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1833]
### contexte

On souhaiterait pouvoir ajouter des liens vers les outils du ministère depuis notre site.

### fonctionnement

Il faudrait qu'ils soient visibles dans la recherche, dans les outils proposés en contenus annexes, sur la liste des outils.

Lorsqu'on clique dessus, on est directement redirigé vers l'url correspondante en ouvrant un nouvel onglet permettant de sortir du CDTN.

Dans la page outils, créer une nouvelle section : "Les outils du ministère du Travail".

La première section peut s'appeler : "Les outils du Code du travail numérique".

### outils à ajouter

- https://www.teleaccords.travail-emploi.gouv.fr/PortailTeleprocedures/
  - titre : "TéléAccords"
  - description : "Le service de dépôt des accords collectifs d’entreprise"
  - icône : resignation ![image](https://user-images.githubusercontent.com/5337489/71015408-d58ab300-20f3-11ea-885c-33d08fb62c8c.png)
- https://www.telerc.travail.gouv.fr/RuptureConventionnellePortailPublic/jsp/site/Portal.jsp?page_id=20
  - titre : "TéléRC"
  - description : "Le service de saisie d'une demande d'homologation de rupture conventionnelle" 
  - icône : contract ![image](https://user-images.githubusercontent.com/5337489/71015306-aa07c880-20f3-11ea-8f90-8e34f1704f5e.png)
- https://www.sipsi.travail.gouv.fr/auth/login
  - titre : "SIPSI"
  - description : "Détachement de travailleurs en France"
  - icône : depart ![image](https://user-images.githubusercontent.com/5337489/71015697-59dd3600-20f4-11ea-8b9e-8e76a58392d9.png)
- https://www.elections-professionnelles.travail.gouv.fr/web/guest
  - titre : "Élections professionnelles"
  - description : "Le site dédié aux élections professionnelles et à la représentativité syndicale"
  - icône : document ![image](https://user-images.githubusercontent.com/5337489/71015743-6a8dac00-20f4-11ea-8976-5ccb5d64acc0.png)
- https://index-egapro.travail.gouv.fr/
  - titre : "Index Egapro" 
  - description : "L’outil de calcul de votre index égalité professionnelle Femmes- Hommes"
  - icône : calculator ![image](https://user-images.githubusercontent.com/5337489/71015900-a1fc5880-20f4-11ea-89be-899bd2dec9e2.png)
- https://www.moncompteformation.gouv.fr/
  - titre : "Mon compte formation"
  - description : "Consulter et utiliser ses droits pour la formation"
  - icône : formation ![image](https://user-images.githubusercontent.com/5337489/71015642-403bee80-20f4-11ea-80d2-281ce322000a.png)

Pour les verbes d'action à mettre sur les cartes, mettons "Consulter" à chaque fois car cela renvoie vers un autre site.

<details><summary>outils à ajouter dans un second temps</summary>

Pas dans cette tâche, en attente de validation avec la DGEFP : 
- https://www.alternance.emploi.gouv.fr/portail_alternance/
  - titre : "Portail de l'alternance"
  - description : "Toutes les informations sur l'apprentissage et les contrats de professionnalisation"
- https://www.agefiph.fr/
  - titre : "agefiph"
  - description : "Ouvrir l'emploi aux personnes handicapées"
- http://reviensteformer.gouv.fr/
  - titre : "Reviens te former"
  - description : "Le site du droit au retour en formation des 16-25 ans"
- http://ruptures-collectives.emploi.gouv.fr.
  - titre : "RUPCO"
  - description : "Le portail des ruptures collectives de contrat de travail"
- https://www.anact.fr/
  - titre : "Anact"
  - description : "L'agence nationale pour l’amélioration des conditions de travail"
- http://www.vae.gouv.fr/
  - titre : "VAE"
  - description : "Le portail de la validation des acquis de l’expérience"

</details>

**Comment by ClementChapalain** [comment]
icônes ajoutées @lionelB

**Comment by jrduscher** [comment]
#2106
