### ISSUE TITLE
À propos V2

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1835]
Idées en vrac [ WIP WIP]

**Comment by ClementChapalain** [comment]
wip : https://docs.google.com/document/d/1-_S1gbHear-hGJsbKTbQsRI_s8wOCvk0aUPSUs0vdwo/edit#heading=h.gvodronx7jgo

**Comment by ClementChapalain** [comment]
done !

lien vers les textes : 
https://docs.google.com/document/d/1-_S1gbHear-hGJsbKTbQsRI_s8wOCvk0aUPSUs0vdwo/edit#

maquette : 
![à propos - clément](https://user-images.githubusercontent.com/5337489/70313473-fdd20200-1815-11ea-817d-12dda325fb90.jpg)

**Comment by lionelB** [comment]
c'est trop bô

**Comment by ClementChapalain** [comment]
je viens de voir qu'il manque un espace avant minsitère du travail et après incubateur des ministères sociaux @lionelB : 
![image](https://user-images.githubusercontent.com/5337489/70698887-91994780-1cc8-11ea-8015-bdc8fc5a7f92.png)

désolé je l'ai raté hier en relisant..

**Comment by UnbearableBear** [comment]
@ClementChapalain je prends

**Comment by ClementChapalain** [comment]
coeur avec les mains
