### ISSUE TITLE
Revoir les descriptions des modèles de document

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1837]
Max 4-5 lignes

**Comment by jrduscher** [comment]
[ 
  {
    "titre": "Modèle : Demande de dérogation à la durée minimale de travail pour un temps partiel",
    "description": "Une durée minimale de travail est prévue pour les salariés travaillant à temps partiel. Cette durée est fixée dans le code du travail ou si elle est plus courte par une convention de branche étendue. Le salarié peut demander à déroger à cette durée du travail mainimale : pour faire face à des contraintes personnelles, pour lui permettre de cumuler plusieurs activités, ou pour permettre à un étudiant de moins de 26 une durée du travail compatible avec une poursuite d'étude. Le modèle ci-dessous propose cette demande. ",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "temps-partiel-demande-de-derogation-du-salarie.docx"
	
  },  
     	 {
    "titre": "Modèle : lettre de réclamation des heures supplémentaires",
    "description": "Les heures travaillées au-delà de la durée légale (35 heures) ouvrent droit en plus du taux horaire, à une contrepartiem soit une majoration du salaire ou à en tout ou partie à des contreparties sous forme de repos (repos compensateur équivalent). Ce modèle permet au salarié de demander le paiement des heures supplémentaires et le droit aux contreparties prévues ",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "reclamation-des-heures-sup.docx"
   },
    {
    "titre": "Modèle : Relevé d’heures supplémentaires",
    "description": "Les heures supplémentaires sont décomptées à la semaine et font l'objet de contreparties. Le document ci-après permet à l'appui d'une demande de réclamation des heures supplémentaires, de présenter le décompte des heures supplémentaires et les contreparties dues.",
       "date_redaction": "01/01/2020",
       "source": "Ministère du Travail",
    "filename": "tableau-recap-des-heures-supplementaires.docx"
  },
	  {
    "titre": "Modèle : réclamation de congés payés",
    "description": "L’employeur a le dernier mot sur l’ordre de départ des congés payés. Le salarié doit pouvoir prendre l’ensemble des congés dus. L’employeur n’a pas le droit de les payer en lieu et place. Ce modèle de courrier permet de demander à l'employeur la prise des congés de droit.",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "reclamation-de-cp.docx"
  },
   {
   
   "Tout salarié doit percevoir son salaire une fois par mois et recevoir un bulletin de paie lors du paiement du salaire. Il est conseillé de faire avec une lettre recommandée à accusé de réception. Le demandeur devra conserver une copie de la lettre. Il est également conseillé au salarié de se rapprocher des services de renseignements juridiques des DIRECCTE ou de l'agent de contrôle de l'inspection du travail qui suit l'entreprise.",
    "questions": [""],
   
   
    "titre": "Modèle : Demande de paiement de salaire",
    "description": "Tout salarié doit percevoir son salaire une fois par mois .Le salarié peut adresser un courrier à son employeur, exigeant le paiement du salaire du en cas de non paiement de salaire. Le demandeur doit aussi garder une copie de ce courrier. Le modèle ci après permet de faire cette demande à l'employeur",
    "date_redaction": "3/12/2019",
    "source": "Ministère du Travail",
    "filename": "demande-paiement-salaire-salarie.docx"
  },
   {
    "titre": "Modèle de rupture du contrat en période d’essai à l'initiative du salarié",
    "description": "Pendant la période d’essai, le contrat de travail peut être rompu librement par le salarié ou l'employeur. Le modèle de document ci-dessous présente  ",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "fin-periode-essai-initiative-du-salarie.docx"
  },
  {
    "titre": "Modèle : Rupture de période d’essai à l'initiative de l'employeur",
    "description": "Pendant la période d’essai, le contrat de travail peut être rompu librement par l’employeur ou le salarié. Le document ci-après est une proposition  de courrier de rupture de la période d'essai sur initiative de l'employeur.",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "fin-periode-essai-initiative-employeur.docx"
  },
    {
    "titre": "Modèle : Demande de rendez-vous en vue d’une rupture conventionnelle",
    "description": "La rupture conventionnelle individuelle est une modalité de rupture du CDI, en dehors de la démission et du licenciement, qui ouvre droit au paiment d'une indemnité spécifique de rupture, et ne peut se faire qu'avec le conssentement de l'employeur et du salarié et dans le cadre d'une procédure d'homologation administrative. Ce modèle permet d'ininitier la rupture par un premier entretien.",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "demande-rdv-rupture-conventionnelle.docx"
  },
  {
    "titre": "Modèle : convocation à entretien préalable",
    "description": "L’employeur qui envisage de licencier un salarié doit le convoquer à un entretien préalable. La convocation, envoyée par lettre recommandée avec accusé de réception ou remise en main propre contre signature, doit parvenir à l’intéressé au moins 5 jours ouvrables avant l’entretien préalable.",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "convocation-a-entretien-prealable.docx"
  },
    {
    "titre": "Modèle : lettre de réclamation des documents de fin de contrat",
    "description": "Les documents de fin de contrat sont dus par l'employeur et le salarié, au moment de la rupture du contrat de travail dans tous les cas de rupture du contrat de travail. (ex: certificat de travail..) Le modèle de courrier ci-après permet de demander à l'employeur la transmissison des documents de fin de contrat, mais également le paiement de certains élements de salaire prime et indemnités. ",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "reclamation-des-documents-de-fin-de-contrat.docx"
  }, 
  {
    "titre": "Modèle: Reçu pour solde de tout compte",
    "description": "Le solde de tout compte est un document obligatoire, remis en fin de contrat de travail. Il est établi par l’employeur et remis (contre reçu) au salarié qui quitte son emploi. Ce document est un modèle de reçu pour solde de tout compte. 
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "recu-solde-de-tout-compte.docx"
  },
  {
    "titre": "Modèle : Demande d'accord du salarié pour le renouvellement de période d’essai",
    "description": "La période d’essai peut être renouvelée, si la branche le prévoit et si cette possibilité est inscrite dans le contrat de travail ou la lettre d’engagement. Dans ces conditions, ce modèle permet de demander le renouvellement du contrat de travail.",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "renouvellement-periode-essai-initiative-employeur.docx"
  },
  {
    "titre": "Modèle : Rupture d’un commun accord d’un contrat d’apprentissage",
    "description": "Le contrat d'apprentissage peut être rompu par l'apprenti ou par l'employeur jusqu'à la fin des 45 premiers jours de pratique en entreprise. Passé ce délai, la rupture du contrat n'est possible que dans certains cas ou certaines modalités. Toutefois, La rupture d'un commun accord entre le salarié et l'employeur est possible. Ce que prévoit le modèle ci-après." 
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "rupture-amiable-du-contrat-d-apprentissage.docx"
  },
  {
    "titre": "Modèle : Rupture d’un commun accord d’un contrat de travail à durée déterminée",
    "description": "La rupture anticipée du  du contrat de travail à durée déterminée par le salarié ou l'employeur, en dehors de la période d'essai est limitée à un certain nombre de cas (ex: embauche en CDI). Pour autant une rupture d'un commun accord entre les parties est possible. Le document suivant présente un tel modèle d'accord. ",
    "date_redaction": "1/12/2019",
    "source": "Ministère du Travail",
    "filename": "rupture-commun-accord-du-cdd.docx"
  },
   {
    "titre": "Modèle : Signalement de faits pouvant relever du harcèlement moral",
    "description": "Le harcèlement moral consiste en des /"faits répétés ayant pour objet ou effet une dégradataion des conditions de travail, susceptibles de porter atteinte aux droits du salarié,sa dignité, compromettre sa santé physique ou mentale ou compromettre son avenir professionnel/". Le modèle suivant peut être utilisé pour signaler une telle situation à l'employeur.",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "signalement-harcelement.docx"
  },
  {
    "titre": "Modèle : Signalement de harcèlement sexuel",
    "description": "L'employeur doit prendre toutes les mesures en vue de de prévenir les faits de harcèlement sexuel, y mettre un terme ou les sanctionner. Le présent modèle permet à un salarié victime ou témoin d'une telle situation d'en alerter l'employeur. ",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "signalement-harcelement.docx"
  },
   {
    "titre": "Modèle : Réponse à Signalement de harcèlement sexuel",
    "description": "L'employeur doit prendre toutes les mesures en vue de de prévenir les faits de harcèlement sexuel, y mettre un terme ou les sanctionner. Le modèle ci-après propose une réponse au salarié ayant signalé des faits de harcèlement sexuel en tant que victime ou témoin.  ",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "signalement-harcelement.docx"
  },
  
]

**Comment by jrduscher** [comment]
[ 
 {
    "title": "Modèle : Affichage obligatoire relatif au harcèlement sexuel",
    "description": "Un affichage obligatoire est prévu en matière de lutte contre le harcèlement sexuel: dans les lieux de travail, et sur les portes ou dans les locaux où ont lieu les embauches. Cet affichage indique les sanctions applicables, les actions contentieuses civiles et pénales en matière de harcèlement sexuel et les coordonnées des autorités et services compétents. Le modèle ci-dessous propose cet affichage obligatoire. ",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "Affichage_Lutte_contre_harcelement_sexuel.docx"
	  },
 
 {
    "title": "Modèle : Certificat de travail",
       "description": "Le certificat de travail est un document obligatoire remis par l’employeur au salarié à la date de fin du contrat de travail. Le modèle ci-après est une proposition de certificat de travail.",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "Certificat_de_travail.docx"
	
  },
    {
    "titre": "Modèle : Demande de rendez-vous en vue d’une rupture conventionnelle",
    "description": "La rupture conventionnelle individuelle est une modalité de rupture spécifique du CDI. Elle nécessite le consentement de l’employeur et du salarié, et son homologation de l’administration. La rupture ouvre droit à une indemnité de rupture conventionnelle. Ce modèle permet d’initier la procédure de rupture par l’invitation à un premier entretien.",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "demande_rdv_rupture_conventionnelle.docx"
  },
  {
    "titre": "Modèle : convocation à un entretien préalable au licenciement pour motif personnel",
    "description": "L’employeur qui envisage de licencier un salarié doit le convoquer à un entretien préalable. La convocation, envoyée par lettre recommandée avec accusé de réception ou remise en main propre contre signature, doit parvenir à l’intéressé au moins 5 jours ouvrables avant l’entretien préalable. Ce modèle propose une telle convocation.",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "entretien_préalable_au_licenciement_personnel.docx"
  },
  {
    "titre": "Modèle : convocation à un entretien préalable au licenciement économique de moins de 10 salariés pendant 30 jours",
    "description": "L’employeur qui envisage le licenciement pour motif économique de moins de 10 salariés durant une période de trente jours, doit convoquer chaque salarié à un entretien préalable. La convocation, envoyée par lettre recommandée avec accusé de réception ou remise en main propre contre signature, doit parvenir à l’intéressé au moins 5 jours ouvrables avant l’entretien préalable. Ce modèle propose une telle convocation. ",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename":"entretien_préalable_au_licenciement_économique_de_moins_de_10_salariés_pendant_30_jours.docx"
  },
  {
    "titre": "Modèle : lettre de réclamation des documents de fin de contrat",
    "description": "À la rupture du contrat de travail, dans tous les cas de rupture: l'employeur doit  délivrer au salarié des documents ( ex: certificat de travail). Ce modèle permet au salarié de réclamer ces documents à l'employeur qui n'aurait pas satisfait à cette obligation ",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "reclamation_des_documents_de_fin_de_contrat.docx"
  },
  {
    "titre": "Modèle: Reçu pour solde de tout compte",
    "description": "Le solde de tout compte est un document obligatoire, remis en fin de contrat de travail. Il est établi par l’employeur et remis (contre reçu) au salarié qui quitte son emploi. Ce document est un modèle de reçu pour solde de tout compte. ",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "Recu_solde_de_tout_compte.docx"
  },
  {
    "titre": "Modèle : Demande d'accord du salarié pour le renouvellement de période d’essai",
    "description": "La période d’essai peut être renouvelée, si la branche le prévoit et si cette possibilité est inscrite dans le contrat de travail ou la lettre d’engagement. Dans ces conditions, ce modèle permet de demander le renouvellement du contrat de travail.",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "renouvellement_periode_essai_initiative_employeur.docx"
  },
   {
    "titre": "Modèle : Réponse à Signalement de harcèlement sexuel",
    "description": "L'employeur doit prendre toutes les mesures en vue de de prévenir les faits de harcèlement sexuel, y mettre un terme ou les sanctionner. Le modèle ci-après propose une réponse au salarié ayant signalé des faits de harcèlement sexuel en tant que victime ou témoin.  ",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "reponse_a_signalement_harcelement_sexuel.docx"
  },
  {
    "titre": "Modèle de rupture du contrat en période d’essai à l'initiative du salarié",
    "description": "Pendant la période d’essai, le contrat de travail peut être rompu librement par le salarié. Le salarié devra informer l'employeur et respecter un délai de prévenance avant de quitter ses fonctions. Le modèle ci-dessous permet au salarié d'avertir l'employeur de son intention de mettre fin à la période d'essai. ",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "Rupture_periode_d'essai_salarie.docx"
  },
  {
    "titre": "Modèle : Rupture de période d’essai à l'initiative de l'employeur",
    "description": "Pendant la période d’essai, le contrat de travail peut être rompu librement par l'employeur. Pour ce faire l'employeur devra informer le salarié et respecter un délai dit de prévenance avant de quitter effectivement ses fonctions. Le modèle ci-dessous permet à l'employeur d'avertir le salarié qu'il sera mis fin à la période d'essai.",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "Rupture_periode_d'essai_employeur.docx"
  },
   {
    "titre": "Modèle : Signalement de faits pouvant relever du harcèlement (moral ou sexuel)",
    "description": "L'employeur doit agir pour faire cesser ou sanctionner les faits relevant du harcèlement sexuel ou les agissements répétés de harcèlement moral. Ce modèle permet au salarié victime ou témoin de ces faits d’avertir l'employeur.  ",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "signalement_harcelement.docx"
  },
  {
    "titre": "Modèle : Signalement de harcèlement sexuel",
    "description": "L'employeur doit prendre toutes les mesures en vue de de prévenir les faits de harcèlement sexuel, les faire cesser ou les sanctionner. Le présent modèle permet à un salarié victime ou témoin d'une telle situation d'alerter l'employeur. ",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "signalement_harcelement_sexuel.docx"
  },
{
    "titre": "Modèle : réclamation de congés payés",
    "description": "L’employeur décide de l’ordre de départ des congés payés. Le salarié doit pouvoir prendre l’ensemble de ses congés dus. L’employeur ne peut pas les payer en lieu et place. Ce modèle de courrier permet de demander à l'employeur la prise des congés de droit.",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "reclamation_de_cp.docx"
  },
{
    "titre": "Modèle : lettre de réclamation des heures supplémentaires",
    "description": "Les heures travaillées au-delà de la durée légale (35 heures) ouvrent droit en plus du taux horaire, à une contrepartie soit sous la forme d'une majoration salariale  soit, en tout ou partie, à des contreparties sous forme de repos (repos compensateur équivalent). Ce modèle permet au salarié de demander le paiement des heures supplémentaires et le droit aux contreparties prévues ",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "reclamation_des_heures_sup.docx"
   },
{
       "titre": "Modèle : Demande de paiement de salaire",
    "description": "Tout salarié doit percevoir son salaire une fois par mois.Le modèle ci-après permet au salarié de demander voire d'exiger le paiement du salaire du en cas de non paiement de salaire. Le demandeur doit aussi garder une copie de ce courrier.",
     "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "demande_paiement_salaire.docx"
  },
   {
    "titre": "Modèle : Demande de dérogation à la durée minimale de travail pour un temps partiel",
    "description": "Le code du travail fixe une durée minimale de travail pour les salariés à temps partiel. Une convention de branche étendue peut prévoir une durée plus courte. Il peut être dérogé à cette règle : pour faire face à des contraintes personnelles, un cumul d’activité ou permettre à un étudiant de moins de 26 ans d’avoir une activité salariée pendant ses études. Le modèle ci-dessous propose cette de demande de dérogation.",
    "date_redaction": "01/01/2020",
    "source": "Ministère du Travail",
    "filename": "temps_partiel_demande_de_derogation_du_salarie.docx"
	
  },  

{
    "titre": "Modèle : Relevé d’heures supplémentaires",
    "description": "Les heures supplémentaires sont décomptées à la semaine et font l'objet de contreparties. Le document ci-après permet à l'appui d'une demande de réclamation des heures supplémentaires, de présenter le décompte des heures supplémentaires et les contreparties dues.",
       "date_redaction": "01/01/2020",
       "source": "Ministère du Travail",
    "filename": "tableau_recap_des_heures_supplementaires.docx"
  }
   
  ]

**Comment by jrduscher** [comment]
PR #2020

**Comment by lionelB** [comment]
closed by #2020
