### ISSUE TITLE
Changer l'ordre des simulateurs sur la page d'accueil

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1838]
Pour ne pas être accusé de faire que des trucs sur la rupture, on prend l'ordre suivant : 
- Modèles de courriers
- Votre convention collective
- Simulateur d'embauche
- Simulateur de durée de préavis de démission
- Simulateur d'indemnités de licenciements
- Simulateur de durée de préavis de licenciement
- Simulateur de prime de précarité

**Comment by revolunet** [comment]
Pour la recherche CC, histoire d'uniformiser avec les autres outils, est-ce qu'on peut rempalcer la modale par un lien classique (et donc une page vide avec l'outil dedans)

**Comment by ClementChapalain** [comment]
oui ce serait top ! comme ça on peut la partager simplement aussi ! tu peux faire ça dans cette tâche ?

**Comment by revolunet** [comment]
right now
