### ISSUE TITLE
Forcer l'affichage de la date sur les impressions

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1839]
Aujourd'hui une option navigateur permet de supprimer l'affichage de la date, et cette date est celle de l'ordinateur donc potentiellement fausse.

Il faut afficher une date + heure dont on est certain sur toutes les impressions (dans le header à côté du logo CDTN par exemple).

**Comment by lionelB** [comment]
n'importe qui peut "éditer" le html et mettre la date qui lui fait plaisir avant d'imprimer. Quel est le but d'avoir cette date ?

**Comment by ClementChapalain** [comment]
Dans certains navigateurs, la date n'est pas ajoutée par défaut (cf. les tests de @virginielastisneres) du coup c'est plus pour éviter ça que des potentiels tricheurs qui de toute façon trouveront toujours un moyen de changer la date

**Comment by nkrmr** [comment]
cf: #1904
