### ISSUE TITLE
Màj glossaire

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1848]
@virginielastisneres prépare une mise à jour des données du glossaire, il faudra récupérer les nouvelles données dès que c'est ok niveau métier

**Comment by jrduscher** [comment]
les étduaints de M1 de la Sorbonne suggèrent l'ajout:
-" harcèlement", 
- harcèlement moral, 
- harcèlement sexuel,
-PSE

**Comment by virginielastisneres** [comment]
**MENTION OBLIGATOIRE :** 

Il faut ajouter la mention suivante sur la page du glossaire : 

« Les définitions de ce glossaire, disponibles en surbrillance dans les textes des réponses, ont pour objectif d’améliorer la compréhension des termes juridiques. Elles ne se substituent pas à la définition juridique exacte de ces termes. »

Si vous savais pas où la rajouter je propose de faire comme cela, comme pour les pages outils, modèles 
![6-Hub-Themes (1)](https://user-images.githubusercontent.com/48682104/70078137-7496b180-1602-11ea-90df-c5d06de799e8.jpg)

**Comment by lionelB** [comment]
c'est trop bo

**Comment by UnbearableBear** [comment]
I take it

**Comment by virginielastisneres** [comment]
Arrive très bientôt le fichier des définitions modifiées. 
A voir est ce que je dois remplacées les définitions une par une dans le datafiller ou cela peut se faire de manière automatique avec l'excel directement.

**Comment by UnbearableBear** [comment]
Je prend le nouveau design avec le wording mais pas la mise à jour des infos du glossaire par contre :o

**Comment by virginielastisneres** [comment]
ahah :D d'acc !

**Comment by virginielastisneres** [comment]
Fichier des définitions revues suite aux retours des agents de la DGT : https://docs.google.com/spreadsheets/d/1qa4UmebIg9br_-OkmDyBU13-RjN53onr/edit#gid=959426034

**Comment by lionelB** [comment]
@virginielastisneres c'est possible de le mettre directement dans le datafiller ?

**Comment by virginielastisneres** [comment]
@lionelB si cela vous permet de gagner du temps, je le fais :)

**Comment by virginielastisneres** [comment]
READY TO DEV @lionelB 
Le glossaire dans le datafiller est modifié :)
