### ISSUE TITLE
Theming modeles et outils

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#1854]
- [ ] dans la page modèles de lettres, classer les modèles par thème puis selon l'ordre du JSON
 - [ ] créer un script update-themes pour les modèles
 - [ ] créer un script update-themes pour les outils
 - [ ] ajouter breadcrumbs aux modèles et outils

**Comment by revolunet** [comment]
Complète la #1837

**Comment by jrduscher** [comment]
-> les modèles sont tous thémés dans le df ( c'était déjà le cas)

**Comment by lionelB** [comment]
@revolunet je ferme car on du breadcrumb partout et le sélecteur de theme sur la page courrier a aussi été rajouté
