### ISSUE TITLE
Contributions : faire un lien quand le contenu est récupéré depuis SP ou MT et supprimer les fiches correspondantes

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1859]
## supprimer les fiches intégrées dans les contributions

Si elles sont intégrées dans les contributions, alors pas besoin de les avoir une deuxième fois indexée (car la question est la même).

Du coup il faudrait supprimer les fiches suivantes : 
- https://www.service-public.fr/particuliers/vosdroits/F317
- https://www.service-public.fr/particuliers/vosdroits/F34414
- https://www.service-public.fr/particuliers/vosdroits/F1910
- https://www.service-public.fr/particuliers/vosdroits/F38
- https://www.service-public.fr/particuliers/vosdroits/F36
- https://www.service-public.fr/particuliers/vosdroits/F31897
- https://www.service-public.fr/particuliers/vosdroits/F31897
- https://www.service-public.fr/particuliers/vosdroits/F1945
- https://www.service-public.fr/particuliers/vosdroits/F2855
- https://www.service-public.fr/particuliers/vosdroits/F2614
- https://www.service-public.fr/particuliers/vosdroits/F13965
- https://www.service-public.fr/particuliers/vosdroits/F2265
- ~https://travail-emploi.gouv.fr/droit-du-travail/les-absences-pour-maladie-et-conges-pour-evenements-familiaux/article/les-conges-pour-evenements-familiaux~
- https://www.service-public.fr/particuliers/vosdroits/F2405
- https://www.service-public.fr/particuliers/vosdroits/F13887

## ajouter le lien vers la fiche lorsqu'on récupère le contenu d'une fiche dans les contributions

Entre "Que dit  le code du travail ?" et le texte récupéré, on met le lien vers la fiche correspondante, en utilisant le design déjà utilisé pour les fiches classiques : 
![image](https://user-images.githubusercontent.com/5337489/70330286-9334bc80-183d-11ea-97d2-ec479528bd2f.png)

**Comment by lionelB** [comment]
je vois plusieurs soucis pour l'instant. 
- Les références du texte original (fiche SP, fiche Mt) sont présente dans le texte mais pas de manière formatée.
- Dans le cas d'une fiche MT pour laquelle on indexe chaque paragraphe, il faudrait supprimer toute la fiche ou seulement le paragraphe ? 

cas intéressant: la recherche https://code.travail.gouv.fr/recherche?q=les%20cong%C3%A9s%20pour%20%C3%A9v%C3%A9nements%20familiaux
la contrib fait référence à une fiche SP et on présente tout les paragraphes (meme ceux sans titre)

**Comment by ClementChapalain** [comment]
je ne comprends pas ça : 
> Les références du texte original (fiche SP, fiche Mt) sont présente dans le texte mais pas de manière formatée.

pour ça : 
> Dans le cas d'une fiche MT pour laquelle on indexe chaque paragraphe, il faudrait supprimer toute la fiche ou seulement le paragraphe ?

On a qu'une seule fiche MT utilisée dans les contributions, et on utilise toute la fiche, donc je pense qu'on peut supprimer tous les paragraphes

**Comment by lionelB** [comment]
Au sujet des données, les références sont faite dans le markdown, il faut donc les extraires en parsant le contenu du champ markdown pour pouvoir les ensuite les utiliser

Au sujet de la fiche MT je ne la trouve pas, c'est quelle contribution ?

**Comment by ClementChapalain** [comment]
ok ! 
c'est celle là : 
- la fiche MT : https://travail-emploi.gouv.fr/droit-du-travail/les-absences-pour-maladie-et-conges-pour-evenements-familiaux/article/les-conges-pour-evenements-familiaux
- la fiche MT chez nous https://code.travail.gouv.fr/fiche-ministere-travail/les-conges-pour-evenements-familiaux 
- la contrib https://code.travail.gouv.fr/contribution/les-conges-pour-evenements-familiaux

**Comment by ClementChapalain** [comment]
En fait la fiche sur les congés pour événement familiaux a été réécrite donc elle n'est plus récupérée depuis MT donc plus besoin de l'enlever, désolé pour le contretemps !
