### ISSUE TITLE
Faute d'orthographe dans la description google

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1866]
personalisée -> personnalisée 

C'est ce qui est utilisé la description de google...
![image](https://user-images.githubusercontent.com/5337489/69997377-54a8b480-1554-11ea-8215-0964964e5c3b.png)

https://github.com/SocialGouv/code-du-travail-numerique/blob/238be0c8ac5278a6887a555ce5211c8b25864a09/packages/code-du-travail-frontend/pages/recherche.js#L46
https://github.com/SocialGouv/code-du-travail-numerique/blob/238be0c8ac5278a6887a555ce5211c8b25864a09/packages/code-du-travail-frontend/pages/index.js#L20

**Comment by UnbearableBear** [comment]
C'est beau :')
