### ISSUE TITLE
Les outils ne sont plus proposés en outils annexes ?

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#1869]
Il semblerait que les outils ne remontent jamais en contenus annexes ?

**Comment by ClementChapalain** [comment]
bien vu

**Comment by ClementChapalain** [comment]
en fait si : http://master.code-du-travail-numerique.dev.factory.social.gouv.fr/fiche-service-public/percoit-on-des-indemnites-en-cas-de-licenciement-pour-inaptitude-physique?q=licenciement%20indemnit%C3%A9
