### ISSUE TITLE
API: prevent duplicate related items

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#1874]
Suite à #1672 : dans les related items renvoyés par l'API, s'assurer que le document en cours n'est pas renvoyé

**Comment by ClementChapalain** [comment]
hello @revolunet @lionelB ! @virginielastisneres  a trouvé un cas où on a toujours le pb : 
https://master-code-travail.dev.fabrique.social.gouv.fr/modeles-de-courriers/modele-convocation-a-un-entretien-prealable-au-licenciement-pour-motif-personnel

**Comment by lionelB** [comment]
hum c'est pas le meme probleme. le document visualisé ne remontent ne pas dans les éléments proposés, par contre, on propose 2 fois un meme contenu dans les éléments proposés

**Comment by ClementChapalain** [comment]
ah oui tu as raison j'avais mal lu les 2 intitulés de docs

**Comment by ClementChapalain** [comment]
je vais faire une autre tâche sur ce pb (le contenu remonte 2 fois)

**Comment by ClementChapalain** [comment]
#2078

**Comment by lionelB** [comment]
merci pour l'issue
