### ISSUE TITLE
BUG : erreur dans le calcul du salaire de référence servant de base au calcul de l'indemnité légale de licenciement

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1880]
# 1. Bug calcul du salaire de référence  

Bug soulevé par jr en décembre 2019 et de nouveau par un usager aujourd'hui.

## Ce que dit le code du travail 

Le salaire de référence se calcule ainsi : _Le salaire à prendre en considération pour le calcul de l'indemnité est :_
- _le douzième de la rémunération des 12 derniers mois **précédant le licenciement**. Lorsque la durée au sein de l'entreprise est inférieure à 12 mois, il faut prendre la moyenne mensuelle de la rémunération de l'ensemble des mois précédant le licenciement ;_
- _ou, si cela est plus avantageux pour le salarié, le tiers des 3 derniers mois, étant entendu que, dans ce cas, toute prime ou gratification de caractère annuel ou exceptionnel, qui aura été versée au salarié pendant cette période, ne sera prise en compte que dans la limite d'un montant calculé prorata temporis._

Il est bien préciser le 12ème de la rémunération des 12 derniers mois **PRECEDANT LE LICENCIEMENT**

## Ce que fait le CDTN 

J'ai indiqué pour l'exemple : 
- à la date d'entrée dans l'entreprise : 02/01/2014
- à la date de notification du licenciement : 09/02/2019
- à la date de sortie de l'entreprise : 07/06/2019

Voici ce que l'on me demande de remplir une fois après avoir indiqué que je n'ai pas eu le même salaire les 12 derniers mois voici ce qui met proposé de remplir : 
![Capture d’écran 2020-12-09 à 15 21 19](https://user-images.githubusercontent.com/48682104/101641665-5132ed80-3a32-11eb-8526-86b104dd57f5.png)

Rappel le code du travail dit "la rémunération des 12 derniers mois **PRECEDANT** LE **LICENCIEMENT**

Donc, il y a 2 erreurs ici : 

1. On ne fait **PAS** le mois **PRECEDANT** : On est ici sur les 12 derniers mois suite au départ de l'entreprise (07/06/2019) EN INCLUANT LE MOIS DU DEPART DE L'ENTREPRISE : juin 2019. 
Ce n'est donc pas les 12 derniers mois **précédant**. Le mois précédant serait ici mai 2019. 

2. On ne fait **PAS** le mois précédant **LE LICENCIEMENT** : On est ici sur les 12 derniers mois  au départ de l'entreprise (juin 2019) et non précédant le licenciement (licenciement = date de notification du licenciement, soit ici février 2019). 

# Solution attendue 

Il faut demander les 12 derniers mois en partant du MOIS PRECEDANT le mois indiqué pour la date de notification du licenciement (réponse à la question n°2 et non n°3) 

Dans l'exemple ici il aurait fallu partir de la date de notification du licenciement : 09  fev. 2019
![Group 830](https://user-images.githubusercontent.com/48682104/101749232-cc95ad00-3acd-11eb-9482-9d15d8537da0.png)

# 2. Affiner la question du salaire de référence 

Dans l'étape 4 de l'outil "Salaires", remplacer la question "Le salaire mensuel a-t-il été le même durant les 12 derniers mois ?" par "Le salaire mensuel brut a-t-il été le même durant les 12 derniers mois précédant la notification du licenciement ?"

**Comment by lionelB** [comment]
> "lorsque la durée de service du salarié est inférieure à douze mois, la moyenne mensuelle de la rémunération de l'ensemble des mois précédant le licenciement ;" En dessous de 12 mois d'ancienneté, on devrait ne proposer que le nombre de mois correspondants".

c'est le cas vu on propose que 11mois  ?

**Comment by jrduscher** [comment]
Modifiée ce jour.

**Comment by virginielastisneres** [comment]
@jrduscher j'ai mis l'issue dans le planning
