### ISSUE TITLE
MAJ data fiches-sp

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#189]
Il y a en fait deux sources de données pour ls fiches s-p :

 - particuliers https://www.data.gouv.fr/fr/datasets/service-public-fr-guide-vos-droits-et-demarches-particuliers/
 - pros : https://www.data.gouv.fr/fr/datasets/service-public-fr-guide-vos-droits-et-demarches-professionnels-entreprises/

Il faudrait intégrer les deux, ceci devrait corriger le pb de liens qui étaient HS !

**Comment by jrduscher** [comment]
on n'arrive pas à voir si les fiches professionnels ont bien été integrées. A voir avec la partie dev pour la recette. A voir aussi la suite: affichage et discriminant:
https://trello.com/c/bKPxzsbZ/327-comment-distinguer-les-fiches-services-public-salari%C3%A9-et-employeur-et-%C3%AAtre-s%C3%BBr-quelles-sont-differentes

**Comment by revolunet** [comment]
ca a été fait ici : https://github.com/SocialGouv/code-du-travail-numerique/pull/268

**Comment by revolunet** [comment]
exemple fiche pro : https://codedutravail-dev.num.social.gouv.fr/fiche-service-public/fermeture-dun-etablissement-obligation-de-rechercher-un-repreneur?q=Fermeture%20d%27un%20%C3%A9tablissement%20%3A%20obligation%20de%20rechercher%20un%20repreneur&search=0
