### ISSUE TITLE
Bug front dans carte résultats de recherche

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#1891]
**Description**
C'est pas beau :) j'ai vu cela que dans cette carte pour le moment
https://code.travail.gouv.fr/recherche?q=ligne%20ou%20installation%20%C3%A9lectrique

![image](https://user-images.githubusercontent.com/48682104/70262088-f833d800-1793-11ea-8c14-fa352890693b.png)

**Comment by lionelB** [comment]
je ferme, le bug a été corrigé, il me semble
