### ISSUE TITLE
Bug front dans page ministère lien url

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#1892]
**Description**
bug un lien url s'affiche pas bien dans prod et master : http://master.code-du-travail-numerique.dev.factory.social.gouv.fr/fiche-ministere-travail/le-salaire-fixation-et-paiement?q=salaire%20conventionnel#Comment-est-fixe-le-salaire-de-base

![image](https://user-images.githubusercontent.com/48682104/70263383-7db88780-1796-11ea-826a-015d868b9385.png)

**Comment by lionelB** [comment]
duplicate de #1733
