### ISSUE TITLE
navigation outils mobile

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1895]
En mobile, au démarrage d'un simulateur ( préavis démission) depuis la page d'accueil ou la boite à outils  l'user tombe nez à nez avec le footer de la page. En mobile, on aurait l'impression que lapge ne s'est pas chargée..

**Comment by ClementChapalain** [comment]
on arrive pas à reproduire avec @jrduscher du coup je ferme :)
