### ISSUE TITLE
filtres à construire: durée du travail

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#19]
je ne pense pas que ce soit la version définitive. Mais si ça ne te fais pas perdre de temps de commencer avec ça; sinon je revois ma copie plus vite.

"Votre mode d'organisation ou de répartition de la durée du travail"

Ordre attendu des propositions:
- période hebdomadaire, travail à temps plein
- période supérieure à la semaine
- forfait

- travail à temps partiel
- travail intermittent
- autres

période supérieure   à la semaine

période supérieure   à la semaine | 19700 | Durée du travail et congés > Durée du   travail > Aménagement Temps de Travail > Horaires individualisés et   récupération des heures perdues
-- | -- | --
période supérieure à la semaine | 19600 | Durée du travail et congés > Durée du travail > Aménagement Temps   de Travail > Période supérieure à la semaine
commun | 19800 | Durée du travail et congés > Durée du travail > Astreintes, travail   effectif et équivalences > Astreintes
commun | 20500 | Durée du travail et congés > Durée du travail > Astreintes, travail   effectif et équivalences > Equivalences
commun | 21700 | Durée du travail et congés > Durée du travail > Astreintes, travail   effectif et équivalences > Travail effectif
commun | 20000 | Durée du travail et congés > Durée du travail > Décompte de la   durée du travail
commun | 20300 | Durée du travail et congés > Durée du travail > Durée légale   "35 heures"
commun | 20400 | Durée du travail et congés > Durée du travail > Durée maximale du   travail > Par jour
commun | 20200 | Durée du travail et congés > Durée du travail > Durée maximale du   travail > Par semaine
forfait | 20100 | Durée du travail et congés > Durée du travail > Forfait
période hebdomadaire, temps plein | 20310 | Durée du travail et congés > Durée du travail > Heures   supplémentaires > Règles générales en matière d'heures supplémentaires
période hebdomadaire, temps plein | 20340 | Durée du travail et congés > Durée du travail > Heures   supplémentaires > Règles spécifiques en cas d'accord d'entreprise ou de   convention collective > Cas des travailleurs saisonniers
période hebdomadaire, temps plein | 20330 | Durée du travail et congés > Durée du travail > Heures   supplémentaires > Règles spécifiques en cas d'accord d'entreprise ou de   convention collective > Contreparties aux heures supplémentaires
période hebdomadaire, temps plein | 20320 | Durée du travail et congés > Durée du travail > Heures   supplémentaires > Règles spécifiques en cas d'accord d'entreprise ou de   convention collective > Définition de la semaine
période hebdomadaire, temps plein | 20360 | Durée du travail et congés > Durée du travail > Heures   supplémentaires > Règles spécifiques en l'absence d'accord ou de   convention > Contreparties aux heures supplémentaires
période hebdomadaire, temps plein | 20370 | Durée du travail et congés > Durée du travail > Heures   supplémentaires > Règles spécifiques en l'absence d'accord ou de   convention > Contreparties: Dépassement de la limite annuelle du nombre   d'heures supplémentaires
période hebdomadaire, temps plein | 20350 | Durée du travail et congés > Durée du travail > Heures   supplémentaires > Règles spécifiques en l'absence d'accord ou de   convention > Définition de la semaine
commun | 20700 | Durée du travail et congés > Durée du travail > Jours fériés
autres | 20800 | Durée du travail et congés > Durée du travail > Outre - mer >   Dispositions générales
autres | 20800 | Durée du travail et congés > Durée du travail > Outre - mer >   DOM, Saint Barthélemy, Saint - Martin, St Pierre et Miquelon
commun | 21300 | Durée du travail et congés > Durée du travail > Repos et temps de   pause > Repos hebdomadaire
commun | 21100 | Durée du travail et congés > Durée du travail > Repos et temps de   pause > Repos quotidien
commun | 21200 | Durée du travail et congés > Durée du travail > Repos et temps de   pause > Repos, jours fériés Moselle, Bas - Rhin, Haut - Rhin
commun | 21400 | Durée du travail et congés > Durée du travail > Repos et temps de   pause > Temps de pause
temps partiel | 21500 | Durée du travail et congés > Durée du travail > Temps partiel et   travail intermittent > Temps partiel
commun| 21600 | Durée du travail et congés > Durée du travail > Temps partiel et   travail intermittent > Travail de nuit
commun | 21800 | Durée du travail et congés > Durée du travail > Temps partiel et   travail intermittent > Travail intermittent
commun| 21000 | Durée du travail et congés > Durée du travail > Travail du dimanche

**Comment by ClementChapalain** [comment]
@jrduscher j'ai l'impression que cette issue est relative à l'ancienne version du produit avec le choix de filtres qu'on imposait à l'utilisateur, est-ce que c'est bien ça ?

Si oui est-ce que le contenu du tableau pourra potentiellement nous être utile encore ? Si oui je vais le déplacer dans le wiki

**Comment by jrduscher** [comment]
il s'est passé un certain nombre de choses en matière de filtres depuis... dont ce que tu évoques. Pour autant, vu le sujet évoqué, ce truc là pourrait encore servir si on se souvient qu'il existe...

**Comment by ClementChapalain** [comment]
ok merci ! je déplace le contenu dans la rubrique générale sur le droit du travail ici :
https://github.com/SocialGouv/code-du-travail-numerique/wiki/%5BDroit-du-travail%5D%C2%A0Organisation-de-la-dur%C3%A9e-du-travail
