### ISSUE TITLE
Bug : sélectionner une CCN dans les outils renvoie à un message CCN non traitée

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1901]
Des utilisateurs d'une organisation professionnelle employeur ( ils n'ont jamais testé l'outil ) nous remonte l'anomalie ci -après, qui a pu être reproduite.

ici avec la CC  transport 0016 
![image](https://user-images.githubusercontent.com/37538697/70323299-ba36c280-182c-11ea-8fd1-31f6dbef1cf3.png)

en tapant l'idcc ou le nom,le parcours est bloqué ou non
![image](https://user-images.githubusercontent.com/37538697/70323384-ed795180-182c-11ea-8f11-0cc73d6984e7.png)

**Comment by ClementChapalain** [comment]
on a toujours le pb sur les contributions, avec par exemple cette contribution http://master.code-du-travail-numerique.dev.factory.social.gouv.fr/contribution/quelle-est-la-duree-maximale-de-la-periode-dessai-sans-et-avec-renouvellement et la CC "commerce de gros"
