### ISSUE TITLE
Afficher le thème des fiches MT dans les résultats de recherche

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1919]
cette fiche par exemple : 
![image](https://user-images.githubusercontent.com/5337489/70443450-77792280-1a98-11ea-884d-c65276ba3b84.png)

nous n'affichons pas le thème alors qu'elle est bien thémée comme on peut le voir quand on clique dessus : 
![image](https://user-images.githubusercontent.com/5337489/70443506-8d86e300-1a98-11ea-9441-6f39c57d5f02.png)

**Comment by ClementChapalain** [comment]
too quick
![image](https://user-images.githubusercontent.com/5337489/70443708-e6567b80-1a98-11ea-9fbc-b546f8e0d682.png)

**Comment by UnbearableBear** [comment]
Alors c'est pas parce que je les prends vite que je vais les faire vite par contre haha

**Comment by lionelB** [comment]
@UnbearableBear Autant la laissé dispo alors et s'assigner les issues quand on a de la bande passante pour les traiter, non ?

**Comment by UnbearableBear** [comment]
@lionelB Yes c'était une blague t'inquiète. Si je la prend c'est que ça me concerne et que je peux m'en occuper rapidement avant la fin du sprint. Ca me sert aussi pour filtrer les issues que je peux prendre de me taguer dessus. Mais je ne le ferai plus à partir du moment ou l'UI est terminée
