### ISSUE TITLE
wording thèmes

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#192]
1) Navigation par thèmes: 
a) wording.
- titres: les titres sont à revoir : 
-sous titres: On ne peut pas mettre en ligne avec les sous titres actuels. le wording est à faire.

-proposition:
*  embauche et exécution du contrat de travail ou  contrat de travail et embauche
             
               sous titre proposition: obligations liés à l'embauche

  * Rupture du contrat de travail: 
                                 sous titre proposition : Licenciement, démission, rupture conventionnelle...
=> (contrat de travail, pas contrat simple)
* Rémunération:
                sous titre proposition: Salaire, primes, avantages, bulletin de salaire
* Santé et sécurité au travail: 
      
              sous titre proposition : conditions de travail, surveillance médicale, pénibilité
* Durée du travail et congés:
   
               sous titre proposition: heures supplémentaires, congés payés, durée maximale du travail
* maladie et inaptitudes: maladie et inaptitude.

                  sous titre proposition : l'inaptitude, procédure, contentieux, arrêts de travail...
*Formation: à supprimer  ( pas nécessaire pour le moment pour l'outil)
*Dialogue social: ( suppression possible. dans quelques sprints)

                   sous titre proposition : représentants du personnel et négociation

* proposition de thème : contentieux et coercitif
                   
                   sous titre proposition: prud’hommes, la prescription, volet pénal, l'inspection du travail

**Comment by lionelB** [comment]
le fichier a été mis à jour coté ES mais doit être exposé coté front pour éviter d'avoir a maintenir une copie dans le source du front
- via une api (mais risque de faire une requête à chaque hit sur l'index
- récupérer au moment du build du site ?

@revolunet je penche pour la deuxieme solution mais en mode `dev`on risque d'avoir des soucis de synchro
