### ISSUE TITLE
Liens dans les contenus: des erreurs 404 et 500

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1928]
# Erreur 404: 
https://code.travail.gouv.fr/fiche-service-public/accueil-dun-enfant-par-une-assistante-maternelle-agreee?q=assistant

![image](https://user-images.githubusercontent.com/37538697/70533284-149b9000-1b59-11ea-96e3-08d0484ae40a.png)
Le lien de la convention collective renvoie une erreur 404. 

 L'URL de ce lien " https://code.travail.gouv.fr/convention-collective/KALICONT000005635807"

# Erreur 500 : 

dans la page suivante:
https://code.travail.gouv.fr/code-du-travail/l1235-14?q=L1235-14
![image](https://user-images.githubusercontent.com/37538697/70533464-6f34ec00-1b59-11ea-94e6-2100d6854a03.png)

Si on clique sur l'un des articles, comme le L1235-11, on obtient une erreur 500. Le lien qui pose problème est constitué comme suit : "https://code.travail.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006072050&idArticle=LEGIARTI000035643497&dateTexte=&categorieLien=id"

### Dans les deux cas: 
> Paradise: renvoyer vers les liens en interne :
  page CCN pour le premier cas,
 page de l'article du code dans le 2ème : https://code.travail.gouv.fr/code-du-travail/l1235-11?q=L1235-11

**Comment by revolunet** [comment]
@ClementChapalain je te laisse close si fixé

**Comment by ClementChapalain** [comment]
yeah !

**Comment by lionelB** [comment]
need moar investigation and test 
https://master-code-travail.dev.fabrique.social.gouv.fr/code-du-travail/l1243-1?q=d%C3%A9mission%20cdd

**Comment by revolunet** [comment]
Ce cas a été traité, on reopen si on en voit d'autres

**Comment by revolunet** [comment]
Exclure les codes tiers : https://master-code-travail.dev.fabrique.social.gouv.fr/code-du-travail/l1242-2

**Comment by ClementChapalain** [comment]
je dépriorise si c'est juste pour les articles des autres codes

**Comment by jrduscher** [comment]
Les liens pointant  vers **des** articles code du travail dans le texte d'un article  du code 
![image](https://user-images.githubusercontent.com/37538697/71915237-993ef580-317b-11ea-83c6-f8ce1b444295.png)
autre exemple similaire
https://master-code-travail.dev.fabrique.social.gouv.fr/code-du-travail/l1251-58-3?q=r4323-58

nb: on notera avec un plaisirs non dissimulé que les 3 liens vers des articles cités dans ce texte fonctionnent bien https://master-code-travail.dev.fabrique.social.gouv.fr/code-du-travail/r4323-62?q=r4323-58

### solutions envisageables ?
-faire pointer le lien vers le premier article de la série citée
-à défaut: renvoyer vers legifrance en corrigeant l'url:

(ex: en remplacant "https://master-code-travail.dev.fabrique.social.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006072050&idArticle=LEGIARTI000006902832&dateTexte=&categorieLien=ci

par: https://legfrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006072050&idArticle=LEGIARTI000006902832&dateTexte=&categorieLien=cid
