### ISSUE TITLE
Les paragraphes HDN ne s'affichent plus dans les contributions qui récupèrent du contenu MT ou SP

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1940]
par exemple ici : http://master.code-du-travail-numerique.dev.factory.social.gouv.fr/contribution/arret-maladie-pendant-la-periode-dessai-quelles-sont-les-regles?q=arr%C3%AAt%20maladie%20p%C3%A9riode%20d%27essai

on devrait avoir la fiche SP et un § sur la hiérarchie des normes : 
https://contributions.codedutravail.num.social.gouv.fr/admin/generic-answers/ccac1236-f435-4869-87a6-220bbd558076

![image](https://user-images.githubusercontent.com/5337489/70610025-20439100-1c03-11ea-964a-004f919b13c5.png)

le paragraphe dans les balises HDN ne s'affiche plus

**Comment by nkrmr** [comment]
Après investigation il faut fermer la balise *Content* il faut passer de :
```
<Content href="https://www.service-public.fr/particuliers/vosdroits/F317" />`
```
à
```
<Content href="https://www.service-public.fr/particuliers/vosdroits/F317"></Content>`
```
Afin que rehype-react puisse remplacer par notre composant React

**Comment by ClementChapalain** [comment]
c'est bon @nkrmr je viens de changer, tu peux vérifier si ça marche bien stp ?

**Comment by revolunet** [comment]
cf #2068

**Comment by nkrmr** [comment]
@ClementChapalain c'est bon pour moi, à part le bug remonté par Julien sur les tabs #2070 que je vais checker sur une autre issue

**Comment by ClementChapalain** [comment]
Ok super merci à vous deux !
