### ISSUE TITLE
Bug on build monorepo image

### ISSUE THREAD

**Issue by nkrmr** [SocialGouv/code-du-travail-numerique#1941]
**Description**
En utilisant `docker-compose.override.dev.yml`  et en lançant la commande :

```
# Build the monorepo image
$ docker build . -t cdtn_master:local
```
J'obtiens le message d'erreur suivant : 

![Screenshot 2019-12-11 at 09 53 19](https://user-images.githubusercontent.com/686395/70612746-cbeee000-1c07-11ea-91fb-79438e41170a.png)

Il semblerait que le package git 2.22.0-r0 ne serait pas compatible avec node:10.17.0-alpine3.10 dans le Dockerfile lorsqu'on execute cette commande : 

```
FROM node:10.17.0-alpine3.10

# NOTE(douglasduteil): add `curl` in the master image
# `curl` is very useful for later health check tests ;)
RUN apk add --no-cache --update git=2.22.0-r0 curl=7.66.0-r0
```

**Comment by lionelB** [comment]
done in #1965
