### ISSUE TITLE
la couleur du bouton de rechercher au rollover à disparu

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#195]
probablement lié au fait que https://github.com/jonathantneal/postcss-color-mod-function ne soit plus sorti de https://cssdb.org/#staging-process

**Comment by jrduscher** [comment]
[ recette/revue]dans la version dev une seule couleur, dans la prod ok ??

**Comment by revolunet** [comment]
je l'ai chez moi, même sur dev.

**Comment by lionelB** [comment]
closed by #238
