### ISSUE TITLE
Exclusions de certaines fiches SP qui sont hors-sujet

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#196]
comment identifier les fiches hors sujet ( enfants handicapés le contenu ne parle pas de travail à aucun moment)

**Comment by revolunet** [comment]
Proposition :
 - on liste les themes proposés SP et détectés par notre script
 - tu nous dis lesquels à exclure ?

**Comment by jrduscher** [comment]
Ca me va!

**Comment by ClementChapalain** [comment]
done in sprint 11
