### ISSUE TITLE
Màj disclaimers

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1960]
- [x] Disclaimer préavis de démission
- [ ] lien préavis de démission
- [ ] Disclaimer préavis de licenciement

# Outils de préavis de démission

## Disclaimer

Le disclaimer qui s'affiche sous le résultat 
![image](https://user-images.githubusercontent.com/37538697/70805482-4f036800-1db9-11ea-81ef-8a68521318bd.png)

Remplacer :
"Une durée de préavis de licenciement plus favorable au salarié peut aussi être prévue dans un accord d'entreprise, le contrat de travail ou un usage dans la localité ou la profession"
par
"Une durée de préavis de démission plus favorable au salarié peut aussi être prévue dans une convention ou un accord au niveau de l'entreprise"

## Référence

Ajouter la référence juridique dans la section source (en bas de la page) :
Article L.1237-1 du code du travail https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006072050&idArticle=LEGIARTI000006901174

# Outil de préavis de licenciement

![image](https://user-images.githubusercontent.com/37538697/70806852-81fb2b00-1dbc-11ea-949c-6ad8621af622.png)

Une distinction doit se faire dans le disclaimer en fonction de l'ancienneté légale (en raison du texte de l'article [L1234-1](https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000006901112&cidTexte=LEGITEXT000006072050&dateTexte=20080501))
- si durée du préavis légal = 0
  - et durée du préavis CCN = 0
"La durée de préavis de licenciement peut aussi être prévue dans une convention ou un accord au niveau de l'entreprise, ou à défaut par les usages pratiqués dans la profession."
  - et durée du préavis CCN > 0
"La durée de préavis de licenciement peut aussi être prévue dans une convention ou un accord au niveau de l'entreprise."
- si durée du préavis légal > 0
"Une durée de préavis de licenciement ou une condition d'ancienneté plus favorable au salarié peut être prévue dans un accord d'entreprise, le contrat de travail ou les usages."

_(explication sur la distinction : pour le premier et le second  cas le recours aux usages est possible à défaut, càd dans le silence des textes de loi, de la ccn et de l'accord. Dans le troisième cas l'usage plus favorable s'applique au salarié)_

**Comment by ClementChapalain** [comment]
\+  corriger la regression qui fait qu'on ne peut plus continuer sans CC : #1961

**Comment by lionelB** [comment]
> * "La durée de préavis de licenciement peut aussi être prévue dans une convention ou un accord au niveau de l'entreprise, ou à défaut par les usages pratiqués dans la profession."

pour info cette situation n'existe pas encore
