### ISSUE TITLE
Poursuite si pas de CCN : préavis de licenciement, préavis de démission

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#1961]
Aujourd'hui pour ces 2 outils, le parcours utilisateur est conditionné au choix de la CC.
Un message existe pour la CC non trouvée, le parcours se poursuit mais l'user peut ne pas avoir de CC dans son entreprise ou ne pas vouloir choisir de CC.

### dans l'outil de préavis de démission

À la sélection de la CC, permettre la poursuite de la navigation sans avoir choisi une CC avec "suivant" et afficher le message suivant dans la même page :

> Le code du travail ne prévoyant pas de durée précise du préavis de démission, nous vous invitons à consulter le contenu de la convention collective. 
Par ailleurs, un accord collectif d'entreprise peut prévoir une durée de préavis de démission différente, qu'elle soit inférieure ou supérieure.
 Dans ce cas la durée de préavis de démission prévu par l'accord au niveau de l’entreprise s'applique.
> Référence : [article L1237-1 du code du travail](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006072050&idArticle=LEGIARTI000006901174)

### dans l'outil de préavis de licenciement

À la sélection de la CC, permettre la poursuite de la navigation sans avoir choisi une CC avec "suivant" et afficher le message suivant dans la même page : 

> Le code du travail  prévoit une de préavis de **[durée de préavis légal]**
> _si durée du préavis légal = 0_
> L'existence et la durée du préavis de licenciement  peut être prévue dans la convention collective, un accord d’entreprise ou à défaut par un usage dans l’entreprise.
> _si durée du préavis légal > 0_
> Une durée de préavis de licenciement ou une condition d'ancienneté plus favorable au salarié peut être prévue par une convention collective, un accord de branche,  un accord d'entreprise ou le contrat de travail ou les usages.
> Référence : [article L1234-1 du code du travail](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006072050&idArticle=LEGIARTI000006901174)

## Visuellement

On peut reprendre le design de l'alerte quand la CC n'est pas traitée
![image](https://user-images.githubusercontent.com/5337489/71008521-07e2e300-20e9-11ea-8be0-dbd8db806190.png)

**Comment by ClementChapalain** [comment]
Je ne vois pas bien l'amélioration par rapport à la version actuelle ? Tu proposes d'ajouter une page plutôt que de mettre les informations dans un bloc sur la page de sélection de la convention collective

**Comment by lionelB** [comment]
note : le champ CC ne doit pas être "required" pour pouvoir traiter l'erreur et bloquer le parcours

**Comment by jrduscher** [comment]
Préavis de démission.

L'user qui passe la sélection de la CC en appuyant sur suivant:
- arrive en page résultat
![image](https://user-images.githubusercontent.com/37538697/71898857-a5668b00-315a-11ea-87ca-88d7bbf4a27d.png)

Résultat: "Aucun résultat communicable: la branche n'a pas été renseignée"
Wording hierarchie..."La durée du préavis de démission est fixée :

Soit par une convention collective ou un accord collectif
Soit par les usages pratiqués dans la localité et dans la profession
Soit par le droit local (en Alsace-Moselle).

Votre contrat de travail peut prévoir un préavis de démission, qui s'applique si sa durée est plus courte que celle prévue par la convention collective, l'accord collectif ou les usages.

Si vous travaillez à temps partiel, la durée calendaire du préavis de démission est la même que celle d'un salarié à temps plein.". 
rappel fiche: [préavis de démision](https://master-code-travail.dev.fabrique.social.gouv.fr/contribution/quelle-est-la-duree-du-preavis-en-cas-de-demission?q=pr%C3%A9vis%20de%20d%C3%A9mission)

**Comment by lionelB** [comment]
> "Aucun résultat communicable: la branche n'a pas été renseignée"

le wording etait moins autere
> Le code du travail ne prévoyant pas de durée précise du préavis de démission, nous vous invitons à consulter le contenu de la convention collective. Par ailleurs, un accord collectif d’entreprise peut prévoir une durée de préavis de démission différente, qu’elle soit inférieure ou supérieure. Dans ce cas la durée de préavis de démission prévu par l’accord au niveau de l’entreprise s’applique.

**Comment by jrduscher** [comment]
ok avec toi, si on ajoute cette austère phrase à l'ancienne réponse: "Votre contrat de travail peut prévoir un préavis de démission, qui s'applique si sa durée est plus courte que celle prévue par la convention collective, l'accord collectif ou les usages."

**Comment by jrduscher** [comment]
### Préavis de démission:  Cas de la CCN non traitée par l'équipe:

résultat: Nous n’avons pas encore traité cette convention collective.  
Hiérarchie :

Le code du travail ne prévoit pas de durée précise du préavis de démission ( en dehors de certaines professions et cas particuliers): nous vous invitons à consulter le contenu de la convention collective.

un accord collectif d’entreprise peut prévoir une durée de préavis de démission différente, qu’elle soit inférieure ou supérieure. Dans ce cas la durée de préavis de démission prévu par l’accord au niveau de l’entreprise s’applique. 

Le contrat de travail peut lui aussi prévoir une durée de préavis de démission, qui s'applique si elle est durée est plus courte que celle prévue par la convention collective, l'accord collectif ou les usages.

**Comment by jrduscher** [comment]
### Préavis de licenciement: CCN non traitée

#### Pour le résultat : 
C’est la durée légale qui est affichée. Quand la durée est également à 0 c’est-à-dire quand l’ancienneté du salarié est inférieure à 6 mois, il faut afficher : 

« Aucun préavis. »

#### Bloc hiérarchie : 

si durée du préavis légal = 0
L'existence et la durée du préavis de licenciement peut être prévue par un accord d’entreprise, dans la convention collective ou à défaut par un usage dans l’entreprise.

si durée du préavis légal > 0
Une durée de préavis de licenciement ou une condition d'ancienneté plus favorable au salarié peut être prévue par la convention collective, un accord de branche, un accord d'entreprise ou le contrat de travail ou les usages.

Source : article L1234-1 du code du travail

#### Éléments saisis : 
durée légale: XXX 
durée conventionnelle : "Nous n’avons pas encore traité cette convention collective"

**Comment by jrduscher** [comment]
## Préavis de licenciement: CCN traitée,  Réponse CCN>0 et Réponse CDTL>=0 ( cas général)

### Pour le résultat :

pour durée de préavis conventionnel> 0, 

si durée légale> 0 

afficher résultat (max entre durée légale et durée conventionnelle

Si durée du préavis légal = 0, il faut afficher :
« Aucun préavis. »
"Le code du travail ne prévoit pas de durée de préavis de licenciement sauf, cas particuliers." 

### Bloc hiérarchie associée :

Si durée du préavis légal = 0
La durée du préavis de licenciement peut être aussi être prévue par dans un accord d’entreprise ou à défaut par un usage dans l’entreprise.

Si durée du préavis légal > 0
Une durée de préavis de licenciement ou une condition d'ancienneté plus favorable au salarié que la loi peut aussi être prévue par un accord d'entreprise ou le contrat de travail ou les usages.
Référence : article L1234-1 du code du travail

### Champ éléments saisis :
- durée légale: XXX 
- durée conventionnelle résultat


## Préavis de licenciement: CCN traitée ,Réponse CDTL et réponse CCN si la convention est listée et ne prévoit rien

### Pour le résultat :

pour durée de préavis conventionnel=0

si durée légale> 0 

afficher résultat (durée légal)

Si durée du préavis légal = 0, il faut afficher :
« Aucun préavis. »
"Le code du travail ne prévoit pas de durée de préavis de licenciement sauf, cas particuliers." 

### Bloc hiérarchie associée :

Si durée du préavis légal = 0
L'existence et la durée du préavis de licenciement peut être  prévue par dans un accord d’entreprise ou à défaut par un usage dans l’entreprise.

Si durée du préavis légal > 0
Une durée de préavis de licenciement ou une condition d'ancienneté plus favorable au salarié que la peut aussi être prévue par un accord d'entreprise ou le contrat de travail ou les usages.
Référence : article L1234-1 du code du travail

### Champ éléments saisis :
- durée légale: XXX 
- durée conventionnelle : Aucun préavis ou 0 ( selon data_simulateur)



## Préavis de licenciement: Réponse CCN:"pas de réponse/0" et Réponse CDTL "pas de réponse/0"

résultat= 0
Le code du travail et la convention collective ne prévoient pas de préavis:
"L'existence et la durée du préavis de licenciement peut être  prévue par dans un accord d’entreprise ou à défaut par un usage dans l’entreprise."


## Préavis de licenciement: CCN non traitée / CCN passée volontairement par l'user/ CCN non trouvée dans la liste

### Pour le résultat :

Si durée du préavis légal > 0
C’est la durée légale qui est affichée. 

Si durée du préavis légal = 0, il faut afficher :
« Aucun préavis. »
"Le code du travail ne prévoit pas de durée de préavis de licenciement sauf, cas particuliers." 

### Bloc hiérarchie associée :

Si durée du préavis légal = 0
L'existence et la durée du préavis de licenciement peut être prévue dans la convention collective, un accord d’entreprise ou à défaut par un usage dans l’entreprise.

Si durée du préavis légal > 0
Une durée de préavis de licenciement ou une condition d'ancienneté plus favorable au salarié peut être prévue par une convention collective, un accord de branche, un accord d'entreprise ou le contrat de travail ou les usages.
Référence : article L1234-1 du code du travail

### Champ éléments saisis :
- durée légale: XXX 
- si CC non traitée => durée conventionnelle : "La convention collective n'a pas été traitée par nos services.
- si CC non renseignée => durée conventionnelle : "La convention collective n'a pas été renseignée."

**Comment by lionelB** [comment]
@jrduscher  pour l'outils __préavis de démission__ si on a pas de resultats, je pense qu'on peut simplement mettre un wording plutot que garder la meme page mais mettre 
```
Resultat
Aucun résultat communicable: la branche n'a pas été renseignée
```

**Comment by virginielastisneres** [comment]
### Préavis de démission: Cas Général durée CCN > 0

****Résultat****

durée conventionnelle

"Le code du travail ne prévoit pas de durée de préavis de démission sauf, cas particuliers."

****Bloc hiérarchie****
"L'existence et la durée du préavis de démission peut être aussi par un accord d’entreprise ou à défaut, par un usage dans l’entreprise."

### Préavis de démission: Cas Général durée CCN =0 / null

****Résultat****

"La convention collective ne prévoit aucun préavis"
"Le code du travail ne prévoit pas de durée de préavis de démission sauf, cas particuliers."

****Bloc hiérarchie****
"L'existence et la durée du préavis de démission peut être fixée par un accord d’entreprise ou à défaut, par un usage dans l’entreprise."

### Préavis de démission: Cas de la CCN non renseignée

****Résultat****

"Aucun résultat : la convention collective n'a pas été renseignée."

"Le code du travail ne prévoit pas de durée de préavis de démission sauf, cas particuliers."

****Bloc hiérarchie****
"L'existence et la durée du préavis de démission peut être prévue par une convention collective, un accord d’entreprise ou à défaut, par un usage dans l’entreprise."


### Préavis de démission: Cas de la CCN non traitée par l'équipe:

****Résultat****

"Aucun résultat : la convention collective n'a pas encore été traitée par nos services. 

"Le code du travail ne prévoit pas de durée de préavis de démission sauf, cas particuliers." 

****Bloc hiérarchie****
"L'existence et la durée du préavis de démission peut être prévue par une convention collective, un accord d’entreprise ou à défaut, par un usage dans l’entreprise."

**Comment by lionelB** [comment]
je pense que c'est pas la peine d'afficher 
> Aucun résultat : la convention collective n'a pas été renseignée.

**Comment by virginielastisneres** [comment]
> je pense que c'est pas la peine d'afficher
> 
> > Aucun résultat : la convention collective n'a pas été renseignée.

Moi je suis plutôt favorable pour l'afficher car si j'ai pas envie de lire les 3 paragraphes qui suivent je veux juste savoir rapidement s'il y a un résultat ou pas. En une ligne je comprends que je n'ai pas de résultat du fait que je n'ai pas renseignée la convention collective.

**Comment by virginielastisneres** [comment]
> ### Préavis de démission: Cas de la CCN non traitée par l'équipe:
> résultat: Nous n’avons pas encore traité cette convention collective.
> Hiérarchie :
> 
> Le code du travail ne prévoit pas de durée précise du préavis de démission ( en dehors de certaines professions et cas particuliers): nous vous invitons à consulter le contenu de la convention collective.
> 
> un accord collectif d’entreprise peut prévoir une durée de préavis de démission différente, qu’elle soit inférieure ou supérieure. Dans ce cas la durée de préavis de démission prévu par l’accord au niveau de l’entreprise s’applique.
> 
> Le contrat de travail peut lui aussi prévoir une durée de préavis de démission, qui s'applique si elle est durée est plus courte que celle prévue par la convention collective, l'accord collectif ou les usages.

"Aucun résultat : la convention collective n'a pas encore été traitée par nos services. 

Le code du travail ne prévoit pas de durée de préavis de démission sauf, cas particuliers. Nous vous invitons donc à consulter le contenu de la convention collective.

Un accord collectif d’entreprise peut également prévoir une durée de préavis de démission différente de celle de la convention collective, qu’elle soit inférieure ou supérieure. Dans ce cas, la durée de préavis de démission prévu par l’accord d’entreprise doit s’appliquer.

Dans tous les cas, le contrat de travail peut toujours prévoir une durée de préavis de démission plus courte que la convention collective, l’accord collectif ou un usage. Il faudra alors l’appliquer en priorité."
