### ISSUE TITLE
slug=text, 404 et random contenu

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#1968]
Actuellement si on va sur une url qui n'existe pas, ex http://master.code-du-travail-numerique.dev.factory.social.gouv.fr/fiche-service-public/il-etait-une-fois-une-404 on a un quand meme un contenu qui est affiché.

Ca porte à confusion, exemple avec les fiches SP:

 - prod (fiche présente) : https://code.travail.gouv.fr/fiche-service-public/recrutement-et-emploi-dun-artiste-ou-technicien-du-spectacle
 - master (fiche supprimée) : http://master.code-du-travail-numerique.dev.factory.social.gouv.fr/fiche-service-public/recrutement-et-emploi-dun-artiste-ou-technicien-du-spectacle

Je tente une PR en remettant le champ slug en `keyword` plutôt qu'en `text`... le seul usage c'était pour le datafiller a priori ? (ce n'est plus nécessaire grâce au dump.json).

**Comment by revolunet** [comment]
https://github.com/SocialGouv/code-du-travail-numerique/pull/1969

**Comment by lionelB** [comment]
si jamais ca manque pour le datafiller on rajoutera un sous field en text

**Comment by lionelB** [comment]
closed by #1969
