### ISSUE TITLE
Supprimer l'affichage des tags liés aux réponses

### ISSUE THREAD

**Issue by HelaG** [SocialGouv/code-du-travail-numerique#197]
Les tags liées aux réponses apparaissent à plusieurs endroits dans les résultats de la recherche.

![image 1](https://user-images.githubusercontent.com/12069445/47178639-1d5d5100-d31c-11e8-92cf-aa39b75e0e87.png)
Sous le titre de la fiche pour du contenu service public, en tag "brut".
![image 2](https://user-images.githubusercontent.com/12069445/47178696-4ed61c80-d31c-11e8-81f2-5b8bbaede731.png)
Entre la questions discriminante et la réponse pour du contenu taggé par nous. 
![image](https://user-images.githubusercontent.com/12069445/47178759-74632600-d31c-11e8-99ee-6eaf3965af02.png)
Sous le titre de la fiche pour de la FAQ, avec la mention du tag.

A ce stade ces indications complexifient la lecture. Il vaut mieux les supprimer.

**Comment by revolunet** [comment]
désolé cetait pour du debug :) c'est enlevé

**Comment by douglasduteil** [comment]
Re-open if not ;)
