### ISSUE TITLE
Nouveaux liens dans le footer

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1974]
La liste des liens à mettre dans le footer : 
travail-emploi.gouv.fr - service-public.fr - legifrance.gouv.fr -  data.gouv.fr -  gouvernement.fr – cnil.fr

2 possibilités : 
- soit on fait une 4e colonne intitulée "Sites gouvernementaux"
- soit on les met dans une ligne tout en bas à la manière de service public : 
![image](https://user-images.githubusercontent.com/5337489/70905953-82d2cd80-2005-11ea-8c4b-bdc892671c73.png)

Je suis plus pour la deuxième possibilité, mais les deux sont ok pour moi

**Comment by lionelB** [comment]
> Je suis plus pour la deuxième possibilité, mais les deux sont ok pour moi

oui legifrance (beta) et service public font de même

**Comment by ClementChapalain** [comment]
fermé pour #1995
