### ISSUE TITLE
Changer l'adresse du lien "journal des modifs"

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1975]
Je pense que le lien devrait pointer vers https://github.com/SocialGouv/code-du-travail-numerique/releases et pas https://github.com/SocialGouv/code-du-travail-numerique/commits/master

C'est plus compréhensible pour un néophyte

**Comment by lionelB** [comment]
@ClementChapalain le lien en prod c'est https://github.com/SocialGouv/code-du-travail-numerique/releases/tag/v3.8.0 qui détaille le contenu de la release actuelle  (tu as master parce que as testé sur master je pense)

**Comment by ClementChapalain** [comment]
merci j'avais pas bien fait attention :)
