### ISSUE TITLE
Mettre le nom court de la CC et pas l'IDCC dans la recherche CC

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#1976]
ici : 
![image](https://user-images.githubusercontent.com/5337489/70906224-2d4af080-2006-11ea-9d8c-c99799275d45.png)

plutôt que IDCC 0044 mettre "Industries chimiques et connexes" qui est le titre court utilisé sur la page convention collective : http://master.code-du-travail-numerique.dev.factory.social.gouv.fr/convention-collective/0044-convention-collective-nationale-des-industries-chimiques-et-connexes-du-30

**Comment by UnbearableBear** [comment]
Je le fais dans la foulée de l'issue qui demande de passer à la ligne le truc à droite sur mobile

**Comment by lionelB** [comment]
hum c'est plutot data oriented, il faudrait aussi peut être en profiter pour changer le mapping pour indexer aussi les nom courts

**Comment by lionelB** [comment]
il faudrait probablement changer les liens vers les CC aussi. Actuellement on utilise l'idcc+ le titre long , le tout tronqué a 80 caractère

**Comment by ClementChapalain** [comment]
bonne idée

**Comment by lionelB** [comment]
en pause le temps que socialgouv/siret2idcc soit mise à jour avec les shortTitle
\cc @revolunet

**Comment by ClementChapalain** [comment]
@lionelB on s'est mal compris je pense, l'objectif était que ce soit le nom court qui apparaisse à la place de l'IDCC : 
![image](https://user-images.githubusercontent.com/5337489/71471814-f1b3e180-27d0-11ea-834c-5fa1bf4ab622.png)

Est-ce que c'est possible de changer stp ?

**Comment by ClementChapalain** [comment]
j'ai fait une nouvelle tâche plus claire : #2118

**Comment by lionelB** [comment]
ahah oui j'avais pas du tout compris çà.
