### ISSUE TITLE
[Orthographe] Résultat Metallurgie // Metalurgie

### ISSUE THREAD

**Issue by HelaG** [SocialGouv/code-du-travail-numerique#198]
Le Code du Travail ne me renvoie rien si j’écris métallurgie comme il faut
<img width="920" alt="metallurgie rien" src="https://user-images.githubusercontent.com/12069445/47178993-23076680-d31d-11e8-93f2-a993928b3927.PNG">

Il préfère que je fasse une faute d'orthographe ^^
<img width="934" alt="metalurgie resultat" src="https://user-images.githubusercontent.com/12069445/47179346-22230480-d31e-11e8-9bd8-9fb4150628b8.PNG">

**Comment by revolunet** [comment]
Voici le souci : 

- *indemnité de licenciement métallurgie* : 1 seul résultat : https://codedutravail-dev.num.social.gouv.fr/?q=indemnit%C3%A9%20de%20licenciement%20m%C3%A9tallurgie&facet=

- *indemnité de licenciement métalurgie* : multiples résultats pertinents : https://codedutravail-dev.num.social.gouv.fr/?q=indemnit%C3%A9%20de%20licenciement%20m%C3%A9talurgie&facet=

Si le moteur ne trouve rien sur "indemnité de licenciement metallurgie", il devrait proposer le cas général des indemnités de licenciement et non pas un autre sujet de la branche métallurgie.

**Comment by lionelB** [comment]
suite aux modifications apportées à elastic search, les 2 recherches remontent désormais le meme [résultat](https://codedutravail-dev.num.social.gouv.fr/fiche-service-public/jours-feries-et-ponts-dans-le-secteur-prive?q=indemnit%C3%A9%20de%20licenciement%20m%C3%A9talurgie&search=0) 

Les autres résultats ne remontent plus car ils ne matchent pas tout les mots de la recherche

je vais voir avec le consultant ES quelle stratégie on peut adopter pour essayer de remonter les autres résultat qui matchent sur seulement une partie de la requête sans que cela ne remonte trop de bruit sur les expression multi-mots

**Comment by ClementChapalain** [comment]
ok on peut fermer cette issue @lionelB ? quitte à continuer à travailler sur une autre issue si besoin d'amélioration sur le multi mot

**Comment by lionelB** [comment]
oki ! je vais alimenté la page wiki pour la prochaine visite du consultant ES avec les améliorations qu'on souhaite apporter
