### ISSUE TITLE
Mise à jour requêtes datafiller + glossaire + data_simulateurs + contrib

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#1980]
Des nouvelles requêtes ont été intégrées au datafiller suite aux retours des tests juridiques. Il faudrait le mettre à jour si possible en fin de semaine prochaine afin que l'on puisse effectuer de nouveaux tests si possible avant la sortie officielle.

**Comment by ClementChapalain** [comment]
updater le glossaire aussi

mergé avec #1913

**Comment by ClementChapalain** [comment]
updater contrib et data_simulateur aussi

**Comment by ClementChapalain** [comment]
et ensuite déploiement 🚀
