### ISSUE TITLE
Sauvegarde quotidienne des logs Matomo dans Azure Blob

### ISSUE THREAD

**Issue by rmelisson** [SocialGouv/code-du-travail-numerique#1981]

**Comment by revolunet** [comment]
espace az blob "cdtndata" container "logs"

**Comment by rmelisson** [comment]
mis en place sur la VM de logs via cron :
https://github.com/SocialGouv/cdtn-monolog/tree/master/backup-logs/

pour le long terme : 
https://gitlab.factory.social.gouv.fr/SocialGouv/documentation/issues/10

**Comment by rmelisson** [comment]
à vérifier après qqs jours pour s'assurer que tous les logs sont bien présents

**Comment by rmelisson** [comment]
all good
