### ISSUE TITLE
IE11 : search HS

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#1982]
La recherche ne fonctionne plus sur IE11 :/ manque a priori un polyfill sur `string.repeat`

et les fichiers du package data qui n'est pas babelifié (template strings)

**Comment by lionelB** [comment]
pour @cdt/data, pourtant il est dans le transpile-modules  > transpileModules: ["@cdt/sources", "@cdt/data"]

**Comment by revolunet** [comment]
au temps pour moi, en dev [ces packages ne sont pas transpilés](https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-frontend/next.config.js#L4)
