### ISSUE TITLE
IE11 : search et touche entrée

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#1988]
L'envoi de recherche avec la touche entrée semble HS sur IE11

Le clic sur icone search ou selection de suggestion est OK

<img width="1198" alt="Capture d’écran 2019-12-16 à 18 17 01" src="https://user-images.githubusercontent.com/124937/70928299-03f38a00-2031-11ea-9d2c-fd64ed9aa502.png">

**Comment by ClementChapalain** [comment]
possible de vérifier si c'est toujours le cas @virginielastisneres @jrduscher svp ?

**Comment by virginielastisneres** [comment]
ca fonctionne pas de mon côté...

**Comment by nkrmr** [comment]
@ClementChapalain Ne marche pas sur IE 11 je regarde

**Comment by nkrmr** [comment]
Fixed by #2192
