### ISSUE TITLE
Ajout des themes dans courriers.json

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#203]
Il manque les themes dans le fichiers courriers.json
A voir aussi si on ne peut pas compléter un peu le fichier avec d'autres infos (date, profil, branches....)
cf PR #202

[/packages/code-du-travail-data/dataset/courrier-type/courriers.json](https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-data/dataset/courrier-type/courriers.json)

**Comment by jrduscher** [comment]
https://github.com/SocialGouv/code-du-travail-numerique/pull/246

**Comment by lionelB** [comment]
nickel, j'avais deja rajouté les date dans une PR précédentes. Je mergerai ta PR sur la PR en cours comme ça on aura aussi les date !

**Comment by lionelB** [comment]
closed by #246
