### ISSUE TITLE
[bug] fiches MT et anchors encoding

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#2032]
Petit souci sur certaines anchors a cause des caractères spéciaux

<img width="888" alt="Capture d’écran 2019-12-20 à 04 29 07" src="https://user-images.githubusercontent.com/124937/71245414-ebc38980-2314-11ea-8794-95467b44f458.png">

**Comment by ClementChapalain** [comment]
ça fonctionne pour moi, quel est le bug ? le fait que le `+` n'apparaisse pas dans l'url ?

**Comment by revolunet** [comment]
Effectivement maintenant ca fonctionne avec l'accordéon ouvert 🤔

**Comment by ClementChapalain** [comment]
🙌
