### ISSUE TITLE
Retours sur la page convention collective

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#2035]
Suite à la démo de la page convention collective, quelques retours mineurs de wording et de présentation.

## Première section

- [x] Enlever la définition de la convention collective et mettre uniquement quelques infos détaillées et deux liens pour voir la CC sur legifrance ou voir la définition dans le glossaire, et enlever le titre de la section pour alléger : 
![image](https://user-images.githubusercontent.com/5337489/71251023-70b4a000-2321-11ea-9340-43f159d5ce2c.png)

Désolé c'est une modif qui rend obsolète #1984 du coup.. 

## Questions fréquentes

- [x] Ajouter des accordéons sur les thèmes afin de rendre la page plus facilement lisible : 
![image](https://user-images.githubusercontent.com/5337489/71251309-4e6f5200-2322-11ea-9c3d-52b5ab740ed5.png)
- [x] Ajouter un encadré au début de chaque question avec le wording suivant : "Pour savoir si la mesure prévue par la convention collective s'applique à votre situation, reportez-vous à la [réponse complète]() à cette question" avec le lien vers la page de la contrib sur "réponse complète"
- [x] Dans les questions, enlever le bouton "voir la fiche complète" car on l'a déjà dans l'encadré

## Articles par thème

- [x] Changer le titre de la section : "Domaines traités par la convention collective"
- [x] Changer le wording d'introduction ("Sélectionnez un thème parmi ceux traités dans la convention collective pour consulter les articles qui y sont rattachés :") pour : 
> Recherchez, lorsqu'elles existent, les dispositions conventionnelles dans : 
> - les 13 domaines où la loi reconnaît la primauté à la convention collective de branche ;
> - les 4 domaines où la branche elle-même peut reconnaitre sa primauté, sauf si l'accord d'entreprise a des garanties au moins équivalentes (représentées avec une * ci-dessous).
> 
> Si votre question concerne un autre domaine, vous pouvez utiliser la recherche par mot-clés dans la section suivante.
- [x] Changer les noms des domaines pour les noms simplifiés suivants : 
  - salaires minima hiérarchiques
  - classifications
  - fond financement paritarisme : mutualisation 
  - fond formation professionnelle : mutualisation 
  - prévoyance
  - durée du travail, répartition et aménagement des horaires
  - contrats à durée déterminée et contrats de travail temporaire
  - contrat à durée indéterminée de chantier ou d'opération
  - égalité professionnelle femme-homme
  - période d'essai : conditions et renouvellement
  - contrats de travail : poursuite
  - salarié temporaire : poursuite
  - salarié porté : rémunération
  - risques professionnels : prévention*
  - emploi des travailleurs handicapés*
  - délégués syndicaux*
  - primes travaux dangereux et insalubres*

## Recherche par mots-clés

- [x] Nouveau nom de la section : "Recherche par mots-clés"
- [x] Ajouter sous le wording d'introduction ("Effectuez une recherche dans le texte de la convention collective sur legifrance :") la phrase suivante : 
> Pour savoir si ce qui est prévu par la convention collective de branche est bien applicable à votre situation particulière vous devez vous reporter à la fiche traitant du même sujet et pour lequel l'accord d'entreprise peut comporter d'autres règles.

## Ordre des sections

- [x] Changer l'ordre des sections pour aller du plus facile à comprendre au plus compliqué : 
1. Questions fréquentes
2. Articles par thème
3. Recherche par mots-clés

**Comment by revolunet** [comment]
@ClementChapalain Dans "Domaines traités par la convention collective", on peut pas remplacer le select par des accordéons ?

**Comment by ClementChapalain** [comment]
C'est une possibilité oui, j'y avais pas pensé. Je veux bien discuter d'abord l'idée avec catherine et florent et laura vu qu'on a bossé la page ensemble.

**Comment by revolunet** [comment]
Voici ce que ca donne

<img width="809" alt="Capture d’écran 2019-12-26 à 17 56 33" src="https://user-images.githubusercontent.com/124937/71483644-19bf3700-2809-11ea-8f5d-97ab865c0ca7.png">

**Comment by ClementChapalain** [comment]
Merci pour la preview je te fais un feedback lundi !

**Comment by lionelB** [comment]
c'est pas mal 👍

**Comment by ClementChapalain** [comment]
c'est ok pour les accordéons @revolunet :)
