### ISSUE TITLE
feat(search) : compléter les résultats des réponses datafiller

### ISSUE THREAD

**Issue by rmelisson** [SocialGouv/code-du-travail-numerique#2037]
Parfois le datafiller retourne peu de réponses pour une requête donnée, nous devrions compléter avec les résultats du moteur de recherche.

En lien avec  #1783

**Comment by virginielastisneres** [comment]
@rmelisson :) on en est où sur cette pr, elle avait été mergée dans master ?

**Comment by lionelB** [comment]
il faut qu'on la review. On fera les modifs si besoin
