### ISSUE TITLE
Vérifier l'existence des fiches référencés depuis les contributions lors de la mise à jour des données

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#2042]
**Description**
Certaine contributions réference des fiche-sp qui ne sont pas indéxées dans ES

**Reproduction**
Etapes à suivre pour reproduire le bug
1. Go to http://master.code-du-travail-numerique.dev.factory.social.gouv.fr/contribution/quelle-peut-etre-la-duree-maximale-dun-cdd
2. See error

**Comportement attendu**
voir la fiche SP ou a minima gérer l'erreur

**Comment by lionelB** [comment]
il faut aussi gérer coté frontend le fait qu'on puisse avoir une erreur 404 quand on demande une fiche non référencée

**Comment by ClementChapalain** [comment]
ça a été corrigé en changeant le lien pour le nouvel ID.

pour éviter que ça se reproduise, on pourrait imaginer une alerte quand les fiches appelées ne sont pas trouvées ?

**Comment by revolunet** [comment]
Toutes les erreurs nous sont remontées éventuellement via sentry mais on pourrait avoir une alerte plus tôt, par exemple au moment où on met à jour les contributions ?

**Comment by lionelB** [comment]
oui ca serait une bonne vérification !
