### ISSUE TITLE
Do not use getInitialProps in _app

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#2061]
https://github.com/zeit/next.js/blob/master/errors/opt-out-auto-static-optimization.md

<img width="741" alt="Screenshot 2019-12-24 at 14 42 48" src="https://user-images.githubusercontent.com/705453/71415396-c9ef3d00-265b-11ea-81ad-233d29b1bca2.png">

We are probably missing some cool optimisation here

**Comment by lionelB** [comment]
It implies to handle error on pages and not in _app.
