### ISSUE TITLE
Nouvelle UI page droit du travail

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#2067]
L'UI de la page droit du travail doit être revue, le texte ne doit pas être changé. 

**Pour retrouver le nouvel UI ===>> https://www.figma.com/file/oph7JpLS74NJAiGbzyit95/CDTN-UI-BlueFinal?node-id=0%3A1** 
- frame "13 - A propos" 
- frame "M5 - A propos"
- frame "kit- Basiques" pour les pictos A propos

Pour info, nouveautés UI les plus importantes : 
-  New composant : carte qui s'ouvre
-  New pictos
-  New timeline

**Comment by virginielastisneres** [comment]
View version desktop de la page 
![13-A Propos](https://user-images.githubusercontent.com/48682104/72721855-443caf80-3b7d-11ea-9b81-dc8c240708b5.jpg)

**Comment by virginielastisneres** [comment]
View version mobile de la page 
![M5-A Propos](https://user-images.githubusercontent.com/48682104/72721926-6c2c1300-3b7d-11ea-9b49-4341c141c0be.jpg)

**Comment by UnbearableBear** [comment]
C'est beau !
