### ISSUE TITLE
Filtres: "Autres" et autres problèmes de filtres

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#207]
nécessite UX. rdv pris.

https://github.com/SocialGouv/code-du-travail-numerique/issues/100

**Comment by revolunet** [comment]
relatif aux tags et #211 à discuter avec Onogone

**Comment by ClementChapalain** [comment]
on a prévu de discuter de ce sujet avec Lionel et JR dans la semaine en fonction des retours des tests utilisateurs menés à Dijon la semaine dernière (https://github.com/SocialGouv/code-du-travail-numerique/wiki/%5BTests-utilisateur%5D-2019.02.07-Dijon), on refera des tâches plus précises à ce moment là
