### ISSUE TITLE
useGlossary in tabs

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#2070]
When glossary is applied inside tab titles, it breaks tab navigation

ex: http://127.0.0.1:3000/contribution/arret-maladie-pendant-la-periode-dessai-quelles-sont-les-regles?q=arr%C3%AAt%20maladie%20p%C3%A9riode%20d%27essai

Ex: second tab is not clickable

<img width="642" alt="Capture d’écran 2019-12-26 à 13 07 43" src="https://user-images.githubusercontent.com/124937/71475497-c3d69900-27e0-11ea-94cb-3a1e1f1afc7d.png">

When removing `data-main-content` tabs works as expected

**Comment by lionelB** [comment]
There is a css rules to target p / li to were glossary is applied
we need to update css rules to tatget only p / li that are not interactive ( !button, !tab, !accordion)

**Comment by revolunet** [comment]
Dans les liens aussi ca peut poser problème: 

<img width="422" alt="Capture d’écran 2019-12-27 à 13 36 15" src="https://user-images.githubusercontent.com/124937/71517447-58f39380-28ae-11ea-8d3a-57f5b0467bef.png">

**Comment by lionelB** [comment]
c'est possible et c'est une limite du systeme actuel

**Comment by lionelB** [comment]
fix by #2087
