### ISSUE TITLE
[bug] modal recherche ccn: résultats

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#208]
Par contre : la recherche " boulangerie industrielle est déceptive": le premier résultat n'est pas la boulangerie, le surlignement ne fait pas apparaître en premier la bonne convention collective.

Dans le moteur principal, il n'y a pas de soucis avec ce test.

**Comment by revolunet** [comment]
cette modale est-elle encore vraiment nécessaire ? 
(en plus elle n'utilise pas elastic)

**Comment by lionelB** [comment]
est ce qu'on devrait pas crée un index avec juste le titre des ccn et leur infos (pas leur contenu) et l'api correspondante ?

**Comment by revolunet** [comment]
liste des idcc : https://travail-emploi.gouv.fr/dialogue-social/negociation-collective/article/conventions-collectives-nomenclatures

**Comment by revolunet** [comment]
la liste KALI actuelle provient du select ici : https://www.legifrance.gouv.fr/rechConvColl.do?reprise=true&page=1

**Comment by jrduscher** [comment]
Booster l'IDCC dans la recherche

**Comment by revolunet** [comment]
cf #341

**Comment by lionelB** [comment]
je ferme vu qu'il y a l'issue #341
