### ISSUE TITLE
search 

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#2082]
bizarrement "durée maximale de la période d'essai" renvoie moins de résultats et surtout la contribution ne ressort pas 🤔

durée maximale de la période
<img width="732" alt="Capture d’écran 2019-12-27 à 15 47 28" src="https://user-images.githubusercontent.com/124937/71521273-4eda9080-28c0-11ea-9751-c3c919efc190.png">

durée maximale de la période d'essai
<img width="748" alt="Capture d’écran 2019-12-27 à 15 47 42" src="https://user-images.githubusercontent.com/124937/71521278-539f4480-28c0-11ea-8bae-0221faa72998.png">

**Comment by revolunet** [comment]
pareil avec "renouvellement période" et "renouvellement période d'essai"

par contre "renouvellement période essayer" marche

**Comment by lionelB** [comment]
tu peux tester sur l'api avec le param &skipSavedResults

**Comment by revolunet** [comment]
OK c'était des liens HS dans le datafiller, cf PR #2090
