### ISSUE TITLE
Bug page "imprimer" des outils

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2084]
**Description**
Je suis sur Chrome, quand je souhaite imprimer, voilà la page qui apparaît. 
[Préavis de démission le 27_12_2019 à à 16_1.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/4005623/Preavis.de.demission.le.27_12_2019.a.a.16_1.pdf)

3 problèmes : 

- je n'ai toujours pas la date et l'heure qui se mettent... je dois aller dans les paramètres de l’impression et cliquer sur En-têtes et pieds de page. 

- j'ai un (/) qui apparaît en haut à coté de code du travail numérique. 

- et j'ai les liens urls des articles qui s'affichent en entier. C'est pas très beau... 

**Corrections** 

- [ ] faire apparaitre la date et l'heure par défaut à chaque fois

- [ ] supprimer le (/)

- [ ] supprimer les liens urls des articles

**Comment by nkrmr** [comment]
@virginielastisneres Pourrais-tu me dire sut quel navigateur tu as eu ce résultat ?

**Comment by virginielastisneres** [comment]
Sur Chrome @nkrmr :)

**Comment by lionelB** [comment]
Pour la date, on pourrait la mettre dans un champ dans le header qui ne serait visible qu'en impression
genre
```css
.printDate { display: none }
@media print {
  .printDate{ display: block }
}
```

**Comment by lionelB** [comment]
Pour les liens, c'est plutôt une bonne pratique de les mettre mais dans le cas des outils, c'est pas nécessaire je pense

**Comment by nkrmr** [comment]
> Pour la date, on pourrait la mettre dans un champ dans le header qui ne serait visible qu'en impression
> genre
> 
> ```css
> .printDate { display: none }
> @media print {
>   .printDate{ display: block }
> }
> ```

Effectivement les différent navigateur ne gèrent pas le titre de la même façon. 
Je vais essayer avec une date dans le header directement

**Comment by nkrmr** [comment]
Il faut également cacher le Toaster lors de l'impression

**Comment by nkrmr** [comment]
Fixed by #2217
