### ISSUE TITLE
position invalide outil préavis de licenciement navigation sticky

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2095]
Quand j'arrive sur cette page de modèle, on me propose deux outils sur le côté dont le préavis de licenciement. 
Le préavis de licenciement ne devrait pas apparaître. d'ailleurs quand je tape le modèle dans la barre de recherche, l'outil de préavis de licenciement n'apparait pas dans les résultats. Bizarre. 
- page modèle : https://master-code-travail.dev.fabrique.social.gouv.fr/modeles-de-courriers/rupture-de-periode-dessai-a-linitiative-de-lemployeur?q=Rupture%20de%20p%C3%A9riode%20d%E2%80%99essai%20%C3%A0%20l%27initiative%20de%20l%27employeur
- page recherche : https://master-code-travail.dev.fabrique.social.gouv.fr/recherche?q=Rupture%20de%20p%C3%A9riode%20d%E2%80%99essai%2C%20%C3%A0%20l%E2%80%99initiative%20de%20l%E2%80%99employeur

A noter que je n'ai pas ce problème sur la prod qui fonctionne parfaitement : https://code.travail.gouv.fr/modeles-de-courriers/rupture-de-periode-dessai-a-linitiative-de-lemployeur?q=Mod%C3%A8le%20:%20Rupture%20de%20p%C3%A9riode%20d%E2%80%99essai%20%C3%A0%20l%27initiative%20de%20l%27employeur

**Comment by lionelB** [comment]
duplicate #2078

**Comment by revolunet** [comment]
c'est un autre souci, non ? plutôt de pertinence de l'outil proposé

**Comment by lionelB** [comment]
ah oui pardon j'ai mal lu, je ré-ouvre

**Comment by lionelB** [comment]
Pb lié au mergeResult qui ne conserve pas l'ordre.
