### ISSUE TITLE
Navigation entre les articles CDT

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#210]
### Problème
Aujourd'hui nous présentons juste les articles en tant que tel. 
![image](https://user-images.githubusercontent.com/48682104/77902996-655b0400-7282-11ea-9c80-55434f7471f2.png)

Or, nous recevons également de l'API Dila le chemin d'arborescence de ces articles. 
![image](https://user-images.githubusercontent.com/48682104/77903048-84f22c80-7282-11ea-8b27-7c01bb2e2ea5.png)

Cette arborescence est très pratique pour y voir plus clair dans les articles du code du travail (ce qui constitue notre objectif). 

### Solution

Dans un premier temps, il faut récupérer cette arborescence et l'afficher. 
A voir si on affiche toute l'arborescence ou seulement le dernier.

**Comment by ClementChapalain** [comment]
Les specs fonctionnelles sont claires, besoin d'un peu d'ux pour voir comment on affiche ces infos de la meilleure manière

**Comment by ClementChapalain** [comment]
lié à #106

**Comment by revolunet** [comment]
Une première modif serait de déjà afficher l'arborescence des sections

Dans un second temps, rendre les sections clicables. ce qui veut dire créer une nouvelle page "section" qui présenterait la liste de sous sections et articles associés avec les liens internes.

autre possibilité : le clic sur une section renvoie vers legifrance mais je trouve ca déroutant pour l'utilisateur

**Comment by virginielastisneres** [comment]
Alors oui au vu de ce je remarque dans les parcours sur les articles c'est que les gens navigue un peu par article mais pas trop trop. 
Je pense que nous verrons après pour le second temps et la section cliquable, des entretiens utilisateurs pourront nous être utiles je pense :)
