### ISSUE TITLE
Contributions non-accessibles

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#2100]
Des contributions ne sont pas accessibles et renvoient une erreur 500 : 

https://master-code-travail.dev.fabrique.social.gouv.fr/contribution/quelle-peut-etre-la-duree-maximale-dun-cdd?q=dur%C3%A9e%20maximale

https://master-code-travail.dev.fabrique.social.gouv.fr/contribution/les-conges-pour-evenements-familiaux?q=les%20cong%C3%A9s%20pour%20%C3%A9v%C3%A9nements%20familiaux

**Comment by revolunet** [comment]
Dans les deux cas ces contributions font référence à des fichesqu'on arrive pas à retrouver  

du coup à l'ouverture de la page, lorsque l'API cherche à récupérer ces contenus pour les mettre dans la contribution :

## Cas 1 :

`error:  there is no document that match https://www.service-public.fr/professionnels-entreprises/vosdroits/F31211`. Fiche transformée en https://www.service-public.fr/particuliers/vosdroits/F36

## Cas 2 :

`error: there is no document that match https://travail-emploi.gouv.fr/droit-du-travail/les-absences-pour-maladie-et-conges-pour-evenements-familiaux/article/les-conges-pour-evenements-familiaux`

**Comment by revolunet** [comment]
cf https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-api/src/server/routes/items/index.js#L86

**Comment by revolunet** [comment]
Pour prévenir ce genre de bug, une solution serait, au moment de la récup des contributions, de vérifier que le contenu est bien accessible chez nous

**Comment by ClementChapalain** [comment]
modif faite sur la fiche SP, pour la fiche MT l'url ne semble pas avoir changée

**Comment by revolunet** [comment]
Donc le souci sur fiches MT c'est que les fiches "racine" ne sont pas référencées, uniquement les sous-paragraphes...

**Comment by revolunet** [comment]
Pour la Fiche MT, son url est toujours accessible, mais il y a une redirection vers une nouvelle fiche.

Or c'est cette nouvelle URL qu'on utilise pour référencer le contenu en interne :)

quand on met à jour les fiches MT, on met à jour les refs en interne mais pas dans les contributions

**Comment by revolunet** [comment]
je n'ai pas de solution aujourd'hui à part : 
 - maintenir des urls
 - afficher une erreur lors de l'importation de la contribution

**Comment by ClementChapalain** [comment]
Pour la fiche MT, Nadia l'a réécrite donc ok pour maintenant
