### ISSUE TITLE
page CC : quelques améliorations

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2116]
Dans la page CC, j'ai testé une CC avec un nom très long. 
L'interligne présent dans le nom est trop grand, cela n'aide pas du tout à la comprendre du nom de la CC. 
![image](https://user-images.githubusercontent.com/48682104/71615332-146b3f00-2bb1-11ea-8ce9-7ab4028b32c2.png)

Il faut réduire l'interligne comme pour un texte lambda :
![image](https://user-images.githubusercontent.com/48682104/71615435-a6734780-2bb1-11ea-8460-96ea853b23f9.png)

**Comment by virginielastisneres** [comment]
version mobile ... 
![Screenshot_20191231-110527](https://user-images.githubusercontent.com/48682104/71617903-9bbeaf80-2bbd-11ea-8704-c7aa0e979c97.png)

**Comment by virginielastisneres** [comment]
il y a un problème de taille de police... les sous-titres dans les questions sont beaucoup trop gros. Il faut les réduire. 
![image](https://user-images.githubusercontent.com/48682104/71625909-a3487d80-2bea-11ea-970e-7521ebef5a73.png)

**Comment by ClementChapalain** [comment]
Pour les tailles de police dans les questions, il faut changer le markdwon (ne pas mettre des titres avec des `###` dans les contributions).
