### ISSUE TITLE
Dans Feedback ajouter la réponse selectionnée par usager 

### ISSUE THREAD

**Issue by Loze-Faelens** [SocialGouv/code-du-travail-numerique#212]
Sur le pavé Feedback en plus de la réponse tapé par l'usager, ajouter le libellé de la question selectionnée par l'usager dnas la liste des suggestion pour avoir le texte suivant : 
ex si question usager = CCCC et que l'usager selectionne " IDCC2905 etc ...."
le texte du feed back doit être  : 
""Avons-nous répondu à votre question : cccc ? en vous suggérant " IDCC2905 etc ....""

**Comment by revolunet** [comment]
https://projects.invisionapp.com/d/main/default/#/console/14828309/325093779/preview

**Comment by lionelB** [comment]
@jeremiecook  Est ce que bloc est a intégré dans tout les page à la place du formulaire actuel ?
![image](https://user-images.githubusercontent.com/160320/48086174-7d993180-e1fc-11e8-8319-f83608de7a28.png)

**Comment by lionelB** [comment]
lié à #214

**Comment by jeremiecook** [comment]
Oui

--
Jérémie Cook
jeremie.cook@protonmail.com
Tél : 06 63 09 76 32

Activé mar., nov. 6, 2018 à 19:46, Lionel <notifications@github.com> a écrit:

**Comment by lionelB** [comment]
@jeremiecook est ce que tu peux ma mettre l'icone dans l'issue ? je ne crois pas l'avoir 
Merci

**Comment by jeremiecook** [comment]
[lost.svg.zip](https://github.com/SocialGouv/code-du-travail-numerique/files/2581232/lost.svg.zip)

**Comment by lionelB** [comment]
thanks
