### ISSUE TITLE
Titre de l'outil salaire brut/net

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#2122]
![image](https://user-images.githubusercontent.com/37538697/71618293-58654080-2bbf-11ea-8700-c45b66788fe4.png)

Le titre a été changé sur les tuiles de la page d'accueil mais pas sur la page de l'outil:
![image](https://user-images.githubusercontent.com/37538697/71618275-4be0e800-2bbf-11ea-812a-c700a858d9e3.png)

- Simulateur d'embauche = >Salaire brut net

**Comment by ClementChapalain** [comment]
changer également le nom de l'outil CC

**Comment by lionelB** [comment]
> l'outil CC 

l'outils de recherche des convention collective ?

**Comment by ClementChapalain** [comment]
oui, dans cette page il faut qu'on change pour "Convention collective" pour être cohérent avec la homepage : https://master-code-travail.dev.fabrique.social.gouv.fr/outils

**Comment by nkrmr** [comment]
Je m'en occupe

**Comment by nkrmr** [comment]
Closed by #2168
