### ISSUE TITLE
Outil de l'indemnité de précarité : quelques améliorations 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2125]
### Etape 4 de l'outil de l'indemnité de précarité : 

Il faut que la phrase "* Majorations, indemnités, primes et accessoires compris sauf les remboursements de frais et l’indemnité de congés payés." soit placée en dessous de la question "Quelle est la rémunération totale brute perçue durant le contrat de travail ?*" et avant le champ à remplir. 

![image](https://user-images.githubusercontent.com/48682104/71621612-9b7bdf80-2bd0-11ea-942a-543b3d7f9aa4.png)

**Comment by virginielastisneres** [comment]
idem pour la seconde option : 

![image](https://user-images.githubusercontent.com/48682104/71621689-13e2a080-2bd1-11ea-9424-0008bc3fd0f7.png)

**Comment by jrduscher** [comment]
Minuscule correction de wording à faire en passant:

Page d'introduction:
passage à modifier:
"Vous pourrez simuler simplement le montant de la prime de précarité définie par le Code du travail avec la prise en compte des particularités présentes dans certaines branches d’activité."

par 
Vous pourrez simuler simplement le montant de la prime de précarité définie par le code du travail avec la prise en compte des particularités présentes dans certaines branches d’activité.

**Comment by virginielastisneres** [comment]
Pourrait-on avoir le symbole euros à coté du montant (quitte à mettre le montant en dessous) ? 

![InkedScreenshot_20191231-133228 (1)_LI](https://user-images.githubusercontent.com/48682104/71621891-607aab80-2bd2-11ea-80d2-a1c22b309b01.jpg)
