### ISSUE TITLE
Dette : ne pas ajouter l'url code.travail.gouv.fr dans l'ingress systématiquement mais uniquement sur la prod

### ISSUE THREAD

**Issue by ylascombe** [SocialGouv/code-du-travail-numerique#2129]
**Description**
Suite à la PR https://github.com/SocialGouv/code-du-travail-numerique/pull/2126#pullrequestreview-337374372, nous avons ajouté l'url code.travail.gouv;fr dans la liste des hosts de l'ingress. Comme ce n'est pas conditionné, cela est fait également sur les env hors prod. Ca ne bloque pas ni fait d'erreur mais il serait tout de même intéressant d'ajouter une condition sur cette url.

**Comment by revolunet** [comment]
Il faudrait également ajouter une ingress pour gérer code.travail.gouv.fr en prod

**Comment by lionelB** [comment]
done in  #2126
