### ISSUE TITLE
Glossaire: définition du CSE

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#2133]
![image](https://user-images.githubusercontent.com/37538697/71624114-3086d480-2be1-11ea-8e22-c950560c5e6a.png)

La définition du glossaire  "Comité Social Economique  s’affiche aussi pour son acronyme "CSE". ( ce qui en soi est plutôt cool)
Problème, dans ce cas: A la fin de la définition, on ne sait pas quels sont les termes cachés derrière cet acronyme.

**Comment by ClementChapalain** [comment]
Oui bien vu ! On pourrait fixer ça en mettant le titre de la définition en gras dans le glossaire genre comme ça : 
> **Comité Social Économique**
> bla bla bla

On peut bien mettre tu markdown dans les définitions @revolunet ?

@virginielastisneres tu en penses quoi ?

**Comment by virginielastisneres** [comment]
Je pense qu'il suffit de séparer les définitions. 

Mettre pour CSE : 
Comité Social Économique
bla bla bla

et pour Comité Social Économique
bla bla bla

Ca évite d'encombrer la définition du Comité Social Économique.

**Comment by ClementChapalain** [comment]
oui meilleure solution effectivement :) je vous laisse gérer ?

**Comment by revolunet** [comment]
Oui pour le markdown côté glossaire par contre ce nest pas encore géré côté front

**Comment by lionelB** [comment]
tout à fait :) 
c'est géré au moment de l'extraction

**Comment by virginielastisneres** [comment]
> oui meilleure solution effectivement :) je vous laisse gérer ?

all ready down
