### ISSUE TITLE
fonctionnalité pouces haut et bas à intégrer

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#214]
https://trello.com/c/8buyKsyc/280-int%C3%A9grer-les-fonctionnalit%C3%A9s-des-indicateurs-thumbsup-thumbsdown

**Comment by jeremiecook** [comment]
![popin de feedback](https://user-images.githubusercontent.com/88306/48058486-d940cc00-e1b6-11e8-92dc-b549e6b24ce6.png)

**Comment by lionelB** [comment]
@jeremiecook la popin est censée arriver une fois le pouce bas clické ?

**Comment by jeremiecook** [comment]
Tout à fait ! Ou bien en cliquant sur les blocs "Vous n'avez pas trouvé votre réponse ?" sous les listes de réponses

**Comment by lionelB** [comment]
@jeremiecook merci !

**Comment by lionelB** [comment]
@jeremiecook @jrduscher Je me pose la question des liens "les réponses qui pourraient vous aider"
Ça me parait étrange de lui représenter les 3 premiers resultats qu'on lui a présenté dans le suggester quand il a tapé sa question, vu que ça ne l'aide pas à réalisé son objectif.  Est que j'ai raté un trucs ?

**Comment by jeremiecook** [comment]
@lionelB Hello ! Je pense que ces résultats ne s'affichent que si l'utilisateur complète, modifie ou affine le champ "question" de cette popin. C'est un moyen de valider que la réponse n'existe pas déjà avant d'envoyer son retour. L'utilisateur n'a pas toujours saisi de question avant d'arriver sur cette page (par exemple, s'il a cliqué sur un thème / dossier puis consulté la liste des réponses)

**Comment by jeremiecook** [comment]
@lionelB Cela dit, je pense que ce bloc peut rester masqué à l'ouverture de la popin

**Comment by lionelB** [comment]
@jrduscher  la PR #264 va répondre partiellement à cette issue car elle ne gére que le pousse bas.
pour le pousse haut, cela va demander un autre travail plus conséquent (impact sur ES / api) 
Je propose qu'une fois la PR mergée, on ferme cette issue et on ouvre une pour le pouce haut ?

**Comment by lionelB** [comment]
ca sera l'occasion de fermer l'issue #134

**Comment by lionelB** [comment]
closed by #264 

pouce haut #294
