### ISSUE TITLE
Progressive web app

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#2141]
Actuellement le code du travail est utilisable meme quand l'api est down, avec uniquement les outils disponibles. Pourquoi ne pas mettre en place du offline, un manifest et carrément transformer le code du travail numérique en une PWA ?

**Comment by ClementChapalain** [comment]
![giphy](https://user-images.githubusercontent.com/5337489/71715691-94dcaa80-2e12-11ea-88ce-fcc5a450eff8.gif)

**Comment by UnbearableBear** [comment]
Franchement t'exagères, je suis sûr que un dev en un sprint c'est plié !
C'est le prix à payer pour être "state of the art" en ergnonomie 😄

**Comment by lionelB** [comment]
je veux bien m'occuper d'ajouter un serviceworker mais comme la majorité du site est du contenu, j'ai du mal à voir ce que ca apporte si on met de coté la partie perf

**Comment by revolunet** [comment]
je mets deux petits warnings sur ce sujet :

 - ce ne serait utile que pour les outils (et encore, sans le picker de ccn)
 - avant de faire de l'offline, il faut être certain de savoir gérer le cache correctement car le risque c'est d'avoir du code outdaté qui ne se met pas à jour (les SW ont été désactivés par défaut dans create-react-app suit à ce genre de problème)

**Comment by UnbearableBear** [comment]
Une fois qu'on aura fini de gérer le static rendering ça pourrait être intéressant de creuser le sujet !
