### ISSUE TITLE
[Modèle de courrier] aperçu et affichage des tableaux et colonnes 

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#2147]
# Affichage et mise en page: bugs
Aujourd’hui, la mise en page des tableaux d'une part et l'affiche des colonnes dans une page ne sont pas reconnus dans les aperçus:

## Exemple 1: Tableau:
[Lien vers le modèle ](https://master-code-travail.dev.fabrique.social.gouv.fr/modeles-de-courriers/lettre-de-reclamation-des-heures-supplementaires)
- **dans le docx:**
![image](https://user-images.githubusercontent.com/37538697/71662600-5a133d80-2d52-11ea-8e6d-ec8333902600.png)

- **dans l'aperçu:**
![image](https://user-images.githubusercontent.com/37538697/71662573-3d770580-2d52-11ea-926e-f8c4c6a89d88.png)

## Exemple 2 Colonnes
[Lien vers le modèle ](https://master-code-travail.dev.fabrique.social.gouv.fr/modeles-de-courriers/affichage-obligatoire-relatif-au-harcelement-sexuel)
- **dans le docx:**
 ![image](https://user-images.githubusercontent.com/37538697/71662702-b37b6c80-2d52-11ea-8880-6698250f6025.png)

- **dans l'aperçu:**
![image](https://user-images.githubusercontent.com/37538697/71662645-8333ce00-2d52-11ea-888e-d7f960f254d1.png)

**Comment by ClementChapalain** [comment]
Pour le deuxième est-ce qu'on ne peut pas modifier le modèle pour avoir une seule colonne plutôt que deux ? J'ai l'impression que le contenu est linéaire

**Comment by jrduscher** [comment]
### Aperçus: 

L'affichage en PDF pourrait être plus simple pour tout le monde ( rédacteur, lecteur) et éliminerait le risque de différences entre le docx et l'aperçu.

Si l'affichage PDF est possible en lieu et place de l'aperçu actuel cela devrait régler les soucis d'affichage des tableaux et des colonnes. ( la présente issue ne serait plus à traiter)

**Comment by lionelB** [comment]
personnellement la partie pdf apporte pas mal de complexité, je préférerai me baser sur des retours / tests utilisateur sur cette partie pour bien cerner les besoins
