### ISSUE TITLE
facetting dans la barre de recherche

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#215]
integrer la fonctionnalité de sélection de types de documents attendus dans la barre de recherche cf https://projects.invisionapp.com/d/main/default/#/console/14828309/308308616/preview

**Comment by lionelB** [comment]
je n'ai pas accès au projet inviion

**Comment by jrduscher** [comment]
![image](https://user-images.githubusercontent.com/37538697/48051636-f7520080-e1a5-11e8-95c9-1c7b1f2ab1fa.png)

**Comment by lionelB** [comment]
merci !

**Comment by jrduscher** [comment]
possibilité de filtrer les résultats attendus en fonction des sources ( réponses FAQ, code du travail, fiches services-public.fr, modèles, outils)

**Comment by jrduscher** [comment]
https://github.com/SocialGouv/code-du-travail-numerique/issues/299
