### ISSUE TITLE
Bug UI Carte outil 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2150]
Il y a un bug au niveau de la carte outil Index Egapro, le titre et le picto ne sont pas centré !
Il serait bon de vérifier les autres. Je vais essayer de trouver des pages qui me les indiquent pour voir. 

https://master-code-travail.dev.fabrique.social.gouv.fr/fiche-ministere-travail/index-de-legalite-professionnelle-calcul-et-questions-reponses?q=Index%20de%20l%E2%80%99%C3%A9galit%C3%A9%20professionnelle%20:%20calcul%20et%20Questions/R%C3%A9ponses#Questions-reponses-sur-le-calcul-de-l-Index

![image](https://user-images.githubusercontent.com/48682104/71668910-1c6ede80-2d6b-11ea-956b-436eced3ef37.png)

**Comment by UnbearableBear** [comment]
Merde,  c'est probablement du à un refacto recent :/

**Comment by virginielastisneres** [comment]
c'est facilement réparable ? et tu peux vérifier les autres cartes ou on doit les vérifier à la main ?

**Comment by UnbearableBear** [comment]
c'est probablement un peu plus compliqué que ça en a l'air. Ca devrait être un lien et c'est un bouton qui s'affiche et j'ai du mal à reproduire en local

**Comment by UnbearableBear** [comment]
D'ailleurs vu que c'est un bouton (probablement parce que le lien n'est pas correctement renseigné), il ne se passe rien quand on clique dessus

**Comment by virginielastisneres** [comment]
ah oui c'est vrai j'avais même pas cliqué dessus...

**Comment by UnbearableBear** [comment]
Ok je crois que j'ai trouvé ! Recemment il a été rajouté la possibilité d'avoir des outils externes non ? Le cas des outils externe n'est pas géré ici. On essaye de constuire le lien comme si il s'agissait d'un outil interne, et ça foire.
EDIT et non, normalement c'est géré
REEDIT: sauf que l'url n'est pas remonté donc ça ne risquait pas de fonctionner

**Comment by virginielastisneres** [comment]
hum hum donc c'est le problème vient du fait que c'est un outil externe ?

**Comment by UnbearableBear** [comment]
Tu peux vérifier sur d'autre outils remontés qui ne sont pas externes normalement ça devrait aller. Je fais un fix dans la foulée

**Comment by virginielastisneres** [comment]
C'est bon pour les outils internes => https://master-code-travail.dev.fabrique.social.gouv.fr/fiche-service-public/indemnite-de-licenciement-du-salarie-en-cdi

**Comment by UnbearableBear** [comment]
J'ai reglé le pb d'alignement dans le cas ou la carte est un bouton !
