### ISSUE TITLE
Bug page fiches pas de contenu proposé sur le côté 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2152]
Contrairement à toutes les autres fiches ministère(cf photo 1), il n'y a pas de contenu proposé sur le côté pour la page : https://master-code-travail.dev.fabrique.social.gouv.fr/fiche-ministere-travail/la-validation-des-acquis-de-lexperience-vae?q=bonus%20malus#Qui-peut-beneficier-de-la-VAE. 

Est-ce normal ? 

![image](https://user-images.githubusercontent.com/48682104/71669686-d109ff80-2d6d-11ea-84e1-d23d0c79d592.png)

![image](https://user-images.githubusercontent.com/48682104/71669602-84bebf80-2d6d-11ea-834e-9fea340b1110.png)

**Comment by UnbearableBear** [comment]
Ca arrive ! Si on ne trouve rien de pertinent parce que la fiche est très spécifique. A voir côté back si on peut aller récupérer malgré tout des résultats non pertinents ? @ClementChapalain

**Comment by virginielastisneres** [comment]
je comprends pas pourtant il y a pleins de contenus sur la vae 
https://master-code-travail.dev.fabrique.social.gouv.fr/recherche?q=La%20validation%20des%20acquis%20de%20l%E2%80%99exp%C3%A9rience%20(VAE)

**Comment by UnbearableBear** [comment]
Je n'ai pas eu l'occasion de creuser les "more_like_this" de elastisearch. C'est le mécanisme que l'on utilise pour le moment. Il faudrait peut-etre envisager de passer par autre chose ou de le modifier pour le rendre moins selectif @lionelB

**Comment by lionelB** [comment]
c'est étrange car justement on double le more_like_this avec une recherche sémantique, ca devrait justement pas arrivé car la recherche sémantique trouve "toujours" des documents

**Comment by virginielastisneres** [comment]
> c'est étrange car justement on double le more_like_this avec une recherche sémantique, ca devrait justement pas arrivé car la recherche sémantique trouve "toujours" des documents

Oui surtout que j'en vois d'autres également qui là est une fiche SP et normalement il y a quand même des fiches sur le congé de proche aidant . 
- fiche : https://code.travail.gouv.fr/fiche-service-public/conge-de-proche-aidant
- résultats recherche "congé de proche aidant" : https://code.travail.gouv.fr/recherche?q=Cong%C3%A9%20de%20proche%20aidant

**Comment by lionelB** [comment]
__probleme identifié__
Une partie du problème vient d'un bug sur le filtrage des fiches retournée


Une autre partie vient du fait que la requete `more_like_this` ne remonte que des contenus qui proviennent de la fiche sur laquelle on se trouve (ses paragraphes, vu que la fiches est divisé en section qui correspondent aux documents)
et dans le cas des pages ministere-travail, on n'utilise pas la recherche sémantique car on n'a pas de vecteur associé au document. 
Et comme les documents associé à la page sont dans un autre index, on ne se base que sur le titre pour chercher des documents "associés", ce qui remonte principalement les sous-parties du document qu'on voit. Voila pourquoi on ne remonte rien.

fix  possible: 
- calculer un vecteur pour l'ensemble du document
- ajouter un moyen d'exclure des document depuis une url dans la requete `more_like_this`
