### ISSUE TITLE
Bug affichage lien externe télérc et mon compte formation

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2156]
J'ai deux affichages différents de l'outil externe TéléRC en fonction de la requête que je fais. Les deux liens fonctionnent et m'amène au même endroit. 
Une idée d'où cela pourrait venir @revolunet @ClementChapalain @UnbearableBear ? datafiller ?

exemple 1 datafillé : 
![image](https://user-images.githubusercontent.com/48682104/71673605-81c9cc00-2d79-11ea-94c3-9d7f7732b624.png)

exemple 2 non datafillé : 
![image](https://user-images.githubusercontent.com/48682104/71673658-a3c34e80-2d79-11ea-8a4c-472576ab0beb.png)

**Comment by virginielastisneres** [comment]
idem pour l'outil mon compte formation : j'ai l'impression que c'est lié au datafiller car une des requêtes est datafillée et une autre non... 

exemple 1 non datafillé : 
![image](https://user-images.githubusercontent.com/48682104/71674544-bfc7ef80-2d7b-11ea-98bc-3b3cef4a14d7.png)

exemple 2 datafillé : 
![image](https://user-images.githubusercontent.com/48682104/71674605-ef76f780-2d7b-11ea-9f2d-0c923efa00b1.png)

**Comment by jrduscher** [comment]
Il restait des liens externes dans le datafiller (partie requete). Nettoyage fait. On avait dit qu'on les virait du df pour le moment pour mieux les réintégrer plus tard. ( #2106)

**Comment by jrduscher** [comment]
il faudra faire une màj des données du df à la prochaine mise en prod @revolunet

**Comment by virginielastisneres** [comment]
Il me semble qu'on enlevait que les liens non validés par Catherine vu que ceux validés on a la carte.

**Comment by ClementChapalain** [comment]
@virginielastisneres ce que tu vois correspond effectivement à deux types de liens différents : 
- les outils externes : outils qu'on a ajouté à la main et qui sont indexés pour ressortir dans la recherche ou dans les contenus qui peuvent vous intéresser
- les liens externes datafillés : ce que JR vient d'enlever car effectivement on les affichait mal dans la recherche

L'idéal serait de pouvoir data-filler les outils externes, est-ce que c'est possible @revolunet ? Car dans le data-filler on demande de remplir une route vers le contenu chez nous, ce qu'on a pas pour ces outils externes (ils renvoient directement vers un autre site)

**Comment by virginielastisneres** [comment]
Oui car moi ca me pose un sacré problème de ne pas les datafiller car s'il n'apparaissent plus c'est pire, je préfère encore les laisser dans le datafiller, ils ressortent au moins. 

Quand je tape index egapro dans le datafiller j'ai un truc qui apparaît comme quoi c'est un outil externe.
![1](https://user-images.githubusercontent.com/48682104/71716434-0f0e2e80-2e15-11ea-8f15-31c95f4c2783.png)

Je serai tenté de mettre celui ci mais le problème c'est que quand je tape dessus apparait une erreur 500 = > https://code.travail.gouv.fr/external/index-egapro

**Comment by ClementChapalain** [comment]
si ça fonctionne de le sélectionner comme ça dans le datafiller c'est effectivement la bonne solution je pense. @revolunet c'est ok de prendre ce lien qui apparait dans le datafiller ?

**Comment by lionelB** [comment]
Les liens externes sont maintenant listés, pour être ensuite récupérér dans le datafiller. Il ne faut donc plus saisir d'url dans les données du datafiller. Pour rajouter un outil externe, on le rajoute au json, qui une fois intégré, et dispo dans le datafiller

**Comment by ClementChapalain** [comment]
trop bien, du coup désolé @jrduscher je ne pensais pas que c'était possible, mais il faudrait maintenant remettre les outils avec les bons liens pris depuis l'auto-complétion, à partir du backup de #2106 j'imagine

**Comment by virginielastisneres** [comment]
du coup les bons liens suite à  l'intégration dans le datafiller c'est celui de ma photo ? @revolunet 
C'est écrit /external/index-egapro
mais j'ai une erreur 500 sur ces liens, sont-ils bons ?

**Comment by revolunet** [comment]
Oui en théorie c'est bon @virginielastisneres . par contre les outils n'ont pas de page dédiée donc l'url ne fonctionne pas . c'est normal.

**Comment by virginielastisneres** [comment]
> Oui en théorie c'est bon @virginielastisneres . par contre les outils n'ont pas de page dédiée donc l'url ne fonctionne pas . c'est normal.

SOUPERRRRR 👍 💃

**Comment by lionelB** [comment]
on ferme @virginielastisneres ?

**Comment by virginielastisneres** [comment]
oui lionel
