### ISSUE TITLE
Afficher le thème des fiches MT dans les résultats

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2157]
Lorsque l'on fait une requête sur le site, les fiches MT qui sont en résultat proposé n'ont pas le thème associé alors que toutes les fiches MT sont thémées. 

Exemple ci-dessous : 
![image](https://user-images.githubusercontent.com/48682104/71679454-eb50d700-2d87-11ea-9b76-82b495aa8d6d.png)
lien : https://code.travail.gouv.fr/recherche?q=cong%C3%A9s%20pay%C3%A9s

**Comment by nkrmr** [comment]
Closed by: #2182
