### ISSUE TITLE
intégrer la page de résultat non trouvée

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#216]
https://trello.com/c/Z3h0WpOG/281-int%C3%A9grer-la-page-de-r%C3%A9sultats-non-trouv%C3%A9e-qui-sera-renseign%C3%A9e-par-lusager-d%C3%A9j%C3%A0-pens%C3%A9e-en-ux

**Comment by lionelB** [comment]
mockup https://projects.invisionapp.com/d/main/default/#/console/14828309/325093779/preview
