### ISSUE TITLE
debt(data): sub packages in data packages

### ISSUE THREAD

**Issue by douglasduteil** [SocialGouv/code-du-travail-numerique#2160]
We should not have sub packages in the `@cdt/data` package.
It seems like this package is mainly use for indexing.
I would recommend that we rename and split the package so it explicitly use the sub dataset **as dependencies** (not explicit relatif path form).
The new package should be named `@cdtn/data...indexing` or `@cdtn/data___indexing` or `@socialgouv/cdtn___data___indexing` (i dunno) it have `@cdt/data...courrier-type` and `@cdt/data...fiches_service_public` etc... as dependencies and maybe outside of the `packages/` monorepo folder. I could be in a `dataset/` folder in the monorepo or completely outside of the `SocialGouv/code-du-travail-numerique` (that should be website-centric IMO)

**Comment by carolineBda** [comment]
Ce package n'existe plus
