### ISSUE TITLE
debt(frontend): data as external endpoint

### ISSUE THREAD

**Issue by douglasduteil** [SocialGouv/code-du-travail-numerique#2162]
I have mixed feeling about having so much `@cdt/data...*` dependencies in the frontend. I would argue that, in itself, the frontend --- in sense of website --- doesn't have dependencies on the data at all.
The used pattern seems to describe the frontend as a backend to where *part* of the static data ressource are embedded in the SSR of the fontend, where it could be a call to an external API.
Considering how much its locking both, I would prefer seeing a separation between the frontend, SSR, rendering part and the backend*s* serving, transforming data.

**Comment by lionelB** [comment]
@douglasduteil  Can we close since we do a lot of refactoring to extract data
