### ISSUE TITLE
CI : ministere-travail-liste-fiches.json

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#2163]
Lorsque qu'une PR est faite sur le fichier `ministere-travail-liste-fiches.json`, voir si on peut trigger un job :

 - récupérer les nouvelles fiches
 - appeler updateTheme
 - Ajouter un commit à la PR avec les changes
 - Envoyer le rapport sur la PR

**Comment by lionelB** [comment]
ca serait trop bien !
