### ISSUE TITLE
MAJ page stats

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#2165]
Mettre à jour la page /stats : https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-frontend/pages/stats.js

**Comment by ClementChapalain** [comment]
j'avais oublié qu'on avait cette page ! faut qu'on la retravaille c'est cool :)

**Comment by lionelB** [comment]
on pourrait rajouter https://github.com/zeit/swr pour la récupération des données issues de l'api matomo ?

**Comment by ClementChapalain** [comment]
Une première liste de stats à intégrer : 
- nombre de visites depuis le 1er janvier et graphique avec nombre de visites / par jour
- nombre de recherches effectuées depuis le 1er janvier et graphique avec nombre de recherches / jour
- nombre de consultations de contenus depuis le 1er janvier et graphique avec nombre de consultations / jour
- nombre de contenus référencés
- % de satisfaction, nombre de personnes ayant cliqué sur oui, nombre de personnes ayant cliqué sur non

Il faudrait également ajouter un lien "Statistiques d'usage" vers cette page dans le footer :)

**Comment by lionelB** [comment]
## chiffres clés
- [x] nb de visites depuis le 01/01/2020 › [lien](http://matomo.fabrique.social.gouv.fr/?idSite=4&format=JSON&method=VisitsSummary.getVisits&date=2020-01-01,today&module=API&period=range) 
- [x] nombre de recherches effectuées › [lien](https://matomo.fabrique.social.gouv.fr/?module=API&method=Actions.get&idSite=4&period=range&date=2020-01-01,today&format=JSON) 
- [x] nombre de consultations de contenus › [lien](https://matomo.fabrique.social.gouv.fr/?module=API&method=Actions.get&idSite=4&period=range&date=2020-01-01,today&format=JSON) 
- [x]  % de satisfaction positive ›  [lien](https://matomo.fabrique.social.gouv.fr/?module=API&method=Events.getAction&idSite=4&period=range&date=2020-01-01,today&format=JSON&label=positive)
- [x]  % de satisfaction negative ›  [lien](https://matomo.fabrique.social.gouv.fr/?module=API&method=Events.getAction&idSite=4&period=range&date=2020-01-01,today&format=JSON&label=negative)

## Graphiques 
https://developer.matomo.org/api-reference/reporting-api-metadata#static-image-graphs
- [ ] graphique des recherche / jour
- [ ] graphique nb de visite
- [ ] graphique nb de consultation

**Comment by ClementChapalain** [comment]
d'ailleurs @lionelB je viens de remarquer que la page actuelle ne se met pas à jour (les stats de visite sont très faibles par rapport au nombre réel) : https://code.travail.gouv.fr/stats

**Comment by lionelB** [comment]
oui les données sont statiques :D
