### ISSUE TITLE
interface: signaler un contenu obsolète

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#217]
ETQ usager je peux signaler un contenu qui ne me parait plus à jour, faux, ou insuffisant

https://trello.com/c/ecnyCufn/18-en-tant-quuser-je-peux-signaler-un-contenu-obsol%C3%A8te-erron%C3%A9

- [ ] volet UX
- [ ] integration

**Comment by jeremiecook** [comment]
![popin de feedback](https://user-images.githubusercontent.com/88306/47301161-8eec1680-d61e-11e8-9a3c-c2fd9c9e88a9.png)

**Comment by jeremiecook** [comment]
Note : Cette page / popin est accessible en cliquant sur le 👎 dans une réponse.

**Comment by ClementChapalain** [comment]
@jrduscher on peut fermer cette tâche ?

**Comment by jrduscher** [comment]
cette issue a été réalisée. il doit y avoir une pr correspondante.

**Comment by lionelB** [comment]
cf PR #264
