### ISSUE TITLE
Outil indemnité de précarité : disclaimer / clean données

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2177]
- [ ]  ajouter un disclaimer sur la HDN dans l'outil de l'indemnité de précarité. 

**Pour les données** 3 situations sont à distinguer pour 3 disclaimers différents.
cf. la colonne Q "Disclaimer" du fichier https://docs.google.com/spreadsheets/d/1SCFHUDjsWWRdVhYP5cVz2Q3AqPa-ubOYsEc3C3kRKOA/edit#gid=1991895535**

### 1| **Disclaimer quand CC non renseignée ou non traitée et que le Code du travail octroie une indemnité de précarité - cas "autres":**
Cas ligne 3 du tableau

_"Une convention collective de branche étendue ou un accord d’entreprise peut prévoit un montant différent qu’il soit plus élevé ou plus faible que celui prévu par le code du travail. Attention, dans le cas où la convention ou l'accord collectif prévoit un taux inférieur à 10% dans la limite de 6 %, il doit y avoir des contreparties offertes au salarié, notamment sous la forme d'un accès privilégié à la formation professionnelle (action de formation, bilan de compétences). 
Dans tous les cas, le contrat de travail peut prévoir un montant plus favorable pour le salarié. Il faut alors appliquer ce montant. "_

### 2| **Disclaimer quand CC renseignée mais pas de disposition conventionnelle - cas classique :**
_"Un accord d’entreprise peut prévoit un montant différent qu’il soit plus élevé ou plus faible. Dans ce cas, s’applique le montant prévu par l’accord d’entreprise, sauf si le contrat de travail prévoit un montant plus favorable pour le salarié.
Attention, dans le cas où l’accord d’entreprise prévoit un taux inférieur à 10% dans la limite de 6 %, il doit y avoir des contreparties offertes au salarié, notamment sous la forme d'un accès privilégié à la formation professionnelle (action de formation, bilan de compétences)."_

### 3| **Disclaimer quand CC renseignée et qu'elle prévoit des dispositions conventionnelles :**
_"Un accord d’entreprise peut prévoit un montant différent qu’il soit plus élevé ou plus faible. Dans ce cas, s’applique le montant prévu par l’accord d’entreprise, sauf si le contrat de travail prévoit un montant plus favorable pour le salarié."_

Liste des cas : 
- Ligne 66 du tableau : IDCC 1486 - Enquêteurs vacataires 
- Ligne 67 du tableau : IDCC 1486 - Contrat d'intervention dans le secteur d'activité d'organisation des foires, salons et congrès
- Ligne 72 du tableau : IDCC 1516 - CDD d'usage
- Ligne 109 du tableau : IDCC 2098 - CDD d'optimisation linéaire
- Ligne 110 du tableau : IDCC 2098 - CDD d'animation commerciale
- Ligne 111 du tableau : IDCC 2098 - Contrat d'intervention dans le secteur de l'accueil événementiel
- Ligne 125 du tableau : IDCC 2511 - CDD d'usage appelé contrat «d'intervention»
- Ligne 142 du tableau : IDCC 3127 - CDD dit de « mission ponctuelle ou occasionnelle »

**Pour le visuel**
cf. photo ci dessous
![image](https://user-images.githubusercontent.com/48682104/71809968-86d89500-3071-11ea-9f1c-9e49898813e3.png)

- [ ] ajouter des références juridiques pour des CC sans disposition conventionnelle

Dans certains cas où la CC est renseignée mais ne prévoit pas de dispositions spécifiques, il arrive qu'elle écrive quand même dans un article "c'est le code du travail qui s'applique". c'est important pour la veille que l'on garde une trace de ces articles, il faut donc rajouter leur référence. 

Le souci est le suivant : le cas CC renseignée mais pas de disposition conventionnelle renvoie à la ligne 3 et donc renvoie aux références juridiques de la ligne 3 : "Article L1243-8 du code du travail et
Article L1243-9 du code du travail ". Cela écrase la référence juridique de la convention collective : exemple ligne 9 IDCC 29  "Article 16.03 de la convention collective". 

Il faudrait pouvoir avoir les 2 références à la fois, cad la référence conventionnelle et les références de la ligne 3 qui correspondent au code du travail, soit pour l'IDCC 29 (ligne 9) : 
Article L1243-8 du code du travail 
Article L1243-9 du code du travail
Article 16.03 de la convention collective

**Comment by virginielastisneres** [comment]
- [ ]  Mettre à jour les données du fichier, nous avions un mauvais IDCC associé à une CC. De plus, j'en ai profité pour rajouter des sources dans les cas où la CC ne prévoit rien.
https://docs.google.com/spreadsheets/d/1SCFHUDjsWWRdVhYP5cVz2Q3AqPa-ubOYsEc3C3kRKOA/edit#gid=1991895535

**Comment by revolunet** [comment]
Le disclaimer doit apparaitre apres "En savoir plus sur la prime de précarité d’un salarié en CDD" ?

<img width="1217" alt="Capture d’écran 2020-01-29 à 15 29 05" src="https://user-images.githubusercontent.com/124937/73365179-21607880-42ac-11ea-8140-caf0ebf7df5d.png">

**Comment by virginielastisneres** [comment]
nop avant le détail du calcul ... 
ah et je peux en profiter pour te demander un petit truc en plus ju ?

**Comment by revolunet** [comment]
allez :)

**Comment by revolunet** [comment]
donc le texte doit etre calé entre le montant et le détail du calcul ?

**Comment by virginielastisneres** [comment]
yes et il faudrait que le détail et les sources soient indiqués comme cela, ca serait possible ? 
![image](https://user-images.githubusercontent.com/48682104/73367205-7fdb2600-42af-11ea-9c77-ff46bd418d39.png)
