### ISSUE TITLE
Une contribution non publiée est visible depuis la page convention collective

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#2185]
Sur la page : 
https://master-code-travail.dev.fabrique.social.gouv.fr/convention-collective/1979-hotels-cafes-restaurants

Lorsque l'on cherche la question "congés pour événements familiaux" on trouve la réponse lié à la convention collective mais lorsque l'on clique sur "réponse complète" on tombe sur une 404 car la réponse générique n'est pas publiée.

Il faudrait que pour les contributions dont la réponse générique n'est pas validée + publiée, on ne voit pas la réponse convention collective dans la page CC.

**Comment by lionelB** [comment]
il faudrait pas plutot corriger le pb coté contrib en n'exposant que les conventions validées et publiées ?

**Comment by lionelB** [comment]
il me faudrait un cas de contribution sans réponses publié car la 50 a une réponse générique (et à l'air publié)

**Comment by lionelB** [comment]
la question 50 a été présente à un moment dans le corpus, (cf https://github.com/SocialGouv/code-du-travail-numerique/commit/3f596f6a7ed94e09c59654e5766ee07e78cc4202#diff-cef3583f4a85017132a49769dbda5549) au moment ou les donnée des page cc ont été générées.
