### ISSUE TITLE
Nouvelle fiche MT à intégrer

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#2188]
https://travail-emploi.gouv.fr/droit-du-travail/la-remuneration/article/la-prime-exceptionnelle-de-pouvoir-d-achat

**Comment by lionelB** [comment]
pour info certaines fiches MT sont non thémées 
cf https://github.com/SocialGouv/code-du-travail-numerique/pull/2171#issuecomment-572130215
poke @virginielastisneres  @jrduscher
