### ISSUE TITLE
contribution "durée de préavis de démission": réponse générale incomplète

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#2190]
La réponse générique reprend les données d'une fiche.
![image](https://user-images.githubusercontent.com/37538697/71902619-bddaa380-3162-11ea-8953-0877fbef67bf.png)

Le cas général ne correspond qu'à un des 3 onglets de cette fiche. Les deux autres ne se trouvent pas dans cette réponse. Il ne s'agit pas d'une volonté de l'équipe, ces éléments sont importants:
https://www.service-public.fr/particuliers/vosdroits/F2883
![image](https://user-images.githubusercontent.com/37538697/71902677-dd71cc00-3162-11ea-9b38-b51a0782478c.png)

**Comment by virginielastisneres** [comment]
ci-joint l'url de la fiche concernée : https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/contribution/quelle-est-la-duree-du-preavis-en-cas-de-demission?q=pr%C3%A9avis%20de%20d%C3%A9mission
