### ISSUE TITLE
Recherche : une requete avec un pourcentage en "%" fait bloquer la recherche

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#2196]
bug: une requête qui contient le caractère % (ce qui est clairement possible) ne peut pas se lancer. 

requetes tests
ex:
 majoration de 25% 
baisse de 10% du salaire

conséquences constatées
1. la requête ne se lance pas 
2. 
![image](https://user-images.githubusercontent.com/37538697/71979895-22f3cf00-321f-11ea-9bfe-ace2d3a4fc76.png)

**Comment by UnbearableBear** [comment]
Bien vu !!
