### ISSUE TITLE
Outils externes: identification sur le site

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#2198]
### Situation:
Aujourd'hui les outils externes sont présentés comme suit:

- page résultat: en tant que résultat

![image](https://user-images.githubusercontent.com/37538697/71988651-8b977780-3230-11ea-8072-569039ff5e73.png)

- page outils: 

![image](https://user-images.githubusercontent.com/37538697/71988141-a61d2100-322f-11ea-9bed-f1018fba1994.png)

### Résolution

Design prévu dans les maquettes:

![image](https://user-images.githubusercontent.com/37538697/71988506-5428cb00-3230-11ea-96f8-9efd056c67bc.png)

**Comment by ClementChapalain** [comment]
Ce que tu montres dans les outils, ce sont les liens externes des contenus, et non les outils externes que l'on référence nous-même
