### ISSUE TITLE
Ajout des trackers pour la campagne d'acquisition

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#2200]
Nous allons faire une campagne d'acquisition de trafic payant (google, réseaux sociaux) géré par une agence externe. Pour mesurer l'efficacité de la campagne il faut que nous implémentions leurs trackers sur le CDTN.

### Trackers

Les deux trackers à implémenter sur toutes les pages sont les suivants (attention, le deuxième tracker contient un paramètre dynamique à remplir avec l'url de la page courante) : 
```
<!-- 
Start of global snippet: Please do not remove
Place this snippet between the <head> and </head> tags on every page of your site.
-->
<!-- Global site tag (gtag.js) - Google Marketing Platform -->
<script async src="https://www.googletagmanager.com/gtag/js?id=DC-3048978"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'DC-3048978');
</script>
<!-- End of global snippet: Please do not remove -->
```

```
<!--
Event snippet for iTag-2020-01-MinduTravail-CodeTravailNumerique-LP on https://code.travail.gouv.fr/: Please do not remove.
Place this snippet on pages with events that you’re tracking. 
Creation date: 01/03/2020
-->
<script>
  gtag('event', 'conversion', {
    'allow_custom_scripts': true,
    'u1': '[URL]',
    'send_to': 'DC-3048978/emplo253/lpcodet+unique'
  });
</script>
<noscript>
<img src="https://ad.doubleclick.net/ddm/activity/src=3048978;type=emplo253;cat=lpcodet;u1=[URL];dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;npa=;ord=1;num=1?" width="1" height="1" alt=""/>
</noscript>
<!-- End of event snippet: Please do not remove -->
```

### Gestion de l'acceptation

Ces deux trackers **doivent** être acceptés par les utilisateurs avant de les intégrer à leur session. Ainsi, lorsqu'un utilisateur arrive sur le CDTN et qu'il n'a pas ces cookies, nous devons lui demander la permission pour les mettre.

L'utilisateur doit également toujours pouvoir activer / désactiver le tracking depuis une page dédiée (dans la section `Utilisation de témoins de connexion (« cookies »)` de la page Mentions légales par exemple).

@revolunet propose de regarder ça pour gérer l'acceptation : https://opt-out.ferank.eu/fr/

**Comment by ClementChapalain** [comment]
du coup je recap les commentaires sur la première version : 
en terme d'UX 2 remarques : 
  - [x] la modale qui s'affiche au départ devrait prendre la forme d'un bandeau (idem que celui qu'on a aujourd'hui), la modale de paramétrage peut quand à elle rester avec son design standard
  -  [x] le module toujours visible en bas à droite devrait être uniquement accessible depuis la page mentions légales
- [x] forcer la langue FR pour les navigateurs qui ne sont pas en FR
- [ ] vérifier avec la personne de l'agence qu ça fonctionne bien, ping @abdessamad.youssfi

**Comment by lionelB** [comment]
@ClementChapalain j'ai modifié ton commentaire pour mettre des cases à cocher

**Comment by Abdessamadyssf** [comment]
Hello
Malheureusement pas de remontée des données dans l'adserver côté Agence.

Voici l'explication du problème :

_Malheureusement nos tests de remontées de données sont négatifs. En effet je ne remonte pas de conversions sur l’adserver suite à mes clics.

Dans le code envoyé il y a 2 parties : un global snippet + un event snipper. En regardant rapidement le code de la page je ne vois pas le global snippet implémenté sur toutes les pages du site. Peux-tu me confirmer s’il a été implémenté ?

Sans global snippet les données ne sont pas envoyés à l’adserver malgré le fait que je voyait l’event snippet bien intégré vendredi soir.

Par ailleurs, la variable u1 doit qui remonter l’extension d’url comme on avait vu ensemble au téléphone, remonte un valeur dclid ou %F. Aurais-tu un moyen d’encodée l’url afin que cela passe ?

![image001](https://user-images.githubusercontent.com/56535039/72717693-d7251c00-3b74-11ea-91ef-0b9610f1e602.jpg)
![image003](https://user-images.githubusercontent.com/56535039/72717695-d8564900-3b74-11ea-918f-773b9fbec519.jpg)

Serait-ce plus simple si je te renvoyait le code en javascript simple et non en global site tag ?_

@lionelB
