### ISSUE TITLE
Intégrer les contributions aux CC locales

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#2213]
cf. message de nadia : 
> hello @julien.bouquillon , @Clément Chapalain et @lionelb . Avec Laura, on s'est rendu compte que les contrib des CC métallurgie locales ne sont pas en ligne sur le CDTN. Ni sous forme de contribution, ni dans une page CC. Pourtant, nous avons bien validé plusieurs CC métallurgie au moins de décembre. (voici quelques numéros de CC : 2542, 860) Pour rappel, ces CC métallurgie ne sont pas sur Legifrance. (Il n'y a qu' 1 ou de 2 CC métallurgie sur legifrance, et donc aussi sur le CDTN, mais ce sont des CC "nationales".) Est-ce qu'il serait possible de mettre en ligne, sur le CDTN, les CC métallurgie déjà en statut "publié" dans l'outil de contrib ? 

et la liste des CC : 
![image](https://user-images.githubusercontent.com/5337489/72141991-15138a80-3394-11ea-98fc-43e0d6e08318.png)

**Comment by revolunet** [comment]
Ca a été intégré dans notre référentiel kali-data : https://github.com/SocialGouv/kali-data/pull/50

On teste sur CDTN
