### ISSUE TITLE
Verifier la récupération des références dans les contributions

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#2215]
Sur 5000 références disponibles dans l'api de contrib, environ 500 sont des référence au code du travail ("category": "labor_code"), mais seulement 4 apparaissent dans notre export de contributions

cc @ivangabriele @revolunet

**Comment by revolunet** [comment]
Côté fetch des données contributions, il n'y a pas de code spécifique pour les references du `labor_code`

https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-data/dataset/contributions/index.js#L70


CDT refs 549
CDT refs with known answers 4

apparemment le `answer_id` de 545 references n'est pas dans les answers publiées

**Comment by revolunet** [comment]
une petite idée là-dessus @ivangabriele ?

**Comment by ivangabriele** [comment]
@lionelB @revolunet À l'heure actuelle, les références sont en effet toutes accessibles publiquement, même si les questions auxquelles elles sont rattachées ne sont pas publiées.

Limiter ce qui est public dans les références est dans ma todo list !

**Comment by ClementChapalain** [comment]
Hello ! Est-ce que vous pouvez préciser ce qui pose problème fonctionnellement svp ? Pour qu'on puisse se mettre d'accord sur la priorisation de cette tâche ?

**Comment by lionelB** [comment]
J'ai ouvert cette issue car on a besoin de vérifier qu'on remonte bien les toutes les références associée à une contribution. c'est plus clair ?

**Comment by ClementChapalain** [comment]
OK mais du coup vous avez repéré des cas où il manque des références ? Ou c'est juste un double check ?

**Comment by revolunet** [comment]
RAS de notre côté; @ivangabriele va créer une nouvelle vue côté API contributions pour nous fournir directement les données sans besoin de traitement de notre côté : https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-data/dataset/contributions/index.js#L25

**Comment by lionelB** [comment]
je propose de fermé et de faire un issue lorsqu'on mettra à jour la récupération des contributions + refacto des data des ccn dans contributions
