### ISSUE TITLE
Bug UI police accordéon fiche SP et MT 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2226]
En naviguant sur les pages contenus (fiches SP et fiches MT), je me suis rendue compte que la police des accordéons n'est pas traitée de la même manière. 

Exemples : 

- une fiche MT : https://master-code-travail.dev.fabrique.social.gouv.fr/fiche-ministere-travail/amenagement-du-temps-de-travail#Quelles-sont-les-obligations-d-information-de-l-employeur
![image](https://user-images.githubusercontent.com/48682104/72248470-899a3380-35f7-11ea-94fc-f0a5ae4cad05.png)

- une fiche SP : https://master-code-travail.dev.fabrique.social.gouv.fr/fiche-service-public/temps-de-travail-du-salarie-amenagement-des-horaires
![image](https://user-images.githubusercontent.com/48682104/72248504-a0408a80-35f7-11ea-9604-39206729ba58.png)

Pourtant, de ce que je vois dans le code (attention, je dis peut être des bêtises... ahah), j'ai l'impression qu'ils sont traités de la même manière càd en H3 : 

- Fiche MT 
![image](https://user-images.githubusercontent.com/48682104/72248668-fe6d6d80-35f7-11ea-94d3-0a478b4e9018.png)

- Fiche SP 
![image](https://user-images.githubusercontent.com/48682104/72248790-4a201700-35f8-11ea-8c8b-0e7e5642f4e8.png)

Mais bon vu que j'y connais rien je vous laisse regarder ahah :) 

****Selon l'UI de Cécile, il faudrait que la police des accordéons soit traitée comme celle des fiches MT****

**Comment by virginielastisneres** [comment]
J'ai l'impression qu'il y a aussi un problème avec les accordéons de la page qu'est ce que le droit du travail ===> https://master-code-travail.dev.fabrique.social.gouv.fr/droit-du-travail

**Comment by UnbearableBear** [comment]
C'est une fine analyse :) Je regarde ce qu'il se passe

**Comment by virginielastisneres** [comment]
:female_detective:

**Comment by virginielastisneres** [comment]
et là c'est bizarre le titre de l'accordéon est en H3 et le sous titre en H4 mais il apparait 2 fois plus grand que le H3... ===> https://code.travail.gouv.fr/fiche-ministere-travail/les-delegues-syndicaux#Quel-est-le-nombre-de-delegues-syndicaux
![image](https://user-images.githubusercontent.com/48682104/72275833-04327580-362f-11ea-92b3-e65894ca43fa.png)

**Comment by UnbearableBear** [comment]
C'est parce que j'ai forcé le rendu sur les accordéons des fiches-mt du premier niveau et laissé le rendu en fonction du niveau de titre sur tous les autres accordéons mais je vias régler !

**Comment by virginielastisneres** [comment]
d'acc :D merciii !
