### ISSUE TITLE
a11y: ajouter un mecanisme pour notifier le changement de page pour les lecteurs d'écran

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#2227]
actuellement, l'utilsateur avec un lecteur d'ecran n'est pas au courant que la page a changer, le focus n'est pas replacé en haut de la page et aucune indication n'est donnée, une fois la navigation faite.

pistes: https://github.com/zeit/next.js/issues/7681

**Comment by ClementChapalain** [comment]
pour le focus on a #2224

**Comment by lionelB** [comment]
c'est lié ! probablement que la PR fixera les 2 :)
