### ISSUE TITLE
bug UI:  Pages articles du Code du travail et interface de feedback 

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#2228]
Le bloc de feedback apparait en bas de l'encart de l'article, quasiment à l'intérieur de celui ci:

![image](https://user-images.githubusercontent.com/37538697/72257185-48138380-360b-11ea-9d9d-4d562f8a5c85.png)

Le détacher dans l'esprit des pages des fiches: 

![image](https://user-images.githubusercontent.com/37538697/72257632-63cb5980-360c-11ea-881e-152d822cce72.png)

**Comment by UnbearableBear** [comment]
Ah flute, je n'avais pas vu que l'on pouvait avoir un contenu aussi court. C'est embêtant pour le design :thinking:

**Comment by lionelB** [comment]
avec un min-height de 300px
![image](https://user-images.githubusercontent.com/160320/72621442-89749d80-3941-11ea-81ae-3d9cd44f56c6.png)

ps: @jrduscher hésite pas à mettre l'url de la page incriminée
