### ISSUE TITLE
UI outils : alignement boutons / espace entre boutons

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#2231]
<img width="965" alt="Capture d’écran 2020-01-13 à 14 26 21" src="https://user-images.githubusercontent.com/124937/72265519-efe57d00-361c-11ea-82dc-271ec1d3bc39.png">

**Comment by UnbearableBear** [comment]
Je regarde

**Comment by lionelB** [comment]
ah oui j'avais vu ca ): un align-items: flex-end marche pas mal. ca permet de laisser le margin top du bouton "précédent"

**Comment by UnbearableBear** [comment]
C'est un oubli de ma part, le margin top du bouton précédent était supposé etre là qu'en mobile :/

**Comment by virginielastisneres** [comment]
Je profite de ton issue julien pour rajouter cela : 
![image](https://user-images.githubusercontent.com/48682104/72277309-fcc09b80-3631-11ea-8ed3-e0174edb51af.png)

Il y a un peu trop d'espace entre montant /le champ de remplissage/supprimer
