### ISSUE TITLE
Liens non désirés dans les fiches MT

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#2241]
Supprimer les liens cachés dans les fiches MT

Exemple sur la fiche `/les-delegues-syndicaux` 

<img width="632" alt="Screenshot 2020-01-14 at 11 34 02" src="https://user-images.githubusercontent.com/705453/72336881-e95d1100-36c1-11ea-9932-779aa762c261.png">

A faire au niveau du scrapping

**Comment by lionelB** [comment]
En utilisant textContent , ca devrait virer les balise `<a>` vides
