### ISSUE TITLE
Nouveau logo

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#2244]
La direction de la communication a élaboré un nouveau logo afin de mettre le CDTN dans la charte du ministère, et notamment en cohérence avec mon compte formation : 
https://drive.google.com/open?id=1KbQ78DVo3MqxZx8ETl8M66HHQArcGqZJ

L'idée est de l'intégrer : 
- à la place du texte "Code du travail numérique" dans le header blanc (tout en gardant la marianne)
- sur la page d'accueil à côté de la marianne

Ce doit être prêt pour la conférence de presse de jeudi après-midi :)

**Comment by ClementChapalain** [comment]
c'est moi qui ai fait le svg avec figma si ça convient pas dites moi !

**Comment by lionelB** [comment]
nickel à part la couleur ;)

**Comment by lionelB** [comment]
![image](https://user-images.githubusercontent.com/160320/72350529-e7ee1180-36de-11ea-937a-70ace5f73f88.png)
![image](https://user-images.githubusercontent.com/160320/72350597-07853a00-36df-11ea-88a8-e45c3277e571.png)

![image](https://user-images.githubusercontent.com/160320/72350547-f0464c80-36de-11ea-8fbd-7e189a6a46b8.png)

![image](https://user-images.githubusercontent.com/160320/72350629-1835b000-36df-11ea-87bf-5ecf3f41a804.png)

**Comment by lionelB** [comment]
![image](https://user-images.githubusercontent.com/160320/72351923-93986100-36e1-11ea-942f-ee0e719e306c.png)

**Comment by lionelB** [comment]
![image](https://user-images.githubusercontent.com/160320/72352004-c6daf000-36e1-11ea-8add-8c99a5481b75.png)

**Comment by ClementChapalain** [comment]
merci je te tiens au courant rapidement !

**Comment by ClementChapalain** [comment]
@lionelB peut-on essayer avec le logo ministère dans le header mais cette version du logo ministère stp : 
https://drive.google.com/open?id=1MEkjTrMCXhY9r4yPrM0fKv4HV7_qOfQE

**Comment by lionelB** [comment]
est ce qu'on pourrait avoir une vrai version svg et pas un png url-encodé ou alors le svg directement ?

**Comment by lionelB** [comment]
![image](https://user-images.githubusercontent.com/160320/72361367-a9158700-36f1-11ea-907a-54b09569a3e7.png)
bof :/

![image](https://user-images.githubusercontent.com/160320/72361415-c34f6500-36f1-11ea-93d1-0f691f4c5b36.png)
