### ISSUE TITLE
Erreur contenu

### ISSUE THREAD

**Issue by marie38500** [SocialGouv/code-du-travail-numerique#2256]
**Description** Sur la page
https://code.travail.gouv.fr/fiche-service-public/registres-du-personnel-obligatoires
Partie "Registre des accidents bénins"
Le texte _"En annexe, doivent y figurer les données collectives d'exposition aux facteurs de pénibilité, évalués selon les critères du compte personnel de prévention de la pénibilité (CPPP). Le défaut de transcription ou de mise à jour du document d'évaluation des risques peut être sanctionné d'une contravention de 1 500 € (3 000 € en cas de récidive)."_ n'est pas à sa place. Il doit figurer dans la partie suivante "Document unique d'évaluation des risques".

**Comment by jrduscher** [comment]
Bonjour,
Merci pour votre signalement.
Nous faisons le même constat: ces éléments concernent bien le document unique  et non le registre des accidents bénins. 
Par contre ils figurent bien également dans la partie portant sur le DUERP.
Pour autant, nous transmettons votre signalement aux rédacteurs de cette fiche.
