### ISSUE TITLE
404 NOT FOUND

### ISSUE THREAD

**Issue by marie38500** [SocialGouv/code-du-travail-numerique#2257]
Page https://code.travail.gouv.fr/fiche-ministere-travail/cse-attributions?q=CSE
Les liens  « Questions/Réponses » sur le CSE mis en ligne sur notre site" affichent l'erreur 404 NOT FOUND

**Comment by lionelB** [comment]
Bonjour, 
La page étant toujours accessible, je me permets de fermer ce ticket. 
N'hésitez pas à en ouvrir d'autres, si vous souhaitez nous signaler d'autres problèmes.
