### ISSUE TITLE
Rendre accessible au clavier la selection de ccn dans les outils / contribution

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#2265]
Actuellement la selection d'une ccn au clavier ou avec un outils comme voice over n'est pas possible car seul le lien vers la fiche entrerprise est selectionnable (au clavier)

**Comment by ClementChapalain** [comment]
J'ai vu qu'on pouvait y accéder avec les tabs du coup est-ce prio ?

**Comment by ClementChapalain** [comment]
On a vu avec @virginielastisneres qu'en fait ça fonctionnait sur la page https://code.travail.gouv.fr/convention-collective/recherche mais pas dans les outils
