### ISSUE TITLE
Gestion des mise en prod de patch

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#2268]
Hello, 
Je pense qu'il serait utile de s'aligne sur les urgences et les délais qu'on se donne pour les traiter et mettre en prod un patch qu'il soit tech ou légal.

poke @ClementChapalain @virginielastisneres, @jrduscher @revolunet @UnbearableBear @nkrmr

**Comment by ClementChapalain** [comment]
Hello, oui très bonne idée :) C'est lié aux problématiques de veille et administration sur lesquelles travaille @virginielastisneres

**Comment by lionelB** [comment]
je propose de fermer car non fait, et peut etre moins nécessaire avec la mise à jour auto des contenu

**Comment by lionelB** [comment]
la mise à jour des données (patch) se fait automatiquement. Pour l'instant il n'y a pas de délais particulier sur le délais de gestion des erreurs.
