### ISSUE TITLE
Mise à jour données LEGI

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#2270]
Suite à la diminution des quotas sur l'API DILA, les articles du code n'ont pas été récupérés correctement depuis le 20/12/2019. Une correction vient d'être faite et les dernières mises à jour sont dispos pour la prochaine MEP. (ex: article R1452-1)

Une correction doit être faite au niveau du script de récupération de legi-data pour que l'on soit bien alerté en cas de défaillance. Actuellement la mise à jour est simplement skippée lorsque cela se passe mal, il faudra que le pipeline fail pour qu'une alerte soit envoyée

**Comment by lionelB** [comment]
> depuis le 20/12/2019.

😱

**Comment by revolunet** [comment]
-> https://github.com/SocialGouv/code-du-travail-numerique/pull/2272
