### ISSUE TITLE
Affichage des références juridiques dans les contributions

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#2273]
Dans la page CCN: les réf jdques qui s'affichent sont précis. ( article)

![image](https://user-images.githubusercontent.com/37538697/72821672-1fc1ff80-3c71-11ea-9c6a-8be456659f0c.png)

une fois sur la page de la contribution, pour la même question il n'est fait référence qu'aux textes  seuls et plus aux articles ( ce qui génère des doublons):
![image](https://user-images.githubusercontent.com/37538697/72821796-50a23480-3c71-11ea-9505-6354d6dd7070.png)

**Comment by revolunet** [comment]
dans la page de contribution, reprendre le texte qui a été saisi par les expert.e.s

**Comment by revolunet** [comment]
NB : à partir de la page contributions, une fois la CC choisie, il n'est plus possible d'aller vers la CCN complète, je ne sais pas si c'est normal ?

<img width="624" alt="Capture d’écran 2020-02-03 à 14 52 30" src="https://user-images.githubusercontent.com/124937/73658561-d4f2af80-4694-11ea-85de-fa0489a9f2a3.png">
