### ISSUE TITLE
Erreur à la sélection de la CCN 1090

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#2274]
Depuis la page de recherche de convention collective: Erreur 500
: https://code.travail.gouv.fr/convention-collective/1090-services-de-lautomobile-commerce-et-reparation-de-lautomobile-du-cycle

Autre exemple: même souci avec la 2216.

**Comment by lionelB** [comment]
les infos de ccn sont bien généré, l'api répond bien, le problème doit venir du front
