### ISSUE TITLE
Problème d'encodage de l'url lors de la recherche

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#2279]
Si je lance un recherche sur le cdtn, l'url est mise à jour et la recherche est encodée dans celle-ci

Si je tape "démission", l'url devient: /recherche?q=d%25C3%25A9mission. Si par la suite je clique sur un résultat de recherche, l'url n'est plus encodée, ce qui est étrange mais soit.

Le problème est que si je rerentre ensuite l'url encodée sur chrome (pas testé sur les autres navigateurs), celle de la page de résultats donc, la recherche se retrouve renseignée avec les caractères encodés et aucun résultat ne remonte.

**Comment by lionelB** [comment]
> Le problème est que si je rerentre ensuite l'url encodée sur chrome 

c'est dire tu met `d%25C3%25A9mission` dans le champ de recherche ?

**Comment by UnbearableBear** [comment]
Si tu cliques sur refresh alors que l'url est encodée plutôt ou que tu la copie colle dans un autre tab, mais ça revient au même oui

**Comment by ClementChapalain** [comment]
Oui du coup le problème utilisateur derrière c'est qu'on ne peut pas sauvegarder ou partager une url de recherche avec des caractères spéciaux.

**Comment by UnbearableBear** [comment]
Already fixed by @revolunet who removed the extra URI encoding already done by the router package
