### ISSUE TITLE
Page contribution non accessible depuis la recherche - IE11 + Firefox

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#2281]
**Description**
sur IE11, il y a une erreur de script dans la page  contribution. Les contribution ne sont pas accessible depuis la page de resultat de recherche. Si l'on ouvre la page dans une nouvelle onglet (on en acces direct) le contenu est affichés mais non interactif (accordeon / onglet ) la  recherche cc ne marche pas non plus

**Reproduction**
Etapes à suivre pour reproduire le bug
1. Faire une recherche sur "durée cdd"
3. cliquer sur une contrib
4. la page ne s'affiche pas

**Comportement attendu**

**Comment by ClementChapalain** [comment]
problème reproduit sur firefox aussi

**Comment by virginielastisneres** [comment]
Problème sur firefox que sur les pages des contributions (exemple de page => https://code.travail.gouv.fr/contribution/quelle-est-la-duree-de-preavis-en-cas-de-licenciement). 
Quand j'arrive sur cette page voilà ce qui apparait 
![image](https://user-images.githubusercontent.com/48682104/72907665-89571200-3d34-11ea-9f07-af6543e78194.png)
Pour clément et JR c'est bon mais pas pour moi, voilà ma version
![image](https://user-images.githubusercontent.com/48682104/72907626-72b0bb00-3d34-11ea-9eaa-4f0c6bc2964c.png)

**Comment by ClementChapalain** [comment]
IE = 9.3% des utilisateurs, je priorise pour le sprint 32

**Comment by lionelB** [comment]
seems to be related to rehype-raw (will try to add it to transpile module)
