### ISSUE TITLE
le formulaire de recherche force le rechargement de la page (sauf ie)

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#2283]
lorsqu'on fait une recherche, la page de recherche se recharge au lieu de faire un requete ajax

**Comment by ClementChapalain** [comment]
Je ne vois pas trop le pb, la recherche se fait vraiment instantanément et si la page se recharge on ne s'en rend pas du tout compte

**Comment by lionelB** [comment]
le problème a été résolu
