### ISSUE TITLE
Exemple de données utilisées pour le NLP

### ISSUE THREAD

**Issue by alexgarel** [SocialGouv/code-du-travail-numerique#2285]
**Fonctionnalité**

Donner un exemple des données utilisées pour le NLP, où en décrire formellement le format, pour permettre l'entraînement avec des données différentes.

**Problème**

Le chargement des données se fait depuis [une image docker](https://github.com/SocialGouv/code-du-travail-numerique/blob/v4.2.0/packages/code-du-travail-nlp/Dockerfile#L2) qui ne semble pas disponible au publique (l'instance est dans le registre [du gitlab privé du ministère](https://gitlab.factory.social.gouv.fr/)). Si c'est normal que ces données soient privées, on ne peut par contre pas en deviner simplement la structure (il faut lire tout le code pour essayer de la deviner) ce qui limite la réutilisation du code, pourtant bien pensé.

**Solution**

Donner un court extrait des données qui en expose la structure (que j'imagine simple), ou, si c'est plus complexe, donner la définition de leur structure.
Un petit paragraphe dans le README peut suffire.

**Comment by lionelB** [comment]
Hello,

Merci pour ton commentaire. L'image docker en question est l'image docker principale, c'est à dire celle correspondant à ce [Dockerfile](https://github.com/SocialGouv/code-du-travail-numerique/blob/master/Dockerfile)
On peut donc créer l'image en local 
```
# Build the monorepo image
$ docker build . -t cdtn_master:local
``` 
Pour le modèle nlp utilisé, il faut aller voir du coté du dossier [code-du-travail-nlp](https://github.com/SocialGouv/code-du-travail-numerique/tree/master/packages/code-du-travail-nlp) 
c'est un modèle "générique" fourni par google. Nous allons essayer de travailler sur un modèle dédié à notre domaine et, à ce moment là, on documentera au mieux le format utilisé pour entrainer le modèle.

Je note aussi pour le README, il faut qu'on le mette à jour ! 

Si tu as d'autres questions n'hésite pas.
