### ISSUE TITLE
Bugs sur IE(mintrav): moteur de recherche est down.

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#229]
rien à voir avec ça: https://github.com/SocialGouv/code-du-travail-numerique/issues/88

ES ne semble plus fonctionner sous IE depuis la dernière mise en prod.
pas de susggestions, requetes n'aboutissant pas.

**Comment by lionelB** [comment]
Il faudrait qu'on ai la version de IE (ou Edge) pour pouvoir refaire les tests avec les bon navigateur
j'ai fait un test avec Edge 13 et le search fontionne. le Pb d'affichage des thems viens du fait qu'on utilise les css variables, que c'est pas supporté dans cet version et que le polyfill est foireux :) il ne remplace pas la la `var(--flex-gutter-size)`
