### ISSUE TITLE
Création d'une page statique "Politique de confidentialité"

### ISSUE THREAD

**Issue by ThomasMenant** [SocialGouv/code-du-travail-numerique#2292]
**Description**
Pour se conformer aux récentes remarques sur les mentions légales du produit, il parait judicieux de créer un lien dans le footer du site intitulé "Politique de confidentialité".

Le texte proposé pour la page statique est présenté ci-après.
https://hackmd.io/@B1L7UIS9RGmBQIZVteFFjg/BkSJMi_ZU
[Politique de confidentialité.zip](https://github.com/SocialGouv/code-du-travail-numerique/files/4109734/Politique.de.confidentialite.zip)

***
# Politique de confidentialité 

## Traitement des données à caractère personnel
Le code du travail numérique ne vous demande ni ne stocke d’information nominative.

Pour autant, nous enregistrons les informations saisies dans la barre de recherche. Elles sont conservées pendant deux années pour analyser les usages, améliorer la précision des réponses apportées et améliorer le service.

Nous nous engageons à ne jamais céder ces informations à des tiers.

Vous avez un droit d’accès, de rectification et de suppression de vos données. Pour l’exercer, faites-nous parvenir une demande en précisant la date et l’heure précise de la requête - ces éléments sont indispensables pour nous permettre de retrouver votre recherche - par voie électronique à l’adresse suivante : [codedutravailnumerique@travail.gouv.fr](mailto:codedutravailnumerique@travail.gouv.fr) ou par voie postale :

*Direction des systèmes d’information
Ministère des affaires sociales et de la santé
39-43 Quai André Citroën
75015 PARIS*

## Utilisation de témoins de connexion (« cookies »)
Un cookie est un fichier déposé sur votre terminal lors de la visite d’un site. Il a pour but de collecter des informations relatives à votre navigation et de vous adresser des services adaptés à votre terminal (ordinateur, mobile ou tablette). 

Nous collectons donc des données par l’intermédiaire de dispositifs appelés “cookies” permettant d’établir des mesures statistiques.

Ces cookies permettent au Code du travail numérique d'établir des mesures statistiques de fréquentation et d'utilisation du site. Pour ce faire, nous utilisons les services proposés par la suite [Google Analytics](https://support.google.com/analytics/answer/9019185?hl=fr&ref_topic=2919631).

Il convient d'indiquer que :
* Les données collectées ne sont pas recoupées avec d’autres traitements.
* Les cookies ne permettent pas de suivre la navigation de l’internaute sur d’autres sites.
* Les cookies sont inactifs avant que vous ayez exprimé votre consentement en cliquant sur le bouton "Ok, tout accepter" ou après que vous ayez pris le soin de personnaliser vos préférences. 

**[BOUTON MODIFIER LES REGLAGES]**

À tout moment, vous pouvez refuser l’utilisation des cookies et désactiver le dépôt sur votre ordinateur en utilisant la fonction dédiée de votre navigateur (fonction disponible notamment sur Microsoft Internet Explorer 11, Google Chrome, Mozilla Firefox, Apple Safari et Opera).

Pour aller plus loin, vous pouvez consulter les fiches proposées par la Commission Nationale de l'Informatique et des Libertés (CNIL) : 
* [Cookies & traceurs : que dit la loi ?](https://www.cnil.fr/fr/cookies-traceurs-que-dit-la-loi)
* [Cookies : les outils pour les maîtriser](https://www.cnil.fr/fr/cookies-les-outils-pour-les-maitriser)

**Comment by lionelB** [comment]
closed by #2294
