### ISSUE TITLE
ES - maintenance et amélioration du cluster

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#2295]
plusieurs petites taches a faire sur elasticcloud
- separer les cluster de prod et dev
- migrer en version 7.5.2
- etudier l'externalisation le fichier de synonymes 
- mettre en route un APM

**Comment by revolunet** [comment]
MAJ

 - création d'un cluster `cdtn-prod` en 7.4.2 avec APM + monitoring
 - création d'un cluster `cdtn-dev` en 7.5.2 avec APM + monitoring

**Comment by lionelB** [comment]
l'externalisation des synonymes sera realisée plus tard (support elasticcloud)
