### ISSUE TITLE
Thème "null" dans la page CC bricolage

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#2297]
Thèmes de contribution dans la page CCN: "null" dans la CCN Bricolage
![image](https://user-images.githubusercontent.com/37538697/72846282-94606280-3ca0-11ea-87b1-a103b09cb688.png)

https://code.travail.gouv.fr/convention-collective/1606-bricolage-vente-au-detail-en-libre-service

**Comment by jrduscher** [comment]
je ne sais pas si c'est lié au même problème:
ici pour la n°176, il manque des contrib.
![image](https://user-images.githubusercontent.com/37538697/73835312-7866d000-480d-11ea-856a-00cea02ac254.png)
par exemple pour les heures de recherche d'emploi on devrait avoir une réponse normallement

**Comment by revolunet** [comment]
Cette contribution, comme quelques autres n'a pas de thème défini.

J'imagine que c'est dû au fait qu'on a pas de vision, dans le DF, des contributions non thémées ?

Liste  des contributions non thémées : 

 - Convention collective nationale des entreprises de prévention et de sécurité du 15 février 1985.  Etendue par arrêté du 25 juillet 1985 (JO du 30 juillet 1985): Dans le cadre d’un contrat de mission (intérim), quel est le montant de l’indemnité de fin de contrat ?

 - Convention collective nationale de l'immobilier, administrateurs de biens, sociétés immobilières, agents immobiliers, etc. (anciennement cabinets d'administrateurs de biens et des sociétés immobilières), du 9 septembre 1988. Etendue par arrêté du 24 février 1989 JORF 3 mars 1989. Mise à jour par avenant  n° 47 du 23 novembre 2010, JORF 18 juillet 2012 : Dans le cadre d’un contrat de mission (intérim), quel est le montant de l’indemnité de fin de contrat ?

 - Convention collective nationale du bricolage (Vente au détail en libre-service) du 30 septembre 1991.  : Dans le cadre d’un contrat de mission (intérim), quel est le montant de l’indemnité de fin de contrat ?

 - Convention collective régionale des ouvriers du bâtiment de la région parisienne du 28 juin 1993. Etendue par arrêté du 9 décembre 1993 JORF 24 décembre 1993.: Dans le cadre d’un contrat de mission (intérim), quel est le montant de l’indemnité de fin de contrat ?

 - Convention collective nationale des télécommunications du 26 avril 2000: Dans le cadre d’un contrat de mission (intérim), quel est le montant de l’indemnité de fin de contrat ?

 - Convention collective nationale des assistants maternels du particulier employeur du 1er juillet 2004.  Etendue par arrêté du 17 décembre 2004 JORF 28 décembre 2004.: Dans le cadre d’un contrat de mission (intérim), quel est le montant de l’indemnité de fin de contrat ?"

**Comment by revolunet** [comment]
Est-ce qu'on peut déjà afficher "Autres" au lieu de "null" ?

**Comment by nkrmr** [comment]
Yes je m'en occupe
