### ISSUE TITLE
Ajouter un lien dans le footer pour devenir ambassadeur

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#2298]
wip :)

**Comment by Abdessamadyssf** [comment]
Mettre "Devenir ambassadeur" dans le footer au niveau de la rubrique "Aidez-nous à améliorer cet outil" et insérer le lien suivant : https://calendly.com/code-du-travail-numerique/ambassadeur-du-code-du-travail-numerique

@ClementChapalain

**Comment by ClementChapalain** [comment]
lié à l'ajout d'un autre lien au même endroit cf. https://github.com/SocialGouv/code-du-travail-numerique/issues/2260#issuecomment-577272206

**Comment by virginielastisneres** [comment]
@ThomasMenant à voir avec Thomas également si nous avons des problématiques de RGPD ou pas

**Comment by UnbearableBear** [comment]
done here https://github.com/SocialGouv/code-du-travail-numerique/pull/2328
