### ISSUE TITLE
Page CC nouveau wording + design

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#2299]
wip

**Comment by virginielastisneres** [comment]
La Page CC va être revue un peu à la fois au niveau du design que du wording. 

**Ci-joint le lien vers le figma => https://www.figma.com/file/K9mtdecQeq5CGglxGsWSFB/Convention-collective?node-id=0%3A1**

page ancienne => https://code.travail.gouv.fr/convention-collective/2120-banque

### Globalement 

- [x] on traite le contenu comme le autres contenus (fiches SP, contributions etc...), c'est à dire contenu sur la gauche avec sur le côté à droite le module "Les articles pouvant vous intéresser :"

- [x] Serait-il possible d'avoir sur la droite dans le module "Les articles pouvant vous intéresser :", les 3 contenus suivants : 
- Fiche SP "Convention collective" : https://code.travail.gouv.fr/fiche-service-public/convention-collective?q=Convention%20collective
- Fiche SP "Comment consulter un accord d'entreprise ?" : https://code.travail.gouv.fr/fiche-service-public/comment-consulter-un-accord-dentreprise?q=Comment%20consulter%20un%20accord%20d%27entreprise%20?
- sous partie 3 Droit du travail du site : il faudrait amener l'utilisateur directement à la sous partie 3 "Existe-t-il une hiérarchie entre les textes ?"

### Haut de la page avec titre de la convention collective 

- [x] on rajoute le fil d'ariane

- [x] on rajoute le thème de la page qui est "Convention collective"

- [x] le titre de la CC reste comme avant : on utilise toujours les titres courts utilisés par légifrance

- [x] en dessous du titre de la CC on rajoute en petit son nom complet avec à côté l'IDCC (déjà présent dans l'ancienne page mais différent UX)

- [x] on rajoute en dessous du nom complet la source et la date d'entrée en vigueur (déjà présents dans l'ancienne version mais différent UX)

### Sous-partie 1 : Questions fréquentes 

- [x] on remplace "Questions fréquentes sur cette convention collective" par "Questions-réponses fréquentes"

- [x] on rajoute une phrase d'introduction sous le sous titre "Retrouvez les questions-réponses les plus fréquentes élaborées par le ministère du Travail concernant la convention collective organisées par thème." 

- [ ] petit changement au niveau des accordéons pour les thèmes des questions : supprimer les lignes entre. 

- [ ] quand on clique sur un thème, comme avant apparaît les questions associées sous forme d'accordéons également. mais cette fois on garde les lignes 

Quand on clique sur une question, on reste quasiment sur qu'il y avait avant. 
Petit point sur les références juridiques : on les inclus dans l'encart source qui est déjà présent sur d'autres contenus. Attention comportement différent en fonction : 
- [x] s'il y a 1 à 2 références juridiques : pas d'accordéon, visibles directement
- [x] s'il y a plus de 2 références juridiques : accordéon avec traitement des références comme le 
sont les références juridiques dans les contenus des fiches SP. 

- [x] petit changement UI au niveau du texte : "Pour savoir si la mesure prévue par la convention collective s'applique à votre situation, reportez-vous à la réponse complète à cette question."


### Sous-partie 2 : Articles de la convention 

- [x] le titre de la sous partie change, on passe de "Domaines traités par la convention collective" à "Articles de la convention collective"

- [x]  suppression du texte : "Recherchez, lorsqu'elles existent, les dispositions conventionnelles dans :
les 13 domaines où la loi reconnaît la primauté à la convention collective de branche ;
les 4 domaines où la branche elle-même peut reconnaitre sa primauté, sauf si l'accord d'entreprise a des garanties au moins équivalentes (représentées avec une * ci-dessous)."

- [x] rajout du texte introductif suivant : "Consultez les articles de la convention collective qui s’appliquent à votre situation dans les thèmes sélectionnés ci-dessous." 

- [x] rajout d'un "En savoir plus" en dessous avec un + à gauche. 
comportement attendu : quand on clique sur le + ou le "en savoir plus", le + tourne pour faire une croix x et apparaît un texte (cf. figma page 2)

- [ ] les thèmes sont en accordéons comme dans la sous partie 1, sans ligne entre. 

- [ ] quand on ouvre un thème apparaît les articles dans des rectangles (cf. page 6 et page 3)
Attention, 2 comportements différents à cette étape : 
- pour les articles du bloc 1 (les cas classiques) : affichage des articles 
- pour les articles du bloc 2 qui étaient identifiés par un astérisque * : on ajoute un message important avant d'afficher les articles 

### Sous-partie 3 : Recherche dans la convention collective 

- [x] changer le titre "Recherche par mots-clés" par "Recherche dans la convention collective"

- [x] changer la phrase d'introduction de la sous partie "Effectuez une recherche dans le texte de la convention collective sur Légifrance :" par "Recherchez par mots clés dans le texte de la convention collective sur le site Légifrance."

- [ ] modifier l'UI du placeholder (cf. figma)

- [ ] déplacer le texte d'alerte et le modifier (cf. figma) 
Dans le "En savoir en plus" cela amène à l'accordéon ouvert "Les conventions et accords collectifs" de la page Droit du travail.
