### ISSUE TITLE
Préavis de démission: CCN Transports

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#2313]
Suite à une remontée OPE.

Il faut modifier le wording d'une question:

personnel de conduite | Le salarié fait-il partie des personnels de conduite ?
-- | --

par

personnel de conduite | Le salarié fait-il partie des conducteurs dans le transport de voyageurs ?
-- | --

**Comment by revolunet** [comment]
@jrduscher comme la definition des questions est partagée entre 3 simulateurs, ce changement affectera également le wording dans preavis licenciement et heures de recherche d'emploi (si cette question à du sens). ok pour toi ?

**Comment by jrduscher** [comment]
@revolunet, à priori la question ne se pose que pour le dernier simulateur.
