### ISSUE TITLE
usage SearchCCN

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#2319]
- utilisation de l'outil depuis quelle page
 - nb de recherches
 - l'usager a-t-il trouvé sa CC ? (clic sur CC)

**Comment by virginielastisneres** [comment]
**Contexte**

Nous n'avons pas de données concernant l'utilisation et l'accessibilité de notre moteur de recherche des conventions collectives présent à la fois comme outil seul, intégré dans des outils et dans les contributions. 
![image](https://user-images.githubusercontent.com/48682104/74672356-642bb700-51ad-11ea-9c8a-d8037caee84a.png)


**Tracking à mettre en place**

L'idée est de mettre en place des événements de tracking dans matomo afin de savoir quelles sont les actions de l'utilisateur concernant ce moteur de recherche.

Proposition de plan de tagage :

Envoyer un événement à matomo lorsqu'un utilisateur fait une recherche dans le paceholder du moteur de recherche des conventions collectives :
category = cc_search
action = [outils/contributions/page]
name = [nom de la recherche]

Envoyer un événement à matomo lorsqu'un utilisateur fait clique sur une convention collective dans les résultats du moteur de recherche des conventions collectives :
category = cc_select
action = [outils/contributions/page]
name = [nom de la sélection]

**- outils représentent les outils**
**- contributions représentent les contributions**
**- et page représente la page de recherche des conventions collectives (https://code.travail.gouv.fr/convention-collective/recherche)**
