### ISSUE TITLE
Bug remontées de réponses déceptives par un user (DIRECCTE)

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#232]
// UTILE POUR INTERVENTIN ES
// test unitaire  
 - [ ] nécessite vérification métier 
 - [ ]  nécessite une fois le test
       unitaire fait, une vue ES

 **1. Un salarié detache intérimaire doit il avoir un relevé horaires ?:**  
[https://codedutravail.num.social.gouv.fr/?q=Un%20salari%C3%A9%20detache%20int%C3%A9rimaire%20doit%20il%20avoir%20un%20relev%C3%A9%20horaires%20%3F](https://codedutravail.num.social.gouv.fr/?q=Un%20salari%C3%A9%20detache%20int%C3%A9rimaire%20doit%20il%20avoir%20un%20relev%C3%A9%20horaires%20%3F)

Erreur sans doute due à une absence de contenu.  

 
[https://trello.com/c/ovx5SO2k/320-bug-r%C3%A9ponse-remont%C3%A9e-user-26-10](https://trello.com/c/ovx5SO2k/320-bug-r%C3%A9ponse-remont%C3%A9e-user-26-10)

Explication: une question complexe ( quatres notions distinctes et complémentaires: durée du travail, prestation de service internationale, travail temporaire; et en filigrane travail illégal)
La répons affichée
**2. Que ce passe t il en cas d'abus d'intérim ?**
https://codedutravail.num.social.gouv.fr/?q=Que%20ce%20passe%20t%20il%20en%20cas%20d%27abus%20d%27int%C3%A9rim%20%3F

propsiitons hors sujets:
Le CDT devrait matcher dans l'idéal.

 **3.Comment rompre le contrat de ma nounou quand mon enfant rentre à l'école**
 https://codedutravail.num.social.gouv.fr/?q=Comment%20rompre%20le%20contrat%20de%20ma%20nounou%20quand%20mon%20enfant%20rentre%20%C3%A0%20l%27%C3%A9cole
explication: pas de contenu sur le site sur ce point. Ici la répnose du site correct au regard du cas de figure: " nous n'avons pas la réponse"

- nounou ajouté aux synonymes assmat

 **4.  Quelles primes quand le chantier est loin de chez moi**
>  Je pensais obtenir les primes de trajet et transport dans le
> btp,
https://codedutravail.num.social.gouv.fr/?q=Quelles%20primes%20quand%20le%20chantier%20est%20loin%20de%20chez%20moi

Bine qu'on ait sans doute pas le contenu attedu;  l'user aurait sans doute au moins apprécié qu'on ui propose ce contenu générique:  https://codedutravail.num.social.gouv.fr/question/ouvrier-dune-entreprise-du-btp-travaillant-sur-chantiers-quelles-sont-les-indemnites-de-deplacements-auxquelles-je-peux-pretendre?q=chantier%20d%C3%A9placement&search=0

**Comment by ClementChapalain** [comment]
est-ce que tout le contenu est bien listé ici aujourd'hui ? https://docs.google.com/spreadsheets/d/1o6hf-Tm3rb5qMXRBId3aGuSt9tNalvxMsOkrbkHSbB4/edit#gid=0

si oui on peut fermer cette tâche ?

**Comment by jrduscher** [comment]
questions ajoutées. issue fermée
