### ISSUE TITLE
Interface annuaire local

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#233]
https://trello.com/c/DhnZZFa9/302-annuaire-integrer

- [ ] UI: recherche d'adresse ( geoloc)
- [ ] ajouter les services publics d'accès au droit Nouvelle Aquitaine.
- [ ] prévoir les tests utilisateurs

**Comment by jrduscher** [comment]
- [ ] https://github.com/SocialGouv/code-du-travail-numerique/issues/4

**Comment by jrduscher** [comment]
https://trello-attachments.s3.amazonaws.com/5a39344bf34cad983b377287/5bc0b1ea816c0e3e600b4084/884661516afce44e11e5b4fd56097899/Home.png

**Comment by revolunet** [comment]
<img width="636" alt="capture d ecran 2018-11-06 a 10 08 54" src="https://user-images.githubusercontent.com/124937/48053882-13f13700-e1ac-11e8-99af-5c4b6e4c3261.png">

**Comment by jeremiecook** [comment]
![annuaire](https://user-images.githubusercontent.com/88306/48058559-042b2000-e1b7-11e8-8598-4ce47f5f483a.png)

**Comment by lionelB** [comment]
closed by #357
