### ISSUE TITLE
UI again : dernière passe !

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2333]
L'UI étant intégrée, il est temps de faire une dernière passe sur des éléments qui ne vont pas, des rectifications, modifications, ajustement à apporter :)

Ci-dessous une liste to do : WIF

- [ ] "Les articles pouvant vous intéresser :" sur le côté n'est pas à la bonne taille 

- [ ] Dans les pages contenu (fiches SP, MT, Contributions) : la header 2 n'est pas aligné avec le header 3 

- [ ] "Texte applicable" sur les contributions il manque un peu de marge au dessus du titre dans l'encadré bleu. 

- [ ] Page résultat : les encarts des sous thèmes sont trop grands.

- [ ] Page CC : les thèmes des questions-réponses fréquentes ne sont pas dans le bon ordre. Le bon ordre est celui défini dans le datafiller pour les thèmes, c.-à.-d. : 
•	Embauche et contrat de travail
•	Salaire et Rémunération
•	Temps de travail
•	Congés et repos
•	Emploi et formation professionnelle
•	Santé, sécurité et conditions de travail
•	Représentation du personnel et négociation collective
•	Départ de l'entreprise
•	Conflits au travail et contrôle de la réglementation

- [ ] Page contribution encart "page personnalisée" sans convention collective sélectionnée : il serait bien de faire un retour à la ligne pour le "voir en bas de page" =>> #2436

**Comment by jrduscher** [comment]
Dans la modale  du lien "contact" dans le footer, mettre le point juste après "dédiés" et pas après la flèche: ![image](https://user-images.githubusercontent.com/37538697/76232798-843c1c80-6227-11ea-94e9-67bbea5026fa.png)
