### ISSUE TITLE
Proposer le téléchargement des fiches en pdf

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#2335]
Remontée d'un user: 
_Pouvez-vous mettre les dossiers en PDF pour nous permettre de les télécharger ? Cela nous évite de consulter le site toute la journée._ 

Sur chaque contenu "fiches":

- Générer l'enregistrement PDF du contenu:  Proposer à l'usager exactement le  contenu d'une en gardant sa mise en forme ( comme pour les impressions et en ajoutant les dates ( dans le document, comme pour une impression, et dans le titre, comme dans le téléchargement des modèles de courrier et la même forme que pour une impression)

- Proposer la fonctionnalité de téléchargement du pdf sur la page de contenu

UI ( à revoir)
![image](https://user-images.githubusercontent.com/37538697/73827833-8cf09b80-4800-11ea-8064-6fb6badb73a7.png)

**Comment by revolunet** [comment]
Fichier, imprimer puis "imprimer au format PDF" ?

**Comment by jrduscher** [comment]
+1, mais tous les usagers ont il bien connaissance de la manip? Et comment on fait avec un mobile?

**Comment by lionelB** [comment]
je suis pas sur que télécharger un pdf depuis le mobile soit un usage important 
il faudrait surtout valider le fait qu'on puisse imprimer l'intégralité de la page  (contenu des accordéons / tab) qui sont souvent cachés parce que généré les 14000 contenu, ca va être pénible à mettre en place à priori.
