### ISSUE TITLE
[SearchCCN]: trop de CCs renvoyées

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#2338]
Selon la recherche, par exemple "invest", on renvoie trop de résultats ES éloignés

ex: https://api-master-code-travail.dev.fabrique.social.gouv.fr/api/v1/idcc?q=Invest

Visiblement `Invest` renvoie les résultats `Industrie`

On affiche les 94 CCs trouvées puis les entreprises tout en bas. il faudrait p-e limiter le nombre de CCs affichées ou réduire la fuzzyness de la recherche

**Comment by virginielastisneres** [comment]
**Solution proposée**

Revoir un peu l'UX et l'UI des résultats affichés : 
figma ici =>> https://www.figma.com/file/wQgXKpQJFfN7tN9lRqiC0m/Untitled?node-id=76%3A503

- [ ] on ne présente que 4 résultats par catégories "Conventions collectives" et "Entreprises" ;

- [ ] on rajoute un "voir plus" pour chacune des catégories

- [ ] on sépare un peu les deux catégories pour bien les différencier

- [ ] et on rajoute le nombre de résultats que la recherche donne à côté de la catégorie pour orienter un peu l'usager
