### ISSUE TITLE
Page résultat contextualisée et enrichie de contenus

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#234]
https://trello.com/c/BDMp34F0/292-page-r%C3%A9sultat-contextualis%C3%A9e-et-enrichie

**Comment by lionelB** [comment]
from trello 
> - [ ] **page FAQ** 
> Afficher le contenu complémentaire sur la base de l'id eposeidon ( artilcles du code, règle hierarchie des normes, outils) tous les contenus taggés e-poseidon

**Comment by revolunet** [comment]
ok dans un premier je vais voir pour remettre ce qu'on avait dans le proto initial

**Comment by jrduscher** [comment]
je vois qu'on avais prévu qqch dans le trello pour la 1.5. je transferts dans la 1.5.

**Comment by jrduscher** [comment]
https://trello.com/c/20L2sBsT/307-todo-mettre-en-valeur-la-convention-collective-dans-la-r%C3%A9ponse-propos%C3%A9e

add texte réf: regles CCN/accords d'entreprise. L2253-1 et svts

**Comment by revolunet** [comment]
Je pars sur les hypothèses suivantes :
 - on se base (dans un 1er temps) sur la classification dans `themes.csv` pour regrouper nos contenus.
 - nous taggons manuellement (dans un 1er temps) les contenus avec un "id theme" (ou une référence à un article CDT)

Ceci va nous permettre, sur certains résultats, de retrouver ce qu'on avait dans le prototype initial :

Si le résultat affiché à un "id theme", on peut remonter :

 - les articles du code correspondants (cités dans theme.csv) et les affichons dans le bon ordre
 - en fonction des articles en jeu, affichage de la bonne "hierarchie des normes"
 - les questions SP qui mentionnent des articles du theme en question
 - les fiches DGT qui mentionnent des articles du theme en question
 - les autres FAQ du thème, modèles de courrier, outils...
 - les thèmes connexes

Comme suggéré par @lionelB, on pourrait ajouter un endPoint à l'api qui nous fournir tous les docs dispo à partir d'un (ou plusieurs) "id theme" donné.

Lorsqu'on affiche un résultat, on demande en plus ces infos pour "compléter" la page.

**Comment by lionelB** [comment]
![image](https://user-images.githubusercontent.com/160320/49859935-09543e00-fdf9-11e8-9206-a748d5a287b5.png)

**Comment by lionelB** [comment]
closed by #370
