### ISSUE TITLE
Bug : page CC il manque des contributions 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2341]
Dans la page CC, il manque des contributions alors que ces dernières sont bien présentes dans la contribution générique sur le site. 
Cela n'a pas l'air d'être un problème de données mais plutôt d'affichage dans la page CC. 

Exemple : IDCC 176 --> contribution sur la durée maximale de la période d'essai

- page CC : la contribution n'y es pas --> https://5e88a33-code-travail.dev.fabrique.social.gouv.fr/convention-collective/176-industrie-pharmaceutique
![image](https://user-images.githubusercontent.com/48682104/73930435-c85d9980-48d6-11ea-93b4-99fe4f16af9d.png)

- page de la contribution "durée maximale de la période d'essai, la contribution est bien là --> https://5e88a33-code-travail.dev.fabrique.social.gouv.fr/contribution/quelle-est-la-duree-maximale-de-la-periode-dessai-sans-et-avec-renouvellement?q=Quelle%20est%20la%20dur%C3%A9e%20maximale%20de%20la%20p%C3%A9riode%20d%27essai,%20sans%20et%20avec%20renouvellement%20?
![image](https://user-images.githubusercontent.com/48682104/73930533-f04cfd00-48d6-11ea-9f68-218ff9c15250.png)

**Comment by revolunet** [comment]
Analyse en cours

 - les contributions sont bien récupérées via dataset/contributions
 - Or c'est le script de récup des données du datafiller qui crée l'index des conventions utilisé dans la page CC

devrait être dispo dans quelques minutes ici : 

https://5e88a33-code-travail.dev.fabrique.social.gouv.fr/convention-collective/176-industrie-pharmaceutique

**Comment by revolunet** [comment]
Ça apparait bien maintenant

Donc actuellement pour que la contribution apparaisse dans la page de la CC il faut aussi mettre a jour les données issues du datafiller

**Comment by revolunet** [comment]
NB : ce serait peut-être plus cohérent de générer ce fichier `agreements.data.json` depuis `dataset/contributions` plutôt que `dataset/datafiller`

**Comment by virginielastisneres** [comment]
@revolunet du coup julien, cette issue est terminée ?

**Comment by revolunet** [comment]
oui pour moi c'est réglé
