### ISSUE TITLE
Résultat : lisibilité articles code du travail

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#235]
dans les résultats, en tant qu'user quand je rencontre un contenu article de code du travail, je dois pouvoir savaoir qu'il s'agit d'un article du code du travail:
![image](https://user-images.githubusercontent.com/37538697/47643933-1da3ea80-db6d-11e8-9be2-a1d3735544e9.png)
![image](https://user-images.githubusercontent.com/37538697/47643957-33191480-db6d-11e8-8aa9-083727301629.png)

**Ajouter " du code du travail"**
- [x] aux articles dans les résultats suggérés,
- [x] aux articles dans la page résultats proposées
- [x] à l'article affiché en page résultat

**Prévoir de décliner l'idée sur d'autres source à venir**
- [ ] Ajouter Convention collective de l'édition sur les propositions IDCC 2121. 
- [ ] Lors de l'integration d'une nouvelle CCN, d'un nouveau code ( rural, transport), l'intitulé doit figurer comme précité

**Comment by revolunet** [comment]
pour les CCNS, à traiter dans une issue dédiée :)
