### ISSUE TITLE
modification/refonte design de la page résultat modèles de courrier

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#236]
- [ ] modifs design https://trello.com/c/POKc0yVJ/313-mod%C3%A8les-de-courrier
- [ ] dans themes2.csv pouvoir lier
- [ ] dans la page des thèmes, ajouter des liens vers les modèles en question

- [ ] Afficher les modèles en complément de réponses rédigées en français facile
- [ ] Afficher les modèles en réponses que si la requête contient "modèle" & "lettre"

**Comment by revolunet** [comment]
![reponse_-_modele_de_courrier](https://user-images.githubusercontent.com/124937/48031454-9b12c080-e154-11e8-95c2-541969ad2a12.png)

**Comment by lionelB** [comment]
@jeremiecook j'ai l'impression qu'il manque une couleur dans celle définie dans CSS, par exemple le "gris" de DOCX dans le bouton télécharger ou bien le "mis à jour" en dessous du titre.
J'ai rajouté cette couleur dit moi si il faut changer
```
  --color-grey: #9ba3ac;
```
