### ISSUE TITLE
Moteur de recherche: recherche par référence juridique, résultats erronés

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#2361]
### Description:

Un user nous fait part par mail d'une recherche décevante.
Elle tape " L1321-4", qui correspond à un article du code du travail sur le règlement intérieur. ( le bon article s'affiche correctement de son côté en bas de page d'ailleurs plutôt bien accompagné d'autres articles sur le même thème).

La majorité des réponses proposées (fiches...) ont trait au licenciement, aucune au règlement intérieur.
https://code.travail.gouv.fr/recherche?q=L1321-4

### Solution:
Dans le sillage des travaux sur la veille, intégrer une table de correspondance entre fiches, thèmes et références juridiques pour améliorer ces recherches. ( si une fiche MT porte sur le règlement intérieur, elle intégrera la référence à l'article L1321-4).

//nb:  je n'ai pas vérifié le nombre de requêtes d'articles du code du travail effectuées aujourd'hui sur le site...

**Comment by rmelisson** [comment]
À noter que l'article est bien présent dans la section, "que dit le code du travail"
Finalement, il s'agit surtout de detecter ce scenario et d'adapter les résultats de recherche en fonction, car ce n'est pas à proprement parler une requête par "mot clé"

**Comment by rmelisson** [comment]
par exemple, on pourrait utiliser la recherche "related item" en partant du text dudit article

**Comment by carolineBda** [comment]
J'ai l'impression que ce cas est géré maintenant : https://code.travail.gouv.fr/recherche?q=L1321-4
@romain-b13 c'est le bon résultat non ?

**Comment by m-maillot** [comment]
Difficile à dire car il n'y a plus de résultat sur cet article, régression ?

**Comment by jrduscher** [comment]
[Lien](https://code.travail.gouv.fr/recherche?q=reglement+int%C3%A9rieur)
