### ISSUE TITLE
[veille] Récupérer les références juridiques associées aux fiches du Ministère du travail

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2365]
Aujourd'hui nous récupérons les références juridiques des fiches SP mais pas celles des fiches MT. 
exemple : https://travail-emploi.gouv.fr/dialogue-social/le-comite-social-et-economique/article/cse-definition-cadre-et-calendrier-de-mise-en-place
![image](https://user-images.githubusercontent.com/48682104/74645811-e5b52200-5178-11ea-87df-aade182da9cd.png)
Il faudrait pouvoir récupérer les références juridiques des fiches MT voir ce que l'on peut récupérer et ensuite décider de ce que l'on affichera.

**Comment by revolunet** [comment]
a reconfirmer mais de mémoire la dicom nous avait dit qu'il valait mieux se baser sur les articles cités **dans le texte** plutôt que cette colonne

**Comment by rmelisson** [comment]
Par rapport à la discussion que l’on a eu pendant le planning, voici ce que je comprends du problème et la façon dont je l’approcherais :

- Nous avons besoin d’identifier dans le texte (free text) des fiches SP et MT les références aux articles, décrets, ordonnances qui constituent le code du travail.
- Ça ressemble à un excercice d’extraction d’entités (https://en.wikipedia.org/wiki/Named-entity_recognition)
- Pour traiter le problème, on peut soit construire un algorithme d’extraction à la main (un mix entre regex, règles autour des tokens, utilisation de modèles NLP standards) : option A.  Où alors on peut créer notre propre modèle d’extraction de références : option B
- Dans tous les cas, il nous faudra commencer par constituter un dataset annoté (d’abord petit pour l’option A, plus conséquent pour l’option B). On peut utiliser un outil dans le genre : https://github.com/doccano/doccano
- L’entrainement d’un modèle est aussi jouable, mais étant donné le formatage assez standard des références, ce n’est pas forcément nécessaire.
- Finalement, ce qui peut aussi être intéressant dans ce travail, c’est de publier notre algo/modèle, car j’imagine qu’il pourrait être utilisable par d’autres équipes (à la Fabrique, ou ailleurs)

**Comment by revolunet** [comment]
je repose là au cas où un petit travail fait à l'époque en se basant sur les données LEGI :

https://github.com/SocialGouv/legi-detect

1) detection de quelques patterns de base
2) validation (avec base LEGI) et creation du lien vers legifrance

ca pourrait être utilisé via une API dédiée

**Comment by lionelB** [comment]
https://excalidraw.com/#json=5648039146422272,KWd71jChaOeSVl5V-TVKMg

**Comment by virginielastisneres** [comment]
**Pour les références juridiques que l'on souhaiterait ça serait bien d'avoir à la fois celles présentes dans le contenu juridique et celles qui sont sur le côté de la fiche.** 
Il n'y a pas toujours toutes les références juridiques dans le contenu et vice versa.

**Comment by rmelisson** [comment]
@lionelB on avait convenu d'ajouter les refs directement dans les fichiers data json, est-ce que je stocke ça au niveau section dans le `fiches-mt-split.json` ou alors au niveau fiche dans le `fiches-mt.json` ?

**Comment by lionelB** [comment]
je dirais `fiches-mt-split.json` car c'est ce qui est utilisé pour l'index de recherche

**Comment by virginielastisneres** [comment]
@rmelisson Est ce que tu pourrais nous faire un point sur cette tâche :) 
Où en es-tu et que reste-t-il à faire ?
Thanks :)

**Comment by UnbearableBear** [comment]
Juste en passant je crois quand dans les fiches MT lorsqu'il y a des références aux articles du code du travail il s'agit tout le temps de liens qui pointent vers légifrance avec une url facilement identifiable. Il y a des fois ou ce sont des plages d'articles alors que le lien point uniquement sur le premier mais c'est le seul cas un peu tordu que je vois

**Comment by rmelisson** [comment]
J'avais loupé ton commentaire @virginielastisneres, en gros pour le moment on a un algo qui trouve les "tokens" qui font reference à des articles.
Maintenant, faut que je refasse le point avec @lionelB pour savoir si je vais jusqu'à la resolution des "liens" Legifrance

**Comment by rmelisson** [comment]
résumé du call avec Lionel :
- utiliser legi-data et unist pour le mapping ref -> id DILA
- gestion des "plages" dans une autre issue "L. 613-19 à L.613-19-2"
- enlever url
- documentation haut niveau de l'algo

commentaire Virginie : 
- essayer de conserver les ref des plages

**Comment by lionelB** [comment]
@rmelisson  pou les plages est ce que c'est possible de mettre la premiere reférence 
ex: L. 613-19 à L.613-19-2 => { ref: "L613-19", id: "", ...}

**Comment by rmelisson** [comment]
yep, même les deux : 
https://github.com/SocialGouv/code-du-travail-numerique/pull/2408/files#diff-4293ca9dc391217ec2b0c7e134c8f6e9R23
  ||
  ||
  V
https://github.com/SocialGouv/code-du-travail-numerique/pull/2408/files#diff-1e93b4ab62074c753769989aeae557c5R325-R364

**Comment by virginielastisneres** [comment]
Hello @rmelisson :) 
Peux-tu me dire où tu en es de cette tâche notamment concernant les plages et les liens Legifrance ? 
Merci :)

**Comment by rmelisson** [comment]
hello @virginielastisneres 
c'est en court de review, les liens sont ok, les plages seront traitées dans une autre issue

**Comment by virginielastisneres** [comment]
> hello @virginielastisneres
> c'est en court de review, les liens sont ok, les plages seront traitées dans une autre issue

Super merci @rmelisson :)
