### ISSUE TITLE
Bug tuiles des contributions dans page résultat

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2366]
Dans la page résultat, pour les contributions apparaît le mot "contributions". 
Or, normalement devrait apparaître le thème de la contribution comme pour les fiches SP et MT. 
![image](https://user-images.githubusercontent.com/48682104/74648810-aa1d5680-517e-11ea-9b4c-7b2f56f548d5.png)

Il faut donc remplacer le mot contributions par le thème de la contribution.

**Comment by lionelB** [comment]
ca fait pas deja la 3e issue la dessus ?

**Comment by lionelB** [comment]
fausse manip, et apriori pas de doublons... je vais aller me coucher je crois :)

**Comment by lionelB** [comment]
a priori le pb vient du fait que certaine contribution ne sont pas encore dans le datafiller, ou ne sont pas thémée (https://code.travail.gouv.fr/recherche?q=interim%20%20fin%20de%20contrat)

**Comment by virginielastisneres** [comment]
@lionelB j'ai un souci, le bug est revenu => https://code.travail.gouv.fr/recherche?q=dur%C3%A9e%20cong%C3%A9%20maternit%C3%A9
![image](https://user-images.githubusercontent.com/48682104/80701782-384b7c80-8ae0-11ea-9730-40fe4caaa94e.png)
Pourtant il n'y a pas de contribution à thémer dans le datafiller. Cela serait-il dû au travail sur les données effecuté ?

**Comment by lionelB** [comment]
je ferme le pb a été réglé avec l'outils d'admin
