### ISSUE TITLE
Balise Meta title & Meta Description : Home page 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2373]
### Meta title

Le titre de la home page dans les résultats de recherche est "code du travail numérique". 

Etant donné qu'on n'est pas explicite dans la meta description, cela serait bien de rajouter dans le Meta title "Ministère du travail" à côté de code du travail numérique. Cela permet d'afficher directement que le site est un site du ministère du travail, cela donne plus de confiance à l'utilisateur.  

Pour exemple : le 2nd résultat qui est le site travail-emploi.gouv.fr

![image](https://user-images.githubusercontent.com/48682104/74748420-c269a000-5268-11ea-8998-687bb5bac549.png)

### Meta Description

Voici la méta description d'aujourd'hui : "Posez votre question sur le droit du travail et obtenez une réponse personnalisée à vos questions (formation, rupture de contrat, démission, indemnités)."

Elle est très bien et claire juste, je changerai les exemples surtout "rupture de contrat" qui est pas top comme image et j'optimiserai les exemples avec les thèmes les plus cherchés par les usagers. 

Proposition : 
"Posez votre question sur le droit du travail et obtenez une réponse personnalisée à vos questions (contrat de travail, congés payés, formation, démission, indemnités)."

**Comment by lionelB** [comment]
je trouve que ca risque d'induire en erreur l'utilisateur qui va penser que c'est un contenu du site ministere du travail alors que pas du tout.

**Comment by virginielastisneres** [comment]
> je trouve que ca risque d'induire en erreur l'utilisateur qui va penser que c'est un contenu du site ministere du travail alors que pas du tout.

Je comprends ce que tu veux dire après je ne suis pas sure que ca ait cet effet. A l'inverse ne rien mettre alors qu'en dessous tu as ministère du travail ca inspire moins confiance je trouve, j'ai plutôt envie de cliquer sur le second lien car je veux des informations en droit du travail données par le ministère du travail. Je suis pas sure qu'en voyant Ministère du travail les gens pensent directement au site du ministère du travail.

**Comment by UnbearableBear** [comment]
Por info les titre à l'heure actuelle ressemblent à ça:

Code du travail numérique - Ministère du Travail
Recherche de convention collective
Convention collective ${titre court cc}
${recherche} - Code du travail numérique
Glossaire - Code du travail numérique
Le droit du travail - Code du travail numérique
Boîte a outils - Code du travail numérique
Politique de confidentialité - Code du travail numérique
À propos - Code du travail numérique
Thèmes - Code du travail numérique
Statistiques du Code du travail numérique
${titre outil}
${tite theme} - Code du travail numérique
${titre fiche sp}
${titre contribution}
Modèle de document : ${titre modele}
${titre modele de courrier} - Code du travail numérique
${titre fiche mt}
${titre article code du travail}
