### ISSUE TITLE
[Veille] Général : changements articles du cdt et CCs VS contenus impactés

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2389]
### **Contexte & Problème**
Aujourd'hui, il y a aucun mécanisme qui alerte les experts métiers des changements intervenus sur les articles du code du travail et les articles des conventions collectives. Ils ne peuvent donc pas faire de veille sur nos contenus.  Cela vaut également pour les fiches Service-Public.fr, les experts ne sont pas alertés lors d'une modification, d'une suppression ou d'un ajout d'une fiche. 

Or, nous avons aujourd'hui grâce à l'API Dila (Api Légi & Api Kali) connaissance quotidiennement de ces changements mais aucun rapport n'est fait aux experts.
Nous avons également connaissance des changements intervenus sur les fiches SP sans remontée vers les experts. 

### **Solution**
Il faudrait sortir tous les jours peut être dans un premier temps (on adaptera le rythme en fonction de l'utilité), un rapport à destination des experts métiers qui comprend : 

- [ ] la liste des articles du cdt qui ont été modifiés, supprimés, ajoutés (les diffs) ;
- [ ] la liste des articles des CCs qui ont été modifiés, supprimés, ajoutés (les diffs) ; 
Pour les CCs on se limite à 52 CCs =>> liste ici https://docs.google.com/document/d/1l3AL3HaQPT_-iqsIiJWVCJbGvF6z0o48WKDlGsN4GzM/edit
- [ ] la liste des fiches Service-Public.fr qui ont été modifiés, supprimés, ajoutés. 

Afin d'aider un peu plus les experts, il faudrait en parallèle des changements, sortir une liste des références juridiques des contenus suivants : 
- [ ] les contributions
- [ ] les outils 
- [x] les fiches SP 
- [ ] les fiches MT  #2365

Cf. #2399 

Idéalement, cela serait bien de faire un lien entre les deux fichiers. Dans le rapport des changements intervenus indiquer les contenus impactés par ces changements. 

![image](https://user-images.githubusercontent.com/48682104/74923421-0d9ec280-53d1-11ea-98b6-c7cdb36906ae.png)

**Comment by lionelB** [comment]
Hello
Pour les 3 premiers points vous pouvez deja vous abonnez aux dépots
- https://github.com/SocialGouv/kali-data ( texte de base des conventions collectives )
- https://github.com/SocialGouv/legi-data (code du travail)
- https://github.com/SocialGouv/fiche-vdd (fiche service publics)

pour avoir un rapport de tout les changements,

**Comment by UnbearableBear** [comment]
Et ce qui concerne les fiche du ministère du travail, il n'y a pas besoin d'avoir an rapport sur celles qui ont été modifiée / supprimées / ajoutées ?

**Comment by virginielastisneres** [comment]
normalement c'est la dicom qui doit nous prévenir de ces changements.

**Comment by revolunet** [comment]
un exemple de ce qu'on peut extraire a chaque modif côté DILA : https://hackmd.io/KKdxD-wFRvq_Eao9kJGFSg?view

**Comment by revolunet** [comment]
c'est un "diff" entre deux versions du code

**Comment by revolunet** [comment]
cf https://github.com/SocialGouv/legi-data/pull/40

**Comment by revolunet** [comment]
Une démo un peu plus à jour de ce qu'on peut extraire avec les repos LEGI/KALI  : https://gs7sz.csb.app/

**Comment by revolunet** [comment]
resterait à faire sur cette demo :
 - faire les liens vers legifrance
 - filter uniquement sur les cc qui nous intéressent
 - ajouter le diff fiches SP

**Comment by revolunet** [comment]
MAJ avec les contenus fiches-SP : https://review-tests-dev-cejapu-veille-git.dev.fabrique.social.gouv.fr/

Reste à faire : 
 - filtrer les CCs sur celles qui nous interessent
 - idem fiche SP
 - pouvoir remonter plus en arrière

**Comment by lionelB** [comment]
moved to https://github.com/SocialGouv/cdtn-admin/issues/23
