### ISSUE TITLE
[bug/spec] indemnité légale de licenciement ancienneté<12 mois et>8 mois après le 25/09/2017

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#239]
c)**vérifier**: si ancienneté>12 mois. et _**si date du licenciement avant le 25/09/2017**_
     si oui: continuer
     si non: afficher principe. "l'indemnité de licenciement est due au delà d'un an d'ancienneté"
** vérifier**: si ancienneté>8 mois. et _**si date du licenciement après le 25/09/2017**_
     si oui: continuer
     si non: afficher principe. "l'indemnité de licenciement est due au delà d'un an d'ancienneté"

 3) Recueillir  salaire brut mensuel**
 lorsque la durée de service du salarié est inférieure à douze mois, la moyenne mensuelle de la rémunération de l'ensemble des mois précédant le licenciement ;
si le nb de mois de slaires saisies >8 et <12; moyenne des salaires 

comparer avec la moyenne des 3 derniers mois

calcul année incomplète: si IL <8 mois: " En cas d'année incomplète, l'indemnité est calculée proportionnellement au nombre de mois complets."

#### "calcul2017" : date du licenciement > 26/09/2017
c= nb de mois/10 ( lorsque ancienneté <12 mois et >8 mois)

Si "ancienneté inférieure  ou égale à 10 ans
`indemnite=1/4*c*10`

Si ancienneté supérieur  à 10 ans: (// en mois par années d'ancienneté)
(d)=ancienneté-10
`indemnite=1/4 *c*10 + 1/3*c*d`

**Comment by jrduscher** [comment]
Mémo:
- [ ] refaire une passe en complétude et vérification indemnité **légale** de licenciement
- [ ] produire des tests unitaires 
- [ ] faire tester l'outil sdr

Suivre le même schéa pour les scenarios indus chim

**Comment by lionelB** [comment]
closed by #259
