### ISSUE TITLE
Résultats des requêtes Datafiller : ajouter une option qui permet de réordonnancer plus facilement 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2391]
**Contexte**
Aujourd'hui dans les requêtes du datafiller, si je veux modifier l'ordre dans lequel les résultats d'une requête apparaît je dois supprimer les résultats et les remettre tous dans l'ordre souhaité. 
![image](https://user-images.githubusercontent.com/48682104/74950368-46ee2700-53ff-11ea-8bbf-ca45da454630.png)
Changer l'ordre des résultats de 100 requêtes va prendre du temps.  

**Solution**
Il faudrait rajouter la même option qui existe dans les thèmes. 
Dans les thèmes du datafiller j'ai une option de déplacer les résultats sans avoir à les supprimer et les remettre dans le bon ordre ensuite. 
cf; ![image](https://user-images.githubusercontent.com/48682104/74950720-ced43100-53ff-11ea-847c-293ffff417eb.png)

**Comment by revolunet** [comment]
@rmelisson @ArmandGiraud @lionelB 

Ici on voudrait remplacer, dans les "requetes" du datafiller la "note" de 1 à 5 par un "order", comme c'est le cas dans les thèmes. du coup ca va remplace lesr "scores" des entrées actuelles avec un nombre de 1 à n selon leur ordre visuel et non plus la "note".

aussi, sauf erreur, actuellement, SCORE=5 très pertinent alors SCORE=1 = pas terrible
Avec l'ordering on inverse le sens.

Est-ce qu'il y a un impact de votre côté si on fait cette modif ?

**Comment by revolunet** [comment]
Sinon pour faire la modif côté DF concrètement il faudrait :

 - corriger l'UI pour gérer l'ordering manuel et supprimer la note
 - faire un script qui corrige tous les scores actuels
 - dans CDTN, modifier [l'import du datafiller](https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-data/dataset/datafiller/fetch-requetes.js#L83) pour gérer ce nouvel ordering "naturel"

**Comment by virginielastisneres** [comment]
@revolunet à voir avec ce que disent rémi, armand et lionel. Rémi me disait qu'il utilisait pas le scoring apparemment...

**Comment by rmelisson** [comment]
J'avais cru comprendre qu'on utilisait l'ordre tel quel, pas forcément en fonction de scores. Je regarde de plus près demain.

**Comment by ArmandGiraud** [comment]
Ce score de pertinence permet l'évaluation (à froid) de l'algorithme de recherche, par rapport à l'avis de nos experts. Est-il possible de rajouter un rang à côté  de la note de pertinence? @revolunet

**Comment by rmelisson** [comment]
Après discussion avec Virginie, on pense que le plus simple serait de rajouter plus d'options de scoring (de 1 à 10 par exemple). Ça devrait nous permettre d'ordonner les résultats comme on le souhaite, avec un minimum de dev.

Est-ce que ça serait possible comme feature niveau data filler ?

**Comment by revolunet** [comment]
on peut passer le scoring de 1 à 10 ou mettre un ordre, les deux sont aussi simples. l'ordre est déjà géré dans les thèmes donc c'est facile à mettre en place.

**Comment by rmelisson** [comment]
Ok, je pense que le scoring 1-10 est mieux car au moins c'est explicite. 
Après ça peut être utile d'avoir l'ordre en terme d'UX.

**Comment by revolunet** [comment]
je pense que si on rajoute un scoring mais que c'est pas orderable c'est illisible donc je propose de faire l'ordering avec une notre de 1 à n qui représente la position. ca irait ?

**Comment by revolunet** [comment]
conclusion : 
 - [ ] mettre l'ordering des résultats dans les requêtes comme dans les thèmes
 - [ ] remapper les scores de la DB de 5 à 1 vers 1 à n

**Comment by revolunet** [comment]
@virginielastisneres 

La modif est en cours, j'ai une petite question pour la reprise des scores actuels.

dans une requete DF, lorsque plusieurs liens ont le même "score" (ex:5), on les ordonne par défaut par "source", avec ces priorités : 

- outils
- contribution
- modeles-de-courriers
- fiche-service-public
- fiche-ministere-travail
- code-du-travail
- external

C'est bon pour toi ?

**Comment by virginielastisneres** [comment]
> @virginielastisneres
> 
> La modif est en cours, j'ai une petite question pour la reprise des scores actuels.
> 
> dans une requete DF, lorsque plusieurs liens ont le même "score" (ex:5), on les ordonne par défaut par "source", avec ces priorités :
> 
> * outils
> * contribution
> * modeles-de-courriers
> * fiche-service-public
> * fiche-ministere-travail
> * code-du-travail
> * external
> 
> C'est bon pour toi ?

oui :) @revolunet

**Comment by revolunet** [comment]
Voici un exemple de comment cela va modifier les scores :

<img width="1885" alt="Capture d’écran 2020-03-04 à 16 20 08" src="https://user-images.githubusercontent.com/124937/75894729-f500c480-5e34-11ea-8270-ce21729fa5bc.png">

col relevance = score actuel
col position = position corrigée

**Comment by virginielastisneres** [comment]
> Voici un exemple de comment cela va modifier les scores :
> 
> <img alt="Capture d’écran 2020-03-04 à 16 20 08" width="1885" src="https://user-images.githubusercontent.com/124937/75894729-f500c480-5e34-11ea-8270-ce21729fa5bc.png">
> 
> col relevance = score actuel
> col position = position corrigée

Pour moi cela semble bon julien :) et pour toi @rmelisson ?

**Comment by rmelisson** [comment]
looks good, et du coup dans l'export on aura relevance et position ?

**Comment by revolunet** [comment]
je comptais enlever relevance vu qu'il ne sera plus modifiable... good for you ?

**Comment by rmelisson** [comment]
yep 👍

**Comment by revolunet** [comment]
fixed in https://github.com/SocialGouv/datafiller/pull/102
