### ISSUE TITLE
Proposer à l'utilisateur de joindre les services de renseignement à tout moment

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#242]
afficher un module d'orientation vers les services de renseignement quand la session de navigation dure longtemps
"Je cherche plusieurs contenus, je ne trouve pas et , on m'oriente vers un service de renseignement"

**Comment by revolunet** [comment]
bonne idée !

 - "dure longtemps" : définir la durée svp

**Comment by jrduscher** [comment]
1. > Mise à jour des données SR 
2. > numéro unique ( exemple) doc officielle le 5/04
3. http://grand-est.direccte.gouv.fr/sites/grand-est.direccte.gouv.fr/local/cache-vignettes/L180xH150/banniereanimeedroitdutravail-1ec92.gif
4. > coordonnées des SR en local ( si liste via DGT)
5. > réintegrer l'orientation vers les SR en bas d epage résultats

**Comment by ClementChapalain** [comment]
to do :
- footer avec le module "besoin d'un accompagnement personnel" présent sur tout le site
- ajoute le numéro unique
- ajoute une phrase d'explication sur ce que sont les SRs

**Comment by jrduscher** [comment]
Précisions de la tâche suite à rdv DGT:

**to do :**

footer avec le module "besoin d'un accompagnement personnel" présent sur tout le site et principalement en bas de page résultat.

ajouter le numéro unique 
logo/vignette.
ajoute une phrase d'explication sur ce que sont les SR:

titre: **Services de renseignement juridique des DI(R)ECCTE**
explicatif à ajouter:" les services de renseignement donnent des informations juridiques générales relatives au code du travail, aux conventions collectives, à la jurisprudence.
Ces informations concernent l’ensemble des secteurs d'activité, les statuts spécifiques et portent notamment sur le contrat de travail, le salarie, le règlement intérieur, le droit disciplinaire, la durée du travail, le congés payés et repos, et la médecine travail.

Ces services délivrent une information juridique, il ne sont pas compétents pour :
- les demandes d'intervention en entreprise (section d'inspection du travail)
- le règlement des litiges, et la constitution des dossiers prud'homaux
- les calculs de droits a au chômage 
- vous rensiegner sur les cotisations sociales ( lien vers le simulateur d'embauche)"
Ajouter le gif animé ou le logo du numéro unique.

Ajouter les coorodnnées des SR:
wording:"Ecrire ou vous rendre dans les services  : trouver mon service de renseignement: ( utilisation de l'applicatif existant) ( passe de vérid

[BanniereanimeeDroitDuTravail.zip](https://github.com/SocialGouv/code-du-travail-numerique/files/3047913/BanniereanimeeDroitDuTravail.zip)


a

**Comment by jrduscher** [comment]
**la liste des coordonnées des SR** 

proposer à l'usager via un champ de retrouver les modalités de contact physque, mail, siaie en ligne que propose son service de rens.
Il existe une modal, qui répond à ces fonctionnlités. elle doit être améliorée.
1) Màj des URL

 https://www.clicrdv.com/direccte-bourgogne-franche-comte pour les dep 21,25,39, 58,70, 71, 89,90

http://normandie.direccte.gouv.fr/L-aide-a-l-acces-au-droit : dép: 14,27, 50, 61, 76

22: http://bretagne.direccte.gouv.fr/Le-Service-Renseignement-du-Public-2949
29: http://bretagne.direccte.gouv.fr/Renseignements-droit-du-travail
35: http://bretagne.direccte.gouv.fr/Renseignements-au-public
56: http://bretagne.direccte.gouv.fr/Renseignement-au-public-3009

75,76, 77,78,91,92,93,94,95 : http://idf.direccte.gouv.fr/Inspection-du-travail

2) améliorer la lisibilité en ajoutant une possibilité de recherche au delà du numéro de département:: 
01 - Ain - Bourg-en-bresse
02 - Aisne - Laon
03 - Allier - Moulins
04 - Alpes-de-Haute-Provence - Digne-les-bains
05 - Hautes-alpes - Gap
06 - Alpes-maritimes - Nice
07 - Ardèche - Privas
08 - Ardennes - Charleville-mézières
09 - Ariège - Foix
10 - Aube - Troyes
11 - Aude - Carcassonne
12 - Aveyron - Rodez
13 - Bouches-du-Rhône - Marseille
14 - Calvados - Caen
15 - Cantal - Aurillac
16 - Charente - Angoulême
17 - Charente-maritime - La rochelle
18 - Cher - Bourges
19 - Corrèze - Tulle
2a - Corse-du-sud - Ajaccio
2b - Haute-Corse - Bastia
21 - Côte-d'Or - Dijon
22 - Côtes-d'Armor - Saint-brieuc
23 - Creuse - Guéret
24 - Dordogne - Périgueux
25 - Doubs - Besançon
26 - Drôme - Valence
27 - Eure - Évreux
28 - Eure-et-loir - Chartres
29 - Finistère - Quimper
30 - Gard - Nîmes
31 - Haute-garonne - Toulouse
32 - Gers - Auch
33 - Gironde - Bordeaux
34 - Hérault - Montpellier
35 - Ille-et-vilaine - Rennes
36 - Indre - Châteauroux
37 - Indre-et-loire - Tours
38 - Isère - Grenoble
39 - Jura - Lons-le-saunier
40 - Landes - Mont-de-marsan
41 - Loir-et-cher - Blois
42 - Loire - Saint-étienne
43 - Haute-loire - Le puy-en-velay
44 - Loire-atlantique - Nantes
45 - Loiret - Orléans
46 - Lot - Cahors
47 - Lot-et-garonne - Agen
48 - Lozère - Mende
49 - Maine-et-loire - Angers
50 - Manche - Saint-lô
51 - Marne - Châlons-en-champagne
52 - Haute-marne - Chaumont
53 - Mayenne - Laval
54 - Meurthe-et-moselle - Nancy
55 - Meuse - Bar-le-duc
56 - Morbihan - Vannes
57 - Moselle - Metz
58 - Nièvre - Nevers
59 - Nord - Lille
60 - Oise - Beauvais
61 - Orne - Alençon
62 - Pas-de-calais - Arras
63 - Puy-de-dôme - Clermont-ferrand
64 - Pyrénées-atlantiques - Pau
65 - Hautes-Pyrénées - Tarbes
66 - Pyrénées-orientales - Perpignan
67 - Bas-rhin - Strasbourg
68 - Haut-rhin - Colmar
69 - Rhône - Lyon
70 - Haute-saône - Vesoul
71 - Saône-et-loire - Mâcon
72 - Sarthe - Le mans
73 - Savoie - Chambéry
74 - Haute-savoie - Annecy
75 - Paris - Paris
76 - Seine-maritime - Rouen
77 - Seine-et-marne - Melun
78 - Yvelines - Versailles
79 - Deux-sèvres - Niort
80 - Somme - Amiens
81 - Tarn - Albi
82 - Tarn-et-garonne - Montauban
83 - Var - Toulon
84 - Vaucluse - Avignon
85 - Vendée - La roche-sur-yon
86 - Vienne - Poitiers
87 - Haute-vienne - Limoges
88 - Vosges - Épinal
89 - Yonne - Auxerre
90 - Territoire de belfort - Belfort
91 - Essonne - Évry
92 - Hauts-de-seine - Nanterre
93 - Seine-Saint-Denis - Bobigny
94 - Val-de-marne - Créteil
95 - Val-d'oise - Pontoise
971 - Guadeloupe - Basse-terre
972 - Martinique - Fort-de-france
973 - Guyane - Cayenne
974 - La réunion - Saint-denis
976 - Mayotte - Dzaoudzi

bonus: suggérer le service sur localisation

**Comment by ClementChapalain** [comment]
Vu avec JR ce matin, on partirait sur revoir le footer avec l'intégration du contact des SR et plus l'annuaire. L'annuaire est important mais on pense que la bonne solution est une intégration contextuelle (i.e. je cherche accident du travail je tombe sur les résultats + le contact de l'agence qui s'occupe de ça). L'idée est aussi que le footer soit le même sur toutes les pages, comme ça l'usager peut avoir le lien vers les SR tout le temps, si jamais le CDTN ne lui offre pas une réponse satisfaisante.

design :
https://www.figma.com/proto/UGkd7UFF3gJSb3a35ClTtPKW/Code-du-travail-num%C3%A9rique?node-id=67%3A0&viewport=1733%2C136%2C0.712359&scaling=min-zoom&redirected=1

image du numéro de téléphone : 
![Sans titre](https://user-images.githubusercontent.com/5337489/55711308-b8da9f00-59ec-11e9-8cc6-cd49718bcd86.png)

**Comment by lionelB** [comment]
je suis un peu triste de supprimer l'annuaire car j'etais content de l'integration de l'api adresse 
mais c'est tout à fait juste :)

**Comment by ClementChapalain** [comment]
oui les tests utilisateurs nous ont pas mal refroidi sur l'usabilité actuelle vu que tous les résultats sont au même niveau, mais très clairement je pense qu'on le reprendra dans les prochaines semaines avec un parcours du style :
1 - je cherche une information
2 - on me donne une information en français facile
3 - si pertinent, on me propose de de parler avec qqun
4 - on me demande mon adresse (ou autre, selon le discriminant pertinent)
5 - je peux contacter le bon service

**Comment by ClementChapalain** [comment]
to do :
- mettre le footer de la page d'accueil sur toutes les pages
- enlever la feature annuaire et mettre modale qui donne le contact des SR :
https://www.figma.com/proto/UGkd7UFF3gJSb3a35ClTtPKW/Code-du-travail-num%C3%A9rique?node-id=67%3A0&viewport=1733%2C136%2C0.712359&scaling=min-zoom&redirected=1
- modifier la modale dans le formulaire de feedback (ou enlever le lien carrément ?)

**Comment by lionelB** [comment]
en regardant ta marquette je me demande si on ne pourrait pas mettre 
"besoin d'un accompagnement..." + bouton dans la premiere colone du footer ?

**Comment by ClementChapalain** [comment]
Dans la situation actuelle on pourrait le faire mais je me dis qu'on va surement ajouter d'autres trucs dans le footer donc comme ça on se laisse de la marge pour intégrer de nouveaux éléments.

En plus je pense que ça doit être mis plus en avant que le reste du footer.
