### ISSUE TITLE
Ajouter des tests end to end

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2422]
_WIP_

**Contexte**
Aujourd'hui nous avons 5 tests end to end. 

**Solution**
Il faudrait en créer d'autres afin de couvrir au mieux toutes les fonctionnalités du code du travail numérique. 
_(où les trouver & où les créer)_

Liste des tests : 

- Recherche sur le site avec sélection de résultats 
- Parcours outils : outil indemnité de licenciement, outil indemnité de précarité & outil préavis de démission, recherche CC. 
- Parcours modèles
- Parcours contributions

_intégrer la fonctionnalité des articles annexes._

**Comment by lionelB** [comment]
# Parcours
- [x] page d'accueil
- [x] page à propos
- [x] Recherche de convention collective
- [x] Recherche
- [ ]  page de contribution
  - [ ]   `/contribution/quelle-peut-etre-la-duree-maximale-dun-cdd`
  - [ ]   `/contribution/faut-il-respecter-un-delai-de-carence-entre-deux-cdd-si-oui-quelle-est-sa-duree`
- [ ] `page de convention collective`
- [ ]   `/convention-collective/829-convention-collective-departementale-des-industries-metallurgiques-et-des-in`
- [ ]  indemnite de licenciement
- [ ]  modele de courrier
- [x] pages du footer

**Comment by revolunet** [comment]
PI les sources des tests actuels : https://github.com/SocialGouv/code-du-travail-numerique/tree/master/optional/e2e/features

**Comment by virginielastisneres** [comment]
@UnbearableBear pourrais-tu me dire à combien de tests tu es actuellement ?

**Comment by UnbearableBear** [comment]
Je suis sur le 5eme qui teste le calculateur d'indemnité (sachant qui'l y a un autre test qui couvre 6-7 pages), je ne sais pas trop si le chiffre est significatif mais j'avance, quand je peux !

**Comment by virginielastisneres** [comment]
> Je suis sur le 5eme qui teste le calculateur d'indemnité (sachant qui'l y a un autre test qui couvre 6-7 pages), je ne sais pas trop si le chiffre est significatif mais j'avance, quand je peux !

D'acc, j'ai pas mis cette issue au prochain sprint car nous avons déjà fait une première création de tests. Tu pourras finir celui de l'outil de licenciement déjà entamé dans ce sprint. Suite à l'utilisation des tests déjà effectués nous pourrons par la suite faire les autres et surement les améliorer après analyse des premiers tests créés.

**Comment by lionelB** [comment]
peut on fermer ? 
on peut aussi recréer une issue par tests avec ce qui manque si besoin

**Comment by UnbearableBear** [comment]
yes on décidera plus tard de si je prend le temps de rajouter les tests écris par Virginie ici: 
https://docs.google.com/document/d/12N5MAaFRYEmaVYQ7qO-BVGIja0xPOoIV_j0y9btjo-A

Mais ce serait bien de s'y mettre tôt ou tard

**Comment by lionelB** [comment]
la liste des parcours testés est à jour ?

**Comment by virginielastisneres** [comment]
oui on ferme si l'intégration dans le CI a été fait
