### ISSUE TITLE
[Veille] : Prototype 1ère Page pour la veille

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2423]
_WIP_

**Contexte & Problème**
_WIP_

**Solution**
_WIP_

Cf. 
[Présentation outil admin et veille.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/4263022/Presentation.outil.admin.et.veille.pdf)

**Comment by lionelB** [comment]
[Page Mises à jour nouvelles v2.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/4508588/Page.Mises.a.jour.nouvelles.v2.pdf)

**Comment by lionelB** [comment]
replace by https://github.com/SocialGouv/cdtn-admin/issues/23
