### ISSUE TITLE
Cacher le lien "devenez ambassadeur"

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2426]
**Contexte**
Nous avons installé il y a peu un lien dans le footer "devenez ambassadeur". ![image](https://user-images.githubusercontent.com/48682104/75551702-0f9dfc80-5a35-11ea-9964-334dabc5e136.png)

La personne qui clique dessus accède à calendly pour prendre rendre vous avec une personne de l'équipe afin d'obtenir des infos et devenir ambassadeur. 

**Problème**
Or, aujourd'hui nous n'avons plus les ressources au sein de l'équipe pour gérer les ambassadeurs et répondre aux demandes de rendez-vous. 

**Solution**
Donc, dans l'attente d'avoir la capacité de répondre à ces demandes, il est opportun de cacher ou d'enlever le lien du footer afin d'éviter toute frustration de l'usager qui souhaiterait devenir ambassadeur.

**Comment by UnbearableBear** [comment]
closed here: https://github.com/SocialGouv/code-du-travail-numerique/pull/2431
