### ISSUE TITLE
[Home page] : les contenus les plus consultés

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2427]
### **Contexte**
Au moment de la construction des fonctionnalités du site Aurélie et Cécile avaient proposé d'intégrer dans la home page la fonctionnalité suivante : une liste des contenus les plus consultés. 

Maintenant que nous avons des données sur les contenus et que la home est le 2ème type de page d'entrée aujourd'hui sur le CDTN, cela serait bien d'intégrer cette fonctionnalité. 

### **Solution**
**Ajouter une section avec les contenus les plus consultés sur le site.** 

**1. Data** : 
Quel contenu ? 
Les contenus consultés regroupent les fiches SP, MT et les contributions. Cela permettrait de pouvoir mettre en avant notamment des contributions. 
Pour rappel, les outils et les modèles sont déjà présentés dans la home page. 
Comment sélectionner le contenu ? 
Pour la sélection du contenu, on pourrait se baser sur les données matomo ? à voir exactement quelle donnée prendre @rmelisson @ArmandGiraud 

**2. UX/UI** : 
- Il faut ajouter une section après les outils et les thèmes. 
- afficher 6 contenus 
- pour l'UI, reprendre les briques des contenus dans la page résultat
cf. https://www.figma.com/file/oph7JpLS74NJAiGbzyit95/CDTN-UI-BlueFinal
![0-CDTN-HP-BlueFinal (1)](https://user-images.githubusercontent.com/48682104/75553200-314cb300-5a38-11ea-85df-e49c2c12e9c1.jpg)

**Comment by ArmandGiraud** [comment]
Pour les contenus les plus visités, on parle d'une liste statique calculée sur tout l'historique?

* on peut imaginer une fonctionnalité un peu dynamique, qui propose les contenus les plus visités sur une fenêtre temporelle définie ou choisi par l'utilisateur. 
* La déviation par rapport à la popularité de long terme permettrait de proposer des résultats en lien avec l'actualité. les fiches canicules remonteraient pendant une canicule par exemple.

@rmelisson tu as d'autres idées?

**Comment by rmelisson** [comment]
- oui je pense que c'est important de calculer la popularité sur une fenêtre de temps, histoire de capturer les tendances
- par contre il vaut mieux imaginer une selection manuelle (via une analyse des logs) pour le moment, car autrement, cela implique la mise en place du pool de logs, et ça risque de prendre un peu plus de temps car gros impact sur l'architecture

**Comment by virginielastisneres** [comment]
> * oui je pense que c'est important de calculer la popularité sur une fenêtre de temps, histoire de capturer les tendances
> * par contre il vaut mieux imaginer une selection manuelle (via une analyse des logs) pour le moment, car autrement, cela implique la mise en place du pool de logs, et ça risque de prendre un peu plus de temps car gros impact sur l'architecture

On est d'accord sur un départ via une sélection manuelle du contenu mis en avant. Comme dit précédemment cela serait bien que cela soit un mix des tendances et des contenus les plus consultés. 

Pour une sélection manuelle du contenu, serait-il possible @revolunet de partir sur le modèle du datafiller ? Avoir un onglet de plus dans le datafiller qui permettrait de sélectionner 6 contenus qui seraient ceux afficher dans la home page au même titre que les thèmes.

**Comment by UnbearableBear** [comment]
Je tente une première approche un peu "naïve" basée sur les stats de matomo (je prends les contenus les plus consultés sur la dernière semaine), on voit ce que ça donne et on implémente la suite ?

**Comment by virginielastisneres** [comment]
> Je tente une première approche un peu "naïve" basée sur les stats de matomo (je prends les contenus les plus consultés sur la dernière semaine), on voit ce que ça donne et on implémente la suite ?

Manu pourrais-tu voir avec @revolunet la mise en place dans le datafiller ? car au final on va vraiment faire une sélection manuelle.

**Comment by revolunet** [comment]
@virginielastisneres tu peux déjà créer une entrée "homepage" dans les requetes et y mettre les liens qui t'interessent ?

**Comment by virginielastisneres** [comment]
> @virginielastisneres tu peux déjà créer une entrée "homepage" dans les requetes et y mettre les liens qui t'interessent ?

yes julien :) 

On est d'accord que l'on mettra "cette requête" dans une section distincte des requêtes @revolunet ? Car là si la personne tape homepage dans notre moteur elle aura les 6 résultats proposés. 
Cela nécessiterait beaucoup de temps selon toi de faire une section à part ?

**Comment by rmelisson** [comment]
de mon côté, je peux calculer les contenus avec le plus fort taux de progression ("hot topics") :
par exemple :
- un contenu (ou une recherche) qui passe de 10 vues par semaine à 100 vues par semaine => taux de progression de x10
- un contenu qui enregistre 200 visites d'habitude et passe à 250 => taux de progression de x1,25

**Comment by UnbearableBear** [comment]
> de mon côté, je peux calculer les contenus avec le plus fort taux de progression ("hot topics") :
> par exemple :
> 
> * un contenu (ou une recherche) qui passe de 10 vues par semaine à 100 vues par semaine => taux de progression de x10
> * un contenu qui enregistre 200 visites d'habitude et passe à 250 => taux de progression de x1,25

J'aime beaucoup cette notion de popularité basé sur le taux de progression ! De ce que je vois dans matomo je peux assez facilement faire un diff / ratio entre le nombre de consultation d'une semaine à l'autre du coup je peux assez facilement aussi faire un mix entre nombre de vues et taux de progression
Ca permettra d'éviter le faux ami de la nouvelle fiche qui a un taux de progression de 100 alors qu'elle est 100 fois moins consultée qu'une autre

**Comment by UnbearableBear** [comment]
Done !
