### ISSUE TITLE
Gestion des contenus, gestion des abondements

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#244]
Extraire des données, un état des FAQ, dans un tableau reprenant dans l'ordre
-n°epos
-question posée
-réponse
-branche
-_autres tags_
- date
- rédacteur

Dans le cadre des abondements quotidiens par certains agents, l'extraction est nécessaire pour prévenir les doublons, et prévoir une stratégie de déploiement.

Paradise: le tout en *.csv serait topissime !!

**Comment by revolunet** [comment]
faq.json et faq-conventions-collectives.json

**Comment by lionelB** [comment]
on peut fermé ?

**Comment by ClementChapalain** [comment]
up :) on ferme @jrduscher ?

**Comment by lionelB** [comment]
@revolunet je retrouve pas le script ni la PR :(

**Comment by jrduscher** [comment]
c'était un csv .
