### ISSUE TITLE
Améliorer la recherche des coordonnées des SdR

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#2443]
**la liste des coordonnées des SR** 
Aujourd'hui, la recherche des coordonnées des SR se fait par numéro de département comme suit
![image](https://user-images.githubusercontent.com/37538697/75975464-da802700-5ed8-11ea-85a8-576a37cef432.png) 

La recherche aboutit à une url:
![image](https://user-images.githubusercontent.com/37538697/75975577-09969880-5ed9-11ea-8fa9-ba59e7df7f06.png)

###  améliorer la lisibilité en ajoutant une possibilité de recherche au delà du numéro de département:

Proposer la possibilité de saisir le numéro de département qcmme aujourd'hui, l nom du département ou du chef lieu

> 01 - Ain - Bourg-en-bresse
> 02 - Aisne - Laon
> 03 - Allier - Moulins
> 04 - Alpes-de-Haute-Provence - Digne-les-bains
> 05 - Hautes-alpes - Gap
> 06 - Alpes-maritimes - Nice
> 07 - Ardèche - Privas
> 08 - Ardennes - Charleville-mézières
> 09 - Ariège - Foix
> 10 - Aube - Troyes
> 11 - Aude - Carcassonne
> 12 - Aveyron - Rodez
> 13 - Bouches-du-Rhône - Marseille
> 14 - Calvados - Caen
> 15 - Cantal - Aurillac
> 16 - Charente - Angoulême
> 17 - Charente-maritime - La rochelle
> 18 - Cher - Bourges
> 19 - Corrèze - Tulle
> 2a - Corse-du-sud - Ajaccio
> 2b - Haute-Corse - Bastia
> 21 - Côte-d'Or - Dijon
> 22 - Côtes-d'Armor - Saint-brieuc
> 23 - Creuse - Guéret
> 24 - Dordogne - Périgueux
> 25 - Doubs - Besançon
> 26 - Drôme - Valence
> 27 - Eure - Évreux
> 28 - Eure-et-loir - Chartres
> 29 - Finistère - Quimper
> 30 - Gard - Nîmes
> 31 - Haute-garonne - Toulouse
> 32 - Gers - Auch
> 33 - Gironde - Bordeaux
> 34 - Hérault - Montpellier
> 35 - Ille-et-vilaine - Rennes
> 36 - Indre - Châteauroux
> 37 - Indre-et-loire - Tours
> 38 - Isère - Grenoble
> 39 - Jura - Lons-le-saunier
> 40 - Landes - Mont-de-marsan
> 41 - Loir-et-cher - Blois
> 42 - Loire - Saint-étienne
> 43 - Haute-loire - Le puy-en-velay
> 44 - Loire-atlantique - Nantes
> 45 - Loiret - Orléans
> 46 - Lot - Cahors
> 47 - Lot-et-garonne - Agen
> 48 - Lozère - Mende
> 49 - Maine-et-loire - Angers
> 50 - Manche - Saint-lô
> 51 - Marne - Châlons-en-champagne
> 52 - Haute-marne - Chaumont
> 53 - Mayenne - Laval
> 54 - Meurthe-et-moselle - Nancy
> 55 - Meuse - Bar-le-duc
> 56 - Morbihan - Vannes
> 57 - Moselle - Metz
> 58 - Nièvre - Nevers
> 59 - Nord - Lille
> 60 - Oise - Beauvais
> 61 - Orne - Alençon
> 62 - Pas-de-calais - Arras
> 63 - Puy-de-dôme - Clermont-ferrand
> 64 - Pyrénées-atlantiques - Pau
> 65 - Hautes-Pyrénées - Tarbes
> 66 - Pyrénées-orientales - Perpignan
> 67 - Bas-rhin - Strasbourg
> 68 - Haut-rhin - Colmar
> 69 - Rhône - Lyon
> 70 - Haute-saône - Vesoul
> 71 - Saône-et-loire - Mâcon
> 72 - Sarthe - Le mans
> 73 - Savoie - Chambéry
> 74 - Haute-savoie - Annecy
> 75 - Paris - Paris
> 76 - Seine-maritime - Rouen
> 77 - Seine-et-marne - Melun
> 78 - Yvelines - Versailles
> 79 - Deux-sèvres - Niort
> 80 - Somme - Amiens
> 81 - Tarn - Albi
> 82 - Tarn-et-garonne - Montauban
> 83 - Var - Toulon
> 84 - Vaucluse - Avignon
> 85 - Vendée - La roche-sur-yon
> 86 - Vienne - Poitiers
> 87 - Haute-vienne - Limoges
> 88 - Vosges - Épinal
> 89 - Yonne - Auxerre
> 90 - Territoire de belfort - Belfort
> 91 - Essonne - Évry
> 92 - Hauts-de-seine - Nanterre
> 93 - Seine-Saint-Denis - Bobigny
> 94 - Val-de-marne - Créteil
> 95 - Val-d'oise - Pontoise
> 971 - Guadeloupe - Basse-terre
> 972 - Martinique - Fort-de-france
> 973 - Guyane - Cayenne
> 974 - La réunion - Saint-denis
> 976 - Mayotte - Dzaoudzi

### Améliorer l'affichage du résultat
au clic renvoi vers l'url correspondante
affichage à l'usager comme suit:
![image](https://user-images.githubusercontent.com/37538697/75976059-f7692a00-5ed9-11ea-8284-5e54b38bcedd.png)

_Originally posted by @jrduscher in https://github.com/SocialGouv/code-du-travail-numerique/issues/242#issuecomment-480349398_

**Comment by m-maillot** [comment]
A voir l'utilisation faite de cette recherche avant d'améliorer son utilisation.
