### ISSUE TITLE
Image qui déborde

### ISSUE THREAD

**Issue by mquandalle** [SocialGouv/code-du-travail-numerique#2450]
**Description**
Certaines images débordent de leur colonne, par exemple sur la page https://code.travail.gouv.fr/fiche-ministere-travail/oppbtp-deux-outils-digitaux-innovants-dans-laccompagnement-a-la-prevention-des-risques-professionnels-aupres-des-tpe-pme?q=btp#PreventionBTP-en-EnDirect-un-service-d-assistance-en-ligne-pour-obtenir-nbsp
Un `img { max-width: 100% }` sur `TabContent` devrait résoudre le problème.

**Screenshots**
![Capture d’écran - 2020-03-08 à 18 42 43](https://user-images.githubusercontent.com/1730702/76168114-b8063c00-616c-11ea-89b4-9f178094d32b.png)

**Comment by revolunet** [comment]
Merci pour le signalement 👍

**Comment by virginielastisneres** [comment]
Idem dans pour cette page : 
![Screenshot_20200326-152756](https://user-images.githubusercontent.com/48682104/77659255-1f4b2b00-6f78-11ea-8a5d-ec942765387b.png)

La solution peut elle régler le problème pour toutes les images de ce type (j'ai l'impression que c'est que sur les fiches MT) ou devons-nous faire une liste de toutes les fiches MT qui ont ce problème ?

**Comment by mquandalle** [comment]
Non normalement la ligne de CSS de mon message initial permet de résoudre le problème systématiquement.

**Comment by UnbearableBear** [comment]
@mquandalle Merci pour le tips, le correctif a été fait, ça ne devrait plus déborder à la prochaine mise en production (dans la journée) !
