### ISSUE TITLE
Recherche de convention collective par le numéro SIRET:  ne fonctionne plus

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#2458]
**Description**

La recherche de CC applicable via le n° SIRET de l'établissement ne semble plus fonctionner. 
Toutes les tentatives aboutissent à: "Aucun résultat n'a été trouvé". (master et prod)

**Reproduction**

Essais infructueux avec les numéros SIRET suivants:
- 38347481400092, (Airbus)
- 57209392000062, (AXA)
- 55214450301248, (AUTOMOBILES PEUGEOT)
- 42049517800014, (societe air france)
- 55212022200013,(societe generale)

**Comment by revolunet** [comment]
- 38347481400092 : absent du fichier weez actuel
 - 57209392000062 : idcc 2357 : CC non référencée dans kali-data
 - 55214450301248 : absent du weez actuel
 - 42049517800014 : convention 256 : **devrait apparaitre**
 - 55212022200013 : convention 2120 : **devrait apparaitre**

**Comment by revolunet** [comment]
a tester sur master dans quelques minutes
