### ISSUE TITLE
Supprimer le lien "cet article" dans la page introduction de l'outil de licenciement

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2466]
Constat suite à des tests utilisateurs : 

Dans l'étape 1 de l'outil de licenciement, 4/4 des personnes testées ont cliqué directement sur le lien "cet article" ouvrant une nouvelle page. Donc 4/4 sont sortis de l'outil avant même d'avoir cliqué sur commencer. 
Il faut donc supprimer ce lien afin d'augmenter le taux de passage à l'étape 2. 

Image du lien
![image](https://user-images.githubusercontent.com/48682104/76554776-ba330800-6496-11ea-86cd-79cdc49d909e.png)

**Comment by UnbearableBear** [comment]
Tu veux que je mette le lien dans la dernière étape, des résultats ?

**Comment by virginielastisneres** [comment]
> Tu veux que je mette le lien dans la dernière étape, des résultats ?
Oui manu c'est une bonne idée pour le moment :)

**Comment by UnbearableBear** [comment]
https://github.com/SocialGouv/code-du-travail-numerique/pull/2470 closed here
