### ISSUE TITLE
Page CC amélioration du chargement de la page

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2469]
Sur google chrome, quand je sélectionne une convention collective dans l'outil de recherche des CCs, la page CC mets bien plus de 4 secondes à se charger. Sur la version mobile de chrome le chargement est un peu plus long 6-7 secondes.  
Sur Firefox, aucun problème.
Sur IE11, chronomètre à l'appui, 59 secondes pour charge de la page CC...  

Déjà 4-5 secondes de chargement c'est long mais 59 secondes cela devient bloquant car je ne pense pas que l'usager patiente ce temps là quand il ne connaît pas le site. Il faut donc améliorer le chargement de la page pour arriver à un chargement "normal".

**Comment by lionelB** [comment]
peut on faire les mesure avec la navigation privée ?

**Comment by virginielastisneres** [comment]
> peut on faire les mesure avec la navigation privée ?

yes lionel je te fais ca et te dit :)

**Comment by virginielastisneres** [comment]
En navigation privée : 
- google chrome : toujours 4 secondes pour le chargement
- firefox : aucune problème
- IE11 :  impossible pour moi de tester en navigation privée...

**Comment by lionelB** [comment]
On pourrait testé de prébuild les page CC avec les nouvelles méthodes de next pour faire des pags statique ?

**Comment by revolunet** [comment]
On peut essayer, surtout si ca fait le processing du glossaire, car a priori le problème vient de là 

<img width="1339" alt="Capture d’écran 2020-03-19 à 16 27 07" src="https://user-images.githubusercontent.com/124937/77083968-96277780-69fe-11ea-90d8-79c9a6fb4c47.png">

<img width="594" alt="Capture d’écran 2020-03-19 à 16 28 00" src="https://user-images.githubusercontent.com/124937/77083995-a0497600-69fe-11ea-8584-c69327949ec8.png">

**Comment by revolunet** [comment]
(ceci dit on doit pouvoir optim cette fonction)

**Comment by lionelB** [comment]
@nkrmr creuse la piste d'utiliser les webcomponent pour faire les tooltip, comme on ajouterai le html avant l'ingestion

**Comment by nkrmr** [comment]
J'ai entièrement réécrit cette méthode pour l'adapter côté back. 
Maintenant le glossaire est généré en back, avec un web component pour chaque définition permettant de gérer l'affichage en front directement à l'affichage de la page.

**Comment by lionelB** [comment]
closed by #2687
