### ISSUE TITLE
Scroll recherche CC

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2471]
Actuellement si je recherche une CC dans une contribution ou dans un outil type préavis de licenciement, je scrolle dans les résultats (cf. image 1) puis que je sélectionne une CC, la page qui s'affiche maintient le scroll (cf. image 2) je me retrouve dans au niveau du footer et du "besoin de plus d'informations". 
![image](https://user-images.githubusercontent.com/48682104/76623576-08e2af80-6534-11ea-80b8-e9f048fd4cc7.png)
![image](https://user-images.githubusercontent.com/48682104/76623607-1730cb80-6534-11ea-86fa-0421bbc0c8c3.png)

Nous avons remarqué cela lors de tests utilisateurs. les utilisateurs ayant scollé dans les résultats des CCs et sélectionné une CC en bas n'ont pas compris la page qui s'affichait après la sélection. Ils étaient un peu déroutés et ont mis un peu de temps à se dire qu'il fallait scroller vers le haut pour retrouver le résultat. 

**Il faudrait que la page de résultats apparaisse donc sans scroll.**

**Comment by lionelB** [comment]
ah zut il m e semblait que la PR d'accessibilité corrigé ce point, je jetterai un oeil
