### ISSUE TITLE
Définir une solution pour l'ingestion des logs

### ISSUE THREAD

**Issue by rmelisson** [SocialGouv/code-du-travail-numerique#2480]
première étape pour #2440

**Comment by rmelisson** [comment]
Pour le support Elastic : 

Nous collectons actuellement les logs d’utilisation de notre service sous la forme d’un fichier JSON par journée. Afin de faciliter leur analyse, nous souhaitons les stocker dans notre cluster Elastic.

Quelques questions à ce sujet, tout d’abord en terme de dimensionnement / volume : 
- Nous souhaitons stocker environ 6 mois de logs dans Elastic, à raison de 200K event / semaine : ~ 5,5 M events
- Chaque event est composé d’une vingtaine de champs : keyword, date, int, binary, object (small), pas de text ou de gros objets.
- Quelle taille d’index nous recommanderiez-vous ? 

Concernant les specs CPU / Mem :
- Ingestion quotidienne de ~50K event 
- Nous comptons mettre en place un dashboard via Kibana qui fera des requêtes sur ces events
- Nous allons lancer des analyses régulières sur ces logs 

Concernant l’ingestion :
- Notre besoin est de traiter des fichiers json (~15MB) et d’ingérer leur contenu sous forme d’events indépendants dans Elastic.
- Nous avons essayé avec Logstash, mais avons rapidement rencontré des soucis avec les scripting stages en Ruby ainsi que des soucis de performance lorsque les fichiers devenaient trop volumineux. Peut-être que ces problèmes étaient dus à notre configuration, mais nous aimerions connaître votre avis sur la question.
- À l’heure actuelle nous penchons plutôt pour un script d’ingestion fait maison s’appuyant la lib Elastic JS ou l’API directement (tout le projet est en JS et nous traitons déjà l’ingestion de l’index avec la lib Elastic). Cela nous apporterai une certaine flexibilité pour faire le lien entre le format initial et le ce que l’on stocke dans Elastic.

**Comment by rmelisson** [comment]
![log-ingestion-proto](https://user-images.githubusercontent.com/752778/77419061-1b78a680-6dc8-11ea-87ea-5c6185ffef91.png)

**Comment by revolunet** [comment]
si je comprends bien, les données ES cloud sont basées sur les dumps azure ?

**Comment by rmelisson** [comment]
oui c'est bien ça

**Comment by rmelisson** [comment]
à présenter à l'équipe lundi
