### ISSUE TITLE
[veille] test et amélioration de la faisabilité et de la performance de la veille

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2482]
Suite aux avancées dans la mise en place d'une veille automatique du CDTN, il est important de tester la faisabilité et la performance de la solution proposée actuellement avant d'aller plus loin. 

Cf. https://review-prerenderi-979vlz-veille-git.dev.fabrique.social.gouv.fr/veille/socialgouv/kali-data

Il faudra donc faire une validation à la fois technique et à la fois métier de cette solution.

**Comment by virginielastisneres** [comment]
@revolunet @lionelB avant l'urgence du coronavirus, vous en étiez où au niveau de cette tâche ? 
mercii :)

**Comment by revolunet** [comment]
Toujours au même point sauf que c'est maintenant a priori utilisable (plus de pb de perf)

**Comment by virginielastisneres** [comment]
> Toujours au même point sauf que c'est maintenant a priori utilisable (plus de pb de perf)

Il vous reste d'autres tests du coup julien à faire pour tester la faisabilité si la perf est bonne ?

**Comment by virginielastisneres** [comment]
@lionelB @revolunet peut-on fermer cette tâche ?

**Comment by revolunet** [comment]
yes
