### ISSUE TITLE
[veille] nouvel ordre d'affichage des mises à jour

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2483]
### Solution actuelle
Actuellement les mises à jour sont affichées ainsi : ⚠️  changement d'adresse ~~https://review-prerenderi-979vlz-veille-git.dev.fabrique.social.gouv.fr/veille/socialgouv/kali-data/commit/9f8a7c146361ca814f8e3c6b660fa74950ec8414~~ ⚠️  https://cdtn-veille-git.fabrique.social.gouv.fr/

**Pour LEGI** : filtre des articles par "nouveaux", "modifiés" et "supprimés".

**Pour Kali** : 
- filtre par IDCC ;
- puis filtre des articles par "nouveaux", "modifiés" et "supprimés".

**Pour les fiches SP** : - filtre des fiches par "nouveaux", "modifiés" et "supprimés".

Cet affichage des mises à jour pourrait être améliorer afin de permettre aux experts métiers une meilleure appréhension des mises à jour. 

### Solution souhaitée

Il a donc été décidé de présenter les mises à jour comme suit : 

**Pour LEGI** : 
- filtre par la source de la modification (c'est le texte juridique qui entraîne les modifications) : exemple décret n°XXX ou avenant n°XXX ou loi n°XX ;
- puis les articles sont filtrés par : "modifié", "supprimés", "ajoutés" ;

**Pour Kali** :
- 1er niveau de filtre c'est les IDCC
- ensuite filtre par la source de la modification (c'est le texte juridique qui entraîne les modifications) : exemple décret n°XXX ou avenant n°XXX ou loi n°XX ;
- puis les articles sont filtrés par : "modifié", "supprimés", "ajoutés" ;

**Pour les fiches SP** :
- 1er filtre par les thèmes des fiches SP.
_Exemple : Famille | Accueil particuliers, Justice | Accueil particuliers, Travail | Accueil particuliers..._ 
- le thème "Travail | Accueil particuliers" est le premier affiché.
- puis dans chaque thème, on affiche les fiches selon les filtres suivants  : "nouveaux", "modifiés", "supprimés"

**Comment by lionelB** [comment]
nouvelle url : https://cdtn-veille-git.fabrique.social.gouv.fr/

**Comment by lionelB** [comment]
moved to https://github.com/SocialGouv/cdtn-admin/issues/22
