### ISSUE TITLE
URL et nom de domaine

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#249]
- URL et nom de domaine: 
* voir le SIG .gouv.fr

**Comment by lionelB** [comment]
c'est possible d'avoir plus d'info ?

**Comment by revolunet** [comment]
on a déjà `code.travail.gouv.fr` nous donner le signal pour mise en ligne

**Comment by jrduscher** [comment]
le SIG a bien validé l'URL?

**Comment by ClementChapalain** [comment]
si l'url est dispo on peut fermer cette tâche ? on basculera à partir du 1.1.20 ?
