### ISSUE TITLE
[coronavirus] Ajouter des liens externes 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2519]
### 1/ Modèles gouvernement 

Actuellement nous intégrons directement sur notre site les modèles du ministère de l'intérieur suivants : 
- Attestation sur l’honneur : déplacement dérogatoire
- Justificatif de l’employeur de déplacement professionnel

Or, ces modèles changent très régulièrement... cela implique des mep juste pour ces modèles avec un temps d'intégration pour coller à la mise en forme de ces modèles. Par ailleurs, le ministère de l'intérieur a demandé à ce que les 2 attestations ne soient téléchargées que depuis leur site.

Par conséquent, il est préférable de ne plus intégrer nos modèles directement mais de faire un renvoi vers le site du ministère de l'intérieur. 

- [ ] Ainsi, les modèles seront traitées comme on traite les liens externes aujourd'hui. 

Exemple du TéléRC : 
![image](https://user-images.githubusercontent.com/48682104/77347823-b75ad180-6d38-11ea-8ba7-5b138195ee09.png)

**Attestation sur l’honneur : déplacement dérogatoire**
- Titre de la tuile : Attestation sur l’honneur : déplacement dérogatoire
- Description de la tuile : Attestation individuelle de déplacement dérogatoire à remplir pour chaque déplacement non professionnel
- Lien : https://www.interieur.gouv.fr/Actualites/L-actu-du-Ministere/Attestation-de-deplacement-derogatoire-et-justificatif-de-deplacement-professionnel

**Justificatif de l’employeur de déplacement professionnel**
- Titre de la tuile : Justificatif de l’employeur de déplacement professionnel
- Description de la tuile : Justificatif permanent à renseigner par l’employeur pour les salariés qui doivent se déplacer pour leur activité professionnelle
- Lien : https://www.interieur.gouv.fr/Actualites/L-actu-du-Ministere/Attestation-de-deplacement-derogatoire-et-justificatif-de-deplacement-professionnel

**Attention, ces modèles sont utilisés dans le dossier spécial coronavirus et dans le "En ce moment" pour l'attestation sur l'honneur**

- [ ] On supprimer l'attestation de la rubrique "En ce moment" car on va y mettre autre chose (cf. plaquette du ministère). 

- [ ] Par contre, cela ne doit pas changer leur utilisation dans le dossier. Il faudra donc : remplacer les liens dans le dossier à l'endroit "les modèles" & conserver et remplacer les tuiles dans le dossier à l'endroit "les modèles pouvant vous intéresser"

- [ ] Bien entendu, ces liens doivent être indexés dans notre moteur de recherche

### 2/ Plaquette obligations de l'employeur Ministère du travail 

Par ailleurs, autre lien externe à ajouter celui de la plaquette suivante produite par le Ministère du travail. Il nous ait demandé de l'aide pour la mettre en avant. 

- [ ] On la traite également comme un lien externe pour faciliter les mises à jour de la plaquette 
- Titre de la tuile : Coronavirus : obligations de l'employeur
- Description de la tuile : Quelles mesures l'employeur doit-il prendre pour protéger la santé de ses salariés face au virus ? 
- Lien :  https://travail-emploi.gouv.fr/IMG/pdf/covid19_obligations_employeur.pdf

- [ ] Ce lien doit être indexé dans notre moteur de recherche

- [ ] Il doit également être rajouté dans la rubrique "En ce moment" à la place de l'attestation dérogatoire

**Comment by UnbearableBear** [comment]
solved in https://github.com/SocialGouv/code-du-travail-numerique/pull/2523
