### ISSUE TITLE
Récupérer les encarts "avertissement" présents dans les fiches SP

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2528]
### Problème
Le gouvernement va sortir des ordonnances qui vont notamment impacter le droit du travail. Les fiches SP anticipent déjà bien ca en mettant un encart d'alerte sur leur fiche impactée. 
Exemple ici =>>> https://www.service-public.fr/particuliers/vosdroits/F3053
Malheureusement ces encarts d'alerte ne sont pas repris sur le cdtn  dans nos fiches => https://code.travail.gouv.fr/fiche-service-public/arret-maladie-indemnites-journalieres-versees-au-salarie?q=Arr%C3%AAt%20maladie%20:%20indemnit%C3%A9s%20journali%C3%A8res%20vers%C3%A9es%20au%20salari%C3%A9
 
### Solution 
Il faudrait récupérer cet encart et l'afficher dans nos fiches.

On peut reprendre l'UX et UI de nos encarts présents dans les fiches MT et contributions
![image](https://user-images.githubusercontent.com/48682104/77531662-93f86980-6e93-11ea-8951-177b12580d8c.png)

**Comment by UnbearableBear** [comment]
closed with #2530
