### ISSUE TITLE
Questions Archi ES

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#253]
Liste des sujets à aborder avec la team ES :

 - quid migration/transfert des données APM quand evolution version ?
 - scalabilité horizontale/failover

**Comment by revolunet** [comment]
- n-grams
 - suggestions

**Comment by revolunet** [comment]
- gestion des phrases longues

**Comment by lionelB** [comment]
indexation des documents arborescent (avec une relation parent / enfant)

**Comment by ClementChapalain** [comment]
ça a été abordé ? on peut fermer ? ou préciser les sujets encore en cours ?

**Comment by revolunet** [comment]
travaux en cours avec ES
