### ISSUE TITLE
Le moteur de recherche des CCs ne fonctionnent plus avec les noms et mal avec le siret

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2539]
### Problème 1
Je suis sur chrome sur mon mac et la recherche des CCs par nom d'entreprise ne fonctionne pas (cf. image). Cela ne fonctionne pas non plus sur IE11 ou sur Firefox.
![Capture d’écran 2020-03-26 à 18 49 59](https://user-images.githubusercontent.com/48682104/77679406-ca68de00-6f92-11ea-83f8-545fdf197fec.png)

### Problème 2
Je cherche par SIRET l'entreprise AREAS SERVICES. Je trouve bien l'entreprise mais aucune CC n'est trouvée. Or, j'avais déjà cherché cette entreprise par siret avant et j'avais une convention collective associée. J'ai testé d'autres sirets et à chaque fois ils ne trouvent pas de CC sélectionnée. 
![image](https://user-images.githubusercontent.com/48682104/77680262-005a9200-6f94-11ea-8d2f-840c949ddd30.png)
![image](https://user-images.githubusercontent.com/48682104/77680380-2849f580-6f94-11ea-9ca7-fa4983d6d3dd.png)

**Comment by virginielastisneres** [comment]
Siret2idcc cassé @revolunet :) (merci lionel)

**Comment by revolunet** [comment]
sniff sniff... c'est corrigé

et j'ai ajouté une alerte sur le [monitorer](https://socialgouv-monitor.herokuapp.com) pour être alerté la prochaine fois !!

**Comment by virginielastisneres** [comment]
mercii julien :)

**Comment by revolunet** [comment]
je pense qu'on peut close cette issue

**Comment by virginielastisneres** [comment]
> je pense qu'on peut close cette issue

complément d'accord avec toi @revolunet :)
