### ISSUE TITLE
Amélioration de la page Thème 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2543]
### Problème
Voici une page thème aujourd'hui : 

![image](https://user-images.githubusercontent.com/48682104/77888117-07bbbd00-726c-11ea-99a0-615e398480b6.png)

Cette page n'est pas très claire, les sous thèmes sont tellement gros que l'on pourrait ne pas voir qu'il y a du contenu proposé. Elle fait un peu négligée par rapport aux autres pages du site. Il manque du contenu.  

### Solution pour toutes les pages Thèmes 

- [ ] Nouveau design des boutons sous-thèmes. Design ici => https://www.figma.com/file/77Fp6oZ3iLPMKIRg2McakC/Th%C3%A8mes?node-id=11%3A5

- [ ] Ajouter le contenu annexe avec 2 sections les outils et les modèles. Pour les outils et les modèles il faudrait les affiches par des tuiles. Il serait bon de voir le maximum d'outils et de modèles que l'on a dans un thème afin de s'assurer qu'il s'agisse de la meilleure présentation. 

- [ ] Décaler le contenu principal sur le côté gauche

- [ ] (test) Mettre également les thèmes pouvant intéresser : à voir s'il y a des thèmes intéressants qui ressortent.

- [x] Fil d'ariane : ca arrive

### Solution uniquement sur les 9 principaux Thèmes (test)

- [ ] Rajouter une petite description pour chaque grand thème dans un premier temps, cette fonctionnalité est présente dans le datafiller. Elle devra se situer entre le titre et les sous-thèmes. 
Descriptions dans le design figma (https://www.figma.com/file/77Fp6oZ3iLPMKIRg2McakC/Th%C3%A8mes?node-id=11%3A5). 
**Attention pour bien gérer la différence entre les thèmes qui auront une description (cad les 9 principaux) et ceux qui n'en auront pas il faudra remonter les boutons sous-thèmes**.

- [ ] Mettre en Meta description ces définitions.

![7-Theme-MiniHub (5)](https://user-images.githubusercontent.com/48682104/78276286-1b3c8180-7513-11ea-898b-3fc150451763.jpg)

**Comment by UnbearableBear** [comment]
Super les boutons bleu ! c'est bien mieux !
Par contre pour le fond il a une hauteur fixe et les nombre de sous thèmes étant aléatoire il va falloir trouver un juste milieu. On en reparle
