### ISSUE TITLE
Modifier le libellé des références juridiques avec la mise à jour des contrib

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2549]
### Problème 
Nous avons voulu hier lors de la mise en prod mettre à jour les contributions. 
Malheureusement nous nous sommes rendus compte que l'affichage des références juridiques présentes dnas les contributions que cela soit dans les contributions elle même ou dans la page CC ne s'affiche pas bien. 
En effet, nous avons le lien Kali qui s'affiche au lieu du nom exact de la référence. 
![image](https://user-images.githubusercontent.com/48682104/78027339-804e7680-735d-11ea-8386-558c881a445b.png)

### Solution
Au lieu d'avoir le lien Kali qui s'affiche il faut que cela soit le nom de la référence. 
![image](https://user-images.githubusercontent.com/48682104/78027526-cb688980-735d-11ea-8658-101d18b61b74.png)

**Comment by virginielastisneres** [comment]
@ivangabriele @lionelB @UnbearableBear pouvez vous me dire où nous en sommes ?

**Comment by lionelB** [comment]
j'ai fait une modif dans la PR #2564 avant de partir en vacances qui fix le problème des ref. ca gère l'ancienne est le nouveau format

**Comment by virginielastisneres** [comment]
> j'ai fait une modif dans la PR #2564 avant de partir en vacances qui fix le problème des ref. ca gère l'ancienne est le nouveau format

Ah super donc cette modif suffit à elle toute seule pour régler le problème ? @lionelB @ivangabriele

**Comment by UnbearableBear** [comment]
Il ne restera rien à faire avec le nouveau format ? Peut-etre garder l'issue pour quand le nouveau format sera là, enlever le code redondant ?

**Comment by lionelB** [comment]
@virginielastisneres  oui :)

**Comment by ivangabriele** [comment]
@virginielastisneres @lionelB @UnbearableBear La raison pour laquelle je n'ai pas encore terminé la nouvelle vue permettant de récupérer le tout sans besoin de seconde passe est que nous avons un certain nombre de problèmes avec la migration des anciennes références: besoin d'une seconde passe de migration, d'un nouveau script/outil, et de features supplémentaires côté back-office.

Je veux donc être sûr d'être sur le bon modèle avant de finaliser cette vue. J'essaie de finir au plus vite mais je pense qu'il faudra compter la fin de la semaine pour y arriver de mon côté.

Du coup, peut-être vaut-il mieux laisser cette issue ouverte pour le moment ?

**Comment by UnbearableBear** [comment]
@ivangabriele je te l'assigne et on va se faire un petit ping pong jusqu'à ce qu'elle se termine. Sinon dès que je la vois je la relis avant de réaliser qu'elle est en stand-by

**Comment by lionelB** [comment]
Pour l'instant, le pb des labels est traité dans la pr #2564.  Il faut attendre que les ref soient migrées et que la nouvelles vue soit dispo pour faire la suite... on peut être fermé et ouvrir un issue pour la migration quand le vue serait dispo ?

**Comment by lionelB** [comment]
la migration des référence a résolu le problème
