### ISSUE TITLE
Permettre à l'utilisateur préciser son feedback

### ISSUE THREAD

**Issue by rmelisson** [SocialGouv/code-du-travail-numerique#2550]
Lorsque l'utilisateur fait un retour sur son utilisation (surtout dans le cas des retours négatifs), il devrait pouvoir laisser un commentaire afin de décrire le problème rencontré, c'est une source précieuse d'information.

La fonctionnalité a été retirée en place il y a qqs mois, peut-être pour une bonne raison que j'ignore ? ;)

**Comment by UnbearableBear** [comment]
Je crois que c'est principalement parce que tous les commentaires remontés étaient des questions sur le droit du travail @ClementChapalain tu confirmes ?

**Comment by ClementChapalain** [comment]
oui 2 raisons principales à cela : 
- beaucoup de retours concernaient des questions de droit du travail
- trop de retours en langage naturel qui étaient difficiles à analyser

mais je ne suis pas opposé à remettre la fonctionnalité, il faut juste qu'on réfléchisse à l'ux du truc c'est pas si évident que ça pour moi. 

@rmelisson qu'est ce qui serait le plus intéressant pour toi ? je vois différents types d'infos qu'on pourrait récupérer : 
- raison pour laquelle il n'est pas satisfait --> à ce moment là on peut faire un dropdown avec différentes possibilités
- commentaire libre sur la raison pour laquelle il n'est pas satisfait --> attention à l'ux pour ne pas inciter à rentrer sa question de droit du travail
- autre ?

**Comment by rmelisson** [comment]
Oui il faut être suffisamment clair sur le wording en précisant bien que ça concerne uniquement le site et que ça n'appelle pas de réponse de notre part.

Pour les retours en language naturel, c'est l'occasion d'essayer de les analyser automatiquement. En tout cas mon point de vue c'est plutôt : si les gens veulent nous envoyer des commentaires on prend, d'autant plus que c'est sans obligation de réponse.

Je ferais au plus simple pour le moment, juste un commentaire libre, avec effectivement un warning explicite concernant la question droit du travail.
Le but c'est de démêler des insatisfactions que l'on ne comprend.

(après c'est mon avis vu d'ici, sans l'expérience des retours laissés dans la version précédente)

**Comment by rmelisson** [comment]
Je relance le sujet suite aux discussions récentes, je suis partant pour :
- un choix d'options standard (contenu non pertinent / contenu incompréhensible / contenu pas assez précis ...)
- une option commentaire libre qui n'aurait surtout pas vocation à recevoir une quelconque réponse (à clairement expliciter dans la formulation)

**Comment by ArmandGiraud** [comment]
On pourrait se calquer sur la méthodologie de service public: 
qui consiste à proposer des options, et ouvrir un commentaire libre si pertinent. 
Pour les options, il faudrait probablement les adapter au type de contenu visité:
par exemple: 

 - Fiche:
    - l'information est facile à comprendre?
      - (1, 2, 3)
   - La fiche est trop complexe ou contient trop d’informations
    - Je ne suis pas satisfait(e) de cette réglementation
    - la fiche que je cherche n'existe pas:
         - Avez vous déjà utilisé la barre de recherche/navigation par thème?
           - Non: voulez vous naviguer par thème/search?   
           - Oui: quelle est le titre de la fiche que vous **souhaiteriez** pouvoir consulter
    - le contenu de la fiche semble erroné ou obsolète? 
        -  quelles partie(s) semble(nt) erronée(s)
    - Le contenu de la fiche n'est pas suffisamment personnalisé:
          - quelle information permettrait d'affiner  la réponse:
           - convention collective
           - contrat de travail
           - ...

- Modèle: 
  - Le modèle que je cherche n'existe pas:
     - quel modèle recherchez vous ? 
  - Le modèle ne s'applique ne correspond pas à ma situation: 
      - quelle est votre situation? 
  - Le modèle ne se télécharge pas correctement
  - le modèle me semble faux..
  - ...
- Outil:
  - Je ne suis pas satisfait(e) de cette réglementation
  -  l'outil ne propose pas de solution dans ma situation
  - l'outil ne me permet pas de renseigner mes informations
  - je ne sais pas où trouver les informations nécessaires
- Contribution: 
  - ...  
![image](https://user-images.githubusercontent.com/22575341/112172174-c5199000-8bf4-11eb-8178-ae1132959609.png)
ping @rmelisson @virginielastisneres @CaptainConan

**Comment by rmelisson** [comment]
J'aime bien la proposition, en gros une option toute simple, et ensuite la possibilité pour les plus motivés de nous en dire plus.
On pourrait faire qqchose d'assez générique pour pouvoir le faire évoluer facilement, car on ne va pas trouver du premier coup les bonnes questions à poser.
En plus on pourrait se servir de ça pour pouvoir faire des évaluations sur des sujets plus précis.
(par exemple on pourrait poser des questions différentes sur tel ou tel contenu qu'on souhaite faire évoluer)

**Comment by romain-b13** [comment]
Voici une proposition travaillée avec Virginie => débuter avec des questions identiques pour les différents contenus (à voir pour les outils) avec 2 parcours différents en fonction de la réponse à la 1ère question (Oui ou Non) : 

### 1ère question  (identique à la question actuelle) :
Avez-vous trouvé la réponse à votre question ? 
- Non / Oui
![image](https://user-images.githubusercontent.com/84397271/119863252-a946a900-bf19-11eb-836e-37cf7d3bcff7.png)


### Si la réponse est non 

1. 
![image](https://user-images.githubusercontent.com/84397271/119862796-2de4f780-bf19-11eb-91c8-79562d853860.png)

2.  Je clique sur "envoyer"
![image](https://user-images.githubusercontent.com/84397271/119863438-d7c48400-bf19-11eb-900e-93cfd3796403.png)



### Si la réponse est oui 

1. 
![image](https://user-images.githubusercontent.com/84397271/119862968-608ef000-bf19-11eb-85ac-437e5e2ebf29.png)

2. Je clique sur "envoyer"
![image](https://user-images.githubusercontent.com/84397271/119863784-37bb2a80-bf1a-11eb-9048-104e542a09f0.png)

Lien vers les maquettes si besoin https://www.figma.com/file/Te4YZI7n69PMq5BvLZi00Z/Refonte-question-de-satisfaction-utilisateur?node-id=0%3A1

**Comment by romain-b13** [comment]
**Petite modification pour le parcours non (cf point n°3)**

### 1. 
![image](https://user-images.githubusercontent.com/84397271/122800470-43a0cf00-d2c3-11eb-866f-330d285398c7.png)

### 2. 
![image](https://user-images.githubusercontent.com/84397271/122800497-4bf90a00-d2c3-11eb-8fa8-8bb5943f1e3c.png)

### 3.
![image](https://user-images.githubusercontent.com/84397271/122800550-5adfbc80-d2c3-11eb-8559-23c3aecd51a8.png)

### 4.
![Non 3](https://user-images.githubusercontent.com/84397271/122800810-adb97400-d2c3-11eb-9bd6-61ce932aa6a7.PNG)

**Comment by romain-b13** [comment]
Serait-il possible d'ajouter également ce module sous la page résultat des outils ?

**Comment by lionelB** [comment]
Tracking
```js 
matopush(["trackEvent", "feedback", "positive" | "negative", url]);
matopush(["trackEvent", "feedback_category", string, url]); // 1 event par valeur pour chaque cases cochées
matopush(["trackEvent", "feedback_suggestion", string,  url]);
```

**Comment by romain-b13** [comment]
Issue validée
