### ISSUE TITLE
Fonctionnement des tooltip du glossaire en mobile

### ISSUE THREAD

**Issue by nkrmr** [SocialGouv/code-du-travail-numerique#2552]
**Description**
Les tooltips du glossaire ne fonctionne pas comme il faudrait en mobile ils s'affichent de façon aléatoire. 

**Reproduction**
Étapes à suivre pour reproduire le bug
1. Se rendre sur une fiche **https://code.travail.gouv.fr/fiche-ministere-travail/le-salaire-fixation-et-paiement?q=Salaire#Comment-est-fixe-le-salaire-de-base** par exemple avec son téléphone.
2. Cliquer sur les définitions du glossaire
3. Les tooltips de définition s'affichent de façon aléatoire

**Comportement attendu**
Lors d'un clique (touch en mobile) on devrait avoir la définition du mot qui s'affiche correctement. 
On peut également faire le choix d'être en mode "dégradé" en mobile et ne pas afficher les définitions.

**Configuration**
  - Device: iPhone
  - Navigateur: Safari

**Comment by virginielastisneres** [comment]
@nkrmr Nico du coup, tu penses que cette tâche sera réglée avec le traitement du glossaire dans le back ?
