### ISSUE TITLE
Elastic logs : instance on Elastic cloud

### ISSUE THREAD

**Issue by rmelisson** [SocialGouv/code-du-travail-numerique#2558]

**Comment by revolunet** [comment]
est-ce qu'on a les "specs" souhaitées ? volume disque, qté RAM ?

<img width="1184" alt="Capture d’écran 2020-04-03 à 17 46 02" src="https://user-images.githubusercontent.com/124937/78379661-058e9100-75d3-11ea-899d-4aca100ae612.png">

**Comment by rmelisson** [comment]
Nan le support était pas du tout clair, mais ça serait bien de configurer ça ensemble aujourd'hui si possible pour toi.

**Comment by rmelisson** [comment]
elastic: https://804b8d99b80941e2a99f551cd481fb5b.westeurope.azure.elastic-cloud.com:9243
kibana : https://0889393a3e19455c9336114c781fb1c0.westeurope.azure.elastic-cloud.com:9243
