### ISSUE TITLE
next/router + Link

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#256]
On a des les liens qui nécessitent une `anchor`, or le composant Link de [next-routes](https://github.com/fridays/next-routes) ne les gère pas... Donc on perd l'intérêt d'une SPA sur ces liens là (la page se recharge).

Solution possible : implémenter https://github.com/fridays/next-routes/pull/91

**Comment by revolunet** [comment]
https://github.com/fridays/next-routes/pull/258#issuecomment-441984990

**Comment by lionelB** [comment]
@revolunet on peut fermé ? #354

**Comment by ClementChapalain** [comment]
up :)

**Comment by revolunet** [comment]
fixed
