### ISSUE TITLE
Fiches min.travail manquantes

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#257]
ex: https://travail-emploi.gouv.fr/droit-du-travail/la-rupture-du-contrat-de-travail/article/la-rupture-conventionnelle-collective

**Comment by lionelB** [comment]
il faudrait généré un json à partir d'un nouvel export ?

**Comment by revolunet** [comment]
Oui comprendre pourquoi cette CCN n'apparait pas et refaire un JSON si besoin a partir des 2 jeux de données sur data gouv

**Comment by revolunet** [comment]
Je propose qu'on se base sur la BDD du site (spip??) plutôt que de scraper

**Comment by lionelB** [comment]
pourquoi pas, est ce qu'on peut avoir un export sqlite, tu crois ?

**Comment by jrduscher** [comment]
on a contacté le service qui gère les fiches pour trouver une solution propre. en attente de rdv.

**Comment by lionelB** [comment]
closed by #288
