### ISSUE TITLE
Ajout outil externe 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2578]
Un simulateur pour calculer l'activité partielle à jour des derniers changements a été mis en ligne sur le site du ministère du travail. Il nous faut récupérer cet outil pour le mettre dans nos outils externes et l'indexer dans notre moteur de recherche. 

### Présentation de l'oOutil externe 

Titre : Simulateur d’activité partielle
Description : Estimez simplement le montant de l'allocation d'activité partielle. 
Adresse url : http://www.simulateurap.emploi.gouv.fr/

### Où le rajouter 

- [x] L'indexer dans notre moteur de recherche.

- [x] Dans le dossier Coronavirus : (cf.image ci-dessous)
Il faut rajouter une section "outil" sur le côté.
![Capture d’écran 2020-04-06 à 15 20 22](https://user-images.githubusercontent.com/48682104/78564322-8b514d00-781c-11ea-810f-13c48913c5b4.png)
et en bas, rajouter une section "Outils pouvant vous intéressez" après la section des modèles. 
![Capture d’écran 2020-04-06 à 15 38 15](https://user-images.githubusercontent.com/48682104/78564411-ad4acf80-781c-11ea-8770-b378bfb557a5.png)

**Comment by UnbearableBear** [comment]
done !
