### ISSUE TITLE
Meta Title et Meta description : dossier coronavirus

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2581]
Pour le dossier Coronavirus (https://code.travail.gouv.fr/dossiers/ministere-du-travail-notre-dossier-sur-le-coronavirus) voici notre méta title et méta description actuelles : 

![Capture d’écran 2020-04-06 à 19 16 25](https://user-images.githubusercontent.com/48682104/78586051-22c59880-783b-11ea-9dee-928e0c595973.png)

### Meta title 

Il faut rajouter une majuscule à "notre".

### Meta description  

Il faut changer la description comme suit : "Coronavirus et le travail : télétravail, démarches chômage partiel, santé, sécurité, obligations de l'employeur, congés payés, arrêt de travail pour garder ses enfants, droit de retrait...".

**Comment by UnbearableBear** [comment]
done !
