### ISSUE TITLE
Sous page dossier Coronavirus français facile : changements ordonnances 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2586]
### **Fonctionnalité**
Nous souhaitons améliorer notre dossier et proposé une page français facile qui résume rapidement et simplement les changements intervenus en droit du travail liés à la crise Coronavirus. 
Seront présents dans cette page : 
- une présentation en français facile par thème des changements
- des infographies simples et claires pour améliorer la compréhension

### **Structure de la page**
Sur l'exemple des pages "A propos" ou "Mentions légales", page simple avec : 
- un titre 
- une date de mise à jour
- une description
- des sous parties avec des accordéons (cf.design pour les différentes parties)
- dans les accordéons du texte avec les références juridiques associées et parfois des infographies (cf. design pour les textes à intégrer + cf. plus bas pour plus de détails sur le traitement des infographies)
![image](https://user-images.githubusercontent.com/48682104/78922342-aaf3aa00-7a96-11ea-96aa-b1969fd8c887.png)

### **Où trouver la page**
- La page n'est pas indexée dans notre moteur de recherche car liée entièrement au dossier toute seule elle a peu d'intérêt. 
- La page est mise dans la rubrique du dossier "L'essentiel" en 1ère position.
- Elle est présentée comme une carte contenu avec un titre et une description (cf. design pour le texte)
- On oublie pas le fil d'ariane qui permet de revenir au dossier (cf. design) 

### **Méta title et Méta description associés**
- Méta title : "Coronavirus : ce que changent les ordonnances en droit du travail - Ministère du travail"
- Méta description : "Coronavirus : aménagement des règles pour le chômage partiel, les congés payés, RTT, l'indemnisation chômage, les durées maximales de travail, la garde d'enfant pour l'assistant(e) maternel(le)."

### **Design**
Pour le design voir ici => https://www.figma.com/file/1ArirP0IXytwPfVk86do9B/Untitled?node-id=0%3A1

### **Cas particulier des sous-parties avec des infographies**

**Comportement attendu :** 
- Quand l'utilisateur clique sur l'accordéon d'un thème présentant une infographie, l'infographie se charge à ce moment là en premier. 
- Rajouter en dessous de l'infographie un "Voir la version texte plus détaillée". 
- Rajouter en dessous du "voir" les références juridiques.
- Quand je clique sur "voir la version" se déroule le texte. 

**Quelles infographies et où ?** 
2 infographies pour l'instant : 
- l'une dans la partie "Congés payés :  imposer ou modifier les congés payés "
- l'autre dans la partie "Jours RTT, jours de repos, compte épargne-temps : imposer des jours"
Les infographies sont ici => https://www.figma.com/file/f6Bzbk5x45DfqNgovU0XLV/RTT?node-id=116%3A5985

**Comment by lionelB** [comment]
c'est pas fait deja ? 
cc @UnbearableBear

**Comment by UnbearableBear** [comment]
Hum si !

**Comment by lionelB** [comment]
@UnbearableBear n'oublie pas de lié les PR avec les issue quand tu fermes une issue :)
#2598
