### ISSUE TITLE
Nouveau logo officiel du site du ministère du travail à intégrer

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2596]
Il y a désormais un nouveau logo pour le ministère du travail qu'il faut donc mettre à jour sur notre site. 
Voici le nouveau logo
![MIN_Travail_RVB (1)](https://user-images.githubusercontent.com/48682104/79002416-b9060100-7b50-11ea-83a5-427e8d65c072.jpg)

**Il doit être intégré dans le header.** 
cf. https://www.figma.com/file/2yQQFyFFnHQVjXnYY1zle8/Untitled?node-id=0%3A1

**Comment by lionelB** [comment]
Je m'interroge sur le fait que le logo dépasse du header , c'est voulu ?

**Comment by virginielastisneres** [comment]
> Je m'interroge sur le fait que le logo dépasse du header , c'est voulu ?

Non, j'ai supprimé :)

**Comment by lionelB** [comment]
https://www.gouvernement.fr/charte/charte-graphique-les-fondamentaux/le-systeme-graphique

pour la reco d'utilisation sur le web

**Comment by virginielastisneres** [comment]
> https://www.gouvernement.fr/charte/charte-graphique-les-fondamentaux/le-systeme-graphique
> 
> pour la reco d'utilisation sur le web

Oui en effet avec la nouvelle charte il y a des standards à respecter. Pour le moment il nous est demandé de rajouter rapidement le logo, du coup on va commencer par simplement remplacer celui que l'on a pas le nouveau et ensuite réfléchir à la meilleure intégration possible car cela va avoir des conséquences sur le header.
