### ISSUE TITLE
Enlever le bandeau des cookies + google analytics + tarteaucitron

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2607]
La com ne nous a pas encore répondu sur la continuité ou pas de la campagne. Pour autant, cela fait 5 jours qu'on a moins de 20 visites campagnes par jour. 

Par conséquent, on a décidé de tout enlever : 
- bandeau cookies
- google analytics
- tarteaucitron

**Comment by lionelB** [comment]
sachant qu'on ne perd pas l'info des visites "campagne" qui seroont identifiées dans matomo

**Comment by revolunet** [comment]
![](https://media.giphy.com/media/l0HUqsz2jdQYElRm0/giphy.gif)

**Comment by lionelB** [comment]
il faut juste qu'on re-boucle avec thomas pour le readcationnel

**Comment by ThomasMenant** [comment]
Hello,

Yeahhhhhh, rien ne s'oppose à tout enlever (bandeau cookies etc).
Il faudra modifier à la marge la politique de confidentialité, en supprimant GA du paragraphe suivant :
Ces cookies permettent au Code du travail numérique d’établir des mesures statistiques de fréquentation et d’utilisation du site. Pour ce faire, nous utilisons les services proposés par la suite Google Analytics et Matomo.

cheers

**Comment by lionelB** [comment]
merci @ThomasMenant

**Comment by UnbearableBear** [comment]
Coohool ! Je mets à jour la PR !

**Comment by UnbearableBear** [comment]
@ThomasMenant Le texte sur cette page est ok pour toi ? https://7819b64-code-travail.dev.fabrique.social.gouv.fr/politique-confidentialite
