### ISSUE TITLE
Prévoir un équivalent texte pour les infographies

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#2610]
la page ~~https://master-code-travail.dev.fabrique.social.gouv.fr/dossiers/ministere-du-travail-notre-dossier-sur-le-coronavirus/ce-que-changent-les-ordonnances-en-droit-du-travail~~  https://master-code-travail.dev.fabrique.social.gouv.fr/information/conges-payes-nouveautes-covid-19
présente des infographies n'ayant pas d'équivalent texte. 
Le texte en dessous est plus complet mais plus difficile a appréhender

#solutions#

Utiliser une balise SR-only avec du contenu html correctement formaté ou renvoyer vers une page avec le contenu textuel

**Comment by UnbearableBear** [comment]
Tu as remarqué que l'inforgraphie est dans une balise `<figure>` et que du html détaillé correctement formaté est présent dans le `<figcatpion>` ? Le alt texte de l'image le précise

**Comment by lionelB** [comment]
oui, j'avais bien vu le figcaption mais qui ne reprend pas le texte de l'image :(

**Comment by lionelB** [comment]
je ferme car le texte d'explication en dessous et deja un simplification et permet de completer l'image.
