### ISSUE TITLE
ES - Ajouter le synonyme covid-19, coronavirus

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#2611]
ajouter à la liste des synonymes ES 
cc @ArmandGiraud ok pour le rajouter dans les synonymes de nlp ?

**Comment by ArmandGiraud** [comment]
Pour ES c'est une bonne chose, pour nlp on a pas vraiment de liste de synonymes.

**Comment by lionelB** [comment]
ok merci

**Comment by virginielastisneres** [comment]
Hello :) Où en est cette tâche @lionelB ?
