### ISSUE TITLE
[Bug] Lien dans des articles qui ne sont pas des articles du code du travail

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2615]
### Problème
Nous renvoyons dans nos articles du code du travail à d'autres articles du code du travail lors ces articles sont mentionnés dans un article. 

Exemple ci-dessous : quand on est dans l'article R3332-8. 
![image](https://user-images.githubusercontent.com/48682104/79254111-86c40e80-7e84-11ea-9ea0-26bd8b8135b2.png)
Il est cité l'article L3332-11. On peut cliquer dessus et on arrive sur cet article dans le CDTN. si on clique sur l'autre article mentionné le "L. 241-3", nous avons une erreur 404 (lien de l'erreur https://code.travail.gouv.fr/code-du-travail/l241-3). 
![image](https://user-images.githubusercontent.com/48682104/79254258-bffc7e80-7e84-11ea-8641-c90268df798e.png)

Le problème vient surement du fait que nous n'avons dans le CDTN que les articles du code du travail et le 2ème article est un article du code de la sécurité sociale, d'où surement le 404. 

Lien pour tester le problème => https://code.travail.gouv.fr/code-du-travail/r3332-8?q=R3332-8%20du%20code%20du%20travail

### Solution à définir
Il faudrait donc trouver une solution car ce n'est pas un cas isolé, beaucoup d'articles du code du travail citent d'autres articles d'autres codes. 
**Peut-on détecter quand il s'agit d'articles d'autres codes ?** @rmelisson 
Nous pourrons alors soit supprimer un possible renvoi soit renvoyer vers le lien légifrance, à voir.

**Comment by lionelB** [comment]
@virginielastisneres il me semble qu'une issue existe deja à ce sujet, je checke et je te dit

**Comment by revolunet** [comment]
A noter que pour l'instant c'est une detection très naive : https://github.com/SocialGouv/code-du-travail-numerique/blob/253436293dbac370c2f697239505a61d124332e7/packages/code-du-travail-frontend/src/lib/replaceArticlesRefs.js#L8

une solution temporaire serait de detecter qu'il y a "du code xxx" à la suite, ce qui indique qu'on parle d'un autre code, et donc de désactiver le lien interne dans ce cas là.

Une solution plus smart serait de faire un lien vers legifrance dans ce cas la, pense que @rmelisson est sur le coup

**Comment by rmelisson** [comment]
Yes on peut appliquer l'algo que j'utilise pour les fiches MT, je peux faire ça dans la foulée. Le seul truc c'est que ça devra plutôt être fait dans le back, sauf à avoir une autre api en ligne pour resolve les ids legi-data dans le front...

**Comment by lionelB** [comment]
vu les pre-traitements  qui s'annoncent, est ce qu'on devrait pas commencé à réfléchir à la mise en place d'un pipeline de traitement ?

**Comment by virginielastisneres** [comment]
est ce que l'on pourra se parler de ce problème la semaine prochaine ?
