### ISSUE TITLE
le widget issuu.com ne marche pas

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#2633]
la page https://code.travail.gouv.fr/fiche-ministere-travail/tapis-roulants-de-montagne-mise-a-niveau?q=tapis%20roulant
charge un widget issuu.com 
celui-ci n'etant pas listé dans les csp, il est donc blacklisté :/

**Comment by revolunet** [comment]
je ne pense pas qu'on veuille l'autoriser

**Comment by lionelB** [comment]
on ferme ?
