### ISSUE TITLE
Ajouter une page résultat "trouver sa CCN"

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#265]
https://trello.com/c/TCXBUBgT/276-ux-r%C3%A9flechir-%C3%A0-comment-lutilsiateur-trouve-sa-ccn

rapprocher des #99 et #37 

 - [ ] ajouter le wording + exemple ( métier)
- [ ] integrer le modèle UX
- [ ] permettre de requeter le rsulatat par une question "comment trouver la CCN"
-

**Comment by lionelB** [comment]
![image](https://user-images.githubusercontent.com/160320/48277263-78c9bd00-e44a-11e8-8bc2-3d8a1913189b.png)

**Comment by ClementChapalain** [comment]
done avec http://master.code-du-travail-numerique.dev.factory.social.gouv.fr/convention-collective/recherche
