### ISSUE TITLE
Mise en place du nouveau backoffice : veille 🚀

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#2663]
## Contexte

Aujourd'hui nous avons différents outils pour gérer la veille et l'administration du CDTN :
- le datafiller
- l'outil de veille git
- github
- les documents spreadsheet

L'objectif est de centraliser et d'unifier ces outils dans un seul et même backoffice pour garantir une meilleure sécurité et usabilité de l'administration du CDTN.

Plan d'attaque : 
1. Créer la structure et les bases techniques du nouveau backoffice
2. Migrer iso-fonctionnellement l'outil de veille git
3. Améliorer les fonctionnalités de veille (commentaires, contenus liés, etc.)
4. Migrer les fonctionnalités du datafiller
5. Ajouter les fonctionnalités d'administration avancées (gestion des courriers, des outils, etc.)

### Objectif

Dans cette tâche l'objectif est de créer une première version en reprenant les fonctionnalités déjà existantes de l'outil de veille git (https://cdtn-veille-git.fabrique.social.gouv.fr/) avec les améliorations prévues par #2483.

### Maquettes

https://www.figma.com/proto/GZaK1nv3bjKvWeWCYU4X70/CDTN-Veille-et-administration?node-id=61%3A1019&viewport=-1841%2C-1713%2C0.9181605577468872&scaling=min-zoom
--> voir le lien MVP

#### Bases
- [x] En tant qu'administrateur du backoffice, je dois pouvoir ajouter / supprimer / modifier des comptes utilisateurs du backoffice
- [x] En tant qu'utiilisateur du backoffice, je dois pouvoir me connecter à la plateforme avec un login / mot de passe

#### Navigation
- [x] En tant qu'utilisateur, je dois pouvoir naviguer entre les différents liens suivants via le menu de gauche toujours accessible : 
  - Alertes LEGI / Alertes KALI / Alertes Fiches SP
  - Liens utiles
    - CDTN prod : http://code.travail.gouv.fr/
    - CDTN master : https://master-code-travail.dev.fabrique.social.gouv.fr/
    - Outil de contribution : https://contributions.codedutravail.num.social.gouv.fr/
    - Matomo : https://matomo.fabrique.social.gouv.fr/index.php?module=MultiSites&action=index&idSite=3&period=range&date=last30
    - Boîte mail partagée CDTN : https://messagerie.social.gouv.fr/
- [x] En tant qu'utilisateur, je dois revenir à la page "Alertes LEGI" lorsque je clique sur le logo "ministère du Travail - Code du travail numérique - veille et administration"
- [x] En tant qu'utilisateur, je dois pouvoir me déconnecter en cliquant sur mon nom dans le menu
- [x] En tant qu'utilisateur, je dois pouvoir accéder à une page de compte avec mes informations en cliquant sur mon nom dans le menu

#### Alertes
- [x] En tant qu'utilisateur, j'ai accès aux même fonctionnalités que dans l'outil actuel de veille git
- [x] En tant qu'utilisateur, les alertes sont triées par source comme définies dans #2483 afin de simplifier leur traitement

**Comment by lionelB** [comment]
done by https://github.com/SocialGouv/cdtn-admin/pull/14

**Comment by CaptainConan** [comment]
Retours sur l'outil d'admin:
- alertes:  inverser l'ordre, pour retrouver la dernière mise à jour en première
- fiches SP: ne récupérer que les fiches du thème "travail"
- ajouter le diff
- ajouter un espace de notes (1/onglet pour chaque catégorie d'alerte)

**Comment by lionelB** [comment]
Je ferme ici suite à la mise en place du projet cdtn-admin
on pourra ouvrir d'autre issue là-bas
