### ISSUE TITLE
Affichage des modèles de courrier

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#267]
- [x] Integrer les modifs de mise en forme suite à proposition UX : https://trello.com/c/POKc0yVJ/313-mod%C3%A8les-de-courrier

**Comment by lionelB** [comment]
c'est pas un duplicate de https://github.com/SocialGouv/code-du-travail-numerique/issues/236  ?

**Comment by lionelB** [comment]
duplicate #236  closed by #262
