### ISSUE TITLE
Ajustements page dossier 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2692]
REMARQUES CONTENUS

- [x] Suppression du lien externe suivant : https://travail-emploi.gouv.fr/IMG/pdf/covid19_obligations_employeur.pdf 

- [x] Dans la rubrique les contenus populaires : remplacer "Nouveautés covid 19 : Congés payés " remplacer par "Nouveautés Covid-19 : congés payés"

- [x] Dans la rubrique activité partielle :
Remplacer "Questions - Réponses : Activité partielle - chômage partiel" par "Questions - Réponses : activité partielle - chômage partiel".
Le 3ème lien est pas bon https://04c7590-code-travail.dev.fabrique.social.gouv.fr/fiche-service-public/remuneration-dun-salarie-place-en-activite-partielle-chomage-partie doit être remplacé par https://code.travail.gouv.fr/fiche-service-public/remuneration-dun-salarie-place-en-activite-partielle-chomage-partiel

- [x] Dans la rubrique "santé et sécurité" remplacer 
"Questions - Réponses : Responsabilité de l’employeur et droit de retrait" par "Questions - Réponses : responsabilité de l’employeur et droit de retrait"
"Questions - Réponses : Mesures de prévention dans l’entreprise contre le COVID-19 - Masques" par "Questions - Réponses : mesures de prévention dans l’entreprise contre le COVID-19"
"Questions - Réponses : Services de santé au travail" par "Questions - Réponses : services de santé au travail"
"Questions - Réponses : Mesures de prévention hors covid" par "Questions - Réponses : mesures de prévention hors covid" 

Et ajouter en 2ème lien ? comme un lien externe la page suivante : https://travail-emploi.gouv.fr/actualites/presse/communiques-de-presse/article/protocole-national-de-deconfinement-pour-les-entreprises-pour-assurer-la
nom de lien : "Protocole national de déconfinement"

- [x] Dans la rubrique "Congés payés, durée du travail et primes" Erreur 500 sur tous les liens de la page nouveautés covid 19 => https://04c7590-code-travail.dev.fabrique.social.gouv.fr/ministere-du-travail-notre-dossier-sur-le-coronavirus/nouveautes-covid19#conges
elle fonctionne ici par contre https://04c7590-code-travail.dev.fabrique.social.gouv.fr/dossiers/ministere-du-travail-notre-dossier-sur-le-coronavirus/nouveautes-covid19#conges
j'ai remarqué qu'il manque un /dossiers/ dans les liens qui ne fonctionnent pas.

et Remplacer : 
"Nouveautés coronavirus : Congés payés" par "Nouveautés Covid-19 : congés payés"
"Nouveautés coronavirus : RTT, jours de repos forfait jours, compte épargne-temps" par "Nouveautés Covid-19 : RTT, jours de repos forfait jours, compte épargne-temps"
"Nouveautés coronavirus : Prime exceptionnelle de pouvoir d’achat" par ""Nouveautés Covid-19 : prime exceptionnelle de pouvoir d’achat"
"Nouveautés coronavirus : Intéressement et participation" par "Nouveautés Covid-19 : intéressement et participation"
"Nouveautés coronavirus : Durées maximales de travail, repos quotidien et dominical" par "Nouveautés Covid-19 : durées maximales de travail, repos quotidien et dominical"
"Questions - Réponses : Adaptation de l’activité, congés, mise à disposition" par 
"Questions - Réponses : adaptation de l’activité, congés, mise à disposition"

- [x] Dans la rubrique "Focus métier secteur" : 
enlever les liens suivants "Transports, logistique (bis)" et "BTP, construction, matériaux" et Remplacer "Nouveautés coronavirus : Assistant(e) maternel(le)" par 
"Nouveautés Covid-19 : assistant(e) maternel(le)"

- [x] Dans la rubrique "Arrêt maladie et garde d'enfant" : 
remplacer "Questions - Réponses : Garde d’enfants et personnes vulnérables" par "Questions - Réponses : garde d’enfants et personnes vulnérables".
et Supprimer les 2 liens suivants : 
- Demander un arrêt de travail pour vos salariés contraints de garder leur enfant à domicile
- et Modèle attestation sur l’honneur : arrêt de travail pour la garde d’enfant

- [x] Dans la rubrique "Formation professionelle" : aucun des liens ne fonctionnent. Rappel des liens ci-dessous à intégrer : 
1. Conventions de FNE-Formation : https://code.travail.gouv.fr/fiche-ministere-travail/conventions-de-fne-formation
2. Questions - Réponses : Formation professionnelle stagiaire : https://code.travail.gouv.fr/fiche-ministere-travail/formation-professionnelle-stagiaires-et-organismes-de-formation
3. Questions - Réponses : Apprentissage : https://code.travail.gouv.fr/fiche-ministere-travail/apprentissage-apprentis-et-organismes-de-formation-cfa
4. Formation professionnelle des salariés en activité partielle : https://code.travail.gouv.fr/fiche-ministere

- [x] Dans la rubrique "CSE et accord collectif" : changer le nom du lien "FAQ - dialogue social" par "Questions-réponses : dialogue social" + ajout du lien de l'onglet lié à l'issue #2705 

- [x] Dans la rubrique "Chômage" changer le nom "FAQ - Indemnisation chômage" par "Questions-réponses : indemnisation chômage".

**Comment by virginielastisneres** [comment]
Pour l'UI ICI

- [x] Dans la rubrique les contenus populaires : enlever le "voir plus" et afficher les 6 résultats proposés

- [x] Ajout encart pour contenus populaires. Le haut de l'encart doit être aligné horizontalement avec le mot "sommaire"

- [x] Aligner les boutons "afficher tout" à gauche et non au centre

- [x] Taille des H2 : dans le design system de cécile les H2 sont en 26px. Là ils sont en 28. Il faudrait les mettre en 26px, à moins que tous nos H2 sur le site ont été passés en 28 ? _<- Oui c'est 28 partout sur le site_

- [x] Réduire la taille des icônes => mettre le meme height que pour le titre associé pour avoir une harmonie soit 33 px après ajustement de la taille des titres (26px) ou 35px si la taille reste 28px.

- [x] Réajuster les espaces entre les icones et le titre de la rubrique. C'est trop espacé. Il faudrait un margin de 8px ou 16px à droite 

- [x] Réajuster les espaces le titre de la rubrique et le contenu, margin de 24px et pas 20px. 

- [x] changer l'icône de la rubrique "CSE et accord collectif" ce n'est pas le bon : cf. Figma

- [x] Limiter les liens sur 2 lignes et non 3 ? _<- Ca malheureusement ce n'est pas possible !_

**Comment by June-law** [comment]
Après avoir cliqué sur "Quelles mesures l'employeur doit-il prendre pour protéger..." , sur la page qui s'ouvre les images sont illisibles  
https://04c7590-code-travail.dev.fabrique.social.gouv.fr/fiche-ministere-travail/quelles-mesures-lemployeur-doit-il-prendre-pour-proteger-la-sante-de-ses-salaries

**Comment by June-law** [comment]
Dans la partie "Formation professionnelle et apprentissage", serait-il possible de donner des noms aux fiches sans les signes /  et - , et d'avoir un nom de document classique ? Exemple : au lieu de "/fiche-ministere-travail/conventions-de-fne-formation", on aurait "Fiche Ministère travail conventions de FNE formation"

**Comment by June-law** [comment]
On parle de "FAQ" à certains endroits et de "Questions-réponses" à d'autres. On pourrait harmoniser et avoir une seule appellation ?

**Comment by virginielastisneres** [comment]
> Dans la partie "Formation professionnelle et apprentissage", serait-il possible de donner des noms aux fiches sans les signes / et - , et d'avoir un nom de document classique ? Exemple : au lieu de "/fiche-ministere-travail/conventions-de-fne-formation", on aurait "Fiche Ministère travail conventions de FNE formation"

oui toute à fait je pense qu'il y a une erreur dans le nom du fait des urls qui sont pas bonnes. Normalement on devrait avoir : 
Conventions de FNE-Formation : https://code.travail.gouv.fr/fiche-ministere-travail/conventions-de-fne-formation
Questions - Réponses : Formation professionnelle stagiaire : https://code.travail.gouv.fr/fiche-ministere-travail/formation-professionnelle-stagiaires-et-organismes-de-formation
Questions - Réponses : Apprentissage : https://code.travail.gouv.fr/fiche-ministere-travail/apprentissage-apprentis-et-organismes-de-formation-cfa
Formation professionnelle des salariés en activité partielle : https://code.travail.gouv.fr/fiche-ministere

**Comment by virginielastisneres** [comment]
> On parle de "FAQ" à certains endroits et de "Questions-réponses" à d'autres. On pourrait harmoniser et avoir une seule appellation ?

Oui tu as raison

**Comment by June-law** [comment]
Je n'ai pas compris ce qui a été décidé au final pour le texte relatif à l'ordonnance sur la durée du travail. On le garde ou pas ? (sachant que la mesure n'est pas applicable et ne le sera jamais) Si on le supprime du dossier, il faudrait modifier le titre de la partie "Congés payés, durée du travail et primes" en supprimant les mots "durée du travail".

**Comment by June-law** [comment]
Concernant ce titre "Mesures de prévention dans l’entreprise contre le COVID-19 - Masques", est-il possible de supprimer le mot "Masques" ? (en demandant peut-être aux rédacteurs du fichier source ?) Quand on ouvre le doc, on voit bien qu'il traite de plusieurs mesures et pas seulement des maques. Avoir ce mot dans le titre induit en erreur le lecteur.

**Comment by virginielastisneres** [comment]
> Concernant ce titre "Mesures de prévention dans l’entreprise contre le COVID-19 - Masques", est-il possible de supprimer le mot "Masques" ? (en demandant peut-être aux rédacteurs du fichier source ?) Quand on ouvre le doc, on voit bien qu'il traite de plusieurs mesures et pas seulement des maques. Avoir ce mot dans le titre induit en erreur le lecteur.

**Comment by virginielastisneres** [comment]
oups fausse manip j'ai clôturé sans faire exprès

**Comment by June-law** [comment]
Dans les contenus populaires, il y a une flèche vers "Nouveautés covid-19 : congés payés" qui ouvre sur une page avec l'infographie sur les CP, mais la page s'appelle cette fois "Nouveautés covid-19". (Ce n'est pas le même titre que la flèche.) Mais dans la partie "Congés payés, durée du travail et prime", la flèche pointe vers "Nouveautés coronavirus : Congés payés". Outre l'erreur 500 déjà repérée, c'est étrange de ne pas avoir le même titre dans les deux parties. Entre les mots "covid-19" et "coronavirus" et la majuscule après le ":", il faudrait harmoniser.

**Comment by June-law** [comment]
De façon générale, dans les titres, après un " : " , il y a parfois une majuscule et d'autres fois une minuscule. Ce serait bien d'harmoniser.

**Comment by June-law** [comment]
Dans le titre "Questions - Réponses : Embauche démission sanctions licenciement", il manque les virgules après "embauche", "démission" et "sanctions".

**Comment by virginielastisneres** [comment]
> Je n'ai pas compris ce qui a été décidé au final pour le texte relatif à l'ordonnance sur la durée du travail. On le garde ou pas ? (sachant que la mesure n'est pas applicable et ne le sera jamais) Si on le supprime du dossier, il faudrait modifier le titre de la partie "Congés payés, durée du travail et primes" en supprimant les mots "durée du travail".

De ce que j'ai compris Catherine veut que l'on garde la partie sur la durée du travail

**Comment by virginielastisneres** [comment]
> Dans le titre "Questions - Réponses : Embauche démission sanctions licenciement", il manque les virgules après "embauche", "démission" et "sanctions".

oui bonne remarque j'harmonise tout ca

**Comment by UnbearableBear** [comment]
N.B. le temps que cette issue là soit résolue https://github.com/SocialGouv/code-du-travail-numerique/issues/2704, on pourrait décider d'enelever le lien qui pointe vers la page `fiche-ministere-travail/quelles-mesures-lemployeur-doit-il-prendre-pour-proteger-la-sante-de-ses-salaries`

**Comment by virginielastisneres** [comment]
> N.B. le temps que cette issue là soit résolue #2704, on pourrait décider d'enelever le lien qui point vers la page `fiche-ministere-travail/quelles-mesures-lemployeur-doit-il-prendre-pour-proteger-la-sante-de-ses-salaries`

Hum à voir car j'ai l'impression que c'était un lien important pour la com surtout en ce moment. Il y a toujours l'accès au pdf.

**Comment by virginielastisneres** [comment]
> > N.B. le temps que cette issue là soit résolue #2704, on pourrait décider d'enelever le lien qui point vers la page `fiche-ministere-travail/quelles-mesures-lemployeur-doit-il-prendre-pour-proteger-la-sante-de-ses-salaries`
> 
> Hum à voir car j'ai l'impression que c'était un lien important pour la com surtout en ce moment. Il y a toujours l'accès au pdf. Le pdf a été téléchargé presque 1000 fois depuis le 15 avril, c'est le 3ème pdf le plus téléchargé du site donc il intéresse, à mon sens, il vaut mieux garder la page. pas grave si l'image est horrible car elle arrive après le lien pdf. De plus si tu cliques (plutot pratique mobile) sur l'image horrible ahah ca te télécharge le pdf (meme si je suis pas fan de cette pratique)

**Comment by June-law** [comment]
Le titre de la page énonce "Ministère du travail : notre dossier sur le coronavirus. L’essentiel à savoir sur le Coronavirus ..." Le mot "coronavirus" est écrit une fois en minuscule, puis en majuscule. Il faudrait harmoniser et que ce soit la même écriture avec le reste du dossier.
