### ISSUE TITLE
Supprimer du site le modèle attestation garde d'enfant 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2707]
Le modèle suivant doit etre supprimé du site car il n'est plus valable juridiquement : https://code.travail.gouv.fr/modeles-de-courriers/attestation-sur-lhonneur-arret-de-travail-pour-la-garde-denfant

**Comment by UnbearableBear** [comment]
clsoed with https://github.com/SocialGouv/code-du-travail-numerique/pull/2691
