### ISSUE TITLE
TeleRC plante à chaque soumission 

### ISSUE THREAD

**Issue by iclems** [SocialGouv/code-du-travail-numerique#2708]
**Description**
Le site TeleRC plante à chaque soumission. Impossible de soumettre avec erreur : 
<img width="954" alt="Screen Shot 2020-05-07 at 7 05 18 PM" src="https://user-images.githubusercontent.com/1120050/81323718-1466d880-9096-11ea-8588-bfc33e8c8ba1.png">

**Reproduction**
Etapes à suivre pour reproduire le bug
1. Go to 'https://www.telerc.travail.gouv.fr/RuptureConventionnellePortailPublic/jsp/site/Portal.jsp?'
2. Click on 'Saisir une demande'
3. Save

**Comportement attendu**
_optionnel_ Si nécessaire, explications du comportement attendu

**Screenshots**
_optionnel_ Si nécessaire, ajoutez ici une capture d'écran du problème

**Configuration**
_optionnel_ Si nécessaire, ajoutez le navigateur sur lequel vous avez repéré le problème
  - Device: _ex: iPhone_
  - Navigateur: _ex: Chrome_
  - Version du navigateur : _ex: 74.0.3729.169_

**Checklist**
Vérifiez que les éléments suivants ont été faits et effacez cette section :
  - la tâche est compréhensible simplement par toute l'équipe
  - la tâche n'existe pas déjà
  - les bons tags ont été ajoutés

**Comment by UnbearableBear** [comment]
Bonjour ! Merci d'avoir remonté l'information ! Malheureusement notre équipe ne s'occupe pas / n'a pas acces au code de TeleRC mais nous pouvons surement leur remonter l'information si celle-ci est toujours d'actualité. @jrduscher tu sais qui gère cet outil ?
