### ISSUE TITLE
Issues sentry à traiter

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#2728]
- [x] https://sentry.fabrique.social.gouv.fr/incubateur/code-du-travail-numerique/issues/4606/ -> pb avec le decodage d'emails des fiches SP sous ie11

------------------------------

- [x] https://sentry.fabrique.social.gouv.fr/incubateur/code-du-travail-numerique/issues/4944/ -> un probleme avec un filtrage sur une valeur undefined dans le nouveau dossier ???

Résolu (pas d'action necessaire): le problème est probablement simplement du à des utilisateurs avec l'ancien dossier mais la nouvelle data (l'issue ne semble plus se produire d'ailleurs) https://github.com/SocialGouv/code-du-travail-numerique/blob/e1fd6c5f86a10d13cc8e0f1142b447f349504a08/packages/code-du-travail-frontend/pages/dossiers/%5Bslug%5D.js ( `ref.filter` avec `ref` à `undefined`)

**Comment by lionelB** [comment]
> https://sentry.fabrique.social.gouv.fr/incubateur/code-du-travail-numerique/issues/4606/ -> pb avec le décodage d'emails des fiches SP sous ie11

il faudrait transpiler le module car il utilise des template string
