### ISSUE TITLE
memory leak sur le front

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#2746]
memory leak
- apparition 29Avril 
la release https://github.com/SocialGouv/code-du-travail-numerique/compare/v4.17.0...v4.18.0
est la derniere avant l'apparition des alertes

**Comment by UnbearableBear** [comment]
Ce n'était pas juste une histoire de pod qui ne scalaient pas correctement ?

**Comment by lionelB** [comment]
non la conso mémoire a changé et le pod est régulierement rebooté

**Comment by lionelB** [comment]
Apres augmentation de la meeoire allouée au container, il semblerait que ce ne soit pas un memory leak mais juste la conso de l'application qui a augmenté. Cela dit, @UnbearableBear @revolunet on identifié un probleme sur les fiche mt qui pourrait etre la cause de cette augmentation. un changement dans le package @socialgouv/fiche-travail-data à introduit le chargement de 12Mo de json dans le bundle de cette page -___-'  

action corrective : monitorerles tailles des bundle js
