### ISSUE TITLE
ERREUR 404 fiche télétravail dans le dossier... 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2747]
Dans le dossier Coronavirus (https://code.travail.gouv.fr/dossiers/ministere-du-travail-notre-dossier-sur-le-coronavirus), le lien "Questions - Réponses : télétravail" est pas bon, erreur 404 =>> https://code.travail.gouv.fr/fiche-ministere-travail/fiche-ministere-travail/teletravail

Il est :  
- le 1er lien dans les contenus populaires : 
- et le 1er lien dans la rubrique "Contrat de travail (embauche, télétravail, rupture…)"

A mon avis c'est parce qu'il y a dans l'url 2 fois /fiche-ministere-travail/. 

L'url doit être modifiée aux 2 endroits par https://code.travail.gouv.fr/fiche-ministere-travail/teletravail.

**Comment by UnbearableBear** [comment]
🤦
