### ISSUE TITLE
cas de hors sujet

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#275]
https://codedutravail-dev.num.social.gouv.fr/?q=d%C3%A9mission%20cdi%20ch%C3%B4mage

le premier résultat ne devrait pas sortir, ici et encore moins en tête. 
La requête porte sur la démission , pas sur l’homologation de la Rupture conventionnelle ,qui vient en tête des résultats.
https://codedutravail-dev.num.social.gouv.fr/fiche-ministere-travail/la-rupture-conventionnelle-du-contrat-de-travail-a-duree-indeterminee-en-quoi-consiste-lhomologation-de-la-convention?q=d%C3%A9mission%20cdi%20ch%C3%B4mage&search=0#En-quoi-consiste-l-homologation-de-la-convention

autre résultat déceptif dans la liste: https://codedutravail-dev.num.social.gouv.fr/fiche-service-public/quest-ce-quun-cdd-dinsertion-cddi?q=d%C3%A9mission%20cdi%20ch%C3%B4mage&search=0
au delà du top 5 les autres résultats sont hs

**Comment by ClementChapalain** [comment]
encore un cas de test unitaire, est-ce qu'il est référencé dans le tableau excel ? si oui on ferme cette tâche je pense

**Comment by lionelB** [comment]
suite aux changement apporté dans ES les réponses ont changées.
 @jrduscher est ce que tu peux vérifier si c'est ok pour toi ?

**Comment by ClementChapalain** [comment]
tests unitaires gérés via le data filler désormais
