### ISSUE TITLE
outils - amélioration de l'affichage des formules

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#2753]

**Comment by virginielastisneres** [comment]
on peut fermer l'issue @UnbearableBear ?

**Comment by UnbearableBear** [comment]
@virginielastisneres not yet, linked to this issue https://github.com/SocialGouv/code-du-travail-numerique/pull/2752

**Comment by virginielastisneres** [comment]
Toujours pas possible de clôturer cette issue @UnbearableBear ?

**Comment by UnbearableBear** [comment]
bientôt j'espère

**Comment by virginielastisneres** [comment]
> bientôt j'espère

d'acc 👍
