### ISSUE TITLE
Datafiller - mise à jour de sources. traitement des réf erronées

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#2755]
via Datafiller errors,
Exemple: requête "Absence-contrat de travail", fiche MT le contrat  doit il être ecrit"
Les références signalées, encadrés rouge, pointent vers des url qui fonctionnent. Le fait de retrouver la fiche dans la suggestion remplace l'url par la même url: le remplacement ne se fait pas, l'url reste considéré comme erronée.
Il devient donc compliqué de faire le tri des réf hs de celles qui ne le sont pas.

Il faudrait:
1 comprendre pourquoi les réf sont signalées comme erronées
2 pouvoir au remplacement de l'url par elle même, supprimer l'alerte

**Comment by revolunet** [comment]
fixed, je te laisse close si ok

**Comment by virginielastisneres** [comment]
@jrduscher c'est bon non maintenant le datafiller ? Julien peut clôturer ?
