### ISSUE TITLE
Affichage de la page résultat (améliorations)

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#276]
- [x] ajouter les pictogrames selon le type de contenus: https://trello-attachments.s3.amazonaws.com/5a39344bf34cad983b377287/5bcf339fb2bb3c455d10e4ee/f21767f97533dcfd96c1cf054951bed0/Icones.png https://trello.com/c/PJcXi3JN/308-diff%C3%A9rencier-les-contenus-officiels-avec-des-picto

- [x] ajouter la date de dernière mise à jour ou publication https://trello.com/c/Op1gpWss/303-ajouter-la-date-dans-la-page-r%C3%A9sultat-pour-les-faq
- [x] ajouter le type de contenus 
- [x] s'assurer que ces éléments fonctionnent aussi sur la FAQ.

**Comment by lionelB** [comment]
closed by #262 
date: 
- fiche sp #268,  
- fiche min #288 
- code_du_travail #347 
- autres #218
