### ISSUE TITLE
Nouvelle page "Prescription d’arrêts du travail par le médecin du travail : nouveautés Covid-19"

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2763]
## CONTEXTE 

Suite à la validation de la DGT nous avons un nouveau contenu concernant le Covid-19 à intégrer au cdtn concernant la prescription d’arrêts du travail par le médecin du travail. 

## SOLUTION

L'intégration se fait via une page dédiée. Cela ne peut se faire que suite au travail du découpage de la page Nouveautés Covid-19 en plusieurs pages différentes. Cela est une autre page Nouveautés Covid-19. 

**- Nom de la page :** Prescription d’arrêts du travail par le médecin du travail : nouveautés Covid-19 

**- Contenu de la page :** https://docs.google.com/document/d/1ZDSXZeOPNEyIgE59QjnUddp6sVqPzkAjA-i4APGOZUA/edit

**- Ajouter un lien dans le dossier Coronavirus** dans la rubrique "santé et sécurité au travail" en 5ème place. 
Le nom du lien est le nom de la page soit "Nouveautés Covid-19 : prescription d’arrêts du travail par le médecin du travail"

**Comment by lionelB** [comment]
closed by #2777
