### ISSUE TITLE
Nouvelle page "Elections du CSE : nouveautés Covid-19"

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2764]
## CONTEXTE
Suite à la validation de la DGT nous avons un nouveau contenu concernant le Covid-19 à intégrer au cdtn concernant les élections du CSE.

## SOLUTION

L'intégration se fait via une page dédiée. Cela ne peut se faire que suite au travail du découpage de la page Nouveautés Covid-19 en plusieurs pages différentes. Cela est une autre page Nouveautés Covid-19.

**Nom de la page :** 
"Elections du CSE : nouveautés Covid-19" Ca serait bien d'avoir un accent sur le E de élections. 

**Structure de la page :** 
-	Phrase introductive : "Les élections de CSE sont suspendues à compter du 12 mars 2020 et jusqu’au 31 août inclus." 
-	Accordéon : Cas des élections qui n’ont pas encore commencé 
-	Accordéon : Cas des procédures électorales qui ont déjà commencé 
-	Accordéon : La prolongation de certains mandats de représentants du personnel 
-	Accordéon : La prolongation de la protection de candidats aux élections du CSE 
-	Accordéon : Les élections partielles du CSE 

**Contenu des accordéons** 
Tout le contenu est ici =>> https://docs.google.com/document/d/1uIWXTILZBeBJA9pY4S5I6Cob0GCi0QG1MK_ONWI2Bqo/edit

**Lien de la page** dans le dossier Coronavirus à la rubrique "CSE et accord collectif" en dernière position.

**Comment by UnbearableBear** [comment]
@virginielastisneres Ca va si il n'y a pas d'accordéon dans un premier temps ? Je n'ai pas prévu ça pour le moment encore :o
p.s. j'ai le word est en privé, il me faut les accès

**Comment by virginielastisneres** [comment]
> @virginielastisneres Ca va si il n'y a pas d'accordéon dans un premier temps ? Je n'ai pas prévu ça pour le moment encore :o
> p.s. j'ai le word est en privé, il me faut les accès

@UnbearableBear C'est pas trop gênant pour celui ci de ne pas avoir d'accordéon, ca sera pour les réunions du CSE ou il faudra regarder ce que cela donne sans accordéon... 
Normalement c'est bon tu as accès maintenant  :)

**Comment by lionelB** [comment]
closed by #2777
