### ISSUE TITLE
Nouvelle page : "Réunions du CSE : nouveautés Covid-19"

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2765]
CONTEXTE
Suite à la validation de la DGT nous avons un nouveau contenu concernant le Covid-19 à intégrer au cdtn concernant les réunions du CSE.

SOLUTION

L'intégration se fait via une page dédiée. Cela ne peut se faire que suite au travail du découpage de la page Nouveautés Covid-19 en plusieurs pages différentes. Cela est une autre page Nouveautés Covid-19.

**Nom de la page :**
"Réunions du CSE : nouveautés Covid-19" 

**Structure et contenu de la page (page avec infographies) :**

Accordéon : Synthèse
- infographie en png synthèse réunions du CSE à retrouver ici =>> https://www.figma.com/file/f6Bzbk5x45DfqNgovU0XLV/RTT?node-id=167%3A1594
![Infographie synthèse réunion du CSE (2)](https://user-images.githubusercontent.com/48682104/83010695-f21f0580-a018-11ea-852f-2f5c74b8997a.png)

- texte associé  => https://docs.google.com/document/d/1ysXR2x9ALzgfB8HmeZpEotqcbBPe9KSqkndV3AvC8IQ/edit

Accordéon : Réunir le CSE par visioconférence
- infographie en png la visioconférence à retrouver ici =>> https://www.figma.com/file/f6Bzbk5x45DfqNgovU0XLV/RTT?node-id=167%3A1594
![Infographie réunion du CSE la visioconférence](https://user-images.githubusercontent.com/48682104/83010590-c7cd4800-a018-11ea-83e2-d4014429a9f2.png)

- texte associé  => https://docs.google.com/document/d/1ysXR2x9ALzgfB8HmeZpEotqcbBPe9KSqkndV3AvC8IQ/edit

Accordéon : Réunir le CSE par conférence téléphonique
- infographie en png synthèse la conférence téléphonique à retrouver ici =>> https://www.figma.com/file/f6Bzbk5x45DfqNgovU0XLV/RTT?node-id=167%3A1594
![Infographie réunion du CSE la conférence téléphonique](https://user-images.githubusercontent.com/48682104/83010622-d4ea3700-a018-11ea-91bd-72687632ab5e.png)

- texte associé  => https://docs.google.com/document/d/1ysXR2x9ALzgfB8HmeZpEotqcbBPe9KSqkndV3AvC8IQ/edit

Accordéon : Réunir le CSE par messagerie instantanée
- infographie en png la messagerie instantanée à retrouver ici =>> https://www.figma.com/file/f6Bzbk5x45DfqNgovU0XLV/RTT?node-id=167%3A1594
![Infographie réunion du CSE la messagerie instantanée](https://user-images.githubusercontent.com/48682104/83010658-df0c3580-a018-11ea-81b1-e32ac0d64f24.png)

- texte associé  => https://docs.google.com/document/d/1ysXR2x9ALzgfB8HmeZpEotqcbBPe9KSqkndV3AvC8IQ/edit

**Télécharger les infographies** 
Les infographies sont téléchargeables et la version téléchargeable des infographies est différente à retrouver ici dans version imprimable =>> https://www.figma.com/file/f6Bzbk5x45DfqNgovU0XLV/RTT?node-id=167%3A1594
[1. Infographie synthèse réunions du cse.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/4688011/1.Infographie.synthese.reunions.du.cse.pdf)
[2. Infographie la visioconférence.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/4688013/2.Infographie.la.visioconference.pdf)
[3. Infographie la conférence téléphonique.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/4688015/3.Infographie.la.conference.telephonique.pdf)
[4. Infographie la messagerie instantanée.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/4688016/4.Infographie.la.messagerie.instantanee.pdf)

**Lien de la page dans le dossier** Coronavirus à la rubrique "CSE et accord collectif" en dernière position.

**Comment by lionelB** [comment]
closed by #2777
