### ISSUE TITLE
Harmoniser les routes de l'api

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#2767]
Actuellement dans l'api nous avons souvent deux manières de faire la même chose, il faudrait choisir entre l'une, ou l'autre et s'y tenir:

![Screenshot 2020-05-22 at 10 50 01](https://user-images.githubusercontent.com/705453/82649782-07132780-9c1a-11ea-8825-9217dd39aabb.png)
![Screenshot 2020-05-22 at 10 49 38](https://user-images.githubusercontent.com/705453/82649790-08445480-9c1a-11ea-9f64-208fa55e6425.png)

On a le choix entre une route generique qui a toujours la même signature
ou bien des routes personnalisées avec beaucoup de duplication de code

cela concerne notamment (liste non exhaustive: les dossiers, les fiches MT, les modeles)

**Comment by lionelB** [comment]
Attention a ce que la solution ne se resume pas à mettre des if dans la la routes items pour traiter chaque cas particulier, ce qui serait pas une meilleure solution de mon point de vue

**Comment by romain-b13** [comment]
@m-maillot ton avis sur cette issue ?

**Comment by m-maillot** [comment]
on a basculer l'API dans nextjs et revue la structure un peu. On peut cloturer.
