### ISSUE TITLE
Page Information et consultation du CSE : nouveautés Covid-19 ajout infographie

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2768]
### CONTEXTE
Suite à la validation de la DGT d'une infographie concernant les délais de consultation du CSE nous avons à l'intégrer au sein de la page Nouveautés Covid-19 : information et consultation du CSE.  Cette page s'appelait avant délais de consultation du CSE. 
Attention cela nécessite quelques changements.

### SOLUTION

Structure de la page : 

**Paragraphe introductif (texte déjà présent dans la page) :** "Afin de favoriser la reprise rapide de l’activité économique dans des conditions protectrices pour les salariés, une ordonnance et deux décrets du 2 mai 2020 ont adaptés la durée des délais d’envoi de l’ordre du jour, de consultation et d’expertise du CSE pour certaines réunions. Du 3 mai au 23 août 2020, l’entreprise appliquera les délais définis par ces textes et non les délais fixés par le code du travail, par un accord collectif ou un accord conclu avec le CSE."

**Sous partie : Synthèse (avec les infographies)**
Ajouter les infographies suivantes dans cet ordre à retrouver ici sous "version définitive web" =>>> https://www.figma.com/file/f6Bzbk5x45DfqNgovU0XLV/RTT?node-id=256%3A2011
- Délais de consultation du CSE
![Infographie consultation du CSE](https://user-images.githubusercontent.com/48682104/83018596-e128c100-a025-11ea-9e30-78ce2dc7041c.png)

- Délais de consultation du CSE central
![Infographie consultation du CSE central](https://user-images.githubusercontent.com/48682104/83018701-fdc4f900-a025-11ea-872f-aa2f7c85dd69.png)

- Délais de consultation du CSE central avec CSE d'établissements 
![Infographie consultation du CSE central + établissements](https://user-images.githubusercontent.com/48682104/83018706-00bfe980-a026-11ea-94f0-59729d623b7b.png)

- Contester une expertise
![Infographie contester une expertise](https://user-images.githubusercontent.com/48682104/83018715-061d3400-a026-11ea-8004-dc5189397625.png)

Ces infographies sont téléchargeables. A télécharger la version "version définitive imprimable"
[Infographie consultation du CSE.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/4688151/Infographie.consultation.du.CSE.pdf)
[Infographie consultation du CSE central.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/4688152/Infographie.consultation.du.CSE.central.pdf)
[Infographie consultation du CSE central + établissements.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/4688153/Infographie.consultation.du.CSE.central.%2B.etablissements.pdf)
[Infographie contester une expertise.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/4688155/Infographie.contester.une.expertise.pdf)

**Sous partie : Réunions pour lesquelles les conditions de fonctionnement sont adaptées**
Tout le texte reste celui déjà présent. 

**Sous partie : Délai d’envoi de l’ordre du jour**
Tout le texte reste celui déjà présent. 

**Sous partie : Délai de consultation du CSE**
Tout le texte reste celui déjà présent. 

**Sous partie : Délai d’expertise**
Tout le texte reste celui déjà présent.

**Comment by lionelB** [comment]
closed by #2777
