### ISSUE TITLE
`excludeFromSearch` should default to false

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#2770]
For one edge case, we must add a prop to all other cases, this should be the contrary

**Comment by lionelB** [comment]
not totally a edge case since the name was chose for later use to unpublish content.

**Comment by romain-b13** [comment]
@m-maillot ton avis sur cette issue ?

**Comment by m-maillot** [comment]
on va revoir cette partie de l'admin mais actuellement ce n'est pas un problème.
