### ISSUE TITLE
Amélioration outil HRE

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2808]
Suite à la relecture de nadia, j-r et florent de l'outil d'heures pour recherche d'emploi des améliorations sont souhaitées. Il est préférable par soucis de clarté de regrouper ces changements dans une issue dédiée plutôt que dans la PR #2773. 

## Schéma de l'outil HRE
![Illustration_sans_titre (3)](https://user-images.githubusercontent.com/48682104/84136765-0a951400-aa4c-11ea-889f-c455827fafa9.png)

## Données l'outil HRE

Les données sont à retrouver ici =>> https://docs.google.com/spreadsheets/d/1zd_hShEui8BHK0349GpDUZRkCcQ9syIZ9gSrkYKRdo0/edit#gid=227376301

## Modifications wording étape "Introduction"

**Changement du texte comme suit :** 
"Ce simulateur vous permet de savoir si le salarié peut bénéficier d’heures d'absence autorisée pendant son préavis pour rechercher un emploi. Il peut s'agir du préavis en cas de licenciement, de démission ou de rupture de la période d'essai.
Le code du travail ne prévoit pas ce droit (sauf cas particulier du droit applicable à l'Alsace Moselle). En revanche, plusieurs conventions collectives fixent un nombre d’heures d’absence autorisée pour rechercher un emploi et les conditions d’utilisation.
Afin de réaliser cette simulation, vous aurez besoin de connaître la convention collective applicable et, dans certains cas, des informations sur le salarié, comme sa catégorie professionnelle ou son ancienneté. La plupart de ces informations se trouvent sur le contrat de travail ou le bulletin de salaire. Prévoyez 2 à 5 minutes pour cette simulation.
Cliquez sur Commencer pour démarrer la simulation."

## Modifications nombre d'étapes 

Actuellement nous avons 4 étapes qui sont réparties comme suit dans le tableau : 
- étape Introduction : aucune colonne correspondante dans le data_simulateur
- étape Convention collective : colonnes en rose B et C (IDCC et CC) 
- étape Informations du salariés : colonnes en bleu de D jusqu'à X 
- étape Résultat : colonnes en vertes de Y à AC. 

Nous avons modifié le data_simulateur afin de rajouter une étape appelée "Type de rupture du contrat de travail".

Ainsi nous aurons 5 étapes réparties comme suit dans le tableau : 

- étape Introduction : aucune colonne correspondante dans le data_simulateur
- étape Convention collective : colonnes en rose B et C (IDCC et CC) 
- [nouveau] étape Type de rupture du contrat de travail : colonne F (cf. partie ci-dessous pour le contenu de cette nouvelle étape)
- étape Informations du salariés : colonnes G jusqu'à Z
- étape Résultat : colonnes en vertes de AA à AE. 

## Page de l'étape "Type de rupture du contrat de travail"

Nom de l'étape : Type de rupture du contrat de travail

Question posée à l'utilisateur : "Comment le contrat de travail a-t-il été rompu ?" 
Normalement la question est à jour avec la mise à jour du tableau excel. A vérifier juste ce point. 

Réponses possibles : cf excel data_simulateur ici https://docs.google.com/spreadsheets/d/1zd_hShEui8BHK0349GpDUZRkCcQ9syIZ9gSrkYKRdo0/edit#gid=227376301 colonne F. 
A afficher dans cet ordre : 
- Démission
- Licenciement 
- Rupture de la période d'essai 

## Modifications wording étape "Informations"

Rappel : cette étape correspondant aux colonnes H à Z.  

- Vérifier suite à la mise à jour des données que la question  "Qui a pris l’initiative de rompre la période d’essai ? » a bien été remplacée par « Pour quelle raison le contrat de travail a-t-il été rompu ?

- Vérifier suite à la mise à jour des données que la question "Quelle est la durée du préavis (aussi appelé « délai de prévenance ») ?" a bien été remplacée par "Quelle est la durée du délai de prévenance ?"

### Page quand l'utilisateur n'a pas renseigné sa CC

Modification du texte de résultat affiché à l'utilisateur comme suit : 
"La convention collective n’a pas été renseignée.
Le code du travail ne prévoit pas le droit pour le salarié de s’absenter pendant son préavis pour pouvoir rechercher un nouvel emploi. Il existe une exception dans les départements de la Moselle, du Bas-Rhin et du Haut-Rhin où le salarié, qui en fait la demande, a droit à un délai raisonnable pour rechercher un emploi pendant son préavis de licenciement (article L. 1234-17 du code du travail)." 

Modification du texte du bloc sur la hiérarchie des normes comme suit : 
"Un accord d’entreprise ou à défaut un usage dans la profession ou l’entreprise peut prévoir que le salarié bénéficie d’heures d’absence autorisée pour rechercher un emploi pendant le préavis. Il peut s’agir du préavis en cas de rupture de la période d’essai, de démission ou de licenciement."

### Page quand l'utilisateur a remplit sa CC et que sa CC prévoit des heures pour recherche d'emploi

**1. La page se présente en 5 sous parties comme suit :**  
![image](https://user-images.githubusercontent.com/48682104/84294576-aa849780-ab49-11ea-8230-9f3b3396cae6.png)
- remplacer "Nombre d’heures" par "Nombre d’heures d’absence autorisée pour rechercher un emploi"
- remplacer "Rémunération" par "Rémunération pendant les heures d’absence autorisée"
- remplacer "Modalités d'utilisation" par "Conditions d’utilisation"
- remplacer "Détails" par "Récapitulatif des éléments saisis"

**2. Dans la partie "Nombre d’heures d’absence autorisée pour rechercher un emploi" :**
- Quand l'usager a choisi l'option "Rupture de la période d'essai", le texte qui s'affiche est remplacé ainsi : "D’après les éléments saisis, durant son préavis (ou délai de prévenance), le salarié peut s’absenter pour rechercher un emploi pendant" + données du tableau excel. 
- Quand l'usager a choisi les options "Démission" ou "Licenciement", le texte qui s'affiche est remplacé ainsi : "D’après les éléments saisis, durant son préavis, le salarié peut s’absenter pour rechercher un emploi pendant" 

**3. Dans la partie "Récapitulatif des éléments saisis"** 
- remplacer "Type de rupture" par "Type de rupture du contrat de travail" 
- bien rajouter l'information "Initiative de la rupture : initiative de l’employeur / du salarié" quand la donnée est demandée. 
- attention rappel changement du texte "Catégorie professionnelle du salarié" qui remplace "Catégorie socio-professionnelle".

**4. Pour le bloc sur la hiérarchie des normes qui est en fond bleu clair.** 
Il faut changer le texte également. Voici le nouveau texte à mettre : 
"Si un accord d’entreprise ou à défaut un usage dans la profession ou l’entreprise plus récent prévoit des heures d’absence autorisée pour rechercher un emploi pendant le préavis, le salarié en bénéficie si ces mesures sont plus favorables que la convention collective."

### Page quand l'utilisateur a remplit sa CC et que sa CC ne prévoit pas d'heures pour recherche d'emploi
Cas où les données des réponses (colonnes AA, AB et AC) ne sont pas complétées. 

- **Changer le texte** a affiché comme suit pour tous les cas ou la CC ne prévoit pas d'heures : "D’après les éléments saisis, dans votre situation, la convention collective ne prévoit pas d’heures d’absence autorisée pour rechercher un emploi."

- **Remplacer "Détails"** par "Récapitulatif des éléments saisis"

- **Dans la partie "Récapitulatif des éléments saisis"**** 
Remplacer "Type de rupture" par "Type de rupture du contrat de travail" 
Bien rajouter l'information "Initiative de la rupture : initiative de l’employeur / du salarié" quand la donnée est demandée. 
Attention rappel changement du texte "Catégorie professionnelle du salarié" qui remplace "Catégorie socio-professionnelle".

**Comment by lionelB** [comment]
### cas Page quand l'utilisateur n'a pas renseigné sa CC

> Modification du texte du bloc sur la hiérarchie des normes comme suit :
"Un accord d’entreprise ou à défaut un usage dans la profession ou l’entreprise peut prévoir que le salarié bénéficie d’heures d’absence autorisée pour rechercher un emploi pendant le préavis. Il peut s’agir du préavis en cas de rupture de la période d’essai, de démission ou de licenciement."

j'ai me suis permis de rajouter 
```diff
+ Une convention collective, un accord d’entreprise ou à défaut un usage 
- Un accord d’entreprise ou à défaut un usage 
```
Pour le  bloc de hierarchie des normes on distingué les cas lorsque la cc prévoyait une durée ou pas avec une petite nuance
__la cc ne prévoie rien__
> Un accord d’entreprise ou à défaut un usage dans la profession ou
        l’entreprise plus récent peut prévoir l’existence, le cadre et la durée
        des absences pour rechercher un emploi au cours du préavis.

__la cc prévoie une durée__
>  Un accord d’entreprise ou à défaut un usage dans la profession ou
        l’entreprise plus récent peut prévoir l’existence, le cadre et une durée
        **différentes des absences** pour rechercher un emploi au cours du préavis.

Est ce qu'on ne distingue plus les 2 cas 
> Si un accord d’entreprise ou à défaut un usage dans la profession ou l’entreprise plus récent prévoit des heures d’absence autorisée pour rechercher un emploi pendant le préavis, le salarié en bénéficie si ces mesures sont plus favorables que la convention collective.

**Comment by June-law** [comment]
Dans le sommaire à gauche, li faudrait modifier le nom de l'étape 5. 
Remplacer "Durée du préavis" par "Résultat"

**Comment by June-law** [comment]
Dans la page "Type de rupture du contrat de travail". 

![image](https://user-images.githubusercontent.com/52570886/85010021-a1a25000-b15f-11ea-901f-2d580e39eb10.png)


Quand on utilise l'outil pour une CC jusqu'à la page Résultat, puis qu'on veut refaire le parcours avec une autre CC, l'étape "Type de rupture du contrat de travail" a gardé l'option choisie précédemment. 
Dans la case qui permet de choisir la bonne option, on devrait revoir les 3 petits points "...".

Sur cette page, il faudrait aussi supprimer les mots "Champs obligatoires" en bas de l'outil.

**Comment by lionelB** [comment]
> Sur cette page, il faudrait aussi supprimer les mots "Champs obligatoires" en bas de l'outil.

comme c'est commun à tout les outils, je pense qu'il faudrait plutot faire un passe pour rajouter les étoiles au champ obligatoire mais on peu en rediscuter plus tard

**Comment by June-law** [comment]
> 
> 
> > Sur cette page, il faudrait aussi supprimer les mots "Champs obligatoires" en bas de l'outil.
> 
> comme c'est commun à tout les outils, je pense qu'il faudrait plutot faire un passe pour rajouter les étoiles au champ obligatoire mais on peu en rediscuter plus tard

tu peux rajouter les étoiles au champ obligatoire. C'est bon aussi. Le plus important, c'est qu'on n'ait pas les mots "Champ obligatoire" qui ne se rattachent à rien.

**Comment by June-law** [comment]
Quand la CC ne prévoit rien, il faudrait changer le paragraphe d'articulation des normes. Pour l'instant, voilà le contenu du paragraphe : 

![image](https://user-images.githubusercontent.com/52570886/85018498-8b02f580-b16d-11ea-90e1-dfcaac5902d8.png)

Il faudrait le remplacer par : "Un accord d’entreprise ou à défaut un usage dans la profession ou
l’entreprise plus récent peut prévoir l’existence, le cadre et la durée
des absences pour rechercher un emploi au cours du préavis."

Il faudrait faire la même modification pour tous les types de rupture (voir par exemple la CC Banque, rupture de la période d'essai).

**Comment by June-law** [comment]
Dans la phrase : "Cliquez sur suivant pour poursuivre la simulation.", il faudrait une majuscule au mot "suivant". Cela donnera "Cliquez sur Suivant pour poursuivre la simulation."

![image](https://user-images.githubusercontent.com/52570886/85019338-f0a3b180-b16e-11ea-8b51-e28ebed4d900.png)

si la modification concerne tous les outils, c'est bon.

**Comment by jrduscher** [comment]
### Page Introduction: Texte

#### 1) Premier paragraphe

> "Ce simulateur vous permet de savoir si le salarié peut bénéficier d’heures d’absence autorisée pendant son préavis pour rechercher un emploi. Il peut s’agir du préavis en cas de licenciement, de démission ou de rupture de la période d’essai."


**anomalies constatées**
->(orthographe) heures d’absence autorisée**s** 
-> (erreur de droit), comme dans la page résultat ajouter le délai de prévenance:

**Reformulation suggérée:**

Ce simulateur vous permet de savoir si le salarié peut s'absenter pour rechercher un emploi durant une période à la fin de son contrat de travail. 
Des heures de recherches d'emploi peuvent être autorisées en cours du préavis en cas de licenciement, de démission ou du délai de prévenance en cas de rupture de la période d’essai."

#### 2)Deuxième paragraphe

> "Afin de réaliser cette simulation, vous aurez besoin de connaître la convention collective applicable et, dans certains cas, des informations sur le salarié, comme sa catégorie professionnelle ou son ancienneté. La plupart de ces informations se trouvent sur le contrat de travail ou le bulletin de salaire. Prévoyez 2 à 5 minutes pour cette simulation.
> Cliquez sur Commencer pour démarrer la simulation."

**Suggestions**
" Prévoyez 2 à 5 minutes pour cette simulation." : Passer à la ligne cette phrase pour alléger le paragraphe.

"Cliquez sur Commencer pour démarrer la simulation" : Inutile à 2 cm du bouton, ou alors cela soulève un problème de visibilité et de fonction du bouton d'action?



### Navigation: Type de rupture

#### Pour quelle raison le contrat de travail a-t-il été rompu ?

**anomalie constatée**
(erreur de droit ou approximation juridique) Le type de rupture et la raison n'ont rien à voir. 
Le problème a été soulevé au cours de l'élaboration de l'issue. La vue en préprod confirme le problème.

**Amélioration suggérée**
Remplacer "pour quelle raison" par "Quelle est la nature" 


### Page résultat

#### a)Le nombre d'heures ne ressort pas assez du texte.
**Anomalie constatée: **

Le nombre d'heures doit arriver plus rapidement et sauter aux yeux ( la couleur de la font et le "bold" contribuent en cela, mais le rendu n'est pas propre)

** Améliorations suggérées**

**Original**
>Nombre d’heures d’absence autorisée pour rechercher un emploi
>D’après les éléments saisis, durant son préavis, le salarié peut s’absenter pour rechercher un >emploi pendant 2 heures par jour.
**Suggestion:**
Nombre d’heures autorisées 
2 heures par jour, durant le préavis ou le délai de prévenance, selon les éléments saisis.  
_Le titre heures de recherche d'emploi juste au dessus pourrait nous épargner un peu de texte superflu_ 

#### b) Erreur de droit: on ne cite encore que le préavis...**
_citer ici le délai de prévenance dans le point a) résout le point b)_

#### c) Il y a trop d'informations**

**anomalie constatée** 
 Globalement la page est trop fournie en informations.
En particulier on notera que les conditions d'utilisation constitue un pavé exhaustif, juridiquement souvent irréprochable, mais parfaitement indigeste.

** Améliorations suggérées**
- Passer en accordéon, le récapitulatif des éléments saisis et les références juridiques( garder le format actuel pour l'impression=
- revoir côté métier le texte des modalités pour aller vers uns synthèse ET/OU passer également en accordéon cette partie ( sauf à l'impression)

#### d) Orthographe :
** Attention : "Rémunération pendant les heures d’absence autorisée" Le tout au pluriel serait plus correct. (il n'y que rarement qu'une seule absence)

#### e) divers, forme
 - Le résultat dans les types de rupture est en minuscule, les autres éléments sont en majuscule.
** Améliorations suggérées**: Majuscules dans les éléments cités:
Une modification du tableau de données serait-elle suffisante?

**Comment by virginielastisneres** [comment]
Petite remarque je pense que ca rejoint la remarque de jr sur la lisibilité de la page résultat : il faudrait que le nombre d'heure soit remis à la ligne automatiquement pour une meilleure lecture pour l'usager car là on voit pas bien que l'usager a droit à 2 heures. 
![image](https://user-images.githubusercontent.com/48682104/85114159-d32b2200-b218-11ea-98d3-8214b684f738.png)

**Comment by June-law** [comment]
Quand l'outil demande à l'usager de choisir une ancienneté, il faudrait que les anciennetés soient classées de la plus petite à la plus grande. 
Par exemple, pour la CC 275, quand l'agent est payé à l'heure, l'outil pose la question. Dans ce cas, il propose en premier "au moins 1 an et demi" puis "inférieur à 1 an et demi". 
Il faudrait que ce soit l'inverse.

**Comment by jrduscher** [comment]
1) ordre ancienneté
>Quand l'outil demande à l'usager de choisir une ancienneté, il faudrait que les anciennetés soient >classées de la plus petite à la plus grande.
>Par exemple, pour la CC 275, quand l'agent est payé à l'heure, l'outil pose la question. Dans ce cas, >il propose en premier "au moins 1 an et demi" puis "inférieur à 1 an et demi".
>Il faudrait que ce soit l'inverse.

- Corrigé dans les datas


//Edit: June Law signale aussi:
2) Critère "aéroport de paris" non demandé

275: le critère aéroport de paris (colonne F dans les datas) n'est pas demandé dans le parcours et n’apparaît pas dans le récapitulatifs des éléments renseignés en fin de parcours en bas de la page résultats.

**Comment by June-law** [comment]
Quand l'usager renseigne une CC non traitée, la page Résultat devrait être changée. Il faut retirer la phrase "Vous pouvez faire une recherche par mots-clés dans votre convention collective" du paragraphe HDN et la placer juste après la phrase " la convention collective n’a pas encore été traitée par nos services."

**Comment by jrduscher** [comment]
# Dans la page "Type de rupture du contrat de travail".


1) bug dans le parcours 
Quand on utilise l'outil pour une CC jusqu'à la page Résultat, puis qu'on veut refaire le parcours avec une autre CC, l'étape "Type de rupture du contrat de travail" a gardé l'option choisie précédemment.
Dans la case qui permet de choisir la bonne option, on devrait revoir les 3 petits points "...".

Sur cette page, il faudrait aussi supprimer les mots "Champs obligatoires" en bas de l'outil.


```
3)(Ecran choix de la convention collective)
Dans la phrase : "Cliquez sur suivant pour poursuivre la simulation.", il faudrait une majuscule au mot "suivant". 

Cela donnera "Cliquez sur Suivant pour poursuivre la simulation."

```


4) Page d'introduction:
a) Ce simulateur vous permet de savoir si le salarié peut bénéficier d’heures d’absence autorisée pendant son préavis pour rechercher un emploi. Il peut s’agir du préavis en cas de licenciement, de démission ou de rupture de la période d’essai. En cas de rupture de la période d'essai, le prévais est aussi appellé délai de prévenance.

b) " Prévoyez 2 à 5 minutes pour cette simulation." : Passer à la ligne cette phrase pour alléger le paragraphe.

c)"Le code du travail ne prévoit pas ce droit (sauf cas particulier du droit applicable à l’Alsace Moselle). En revanche, plusieurs conventions collectives fixent un nombre d’heures d’absence autorisée pour rechercher un emploi et leurs conditions d’utilisation."

5) Page résultat
a)Le nombre d'heures ne ressort pas assez du texte.

**Anomalie constatée: **

Le nombre d'heures doit arriver plus rapidement et sauter aux yeux

** Améliorations suggérées**

Ajout d'un espace insécable entre la phrase "D’après les éléments saisis, durant son préavis, le salarié peut s’absenter pour rechercher un emploi pendant " et la réponse de l'outil ( le nombre doit apparaitre à la ligne )


b) Quand la CC ne prévoit rien, il faudrait changer le paragraphe d'articulation des normes. Pour l'instant, voilà le contenu du paragraphe :


Il faudrait le remplacer par : "Un accord d’entreprise ou à défaut un usage dans la profession ou
l’entreprise plus récent peut prévoir l’existence, le cadre et la durée
des absences pour rechercher un emploi au cours du préavis."

Il faudrait faire la même modification pour tous les types de rupture (voir par exemple la CC Banque, rupture de la période d'essai).


c) Quand la CC n'a pas été traitée

Quand la CC n'a pas été traitée, dans le paragraphe d'articulation des normes:
 Il faut retirer la phrase "Vous pouvez faire une recherche par mots-clés dans votre convention collective" du paragraphe HDN et la placer juste après la phrase " la convention collective n’a pas encore été traitée par nos services."
 
d) "Récapitulatif des éléments saisis"

Remplacer le critère " période d'essai" par "Initiative de la rupture de la période d'essai" (modfié dans le tableau).

e) Ajouter le numéro IDCC dans le récapitulatif des éléments saisis:
Convention collective : Entreprises de la publicité et assimilées (**IDCC**)

**Comment by June-law** [comment]
Dans la page d'introduction, il y a une faute à corriger.

Dans le premier paragraphe, la phrase "le préavis est aussi appellé délai de prévenance." doit être corrigée ainsi "le préavis est aussi **appelé** délai de prévenance."

**Comment by June-law** [comment]
Quand l'outil pose la question "Qui a pris l'initiative de rompre la période d'essai ?", il faudrait ajouter un espace entre le mot "essai" et le " ? ". 

![image](https://user-images.githubusercontent.com/52570886/86005196-9af3c280-ba14-11ea-9033-7f5e44c8290c.png)
