### ISSUE TITLE
Id unique pour chaque contenu

### ISSUE THREAD

**Issue by rmelisson** [SocialGouv/code-du-travail-numerique#2816]
S'assurer que chaque contenu dispose d'un id unique nous permettant de le référencer.
Pour le moment, on s'appuie essentiellement sur le slug qui est sujet à modification.

Certains contenus ont déjà des ids, mais ils ne sont pas forcément stockés.

- [x] faire le point pour chaque type de contenu
- [x] créer un id pour le contenus sans
- [x] créer une fonction pour standardiser les ids dans un format unique (cdt-id ?)
- [x] stocker le cdt-id dans ES et utiliser l'id dans les logs

**Comment by UnbearableBear** [comment]
Cette tache devrait précéder celle-ci https://github.com/SocialGouv/code-du-travail-numerique/issues/1482 dans l'idéal, mais pas forcément.

**Comment by lionelB** [comment]
- [x]  Fiches SP (id)
- [x]  Fiches MT (pubId)
- [x]  Contributions (id)
- [x]  Outils (id à créer)
- [x]  courrier (id à créer)
- [x]  dossiers (id à créer)
- [ ] themes (id)
- [x]  editorial-content (id à créer)
- [x] Convention collective (KALITCONT ou idcc)
- [x] articles cdt  (cid)

**Comment by rmelisson** [comment]
Est-ce que ça vous conviendrait des ids du type : `2df-7d1-9a2`

En gros on pourrait utiliser MurmurHash3 en 32 bits pour encoder l'id source : 8 octets (caractères hexadécimaux) / ~1% de chance de collision avec 10K contenus. Il existe des [implementations](https://github.com/garycourt/murmurhash-js/blob/master/murmurhash3_gc.js) pure JS de MMH-3.

Ensuite on peut préfixer l'id par son type encodé sur 4 bits (1 hex): SP = 1 / MT = 2 / ... / Article CDT = A. On peut aller jusque 16 types (F), on en a 10 pour le moment. (Et si il faut en ajouter un jour on pourra toujours rajouter 4 bits à l'id et passer à un encodage sur un octet / 2 hex.)

Ce qui nous donne un id à 9 caractères hex / 36 bits, qu'on peut split avec des dash pour ressembler à ce qu'on a au dessus. Avec l'avantage de connaitre directement le type de contenu en regardant le premier hex.

Donc en décomposant : 
`2df-7d1-9a2` => `2df7d19a2` => `2` : fiche MT / `df7d19a2` : MMH-3 de l'id de la fiche MT

On en rediscute lundi, mais voila une idée déjà.

**Comment by UnbearableBear** [comment]
Sympa ce MMH-3 ! Pas fan de rajouter des "-" si c'est juste pour faire joli
J'ai trouvé une liste des fonctions de hashage non cyrptographiques ici: https://fr.wikipedia.org/wiki/Liste_de_fonctions_de_hachage
Comment tu as fait pour avoir le % de chances de collision pour un nombre donné ? :o 1% ça me semble bcp surtout que l'on dépasser les 10K de documents je crois nous

**Comment by rmelisson** [comment]
Le "-" c'est pour rendre l'id un peu plus lisible surtout.
C'est 1% par type du coup si on ajoute un prefix pour le type, car l'encodage est par contenu. Donc 1% de chance si 10K contenus du même type.
C'est la limite si on reste sur 32bits voir :
https://stackoverflow.com/questions/14210298/probability-of-collision-when-using-a-32-bit-hash
Birthday problem : https://en.wikipedia.org/wiki/Birthday_problem#Cast_as_a_collision_problem

Le calcul ça serait la probabilité p(n; d) que deux nombres soient identiques:
- d = 2^32 = ~ 4B
- n = 10K

https://wikimedia.org/api/rest_v1/media/math/render/svg/85e10a5ef850209f4f2010865e273fc0ce51d35b

**Comment by UnbearableBear** [comment]
Stylé, merci pour les précisions, j'adorais les probas au lycée !
Donc pour un groupe de 10K d'éléments c'est à peu près la même proba que d'avoir un full au poker du premier coup; et un carré au poker du premier coup si on réduit à 3K éléments (plus proche de ce qu'on a pour des contenus du même type en ce moment).
Ok fair enough, ça se tente.

Après il y a peut-etre une autre option, l'entre deux, ce serait de passer sur du 64 bits (on passe à une proba de `0.0000000000027103` pour 10K pour un seul type) maiiis, on utiliserait que 9 des 16 charactères pour l'url, ce qui à mon avis en termes de proba serait encore en dessous de la quinte flush royale du premier coup ! Et si jamais il s'vérait que ça pose aussi problème, ce serait très facile de passer à 10 voir 11 ou 12 caractères dans l'url pour fixer ça.

**Comment by UnbearableBear** [comment]
Au passage pour l'instant on a ça:

› conventions_collectives... 385 items
› code_du_travail... 10794 items <----- + 10K
› information... 15 items
› fiches_service_public... 535 items
› fiches_ministere_travail... 1492 items
› themes... 121 items
› modeles_de_courriers... 20 items
› outils... 4 items
› external... 9 items
› contributions... 41 items
› dossiers... 1 items
› highlights... 1 items
› glossary... 1 items
› prequalified... 1 items
› page_fiche_ministere_travail... 311 items

**Comment by lionelB** [comment]
ok et pour les collisions, il suffira de tester qu'il y en ai pas :)
je partirai sur 8bit pour la source histoire d'etre tranquille (pour pouvoir avoir plus de 6 nouveaux type de contenus)
et comme le precise manu, ou pourrait augmenter la taille et utiliser 36 /  40 bits ?

**Comment by rmelisson** [comment]
- Pour confirmation : l'id dans l'URL, c'est juste pour retrouver un contenu qui aurait changé de slug en cas de lien "outdated" ? Donc en gros, on recherche toujours par slug mais si il n'existe pas on utilise l'id, voire l'id + theme.

Si c'est bien le cas, et étant donné la repartition des contenus (80% dans une seule catégorie), je pense que la solution de Manu à 64bits avec une fraction dans l'URL pourrait convenir.
Au moins on est tranquille sur la generation des ids et l'utilisation dans le back, "sans" risque de collision. Et le seul problème serait dans le cas ou la fraction dans URL entre en collision avec un autre contenu, auquel cas, on peut encore utiliser le theme.

La probabilité d'un problème serait donc :
proba de l'utilisation d'un lien outdated * proba de collision des fractions d'id dans url * proba que les 2 contenus aient le même thème

Pour rester sur un id standard (64 bits issus d'un algo de hash), je ne mettrai pas le prefix de type finalement.
Murmush hash 3 ne propose pas de 64bits, on peut utiliser Murmurhash 2 ou encore CRC64 ou FNV.

https://softwareengineering.stackexchange.com/a/145633/86761

**Comment by rmelisson** [comment]
Après réflexion et discussion avec Manu, ça serait quand même bien plus solide d'avoir un id dans sur lequel on puisse compter de l'URL aux logs en passant par le back, sans collision et sans avoir besoin de recourir au thème.
Je vais déjà mettre en place un script pour tester l'approche.

**Comment by rmelisson** [comment]
Hello there,

J'ai avancé sur le sujet, on a maintenant des ids pour tous les contenus.

Concernant le hash, j'ai utilisé xxhash, un algo récent, rapide et avec tout ce qu'il faut : https://cyan4973.github.io/xxHash/
Pour la petite histoire l'algo semble avoir été inventé par un frenchy de chez FB.
J'ai utilisé cette implem JS : https://github.com/pierrec/js-xxhash

La solution actuelle prend les 10 premiers chars de la représentation hexadécimale du hash sur 64bits. Étant donné que la fonction de hash distribue uniformément les hashs, on devrait avoir un risque de collision très faible sur 10 chars, et si besoin, il nous suffit d'ajouter un char, en conservant la même fonction de hash, et donc en conservant le lien avec ids à 10 chars.

Je fais un test de collision dans le dump lors de la génération des ids, au cas où.

Il me reste deux trois trucs à voir, et ensuite je pense qu'on pourra ouvrir d'autres issues indépendantes pour l'utilisation de l'id à différents endroits du projet.

**Comment by lionelB** [comment]
@rmelisson cool ! bien joué !

**Comment by virginielastisneres** [comment]
@rmelisson on peut clôturer ?
