### ISSUE TITLE
Les meta og:image, et og:url sont incorrects

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/code-du-travail-numerique#2818]
**Description**
Quand on arrive sur la homepage, les meta og:image et og:url comportent des _undefined_

`<meta property="og:url" content="undefined://code.travail.gouv.frundefined">`
`<meta property="og:image" content="undefined://code.travail.gouv.fr/static/assets/img/social-preview.png">`

**Reproduction**
Etapes à suivre pour reproduire le bug
1. Aller sur le site du code du travail
2. Afficher la source
3. Regarder les meta og:url et og:image

**Comportement attendu**
`<meta property="og:image" content="https://code.travail.gouv.fr/static/assets/img/social-preview.png">`
`<meta property="og:url" content="https://code.travail.gouv.fr/">`

**Checklist**
Vérifiez que les éléments suivants ont été faits et effacez cette section :
  - la tâche est compréhensible simplement par toute l'équipe
  - la tâche n'existe pas déjà
  - les bons tags ont été ajoutés

**Comment by UnbearableBear** [comment]
Thanks a lot !!
