### ISSUE TITLE
Changements Widget CDTN

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2825]
### Contexte 

Suite au test d'intégration du widget du cdtn sur cette page : http://centre-val-de-loire.direccte.gouv.fr/Travail-et-relations-sociales. 
La communication souhaiterait mettre plus en avant le widget. 

### Solution 

Pour cela, on remplace le titre "Code du travail numérique" par le logo du CDTN. 
Voici la maquette à retrouver ici selon les dimensions des sites des Direccte https://www.figma.com/file/XHPFtuAhUyvFbJfIKBiTsW/WIDGET-CDTN?node-id=18%3A2 : 
![Widget CDTN](https://user-images.githubusercontent.com/48682104/84644167-17f44780-aeff-11ea-83f6-1833c054e10c.png)

**Comment by revolunet** [comment]
😱 le logo RF dans le header de ce site me fend le coeur

**Comment by virginielastisneres** [comment]
> 😱 le logo RF dans le header de ce site me fend le coeur

Ahahahhaha 🤣 tu n'es pas le seul à avoir eu cette réaction 😱

**Comment by lionelB** [comment]
![image](https://user-images.githubusercontent.com/160320/84863648-8ce98d80-b075-11ea-9f68-e6fdae569288.png)
le double logo marianne on en parle ?
