### ISSUE TITLE
[fiches-MT] videos

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#2832]
les videos dailymotion sont bloquées par la CSP 

Ex : https://code.travail.gouv.fr/fiche-ministere-travail/quelles-mesures-lemployeur-doit-il-prendre-pour-proteger-la-sante-de-ses-salaries

Refused to frame 'https://www.dailymotion.com/' because it violates the following Content Security Policy directive: "frame-src"

**Comment by virginielastisneres** [comment]
> les videos dailymotion sont bloquées par la CSP
> 
> Ex : https://code.travail.gouv.fr/fiche-ministere-travail/quelles-mesures-lemployeur-doit-il-prendre-pour-proteger-la-sante-de-ses-salaries
> 
> Refused to frame 'https://www.dailymotion.com/' because it violates the following Content Security Policy directive: "frame-src"

héhé merci @revolunet je pensais que c'était lié à mon navigateur et aux restrictions du ministère mais non :) merci !
