### ISSUE TITLE
fix warining output in test

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#2834]
there is some warning in test that should be fixed

| file | lib | mesage |
|---|---|---|
| SearchBar.test.js | react-testing-library | `waitForElement` has been deprecated. Use a `find*` query (preferred: https://testing-library.com/docs/dom-testing-library/api-queries#findby) or use `waitFor` instead: https://testing-library.com/docs/dom-testing-library/api-async#waitfor  | 
| Search.test.js | react-testing-library |  `wait` has been deprecated and replaced by `waitFor` instead. In most cases you should be able to find/replace `wait` with `waitFor`. Learn more: https://testing-library.com/docs/dom-testing-library/api-async#waitfor.|
| FormulaDetails.test.js | MathComponent | Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details. |
| Mdx.test.js | remark-rehype |  mdast-util-to-hast: deprecation: `allowDangerousHTML` is nonstandard, use `allowDangerousHtml` instead |
| src/conventions/Convention/__tests__/index.test.js | react-ui | Warning: Failed prop type: The prop `title` is marked as required in `Tile`, but its value is `undefined`.  in Tile (at Articles.js:44) | 
| src/conventions/Convention/__tests__/index.test.js | react-ui |uuid must be a valid HTML5 id but was given "accordion__heading-Salaires minima hiérarchiques", ASCII whitespaces are forbidden

**Comment by UnbearableBear** [comment]
@lionelB C'est good si je m'ne occupe ou tu veux le faire ?

**Comment by lionelB** [comment]
fais toi plaiz'
