### ISSUE TITLE
Au moins input type number est trop larges sur mobile

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#2838]
![image-a99ee095-7fdf-4207-9717-87ae2811a81e](https://user-images.githubusercontent.com/705453/85134577-05e71180-b23d-11ea-9342-fe6aa7c66619.jpg)

**Comment by virginielastisneres** [comment]
Pour reproduire aller dans l'outil indemnité de licenciement à l'étape 4 Salaires de l'outil de licenciement. 
Essai sur mobile, navigateur Chrome.
