### ISSUE TITLE
Ajouter la CCN Métallurgie au calcul d'indemnité de licenciement

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#284]
SPECIFICATONS NON FINALISEES

1) Métallurgie accords nationaux
2) Métallurgie accords nationaux ngénieurs et cadres

1) Métallurgie accords nationaux ouvriers ETAM

Le montant de l'indemnité de licenciement est comme suit : 
demander ancienneté. 
soit x : salaire mensuel.
calcul de la moyenne des mois sur 12 MOIS. ( récupérer la moyenne des 12 deniers mois)

soit **y** l’ancienneté en année complète"récupérer années complète": ex si 25 mois : 25 mois/12 2,1, récupérer 2

soit z,  ancienneté de 10 ans/ 120 mois., valeur 10 ans ou 120 mois
soit z', quand y>z , z' est en année complète

si y>z: "non" : 
x/5+(x/5)/12*11

si y>z: "oui"

1/5x+(1/5x)/12*11+ [(x/15*2)+(x/15x2)/12*11.

le résultat est à comparer avec l'indemnité de licenciement légale.
Ensuite, vérifier que l'indemnité n'est pas différente en départements. on ajoutera que les calculs des départements pour lequel c'est le cas.
prévoir aussi le cas où la CC locale stipule autrement.

Une passe sera nécessaire pour affiner la notion d'ancienneté, et d'autre part des cas particuliers ( comme les différences de catégories...)

2) Métallurgie ingénieurs et cadres

définir ingénieur et cadre ( ajouter 

_Originally posted by @jrduscher in https://github.com/SocialGouv/code-du-travail-numerique/issues/39#issuecomment-425368330_

**Comment by jrduscher** [comment]
https://www.legifrance.gouv.fr/affichIDCC.do;jsessionid=2806D7F3C4697ED4B02796FDF9F0BFC5.tplgfr35s_2?idSectionTA=KALISCTA000005749867&cidTexte=KALITEXT000005673470&idConvention=KALICONT000005635842

**Comment by ClementChapalain** [comment]
close for #874
