### ISSUE TITLE
Parsing du MDX cassé par le glossaire

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#2845]
Dans certains cas, (e.g. https://code.travail.gouv.fr/contribution/dans-le-cadre-dun-cdd-quel-est-le-montant-de-lindemnite-de-fin-de-contrat), le markup du webcomponent du glossaire va casser l'interpretation du MDX.

En l'occurence dans l'exemple plus haut, c'est le webcomponent dans l'attribut `title` de `Tab` qui fait que notre composant [Mdx](https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-frontend/src/common/Mdx.js) n'utilise pas le component `Tab` fourni [ici](https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-frontend/src/contributions/rehypeToReact.js)
Voici le markdown qui pose problème:

```
<Tab title=\"Cas où le salarié ne perçoit pas l'<webcomponent-tooltip
content=\"Sommes%20vers%C3%A9es%20en%20compensation%20ou%20en%20r%C3%A9paration%20de%20quelque%20chose.\">indemnité</webcomponent-tooltip>\">
   blah blah blah
</Tab>
```

Donc au choix:
- On fait évoluer la regexp du glossaire avec un negative lookbehind pour ne pas transformer les mots du glossaire en webcomponents si ils sont dans des attributs (à minima des titres). A voir aussi si on ne pourrait pas supprimer les webcompoenents lorsqu'ils sont dans des liens.
- On arrive à trouver un moyen de faire en sorte que le parsing de Mdx fonctionne mieux et arrive à comprendre ce cas-ci, mais vu qu'il s'agit d'un package, ça ne va pas forcément être trivial.
- Une autre option ?

**Comment by virginielastisneres** [comment]
@lionelB on peut passer cette issue dans done du coup ?

**Comment by lionelB** [comment]
ah oui ;)
