### ISSUE TITLE
Récupération des nouvelles données sur les références juridiques des contributions 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2857]
### CONTEXTE 

Dans les contributions en prod, les références juridiques bien que parfois précises renvoient uniquement sur la page générale de la convention collective et non sur l'article précis de la convention collective. 
Exemple : dans la [contribution sur la durée du congé maternité](https://code.travail.gouv.fr/contribution/quelle-est-la-duree-du-conge-de-maternite?q=dur%C3%A9e%20cong%C3%A9%20maternit%C3%A9), convention collective de la banque : nous avons comme référence juridique l’article 51 de la convention collective de la banque. Or lorsqu'on clique dessus on tombe sur la convention collective générale et non sur l'article 51. 
![image](https://user-images.githubusercontent.com/48682104/86113793-0055bb00-baca-11ea-8157-198163cdd722.png)

Or, Ivan a fait un travail dans l'outil de contribution pour que les références juridiques indiquées renvoient directement vers l'article de la convention collective en question.

### SOLUTION 

Il faut donc trouver une solution pour récupérer les données de l'outil de contribution via son API afin de l'intégrer dans le code du travail numérique. 
Il semblerait d'après Lionel que cela vienne du package contributions-data qui n'a pas l'air de remonter les nouvelles infos.

**Comment by lionelB** [comment]
closed by #2866
