### ISSUE TITLE
Tracking des recherches cc

### ISSUE THREAD

**Issue by Armandgrd** [SocialGouv/code-du-travail-numerique#2879]
**Description**
Le tracking des recherches éffectuées dans [la recherche CC ](https://code.travail.gouv.fr/convention-collective) génère un évenement par charactère. par exemple pour un utilisateur qui recherche "ministère" les évènements générés sont:

"m"
"mi"
"min"
"mini"
"minis"
"minist"
"ministè"
...

Cela a pour conséquence:
- de fausser le nombre d'évènement cc_search,
- rend l'utilisation des logs difficiles
- génère du volume de logs inutiles

**Comportement attendu**
un seul èvenement de tracking générée "ministère"

**Comment by virginielastisneres** [comment]
> **Description**
> Le tracking des recherches éffectuées dans [la recherche CC ](https://code.travail.gouv.fr/convention-collective) génère un évenement par charactère. par exemple pour un utilisateur qui recherche "ministère" les évènements générés sont:
> 
> "m"
> "mi"
> "min"
> "mini"
> "minis"
> "minist"
> "ministè"
> ...
> 
> Cela a pour conséquence:
> 
> * de fausser le nombre d'évènement cc_search,
> * rend l'utilisation des logs difficiles
> * génère du volume de logs inutiles
> 
> **Comportement attendu**
> un seul èvenement de tracking générée "ministère"

Super @ArmandGiraud 👍

**Comment by UnbearableBear** [comment]
Finalement le comportement choisi est le suivant: à chaque consultation de la search des ccn, on génère un identifiant unique, propre à la consultation de cette page (c'est à dire que changer de page et revenir ensuite sur la page crée un nouvel identifiant); ensuite on attend que l'utilisateur entre du texte et on "traque" le texte saisi que l'on correle à l'identifiant unique mais seulement si l'utilisateur ne modifie pas sa recherche dans les 2 secondes qui suivent. Si l'utilisateur modifie sa recherche dans les deux secondes qui suivent, on reset le chrono et on attend encore 2 secondes (pour éviter d'avoir trop d'évènement envoyés) et bis repetita si ça continue ainsi. Néanmoins, si après deux secondes ou plus l'utilsateur décide de modifier à nouveau le champ, rebelote, on traque à nouveau cette saisie, mais on saura qu'il s'agit du même utiliateur dans matomo grace à l'idenfiant unique.

**Comment by ArmandGiraud** [comment]
Super @UnbearableBear , je teste ce que ça donne dans le tracking au cours de la prochaine release, et on pourra clôturer
Merci!

**Comment by lionelB** [comment]
pourquoi on ne track la recherche effectué au click sur la CC ? 
et aussi, il me semblait que la recherche était débouncé, il faudrait peut-être voir pourquoi ce n'est pas le cas ?

**Comment by UnbearableBear** [comment]
@ArmandGiraud De rien, c'était fun ! Prochaine fois je te laisse coder toi et je supervise si tu veux 😈 

@lionelB On a pensé à le faire comme ça et finalement Armand a préféré qu'on track plutôt les input que le click; sachant que le click pourrait très bien ne jamais arriver et on ne saurait pas ce qui a "foiré". Ceci dit le click sur une CCN est traqué aussi ! Pour la même raison, on a choisi de tracker aussi les différentes "étapes" de recherche qu'il pourrait y avoir (e.g: recherche d'abord "macdo", puis "restauration", sans quitter la page) sans vraiment savoir encore si ça va être utile ou pas.

Pour la recherche il y a un "hookSearch", ça m'a pas l'air débouncé et j'ai l'impression qu'il y a une volonté de ne pas la débounce 🤷 En tous cas c'est plutôt élaboré vu qu'il y a marqué en commentaire qu'il faudrait en faire un package ? Si tu as envie de faire différement, n'hésite pas à proposer ! https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-frontend/src/conventions/Search/searchHook.js

(personnellement je ne pense pas que corréler les calls http et le tracking apporte une plus-value, il faudrait un peu éloigner le tracking de là ou se passe "l'action", ça ne me branche pas plus que ça)

**Comment by lionelB** [comment]
ok je suis pas sur de comprendre "il y a une volonté de ne pas la débounce". 
pour ma part, je faisais référence aux appels api et ils sont déjà "debounce" & "memoize" 
Il me semble qu'on veut traquer ce que les gens cherchent, donc ça me paraissait bien de se baser sur le service qui fait la recherche plutôt qu'on composant ui.

Les 2 secondes risquent de ne pas remonter les recherches dans le cas où le formulaire est utilisé pour rechercher CC suivi d'une navigation (les outils et la formulaire `/convention-collective`
Donc si on garde l'approche composant UI, il faudrait qu'on gère le cas où le composant est démonté pour faire remonter la recherche si ce n'est pas deja fait

**Comment by UnbearableBear** [comment]
Yes ça s'est géré tout seul ! Le timeout et la closure dans le debounce est "indépendant" et la navigation / unmount ne l'empechent pas de s'executer avec les bons params.
