### ISSUE TITLE
Thémage des sous fiches MT

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#2908]
## Problèmes :
- __Dans le datafiller, il est possible de selectionner des sous-fiches comme références dans les thèmes__
- __Dans le datafiller, il n'est pas possible à l'heure actuelle de savoir si les sous fiche sont thémées ou pas__

## Constats :
- La verification des contenus themés/non-thémés se fait via le sitemap du cdtn qui ne contient pas les sous-fiches.
- Les sous-thèmes d'une fiche auront toujours le même thème que la fiche principale

## Solutions :
1. Avoir la possibilité d'exclure les sous-fiche MT et d'inclure les fiches MT entières de l'API search du CDTN. L'objectif final étant que le suggester du datafiller (qui utilise l'api CDTN) remonte les fiches entières uniquement. __Attention, il faut distinguer le suggester des references, du suggester des résultats de recherche qui, eux, doivent proposer des sous-themes !__
2. Faire en sorte que le `#` ne soit pas fourni à `getBreadcrumb` lors de l'indexation des sous-fiches afin que le thémage puisse se faire à partir des slugs des fiches MT entières. e.g. https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-data/indexing/populate.js#L127 rajouter un `.replace("#and co", "")` ici

**Comment by UnbearableBear** [comment]
@lionelB @revolunet Vous en pensez quoi ?

**Comment by revolunet** [comment]
sound good to me : 
 - dans la partie DF, on manipule/search uniquement des urls "racines"
 - on fait le nécessaire au moment du split/ingestion des fiches MT pour retrouver le theme d'après la fiche "parente"

**Comment by lionelB** [comment]
coté api 
```js
  // in packages/code-du-travail-api/src/server/routes/search/index.js
  const { q: query } = ctx.query;
  // nom a modifier :D
  const withFullPage = ctx.query.withFullPage === "true";

  const sources = [
    withFullPage ? SOURCES.SHEET_MT_PAGE : SOURCES.SHEET_MT,
```

**Comment by virginielastisneres** [comment]
@UnbearableBear manu tu as mis cette issue en done on peut la clôturer du coup ?

**Comment by UnbearableBear** [comment]
closes by https://github.com/SocialGouv/code-du-travail-numerique/pull/2912 and https://github.com/SocialGouv/code-du-travail-numerique/pull/2910
