### ISSUE TITLE
indicateurs pouce haut dans la page résultat

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#294]
SPEC WIP!
définir l'action attendue
le pouce haut doit valider une réponse satisfaisante à une question posée. 
=> L'équipe projet doit pouvoir avoir trace de plusieurs éléments:
1) le couple question posé+ url de la page résultat. 
2) d'autres données pourraient être intéressantes:

   - durée de consultation de la page
   - clic vers des liens externes,
   - poursuite de la navigation vers des données approfondies ( articles du CDTL), vers des interlocuteurs ou sortie du site? ( faisabilité RGPD et pertinence de ces détails à définir)

définir le cas échéant les besoins UX
- la question posée à l'UX: je suis utilisateur, je clique sur le pouce haut, quelles sont mes attentes? un remerciement? une validation ( le pouce haut garde une couleur après le clic)?
- le clic appelle t-il une modal? faut il recueillir là également un avis de l'utilsitaeur?

définir les effets sur l'outil statistique 
Piwiki/ pas piwik, comment intégrer dans l'outil les remontées sur les actions pouce haut ( et pouce bas?)
définir les effets sur l'apprentissage

le couple question/ réponse

**Comment by lionelB** [comment]
closed by  #360
