### ISSUE TITLE
Intégration de la charte graphique du gouvernement // HOME PAGE

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2943]
# Contexte

Le gouvernement a sorti une charte graphique obligatoire et commune à toutes les institutions publiques ayant des conséquences notamment pour les sites web. 

Charte à retrouver ici : https://www.gouvernement.fr/charte/charte-graphique-les-fondamentaux/introduction

Entre autre, elle réglemente le header des sites web avec de nouveaux logos, taille et position spécifiques. Par conséquent, nous devons intégrer cette charte à notre site et cela a des conséquences sur le header actuel. 

Pour rappel, nous avons 3 types de header en fonction sur le site, cette issue concerne uniquement la home page. 

# Solution (version Desktop) 

🚨 🚨 🚨 🚨
👉 TOUTES LES MAQUETTES SONT ICI ===>>> https://www.figma.com/file/Lv4OCQwZ39lVNAZt97cIRP/Untitled?node-id=63%3A341 🎉 🎉 🎉 🎉 🎉

### Maquette 
![Image collée à 2020-8-14 16-06](https://user-images.githubusercontent.com/48682104/90265340-bc88fc00-de52-11ea-9891-6970901ea3f7.png)

### Changements à effectuer 

1. Taille du header : 150 px 
2. Taille du logo du ministère : 150 px 
Voici le logo à utiliser : 
![Logo marianne](https://user-images.githubusercontent.com/48682104/90619050-0d14a680-e211-11ea-87c6-0e73bc9c7c52.png)
3. Le positionnement de l'illustration a été modifié. 
4. Taille  "Accessibilité Boîte à outils Thèmes"  : 16px. _(On l'avait passé à 18px mais je ne suis plus trop convaincue de cette utilité surtout quand on voit cela donnerait avec le header en position de scroll. Cela fait lourd je trouve. Donc je resterai sur la taille de 16px comme initialement défini par Cécile sauf à mettre 18px en header sans scroll et dès qu'il y a scroll on passe en 16px)_ 
5. Couleur du fond du header : blanc

@lionelB tu peux compléter/modifier les infos que tu avais noté toi. 

### Maquette 

![0-CDTN-HP-BlueFinal (4)](https://user-images.githubusercontent.com/48682104/90619995-3550d500-e212-11ea-96a3-27802f1b3490.jpg)

#### UI

1. Taille du header : 90px.
2. Taille du logo du CDTN (ajusté à la barre de recherche) : 54px . 
3. Ajout de la barre de recherche au centre du header. Taille : 54px (comme utilisé aujourd'hui dans les autres pages). 
4. L'icone de recherche (la loupe) dans la barre de recherche : mettre en couleur secondaire (il n'y a pas de raison qu'il soit traité différemment que le bouton de contacter les SR en bas de page ou que le burger dans le mode mobile, il s'agit bien d'une action secondaire comme une autre). 
5. Taille de "Accessibilité Boîte à outils Thèmes" : 16px. 

#### Comportement attendu

1. Header : sticky au scroll. 
_Jusqu'à présent cela n'était pas nécessaire car le mode sticky n'apportait rien à l'utilisateur. 
Ici, vu que l'on rajoute la barre recherche, le mode sticky permet à l'usager qui scroll dans la home page et qui après scroll veut faire une recherche d'éviter d'avoir à de nouveau scroller vers le haut pour aller chercher la barre de recherche._  
**2. Le logo du ministère disparaît et il reste seulement le logo du CDTN** 

Vidéo ici : 

# Solution (version Mobile) 

🚨 🚨 🚨 🚨
👉 TOUTES LES MAQUETTES SONT ICI ===>>> https://www.figma.com/file/Lv4OCQwZ39lVNAZt97cIRP/Untitled?node-id=63%3A341 🎉 🎉 🎉 🎉 🎉

### Maquette 
![image 11](https://user-images.githubusercontent.com/48682104/90642513-c33cb800-e232-11ea-8e37-826899b236f8.png)

### Changements à effectuer 

1. Taille du header : 90px (c'est plus que ce que l'on a aujourd'hui mais pour avoir essayé avec la taille d'aujourd'hui en 66px [voir figma], c'est affreux on ne peut pas lire le nom du ministère donc aucun intérêt)
2. Taille du logo ministère : 90px aussi (même png qu'au dessus)
3. Personnellement je trouve le burger trop gros sur notre version actuelle (15.75px) je le passerai à 14px (comme pour la version du header sticky lors du scroll)
4. Couleur fond du header : blanc 

### Maquette 
![image 6 (1)](https://user-images.githubusercontent.com/48682104/90638199-5541c200-e22d-11ea-9bec-8936ad891bdf.png)

#### UI

1. Taille du header : 76px (j'ai copié le site d'airbnb version mobile, je trouve le header sticky bien proportionné)
**2. Les logo du Ministère et du CDTN disparaissent** 
3. Ajout de la barre de recherche au centre (cf. site airbnb version mobile qui nous a inspiré)
4. Taille de la barre de recherche : 44px de hauteur (à l'heure actuelle le 54px est un peu trop gros pour un header de 76px)
4. Couleur fond du header : blanc 

#### Comportement attendu

Comportement identique que sur Desktop.

**Comment by lionelB** [comment]
closed by #2960
