### ISSUE TITLE
Intégration de la charte graphique du gouvernement // PAGE DE RESULTAT

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2944]
# Contexte

Le gouvernement a sorti une charte graphique obligatoire et commune à toutes les institutions publiques ayant des conséquences notamment pour les sites web. 

Charte à retrouver ici : https://www.gouvernement.fr/charte/charte-graphique-les-fondamentaux/introduction

Entre autre, elle réglemente le header des sites web avec de nouveaux logos, taille et position spécifiques. Par conséquent, nous devons intégrer cette charte à notre site et cela a des conséquences sur le header actuel. 

Pour rappel, nous avons 3 types de header en fonction sur le site. Ici page de résultat de recherche.

# Solution (version Desktop)

🚨 🚨 🚨 🚨
👉 TOUTES LES MAQUETTES SONT ICI ===>>> https://www.figma.com/file/Lv4OCQwZ39lVNAZt97cIRP/Untitled?node-id=63%3A341 🎉 🎉 🎉 🎉 🎉

### Maquette 

![5-Recherche](https://user-images.githubusercontent.com/48682104/90621923-b1e4b300-e214-11ea-9085-56f386475e47.jpg)

### Changements à effectuer 
Mêmes changements que pour la HOME PAGE. 
1. La **taille du header** qui est de 150 pour rappel. 
2. La **taille du logo Ministère** est également de 150. 
Voici le logo à utiliser : 
![Logo marianne](https://user-images.githubusercontent.com/48682104/90619050-0d14a680-e211-11ea-87c6-0e73bc9c7c52.png)
3. Laisser laa taille de "Accessibilité Boîte à outils Thèmes" à 16px. 
4. Espace entre le header et le fil d'ariane : 40px (comme dans les maquettes de Cécile)

### Maquette 

![5-Recherche (1)](https://user-images.githubusercontent.com/48682104/90622008-d2ad0880-e214-11ea-8c65-69c1bf75b3ce.jpg)

### Changements à effectuer 

**UI**
1. Le header en scroll est de taille 90px
2. La taille du logo du CDTN est ajusté à la barre de recherche soit 54px pour équilibrer. 
3. On ajoute la barre de recherche au centre du header. Sa taille reste 54px (comme utilisé aujourd'hui dans les autres pages). 
4. Contrairement à la home page il serait bien que la recherche effectuée reste dans la barre de recherche => comme ici https://code.travail.gouv.fr/fiche-service-public/conges-payes?q=cong%C3%A9s
4. L'icone de recherche (la loupe) dans la barre de recherche est passé en couleur secondaire (je crois que c'est celle ci #7598D6).
5. La taille de "Accessibilité Boîte à outils Thèmes" reste à 16px sinon ca déséquilibre. 

**Comportement attendu**
Mêmes comportement que pour la HOME PAGE. 
1. Le header reste sticky au scroll. 
Pourquoi le laisser sticky avec une barre de recherche alors que l'on est dans la page résultat ? Une personne qui scrolle pour chercher des résultats, soit elle trouve ce qu'elle chercher et clique dessus ok, soit elle scrolle, cherche, regarde plus de résultats, ne trouve rien et là ca serait bien qu'on lui permette de faire une nouvelle recherche rapidement sans avoir à scroller de nouveau. 
2. Le logo du ministère disparaît et il reste seulement le logo du CDTN 

# Solution (version Mobile)

🚨 🚨 🚨 🚨
👉 TOUTES LES MAQUETTES SONT ICI ===>>> https://www.figma.com/file/Lv4OCQwZ39lVNAZt97cIRP/Untitled?node-id=63%3A341 🎉 🎉 🎉 🎉 🎉

### Maquette 

![image 13](https://user-images.githubusercontent.com/48682104/90643126-80c7ab00-e233-11ea-9cc0-588de601e7a8.png)

### Changements à effectuer 
Comme Homepage 

1. Taille du header : 90px (c'est plus que ce que l'on a aujourd'hui mais pour avoir essayé avec la taille d'aujourd'hui en 66px [voir figma], c'est affreux on ne peut pas lire le nom du ministère donc aucun intérêt)
2. Hauteur du logo ministère : 85px aussi (même png qu'au dessus).
3. Hauteur du logo du CDTN : 50px 
3. Burger : 14px 
4. Couleur fond du header : blanc 
5. Espace entre le header et le fil d'ariane : 15px (comme dans les maquettes de Cécile)

### Maquette 

![image 14](https://user-images.githubusercontent.com/48682104/90643377-d603bc80-e233-11ea-9816-552175de4d4d.png)

### Changements à effectuer 

Comme home page version mobile sauf dans la barre de recherche ca serait bien d'avoir la recherche effectuée. 

**UI**
1. Taille du header : 76px (j'ai copié le site d'airbnb version mobile, je trouve le header sticky bien proportionné)
2. Les logo du Ministère et du CDTN disparaissent
3. Ajout de la barre de recherche au centre avec la recherche effectuée dedasn (cf. site airbnb version mobile qui nous a inspiré)
4. Taille de la barre de recherche : 44px de hauteur (à l'heure actuelle le 54px est un peu trop gros pour un header de 76px)
5. Couleur fond du header : blanc

**Comportement attendu**
Comportement identique que sur Desktop.

**Comment by lionelB** [comment]
closed by  #2960
