### ISSUE TITLE
Intégration de la charte graphique du gouvernement // TOUTES LES AUTRES PAGES

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2945]
# Contexte

Le gouvernement a sorti une charte graphique obligatoire et commune à toutes les institutions publiques ayant des conséquences notamment pour les sites web. 

Charte à retrouver ici : https://www.gouvernement.fr/charte/charte-graphique-les-fondamentaux/introduction

Entre autre, elle réglemente le header des sites web avec de nouveaux logos, taille et position spécifiques. Par conséquent, nous devons intégrer cette charte à notre site et cela a des conséquences sur le header actuel. 

Pour rappel, nous avons 3 types de header en fonction sur le site. Ici toutes les pages hors homepage et page de résultats recherche.

# Solution Desktop

🚨 🚨 🚨 🚨
👉 TOUTES LES MAQUETTES SONT ICI ===>>> https://www.figma.com/file/Lv4OCQwZ39lVNAZt97cIRP/Untitled?node-id=63%3A341 🎉 🎉 🎉 🎉 🎉

### Maquette 

![1-Page contenu - MinistereTravail (5)](https://user-images.githubusercontent.com/48682104/90623515-db9ed980-e216-11ea-81d8-2645af105f8e.jpg)

### Changements à effectuer 

1. Hauteur du header : 150px  
2. Hateur du logo Ministère : 150px. 
Voici le logo à utiliser : 
![Logo marianne](https://user-images.githubusercontent.com/48682104/90619050-0d14a680-e211-11ea-87c6-0e73bc9c7c52.png)
3. Hauteur du logo CDTN reste la même
4. Barre de rechercher au centre alors qu'aujourd'hui elle est toute à droite (armand avait déjà dit que cela n'était pas optimal pour inciter les gens à faire des recherches). 
5. Icone de recherche (la loupe) dans la barre de recherche en couleur secondaire (#7598D6)
6. Laisser la taille de "Accessibilité Boîte à outils Thèmes" à 16px + mettre à droite
7. Espace entre le header et le fil d'ariane : 15px (comme dans les maquettes de Cécile)

### Maquette 

![1-Page contenu - MinistereTravail (6)](https://user-images.githubusercontent.com/48682104/90623529-e0fc2400-e216-11ea-887e-e7f68fe8e1ac.jpg)

#### UI

1. Hauteur du header : 90px.
2. Hauteur du logo CDTN (ajusté à la barre de recherche) : 54px 
3. Barre de recherche au centre du header. Sa taille reste 54px (comme utilisé aujourd'hui). 
4. L'icone de recherche (la loupe) dans la barre de recherche est passé en couleur secondaire (#7598D6).
5. La taille de "Accessibilité Boîte à outils Thèmes" reste à 16px sinon ca déséquilibre. 

#### Comportement attendu

1. Le header reste sticky au scroll (comme aujourd'hui)
2. Le logo du ministère disparaît et il reste seulement le logo du CDTN 

# Solution Mobile

🚨 🚨 🚨 🚨
👉 TOUTES LES MAQUETTES SONT ICI ===>>> https://www.figma.com/file/Lv4OCQwZ39lVNAZt97cIRP/Untitled?node-id=63%3A341 🎉 🎉 🎉 🎉 🎉

### Maquette 
![image 15](https://user-images.githubusercontent.com/48682104/90644886-93db7a80-e235-11ea-8508-cc1c3f98a6d9.png)

### Changements à effectuer 

Comme Homepage

1. Taille du header : 90px (c'est plus que ce que l'on a aujourd'hui mais pour avoir essayé avec la taille d'aujourd'hui en 66px [voir figma], c'est affreux on ne peut pas lire le nom du ministère donc aucun intérêt)
2. Hauteur du logo ministère : 85px aussi (même png qu'au dessus).
3. Hauteur du logo du CDTN : 50px
4. Burger : 14px
5. On laisse l'icone de recherche
6. Espace entre le header et le fil d'ariane : 15px (comme dans les maquettes de Cécile)

### Maquette 
![image 15](https://user-images.githubusercontent.com/48682104/90644949-a6ee4a80-e235-11ea-8e66-ddf00e02a967.png)

### Changements à effectuer 

Comme home page version mobile sauf dans la barre de recherche ca serait bien d'avoir la recherche effectuée.

#### UI

1. Taille du header : 76px (j'ai copié le site d'airbnb version mobile, je trouve le header sticky bien proportionné)
2. Les logo du Ministère et du CDTN disparaissent
3. Barre de recherche au centre avec la recherche effectuée dedan (cf. site airbnb version mobile qui nous a inspiré)
4. Taille de la barre de recherche : 44px de hauteur (à l'heure actuelle le 54px est un peu trop gros pour un header de 76px)
5. Icone recherche en bleu couleur secondaire

#### Comportement attendu
Comportement identique que sur Desktop.

**Comment by lionelB** [comment]
closed by  #2960
