### ISSUE TITLE
Ajout d'une aide au moteur de recherche des conventions collectives

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2947]
# Contexte 
On a regardé un peu le tracking des outils et notamment les nombres de personnes qui cliquent sur suivant pour chaque étape de l'outil. 
Comme on pouvait s'en douter, il y a une perte très importante des utilisateurs après l'étape qui demande de remplir sa convention collective. 
Exemple ici avec préavis de démission
![image](https://user-images.githubusercontent.com/48682104/90770306-dbbfd780-e2f1-11ea-83a7-03f61543f032.png)
Cette perte peut s'expliquer pour diverses raisons : les gens ne trouvent pas leur convention collective, les utilisateurs ne connaissent pas le nom de leur convention collective voire les gens ne connaissent pas ce qu'est une convention collective et ils s'arrêtent là. 

#### **Cette problématique ne concerne pas uniquement les outils en tant que tel mais tous les contenus où l'on utilise notre moteur de recherche de CC.** 

Aussi, nous avons regardé ce qui se fait ailleurs sur cette problématique. Nous avons trouvé 2 sites ayant la même problématique que nous et proposant un accompagnement à l'utilisateur pour remplir sa CC. 
- [Alan ](https://alan.com/?utm_term=%2Balan&utm_campaign=fr_fr_f1_m1_x_x_brand_na&utm_source=google&utm_medium=ppc&hsa_acc=3792770307&hsa_cam=9559769002&hsa_grp=104793169424&hsa_ad=423279654128&hsa_src=g&hsa_tgt=kwd-301175734049&hsa_kw=%2Balan&hsa_mt=b&hsa_net=adwords&hsa_ver=3&gclid=Cj0KCQjwvvj5BRDkARIsAGD9vlIO7SqLc6ZuGxTL0EuY4EYKAs2QlBHQAgoAfeGoFNK2u62QiYOo3QgaAlEPEALw_wcB#/qualify):
- [mes-indemnités.com](https://mesindemnites.com/calculation/step1)
Les 2 approches sont différentes : 
- l'un indique ce qu'est une convention collective et où on peut la trouver de manière très sommaire.  
- l'autre propose de sélectionner son bulletin de paie au départ parmi 13 choix et en fonction indique visuellement où se trouve dans le bulletin de paie le nom de la convention collective 
Les 2 approches ont des avantages et des inconvénients : 
- celle du bulletin de paie semble très pragmatique et accompagne en profondeur l'utilisateur. Toutefois il faut passer par l'étape de sélectionner son bulletin parmi 13 bulletins possibles... étape qui semble complexifier le processus. 
- celle d'Alan est simple, courte, rappelle ce qu'est une convention collective (on sait à quel point ce point est important, beaucoup ne savent même pas l'existence de la convention collective). Toutefois, elle est n'offre pas d'autres possibilités mise à part le bulletin de paie alors qu'il existe d'autres moyens également rapides (je compte pas le renvoi au comptable qui ne concerne que les entreprises. Autre point, elle n'aide pas à trouver sa convention collective sur son bulletin et si on regarde les 13 bulletins de paie c'est vraiment pas toujours facile de trouver car il y a beaucoup de lignes et de textes sur un bulletin. 

# Solution 

L'idée est donc d'essayer de trouver un compromis entre les 2 solutions : 
- rappeler ce qu'est une CC pour ceux qui ne savent pas car c'est quand même la base de la question. 
- offrir de manière rapide des possibilités pour trouver sa convention collective
- essayer d'accompagner au mieux l'utilisateur notamment concernant la recherche dans le bulletin de paie. 

### La solution présentée est à intégrer à l'"outil" de recherche des conventions collectives qui est utilisé soit tout seul, soit dans les outils, dans les contributions etc..
![image](https://user-images.githubusercontent.com/48682104/90784451-94d9de00-e301-11ea-94e4-89e13cb1a4f8.png)

## Maquette
:rotating_light: :rotating_light: :rotating_light:
## Présentation de la solution et comportement attendu

1. On indique en dessous de la barre de recherche de la CC : 
"_Vous ne connaissez pas votre convention collective ? 
Consultez notre aide._"
2. Au clic sur "notre aide" s'ouvre une modale
3. Dans la modale est présenté en 2 parties : Qu'est ce qu'une convention collective ? et Où trouver le nom de sa convention collective ? + une aide à la fin. 
4. Le texte de la modale est sous dans la maquette directement, soit je vous l'ai mis ici. 
5. Image à intégrer dans "Voir l'exemple" de la partie 2 "Vérifiez dans le fiche de paie". Afin d'éviter de montrer une dizaine de bulletin de paie et d'éviter à rentrer trop dans les détails, il a été choisi de faire un exemple type qui regroupe 90% des cas des bulletin de paie sans rentrer dans les détails, le but étant juste d'orienter l'oeil de l’utilisateur lors de sa recherche dans son bulletin. 
5. Encart Help : petite aide tout en bas si on ne l'a toujours pas trouvé sa convention collective. Si l’utilisateur clique sur "Contacter l'inspection du travail" il est renvoyé à la modale de contact de nos services en région. 

Vidéo ici :point_right:
![▶ maquette aide CC - Aide Conventions collectives (1)](https://user-images.githubusercontent.com/48682104/90782990-cf427b80-e2ff-11ea-853c-66e97aa31ba2.gif)

## UI

:rotating_light: :rotating_light: :rotating_light:
### Maquette à retrouver ici :point_right: https://www.figma.com/file/kxgpd3dchAxZKzoIlEXBpj/Aide-Conventions-collectives?node-id=0%3A1

0. Texte en dessous de la barre de recherche (espace 24 px), texte en 16px. Espace entre la question et la réponse 8px. 
1. Modale classique
2. Titre partie en Merriweather bold 22px
3. Texte Open sans en 16px
4. Espace entre titre et texte de 16px
5. Espace entre les parties 24px
6. Sous-titre en Open sans semibold 18px
7. Espace entre sous titre et texte 8px
8. Image ici pour l'exemple 
![Exemple desktop](https://user-images.githubusercontent.com/48682104/90774485-dc5b6c80-e2f7-11ea-966f-7bec76c29683.png)

## Version mobile (comportement & UI) 

Même idée générale sauf que la modale s'ouvre en grand sur l'écran cf vidéo en dessous. 

![▶ maquette aide CC - Aide Conventions collectives (3)](https://user-images.githubusercontent.com/48682104/90783775-d027dd00-e300-11ea-89d7-c64df0052629.gif)

:rotating_light: :rotating_light: :rotating_light:
### Maquette à retrouver ici :point_right: https://www.figma.com/file/kxgpd3dchAxZKzoIlEXBpj/Aide-Conventions-collectives?node-id=0%3A1

0. Texte en dessous de la barre de recherche (espace 14 px), texte en 14px. Espace entre la question et la réponse 8px. 
1. Modale classique
2. Titre partie en Merriweather bold 22px
3. Texte Open sans en 14px
4. Espace entre titre et texte de 10px
5. Espace entre les parties 30px. 
6. Accordéon pour les sous parties : Version mobile j'ai rajouté des accordéons pour les différentes parties pour permettre à l'utilisateur de voir les 3 possibilités à la fois sur son écran. 
6. Sous-titre en Open sans semibold 18px
7. Espace entre sous titre et texte 8px
8. Image ici pour l'exemple 
![Exemple mobile](https://user-images.githubusercontent.com/48682104/90774520-e8dfc500-e2f7-11ea-94fc-92625e7e9aea.png)

**Comment by jrduscher** [comment]
Je viens de voir une petite contradiction dans le parcours de l'utilisateur:
Dans l'aide on rappelle comment trouver sa convention collective de façon classique ( Bull. de salaire, etc.)
**Pour autant, dans le CDTN on détient une information fiable à ce sujet provenant de la déclaration de l'employeur.**
L'user devrait donc être prioritairement invité à renseigner SIRET et raison sociale ( voire un jour l'enseigne?) de son entreprise ou établissement, et à défaut d'une réponse être renvoyé sur les moyens classiques résumés dans l'aide ci dessus.

Le cas présenté fonctionne mais ne met pas en valeur cette information qui est une valeur ajouté du CDTN.

**Comment by revolunet** [comment]
Côté recherche, voir si on intègre un index des données SIREN pour mieux chercher par nom/raison sociale/etablissement

**Comment by UnbearableBear** [comment]
J'ai pris en compte la remarque de @jrduscher et j'ai rajouté une section dans la modale d'aide pour rappeler que la search donne la possibilité de retrouver sa convention collective via la raison social, le siret ou ... le siren ! C'était très facile à implémenter alors j'ai rajouté la recherche par siren.
J'ai aussi corrigé un bug ou on affichait que le service était indisponible alors qu'on ne trouvait pas de résultats.

**Comment by jrduscher** [comment]
Top pour la recherche du SIREN!
Si simple à implémenter? Si le SIREN correspond au 9 premiers chiffres du SIRET, la difficulté va résider à en faire un filtre pour afficher ensuite tous les établissements et siret répondant au siren:
Exemple:
XXX.XXX.XXX = Mc Burger SA  => CCN restauration rapide
XXX.XXX.XXX.00010 MC Burger Paris => CCN restauration rapide
XXX.XXX.XXX.00020 MC Burger Chartres=> CCN Chimie

**Comment by UnbearableBear** [comment]
Hunnn, je ne comprenais pas pourquoi ça me renvoyait des sirets aussi avec, ok je vois ! Je rajoute ça demain 👌

**Comment by virginielastisneres** [comment]
@UnbearableBear Manu tu en es ou de cette tâche ?

**Comment by UnbearableBear** [comment]
Elle devrait être mergée dans la matinée !
