### ISSUE TITLE
Update dossier // prochaine mise en prod

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#2948]
# Contexte

Suite à des changements ou des erreurs de lien il faut faire un update du dossier sur le covid_19 : https://code.travail.gouv.fr/dossiers/ministere-du-travail-notre-dossier-sur-le-coronavirus

# Update dossier 

1.	Section Activité partielle

- le lien source ministère du travail dans cette fiche https://code.travail.gouv.fr/fiche-ministere-travail/activite-partielle-chomage-partiel renvoie une erreur 301  : https://travail-emploi.gouv.fr/le-ministere-en-action/coronavirus-covid-19/questions-reponses-par-theme/article/activite-partielle-chomage-partiel. 
La bonne url est là : https://travail-emploi.gouv.fr/le-ministere-en-action/coronavirus-covid-19/questions-reponses-par-theme/faq-chomage-partiel-activite-partielle
![image](https://user-images.githubusercontent.com/48682104/90886998-d1661200-e3b3-11ea-9915-be62d7e0a6a5.png)

- changement du titre de la rubrique en « Activités partielles (chômage partiel et APLD)"

2.	Salaire et rémunération 

- le lien source ministère du travail dans cette fiche https://code.travail.gouv.fr/fiche-ministere-travail/prime-exceptionnelle-et-epargne-salariale renvoie une erreur 301  : https://travail-emploi.gouv.fr/le-ministere-en-action/coronavirus-covid-19/questions-reponses-par-theme/article/primes-exceptionnelles-et-epargne-salariale. 
La bonne url est là : https://travail-emploi.gouv.fr/le-ministere-en-action/coronavirus-covid-19/questions-reponses-par-theme/article/prime-exceptionnelle-et-epargne-salariale
![image](https://user-images.githubusercontent.com/48682104/90887206-3a4d8a00-e3b4-11ea-87b2-424d002d1b38.png)

3.	CSE et accord collectif
 
- supprimer « nouveautés : information et consultation du CSE » car date de fin du dispositif au 23/08/2020 : https://code.travail.gouv.fr/information/information-et-consultation-du-cse-nouveautes-covid-19
(à avoir en tête suppression à venir de :  « nouveautés : élection du CSE » car date de fin du dispositif au 31/08/2020 )

4.	SST

- le lien source ministère du travail dans cette fiche https://code.travail.gouv.fr/fiche-ministere-travail/quelles-mesures-lemployeur-doit-il-prendre-pour-proteger-la-sante-de-ses-salaries renvoie une erreur 301  : https://travail-emploi.gouv.fr/le-ministere-en-action/coronavirus-covid-19/proteger-les-travailleurs/article/quelles-mesures-l-employeur-doit-il-prendre-pour-proteger-la-sante-de-ses
La bonne url est là : https://travail-emploi.gouv.fr/le-ministere-en-action/coronavirus-covid-19/proteger-les-travailleurs-les-emplois-les-savoir-faire-et-les-competences/proteger-les-travailleurs/mesures-employeur-protection-salaries

**Comment by jrduscher** [comment]
Après vérification, et pour info, l'actuel datafiller ne semble pas remonter ces erreurs d'url.
