### ISSUE TITLE
ngramswip_pour_lionel.json

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#296]
[

"indemnité de licenciement",
"Contrat à durée indéterminée",
"Période d'essai",
"rupture conventionnelle",
"arrêt maladie",
"certificat de travail",
"chèque vacances",
"contrat de travail",
"durée du travail",
"délai de carence",
"entretien préalable",
"heures pour recherche d'emploi",
"inspection du travail",
"inspecteur du travail",
"contrôle du travail",
"rupture conventionnelle collective",
"rupture conventionnelle individuelle",
"congés payés",
"poussières   de bois",
"harcèlement moral",
"harcèlement sexuel",
"document unique",
"évaluation des risques professionnels",
"solde de tout compte",
"travail temporaire",
"travail illégal",
"travailleur détaché",
"travail dissimulé",
"accessoires de levage"
  ]

**Comment by jrduscher** [comment]
listing à abonder (WIP)

**Comment by lionelB** [comment]
avec un boost sur un match_phrase la recherche  "chèque vacances" permettrait de mieux remonté par rapport au document ou les occurences "cheque" ou "vacance" apparaisse plusieurs fois sans être à coté.

**Comment by lionelB** [comment]
J'ai fait le tour des expréssions, je pense qu'on est globalement très pertinant

cas bof à vérifier poke @jrduscher  (voir intégrer dans tests unitaires)
- poussières de bois
- évaluation des risques professionnels
- travail temporaire

**Comment by ClementChapalain** [comment]
je ne sais pas trop comment tester ça ? est-ce qu'on est ok ?

**Comment by lionelB** [comment]
ok pour moi, j'ai rajouté les 3 cas dans le spreadsheet
