### ISSUE TITLE
Petit souci de z-index sur la liste de recherche

### ISSUE THREAD

**Issue by jeremiecook** [SocialGouv/code-du-travail-numerique#297]
<img width="1389" alt="capture d ecran 2018-11-20 a 10 28 53" src="https://user-images.githubusercontent.com/88306/48764245-69027200-ecaf-11e8-837c-07e12407822e.png">

**Comment by lionelB** [comment]
est ce que tu pourrais préciser le navigateur ? merci.

**Comment by jeremiecook** [comment]
Oui ! Pardon. Firefox Quantum 64.0b10 (64-bit)
