### ISSUE TITLE
Rendre le contenu d'une contribution (pour une cc accessible) directement via l'url

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#2978]
Pour ce faire, il faudrait:

- Un id pour la contribution générale + un id pour chaque réponse liée à un convention spécifique
- ces contenu spécifique ne permettront pas de modifier sa CC et ne prendront pas un compte une éventuelle CC déj) renseigner auparavant sur le site.
- Ne pas indexer dans la recherche ces contenus spécifique à la CC
- Mais que ces contenus puissent être accessible via une url (et un endpoint ES spécifique) et par google
- Que ces contenus soient présents dans le sitemap
- Les thèmes de ces contenus spécifique reprendront les thèmes de la page "complète"

**Comment by UnbearableBear** [comment]
@lionelB @virginielastisneres 

J'ai mis à jour le doc, n'hésitez pas si il manque un truc 🙏

**Comment by lionelB** [comment]
> ces contenu spécifique ne permettront pas de modifier sa CC 

à voir,  c'est peut être faisable  :)

**Comment by virginielastisneres** [comment]
> > ces contenu spécifique ne permettront pas de modifier sa CC
> 
> à voir, c'est peut être faisable :)

Oui je suis d'accord avec lionel à voir dans un premier temps si cela est possible :)

**Comment by virginielastisneres** [comment]
j'ai une petite question pratique de veille : 
du coup avec cette solution si la contribution générale est modifiée est ce que cela modifiera la contribution générale présente dans les pages des contributions conventionnelles ?

**Comment by UnbearableBear** [comment]
> j'ai une petite question pratique de veille :
> du coup avec cette solution si la contribution générale est modifiée est ce que cela modifiera la contribution générale présente dans les pages des contributions conventionnelles ?

Je suis pas sur de bien saisir la question mais oui, il faut que la source de donnée soit mutualisée, qu'on soit sur la page générale ou sur une page spécifique avec l'info générale. Ce serait ingérable sinon.

**Comment by virginielastisneres** [comment]
> > j'ai une petite question pratique de veille :
> > du coup avec cette solution si la contribution générale est modifiée est ce que cela modifiera la contribution générale présente dans les pages des contributions conventionnelles ?
> 
> Je suis pas sur de bien saisir la question mais oui, il faut que la source de donnée soit mutualisée, qu'on soit sur la page générale ou sur une page spécifique avec l'info générale. Ce serait ingérable sinon.

Super on est d'accord :)
