### ISSUE TITLE
Update dossier // prochaine mise en prod

### ISSUE THREAD

**Issue by CaptainConan** [SocialGouv/code-du-travail-numerique#2979]
**Contexte**
Suite à des changements, il faut faire un update du dossier sur le covid_19 : https://code.travail.gouv.fr/dossiers/ministere-du-travail-notre-dossier-sur-le-coronavirus

**Update dossier**

1. Section CSE et accord collectif

- supprimer « nouveautés : élection du CSE » car date de fin du dispositif au 31/08/2020 
https://code.travail.gouv.fr/information/elections-du-cse-nouveautes-covid-19

2. Section SST
Le nouveau protocole (dénommé désormais « Protocole national pour assurer la santé et la sécurité des salariés en entreprise face à l’épidémie de COVID-19 ») est entré en vigueur le 01/09.

- L'ancien lien source https://travail-emploi.gouv.fr/actualites/presse/communiques-de-presse/article/protocole-national-de-deconfinement-pour-les-entreprises-pour-assurer-la doit être remplacé.

La bonne url est là: https://travail-emploi.gouv.fr/le-ministere-en-action/coronavirus-covid-19/reprise-de-l-activite/protocole-national-sante-securite-salaries

- Le titre doit être changé pour devenir: Protocole national pour assurer la santé et la sécurité des salariés en entreprise face à l’épidémie de COVID-19 

![CDTN sst KO](https://user-images.githubusercontent.com/53531631/92012664-075cac00-ed4d-11ea-860d-464ae7ebd3af.png)

**Comment by UnbearableBear** [comment]
Merci @CaptainConan ! C'est fait ici: https://github.com/SocialGouv/code-du-travail-numerique/pull/2981
C'est tout ce qu'il faut avant la prochaine mise en prod ?
