### ISSUE TITLE
Problème de contraste sur les types de contenus

### ISSUE THREAD

**Issue by jeremiecook** [SocialGouv/code-du-travail-numerique#298]
Pas totalement accessible (même si c'est valide AA)
Proposition de couleur de fond : #dde4ed (à la place de l'actuel "--color-grey")

<img width="287" alt="capture d ecran 2018-11-20 a 10 34 50" src="https://user-images.githubusercontent.com/88306/48764442-f219a900-ecaf-11e8-83c5-bc46ce52d956.png">

**Comment by lionelB** [comment]
@jeremiecook est ce qu'une des 2 couleurs suivantes est envisageable pour éviter de multiplier les couleurs similaire ? 
``` scss
  --color-lighter-grey: #ebeff3;
  --color-light-grey: #c9d3df;
```

**Comment by jeremiecook** [comment]
Tout à fait !

J’aime bien --color-lighter-grey: #ebeff3;

Jérémie Cook
hello@jeremiecook.com
06 63 09 76 32

**Comment by lionelB** [comment]
👍 merci
