### ISSUE TITLE
Problème d'affichage d'un aperçu pdf dans une fiche du ministère

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#2984]
**Description**

Dans une fiche ministère, un pdf est proposé au téléchargement, avec un aperçu visualisable sur la page de la fiche.
https://code.travail.gouv.fr/fiche-ministere-travail/aide-a-lembauche-des-jeunes?q=aide%20%C3%A0%20l%27embauche%20des%20jeunes#Par-qui-et-quand-l-aide-est-elle-versee

Dans le cdtn, cet aperçu ne fonctionne pas. Pour l'utilisateur, deux cas de figure:
- sur les réseaux du ministère: 
![image](https://user-images.githubusercontent.com/37538697/92372544-629bef00-f0fd-11ea-9e69-9cf1efecf334.png)
- hors réseau du ministère, l'aperçu n’apparaît simplement pas, mais l'espace correspondant à l'aperçu existe toujours: il repousse plus bas le lien de téléchargement.

**Comportement attendu**
1) Affichage de l'aperçu comme pour la fiche ministère
2) En cas d'impossibilité technique, supprimer l'espace de l'aperçu pour mettre davantage en valeur le lien de téléchargement.

**Comment by lionelB** [comment]
je ferme c'est un doublon de #2633
