### ISSUE TITLE
Bug sur les recommandations de contenu similaire

### ISSUE THREAD

**Issue by ArmandGiraud** [SocialGouv/code-du-travail-numerique#2988]
**Description**
Sur certaines pages (modèles de couriers) , la recommandation de contenu similaire inclut un lien vers la même page

**Reproduction**
https://code.travail.gouv.fr/modeles-de-courriers/convocation-a-un-entretien-prealable-au-licenciement-economique-de-moins-de-10-salaries-pendant-30-jours

**Comportement attendu**
on souhaite obtenir des pages différentes de celle actuellement consultée

**Screenshots**
![image](https://user-images.githubusercontent.com/22575341/92595010-fc9d9c00-f2a3-11ea-8a29-97ac4679dc6f.png)

**Comment by rmelisson** [comment]
merci Armand, à priori c'est juste sur les modèles de courrier, je vais regarder ça
