### ISSUE TITLE
Facetting suites

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#299]
- [ ] en tant qu'utilisateur, si je choisis une source dans le facetting et qu'il n'y a pas de résultat pour moi:
         - je m'attends bien à la réponse actuelle "Nous n’avons pas trouvé de résultat pour votre recherche."
         - je m'attends à continuer mon parcours en quête de vérité: à des suggestions, d'autres contenus, d'autres sources? UX needed  

- [ ] Déçu ne pas avoir trouvé ma réponse après utilisation du facetting, je remplis mon formulaire de retour déceptif : l'équipe n'a pas le retour sur la sélection des sources qui aboutit à la réponse déceptive ( cela peut nous faire croire qu'un parcours a été déceptif , alors que la réponse existait quand même dans une des autres sources proposées: ex pas de modèle de courrier sur travail de nuit, mais quelques fiches très bien faites sur la question, le formulaire ne dit pas que je cherchais un modèle de courrier)
-> ajouter l'information type de sources dans le formulaire (UX validation needed)

**Comment by jrduscher** [comment]
issue de départ facetting: https://github.com/SocialGouv/code-du-travail-numerique/issues/215

**Comment by jrduscher** [comment]
@jeremiecook , on peut voir ça ensemble?

**Comment by jeremiecook** [comment]
Normalement je passe demain mais j’attends une confirmation d’eMJPM

Jérémie Cook
hello@jeremiecook.com
06 63 09 76 32

**Comment by lionelB** [comment]
Idée: ajouter un lien dans le message affiché qui permet de relancer la recherche sans le filtres "facet"
