### ISSUE TITLE
Affichage du header en page de contenu: difficulté de faire une recherche

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#2993]
**Description**
Remonté par Catherine

Description claire et concise du bug
1. Impossibilité de faire une recherche avec le header principal : 
![image](https://user-images.githubusercontent.com/37538697/93058682-fe82a900-f66f-11ea-8de8-9740c8543a35.png)

2. Le header miniaturisé n’apparaît qu'en remontant la page. 
![image](https://user-images.githubusercontent.com/37538697/93058812-28d46680-f670-11ea-8bdc-2d00ef0a2324.png)

=> Il n'est pas possible de faire une recherche en haut de page, et en cours de lecture sauf, à "scroller" pour remonter, je ne peux pas faire de recherche

**Reproduction**
Ouvrir un contenu, par exemple: 
https://code.travail.gouv.fr/contribution/quelle-est-la-duree-du-conge-de-maternite?q=cong%C3%A9%20de%20maternit%C3%A9
1. Voir le header du haut de page et constater qu'il n'y a pas de champ de recherche
2. Consulter le contenu, et constater que le header n'est pas affiché, qu'il n’apparaît pas au survol, qu'il est affiché uniquement au scroll ver le haut.
3. En conclure qu'il n'est pas facile pour l'user de faire une recherche avec ce header depuis une page contenu.

**Comportement attendu**
Ajouter un nouveau comportement, type on mouseover pour afficher le header
Afficher le champ de recherche dans le header principale

**Comment by lionelB** [comment]
je ferme car le champ de recherche a été rajouté dans le header #2989.
Pour l'affichage du header au scroll, c'est un choix qui vise à privilégier l'a surface d'affichage et qui évite d'avoir à remonter en  haut de page pour faire une recherche
