### ISSUE TITLE
Autres sources de droit raffinés [trop tard pour démo, donc pas urgent]

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#30]
-> Il faudra integrer les fiches services publics
-> Il faudra intégrer les "articles du Code BFC"

Comment intégrer de manière durable d'autres sources de droit raffiné à venir?

**Comment by revolunet** [comment]
de manière durable, idéalement il faudrait que chaque service nous propose soit une API soit un dump de leurs données pour que l'on puisse mettre à jour régulièrement
