### ISSUE TITLE
Modif dossier  

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3010]
## Solution 

Dans le dossier coronavirus : https://code.travail.gouv.fr/dossiers/ministere-du-travail-notre-dossier-sur-le-coronavirus.

Il faut modifier le nom du lien "Protocole national de déconfinement du Ministère du travail" présent dans la rubrique "Santé et sécurité au travail" par "Protocole national pour assurer la santé et la sécurité des salariés en entreprise face à l’épidémie de COVID-19"

+ changement de l'url. Avec cette nouvelle url = https://travail-emploi.gouv.fr/le-ministere-en-action/coronavirus-covid-19/reprise-de-l-activite/protocole-national-sante-securite-salaries

![image](https://user-images.githubusercontent.com/48682104/94129815-220dd680-fe5c-11ea-8de8-a83ac643be69.png)

**Comment by UnbearableBear** [comment]
Already done: https://master-code-travail.dev2.fabrique.social.gouv.fr/dossiers/ministere-du-travail-notre-dossier-sur-le-coronavirus
