### ISSUE TITLE
Kibana : Reporting V1

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3013]
# Contexte 

Très bonne présentation de Kibana ici =>> https://hackmd.io/rHB_eeL5QlWcXAV1blfLXQ?both
En parallèle de la préparation de Kibana, l'équipe métier a été créé un rapport mensuel sur le CDTN comprennant diverses métriques. 
Par conséquent, et afin d'automatiser au mieux ce rapport mensuel, il a été décidé d'intégrer dans Kibana les données utiles au rapport. 

# Solution

A intégrer dans Kibana, le rapport mensuel du CDTN à destination du métier avec les données suivantes : 

1. La fréquentation :

Nombre de visites mensuel 
avec si possible visuel barplot par mois
Nombre de visites depuis le 1er janvier 2020
Nombre de visites par jour en moyenne par chaque semaine 
avec si possible visuel courbe d'évolution de la moyenne pour chaque semaine 
Nombre de visites maximal sur une journée dans le mois 

2. Contenus et recherches populaires :

top 10 des contenus tendances du mois 
top 10 des contenus évolution 3 derniers mois 
top 10 annuelle des contenus
top 10 des recherches tendances du mois 
top 10 annuelle des recherches 
graphique d'armand sur les thèmes populaires 

3. Données sur les conventions collectives

Top 10 des pages des conventions collectives les plus sur consultées sur l'année et sur les 3 derniers mois. 
Top 10 des conventions collectives les plus sélectionnées dans notre moteur de recherche de CCs sur l'année et sur les 3 derniers mois (utiliser tracking mis en place) 
Le pourcentage que représentent nos 51 CCs traitées par rapport à toutes les CCs sélectionnées =>> [liste des 51 CCs traitées](https://docs.google.com/spreadsheets/d/1PiteO5_xy-jMEtRNiAlHhanZCYiEakDG/edit#gid=1150965234)
TOP 20 des CCs locales des métallurgies par mois =>> [liste des cc locales de la métallurgie](https://docs.google.com/spreadsheets/d/1PiteO5_xy-jMEtRNiAlHhanZCYiEakDG/edit#gid=1265766658)
Nombre et nom des CCs non traitées dans le top 50 des CCs sélectionnées

**Comment by rmelisson** [comment]
et aussi, de manière ponctuelle : contenus jamais visité pour Jonathan

**Comment by ArmandGiraud** [comment]
1. La fréquentation :

- [x] Nombre de visites mensuel 
- [x] avec si possible visuel barplot par mois
- [x] Nombre de visites depuis le 1er janvier 2020 
`On a de la donnée que depuis mars`
- [x] Nombre de visites par jour en moyenne par chaque semaine 
`la moyenne c'est indispensable? le nombre de visites par semaine c'est pas mal aussi non?`
- [x] avec si possible visuel courbe d'évolution de la moyenne pour chaque semaine 
- [x] Nombre de visites maximal sur une journée dans le mois 

2. Contenus et recherches populaires :

- [x] top 10 des contenus tendances du mois 
- [x] top 10 des contenus évolution sur les 3 derniers mois 
- [x] top 10 annuelle des contenus
- [x] top 10 des recherches tendances du mois 
- [x] top 10 des recherches évolution sur les 3 derniers mois 
- [x] top 10 annuelle des recherches 
- [ ] graphique d'armand sur les thèmes populaires (impossible dans kibana, à faire à la main)
~~Ponctuellement les contenus zombies : cad les contenus qui n'ont eu aucune visite~~

3. Données sur les conventions collectives

- [x] Top 10 des pages des conventions collectives les plus sur consultées sur l'année et sur les 3 derniers mois. 
- [ ] Top 10 des conventions collectives les plus sélectionnées dans notre moteur de recherche de CCs sur l'année et sur les 3 derniers mois (utiliser tracking mis en place) 
- [ ] Le pourcentage que représentent nos 51 CCs traitées par rapport à toutes les CCs sélectionnées =>> [liste des 51 CCs traitées](https://docs.google.com/spreadsheets/d/1PiteO5_xy-jMEtRNiAlHhanZCYiEakDG/edit#gid=1150965234)
- [ ] TOP 20 des CCs locales des métallurgies par mois =>> [liste des cc locales de la métallurgie](https://docs.google.com/spreadsheets/d/1PiteO5_xy-jMEtRNiAlHhanZCYiEakDG/edit#gid=1265766658)
- [ ] Nombre et nom des CCs non traitées dans le top 50 des CCs sélectionnées

**Comment by ArmandGiraud** [comment]
[Document retour métier](https://docs.google.com/document/d/1SXd498jFd6DIsDH_o7TMElM61mrS2OD3JMniOenP9CA/edit#heading=h.divozzy4zjsb)

**Comment by virginielastisneres** [comment]
@ArmandGiraud pourra t-on faire un point rapide sur ce sujet afin de nettoyer un peu kibana :)

**Comment by Armandgrd** [comment]
Oui, pas de soucis @virginielastisneres , quand tu veux, j'ai plus accès à mattermost par contre, je crois que le certificat a expiré.

**Comment by virginielastisneres** [comment]
> Oui, pas de soucis @virginielastisneres , quand tu veux, j'ai plus accès à mattermost par contre, je crois que le certificat a expiré.

Ah mince bizarre... nous on a bien accès... Après le planning de 14H on pourra se faire le point si ca te va :) on en parle au planning ;) rdv sur la room 1 à 14H
