### ISSUE TITLE
BUG Pas de bouton sur le lien "Notre aide" dans les outils 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3032]
## Problème détecté et solution

Quand je veux cliquer sur notre aide ca me renvoi à la fin du parcours https://code.travail.gouv.fr/outils/preavis-demission
Alors que cela devrait me renvoyer à la modale d'aide à la recherche des CCs comme ici => https://code.travail.gouv.fr/convention-collective
J'ai l'impression que cela est bon également sur les pages des contributions. 
Le problème semble apparaitre que sur les pages des outils où l'on demande la convention collective.

**Comment by lionelB** [comment]
closed by #3034
