### ISSUE TITLE
ML - on n'utilise pas le bon jeux de stop words

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#3033]
Sur cdtn on a 2 jeux de stopwords
 - un jeu pour elastic
 - un jeu pour la vectorisation des document 

Le vectorizer utilise `require("../dataset/stop_words");` qui renvoi le fichier stop_words.json  (et non semantic_stop_words.json)

Concernant les stopwords, il existe un package qui liste les stopwords, est ce qu'on l'utilise ?

**Comment by revolunet** [comment]
https://github.com/stopwords-iso/stopwords-fr ?
