### ISSUE TITLE
Questionnaire aléatoire // Mieux connaître nos utilisateurs

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3056]
# Contexte

Le code du travail numérique a pour objectif de viser les salariés et employeur en particulier ceux de TPE/PME afin de les aider dans la compréhension du droit du travail. 
Plusieurs fois nous nous sommes interrogés sur qui étaient nos utilisateurs réels. Nous avons eu une forte hausse des consultations des articles du code du travail consultés, des requêtes très spécifiques type juridiques ... 
Il est donc important d'en savoir un peu plus et cela pour plusieurs raisons : 
- pour pouvoir adapter notre plan de déploiement 
- améliorer nos parcours 
- aller chercher nos utilisateurs cibles si jamais on se rend compte que ceux ne sont pas les principaux visés qui utilisent notre site. 

# Solution : Un questionnaire 

L'objectif est de créer un questionnaire sur notre site à destination de nos utilisateurs avec 3 questions rapides qui nous permettra de pouvoir avoir une idée plus précise de leur profil. 

## Contenu du questionnaire 

1. introduction 

"Avant de partir...
Vous pouvez nous aider à améliorer notre service en répondant aux 3 questions suivantes. 
Merci pour votre aide !
Souhaitez-vous répondre au questionnaire ? Oui Non"

2. 1ère question

"Vous êtes...
- salarié(e)
- employeur ou particulier employeur
- fonction RH 
- professionnel du droit du travail (avocat, juriste, organisation syndicale…)
- autre (demandeur d’emploi, étudiants, retraités…)"

3. 2ème question

"Quelle est la taille de votre entreprise ? 
- moins de 10 salariés
- de 10 à 249 salariés
- de 250 à 4 999 salariés 
- de 5 000 salariés et plus 
- je suis particulier employeur 
- je ne suis pas concerné(e)"

4. 3ème question 

"Quels sont le(s) contenu(s) que vous souhaiteriez voir enrichi(s) ?
- les fiches sur le droit du travail
- les modèles de documents
- les simulateurs/calculateurs ou autres outils 
- les informations sur une ou des convention(s) collective(s)
- autre(s) contenu(s) 
- je ne sais pas"

5. fin remerciements 

"Merci pour votre aide ! 
Nous espérons vous revoir bientôt."

## Comportement du questionnaire 

- Il faudrait une pop-up en Exit Intent donc qui apparait au moment où la personne clique sur quitter le site
- le questionnaire serait aléatoire (1 visiteur sur 3)
- Il faudrait pouvoir ne pas resoumettre le questionnaire à une personne qui a déjà terminé le questionnaire voire qui a répondu non au fait qu'elle souhaite participer au questionnaire ? (A TRANCHER) 

## Maquettes du questionnaire 

Les maquettes des différentes étapes sont ici =>> https://www.figma.com/file/vDv0zHOEc7m5zhxhcblA94/Survey-conna%C3%AEtre-nos-utilisateurs?node-id=110%3A5408

- une modale classique

- une petite barre de repérage sur l'avancée du questionnaire qui avance à chaque nouvelle question

![Group 34 (1)](https://user-images.githubusercontent.com/48682104/96886617-0bbb6080-1484-11eb-8d08-d1e7c8c3bb67.png)

- les icones ou logo utiles ici et à retrouver en svg dans figma (export SVG)
![Most popular](https://user-images.githubusercontent.com/48682104/96727335-38537780-13b3-11eb-881a-84e05185750f.png)    ![validé](https://user-images.githubusercontent.com/48682104/96727330-37bae100-13b3-11eb-8525-3809b055d5ad.png)   ![url cdtn LOGO](https://user-images.githubusercontent.com/48682104/96727320-3689b400-13b3-11eb-87f5-6dbef81ca560.png)  ![Logo CDTN_CMJN 1 1 (3) 1](https://user-images.githubusercontent.com/48682104/96727327-37224a80-13b3-11eb-8788-2a9b072f3735.png)  

![survey (1)](https://user-images.githubusercontent.com/48682104/96891249-c3eb0800-1488-11eb-8383-135457b9fa56.gif)

## Tracking à mettre en place

Nous souhaiterions pouvoir : 
- connaître la proportion des utilisateurs ayant cliqué pour chaque statut : salarié/employeur/professionnel du droit etc
- connaître la proportion des utilisateurs ayant cliqué pour chaque tranche de taille d'entreprise 
- connaître la proportion des utilisateurs ayant cliqué pour chaque contenus déclarés utiles par les utilisateurs
- connaître toutes les réponses données par un utilisateur

@ArmandGiraud @rmelisson des idées pour le tracking à mettre en place pour avoir toutes ces données. Avec @UnbearableBear nous en avons parlé un peu mais on arrivait pas à une solution qui nous permettait d'avoir toutes ces données à la fois...

**Comment by virginielastisneres** [comment]
@lionelB @UnbearableBear Hello :) on en est où du coup concernant le tracking ? Lionel tu as pu voir s'il existait une solution auprès de la Fabrique ?

**Comment by lionelB** [comment]
pas de solution en place pour l'instant
