### ISSUE TITLE
Gérer les 404 correctement (edit: solved avec next 10 ?)

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#3057]
Actuellement, nos pages 404 renvoient un status 200 sur la plupart des url. 
exemple: https://code.travail.gouv.fr/fiche-service-public/pouet
Dans la console google, on peut constater que tous les contenus dont le slug a recemment changé sont considérées comme du "contenu dupliqué". Google considère la 404 comme une page de contenu normale :shrug:

Il faut toruver un moyen de renvoyer un status 404 à nos utilisateur

**Comment by revolunet** [comment]
<img width="707" alt="Capture d’écran 2020-11-18 à 11 12 10" src="https://user-images.githubusercontent.com/124937/99516873-fb1cde00-298e-11eb-900e-a025157e7d32.png">

**Comment by revolunet** [comment]
<img width="858" alt="Capture d’écran 2020-11-18 à 11 22 21" src="https://user-images.githubusercontent.com/124937/99518045-59968c00-2990-11eb-8244-172942d422da.png">

**Comment by UnbearableBear** [comment]
Lorsque la page existe (dans le dossier `/pages`) mais que le fetching de data retourne une 404 on renvoie un status 200 côté front :/

**Comment by revolunet** [comment]
Oui visiblement il nous manque le `res.statusCode` quand on ne reçoit pas d'info de l'API

https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-frontend/pages/fiche-service-public/%5Bslug%5D.js#L24

https://github.com/vercel/next.js/issues/746#issuecomment-305075299

**Comment by UnbearableBear** [comment]
hunhunnn je vais tester ça ! on utilise pas `res` pour le moment, on met statusCode dans les props directement, that's probably why
