### ISSUE TITLE
Rendre accessibles les pages des conventions collectives dans le moteur de recherche

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3064]
# Contexte

Toujours dans le contexte de l'analyse d'armand sur l'utilisation de notre moteur de recherche des CCs, nous avons également regarder la recherche des CCs dans notre moteur général. (résumé ici > https://docs.google.com/presentation/d/1u7FisZo5RaB47wWgUDZ_OXqpGlkP5UmD7dHfSPMqFGE/edit#slide=id.ga422df53d1_0_131).
Rien que sur 3 mois, pour uniquement les 51 CCs traitées et uniquement avec une recherche classique "Convention collective + nom de la CC", il y a eu 230 recherches effectuées. 
Or si on regarde par exemple des recherches fréquentes voici les résultats que nos utilisateurs obtiennent : 
![image](https://user-images.githubusercontent.com/48682104/96703393-15b16680-1393-11eb-8824-a1f30531e52c.png)
![image](https://user-images.githubusercontent.com/48682104/96703442-2235bf00-1393-11eb-996a-5d4815fddc7e.png)

Ils n'ont aucune information sur la requête demandée alors qu'on a une page dédiée sur ces CCs avec à la fois les questions fréquentes (contributions) et le travail de Florent 'exemple de page : https://code.travail.gouv.fr/convention-collective/650-metallurgie-ingenieurs-et-cadres).

Ces pages étant une plus value du code du travail numérique ne sont pas accessible via notre moteur de recherche général (rappel : la recherche est l'action première des utilisateurs sur la home page). Pourtant ces pages  sont au final des contenus comme les autres. 

# Solution 

- [x] Mettre dans ElasticSearch les pages des CCs afin de les rendre trouvable dans notre moteur de recherche
Dans un 1er temps, on ne rajoute **que les 51 CCs traitées et des métallurgies** (liste ici => https://docs.google.com/spreadsheets/d/1PiteO5_xy-jMEtRNiAlHhanZCYiEakDG/edit#gid=1150965234). Cela a pour but d'éviter d'avoir trop de bruit dans notre moteur et pour le moment les autres pages n'ont pas vraiment d'apport pour l'utilisateur car on renvoi vers Légifrance. 

- [x] Pour la présentation de la tuile de ces pages CCs : 
=> le thème serait : convention collective
=> le titre : le titre de la page
=>la description : si possible ca serait bien que cela soit la description mise sous la section "Questions-réponses fréquentes" de nos pages afin d'attirer l'attention et permettre une compréhension pour l'usager de ce qu'il peut trouver. 
_Exemple maquette :_ 
![image](https://user-images.githubusercontent.com/48682104/96702777-62487200-1392-11eb-82ef-3d784ab5c4e3.png)

**Comment by rmelisson** [comment]
on rajoute donc :
- les 50 CCs dans le documents
- toutes les CCs en lien avec la métallurgie

**Comment by rmelisson** [comment]
Commentaires v1 :
- Metallurgie : booster CC nationale vs. departementales
- CC trop haute : handicap / hospitalisation enfant / transport
- CC trop basse : syntec / cc chimie
