### ISSUE TITLE
Problèmes à l'impression des pages

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#3066]
**Description**
Problèmes à l'impression des documents depuis le code du travail : une partie du contenu est manquant et la mise en forme n'est pas bonne ( pages blanches, pages avec l'entête du site uniquement...)

[Sécurité et santé des travailleurs _ les obligations générales de l’employeur et sa responsabilité.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/5428319/Securite.et.sante.des.travailleurs._.les.obligations.generales.de.l.employeur.et.sa.responsabilite.pdf)

**Reproduction**
Le contenu du site  sur lequel le constat a été effectué:
https://code.travail.gouv.fr/fiche-ministere-travail/securite-et-sante-des-travailleurs-les-obligations-generales-de-lemployeur-et-sa-responsabilite

**Comment by jrduscher** [comment]
### Autre exemple complémentaire: 

Un scroll vers le haut en pleine page suivi d'un ctrl-p fait apparaitre le champ de recherche du site sur le document imprimé relatif au contenu suivant  https://code.travail.gouv.fr/contribution/quelle-est-la-duree-de-preavis-en-cas-de-depart-a-la-retraite

![image](https://user-images.githubusercontent.com/37538697/97193109-eb9fe000-17a8-11eb-9236-61cd081ae8c2.png)

**Comment by UnbearableBear** [comment]
Alors j'ai essayé de repro le contenu tronqué sur chrome (latester) safari (lastest) et firefox (latest), mais j'ai la page en entier à chaque fois. A mon avis, peut-etre que l'option d'impression des pages était renseigné à 0-2 ce qui coupe effectivement les pages suivantes sur ton navigateur.

Concernant la search là pour le coup je pense que c'est un bug qui a été déjà résolu dans une autre PR, impossible à repro non plus sur chrome, firefox et safari.

Je cloture donc cette issue; n'hésite pas à réouvrir si tu as toujours le problème, en précisant le navigateur.

Le pdf généré chez moi:
[Sécurité et santé des travailleurs : les obligations générales de l’employeur et sa responsabilité.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/5880838/Securite.et.sante.des.travailleurs.les.obligations.generales.de.l.employeur.et.sa.responsabilite.pdf)
