### ISSUE TITLE
Bug report : l'adresse de contact codedutravailnumerique@travail.gouv.fr ne fonctionne pas !

### ISSUE THREAD

**Issue by undeuxdroit** [SocialGouv/code-du-travail-numerique#3069]
**Description**
j'ai envoyé un mail à codedutravailnumerique@travail.gouv.fr et j'ai reçu le message d'erreur suivant : 

**Reproduction**

Exchange2013-Postmaster@eridan.social.gouv.fr
5:25 AM (11 minutes ago)
to me

Échec de la remise pour ces destinataires ou groupes :

code-du-travail-numerique@orion.gouv.TO.RES
L'adresse de messagerie que vous avez entrée est introuvable. Vérifiez l'adresse de messagerie du destinataire et essayez de renvoyer le message. Si le problème persiste, contactez le support technique de votre organisation.

Informations de diagnostic pour les administrateurs :

Serveur de génération : PRO075001EXH002.eridan.social.gouv.fr
code-du-travail-numerique@orion.gouv.TO.RES
Remote Server returned '550 5.1.1 RESOLVER.ADR.RecipNotFound; not found'
En-têtes de message d'origine :

Received: from PRO075001EXH011.eridan.social.gouv.fr (192.168.40.12) by
 PRO075001EXH002.eridan.social.gouv.fr (192.168.40.3) with Microsoft SMTP
 Server (TLS) id 15.0.1497.2; Mon, 26 Oct 2020 05:25:48 +0100
Received: from PRO-HUB02-0921.orion.gouv (192.168.40.24) by
 PRO075001EXH011.eridan.social.gouv.fr (192.168.40.12) with Microsoft SMTP
 Server (TLS) id 15.0.1497.2 via Frontend Transport; Mon, 26 Oct 2020 05:25:48
 +0100
Received: from pro093001app060.social.gouv.fr (10.200.4.222) by
 mailint2.orion.gouv (10.200.4.229) with Microsoft SMTP Server id 8.3.485.1;
 Mon, 26 Oct 2020 05:25:25 +0100
Received: from pps.filterd (pro093001app060.social.gouv.fr [127.0.0.1])	by
 pro093001app060.social.gouv.fr (8.16.0.42/8.16.0.42) with SMTP id
 09Q4Oq0D029531	for <codedutravailnumerique@travail.gouv.fr>; Mon, 26 Oct 2020
 05:25:25 +0100
Authentication-Results: social.gouv.fr;
	spf=softfail smtp.mailfrom=yyyyyy@xxxxxxxx.com;
	dkim=pass header.d=xxxxxxxx-com.20150623.gappssmtp.com header.s=20150623;
	dmarc=none
Received: from mail-il1-f182.google.com (mail-il1-f182.google.com
 [209.85.166.182])	by pro093001app060.social.gouv.fr with ESMTP id
 34cc9su1vt-1	(version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128
 verify=OK)	for <codedutravailnumerique@travail.gouv.fr>; Mon, 26 Oct 2020
 05:25:24 +0100
Received: by mail-il1-f182.google.com with SMTP id c11so3961781iln.9
        for <codedutravailnumerique@travail.gouv.fr>; Sun, 25 Oct 2020
 21:25:24 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=xxxxxxxx-com.20150623.gappssmtp.com; s=20150623;
        h=mime-version:from:date:message-id:subject:to;
        bh=RW53JfMSgCzqx6rKcGiKq8ct/0Fs4qDZncPehZI/O/c=;
        b=oV4XoJ1ktRBSPjmc0wNxmZ/QG8lYiop2Vx1qk+B4N7laN1KRFrJ5Jmwil8EyZMRq3N
         0mzBS2/yfPoV3B3qLCqbwedveZY3Z5QKQ/zgguenrEx/rOwCDY4Ip5+hXvBlR1HJPYRW
         Jj6O3JxHHmJcPzKPpwa8x6omFTPFiYxce+1z2THT2H9ioFDt0nyCRbc04HlXc4ghyF5d
         51uWZp4wz9nrmAtBpyxepU6oiDIAeGQLVlC5WoBzjliTdb8Nr3fTc5SW7CbnTMyBI/jN
         G+jIx043Dn9NMzbugebbgdSG2OgMwhuSfwDex3lohxs0KzIlJdVAak4pB+UFO0ulXvbL
         MZFQ==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:mime-version:from:date:message-id:subject:to;
        bh=RW53JfMSgCzqx6rKcGiKq8ct/0Fs4qDZncPehZI/O/c=;
        b=koUmbicejwZUJ/9lYB+j+tOmUQ8GYDMhCacg2xOENLXaI6JZV9MKT97ht4eO8XzVNK
         RyhADr28+8yk37t1X4P9ejPS6WpArMl7J86c0y3gT022QPp+GeC2WFkAENkT6XbqquXM
         YBHhlGrjQGy6hxrGV26pc2cOANj7VezEBFdNN5c2d4Ar0cHd+4gBrQwQy4Vi9cIec6Iq
         ZFFxZUtCx86oNrH3wSNOYCZHxXkoGfr6+qpMWiZ7h2s5SZ/sOpPHL5vosfEkbh/ZW1wQ
         PBFxKcovT7rBCKM8OE5OWLPYvW5bauWR6lwmFmSJLi1hQGsK9XOIrNbJshUz6xPLjTg7
         J6wg==
X-Gm-Message-State: AOAM532sBKw3Zzj3Wn3Ib5Y4wXJp19jB5ccaSjk6Oymw9YXbPrWe/kHi
	ryHdije5DhLkl/N7TGy3zFXOkTi/E5GFdlIMRg4jxt52cYoZVzWO
X-Google-Smtp-Source: ABdhPJxqyXkv58SXkOGjdvTLGecuqmrip+F2gL6Erl67lGASYvOV0+vH6dJFrbZjqdKQSdENuSIezYWCbnAA2Rw4Jgc=
X-Received: by 2002:a92:670e:: with SMTP id b14mr9435119ilc.36.1603686321920;
 Sun, 25 Oct 2020 21:25:21 -0700 (PDT)
From: yyyyyy xxxxxxxx <yyyyyy@xxxxxxxx.com>
Date: Mon, 26 Oct 2020 05:24:45 +0100
Message-ID: <CAEybsgY_j4qHjSH68OOAjzKbvMZ1eK0+ei8Dapmm_dXKUJ_YMg@mail.gmail.com>
Subject: =?UTF-8?Q?Erreur_dans_le_formulaire_pour_le_calcul_de_l=27indemn?=
	=?UTF-8?Q?it=C3=A9_de_pr=C3=A9carit=C3=A9?=
To: <codedutravailnumerique@travail.gouv.fr>
Content-Type: multipart/related; boundary="0000000000008ddbd705b28b51df"
X-CLX-Shades: MLX
X-CLX-Response: 1TFkXGxIdEQpMehccGhEKWUQXYWhQTmBhWRMYHGsRClhYF2NiUH5GfRJcYGh mEQp4ThdgaXlweVBiSFgFehEKeUwXY31GQmVjQHBoRF8RCkNIFwcSEQpDWRcHEx0RCkNJFxoEGh oaEQpZTRdnZnIRCllJFxpxGhAadwYbHB1xHhwQGncGGBoGGhEKWV4XaGN5EQpJRhdHQ0RDWV5YU
 09HWkZFU0xYdVpYRU5fSV5DRUQRCkNOFxlwX3BYWHUYG1pCHFh6QGNrcEgSR1tefVpIXR1cWlB+ EQpYXBcfBBoEGBscBRsaBB0aBB4fBBsaGBAbHhofGhEKXlkXfVMFeHoRCk1cFxkaGhEKTFoXaGl CTWkRCkJPF21tUk1rbFtvSGxtEQpDWhcYGhMEEh8EGxwcBBsSGBEKQl4XGxEKQkUXZGlpZ0kYf1
 8FQFsRCkJOF2BpeXB5UGJIWAV6EQpCTBdjYlB+Rn0SXGBoZhEKQmwXZnh4Q3lpZ1tPHwERCkJAF 2FeHU16Xl9pb1tiEQpCWBdlf2YcRl97E2tsYhEKWlgXGBEKeUMXYRkFXkBYfnATWkkRCnBoF2RZ WB95RhpQcAFeEBkaEQpwaBdkYU19XXxafW5BcxAZGhEKcGgXZB1ffm9DemZcGmAQGRoRCnBoF2Y
 aEkEYQ3JPbRp6EBkaEQpwaBdnHVBQAR1HeQVYZhAZGhEKcH0XZ2JEcmJ/ZllzGh4QGRoRCnB9F2 Jsf2ZOQ1haHkFMEBkaEQpwYxdteRhbSXxccEtdexAZGhEKcH8Xenx/ElhHQ3hsWm8QGxocEQpwX xdofE1tYh4FexxmYhAZGhEKcH8XZGllTWJeX25IS0gQExgRCnBfF2sBcmxoQR9DQUxvEB4SEQpw
 bBdjclp+WUVkfUIZeRAZGhEKbX4XGhEKWE0XSxEg
MIME-Version: 1.0
X-Proofpoint-SPF-Result: softfail
X-Proofpoint-SPF-Record: v=spf1 include:mx.ovh.com ~all
X-Proofpoint-Virus-Version: vendor=fsecure engine=2.50.10434:6.0.235,18.0.737
 definitions=2020-10-26_02:2020-10-23,2020-10-25 signatures=0
X-Proofpoint-Spam-Details: rule=inboundspam_notspam policy=inboundspam score=0 spamscore=0
 impostorscore=0 bulkscore=0 clxscore=187 lowpriorityscore=0
 priorityscore=60 mlxlogscore=769 phishscore=0 adultscore=0 mlxscore=0
 malwarescore=0 suspectscore=0 classifier=spam adjust=0 reason=mlx
 scancount=1 engine=8.12.0-2009150000 definitions=main-2010260028
Return-Path: yyyyyy@xxxxxxxx.com

**Comment by UnbearableBear** [comment]
Bonjour, merci beaucoup d'avoir remonté ce problème, nous allons regarder ça très prochainement !

**Comment by UnbearableBear** [comment]
Le problème est résolu ! N'hésitez pas à revenir vers nous si il ressurgit. Encore merci d'avoir remonté le problème.

**Comment by undeuxdroit** [comment]
ok
c'est l'autre bug que j'avais remonté avant qui est plus important (à mon sens)

**Comment by UnbearableBear** [comment]
Je revien vers vous rapidement à ce sujet
