### ISSUE TITLE
Erreur dans le formulaire pour le calcul de l'indemnité de précarité

### ISSUE THREAD

**Issue by undeuxdroit** [SocialGouv/code-du-travail-numerique#3070]
il y a une erreur dans le formulaire [https://code.travail.gouv.fr/outils/indemnite-precarite](https://code.travail.gouv.fr/outils/indemnite-precarite)

A la troisième étape, _"informations générales"_ il est demandé _"Le salarié a-t-il refusé de renouveler le CDD alors que le CDD comportait **une clause de renouvellement automatique** ?"_
Et il faut répondre non à cette question, sinon il est indiqué _"Le salarié en CDD qui refuse le renouvellement de son CDD alors que son contrat prévoyait son renouvellement automatique n’a pas le droit à une prime de précarité."_

Sauf que une clause de renouvellement automatique de CDD **ça n'existe pas et ça n'aurait même aucun sens** puisque le principe est que le CDD ne peut être renouvelé plus que la convention collective de branche ne le permet et, par défaut, 2 fois, selon le code du travail 
(cf. not. [https://www.service-public.fr/particuliers/vosdroits/F38#:~:text=Un%20CDD%2C%20quel%20que%20soit,%C3%AAtre%20renouvel%C3%A9%20que%202%20fois.](https://www.service-public.fr/particuliers/vosdroits/F38#:~:text=Un%20CDD%2C%20quel%20que%20soit,%C3%AAtre%20renouvel%C3%A9%20que%202%20fois.))

Bien cordialement
tc

**Comment by UnbearableBear** [comment]
Bonjour,

Merci d'avoir remonté cette anomalie. Dès que les experts juridiques de notre côté auront confirmé l’erreur, nous ferons le correctif nécessaire. Nous vous tiendrons informé de la résolution.

Cordialement et en vous remerciant de l'intérêt que vous portez au CDTN

**Comment by undeuxdroit** [comment]
vous avez l'adresse mail du RH des experts juridiques à qui je peux adresser mon cv ? (je suis sérieux - cela m'intéresse)

**Comment by virginielastisneres** [comment]
> vous avez l'adresse mail du RH des experts juridiques à qui je peux adresser mon cv ? (je suis sérieux - cela m'intéresse)

Bonjour, 

Je vous propose d'envoyer votre cv à l'adresse suivante afin de contacter l'équipe du code du travail numérique : codedutravailnumérique@travail.gouv.fr. 

Je vous remercie pour votre intérêt et vous souhaite une bonne journée.

**Comment by undeuxdroit** [comment]
maintenant qu'elle fonctionne :-) 
à très vite !
