### ISSUE TITLE
Calculateur d'indemnité de licenciement , CCN: detection OPE

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#308]
Comment aider l'usager à répondre à cette question 

> Votre entreprise est-elle affiliée à une des organisations patronales employeur ? ( signataire des textes conventionnels)

 -  Prévoir un « je ne sais pas » : avec une modal de wording (de  type : si votre entreprise est affiliée, dans le cas d’une indemnité de licenciement pour motif économique et au regard de votre situation vous pourriez prétendre à une indemnisation particulière, demandez conseil à vos représentants du personnel et / ou prenez contact avec les services de renseignement juridique en DIRECCTE) et une poursuite sur l’indemnité « étendue/ non affilié »

 - Voir avec DGT si OPE seraient prêtes à nous partager leurs listes d’adhérents.

 - Voir avec BDCC, s’il est possible de préciser au moins les orgnisations patronales signataires en fonction des textes/CCN  non étendues qu’on utilse dans les calculs ( possible à la main aussi du coup)

**Comment by jrduscher** [comment]
la question qui nous préoccupe touche prioritairement l'indemnité de licenciement. Pour le reste il faut creuser mais cela est moins prioritaire ( ne concerne que les textes non étendus publiés sur legifrance,à savoir notamment les plus importants)

**Comment by jrduscher** [comment]
Kali  nous donnera surement de quoi résoudre, je viens de voir ça j'avais jamais fait attention:

KALI: https://www.legifrance.gouv.fr/affichCacheMenu.do?type=conv&option=convCollSommaire

**Comment by ClementChapalain** [comment]
plus d'actualité
