### ISSUE TITLE
EDGE: Affichage, suggester et fonction de recherche CCN ne fonctionnent pas

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#3117]
**Description**
Différents bugs constatés sous les accordéons ne s'ouvrent pas ( et ne délivrent pas leurs précieuses informations) dans **Edge** 
Microsoft Edge 42.17134.1098.0

1. Aucun suggesteur dans el moteur principal et celui des ccn( la fonctionnalité de recherche des CCN est inopérante).

2. les accordéons ne s'ouvrent pas ( et ne délivrent pas leurs précieuses informations) dans **Edge** 
Microsoft Edge 42.17134.1098.0
( mais fonctionnement parfaitement sous Chrome, testé aussi avec succès sous Edge Mobile), par exemple:

**Reproduction**
https://code.travail.gouv.fr/fiche-ministere-travail/plomb?q=contra#Les-moyens-de-prevention
https://code.travail.gouv.fr/contribution/quelles-sont-les-conditions-de-la-clause-de-non-concurrence

**Comment by lionelB** [comment]
ca sent le bug de transpil :/

**Comment by jrduscher** [comment]
### Détail de navigation pour la reproduction des bugs précités.
1. Ouverture de Edge
2. ouverture de la page principale: code.travail.gouv.fr
3. Je tape "contrat" dans le moteur de recherche. Aucun contenu n'est suggéré, mais je peux  sélectionner ok et observer une liste de résultats correspondant à la saisie.
4. Dans la liste des résultats, je vais dans la première fiche proposée: https://code.travail.gouv.fr/fiche-service-public/contrat-de-professionnalisation?q=contrat
Je constate que les accordéons ne fonctionnent pas.
5. Scroll vers le haut toujours dans la fiche pour afficher le header. Dans le champ de recherche, je retape toujours "contrat", il ne m'est toujours pas proposé de suggestion de recherche. j'arrête là.

___
6. Dans ce même header, je vais dans la boite à outils, puis dans convention collective: je tape "16" dans le moteur de recherche de convention collective. il ne se passe rien. je tente d'appuyer sur entré eau cas où. Même résultat.
7. Je retente avec "transport". il ne se passe toujours rien. Je m'arrête là.

___
8. Je reviens sur la Home. Je tape" durée période essai" puis je sélectionne "ok". Je sélectionne le premier contenu, la contribution "https://code.travail.gouv.fr/contribution/quelle-est-la-duree-maximale-de-la-periode-dessai-sans-et-avec-renouvellement?q=dur%C3%A9e%20p%C3%A9riode%20essai"
9. J'ouvre cette contribution et descend en bas de page au champ" Que dit votre convention collective ?", je teste une saisie de "16" et "transport". Il ne se passe rien.

**Comment by UnbearableBear** [comment]
@virginielastisneres Des retours sur le nombre d'utilisateurs que ça représente ? (edge version antérieure à la 5x) Version actielle de edge: 8x, 100% fonctionnelle

**Comment by virginielastisneres** [comment]
@jrduscher le bug est-il toujours présent sur Edge ?
