### ISSUE TITLE
Page CCN, signalement de faute d'orthographe

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#3143]
### Anomalie rencontrée et solution envisagée

Dans la page suivante: 

https://code.travail.gouv.fr/outils/convention-collective

- Dans la section "Articles de la convention collective", 

pour les thèmes suivants ci-après, "fond" doit être corrigé par "fonds" (avec s https://www.cnrtl.fr/definition/fonds)
>Fond financement paritarisme : mutualisation
>Fond formation professionnelle : mutualisation

### Reproduire l'anomalie:
https://code.travail.gouv.fr/convention-collective/1518-animation

**Comment by lionelB** [comment]
il y a aussi celle la dans le kali-block 
![image](https://user-images.githubusercontent.com/160320/99774828-98525080-2b0e-11eb-8281-9b3e6e3e08ac.png)
