### ISSUE TITLE
Récupérer les mots commençant par "é" dans le glossaire de l'admin 

### ISSUE THREAD

**Issue by CaptainConan** [SocialGouv/code-du-travail-numerique#3157]
**Récupérer les mots commençant par "é" dans le glossaire de l'admin **

Les mots du glossaire commençant par "é", présents sur le CDTN ne sont pas dans le glossaire de l'admin. Il faut les y intégrer.
Il s'agit de "éligible" et "état d'urgence sanitaire".
![CDTN Glossaire KO](https://user-images.githubusercontent.com/53531631/100078320-b20fd280-2e43-11eb-886c-dadd17aa35c3.png)

**Comment by UnbearableBear** [comment]
Alors c'est pire que ça, ils y sont mais je ne le affiche pas 😱
