### ISSUE TITLE
Feedback utilisateur : ajouter l'url de la page résultat déceptive

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#316]
- [ ] ajouter l'url de la page résultat au message transmis à l'équipe lors du signalement utilisateur ( on doit avoir l'url+ la question+ motif)
 - [ ] ajouter l'url du contenu sélectionné dans les résultat transmis à l'équipe lors du signalement utilisateur ( on doit avoir l'url+ la question+ motif)

https://trello.com/c/BJorXwCz/301-dans-le-feedback-ajouter-la-r%C3%A9ponse-r%C3%A9sultat-aux-donn%C3%A9es-remont%C3%A9es

**Comment by lionelB** [comment]
pour l'instant on transmet la recherche de l'utilisateur. 
pour avoir l'url il faut rajouter code-du-travail-numerique.social.gouv.fr/?q=la-recherche

**Comment by jrduscher** [comment]
Ok, c'est déjà un élément; après c'est plus carrément sur le résultat en lui même ( la fiche, l'article la question réponse consultée par l'user) .

**Comment by lionelB** [comment]
oki je comprends mieux ! 
Donc si on utilise le pouce haut, il faudrait aussi transmettre le contenu consulté !

**Comment by jrduscher** [comment]
Yep, même si pour l'instant on ne sait pas quoi en faire exactement, si on peut stocker des parcours satisfaisants quelque part, à terme les données pourarient être intéressantes pour améliorer le parcours utilisateur.

**Comment by jrduscher** [comment]
Les remontées des pouces hauts et pouces bas doivent pouvoir etre remontées pour être consultées dans le piwik

**Comment by lionelB** [comment]
fix by #479
