### ISSUE TITLE
Fiche Service-Public.fr vide : changement de la fiche avec maintien de l'url

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3163]
# Problème 

Il y a une fiche Service-Public.fr nommée Licenciement économique : entretien préalable qui est ici https://code.travail.gouv.fr/fiche-service-public/licenciement-economique-entretien-prealable et qui est VIDE. 

![Capture d’écran 2020-11-25 à 10 41 55](https://user-images.githubusercontent.com/48682104/100210121-e7cbbe80-2f0a-11eb-80bd-37ba4c44650e.png)

Quand on clique sur la source de cette fiche sur Service-Public on arrive sur le thème licenciement : https://www.service-public.fr/particuliers/vosdroits/N481 et non la fiche elle-même. 
La fiche elle même existe bien mais sous une autre url : https://www.service-public.fr/particuliers/vosdroits/F13782

Il semblerait qu'ils aient déplacé la fiche sous une nouvelle url et utilisée l'ancienne url pour un autre contenu mais sans redirection. 

# Solution 

Il faudrait que l'on puisse gérer ces changements de contenus et ce manque de redirection d'une certaine manière...

**Comment by virginielastisneres** [comment]
J'ai découvert une nouvelle fiche ca serait bien de faire une passe ou de trouver un moyen de détecter ces pages vides car honnêtement elle pollue le cdt. 

Ici la fiche de SP sur la période d'essai qui est un sujet assez important... https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/fiche-service-public/periode-dessai
Cette fiche m'est proposée sur le coté alors qu'elle est vide 
![image](https://user-images.githubusercontent.com/48682104/105361596-27a4de80-5bfa-11eb-8876-d24858efefee.png)

Ce que je comprends pas avec cette fiche c'est que la bonne fiche sur la période d'essai est celle ci : https://www.service-public.fr/particuliers/vosdroits/F1643 je la vois bien dans notre liste des fiches SP mais impossible à trouver sur le site... https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/themes/periode-dessai

Elle est surement pas thémée mais dans ce cas cela signifie qu'il y a un soucis avec notre système car j'ai pas de fiche à thémer dans le datafiller... 
![image](https://user-images.githubusercontent.com/48682104/105362597-5d969280-5bfb-11eb-81a3-8459c4c1b431.png)

**Comment by UnbearableBear** [comment]
duplicate of https://github.com/SocialGouv/cdtn-admin/issues/263 and https://github.com/SocialGouv/cdtn-admin/issues/133
Qui plus est, les fiches qui posaient problème sont désormais remplies à nouveau 👍
