### ISSUE TITLE
[Admin] Création d'une page de contenu propre

### ISSUE THREAD

**Issue by CaptainConan** [SocialGouv/code-du-travail-numerique#3189]
**Objectif**
Pouvoir créer une page de contenu via l'admin.
Il existe 3 types de pages de contenu propre:

1. Texte seul (titre et références): https://code.travail.gouv.fr/information/rupture-conventionnelle-nouveautes-covid-19
2. Plusieurs accordéons de texte: https://code.travail.gouv.fr/information/interessement-et-participation-nouveautes-covid-19
3. Plusieurs accordéons comprenant différents types de contenus (texte, infographie): https://code.travail.gouv.fr/information/covid-19-integrer-le-risque-sanitaire-dans-lentreprise-protocole-national

**Comportement attendu**
Permettre de construire, sauvegarder, puis créer une page de contenu propre
https://www.figma.com/file/VqjRDrzxGAX1y0b61XZ8C3/Interface-admin%2Fveille?node-id=0%3A1

**Comment by lionelB** [comment]
moved to https://github.com/SocialGouv/cdtn-admin/issues/207
