### ISSUE TITLE
Dossier aides à l'embauche et au maintien à l'emploi

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3200]
# Contexte

Dossier fait et suivi par @jrduscher 

Il a été fait le choix pour balancer le dossier licenciement de créer un dossier dédié à l'incitation à l'embauche et au maintien de l'emploi.
L'objet de ce développement est permettre sa validation dans des conditions réelles. La validation se fera sur la branche. 
Ce dossier contient des contenus déjà hébergés sur le CDTN et quelques ressources externes (sous la forme de liens externes). Il est semblable au dossier Coronavirus avec toutefois des particularités propres. 

# Solution 

## Maquette du dossier 

https://www.figma.com/file/hwadyHO3FGj0NKAPFDUYf1/Aides-%C3%A0-l'embauche?node-id=219%3A1

Certains aspects graphiques les pictos seront revus en vue de la mise en prod définitive. 

## Structure & Comportement attendus 

Comme pour le dossier Coronavirus : 
- un titre : "Aides aux entreprises : recrutement et maintien à l’emploi"
- une description : "Retrouvez ici l’essentiel des aides au recrutement (aides financières, contrats aidés...) et des dispositifs d’accompagnement pour maintenir l’emploi notamment pour les entreprises en difficultés (activité partielle, accord de maintien de l'emploi...)"
- une section contenus populaires
- une section par thèmes
- un sommaire sur le côté pour retrouver les thèmes

#### Différences par rapport au dossier Coronavirus : 
- un **bouton "voir plus"** à ajouter dès qu'il y a plus de 4 liens sauf contenus populaires qui n'est pas une section thème à proprement parlé
- les sections sont triés par **sous-thèmes** : "Aides pour recruter", "Aides pour maintenir l'emploi", "Outils et ressources utiles". Ces sous-thèmes ne sont pas cliquables et sont présents dans le sommaire et dans le corps du dossier. Ils ont également un design différent des sections pour bien les différencier, il sont à l'image des thèmes dans nos cartes ou contenus. 

## Les données à intégrer 
https://docs.google.com/spreadsheets/d/1yw41rG43gTviJ1KNfJ6XB6FJ4T7_NAqM4PEDHEsUz7Y/edit#gid=1006759695
Le fichier contient les liens à intégrer au dossier classés par thèmes dans les onglets avec le titre des liens.

**Comment by lionelB** [comment]
> Différences par rapport au dossier Coronavirus :

 cela veut dire qu'on va rendre les dossiers paramétrables pour pouvoir supporter
- le déclenchement du bouton voir plus
- l'utilisation possible de sous-thèmes

**Comment by virginielastisneres** [comment]
> > Différences par rapport au dossier Coronavirus :
> 
> cela veut dire qu'on va rendre les dossiers paramétrables pour pouvoir supporter
> 
> * le déclenchement du bouton voir plus
> * l'utilisation possible de sous-thèmes

Honnêtement lionel j'aurais bien voulu dire oui, mais de ce que je comprends il vaut mieux ne rien prévoir pour l'administration des dossiers pour l'instant car : chaque dossier doit pouvoir avoir sa propre structure ... donc potentiellement en 21 si on a un autre dossier ca pourrait être complètement différent

**Comment by UnbearableBear** [comment]
> Honnêtement lionel j'aurais bien voulu dire oui, mais de ce que je comprends il vaut mieux ne rien prévoir pour l'administration des dossiers pour l'instant car : chaque dossier doit pouvoir avoir sa propre structure ... donc potentiellement en 21 si on a un autre dossier ca pourrait être complètement différent

Il faudra faire les modifications côté côté cdnt quoi qu'il en soit

**Comment by lionelB** [comment]
> le déclenchement du bouton voir plus

si pas de valeur > on affiche tout, sinon on utilise la valeur pour configurer le "voir plus". Cela permet d'éviter de migrer les données.

> l'utilisation possible de sous-thèmes

format des références actuelles: 
```json
{
   "refs": [{
        "url": "/fiche-service-public/arret-maladie-indemnites-journalieres-versees-au-salarie",
        "title": "Arrêt maladie : indemnités journalières versées au salarié"
   }]
}
```

proposition de migration 
```json
{
   "children": [
       {
          "category": "SOUS LABEL",
          "refs": [{
            "url": "/fiche-service-public/arret-maladie-indemnites-journalieres-versees-au-salarie",
            "title": "Arrêt maladie : indemnités journalières versées au salarié"
          }]
      }]
}
```
and `category` field is non mandatory

I also propose to remove `position` and use the array order for that.

**Comment by UnbearableBear** [comment]
```
{
  "document": {
    "populaires": [
      {
        "url": "/information/covid-19-les-mesures-de-protection-en-entreprise-protocole-national",
        "title": "Covid-19 : Les mesures de protection en entreprise (Protocole national)"
      },
      {
        "url": "/information/covid-19-integrer-le-risque-sanitaire-dans-lentreprise-protocole-national",
        "title": "Covid-19 : évaluer le risque sanitaire (document d'évaluation des risques) [Infographie]"
      }
    ],
    "sections": [
      {
        "categories": [
          {
            "id": "no-label",
            "icon": "Star",
            "refs": [
              {
                "url": "/fiche-service-public/arret-maladie-indemnites-journalieres-versees-au-salarie",
                "title": "Arrêt maladie : indemnités journalières versées au salarié"
              },
              {
                "url": "https://www.service-public.fr/particuliers/actualites/A14380",
                "title": "Personnes vulnérables"
              },
              {
                "url": "https://declare.ameli.fr/cas-contact/conditions",
                "title": "Cas contact : demander un arrêt maladie en ligne"
              }
            ],
            "title": "Je suis une catégorie sans label, bien placée"
          }
        ]
      },
      {
        "label": "Aides pour recruter",
        "categories": [
          {
            "id": "jeunes",
            "icon": "Star",
            "refs": [
              {
                "url": "/fiche-service-public/arret-maladie-indemnites-journalieres-versees-au-salarie",
                "title": "Arrêt maladie : indemnités journalières versées au salarié"
              },
              {
                "url": "https://www.service-public.fr/particuliers/actualites/A14380",
                "title": "Personnes vulnérables"
              },
              {
                "url": "https://declare.ameli.fr/cas-contact/conditions",
                "title": "Cas contact : demander un arrêt maladie en ligne"
              }
            ],
            "title": "Jeunes"
          }
        ]
      }
    ]
  }
}
```

**Comment by virginielastisneres** [comment]
Nous avons eu des retours pour modifier le dossier. cc @lionelB 
Je ne trouve plus la PR sinon j'aurais commenté direct dans la PR. 

# Rubrique "Contenus populaires"

1. On supprime : [Aide à l’embauche pour un contrat d’apprentissage](https://code.travail.gouv.fr/fiche-service-public/aides-a-lembauche-pour-un-contrat-dapprentissage) et la fiche derrière aussi 

2. On remplace par "[Alternance : Les aides à l’embauche](https://code.travail.gouv.fr/fiche-service-public/aides-a-lembauche-en-alternance-apprentissage-ou-professionnalisation)" avec une nouvelle fiche. 

# Rubrique "Jeunes"

1. Changer le titre : "Aide de 4 000 euros à l'embauche d'un jeune" par "Aide maximum de 4 000 euros à l'embauche d'un jeune de moins de 26 ans"

2. Changer le titre : "Emploi franc : aide de 8000 à 17000 euros pour un jeune" par "Emploi franc + : aide de 8000 à 17000 euros pour un jeune des quartiers prioritaires"

3. Changer le titre : "Volontariat Territorial en Entreprise Vert : Aide de 8000 euros" par "Volontariat Territorial en Entreprise Vert : Aide maximum de 8000 euros" 

# Rubrique "Alternance"

1. On supprime le lien  : Contrat   d’apprentissage : aide de 5000 ou 8000 euros -> https://code.travail.gouv.fr/fiche-service-public/aides-a-lembauche-pour-un-contrat-dapprentissage

2. On supprime le lien  : Contrat de   professionnalisation : aide de 2000 à 8000 euros -> https://code.travail.gouv.fr/fiche-service-public/aides-a-lembauche-dune-personne-en-contrat-de-professionnalisation

3. On supprime le lien  : Aide à l’embauche d’un demandeur d’emploi de 45 ans et plus en contrat de professionnalisation -> https://code.travail.gouv.fr/fiche-ministere-travail/laide-a-lembauche-dun-demandeur-demploi-de-45-ans-et-plus-en-contrat-de-professionnalisation

4. On remplace ces 3 liens par une seule fiche : "Alternance : Les aides à l’embauche" -> https://code.travail.gouv.fr/fiche-service-public/aides-a-lembauche-en-alternance-apprentissage-ou-professionnalisation


# Rubrique "Seniors et demandeurs d'emploi"

1. Changer le titre du lien "CUI - Parcours emploi compétences" par "Parcours Emploi Compétences (PEC ex-CUI-CAE)" 


# Rubrique "Personnes handicapées"

1. Changer le titre de la section "Personnes handicapées" par "Travailleurs handicapés"

**Comment by virginielastisneres** [comment]
@lionelB pour cette issue il faudra associer pour chaque sous partie une icône spécifique. Je te les transmets cette aprem (j'attends juste l'accord des autres dessus ;))

**Comment by virginielastisneres** [comment]
@lionelB Voici les icônes pour chaque partie 

**ILS SONT EN SVG ICI** (impossible de mettre du SVG dans Github...) https://www.figma.com/file/hwadyHO3FGj0NKAPFDUYf1/Aides-à-l'embauche?node-id=309%3A31

Pour les télécharger cliquer sur l'icône, aller en bas à droite, sélectionner export et mettre format SVG 
cf image 
![Capture d’écran 2021-04-14 à 18 40 37](https://user-images.githubusercontent.com/48682104/114729458-0d8a2080-9d51-11eb-8110-fc114c2a1c1a.png)

**Comment by lionelB** [comment]
ca roule ! merci

**Comment by virginielastisneres** [comment]
NB : A FAIRE AVANT PUBLICATION 
- Ajouter dans les requêtes préenregistrées 
- Ajouter à la Une ? 
- Indexation recherche sur lesquelles il faudrait que le dossier remonte à mettre dans le champ "text" dans l'admin
cc @jrduscher

**Comment by jrduscher** [comment]
Retours après publication sur branche https://c6c1e20-code-travail.dev2.fabrique.social.gouv.fr/dossiers/aides-et-accompagnement-embauche-et-perennisation-des-emplois?q=aide%20et%20accompagnement

**Ajout d'un contenu externe**
En lien avec la #3455 
Ajouter le lien vers l'outil externe du[ Simulateur d'aides jeunes](https://www.1jeune1solution.gouv.fr/mes-aides)
dans la section **Outils et ressources** du dossier, Avec l'intitulé suivant:
"Simulateur d'aides : 1jeune1solution"

**Comment by virginielastisneres** [comment]
CF Réécrire les urls internes propres cc @jrduscher @lionelB :)
