### ISSUE TITLE
Fusion CCN ( WIP) - ceci n'est pas une spec-

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#322]
suivi des fusions.

https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000037646785&dateTexte=&categorieLien=id

Convention collective rattachée IDCC | Convention collective rattachée  Intitulé | Convention collective de rattachement IDCC | Convention collective de rattachement Intitulé
418 | Convention collective nationale de la chemiserie sur mesure | 303 | Convention collective nationale de la couture parisienne
780 | Convention collective régionale des tailleurs sur mesure de la région parisienne | 303 | Convention collective nationale de la couture parisienne
1588 | Convention collective du personnel des sociétés coopératives d'HLM | 3220 | Convention collective nationale du personnel des Offices Publics de l'Habitat
1044 | Convention collective nationale de l'horlogerie | 567 | Convention collective nationale de la bijouterie, joaillerie, orfèvrerie et des activités qui s'y rattachent
1800 | Convention collective nationale du personnel de la céramique d'art | 1558 | Convention collective nationale relative aux conditions de travail du personnel des industries céramiques de France
1001 | Convention collective nationale des médecins spécialistes qualifiés au regard du conseil de l'ordre travaillant dans des établissements et services pour personnes inadaptées et handicapées | 413 | Convention collective nationale de travail des établissements et services pour personnes inadaptées et handicapées

**Comment by ClementChapalain** [comment]
Ajouté ici : https://github.com/SocialGouv/code-du-travail-numerique/wiki/%5BDroit-du-travail%5D-Fusion-CCN
