### ISSUE TITLE
Migration des données datafiller vers l'admin

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#3226]
Afin de pouvoir débrancher le datafiller, nous avons besoin de migrer les données des requêtes `prequalified`dans cdtn-admin.

Pour cela, on pourrait créer un nouveau type de relation.
```ts
type: "prequalified"
data: {
  name: string,
  variants : string[]
}
```

**Comment by virginielastisneres** [comment]
je clôture car on déjà une issue ~~#272~~

**Comment by lionelB** [comment]
https://github.com/SocialGouv/cdtn-admin/issues/272
