### ISSUE TITLE
Thémes : contenus populaires

### ISSUE THREAD

**Issue by rmelisson** [SocialGouv/code-du-travail-numerique#3227]
Pour le moment, les seuls contenus affichés dans les thèmes sont ceux directement attaché au thème.

Nous pourrions mettre en avant certains contenus populaires directement dans les thèmes principaux (de niveau 1, en haut de la hiérarchie).

Par exemple si le contenu "duree-du-travail-dun-salarie-a-temps-plein" (situé dans `Temps de travail / Durée du travail / Durée du travail à temps complet`) est très populaire, nous pourrions directement l'afficher dans `Temps de travail` sans que l'utilisateur ait besoin d'explorer l'arbre des thèmes en profondeur.

**Comment by rmelisson** [comment]
ce ticket fait suite au travail sur les thèmes d'@ArmandGiraud

**Comment by UnbearableBear** [comment]
@virginielastisneres Bonne idée non ?

**Comment by virginielastisneres** [comment]
> @virginielastisneres Bonne idée non ?

ahah on se calme manu :) oui je regarde ca demain !

**Comment by m-maillot** [comment]
Les thèmes vont être retirés
