### ISSUE TITLE
Modification vignette pour les réseaux sociaux 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3229]
# Contexte 

Cela fait 2 fois que la com de la dgt nous demande de modifier notre vignette présente sur les réseaux sociaux lorsque l'on met un lien du code du travail numérique. 
Or, la vignette actuelle est le logo de la mariane. Cela était voulu pour affirmer notre légitimité et fiabilité. 
Aujourd'hui, ca donne ca 
![image](https://user-images.githubusercontent.com/48682104/103663093-02b13a00-4f71-11eb-8cdd-681199def172.png)

D'autres arguments soulevés par la com sur l'intérêt et l'utilité d'avoir à la place le logo du code du travial numérique a été avancé également. 

En regardant un peu ce qui se fait à côté on peut voir l'exemple de service public qui par exemple fait un mix des 2 : leur logo et le logo de la république française. 

# Solution

Adopter une solution mix (à l'image de service-public) : affirmer notre identité (via notre logo) tout en gardant cette fiabilité et légitimité (via la marianne) en mettant cela aux bonnes dimensions. 

### Maquette 

![Facebook post - 5 (1)](https://user-images.githubusercontent.com/48682104/103661524-1d82af00-4f6f-11eb-8f9e-7969cfaad4e6.png)

https://www.figma.com/file/mp2QpsjDK7M6NjWSVLE0E9/Com?node-id=23%3A0

### Taille 

D'après quelques articles la taille optimale serait 1.91:11 (soit 1200px X 628px)
https://knowledge.hubspot.com/fr/social/featured-image-not-displaying-correctly-in-social-preview
https://www.blogdumoderateur.com/guide-taille-images-reseaux-sociaux/

Il sera possible de tester l'affichage avec ces outils :
- Linkedin : https://www.linkedin.com/post-inspector/
- Facebook : https://developers.facebook.com/tools/debug/
- Twitter : https://cards-dev.twitter.com/validator

**Comment by lionelB** [comment]
Je pense qu'on pourrait agrandir un peu la taille du logo (#makemylogobigger)  pour occuper plus d'espace mais sinon la proposition est top !

**Comment by UnbearableBear** [comment]
Gut !

**Comment by virginielastisneres** [comment]
> Je pense qu'on pourrait agrandir un peu la taille du logo (#makemylogobigger) pour occuper plus d'espace mais sinon la proposition est top !

oui oui why not j'ai mis dans la maquette une version avec le logo plus gros 👍
