### ISSUE TITLE
[Bug] pas de fiche dans la requête amiante

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3232]
# Bug 

Lorsque l'on fait la requête "amiante" nous n'avons aucun contenu proposé. 
https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/recherche?q=amiante

Or, cette requête est pré-qualified dans le datafiller et il y a une fiche du ministère du travail renseignée 
![image](https://user-images.githubusercontent.com/48682104/103784782-a9add880-503a-11eb-98ee-73aa13e59d99.png)

Pourtant cette fiche n'apparait pas alors qu'elle existe toujours https://master-code-travail.dev2.fabrique.social.gouv.fr/fiche-ministere-travail/amiante#Reperage-avant-travaux

# Comportement attendu 

- [ ] Que la fiche indiquée dans le datafiller pour la requête amiante apparaisse dans nos résultats lorsqu'on tape amiante. 
Réflexion : on dirait que les sous-parties ne sont plus exactement les mêmes que celles indiquées dans le datafiller (peut etre que cela pourrait expliquer le fait que la fiche ne remonte plus)

- [ ] De plus, j'ai rajouté dans le datafiller 2 nouvelles fiches également sur l'amiante qui devront également apparaitre dans les résultats : 

- https://master-code-travail.dev2.fabrique.social.gouv.fr/fiche-service-public/victime-de-lamiante-comment-etre-indemnise
- https://master-code-travail.dev2.fabrique.social.gouv.fr/fiche-service-public/preretraite-amiante-du-salarie-du-secteur-prive

**Comment by lionelB** [comment]
Je pense que cela vient du fait que la fiche n'est plus découpée en paragraphe, du coup les ancres ne correspondent plus à un document d'où le fait qu'on pas de tuile résultats.

**Comment by lionelB** [comment]
les sections qui existent sont 
- Plan d’actions interministériel amiante
- Plan pluriannuel et stratégique du ministère du travail – prévention des expositions des travailleurs à l’amiante (2017-2021)

**Comment by UnbearableBear** [comment]
outdated, datafiller passed away
