### ISSUE TITLE
Exception /stats

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#3235]
Je n'ai pas beaucoup plus d'info mais dans les logs je vois pas mal d'erreurs de ce type : 

<img width="576" alt="Capture d’écran 2021-01-08 à 10 37 30" src="https://user-images.githubusercontent.com/124937/103999813-ad0da500-519d-11eb-97f3-39a1e15f4cb3.png">

La page "/stats" semble inaccessible

https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-api/src/server/routes/stats/index.js#L80

**Comment by virginielastisneres** [comment]
Je confirme j'ai une erreur 500 quand j'essaye d'accéder à cette page https://code.travail.gouv.fr/stats

![image](https://user-images.githubusercontent.com/48682104/104039686-f9c1a200-51d6-11eb-848a-5b2d096e0f49.png)

**Comment by lionelB** [comment]
Je propose qu'on voit si on peut reprendre la page en utilisant des infos provenant de monolog
