### ISSUE TITLE
fix: fix default DOMAIN for production

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#3243]
Je pense qu'il faudrait également changer le DOMAIN de prod ici : https://github.com/SocialGouv/code-du-travail-numerique/blob/master/.gitlab-ci/env.sh#L51

tout en ne modifiant pas l'url de l'api qui doit rester api.code.travail.fabrique.social.gouv.fr

**Comment by carolineBda** [comment]
@revolunet on fermer cette issue ou c'est toujours valide ?

**Comment by revolunet** [comment]
Huhu oui ça date...
