### ISSUE TITLE
Lien vers la CC legifrance

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#3249]
Le lien vers la CC legifrance ne semble plus opérationnel 

<img width="704" alt="Capture d’écran 2021-01-13 à 10 29 04" src="https://user-images.githubusercontent.com/124937/104433478-70b9ba80-558a-11eb-91e1-394d23bb802c.png">

Le champ `url` n'est pas présent dans ce que l'on récupère via l'api

https://code.travail.gouv.fr/convention-collective/829-convention-collective-departementale-des-industries-metallurgiques-et-des-in

https://api.code.travail.fabrique.social.gouv.fr/api/v1/conventions/829-convention-collective-departementale-des-industries-metallurgiques-et-des-in

**Comment by virginielastisneres** [comment]
humm cela ne serait-il pas dû au fait que cette convention collective n'existe pas sur Légifrance cc @CaptainConan ?

**Comment by CaptainConan** [comment]
C'est tout à fait ça @virginielastisneres: elle n'est pas sur LégiFrance (en tant qu'infra) :)

**Comment by lionelB** [comment]
on enleve le lien pour les cc qui n'ont pas d'url ?

**Comment by CaptainConan** [comment]
> on enleve le lien pour les cc qui n'ont pas d'url ?

Le lien "Source: Légifrance" ? Oui :)

**Comment by virginielastisneres** [comment]
yes
