### ISSUE TITLE
Perf: Glossaire

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#3259]
la performance de l'algo de marquage / remplacement des mots du glossaire dans les document prend énormement de temps. Il faudrait voir comment on peut améliorer ses performance / changer l'organisation des pipeline pour éviter que la tache ne dure 1heure

**Comment by lionelB** [comment]
poke @rmelisson @ArmandGiraud  @revolunet @UnbearableBear

**Comment by lionelB** [comment]
some idea https://www.npmjs.com/package/hast-util-find-and-replace

**Comment by revolunet** [comment]
J'ai fait quelques tests ici : https://github.com/SocialGouv/code-du-travail-numerique/compare/glossary-test en utilisant `mdast-util-find-and-replace` et autres utils de la suite unist.

Ca a l'air de fonctionner, ca ne gère pas les variantes/diacritiques/fuzzy (sauf si on les fournit en amont)

Par contre certains de nos contenus sont de type HTML, d'autres en MDX (Md avec du JSX et/ou HTML pour les contributions); et actuellement le code de replace ne fonctionne pas avec certains HTML, il faut que je creuse pourquoi et je pourrai seulement alors tester si c'est efficace ou pas. 

Le code avec test-cases foireux ici : https://codesandbox.io/s/addglossary-in-mdx-zxyzw?file=/src/glossary.js

**Comment by revolunet** [comment]
Quelques news : l'implem a l'air de fonctionner avec un traitement distinct pour HTML ou MDX... je n'ai pas réussi avec le même traitement :/

J'ai repéré un bug dans la transformation du markdown, visible ici dans le bloc CDI/Textes applicables : https://cf13d01-code-travail.dev2.fabrique.social.gouv.fr/contribution/quelle-est-la-duree-maximale-de-la-periode-dessai-sans-et-avec-renouvellement?q=dur%C3%A9e%20maximale%20periode%20d%27essai 

Le bug se situe au niveau de l'indentation qui est produite par le parsing/compile du markdown, je ne sais pas exactement où, et cela génère un bloc `code` au lien de parser le contenu... je [creuse](https://codesandbox.io/s/mdx-inputoutput-react-renderer-56giy?file=/src/App.js)...

La durée du job "register data" est réduite à environ 10minutes et je pense qu'on pourra encore optimiser, aussi bien sur ce code que sur les appels au NLP.

**Comment by lionelB** [comment]
whoooo super cool @revolunet !!

**Comment by revolunet** [comment]
Update : j'en suis au point ou le html/mdx est correctement modifié avec le tooltip intégré

Mais j'ai un problème côté rendu avec cette approche :maintenant que le MDX est parfait, le renderer rehype-react n'est plus capable de l'interpreter correctement. 

De là je vois deux possibilités : 

 - corriger la source MDX pour qu'elle soit compatible rehype-react (c'est "juste" une histoire d'indentation)
 - utiliser [XDM](https://github.com/wooorm/xdm) ou autre qui fait un vrai rendu MDX mais oblige à avoir la CSP `unsafe-eval`

Le probleme est visible dans "textes applicables" 

http://cf13d01-code-travail.dev2.fabrique.social.gouv.fr/contribution/quelle-est-la-duree-du-preavis-en-cas-de-demission?q=préavis

L'avantage de la methode actuellement en prod c'est qu'on ne touche pas à la structure du document

**Comment by revolunet** [comment]
woot ca a l'air pas mal : https://cf13d01-code-travail.dev2.fabrique.social.gouv.fr/contribution/quelle-est-la-duree-maximale-de-la-periode-dessai-sans-et-avec-renouvellement?q=dur%C3%A9e%20maximale%20periode%20d%27essai

**Comment by romain-b13** [comment]
Cette issue est-elle à clôturer ?

**Comment by lionelB** [comment]
il faudrait integrer le travail de julien avant
