### ISSUE TITLE
Intégrer des documents

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#326]
Proposer aux usagers en complément d'une réponse à question, un outil supplémentaire d'information, made in DIRECCTE.
- [x] centraliser ces productions, mise en place d'un flux organisationnel
- [ ] comment stocker ces documents.?
      où les stocker?
      un flux entre le sharepoint des ARDSR et le CDTn est il techniquemnt envisgaeable?
- [x] comment intégrer ces documents.?
      un json dédié à l'image des courriers avec les url et métadonnées?
- [ ] la variété des formats  pose t-elle un problème d'ergonomie? de développement?
- [ ] la communcation des métadonnées des documents des formats propritétaires pose t-elle un soucis de RGPD?

- [ ] comment afficher la proposition aux users? UX needed
      1) proposer le contenu dans la page résultat
     2) faut il une pasge spécifique ddié à la proposition de contenu ?

**Comment by revolunet** [comment]
Oui on peut envisager un flux entre un repertoire partagé ou sharepoint vers le CDTN

Il faudrait en effet pour démarrer un JSON qui référence et décrit les fichiers à publier.

Sur le format oui il vaut mieux que l'on standardise. DOCX semble le format le plus accessible (et editable) ? On peut automatiser la suppression des métadonnées sur ce format

 - Sur service-public, les modèles sont proposés au format HTML (l'impression n'est pas gérée)
 - A la CNIL ils proposent [un outil pour générer le courrier](https://www.cnil.fr/fr/modele/courrier/acceder-des-images-video-vous-concernant)

**Comment by jrduscher** [comment]
nécessite précisions sur la nature des documents qui pourraient être intégrées.

**Comment by revolunet** [comment]
je pense qu'on peut close pour l'instant
