### ISSUE TITLE
[Bug] Perte des thèmes dans les page des conventions collectives 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3266]
**Description**
Dans nos pages des conventions collectives nous avons perdu les thèmes affiliés aux contributions. Toutes les contributions se retrouvent désormais sous le thème "autres". 
![image](https://user-images.githubusercontent.com/48682104/105011330-1ebade00-5a3d-11eb-98ec-89314adef19d.png)

**Reproduction**
Aller en préprod sur une page de convention collective. Exemple celle de la banque : https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/convention-collective/2120-banque

**Solution**
Permettre un affichage des contributions par thème (Embauche / salaire / Départ de l'entreprise etc.) comme cela été avant.

**Comment by lionelB** [comment]
closed by #3265

**Comment by lionelB** [comment]
duplicate of  #3264
