### ISSUE TITLE
Simulateur de départ ou de mise à la retraite

### ISSUE THREAD

**Issue by noemiechassard** [SocialGouv/code-du-travail-numerique#3268]
# Contexte #
## Objectif : ##
 
Permettre à l’utilisateur, employeur ou salarié, de connaître la durée du préavis qu’il aura à effectuer avant son départ ou sa mise à la retraite.

Le départ à la retraite et la mise à la retraite sont 2 situations différentes. Le départ à la retraite correspond à la situation où le salarié décide de lui-même de quitter son emploi afin de prendre sa retraite.

La mise à la retraite correspond à la situation où l’employeur prend la décision de mettre d’office un salarié à la retraite.

Dans les 2 cas, il y a un préavis à effectuer. Le préavis légal du code du travail correspond en réalité au préavis déjà existant en matière de préavis de licenciement.

Il existe également des dispositions dans les conventions collectives. En revanche, si c’est une mise à la retraite ou un départ à la retraite, la durée à appliquer, c'est à dire la durée légale ou la durée conventionnelle, ne va pas être la même. En effet, pour le départ à la retraite, cela va être la durée la plus courte qui va être appliquée. Alors que pour la mise à la retraite, ce sera la durée la plus longue.

## Données : ##

https://docs.google.com/spreadsheets/d/1zd_hShEui8BHK0349GpDUZRkCcQ9syIZ9gSrkYKRdo0/edit#gid=1592811420

## Titre de l’outil : ##

Préavis de départ ou de mise à la retraite

## Description de l’outil : ##

Calculez la durée de préavis à respecter en cas de départ à la retraite ou de mise à la retraite 

_Voir maquette_ 

# Introduction #

Ce simulateur est un outil qui permet de calculer la durée de préavis à respecter en cas de départ ou de mise à la retraite, telle qu'elle est prévue par la loi et la convention collective applicable.

En effet, en cas de départ ou de mise à la retraite, le salarié ne peut pas quitter l’entreprise immédiatement. Il doit y rester durant une certaine période, qu’on appelle préavis ou parfois délai congé.

Afin de réaliser cette simulation, vous aurez besoin d’informations concernant la situation du salarié, comme sa convention collective, sa catégorie ou son coefficient. La plupart de ces informations se trouvent sur le bulletin de salaire ou le contrat de travail. Prévoyez X à X minutes pour cette simulation.

Cliquez sur commencer pour démarrer la simulation.

# Etape 1 - Origine du départ à la retraite #
### 1ère question : Demander à l’utilisateur s’il s’agit d’un départ ou d’une mise à la retraite  ###

“**Qui est à l’origine du départ en retraite ?**” 

- **L’employeur décide de lui-même de mettre à la retraite le salarié par une décision adressée à celui-ci**.*  

(* Même si le salarié accepte sa proposition, c’est bien l’employeur qui a lui-même pris la décision de mettre à la retraite le salarié.)

- **Le salarié décide de quitter volontairement l’entreprise pour prendre sa retraite.**

Si l’utilisateur clique sur la première proposition, on passe à l’étape suivante en appliquant par la suite les règles relatives à la mise à la retraite. 

Si l’utilisateur clique sur la deuxième proposition, on passe à l’étape suivante en appliquant par la suite les règles relatives au départ à la retraite. 

_Voir maquette_

# Etape 2 - Convention collective #
### 2ème question : Demander à l’utilisateur quelle est sa convention collective applicable ###

“**Sélectionnez une convention collective**”

-> Reprise du choix de la convention collective que l’on trouve dans d’autres simulateurs, notamment le préavis de licenciement ou le préavis de démission 

Si l’utilisateur ne sélectionne pas de convention collective, afficher “ **Vous n’avez pas de rempli de convention collective. Vous pouvez poursuivre la simulation pour connaître la durée prévue par le code du travail mais nous vous conseillons de vérifier si votre convention collective prévoit un délai plus favorable qui vous serait applicable**”
Puis, passer directement à la question 9.

Si l’utilisateur sélectionne une convention collective ne faisant pas partie des 50 CC traitées par le tableau, afficher “**La convention collective sélectionnée n'a pas été traitée par nos services. Vous pouvez poursuivre la simulation pour connaître la durée prévue par le code du travail mais nous vous conseillons de vérifier si votre convention collective prévoit un délai plus favorable qui vous serait applicable**” 
Puis, passer directement à la question 9.

Si l’utilisateur sélectionne une convention collective faisant partie des 50 CC traitées par le tableau, passer à l’étape 3, question 3.

_Voir maquette_

# Etape 3 - Informations sur le statut du salarié #

Il ne faut pas systématiquement poser les questions suivantes. En effet, cela correspond aux spécificités des conventions collectives. Il faudra poser la question si la colonne est remplie pour la convention collective renseignée. 

### 3ème question: Il faut poser cette question si la colonne H est remplie. ###

“**Quelle est la catégorie professionnelle du salarié ?**” 

Les propositions de réponse correspondent à ce qui est rempli dans cette colonne.

Quand l’utilisateur a répondu, il faut passer à la question suivante en fonction des colonnes remplies pour la convention collective renseignée.

### 4ème question: Cette question ne concerne que la convention collective de l’industrie pharmaceutique (IDCC 0176). Cela correspond à la colonne P. ###

“**À quelle date le contrat a-t-il été conclu ?**”

- **Contrat de travail conclu avant le 1er juillet 2009**
- **Contrat de travail conclu à partir du 1er juillet 2009**

Quand l’utilisateur a répondu, il faut passer à la question suivante en fonction des colonnes remplies pour la convention collective renseignée.

### 5ème question: Cette question ne concerne que la convention collective des gardiens, concierges et employés d’immeubles (IDCC 1043). Cela correspond à la colonne Q. ###

“**Le salarié est-il logé ?**” 
- **Oui** 
- **Non**

Oui correspond à la réponse “logés”
Non correspond à la réponse“ Non logé”

Quand l’utilisateur a répondu, il faut passer à la question suivante en fonction des colonnes remplies pour la convention collective renseignée.

### 6ème question: Il faut poser cette question si la colonne U est remplie. ###

“**Quel est le groupe du salarié ?** ” 

Les propositions de réponse correspondent à ce qui est rempli dans cette colonne.

Quand l’utilisateur a répondu, il faut passer à la question suivante en fonction des colonnes remplies pour la convention collective renseignée.

### 7ème question: Il faut poser cette question si la colonne V est remplie. ###

“**Quel est le coefficient du salarié ?** ”

Les propositions de réponse correspondent à ce qui est rempli dans cette colonne.

Quand l’utilisateur a répondu, il faut passer à la question suivante en fonction des colonnes remplies pour la convention collective renseignée.

### 8ème question: Il faut poser cette question si la colonne W est remplie. ###

“**Quel est l’échelon du salarié ?**”

Les propositions de réponse correspondent à ce qui est rempli dans cette colonne.

Quand l’utilisateur a répondu, il faut passer à la question suivante en fonction des colonnes remplies pour la convention collective renseignée.

### 9ème question: Cette question est à poser dans tous les cas, que le salarié ait sélectionné une convention collective ou non, peu importe qu’il s’agisse d’une des 50 CC traitées ou non... ###

“**Le salarié concerné est-il reconnu en tant que travailleur handicapé ?**”
- **Oui** 
- **Non**
 
Si l’utilisateur répond Non, on passe à l’étape suivante et il n’y a aucun impact sur le délai de préavis. 

Si l’utilisateur répond Oui, il faut doubler la durée légale et conventionnelle dans la limite de 3 mois.

_Calcul_ :  Durée de préavis x 2 ≤ 3 mois 

# Etape 4 - Ancienneté du salarié #
_A voir plus tard_

# Etape 5 - Durée du préavis #
### Introduction  : ###

Pour déterminer le résultat, il faut faire une règle de calcul et comparer la durée prévue par la convention collective et celle prévue par le code du travail: 
- Le préavis de CC correspond à la colonne Z (durée exprimée en mois ou semaine) et à la colonne AB (durée exprimée en jours).
- Le préavis du code du travail correspond aux cases Z554, Z555 et Z556 (durée exprimée en mois) et à la colonne AB554, AB555 et AB556 (durée exprimée en jours)

### Départ à la retraite : Calcul à effectuer ###

**Situation 1** : La convention collective prévoit une durée de préavis 

Si ancienneté du salarié moins de 6 mois alors => préavis de CC

Si ancienneté de 6 mois ou plus alors 

- si préavis de CC < préavis du code du travail => préavis de CC
- si préavis de CC > préavis du code du travail => préavis du code du travail
- si préavis de CC = préavis du code du travail => préavis de CC et/ou préavis du code du travail

**Situation 2** : La convention collective ne prévoit pas une durée de préavis (soit car elle n’en prévoit pas, soit parce que l’usager n’a pas rempli sa CC)

alors => préavis du code du travail

### Mise à la retraite : Calcul à effectuer ###

**Situation 3** : La convention collective prévoit une durée de préavis 

Si ancienneté du salarié moins de 6 mois alors => préavis de CC

Si ancienneté de 6 mois ou plus alors 
- si préavis de CC > préavis du code du travail => préavis de CC
- si préavis de CC < préavis du code du travail => préavis du code du travail
- si préavis de CC = préavis du code du travail => préavis de CC et/ou préavis du code du travail 

**Situation 4** : La convention collective ne prévoit pas une durée de préavis (soit car elle n’en prévoit pas, soit parce que l’usager n’a pas rempli sa CC)

alors => préavis du code du travail

#### Page à afficher quand il n’y a pas de préavis (Préavis légal = 0) et que la convention collective n’a pas été remplie à l’étape 2: ####

Ajoutez * après le résultat et plus bas, en caractère plus petit et en italique la phrase indiquée dans la colonne AA si celle-ci est remplie

_Voir maquette_

Quand l’utilisateur clique sur “Comprendre mon résultat” une modal s’affiche : 

_Voir maquette_

#### Page à afficher quand il n’y a pas de préavis mais que la convention collective a été remplie (Préavis de CC = 0 et Préavis du code du travail= 0): ####

Ajoutez * après le résultat et plus bas, en caractère plus petit et en italique la phrase indiquée dans la colonne AA si celle-ci est remplie

Voir maquettes

#### Page à afficher quand la convention collective est remplie et qu’il y a un délai de préavis: ####

Ajoutez * après le résultat et plus bas, en caractère plus petit et en italique la phrase indiquée dans la colonne AA si celle-ci est remplie (comme sur la maquette ci-dessous)

_Voir maquette_

Quand l’utilisateur clique sur “Comprendre mon résultat” une modal s’affiche: 

**Modal à afficher si préavis du code du travail < préavis de CC:**  

_Voir maquette_

**Modal à afficher si préavis du code du travail = préavis de CC :**

_Voir maquette_ 

**Modal à afficher si préavis du code du travail > préavis de CC:**

_Voir maquette_

#### Page à afficher quand la convention collective n’est pas remplie mais qu’il y a un délai de préavis qui correspond au délai légal: ####

Ajoutez * après le résultat et plus bas, en caractère plus petit et en italique la phrase indiquée dans la colonne AA si celle-ci est remplie (comme sur la maquette ci-dessous)

_Voir maquette_ 

Quand l’utilisateur clique sur “Comprendre mon résultat” une modal s’affiche:  

_Voir maquette_ 

#### Page à afficher quand il n’y a pas de préavis (Préavis légal = 0) et que la convention collective n’a pas été remplie à l’étape 2: ####

Ajoutez * après le résultat et plus bas, en caractère plus petit et en italique la phrase indiquée dans la colonne AA si celle-ci est remplie

_Voir maquette_

Quand l’utilisateur clique sur “Comprendre mon résultat” une modal s’affiche : 

_Voir maquette_

#### Page à afficher quand il n’y a pas de préavis mais que la convention collective a été remplie (Préavis de CC = 0 et Préavis du code du travail= 0): ####

Ajoutez * après le résultat et plus bas, en caractère plus petit et en italique la phrase indiquée dans la colonne AA si celle-ci est remplie

_Voir maquettes_

#### Page à afficher quand la convention collective est remplie et qu’il y a un délai de préavis: ####

Ajoutez * après le résultat et plus bas, en caractère plus petit et en italique la phrase indiquée dans la colonne AA si celle-ci est remplie (comme sur la maquette ci-dessous)

_Voir maquette_

Quand l’utilisateur clique sur “Comprendre mon résultat” une modal s’affiche: 

**Modal à afficher si préavis du code du travail > préavis de CC :**  

_Voir maquette_

**Modal à afficher si préavis du code du travail = préavis de CC :**

_Voir maquette_ 

**Modal à afficher si préavis du code du travail < préavis de CC:**

_Voir maquette_

#### Page à afficher quand la convention collective n’est pas remplie mais qu’il y a un délai de préavis qui correspond au délai légal : ####

Ajoutez * après le résultat et plus bas, en caractère plus petit et en italique la phrase indiquée dans la colonne AA si celle-ci est remplie (comme sur la maquette ci-dessous)

_Voir maquette_ 

Quand l’utilisateur clique sur “Comprendre mon résultat” une modal s’affiche:  

_Voir maquette_

**Comment by m-maillot** [comment]
## Concernant l'étape 4 : Ancienneté du salarié 

La première version va intégrer une version allégée avec deux possibilités pour l'utilisateur:
 * Un champ permettant de saisir directement son ancienneté (année, mois, jour).
 * 2 champs permettant de saisir la date d'entrée et de sortie et le nombre de mois d'absences. 

Pas de prise en compte de la CC pour le moment. Le simulateur pour calculer l'ancienneté sera développé plus tard. On verra à ce moment comment l'intégrer avec prise en compte de la CC.

**Comment by m-maillot** [comment]
Il serait intéressant de réfléchir à comment surveiller l'utilisateur lors de la saisie de son ancienneté (via matomo).

**Comment by m-maillot** [comment]
Liste des CC à implémenter pour le suivi :

- [x] 16
- [x] 29
- [x] 44
- [x] 54
- [x] 86 (cas particulier: résultat en min et max)
- [x] 176
- [x] 275
- [x] 292
- [x] 413
- [x] 573
- [x] 650
- [x] 675
- [x] 787
- [x] 843
- [x] 1043
- [x] 1090
- [x] 1147
- [x] 1266
- [x] 1351
- [x] 1404
- [x] 1480
- [x] 1483
- [x] 1486
- [x] 1501
- [x] 1505
- [x] 1516
- [x] 1517
- [x] 1518
- [x] 1527
- [x] 1596
- [x] 1597
- [x] 1606
- [x] 1672
- [x] 1702
- [x] 1740
- [x] 1979
- [x] 2098
- [x] 2111
- [x] 2120
- [x] 2148 (cas particulier: durée fixé dans le contrat ne peut être inférieur à 3 mois)
- [x] 2216
- [x] 2264
- [x] 2395 (cas particulier: pas de préavis)
- [x] 2420
- [x] 2511
- [x] 2596 (voir le nommage de la catégorie professionnelle)
- [x] 2609
- [x] 2614
- [x] 2941 (cas particulier: 1 semaine de date à date, peut être géré via une notification?)
- [x] 3043 
- [x] 3127

**Comment by m-maillot** [comment]
En cours de validation par @noemiechassard (seulement les CCs 16, 29, 44, 54, 176, 275, 292, 413, 573, 650 et 675 sont à tester pour le moment)

**Comment by m-maillot** [comment]
Retours de @noemiechassard:

## 2ème étape : Qui est à l’origine du départ à la retraite ?

Voir issue #3526

## 3ème étape : Quelle est la convention collective applicable au salarié ?

Voir issue #3543

## 4ème étape: Information

Voir issue #3527 

## 6ème étape: Résultat

En cours d'analyse avec @romain-b13 

## 16 Transports routiers et activités auxiliaires du transport

 - [x] Revoir la question sur le groupe: Quel est le groupe du salarié ? (cf dans cette issue même)

 - [x] Groupe 6 à 8, retirer la deuxième partie sur la rémunération dans la réponse 2

## 29 Hospitalisation privée : établissements privés d'hospitalisation, de soins, de cure et de garde à but non lucratif (FEHAP)

Issue dédiée: https://github.com/SocialGouv/code-du-travail-numerique/issues/3546

## 44 Industrie chimique et connexe 

 - [x] Revoir la question sur le coefficient : Quel est le coefficient du salarié ? (cf dans cette issue même)

## 176 Industrie pharmaceutique

 - [x] Supprimer le description sur le groupe
 - [x] Modifier la question sur le groupe: Quel est le groupe du salarié ?
 - [x] Revoir la question sur le contrat: À quelle date le contrat a-t-il été conclu ? 
 - [x] Réponse 2, rempalcer par : Cette durée **ne** s’applique **que** si les salariés ne bénéficient pas des dispositions de l’article 4 de la convention collective nationale de retraite et de prévoyance des cadres du 14/3/1947.
 - [x] Erreur mise à la retraite, groupe 6 -> conclu après le 1er juillet 2019 -> 3 mois et non 4 mois.
 - [x] Mise à la retraite → Groupe 1 à 3 → 2 mois → Non étendu → Rajouter en réponse 2 la phrase :” Attention : L'article de la convention collective ou la convention collective saisie n’a pas été étendue au niveau national. Par conséquent, pour que ce résultat soit applicable à votre situation, il faut que l’employeur ait adhéré à l’organisation patronale signataire de cette convention. Sans cette adhésion, l'employeur n'a pas l'obligation d'appliquer les règles de la convention mais il applique le préavis prévu par le code du travail.” 
 - [x] Et il faut également modifier l’article 35. Il ne faut pas afficher cette phrase si le salarié fait partie du groupe 4. (Modification effectuée dans le data simulateur)

## 275 Transport aérien : personnel au sol

 - [x] Case vide sur l'écran d'informations pour les cadres

## 292 Plasturgie 

 - [x] Il y a une erreur dans le libellé des articles. il s’agit de l’article 28 de la CC et l’article 15 de l’Avenant Collaborateurs (cf data_simulateurs).

## 413 Handicapés : établissements et services pour les personnes inadaptées et handicapées 

- [x] Dans le menu déroulant de la catégorie professionnelle, il faudrait plutôt ajouter la catégorie “Autres cadres” en dernier.

## 513 Commerce de gros

 - [x] Supprimer la réponse 2

## 650 Métallurgie : ingénieurs et cadres

 - [x] Supprimer la réponse 2
 
 


Source: https://docs.google.com/document/d/1THvPApYoTCnHOU54NaIwNpYjCHJMF8bV9bR0G12Cf5g/edit#heading=h.oo2jls5z5h6h

**Comment by m-maillot** [comment]
Ready for tests here: https://007e24b-code-travail.dev2.fabrique.social.gouv.fr/
