### ISSUE TITLE
afficher unepage de résultat  par paragraphe Fiches ministères précision au paragraphe

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#328]
https://codedutravail-dev.num.social.gouv.fr/fiche-ministere-travail/le-licenciement-pour-motif-personnel-quest-ce-quune-cause-reelle-et-serieuse?q=Quelles%20sont%20les%20indemnit%C3%A9s%20dues%20au%20salari%C3%A9%20en%20l%E2%80%99absence%20de%20cause%20r%C3%A9elle%20et%20s%C3%A9rieuse%20%3F&search=0#Qu-est-ce-qu-une-cause-reelle-et-serieuse

le paragraphe suivant : Quelles sont les indemnités dues au salarié en l’absence de cause réelle et sérieuse ? n'apparait pas dans les contenus possibles/ si on recherche "Quelles sont les indemnités dues au salarié en l’absence de cause réelle et sérieuse ?" on ne tombe pas précisément sur ce paragraphe

**Comment by jrduscher** [comment]
#105 #270

**Comment by lionelB** [comment]
Suite à notre échange avec @jrduscher, on ne pas cibler le paragraphe 
`"Quelles sont les indemnités dues au salarié en l’absence de cause réelle et sérieuse ?`  car celui-ci n'est pas accessible via une ancre, comme les titres pricipaux de la page.

Cette issue a été l'occasion de découvrir que certaine fiches sont en doublons #421
