### ISSUE TITLE
Comment fonctionne la mise à jour des fiches SP 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3292]
**Description**

Suite au bug détecté et réparé directement sur la fiche de Service-Public.fr : https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/fiche-service-public/duree-du-travail-dun-salarie-a-temps-plein, on s'interroge sur le système de mise à jour des fiches SP et comment cela a pu arriver. 

1. Question : à partir de quand les mises à jour des fiches SP remontent chez nous ? 
2. Question : Pourquoi avons nous eu cette différence de plusieurs jour entre les fiches SP et chez nous ?

**Comment by lionelB** [comment]
les fiches sont mises à jour dans l'outils d'admin des que les données sont dispo sur  https://www.data.gouv.fr/fr/search/?q=vos+droits+et+d%C3%A9marches. 
Ensuite il faut lancer la mise à jour des fiches sur la prod pour que celles ci arrivent en prod

**Comment by virginielastisneres** [comment]
@lionelB @m-maillot @CaptainConan 
Faut qu'on améliore cela car encore une fois on a une fiche qui n'est pas à jour https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/fiche-service-public/lemployeur-doit-il-amenager-un-espace-pour-la-pause-dejeuner
fiche à jour https://www.service-public.fr/particuliers/vosdroits/F1731

**Comment by lionelB** [comment]
from mattermost
> Les mise à jours sont automatiques dans l'admin (ie la dernière version est remontée le soir ou le lendemain de la publication sur fiche-vdd ). Ensuite tant qu'on ne fait pas de déploiement [...] ou qu'on le fait pas une mise à jour depuis l'admin, les données ne sont pas mises à jour. 
> Dans le détail, la fiche est daté du 17 Février, [@socialgouv/fiches-vdd](https://github.com/SocialGouv/fiches-vdd/) a été mis à jour le 18 Février à 5h29 et rendu disponible dans l'admin le 19 Février vers 0h30

**Comment by lionelB** [comment]
on peut fermer ?

**Comment by virginielastisneres** [comment]
yes :)
