### ISSUE TITLE
Formatage des balise title des contributions avec les CCs

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3293]
# Contexte 

Suite au travail sur la découpe des urls des contributions pour obtenir une url par contribution et par convention collective, j'ai regardé ce que cela donnait en présentation sur les moteurs. 

Exemple ici avec durée préavis de la CC automobile : 
![image](https://user-images.githubusercontent.com/48682104/107370784-b747f980-6ae3-11eb-9953-59ebb0467f03.png)

On remarque que l'on ne met pas du tout en avant qu'il s'agit ici de la CC automobile, il faut vraiment connaître pour comprendre que la CC est là. 

# Solution 

Serait-il possible de modifier dans un premier temps et de manière automatique le méta title de la manière suivante : 
**Thème de la contribution + nom de la CC concernée**

cc @Jonathan2051 je ne sais pas si tu as vu cela mais peut être qu'il faudrait réduire les titres des contributions qui ont repris les questions brutes, ca fait long... et ca laisserait un peu de place pour ajouter le nom de la CC non ? 

Quelque chose qui donnerait cela :
![image](https://user-images.githubusercontent.com/48682104/107373201-8cab7000-6ae6-11eb-844d-b9dd7e3977d6.png)

**Comment by Jonathan2051** [comment]
Pas sûr que l'on puisse automatiser **l'optimisation de la longueur la balise <title>** sur chaque CC. Du coup, peut-être qu'il faudra envisager de faire celle-ci à la main...

**Comment by m-maillot** [comment]
Travaux en cours pour l'amélioration. Comme ça a beaucoup changé depuis, je clôture.
