### ISSUE TITLE
Test : Listes des meta title / meta description des contributions avec nouveau formatage automatique

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3297]
**Problème**

cf. le constat [ici ](#3293)

**Solution**

Avant de savoir si nous allons changer les metatitles/metadescription des 5 000 contributions en les formatant de manière automatique, il faudrait sortir **la liste des metatitles et des metadescription pour chaque contribution comme suit :  

## Pour les contributions avec dans l'url la convention collective déjà indiquée 

Exemple d'url : https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/contribution/1090-quelle-est-la-duree-du-preavis-en-cas-de-demission

### Meta title 

Formatage automatique : "[thème de la contribution] - Convention collective [nom de la convention collective]"

Exemple : pour cette page https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/contribution/1090-quelle-est-la-duree-du-preavis-en-cas-de-demission cela donnerait  **"Démission - Convention collective Services de l'automobile"** 

### Meta description 

Formatage automatique : "[Titre de la contribution H1] Réponse pour la convention collective [nom de la convention]"

Pour le même exemple, cela donnerait : "Quelle est la durée du préavis en cas de démission ? Retrouvez la réponse pour la convention collective Services de l'automobile"

## Pour les contributions générique (donc aucune convention collective de sélectionnée)

Exemple d'url :  https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/contribution/quelle-est-la-duree-du-preavis-en-cas-de-demission

### Meta title 

Formatage automatique : "[question de la contribution = le H1]"

Exemple : "Quelle est la durée du préavis en cas de démission"

### Metadescription 

Formatage automatique : "[question de la contribution = le H1] Ce que dit le code du travail et sélectionnez votre convention collective pour savoir si elle prévoit des règles spécifiques."

Exemple : "Quelle est la durée du préavis en cas de démission ? Ce que dit le code du travail et sélectionnez votre convention collective pour savoir si elle prévoit des règles spécifiques.

**Comment by m-maillot** [comment]
@virginielastisneres suite à une discussion avec @lionelB, on a détecté que les contributions personnalisées ne possédaient pas  de fil d'ariane et de thème (cf: https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/contribution/1090-quelle-est-la-duree-du-preavis-en-cas-de-demission). Il y en a 41 qui ont cette information seulement. L'idée est de reprendre le thème de la page générique dans les pages personnalisées. 
Je crée une issue dédiée pour le traiter: https://github.com/SocialGouv/cdtn-admin/issues/327
Celle ci est donc en attente de l'autre issue pour pouvoir réaliser l'export.

/related https://github.com/SocialGouv/cdtn-admin/issues/327

**Comment by m-maillot** [comment]
@virginielastisneres j'ai fait un google sheet avec le rendu avec les valeurs disponibles aujourd'hui en base. Je n'ai pas fait de modification. Il y a un onglet données (données brutes), un onglet résultats (avec la balise title et metadata) et un onglet analyse où j'ai déjà mis mes premières impressions. 

Le document est dispo ici:
https://docs.google.com/spreadsheets/d/1SHoE1LqlRQGHAXHOh396NoDVTKzgPjOYr9HkzzVZ_lk/edit?usp=sharing

**Comment by virginielastisneres** [comment]
ici les 1000 premières
