### ISSUE TITLE
Bug Kibana : rapport mensuel sur les recherches 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3298]
# Contexte

Attention dans le rapport sur les recherches effectuées, il semblerait que les titres des thèmes sont loggées comme recherche. Exemple : santé, sécurité et conditions de travail. 
Cela n'est pas une vraie recherche et ca fausse les rapports. 
![Image collée à 2021-2-8 17-57](https://user-images.githubusercontent.com/48682104/107626260-d074b580-6c5d-11eb-97d2-153aebeb8469.png)

# Solution

Il faudrait soit enlever ces logs soit les filtrer. 

**"Il semblerait que le problème vient des logs bruts : visiblement, l'event ThemeResults, envoie avec lui un petit event searchKeyword, qui est le nom du thème.. et c'est pas géré par monolog en aval"**

**Comment by virginielastisneres** [comment]
Hello @ArmandGiraud est ce que tu pourrais me dire ou cette issue en est ? (je suis vraiment désolée la semaine dernière j'ai pas eu le temps de te demander avant ton départ...)

**Comment by virginielastisneres** [comment]
Ah j'ai l'impression que nous avons avec le t dans les logs cc @ArmandGiraud et @rmelisson 
![Capture d’écran 2021-03-02 à 09 48 34](https://user-images.githubusercontent.com/48682104/109622648-a3207680-7b3c-11eb-89c4-940ea87be2cf.png)

**Comment by virginielastisneres** [comment]
@Armandgrd Du coup on peut clôturer l'issue ?

**Comment by ArmandGiraud** [comment]
Yep, si tu es satisfaite des données dans Kibana on peut clôturer!
