### ISSUE TITLE
pertinence elastic search 

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#330]
quand je tape  le titre de ma fiche ministère du travail, c'est plutôt cool de me voir suggérer les différents paragraphes contenus dans cette fiche, je peux choisir celui qui pourrait m’intéresser alors même que je n'ai pas tout précisé dans ma requete/  
MAIS:
- [ ] si je tape exactement "Congé parental d'éducation" et qu'un contenu correspond exactement à cela, je m'attends à le voir en tête des propositions
- [ ] si je tape "congé parental d'éducation", et rien d'autre, que le contenu correspond bien à  l'intitulé d'une fiche, qu'on m'en suggère des paragraphes, je m'attendrais à les voir s'afficher dans l'ordre de la fiche ( comme une table des matières): l'ordre de la fihce suivant une certaine logique à reprendre:

![image](https://user-images.githubusercontent.com/37538697/49152331-c2ebe300-f312-11e8-967a-67704a70b689.png)

**Comment by revolunet** [comment]
En fait ce bug vient du fait qu'on indexe plusieurs fois la même fiche ministère du travail alors qu'il s'agit du même document mais de paragraphes différents.

**Comment by lionelB** [comment]
idée = ajouté un poids lors de l'indexation par paragraphe
