### ISSUE TITLE
Ajout de la source de la fiche dans certaines contributions 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3300]
# Problème

On a eu une réunion avec des personnes de Service-Public.fr, nous leur avons présenté les contributions notamment et on a remarqué une chose : lorsqu'on reprend entièrement la fiche Service-Public.fr on n'indique pas la source... :O
(on avait un peu honte de leur montrer cela...)

Exemple d'une contribution ici : https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/contribution/a-quelles-indemnites-peut-pretendre-un-salarie-qui-part-a-la-retraite

# Solution 

Serait-il possible de rajouter la source de la fiche utilisée lorsqu'on utilise une fiche en entière (comme cela est traitée dans nos autre contenus) 

Exemple de visuel 
![image](https://user-images.githubusercontent.com/48682104/107653533-0af04980-6c82-11eb-8d4b-e8ace2d44615.png)

**Comment by lionelB** [comment]
je pense qu"il faudrait plutot le rajouter en fin de contenu plutot que sous le titre général de la page qui contient aussi la réponse conventionnelle. cela voudrait dire que tout le contenu provient de service-public, or seulement la premier partie est concernée

**Comment by virginielastisneres** [comment]
> je pense qu"il faudrait plutot le rajouter en fin de contenu plutot que sous le titre général de la page qui contient aussi la réponse conventionnelle. cela voudrait dire que tout le contenu provient de service-public, or seulement la premier partie est concernée

Oui très bien, je pensais à la base plutôt en dessous de "ce que dit le code du travail ?" mais très bien aussi à la fin comme c'est déjà le cas pour les contributions ou cela a été rajouté à la main 👍

**Comment by lionelB** [comment]
possible aussi a cet endroit. 
Je prépare les 2 et je te montre

**Comment by lionelB** [comment]
![image](https://user-images.githubusercontent.com/160320/108198864-73c14100-711c-11eb-80e0-95a79c18154d.png)
![image](https://user-images.githubusercontent.com/160320/108198934-8f2c4c00-711c-11eb-92e8-ee56dad09ad2.png)

**Comment by virginielastisneres** [comment]
@lionelB Pendant le test version mobile j'ai remarqué un petit truc :) Est ce que l'on pourrait afficher en version mobile la mise à jour sous la source et non à côté comme c'est le cas pour les fiches lambda

### Affichage version mobile des ref dans contributions
![image-2058add1-34b0-4aaa-bc55-e2aa47209170](https://user-images.githubusercontent.com/48682104/108346715-fb23b880-71df-11eb-8f1c-f9165869c6fb.jpg)


### Affichage version mobile de la fiche "normale" hors contribution 
![image-413df290-c415-4139-9328-f0bb2e1d9445](https://user-images.githubusercontent.com/48682104/108346765-070f7a80-71e0-11eb-9e6a-25e18d15ab75.jpg)
