### ISSUE TITLE
Améliorer le champ de saisie des dates des outils ? 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3301]
# Retour utilisateur par mail 

![image](https://user-images.githubusercontent.com/48682104/107672260-fd908a80-6c94-11eb-9f44-3e7002cc105d.png)

je le pose là pour l'avoir en tête et réfléchir si vous avez des idées @lionelB @UnbearableBear @m-maillot ;)

**Comment by UnbearableBear** [comment]
Oh :( On a choisi d'utiliser les calendriers par défaut des naviguateurs parcequ'ils sont supposés être super accessibles, mais de toute évidence celui utilisé par cette personne ne mets pas suffisamment en avant le fait qu'on puisse directement changer l'année

**Comment by virginielastisneres** [comment]
> Oh :( On a choisi d'utiliser les calendriers par défaut des naviguateurs parcequ'ils sont supposés être super accessibles, mais de toute évidence celui utilisé par cette personne ne mets pas suffisamment en avant le fait qu'on puisse directement changer l'année

Du coup manu il y aurait possibilité d'utiliser d'autres calendriers que ceux des navigateurs par défaut ?

**Comment by lionelB** [comment]
je me demande si le plus simple serait de ne pas utiliser le champ date mais seulement un champ texte  au format jj/mm/aaaa (avec une info sur le format attendu)

**Comment by UnbearableBear** [comment]
oui ça me semble être la meilleur option

**Comment by virginielastisneres** [comment]
moi aussi

**Comment by romain-b13** [comment]
@lionelB  je peux clôturer cette issue ? => la saisie des dates se fait déjà avec un champ texte au format jj/mm/aaaa dans tous nos outils
