### ISSUE TITLE
Changer la fonctionnalité imprimer sur la page résultat des outils

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3303]
# 1. Bouton imprimer à modifier

### Constat 
Voici le commentaire d'un de nos utilisateurs dans le questionnaire : 
![image](https://user-images.githubusercontent.com/48682104/107939240-c10baa00-6f86-11eb-99e2-f7cb9638999d.png)

Qu'est ce qui est le plus important pour nous ? que l'utilisateur télécharge le résultat ou qu'il l'imprime ? à mon sens qu'il puisse garder son résultat et le télechargement est plus sécurisé pour l'utilisateur. 
Il est vrai qu'il existe l'option imprimer dans l'impression mais elle ne doit pas être connue de tous. Or, tout le monde qui télécharge un document sait après l'imprimer s'il le souhaite. 

### Solution

Modifier le bouton "imprimer le résultat" par le bouton "Télécharger le résultat". 
Reprendre pour cela le design du bouton déjà présent dans les modèles de document. 

**Petite question : le fait d'ajouter le bouton télécharger comme pour les modèles cela signifie que nous aurons donc la trace des téléchargements dans matomo (rubrique téléchargement) ?** 

### Maquette du rendu 
![image](https://user-images.githubusercontent.com/48682104/107939755-73dc0800-6f87-11eb-8087-0144db10a4f2.png)

# 2. Réajuster les espaces (padding et margin) 

### Aujourd'hui constat 

Voici ce que je vois avec mon écran résolution 1366 x 768.
Information préliminaire : cette résolution est la 2ème la plus utilisée par nos utilisateurs et représente 10%. 

![image](https://user-images.githubusercontent.com/48682104/107936451-fa421b00-6f82-11eb-961f-22f4e93fee65.png)
![image](https://user-images.githubusercontent.com/48682104/107936983-9b30d600-6f83-11eb-84bf-2d2d17132f00.png)

Pourquoi 2 captures ? 
- l'un j'ai le questionnaire proposé en bas
- l'autre j'ai des contenus annexes proposés en bas

Dans aucun des cas je ne vois ce qui m'est proposé en bas de l'outil. 

#### a. Padding 
3.2rem au lieu de 4 rem

#### b. Margin de boutons "précédent" et "télécharger le résultat" 
Supprimer le margin du bas qui était à 3.2
![image](https://user-images.githubusercontent.com/48682104/107938816-3165fb80-6f86-11eb-855a-1f3191cb027f.png)

#### c. Contenus annexes proposés en bas
Réduire le margin du haut de 3.2 à 2.4 (cela permet d'avoir le titre au dessus de la ligne de flottaison pour les petits écrans lorsqu'on a l'outil au centre de l'écran) 

#### d. Maquettes 

Avec le questionnaire : 
![image](https://user-images.githubusercontent.com/48682104/107936772-55740d80-6f83-11eb-8227-1e1a428facd1.png)

Avec les contenus annexes : 
![image](https://user-images.githubusercontent.com/48682104/107937301-0a0e2f00-6f84-11eb-8051-ee457c7da451.png)

**Comment by UnbearableBear** [comment]
Malheureusement, il n’est pas possible de proposer à l’utilisateur de télécharger le contenu de la page via un bouton sans le générer au format PDF au préalable. Concrètement, cela impliquerait de devoir embarquer un générateur de pdf dans les outils ce qui est lourd de conséquences au niveau du poids de la page. Et cela implique beaucoup plus de code à maintenir aussi car il ne suffit pas de dire "voila le HTLM merci pour le PDF". Il y a de fortes chances que les styles pour l’impression ne s’appliquent pas non plus. Bref, je pense que ce n’est vraiment pas une bonne chose à faire ! Mais alors vraiment pas !

**Comment by romain-b13** [comment]
@m-maillot @lionelB  vous êtes en accord avec le commentaire de Manu ?

**Comment by lionelB** [comment]
il faudrait réfléchir a une solution qui permette de généré un pdf coté serveur plutot.

**Comment by m-maillot** [comment]
La solution est complexe à mettre en place. Il serait intéressant de voir si c'est fortement utiliser. 

Proposition:
 * Ajouter un tracking sur l'impression 
 * Ajouter un bouton enregistrer 'fake' qui renvoie sur l'impression pour voir la quantité qui clique sur Télécharger à la place d'imprimer.

**Comment by maxgfr** [comment]
La première étape que j'implémente avec la CC, c'est de tracker le nombre de personne qui clique sur imprimer le résultat
