### ISSUE TITLE
Contributions : Affichage des références juridiques dans les réponses génériques

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#3304]
# Contributions : Affichage des références juridiques dans les réponses génériques

## Contexte:
Les pages des contributions sont composées de deux parties:
 - Les réponses génériques qui reprennent les aspects légaux et réglementaires  
 - Les réponses "conventionnelles"

Dans l'outil de contribution, ces deux aspects sont traités de façon similaire pour les réponses génériques et conventionnelles.
La contribution qu'elle soit générique ou conventionnelle se compose:
1) du texte de la contribution ou en tout en parties des balises d’ une fiche ( réponses génériques uniquement)
2) de références juridiques, qui se subdivisent en deux blocs:
	-> Les références juridiques liés aux bases KALI ou LEGI
	-> Les références juridiques "autres", qui regroupent des sources juridiques diverses mais à forte valeur ajoutée pour l'utilisateur. 
	Ces dernières se composent d'un label et d'une URL. 

### Problème	
Aujourd'hui, seules les références des* réponses conventionnelles* apparaissent sur la page de contribution du CDTN.

Par exemple ici, on constate l'affiche des références de façon exhaustive dans la partie conventionnelle: 
https://code.travail.gouv.fr/contribution/quand-le-salarie-a-t-il-droit-a-une-prime-danciennete-quel-est-son-montant?q=prime%20d%27anciennet%C3%A9

Dans cette exemple, 
https://code.travail.gouv.fr/contribution/est-il-obligatoire-davoir-un-contrat-de-travail-ecrit-et-signe

le rédacteur a renseigné des articles du code du travail et des références "autres" https://contributions.codedutravail.fabrique.social.gouv.fr/admin/generic-answers/30f78e08-f7db-46df-889c-9dbcc5516199
On constate bien que ces références n'apparaissent pas à l'utilisateur final.

### Solution:

Récupérer depuis l'outil de contribution et proposer pour les contributions génériques les références juridiques et autres ( appelées sources) de façon similaire à ce qui s'affiche pour les références conventionnelles.

**Références:**
	**_Code du travail
	Sources_**

###  Concernant, l'affichage,

Les références juridiques des fiches comprennent fréquemment des blocs d'articles repris sous la forme (Article XXXX- 1 à 12 du code du travail). Dans l'outil de contribution et eu égard aux contraintes de la veille, ces articles sont dépilées. 

Dans ce dernier cas l'affichage de ces mêmes références du code du travail dans la partie réponse générique de la page de contribution va supposer une liste de plusieurs articles. 

Pour limiter les effets indésirables de l'affichage de listes d'articles pour l'utilisateur, il faudrait s'assurer de la mise en place d'un affichage sous forme d'accordéon au-delà d'un certain nombre d'articles. En cohérence avec la solution retenue pour l'affichage des références juridiques pour les réponses conventionnelles.

**Comment by lionelB** [comment]
closed by #3328

**Comment by virginielastisneres** [comment]
Je vais réouvrir l'issue car la solution proposée ne me satisfait pas. 
![image](https://user-images.githubusercontent.com/48682104/110511251-53294d00-8104-11eb-8b84-10162052d07f.png)
Exemple : 
https://master-code-travail.dev2.fabrique.social.gouv.fr/contribution/jours-feries-et-ponts-dans-le-secteur-prive?q=jours%20f%C3%A9ri%C3%A9s

# Solution 

Il faudrait que les références juridiques présentées sur les fiches soit uniquement celles du code du travail numérique. Je ne vois pas l'intérêt de mettre des liens de fiches service-public.fr 

et d'autre part, il faut présenter les références juridiques comme pour les fiches => un bloc avec un accordéon 
![image](https://user-images.githubusercontent.com/48682104/110511913-098d3200-8105-11eb-87f7-51506d7a319f.png)

**Comment by lionelB** [comment]
dans ce cas, il faut aussi modifier les références affichées dans la réponse convention

**Comment by virginielastisneres** [comment]
> dans ce cas, il faut aussi modifier les références affichées dans la réponse convention

d'acc :) oui en effet si cela est lié il le faut :) merci Lionel
