### ISSUE TITLE
Bug sur le simulateur brut/net : accès à l'outil interdit

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3305]
# Description du bug 

Sur le master, la pré-prod et la prod l'outil de simulation du salaire brut/net est inaccessible. 
J'ai ce message : "Ce contenu est bloqué. Pour résoudre le problème, contactez le propriétaire du site."$

Pour info : je suis sur le navigateur Chrome de l'ordinateur du ministère

![image](https://user-images.githubusercontent.com/48682104/107959115-3be2be00-6fa3-11eb-9ce0-56a1510c35a7.png)

**Comment by virginielastisneres** [comment]
A NOTER : sur mon téléphone cela fonctionne bien (navigateur chrome également)

**Comment by virginielastisneres** [comment]
A priori sur FF et Chrome (constats de @lionelB et @rmelisson) cela fonctionne. 
Sur safari sur mon ipad ca fonctionne également. 

Apparemment sur Edge bon également après rafraichissement (cc @jrduscher) 

Donc cela serait un bug que sur les ordinateurs du ministère du travail ?

**Comment by jrduscher** [comment]
testé hors ministère:
Mêmes constats: pour les premières actualisations de page sur le site en prod sur Edge, Firefox et Chrome. Au bout d'un moment, l'outil finit par s'afficher.

**Comment by virginielastisneres** [comment]
> testé hors ministère:
> Mêmes constats: pour les premières actualisations de page sur le site en prod sur Edge, Firefox et Chrome. Au bout d'un moment, l'outil finit par s'afficher.

humm c'est pas bon ca... combien vont penser à rafraichir la page ...

**Comment by virginielastisneres** [comment]
@lionelB tu as fais quelque chose ? car avec @CaptainConan on a l'impression que c'est revenu en fait sur notre ordinateur professionnel 
![image](https://user-images.githubusercontent.com/48682104/108046341-caf3e280-7044-11eb-90ff-f432f5c5b4e6.png)

**Comment by virginielastisneres** [comment]
Par contre j'ai l'impression qu'il galère... je mets un chiffre rien ne se passe. 
![image](https://user-images.githubusercontent.com/48682104/108047165-c7149000-7045-11eb-9d32-c43ed155351c.png)

Idem sur mon téléphone 
![image-c81c4e64-17d9-4771-85b0-085e430ff5d0](https://user-images.githubusercontent.com/48682104/108047360-faefb580-7045-11eb-95a2-d8bdd27592dd.jpg)

**Comment by CaptainConan** [comment]
Effectivement, rien ne se passe (ordi pro, perso, tél) @virginielastisneres

**Comment by virginielastisneres** [comment]
Hello Maxime :) @mquandalle

Je t'ai taggué dans une de nos issues car nous avons des petits soucis avec votre simulateur brut/net. Il semblerait que : 
- dans certains cas il y a un message "Ce contenu est bloqué. Pour résoudre le problème, contactez le propriétaire du site." Après rafraichissement de la page l'outil revient
- Autre point plus inquiétant encore : on indique un chiffre dans l'outil et rien ne se passe, la simulation ne part pas. 

Par hasard, avez-vous eu des alertes d'autres sites utilisant votre outil qui rencontreraient les mêmes soucis ? ou peut-être que cela vient de chez nous...

**Comment by virginielastisneres** [comment]
Chez eux ca fonctionne donc ca doit venir de nous...
![image](https://user-images.githubusercontent.com/48682104/108048814-c5e46280-7047-11eb-96cf-b05e00bd81d4.png)

**Comment by mquandalle** [comment]
Je regarde. Quelques remarques rapidement :

* > Au bout d'un moment, l'outil finit par s'afficher.
  
  C'est probablement le cache local (service worker) qui finit par s'afficher, mais pas la version "live" du simulateur
* J'ai identiifé des erreurs
  > Error: SecurityError: Permission denied to access property "dispatchEvent" on cross-origin object
  
  Je ne sais pas exactement d'où ça vient (la config de votre serveur a t-elle changé récemment ? Sur les en-tête HTTP retournées ?) mais ça me semble lié au problème.

**Comment by mquandalle** [comment]
Je crois que le problème vient de notre côté, on a un affichage cassé sur le site mon-entreprise.fr

**Comment by mquandalle** [comment]
Vous avez encore le problème ? Je n'arrive plus à reproduire.

**Comment by virginielastisneres** [comment]
cc @mquandalle 

Sur firefox depuis ordinateur professionnel cela ne fonctionne toujours pas 
![image](https://user-images.githubusercontent.com/48682104/108078672-3f8f4700-706e-11eb-80e5-06fdaf1b6ef4.png)
Que ca soit sur code.travail.gouv.fr ou sur mon-entreprise.fr

En navigation privée sur firefox j'ai pas l'outil 
![image](https://user-images.githubusercontent.com/48682104/108078872-79604d80-706e-11eb-9e59-d8ed6d9ec5fd.png)

**Comment by virginielastisneres** [comment]
Bizarre pour @m-maillot cela fonctionne sur Firefox...

**Comment by virginielastisneres** [comment]
Android chrome comme navigateur ca ne fonctionnait pas sur code.travail.gouv.fr mais sur mon-entreprise.fr oui
![image-8923ba8a-dd90-49ae-8a75-b63eba18567b](https://user-images.githubusercontent.com/48682104/108079356-05727500-706f-11eb-90ff-3a2c27d238ea.jpg)

c'est étrange un coup c'est bon un coup non

**Comment by virginielastisneres** [comment]
Android chrome comme navigateur ca ne fonctionnait pas sur code.travail.gouv.fr mais sur mon-entreprise.fr oui
![image-8923ba8a-dd90-49ae-8a75-b63eba18567b](https://user-images.githubusercontent.com/48682104/108079356-05727500-706f-11eb-90ff-3a2c27d238ea.jpg)

c'est étrange un coup c'est bon un coup non

**Comment by virginielastisneres** [comment]
après rafraichissement de la page 
![image-dcb83cec-8e36-4e4e-aebe-707bb171a415](https://user-images.githubusercontent.com/48682104/108079754-731ea100-706f-11eb-846a-c4e8b3062494.jpg)

**Comment by m-maillot** [comment]
Suite à un correctif du coté mon-entreprise.fr, je ne reproduis plus. Pouvez vous tester de votre coté  @virginielastisneres @CaptainConan @jrduscher ?

**Comment by virginielastisneres** [comment]
> Suite à un correctif du coté mon-entreprise.fr, je ne reproduis plus. Pouvez vous tester de votre coté @virginielastisneres @CaptainConan @jrduscher ?

Je regarde :) merci Martial

**Comment by virginielastisneres** [comment]
Ca fonctionne pour moi sur ordi navigation chrome et firefox et sur mon tel android sous chrome

**Comment by virginielastisneres** [comment]
merciii @mquandalle ;)

**Comment by mquandalle** [comment]
Pardon pour le bug, on fera en sorte que ça ne se reproduise plus

**Comment by virginielastisneres** [comment]
> Pardon pour le bug, on fera en sorte que ça ne se reproduise plus

Pas de souci Maxime ca arrive :) 

Pour info, j'ai remarqué du coup que vous renvoyez à la fin de la simulateur à un outil de recherche de convention collective. Je sais pas si vous savez mais nous avons un outil de recherche de CCs. :O => https://code.travail.gouv.fr/outils/convention-collective
Je t'invite à regarder et surtout tester notre outil de recherche de CCs qui permet de rechercher via nom de la CC (qui comprends les synonymes ex : syntec ;)) ou son IDCC bien sur mais surtout par le nom de ton entreprise (et en ce moment on le perfectionne pour ajouter la recherche par enseigne et par adresse postale de ton entreprise) 
Si vous voulez une démo ou prés n'hésite pas
