### ISSUE TITLE
Réduire encore plus le nom des conventions collectives ? 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3308]
## Problème à résoudre 

Les noms des conventions collectives restent trop longs 

Ici page CC (surtout qu'ici le nom complet est en dessous...)
![image](https://user-images.githubusercontent.com/48682104/108081693-8599da00-7071-11eb-8b43-c61260f18bed.png)

Ici dans moteur de recherche CC 
![image](https://user-images.githubusercontent.com/48682104/108081868-b974ff80-7071-11eb-9fc1-235ed73e7ab9.png)

## Solution 

Supprimer les mots entre les parenthèses ? car normalement si cela est entre parenthèse c'est que c'est pas important...
A reflechir et à voir l'impact

cc @CaptainConan @rmelisson 

Peut-être que l'on pourrait faire comme pour l'issue sur les méta titles avant de décider avec une liste de toutes les CCs avec : 
- nom actuel 
- nom sans les mots entre parenthèses
Et on regarde rapidos même 700 lignes ca se regarde rapidement ;)

**Comment by CaptainConan** [comment]
Remplaçons les titres longs pour les titres courts (Légifrance le fait :) )

**Comment by virginielastisneres** [comment]
> Remplaçons les titres longs pour les titres courts (Légifrance le fait :) )

J'étais persuadée qu'on l'avait fait... On ne l'avait pas fait ? pourquoi tu sais ? 
je suis pour à 100% 
à voir par contre l'effet notamment au niveau du moteur de CCs

**Comment by CaptainConan** [comment]
> J'étais persuadée qu'on l'avait fait... On ne l'avait pas fait ? pourquoi tu sais ?
> 
Non, je ne m'en rappelle pas.

**Comment by lionelB** [comment]
c'est ce qu'on fait , mais pas toutes les conventions on un nom court. pour le voir c'est sur [le repo kali-data ](https://github.com/SocialGouv/kali-data/blob/master/data/index.json)

**Comment by CaptainConan** [comment]
Grâce au com de @lionelB , je me rappelle pourquoi nous n'étions pas allés plus loin là-dessus:
intégrer le nom court de l'ensemble des CC en vigueur nous demandait une intervention à la main, à partir de la liste issue de BD3C, car la beta de Légifrance ne pointait pas à tous les coups sur le nom court.

**Comment by m-maillot** [comment]
D'autres issues sur le sujet sont en cours. Le soucis est de trouver des noms encore plus court qui font sens.
