### ISSUE TITLE
Articles liés sur les contributions personnalisées

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#3309]
# Description

Lorsque l'on se rend sur une contribution personnalisée avec une convention collective, on a dans la liste des articles liés le même article que l'on consulte actuellement.

![CleanShot 2021-02-16 at 16 45 11@2x](https://user-images.githubusercontent.com/992514/108086956-3787d500-7077-11eb-9225-e05b09adc02b.png)

Le lien mène vers la contribution générique mais ça reste étrange pour un utilisateur.

# Solutions

* Ne pas afficher cet article dans la liste
* Ajouter une indication pour indiquer que c'est sans la convention collective
* autre?

Je ne pense pas que ce soit critique mais je pose l'issue pour en discuter.

@virginielastisneres @rmelisson

**Comment by lionelB** [comment]
j'avais identifié le pb quand on avait ajouté les page contribution spécifique. il faudrait regarder du coté de la requetes elastic si on peut géré ce cas sans rendre la requète trop spécifique. Sinon on peut gérer ça en js une fois les resultats reçus

**Comment by romain-b13** [comment]
Je n'arrive pas à reproduire ce problème
Le souci a t-il été traité ?
