### ISSUE TITLE
[KALI] Cibler les accords non étendu

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#331]
- [ ] Arriver à cibler les accords non étendus
- [ ] Quand on arrive à les cibler, pouvoir extraire les organisations patronales signataires
- [ ] faire le lien avec :https://github.com/SocialGouv/code-du-travail-numerique/issues/308

**Comment by lionelB** [comment]
est ce qu'on devrait pas déplacer cette issue sur le projet kali poke @adipasquale
