### ISSUE TITLE
[Bug] :O Disparition de certaines références juridiques sur nos fiches ! 😨 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3316]
# Bug 

## Description 

Sur certaines fiches Service-public.fr et sur TOUTES les fiches MT nous avons perdu le bloc références juridiques alors que ces fiches ont bien des références juridiques dans la fiche originale. :fearful:

Exemple du bloc 
![image](https://user-images.githubusercontent.com/48682104/108338598-bba49e80-71d6-11eb-8b76-e4c926e31237.png)

#### Fiches SP : 
- https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/fiche-service-public/quels-sont-les-differents-motifs-dabsence-de-lassistante-maternelle
- https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/fiche-service-public/rupture-du-contrat-de-travail-a-duree-indeterminee-cdi
- https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/fiche-service-public/que-devient-le-contrat-du-salarie-au-deces-du-particulier-employeur
- https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/fiche-service-public/licenciement-economique-quelles-indemnites-peut-percevoir-un-salarie

#### Fiches MT : 
- https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/fiche-ministere-travail/formation-professionnelle-stagiaires-et-organismes-de-formation
- https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/fiche-ministere-travail/aide-exceptionnelle-aux-employeurs-qui-recrutent-en-apprentissage 
- https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/fiche-ministere-travail/la-rupture-conventionnelle-du-contrat-de-travail-a-duree-indeterminee

#### Fiches SP : 

- https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/fiche-service-public/registres-du-personnel-obligatoires
- https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/fiche-service-public/fin-de-contrat-documents-a-remettre-au-salarie
- https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/fiche-service-public/quels-sont-les-documents-remis-au-salarie-a-la-fin-de-son-contrat

#### Fiches MT : 

# Solution 

Retrouver ces blocs de référence et les remettre :eyes: :mag:

**Comment by lionelB** [comment]
j'ai déplacé l'issue  pour vers https://github.com/SocialGouv/cdtn-admin/issues/332
