### ISSUE TITLE
Pas beau et pas très lisible questionnaire utilisateur version mobile

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3317]
# Apparition du questionnaire dans les outils

Voilà comme le questionnaire apparait. C'est pas lisible pour l'utilisateur. 

![image-48bc564c-de1b-4efe-8ac6-7338febdc1d1](https://user-images.githubusercontent.com/48682104/108345574-bb100600-71de-11eb-8b0f-7cdab2a2e613.jpg)

# Solution 

Il faudrait qu'il apparaissent comme pour les autres pages 
![image-e960331a-a5f6-4b1c-a15d-a03baf9fb727](https://user-images.githubusercontent.com/48682104/108345859-09250980-71df-11eb-916d-f32b2ba67bc8.jpg)

**Comment by UnbearableBear** [comment]
Bien vu !
