### ISSUE TITLE
[Bug] Modèles avec tableau version mobile 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3319]
# Description Bug 

Pour les modèles suivants (modèles qui ont des tableaux) : 
- https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/modeles-de-courriers/releve-dheures-supplementaires
- https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/modeles-de-courriers/lettre-de-reclamation-des-heures-supplementaires

Le tableau dépasse en version mobile... Il n'est pas responsive 

![image](https://user-images.githubusercontent.com/48682104/108362438-084aa280-71f4-11eb-8420-6959aad74d5b.png)
![image](https://user-images.githubusercontent.com/48682104/108362563-30d29c80-71f4-11eb-9cbd-03dc76245851.png)

# Reproduire bug

Aller sur un modèle et passer en mode mobile 

# Comportement attendu 

C'est assez gênant à la lecture... En plus on a fait une com sur les réseaux sociaux pour le modèle de réclamation d'heures supplémentaires... :/ 

Il faudrait que le tableau soit responsive et rentre dans le cadre de l'écran.

**Comment by UnbearableBear** [comment]
Un tableau ne peut pas être "responsive" malheureusement, mais on peut essayer d’utiliser notre composant d’overflow pour au moins laisser la possibilité de scroll.

**Comment by virginielastisneres** [comment]
> overflow

Comment les tableaux traités dans les fiches service public ? Je suis pour, l'objectif étant que cela soit facilement lisible en version mobile

**Comment by UnbearableBear** [comment]
> > overflow
> 
> Comment les tableaux traités dans les fiches service public ? Je suis pour, l'objectif étant que cela soit facilement lisible en version mobile

Exactement !
