### ISSUE TITLE
Listes des meta title / meta description des contributions avec nouveau formatage automatique 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3326]
## Description 

Suite au test effectué cf. #3297, constat : mis à part quelques 3-4 thèmes qui ne sont pas trop évocateurs pour l'utilisateur les autres sont bien et le titre court des CCs est un bon point. 
Point noir : le titre très long des CCs métallurgies départementales. 

## Solution 

On met en prod la solution indiquée dans le test et on analysera dans 1 à 2 mois s'il y a un impact sur le référencement des pages. 
En parallèle @Jonathan2051 fait une analyse pour évaluer les nombres de recherches effectuées sur google et le marché potentiel que l'on pourrait envisager en termes de trafic sur les 10 premières pages suivantes cf. https://docs.google.com/spreadsheets/d/1R9CfuPJpkXkJm0mlfNRc7Bmlzcoo1HY5sCZXNlgfLZA/edit#gid=0

**Comment by Jonathan2051** [comment]
Le test est positif (beaucoup plus de clics reçus globalement sur ces pages).
A revoir dans 2-3 mois pour confirmer l'impact sur certaines pages.
En savoir plus : https://docs.google.com/document/d/1BjlHoCI8EyML_lyw-lr0WK7RgCgNvcPJKigS54pIQEc/edit?usp=sharing
