### ISSUE TITLE
[ui] safari tooltips

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#3351]
Il semblerait que les tooltips aient un petit souci de CSS sur Safari :

Initial : 

<img width="770" alt="Capture d’écran 2021-03-13 à 12 28 49" src="https://user-images.githubusercontent.com/124937/111028577-c928ff00-83f7-11eb-8503-d0ae8813319e.png">

Over :

<img width="804" alt="Capture d’écran 2021-03-13 à 12 28 56" src="https://user-images.githubusercontent.com/124937/111028589-d7771b00-83f7-11eb-8749-11722d655927.png">

After :

<img width="790" alt="Capture d’écran 2021-03-13 à 12 29 01" src="https://user-images.githubusercontent.com/124937/111028595-dfcf5600-83f7-11eb-9171-b161c17672ab.png">

**Comment by m-maillot** [comment]
Je vais regarder, j'ai un safari sous la main pour tester et corriger :)

**Comment by m-maillot** [comment]
Sandbox pour reproduire le problème avec le code isolé:
https://codesandbox.io/s/bitter-bird-rs5k6

Les pages contenant des tooltips pour tester:
https://code.travail.gouv.fr/fiche-ministere-travail/teletravail-en-periode-de-covid-19
https://code.travail.gouv.fr/information/accord-collectif-dentreprise-nouveautes-covid-19?q=accord
