### ISSUE TITLE
feat(api): proxy and cache of the https://entreprise.data.gouv.fr/api/ calls

### ISSUE THREAD

**Issue by douglasduteil** [SocialGouv/code-du-travail-numerique#3361]
**Problème**

Les apples à l'api `https://entreprise.data.gouv.fr/api/` sont plutôt lents ~1s pour un élément...

```sh
time curl https://entreprise.data.gouv.fr/api/sirene/v1/full_text/boulangerie\?per_page\=1
{"total_results":49873,"total_pages":49873,"per_page":1,"page":1,"etablissement":[...],"spellcheck":null,"suggestions":[...]}
curl   0.01s user 0.00s system 0% cpu 48.495 total
```

**Presque une minute dans le test e2e "Recherche de convention collective"**
https://github.com/SocialGouv/code-du-travail-numerique/blob/c03da1ea4745191a59fad8c3a658ad2d0c88d226/optional/e2e/features/search-ccn.feature#L12-L13
![image](https://user-images.githubusercontent.com/730511/111407325-f31e4200-86d3-11eb-852f-4d770bde522b.png)

**Solution**

Proxy et cache (redis?) de l'api `https://entreprise.data.gouv.fr/api/`

**Comment by lionelB** [comment]
leur serveur est sous l'eau en ce moment, on travaille sur une autre solution qui n'utilisera plus cette api

**Comment by virginielastisneres** [comment]
> sur

d'acc :) tenez moi au courant :)
