### ISSUE TITLE
New UX moteur de recherche des CCs - Outil seul 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3364]
# Rappel du contexte 

Rappel, la recherche des conventions collectives via [notre moteur de recherche actuel ](https://code.travail.gouv.fr/outils/convention-collective) est assez limitée pour le moment. Par exemple, si la raison sociale de l'entreprise est très différente du nom de l'enseigne, il n'y a pas de correspondance entre les deux désignations.

Rémi a fait un gros travail dessus au niveau des différentes données récoltées et également de l'algorithme de recherche utilisé. cc #3207 

Un atelier design a été effectué également avec les designers transversaux de Betagouv pour nous aider à améliorer et à adapter l'UX aux différents comportements des usagers détectés suite à une analyse d'Armand sur le comportement des utilisateurs. 

# Maquette du nouvel UX de l'outil 

On reste bien sur l'idée d'un outil à part qui est également intégrer à d'autres outils (à voir dans une autre issue l'intégration dans les autres outils) 
Les maquettes de l'outil sont à retrouver ici => https://www.figma.com/file/xQi6Tmu3tIzojTwKxmooXP/Recherche-CC?node-id=259%3A0

# 2 parcours distincts 

Nous offrons 2 modes pour rechercher sa convention collective (CC) : 
- via le nom de la CC ou son numéro IDCC : l'utilisateur connait sa CC ou IDCC
- via le nom de l'entreprise du salarié : l'utilisateur ne connait pas ce qu'est ou sa convention collective 

Par conséquent, cela a été retranscrit comme cela au niveau du design : 

#### Titre de l'outil 
"Rechercher sa convention collective"

#### Icône 
**Le SVG est disponible dans la maquette (je n'arrive pas à mettre de SVG dans Github)**
![Picto recherche CC](https://user-images.githubusercontent.com/48682104/111488230-58584e80-8739-11eb-9e9c-6c786827a957.png)

#### Etapes de l'outil sur le côté gauche 
1. Introduction 
2. Entreprise 
3. Convention collective 

### 2. Une présentation de ce qu'est une CC et ou trouver rapidement son nom 
![Group 456](https://user-images.githubusercontent.com/48682104/111484800-5ccf3800-8736-11eb-8a78-be90c24be769.png)

### 3. 2 cartes pour les 2 parcours 
![Group 479](https://user-images.githubusercontent.com/48682104/111484831-62c51900-8736-11eb-8fe2-340c6b7d6f50.png)
Pour le comportement des cartes cela est le même que nos cartes déjà utilisées dans la boite à outils par exemple.

**Comment by virginielastisneres** [comment]
# Parcours 1 : je connais ma convention collective // moteur de recherche via CC

Ici la personne a dans l'Introduction cliqué sur la carte "Je connais ma convention collective. Je la saisis"
L'utilisateur ici arrive donc directement à l'étape 3 convention collective 

## ETAPE : Recherche de la CC 

### 1/ Un titre 
"Précisez et sélectionnez votre convention collective *"

### 2/ Un moteur de recherche 
Mettre le moteur de recherche des CCs qui recherche via le nom de la CC ou le numéro IDCC

![Group 518](https://user-images.githubusercontent.com/48682104/111513320-f99ecf00-8750-11eb-92ff-b7c5595fdf11.png)

#### a/ Une consigne pour le moteur de recherche 
"Nom de la convention collective ou son numéro d’identification (IDCC)"

#### b/ Une icône 
Icône d'un point d'interrogation après la consigne 

#### c/ Texte qui apparait lorsqu'on passe la souris sur l'icône du point d'interrogation  
"L'Identifiant de la Convention Collective (IDCC) est un numéro unique de 4 chiffres déterminant chaque convention collective (Ex : 1090 ou 1486).

Attention à ne pas confondre avec les codes APE (Activité Principale Exercée) ou NAF (Nomenclature des Activités Françaises) qui sont des numéros composés de 4 chiffres et d’une lettre dont l’objectif est d’identifier l’activité principale de l’entreprise (Ex : 4752A)."  

#### d/ Placeholder du moteur de recherche 
"Ex : Transports routiers ou 1486"

#### e/ Un loader lors de la recherche 
Nous n'avions pas cela mais il serait bien de mettre un loader lorsque l'utilisateur commence à rechercher. 
Idée de loader (SVG dans maquette)  
![loader 1](https://user-images.githubusercontent.com/48682104/111514594-2e5f5600-8752-11eb-9e15-fd34106d7697.png)

### 3/ Affichage des résultats 

- On affiche le nombre de résultats : "X conventions collectives trouvées" (si une seule "1 convention collective trouvée")
- 5 résultats max affichés 
- Bouton "voir plus" à partir du 6ème résultat 

Comportement de la liste des résultats 
- Remplissage lorsqu'on passe la souris sur les résultats : #BBCADF
- Surlignage + police Bold des lettres qui correspondent à la recherche de l'utilisateur 

![REF JURIDIQUE](https://user-images.githubusercontent.com/48682104/111972243-8bb22900-8afd-11eb-97a4-8681fc8096d9.png)

### 4/ Sélection d'un résultat 

Lorsque l'usager clique sur une convention collective alors il est envoyé sur la page synthèse de la convention collective en question. 
Exemple pour la CC transports routiers sélectionnées, l'usager attire sur cette page https://code.travail.gouv.fr/convention-collective/16-transports-routiers-et-activites-auxiliaires-du-transport

## Feedback - recherches infructueuses 

### 1/ Pas de résultat 

L'utilisateur indique un nom d'entreprise qui ne renvoie aucun résultat. On affiche alors ce message 
"Aucune convention collective n’a été trouvée
Suggestions :
- Vérifiez l’orthographe des termes de recherche
- Utilisez la rubrique ci-dessous “Vous ne trouvez pas votre convention collective ?”"

Design
![REF JURIDIQUE (2)](https://user-images.githubusercontent.com/48682104/112328751-e80c7880-8cb6-11eb-8952-8445c11f1b28.png)

### 2/ Suite numérique fausse : pas un bon IDCC 

**1. Confusion avec code APE ou NAF** 

L'utilisateur indique une suite de 4 chiffres et une lettre avant ou après (ex : 4711C), on met alors un feedback error avec ce texte : 
"Numéro d’indentification (IDCC) incorrect.
Il semblerait que vous ayez saisi un code APE (Activité Principale Exercée) ou NAF (Nomenclature des Activités Françaises)"

Design
![Group 519](https://user-images.githubusercontent.com/48682104/112329660-ae883d00-8cb7-11eb-83c6-7e423c65f93a.png)
 

![Group 521](https://user-images.githubusercontent.com/48682104/112332350-f4de9b80-8cb9-11eb-8cae-2386610d9448.png) Pour le point d'interrogation on met derrière le texte suivant : 
"Les codes APE (Activité Principale Exercée) ou NAF (Nomenclature des Activités Françaises) qui sont des numéros composés de 4 chiffres et d’une lettre dont l’objectif est d’identifier l’activité principale de l’entreprise.
Ex : 4752A."

**2. Trop de numéros** 

A partir de 5 chiffres remplis par l'utilisateur, il faut afficher un feedback error avec ce texte : 
"Numéro d’indentification (IDCC) incorrect. Ce numéro est composé de 4 chiffres uniquement."

Design 
![Group 520](https://user-images.githubusercontent.com/48682104/112329972-f018e800-8cb7-11eb-97e5-81e8c110b893.png)


## Modale d'aide 

### 1/ Emplacement 

- Une phrase en dessous des résultats pour l'aide "Vous ne trouvez pas votre convention collective ? Consultez notre aide"
- "notre aide" est un bouton qui permet d'ouvrir une modale 

### 2/ Contenu 

"Vous ne trouvez pas votre convention collective ? 
Il peut y avoir plusieurs explications à cela : 
- Votre convention collective a un autre code : si vous le pouvez, utilisez le numéro Siret de votre entreprise. Ce dernier doit être présent sur votre bulletin de paie. 
- Votre convention collective a un statut particulier : administration ou établissement publics, associations, secteur agricole, La Poste, La Croix Rouge etc.
- Votre entreprise n’est rattachée à aucune convention collective."

"Essayez par la recherche de votre entreprise
Avec le nom de l’entreprise, il est possible de retrouver la convention collective associée"
+ Ajouter le moteur de recherche de CCs par nom de l'entreprise

Design
![Group 510](https://user-images.githubusercontent.com/48682104/111979811-cddf6880-8b05-11eb-86cd-b3e137631a23.png)

**Comment by virginielastisneres** [comment]
# Parcours 2 : je ne connais pas ma convention collective // moteur de recherche via Entreprise

Ici la personne a dans l'Introduction cliqué sur la carte "Je ne connais pas ma convention collective. Je la recherche"
L'utilisateur ici arrive donc à l'étape 2 "Entreprise" 

## ETAPE 1 : Recherche de l'entreprise

### 1/ Un titre et une aide
Titre : "Précisez et sélectionnez votre entreprise"
Encart aide avec icone : "Avec le nom de l’entreprise, il est possible de retrouver la convention collective associée"

### 2/ Le moteur de recherche 

On met ici le moteur de recherche des CCs par le nom de l'entreprise

![Group 496 (1)](https://user-images.githubusercontent.com/48682104/112351476-3bd48d00-8cca-11eb-95ab-2ccb3c75c4b2.png)

#### a/ 1er champ : Nom de l'entreprise ou siret 

- Une consigne pour le moteur de recherche : "Nom de votre entreprise ou numéro Siret (obligatoire)" avec une icône point d'interrogation à la fin 

- Texte qui apparait lorsqu'on passe la souris sur l'icône du point d'interrogation : "Le numéro Siret est un numéro de 14 chiffres unique pour chaque entreprise. Il est présent sur la fiche de paie du salarié. Ex : 40123778000127"

- Placeholder du moteur de recherche : "Ex : Café de la gare ou 40123778000127 " 

#### b/ 2ème champ : Code postal  

- Une consigne pour le moteur de recherche : "Code postal ou ville" 

- Placeholder du moteur de recherche : "Ex : 31000 ou Toulouse" 


### 3/ Affichage des résultats 

![Group 499](https://user-images.githubusercontent.com/48682104/112355037-91f6ff80-8ccd-11eb-8d85-20fa734143c3.png)

#### a/ Un loader lors de la recherche 
Nous n'avions pas cela mais il serait bien de mettre un loader lorsque l'utilisateur commence à rechercher. 
Cela vaut dès qu'il rempli un champ donc s'il a rempli le nom de l'entreprise loader puis il remplit le code postal loader également.
Idée de loader (SVG dans maquette)  
![loader 1](https://user-images.githubusercontent.com/48682104/111514594-2e5f5600-8752-11eb-9e15-fd34106d7697.png)

#### b/ Afficher le nombre de résultats obtenus 

**Si champ nom de l'entreprise rempli uniquement**
Afficher le nombre de résultat au dessus des résultats avec le texte suivant : "X entreprises correspondant au mieux à votre recherche (affiner avec le code postal)"

**Si les 2 champs remplis**
Afficher le nombre de résultat au dessus des résultats avec le texte suivant : "X entreprises correspondant au mieux à votre recherche" 

#### c/ Les résultats en tant que tel 

Différentes éléments à indiquer en fonction des situations 

- **Entreprise sans établissement** : on affiche le nom de l'entreprise, l'activité de l'entreprise en couleur différente et adresse. Voir les maquettes pour les polices, couleurs et espaces à respecter

- **Entreprise avec établissement** : on affiche le nom de l'entreprise, l'activité et via un label le nombre d'établissement

- **Entreprise avec établissement** mais l'établissement qui matche a un nom différent de l'entreprise : on affiche le nom de l'entreprise, le nom de l'établissement qui matche avec la recherche, l'activité et via un label le nombre d'établissements.

POUR TOUS LES CAS : on surligne et on met en bold les lettres de recherche qui matchent avec la recherche. Cf. maquettes

#### d/ Survol des résultats

![Group 26 (2)](https://user-images.githubusercontent.com/48682104/112355268-c66abb80-8ccd-11eb-93cf-927fb45626d6.png)

- Remplissage lorsqu'on passe la souris sur les résultats : #BBCADF
- Les noms des activités passent en couleur #2A3356 pour respect un contraste accessible
- Surlignage + police Bold des lettres qui correspondent à la recherche de l'utilisateur 

### 4/ Sélection d'un résultat
 


## Feedback - recherches infructueuses 

### 1/ Pas de résultat 

**Texte** 

"Aucune entreprise n’a été trouvée

Suggestions :

- Vérifiez l’orthographe des termes de recherche
- Utilisez la rubrique ci-dessous “Vous ne trouvez pas votre entreprise ? Consultez notre aide”"

**Design** 
![REF JURIDIQUE (4)](https://user-images.githubusercontent.com/48682104/112510525-c9c77b00-8d91-11eb-8261-595c05ccaf65.png)

### 2/ Suite numérique fausse : pas un bon Siret/Siren 

#### a. Si moins de 9 chiffres indiqués

**Texte**
"Veuillez indiquer un numéro Siret (14 chiffres) ou Siren (9 chiffres) valide"

**Design**
![Group 446](https://user-images.githubusercontent.com/48682104/112509738-09da2e00-8d91-11eb-9afe-04ee1dd0e00b.png)


#### b. Plus de 10 chiffres indiqués 

**Texte**
"Veuillez indiquer un numéro Siret valide (14 chiffres obligatoire)"

**Design**
![Group 446 (1)](https://user-images.githubusercontent.com/48682104/112510173-7a814a80-8d91-11eb-91b7-34a0bac72dbf.png)


#### d. 14 chiffres indiqués et des lettres en trop

**Texte**
"Veuillez indiquer un numéro Siret valide (14 chiffres uniquement)"

**Design**
![Group 446 (2)](https://user-images.githubusercontent.com/48682104/112510252-8c62ed80-8d91-11eb-8a9c-e45d80b28c1d.png)


## Modale d'aide 

### 1/ Emplacement 

- Une phrase en dessous des résultats pour l'aide "Vous ne trouvez pas votre entreprise ? Consultez notre aide"
- "notre aide" est un bouton qui permet d'ouvrir une modale 

### 2/ Contenu 

![Group 509](https://user-images.githubusercontent.com/48682104/112511132-65f18200-8d92-11eb-9c85-d58c653b068d.png)

#### Partie 1 : "Vous ne trouvez pas votre entreprise ?" 

"Il peut y avoir plusieurs explications à cela : 

-  Votre entreprise a été enregistrée sous un autre nom ou un autre code : si vous le pouvez, utilisez son numéro Siret. Ce dernier doit être présent sur votre bulletin de paie. 
- Votre entreprise a un statut particulier : administration ou établissement publics, associations, secteur agricole, La Poste, La Croix Rouge etc. ;
- Votre entreprise n’a pas de convention collective."

#### Partie 2 : "Essayez par l’activité de votre entreprise"

- On met ici le moteur de recherche de convention collective 
- Consigne à indiquer : Recherchez par mots clés
- Placeholder : "Ex : Boulangerie ou transports routiers"

## ETAPE 2 : Résultat pour l'entreprise sélectionnée

Lorsque l'utilisateur sélectionne une entreprise, il arrive sur **l'étape 3 : convention collective**. 

Est présent sur cette étape : 
- un titre : "Convention collective"
- un résumé de l'entreprise sélectionnée : "Vous avez sélectionné l’entreprise suivante :" puis encart de l'entreprise sélectionnée cf. maquette
- phrase annonce du résultat en rouge : X convention(s) collective(s) trouvée(s) pour “nom de l'entreprise”
- résultats des conventions trouvées sous forme de carte comme celles présentes dans les résultats du moteur général

![Group 526](https://user-images.githubusercontent.com/48682104/112355422-e9956b00-8ccd-11eb-921e-86d11feeabb8.png)

**Comment by virginielastisneres** [comment]
# Tracking 

On voudrait avoir comme données et donc traquer les éléments suivants : 

- [x] **Clics sur les 2 blocs "Je connais ma CC" et "Je ne connais pas ma CC"**
**Catégorie de l'évent** : cc_search_type_of_users
**Action de l'évent** : click_p1 ou click_p2
**Name de l'évent** : [nom de la page]

## Parcours 1 

- [x] **Les recherches effectuées par l'utilisateur**
Il existe déjà un tracking : 
**Catégorie de l'évent** : cc_search_p1
**Action de l'évent** : [nom de la page] 
**Name de l'évent** : [nom de la recherche]


- [x] **La CC sélectionnée par l'utilisateur**
**Catégorie de l'évent** : cc_select_p1
**Action de l'évent** : [nom de la page] 
**Name de l'évent** : [nom de la CC sélectionnée]

- [x] **Les clics sur le bouton "Précédent"** 
Catégorie de l'évent : view_step_cc_search_p1
Action de l'évent : back_step_cc_search_p1
Name de l'évent : [nom de l'étape]

- [x] **Les clics sur la modale "Help"** 
Catégorie de l'évent : cc_search_help
Action de l'évent : click_cc_search_help_p1


## Parcours 2 

- [x] **Les recherches effectuées par l'utilisateur**
**Catégorie de l'évent** :enterprise_search
**Action de l'évent** : [nom de la page] 
**Name de l'évent** :  [nom de la recherche d'entreprise]

- [x] **Recherches par code postal//villes** pour le parcours recherche par entreprise
Catégorie de l'évent : enterprise_search 
Action de l'évent : [nom de la page] 
Name de l'évent : [nom de la recherche] ## [adresse]
est-ce qu'avec cela on peut relier avec la recherche de l'entreprise ? 

- [x] **L'entreprise sélectionnée par l'utilisateur** dans le parcours recherche par entreprise
**Catégorie de l'évent** : enterprise_select
**Action de l'évent** : [nom de la page] 
**Name de l'évent** : [nom de l'entreprise sélectionnée] 

- [x] **La CC sélectionnée par l'utilisateur**
**Catégorie de l'évent** : cc_select_p2 
**Action de l'évent** : [nom de la page] 
**Name de l'évent** : [nom de la CC sélectionnée]

- [x] **Les clics sur le bouton "Précédent"** 
Catégorie de l'évent : view_step_cc_search_p2
Action de l'évent : back_step_cc_search_p2
Name de l'évent : [nom de l'étape]


- [x] **Les clics sur le bouton "Précédent"**  (retour election entreprise)
Catégorie de l'évent : view_step_cc_search_p2
Action de l'évent : back_step_cc_select_p2
Name de l'évent : [nom de l'étape]

- [x] **Les clics sur la modale "Help"** 
Catégorie de l'évent : cc_search_help
Action de l'évent : click_cc_search_help_p2

**Comment by rmelisson** [comment]
Quelques remarques sur les events :
- pas de selection : c'est pê compliqué de créer un event pour ça, je pense qu'on devra le calculer lors de l'analyse des logs (lorsque l'on ne trouve pas l'event selection)
- position : la position pourra être envoyée dans l'event "selection entreprise / cc" directement 
- selection : je pense qu'il vaut mieux avoir un seul event "cc_select" et on devrait pouvoir passer le type (p1/p2) dans l'event directement
- [nom de la page] qu'est ce que cela représente ? c'est toujours la même page non ?

finalement, je pense que cette spec est bien complète, et je regarderai plus en details avec Lionel lors du dev

**Comment by lionelB** [comment]
je me demande si on devrait pas uniformiser les Category / Action / Name / Value des évènement qu'on veut suivre

**Comment by lionelB** [comment]
qu'est ce que représente `[nom de l'étape]` ?
c'est le nom de la page ou l'url ? dans les précédente version on passait aussi un uuid en plus du nom de l'evenement 
ex: ` matopush(["trackEvent", "cc_search", path, `${trackingUID} : ${query}`]);`
sachant qu'on peut passer4 valeur a trackEvent
- Event Category
- Event Action
- Event Name
- Event Value

est ce qu'on laisserai pas l'uuid dans value ?

**Comment by lionelB** [comment]
Pour la sélection de l'entreprise on prend le label. 
Est ce qu'on devrait pas prendre plutôt le siren   ?

**Comment by rmelisson** [comment]
- oui clairement, il faut plutôt prendre le siren
- question uniformisation, est-ce qu'on peut respecter le format utilisé pour les autres outils ?

**Comment by ArmandGiraud** [comment]
Si je comprends bien les 2 events  `recherches effectuées par l'utilisateur` et  `CC sélectionnée par l'utilisateur` sont déclenchés au même moment (au select de la CC)? Auquel cas on aurait pas de log pour les recherches ne générant pas de select (c'est gênant il nous faudrait une trace), On pourrait garder la logique actuelle avec un debounce de quelques secondes. Une autre option serait de déclencher un event en cas de delete ou de retour en arrière, mais pas sûr que ce soit vraiment souhaitable.
What you think @lionelB ?

> est ce qu'on laisserai pas l'uuid dans value ?

Cet uuid permet d'identifier les requêtes infructueuses. Par exemple un user tape "syntech", ne trouve rien, efface syntech, et écrit à la place "bureau d'études". Sans cet uuid je ne suis pas sûr que la nouvelle recherche concerne le même user/session.  Mais on peut toujours capitaliser sur l'id utilisateur matomo. 

Pour les category d'event, il serait pas mal d'avoir le même préfix pour tous les event qui concernent cet outil, pour regrouper facilement tous les events qui le concerne. 

et si on pouvait avoir des noms d'event un peu plus explicites que p1 p2 par exemple `view_step_cc_search_known- unknown` ce serait top :) .

**Comment by lionelB** [comment]
> On pourrait garder la logique actuelle avec un debounce de quelques secondes. Une autre option serait de déclencher un event en cas de delete ou de retour en arrière, mais pas sûr que ce soit vraiment souhaitable.
> What you think @lionelB ?

oui c'est ce qui est place

> est ce qu'on laisserai pas l'uuid dans value ?

pour un parcours, on génére un uuid au chargement de la page est qui est passé dans chaque event


> et si on pouvait avoir des noms d'event un peu plus explicites que p1 p2 par exemple `view_step_cc_search_known- unknown` ce serait top :)

pour les noms des event c'est lié au parcours, (p1 = parcours 1 = je connais ma cc et p2 = parcours 2 = je connais pas ma cc)
on peut être suffixer tout les event qui reste par p1 / p2 sinon ?

dispo pour en discuter pour harmoniser tout ca

**Comment by romain-b13** [comment]
Pour le tracking : correctif à appliquer car dans les logs on arrive pas à différencier les recherches des 2 parcours

**Comment by ArmandGiraud** [comment]
Pas la peine. On a 2 events différents, c'est moi qui n'avait pas compris 😬
