### ISSUE TITLE
ajouter du wording explicatif calculateur

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#338]

**Comment by jrduscher** [comment]
- [ ] meilleure moyenne
- [ ] wording explicatif

**Comment by lionelB** [comment]
en attente du wording

**Comment by jrduscher** [comment]
Sorry!!
Wording sur le premier écran:
Ce calculateur vous permettra une estimation de votre indemnité de licenciement. il tien t compte de l’indemnité légale de licenciement de l’indemnité conventionnelle pour en livrer le montant plus favorable. Un accord collectif au niveau de l'entreprise peut prévoir un montant différent.

**Corrections de wording** ( suite à une remarque pertinente d'hier, si on s'adresse aux employeurs des TPE, le wording doit être adapté et à minima être neutre):

- [ ] Est ce que la date de fin de votre contrat se situe avant le 26 Août 2017 ?: A quelle date a le liceniment at-il été pronconcé?
- Est ce que votre entreprise est affilié à une convention collective ?:

**Comment by lionelB** [comment]
- ~~Est ce que votre entreprise est affilié à une convention collective ?:~~  
on laisse comme ca en attendant de pouvoir faire quelque chose de mieux avec les signataire d'un accord

**Comment by revolunet** [comment]
question de style, perso je préfère les formules type "Votre entreprise est-elle affiliée à xxx" plutôt que "Est-ce que votre entreprise est affilée à xxx" ? (plus léger IMO)

**Comment by lionelB** [comment]
ah zut :(  il faudrait qu'on harmonise avec @jrduscher
