### ISSUE TITLE
debt(react-ui): built icons components comitted 

### ISSUE THREAD

**Issue by douglasduteil** [SocialGouv/code-du-travail-numerique#3384]
Going through the `react-ui` package, I was suprise to found that we commit the result of the [svgr](https://github.com/gregberge/svgr) transformation (see [./packages/react-ui/src/icons/components](packages/react-ui/src/icons/components))
It would be preferable to have an `socialgouv/cdtn-icons` package with the svg source code only.

**Comment by m-maillot** [comment]
Passage sous dsfr prévue cette année.
