### ISSUE TITLE
[Admin] Authentification longue ou impossible

### ISSUE THREAD

**Issue by CaptainConan** [SocialGouv/code-du-travail-numerique#3387]
**Description**
L'authentification dans l'admin prend une dizaine de secondes ou nécessite un rechargement de la page.

![CDTN admin login KO](https://user-images.githubusercontent.com/53531631/111955131-661b2480-8ae9-11eb-90e0-d7ff1e5fd4fc.png)

  - Navigateur: Chrome
  - Version du navigateur : 89.0.4389.90

**Comment by lionelB** [comment]
j'ai déplacé l'issue sur cdtn-admin https://github.com/SocialGouv/cdtn-admin/issues/364
