### ISSUE TITLE
[Bug] OUTIL EXTERNES INACCESSIBLES 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3400]
**Description**
Lorsque je clique sur un outil externe rien ne se passe. Je ne peux pas accéder au site correspondant. 

**Reproduction**
Si on recherche "index égapro" ou "élections professionnelles" et que l'on clique sur la tuile : 

"EGALITÉ PROFESSIONNELLE
Index Egapro
L’outil de calcul de votre index égalité professionnelle femmes-hommes
Consulter"

ou 
"REPRÉSENTATION DU PERSONNEL
Élections professionnelles
Le site dédié aux élections professionnelles et à la représentativité syndicale
Consulter"

Rien ne se passe. 

**Comportement attendu**
Normalement en cliquant sur les tuiles des outils externes on devrait arriver sur les sites correspondants. 
En l'espèce, sur le site https://index-egapro.travail.gouv.fr/ ou https://www.elections-professionnelles.travail.gouv.fr/

**Screenshots**
![image](https://user-images.githubusercontent.com/48682104/112818398-c5e27400-9083-11eb-985e-2ecb6191695f.png)

**Comment by lionelB** [comment]
le probleme provient des requetes pré-enregistrées qui ne fournisse pas l'url
voir la fonction toRefs (fetchCdtnAdminDocuments.js)

**Comment by virginielastisneres** [comment]
@lionelB je clôture ok ?
