### ISSUE TITLE
Afficher notre niveau d'accessibilité sur toutes les pages + une page explicative

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3404]
# Rappel des obligations 

En tant que site public, nous avons l'obligation même si n'avons pas effectué d'audit d'accessibilité d'afficher notre niveau d'accessibilité. 
Tant que le niveau de conformité est inconnu, il est considéré comme non conforme.

cf.image issue du site https://pidila.gitlab.io/checklist-pidila/
![Capture d’écran 2021-03-31 à 17 21 34](https://user-images.githubusercontent.com/48682104/113169106-954a3800-9245-11eb-9b56-3670bf5a0027.png)

Autre source d'explication => https://www.numerique.gouv.fr/publications/rgaa-accessibilite/obligations/#mention-obligatoire-sur-la-page-daccueil

Autre obligation cette mention de notre niveau d'accessibilité doit ensuite être un lien vers une page dédiée à la déclaration d'accessibilité.
![Capture d’écran 2021-03-31 à 17 20 15](https://user-images.githubusercontent.com/48682104/113168963-6b911100-9245-11eb-90d1-824dc39e4b2f.png)

# 1. Ajouter "Accessibilité : non conforme" dans le footer 

Voici un exemple d'affichage du niveau. 
![Capture d’écran 2021-03-31 à 17 12 03](https://user-images.githubusercontent.com/48682104/113167914-74351780-9244-11eb-9976-a7ed9eb22cd5.png)

Ajouter "Accessibilité : non conforme" dans le footer dans la colonne après "Mentions légales" et avant "Politique de confidentialité"
![Capture d’écran 2021-03-31 à 17 16 42](https://user-images.githubusercontent.com/48682104/113168411-eefe3280-9244-11eb-9ed6-9ee2404ffc6b.png)

# 2. Une page dédiée à la déclaration d'accessibilité 

3 exemples de pages qui n'ont pas encore effectué d'audit d'accessibilité : 
- page de [g_nuis e sante](https://gnius.esante.gouv.fr/accessibilite)
- page de [Betagouv](https://beta.gouv.fr/accessibilite/) 

## Contenu 
Mettre un lien derrière "Accessibilité : non conforme" qui renvoie à une page comprenant ce texte => [ICI](https://docs.google.com/document/d/1ouk54P4pInmXkDrecuHclSemTh8ZrhSsH9_7Rqar9p4/edit#)

## Design 
Pour le design on reprend le même que pour les pages A propos, Mentions Légales ou Politique de confidentialité. 
Exemples : 
- https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/a-propos
- https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/politique-confidentialite

**Comment by m-maillot** [comment]
@virginielastisneres tu peux voir le résultat ici : https://07a90f0-code-travail.dev2.fabrique.social.gouv.fr/
N'hésite pas à l'indiquer si tu vois des choses à modifier.

**Comment by virginielastisneres** [comment]
> @virginielastisneres tu peux voir le résultat ici : https://07a90f0-code-travail.dev2.fabrique.social.gouv.fr/
> N'hésite pas à l'indiquer si tu vois des choses à modifier.

Super merci martial je regarde ça :)

**Comment by virginielastisneres** [comment]
@m-maillot C'est parfait, juste 2/3 mini corrections : 

1. Partie : "Déclaration d’accessibilité"
J'ai l'impression mais c'est peut être un effet optique qu'il y a un espace après 2021 et avant le point. 
![Capture d’écran 2021-04-12 à 13 54 50](https://user-images.githubusercontent.com/48682104/114376449-b04a6f80-9b96-11eb-9c01-58b893791ad4.png)

2. Partie "Amélioration et contact"
Je mettrai pas de C majuscule à "code.travail.gouv.fr" et je rajouterai 2 petits mots à cette phrase "vous pouvez contacter le responsable de Code.travail.gouv.fr ..." par "vous pouvez contacter le responsable du site Internet code.travail.gouv.fr ..."
![Capture d’écran 2021-04-12 à 13 55 45](https://user-images.githubusercontent.com/48682104/114376593-ce17d480-9b96-11eb-994e-eb114984f1ed.png)

Voilà sinon perfect :) merciiii premier pas vers une meilleure accessibilité ;)

**Comment by m-maillot** [comment]
> J'ai l'impression mais c'est peut être un effet optique qu'il y a un espace après 2021 et avant le point.

En effet, c'est un effet optique car il n'y pas d'espace. Ce doit venir de la police qui doit aligner le 1 sur la gauche.

> Je mettrai pas de C majuscule à "code.travail.gouv.fr" et je rajouterai 2 petits mots à cette phrase "vous pouvez contacter le responsable de Code.travail.gouv.fr ..." par "vous pouvez contacter le responsable du site Internet code.travail.gouv.fr 

Ok même remarque que pour @lionelB qui ne mettait pas le lien mais l'idée était la même.
