### ISSUE TITLE
Le focus des tooltips

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3405]
# Retours audit d'Anne-Sophie 

"Sur la page https://code.travail.gouv.fr/fiche-ministere-travail/les-jours-feries-et-les-ponts?q=congés payés, je ne sais pas où est le focus à ce stade :" 
![Capture_decran_2021-03-16_a_13 45 00](https://user-images.githubusercontent.com/48682104/114401633-2ad5b800-9bb4-11eb-9cf9-284000604b6b.png)

# Obligation RGAA liée

Critère 10.7. Dans chaque page web, pour chaque élément recevant le focus, la prise de focus est-elle visible ?
cf ici : https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/#topic10

![Capture d’écran 2021-04-12 à 17 26 20](https://user-images.githubusercontent.com/48682104/114401723-3e811e80-9bb4-11eb-9208-8dee1450e3a4.png)

**Comment by m-maillot** [comment]
Je ne reproduis pas le soucis. J'ai essayé sur différents navigateurs et j'ai bien le focus qui est visible sur les tooltips:

Safari:
<img width="855" alt="CleanShot 2021-04-09 at 16 25 21@2x" src="https://user-images.githubusercontent.com/992514/114195145-7e47cc00-9950-11eb-8bfa-f2a8a9a4e306.png">

Chrome:
<img width="837" alt="CleanShot 2021-04-09 at 16 26 37@2x" src="https://user-images.githubusercontent.com/992514/114195168-843dad00-9950-11eb-9979-b041db872cd1.png">

Firefox:
<img width="946" alt="CleanShot 2021-04-09 at 16 26 46@2x" src="https://user-images.githubusercontent.com/992514/114195197-8bfd5180-9950-11eb-8502-362934bd520c.png">

**Comment by virginielastisneres** [comment]
> Je ne reproduis pas le soucis. J'ai essayé sur différents navigateurs et j'ai bien le focus qui est visible sur les tooltips:
> 
> Safari:
> <img alt="CleanShot 2021-04-09 at 16 25 21@2x" width="855" src="https://user-images.githubusercontent.com/992514/114195145-7e47cc00-9950-11eb-8bfa-f2a8a9a4e306.png">
> 
> Chrome:
> <img alt="CleanShot 2021-04-09 at 16 26 37@2x" width="837" src="https://user-images.githubusercontent.com/992514/114195168-843dad00-9950-11eb-9979-b041db872cd1.png">
> 
> Firefox:
> <img alt="CleanShot 2021-04-09 at 16 26 46@2x" width="946" src="https://user-images.githubusercontent.com/992514/114195197-8bfd5180-9950-11eb-8502-362934bd520c.png">

ah bizarre quand elle l'a montré c'était pas comme ça, je vais check également de mon côté et regarder plus en détails ce que dit le RGAA dessus :)

**Comment by virginielastisneres** [comment]
Cette question pourra être demandé sur le channel accessibilité en effet. 

J'ai regardé sur Service-Public.fr ils mettent bien le focus comme nous lorsqu'on sélectionne au clavier la définition. La seule différence est lorsqu'on passe avec la souris sur le mot, le mot change de couleur il devient bleu. Je ne sais pas si cela est une obligation...

Exemple : https://www.service-public.fr/particuliers/vosdroits/F2405#main
![Capture d’écran 2021-04-12 à 17 14 59](https://user-images.githubusercontent.com/48682104/114400084-aafb1e00-9bb2-11eb-9038-36ab0667d020.png)

**Comment by virginielastisneres** [comment]
@m-maillot J'ai trouvé ce critère RGAA qui parle des survols est ce que ça serait pas ça ? https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/#topic10
![Capture d’écran 2021-04-12 à 17 20 27](https://user-images.githubusercontent.com/48682104/114400902-7cca0e00-9bb3-11eb-9b10-f7d995a04feb.png)

**Comment by m-maillot** [comment]
Il parle de lien, là ce n'est pas un lien... je ne pense pas que ce soit lié mais à valider.

**Comment by virginielastisneres** [comment]
> Il parle de lien, là ce n'est pas un lien... je ne pense pas que ce soit lié mais à valider.

d'acc :)

**Comment by m-maillot** [comment]
Question posée sur Slack, en attente de retours.
https://startups-detat.slack.com/archives/C015LNMTTJ9/p1618234295011900

**Comment by virginielastisneres** [comment]
Méthodologie de test pour vérifier le critère trouvée sur https://www.numerique.gouv.fr/publications/rgaa-accessibilite/documentation-rgaa/methodologie-test/

![Capture d’écran 2021-04-12 à 17 38 10](https://user-images.githubusercontent.com/48682104/114403740-1b576e80-9bb6-11eb-90c9-8b2207e09371.png)

**Comment by virginielastisneres** [comment]
J'ai vraiment l'impression que c'est parce que le focus est quasi invisible sur Firefox... c'est vrai qu'il faut le chercher pour le voir comparé aux autres navigateurs. 
![Capture d’écran 2021-04-12 à 17 58 51](https://user-images.githubusercontent.com/48682104/114407389-645cf200-9bb9-11eb-9699-7fb93619213e.png)

D'ailleurs en testant le focus sur firefox je ne comprends pas il y a pleins de boutons où le focus ne fonctionne pas. Exemple si je veux aller sur le bouton en haut à droite de la page "Boite à outils" je n'y ai pas accès. Et je viens de regarder sur safari c'est pareil...

**Comment by m-maillot** [comment]
Sur Slack, on remonte le soucis que le focus est perdu entre “accord de branche” et "dispositions" sur cette page: “accord de branche”.

En effet, le focus part ensuite sur le lien dans la popup mais qui disparait car il n'y a plus de focus sur le texte, du coup tu es perdu.

**Comment by m-maillot** [comment]
> D'ailleurs en testant le focus sur firefox je ne comprends pas il y a pleins de boutons où le focus ne fonctionne pas. Exemple si je veux aller sur le bouton en haut à droite de la page "Boite à outils" je n'y ai pas accès. Et je viens de regarder sur safari c'est pareil...

Il n'y a peut être pas qu'un seul soucis :(

**Comment by virginielastisneres** [comment]
@m-maillot autre commentaire dans Slack (comprends pas tout mais je te le mets ici ahah)

"dans Stylus
https://addons.mozilla.org/en-US/firefox/addon/styl-us/
avec :
:focus {
    outline: 5px solid black !important;
}
on obtient un indicateur de focus très visible. Sauf sur les webcomponents (info bulles sur jour fériés, accord de branche, dispositions)."

**Comment by m-maillot** [comment]
Du coup, c'est la règle 10.7.1 `Un style du focus défini par l’auteur est visible.` qui n'est pas respecté ici.

On a donc 2 soucis à corriger:
* Un style du focus défini par l’auteur est visible. (testable avec Stylus)
* La perte du focus après accord de branche sur cette page https://code.travail.gouv.fr/fiche-ministere-travail/les-jours-feries-et-les-ponts?q=cong%C3%A9s

Pour le deuxième point, je cherche la règle exacte.

**Comment by m-maillot** [comment]
Pour le deuxième point, c'est cette règle du coup : https://www.w3.org/TR/WCAG21/#focus-visible

**Comment by m-maillot** [comment]
Pas mal de documentation ici aussi:
https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html

On a un soucis avec "accord de branche" car le tooltip contient une action et un tooltip ne devrait pas contenir d'action, sinon ce n'est plus un tooltip.

Il y a plusieurs solutions envisageables ici:
 * Transformer nos tooltips en modals. L'utilisateur doit cliquer sur un texte qui ouvre une modale qui va afficher la description. Cette dernière peut être fermée avec un bouton dédié. 
 * Supprimer le lien pour l'accord de branche et mettre une explication (pas terrible car on perd le lien direct...)
 * Première solution mais que pour les tooltips contenant des actions. Peut être dérangeant pour l'utilisateur.

**Comment by m-maillot** [comment]
J'ai réussi à gérer le focus sur le lien

![CleanShot 2021-04-23 at 15 28 45](https://user-images.githubusercontent.com/992514/115881015-9ab52f80-a44b-11eb-950f-0d5d30007956.gif)


Il reste le style sur le focus à gérer.

**Comment by virginielastisneres** [comment]
> J'ai réussi à gérer le focus sur le lien
> 
> ![CleanShot 2021-04-23 at 15 28 45](https://user-images.githubusercontent.com/992514/115881015-9ab52f80-a44b-11eb-950f-0d5d30007956.gif)
> 
> Il reste le style sur le focus à gérer.

Yes super :) :) :) Du coup tu n'as pas eu besoin de faire une des 3 solutions envisagées :)

**Comment by virginielastisneres** [comment]
Pour le style du focus on est d'accord que c'est surtout avec le navigateur Firefox non ? ou de manière générale ?

**Comment by m-maillot** [comment]
Non c'est pour l'ensemble des navigateurs. L'idée est qu'un utilisateur avec un handicap utilise un outil pour améliorer la visibilité du focus qui n'est pas terrible sur certains navigateurs... Le soucis c'est que ça ne marche pas sur nos tooltips :( Ca semble venir du composant que l'on utilise... Je n'ai pas encore trouvé de solution mais je suis tombé sur de la documentation technique sur le sujet:

 * https://stackoverflow.com/questions/32417235/how-to-make-a-custom-web-component-focusable
 * https://github.com/WICG/webcomponents/blob/gh-pages/proposals/custom-element-default-focus.md
 
Rien de très encourageant :(
Le fait d'avoir des composant custom semble ne pas aider les navigateurs dans cette tâche. Après cela vient peut être de l'outil stylus. Il faut que je regarde de ce coté.
