### ISSUE TITLE
L'utilisateur est averti de l'ouverture d'une nouvelle fenêtre (dossier Covid)

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3406]
# Retours d'Anne-Sophie 
![Capture d’écran 2021-04-12 à 18 13 19](https://user-images.githubusercontent.com/48682104/114408813-da158d80-9bba-11eb-8471-ac8980b39493.png)

# Obligation accessibilité 

Critère 13.2. Dans chaque page web, l’ouverture d’une nouvelle fenêtre ne doit pas être déclenchée sans action de l’utilisateur. Cette règle est-elle respectée ?

Méthodologie du test pour vérifier le respect de cette obligation 
![Capture d’écran 2021-04-12 à 18 19 13](https://user-images.githubusercontent.com/48682104/114409612-ad15aa80-9bbb-11eb-9561-eecb24dcc561.png)

Autre info dessus : https://checklists.opquast.com/fr/assurance-qualite-web/lutilisateur-est-averti-des-ouvertures-de-nouvelles-fenetres
https://aveuglesdefrance.org/initier-un-premier-pas-vers-laccessibilite-numerique/conseil-n7-prevenir-lutilisateur-en-cas-douverture-dune-nouvelle-fenetre/

# Solution à faire

## 1. Dossier Covid : les PDF 

**Pour chaque lien étant un PDF il faut :** 

1. Ajouter l'icone indiquant l'ouverture d'une nouvelle fênetre
2. Le libellé suivant après le titre du lien (PDF - "taille du pdf") comme cela est fait pour nos modèles 
3. Puis attribut title mentionnant (nouvelle fenêtre) cf le point 3 de l'issue

Voici un bon exemple 
![Capture d’écran 2021-04-12 à 18 46 28](https://user-images.githubusercontent.com/48682104/114413882-6d50c200-9bbf-11eb-94c6-8b9953723112.png)

**Quels liens dans le dossier sont des PDF ? Voici la liste ici :** 
- "Covid-19 : organisation et fonctionnement des restaurants d'entreprise" dans la rubrique Santé et sécurité au travail
- "Covid-19 : gestion des cas contacts entreprise" dans la rubrique Santé et sécurité au travail
- "Conseils et bonnes pratiques pour l'employeur" dans la rubrique Santé et sécurité au travail
- "Conseils et bonnes pratiques pour les salariés" dans la rubrique Santé et sécurité au travail

## 2. Dossier Covid : les liens externes autre que PDF 

**Pour chaque lien étant un PDF il faut :** 

1. Ajouter l'icone indiquant l'ouverture d'une nouvelle fênetre
2. Puis attribut title mentionnant (nouvelle fenêtre) cf le point 3 de l'issue

**Quels liens dans le dossier sont des liens externes ? Voici la liste ici :** 

Rubrique Contenus populaires 
- Covid-19 : vaccination par les services de santé au travail

Arrêt maladie et personnes vulnérables
- Personnes vulnérables
- Demander un arrêt maladie en ligne

Aides exceptionnelles pour les entreprises => TOUS LES LIENS

Activités partielles (chômage partiel et APLD)
- Activité partielle : démarches de l’employeur (chômage partiel ou technique)
- Demander l’activité partielle
- Simulateur d’activité partielle

Santé et sécurité au travail
- Covid-19 : vaccination par les services de santé au travail
- Protocole national pour assurer la santé et la sécurité des salariés en entreprise face à l’épidémie de COVID-19

Jeunes : aides à l’embauche
- Contrat de professionnalisation
- Renforcement des dispositifs d’inclusion durable dans l’emploi
- Présentation du plan de relance apprentissage

Travailleurs handicapés : aides exceptionnelles => TOUS LES LIENS

Formation professionnelle et apprentissage
- Dispositif de FNE-Formation

Ressources utiles => TOUS LES LIENS

## 3. Sur tout le site : Informer sur l'ouverture d'une nouvelle fenêtre

Voilà ce que j'ai trouvé pour respecter le critère : https://checklists.opquast.com/fr/assurance-qualite-web/lutilisateur-est-averti-des-ouvertures-de-nouvelles-fenetres

"Mise en œuvre
Ajouter une mention du type « (nouvelle fenêtre) », soit directement dans le libellé du lien, soit dans son attribut title qui doit alors reprendre et compléter le libellé.
Ajouter une mention du type « (nouvelle fenêtre) » dans les étiquettes de contrôle de formulaire, dans les libellés de boutons ou dans tout autre objet provoquant l'ouverture d'une nouvelle fenêtre."

Il semblerait que l'icône ne soit pas un problème en soit quand je vois sur service-public.fr ils l'ont bien. Par contre, ils indiquent (nouvelle fenêtre) dans l'attribut title 
cf capture d'écran dessous  : 
![Capture d’écran 2021-04-12 à 18 28 34](https://user-images.githubusercontent.com/48682104/114411400-31b4f880-9bbd-11eb-916a-36828f17dbf0.png)

Par contre chez nous nous n'avons pas cet attribut 
![Capture d’écran 2021-04-12 à 18 28 26](https://user-images.githubusercontent.com/48682104/114411363-29f55400-9bbd-11eb-930c-67c7de13ca71.png)

**Comment by virginielastisneres** [comment]
@lionelB @m-maillot Je reouvre cette issue car du coup j'ai pu vérifier sur master la PR mergée et il me manque des trucs :

1. LES PDF 

Il manque l'indication entre parenthèse (PDF - avec la taille) pour le lien qui télécharge un pdf 
Pour rappel, voici les liens sur lesquels l'information doit être rajoutée :
- "Covid-19 : organisation et fonctionnement des restaurants d'entreprise" dans la rubrique Santé et sécurité au travail
- "Covid-19 : gestion des cas contacts entreprise" dans la rubrique Santé et sécurité au travail
- "Conseils et bonnes pratiques pour l'employeur" dans la rubrique Santé et sécurité au travail
- "Conseils et bonnes pratiques pour les salariés" dans la rubrique Santé et sécurité au travail

![Capture d’écran 2021-04-27 à 17 17 56](https://user-images.githubusercontent.com/48682104/116248391-e41fba80-a77c-11eb-86c7-80820c159616.png)

2. LE LABEL 

Pour le label arial-label, j'ai bien vu que cela a été mis sur les liens externes. On peut le voir ici, c'est super
![Capture d’écran 2021-04-27 à 17 23 47](https://user-images.githubusercontent.com/48682104/116249258-af603300-a77d-11eb-8594-ec09ecc74952.png)

Par contre, je m'interroge pour les liens par contre du dossier car j'ai regardé pour les liens externes et je vois pas le label 
![Capture d’écran 2021-04-27 à 17 24 04](https://user-images.githubusercontent.com/48682104/116249430-e1719500-a77d-11eb-84a4-0b91389a3142.png)

**Comment by lionelB** [comment]
> Par contre, je m'interroge pour les liens par contre du dossier car j'ai regardé pour les liens externes et je vois pas le label

le aria-label est sur la balise a (celle qui contient l'attribut `href` qui indique la destination du lien.

**Comment by lionelB** [comment]
Covid-19 : Conseils et bonnes pratiques pour l’employeur (pdf - 1.8 Mo)
Covid-19 : Conseils et bonnes pratiques pour le salarié (pdf - 1.1 Mo)
Covid-19 : gestion des cas contacts en entreprise (pdf - 167.5 ko) 
Covid 19 : Restauration d’entreprise (pdf - 923.6 ko)

**Comment by virginielastisneres** [comment]
> Covid-19 : Conseils et bonnes pratiques pour l’employeur (pdf - 1.8 Mo)
> Covid-19 : Conseils et bonnes pratiques pour le salarié (pdf - 1.1 Mo)
> Covid-19 : gestion des cas contacts en entreprise (pdf - 167.5 ko)
> Covid 19 : Restauration d’entreprise (pdf - 923.6 ko)

Super 👍

**Comment by lionelB** [comment]
exemple https://c6c1e20-code-travail.dev2.fabrique.social.gouv.fr/dossiers/ministere-du-travail-notre-dossier-sur-le-coronavirus

**Comment by romain-b13** [comment]
@lionelB @m-maillot Quand je regarde cette ancienne issue  je me demande du coup s'il ne manque pas des pictos pour signaler l'ouverture d'une nouvelle fenêtre ex :
- "Mon compte formation" dans la boite à outils https://preprod-code-du-travail-numerique.dev2.fabrique.social.gouv.fr/outils
- Les outils externes : telerc (rupture conventionnelle individuelle) et simulateur d'aides 1jeune1solution

![Image collée à 2021-7-1 16-50](https://user-images.githubusercontent.com/84397271/124274575-b9b5f900-db41-11eb-8bef-309bbd8ed43d.png)
![Image collée à 2021-7-1 16-48](https://user-images.githubusercontent.com/84397271/124274581-bae72600-db41-11eb-8c58-18546b325208.png)
