### ISSUE TITLE
RECHERCHE CCN PAR IDCC

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#341]
sans doute pas chronophage.
La recherche sur legifrance via l'IDCC est déceptive dans le cas suivant:
"0843" ne marche pas
"843" marche.
supprimer le 0 des IDCC pour la recherchedans legifrance.

**Comment by revolunet** [comment]
ex: La CC des boulangeries devrait apparaitre en 1er ici : 

![capture d ecran 2018-11-29 a 10 56 56](https://user-images.githubusercontent.com/124937/49289823-4dfce280-f4a5-11e8-8961-816fe6aaa145.png)

**Comment by lionelB** [comment]
closed by #358
