### ISSUE TITLE
Etude de la mesure de la satisfaction des usagers 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3417]
# Contexte 
Voici la question à laquelle l'étude doit répondre :
**Comment analyser la satisfaction des usagers grâce à de nombreux indicateurs et pas uniquement la question de satisfaction présente sur chaque contenu ?**
@Armandgrd 

# Résultats de l'étude 

1ère chose déjà l'indication de la question de satisfaction des usager n'est pas assez précise et pertinente : elle nécessité donc une refonte cc issue #2550 
@Armandgrd je te laisserai compléter et modier cette issue. Elle me permet de rajouter cela au planning surtout dans le doing

**Comment by ArmandGiraud** [comment]
En attente du development de l'outil de feedback #2550
