### ISSUE TITLE
Mise à jour des adresses des Services de renseignement

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#3429]
CF #4 pour historique.

### Contexte

Aujourd'hui, avec l'encart " Besoin de plus d'informations?"; le CDTN renvoie vers les services en région, et plus précisément sur les pages de modalités de contact des services sur les site des DIRECCTE.

### Problème
Les DIRECCTE et DIECCTE ont évolué vers les DEETS ET DREETS depuis le 1er avril2021. L'impact sur les urls a été constaté ce matin. 
A ce stade une simple redirection est en place, qui évite les erreurs 404 sur tous les liens ( après vérification).

### Solution 
Pour autant la liste des direccte peut être durablement actualisée et remplacée comme suit :

Liste vérifiée le 9/04/2021

95	https://idf.drieets.gouv.fr/Rendez-vous-droit-du-travail-Paris-93-94-95
94	https://idf.drieets.gouv.fr/Rendez-vous-droit-du-travail-Paris-93-94-95
93	https://idf.drieets.gouv.fr/Rendez-vous-droit-du-travail-Paris-93-94-95
92	https://idf.drieets.gouv.fr/Rendez-vous-droit-du-travail-Paris-93-94-95	
91	https://idf.drieets.gouv.fr/Une-question-en-droit-du-travail
90	https://bourgogne-franche-comte.dreets.gouv.fr/Renseignements-en-droit-du-travail-par-telephone-uniquement-le-matin-18337
89	https://bourgogne-franche-comte.dreets.gouv.fr/Renseignements-en-droit-du-travail-par-telephone-uniquement-le-matin-18334
88	https://grand-est.dreets.gouv.fr/Presentation-de-l-Unite-departementale-Nous-contacter-17714
87	https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-droit-du-travail-17666
86	https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-droit-du-travail-5599
85	https://pays-de-la-loire.dreets.gouv.fr/Acces-au-droit-du-travail-les-DDETS-et-DDETS-PP-ex-UD-Direccte-vous-renseignent
84	https://paca.dreets.gouv.fr/Les-numeros-utiles-de-l-Unite-departementale-du-Vaucluse
83	https://paca.dreets.gouv.fr/Les-numeros-utiles-de-l-Unite-departementale-du-Var
82	https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
81	https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
80	https://hauts-de-france.dreets.gouv.fr/Salaries-et-employeurs-du-secteur-prive-renseignez-vous-sur-le-droit-du-travail
79	https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-en-droit-du-travail
78	https://idf.dreets.gouv.fr/Une-question-en-droit-du-travail
77	https://idf.dreets.gouv.fr/Une-question-en-droit-du-travail
76	https://normandie.dreets.gouv.fr/Un-numero-unique-pour-contacter-le-service-de-renseignements-en-droit-du-6180
75	https://idf.dreets.gouv.fr/Une-question-en-droit-du-travail
74	https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
73	https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
72	https://pays-de-la-loire.dreets.gouv.fr/Acces-au-droit-du-travail-les-DDETS-et-DDETS-PP-ex-UD-Direccte-vous-renseignent
71	https://bourgogne-franche-comte.dreets.gouv.fr/Le-renseignement-du-public
70	https://bourgogne-franche-comte.dreets.gouv.fr/Ou-se-renseigner-4594
69	https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
68	https://grand-est.dreets.gouv.fr/Renseignements-en-droit-du-travail-18664
67	https://grand-est.dreets.gouv.fr/Renseignements-en-droit-du-travail-18663
66	https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
65	https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
64	https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-droit-du-travail-17672
63	https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
62	https://hauts-de-france.dreets.gouv.fr/Salaries-et-employeurs-du-secteur-prive-renseignez-vous-sur-le-droit-du-travail
61	https://normandie.dreets.gouv.fr/Un-numero-unique-pour-contacter-vos-services-de-renseignements-en-droit-du-18314
60	https://hauts-de-france.dreets.gouv.fr/Salaries-et-employeurs-du-secteur-prive-renseignez-vous-sur-le-droit-du-travail
59	https://hauts-de-france.dreets.gouv.fr/Salaries-et-employeurs-du-secteur-prive-renseignez-vous-sur-le-droit-du-travail
58	https://bourgogne-franche-comte.dreets.gouv.fr/Renseignements-en-droit-du-travail-par-telephone-uniquement-le-matin-18336	
57	https://grand-est.dreets.gouv.fr/Presentation-de-l-Unite-departementale-Nous-contacter-17710
56	https://bretagne.dreets.gouv.fr/Renseignement-au-public-3009
55	https://grand-est.dreets.gouv.fr/Presentation-de-l-Unite-departementale-Nous-contacter-17709
54	https://grand-est.dreets.gouv.fr/Presentation-de-l-Unite-departementale-Nous-contacter-17708
53	https://pays-de-la-loire.dreets.gouv.fr/Acces-au-droit-du-travail-les-DDETS-et-DDETS-PP-ex-UD-Direccte-vous-renseignent
52	https://grand-est.dreets.gouv.fr/Presentation-de-l-Unite-departementale-Nous-contacter-17707
51	https://grand-est.dreets.gouv.fr/Presentation-de-l-Unite-departementale-Nous-contacter-17706
50	https://normandie.dreets.gouv.fr/Un-numero-unique-pour-contacter-vos-services-de-renseignements-en-droit-du-18313
49	https://pays-de-la-loire.dreets.gouv.fr/Acces-au-droit-du-travail-les-DDETS-et-DDETS-PP-ex-UD-Direccte-vous-renseignent
48	https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
47	https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-droit-du-travail-17671
46	https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
45	https://centre-val-de-loire.dreets.gouv.fr/L-application-du-droit-du-travail-17737
44	https://pays-de-la-loire.dreets.gouv.fr/Acces-au-droit-du-travail-les-DDETS-et-DDETS-PP-ex-UD-Direccte-vous-renseignent
43	https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
42	https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
41	https://centre-val-de-loire.dreets.gouv.fr/L-application-du-droit-du-travail
40	https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-droit-du-travail-17670
39	https://bourgogne-franche-comte.dreets.gouv.fr/Ou-se-renseigner-4595
38	https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
37	https://centre-val-de-loire.dreets.gouv.fr/Indre-et-Loire
36	https://centre-val-de-loire.dreets.gouv.fr/Indre-4954
35	https://bretagne.dreets.gouv.fr/Renseignements-au-public
34	https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
33	https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-droit-du-travail-17665
32	https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
31	https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
30 	https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
29	https://bretagne.dreets.gouv.fr/Renseignements-en-droit-du-travail-en-Bretagne
28	https://centre-val-de-loire.dreets.gouv.fr/Eure-et-Loir
27	https://normandie.dreets.gouv.fr/Un-numero-unique-pour-contacter-vos-services-de-renseignements-en-droit-du
26	https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
25	https://www.clicrdv.com/direccte-bourgogne-franche-comte
24	https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-droit-du-travail-17669
23	https://nouvelle-aquitaine.dreets.gouv.fr/Creuse
22	https://bretagne.dreets.gouv.fr/Le-Service-Renseignement-du-Public-2949
21	https://bourgogne-franche-comte.dreets.gouv.fr/Contacts-et-horaires-d-ouverture-des-services-au-public
19	https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-droit-du-travail-17668
18	https://centre-val-de-loire.dreets.gouv.fr/L-application-du-droit-du-travail-17722
17	https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-droit-du-travail-6373
16	https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-droit-du-travail-17780
15	https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
14	https://normandie.dreets.gouv.fr/Un-numero-unique-pour-contacter-vos-services-de-renseignements-en-droit-du
13	https://paca.dreets.gouv.fr/Renseignements-sur-la-legislation-du-travail
12	https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
11	https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
10	https://grand-est.dreets.gouv.fr/Renseignements-en-droit-du-travail-18657
9	https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
8	https://grand-est.dreets.gouv.fr/Renseignements-en-droit-du-travail
7	https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
6	https://paca.dreets.gouv.fr/Alpes-Maritimes
5	https://paca.dreets.gouv.fr/Le-Service-Renseignement-en-droit-du-Travail
4	https://paca.dreets.gouv.fr/Alpes-de-Haute-Provence
3	https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
2a	https://corse.dreets.gouv.fr/Renseignements-en-droit-du-travail
2b	https://corse.dreets.gouv.fr/Renseignements-en-droit-du-travail-17835
1	https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail

**Comment by virginielastisneres** [comment]
@jrduscher Merci :) 
Est ce qu'il serait possible de rajouter les DOMTOM également ? ;)

**Comment by jrduscher** [comment]
Ajouter des adresses des SR en DEETS: liste modifiée comme suit (19/04) :


95 https://idf.drieets.gouv.fr/Rendez-vous-droit-du-travail-Paris-93-94-95
94 https://idf.drieets.gouv.fr/Rendez-vous-droit-du-travail-Paris-93-94-95
93 https://idf.drieets.gouv.fr/Rendez-vous-droit-du-travail-Paris-93-94-95
92 https://idf.drieets.gouv.fr/Rendez-vous-droit-du-travail-Paris-93-94-95
91 https://idf.drieets.gouv.fr/Une-question-en-droit-du-travail
90 https://bourgogne-franche-comte.dreets.gouv.fr/Renseignements-en-droit-du-travail-par-telephone-uniquement-le-matin-18337
89 https://bourgogne-franche-comte.dreets.gouv.fr/Renseignements-en-droit-du-travail-par-telephone-uniquement-le-matin-18334
88 https://grand-est.dreets.gouv.fr/Presentation-de-l-Unite-departementale-Nous-contacter-17714
87 https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-droit-du-travail-17666
86 https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-droit-du-travail-5599
85 https://pays-de-la-loire.dreets.gouv.fr/Acces-au-droit-du-travail-les-DDETS-et-DDETS-PP-ex-UD-Direccte-vous-renseignent
84 https://paca.dreets.gouv.fr/Les-numeros-utiles-de-l-Unite-departementale-du-Vaucluse
83 https://paca.dreets.gouv.fr/Les-numeros-utiles-de-l-Unite-departementale-du-Var
82 https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
81 https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
80 https://hauts-de-france.dreets.gouv.fr/Salaries-et-employeurs-du-secteur-prive-renseignez-vous-sur-le-droit-du-travail
79 https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-en-droit-du-travail
78 https://idf.dreets.gouv.fr/Une-question-en-droit-du-travail
77 https://idf.dreets.gouv.fr/Une-question-en-droit-du-travail
76 https://normandie.dreets.gouv.fr/Un-numero-unique-pour-contacter-le-service-de-renseignements-en-droit-du-6180
75 https://idf.dreets.gouv.fr/Une-question-en-droit-du-travail
74 https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
73 https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
72 https://pays-de-la-loire.dreets.gouv.fr/Acces-au-droit-du-travail-les-DDETS-et-DDETS-PP-ex-UD-Direccte-vous-renseignent
71 https://bourgogne-franche-comte.dreets.gouv.fr/Le-renseignement-du-public
70 https://bourgogne-franche-comte.dreets.gouv.fr/Ou-se-renseigner-4594
69 https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
68 https://grand-est.dreets.gouv.fr/Renseignements-en-droit-du-travail-18664
67 https://grand-est.dreets.gouv.fr/Renseignements-en-droit-du-travail-18663
66 https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
65 https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
64 https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-droit-du-travail-17672
63 https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
62 https://hauts-de-france.dreets.gouv.fr/Salaries-et-employeurs-du-secteur-prive-renseignez-vous-sur-le-droit-du-travail
61 https://normandie.dreets.gouv.fr/Un-numero-unique-pour-contacter-vos-services-de-renseignements-en-droit-du-18314
60 https://hauts-de-france.dreets.gouv.fr/Salaries-et-employeurs-du-secteur-prive-renseignez-vous-sur-le-droit-du-travail
59 https://hauts-de-france.dreets.gouv.fr/Salaries-et-employeurs-du-secteur-prive-renseignez-vous-sur-le-droit-du-travail
58 https://bourgogne-franche-comte.dreets.gouv.fr/Renseignements-en-droit-du-travail-par-telephone-uniquement-le-matin-18336
57 https://grand-est.dreets.gouv.fr/Presentation-de-l-Unite-departementale-Nous-contacter-17710
56 https://bretagne.dreets.gouv.fr/Renseignement-au-public-3009
55 https://grand-est.dreets.gouv.fr/Presentation-de-l-Unite-departementale-Nous-contacter-17709
54 https://grand-est.dreets.gouv.fr/Presentation-de-l-Unite-departementale-Nous-contacter-17708
53 https://pays-de-la-loire.dreets.gouv.fr/Acces-au-droit-du-travail-les-DDETS-et-DDETS-PP-ex-UD-Direccte-vous-renseignent
52 https://grand-est.dreets.gouv.fr/Presentation-de-l-Unite-departementale-Nous-contacter-17707
51 https://grand-est.dreets.gouv.fr/Presentation-de-l-Unite-departementale-Nous-contacter-17706
50 https://normandie.dreets.gouv.fr/Un-numero-unique-pour-contacter-vos-services-de-renseignements-en-droit-du-18313
49 https://pays-de-la-loire.dreets.gouv.fr/Acces-au-droit-du-travail-les-DDETS-et-DDETS-PP-ex-UD-Direccte-vous-renseignent
48 https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
47 https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-droit-du-travail-17671
46 https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
45 https://centre-val-de-loire.dreets.gouv.fr/L-application-du-droit-du-travail-17737
44 https://pays-de-la-loire.dreets.gouv.fr/Acces-au-droit-du-travail-les-DDETS-et-DDETS-PP-ex-UD-Direccte-vous-renseignent
43 https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
42 https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
41 https://centre-val-de-loire.dreets.gouv.fr/L-application-du-droit-du-travail
40 https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-droit-du-travail-17670
39 https://bourgogne-franche-comte.dreets.gouv.fr/Ou-se-renseigner-4595
38 https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
37 https://centre-val-de-loire.dreets.gouv.fr/Indre-et-Loire
36 https://centre-val-de-loire.dreets.gouv.fr/Indre-4954
35 https://bretagne.dreets.gouv.fr/Renseignements-au-public
34 https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
33 https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-droit-du-travail-17665
32 https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
31 https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
30 https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
29 https://bretagne.dreets.gouv.fr/Renseignements-en-droit-du-travail-en-Bretagne
28 https://centre-val-de-loire.dreets.gouv.fr/Eure-et-Loir
27 https://normandie.dreets.gouv.fr/Un-numero-unique-pour-contacter-vos-services-de-renseignements-en-droit-du
26 https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
25 https://www.clicrdv.com/direccte-bourgogne-franche-comte
24 https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-droit-du-travail-17669
23 https://nouvelle-aquitaine.dreets.gouv.fr/Creuse
22 https://bretagne.dreets.gouv.fr/Le-Service-Renseignement-du-Public-2949
21 https://bourgogne-franche-comte.dreets.gouv.fr/Contacts-et-horaires-d-ouverture-des-services-au-public
19 https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-droit-du-travail-17668
18 https://centre-val-de-loire.dreets.gouv.fr/L-application-du-droit-du-travail-17722
17 https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-droit-du-travail-6373
16 https://nouvelle-aquitaine.dreets.gouv.fr/Renseignements-droit-du-travail-17780
15 https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
14 https://normandie.dreets.gouv.fr/Un-numero-unique-pour-contacter-vos-services-de-renseignements-en-droit-du
13 https://paca.dreets.gouv.fr/Renseignements-sur-la-legislation-du-travail
12 https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
11 https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
10 https://grand-est.dreets.gouv.fr/Renseignements-en-droit-du-travail-18657
9 https://occitanie.dreets.gouv.fr/Modalites-de-renseignements-en-droit-du-travail-a-la-DREETS-Occitanie
8 https://grand-est.dreets.gouv.fr/Renseignements-en-droit-du-travail
7 https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
6 https://paca.dreets.gouv.fr/Alpes-Maritimes
5 https://paca.dreets.gouv.fr/Le-Service-Renseignement-en-droit-du-Travail
4 https://paca.dreets.gouv.fr/Alpes-de-Haute-Provence
3 https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
2a https://corse.dreets.gouv.fr/Renseignements-en-droit-du-travail
2b https://corse.dreets.gouv.fr/Renseignements-en-droit-du-travail-17835
1 https://auvergne-rhone-alpes.dreets.gouv.fr/Vos-interlocuteurs-en-droit-du-travail
 _ _ 
971 https://guadeloupe.deets.gouv.fr/nos-adresses
972 https://martinique.deets.gouv.fr/Renseignements-en-droit-du-travail-prenez-rendez-vous-en-ligne
973 https://guyane.deets.gouv.fr/Infos-droit-du-travail,2790
974 https://reunion.deets.gouv.fr/Un-numero-unique-pour-contacter-vos-services-de-renseignements-en-droit-du

**Comment by virginielastisneres** [comment]
Merci @jrduscher pour cette liste :)

**Comment by revolunet** [comment]
Ce serait pas possible de demander à la DGT/DREETS une vue consolidée des horaires et contacts ?

Je veux bien consolider la liste initiale si besoin; Ca permettrait de proposer une meilleure UX 😃
