### ISSUE TITLE
Réflexion: Index ES selon les environnements

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#3443]
**Lexique**

cdtn-admin : Représente l'administation de CDTN
cdtn-frontend : Représente le frontend de CDTN (site visible par l'ensemble des utilisateurs) 
index: Index dans ES

**Contexte**

Suite à la mise en place d'un environnement de master/pre-prod/prod pour ctdn-admin, un mécanisme a été mis en place pour assurer la compatibilité du format de données au niveau d'ES entre cdtn-admin et ctdn-frontend.

Ce mécanisme consiste à la mise en place d'un index sur ES versionné afin d'éviter des conflits de versions durant des mise à jour incluant des break changes sur les formats. En effet, ctdn-admin va alimenter ES avec des documents sous un format spécifique. De l'autre coté, cdtn-frontend va venir consommer cette donnée. L'admin étant le créateur de la donnée, s'il vient à changer le format, cela peut casser cdtn-frontend.

Cela n'est pas bloquant car l'on va mettre à jour cdtn-frontend pour utiliser ce nouveau format. Cependant, cela entraine une coupure du service entre le moment où l'on met à jour les données dans ES via le nouvel cdtn-admin et la mise à jour de cdtn-frontend.

Pour palier à ce problème, l'index dans ES a été versionnée. Ce dernier contient la version majeure de cdtn-admin qui est l'indicateur quand le format des données changent et entraine des breaking changes. 

Le workflow sera donc:
 * L'index ES est en version 1, cdtn-frontend va récupérer ces données dans cet index.
 * On met à jour cdtn-admin avec des changements dans la structure des données, on tag en version 2.X.Y
 * On déploie cdtn-admin sur la prod et on décide de mettre à jour les données (@lionelB c'est bien une action manuelle ici ?)
 * cdtn-admin va créer l'index en version 2 et populer les données
 * cdtn-frontend continue de pointer sur la version 1 et est donc toujours fonctionnel
 * On met à jour le cdtn-frontend pour pointer sur la version 2 et la migration est transparente pour l'utilisateur 🎉 

Question: Que fait on de l'ancien index ? Il y a un process de clean ? 

Nous avons aujourd'hui 4 environnements possibles:
 1. Feature: pull request contenant une nouvelle fonctionnalité
 2. Master: environnement avec l'ensemble des derniers devs réalisés
 3. Pre-prod: environnement de validation pour le métier (pouvoir jouer avec les données sans impacter la prod)
 4. Prod: environnement de production

**Sujets**

Il y a 3 sujets qui aujourd'hui demande réflexion:

 1. Comment nommer l'index ? 

Aujourd'hui, on a 2 indexs ES (cdtn-document et cdtn-???). Pour la montée de version, il a été décidé d'ajouter la version à ces indexs: `cdtn-document-v1`, `cdtn-document-v2`... Cette version s'appuie sur la version majeure de cdtn-admin qui est récupéré via le tag dans GIT. L'idée est de voir comment on nomme cet index dans les différents environnements.

En parallèle, il est important de noter que l'on a 2 instances d'elasticsearch disponibles, une pour la prod et une autre pour le dev.

 2. Gérer les données dans ES selon les environnements

L'idée est de voir comment on récupère les données et de où ? Notamment lors d'une branche feature.

 3. Utiliser `cdtn-elasticsearch` comme source of truth pour la gestion de l'index (naming, accès...) 

On dispose aujourd'hui d'une librairie `cdtn-elasticsearch`. Il faudrait définir son rôle. Une idée est de lui donner le rôle de source of truth pour ES. Elle aurait donc la responsabilité de fournir l'url et l'index pour se connecter à ES. cdtn-admin et cdtn-frontend pourrait alors s'appuyer sur cette librairie pour récupérer les infos. Renovator pourrait nous aider à garder à jour le frontend sur le modèle de données.

**Comment by lionelB** [comment]
>     * On déploie cdtn-admin sur la prod et on décide de mettre à jour les données (@lionelB c'est bien une action manuelle ici ?)

la release est manuelle et la mise en prod automatique

**Comment by m-maillot** [comment]
*Comment nommer l'index ?*

On versionne avec master

*Gérer les données dans ES selon les environnements*

cdtn-feature-branch-v1

**Comment by romain-b13** [comment]
@m-maillot C'est une issue en cours ?

**Comment by m-maillot** [comment]
On peut fermer, l'idée étant de passer par un autre mécanisme.
