### ISSUE TITLE
[CCN] Changement de titre de la CCN 1518: ECLAT (ex-animation)

### ISSUE THREAD

**Issue by CaptainConan** [SocialGouv/code-du-travail-numerique#3449]
**Prise en compte du changement de titre de la CCN 1518 (ex-animation)**

Le changement de nom de la CCN 1518 vient d'arriver sur Légifrance, désormais  **"convention collective nationale des métiers de l'éducation, de la culture, des loisirs et de l'animation agissant pour l'utilité sociale et environnementale, au service des territoires (ÉCLAT)"**. 
il s'agit de prendre en compte cette nouvelle dénomination dans tous nos éléments.

@jrduscher a fait la modification dans l'outil de contrib et j'ai effectué la modification dans l'admin.
Pour autant, d'autres modifications pourraient être nécessaires (poke @rmelisson @ArmandGiraud @lionelB @m-maillot @virginielastisneres ).

**Comment by virginielastisneres** [comment]
Bonne question florent :) @lionelB @m-maillot. Le changement de nom dans l'admin, l'outil de contrib et dans Legifrance sont-ils suffisants pour que cela soit bien modifié dans notre simulateur par exemple ?

**Comment by lionelB** [comment]
il faut probablement faire une modif coté kali-data aussi

**Comment by lionelB** [comment]
j'ai modifié l'index https://github.com/SocialGouv/kali-data/commit/0ffb56d92de7432c6c621d0e97f256173b6b3e00 
la modif dans le container est arrivé le 20 avril. Des que la nouvelle version sera prete, il faudrait mettre à jour la prod avec les nouvelles données

**Comment by lionelB** [comment]
il faudrait aussi modifier et afficher le titre long dans la page

**Comment by virginielastisneres** [comment]
@lionelB que reste-t-il a faire sur cette tâche ? Je ne vois pas de changement en prod lors de la recherche de la CC ?

**Comment by lionelB** [comment]
je pense que c'est ok, cf l'api » https://api-preprod-code-travail.dev2.fabrique.social.gouv.fr/api/v1/items/7d5c621b2c
c'est juste qu'on afficher plus le nom long dans la page CC » https://preprod-code-travail.dev2.fabrique.social.gouv.fr/convention-collective/1518-animation?q=1518

**Comment by romain-b13** [comment]
La CC 1518 (ex-animation) est toujours intitulée "Animation" en prod ce qui est normal puisque l'on affiche le nom court et que sur legifrance le nom court est toujours "animation"
Ce qu'il pourrait être intéressant de faire serait d'afficher le nom court en titre et afficher le nom long en dessous en petits caractères car aujourd'hui on affiche la même chose aux 2 endroits : 

![image](https://user-images.githubusercontent.com/84397271/136800223-26d523fa-3776-4ee2-93fe-2e55a03aad52.png)

**Autre exemple :** 

![image](https://user-images.githubusercontent.com/84397271/136800650-85ebc8f9-cbf8-465f-961d-575e3704fc19.png)
