### ISSUE TITLE
Requêtes préqualifiées : rapports de requêtes

### ISSUE THREAD

**Issue by rmelisson** [SocialGouv/code-du-travail-numerique#3458]
Fournir à l'équipe métier les rapports de requête sous forme de fichier Excel afin de faciliter la correction des requêtes prequalifiées.

- 1 tableau "préqualifiées"
- 1 tableau "search"
- ajouter les score NDCG / clic ratio ... (+ résultats avec clics)

**Comment by virginielastisneres** [comment]
@rmelisson je ferme l'issue vu que cela a été fait/ Maintenant c'est au métier de s'en emparer
