### ISSUE TITLE
détecter dans le texte : " article LXXX-x et suivants"

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#346]
- [ ] L'expression L3231-1 et svts ou L3231-1 et suivants:  
            Comprend les articles de la section ou sous section suivant l'article mentionné
              Détecter la sous- section, (LEGI ou KALI selon la source)
              Proposer les articles contenus dans la sous-section à la suite de l'article.
exemple: L3231-1 et suivants:  L3231-1 ( article seul dans sa ss section) adjoindre les articles de la section suivante L3231-2 et 3. 
L'article en l'espèce est le premier article d'un chapitre, l'auteur voulait soit cibler les articles immédiatement après ou tout le chapitre.

**Comment by revolunet** [comment]
PI une base de grammaire pour detecter ces expressions : https://framagit.org/parlement-ouvert/metslesliens

**Comment by jrduscher** [comment]
DuraLex/SedLex permet de visualiser l'impact d'un amendement sur les textes de loi en "parsant" la grammaire légistique pour en déduire automatiquement un "diff" à appliquer.

1/2 https://twitter.com/ljo/status/1070681933389148160

**Comment by ClementChapalain** [comment]
lié à #210 (et #106 dans une moindre mesure)

**Comment by ClementChapalain** [comment]
réglé par #549
