### ISSUE TITLE
Page Modèle de document (Certificat de travail) H3 incohérente

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3462]
# Contexte

Cf #3441 

Nous avons détecté une incohérence dans la hiérarchie des balises Hn de cette page => https://code.travail.gouv.fr/modeles-de-courriers/certificat-de-travail

![Capture d’écran 2021-05-04 à 11 12 02](https://user-images.githubusercontent.com/48682104/116970757-98fc2f00-acc9-11eb-86a0-3cae5bfe34c4.png)
 
En effet, le titre du modèle "certificat de travail" est en H3 créant donc un saut de balise entre le titre de la page en H1 et le titre du modèle en H3. 

# Solution 

Solution proposée par @lionelB et @m-maillot  : 
- Mettre une balise <article> qui représente du contenu autonome dans un document, une page, une application, ou un site. cf. https://developer.mozilla.org/fr/docs/Web/HTML/Element/article
- Martial évoquait également un label "prévisualisation du documen" ?

**Comment by romain-b13** [comment]
Ce problème sera traité dans l'issue https://github.com/SocialGouv/code-du-travail-numerique/issues/3514
