### ISSUE TITLE
Pages internes niveau 2 navigation (boite à outils, thèmes, stats etc.) incohérence balises

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3463]
# Contexte

Cf #3441 

Dans nos pages internes type 
- La boite à outils
![Capture d’écran 2021-05-04 à 11 50 05](https://user-images.githubusercontent.com/48682104/116974318-02327100-accf-11eb-97d1-2cfaa3d949f4.png)
- La page présentation des thèmes 
![Capture d’écran 2021-05-04 à 11 50 14](https://user-images.githubusercontent.com/48682104/116974331-08285200-accf-11eb-8bc3-9cf10ff80c85.png)
- Les stats 
![Capture d’écran 2021-05-04 à 11 50 51](https://user-images.githubusercontent.com/48682104/116974345-0f4f6000-accf-11eb-816d-d4c44c252da8.png)

Nous avons détecté le même problème dans toutes : nous passons d'une balise H1 à des balises H3. Il manque donc la balise H2

# Solution

Pour chacune de ces pages, il faut passer les balises H3 en balise H2

**Comment by romain-b13** [comment]
Ce problème sera traité dans l'issue https://github.com/SocialGouv/code-du-travail-numerique/issues/3514
