### ISSUE TITLE
Page résultat de recherche : balise incohérente 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3464]
# Contexte 

Cf. #3441 

Dans nos pages de résultat lors d'une recherche nous avons une incohérence, nous passons directement à une balise H3 sans avoir de H2 avant. 
exemple ici = https://preprod-code-travail.dev2.fabrique.social.gouv.fr/recherche?q=cong%C3%A9s
![Capture d’écran 2021-05-04 à 11 59 22](https://user-images.githubusercontent.com/48682104/116975196-4e31e580-acd0-11eb-865d-512000e12a57.png)

# Solution 

Passez les balises H3 des tuiles en H2

**Comment by romain-b13** [comment]
Cette issue est toujours d'actualité :

![image](https://user-images.githubusercontent.com/84397271/165252199-6ed5b60a-9334-458d-a728-7dbe0ac6c671.png)

**Comment by carolineBda** [comment]
C'est fixed: https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/recherche?q=cong%C3%A9s
