### ISSUE TITLE
Incohérence hiérarchie balise Hn pages avec des accordéons et tableaux

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3466]
# Contexte

Cf. #3441

Dans nos pages contenus avec des accordéons nous avons beaucoup de problèmes de hiérarchie. En effet, les accordéons étant en balise H3 dans beaucoup de cas cela engendre un saut dans la hiérarchie des balises...

Voici différentes situations que l'on rencontre : 

### 1. [Une fiche SP avec accordéons](https://code.travail.gouv.fr/fiche-service-public/a-partir-de-quel-age-peut-on-travailler)
![Capture d’écran 2021-05-04 à 18 05 36](https://user-images.githubusercontent.com/48682104/117016045-5c4d2980-ad03-11eb-876d-d080dbe05fda.png)
https://code.travail.gouv.fr/fiche-service-public/a-partir-de-quel-age-peut-on-travailler

### 2. [Une fiche SP avec tableau puis accordéons](https://code.travail.gouv.fr/fiche-service-public/accident-du-travail-reprise-du-travail-du-salarie)
![Capture d’écran 2021-05-04 à 18 10 52](https://user-images.githubusercontent.com/48682104/117016864-2c525600-ad04-11eb-9ca9-ec8692bad3a4.png)
https://code.travail.gouv.fr/fiche-service-public/accident-du-travail-reprise-du-travail-du-salarie

### 3. [Une fiche SP avec tableau puis accordéons puis tableau](https://code.travail.gouv.fr/fiche-service-public/aides-a-lembauche-pour-un-contrat-dapprentissage)
![Capture d’écran 2021-05-04 à 18 13 42](https://user-images.githubusercontent.com/48682104/117017388-9d920900-ad04-11eb-9048-4a2b2f537a3b.png)
https://code.travail.gouv.fr/fiche-service-public/aides-a-lembauche-pour-un-contrat-dapprentissage

### 4. [Une fiche SP avec accordéon puis tableau](https://code.travail.gouv.fr/fiche-service-public/aide-a-domicile-services-a-la-personne-remuneration-du-salarie)
![Capture d’écran 2021-05-04 à 18 18 27](https://user-images.githubusercontent.com/48682104/117018029-32950200-ad05-11eb-8d80-13908c4cd9b6.png)
https://code.travail.gouv.fr/fiche-service-public/aide-a-domicile-services-a-la-personne-remuneration-du-salarie

### 5. [Une fiche SP avec un tableau dans le tableau](https://code.travail.gouv.fr/fiche-service-public/a-quelles-indemnites-peut-pretendre-un-salarie-qui-part-a-la-retraite)
![Capture d’écran 2021-05-04 à 18 08 50](https://user-images.githubusercontent.com/48682104/117016560-e3020680-ad03-11eb-918b-a1cbb11872ba.png)
https://code.travail.gouv.fr/fiche-service-public/a-quelles-indemnites-peut-pretendre-un-salarie-qui-part-a-la-retraite

### 8. [Une fiche éditoriale avec accordéons](https://preprod-code-travail.dev2.fabrique.social.gouv.fr/information/covid-19-integrer-le-risque-sanitaire-dans-lentreprise-protocole-national)  
![Capture d’écran 2021-05-04 à 17 10 10](https://user-images.githubusercontent.com/48682104/117008296-9f0b0380-acfb-11eb-967c-ab496e548dc6.png)
https://preprod-code-travail.dev2.fabrique.social.gouv.fr/information/covid-19-integrer-le-risque-sanitaire-dans-lentreprise-protocole-national

# Solution

**Comment by romain-b13** [comment]
Ce problème sera traité dans l'issue https://github.com/SocialGouv/code-du-travail-numerique/issues/3514
