### ISSUE TITLE
[Admin] Ajout des requêtes pré-qualifiées aux "contenus liés" dans les alertes

### ISSUE THREAD

**Issue by CaptainConan** [SocialGouv/code-du-travail-numerique#3468]
**Ajout des requêtes pré-qualifiées au "contenus liés" dans les alertes**

Lorsqu'un contenu en alerte (article du code du travail, fiche SP ou fiche MT) est repris dans une requête pré-qualifiée, il faudrait qu'il apparaisse dans l'alerte en tant que "contenus liés".

**Comment by lionelB** [comment]
closed for  #444
