### ISSUE TITLE
Ajouter les articles du code du travail lors d'une recherche d'un article du code du travail

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3471]
# Description du problème 

@rmelisson  a fait une analyse des recherches effectuées sur le site sur les 2 derniers mois afin d'évaluer les scores de sélections et les scores de l'ordre des résultats proposés. Il a fait cela sur les recherches pré-qualifiées et également sur les recherches non pré-qualifiées. 

Un problème récurrent a été détecté : les recherches des articles du code du travail. Or, ces recherches représentent quand même plus de 600 recherches sur les 2 derniers mois. 

On voit dans le tableau ci-dessous qu'aucune des recherches sur les articles du cdt n'a un taux de sélection (= lorsqu'une personne a sélectionné un résultat) qui dépasse 0,14... 
0,14 comme score = 14% des personnes ayant cherché ont cliqué sur un résultat... et c'est le meilleur score. Il y a quasiment la moitié qui n'ont tout simplement pas cliqué sur un résultat...
![Capture d’écran 2021-05-06 à 18 54 56](https://user-images.githubusercontent.com/48682104/117319724-a1f12a00-ae9c-11eb-819b-873dca0749b7.png)

Ces résultats pourraient s'expliquer du fait que les articles du code du travail se situe tout en bas de la page de résultats après les pages de contenus rédigés. Ils avaient été mis là car nous étions parti du principe que nos utilisateurs ne rechercheraient pas des articles du code (car pas experts) mais par mots clés. 
Au regard du nombre de recherches que cela représente nous devons prendre en considération ce type d'utilisateurs et résoudre ce problème. 

# Solution 

### Détection de ces recherches spécifiques 
Il faudrait donc détecter les recherches d'articles du code du travail. Cela se baserait sur le travail déjà effectué par @rmelisson lors de la recherche des articles du code du travail dans les fiches du ministère du travail. Les articles ayant une composition bien spécifique. cf. #2365

### Donner un meilleur accès à ces articles 
Il faudrait ajouter au sein des tuiles contenus rédigés les tuiles des articles du code du travail selon le même design.

**Comment by rmelisson** [comment]
aussi, on peut s'inspirer de ce qui avait été fait pour les fiches MT
https://github.com/SocialGouv/fiches-travail-data/blob/master/src/fetch-data/referenceExtractor.js#L97
