### ISSUE TITLE
Amélioration ui pour la recherche de CC 

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#3485]
- [x]  prise en compte du bouton retour navigateur
 - [x]  gestion des messages d'erreurs, pas de resultats (renvoi depuis Idcc => entreprise)
 - [x] mise en valeur de la recherche dans les résultat

**Comment by romain-b13** [comment]
cf https://github.com/SocialGouv/code-du-travail-numerique/pull/3490
