### ISSUE TITLE
Absence d'URL canoniques internes (self canonical)

### ISSUE THREAD

**Issue by Jonathan2051** [SocialGouv/code-du-travail-numerique#3487]
**Fonctionnalité**
- la balise canonique sert à indiquer au moteur de recherche la page d’origine qu’il doit prendre en compte
- soit la page est dupliquée et la balise pointe vers la page canonique, soit la page est canonique et la balise pointe vers elle-même (_self canonical_)

**Problème**
- certaines pages du CDTN affichent des balises canoniques vers l'externe, mais pas vers l'interne (_self canonical_)
- il faut faciliter le travail de Google en lui fournissant cette information

**Solution**
- ajouter les balises canoniques sur les pages affichant du contenu original du CDTN, notamment les **contributions**
- après un temps d'observation, nous pourrons généraliser la balise canonique à tous les contenus originaux du CDTN

**Ressources**
https://drive.google.com/file/d/122xE2qBldXDOk7gDGdeMFALAjFBKkFq6/view?usp=sharing

**Autres informations**
Les pages ciblées sont en jaune dans le tableau : les contributions

**Comment by romain-b13** [comment]
Je laisse @Jonathan2051 valider cette issue
