### ISSUE TITLE
Séparation WeekDay et Weekend pour stats Journalières Kibana

### ISSUE THREAD

**Issue by Armandgrd** [SocialGouv/code-du-travail-numerique#3492]
Calculer 2 stats pour le nb de visites journalières (weekeday et weekend , voir si possible jours fériés)

**Comment by romain-b13** [comment]
@ArmandGiraud On peut clôturer cette issue ?

**Comment by Armandgrd** [comment]
J'ai pas encore totalement terminé la partie sur les jours fériés.
