### ISSUE TITLE
ghreiogi

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3493]

**Comment by lionelB** [comment]
ok :smile:

**Comment by douglasduteil** [comment]
Moi aussi 🍡

**Comment by virginielastisneres** [comment]
ahah :see_no_evil: :see_no_evil: :see_no_evil:  :see_no_evil:
désolé je montrai comment faire des issues github à Romain... :joy:

**Comment by m-maillot** [comment]
Alors il faut être plus explicite dans le titre de préférence 😛  (et le contenu aussi 😄 )
