### ISSUE TITLE
L'absence de la balise Title

### ISSUE THREAD

**Issue by Jonathan2051** [SocialGouv/code-du-travail-numerique#3504]
**Fonctionnalité**
- les balises Title permettent aux _spiders_ des moteurs de recherche de mieux indexer les pages du CDTN.

**Problème**
- certaines balises Title sont absentes

**Solution**
- ajouter les balises manquantes

**Ressources**
- https://drive.google.com/file/d/1guXdZFu48NZYtcB4sRa9IB8lnBxiiAjl/view?usp=sharing

**Comment by carolineBda** [comment]
@Jonathan2051 normalement il n'y a plus de pages sans balise title, est-ce que tu peux nous le confirmer ?

**Comment by Jonathan2051** [comment]
@carolineBda Effectivement, le dernier audit a montré qu'il n'y avait plus de balise title absente.

**Comment by carolineBda** [comment]
Super merci de ta réponse
