### ISSUE TITLE
La marque dans la balise Title

### ISSUE THREAD

**Issue by Jonathan2051** [SocialGouv/code-du-travail-numerique#3506]
**Problème**
- on retrouve de façon aléatoire les marques « Code du travail numérique » ou « Ministère du Travail » dans les balises Title

**Solution**
- définir une règle pour la rédaction des balises title : titre du contenu + « Code du travail numérique » ou « Ministère du Travail » ou alors les deux ?

**Ressources**
- https://drive.google.com/file/d/1E9r_0U7h0rEDwIaFK8kpoGnfLlP92SaB/view?usp=sharing

**Comment by romain-b13** [comment]
Un certain nombre de contenus ont déjà la marque "code du travail numérique" dans la balise title. De plus, l'audit accessibilité nous suggère d'ajouter le nom du site dans la balise pour les pages qui ne l'ont pas encore.

Pour l'ensemble des pages on part sur le format suivant : [titre du contenu - Code du travail numérique]

=> retirer "Ministère du travail" des balises title des outils

**Comment by romain-b13** [comment]
Pour la home, a-t-on laissé "code du travail numérique - Ministère du travail" ?

**Comment by carolineBda** [comment]
> Pour la home, a-t-on laissé "code du travail numérique - Ministère du travail" ?

Hum non c'est vrai que j'ai laissé tel quel :
**"Code du travail numérique - Ministère du Travail -  Code du travail numérique"**

Mais c'est pas top.

Par hasard si je mets ceci ça irait ? :
**"Ministère du Travail -  Code du travail numérique"**

Sinon pas de soucis je remet :
**"Code du travail numérique - Ministère du Travail"**

**Comment by romain-b13** [comment]
Du coup il faudrait plutôt partir sur "Code du travail numérique - Ministère du Travail"

**Comment by carolineBda** [comment]
> Du coup il faudrait plutôt partir sur "Code du travail numérique - Ministère du Travail"

Ok j'ai laissé comme ça 👍
