### ISSUE TITLE
Bug fiche service public Temps partiel 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3509]
For my last issue 😢

## Description du bug 

Nous avons remarqué que la fiche Service public sur le temps partiel chez nous a un paragraphe en plus que celle présente chez service public.fr. A noter que la date de mise à jour semble la même... 

- url fiche chez nous : https://preprod-code-travail.dev2.fabrique.social.gouv.fr/fiche-service-public/temps-partiel-dans-le-secteur-prive
- url fiche chez service public : https://www.service-public.fr/particuliers/vosdroits/F32428

**Chez nous** 
![Capture d’écran 2021-05-27 à 20 11 47](https://user-images.githubusercontent.com/48682104/119860884-d601bd00-bf27-11eb-95e3-c1639886a88d.png)

**Chez Service public**
![Capture d’écran 2021-05-27 à 20 11 41](https://user-images.githubusercontent.com/48682104/119860844-caae9180-bf27-11eb-954b-54f78a85da61.png)

## Solution attendue 

Normalement nous devrions avoir exactement le meme contenu chez nous que la fiche chez service-public.fr

**Comment by romain-b13** [comment]
Le paragraphe est désormais bien identique chez nous et chez SP.
