### ISSUE TITLE
La présence de liens en nofollow

### ISSUE THREAD

**Issue by Jonathan2051** [SocialGouv/code-du-travail-numerique#3517]
**Problème**
- certains liens en _nofollow_ ont été identifiés

**Solution**
- passer les liens concernés en _dofollow_

**Ressources**
- https://drive.google.com/file/d/1pu4-lFnxa_T1IkpwsZukL-1H_V0XWy5-/view?usp=sharing

**Comment by m-maillot** [comment]
Tout les nofollow ont été retirés. Cependant, une règle de sécurité imposé par l'Etat impose de mettre un nofollow. Cela risque de changer avec le passage en dsfr.
