### ISSUE TITLE
Absence des balises Open Graph Protocol

### ISSUE THREAD

**Issue by Jonathan2051** [SocialGouv/code-du-travail-numerique#3520]
**Problème**
- certaines pages n'affichent pas les informations _Open Graph Protocol_ (optimisation de l'affichage du contenu des pages sur les réseaux sociaux)

**Solution**
- rajouter les balises  _Open Graph Protocol_ sur les pages concernées

**Ressources**
- https://drive.google.com/file/d/1iGa84QzXSw2sNHD3fP_rntG3OxfEl8Ks/view?usp=sharing
- https://drive.google.com/file/d/1EInXMAls_v8fUnhhQ1BtexcOxmvRaiOJ/view?usp=sharing

**Comment by lionelB** [comment]
Hello, 

Dans la liste de fiches; une bonne partie n'existe pas d'ou le manque de balise og sur la page d'erreur
sinon sur cette url https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/fiche-ministere-travail/entreprises-de-travail-temporaire-dinsertion-etti il y a bien les balises og... il manque autre chose ?
