### ISSUE TITLE
Images sans texte alternatif

### ISSUE THREAD

**Issue by Jonathan2051** [SocialGouv/code-du-travail-numerique#3521]
**Problème**
- certaines images n'affichent pas de texte alternatif (problème d'accessibilité et de référencement naturel)

**Solution**
- ajouter la balise _ALT_ aux images concernées

**Ressources**
https://drive.google.com/file/d/10USD2k8oNokXUssEUv8oQquV939fhVBK/view?usp=sharing

**Comment by lionelB** [comment]
@Jonathan2051 sur les images issues de contenus externes, on ne peut pas faire grand chose hormis faire remonter l'info. Pour la home, je pense que c'est corrigé. Je te laisse fermé si c'est ok

**Comment by Jonathan2051** [comment]
Effectivement, impossible pour les contenus externes 😕
Concernant le logo du Code du travail, je n'arrive pas à lire sa balise ALT dans le code de la page. Tu y arrives ?

**Comment by m-maillot** [comment]
tout est ok à ce niveau aujourd'hui.
