### ISSUE TITLE
Modification propriété Google Search Console 

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#3523]
# Contexte

Dans le cadre de mon départ, il faut que je donne l'accès de la Google Search Console à Romain en tant que propriétaire. Aujourd'hui je suis propriétaire délégué car clément m'avait donné cette accès. 
On voit que Clément est toujours le propriétaire attitré 
![Capture d’écran 2021-05-31 à 11 03 50](https://user-images.githubusercontent.com/48682104/120153843-3fbbe880-c200-11eb-935d-56e0c8f0fbba.png)

# Solution

Je dois passer propriétaire confirmé pour supprimer Clément et donner l'accès à Romain. Pour cela voici les consignes de Google : 
![Capture d’écran 2021-05-31 à 11 04 41](https://user-images.githubusercontent.com/48682104/120153965-6548f200-c200-11eb-9332-425ae3c7b960.png)

Pour cela, il faut mettre un fichier HTML dans le site à la place de celui de Clément qui y est aujourd'hui. 
![Image Pasted at 2021-5-27 15-07](https://user-images.githubusercontent.com/48682104/120154231-b527b900-c200-11eb-9fa1-edbb15dd1ed4.png)

Voici le fichier HTML à intégrer dans le drive (impossible de mettre un HTML dans github) https://drive.google.com/drive/folders/1GDS3tHDaTnYEOp3OWSc6KKM6KSCYcyRd

**Comment by m-maillot** [comment]
Le fichier est disponible sur la prod : https://code.travail.gouv.fr/google6147ec315bc44cce.html
Tu peux passer ton compte en propriétaire confirmé et faire la même issue pour mettre celui de Romain ensuite 😄

**Comment by m-maillot** [comment]
Je te laisse clôturer l'issue quand tu auras fait la manip et que ce sera bon :)
