### ISSUE TITLE
Ajouter temps nécessaire pour calcul du préavis de retraite

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3525]
Ajouter le temps nécessaire à l'utilisateur pour calculer son préavis de départ ou de mise à la retraite dans l'étape d'introduction de l'outil : " Prévoyez X à X minutes pour cette simulation"

**Comment by noemiechassard** [comment]
Proposition de modification de l’introduction avec l’ajout de mots en gras pour en faciliter la lecture :

« Ce simulateur est un outil qui permet de calculer la **durée de préavis** à respecter en cas de **départ** ou de **mise à la retraite**, telle qu'elle est prévue par la loi et la convention collective applicable.

En effet, en cas de départ ou de mise à la retraite, le salarié ne peut pas quitter l’entreprise immédiatement. Il doit y rester durant une certaine période, qu’on appelle **préavis** ou parfois **délai congé**.

Afin de réaliser cette simulation, vous aurez besoin d’informations concernant la situation du salarié, comme sa convention collective, sa catégorie ou son coefficient. La plupart de ces informations se trouvent sur le bulletin de salaire ou le contrat de travail. Prévoyez X à X minutes pour cette simulation.

Attention : Le résultat affiché correspond à la durée légale ou conventionnelle, en fonction des informations renseignées. Toutefois, une durée plus favorable peut être prévue par un accord collectif d’entreprise, le contrat de travail, un usage ou encore une convention collective de branche (si non renseignée dans le simulateur). Dans ce cas, c’est cette durée plus favorable qui s’applique au salarié.

Cliquez sur commencer pour démarrer la simulation. »

**Comment by romain-b13** [comment]
je pense que l'on peut indiquer "environ 5 min" cela me paraît cohérent par rapport au temps indiqué sur les autres simulateurs

**Comment by m-maillot** [comment]
@romain-b13 je pense que l'on peut doit aussi faire cette issue avant la mise en prod.
