### ISSUE TITLE
Ajouter q° handicap étape "informations" outil préavis retraite

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3527]
**Description**
Dans l'étape n°4 (informations), cette question est à poser dans tous les cas, que le salarié ait sélectionné une convention collective ou non, peu importe qu’il s’agisse d’une des 50 CC traitées ou non...
“Le salarié concerné est-il reconnu en tant que travailleur handicapé ?”

- Oui
- Non

Si l’utilisateur répond Non, on passe à l’étape suivante et il n’y a aucun impact sur le délai de préavis.

Si l’utilisateur répond Oui, il faut doubler la durée légale et conventionnelle dans la limite de 3 mois.

Calcul : Durée de préavis x 2 ≤ 3 mois

**Comment by romain-b13** [comment]
Ok pour moi

**Comment by romain-b13** [comment]
Il y a une erreur pour les salariés reconnus en tant que travailleur handicapé. Leur durée de préavis est doublée dans la limite de 3 mois. Cependant, si la convention collective prévoit une durée au moins égale à 3 mois, c’est cette durée supérieure à 3 mois qui s’applique (Article L5213-9). Or, dans le simulateur, pour le préavis de mise à la retraite, on affiche les 3 mois maximum même quand la durée de préavis conventionnelle est supérieure. Par exemple, quand la durée de mise à la retraite est de 6 mois, on affiche quand même 3 mois alors que la durée affichée devrait être 6 mois.

**Comment by m-maillot** [comment]
A voir avec @noemiechassard

**Comment by m-maillot** [comment]
Algo à mettre en place:

Calcul du légal : calcul actuel * 2 dans la limite de 3 mois
Calcul du CC : si calcul actuel < 3 mois alors calcul actuel * 2 dans la limite de 3 mois sinon calcul actuel 

On garde la logique pour le reste.
