### ISSUE TITLE
Améliorer UX page "ancienneté" outil préavis retraite

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3528]
**Problème**
Actuellement l'ancienneté est demandée en mois ce qui nécessite des calculs de la part de l'utilisateur et d'aller chercher l'information (bulletin de paie).

**Proposition**
Etant donné que pour la majorité des CC le calcul du préavis est le même à partir de 2 ans d'ancienneté (les modalités diffèrent surtout en dessous de 2 ans d'ancienneté) : 

**Pour toutes les CCs :**
**1ère question**
"Le salarié a-t-il plus de 2 ans d'ancienneté dans l'entreprise (2 ans exclu) ? (obligatoire)"
     - Oui
     - Non
Si la réponse est "Oui" => l'utilisateur passe à l'étape suivante
Si la réponse est "Non" => l'utilisateur passe à la 2ème question 

**2ème question**
"Quelle est l'ancienneté du salarié dans l’entreprise en mois ? (obligatoire)"
Ajouter un **point info** : la salarié peut trouver son ancienneté sur son bulletin de paie

**Pour la CC 2264 :**
**1ère question**
"Le salarié a-t-il au minimum 5 ans d'ancienneté dans l'entreprise ?"
- Oui
- Non
Si la réponse est « Oui » => On passe à l’étape suivante
Si la réponse est « Non » => l'utilisateur passe à la question suivante :

"Quelle est l'ancienneté du salarié dans l’entreprise en mois ? (obligatoire)"
Ajouter un **point info** : le salarié peut trouver son ancienneté sur son bulletin de paie

**Comment by romain-b13** [comment]
@jrduscher @noemiechassard pouvez-vous valider le wording et le parcours svp ?

**Comment by noemiechassard** [comment]
Je valide le wording. Il faut toutefois faire attention au point info et bien indiquer « **le** salarié »
Concernant le parcours utilisateur pour la CCN 2264, je commencerais par poser la question « Le salarié a-t-il au minimum 5 ans d'ancienneté dans l'entreprise ?
- Oui
- Non »
Si la réponse est « Oui » => On passe à l’étape suivante
Si la réponse est « Non » => l'utilisateur passe à la question suivante :
« Quelle est l'ancienneté du salarié dans l’entreprise en mois ? (obligatoire) »
Ajouter un point info : le salarié peut trouver son ancienneté sur son bulletin de paie 

En effet, je pense qu’il est nécessaire de lui indiquer également le préavis légal qui s'applique quand l'ancienneté est inférieure à 2 ans, même s’il ne s’appliquera pas en l’espèce car il s'agit de la mise à la retraite.

**Comment by noemiechassard** [comment]
Il faudrait remplacer la question « _Le salarié a-t-il plus de 2 ans d'ancienneté dans l'entreprise (2 ans exclu) ?_ » par « _Le salarié a-t-il plus de 2 ans d'ancienneté dans l'entreprise (à partir de 2 ans + 1 jour) ?_ »

Nous avons pensé à indiquer par une phrase que certaines périodes d’absence pouvaient être inclues ou exclues. Cependant, en l’état actuel, cela peut plus perdre l’utilisateur plutôt que l’aider à calculer son préavis. Pour l’instant, on n’inclut pas de phrase d'information dans l’outils.

Nous pourrons par la suite réfléchir au fait d’inclure ou non une information pour l'utilisateur avec éventuellement cette page : https://code.travail.gouv.fr/contribution/comment-determiner-lanciennete-du-salarie?q=calcul%20anciennet%C3%A9

**Comment by noemiechassard** [comment]
Proposition de modification de l’introduction avec l’ajout de mots en gras pour en faciliter la lecture :
« Ce simulateur est un outil qui permet de calculer la **durée de préavis** à respecter en cas de **départ** ou de **mise à la retraite**, telle qu'elle est prévue par la loi et la convention collective applicable.

En effet, en cas de départ ou de mise à la retraite, le salarié ne peut pas quitter l’entreprise immédiatement. Il doit y rester durant une certaine période, qu’on appelle **préavis** ou parfois **délai congé**.

Afin de réaliser cette simulation, vous aurez besoin d’informations concernant la situation du salarié, comme sa convention collective, sa catégorie ou son coefficient. La plupart de ces informations se trouvent sur le bulletin de salaire ou le contrat de travail. Prévoyez X à X minutes pour cette simulation.

Attention : Le résultat affiché correspond à la durée légale ou conventionnelle, en fonction des informations renseignées. Toutefois, une durée plus favorable peut être prévue par un accord collectif d’entreprise, le contrat de travail, un usage ou encore une convention collective de branche (si non renseignée dans le simulateur). Dans ce cas, c’est cette durée plus favorable qui s’applique au salarié.

Cliquez sur commencer pour démarrer la simulation. »

**Comment by romain-b13** [comment]
Il manque pour le moment un point info à la 2ème question de l'étape ancienneté, lorsque l'utilisateur a répondu "non" à la question "Le salarié a-t-il plus de 2 ans d'ancienneté dans l'entreprise (2 ans exclu) ?" nous lui demandons d'indiquer l'ancienneté en mois => à ce moment il faudra guider l'utilisateur pour lui indiquer où est-ce qu'il peut trouver l'ancienneté

**Comment by romain-b13** [comment]
Est-il possible de diminuer la typo de  "(à partir de 2 ans + 1 jour)" pour que le point d'interrogation de l'aide se trouve sur la même ligne que la question ? 

Est-il possible de mettre en gras uniquement "bulletin de salaire" dans phrase qui s'affiche une fois que l'on clique sur l'aide (comme ce qui a été fait sur l'aide dans l'outil "trouver sa CC") ?  "L'ancienneté du salarié est habituellement mentionnée sur le **bulletin de salaire**"

**Comment by m-maillot** [comment]
C'est fait, tu peux voir le résultat : 
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/992514/132344926-e56277d1-e76f-4329-9ec9-c72c2a62d4ac.png">

Branche de test : https://feature-improve-r-7u1zfh-code-du-travail-numerique.dev.fabrique.social.gouv.fr/outils/preavis-retraite

Dis moi si ça te va ?

**Comment by romain-b13** [comment]
Top merci @m-maillot

**Comment by romain-b13** [comment]
Désolé @m-maillot en retestant l'outil je trouve que le fait que le point d'interrogation soit après "(à partir de 2 ans + 1 jour)" fait bizarre
Est-ce qu'on ne devrait pas mettre "(à partir de 2 ans + 1 jour)" après "2 ans" ? 
Je soumets dans mattermost au reste de l'équipe comme ils vont réaliser le test de l'outil
