### ISSUE TITLE
Integration CC cas particuliers outil préavis retraite

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#3532]
**Fonctionnalité**

Intégration des CCs avec des cas particulier.

- [x] 86 (cas particulier: résultat en min et max)
- [x] 2148 (cas particulier: durée fixé dans le contrat ne peut être inférieur à 3 mois)
- [x] 2596 (voir le nommage de la catégorie professionnelle)
- [x] 2941 (cas particulier: 1 semaine de date à date, peut être géré via une notification?)

Données : https://docs.google.com/spreadsheets/d/1zd_hShEui8BHK0349GpDUZRkCcQ9syIZ9gSrkYKRdo0/edit#gid=1592811420

Related to #3268

**Comment by romain-b13** [comment]
Il faudrait également traiter une nouvelle CC qui sera bientôt disponible dans l'Excel : la 3239 (il ne faudra pas qu'elle soit en prod tant qu'elle n'a pas été étendue)
Cette CC résulte de la fusion des CC 2111 et 2395 => /!\ il faut quand même traiter la 2111 et la 2395 dans le préavis de retraite car ce sont elles qui sont en vigueur jusqu'au 31/12/2021
cf https://github.com/SocialGouv/code-du-travail-numerique/issues/3868

**Comment by maxgfr** [comment]
Il y a cette PR, avec l'ancienneté > 5 ans : #3826

**Comment by carolineBda** [comment]
Solution pour chacune des CC

- **86** (cas particulier: résultat en min et max)
	- renvoi un un résultat mais affiche une notif qui dit "les 2 mois sont un minimum peut aller jusqu'à 3 mois maximum"
- **2148** (cas particulier: durée fixé dans le contrat ne peut être inférieur à 3 mois)
	- on renvoit le résultat du code du travail mais on ajoute une notif : "La durée du préavis des salariés hors classification est fixée par le contrat de travail sans pouvoir être inférieure à 3 mois" 
- **2596** (voir le nommage de la catégorie professionnelle)
	- split en 3 catégories la catégorie "Salariés occupant un emploi technique de la coiffure, un emploi non technique ou un emploi de l'esthétique cosmétique" qui renvoient tous le même résultat :
		-  Salariés occupant un emploi technique de la coiffure
		- Salariés occupant un emploi non technique de la coiffure
		- Salariés occupant un emploi de l'esthétique cosmétique
- **2941** (cas particulier: 1 semaine de date à date, peut être géré via une notification?)
	- utilisation de notif pour spécifier "1 mois de date à date"
	- pour plus/moins de 2 ans => 2 ans ou moins et plus de 2 ans

**Comment by maxgfr** [comment]
Suite au point que nous avons eu :

**86** : Il faudrait créer un flag sur publicode qui nous permet d'ajouter une valeur maximum. Ainsi, sur le résultat affiché, on mettra c'est X mois minimum et Y mois maximum. Pour le résultat decrypté, il faudra bien override pour dire que c'est la CC qui prévaut. Le message de notification doit être mis en place.

**2148** : Il serait intéressant de reprendre la logique ci-dessus, en mettant un maximum et minimum égale. Le message de notification doit être mis en place. Concernant le dernier point blocant, qui est le départ à la retraite, une re-verification est en cours.
