### ISSUE TITLE
Ajouter modale "pas de CC" et message "CC non prise en compte" outil préavis retraite

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3543]
**Problème**
Simulateur départ ou mise à la retraite : étape "convention collective"
1)  Actuellement il n'y a pas de message indiquant à l'utilisateur qu'il n'a pas choisi de CC et donc qu'il peut continuer mais que sa CC peut prévoir un délais plus favorable
2) Actuellement il n'y a pas de message indiquant à l'utilisateur que la CC indiquée n'est pas traitée par nos services lors du choix de la CC

**Solution**
1) Si l'utilisateur clique sur "suivant" sans avoir rempli de CC le modal suivant apparaît:

![Group 2](https://user-images.githubusercontent.com/84397271/120979817-41445e00-c776-11eb-93b7-dc8105f8c54f.png)

2) Si l'utilisateur sélectionne une CC qui n'est pas traitée : 

![Group 5](https://user-images.githubusercontent.com/84397271/120988916-48239e80-c77f-11eb-868f-c5ebde0edc06.png)

https://www.figma.com/file/8drdd9OhCJjYqffvYeJynl/Outil-pr%C3%A9avis-de-retraite?node-id=36%3A0

**Comment by m-maillot** [comment]
La première partie où l'on affiche la popup ne sera pas implémenté. La popup ne semble pas être la bonne solution. Un étude sera mené pour identifier les aces d'amélioration de cette étape.

**Comment by romain-b13** [comment]
C'est ok pour moi
