### ISSUE TITLE
Revoir CC 29 Hospitalisation privée outil préavis retraite

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#3546]
**Problème**

Légifrance ne fonctionne toujours pas pour les articles → Réponse de la DILA → Mi-juin 
@noemiechassard va surveiller quand cela fonctionnera à nouveau et elle préviendra en cherchant les bons liens à ajouter pour les Sources 

**Solution**

Il manque la réponse 2: “Attention : L'article de la convention collective ou la convention collective saisie n’a pas été étendue au niveau national. Par conséquent, pour que ce résultat soit applicable à votre situation, il faut que l’employeur ait adhéré à l’organisation patronale signataire de cette convention. Sans cette adhésion, l'employeur n'a pas l'obligation d'appliquer les règles de la convention mais il applique le préavis prévu par le code du travail.”

Cependant, il faut attendre que Légifrance ait mis à jour les articles pour voir si cela s’applique toujours

**Comment by m-maillot** [comment]
On a eu des nouvelles sur cette CC @noemiechassard @jrduscher ?

**Comment by maxgfr** [comment]
@m-maillot Il me semble l'avoir implémenté quelques jours auparavant

**Comment by romain-b13** [comment]
Pas de nouveau sur ce sujet pour le moment

En attendant, pour les 2 sources entourées ci dessous il faudrait les laissées mais retirer le lien qui va vers legifrance : 

![image](https://user-images.githubusercontent.com/84397271/149323940-f87c459d-887c-4acf-991d-154e38009d6e.png)
