### ISSUE TITLE
Améliorer page résultat outil préavis retraite

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3550]
### Contexte
Page résultat actuelle 
![image](https://user-images.githubusercontent.com/84397271/121526674-e4f17080-c9f9-11eb-9cd4-40d638069ced.png)

### 1) Définir les informations à afficher parmi : 
- La règle de droit utilisée
- Les éléments saisis
- Les résultats décryptés
- Les textes juridiques appliqués (ou "Sources"=> wording à définir)

### a) format actuel : informations disponibles sans action de l'utilisateur
![image](https://user-images.githubusercontent.com/84397271/121528056-6564a100-c9fb-11eb-9f59-33fb14140aec.png)

### b) détails disponible dans un accordéon
        **b.1. accordéon fermé**
![Brouillon Romain 2 (1)](https://user-images.githubusercontent.com/84397271/121534586-a52e8700-ca01-11eb-82af-32b458453c05.jpg)

        **b.2. accordéon ouvert**
![Brouillon Romain 4 (1)](https://user-images.githubusercontent.com/84397271/121534457-8af4a900-ca01-11eb-951c-3f953430c922.png)

### c) détails dans plusieurs accordéons
![Brouillon Romain 6](https://user-images.githubusercontent.com/84397271/121534244-584ab080-ca01-11eb-9fff-35279569b7e3.png)

### d) détails dans une modale
         **d.1. Avant ouverture modale**
Voir le format pour "Comprendre mon résultat" => souligné ? picto ouverture de fenêtre ?

         **d.2. La modale**
![Brouillon Romain 3](https://user-images.githubusercontent.com/84397271/121535356-60efb680-ca02-11eb-8af8-a0f5f7f79c17.png)

**Comment by romain-b13** [comment]
### C'est la proposition " b) Détails disponibles dans un accordéon" qui est retenue :

1) Accordéon fermé 
![Accordéon fermé](https://user-images.githubusercontent.com/84397271/122192588-15bb2500-ce94-11eb-9c97-6f95fdf15b54.jpg)

2) Accordéon ouvert 
![Accordéon ouvert](https://user-images.githubusercontent.com/84397271/122177064-8eff4b80-ce85-11eb-9155-ab40fc12de23.png)

=> maquettes : https://www.figma.com/file/4k4hrIzDkgD6VgYBjwqMux/Maquettes-page-r%C3%A9sultat-outils?node-id=26%3A101

### Détails 
### 1) Annonce du préavis
Forme : le résultat du préavis apparaît seul sur une seconde ligne en rouge (FF7067) [open sans, bold, 24]

**Préavis de départ à la retraite**
- Si pas de préavis : 
À partir des éléments que vous avez saisis : [open sans, regular, 16, 3E486E]
il n’y a pas de préavis à effectuer [open sans, bold, 24, FF7067, line height : 160%]

- Il y a un préavis à effectuer : 
À partir des éléments que vous avez saisis, la durée du préavis en cas de départ à la retraite est estimée à :
2 heures par jour * 
* Le salarié pourra quitter son emploi après avoir exécuté un préavis de 1 mois sous réserve d’en avoir informé son employeur au moins 10 jours à l’avance. Dans ce cas, il n’a droit qu’à la rémunération correspondant au temps qu’il a effectivement travaillé (et éventuellement une indemnité de congédiement). [open sans, italic, 14, 3E486E, espacement avec le résultat : 16]

**Préavis de mise à la retraite**
- Si pas de préavis : 
À partir des éléments que vous avez saisis : [open sans, regular, 16, 3E486E]
il n’y a pas de préavis à effectuer [open sans, bold, 24, FF7067, line height : 160%]

- Il y a un préavis à effectuer : 
À partir des éléments que vous avez saisis, la durée du préavis en cas de mise à la retraite est estimée à :
2 mois *
* Le salarié pourra quitter son emploi après avoir exécuté un préavis de 1 mois sous réserve d’en avoir informé son employeur au moins 10 jours à l’avance. Dans ce cas, il n’a droit qu’à la rémunération correspondant au temps qu’il a effectivement travaillé (et éventuellement une indemnité de congédiement). [open sans, italic, 14, 3E486E, espacement avec le résultat : 16]

### 2) Comprendre le résultat
**Les éléments saisis** [open sans, semibold, 18, 4D73B8]
        Origine du départ à la retraite : XXX
        Convention collective: XXX
        Catégorie professionnelle : XXX
        Travailleur handicapé : XXX
        Ancienneté du salarié : XXX

**Le résultat décrypté** (de nombreux cas) [open sans, semibold, 18, 4D73B8]

- Le résultat décrypté **(si pas de préavis et cc non remplie)**
Durée prévue par le code du travail (durée légale) : pas de préavis. [open sans, regular, 16, 3E486E]

Le salarié ayant une ancienneté inférieure à 6 mois, il n’y a pas de préavis à respecter. [open sans, regular, 16, FF7067]

- Le résultat décrypté **(si pas de préavis et cc remplie)**
Durée prévue par le code du travail (durée légale) : pas de préavis
Durée prévue par la convention collective (durée conventionnelle) : pas de préavis

Pour un salarié ayant une ancienneté inférieure à 6 mois, ni le code du travail ni la convention collective sélectionnée ne prévoit de préavis à respecter. 

- Le résultat décrypté **(préavis de départ à la retraite, CC remplie, CDT<CC)**
Durée prévue par le code du travail (durée légale) : XX mois
Durée prévue par la convention collective (durée conventionnelle) : XX mois 

La durée à appliquer pour le salarié est donc la durée légale, celle-ci étant plus courte que la durée prévue par la convention collective. 

- Le résultat décrypté **(préavis de départ à la retraite, CC remplie, CDT=CC)**
Durée prévue par le code du travail (durée légale) : XX mois
Durée prévue par la convention collective (durée conventionnelle) : XX mois 

Le résultat correspond à la fois à la durée prévue par le code du travail et à la fois à la durée prévue par la convention collective, celles-ci étant identiques dans cette situation.

- Le résultat décrypté **(préavis de départ à la retraite, CC remplie, CDT>CC)**
Durée prévue par le code du travail (durée légale) : XX mois
Durée prévue par la convention collective (durée conventionnelle) : XX mois 

La durée à appliquer pour le salarié est donc à la durée conventionnelle, celle-ci étant plus courte que la durée prévue par le code du travail. 

- Le résultat décrypté **(préavis de départ à la retraite, CC non remplie)**
Durée prévue par le code du travail (durée légale) : XX mois

La durée à appliquer pour le salarié est donc la durée prévue par le code du travail pour son ancienneté. 

- Le résultat décrypté **(préavis de mise à la retraite, CC remplie, CDT<CC)**
Durée prévue par le code du travail (durée légale) : XX mois
Durée prévue par la convention collective (durée conventionnelle) : XX mois 

La durée à appliquer pour le salarié est donc à la durée prévue par la convention collective, celle-ci étant plus longue que la durée légale. 

- Le résultat décrypté **(préavis de mise à la retraite, CC remplie, CDT=CC)**
Durée prévue par le code du travail (durée légale) : XX mois
Durée prévue par la convention collective (durée conventionnelle) : XX mois 

Le résultat correspond à la fois à la durée prévue par le code du travail et à la fois à la durée prévue par la convention collective, celles-ci étant identiques dans cette situation. 

- Le résultat décrypté **(préavis de mise à la retraite, CC remplie, CDT>CC)**
Durée prévue par le code du travail (durée légale) : XX mois
Durée prévue par la convention collective (durée conventionnelle) : XX mois 

La durée à appliquer pour le salarié est donc la durée légale, celle-ci étant plus longue que la durée prévue par la convention collective. 

- Le résultat décrypté **(préavis de mise à la retraite, CC non remplie)**
Durée prévue par le code du travail (durée légale) : XX mois

La durée à respecter pour l’employeur est donc la durée prévue par le code du travail pour son ancienneté.

**Les textes juridiques appliqués** [open sans, semibold, 18, 4D73B8]
Article XXX du code du travail [open sans, regular, 16, 3E486E]
Article XXX du code du travail
Articles XXX de la convention collective concernée

**Encadré "Attention"**
- Encadré attention **(pas de préavis, CC non remplie)**
Attention il peut quand même exister une durée de préavis [open sans, semibold, 18]
Une convention collective de branche, un accord collectif d’entreprise, le contrat de travail ou un usage peut prévoir une durée de préavis. Dans ce cas, cette durée doit s’appliquer. [open sans, regular, 16]
Nous vous conseillons de vérifiez cela.

- Encadré attention **(pas de préavis, CC remplie)**
Attention il peut quand même exister une durée de préavis
Un accord collectif d’entreprise, le contrat de travail ou un usage peut prévoir une durée de préavis.
Dans ce cas, cette durée doit s’appliquer. 
Nous vous conseillons de vérifiez cela.

- Encadré attention **(préavis départ à la retraite, CC remplie)**
Attention il peut exister une durée plus favorable
Un accord collectif d’entreprise, le contrat de travail ou un usage peuvent prévoir une durée de préavis* ou encore une condition d’ancienneté* plus favorable pour le salarié. Dans ce cas, c’est cette durée plus favorable ou cette ancienneté plus favorable qui s’applique au salarié.

*durée de préavis plus favorable pour le salarié = durée plus courte. [open sans, italic, 16]
*condition d’ancienneté plus favorable pour le salarié = condition d’ancienneté moins restrictive et conduisant à une durée de préavis plus courte.

- Encadré attention **(préavis départ à la retraite, CC non remplie)**
Une convention collective de branche, un accord collectif d’entreprise, le contrat de travail ou un usage peut prévoir une durée de préavis* ou encore une condition d’ancienneté* plus favorable pour le salarié. Dans ce cas, c’est cette durée plus favorable ou cette ancienneté plus favorable qui s’applique au salarié.

*durée de préavis plus favorable pour le salarié = durée plus courte. 
*condition d’ancienneté plus favorable pour le salarié = condition d’ancienneté moins restrictive et conduisant à une durée de préavis plus courte.

- Encadré attention **(préavis de mise à la retraite, CC remplie)**
Un accord collectif d’entreprise, le contrat de travail ou un usage peuvent prévoir une durée de préavis* ou encore une condition d’ancienneté* plus favorable pour le salarié. Dans ce cas, c’est cette durée plus favorable ou cette ancienneté plus favorable qui s’applique au salarié.

*durée de préavis plus favorable pour le salarié = durée plus longue. 
*condition d’ancienneté plus favorable pour le salarié = condition d’ancienneté moins restrictive et conduisant à une durée de préavis plus longue.

- Encadré attention **(préavis de mise à la retraite, CC non remplie)**
Une convention collective de branche, un accord collectif d’entreprise, le contrat de travail ou un usage peut prévoir une durée de préavis* ou encore une condition d’ancienneté* plus favorable pour le salarié. Dans ce cas, c’est cette durée plus favorable ou cette ancienneté plus favorable qui s’applique au salarié.

*durée de préavis plus favorable pour le salarié = durée plus longue. 
*condition d’ancienneté plus favorable pour le salarié = condition d’ancienneté moins restrictive et conduisant à une durée de préavis plus longue.

**Comment by romain-b13** [comment]
Pour l'intitulé de l'accordéon : remplacer "comprendre le résultat" par "voir le détail du calcul"

**Comment by noemiechassard** [comment]
Je valide ces formulations pour la page résultat. Je remplacerais juste "Les textes juridiques appliqués" par "Source" (ce qui est déjà le cas actuellement il me semble). Et il faut également remplacer dans les encadrés attention les "peuvent prévoir" par "peut prévoir"

**Comment by m-maillot** [comment]
Il me manque la formule quand le salarié à moins de 6 mois d'ancienneté et que la CC prévoit une durée. Ques dois je mettre comme formule ? @romain-b13 @noemiechassard

**Comment by noemiechassard** [comment]
La formule est identique pour le départ et la mise à la retraite: 

•"	**Le résultat décrypté (préavis de départ et de mise à la retraite, CC remplie, Ancienneté < 6 mois)**
Durée prévue par le code du travail (durée légale) : XX mois
Durée prévue par la convention collective (durée conventionnelle) : XX mois

Le code du travail ne prévoit pas de durée de préavis pour une ancienneté inférieure à 6 mois mais il renvoie à la convention ou l'accord collectif de travail ou, à défaut, aux usages pratiqués dans la localité et la profession. La durée à appliquer pour le salarié est donc la durée prévue par la convention collective. "

**Comment by romain-b13** [comment]
Passer en bleu la phrase "La durée à appliquer pour le salarié est donc à la durée conventionnelle, celle-ci étant plus courte que la durée prévue par le code du travail" dans le résultat décrypté
Et ajouté de l'espacement avant cette phrase

**Comment by noemiechassard** [comment]
### Modification des messages à afficher dans le résultat décrypté en fonction du cas de figure: 

**Pour les cas suivants**: 

- (préavis de départ à la retraite, CC remplie, CDT>CC)
- (préavis de mise à la retraite, CC remplie, CDT<CC)


Actuellement, il est indiqué cela : “_Durée prévue par le code du travail (durée légale) : XX mois
Durée prévue par la convention collective (durée conventionnelle) : XX mois
La durée à appliquer pour le salarié est donc à la durée prévue par la convention collective, celle-ci étant plus longue que la durée légale._”

Modifier le message et enlever le “à” en trop : “_La durée à appliquer pour le salarié est donc la durée prévue par la convention collective, celle-ci étant plus longue que la durée légale._” 

**Ancienneté de moins de 6 mois et la CC ne prévoit rien** : (préavis de départ à la retraite et préavis de mise à la retraite, CC remplie, ancienneté < 6 mois, CC=0)
Actuellement il est indiqué cela : “_Durée prévue par le code du travail (durée légale) : pas de préavis
Durée prévue par la convention collective (durée conventionnelle) : pas de préavis_”

Afficher le message suivant : “_Durée prévue par le code du travail (durée légale) : pas de préavis
Durée prévue par la convention collective (durée conventionnelle) : pas de préavis
Ni la loi, ni la convention collective ne prévoient de durée de préavis._”

**CC non renseignée** : (préavis de départ à la retraite et préavis de mise à la retraite, CC non renseignée)
Actuellement il est indiqué cela : “_Durée prévue par le code du travail (durée légale) : XX mois
La durée à respecter pour l’employeur est donc la durée prévue par le code du travail pour son ancienneté._”

Afficher le message suivant: “_Durée prévue par le code du travail (durée légale) : XX mois
Durée prévue par la convention collective (durée conventionnelle) : convention collective non renseignée
La convention collective n’ayant pas été renseignée, la durée de préavis affichée correspond à la durée légale._”

**CC sélectionnée mais n’est pas traitée** :  (préavis de départ à la retraite et préavis de mise à la retraite, CC non traitée)
Actuellement, la phrase indiquée est la suivante : “_Durée prévue par le code du travail (durée légale) : XX  mois
Durée prévue par la convention collective (durée conventionnelle) : pas de préavis
La durée à appliquer pour le salarié est donc à la durée conventionnelle, celle-ci étant plus courte que la durée prévue par le code du travail._”

Afficher le message suivant: “_Durée prévue par le code du travail (durée légale) : XX  mois
Durée prévue par la convention collective (durée conventionnelle) : convention collective non traitée
La convention collective n’ayant pas été traitée par nos services, la durée de préavis affichée correspond à la durée légale_.”

**CC ne prévoit rien mais le code du travail si** : (préavis de départ à la retraite et préavis de mise à la retraite, CC=0)
Actuellement il est indiqué cela : “_Durée prévue par le code du travail (durée légale) : XX mois
Durée prévue par la convention collective (durée conventionnelle) : pas de préavis
La durée à appliquer pour le salarié est donc à la durée conventionnelle, celle-ci étant plus courte que la durée prévue par le code du travail._”

Afficher le message suivant : “_Durée prévue par le code du travail (durée légale) : XX mois
Durée prévue par la convention collective (durée conventionnelle) : pas de préavis
En l’absence de durée prévue par la convention collective, la durée de préavis à appliquer pour le salarié est donc la durée légale._”


**L'utilisateur répond “Oui” à la question “Le salarié concerné est-il reconnu en tant que travailleur handicapé ?” et le résultat conventionnelle pour la mise à la retraite est inférieure à 3 mois** : (préavis de mise à la retraite, salarié reconnu en tant que travailleur handicapé, CC<3 mois)
Actuellement, on affiche le message suivant: “_La durée à appliquer pour le salarié est donc à la durée prévue par la convention collective, celle-ci étant plus longue que la durée légale._”

Modifier par la phrase suivante: “_Le salarié étant reconnu comme travailleur handicapé, la durée du préavis est doublée sans pouvoir excéder trois mois._”

**Comment by romain-b13** [comment]
Dans l'encadré "attention" de l'étape résultat :
=> remplacer "Un accord collectif d’entreprise, le contrat de travail ou un usage peuvent prévoir" par "peut prévoir"
=> remplacer "c’est cette durée plus favorable ou cette ancienneté plus favorable" par "c’est cette durée ou cette ancienneté plus favorable"
=> Dans la phrase "une durée de préavis* ou encore une condition d’ancienneté" enlever le mot "encore" qui "alourdit"

**Comment by m-maillot** [comment]
> Ancienneté de moins de 6 mois et la CC ne prévoit rien : (préavis de départ à la retraite et préavis de mise à la retraite, CC remplie, ancienneté < 6 mois, CC=0)
Actuellement il est indiqué cela : “Durée prévue par le code du travail (durée légale) : pas de préavis
Durée prévue par la convention collective (durée conventionnelle) : pas de préavis”

> Afficher le message suivant : “Durée prévue par le code du travail (durée légale) : pas de préavis
Durée prévue par la convention collective (durée conventionnelle) : pas de préavis
Ni la loi, ni la convention collective ne prévoient de durée de préavis.”

Il y avait un bug, il y a bien une phrase normalement : 

<img width="813" alt="image" src="https://user-images.githubusercontent.com/992514/128730421-81314cb6-4d8f-4f7c-a06b-21a3f994f05f.png">

Je garde cette phrase ou je remplace par : Ni la loi, ni la convention collective ne prévoient de durée de préavis.

**Comment by m-maillot** [comment]
> L'utilisateur répond “Oui” à la question “Le salarié concerné est-il reconnu en tant que travailleur handicapé ?” et le résultat conventionnelle pour la mise à la retraite est inférieure à 3 mois : (préavis de mise à la retraite, salarié reconnu en tant que travailleur handicapé, CC<3 mois)
Actuellement, on affiche le message suivant: “La durée à appliquer pour le salarié est donc à la durée prévue par la convention collective, celle-ci étant plus longue que la durée légale.”
> 
> Modifier par la phrase suivante: “Le salarié étant reconnu comme travailleur handicapé, la durée du préavis est doublée sans pouvoir excéder trois mois.”

J'attends le retour de @noemiechassard par rapport à ce message sur Mattermost:
> Il y a une erreur pour les salariés reconnus en tant que travailleur handicapé. Leur durée de préavis est doublée dans la limite de 3 mois. Cependant, si la convention collective prévoit une durée au moins égale à 3 mois, c’est cette durée supérieure à 3 mois qui s’applique (Article L5213-9). Or, dans le simulateur, pour le préavis de mise à la retraite, on affiche les 3 mois maximum même quand la durée de préavis conventionnelle est supérieure. Par exemple, quand la durée de mise à la retraite est de 6 mois, on affiche quand même 3 mois alors que la durée affichée devrait être 6 mois.

cf: https://github.com/SocialGouv/code-du-travail-numerique/issues/3527

**Comment by noemiechassard** [comment]
Pour le départ à la retraite, quand le salarié a répondu « Oui » à la question «  Le salarié concerné est-il reconnu en tant que travailleur handicapé ? » :
Dans la page résultat, dans les éléments saisis, ajouter un astérisque après  «  Travailleur handicapé: Oui »
Puis, en bas des éléments saisis afficher la phase suivante : 
« _* Le salarié étant reconnu en tant que travailleur handicapé, la durée du préavis de départ à la retraite est doublée mais ne peut pas dépasser un maximum de 3 mois._ »

Pour la mise à la retraite, quand le salarié a répondu « Oui » à la question «  Le salarié concerné est-il reconnu en tant que travailleur handicapé ? » :
Dans la page résultat, dans les éléments saisis, ajouter un astérisque après  «  Travailleur handicapé: Oui »
Puis, en bas des éléments saisis afficher la phase suivante : 
« _* Le salarié étant reconnu en tant que travailleur handicapé, la durée du préavis de mise à la retraite est doublée mais ne peut pas dépasser un maximum de 3 mois. Si la durée de préavis prévue par la convention collective est supérieure à 3 mois, le résultat conventionnel n’est pas doublé et c’est cette durée qui s’applique car elle est plus favorable._ »

De plus, dans tous les cas quand le salarié est reconnu en tant que travailleur handicapé, ajouter l’article L5213-9 dans les sources (https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006903707/)

**Comment by noemiechassard** [comment]
### Dans le résultat décrypté : 

**Départ à la retraite, CC remplie, CDT<CC**: la phrase affichée actuellement est la suivante : « _La durée à appliquer pour le salarié est donc la durée légale, celle-ci étant plus longue que la durée prévue par la convention collective._ ». 

Or, il devrait être indiqué ceci « _La durée à appliquer pour le salarié est donc la durée légale, celle-ci étant plus courte que la durée prévue par la convention collective._ »

**Départ à la retraite, CC remplie, CC<CDT**:  la phrase affichée actuellement est la suivante :  « _La durée à appliquer pour le salarié est donc la durée prévue par la convention collective, celle-ci étant plus longue que la durée légale._ ». 

Or, il devrait être indiqué ceci « _La durée à appliquer pour le salarié est donc la durée prévue par la convention collective, celle-ci étant plus courte que la durée légale._ ».

### Dans les éléments saisis:

**Mise à la retraite, salarié reconnu en tant que travailleur handicapé, CC non renseignée ou renseignée mais non traitée** : Je remplacerais le message affiché par un message semblable à celui existant pour le départ à la retraite:  "_Le salarié étant reconnu en tant que travailleur handicapé, la durée du préavis de mise à la retraite est doublée mais ne peut pas dépasser un maximum de 3 mois._"
