### ISSUE TITLE
Modifier wording outil préavis retraite

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3551]
### Description
Remplacer tous les "quelle est **votre** X" par "quelle est l'X **du salarié**" 

Étape "informations" : remplacer "quelle est votre catégorie professionnelle ?" par "Quelle est la catégorie professionnelle du salarié ? "

Étape "ancienneté" : remplacer "Quelle est votre ancienneté dans l’entreprise ?" par "Quelle est l'ancienneté du salarié dans l’entreprise ?" cf https://github.com/SocialGouv/code-du-travail-numerique/issues/3528

**Comment by m-maillot** [comment]
A valider mais tout le wording est bon maintenant.

**Comment by m-maillot** [comment]
On peut cloturer @romain-b13  ?
