### ISSUE TITLE
Investiguer les 404

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3553]
**Description**
114 erreurs 404 ont été détectées lors de l'audit de Jonathan du 10/06/21 : 
https://docs.google.com/spreadsheets/d/1RuiIiXxUecH31PuKRw99OhaAovNnXPlf/edit#gid=420209843

D'autres erreurs 404 ont été identifiées le 02/06/21(toujours en 404) : 
https://docs.google.com/spreadsheets/d/1te_4Zbt9nwo4ftAz1xpBSnWryKLs0LC5rMQP1EpNRxw/edit#gid=0

D'autres 404 ont été identifiées le 07/06/21 : ces 404 étaient-elles liées à la MAJ de la preprod le même jour ? (1ère explication : la prod ne récupérait plus les fiches). Pourquoi la préprod n'était pas le reflet de la prod ?

Pourquoi certaines fiches sont en 404 chez nous alors qu'elles existent toujours sur MT ou SP et que l'URL MT ou SP dans l'admin est la bonne ?
ex : 
- https://code.travail.gouv.fr/fiche-ministere-travail/etre-apprenti
- https://www.service-public.fr/particuliers/vosdroits/F2918

**Comment by revolunet** [comment]
De mes recherches : 

 - les liens HS impots.gouv.fr sont de nouveau accessibles
 - pas mal d'erreurs viennent d'un bug sur travail-emploi.gouv.fr. exemple sur le lien "délégation du personnel du CSE" sur [cette page](https://travail-emploi.gouv.fr/dialogue-social/le-comite-social-et-economique/article/cse-commissions-sante-securite-et-conditions-de-travail-cssct). 
<img width="582" alt="Capture d’écran 2021-06-11 à 14 06 31" src="https://user-images.githubusercontent.com/124937/121684621-36affe80-cabf-11eb-8fa5-1329557cb910.png">


- aussi, ce contenu absent : https://travail-emploi.gouv.fr/sante-au-travail/suivi-de-la-sante-au-travail-10727/article/le-suivi-de-l-etat-de-sante-des-salaries, référencé dans leurs contenus, mais aussi dans le menu du meme site nous cause quelques soucis :

<img width="1621" alt="Capture d’écran 2021-06-11 à 14 10 11" src="https://user-images.githubusercontent.com/124937/121684483-07998d00-cabf-11eb-854d-961365d14b9e.png">

Pour le reste ce sont des liens morts qui sont toujours référencés sur les contenus que nous récupérons.

**Comment by romain-b13** [comment]
@jrduscher on peut mentionner les exemples cités par Julien si on leur fait un mail
