### ISSUE TITLE
Ajouter encadré "attention" intro outil préavis retraite

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3561]
**Description**
à l'étape résultat de l'outil de préavis de retraite apparaît l'encadré suivant : 
![image](https://user-images.githubusercontent.com/84397271/122196185-4badd880-ce97-11eb-9122-3c418a3d99e5.png)

Il faudrait prévenir dès l'introduction avec un message général (puisque l'utilisateur n'a pas encore entré ses infos) qu'un autre délais différent de celui calculé pourrait s'appliquer (Une convention collective de branche, un accord collectif d’entreprise, le contrat de travail ou un usage).

Contenu du message à définir

**Comment by noemiechassard** [comment]
**Proposition de modifier l’introduction par**: 

“Ce simulateur est un outil qui permet de calculer la durée de préavis à respecter en cas de départ ou de mise à la retraite, telle qu'elle est prévue par la loi et la convention collective applicable.

En effet, en cas de départ ou de mise à la retraite, le salarié ne peut pas quitter l’entreprise immédiatement. Il doit y rester durant une certaine période, qu’on appelle préavis ou parfois délai congé.

Afin de réaliser cette simulation, vous aurez besoin d’informations concernant la situation du salarié, comme sa convention collective, sa catégorie ou son coefficient. La plupart de ces informations se trouvent sur le bulletin de salaire ou le contrat de travail. Prévoyez X à X minutes pour cette simulation.

_Attention : Le résultat affiché correspond à la durée légale ou conventionnelle, en fonction des informations renseignées. Toutefois, une durée plus favorable peut être prévue par un accord collectif d’entreprise, le contrat de travail, un usage ou encore une convention collective de branche (si non renseignée dans le simulateur). Dans ce cas, c’est cette durée plus favorable qui s’applique au salarié._ 

Cliquez sur commencer pour démarrer la simulation.”

**Précisions**: 

- Hésitation concernant la mention ou non de la convention collective de branche car elle peut être tout de même renseignée.

- Pas de précision, comme dans l’encadré qui apparaîtra dans la page résultat, concernant la définition d’une durée plus favorable (Rappel: Durée différente en fonction du départ ou de la mise à la retraite)

- Pas de précision non plus sur la condition d’ancienneté plus favorable qui peut être abrupte pour l’utilisateur dès le début du simulateur

**Comment by romain-b13** [comment]
mettre le message "attention" dans un encadré à part (italique)

**Comment by m-maillot** [comment]
Décision à prendre sur l'affichage ou non de cette information et le format d'affichage (voir Mattermost pour les propositions)

**Comment by m-maillot** [comment]
On garde en format italique en bas de page.
