### ISSUE TITLE
Impression accordéon résultat outil préavis retraite

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3562]
**Description**
Lors de l'étape résultat de l'outil de préavis de retraite, le détail résultat est accessible dans un accordéon : 
![image](https://user-images.githubusercontent.com/84397271/122196932-fde5a000-ce97-11eb-9f0b-33bac056c116.png)

Il faut voir le comportement lors de l'impression

**Comment by m-maillot** [comment]
Accordéon plié : 
<img width="621" alt="image" src="https://user-images.githubusercontent.com/992514/129351537-a17b0449-c992-4de9-984f-ee3b3bb0e427.png">

Accordéon déplié:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/992514/129351602-db851b03-0fc0-4b9e-a26b-ba70e8d9688d.png">
<img width="569" alt="image" src="https://user-images.githubusercontent.com/992514/129351619-aa42314e-b255-4016-8c07-34e46f8747d9.png">

Ca me semble bon :)

Qu'en penses tu @romain-b13 ? On peut clôturer cette issue ?

**Comment by romain-b13** [comment]
Parfait je clôture :)
