### ISSUE TITLE
Tracking outil préavis retraite

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3568]
### Étape « introduction »
event : start_préavis retraite

### Étape « origine du départ à la retraite »
**Clics sur les 2 propositions « le salarié décide lui-même de partir à la retraite » ou « l’employeur décide de mettre le salarié à la retraite »**
event : view_step origine départ retraite
Action de l'évent : click_départ à la retraite ou click_mise à la retraite

### Étape « Convention collective »
**Convention collective**
event action : view_step_convention collective
nom de l'event : convention_collective

**Les recherches de CC effectuées par l'utilisateur**
Catégorie de l'évent : cc_search
name de l'event : recherche utilisateur

**La CC sélectionnée par l'utilisateur**
Catégorie de l'évent : cc_select

**Les clics sur le bouton "Précédent"**
action event : click_previous_préavis retraite
event name : click previous convention collective

### Étape « informations »
event : view_step_informations

**La catégorie professionnelle sélectionnée par l'utilisateur**
event value= texte de la catégorie
event Action :  select_position_category

**Les clics sur le bouton "précédent"**
Action de l'évent : click_previous_step_préavis_retraite
Name de l'évent : click_previous_step_informations

### Étape ancienneté 
Nom de l'event : view_step_ancienneté

**Clic « oui » ou « non » "Le salarié a-t-il plus de 2 ans d'ancienneté dans l'entreprise (2 ans exclu) ? »** (comprend également la question spécifique à la CC 2264 : "Le salarié a-t-il au minimum 5 ans d'ancienneté dans l'entreprise ?")
Action de l'évent : click_oui_ancienté plus N ans ou click_non_ancienneté plus N ans

**Le nombre de mois indiqué dans « Quelle est votre ancienneté dans l’entreprise en mois ? »**
event value
action name : ancienneté value

**Les clics sur le bouton "précédent"**
Action de l'évent : click_previous_step_préavis_retraite
Name de l'évent : click_previous_step_ancienneté

### Étape résultat
event : view_step_resultats

**Clic sur « Détail du calcul »**
event : click_calcul_détail 

Les clics sur le bouton "Précédent"
Action de l'évent : click_previous_step_préavis_retraite
Name de l'évent : click_previous_step_résultats

**Comment by romain-b13** [comment]
@ArmandGiraud je te laisse commenter cette issue en indiquant si besoin le format de base à utiliser à chaque fois que l'on veut tracker un choix entre deux propositions -  la sélection d'une CC/d'une catégorie pro... - une saisie dans un champ

**Comment by ArmandGiraud** [comment]
### Étape « introduction »
```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "start"
}
```

### Étape « origine du départ à la retraite »
Clics sur les 2 propositions « le salarié décide lui-même de partir à la retraite » ou « l’employeur décide de mettre le salarié à la retraite »
```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "préavis_salarié" ou "préavis_employeur"
}
```

### Étape « Convention collective »
Convention collective
```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "infos_cc"
}
```
### Les recherches de CC effectuées par l'utilisateur
Catégorie de l'évent : cc_search
```
{
    "eventCategory": "cc_search",
    "eventAction": "{nom de la page}",
    "eventName": "{nom de la recherche + uuid}"
}
```
### La CC sélectionnée par l'utilisateur
Catégorie de l'évent : cc_select
```
{
    "eventCategory": "cc_select",
    "eventAction": "{nom de la page}",
    "eventName": "{nom de la cc sélectionnée}"
}
```

### Les clics sur le bouton "Précédent"
```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "click_previous_{nom d'étape}"
}
```

### Étape « informations »
```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "infos"
}
```

### La catégorie professionnelle sélectionnée par l'utilisateur
event value= texte de la catégorie
event Action : select_position_category
```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "select_pos_category_{name_pos}"
}
```

### Étape ancienneté
Nom de l'event : view_step_ancienneté
```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "select_pos_category_{nom de la position}"
}
```
### Clic « oui » ou « non » "Le salarié a-t-il plus de 2 ans d'ancienneté dans l'entreprise (2 ans exclu) ? » (comprend également la question spécifique à la CC 2264 : "Le salarié a-t-il au minimum 5 ans d'ancienneté dans l'entreprise ?")
```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "click_anciennete_plus" ou "click_anciennete_moins"
}
```

### Le nombre de mois indiqué dans « Quelle est votre ancienneté dans l’entreprise en mois ? »
event value
action name : ancienneté value
```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "anciennete_mois_{nombre de mois}"
}
```
ping @lionelB tu sais comment on peut passer le nombre de mois en valeur numérique, sans avoir à parser le nom d'event derrière? , un peu comme dans le questionnaire? 


### Étape résultat
```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "results"
}
```

### Clic sur « Détail du calcul »
```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "click_calcul_détail"
}
```

**Comment by romain-b13** [comment]
### **Events mis à jour suite au point réalisé le 07/09/21 :**


### **Étape « introduction »**
```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "start"
}
```
### **Étape « origine du départ à la retraite »**
Clics sur les 2 propositions « le salarié décide lui-même de partir à la retraite » ou « l’employeur décide de mettre le salarié à la retraite »
```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "préavis_salarié" ou "préavis_employeur"
}
```
### **Étape « Convention collective »**
Convention collective
```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "ccn"
}
```
### **Les recherches de CC effectuées par l'utilisateur**
Catégorie de l'évent : cc_search
```
{
    "eventCategory": "cc_search",
    "eventAction": "{nom de la page}",
    "eventName": "{nom de la recherche + uuid}"
}
```
### **La CC sélectionnée par l'utilisateur**
Catégorie de l'évent : cc_select
```
{
    "eventCategory": "cc_select",
    "eventAction": "{nom de la page}",
    "eventName": "{nom de la cc sélectionnée}"
}
```
### **Les clics sur le bouton "Précédent"**

```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "click_previous_{nom d'étape}"
}
```

### **Étape « informations »**
```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "infos"
}
```

### **Étape ancienneté**
Nom de l'event : view_step_ancienneté

```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "ancienneté" (?)
}
```

### **Clic « oui » ou « non » "Le salarié a-t-il plus de 2 ans d'ancienneté dans l'entreprise (2 ans exclu) ? » (comprend également la question spécifique à la CC 2264 : "Le salarié a-t-il au minimum 5 ans d'ancienneté dans l'entreprise ?")**

```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "click_anciennete_plus" ou "click_anciennete_moins" => **pas de dédoublement, event lancé au clic sur "suivant**"
}
```

### **Étape résultat**

```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "results"
}
```

### **Clic sur « Détail du calcul »**

```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "click_calcul_détail" => **pas de dédoublement**
}
```

**Comment by m-maillot** [comment]
@romain-b13 est ce que l'on ne fait pas cette issue également avant la mise en prod ?

**Comment by maxgfr** [comment]
J'ai deux questions :

Pourquoi l'utilité de rajouter cet event, du fait que on le track après que la personne ait choisi si c'est un départ ou mise à la retraite ?

```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "ccn"
}
```
Est-ce qu'ici c'est un `view_step` ?

```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "ancienneté" (?)
}
```

**Comment by maxgfr** [comment]
## **Events mis à jour suite au point réalisé le 12/10/21 :**

Tous les events sont activés après l'utilisation du bouton suivant

### **Étape « origine du départ à la retraite »**
Clics sur les 2 propositions « le salarié décide lui-même de partir à la retraite » ou « l’employeur décide de mettre le salarié à la retraite »
```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "depart" ou "mise"
}
```

### **Clic « oui » ou « non » "Le salarié a-t-il plus de 2 ans d'ancienneté dans l'entreprise (2 ans exclu) ? »** 

```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "anciennete_plus_2_ans" ou "anciennete_moins_2_ans"
}
```

### **Clic sur « Détail du calcul »** 

```
{
    "eventCategory": "outil",
    "eventAction": "Préavis de Retraite",
    "eventName": "click_calcul_détail" => **pas de dédoublement**
}
```

> Le dernier point à mettre sur tous les outils
