### ISSUE TITLE
Permettre d'entrer les périodes via un calendrier outil indemnité licenciement

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3573]
**Description**
Dans l'outil de calcul de l'indemnité légale de licenciement, lorsqu’il y a une alternance entre périodes à temps plein et à temps partiel (cf image) on demande à l'utilisateur d'entrer le nombre de mois. En fonction du format sous lequel il trouve l'info il peut être amené a efctuer un calcul de nombre de mois
![image](https://user-images.githubusercontent.com/84397271/122795177-56b0a080-d2bd-11eb-9710-fd5210b09273.png)

**Solution**
Permettre à l'utilisateur d’entrer le début et la fin d’une période via un calendrier

**Comment by m-maillot** [comment]
Cette fonctionnalité n'existant plus, je clôture cette issue.
