### ISSUE TITLE
Préciser champ rémunération outil indemnité licenciement

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3574]
**Description**
[alternance périodes à temps plein et à temps partiel] : il faudrait préciser ce que l’on attend dans le champ rémunération : le salaire brut mensuel, la rémunération totale sur l’ensemble des mois… ?
![image](https://user-images.githubusercontent.com/84397271/122796104-4f3dc700-d2be-11eb-9611-191bb92b1750.png)

**Comment by m-maillot** [comment]
Cette fonctionnalité n'étant plus présente, je clôture l'issue.
