### ISSUE TITLE
CCs down en prod

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3612]
**Description**
1) Dans l'outil "trouver sa convention collective" le moteur de recherche de CCs ne trouve aucune CC dans le parcours "je connais ma CC". 
2) Toujours dans l'outil "trouver sa convention collective",  dans ans le parcours "je ne connais pas ma CC" une fois l'entreprise sélectionnée, lorsque je clique sur la CC proposée, la page de la CC est en 404
3) Lorsque je cherche une CC dans le moteur général interne, les CCs n'apparaissent plus dans les résultats

**Tout ceci fonctionne bien en preprod**

**Reproduction**
Etapes à suivre pour reproduire le bug n°1
1. Go to 'Trouver sa convention collective'
2. Click on 'Je connais ma convention collective'
3. Type 'Transports routiers'

Etapes à suivre pour reproduire le bug n°2
1. Go to 'Trouver sa convention collective'
2. Click on 'Je ne connais pas ma convention collective'
3. Type 'Castorama' in 'Nom de votre entreprise ou numéro Siret (obligatoire)'
4. Click on 'Castorama France'
5. Click on 'Bricolage (vente au détail en libre-service) IDCC 1606'
6. See error

Etapes à suivre pour reproduire le bug n°3
1. Type 'boulangerie' in the search engine
2. Press enter
3. See error : la convention collective de la boulangerie is not present in the results

**Comment by m-maillot** [comment]
Merge du fix pour éviter de pousser les données en prod s'il y a eu un échec. 
En cours d'investigation avec les Ops + SRE pour voir si le soucis ne vient pas de la configuration d'ES sur le prod. Car le processus ne plante pas en preprod et ce sont les mêmes processus.

**Comment by romain-b13** [comment]
Lionel va : 
- investiguer la cause des CCs down en prod qui ne l'étaient pas en preprod
- voir pour que cela remonte bien en échec

Idées de solutions mentionnées par Lionel : 
- faire des tests e2e après le job de mise à jour
- faire des tests de matching de nombre de documents dans l'admin et dans elastic
