### ISSUE TITLE
Problème affichage et téléchargement des infographies

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3614]
### 1) Les infographies ne sont pas visibles lors de l'ouverture de l'accordéon 
![image](https://user-images.githubusercontent.com/84397271/124780826-33cfee80-df43-11eb-8bc0-99cd5c9c2bef.png)

### 2) Les infographies ne peuvent pas être téléchargées
![image](https://user-images.githubusercontent.com/84397271/124780699-1a2ea700-df43-11eb-9c93-e65137cc727a.png)

Ex : 
- https://preprod-code-du-travail-numerique.dev2.fabrique.social.gouv.fr/information/report-ou-annulation-de-visites-medicales-nouveautes-covid-19?q=suivi%20medical
- https://preprod-code-du-travail-numerique.dev2.fabrique.social.gouv.fr/information/covid-19-reagir-en-cas-de-contamination-dans-lentreprise-protocole-national?q=guide%20employeur

**Comment by m-maillot** [comment]
Problème sur le job de copie des fichiers :
https://gitlab.factory.social.gouv.fr/SocialGouv/cdtn-admin/-/jobs/1706687

**Comment by m-maillot** [comment]
Problème corrigé via la PR https://github.com/SocialGouv/code-du-travail-numerique/pull/3615
Fixé en prod, encore présent en préprod. Prévoir une MEP pour le corriger définitivement.

**Comment by lionelB** [comment]
fixé en preprod en attendant une release
