### ISSUE TITLE
Proposer des contenus lors d'une recherche d'un article du CDT

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3619]
**Fonctionnalité**
Actuellement le moteur détecte le format d'un article du code du travail afin de proposer des articles du CDT dans les résultats de la recherche.
Il serait intéressant de proposer dans les résultats d'une recherche d'article du CDT, les contenus (fiches...) dans lesquels l'article recherché par l'utilisateur est référencé.

**Comment by romain-b13** [comment]
Voir en premier lieu le taux de sélection lors d'une recherche d'article du CDT pour voir s'il est pertinent de proposer des contenus (fiches...) référençant l'article recherché plutôt que l'article lui-même => https://github.com/SocialGouv/code-du-travail-numerique/issues/3590

**Comment by rmelisson** [comment]
taux de recherches de type "reference article" : 3%
taux de selection d'article avant / après modif : 41% / 60%
