### ISSUE TITLE
affichage intitulé complet texts ex: art. CDTravaill

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#362]
ajouter dans l'intitulé des résultats d'afficage des articles du code du travail , " du code du travail" après l'article LXXX-XX **du code du travail**.

Attention, il pourrait y avoir par la suite d'autres codes à indexer ( code rural... ) en tenir compte.
![image](https://user-images.githubusercontent.com/37538697/49924448-a88b3b00-feb6-11e8-942f-496adc5481c4.png)

![image](https://user-images.githubusercontent.com/37538697/49924522-de302400-feb6-11e8-81fb-2ee9a40bc87f.png)

![image](https://user-images.githubusercontent.com/37538697/49924571-01f36a00-feb7-11e8-8f55-90688995ccc6.png)

- [ ] **harmoniser l**'affichage entre les différentes propositions: généraliser  l’affichage "Code du Travail | L. 1121-1 "  des suggestions.

**Comment by lionelB** [comment]
tu veux qu'on rajoute `du code du travail` apres le title en bleu ?
![](https://user-images.githubusercontent.com/37538697/49924522-de302400-feb6-11e8-81fb-2ee9a40bc87f.png)

Est ce que sur les autres images c'est ok ?

**Comment by lionelB** [comment]
![image](https://user-images.githubusercontent.com/160320/51025655-eef2b900-158c-11e9-92ac-1fc45d83e1f8.png)
