### ISSUE TITLE
Liste des contenus et préqualifiées associeés

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3625]
Il serait intéressant d'avoir un tableau dans lequel on aurait tous les contenus du CDTN et en face les requêtes préqualifiées associées à chaque contenu. Cela nous permettrait d'identifier les contenus pour lesquels l'ajout de préqualifiées serait peut-être nécessaire.

**Comment by Armandgrd** [comment]
Liste disponible [ici](https://docs.google.com/spreadsheets/d/1VtzVG34CSucAiwNduF6EngEHOhqPTwyN3b-P0_amk3k/edit?usp=sharing), format à valider
