### ISSUE TITLE
Analyser la page qui suit la consultation d'un dossier dans les sessions

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3629]
**Description**
Aujourd'hui nous n'avons pas de moyen pour analyser l'impact de la mise en ligne sur les contenus qu'il référence. 
Sur Matomo on voit uniquement le nombre de clics sur les "rubriques" du dossier mais pas sur les contenus (fiches, modèles, outils...).

L'idée serait donc de développer quelque chose pour voir à chaque fois la page qui suit la visite du dossier dans les sessions. Autrement dit pouvoir identifier à chaque fois qu'un contenu est visité depuis le dossier.

**Comment by Armandgrd** [comment]
Statistiques dans ce fichier:
https://docs.google.com/spreadsheets/d/1jrxX5zo-U-loGg9SEZj8cKvbVkD8eafcGC14FGLvOZM/edit#gid=0
