### ISSUE TITLE
Harmoniser le format des events sur Matomo

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3633]
### Problème
Il est difficile de bien comprendre ce qui est tracké derrière les noms d'events, les events actions.. Parfois les noms d'events dans un cas semblent être plutôt une action d'event dans un autre cas.

Exemple d'actions d'event :
![image](https://user-images.githubusercontent.com/84397271/125907180-74dc7035-aa01-4f37-b4f5-3868786cd641.png)

Exemple de noms d'event :
![image](https://user-images.githubusercontent.com/84397271/125907378-7599dcff-28b3-42b4-bcd3-f5e68ce3282f.png)

### Proposition
1) définir ce que l'on appelle une action d'événement dans matomo (ex : le clic sur une proposition dans une étape ou sélection d'une proposition dans une liste déroulante), un nom d'événement et une catégorie d'événement.

2) Définir un format spécifique pour les noms d'event, les actions d'event, les catégoriesd'event
Ex : 
view_step_nom de l'étape
Click_nom du choix 1_nom de l'étape

**Comment by Armandgrd** [comment]
J'ai écrit une [documentation sur les évènements présents sur le site aujourd'hui ainsi que quelques bonnes pratiques. ](https://hackmd.io/T0X5EjHqTR6C0cGVs10qJw)
A intégrer au wiki du site dès que le document est finalisé. 
Il y a déjà quelques incohérences:
-  dans la manière dont on track les noms de CCN (IDCC, dans le nouvel outil "trouver sa convention" vs Nom dans les `CC_SELECT`).
- le champ `event_name`, `event_action` et `event_value` sont utilisés de manières détournée dans certains évènements

**Comment by m-maillot** [comment]
Doc placé dans le wiki et mise à jour.
