### ISSUE TITLE
Critère accessibilité 7.4 outil préavis de retraite

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3642]
**Fonctionnalité**
Traiter le critère 7.4 avant MEP de l'outil : Pour chaque script qui initie un changement de contexte, l’utilisateur est-il averti ou en a-t-il le contrôle ?
Cf issue https://github.com/SocialGouv/code-du-travail-numerique/issues/3571 pour laquelle le critère 7.4 a été traité dans la modale de contact téléphonique

A l'étape CC dans le préavis de retraite, lorsque que l'utilisateur commence à taper des lettres, les résultats s'affichent sans action de "lancement" de la recherche de la part de l'utilisateur. Ainsi l'utilisateur utilisant le lecteur d'écran n'est pas averti de l'apparition des résultats.

![image](https://user-images.githubusercontent.com/84397271/126784545-b35545c6-47c7-41b0-a3e2-1943db858c10.png)

Ce critère sera aussi à traiter pour chaque étape CC des outils + les pages contrib (pages personnalisables)

**Comment by m-maillot** [comment]
Je repasse la tâche en Spec en cours en attendant de voir comment on traitre la recherche de CC en étant accessible.

**Comment by romain-b13** [comment]
voici une solution proposée par Maroua (ayanr réalisé l'audit) pour rendre le composant accessible sans ajouter un bouton (bien vérifier l'ajout des role / aria ...et le comportement clavier (Keyboard Support))
https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/grid-combo.html

**Comment by romain-b13** [comment]
cf https://github.com/SocialGouv/code-du-travail-numerique/issues/4227
