### ISSUE TITLE
Analyse sélection des CCs dans les outils

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3646]
**Description**
Analyser le nombre de visiteurs ayant sélectionné une CC dans les outils sur le nombre total de visiteurs de l'outil

 Analyser le nombre de visiteurs allant jusqu'à l'étape résultat et ayant sélectionné une CC (= les visiteurs qui obtiennent un résultat conventionnel et non légal) sur le nombre de visiteurs total allant jusqu'à l'étape résultat
 Type de résultat attendu : 61% des utilisateurs de l'outil X arrivent à l'étape résultat mais uniquement 24% avec un “résultat conventionnel”

**Comment by ArmandGiraud** [comment]
- nécessite une analyse dédie (on peut ajouter les cc_search et cc_select dans un flowchart qui décrit l'usage des outils)

**Comment by Armandgrd** [comment]
Analyse cours,  en même temps que celle pour #3655
