### ISSUE TITLE
Ajouter outils préavis licenciement + trouver sa CC dans Kibana

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3647]
**Description**
Ajouter les outils préavis de licenciement + trouver sa convention collective dans les graph "Outils/Actions" du rapport "Aggregated Popularity"

**Comment by ArmandGiraud** [comment]
Done, on peut close

**Comment by ArmandGiraud** [comment]
- préavis de licenciement ajouté, il reste un bug sur trouver sa convention collective, on a que l'event start pour le moment
