### ISSUE TITLE
Analyser le nombre de visiteurs d'une contrib qui sélectionnent une CCs

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3648]
**Description**
Sur le nombre total de visiteurs des pages contributions (= pages personnalisables) avoir la proportion de visiteurs sélectionnant une CC.

**Comment by ArmandGiraud** [comment]
[Segment Matomo CC_SEARCH + Contrib](https://matomo.fabrique.social.gouv.fr/index.php?module=CoreHome&action=index&idSite=4&period=day&date=yesterday&updated=1#?idSite=4&period=day&date=yesterday&segment=eventCategory%3D%3Dcc_search;eventAction%3D@%25252Fcontribution%25252F&category=Dashboard_Dashboard&subcategory=1)

A comparer avec le [segment Contributions](https://matomo.fabrique.social.gouv.fr/index.php?module=CoreHome&action=index&idSite=4&period=day&date=yesterday#?idSite=4&period=day&date=yesterday&segment=eventCategory%3D%3Dcc_search;eventAction%3D@%25252Fcontribution%25252F&category=Dashboard_Dashboard&subcategory=1&compareSegments%5B%5D=pageUrl%3D@%25252Fcontribution) seulement:

**Comment by romain-b13** [comment]
> [Segment Matomo CC_SEARCH + Contrib](https://matomo.fabrique.social.gouv.fr/index.php?module=CoreHome&action=index&idSite=4&period=day&date=yesterday&updated=1#?idSite=4&period=day&date=yesterday&segment=eventCategory%3D%3Dcc_search;eventAction%3D@%25252Fcontribution%25252F&category=Dashboard_Dashboard&subcategory=1)
> 
> A comparer avec le [segment Contributions](https://matomo.fabrique.social.gouv.fr/index.php?module=CoreHome&action=index&idSite=4&period=day&date=yesterday#?idSite=4&period=day&date=yesterday&segment=eventCategory%3D%3Dcc_search;eventAction%3D@%25252Fcontribution%25252F&category=Dashboard_Dashboard&subcategory=1&compareSegments%5B%5D=pageUrl%3D@%25252Fcontribution) seulement:

J'ai voulu faire la même chose en créant le segment suivant pour connaître la proportion d'utilisateurs recherchant une CC sur le nombre d'utilisateurs étant présent à l'étape "info_CC" d'un outil : 

Catégorie d'évènement est CC_select
ET
 Nom d'évènement est info_CC
 
 Problème : ça m'indique 0 visite

**Comment by ArmandGiraud** [comment]
Il s’agit ici de réaliser un segment sur 2 évents différents d’une même
visite, malheureusement c’est impossible avec la version gratuite de
matomo. La solution est le custom report qui permet de combiner des filtres
mais c’est une feature payante

ERRATUM:
il s'agit probablement d'un bug dans l'implementation de la requête côté matomo, probablement lié à [cette issue](https://github.com/matomo-org/matomo/issues/17388)

**Comment by romain-b13** [comment]
D'accord merci Armand.
Ce n'est pas non plus possible d'après ce que je vois d'avoir le segment : 

Catégorie d'évènement est CC_select
ET
URL de la page est https://code.travail.gouv.fr/outils/convention-collective#convention
