### ISSUE TITLE
Analyser la proportion de visiteurs d'une page CC qui effectue une recherche sur légifrance

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3649]
**Description**
Avoir la proportions des visiteurs des pages CC (ex : page de la CC Boulangerie-pâtisserie (entreprises artisanales)) qui effectue une recherche en bas de page sur légifrance : 
![image](https://user-images.githubusercontent.com/84397271/127023078-f28e1e54-3ed2-434a-b841-fdd2dcc8198c.png)

Cet event pourrait être utilisé pour la mesure de la satisfaction des usagers (en considérant que les utilisateurs effectuant une recherche n'ont pas trouvé leur réponse dans la page "questions-réponses" de la CC

**Comment by romain-b13** [comment]
Il faut d'abord vérifier qu'il n'y a pas d'autre moyen d'arriver sur legifrance/search depuis le CDTN hormis la recherche en bas des pages CC

**Comment by ArmandGiraud** [comment]
Analyse one shot, ou dashboard à créer?

**Comment by ArmandGiraud** [comment]
il existe un event dédié : `pagecc_searchcc` , [comparaison de segments créés sur matomo](https://matomo.fabrique.social.gouv.fr/index.php?module=CoreHome&action=index&idSite=4&period=day&date=yesterday&updated=1#?idSite=4&period=range&date=2021-06-21,2021-06-24&segment=pageUrl%3D@convention-collective%25252F;pageUrl!@outils&category=Dashboard_Dashboard&subcategory=1&compareSegments%5B%5D=eventCategory%3D%3Dpagecc_searchcc)

**Comment by ArmandGiraud** [comment]
On trouve sur une journée 300-400 recherches sur légifrance pour 2000 - 3000 visites de pages:
ça fait un taux de search autour de ~15%. 
![image](https://user-images.githubusercontent.com/22575341/127136876-3d45b318-6997-483f-85c5-eebe0a6f08cb.png)
