### ISSUE TITLE
Ecart entre données outils kibana et events matomo

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3650]
**Description**
Sur kibana, dans le rapport Aggregated Popularity, lorsqu'on regarde le graphe "outils/actions - indemnité de licenciement" du 1er juin au 30 juin on voit 32 834 visites en "start" => donc sur la page d'intro

Sur matomo lorsqu'on regarde l'event view_step_Indemnité de licenciement du 01/06 au 30/06 on a 176 184 visites

Pourquoi un tel écart ?

**Comment by ArmandGiraud** [comment]
`view_step_Indemnité de licenciement` est la somme de toutes les étapes de l'outil en question soit 5 étapes avec ~30K consultations par étapes ça réduit sensiblement l'écart. Pour avoir seulement le nombre au départ il faut combiner event action `view_step_Indemnité de licenciement` et eventName `start`

**Comment by romain-b13** [comment]
> `view_step_Indemnité de licenciement` est la somme de toutes les étapes de l'outil en question soit 5 étapes avec ~30K consultations par étapes ça réduit sensiblement l'écart. Pour avoir seulement le nombre au départ il faut combiner event action `view_step_Indemnité de licenciement` et eventName `start`

Yes merci,  là je viens de regarder du 01/05 au 30/06 pour l'indemnité de licenciement
- En start sur Kibana : 62 719
- Matomo : action d'event "view_step_Indemnité de licenciement" combiné à name d'event "start" : 82 402

Du coup on a 20 000 d'écart, mais ça ne peut pas être lié à la perte de jours côté Kibana comme vous aviez récupéré les jours et régénéré les rapports de mai et juin ?

**Comment by ArmandGiraud** [comment]
Yep, bien v u ! cela vient du dédoublonnage des visites: sur kibana on compte le nombre de visites uniques seulement, alors que matomo compte le nombre d'event brut. 

Sur kibana on trouve quasiment 82 000 si je passe en nombre d'event brut.
![image](https://user-images.githubusercontent.com/22575341/127184027-ac75b511-83f4-439d-9cf6-caeb44fa5fac.png)

On peut changer le dashboard si tu préfères le nombre d'event Brut. Il n'ya pas de trou dans la donnée
