### ISSUE TITLE
Quelle est la signification du click_previous dans Matomo ?

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3652]
**Description**
L'event click_previous correspond-il au clic sur le bouton précédent de l'étape indiquée  ?
A quoi correspond le click_previous de l'introduction puisqu'il n'y a pas de bouton précédent => est-ce le précédent du navigateur ?

**Comment by ArmandGiraud** [comment]
the code generating the click_previous [is here](https://github.com/SocialGouv/code-du-travail-numerique/blob/1fd3d27d8239257036be03320ebeffa68047b12c/packages/code-du-travail-frontend/src/outils/common/Wizard.js#L49):
L'étape indiquée est la page source du click previous

**Comment by romain-b13** [comment]
> the code generating the click_previous [is here](https://github.com/SocialGouv/code-du-travail-numerique/blob/1fd3d27d8239257036be03320ebeffa68047b12c/packages/code-du-travail-frontend/src/outils/common/Wizard.js#L49):
> L'étape indiquée est la page source du click previous

Pour la page d'intro c'est bien le bouton précédent du navigateur du coup ?

**Comment by Armandgrd** [comment]
l'event view_step intro n'arrive que lors d'un click previous, depuis la page précédente
