### ISSUE TITLE
Absence de log kibana depuis le 18/07

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3654]

**Comment by ArmandGiraud** [comment]
- Backup Jobs Fail with timout from 27/07 https://gitlab.factory.social.gouv.fr/SocialGouv/cdtn-monolog/-/jobs/1784417
- Register Image fail with access denied https://gitlab.factory.social.gouv.fr/SocialGouv/cdtn-monolog/-/jobs/1777565
- ingest job fail `TypeError: yargs_namespaceObject.scriptName is not a function` with https://gitlab.factory.social.gouv.fr/SocialGouv/cdtn-monolog/-/jobs/1778855

**Comment by ArmandGiraud** [comment]
- Fix apporté sur le module Yargs
- rattrapage des logs effectués

**Comment by Armandgrd** [comment]
Relancé par Julien, la CI monlog a l'air de fonctionner, à surveiller
