### ISSUE TITLE
Analyser le parcours des utilisateurs lors d'une recherche sur le CDTN

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3655]
**Description**
Sur Matomo on observe que la home arrive en tête des pages consultées après une recherche interne, cela signifie que la majorité des utilisateurs arrivent sur la home après la requête ?

**Comment by ArmandGiraud** [comment]
Pas nécessairement, 
 (c'est la même pour toutes les recherches infructueuse, alors qu'il s'agit d'une page différente pour toutes celles qui sont fructueuses).
Cela signifie que l'event `retour à la home` est plus fréquent que la page la plus clickée (mais je suppose que c'est le cas pour tous les moteurs).  
 
par ailleurs:
- le selection ratio après une search est faible ~0,5
- Les évènements intermédiaires (selection results, etc...) peuvent interférer dans le calcul de matomo.
A vérifier en détail
