### ISSUE TITLE
Pb affichage résultat préavis de démission quand la CC ne prévoit rien 

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3659]
**Description**
Pour tous les cas où la CC ne prévoit rien pour le préavis de démission comme sur l'image si dessous : 

![image](https://user-images.githubusercontent.com/84397271/127679842-0ec28264-28c9-4046-a252-48c3aac8066d.png)

**1) Remplacer "A partir des éléments..." par :**

**"À partir des éléments que vous avez saisis : 
il n’y a pas de préavis à effectuer"** 

**2) Le message dans l'encadré doit être remplacé par "L'existence ou la durée du préavis de démission peut être prévue par un accord d’entreprise ou à défaut, par un usage dans l’entreprise."**

Voici les cas concernés pour l'outil préavis de démission :
![image](https://user-images.githubusercontent.com/84397271/150632957-978c0df1-baec-4cd5-96a2-067e7202710b.png)

**Comment by noemiechassard** [comment]
Je valide cette issue

**Comment by m-maillot** [comment]
- [x] Pas de tests unitaires (snapshot seulement)
- [x] Pas en typescript

Il faudrait typer le json et pourvoir retourner null dans l'`answer` pour indiquer qu'il n'y a pas de réponse de la CC. A partir de là, on pourrait afficher tel ou tel message.

**Comment by carolineBda** [comment]
@romain-b13 c'est normal qu'on affiche cette phrase même si on une durée prévu par la CC (quand on une CC sélectionnée) :
![Screenshot from 2022-02-03 16-16-24](https://user-images.githubusercontent.com/4971715/152371392-4bba1fb4-14f7-4ca2-850f-b2e4aeba0549.png)

**Comment by romain-b13** [comment]
En fait en principe on devrait bien avoir l'encadré "attention" mais la phrase devrait être "L'existence ou la durée du préavis de démission peut être prévue par un accord d'entrprise ou à défaut, par un usage dans l'entreprise"
=> on ne devrait donc pas avoir la mention "convention collective" dans l'encdaré bleu

Ce problème est déjà identifié et fait partie de la to do d'Axel dans le but de proposer pour chaque simulateur et pour chaque situation des phrases cohérentes avec les informations entrées (comme ce qui a été fait pour le préavis de retraite)

**Comment by carolineBda** [comment]
@romain-b13 d'après ce qu'on s'est dit ce matin, maintenant le message d'alerte sera :
"  L’existence ou la durée du préavis de démission peut être prévue par un accord d’entreprise ou à défaut, par un usage dans l’entreprise."
dès qu'il y a une CC, qu'il y ait un résultat ou non. C'est bien ça ?

**Comment by romain-b13** [comment]
> @romain-b13 d'après ce qu'on s'est dit ce matin, maintenant le message d'alerte sera : " L’existence ou la durée du préavis de démission peut être prévue par un accord d’entreprise ou à défaut, par un usage dans l’entreprise." dès qu'il y a une CC, qu'il y ait un résultat ou non. C'est bien ça ?

C'est ça il faut cette phrase dès lors qu'il y a une CC de sélectionnée **que nous traitons**
Si nous ne traitons pas la CC sélectionné alors on garde l'autre message
