### ISSUE TITLE
Bouton "voir plus" prend le rôle de "suivant" étape CC des outils

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3669]
A l'étape convention collective des outils, lorsque je commence à tape dans le champ "Renseignez le nom de votre convention collective, le nom de votre entreprise ou son SIRET" et qu'il y a plusieurs résultats, lorsque je clique sur "voir plus" pour voir plus de résultats alors je passe à l'étape suivante.

En résumé : le bouton "voir plus" à le rôle de "suivant".

![image](https://user-images.githubusercontent.com/84397271/127825340-68e99f51-e998-4b53-9345-df26b0d7b63b.png)

Lorsque je clique sur "voir plus" j'arrive ici (ex de l'outil "préavis de démission")

![image](https://user-images.githubusercontent.com/84397271/127825487-0c34b949-45ad-4382-836a-de5bf0b39031.png)

**Comment by m-maillot** [comment]
Je ne reproduis pas. Pourrais tu indiquer le navigateur utiliser et décrire les étapes pour le reproduire ?

**Comment by romain-b13** [comment]
Aller sur le simulateur "préavis de démission" (ou un autre)
A l'étape "convention collective" dans le champ de saisie il faut taper "tra" puis cliquer sur "voir plus"
