### ISSUE TITLE
Change the way we collect pre-qualified in monolog

### ISSUE THREAD

**Issue by ArmandGiraud** [SocialGouv/code-du-travail-numerique#3679]
since pre-qualified results are completed with search results, we can no longer rely on identical results to group variations, we need to query the admin interface to collect them.

**Comment by Armandgrd** [comment]
ping @rmelisson

**Comment by rmelisson** [comment]
we miss the query clusters : for PQ variants / for search variations

**Comment by rmelisson** [comment]
https://github.com/SocialGouv/cdtn-monolog/commit/57e142a53e667c62b1c7c85174ab915ef2c066e0

**Comment by rmelisson** [comment]
todo: vérifier les query reports avec Armand
