### ISSUE TITLE
Events module précision du feedback des usagers

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3682]
**Description**
Créer les events pour le nouveau module permettant aux utilisateurs de préciser leur feedback en fin de page qui devrait être mergé prochainement

@ArmandGiraud il me semble que tu es juste en attente de la la MEP du module ?

**Comment by lionelB** [comment]
les event existent déjà, cela a été discuté dans l'issue  https://github.com/SocialGouv/code-du-travail-numerique/issues/2550#issuecomment-887501394
