### ISSUE TITLE
Modèles de lettre de notification de licenciement [2] : motif éco collectif et individuel

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#369]
la trame centrale et les premiers exemples resservent pour attaquer le volet économique.
- 3 items:, voire 4, selon découpage. SPEC needed
- Au préalable retour d'expérience du sprint précédent #368, et corrections des bugs et spec.

**Comment by ClementChapalain** [comment]
done avec les modèles de courrier intégrés et valiés par la DGT
