### ISSUE TITLE
Interface CCN à harmoniser pour les recherches infructueuses sur le moteur du CDTN

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#3699]
**Description**

Des alternatives à la recherche infructueuse sur le moteur de recherche sont proposées à l'usager : à savoir la navigation par thème ou la recherche de CCN.
![image](https://user-images.githubusercontent.com/37538697/130258792-270031eb-3b5c-41f8-88c2-88f436369886.png)

La recherche de CCN renvoie à une modale reprenant les anciennes modalités de recherche: 
![image](https://user-images.githubusercontent.com/37538697/130258882-e2d8cce0-356d-4a00-9048-06c74b5b0195.png)

**Reproduction**
Etapes à suivre pour reproduire le bug
1. En page d'accueil taper contrat dans le champ de recherche
2. Aller en bas de page , à l'encadré "Vous n'avez pas trouvé ce que vous cherchez?"
3. Cliquer sur "Chercher une convention collective"

**Comportement attendu**
Renvoi vers la page de recherche de convention collective conventionnelle. https://code.travail.gouv.fr/outils/convention-collective

**Comment by m-maillot** [comment]
Cette recherche a été complètement revue. Je clôture ce ticket.
