### ISSUE TITLE
Ajout d'une aide dans la modal "choisissez votre CCN"

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#37]
info pour trouver la CCN. comment l'integrer?

**Comment trouver ma convention collective ?**
	Elle doit figurer au bulletin de paie, et sur une notice remise à l’embauche ou sur le contrat de travail
	Sur l’affichage obligatoire dans l’entreprise (avec les modalités de consultation en entreprise)
Quelle est la CCN applicable :
•	En principe celle relevant de l’activité principale dans l’entreprise pour les cas les plus simples.

**Comment by revolunet** [comment]
cf #99
