### ISSUE TITLE
En tant qu'utilisateur je souhaite pouvoir afficher les infographies en taille réelle

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3702]
**Problème**
Les infographies (images) dans les pages informations sont peu lisibles

**Solution**
Permettre à l'utilisateur d'afficher l'image en taille réelle 

**Résultat attendu**
Une loupe apparaît lorsque l'utilisateur passe son curseur sur l'image, au clic l'image apparaît en plein écran.
L'utilisateur peut utiliser la barre de défilement pour parcourir l'intégralité de l'image. Une croix est disponible en haut à droite pour quitter l'affichage en taille réelle.

**Comment by maxgfr** [comment]
J'ai fixé le bug du scrolling sur mon dernier commit @romain-b13

**Comment by romain-b13** [comment]
Merci @maxgfr 
Retour : Sur internet explorer ( :sweat_smile: ) la loupe ne s'affiche pas au survol de l'image

**Comment by romain-b13** [comment]
**Issue validée** 
Nous ne modifions pas le curseur (zoom-in et zoom-out) qui n'apparaît par sur internet explorer puisque cela fonctionne quand même au clic et que internet explorer est utilisé par une faible proportion de nos utilisateurs
