### ISSUE TITLE
Tracker les clics sur les "Articles de la convention collective"

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3703]
**Description**
L'objectif est de pouvoir analyser le nombre de clics sur les tuiles des articles proposées dans la rubrique "Articles de la convention collective" des pages CC. Les articles sont regroupés par thème. Voir image ci-dessous

![image](https://user-images.githubusercontent.com/84397271/130810487-18eeb9de-a1c4-45ae-824b-4135e0a7d9ef.png)

**Comment by romain-b13** [comment]
On pourrait en profiter pour faire une analyse plus globale du parcours des visiteurs de pages convention collective ([ex de page CC ici](https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/convention-collective/843-boulangerie-patisserie-entreprises-artisanales?q=convention%20collective%20de%20la%20boulangerie%20et%20p%C3%A2tisserie%20industrielle)).
Que fait un utilisateur quand il consulte une page CC : 
- il repart aussitôt ? => avoir le temps moyen passé sur une page CC
- il clique sur les articles de la convention collective ? 
![image](https://user-images.githubusercontent.com/84397271/136337679-36a2d71e-883d-44a1-bd8c-05692fbbc46d.png)

- il fait une recherche dans sa CC (qui amène sur Légifrance) ? 
![image](https://user-images.githubusercontent.com/84397271/136337763-ee57ea68-e05b-4d90-bda7-7c3044829113.png)

**Comment by Armandgrd** [comment]
https://docs.google.com/presentation/d/1AesLg_jo0waIUmpR5Mdw2AHUU7i_zhyG83yHnhwo32M/edit?usp=sharing
