### ISSUE TITLE
[Audit RGAA] P01 à P14 - 11.9

### ISSUE THREAD

**Issue by maxgfr** [SocialGouv/code-du-travail-numerique#3718]
- Zone de recherche qui s’affiche au scrolle en haut de page – le bouton de recherche n’a pas d’intitulé → ajouter un title sur le bouton de recherche (title="Lancer ma recherche")

**Comment by romain-b13** [comment]
A voir si ce critère est à traiter dans :
- modale "Contacter nos services en région"

![image](https://user-images.githubusercontent.com/84397271/131887470-624a1c49-4d19-458b-bea7-24c72cecfeb1.png)

- dans les pages "convention collective" => en bas de page on propose d'effectuer une recherche ("Recherche dans la convention collective") qui amène sur legifrance (ex de [page convention collective](https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/convention-collective/843-boulangerie-patisserie-entreprises-artisanales?q=convention%20collective%20de%20la%20boulangerie%20et%20p%C3%A2tisserie%20industrielle))

![image](https://user-images.githubusercontent.com/84397271/131887529-8d6ca28f-a476-4339-a0db-d6c21eef6a6c.png)

- la zone de recherche qui s'affiche au scroll en haut de page est présente sur l'ensemble des pages 

![image](https://user-images.githubusercontent.com/84397271/131887667-3ce950c8-608d-4020-bc96-7ab00468de47.png)


Les autres zones de recherche présentes ( ex : étape convention collective des simulateurs) n'ont pas de bouton pour lancer la recherche

**Comment by maxgfr** [comment]
Attention à P9

**Comment by maxgfr** [comment]
> Attention à P9

Corrigé

**Comment by maxgfr** [comment]
> A voir si ce critère est à traiter dans :
> 
> * modale "Contacter nos services en région"
> 
> ![image](https://user-images.githubusercontent.com/84397271/131887470-624a1c49-4d19-458b-bea7-24c72cecfeb1.png)
> 
> * dans les pages "convention collective" => en bas de page on propose d'effectuer une recherche ("Recherche dans la convention collective") qui amène sur legifrance (ex de [page convention collective](https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/convention-collective/843-boulangerie-patisserie-entreprises-artisanales?q=convention%20collective%20de%20la%20boulangerie%20et%20p%C3%A2tisserie%20industrielle))
> 
> ![image](https://user-images.githubusercontent.com/84397271/131887529-8d6ca28f-a476-4339-a0db-d6c21eef6a6c.png)
> 
> * la zone de recherche qui s'affiche au scroll en haut de page est présente sur l'ensemble des pages
> 
> ![image](https://user-images.githubusercontent.com/84397271/131887667-3ce950c8-608d-4020-bc96-7ab00468de47.png)
> 
> Les autres zones de recherche présentes ( ex : étape convention collective des simulateurs) n'ont pas de bouton pour lancer la recherche

Bien vu Romain, j'ai corrigé les points que t'as cité. Il manquait belle et bien les éléments pour le RGAA
