### ISSUE TITLE
[AUDIT RGAA] P01 à P14 - 9.2

### ISSUE THREAD

**Issue by maxgfr** [SocialGouv/code-du-travail-numerique#3720]
```
-Enlever la balise <nav> dans <footer>
-Enlever la balise <header> appliqué sur « Besoin de plus d’informations ? » 
-Mettre les 3 liens d’évitement (allez à la navigation ,…) dans une balise <nav>
-En haut de page : mettre en dehors de la balise <nav> le bouton «Accessibilité» 
```

**Comment by romain-b13** [comment]
A voir si le critère "Enlever la balise header appliqué sur « Besoin de plus d’informations ? »" est à traiter dans les cas suivants :
- « Besoin de plus d’informations ? » est présent sur chaque page 

- "Avez-vous trouvé la réponse à votre question ?" en fin de page se trouve-t-il dans le même cas que « Besoin de plus d’informations ? » ?
![image](https://user-images.githubusercontent.com/84397271/131891232-ff80e521-241b-47f0-94fd-cef123fecddc.png)

- "Vous n’avez pas trouvé ce que vous cherchiez ? Essayez …" en fin de page lors d'une recherche sur le CDTN se trouve-t-il dans le même cas que « Besoin de plus d’informations ? » ?
![image](https://user-images.githubusercontent.com/84397271/131891170-196c2d32-02db-4cd5-a915-2e432017ec56.png)

- Les titres des thèmes et "contenus correspondants" se trouve-t-il dans le même cas que « Besoin de plus d’informations ? » ?
![image](https://user-images.githubusercontent.com/84397271/131891430-ff8a5535-0902-4031-a4b8-d1521da262fe.png)

**Comment by romain-b13** [comment]
**La balise header a été identifiée à plusieurs endroits :**

### - Sur la Home : les parties sélectionnées dans les captures ci dessous
![image](https://user-images.githubusercontent.com/84397271/132496764-06a29d72-3cb9-4092-8376-79a93bdd1693.png)

![image](https://user-images.githubusercontent.com/84397271/132496821-b203c795-1de1-4840-975f-cc5e4a03bec2.png)

![image](https://user-images.githubusercontent.com/84397271/132496908-eaa82e2b-6e4c-40fa-84bf-5bb3704552a8.png)

![image](https://user-images.githubusercontent.com/84397271/132496975-42f14066-2b80-46ef-ae82-3a69e5b32079.png)

### - Lors d'une recherche sur le site 

![image](https://user-images.githubusercontent.com/84397271/132497238-88d1fc91-e1e1-4f59-b7d6-6633dc3ec588.png)

### - Tout en bas de la page lors d'une recherche sur le site 
![image](https://user-images.githubusercontent.com/84397271/132497389-5bbdc235-7d90-4faa-bf6c-e2210284072a.png)

+

![image](https://user-images.githubusercontent.com/84397271/132497456-0c97cced-81ee-4002-a868-606be4c8f95e.png)

### - Dans la boîte à outils 
![image](https://user-images.githubusercontent.com/84397271/132497546-9a017590-4c97-42c2-9856-1a6c21416bbd.png)

### - Dans les thèmes 
![image](https://user-images.githubusercontent.com/84397271/132497784-0c89f028-c7a4-4169-b67f-bc5ed2b6dbd9.png)

**Comment by maxgfr** [comment]
Pour corriger ce bug, j'ai mis par défaut le composant `<Title>` comme étant une div. En revanche, j'ai rajouté la propriété `isHeader` to set le HOC comme étant un header.

**Comment by romain-b13** [comment]
J'avais identifié d'autres endroits où il y a avait une balise "header", du coup est-ce que c'est bon aussi pour les suivants : 

### - Une fois que j'ai cliqué sur un thème ([ex ici](https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/themes/salaire-et-remuneration))
![image](https://user-images.githubusercontent.com/84397271/132540101-3c566fa5-1dc6-4b2b-b0ce-1b7fb2a40c03.png)

### - Toujours une fois que j'ai cliqué sur un thème ([ex ici](https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/themes/salaire-et-remuneration))
![image](https://user-images.githubusercontent.com/84397271/132540583-97762269-e267-4175-8697-7ad8549fb35c.png)

### - Dans la modale accessibilité 
![image](https://user-images.githubusercontent.com/84397271/132540849-5cbfde50-16bb-4afc-ae03-c72c83caa496.png)

### - Les titres H1 et H2 de toutes les fiches ministère du travail/service-public/Pages personnalisables (contribution)/pages information ([exemple ici)](https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/information/pass-sanitaire-et-contrat-de-travail)
![image](https://user-images.githubusercontent.com/84397271/132541846-10252dba-a169-430b-99be-c2611b9e904d.png)

### - Le h2 "que dit votre convention collective" en bas des pages personnalisables ([exemple ici)](https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/contribution/les-conges-pour-evenements-familiaux?q=les%20cong%C3%A9s%20pour%20%C3%A9v%C3%A9nements%20familiaux)
![image](https://user-images.githubusercontent.com/84397271/132542009-a1489656-3870-4ec2-b9d6-2ba684dd142c.png)

**Comment by maxgfr** [comment]
Merci @romain-b13 

Les balises header sont toujours présentes sur les URLs que tu m'as envoyé.

La question que je me pose, concerne si cela fait partie des modifications nécessaires pour le critère.

https://www.geeksforgeeks.org/html-5-header-tag/#:~:text=The%20tag%20in%20HTML,but%20this%20is%20not%20required.

A en discuter avec @lionelB @m-maillot
