### ISSUE TITLE
[Audit RGAA] P01 à P14 - 9.3

### ISSUE THREAD

**Issue by maxgfr** [SocialGouv/code-du-travail-numerique#3723]
```
-Mette les 2liens de navigation en haut de page « Boîte à outils + Thèmes » dans une balise <ul><li> 
-En bas de page : mettre les 6 liens externes dans une <ul><li>( « travail-emploi.gouv.fr / service-public.fr , etc..)  
-Mettre les blocs dans <div> a la place de <ul><li>
```

**Comment by romain-b13** [comment]
A voir si ce critère est à traiter pour les cas listés ci-dessous

Nous avons beaucoup de liens externes : 
### - Dans le footer : 
![image](https://user-images.githubusercontent.com/84397271/131888540-f1bebb2d-e789-4404-ba54-399ed4e45f33.png)

### - Dans les dossiers => de nombreux liens vers des contenus externes
![image](https://user-images.githubusercontent.com/84397271/131888641-3ac12776-99ac-41d8-882f-b5095367fb45.png)
[Dossier aides à l'embauche ici](https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/dossiers/aides-et-accompagnement-embauche-et-perennisation-des-emplois)
[Dossier coronavirus ici](https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/dossiers/ministere-du-travail-notre-dossier-sur-le-coronavirus)

### - Dans les pages résultats des simulateurs =>dès qu'on clique sur une référence juridique avec le picto signalant l'ouverture d'une fenêtre on quitte le site
![image](https://user-images.githubusercontent.com/84397271/131888839-fbe5df6a-337e-4e8a-967f-c463f4dae1bd.png)
=> il s'agit de la dernière étape (étape résultat) des outils suivants : indemnité de licenciement, préavis démission, indemnité de précarité, préavis de licenciement, Heures pour recherche d'emploi, Préavis de départ et de mise à la retraite.
[Boîte à outils ici](https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/outils)

### - Dans les fiches Ministère du travail/ service-public (mais nous n'avons pas la main) => lorsque l'on clique sur la source on arrive sur le site du ministère du travail ou de service public

![image](https://user-images.githubusercontent.com/84397271/131889017-faf7cec2-26cb-4d47-baae-7f491285ad8e.png)
[ Ex de fiche service-public ici ](https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/fiche-service-public/conges-payes?q=cong%C3%A9)
[Ex de fiche ministère du travail ici](https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/fiche-ministere-travail/les-jours-feries-et-les-ponts?q=cong%C3%A9) 

### - Dans nos pages information (contenus éditoriaux) => dès qu'il y a un picto signalant l'ouverture d'une fenêtre on quitte le CDTN
![image](https://user-images.githubusercontent.com/84397271/131889138-955ae87e-e029-44c0-870c-6ff2fee57ad6.png)
[Ex de page information ici ](https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/information/pass-sanitaire-et-contrat-de-travail)

### - Dans les références juridiques en bas des pages contribution / information / fiches MT-SP / convention collective => quand on clique sur une référence juridique on arrive sur un site externe
![image](https://user-images.githubusercontent.com/84397271/131889699-e6b20249-ad25-4c34-9715-d98317d5ed7b.png)
[Ex de page contribution ici](https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/contribution/les-conges-pour-evenements-familiaux?q=les%20cong%C3%A9s%20pour%20%C3%A9v%C3%A9nements%20familiaux)
[Ex de page convention collective ici](https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/convention-collective/843-boulangerie-patisserie-entreprises-artisanales?q=boulangerie)
Il faut parfois ouvrir les accordéons pour voir les références juridiques (ex dans les pages convention collective)

### - Dans les pages convention collective quand on clique sur un article on arrive sur legifrance
![image](https://user-images.githubusercontent.com/84397271/131889804-bbbe65a5-e219-4661-bc9e-05d1418fbcda.png)
[Ex de page convention collective ici](https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/convention-collective/843-boulangerie-patisserie-entreprises-artisanales?q=boulangerie)

Voir ce qui est considéré comme "un bloc" pour définir si d'autres pages sont concernées par "Mettre les blocs dans div a la place de ul li"

Voir si d'autres liens de navigation sont à mettre dans une balise ul li

**Comment by maxgfr** [comment]
Attention à P5 - P6 - P7  - P13

**Comment by maxgfr** [comment]
Update : Point ci-dessus corrigé

**Comment by maxgfr** [comment]
> Attention à P5 - P6 - P7 - P13

Update : Point ci-dessus corrigé

**Comment by romain-b13** [comment]
### On retrouve également des blocs : 

### Sur la home dans "à la une" , dans les thèmes et dans la boîte à outils
![image](https://user-images.githubusercontent.com/84397271/132549801-836d2bd1-5e14-4c58-b35c-2d29d8c708dd.png)

![image](https://user-images.githubusercontent.com/84397271/132549377-2f41f8e6-4f94-45bb-b3a2-3b331f51fc78.png)

![image](https://user-images.githubusercontent.com/84397271/132549722-73a7667a-df7f-4ac4-a06f-9e9a72aa3bbe.png)

### Dans la boîte à outils :
https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/outils

### Dans les thèmes : 
https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/themes

### Dans les résultats d'une recherche sur le moteur 
https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/recherche?q=les+cong%C3%A9s+pour+%C3%A9v%C3%A9nements+familiaux

### Dans la partie "articles de la convention collective" des pages convention collective ([exemple ici](https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/convention-collective/843-boulangerie-patisserie-entreprises-artisanales?q=boulangerie)
![image](https://user-images.githubusercontent.com/84397271/132550509-ecf7b560-4994-4ca4-8bd4-17e52ee59599.png)
