### ISSUE TITLE
Voir s'il est possible d'améliorer la qualité des images 

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3724]
**Description**
Les infographies sur le CDTN (png) sont difficilement lisibles.
Même lorsque la taille de la typo est suffisante on voit un "léger flou" qui rend difficile la lecture des infographies.

Est-ce que quelque chose est faisable pour améliorer la qualité des images ?

**Comment by m-maillot** [comment]
La flou est dû au resize de l'image originale en plus petit. Pour éviter ce soucis, on peut : 
 * Utiliser des SVG mais cela demande du dev (et à valider)
 * Adapter la taille de l'image à 750px max mais du coup le zoom sur l'image n'est plus très utile
 * Générer plusieurs tailles images pour choisir l'image la plus adapté à ce que l'on va afficher (notamment sur écran mobile)

@romain-b13 peux tu nous donner une info en SVG pour que l'on teste sur nos environnements de dev ?
 *

**Comment by romain-b13** [comment]
Prochaine tâche sur ce sujet => pouvoir importer du svg dans l'admin
