### ISSUE TITLE
Affichage simulateur brut/net différent preprod/prod

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3728]
Lorsque l'on se rend sur le simulateur [brut/net sur la preprod ](https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/outils/simulateur-embauche) on voit sous le simulateur "Vous êtes dirigeant d'une SAS(U) ? Accéder au simulateur de revenu dédié" => quand on clique sur "Accéder au simulateur de revenu dédié" on a une erreur

![image](https://user-images.githubusercontent.com/84397271/131995627-7f564707-4e36-4a4b-9e61-44040b488c06.png)

![image](https://user-images.githubusercontent.com/84397271/131995898-ccdcddb7-cf28-4c0a-8805-445f3e74440c.png)

Par contre sur la prod la phrase "Vous êtes dirigeant d'une SAS(U) ? Accéder au simulateur de revenu dédié" sous le simulateur apparait 1 seconde puis disparaît => on ne peut donc pas cliquer sur "Accéder au simulateur de revenu dédié" puisqu'il n'est pas affiché

**Comment by lionelB** [comment]
j'ai bien le simulateur chez moi, c'est toujours le cas @romain-b13 ?

**Comment by romain-b13** [comment]
Oui il y a toujours le problème
En prod cette phrase sous le bloc bleu disparaît au bout de 1 ou 2 secondes : 
![image](https://user-images.githubusercontent.com/84397271/133255259-edeacd9b-85e7-4fbd-be49-d5f6349d0e6d.png)

En preprod la phrase reste bien affichée mais quand on clique sur "Accéder au simulateur de revenu dédié" il y a un erreur
