### ISSUE TITLE
Tracking CC traitées et non traitées 

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3733]
Dans l'ensemble des simulateurs ayant  une étape "convention collective" il serait  intéressant  de connaître la proportion  d'utilisateurs qui sélectionne une CC que nous traitons et la proportion  d'utilisateurs qui sélectionne une CC que nous ne traitons pas. 
Il faudrait  du coup  sûrement  créer  2 événements distincts : cc_select_traitée et cc_select_non traitée

**Comment by Armandgrd** [comment]
Realiser une PR dédiée, ajouter dans tous les modules CC_SEARCH/CC_SELECT un event dédié au moment du CC_SELECT: 
convention traitée/non-traitée. 
ping @m-maillot

**Comment by maxgfr** [comment]
Est-ce que ça vaut le coup de savoir exactement quelle CC a été traitée ou non traitée de manière interne à l'outil ?

**Comment by m-maillot** [comment]
Faire une étude pour savoir quels sont les simulateurs où l'information est dispo facilement (cc traitée et cc non traitée). 
Selon étude, on implémente si on a l'info sur l'ensemble des simulateurs.

**Comment by Armandgrd** [comment]
> Est-ce que ça vaut le coup de savoir exactement quelle CC a été traitée ou non traitée de manière interne à l'outil ?

Cela permet de savoir si à la date d'utilisation de l'outil quelles étaient les CC traitées, et permet d'expliquer un certain type de comportement a posteriori

Ex: la satisfaction utilisateur dépend probablement du fait qu'on a traité ou non sa CC.

**Comment by maxgfr** [comment]
> > Est-ce que ça vaut le coup de savoir exactement quelle CC a été traitée ou non traitée de manière interne à l'outil ?
> 
> Cela permet de savoir si à la date d'utilisation de l'outil quelles étaient les CC traitées, et permet d'expliquer un certain type de comportement a posteriori
> 
> Ex: la satisfaction utilisateur dépend probablement du fait qu'on a traité ou non sa CC.

Oui, je disais plus en mode : "Il faudrait rajouter le numéro exact de la CC sélectionné en plus du fait qu'on sache si c'est traité ou pas" 😅

Mais du coup, normalement c'est bon sur : #3872

**Comment by Armandgrd** [comment]
@maxgfr Tu pourrais détailler un petit peu ce qu'il se passe dans #3872 (je suis pas expert en js et le diff est assez costaud 😅 )?

Si j'ai bien compris, On track en tant que `eventName` la valeur de la variable CC_TREATED ou CC_UNTREATED, concaténé avec le numéro de la CC, c'est ça? C'est implémenté pour le préavis de retraite seulement ou tous les outils? 

Est-il possible de le logger dans le même event que le CC_SELECT, ou au moins au même moment? 
Il me semble que dans les events CC_SELECT on passe le nom de la cc plutôt que son numéro, c'est probablement mieux avec l'IDCC , en effet mais ce serait pas mal de rester cohérent (soit changer les deux en numéro, soit mettre les noms partout) cf #3633 . Un avis là dessus @romain-b13

J'ai d'ailleurs remarqué qu'on a un trou dans la raquette avec les CC_SELECT, pour les personnes qui ont déjà sélectionné leur CC précédemment dans leur session, c'est difficile de retrouver quelle est la CC.

**Comment by romain-b13** [comment]
> Est-il possible de le logger dans le même event que le CC_SELECT, ou au moins au même moment? Il me semble que dans les events CC_SELECT on passe le nom de la cc plutôt que son numéro, c'est probablement mieux, en effet mais ce serait pas mal de rester cohérent (soit changer les deux en numéro, soit mettre les noms partout) cf #3633 . Un avis là dessus @romain-b13

Pour moi du moment que l'on a la CC peu importe si c'est avec le nom ou avec le code IDCC donc faîtes au plus simple, mais en effet il faut que l'on harmonise les events

**Comment by romain-b13** [comment]
> J'ai d'ailleurs remarqué qu'on a un trou dans la raquette avec les CC_SELECT, pour les personnes qui ont déjà sélectionné leur CC précédemment dans leur session, c'est difficile de retrouver quelle est la CC.

Tu veux dire que pour les outils qu'ils vont utiliser après, ou les contributions qu'ils vont consulter après (avec la CC déjà présélectionner) on n'envoie plus d'event CC_SELECT ? Tu veux que je crée une issue dédiée ?

**Comment by maxgfr** [comment]
> J'ai d'ailleurs remarqué qu'on a un trou dans la raquette avec les CC_SELECT, pour les personnes qui ont déjà sélectionné leur CC précédemment dans leur session, c'est difficile de retrouver quelle est la CC.

@ArmandGiraud Tout d'abord rebondis sur ton point, c'est absolument vrai.  Le problème étant que si tu as déjà selectionné une CC, ça va te la mettre par défaut dans l'outil @romain-b13 .  Je pense qu'il faudrait créer une issue pour régler ça...

Concernant la PR, ce qu'il faut retenir, c'est juste ça dans [Search/index.tsx](https://github.com/SocialGouv/code-du-travail-numerique/blob/de9723407457af45fd0988d2ac7bc2f693de2d4d/packages/code-du-travail-frontend/src/conventions/Search/index.tsx) : 

```ts
 const onSelectLocalConvention = (ccn) => {
    const agreementStatus = getAgreementStatus(ccn);
    if (agreementStatus === AgreementStatus.Supported) {
      matopush([TRACK_EVENT, OUTIL, `${CC_TREATED}_${ccn.num}`]);
    } else {
      matopush([TRACK_EVENT, OUTIL, `${CC_UNTREATED}_${ccn.num}`]);
    }
    onSelectConvention(ccn);
  };
```

Concrètement, ce que je dis, c'est qu'à chaque fois qu'on sélectionne une convention collective, je crée un event comme quoi elle est traité ou non. Je spécifie le numéro de la convention collective au passage 😁

**Comment by Armandgrd** [comment]
Merci @maxgfr pour la clarification !
Plutôt que `matopush([TRACK_EVENT, OUTIL, `${CC_TREATED}_${ccn.num}`]);` je suggère d'utiliser le champ event_name pour passer le numéro de convention collective soit:
 `matopush([TRACK_EVENT, OUTIL, CC_TREATED, ccn.num]);` 

Pour rappel, les paramètres de la fonction sont ceux-ci: `matopush(["trackEvent", "eventCategory", "eventAction", "eventName", "eventValue"])` [cf le doc sur les evenements](https://hackmd.io/T0X5EjHqTR6C0cGVs10qJw?view#Liste-des-events-de-tracking).
Dans les autres events le numéro de cc était `idcc44`, si le format pouvait être le même ça serait top.

Merci pour la PR au passage, ça nous permettra de cibler les CC à traiter en priorité 💯

**Comment by maxgfr** [comment]
Ok, super, je te remercie pour ton retour @Armandgrd 😁

**Comment by romain-b13** [comment]
Il reste 2 questions à voir avec @ArmandGiraud 
 - Comment gérer le fait que les CC traitées et non traitées ne soient pas les mêmes pour chaque simulateur
 - Confirmer qu'il faut lancer l'event cc_select_traitée à la sélection de la CC et non au clic sur suivant

**Comment by maxgfr** [comment]
Attention à ce [commentaire](https://github.com/SocialGouv/code-du-travail-numerique/issues/3893#issuecomment-954698050)

**Comment by maxgfr** [comment]
Vérifiez aussi : 
```
switch (steps[stepIndex].name) {
      case initialState.steps[1].name: // "origine"
        matopush([
          MatomoCommonEvent.TRACK_EVENT,
          MatomoCommonEvent.OUTIL,
          form.getState().values["contrat salarié - mise à la retraite"] ===
          "oui"
            ? MatomoPreavisRetraiteEvent.MISE_RETRAITE
            : MatomoPreavisRetraiteEvent.DEPART_RETRAITE,
        ]);
        break;
      case initialState.steps[4].name: // "anciennete"
        matopush([
          MatomoCommonEvent.TRACK_EVENT,
          MatomoCommonEvent.OUTIL,
          form.getState().values.seniorityGreaterThanTwoYears
            ? MatomoPreavisRetraiteEvent.ANCIENNETE_PLUS_2_ANS
            : MatomoPreavisRetraiteEvent.ANCIENNETE_MOINS_2_ANS,
        ]);
        break;
      default:
        return;
```

Il manque sûrement le eventAction

**Comment by maxgfr** [comment]
> Attention à ce [commentaire](https://github.com/SocialGouv/code-du-travail-numerique/issues/3893#issuecomment-954698050)



> Vérifiez aussi :
> 
> ```
> switch (steps[stepIndex].name) {
>       case initialState.steps[1].name: // "origine"
>         matopush([
>           MatomoCommonEvent.TRACK_EVENT,
>           MatomoCommonEvent.OUTIL,
>           form.getState().values["contrat salarié - mise à la retraite"] ===
>           "oui"
>             ? MatomoPreavisRetraiteEvent.MISE_RETRAITE
>             : MatomoPreavisRetraiteEvent.DEPART_RETRAITE,
>         ]);
>         break;
>       case initialState.steps[4].name: // "anciennete"
>         matopush([
>           MatomoCommonEvent.TRACK_EVENT,
>           MatomoCommonEvent.OUTIL,
>           form.getState().values.seniorityGreaterThanTwoYears
>             ? MatomoPreavisRetraiteEvent.ANCIENNETE_PLUS_2_ANS
>             : MatomoPreavisRetraiteEvent.ANCIENNETE_MOINS_2_ANS,
>         ]);
>         break;
>       default:
>         return;
> ```
> 
> Il manque sûrement le eventAction

Les deux ont été traités

**Comment by maxgfr** [comment]
> Comment gérer le fait que les CC traitées et non traitées ne soient pas les mêmes pour chaque simulateur

Armand sait dans quel module on passe au préalable, par conséquent pas besoin de spécifier ça dans le payload. Et oui, ça serait intéressant de remonter cette information sur tous les simulateurs... (à voir comment gérer ça dans le code)

> Confirmer qu'il faut lancer l'event cc_select_traitée à la sélection de la CC et non au clic sur suivant

C'est clair que c'est mieux de gérer ça au suivant car ça se lie facilement au problème du fait que la CC est enregistré par l'outil

**Comment by maxgfr** [comment]
Avec la PR, je track tous les simulateurs. Il faudrait juste que je confirme avec un metier l'indemnité de précarité sur les CC trackées ou non.

De plus, en raison de la sauvegarde automatique de la CC entre tous les simulateurs, lorsque celle ci est selectionnée par défaut, j'envoie bien l'information à Matomo, or si la personne change n fois la CC, il y aura n evenements qui seront envoyés. Cela ne se trigger pas au suivant, mais au moment où le DOM sélectionne de manière automatique la CC (en remplissant le champ)

**Comment by maxgfr** [comment]
> Avec la PR, je track tous les simulateurs. Il faudrait juste que je confirme avec un metier l'indemnité de précarité sur les CC trackées ou non.

Point confirmé avec l'équipe métier
