### ISSUE TITLE
DO NOT EMOJI IN MATOMO

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#374]
because emoji are not supported  https://github.com/matomo-org/matomo/issues/7766
![oh-noes](https://user-images.githubusercontent.com/160320/49884458-30306580-fe35-11e8-936d-b53db77cbf95.gif)

**Comment by douglasduteil** [comment]
lol

**Comment by lionelB** [comment]
closed by #404

**Comment by douglasduteil** [comment]
Closed by 404 haha
