### ISSUE TITLE
Apparition des IDCC commençant par 0 dans les résultats

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3755]
**Description**
Dans l'outil "trouver sa convention collective", les idcc commençant par 0 sont bien interprétées, cependant en fonction du "poids" de la CC le résultat apparaît parfois dans "voir plus" alors qu'on tape le numéro IDCC exacte (ex : 0029 disponible dans voir plus) : 

![image](https://user-images.githubusercontent.com/84397271/133788055-105ffd84-e57e-47e0-bc0a-6eeb6b542874.png)

On voit que le moteur fait remonter des IDCC contenant "29" mais ne fait pas remonter en priorité le l'IDCC recherché.

**Solution**
Lorsque la requête ressemble à un IDCC complet existant alors on fait remonter ce résultat en premier

**Comment by rmelisson** [comment]
le format d'idcc complet est bien standard, de la forme `cccc` (c: chiffre) ?

**Comment by romain-b13** [comment]
**Ex de comportement attendu :** 

Requête : 00029
Résultat : la CC 0029 apparaît en premier dans les résultats

Requête : 29
Résultat : la CC 0029 apparaît en premier dans les résultats

**Comment by rmelisson** [comment]
dispo pour tester ici :

https://code-du-travail-numerique-remi-cc-search-3755-65fufo.dev.fabrique.social.gouv.fr/

**Comment by romain-b13** [comment]
> dispo pour tester ici :
> 
> https://code-du-travail-numerique-remi-cc-search-3755-65fufo.dev.fabrique.social.gouv.fr/

C'est top, je valide 👍
