### ISSUE TITLE
Les mots du glossaire n'apparaissent pas dans l'ordre alphabétique en prod

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3757]
**Description**
Quand on regarde dans l'admin les mors du glossaire sont bien classés dans l'ordre alphabétique (ex : "Base de données économiques, sociales et environnementales" apparaît en dernier en prod et bien en 1er dans l'admin)

En prod :  
![image](https://user-images.githubusercontent.com/84397271/133824190-717631d8-0ee0-427e-acf5-9e97cad02e15.png)

Dans l'admin :  
![image](https://user-images.githubusercontent.com/84397271/133824246-7abcb1d1-a074-48c7-b7e6-98ad7d4ae08d.png)

**Comment by m-maillot** [comment]
corrigé en prod.
