### ISSUE TITLE
[proposal] refacto CI

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#3760]
Afin de gagner en performance et en autonomie pour l'équipe, nous souhaiterions mettre en place github-actions en remplacement de gitlab-ci.

Une première étape serait de créer les workflows de lint et tests dans GH actions. il y a un exemple [ici](https://github.com/SocialGouv/code-du-travail-numerique/pull/3747/files#diff-b31f1e5654d027d84c24cdba2ff31ab79e3ea617091ed348a97476a27b076078) si besoin.

Une fois les workflows de tests en place, on pourra ajouter les actions de docker build, register et release cf [@socialgouv/actions](https://github.com/SocialGouv/actions). Il y aura un travail à faire sur les images docker elles-mêmes (les simplifier) qui embarquent aujourd'hui trop de code, notamment pour l'image frontend qui embarque le tooling pour les tests 🔫

Une fois les docker images bien register, il suffira de switcher les images docker utilisées dans les déploiements

Idéalement, on garde la CI de gitlab en parallèle jusqu'à ce que tout le process soit OK côté GitHub

A dispo pour aider à avancer là-dessus

les mêmes opérations seront à reproduire sur cdtn-admin et repos associés

**Comment by maxgfr** [comment]
+1
