### ISSUE TITLE
Erreur de tracking outil trouver sa CC

### ISSUE THREAD

**Issue by Armandgrd** [SocialGouv/code-du-travail-numerique#3814]
- Lorsqu'on se connecte sur: https://code.travail.gouv.fr/outils/convention-collective
2 évènements view_step - start sont envoyés. (il n'en faudrait qu'un).
- Lorsqu'on clique sur l'un des deux parcours:
 3 events sont envoyés:
   - un nouvel event view_step start (inutile)
   - un cc_search_type_of_users - click_p1 (celui-ci est correct)
   - un cc_search vide (inutile)
- lorsqu'on entre des caractères dans la barre le debounce est très faible, la valeur utilisée dans l'ancienne version (toujours présente ailleurs)

[ancienne version debounce tracking](https://github.com/SocialGouv/code-du-travail-numerique/blob/85ede1ed0cd193db8c10e188b726120e2276f859/packages/code-du-travail-frontend/src/conventions/Search/index.js#L16)

[Nouvelle version du debounce tracking](https://github.com/SocialGouv/code-du-travail-numerique/blob/85ede1ed0cd193db8c10e188b726120e2276f859/packages/code-du-travail-frontend/src/outils/ConventionCollective/agreement/SearchAgreement.tsx#L30)

**Comment by rmelisson** [comment]
pour les events cc_search / enterprise_search :
- les problemes d'event vide et de debounce sont résolus
- j'ai changé le payload de l'event pour un objet (plutot qu'une string avec un delimiter ##), il faudra le parser côté Monolog

pour les events view_step, ils sont générés automatiquement par la page "Outils", ça me semble un peu plus compliqué de modifier ça :
https://github.com/SocialGouv/code-du-travail-numerique/blob/remi/cc-search-events-3814/packages/code-du-travail-frontend/pages/outils/%5Bslug%5D.tsx#L61

**Comment by rmelisson** [comment]
les duplicats sont résolus également
