### ISSUE TITLE
Titre encadré "A noter" CCs qui ne seront pas traitées préavis retraite

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3841]
**Description**
A l'étape convention collective de l'outil préavis de retraite, lorsque l'utilisateur sélectionne une CC qui n'est pas traitée (et ne le sera pas), un encadré "A noter" s'affiche. Dans le titre de l'encadré "A noter" ajouter "A noter : convention non traitée"

**Comment by m-maillot** [comment]
Fixed by https://github.com/SocialGouv/code-du-travail-numerique/pull/3839
