### ISSUE TITLE
Fix "Content-Security-Policy HTTP header" on all pages

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#3847]
Sur toutes nos pages on a cette erreur
![Screenshot 2021-10-12 at 14 24 45](https://user-images.githubusercontent.com/4971715/136955626-d2cb6ea4-b08f-4a6c-9272-46c1336556bd.png)

Vu dans Ligthouse aussi :

![Screenshot 2021-10-13 at 12 51 58](https://user-images.githubusercontent.com/4971715/137119701-3e82d6b5-88ff-4d93-889c-5fef7462e373.png)

**Comment by carolineBda** [comment]
Solution : downgrader la version du client Sentry. revert ce commit : https://github.com/SocialGouv/code-du-travail-numerique/pull/3282

**Comment by m-maillot** [comment]
La version de Sentry va être mise à jour cette semaine. Il faudrait voir si l'erreur est toujours présente.

**Comment by carolineBda** [comment]
Sentry a été mise à jour. Nous pouvons donc updater le clicent et passer sur le client Nextjs :
https://docs.sentry.io/platforms/javascript/guides/nextjs/

**Comment by maxgfr** [comment]
cf: https://validator.w3.org/nu/?doc=https%3A%2F%2Fcode.travail.gouv.fr%2Fmodeles-de-courriers%2Frupture-dun-commun-accord-dun-contrat-de-travail-a-duree-determinee

**Comment by maxgfr** [comment]
Avec la balise `style`
