### ISSUE TITLE
accent en trop balise title contribution congés pour événement familial

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3870]
**Description**
Dans les balises title des contributions "congés pour événement familial" il y a un accent sur le 3ème "e" qui ne devrait y être 

![image](https://user-images.githubusercontent.com/84397271/137343342-d7e739d3-3755-498d-b908-7ffa1e61fdd4.png)

![image](https://user-images.githubusercontent.com/84397271/137343602-7620189d-528b-493f-a3b8-c174baa16b9b.png)

**Comment by m-maillot** [comment]
@romain-b13, la donnée est obtenue via le thème créé dans l'admin. Il faut corriger le thème directement :
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/992514/137685943-d9d5f8ce-2e67-4382-b301-cf30836dbc6d.png">

**Comment by romain-b13** [comment]
Fait depuis l'admin
