### ISSUE TITLE
Nouveaux events préavis retraite

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3893]
### 1) Ajouter un event sur les bouton "aide" (picto point d'interrogation) 

- **Etape informations** : 
    - pour la question "Quelle est la catégorie professionnelle du salarié ?"
    -  pour les questions "Quel est l'échelon du salarié ?" ou "Quel est le groupe du salarié ?" [existe-t-il d'autres questions similaires avec un autre terme que "échelon" ou "Groupe" (ex : quel est le niveau du salarié ? / quelle est la position du salarié ?)]

- **Etape ancienneté** : pour la question "Le salarié a-t-il plus de 2 ans d'ancienneté dans l'entreprise (à partir de 2 ans + 1 jour) ?"

/!\ : l'event n'est pas envoyé au clic sur "suivant" mais au moment de la sélection de la valeur

```
event_category: "outil"
event_action: "view_step_Préavis de départ ou de mise à la retraite"
event_name: click_help_button_categorie_pro / event_name: click_help_echelon / event_name: click_help_groupe
```

### 2) Ajouter un event sur la sélection d'une réponse pour les questions : "Quelle est la catégorie professionnelle du salarié ?" / "Quel est l'échelon du salarié ?" / "Quel est le groupe du salarié ?" [existe-t-il d'autres questions similaires avec un autre terme que "échelon" ou "Groupe" (ex : quel est le niveau du salarié ? / quelle est la position du salarié ?)]

/!\ : l'event n'est pas envoyé au clic sur "suivant" mais au moment de la sélection de la valeur

```
event_category: "outil"
event_action: "view_step_Préavis de départ ou de mise à la retraite"
event_name: select_value_echelon / event_name: select_value_categorie_pro / event_name: select_value_groupe
```

**Comment by maxgfr** [comment]
Pour le bouton help de l'ancienneté, j'ai nommé l'event : `click_help_anciennete`

**Comment by maxgfr** [comment]
Quid si le mec click plusieurs sur le bouton "aide" ?

De même s'il switch de value plusieurs fois ?

Enfin ici mon event envoyé : 
```
MatomoCommonEvent.TRACK_EVENT, //trackEvent
MatomoCommonEvent.OUTIL, // outil
MatomoPreavisRetraiteEvent.ACTION, // "view_step_Préavis de départ ou de mise à la retraite",
MatomoPreavisRetraiteEvent.CLICK_HELP_ANCIENNETE, // "click_help_anciennete"
```

Alors que sur l'issue #3733 :
```
TRACK_EVENT, OUTIL, CC_TREATED, ccn.num
```

Je pense que sur #3733, il faut rajouter : `MatomoPreavisRetraiteEvent.ACTION`

**Comment by maxgfr** [comment]
D'ailleurs les `select_value` sur l'ancienneté sont dispatchés après un suivant, ici les `select` ont un train de vie différent

**Comment by maxgfr** [comment]
Pour finir l'issue il faudrait mettre en place la problématique de la question : Quel est le groupe du salarié et les autres questions du style :

<img width="758" alt="Screenshot 2021-10-29 at 15 35 36" src="https://user-images.githubusercontent.com/25312957/139444757-5b190cb7-6f0e-49c5-94cf-7d390c8526c4.png">

**Comment by maxgfr** [comment]
Update : Si le mec clique plusieurs fois sur le bouton aide, on envoie plusieurs fois l'event

**Comment by Armandgrd** [comment]
> Update : Si le mec clique plusieurs fois sur le bouton aide, on envoie plusieurs fois l'event

Yep, c'est pas gênant on le considère comme une étape optionnelle, et on dédupliquera l'event au niveau de la session dans l'analyse si besoin.
