### ISSUE TITLE
[CI] Optimiser les Dockerfile du frontend (monorepo) et de l'interface de programmation d'application (API)

### ISSUE THREAD

**Issue by maxgfr** [SocialGouv/code-du-travail-numerique#3916]

**Comment by 62f** [comment]
> 
You didn't say much.
![image](https://user-images.githubusercontent.com/68332197/138576110-6c45f08c-bc0c-48e1-a6f6-c7a3d78b2dbd.jpeg)
Acronyms should have every letter capitalized!

**Comment by maxgfr** [comment]
@62f ahaha not false, I might rename it : "interface de programmation d'application" 

It's more french
