### ISSUE TITLE
Nouveaux modèles licenciement à intégrer 

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3917]
**Description**
5 nouveaux modèles à intégrer :

- Titre à mettre : "Convocation à un entretien préalable au licenciement économique d'au moins 10 salariés pendant 30 jours"

[Entretien préalable au licenciement économique d'au moins 10 salariés sur 30 jours.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7397227/Entretien.prealable.au.licenciement.economique.d.au.moins.10.salaries.sur.30.jours.docx)

- Titre à mettre : "Lettre de licenciement économique avec entretien préalable - congé de reclassement"

[Lettre de licenciement économique avec entretien préalable - congé de reclassement.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7397236/Lettre.de.licenciement.economique.avec.entretien.prealable.-.conge.de.reclassement.docx)

- Titre à mettre : "Lettre de licenciement économique sans entretien préalable - congé de reclassement"

[Lettre de licenciement économique sans entretien préalable - congé de reclassement.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7397244/Lettre.de.licenciement.economique.sans.entretien.prealable.-.conge.de.reclassement.docx)

- Titre à mettre : "Rupture d'un commun accord - Congé de mobilité"

[Rupture d'un commun accord - Congé de mobilité.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7397254/Rupture.d.un.commun.accord.-.Conge.de.mobilite.docx)

- Titre à mettre : "Rupture d'un commun accord - Rupture conventionnelle collective"

[Rupture d'un commun accord - Rupture conventionnelle collective.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7397269/Rupture.d.un.commun.accord.-.Rupture.conventionnelle.collective.docx)

/!\ Dans chaque modèle, le passage situé avant la ligne en pointillé est à placer dans le "chapeau" de la page (= l'intro de la page) mais doit être enlever de l'aperçu du modèle et du modèle à télécharger

**Comment by maxgfr** [comment]
> L’employeur qui envisage le licenciement pour motif économique de 10 salariés et plus durant une période de 30 jours doit convoquer chaque salarié à un entretien préalable, si l’entreprise n’a pas mis en place un CSE (article L. 1233-38 du code du travail : «Lorsque l'employeur procède au licenciement pour motif économique d'au moins dix salariés dans une même période de trente jours et qu'il existe un comité social et économique dans l'entreprise, la procédure d'entretien préalable au licenciement ne s'applique pas ».). La convocation, envoyée par lettre recommandée avec accusé de réception ou remise en main propre contre signature, doit parvenir au salarié au moins 5 jours ouvrables avant l’entretien préalable.

[Entretien.prealable.au.licenciement.economique.d.au.moins.10.salaries.sur.30.jours.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7442515/Entretien.prealable.au.licenciement.economique.d.au.moins.10.salaries.sur.30.jours.docx)

> La lettre de licenciement comporte l'énoncé précis des motifs invoqués par l'employeur (article L. 1232-6 du code du travail). Elle doit être envoyée au salarié par lettre recommandée avec avis de réception, après les délais suivants : <ul> <li> Licenciement économique individuel : 7 jours ouvrables après la date prévue de l’entretien préalable (article L. 1233-15) ou 2 jours en cas de procédure collective ; </li> <li> Licenciement économique de 2 à 9 salariés : 7 jours ouvrables après la date prévue de l’entretien préalable (article L. 1233-15), ce délai est porté à quinze jours ouvrables si cela concerne un membre du personnel d'encadrement (article L. 1441-13) ou 2 jours en cas de procédure collective ; </li><li> Licenciement économique d’au moins 10 salariés pendant 30 jours, dans une entreprise de moins de 50 salariés, sans CSE : 30 jours calendaires après la notification du projet de licenciement à la DREETS (article L. 1233-39), y compris en cas de procédure collective ; </li><li> Licenciement économique d’au moins 10 salariés pendant 30 jours, dans une entreprise de 50 salariés ou plus, sans CSE : après la validation de l’accord collectif ou l’homologation du document unilatéral par la DREETS (article L. 1233-39), y compris en cas de procédure collective. </li></ul>


[Lettre.de.licenciement.economique.avec.entretien.prealable.-.conge.de.reclassement.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7442532/Lettre.de.licenciement.economique.avec.entretien.prealable.-.conge.de.reclassement.docx)


> La lettre de licenciement comporte l'énoncé précis des motifs invoqués par l'employeur (article L. 1232-6 du code du travail). Elle doit être envoyée au salarié par lettre recommandée avec avis de réception, après les délais suivants : <ul><li> Licenciement économique individuel : 7 jours ouvrables après la date prévue de l’entretien préalable (article L. 1233-15) ou 2 jours en cas de procédure collective ; </li><li> Licenciement économique de 2 à 9 salariés : 7 jours ouvrables après la date prévue de l’entretien préalable (article L. 1233-15), ce délai est porté à quinze jours ouvrables si cela concerne un membre du personnel d'encadrement (article L. 1441-13) ou 2 jours en cas de procédure collective ; </li><li> Licenciement économique d’au moins 10 salariés pendant 30 jours, dans une entreprise de moins de 50 salariés, sans CSE : 30 jours calendaires après la notification du projet de licenciement à la DREETS (article L. 1233-39), y compris en cas de procédure collective ; </li><li> Licenciement économique d’au moins 10 salariés pendant 30 jours, dans une entreprise de 50 salariés ou plus, sans CSE : après la validation de l’accord collectif ou l’homologation du document unilatéral par la DREETS (article L. 1233-39), y compris en cas de procédure collective. </li></ul>

[Lettre.de.licenciement.economique.sans.entretien.prealable.-.conge.de.reclassement.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7442549/Lettre.de.licenciement.economique.sans.entretien.prealable.-.conge.de.reclassement.docx)


> Dans le cadre de l’application d’un accord collectif de congé de mobilité, le salarié peut présenter sa candidature au départ dans les conditions prévues par cet accord. Si l’employeur accepte sa candidature, il peut signer avec le salarié une convention individuelle de rupture d’un commun accord qui précise les conditions de départ du salarié.


[Rupture.d.un.commun.accord.-.Conge.de.mobilite.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7442554/Rupture.d.un.commun.accord.-.Conge.de.mobilite.docx)

> Dans le cadre de l’application d’un accord collectif portant rupture conventionnelle collective, le salarié peut présenter sa candidature au départ dans les conditions prévues par cet accord. Si l’employeur accepte sa candidature, il signe avec le salarié une convention individuelle de rupture d’un commun accord qui précise les conditions de départ du salarié (article L. 1237-19-1 du code du travail).


[Rupture.d.un.commun.accord.-.Rupture.conventionnelle.collective.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7442558/Rupture.d.un.commun.accord.-.Rupture.conventionnelle.collective.docx)

**Comment by maxgfr** [comment]
Concernant `Rupture.d.un.commun.accord.-.Conge.de.mobilite.docx`, je ne vois aucune référence juridique, est-ce normal ?

**Comment by maxgfr** [comment]
NB: Il faudra mettre un parser d'html côté frontend pour utiliser les retours à la ligne pour les lettres de licenciement

**Comment by maxgfr** [comment]
TODO: mettre en place cdtn_id sur les modèles de documents et lancer hasura

**Comment by jrduscher** [comment]
# Entretien.prealable.au.licenciement.economique.d.au.moins.10.salaries.sur.30.jours.docx 

## Réf juridiques :  
 - [Article L.1233-38 du cde du travail ](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006901050)
# Lettre.de.licenciement.economique.avec.entretien.prealable.-.conge.de.reclassement.docx
## Réf juridiques : 
 - [article L. 1232-6 du code du travail](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000036762096/)
 - [article L. 1233-15 du code du travail](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000032344944)
 - [article L. 1233-39 du code du travail](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006901051/2008-05-01)
# Lettre.de.licenciement.economique.sans.entretien.prealable.-.conge.de.reclassement.docx
## Réf juridiques (les mêmes qu'au dessus):
 - [article L. 1232-6 du code du travail](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000036762096/)
 - [article L. 1233-15 du code du travail](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000032344944)
 - [article L. 1233-39 du code du travail](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006901051/2008-05-01)
# Rupture.d.un.commun.accord.-.Conge.de.mobilite.docx
## Réf juridiques :
-  [Article L.1237-18 du cde du travail ](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000036702808)
-  [Article L.1237-18-4 du cde du travail ](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000035623963)
-  [Article L.1237-18-5 du cde du travail ](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000036702967)
# Rupture.d.un.commun.accord.-.Rupture.conventionnelle.collective.docx
## Réf juridiques :
 - [Article L.1237-19-1 du cde du travail ](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000036762168)
 - [Article L.1237-19-2 du cde du travail ](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000036762166)

**Comment by maxgfr** [comment]
Merci @jrduscher :)

**Comment by maxgfr** [comment]
> TODO: mettre en place cdtn_id sur les modèles de documents et lancer hasura

Done

**Comment by maxgfr** [comment]
> NB: Il faudra mettre un parser d'html côté frontend pour utiliser les retours à la ligne pour les lettres de licenciement

Normalement c'est ok

**Comment by m-maillot** [comment]
* "Convocation à un entretien préalable au licenciement économique d'au moins 10 salariés pendant 30 jours" -> OK
 * "Lettre de licenciement économique avec entretien préalable - congé de reclassement" -> OK
 * "Lettre de licenciement économique sans entretien préalable - congé de reclassement" -> OK
 * "Rupture d'un commun accord - Congé de mobilité" -> OK
 * "Rupture d'un commun accord - Rupture conventionnelle collective" -> Renommage du fichier en local - mise à jour des données - OK

**Comment by CaptainConan** [comment]
https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/modeles-de-courriers/lettre-de-licenciement-economique-avec-entretien-prealable-conge-de-reclassement?q=Lettre%20de%20licenciement%20%C3%A9conomique%20avec%20entretien%20pr%C3%A9alable
Sur l'aperçu , la ligne avec la ville devrait être ferrée à droite.
![CDTN modele corr 1](https://user-images.githubusercontent.com/53531631/141980529-5406ffa5-7ee5-4c7d-82f2-766e59b69c20.png)
Sur l'aperçu, il manque un trait d'union (modèle corrigée et reuploaded dans l'admin.
![CDTN modele corr 2](https://user-images.githubusercontent.com/53531631/141980670-472df3a8-73a6-4905-a1c7-e7c3d19f5f17.png)

https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/modeles-de-courriers/lettre-de-licenciement-economique-sans-entretien-prealable-conge-de-reclassement?q=Lettre%20de%20licenciement%20%C3%A9conomique%20sans%20entretien%20pr%C3%A9alable
Sur l'aperçu, il manque un trait d'union (modèle corrigée et reuploaded dans l'admin.
![CDTN modele corr 3](https://user-images.githubusercontent.com/53531631/141995797-c656caf0-959d-4f57-ab95-a898d319bb61.png)

**Comment by romain-b13** [comment]
[Entretien.prealable.au.licenciement.economique.d.au.moins.10.salaries.sur.30.jours.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7579693/Entretien.prealable.au.licenciement.economique.d.au.moins.10.salaries.sur.30.jours.docx)
[Lettre.de.licenciement.economique.avec.entretien.prealable.-.conge.de.reclassement.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7579695/Lettre.de.licenciement.economique.avec.entretien.prealable.-.conge.de.reclassement.docx)
[Lettre.de.licenciement.economique.sans.entretien.prealable.-.conge.de.reclassement.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7579697/Lettre.de.licenciement.economique.sans.entretien.prealable.-.conge.de.reclassement.docx)

**Comment by romain-b13** [comment]
Voici la dernière version des modèles avec les styles :
[Lettre-de-licenciement-economique-avec-entretien-prealable-conge-de-reclassement.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7590059/Lettre-de-licenciement-economique-avec-entretien-prealable-conge-de-reclassement.docx)
[Lettre-de-licenciement-economique-sans-entretien-prealable-conge-de-reclassement.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7590060/Lettre-de-licenciement-economique-sans-entretien-prealable-conge-de-reclassement.docx)
[Rupture-d-un-commun-accord-conge-de-mobilite.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7590061/Rupture-d-un-commun-accord-conge-de-mobilite.docx)
[Rupture-d-un-commun-accord-rupture-conventionnelle-collective.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7590062/Rupture-d-un-commun-accord-rupture-conventionnelle-collective.docx)
[Entretien-prealable-au-licenciement-economique-d-au-moins-10-salaries-sur-30-jours.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7590063/Entretien-prealable-au-licenciement-economique-d-au-moins-10-salaries-sur-30-jours.docx)

**Comment by romain-b13** [comment]
Voici le modèle dont le H1 a été retiré : 

[affichage_lutte_contre_harcelement_sexuel.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7594324/affichage_lutte_contre_harcelement_sexuel.docx)

**Comment by romain-b13** [comment]
Nouvelle version des modèles :
[Lettre-de-licenciement-economique-avec-entretien-prealable-conge-de-reclassement.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7604809/Lettre-de-licenciement-economique-avec-entretien-prealable-conge-de-reclassement.docx)
[Lettre-de-licenciement-economique-sans-entretien-prealable-conge-de-reclassement.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7604810/Lettre-de-licenciement-economique-sans-entretien-prealable-conge-de-reclassement.docx)
[Rupture-d-un-commun-accord-conge-de-mobilite.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7604811/Rupture-d-un-commun-accord-conge-de-mobilite.docx)
[Rupture-d-un-commun-accord-rupture-conventionnelle-collective.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7604812/Rupture-d-un-commun-accord-rupture-conventionnelle-collective.docx)
[Entretien-prealable-au-licenciement-economique-d-au-moins-10-salaries-sur-30-jours.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7604813/Entretien-prealable-au-licenciement-economique-d-au-moins-10-salaries-sur-30-jours.docx)

**Comment by carolineBda** [comment]
@maxgfr tu pourra les mettre à jour ?

**Comment by maxgfr** [comment]
@carolineBda yes

**Comment by romain-b13** [comment]
Nouvelle version des modèles :
[Lettre-de-licenciement-economique-sans-entretien-prealable-conge-de-reclassement.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7624245/Lettre-de-licenciement-economique-sans-entretien-prealable-conge-de-reclassement.docx)
[Rupture-d-un-commun-accord-conge-de-mobilite.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7624246/Rupture-d-un-commun-accord-conge-de-mobilite.docx)
[Rupture-d-un-commun-accord-rupture-conventionnelle-collective.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7624248/Rupture-d-un-commun-accord-rupture-conventionnelle-collective.docx)
[Entretien-prealable-au-licenciement-economique-d-au-moins-10-salaries-sur-30-jours.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7624250/Entretien-prealable-au-licenciement-economique-d-au-moins-10-salaries-sur-30-jours.docx)
[Lettre-de-licenciement-economique-avec-entretien-prealable-conge-de-reclassement.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/7624251/Lettre-de-licenciement-economique-avec-entretien-prealable-conge-de-reclassement.docx)

**Comment by carolineBda** [comment]
La PR n'a toujours pas été mergé, donc je remet cette carte en "doing" : https://github.com/SocialGouv/cdtn-docx-to-html/pull/4
Attention : avant de la merger il faut réimporter une dernière fois les doc pour que ces derniers n'est plus la balise <style> qui a été déplacé dans le front.
