### ISSUE TITLE
Derniers retours outil préavis de retraite

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3972]
- [x] On ne peut pas sélectionner de catégorie pro dans la liste déroulante

- Une fois que la catégorie pro sera corrigée, vérifier que le bouton d'aide à bien été ajouté à tous les types de questions "similaires" (différents en fonction des CC) : 
Quel est le niveau du salarié ? => ex de CCs concernées : 1351, 1404, 1517, 1518, 1560, 1564
Quel est le groupe du salarié ? => ex de CC concernées : 0016, 0044
Quel est l'échelon du salarié ? => ex de CC concernée : 1090
Quel est la position du salarié ? => ex de CC concernée : 650
Quel est le coefficient du salarié => ex de CC concernées : 29, 44
Quel est la classe du salarié ? => ex de CC concernée : 1672

- [Romain] Une fois que la sélection de la catégorie pro sera corrigée : 
Vérifier que la phrase est bien simplifiée pour le cas : ancienneté < 6 mois et CC prévoit quelque chose (ex de cc concernée : ligne 492 du data-simulateur)
- [Romain] Une fois que la sélection de la catégorie pro sera corrigée : 
Vérifier que la phrase de conclusion dans "résultat décrypté" quand le résultat conventionnel et légal est le même a été retirée
- [Romain] Vérifier que la phrase est bien simplifiée pour les CC non étendues (vérifier avec la 2420 lorsqu'elle sera intégrée)

- [x] Le picto sur la durée nécessaire doit être enlevé des étapes autres que l'intro
- [x] Changer le picto calendrier (mettre le nouveau qui est plus fin)
- [x] Pour le picto annonçant la durée de la simulation : "5 min" doit être de la même couleur que le picto (en bleu et non en noir)
- [x] Il n'y que l'étape information pour laquelle on bloque le passage à l'étape suivante s'il n'y a pas de réponse à la question (les autres étapes je peux les passer même si je ne réponds pas aux questions)
- [x] Est-ce que les CCs prochainement traitées ont été définies ? car quand j'essaie la 2264 par exemple on me dit que c'est une CC "non traitée" alors qu'elle devrait être considérée comme "prochainement traitée"
- [x] A l'étape "informations" il faut cliquer 2 fois pour cocher un des boutons radio
- [x] Quand on revient sur les étapes précédentes après avoir répondu aux différentes questions les boutons radio ne sont plus cochés, il faut qu'ils restent cochés
- [x] Modifier le wording de l'intro :    
           - Remplacer "Ce simulateur est un outil qui permet de calculer la durée de préavis à respecter en cas de départ ou de mise à la retraite, telle qu'elle est prévue par la loi et la convention collective applicable." **PAR => "Ce simulateur vous permet de calculer la durée de préavis à respecter en cas de départ ou de mise à la retraite, telle qu'elle est prévue par la loi et la convention collective applicable."**
          - Remplacer "Afin de réaliser cette simulation, vous aurez besoin d’informations concernant la situation du salarié, comme [...]" **PAR => "Vous aurez besoin d’informations concernant la situation du salarié, comme [...]"**

- [x] Dans l'étape "ancienneté" modifier le contenu de la parenthèse dans la question "Le salarié a-t-il plus de 2 ans d'ancienneté dans l'entreprise (à partir de 2 ans + 1 jour) ? (obligatoire)" => mettre uniquement dans la parenthèse "2 ans + 1 jour", ce qui donnerait "Le salarié a-t-il plus de 2 ans d'ancienneté dans l'entreprise (2 ans + 1 jour) ? (obligatoire)"
- [x] Dans les messages d'aide qui ont été ajoutés (questions catégorie pro, échelon, groupe, niveau, position, coefficient, classe), dans le message d'aide qui s'affiche au clic sur le bouton, **"bulletin de salaire" doit être en gras** -> cf https://github.com/SocialGouv/code-du-travail-numerique/issues/3973

- [x] Il faudrait mettre un astérisque au niveau du résultat effectivement doublé quand le travailleur est en situation de handicap car on se sait pas à quoi renvoie l'astérisque "Ce résultat tient compte de la majoration pour les travailleurs handicapés"

![image](https://user-images.githubusercontent.com/84397271/140291998-e65dbb58-2918-4894-bc55-b290dade31c5.png)

**Comment by m-maillot** [comment]
J'ai fait une passe sur les IDCC avec le fichier excel. Voici le status:

| IDCC | status | Issue |
| ----- | ----- | ----- |
| 16 | ok |  |
| 29 | ok |  |
| 44 | ok |  |
| 54 | ok |  |
| 86 | à venir | #3532 |
| 176 | ok |  |
| 275 | ok |  |
| 292 | ok |  |
| 413 | ok |  |
| 573 | ok |  |
| 650 | ok |  |
| 675 | ok |  |
| 787 | ok |  |
| 843 | ok |  |
| 1043 | ok |  |
| 1090 | ok |  |
| 1147 | ok |  |
| 1266 | ok |  |
| 1351 | ok |  |
| 1404 | ok |  |
| 1480 | ok |  |
| 1483 | ok |  |
| 1486 | ok |  |
| 1501 | ok |  |
| 1505 | ok |  |
| 1516 | à venir | #3538 |
| 1517 | à venir | #3537 |
| 1518 | ok |  |
| 1527 | ok |  |
| 1596 | ok |  |
| 1597 | ok |  |
| 1606 | à venir | #3538 |
| 1672 | à venir | #3537 |
| 1702 | ok |  |
| 1740 | à venir | #3537 |
| 1979 | ok |  |
| 1996 | KO (indiqué comme non traité) | #3537 |
| 2098 | ok |  |
| 2111 | à venir | #3868 |
| 2120 | ok |  |
| 2148 | à venir | #3532 |
| 2216 | ok |  |
| 2264 | ok |  |
| 2395 | à venir | #3868 |
| 2420 | à venir | #3538 |
| 2511 | à venir | #3538 |
| 2596 | à venir | #3532 |
| 2609 | ok |  |
| 2614 | à venir | #3538 |
| 2941 | à venir | #3532 |
| 3043 | ok |  |
| 3127 | à venir | #3537 |
| 3239 | KO (indiqué comme non traité) | #3868 |

Il y a 2 IDCC dont l'information n'est pas correcte actuellement (3239 et 1996). Donc à corriger. Pour les autres, on a tout dans les issues restantes pour le simulateur.

**Comment by romain-b13** [comment]
Pour l'instant un seul commentaire (je termine les tests demain) :
- Le "5 min" du picto n'est pas du même bleu que celui du picto

**Comment by romain-b13** [comment]
@m-maillot pourquoi on ne traite pas 1996 ? => elle a bien été traitée dans l'issue

**Comment by maxgfr** [comment]
@m-maillot @romain-b13 Elle est traitée ici : https://github.com/SocialGouv/code-du-travail-numerique/pull/4003

**Comment by m-maillot** [comment]
Elle est notée comme KO (sur la preprod) et je l'ai corrigé dans la PR en fait :)
