### ISSUE TITLE
Bug aléatoire "une erreur est survenue"

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#3977]
**Description**
En réalisant une simulation, au moment de passer à une étape suivante je suis tombé sur : 

![image](https://user-images.githubusercontent.com/84397271/140366525-6bdf071d-628c-4ec0-8ffa-01d02e79940e.png)

Je n'arrive pas à reproduire le bug

**Comment by romain-b13** [comment]
J'ai eu le bug plusieurs fois en preprod et pas uniquement dans les simulateurs : 
- Je l'ai eu en cliquant sur le modèle "Rupture du contrat en période d’essai à l’initiative du salarié"
- Dans la boîte à outils au moment où j'ai cliqué sur la carte "préavis de démission"

**Comment by maxgfr** [comment]
Il me semble que ce problème a été corrigé via cette [PR](https://github.com/SocialGouv/code-du-travail-numerique/commit/05342e3c44eb088816d464a2940cab9aa9569ec1#diff-a6b86664e2464ef3790f3d2546347a8e905b44ad2457b355568305e3539177f9R118) qui a été merge et appliquée en production

**Comment by maxgfr** [comment]
Update, on a reproduit le bug avec Florent et Martial, normalement ça a été fix

**Comment by romain-b13** [comment]
je peux clôturer cette issue ?

**Comment by maxgfr** [comment]
Pour moi, oui, à confirmer avec @m-maillot @carolineBda

**Comment by carolineBda** [comment]
Non non ce bug est toujours présent en prod il faut qu'on le corrige. Pour le reproduire :
 - Effectuer une simulation sur /outils/indemnite-licenciement 
 - aller jusqu'au resultat
 - revenir en arriere et modifier des infos
 - quand on arrive à nouveau au résultat, on a l'erreure.
