### ISSUE TITLE
CC fusionné

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#3995]
**Description**
Lorsqu'une contribution est dépubliée pour modification, ou lorsque le numéro IDCC change, les pages des contributions accessibles depuis les moteurs de recherche, (pour lesquelles les urls concatènent l'idcc et la question) aboutissent à des erreurs 404.

Nous savons par ailleurs que des changement sont intervenus impliquant ou qui vont impliquer prochainement des erreurs 404.
En effet ,
- la CC portant le n°IDCC (1375) porte désormais le numéro (3209
- la CC portant le n°IDCC (1809) porte désormais le numéro (3231)- 
- les CC portant les n°IDCC (2111) et (2395) vont fusionner et porter désormais le numéro (3239)

Les contributions rattachées à l'ensemble de ces 4 CC seront dépubliées, et vont générer environs 120 erreurs 404.
Par ailleurs, ces anciennes IDCC pourraient être encore recherchées pendant un long moment par nos utilisateurs avec leurs noms ou IDCC d'origine.

**Reproduction**
Etapes à suivre pour reproduire le bug

1. Aller à https://code.travail.gouv.fr/contribution/1809-quelle-est-la-duree-de-preavis-en-cas-de-licenciement?q=dur%C3%A9e ou à https://code.travail.gouv.fr/contribution/1375-quelle-est-la-duree-de-preavis-en-cas-de-licenciement?q=dur%C3%A9e

**Comportement attendu**

1) Si le numéro IDCC ( ou également l'intitulé de la CC) a changé, il faudrait que l'usager se voit redirigé vers la réponse de la nouvelle CC 
2) Lorsqu'une contribution isolée est dépubliée ( ex: dépublication dans le cadre de la veille...), il ne devrait pas y avoir d'erreur 404, mais l'usager devrait être orienté sur la page de sa convention collective par exemple.

**Comment by m-maillot** [comment]
@romain-b13 a voir ensemble à ton retour. Ca peut demander un peu de boulot.

**Comment by jrduscher** [comment]
### Autre cas de figure lié:

La recherche d'une CC par établissement ou entreprise : Les déclarations de CC par l'employeur risquent de comporter d'anciennes IDCC. Un renvoi est également à prévoir dans ce cas là.
