### ISSUE TITLE
Module de recherche sur les pages CC :  déceptif pour les cc de la métallurgie

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#3996]
**Description**
Les pages conventions collectives du CDTN proposent un module de recherche du ou des textes conventionnelles sur Legifrance.

![image](https://user-images.githubusercontent.com/37538697/140967828-73487f2a-4680-4b46-93ba-49347f1eabf4.png)

Les convention collectives locales  de la métallurgie ne sont pas publiées sur Legifrance.
Le CDTN propose des pages CC pour ces conventions collectives sur lesquelles se retrouvent des contributions par exemple.
LE module de recherche sur Legifrance est donc aujourd'hui aussi proposé pour ces conventions collectives, alors qu'elles n'y sont pas publiées.

**Reproduction**
https://code.travail.gouv.fr/convention-collective/822-convention-collective-departementale-applicable-aux-mensuels-de-la-metallurg
**Comportement attendu**
Le module de recherche ne devrait pas être proposé pour ces conventions locales de la métallurgie

**Comment by m-maillot** [comment]
A voir la complexité :
 * En dur dans le frontend
 * Checkbox sur l'admin pour activer ou non le module de recherche
 * Détecté si la CC n'est pas dispo sur legifrance (ingester).
