### ISSUE TITLE
liste des services de renseignement DIRECCTE

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#4]
Afficher contacts en fonction geoloc user

**Comment by jrduscher** [comment]
/!\ certains liens renvoient vers l'UC ou la DIRECCTe, une nouvelle passe de vérif  plus précise s'impose.

dept | lien | check avril 2019
-- | --
Ain | http://auvergne-rhone-alpes.direccte.gouv.fr/Vos-interlocuteurs-17741|ddz
Aisne | http://hauts-de-france.direccte.gouv.fr/Nos-coordonnees-et-acces
Allier | http://auvergne-rhone-alpes.direccte.gouv.fr/Vos-interlocuteurs-17742
alpes Maritime | http://paca.direccte.gouv.fr/Alpes-Maritimes |  
Alpes-de-Haute-Provence | http://paca.direccte.gouv.fr/Alpes-de-Haute-Provence
Ardèche | http://auvergne-rhone-alpes.direccte.gouv.fr/Vos-interlocuteurs-17743
Ardennes | http://grand-est.direccte.gouv.fr/Inspection-du-travail-4982
Ariège | http://occitanie.direccte.gouv.fr/Renseignements-en-droit-du-travail-en-Direccte-Occitanie
Aube | http://grand-est.direccte.gouv.fr/Inspection-du-travail-4981
Aude | http://occitanie.direccte.gouv.fr/Renseignements-en-droit-du-travail-en-Direccte-Occitanie
Aveyron | http://occitanie.direccte.gouv.fr/Renseignements-en-droit-du-travail-en-Direccte-Occitanie
Bas Rhin | http://grand-est.direccte.gouv.fr/Inspection-du-travail-4974
Bouches du Rhone | http://paca.direccte.gouv.fr/Renseignements-sur-la-legislation-du-travail
Calvados | http://normandie.direccte.gouv.fr/Contacter-l-inspection-du-travail
Cantal | http://auvergne-rhone-alpes.direccte.gouv.fr/Vos-interlocuteurs-17744
Charente | Charente |   |   |   |  
Charente-Maritime | Charente-Maritime |   |   |   |  
Cher | http://centre-val-de-loire.direccte.gouv.fr/Cher |  
Corrèze | Corrèze |   |   |   |  
Corse du Sud | http://corse.direccte.gouv.fr/Contacter-la-Direccte |  
Côte d'Armor | http://bretagne.direccte.gouv.fr/Le-Service-Renseignement-du-Public-2949
Côte-d'Or | http://bourgogne-franche-comte.direccte.gouv.fr/sites/bourgogne-franche-comte.direccte.gouv.fr/IMG/xlsx/copie_de_coordonnees_des_uc_bfc-1.xlsx
Creuse | Creuse |   |   |   |  
Deux-sèvres | Deux-sèvres |   |   |   |  
Dordogne | Dordogne |   |   |   |  
Doubs | http://bourgogne-franche-comte.direccte.gouv.fr/sites/bourgogne-franche-comte.direccte.gouv.fr/IMG/xlsx/copie_de_coordonnees_des_uc_bfc-1.xlsx
Drôme | http://auvergne-rhone-alpes.direccte.gouv.fr/Vos-interlocuteurs-17745
Essonne | http://idf.direccte.gouv.fr/Annuaire-de-l-inspection-du-travail-en-Ile-de-France
Eure | http://normandie.direccte.gouv.fr/Contacter-l-inspection-du-travail
Eure-et-Loire | http://centre-val-de-loire.direccte.gouv.fr/Eure-et-Loir
finistère | http://bretagne.direccte.gouv.fr/Les-services-des-renseignements-au-public
Gard (30) | http://occitanie.direccte.gouv.fr/Renseignements-en-droit-du-travail-en-Direccte-Occitanie
Gers (32) | http://occitanie.direccte.gouv.fr/Renseignements-en-droit-du-travail-en-Direccte-Occitanie
Gironde | Gironde |   |   |   |  
guadeloupe | http://guadeloupe.dieccte.gouv.fr/nos-adresses |  
Guyane | http://guyane.dieccte.gouv.fr/Nos-adresses |  
Haute Corse | http://corse.direccte.gouv.fr/Contacter-la-Direccte |  
Haute Marne (52) | http://grand-est.direccte.gouv.fr/Inspection-du-travail-4980
Haute-Garonne (31) | http://occitanie.direccte.gouv.fr/Renseignements-en-droit-du-travail-en-Direccte-Occitanie
Haute-Loire | http://auvergne-rhone-alpes.direccte.gouv.fr/Vos-interlocuteurs-17748
Hautes Alpes | http://paca.direccte.gouv.fr/Hautes-Alpes |  
Haute-Saône (70) | http://bourgogne-franche-comte.direccte.gouv.fr/sites/bourgogne-franche-comte.direccte.gouv.fr/IMG/xlsx/copie_de_coordonnees_des_uc_bfc-1.xlsx
Haute-Savoie | http://auvergne-rhone-alpes.direccte.gouv.fr/Vos-interlocuteurs-17752
Hautes-Pyrénées (65) | http://occitanie.direccte.gouv.fr/Renseignements-en-droit-du-travail-en-Direccte-Occitanie
Haute-Vienne | Haute-Vienne
Haut-Rin(68) | http://grand-est.direccte.gouv.fr/Inspection-du-travail-4975
Hauts-de-Seine (92) | http://idf.direccte.gouv.fr/Annuaire-de-l-inspection-du-travail-en-Ile-de-France
Hérault (34) | http://occitanie.direccte.gouv.fr/Renseignements-en-droit-du-travail-en-Direccte-Occitanie
Ille-et-Vilaine (35) | http://bretagne.direccte.gouv.fr/Renseignements-au-public
Indre | http://centre-val-de-loire.direccte.gouv.fr/Indre-4954
Indre-et-Loire | http://centre-val-de-loire.direccte.gouv.fr/Indre-et-Loire
Isère | http://auvergne-rhone-alpes.direccte.gouv.fr/Vos-interlocuteurs-17746
Jura (39) | http://bourgogne-franche-comte.direccte.gouv.fr/sites/bourgogne-franche-comte.direccte.gouv.fr/IMG/xlsx/copie_de_coordonnees_des_uc_bfc-1.xlsx
La Martinique | http://martinique.dieccte.gouv.fr/sites/martinique.dieccte.gouv.fr/IMG/pdf/sve_-_contacts_et_demarches.pdf
La Réunion | http://reunion.dieccte.gouv.fr/Nous-contacter,8384
Landes | Landes |   |   |   |  
Loire | http://auvergne-rhone-alpes.direccte.gouv.fr/Vos-interlocuteurs-17747
Loire-Atlantique | http://pays-de-la-loire.direccte.gouv.fr/Acces-au-droit-du-travail-la-Direccte-vous-renseigne
Loiret | http://centre-val-de-loire.direccte.gouv.fr/L-application-du-droit-du-travail-17737
Loir-et-Cher | http://centre-val-de-loire.direccte.gouv.fr/Loir-et-Cher
Lot (46) | http://occitanie.direccte.gouv.fr/Renseignements-en-droit-du-travail-en-Direccte-Occitanie
Lot-et-Garonne | Lot-et-Garonne |   |   |   |  
Lozère (48) | http://occitanie.direccte.gouv.fr/Renseignements-en-droit-du-travail-en-Direccte-Occitanie
Maine et Loire | http://pays-de-la-loire.direccte.gouv.fr/Acces-au-droit-du-travail-la-Direccte-vous-renseigne
Manche | http://normandie.direccte.gouv.fr/Contacter-l-inspection-du-travail
Marne (51) | http://grand-est.direccte.gouv.fr/Inspection-du-travail-4978
Mayenne (53) | http://pays-de-la-loire.direccte.gouv.fr/Acces-au-droit-du-travail-la-Direccte-vous-renseigne
Mayotte | http://mayotte.dieccte.gouv.fr/ |   |  
Meurthe-et-Moselle (54) | http://grand-est.direccte.gouv.fr/Inspection-du-travail-4977
Meuse (55) | http://grand-est.direccte.gouv.fr/Inspection-du-travail-4978
Morbihan (56) | http://bretagne.direccte.gouv.fr/Renseignement-au-public-3009
Moselle (54) | http://grand-est.direccte.gouv.fr/Inspection-du-travail-4976
Nièvre (58) | http://bourgogne-franche-comte.direccte.gouv.fr/sites/bourgogne-franche-comte.direccte.gouv.fr/IMG/xlsx/copie_de_coordonnees_des_uc_bfc-1.xlsx
Nord (59) | http://hauts-de-france.direccte.gouv.fr/Nos-coordonnees-et-acces
Oise (60) | http://hauts-de-france.direccte.gouv.fr/Nos-coordonnees-et-acces
Orne | http://normandie.direccte.gouv.fr/Contacter-l-inspection-du-travail
Paris (75) | http://idf.direccte.gouv.fr/Annuaire-de-l-inspection-du-travail-en-Ile-de-France
Pas-de-calais (62) | http://hauts-de-france.direccte.gouv.fr/Nos-coordonnees-et-acces
Puy-De-Dôme | http://auvergne-rhone-alpes.direccte.gouv.fr/Vos-interlocuteurs-17749
Pyrénées-Atlantiques | Pyrénées-Atlantiques |   |   |   |  
Pyrénées-Orientales (66) | http://occitanie.direccte.gouv.fr/Renseignements-en-droit-du-travail-en-Direccte-Occitanie
Rhône | http://auvergne-rhone-alpes.direccte.gouv.fr/Vos-interlocuteurs-17750
Saône-et-Loire (71) | http://bourgogne-franche-comte.direccte.gouv.fr/sites/bourgogne-franche-comte.direccte.gouv.fr/IMG/xlsx/copie_de_coordonnees_des_uc_bfc-1.xlsx
Sarthe | http://pays-de-la-loire.direccte.gouv.fr/Acces-au-droit-du-travail-la-Direccte-vous-renseigne
Savoie | http://auvergne-rhone-alpes.direccte.gouv.fr/Vos-interlocuteurs-17751
Seine Maritime | http://normandie.direccte.gouv.fr/Contacter-l-inspection-du-travail
Seine-et-Marne (77) | http://idf.direccte.gouv.fr/Annuaire-de-l-inspection-du-travail-en-Ile-de-France
Seine-Saint-Denis (93) | http://idf.direccte.gouv.fr/Annuaire-de-l-inspection-du-travail-en-Ile-de-France
somme(80) | http://hauts-de-france.direccte.gouv.fr/Nos-coordonnees-et-acces
Tarn | http://occitanie.direccte.gouv.fr/Renseignements-en-droit-du-travail-en-Direccte-Occitanie
Tarn-et-Garonne | http://occitanie.direccte.gouv.fr/Renseignements-en-droit-du-travail-en-Direccte-Occitanie
Territoire de Belfort (90) | http://bourgogne-franche-comte.direccte.gouv.fr/sites/bourgogne-franche-comte.direccte.gouv.fr/IMG/xlsx/copie_de_coordonnees_des_uc_bfc-1.xlsx
Val-d’Oise (95) | http://idf.direccte.gouv.fr/Annuaire-de-l-inspection-du-travail-en-Ile-de-France
Val-de-Marne (94) | http://idf.direccte.gouv.fr/Annuaire-de-l-inspection-du-travail-en-Ile-de-France
Var | http://paca.direccte.gouv.fr/Renseignements-sur-la-reglementation-du-travail-17723
Vaucluse | http://paca.direccte.gouv.fr/Les-numeros-utiles-de-l-Unite-departementale-du-Vaucluse
Vendée | http://pays-de-la-loire.direccte.gouv.fr/Acces-au-droit-du-travail-la-Direccte-vous-renseigne
Vienne | Vienne |   |   |   |  
Vosges (88) | http://grand-est.direccte.gouv.fr/Inspection-du-travail-4979
Yonne (89) | http://bourgogne-franche-comte.direccte.gouv.fr/sites/bourgogne-franche-comte.direccte.gouv.fr/IMG/xlsx/copie_de_coordonnees_des_uc_bfc-1.xlsx
Yvelines (78). | http://idf.direccte.gouv.fr/Annuaire-de-l-inspection-du-travail-en-Ile-de-France

**Comment by revolunet** [comment]
source à éditer : https://github.com/SocialGouv/code-du-travail-explorer/blob/master/src/data/services-de-renseignement.json
