### ISSUE TITLE
Licenciement sans CRS: baremisation de l'indemnisation

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#40]
Principe : 
Le licenciement jugé sans cause réelle et sérieuse entraîne le droit à la réintégration du salarié dans l'entreprise. Mais en cas de refus par le salarié/l'employeur, le juge décidera du versement par l'employeur d'une indemnité au salarié.
- Le montant de cette indemnité est décidée par le juge, dans les limites fixées par le texte. Elle est modulée, en fonction de **l'ancienneté des salariés**, et de **l'effectif de l'entreprise**

 **L'usager peut donc être en mesure de connaitre sur ces critères une estimation de son indemnité**

Ancienneté du salarié dans l'entreprise(en années complètes) | Indemnité minimale(en mois de salaire brut) | Indemnité maximale(en mois de salaire brut)
-- | -- | --
0 | Sans objet | 1
1 | 1 | 2
2 | 3 | 3,5
3 | 3 | 4
4 | 3 | 5
5 | 3 | 6
6 | 3 | 7
7 | 3 | 8
8 | 3 | 8
9 | 3 | 9
10 | 3 | 10
11 | 3 | 10,5
12 | 3 | 11
13 | 3 | 11,5
14 | 3 | 12
15 | 3 | 13
16 | 3 | 13,5
17 | 3 | 14
18 | 3 | 14,5
19 | 3 | 15
20 | 3 | 15,5
21 | 3 | 16
22 | 3 | 16,5
23 | 3 | 17
24 | 3 | 17,5
25 | 3 | 18
26 | 3 | 18,5
27 | 3 | 19
28 | 3 | 19,5
29 | 3 | 20
30 et au-delà | 3 | 20

Tableau spé: moins de onze       ######salriés

Ancienneté du salarié dans l'entreprise(en années complètes) | Indemnité minimale(en mois de salaire brut)
-- | --
0 | Sans objet
1 | 0,5
2 | 0,5
3 | 1
4 | 1
5 | 1,5
6 | 1,5
7 | 2
8 | 2
9 | 2,5
10 | 2,5

**Comment by revolunet** [comment]
-> https://www.service-public.fr/particuliers/vosdroits/F1848

**Comment by ClementChapalain** [comment]
D'après ce que j'ai vu, la distinction +/- de 11 salariés n'est pas prise en compte dans l'outil actuel, du coup cette tâche est bien toujours d'actualité ?

**Comment by ClementChapalain** [comment]
Après discussion avec @jrduscher en fait ici on parle de la barémisation des indemnités prud'homales en cas de licenciement sans cause réelle ni sérieuse (CRS) prononcée par un juge. Donc pas la même chose que notre outil actuel de calcul d'indemnité de licenciement. Je déplace le tableau avec les infos ici :
https://github.com/SocialGouv/code-du-travail-numerique/wiki/%5BDroit-du-travail%5D
