### ISSUE TITLE
Mettre la durée nécessaire pour réaliser une simulation sous forme de picto dans tous les outils

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4014]
**Fonctionnalité**
Comme ce qui a été fait dans le simulateur du préavis de retraite, proposer le temps nécessaire en haut à droite avec le picto.
Il faudra en même temps retirer les phrases de l'intro telles que : 
"Cette simulation nécessite entre 5 et 10 minutes." / "Prévoyez une à deux minutes pour cette simulation" etc

**Résultat attendu**
![image](https://user-images.githubusercontent.com/84397271/142025755-ed997b16-d573-41c2-ab1d-fa6518211d8c.png)

Il faudra respecter la formulation qui se trouve dans le texte de l'intro. Par exemple pour l'outil "indemnités de licenciement" dans l'intro il est écrit "Cette simulation nécessite entre 5 et 10 minutes." => du coup dans le Picto on écrira "5 à 10 min"

**Comment by carolineBda** [comment]
@romain-b13 du coup on enlève la phrase "Cette simulation nécessite entre 5 et 10 minutes" ?

**Comment by carolineBda** [comment]
On pourrait supprimer la phrase "Cliquez sur commencer pour démarrer la simulation." qui n'amène pas grand chose non ?

**Comment by romain-b13** [comment]
> On pourrait supprimer la phrase "Cliquez sur commencer pour démarrer la simulation." qui n'amène pas grand chose non ?

Oui je suis d'accord
