### ISSUE TITLE
Ajouter bouton help sur les questions de catégorie/groupe/échelon dans les simulateurs + event 

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4015]
**Fonctionnalité**
Pour les outils : 
Préavis de démission (étape "informations")
Préavis de licenciement (étape "informations complémentaires")
Heures pour recherche d’emploi (étape "informations")

Comme pour le préavis de retraite, ajouter un bouton d'aide à tous les types de questions "similaires" (différents en fonction des CC) avec le message "L'X du salarié est habituellement mentionnée sur le **bulletin de salaire**."
Quel est le niveau du salarié ? 
Quel est le groupe du salarié ? 
Quel est l'échelon du salarié ? 
Quel est la position du salarié ? 
Quel est le coefficient du salarié ?
Quel est la classe du salarié ? 

Ajouter aussi le bouton pour la question sur l'ancienneté (étape "informations complémentaires")

Ajouter également les events sur le bouton help comme ce qui a été fait sur le préavis de retraite

**Comment by maxgfr** [comment]
@romain-b13 Il faudra binder de nouveaux events aussi, à ces questions qui pour certaines ne sont pas trackées

**Comment by romain-b13** [comment]
Mettre les mêmes event que ceux qui ont été mis sur le preavis de retraite pour ces questions

**Comment by maxgfr** [comment]
Quid des autres questions du simulateurs comme celle-ci :

```json
    {
      "name": "âge",
      "question": "Quel est l'âge du salarié ?"
    },
    {
      "name": "agents payés à l'heure",
      "question": "L'agent est-il payé à l'heure ?"
    },
    {
      "name": "durée d'accueil de l'enfant",
      "question": "Quelle est la durée d'accueil de l'enfant ?"
    },
    {
      "name": "catégorie professionnelle",
      "question": "Quelle est la catégorie professionnelle du salarié ?"
    },
    {
      "name": "initiative de la rupture de la période d'essai",
      "question": "Qui a pris l'initiative de rompre la période d'essai ?"
    },
    {
      "name": "personnel de conduite",
      "question": "Le salarié fait-il partie des personnels de conduite du transport de voyageurs ?"
    },
    {
      "name": "motif de rupture",
      "question": "Quel est le motif de rupture du contrat de travail ?"
    },
    {
      "name": "durée du travail",
      "question": "Quelle est la durée du travail du salarié ?"
    },
    {
      "name": "durée du préavis",
      "question": "Quelle est la durée du préavis du salarié ?"
    },
    {
      "name": "délai de prévenance",
      "question": "Quelle est la durée du préavis (aussi appelé délai de prévenance) ?"
    },
    {
      "name": "type de rupture",
      "question": "Pour quelle raison le contrat de travail a-t-il été rompu ?"
    },
    {
      "name": "conclusion contrat travail",
      "question": "Quelle est la date d'entrée du salarié dans l'entreprise?"
    },
    {
      "name": "logement",
      "question": "Le salarié est-il logé ?"
    },
```

**Comment by maxgfr** [comment]
D'ailleurs sur le préavis de retraite on track le select value, mais pas là

**Comment by maxgfr** [comment]
```
export enum MatomoActionEvent {
  RETIREMENT = "view_step_Préavis de départ ou de mise à la retraite",
  HOUR = "view_step_Heure recherche emploi",
  RESIGNATION = "view_step_Préavis de démission",
  DISMISSAL = "view_step_Préavis de licenciement",
}
```

Ce sont les actions attribué à chaque simulateurs
