### ISSUE TITLE
Message "attention" CC non traitée ou prochainement traitée préavis retraite 

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4020]
**Fonctionnalité**
Lorsque l'utilisateur sélectionne une CC non traitée ou une CC prochainement traitée le message à afficher sur la page résultat dans l'encadré bleu "Attention il peut exister une durée plus favorable" doit être le même que celui qui est affiché quand l'utilisateur ne sélectionne pas de CC, c'est à dire : 

![image](https://user-images.githubusercontent.com/84397271/142253886-6ab216b4-ef9c-498e-8538-be1204c4c59a.png)

**Comment by maxgfr** [comment]
Problématique lié à cette issue : #3550
