### ISSUE TITLE
Création de KPI mensuels

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4026]
L'idée serait de pouvoir consulter ces KPI chaque mois. 
Les 3 premiers KPI sont les plus importants.

### KPI : Taux de  complétion des outils => Fait

**Définition** : Part des   personnes qui vont jusqu'à l'étape résultat d'un outil par rapport au nombre total de personnes présentes sur l'étape introduction des outils (voir si le dénominateur n'est pas plutôt : le nombre de personnes qui sortent de l'outil ?)
**Formule** : (Nb de sessions   allant jusqu'à l'étape résultat)/ (Nb de visites sur la page intro des   outils)*100

### KPI : Pourcentage de personnes qui obtiennent un résultat conventionnel dans les outils => Fait
**Définition** : Part   des personnes qui vont jusqu'à l'étape résultat des outils et qui ont sélectionné une CC traitée par rapport au nombre total de personnes qui vont jusqu'à l'étape résultat des outils
**Formule** : (Nb   de sessions allant jusqu'à l'étape résultat + CC select)/ (Nb de sessions   allant jusqu'à l'étape résultat)*100

### **3.1.** => Fait
**Définition** : Part   des personnes qui sélectionnent une CC dans les pages personnalisables par rapport au nombre total de personnes qui consultent des pages personnalisables (en excluant celles qui ont un n°IDCC dans l'url)
**Formule** : CC select dans les contributions/Nb de visites sur contributions (en excluant celles qui ont un n°IDCC dans l'url)*100

### **3.2.** => Fait
**Définition** : Part   des personnes qui consultent une pages personnalisable personnalisée (soit par un CC select soit en arrivant direct sur une page personnalisée avec une recherche internet) par rapport au nombre total de personnes qui consultent des pages personnalisables (= toutes les url qui commencent par "/contribution" = en incluant celles qui ont un n°IDCC dans l'url)
**Formule** : (Somme des visites de url qui commencent par chiffre + CC select dans les pages contribution)/Somme des visites sur toutes les url qui commencent par "/contribution"

### KPI : Taux de recherche fructueuse de convention collective sur les outils
**Définition** : Part   des personnes qui sélectionnent une convention collective par rapport au nombre de personnes qui en recherche une (nombre de session où il y a au moins 1 CC search ?)
**Objectif** :  voir parmi ceux qui cherchent une CC combien en sélectionnent une

### KPI : Taux de recherche fructueuse de convention collective sur les contribs
**Définition** : Part des personnes qui sélectionnent une convention collective par rapport au nombre de personnes qui en recherche une (nombre de session où il y a au moins 1 CC search ?)

### KPI : Taux de sélection moyen d'un résultat pour une requête
**Définition** : le nombre de   fois où l'un des résultats du moteur a été sélectionné à l'issue de la recherche

### KPI : Taux de téléchargement des modèles (.docx)
**Définition** : Part   des personnes qui téléchargent des modèles par rapport au nombre total de personnes qui visitent des modèles
**Formule** : (Nb   de visites sur modèles + téléchargement) / (Nb de visites sur modèles)*100

**Comment by romain-b13** [comment]
Intégrer le graphe sur la complétion des outils dans Kibana

**Comment by m-maillot** [comment]
Refaire une passe sur ce ticket
