### ISSUE TITLE
Upgrade next js

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#4044]
Upgrade next to 12
https://github.com/SocialGouv/code-du-travail-numerique/pull/3954

**Comment by m-maillot** [comment]
Sur le sujet, @maxgfr avait identifié un soucis avec styled-component : https://github.com/vercel/next.js/issues/30802

**Comment by maxgfr** [comment]
Oui, normalement ça sera bon dans les prochaines semaines
