### ISSUE TITLE
Recap ES

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#405]
## Elastic Search

 - Revue fonctionnement api/index ES actuels
 - Tuning data/ES :
    - privilégier les matches de plusieurs mots. ex : "Congé parental d'éducation" ou "contrat unique d'insertion" doivent être boostés #330 #116
    - problèmes avec fautes d'orthographe / fuzzy #198 #80
    - gestion des phrases longues : pouvoir repérer les mots importants pour la recherche dans un long texte. elargir la recherche si nécessaire (pas de résultats). ex: "convention collective disquaires" : si ca ne renvoie rien, il faudrait chercher avec "convention collective" uniquement (et avoir l'info en réponse). #80 #330 #116
 - Granularité des docs indéxés :
    - gestion des anchors pour cibler des parties de documents ?
    - gestion des docs indéxés pour chaque paragraphe d'une meme page web -> du coup plusieurs résultats affichés pour une meme fiche. -> comment les grouper #330

## General :
 - gestion synonymes, acronymes #142
 - gestion parent/child pour les documents hierarchiques (ex: CdT) #253
 - bonnes pratiques tests unitaires et prévention des régressions
 - suggestions :
      - suggestions de recherches
      - suggestion de contenus
 - gestion ordre des articles pour le CdT. grouper/sorter logiquement #106
 - gestion des words embeddings dans ES ? pour recherche sémantique. ex : 'remboursement transport' doit aussi chercher 'Frais de transport' (dénomination dans le CdT). source de données possible : textes fiches SP/Min.T + liens articles & ePoseidon.

## Archi :
 - Maintenance des datas APM/Kibana
 - scalabilité
 - intégrité des données

**Comment by lionelB** [comment]
# mapping 
- utiliser le type `keyword`  plutôt que `type: text` + `analyzer: keyword` 
- analyzer: https://jolicode.com/blog/construire-un-bon-analyzer-francais-pour-elasticsearch
# index  
- basculer sur un shard (rule of thumb  1 shard = 20-50Go)

# API
- utiliser `suggestter` pour replacer le fuzzy
-  Refacto api `soc`
- expression multi-mot: utilisation du should avec un match phrase
- utilisation des min-term pour activer les clauses should 

# Test 
- utiliser la ranking api 

# auto complete (proposition de requete)
- voir completion suggester (travail lors de l'indexation)
- voir context suggestter  (travail lors de l'indexation)
piste: https://hackernoon.com/elasticsearch-building-autocomplete-functionality-494fcf81a7cf

## Booster par type de document 
- lors de l'indexation booster le score de depart

**Comment by revolunet** [comment]
Autre point : Comment gérer cas des questions déclinables par branche ?

Ex: 50 déclinées sur 50 branches pros...

**Comment by lionelB** [comment]
closed in favor of 
- ajouter un outils de control de pertinence pour elastic #433
- modifier le mapping elasticsearch #412 
- modifier l'analyser pour le francais dans elastic #413 
- modifier la config des shard dans Elastic #414
- refacto : Améliorer la spéaration des responsabilité entre les routes et les sources de données #415 
- APi : supprmier le param fuzzy et le remplacer par un suggest elastic #416 
- API : booster les faq pour qu'elles remontent avant les autres document #417 
- utiliser la ranking evaluation API #418
- Comment gérer cas des questions déclinables par branche ?#425
