### ISSUE TITLE
FAQ :  ajouter plusieurs questions par réponse

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#406]
je constate qu'une même réponse peut avoir différentes questions possibles: par exemple posée par l'employeur ou le salarié, ou comme ici: 

question: Le 3 du mois dernier, j’ai demandé un acompte à mon employeur qui me l’a refusé. En a-t-il le droit ?

réponse :
Il convient de faire la différence, juridiquement, entre une avance et un acompte.Ce que vous avez demandé à votre employeur, en début de mois, était une avance, laquelle s’analyse en un prêt sur des salaires non encore acquis, et que votre employeur était en droit de vous refuser.
L’acompte consiste au contraire en un paiement anticipé d’un salaire déjà acquis.
Il  correspond, pour une quinzaine travaillée, à la moitié de la rémunération mensuelle, et l’employeur ne peut le refuser au salarié qui en fait la demande.

On constate que dans une certaine mesure et en arrangeant un peu la réponse : on aurait également d'autres questions possible par exemple: "quelle est la différence entre acompte et avance?"

**Comment by ClementChapalain** [comment]
Je ne comprends pas bien le besoin derrière, on peut déjà avoir une même réponse à deux questions différentes si les mots trouvés pas elastic search matchent bien entre question et réponse non ?

**Comment by lionelB** [comment]
dans l'approche actuelle, si les mot de la requête correspondent au contenu de la réponse, la correspondance de la question  est secondaire car elle permet juste de donner un bonus de pertinence

Si on choisit de mettre plusieurs question, on pourrait imaginer dupliquer le contenu pour chaque question lors de l'indexation.

**Comment by ClementChapalain** [comment]
possible via le datafiller aujourd'hui
