### ISSUE TITLE
[Préavis retraite] Q° restent à remplir quand je fais précédent alors que je n'ai plus de CC de sélectionnée

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4060]
**Description**
Lorsque j'effectue un calcul du préavis de retraite, si je sélectionne une CC et que je vais jusqu'à l'étape résultat, lorsque je reviens en arrière et que j'enlève la CC, si je poursuis la simulation sans CC,  dans l'étape "informations" on me propose toujours les questions relatives à la CC qui avait été précédemment sélectionnée 

En résumé : comme on garde les données en mémoire, on garde aussi les réponses aux questions relatives 

**Reproduction**
Etapes à suivre pour reproduire le bug

1. Aller à sur l'outil "Préavis de départ ou de mise à la retraite"
2. Cocher "Le salarié décide lui-même de partir à la retraite" ou bien "L'employeur décide de mettre le salarié à la retraite"
3. Cliquer sur suivant
4. Sélectionner la CC 1090
5. Cliquer sur suivant 
6. [Quelle est la catégorie professionnelle du salarié ?] Sélectionner "Ouvriers, Employés" ou "Agents de maitrise"
7. [Quel est l'échelon du salarié ?] Sélectionner "1 et 2" ou "De 3 à 12"
8. [Le salarié concerné est-il reconnu en tant que travailleur handicapé ?] Cocher "oui" ou "non"
9. Cliquer sur suivant
10. Cliquer sur "précédent" 2 fois pour revenir à l'étape "convention collective"
11. Cliquer sur la croix pour "désélectionner" la convention collective
12. Cliquer sur suivant
13. Observer que les questions liées à la CC précédemment sélectionnée sont toujours présentes 

**Comportement attendu**
Les questions spécifiques aux CC ne doivent plus apparaître à l'étape "informations" si je désélectionne la CC et que je poursuis la simulation sans CC

**Comment by m-maillot** [comment]
On a aussi un soucis similaire quand on revient au choix entre départ ou mise à la retraite. S'il y a des changements de questions, on a les anciennes questions déjà répondues en premier:
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/992514/144090805-a00ffa0c-5819-4037-a2f4-cb0a83a7e87f.png">

Je pense qu'il faudrait remonter la question du handicap en premier ? Elle est toujours posée cette question.
