### ISSUE TITLE
User wait too long to see CC search result

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#4066]
When searching a CC, the call to `https://entreprise.data.gouv.fr/api/sirene/v1/full_text/boul?per_page=50` timeout frequently. In that case the user has to wait more than 10sec to see any results

Solution : show the first results as soon as one of the call succeed

**Comment by m-maillot** [comment]
Le problème a été résolu par l'équipe d'entreprise data. 
Cependant, l'API va être arrêté courant 2022. Ce n'est pas gênant pour nous car l'on va migrer rapidement sur le nouveau workflow :)

**Comment by carolineBda** [comment]
je ferme cette issue donc
