### ISSUE TITLE
En tant qu'utilisateur rattaché à la CC 3239, je souhaite être averti que le résultat réel peut-être différent de celui donné lorsque les dispositions applicables sont celles de l'ancienne CC (en vigueur jusqu'au 31/12/21)

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4071]
**Indemnité de licenciement conventionnelle**
Pour la CC 3239, si l'utilisateur sélectionne une date de départ de l'entreprise qui se trouve avant le 31/12/2021 il faut indiquer dans l'encadré "attention" : 
"L'indemnité de licenciement peut être différente du résultat donnée car les dispositions qui s'appliquent pour les salariés ayant été licencié avant le 31/12/2021 [...]

Voir si on ajoute un message dans les autres outils même lorsqu'il n' a pas de date à renseigner

**Comment by m-maillot** [comment]
On ne l'a pas encore implémenté cette CC ?

**Comment by romain-b13** [comment]
Non non pas encore implémenté, j'ai juste crée l'issue pour la mettre dans le backlog

**Comment by romain-b13** [comment]
Tout est indiqué dans l'issue https://github.com/SocialGouv/code-du-travail-numerique/issues/4079
