### ISSUE TITLE
En tant que salarié/employeur qui sera rattaché à la CC 3239 je souhaite pouvoir personnaliser une contribution avec la CC 3239 dès le mois de décembre pour voir les dispositions qui s'appliqueront à moi en 2022

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4078]
Avant le 31/12/21, dès que les contrib de la 3239 seront en prod, l'utilisateur doit pouvoir personnaliser une contrib avec la CC 3239, il faut donc qu'il puisse la trouver et la sélectionner dans les pages personnalisables.

Par contre dans les outils la CC3239 doit apparaître comme  une CC non traitée jusqu'au 31/12/21

**Comment by m-maillot** [comment]
En cours par @ivangabriele et @maxgfr
