### ISSUE TITLE
En tant que salarié/employeur rattaché à la CC 3239 je souhaite pouvoir sélectionner la CC 3239 dans chaque simulateur dès le 01/01/2022

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4079]
### Intégration de la CC 3239 dans les simulateurs
à partir du 01/01/2022, la CC 3239 doit être "trouvable" et "sélectionnable" en tant que CC traitée dans les outils suivants : Préavis de démission / Préavis de licenciement / Préavis de retraite / Indemnité de précarité / Heures pour recherche d'emploi / Trouver sa convention collective

### Tooltip sur les mots "assistant maternel" et "salarié du particulier employeur"
Lorsque l'utilisateur sélectionnera la CC 3239, la question suivante lui sera posée :
Quel est le statut du salarié ? 
- Assistant maternel
- Salarié du particulier employeur

Il faudra ajouter un tooltip sur les mots "assistant maternel" et "salarié du particulier employeur" en affichant la définition du glossaire

### Messages à afficher à l'étape résultat

**Pour les 3 outils suivants (avec 2 messages différents ou départ et mise à la retraite), un message doit être affiché à l'étape résultat des outils lorsque l'utilisateur aura sélectionné "assistant maternel" au moment où on lui demandera de faire le choix entre "assistant maternel" et "salarié du particulier employeur" :** 

**1) Préavis de licenciement**
![image](https://user-images.githubusercontent.com/84397271/144888863-d7df736f-f64c-4e66-9736-3d72ac0e0f4e.png)

Contenu du message : 
_Si la lettre de licenciement a été présentée avant le 01/01/2022, la durée de préavis ne correspond pas au résultat donné. En effet, jusqu’au 31/12/2021 c’est la convention collective “Assistants maternels du particulier employeur (IDCC 2395)” qui s’appliquait. Celle-ci a fusionné avec la convention collective “Salariés du particulier employeur (IDCC 2111)” pour former la convention collective “Particuliers employeurs et emploi à domicile (IDCC 3239)” applicable à partir du 01/01/2022._

**2) Préavis de démission**
_Si la lettre de démission a été présentée avant le 01/01/2022, la durée de préavis ne correspond pas au résultat donné. En effet, jusqu’au 31/12/21 c’est la convention collective "Assistants maternels du particulier employeur (IDCC 2395)" qui s’appliquait. Celle-ci a fusionné avec la convention collective “Salariés du particulier employeur (IDCC 2111)” pour former la convention collective “Particuliers employeurs et emploi à domicile (IDCC 3239)” applicable à partir du 01/01/2022._

**3) Préavis de départ (volontaire) à la retraite**
_Si la lettre de départ à la retraite a été présentée avant le 01/01/2022, la durée de préavis ne correspond pas au résultat donné. En effet, jusqu’au 31/12/21 c’est la convention collective "Assistants maternels du particulier employeur (IDCC 2395)" qui s’appliquait. Celle-ci a fusionné avec la convention collective “Salariés du particulier employeur (IDCC 2111)” pour former la convention collective “Particuliers employeurs et emploi à domicile (IDCC 3239)” applicable à partir du 01/01/2022._

**4) Préavis de mise à la retraite**
_Si la lettre de mise à la retraite a été présentée avant le 01/01/2022, la durée de préavis ne correspond pas au résultat donné. En effet, jusqu’au 31/12/21 c’est la convention collective "Assistants maternels du particulier employeur (IDCC 2395)" qui s’appliquait. Celle-ci a fusionné avec la convention collective “Salariés du particulier employeur (IDCC 2111)” pour former la convention collective “Particuliers employeurs et emploi à domicile (IDCC 3239)” applicable à partir du 01/01/2022._

**Comment by romain-b13** [comment]
Pour l'intégration de la CC 3239 dans l'outil de calcul du préavis de retraite voir aussi https://github.com/SocialGouv/code-du-travail-numerique/issues/3868 pour les spécificités

**Comment by romain-b13** [comment]
**Lien du data-simulateur** 
Regarder le 1er onglet intitulé "préavis" pour les outils : préavis de démission / préavis de licenciement / heures pour recherche d'emploi. Pour l'outil préavis de retraite, il faut regarder le 2ème onglet du data-simulateur intitulé "préavis départ en retraite".

https://docs.google.com/spreadsheets/d/1zd_hShEui8BHK0349GpDUZRkCcQ9syIZ9gSrkYKRdo0/edit#gid=227376301



**Lien de l'excel pour l'outil indemnité de précarité**
https://docs.google.com/spreadsheets/d/1SCFHUDjsWWRdVhYP5cVz2Q3AqPa-ubOYsEc3C3kRKOA/edit#gid=1991895535


**Traiter les outils dans l'ordre suivant (par ordre de popularité) :** 
Question préalable : Pour l'outil "trouver sa convention collective" il n'y a rien à faire de plus ? => la CC est déjà trouvable et sélectionnable ?

1- Préavis démission
2- Préavis licenciement
3- Indemnité de précarité 
4- Heures pour recherche d'emploi
5- Préavis de retraite

**Comment by romain-b13** [comment]
Si possible il faudrait ici que ce soit des boutons radios à la place du menu déroulant afin d'avoir un tooltip qui s'affiche sur "salariés du particulier employeur" et "assistants maternels du particulier employeur" 

![image](https://user-images.githubusercontent.com/84397271/148029175-d5f56da7-b6cd-4415-9586-2607ad851633.png)

**Comment by maxgfr** [comment]
@romain-b13 ça va s'appliquer à tout le simulateur par contre.

Je pense vaut mieux créer une issue spéciale pour cela

**Comment by romain-b13** [comment]
+ dans les outils "préavis de démission" / "préavis de licenciement" / "préavis de départ/mise à la retraite" quand l'utilisateur sélectionne la réponse "salariés du particulier employeur" à la question suivante : 

![image](https://user-images.githubusercontent.com/84397271/148029904-840291ae-aa6b-4b69-b6ff-22101e027e6a.png)

Il faut retirer le message qui s'affiche à l'étape résultat : 

![image](https://user-images.githubusercontent.com/84397271/148030059-7d8aac17-0169-4329-8f21-bf095e68fcfa.png)

=> ce message doit s'afficher uniquement quand l'utilisateur a selectionné ""Assistants maternels du particulier employeur"

**Comment by romain-b13** [comment]
> @romain-b13 ça va s'appliquer à tout le simulateur par contre.
> 
> Je pense vaut mieux créer une issue spéciale pour cela

Ok j'ai vu avec le métier pas nécessaire d'avoir le tooltip sur "assistants maternels" et "salariés du particulier employeur" donc on laissse le menu déroulant comme il est sans rien ajouter
