### ISSUE TITLE
Bug accordéon fiche SP

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4080]
**Description**
https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/contribution/combien-de-fois-le-contrat-de-travail-peut-il-etre-renouvele?q=Combien%20de%20fois%20mon%20contrat%20peut-il%20%C3%AAtre%20renouvel%C3%A9%20?
On voit dans cette fiche que l'espacement entre chaque accordéon est anormalement grand 

![image](https://user-images.githubusercontent.com/84397271/144603109-4f6ea5e4-d21a-4e82-9a84-f68a2bab4fda.png)

**Résultat attendu**
Réduction de l'espacement entre les accordéons (comme sur l'ensemble des fiches/pages du CDTN)

**Comment by maxgfr** [comment]
Oh bien vu !!!!

**Comment by romain-b13** [comment]
remplacé par https://github.com/SocialGouv/code-du-travail-numerique/issues/4101
