### ISSUE TITLE
En tant que salarié/employeur qui sera rattaché à la CC 3239, avant le 01/01/22 je souhaite que l'on m'indique clairement que les informations que je consulte sur la page de la CC ne sont pas encore applicables

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4081]
**Contexte pour la page CC**
La page de la CC 3239 va être publiée courant du mois de décembre alors qu'elle n'entrera en vigueur seulement le 01/01/22 permettant à l'utilisateur de se renseigner sur ce qui lui sera applicable à partir de 2022.
Il faut donc avertir l'utilisateur que les infos qu'il lit sur cette page ne prendront effet seulement à partir du 01/01/22.

**Résultat attendu pour la page CC 3239**
![image](https://user-images.githubusercontent.com/84397271/144871692-c9e86b96-778d-4fbc-af38-7bfa5d6fe0c9.png)

**Contenu du message :**
Attention : les informations données sur cette page seront applicables à partir du 01/01/2022
Cette page est publiée pour vous donner accès aux dispositions avant leur entrée en vigueur à partir du 01/01/2022. Cette convention collective résulte de la fusion des conventions collectives “Salariés du particulier employeur (IDCC 2111)” et “Assistants maternels du particulier employeur (IDCC 2395)”. Ces dernières restent applicables jusqu’au 31/12/2021.

**Comment by m-maillot** [comment]
Code implémenté, il faudra ajouter le texte depuis l'admin dans la CC.

**Comment by m-maillot** [comment]
Texte ajouté dans l'admin pour test sur la branche de PR.
