### ISSUE TITLE
En tant que salarié/employeur rattaché à la CC3239, à partir du 01/01/22 je souhaite être informé sur la page de cette CC que les infos données n'étaient pas valables avant le 01/01/21

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4084]
**Page de la CC 3239**
A partir du 01/01/2022 le message suivant devra être affiché sur la page de la CC 3239 : 
![image](https://user-images.githubusercontent.com/84397271/144883124-0a25da5b-1d59-4b84-a6a5-9d8eef5dfb6f.png)

**Contenu du message :** 
A noter : les informations données sur cette page sont applicables depuis le 01/01/2022
Cette convention collective est entrée en vigueur le 01/01/2022 suite à la fusion des conventions collectives “Salariés du particulier employeur (IDCC 2111)” et “Assistants maternels du particulier employeur (IDCC 2395)” qui étaient applicables jusqu’au 31/12/2021.

**Comment by m-maillot** [comment]
Dev -> OK
Modification du texte à faire dans l'admin pour le 1er janvier @romain-b13 @maxgfr

**Comment by maxgfr** [comment]
+1
