### ISSUE TITLE
En tant que salarié/employeur rattaché aux CC 211 ou 2395, je souhaite pouvoir consulter la page de la CC 3239 avant le 31/12 afin de voir si ce qui sera applicable en 2022

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4089]
**Description**
Mettre en ligne la page de la CC 3239 pour que l'utilisateur puisse la consulter avant le 31/12/21 même si elle n'est pas encore en vigueur.

Un message devra être afficher en haut de cette page (avant le 31/12/21) pour cela voir l'issue https://github.com/SocialGouv/code-du-travail-numerique/issues/4081

**Comment by m-maillot** [comment]
Ajout de la CC à kali-data en cours pour ensuite apparaitre sur l'admin.
