### ISSUE TITLE
Mise à jour des données SMIC

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#409]
- [ ] détecter les contenus "maison" impactés par le décret
- [x] modifier les données: réponse directe FAQ smic.
- [ ] le décret de revalorisation a toujours le même intitulé, peut on créer une règle de maj avec les données legifrance? 

https://www.legifrance.gouv.fr/eli/decret/2018/12/19/MTRX1833925D/jo/texte

**Comment by jrduscher** [comment]
@lionelB je te rajoute les données sous la fomre d'une FAQ à ce sujet(faq.json). A voir si tu veux expérimenter avec une idée de "réponse directe"
https://github.com/SocialGouv/code-du-travail-numerique/blob/jrduscher-patch-8/packages/code-du-travail-data/dataset/faq.json

**Comment by ClementChapalain** [comment]
@lionelB est-ce que cette tâche est terminée ?

**Comment by lionelB** [comment]
oui et non 

> * [ ] détecter les contenus "maison" impactés par le décret
> * [ ]  le décret de revalorisation a toujours le même intitulé, peut on créer une règle de maj avec les données legifrance?

je pense que cela devrait être gérés coté outils de contrib avec un systême d'alerte qui tourne en tache de fond

**Comment by ClementChapalain** [comment]
ok ce sont d'autres tâches pour moi, je vais transférer dans une nouvelle issue si c'est ok :)
