### ISSUE TITLE
En tant que salarié/employeur rattaché aux CC 2111 et 2395, je souhaite être informé que les infos consultées sur les pages CC ne sont applicables que jusqu'au 31/12/21

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4091]
**Pages convention collective des CC 2111 et 2395**
Avant le 31/12/21, une fois que la page de la CC 3239 sera publiée, sur les pages des CC 2111 et 2395, il faut ajouter le message suivant : 

"A noter : à partir du 01/01/2022 les informations ci-dessous ne seront plus applicables
Pour accéder aux informations applicables à partir du 01/01/2022, consultez la page de la convention collective "Particuliers employeurs et emploi à domicile (IDCC 3239)"

la partie "convention collective Particuliers employeurs et emploi à domicile (IDCC 3239)" doit être un lien vers la page de la CC 3239

**Comment by m-maillot** [comment]
Code implémenté, il faudra ajouter le texte depuis l'admin dans la CC.

**Comment by m-maillot** [comment]
Dev OK 
Il faut ajouter les informations sur l'admin pour ces 2 CC

**Comment by m-maillot** [comment]
Il faut ajouté le support d'un format permettant d'ajouter un lien dans le content. @carolineBda @maxgfr

**Comment by maxgfr** [comment]
+1

**Comment by carolineBda** [comment]
> Il faut ajouté le support d'un format permettant d'ajouter un lien dans le content. @carolineBda @maxgfr

C'est fait : [`9ae1396` (#4115)](https://github.com/SocialGouv/code-du-travail-numerique/pull/4115/commits/9ae139615777b67b05587ad70d565227a40e546e)
