### ISSUE TITLE
En tant que salarié/employeur rattaché aux CC 2111 et 2395, je souhaite être informé que les infos consultées les contrib personnalisées ne sont applicables que jusqu'au 31/12/21

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4092]
**Contributions personnalisées avec les CC 2111 et 2395 avant le 31/12**
Avant le 31/12/21, une fois que la page de la CC 3239 sera publiée, quand un utilisateur personnalisera une contrib avec la CC 2111 ou 2395, le message suivant s'affiche :  

"A noter : à partir du 01/01/2022 les informations ci-dessous ne seront plus applicables
Pour accéder aux informations applicables à partir du 01/01/2022, sélectionnez la convention collective "Particuliers employeurs et emploi à domicile (IDCC 3239)"

la partie "convention collective Particuliers employeurs et emploi à domicile (IDCC 3239)" doit être un lien vers la page de la CC 3239

**Comment by m-maillot** [comment]
Code implémenté, il faudra ajouter le texte depuis l'admin dans la CC.
