### ISSUE TITLE
En tant que salarié/employeur rattaché à la CC3239, à partir du 01/01/22 je souhaite être informé sur les contrib personnalisées avec cette CC que les infos données n'étaient pas valables avant le 01/01/21

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4094]
**Contrib (pages personnalisables) personnalisées avec la CC3239**
A partir du 01/01/2022 le message suivant devra être affiché lorsque l'utilisateur sélectionnera la CC3239 dans une contrib : 
![image](https://user-images.githubusercontent.com/84397271/144882363-84153359-7c32-4466-bef4-89ce2f446afa.png)

Contenu du message : 
A noter : les informations données sur cette page sont applicables depuis le 01/01/2022
Cette convention collective est entrée en vigueur le 01/01/2022 suite à la fusion des conventions collectives “Salariés du particulier employeur (IDCC 2111)” et “Assistants maternels du particulier employeur (IDCC 2395)” qui étaient applicables jusqu’au 31/12/2021.

**Comment by m-maillot** [comment]
Dev -> OK
Modification du texte à faire dans l'admin pour le 1er janvier @romain-b13 @maxgfr
