### ISSUE TITLE
En tant que salarié/employeur rattaché à la CC 3239, à partir du 01/01/22 dans le moteur de recherche des CC je souhaite savoir que la 3239 correspond aux anciennes CC 2111 et 2395

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4096]
Dans l'outil "trouver sa CC" + dans l'étape "convention collective" de tous les outils + dans les contrib, le résultat de la CC 3239 est accompagné d'une information supplémentaire :
"(anciennement conventions collectives “Assistants maternels du particulier employeur” IDCC 2395 et “Salariés du particulier employeur” IDCC 211)" => la formulation reste à valider par le métier

![image](https://user-images.githubusercontent.com/84397271/144894726-5058e057-13b7-4f3a-9309-12389467fe99.png)

**Comment by m-maillot** [comment]
Dev -> OK
Modification du texte à faire dans l'admin pour le 1er janvier @romain-b13 @maxgfr
