### ISSUE TITLE
En tant que salarié/employeur anciennement rattaché aux CC 2111 et 2395, à partir du 01/01/22 lorsque j'effectue une recherche sur le moteur global du CDTN avec les anciens mots clés, je souhaite comprendre pourquoi on me renvoie en résultat la CC 3239

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4097]
A partir du 01/01/22, quand l'utilisateur effectuera une recherche avec les mots clés "assistants maternels" "assistant maternel" assistantes maternelles" "assistante maternelle" "ass mat" etc. il faut modifier la description de la tuile de la CC 3239 qui apparaît en résultat :

![image](https://user-images.githubusercontent.com/84397271/144895850-d0c3e6eb-5a45-479c-9750-372796a15424.png)

**Comment by m-maillot** [comment]
Dev à faire. L'info actuellement en description n'est pas dynamique. Il faut la rendre dynamique et s'appuyer sur le highlight ajouté sur la CC.

**Comment by maxgfr** [comment]
TODO: Modifier les highlight vendredi, et faire la MAJ des données
