### ISSUE TITLE
Bug accordéon 

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4101]
Sur la page suivante : https://code.travail.gouv.fr/contribution/en-cas-darret-maladie-du-salarie-lemployeur-doit-il-assurer-le-maintien-de-salaire?q=arr%C3%AAte%20maladie%20r%C3%A8gles

1) Le texte du premier accordéon est visible même quand l'accordéon est fermé
2) Il y a un grand espacement entre les accordéons 

Ce bug semble présent sur plusieurs types de contenu puisqu'une issue avait déjà été ouverte sur ce même bug présent sur une fiche SP : https://github.com/SocialGouv/code-du-travail-numerique/issues/4080

**Comment by romain-b13** [comment]
Bug également présent ici https://code.travail.gouv.fr/contribution/1979-dans-le-cadre-dun-cdd-quel-est-le-montant-de-lindemnite-de-fin-de-contrat

**Comment by carolineBda** [comment]
Je ne vois le bug que sur la première url. Pour cette dernière, il faudrait juste ajouter dans l'outil de contrib un saut de ligne supplémentaire avant le premier Tab.

**Comment by romain-b13** [comment]
Le saut de ligne a été ajouté dans l'outil de contrib 👍
