### ISSUE TITLE
[ OUTILS ] durées des préavis de rupture  : Nouvelles catégories de la 2941. 

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#4111]
**Description**
Une alerte de convention collective est remontée dans l'outil d'administration.
Il en ressort les faits suivants : 
La CC 2941 a revu sa nomenclature de catégories professionnelles, comme suit :
- Les catégories A,B,C,D deviennent : la catégorie employé;
- Les catégories E,F deviennent : la catégorie technicien-agents de maîtrise;
- Les catégories G,H,I deviennent : la catégorie cadre.

Ce qui implique quelques changements nécessaires dans les données des différents outils :
- Durée de mise en retraite;
- Durée de préavis en cas de démission;
- Durée de préavis en cas de licenciement.

**Une modification des données est nécessaire :**
Des lignes vont être supprimées, et les noms des catégories devront être changés.

Faut il modifier le fichiers de données ( data_simulateur)? dans quels onglets ?
Quid des outils déjà sur publicode?

**Comment by CaptainConan** [comment]
Pour mémoire, il s'agit de cette alerte (portant sur l'accord 2941-118, publié au BOCC 2021-41 et étendu).
![CDTN 2921 alerte 2 182](https://user-images.githubusercontent.com/53531631/145075223-1dc1f6b8-9aa5-4c1b-95c5-5a1bd2a1064d.png)

**Comment by romain-b13** [comment]
cf https://github.com/SocialGouv/code-du-travail-numerique/issues/4955
