### ISSUE TITLE
En tant qu'utilisateur des pages CC, je ne souhaite pas avoir accès à un moteur de recherche si je n'ai aucun résultat sur Legifrance

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4113]
**Description**
Les pages conventions collectives du CDTN proposent un module de recherche du ou des textes conventionnelles sur Legifrance.
![image](https://user-images.githubusercontent.com/84397271/145367664-3ddc1584-c173-4f4e-85f0-825338ba30c9.png)

Il faut retirer ce module sur les pages CC dont la recherche ne donne aucun résultat sur Légifrance : 

![image](https://user-images.githubusercontent.com/84397271/145367943-194f165b-d252-41b4-a795-98bd2ca68cf1.png)

**Exemple**
https://code.travail.gouv.fr/convention-collective/822-convention-collective-departementale-applicable-aux-mensuels-de-la-metallurg

**Comportement attendu**
Le module de recherche ne devrait pas être proposé pour ces conventions locales de la métallurgie ni pour la CC 3239 tant qu'elle n'est pas sur Legifrance

**Comment by m-maillot** [comment]
Corrigé en même temps que l'ajout du text.
