### ISSUE TITLE
Retirer AT Internet et Google Analytics + bandeau cookies

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4119]
La campagne se termine le 18/12, ainsi après le 18/12 il s'agira de : 

- [x] retirer les cookies AT internet et les cookies Google Analytics
- [x] retirer le bandeau cookies
- [x] mettre à jour la politique de confidentialité
    - on peut garder celle que l'on a actuellement qui avait été proposée par Osiris, juste en retirant du tableau AT Internet et Google Analytics
    - retirer le passage suivant : 
"Seules certaines pages du site sont concernées par la mesure d’audience et l’analyse comportementale avec Google Analytics et vous n’avez visité aucune de ces pages. Aucun cookie Google Analytics n’a donc été déposé sur votre terminal."

**Comment by romain-b13** [comment]
- [x] Ajouter at internet avec le minimum (juste pour l'audience)
- [x] Modifier la politique de confidentialité (ajouter at internet dans le tableau)
![image](https://user-images.githubusercontent.com/84397271/147951363-872de805-c5c9-43af-9e2f-ebf05d9a160b.png)

- [ ] Faut-il ajouter / est-il possible d'ajouter cette case à cocher (que nous avons pour Matomo) pour AT internet ?
=> peut-être à valider avec Osiris mais il faudrait lui donner les infos du cookie utilisé
![image](https://user-images.githubusercontent.com/84397271/147951843-8d1757cb-8ecd-4264-8fcb-cdc764b1b008.png)

**Comment by maxgfr** [comment]
Concernant le dernier point, j'ai vu de la doc [ici](https://developers.atinternet-solutions.com/as2-tagging-en/javascript-en/users-javascript-en/respecting-data-privacy-javascript-en/)

**Comment by romain-b13** [comment]
On fait ce qui a été discuté lors du point plannig d'aujourd'hui : 

- [x] "désactiver" le cookie at internet pour que cela fasse uniqumeent de la mesure d'audience.
- [x] enlever la phrase surligner en jaune (juste laissser "mesure d'audience")

![image](https://user-images.githubusercontent.com/84397271/148771987-6737abab-8398-48d7-bb5e-fdce093f188c.png)
