### ISSUE TITLE
Description tuile 

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4146]
### 1) Problème dans la description de la tuile résultat d'une fiche MT

![image](https://user-images.githubusercontent.com/84397271/148027419-837586c1-93b0-4d50-a9de-1c10484fe665.png)

https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/recherche?q=mesures+de+pr%C3%A9vention+dans+l%27entreprise+contre+la+covid+19

### 2) Problème dans la description de la tuile résultat d'une contrib (la description est "...")

![image](https://user-images.githubusercontent.com/84397271/148027554-f3c04ac4-e611-4a61-a1d7-4982b00b26c1.png)

https://code.travail.gouv.fr/recherche?q=embauche+en+contrat+d%27extra

**Comment by maxgfr** [comment]
Le problème ne vient pas du problème, mais de la manière dont la description de la fiche a été générée

**Comment by maxgfr** [comment]
On le génère côté admin ici : <https://github.com/SocialGouv/cdtn-admin/tree/master/targets/ingester/src/transform>

**Comment by maxgfr** [comment]
## Problématique

Suite à l'issue #4146, une problématique globale à l'application fut soulevée. 

Dans un premier temps, j'ai essayé de régler les problèmes en patchant le traitement du texte via le frontend, cela semblait efficace. Car localement, et visuellement l"erreur semblait corrigé. Or, philosophiquement parlant, le problème globale n'était pas réglé. En effet, le postulat que **des données issues de scraping puisse disposer de données non-pertinente au sein de l'application**, ne serait pas global qu'à ces uses cases.

## Solution

Nous avons vu, qu'initialement, que régler ce problème via des `parsers` côté front-end n'est pas la solution, car celui-ci risqué de se reproduire.

La solution d'utiliser des `parsers` plus poussée côté `ingester` permettrait de régler le risque d'avoir des bouts de code qui trainent au sein de l'indexation de la description, mais ne réglerait toujours pas le problème de façon globale. Peu importe la manière algorithmique dont nous opérerons, `scrapper` la donnée, provoquera toujours à une incohérence entre le contenu récupéré par la machine et le contenu pertinent à disposer à l'utilisateur.

Par conséquent, la solution serait de laisser aux administrateurs du site, d'éditer manuellement la donnée traitée au sein du contenu indexé.

Il serait donc pertinent de permettre aux administrateurs, de laisser la possibilité d'`overrider` certains champs avant son indexation sur `elastic-search`

**Comment by maxgfr** [comment]
Pour le premier point, ça s'est corrigé tout seul

Pour le second point, il faut rajouter de l'information sur l'outil de contribution
