### ISSUE TITLE
Fix frequent errors seen in Sentry

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#4153]
- [ ]  **ChunkLoadError**

Occured more than 2.3k times the last 14 days :
https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/?environment=production&project=5&query=ChunkLoadError&statsPeriod=14d

Solution ?
https://raphael-leger.medium.com/react-webpack-chunkloaderror-loading-chunk-x-failed-ac385bd110e0

- [x]  **ReferenceError** "Can't find variable: globalThis"

Occured more than 1k times the last 14 days :
https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/?environment=production&groupStatsPeriod=auto&project=5&query=ReferenceError&statsPeriod=14d

Solution ?
https://stackoverflow.com/a/65530907

**Comment by maxgfr** [comment]
Pour le coup, je ne pense pas qu'on puisse fixer ces erreurs facilement.

La première semble venir de la manière dont on gère le loading des composants, or, au vu du nombre de composant qu'on a, la tâche semble bien compliqué d'handle les comportants asynchrone de chargement `lazy`.

Pour la seconde, cela semble venir d'une library externe qu'on utilise comme dépendance, aucun élément de notre côté semble confirmer l'utilisation d'un `globalThis`

**Comment by carolineBda** [comment]
Je ferme maintenant que nous regardons activement les erreurs Sentry
