### ISSUE TITLE
APi : supprmier le param fuzzy et le remplacer par un suggest elastic

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#416]
Afin de simplifier les requetes, et d'améliorer leur pertinence, il faudrait desactiver le fuzzy et le remplacer par un suggester elastic
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html

**Comment by revolunet** [comment]
comment gérer les photes d'orth/typos ?

ex :

paiment, paiement
salaire, salair

dans la version précédente, ces cas là marchaient un peu mieux: 

ex "salair base" et "salaire base".

également on a plus de completion sur "calcul indemn..."

**Comment by lionelB** [comment]
on s'est surtout concentré sur le search (et moins le suggest qui est une copie du search)
pour les typo, je pensais testé le scénario du suggester 
- faire une requête vide avec la query pour récupérer les "suggestions de correction typo" (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html) 
- faire la requête de search avec la suggestion

en testant le suggester, je me rend compte qu'il nous manque un champ non-stemm pour que le suggester marche :(
