### ISSUE TITLE
Les tooltip fonctionnent dans la page de la CC mais pas dans les pages personnalisables

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4165]
**Description**
Les tooltip sur les mots fonctionnent bien dans la page des CC (ex : dans l'accordéon "Quelle est la durée du congé de maternité ?" (lui même dans l'accordéon "Congés et repos" de cette page CC : https://code.travail.gouv.fr/convention-collective/3239-particuliers-employeurs-et-emploi-a-domicile?q=3239)

![image](https://user-images.githubusercontent.com/84397271/148434719-6f92e447-5b7f-4c65-bb3d-dc6de062541f.png)

Par contre la contrib qui correspond à cette question mais cette fois dans la page personnalisable personnalisée avec la CC en question, il n'y a pas de tooltip (cette page lorsqu'elle est personnalisée avec la 3239 : https://code.travail.gouv.fr/contribution/quelle-est-la-duree-du-conge-de-maternite)

![image](https://user-images.githubusercontent.com/84397271/148435046-6e7294d5-f703-4b75-8918-90cc02fa40f2.png)

C'est pourtant dans les 2 cas le même contenu rédigé dans l'outil de contrib

**Comment by m-maillot** [comment]
- [ ] Méthode addGlossary dispo sur l'admin. Fonctionne sur du markdown (cf editorial content). 
- [ ] Pas de test unitaire sur cette partie
- [ ] Pas de typescript

**Comment by maxgfr** [comment]
Du coup, le problème a été réglé. En gros, ça venait du fait que le "0" et le "1" était interprété par le matching. Cela règle aussi le fait que sur le tooltip où y'avait des 1, ça le soulignait et ça mettait une définition. 

Si la PR passe, on pourra virer le hack du frontend
