### ISSUE TITLE
Permettre à l'utilisateur de modifier une info facilement depuis le résultat d'un simulateur

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4172]
**Problème**
Bcp d'utilisateurs ne quittent pas les simulateurs une fois arrivée àa la page résultat mais reviennent sur des étapes précédentes

**USER STORIE**
En tant qu'utilisateur de simulateurs
Je souhaite pouvoir modifier une info saisie rapidement depuis la page résultat 
Afin de corriger une erreur de saisie ou de voir l'impact d'une modification sur le résultat

**Critères d'acceptation n°1**
Etant donné que j'ai ouvert l'accordéon "Voir le détail du calcul" et que je suis face aux éléments saisis
Lorsque je clique sur le bouton "modifier"
Alors j'accéde à l'étape en question 

**Critères d'acceptation n°2** (à voir si on garde les étapes cliquables)
Etant donné que je suis sur une étape N d'un simulateur 
Lorsque je clique sur le nom d'une étape N-1 / N-2 etc dans la liste affichée à gauche
Alors j'accéde à l'étape en question 
+
Etant donné que je suis passé de l'étape N à l'étape N-2 du simulateur
Lorque je clique sur l'étape N depuis l'étape N-2
Alors il ne se passe rien, je dois forcément cliquer sur le bouton "suivant" pour repasser de N-2 à N-1 puis N.

**Visuel** 
 
Je suis à l'étape 3

![image](https://user-images.githubusercontent.com/84397271/155155506-eb879f33-e2a5-499e-9cbc-84d51dd6bf12.png)

Je suis à l'étape 3 et je survole l'intitulé de l'étape 2 

![image](https://user-images.githubusercontent.com/84397271/155156091-cdf2617a-d1f9-4720-a10d-0ffb36fb4e88.png)

**Comment by m-maillot** [comment]
- [ ] Plutôt simple à mettre en place. Faire attention à l'accessibilité.
- [ ] Quid de la gestion du bouton back sur le navigateur ? C'est un point que l'on avait identifié à l'époque (peut être pas bloquant) mais si tu fais back avec ton navigateur, tu ne reviens pas à l'étape précédente mais sur la liste des outils. C'est un comportement qui peut faire quitter un utilisateur qui voulait revenir en arrière.

**Comment by romain-b13** [comment]
### Pour les clics sur une étape précédente
=> envoyer l'event suivant :
- event action : click_previous_nom de l'outil
- event name : nom de l'étape de destination

Ex : je suis à l'étape n°3 "informations" et je clique sur le nom de l'étape n°2 "Convention collective" => au moment du clic sur l'étape convention collective on envoie un event click_previous

=> Question : ajd quand il y a un click_previous a-t-on également l'event décrit ci-dessous d'envoyé : 
- event_action : view_step_nom de l'outil
- event_name : nom de l'étape de destination

**Comment by m-maillot** [comment]
Je suis un peu perplexe sur la user story qui me semble orienté déjà sur une solution : 

> En tant qu'utilisateur de simulateurs
> Je souhaite pouvoir me rendre facilement sur une étape précédemment complétée
> Afin de modifier certaines informations

J'aurai plutôt pensé à :

> En tant qu'utilisateur de simulateurs
> Je souhaite pouvoir modifier facilement certaines informations
> Afin de peaufiner le calcul 

J'aurai dit dans ce cas que le plus simple est d'avoir une édition sur les infos saisies listés dans le simulateur. Car l'objectif va être de modifier une valeur et peut importe sur quelle étape elle se trouve. Je ne suis pas sûr de l'efficacité de la cette solution. Sachant que dans le cas où il édite une info, on pourrait soit revenir directement à l'étape de résultat ou si l'info modifiée change d'autres données, on repasse sur les étapes pour les renseigner.

**Comment by romain-b13** [comment]
Propositions pour modifier ses données depuis l'étape résultat (ex ici pour l'indemnité de licenciement conventionnelle)

1) 
![image](https://user-images.githubusercontent.com/84397271/163579894-b962620a-41c9-4f52-adbf-fe170758e913.png)

2) [à voir si pertinent] Pour rendre plus compréhensible ce qui se cache derrière "voir le détail du calucl" => distinguer en 2 accordéons (afin d'induire plus facilement l'action pour la personne qui souhaite modifier une donnée ?)

a. Accordéons fermés

![image](https://user-images.githubusercontent.com/84397271/163580476-f3c23928-f655-495e-be26-d7a4218fb5b9.png)

b. Accorédon ouvert

![image](https://user-images.githubusercontent.com/84397271/163581847-5d909614-ebd9-47b9-8720-12cc4cba5bb8.png)

**Comment by romain-b13** [comment]
Pour les outils pour lesquels les éléments saisis sont déjà tous listés dans "éléments saisis" (préavis démission, préavis licenciement, heures pour recherche d'emploi et préavis de retraite) : il faudra sûrement augmenter l'espacement entre chaque ligne d'élément saisi pour pouvoir mettre le bouton "modifier" en face de chaque élément saisi (avec au minimum 8px entre les boutons)

![image](https://user-images.githubusercontent.com/84397271/166698228-35b42cd0-77b9-4141-a564-5fe6159b1aeb.png)

**Question**
Si l'utilisateur clique sur "modifier" face à l'élément "Groupe 1 à 5", est-on capable de faire le focus sur cette question précisément ("quel est le groupe du salarié ?") au sein de l'étape "informations" ?
Ou est-ce qu'on peut simplement le faire revenir en haut de la page de l'étape "informations" ? (ce qui veut dire que l'utilisateur va devoir scroller pour atteindre l'info qu'il souhaitait modifier)

**Comment by romain-b13** [comment]
Exemple vu sur 1jeune1 solution : 

![image](https://user-images.githubusercontent.com/84397271/183709237-77d0c88b-62b1-4bbe-81ca-42d9d9d7c412.png)


Après le clic sur sur le bouton :  

![image](https://user-images.githubusercontent.com/84397271/183709354-662b27ac-5a7c-4ca4-8c2d-9ccccc02113a.png)
