### ISSUE TITLE
Erreur 404:  5 questions/réponses sur le versement du salaire.

### ISSUE THREAD

**Issue by Armandgrd** [SocialGouv/code-du-travail-numerique#4173]
I can't access, [5 questions/réponses sur le versement du salaire](https://code.travail.gouv.fr/fiche-ministere-travail/5-questions-reponses-sur-le-versement-du-salaire?q=r%C3%A9mun%C3%A9ration) , I get a 404 `GET https://travail-emploi.gouv.fr/IMG/png/caroussel---salaire.png 404 (Not Found)`

**Comment by maxgfr** [comment]
@romain-b13

**Comment by romain-b13** [comment]
Merci Armand. La page n'est pas en 404 mais c'est l'image qui ne s'affiche pas.

**Comment by maxgfr** [comment]
Normalement à la prochaine MAJ des données, ça serait bon
