### ISSUE TITLE
Seul "moins de 50 ans"est disponible outil préavis de licenciement

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4174]
Dans l'outil : https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/outils/preavis-licenciement

1. Commencer la simulation
2. Etape "situation du salarié" cocher "non" pour les 2 premières questions et sélectionner aléatoirement une des 3 valeurs pour la 3ème question
3. Etape "convention collective" sélectionner la CC 0650
4. Etape "Informations complémentaires", sélectionnez aléatoirement une valeur pour les questions "Quelle est la position du salarié ?" et "Quelle est l'ancienneté du salarié ?"
5. BUG => pour la question "Quel est l'âge du salarié ?" une seule valeur est dispo dans le menu déroulant

**Comment by romain-b13** [comment]
![image](https://user-images.githubusercontent.com/84397271/149309841-8abb7b91-027c-4d01-8e08-683c8583d647.png)

**Comment by maxgfr** [comment]
![image](https://user-images.githubusercontent.com/25312957/149910435-c2b28e59-10e7-4af7-b032-e1751b950288.png)
