### ISSUE TITLE
Mettre en place redirections pour 2  nouvelles pages info

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4189]
**pages actuelles concernées**
- https://code.travail.gouv.fr/information/pass-sanitaire-et-contrat-de-travail
- https://code.travail.gouv.fr/information/vaccination-et-pass-sanitaire-les-dates-a-retenir

**Ces pages auront un nouveau titre**
- Pass vaccinal et contrat de travail [infographie]
- Pass vaccinal : les dates à retenir [infographie]

L'objectif global que l'on cherche à atteindre est de modifier le slug de la page info pour qu'il corresponde bien au nouveau titre de la page info (puisque le slug ne se met pas à jour quand on modifie le titre de la page) sans avoir de 404.

Process global pour la modification du slug : 
- Le jour J, on publie les nouvelles pages infos (on laisse les anciennes publiées que l'on aura également mise à jour)
- Ensuite, on met en prod le frontend avec la redirection sur les pages infos.
- Dès que l'on est en prod et que c'est validé, on peut dépublier les anciennes pages infos. Et on force Google pour réindexer notre contenu.

**Comment by maxgfr** [comment]
On redirigerai ces deux pages, vers quelles URL du coup?

**Comment by romain-b13** [comment]
> On redirigerai ces deux pages, vers quelles URL du coup?

L'url n'existe pas encore mais du coup j'imagine qu'on peut la définir à partir du nouveau titre que l'on va proposer : 
- Pass vaccinal et contrat de travail [infographie] => je suppose que ça donnerait code.travail.gouv.fr/information/pass-vaccinal-et-contrat-de-travail
- Pass vaccinal : les dates à retenir [infographie] => code.travail.gouv.fr/information/pass-vaccinal-les-dates-a-retenir

**Question** : dans le titre de ces pages il y aura également la mention : "[infographie]" => ce n'est pas nécessaire dans le slug mais je ne sais pas si ç apparaîtra aussi dans le slug
