### ISSUE TITLE
Vérifier que toutes les CC sont bien intégrées dans les simulateurs

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4194]
**Description**
Par hasard j'ai découvert que les CC suivantes n'étaient pas traitées dans l'outil "heures pour recherche d'emploi", qui plus est ces CC font partie des 10 CC les plus sélectionnées dans ce simulateur : 
- Batiment etam (2609)
- Hotels cafés restaurants (1979)

Je me demande donc si il ne manque pas d'autres CC dans d'autres outils.

Il faudrait donc checker que les CC listées si dessous soient bien implémentée dans tous les simulateurs qui ont une étape CC (préavis démission, préavis licenciement, heures pour recherche d'emploi, indemnité de précrité, préavis de retraite)

<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">
<style>

</style>
</head>

<body>

IDCC | Nom   de la convention collective
-- | --
16 | TRANSPORTS ROUTIERS
29 | HOSPITALISATION A BUT NON   LUCRATIF FEHAP
44 | CHIMIE INDUSTRIE
54 | METALLURGIE OETAM REGION   PARISIENNE
86 | PUBLICITE
176 | PHARMACEUTIQUE INDUSTRIE
275 | TRANSPORT AERIEN PERSONNEL AU SOL
292 | PLASTURGIE
413 | PERSONNES INADAPTEES ET   HANDICAPEES ETABLISSEMENTS
573 | COMMERCES DE GROS
650 | METALLURGIE INGENIEURS ET CADRES
675 | HABILLEMENT COMMERCE SUCCURSALES
787 | EXPERTS-COMPTABLES ET   COMMISSAIRES AUX COMPTES
843 | BOULANGERIE PATISSERIE   ENTREPRISES ARTISANALES
1043 | GARDIENS CONCIERGES ET EMPLOYES   D'IMMEUBLES
1090 | AUTOMOBILE SERVICES
1147 | CABINETS MEDICAUX
1266 | RESTAURATION DE COLLECTIVITES
1351 | PREVENTION SECURITE ENTREPRISES
1404 | TRACTEURS MATERIELS AGRICOLES   COMMERCE REPARATION
1480 | JOURNALISTES
1483 | HABILLEMENT ARTICLES TEXTILES   COMMERCE DE DETAIL
1486 | BUREAUX D'ETUDES TECHNIQUES
1501 | RESTAURATION RAPIDE
1505 | FRUITS LEGUMES EPICERIE PRODUITS   LAITIERS
1516 | FORMATION ORGANISMES

</body>

</html>
<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">
<style>

</style>
</head>

<body>

1517 | COMMERCE   DETAIL NON ALIMENTAIRE
-- | --
1518 | ANIMATION
1527 | IMMOBILIER
1596 | BÂTIMENT   OUVRIERS (JUSQU'À 10 SALARIÉS)
1597 | BATIMENT   OUVRIERS (PLUS DE 10 SALARIES)
1606 | BRICOLAGE   VENTE AU DETAIL EN LIBRE-SERVICE
1672 | ASSURANCES   SOCIETES
1702 | TRAVAUX   PUBLICS OUVRIERS
1740 | BATIMENT   OUVRIERS REGION PARISIENNE
1979 | HOTELS   CAFES RESTAURANTS
1996 | PHARMACIE   D'OFFICINE
2098 | PRESTATAIRES   DE SERVICES SECTEUR TERTIAIRE
2120 | BANQUE
2148 | TELECOMMUNICATIONS
2216 | COMMERCE   DETAIL ET GROS A PREDOMINANCE ALIMENTAIRE
2264 | HOSPITALISATION   PRIVEE
3239 | PARTICULIERS   EMPLOYEURS ET EMPLOI À DOMICILE
2420 | BATIMENT   CADRES
2511 | SPORT
2596 | COIFFURE
2609 | BÂTIMENT   ETAM
2614 | TRAVAUX   PUBLICS ETAM
2941 | AIDE   SOINS SERVICES A DOMICILE (BAD)
3043 | PROPRETE   ENTREPRISES ET SERVICES ASSOCIES
3127 | SERVICES   A LA PERSONNE ENTREPRISES
  |  

</body>

</html>

**Comment by carolineBda** [comment]
CC manquantes par simulateurs :

- préavis démission

54 | METALLURGIE OETAM REGION   PARISIENNE
-- | --

- préavis licenciement
Aucune ne manque mais les CC suivant sont en implantées en plus :
822
860
878
898
914
937
965
1560
1564
1626
1885
1960
2266
2126

- heures pour recherche d'emploi
1979 et 2609 sont bien implantées. Pourquoi tu dis qu'elles ne le sont pas @romain-b13  ?

54 | METALLURGIE OETAM REGION   PARISIENNE
-- | --

-  indemnité de précarité

1480 | JOURNALISTES
-- | --

Beaucoup de CC implémentées en plus :
714
822
827
828
829
836
860
863
878
887
898
899
911
914
920
923
930
934
937
943
948
965
979
984
1007
1059
1060
1159
1164
1274
1315
1353
1365
1369
1387
1472
1525
1560
1564
1572
1576
1577
1578
1592
1626
1627
1628
1634
1635
1732
1813
1867
1885
1902
1912
1960
1966
1967
2003
2126
2221
2266
2294
2489
2542
2579
2615
2630
2700
2755
2980
2992
3053
3209
3231

- préavis de retraite
OK

**Comment by romain-b13** [comment]
**Pour l'outil heure pour recherche d'emploi** : à l'étape résultat on indique "Aucun résultat : la convention collective n’a pas encore été traitée par nos services." pour les CC 1979 et 2609

![image](https://user-images.githubusercontent.com/84397271/151935247-52dffb7b-c4d9-4964-9952-fa4c28237926.png)

**Comment by romain-b13** [comment]
Pour l'absence de la CC 54 (métallurgie région parisienne) dans préavis de démission et heures pour recherche d'emploi ce serait normal car il y a des incohérences entre le texte de la CC locale et le texte national donc on ne traite pas la CC pour ces cas là

Pour la CC 1480 manquante dans heures pour recherche d'emploi, cette CC est surlignée en rouge dan sle data-simulateur donc je pense qu'il y avait là aussi une explication métier (je vois avec le métier)

Toutes les CC implémentées en plus sont des CC locales de la métallurgie qui sont assez spécifiques 

La seule tâche restante ici est donc d'identifier le bug dans heures pour recherche d'emploi qui dit que certaines CC ne sont pas traitées alors qu'elles sont bien implémentées => je crée une issue pour ça, je l'a mets dans le prochain sprint
