### ISSUE TITLE
Passer l'outil existant indemnité de licenciement conventionnelle sous publicode

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4199]
**Développement de l'indemnité conventionnelle**

- [x] #4215 
- [x] Valider l'outil et le passer en prod
- [x] Ajouter l'étape CC au simulateur
- [x] Implémenter une CC simple (pas de modif sur l'ancienneté et salaire de référence mais avec des questions)
- [x] Implémenter une CC moyenne (modif ancienneté et salaire de ref)
- [x] #4317 
- [x] Implémenter le top 10 des CCs
- [x] Valider l'outil et le passer en prod
- [ ] Dérouler les CCs restantes avec validations et livraisons régulières

**Comment by m-maillot** [comment]
- [ ] Je propose d'écrire en premier le publicode et de voir comment faire cohabiter les 2 simulateurs (ce qui n'a pas été prévu à la base). 
- [ ] Est ce que l'on garde l'ancienneté calculée comme aujourd'hui ou on la simplifie comme pour le préavis de retraite ? (partie ancienneté difficilement intégrable dans publicode qui ne gère pas les listes).
- [ ] Pas de typescript

**Comment by romain-b13** [comment]
@m-maillot c'est cette partie de l'étape qui serait difficilement intégrable ? : 

![image](https://user-images.githubusercontent.com/84397271/151332140-06350845-3edb-4022-af6e-ff877f384bfc.png)

**Comment by m-maillot** [comment]
Oui @romain-b13, elle peut l'être dans le cas sans CC mais dès qu'il y aura des CCs, ça risque de devenir complexe.

**Comment by romain-b13** [comment]
Cette carte va être spliter en différentes cartes : 
- Ecriture publicode https://github.com/SocialGouv/code-du-travail-numerique/issues/4215
- Utilisation de publicode pour la page résultat https://github.com/SocialGouv/code-du-travail-numerique/issues/4216
- Etude sur les étapes salaires et ancienneté pour l'intégration avec publicode https://github.com/SocialGouv/code-du-travail-numerique/issues/4217
- Finaliser l'intégration sur l'outil 
- Ajouter une CC simple

**Comment by carolineBda** [comment]
TODO :
- [ ] avant 8 mois d'ancienneté, l'IL est toujours de 0
- [ ] gérer l'inaptitude suite à un accident du travail ou maladie professionnelle reconnue dans publicode (on fait x2)
- [ ] tout tester et merger
