### ISSUE TITLE
affichage des données de site teleRC

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#42]
Rupture conventionnelle id tagn° 1700.

Intégrer la RC aux réponses contextualisées

* calcul du délai de retraction
https://www.telerc.travail.gouv.fr/RuptureConventionnellePortailPublic/jsp/site/Portal.jsp?page=calculerdelairetractation
* calcul de l'indemnité légale de rupture conventionnelle
https://www.telerc.travail.gouv.fr/RuptureConventionnellePortailPublic/jsp/site/Portal.jsp?page_id=14

**Comment by revolunet** [comment]
Dans le cas ou tag=1700, tu veux que tele RC doit apparaitre en priorité ?

a quel endroit ca aurait le plus de sens ?

**Comment by ClementChapalain** [comment]
je ferme, géré par le data filler aujourd'hui
