### ISSUE TITLE
Alléger les textes d'intro des simulateurs

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4200]
### US
En tant qu'utilisateur des outils
Je souhaite pouvoir commencer une simulation en ayant accès uniquement aux infos utiles pour pouvoir débuter la simulation

### Nouveaux textes

**Indemnité de licenciement**

Ce simulateur permet d’estimer le montant de l’indemnité minimale de licenciement d’un salarié.
Vous aurez besoin d’informations relatives au licenciement (dates d’entrée et de sortie de l’entreprise, date de notification du licenciement et derniers bulletins de salaire).

**Préavis de démission**

Ce simulateur permet de calculer la durée du préavis que le salarié doit respecter en cas de démission.
En cas de démission, le salarié ne peut pas quitter l’entreprise immédiatement après avoir informé l’employeur de ses intentions. Il doit rester dans l’entreprise durant une certaine période, qu’on appelle préavis ou parfois délai congé.
Vous aurez besoin d’informations concernant la situation du salarié concerné, comme sa convention collective et, dans certains cas sa catégorie professionnelle ou son coefficient. La plupart de ces informations se trouvent sur le contrat de travail ou le bulletin de salaire.

**Indemnité de précarité**

Ce simulateur permet d’estimer le montant de l’indemnité de fin de contrat ou de fin de mission (dite “prime de précarité”) d’un salarié en CDD ou en contrat d’intérim.
Vous aurez besoin d’informations relatives au contrat de travail (CDD ou contrat de travail temporaire (contrat d’intérim), et derniers bulletins de salaire).

**Préavis de licenciement**

Ce simulateur permet de calculer la durée du préavis accordée au salarié en cas de licenciement.
Le préavis est une période accordée au salarié entre la notification du licenciement et son départ effectif de l’entreprise (fin du contrat). Vous pouvez trouver plus d’informations sur le préavis de licenciement sur cette fiche.
Vous aurez besoin d’informations concernant la situation du salarié concerné, comme sa convention collective et, dans certains cas sa catégorie ou son coefficient. La plupart de ces informations se trouvent sur le bulletin de salaire ou le contrat de travail.

**Heures pour recherche d’emploi**

Ce simulateur permet de savoir si le salarié peut bénéficier d’heures d’absence autorisée pendant son préavis pour rechercher un emploi. Il peut s’agir du préavis en cas de licenciement, de démission ou de rupture de la période d’essai.
Le code du travail ne prévoit pas ce droit (sauf cas particulier du droit applicable à l’Alsace Moselle). En revanche, plusieurs conventions collectives fixent un nombre d’heures d’absence autorisée pour rechercher un emploi et leurs conditions d’utilisation.
Vous aurez besoin d’informations concernant la situation du salarié concerné, comme sa convention collective et, dans certains cas sa catégorie professionnelle ou son ancienneté. La plupart de ces informations se trouvent sur le contrat de travail ou le bulletin de salaire.

**Comment by m-maillot** [comment]
Réserve: 
L'ensemble des textes ont ils été validés par le métier ?

**Comment by carolineBda** [comment]
Je me demande si on a vraiment besoin de préciser ce dont l'utilisateur a besoin en amont ?
ça alourdi le texte je trouve et ça décourage un peu, non ?

**Comment by romain-b13** [comment]
Voici la nouvelle version : 

**Indemnité de licenciement** 
Ce simulateur permet d’estimer le montant de l’indemnité légale de licenciement [tooltip sur "indemnité légale de licenciement"] d’un salarié. 

Vous aurez besoin d’informations telles que les dates d’entrée et de sortie de l’entreprise, la date de notification du licenciement et le montant des derniers salaires.


**Préavis de démission** 
Ce simulateur permet de calculer la durée du préavis que le salarié doit respecter en cas de démission. 

Des informations disponibles sur le bulletin de salaire pourraient être utiles pour réaliser cette simulation.

**Indemnité de précarité** 
Ce simulateur permet d’estimer le montant de l’indemnité de fin de contrat ou de fin de mission, (dite “prime de précarité”), d’un salarié en CDD ou en contrat d’intérim. 

Les montants des salaires perçus pourraient être utiles pour réaliser cette simulation.

**Préavis de licenciement** 
Ce simulateur permet de calculer la durée du préavis accordée au salarié en cas de licenciement.

Des informations disponibles sur le bulletin de salaire pourraient être utiles pour réaliser cette simulation.

Vous pouvez trouver plus d’informations sur le préavis de licenciement sur [cette fiche](https://code.travail.gouv.fr/fiche-service-public/preavis-de-licenciement).

**Heures pour recherche d’emploi** 
Ce simulateur permet de calculer le nombre d’heures d’absence autorisée pendant la période de préavis (de licenciement, de démission ou de rupture de la période d’essai), pour rechercher un emploi, si la convention collective le prévoit.

Des informations disponibles sur le bulletin de salaire pourraient être utiles pour réaliser cette simulation.

Vous pouvez trouver plus d’informations sur les heures d’absence autorisée pour rechercher un emploi pendant le préavis sur [cette fiche](https://code.travail.gouv.fr/contribution/le-salarie-peut-il-sabsenter-pour-rechercher-un-emploi-pendant-son-preavis).


**Préavis de retraite** 
Ce simulateur vous permet de calculer la durée de préavis à respecter en cas de départ ou de mise à la retraite.
Des informations disponibles sur le bulletin de salaire pourraient être utiles pour réaliser cette simulation.
