### ISSUE TITLE
[indemnité de licenciement] ajout d'un encadré "à noter"

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4209]
**Problème**
à l'étape "contrat de travail" pour la question "Quel est le type du contrat de travail ? (obligatoire)" quand on sélectionne la réponse "Contrat à durée determiné (CDD) ou contrat d’intérim" un message s'affiche pour indiquer qu''il n'y a pas d'indemnité de licenciement pour ce cas mais ce message est peu lisible de part sa mise en forme et n'est pas harmonisé avec les autres disclaimer. Par la même occasion on rempacera l'url vers laquelle on renvoit dans le message qui est down.

![image](https://user-images.githubusercontent.com/84397271/150971891-f91b5450-fa64-4a11-9527-a346671a6290.png)

**Solution**
Intégrer le message dans un encadré "à noter" comme c'est le cas pour la question juste en dessous "Le licenciement est-il dû à une faute grave (ou lourde) ? (obligatoire)" quand on séléctionne la réponse "oui" : 

![image](https://user-images.githubusercontent.com/84397271/150972485-75580b56-350f-47be-92cf-5e694ed257d9.png)

Mettre sur une première ligne en gras "L’indemnité de licenciement n’est pas dûe pour les CDD et contrats de travail temporaires."
Mettre sur une deuxième ligne "Sous certaines conditions, le salarié peut avoir le droit à une indemnité de précarité." => (enlever "nouvelle fenêtre")

**Autre modification**
Enlever l'espace entre "à noter" et la première phrase 

![image](https://user-images.githubusercontent.com/84397271/161305359-044ad72b-ccc4-46b6-b866-dc4480b176cb.png)

**Comment by maxgfr** [comment]
Done
