### ISSUE TITLE
Dashboard satisfaction: commentaires utilisateurs. 

### ISSUE THREAD

**Issue by Armandgrd** [SocialGouv/code-du-travail-numerique#4211]
Le filtre par mois du dashboard satisfaction ne fonctionnement pas correctement. 
les mêmes commentaires sont remontés chaque mois. 

- ajouter si possible la date de création d'un commentaire pour identifier si le problème continue de survenir après une résolution

A inspecter également: possibles mismatch entre les nom de page et les commentaires. 
ex:  `LA PAGE N'EST PAS ACCESSIBLE POUR INDEMNITE PRECARITE`

**Comment by Armandgrd** [comment]
> LA PAGE N'EST PAS ACCESSIBLE POUR INDEMNITE PRECARITE

Cette remarque est bien faite pour la page indemnité de licenciement... ping @romain-b13

**Comment by romain-b13** [comment]
Je pense que le filtre ne fonctionne pas correctement non plus pour le ration de feedback

Dans cet exemple sur 4 mois en arrière il y a moins de feedbacks (positifs ou négatifs) de comptabilisés par rapport à la période de 2 mois en arrière.

4 mois en arrière : 

![image](https://user-images.githubusercontent.com/84397271/151574449-cd524f67-c940-499d-9fb4-5652d5314666.png)



2 mois en arrière : 
![image](https://user-images.githubusercontent.com/84397271/151574303-d87cdc09-6428-4569-b9b7-e3be0290f62f.png)

**Comment by romain-b13** [comment]
Comment peut-on avoir des nombres de feedbacks à virgule ?

**Comment by Armandgrd** [comment]
@romain-b13 C'est Corrigé
