### ISSUE TITLE
Ecrire la partie publicode de l'outil indemnité de licenciement

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4215]
Passage de la version actuelle de l'outil en publicodes pour ensuite intégrer les CCs.

 - [x] Ecrire la formule de calcul dans publicodes
 - [x] Utiliser la formule de publicodes pour afficher le résultat à l'utilisateur
 - [x] #4371
 - [x] #4372 
 - [x] #4217
 - [x] #4413
 - [x] #4373
 - [x] #4370
 - [x] #4374
 - [x] #4317 
 - [x] #4478

**Comment by maxgfr** [comment]
Je vais m'occuper du split de la partie publicode du préavis de retraite et celui du nouveau simulateur. Je vais voir comment je peux optimiser le truc

**Comment by maxgfr** [comment]
Du coup, c'est plus la partie frontend en `ts` , que je vais faire dans un premier temps

**Comment by maxgfr** [comment]
La tâche est en cours sur cette PR : https://github.com/SocialGouv/code-du-travail-numerique/pull/4252 qui dérive de la PR de caro : https://github.com/SocialGouv/code-du-travail-numerique/pull/4249

Celle-ci est très fat, car j'ai réecris en bonne partie la partie `modeles` de l'application. Celle-ci est composée de la partie handler qui est traitée dans cette issue : https://github.com/SocialGouv/code-du-travail-numerique/issues/4247

Du coup, là ce qui faut faire, c'est diviser la partie handler (frontend), de la partie modèles (publicodes). Afin d'alléger la PR, et de merge la première partie assez rapidement

**Comment by m-maillot** [comment]
TODO:

 * [x] Ecrire le publicodes pour l'indemnité de licenciement (+ TU) (voir https://github.com/SocialGouv/code-du-travail-numerique/pull/4249)
 * [x] Ecrire le publicodes pour activer / désactiver un simulateur via la situation (voir https://github.com/SocialGouv/code-du-travail-numerique/pull/4252)
 * [ ] Regarder le problème de la duplication pour la règle d'ancienneté

**Comment by carolineBda** [comment]
A confirmer :
1) Ici A1 et A2 sont exprimé un années non arrondi (par exemple 13 mois = 1,083333333)
```
#  (1/4*Sref*A1) + (1/3*Sref*A2)
#  A1 : Ancienneté de 10 ans ou moins
#  A2 : Ancienneté au delà de 10 ans
```

2) avant 8 mois d'ancienneté, l'IL est toujours de 0

3) avant on effectué un calcul différent si la date de notification était avant le 27/09/2017. Devons-nous toujours gérer ce cas? On peut juste afficher une notification au moment l'usager met la date de notif si elle est antérieur à 27/09/2017 ?
Et dans ce cas avant nous toujours besoin de demander la date de notif ?

4) Le licenciement est-il dû à une inaptitude suite à un accident du travail ou maladie professionnelle reconnue?
    => on fait x 2 de résultat ?

5) actuellement on retranche le nombre de mois d'absences longues avec de coef :
```
  { label: "Absence pour maladie non professionnelle", value: 1.0 },
  { label: "Arrêt maladie lié à un accident de trajet", value: 1.0 },
  { label: "Congé sabbatique", value: 1.0 },
  { label: "Congé pour création d'entreprise", value: 1.0 },
  { label: "Congé parental d'éducation", value: 0.5 },
  { label: "Congés sans solde", value: 1.0 },
  { label: "Grève", value: 1.0 },
  { label: "Mise à pied", value: 1.0 },
  { label: "Maladie d'origine non professionnelle", value: 1.0 },
  { label: "Congé de paternité", value: 1.0 },
```
Toujours ok ?
 Pour les devs : https://github.com/SocialGouv/code-du-travail-numerique/pull/4263/files#r814919042

**Comment by romain-b13** [comment]
1. Oui
2. Oui = pas d'indemnité si ancienneté < 8 mois
3. ne pas faire le calcul différent mais si l'utilisateur sélectionne une date avant 2017 on lui met un message 
4. oui x 2 à faire
5. On laisse l'ancienne méthode de calcul de l'ancienneté

**Comment by carolineBda** [comment]
TODO :
- [x] avant 8 mois d'ancienneté, l'IL est toujours de 0
- [x] gérer l'inaptitude suite à un accident du travail ou maladie professionnelle reconnue dans publicode (on fait x2) => il y a-t-il une référence spécifique à ajouter dans ce cas ? @romain-b13 
- [x] cleaner le code js qui n'est plus utilisé (pour le calcul de l'indemnité)
- [ ] ajouter la phrase de notif pour les utilisateurs qui sélectionne une date de notification avant 09/2017 (à préciser par @romain-b13)
- [ ] tout tester et merger

**Comment by carolineBda** [comment]
On a oublié : 
- [x] gérer l'explication du résultat (on le garde en js)

**Comment by romain-b13** [comment]
si l'usager est licencié suite à une inaptitude d'origine professionnelle (donc s'il coche "oui" dans l'outil), on pourra rajouter l'art. L. 1226-14 en référence. C'est cet article qui prévoit le doublement de l'indemnité légale dans cette hypothèse.

**Comment by romain-b13** [comment]
[Cas de la notification du licenciement antérieur à septembre 2017]
bloquer la poursuite de la simulation pour toute date de notification du licenciement antérieure à 18 mois avant le jour de la simulation.
Si l'utilisateur saisie une date antérieure à cette limite, on affiche juste le message "La date de notification doit se situer dans les 18 derniers mois"

**Comment by carolineBda** [comment]
je laisse ici une trace de ce que j'avais fait pour le calcul de l'ancienneté avec les dates dans publicodes : [`c341334` (#4263)](https://github.com/SocialGouv/code-du-travail-numerique/pull/4263/commits/c34133482bb1f818176c5fffb8bffe0d361b4acf)
