### ISSUE TITLE
Utiliser publicode pour la page résultat outil indemnités de licenciement

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4216]

**Comment by m-maillot** [comment]
TODO :

 * [ ] Ajouter l'indemnité de licenciement dans le publicodeContext
 * [ ] Utiliser le publicodeContext pour afficher le résultat sur l'indemnité de licenciement (Résultat (Le code du travail prévoit un montant minimum de : XXXX € brut, Éléments saisis et Sources)
 
 Soucis identifié:
  * Valeur euro dans le résultat (unit)
  * Sources
