### ISSUE TITLE
Etudier l'intégration du calcul du salaire de référence CC

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4217]
L'étapes "salaires" et "primes" implique de gérer des listes => voir comment gérer ces étapes avec publicode

Document excel d'étude : https://docs.google.com/spreadsheets/d/1ZbI-kE3CvP1UmwL4TJau3l_LAOrEo3UcRFZpXov4PoM/edit#gid=0

Klaxoon brainstorming : https://app.klaxoon.com/participate/board/RFXEGPE

**Etape salaire** 

![image](https://user-images.githubusercontent.com/84397271/151408739-ec109b87-9bd0-47e0-8029-0a25b0d2d222.png)

**Comment by carolineBda** [comment]
**Étape Salaire**

Les infos ici : https://docs.google.com/spreadsheets/d/1ZbI-kE3CvP1UmwL4TJau3l_LAOrEo3UcRFZpXov4PoM/edit#gid=0

Il vaut mieux commencer par les CC "SIMPLE"

 - on implémente le code du travail par défaut comme actuellement 

La colonne "Cas de figure"
 -  toutes les CC indiquées "renvoi implicite/explicite aux dispositions légales" => rien à faire on affiche le code du travail
 - "L'IDCC prévoit une méthode de calcul spécifique/spécifique simplifié" => nuance sur la formule de calcul
-  la méthode de calcul peut différer pour une même CC en fonction des autres réponses (colonnes E, F et G)

La colonne "Phrase à afficher au moment du calcul du Sref (colonne I)"  : 
- notification à afficher sur la page de résultat

Conclusion : pour l'utilisateur l'UI ne change pas, on demande bien les 12 derniers salaires (si différent sur les 12 dernier mois)

**Comment by carolineBda** [comment]
Prochaine étape :
 - on part sur l'écriture de publicode avec :
    - on gère l'ancienneté avec les absences prolongées tel que c'est actuellement (en js)
 	- le salaire en question hardcodé (ok pour l'affichage ?  On créé un type CDTN ?)
 	- pour chaque règles on rajoute dans le type cdtn la step à laquelle elle doit s'afficher
 	- On ajoute 2 steps 
 		- CC	
 		- "Informations" (optionel): pour les 

 ```
contrat salarié . salaire annuel:
  titre: Salaire mensuel
  question: Le salaire mensuel brut a-t-il été le même durant les 12 derniers mois précédant la notification du licenciement ?
  cdtn:
    type: oui-non

contrat salarié . salaire annuel . total:
  applicable si: contrat salarié . travailleur annuel

contrat salarié . salaire mensuel:
  valeur: salaire annuel = non

contrat salarié . salaire mensuel . janvier:
  titre: Salaire mensuel janvier
  question: Salaire mensuel brut du mois de janvier ?
  unité: euro
  cdtn:
    type: entier
    
contrat salarié . salaire mensuel . février:
  titre: Salaire mensuel février
  question: Salaire mensuel brut du mois de février ?
  unité: euro
  cdtn:
    type: entier
  ...
 ```



ou alors
- on réfléchit des maintenant à comment gérer l'ancienneté dynamiquement ?

Il y a-t-il d'autres point à vérifier avant de commencer ?

**Comment by carolineBda** [comment]
- [ ] créer un module CDTN spécifique pour le salaire mensuel (12 mois) - Caro
- [ ] comment gérer l'ancienneté par CC - en attente d'Axel
- [ ] comment on gère le blocage du simulateur (exemple "faute grave")*
- [ ] regarder si on peut améliorer l'implémentation des states sur le simulateur - Max

Questions pour Axel : 
- il y a-t-il des cas pour lesquels il faut un truc différent du "salaire mensuel brut a-t-il été le même durant les 12 derniers mois précédant la notification du licenciement ? (obligatoire)" ? Par exemple **1483**, **1404**
- comment est géré le temps partiel ? Pour le code du travail ? Et pour les CC ?
	=> seulement si alternance sur les 12 derniers mois de temps partiel / temps plein : le salaire de ref diffère 
    => pour l'instant pas de spécificité par CC (à confirmer une fois étude terminé)
- ancienneté 
	=> pour l'instant on attends
- variation travailleur handicapé ?
	=> pas d'influence sur le legal ni sur les CC

Il nous faudrait la de **calcul formule global** (excel ?)

**Comment by maxgfr** [comment]
Je passe sur l'amélioration du state du coup

**Comment by carolineBda** [comment]
**Need refactor**

- [ ]   rendre `seniorityMaximum` et `seniorityValue` optionel sur le [FormContent](https://github.com/SocialGouv/code-du-travail-numerique/blob/1936fc10d54010580fb127926c413212e620dfe3/packages/code-du-travail-frontend/src/outils/common/type/WizardType.ts#L45)
- [ ] rendre le handler generic:
	- supprimer l'utilisation de la method [convertDaysIntoBetterUnit](https://github.com/SocialGouv/code-du-travail-numerique/blob/1936fc10d54010580fb127926c413212e620dfe3/packages/code-du-travail-frontend/src/outils/publicodes/Handler.tsx#L42) - déplacer dans le préavis de retraite ?
	- enlever la [unit par défaut](https://github.com/SocialGouv/code-du-travail-numerique/blob/1936fc10d54010580fb127926c413212e620dfe3/packages/code-du-travail-frontend/src/outils/publicodes/Handler.tsx#L32) ?
	- rendre optionel [valueInDays](https://github.com/SocialGouv/code-du-travail-numerique/blob/1936fc10d54010580fb127926c413212e620dfe3/packages/code-du-travail-frontend/src/outils/publicodes/Handler.tsx#L34) - idem sur [publicodes/index.tsx](https://github.com/SocialGouv/code-du-travail-numerique/blob/1936fc10d54010580fb127926c413212e620dfe3/packages/code-du-travail-frontend/src/outils/publicodes/index.tsx)
- [ ] rendre customisable [mapToPublicodesSituation](https://github.com/SocialGouv/code-du-travail-numerique/blob/1936fc10d54010580fb127926c413212e620dfe3/packages/code-du-travail-frontend/src/outils/publicodes/Utils.ts#L10) (ou laisser chaque Wazrd fournir son implémentation spécifique


**Questions qui me reste à éclaircires**
j'appel qu'une seule fois `setSituation` et `execute("contrat salarié . indemnité de licenciement")` sur la page résultat
```
  useEffect(() => {
    publicodesContext.setSituation(
      mapToPublicodesSituationForPreavisDeLicenciement(formValues, salaireRef)
    );
    publicodesContext.execute("contrat salarié . indemnité de licenciement"); // Pourquoi ce n'est pas fait par le handler alors qu'on lui passe la régle cible
  }, [formValues]);
```
- C'est ok ?

- Comment on utilise `StepDynamicPublicodes` ?
- Si j'utilise l'ancienneté tel quel ça foncitonne mais j'ai le warning suivant (provient de publicodes):
```
 [ Avertissement ]
➡️  Dans la règle "contrat salarié . indemnité de licenciement"
⚠️  Erreur lors de la conversion d'unité explicite
ℹ️  Impossible de convertir l'unité 'mois.€' en '€'
```

**Comment by maxgfr** [comment]
@carolineBda ça dépend de quel endroit, mais il me semble que l'on avait corrigé ça (à confirmer avec @m-maillot), mais généralement, l'execution multiple vient du fait qu'à chaque render, le code se réexecute, s'il est pas géré dans un `usecallback` ou un `useeffect` avec des dépendances de re-render

**Comment by carolineBda** [comment]
Exemple d'Axel pour le temps partiel (il faut mettre des valeurs à moins d'un an):

	  Un salarié a travaillé 4 ans à temps plein puis 2 ans à mi-temps.
	  La rémunération mensuelle de ce mi-temps était égale à 1 500 € (soit un salaire de base de 3 000 € pour les années à temps plein)
	  
	  Le salaire de référence sera égal à :
	  
	  pour les années à temps plein : 3 000 × 4/6 = 2 000 € 
	  pour les années à temps partiel : 1 500 × 2/6 = 500 €
	  Soit un salaire moyen de référence égal à 2 500 €

**Comment by m-maillot** [comment]
J'ai terminé la passe sur le fichier Excel. J'ai fais une review sur ce qui avait déjà était fait et j'ai modifié une CC de NON à OUI car on doit exclure des primes dans la CC ce que l'on ne fait pas dans le CDT. Du coup, il faudra peut être avoir les 2 valeurs pour les primes. A voir avec Axel.
cc @carolineBda

**Comment by m-maillot** [comment]
# Retour sur l'analyse pour le calcul du Salaire de référence 

Pour rappel, l’étude s’est portée sur le document : https://docs.google.com/spreadsheets/d/1ZbI-kE3CvP1UmwL4TJau3l_LAOrEo3UcRFZpXov4PoM/edit#gid=0

## Code du travail  

> - soit S1/12 ou S2/mois dans l'entreprise 
> 
> S1 : total des salaires perçus lors des 12 derniers mois précédant le jour de l'envoi de la lettre de licenciement (brut) 
> S2 : total des salaires perçus précédemment à l'envoi de la lettre de licenciement si l'ancienneté est inférieure à 12 mois (brut) 
> 
> - soit 1/3*(S + ((P/12)*3)) 
> S : total des salaires perçus lors des 3 derniers mois précédant le jour de l'envoi de la lettre de licenciement (brut) 
> P : prime(s) ou gratification(s) de caractère annuel ou exceptionnel versée(s) pendant cette période (prise en compte prorata temporis)

Pour calculer le salaire de référence pour le code du travail, il est nécessaire d’avoir ces informations:
 * Le jour de l’envoi de la lettre de licenciement
 * Les salaires bruts des 12 derniers mois avant cette date (si reçu le 21 mai, on va demander les 12 derniers mois complets donc à partir d’avril)
 * Les primes ou gratification(s) de caractère annuel ou exceptionnel versée(s) sur les 3 derniers mois 

## Conventions collectives 

Pour le calcul sur les CC, on a pu identifier 3 cas de figure (colonne D):
* Calcul identique au code du travail
* Calcul identique à l’ancienne méthode du code du travail
* Calcul spécifique

Pour les 2 premières, nous n’avons pas identifié de comportement spécifique. On peut calculer le salaire de référence pour la CC via les informations récoltées pour le code du travail.

On va donc s’intéresser à la dernière : calcul spécifique. Celle ci concerne 25 CC.


### Modification de la date pour la demande des derniers salaires


On a identifié des cas où la date n’est pas **jour de l'envoi de la lettre de licenciement** comme pour le CDT. On a identifié 2 cas:

 * Date de fin du préavis (2596)  
 * Date de réception de la lettre de licenciement (176, 44)

  Il est important de prendre en compte cette information. Dans ce cas, il faut demander en plus les mois nécessaire pour faire le calcul de la CC.  Solution envisageable : Demande les dates et à partir de cette information demander les salaires supplémentaires dans la liste des X derniers salaires.  


### Information spécifique à la CC


On a identifié des cas où le salaire de référence est donné et/ou calculé à partir d’une information propre à la CC.

 * salaire perçu et convenu par les parties dans le contrat (1527)
 * salaire global brut mensuel contractuel visée à l'article 22-2 de l'avenant n° 88 du 11 janvier 2016 relatif à la modification de la convention collective suite à la nouvelle classification (1043)  
 * Nombre de mois passés dans l’entreprise précédant le début du préavis (réception de la lettre) (176)  
 * salaire versé avant le déclassement (176)
 * 13ème mois (2120)
 * total des sommes de cette rémunération variable sur les 12 derniers mois (2420, 2609)  
 * partie fixe du dernier mois et parties variables des 12 derniers mois (16, 44) 
 
Les informations peuvent être demandé dans un champ supplémentaire dans ces cas spécifiques. A l’utilisateur de calculer cette information.

**Challenge :** Aider l’utilisateur à comprendre et trouver l’information


### Demande de salaire sur des longues périodes


On a identifié des cas où le salaire de référence est donné et/ou calculé à partir d’une longue période de salaire.   
 
* Salaire brut de la première puis seconde et au-delà et jusqu'à l'expiration du préavis (1404)
* total des salaires perçus depuis le début de l'engagement (1404, 3239, 176)


### Cas spécifique à éclaircir  


* 105 jours d'indemnisation maladie (2148)
* En cas de modulation horaire, le calcul de l’indemnité de licenciement se fait sur la base de la rémunération lissée (2614 )
* total des 6 meilleurs salaires perçus consécutivement (29)

### Primes

On a identifié des notes portant sur l’inclusion ou l’exclusion de primes (1596, 1597, 1702, 1740). Ce point est à éclaircir car cela peut complexifier la saisie des informations pour l’utilisateur.  Aujourd’hui, on demande les primes pour le CDT, si on doit également les demander mais en soustrayant des primes non prises en compte pour la CC, cela peut être complexe pour l’utilisateur. 

**Important**: Un point a été relevé par Axel. Comment accompagner l’utilisateur dans l’extraction des informations dans sa fiche de paie. L’utilisateur risque par défaut de remplir ces salaires avec la prime car il va regarder le montant total sur sa fiche de paie. Au moment de la demande des primes, il risque de les renseigner une seconde fois. Il y a peut être une amélioration UX à réaliser sur cette partie (case ) cocher sur le salaire pour indiquer qu’il contient une prime ?)

**Comment by romain-b13** [comment]
### Excel (attention des filtres sont peut-être actifs) : https://docs.google.com/spreadsheets/d/1ZbI-kE3CvP1UmwL4TJau3l_LAOrEo3UcRFZpXov4PoM/edit#gid=0
### Klaxoon : https://app.klaxoon.com/join/RFXEGPE
