### ISSUE TITLE
Ajouter ligne entre les accordéons dans les contribs

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4218]
**Problème 1**
Dans les pages personnalisables (partie "que dit le code du travail") il n'y a pas de ligne entre les accordéons que cela soit une fiche SP qui est référencé ou que cela soit un contenu rédigé dans l'outil de contrib avec des balises tab pour les accordéons.
Suite à un test utilisateur on a pu voir que les ligne avit une importance entre les accordéons car elles permettent de mieux comprendre que les accordéons sont cliquables et qu'un contenu va apparaître en dessous.
Ex d'une contrib où c'est une fiche SP qui est intégrée : https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/contribution/combien-de-fois-le-contrat-de-travail-peut-il-etre-renouvele
Ex d'une contrib où c'est nous qui avons rédigé les accordéons en utilisant des balises tab dans l'outil de contrib : https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/contribution/quelle-est-la-duree-du-preavis-en-cas-de-demission

![image](https://user-images.githubusercontent.com/84397271/151595631-61f4a4f3-2fc5-4293-ba37-e408958be29d.png)

**Problème 2**
Le dernier accordéon dans les pages personnalisables est trop proche du cadre "références" ce qui induit l'utilisateur en erreur sur le fait de penser qu'il n'y a pas de contenu à ouvrir dans ce dernier accordéon

![image](https://user-images.githubusercontent.com/84397271/151596077-42a02cfe-ed74-49ad-b406-b23c8e256534.png)

**Solutions**
1) Ajouter les lignes entre chaque accordéon dans les pages personnalisables (partie "que dit le code du travail") comme c'est le cas dans les autres contenus du site, ex : 

![image](https://user-images.githubusercontent.com/84397271/151596834-a46e644d-9550-4475-b713-732b3e23f5d1.png)

2) Ajouter un espacement entre le dernier accordéon et le cadre "références"

**Comment by carolineBda** [comment]
@romain-b13 t'aurai un exemple de contrib qui génère ce code (depuis l'outil de contrib) ?

**Comment by romain-b13** [comment]
> @romain-b13 t'aurai un exemple de contrib qui génère ce code (depuis l'outil de contrib) ?

![image](https://user-images.githubusercontent.com/84397271/153417931-35986e14-c78b-4865-9bce-b74744911021.png)

![image](https://user-images.githubusercontent.com/84397271/153418672-08d8af7d-45c1-4011-96f3-3aa0cecea96f.png)

**Comment by romain-b13** [comment]
[Accordéons contrib.txt](https://github.com/SocialGouv/code-du-travail-numerique/files/8041590/Accordeons.contrib.txt)
