### ISSUE TITLE
CC implémentées dans l'outil heures pour recherche d'emploi mais considérées comme non traiteés 

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4224]
**Descripttion**
Voici 2 CC concernées par ce bug (d'autres le sont) : 
- Batiment etam (2609)
- Hotels cafés restaurants (1979)

Ces CC sont bine implémentées mais quand on sélectionne une de ces CC on arrive direct à l'étape résultat et on dit que la CC n'est pas traitée 

![image](https://user-images.githubusercontent.com/84397271/152136461-0be5f29d-e5e6-47e6-82b9-b33644368573.png)

**Comment by romain-b13** [comment]
C'est également le cas pour la 1672

**Comment by m-maillot** [comment]
* [ ] Mettre en place des TUs sur le bug pour ensuite tester les autres CCs
