### ISSUE TITLE
Rendre accessible les combobox

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4227]
**1) le bouton "voir plus"**
actuellement lorsqu'il y a plus de 5 résultats nous avons un bouton "voir plus" qui permet d'accéder aux autres résultats

Si on veut rendre accessible le bouton "voir plus" il faut (réponse de Maroua) :
- Ajoutez un "title" sur le bouton car l'intitulé est considéré comme pas pertinent "voir plus de quoi ??" => Facile

-  Au clavier, a chaque affichage des n résultats, il faut repositionner le focus sur la zone mise à jour => le point le plus important

**2) la scroll bar**

ajout d'une scroll bar dans les résultats => pour Maroua la solution de scroll est la plus facile à mettre en place et à manipuler côté lecteur d'écran, car cela va être un scrolle de liste qui est manipulable au clavier et à la souris 

![image](https://user-images.githubusercontent.com/84397271/152310619-83366988-fdd8-422d-bbe4-b1bb91b7d2fe.png)

**Problème rencontré avec la scroll bar**

![image](https://user-images.githubusercontent.com/84397271/152327751-4a5fc8d3-0268-4a82-90f2-ba574f5df6b0.png)

- la fenêtre de résultat ne prend plus toute la largeur (ne va plus jusqu'au CP)
- quand on fait une recherche d'entrprise et que l'on va ensuite saisir le CP la liste des résultats d'entrprise disparaît 

**Actuellement voici le comportement :** 

![image](https://user-images.githubusercontent.com/84397271/152327115-3b39e1aa-48e9-457e-adb1-e8b7cee9628b.png)

**Comment by carolineBda** [comment]
# Compte rendu Dr Design

Il faut regarder les stats pour identifier :
- nombre d'utilisateurs qui trouvent sans le code postal
- nombre d'utilisateurs qui trouvent dans les 5 premiers résultats
- nombre qui ne trouvent pas leur entreprise (avec les queries associées)
- nombre d'utilisateurs qui ont cliqués plusieurs fois sur "voir plus"

## Remarques générales

- "Voir plus" => mauvaise solution si trop de résultats :
  - soit scroll
  - soit pagination
- Affichage des variations pas forcément pertinentes
  - "Cara" si on tape "Zara"
  - juste gérer les "s" à la fin, les accents, ...
- Bouton de recherche pas obligatoire mais dans ce cas il faut être sur des labels d'accessibilités pour spécifier que les 2 champs filtres et que la zone d'affichage de résultats correspond à cette recherche => possibilité de demander de l'aide sur channel "domaine-accessibilité"
- si on rajoute un bouton de recherche :
  - pas grave si un bouton à cliquer en plus car ce parcours n'est fait qu'une seule fois par utilisateurs
  - pas grave si parcours différent de parcours "je connais ma CC"
  - éventuellement si après investigation c'est pertinent, afficher en plus le dropdown si seulement "3" résultats
- afficher toujours message "je ne trouve pas mon entreprise" à la fin de la liste (notamment pour inciter à utiliser le siret)

## 2 Solutions possibles
### On garde la solution actuelle qu'on rend accessible
- dommage de recoder nous même toute l'accessibilité 
- il faut gérer autrement le "voir plus"
### On rajoute un bouton "search"
- fonctionne pour tout le monde
- est facilement accessible 
- c'est ce que fait [Signal Conso](https://signal.conso.gouv.fr/cafe-restaurant/le-commer%C3%A7ant)
![Screenshot from 2022-02-14 11-44-14](https://user-images.githubusercontent.com/4971715/153849391-fb51edd2-d3a4-4e3f-a3f8-5e781163ab46.png)

**Comment by carolineBda** [comment]
Je rajoute à la discussion les notes envoyés par Dr Design : https://pad.incubateur.net/xR0XGJOWQBW0TktyfNohzg#

**Comment by carolineBda** [comment]
Lors de l'implémentation, il faudra veiller à extraire dans `outils/common` les composants utiliser dans les parcours trouver ma CC (aujourd'hui on utilise ceux présent dans `outils/ConventionCollective`

**Comment by romain-b13** [comment]
### CR point du 28/04/2022

### Contexte
1) le composant pour la recherche de CC est accessible car il n'y a qu'un champ (il faut juste remplacer le bouton "voir plus" par la scroll bar
2) le composant de la recherche entreprise (parcours "je ne connais pas ma CC") n'est pas accessible car on ne peut pas lier la zone de résultat à 2 hamps (nom entreprise + CP). Dans la combobox actuelle, les résultats change lors de la saisie d'un CP.

### Solutions
1) pour la recehrche de CC on garde la combobox actuelle
2) pour la recherche d'entreprises : 

a. Si on considère que l'auto complétion avec l'ajustement des résultats au cours de la saisie est une fonctionnalité essentielle pour l'utilisateur => on laisse la combobox actuelle sans la rendre accessible
b. On met un bouton de recherche (pas de résultat visible ni de suggestions tant qu'on a pas lancer de recherche)
c. On met un bouton de recherche en ajoutant les suggestions qui évoluent au cours de la saisie : 
l'exemple de page jaune est plutôt pas mal : bouton de recherche + suggestions au cours de la saisie (avec max 5 suggestions)

![image](https://user-images.githubusercontent.com/84397271/165803654-aefb1a68-221d-4163-b1ce-43d0af3621f3.png)

![image](https://user-images.githubusercontent.com/84397271/165803767-7302875f-c4ad-4a10-bc06-fc08c4cbba3b.png)



/!\ : il faut penser à l'implémentation du nouveau parcours dans l'étape CC des simulateurs

Pour évaluer si l'auto-complétion (résultats directement disponibles au cours de la saisie) est utile => mettre en place le bouton de recherche (qui pemet d'accéder aux résultats) et voir si les utilisateurs font plusieurs recherches : on pourraient comparer :  le nombre d'entreprise_select/nombre de clics sur le bouton de recherche

**Comment by romain-b13** [comment]
### 1. Outil "Trouver sa convention collective"

### Parcours "je ne connais pas ma CC"

**1) Etape 1 : J'arrive sur le parcours "je ne connais pas ma CC"**

![image](https://user-images.githubusercontent.com/84397271/204516566-87bb345e-de9d-43d2-a21d-de53d5085125.png)


**2) Etape 2 : je renseigne le nom de mon entreprise sans renseigner de code postal**

![image](https://user-images.githubusercontent.com/84397271/204539851-9c89dfb9-2b05-4b37-85a6-473730fc1df8.png)

**3) Etape 3 : je lance la recherche**

![image](https://user-images.githubusercontent.com/84397271/204540035-0435a025-c5e1-4b33-8646-5623d8406c04.png)

**4) Variante : je renseigne le nom de mon entreprise + le code postal (ou la ville)**

**=> voir si couteux de proposer la sugegstion de recherche pour le CP** 

![image](https://user-images.githubusercontent.com/84397271/204542171-ef16b6b0-547e-4ca1-a850-ab653ed5a730.png)

**4.bis) Je lance la recherche avec l'entreprise + le CP**

![image](https://user-images.githubusercontent.com/84397271/204542363-5d61ada8-d167-4ab7-b6fc-7d5eca76dfb6.png)

### 2.Etape "convention collective" des simulateurs

![image](https://user-images.githubusercontent.com/84397271/204549826-f9c7c594-042d-415c-ba52-47833c750b86.png)


**Voir si pour les simulateurs on opte pas plutôt pour l'UI ci-dessous : mais attention comment ça s'affiche en mobile**


![image](https://user-images.githubusercontent.com/84397271/204550474-0b88e3bd-b9b4-42b4-a663-63153f937b7e.png)
