### ISSUE TITLE
Mauvais url dans les événements de tracking

### ISSUE THREAD

**Issue by Armandgrd** [SocialGouv/code-du-travail-numerique#4232]
**Description**
mauvais urls dans les events de tracking

**Reproduction**
ouvrir l'onglet developer de son browser onglet network
Aller dans la search: taper "indemnité licenciement"
 clicker sur l'outil indemnité de licenciement: observer l'évenèment view-step, l'url tracké  est toujours celui de la page précédente (search).  voir capture

**Comportement attendu**
url de l'outil reporté dans le tracking

**Screenshots**
![image](https://user-images.githubusercontent.com/61156889/153029835-a21b1928-7bbd-4f75-82ac-56c6e86c1dde.png)

**Comment by Armandgrd** [comment]
ping @maxgfr j'ai essayé de décrire le comportement décrit ce matin, je pense que c'est effectivement lié à l'état de l'application,il semblerait que le matopush est appelé avant le changement d'état du site. 

voici les évènements qui surviennent sur une page outil:
outil                    49859 (ok)
cc_search                18726 (ok)
visit_content            17730 (ok)
cc_select                 5983 (ok)
select_related            2003 (pas de reco sur les outils: pas normal)
result_candidates         1355 (évènement lié à la search (pas normal))
cc_search_help             764 (OK)
feedback                   342 (OK)
contact                    248 (OK)
suggestion_candidates      126
select_suggestion          126
feedback_category           33
clic_share                  28
feedback_suggestion         19

N'hésite pas si t'as besoin de plus d'infos

**Comment by romain-b13** [comment]
@FabienRoussel devra sûrement modifier la méthode de calcul des KPI quand cette issue aura été traitée

**Comment by romain-b13** [comment]
1 jour max dédié à cette issue pour le sprint n°3

**Comment by maxgfr** [comment]
UPDATE: à tester et à voir si on peut l'appliquer à `matomo-next` de la fabrique

**Comment by carolineBda** [comment]
PR ouverte sur `matomo-next` : https://github.com/SocialGouv/matomo-next/pull/72

**Comment by carolineBda** [comment]
Pour info la PR a été mergé : https://github.com/SocialGouv/matomo-next/pull/72
On peut donc terminer cette carte
