### ISSUE TITLE
Reporter un bug

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#4234]
## Description

Liens morts vers les SDR 

## Liste

```
 "8": {
    "name": "ARDENNES",
    "url": "https://grand-est.dreets.gouv.fr/Renseignements-en-droit-du-travail"
  },
67": {
    "name": "BAS-RHIN",
    "url": "https://grand-est.dreets.gouv.fr/Renseignements-en-droit-du-travail-18663"
  },
  "68": {
    "name": "HAUT-RHIN",
    "url": "https://grand-est.dreets.gouv.fr/Renseignements-en-droit-du-travail-18664"
  },
  "974": {
    "name": "LA REUNION",
    "url": "https://reunion.deets.gouv.fr/Nous-contacter,8384"
  },
```

## Checklist

 * [x] Ardennes -> https://grand-est.dreets.gouv.fr/La-DDETSPP-des-Ardennes
 * [x] BAS-RHIN -> ???
 * [x] HAUT-RHIN -> ???
 * [ ] LA REUNION -> ???

cc @romain-b13 @carolineBda

**Comment by romain-b13** [comment]
BAS-RHIN : https://grand-est.dreets.gouv.fr/Presentation-de-la-DDETS-67-Nous-contacter
HAUT-RHIN : https://grand-est.dreets.gouv.fr/La-DDETS-du-Haut-Rhin

LA REUNION : le site est inacessible

**Comment by maxgfr** [comment]
modification effectuée : https://github.com/SocialGouv/code-du-travail-numerique/pull/4240

**Comment by maxgfr** [comment]
Pour la Réunion, c'est juste le certificat qui n'est pas à jour, l'url est bonne
