### ISSUE TITLE
Nouveaux contenus n'apparaissent pas dans kibana

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4243]
### Problème
Les nouveaux contenus (ceux qui n'existaient pas les 2 mois précédents le mois en cours) n'apparaissent pas dans les dashboard kibana

Ex : dans le top 10 des contenus du mois de janvier les contenus suivants n'apparaissent pas, alors que sur Matomo on voit bien qu'ils sont dans le top 10 : 
- https://code.travail.gouv.fr/modeles-de-courriers/demande-de-versement-de-lindemnite-inflation
- https://code.travail.gouv.fr/information/indemnite-inflation-infographies

**Top 10 des contenus sur kibana :** 

![image](https://user-images.githubusercontent.com/84397271/153262858-046990be-cf88-4f94-aae5-a7246535aa92.png)

https://cdtn-logs-kibana.fabrique.social.gouv.fr/app/dashboards#/view/47216e40-1ded-11eb-897c-cde847a9d698?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))

**Sur matomo :** 

![image](https://user-images.githubusercontent.com/84397271/153263405-ed9c882e-2f0a-454d-a8ac-dfe3c3fae719.png)

https://matomo.fabrique.social.gouv.fr/index.php?module=CoreHome&action=index&idSite=4&period=day&date=yesterday&updated=1#?idSite=4&period=month&date=2022-01-15&segment=&category=General_Actions&subcategory=General_Pages

**C'est pareil si on regarde le top des conventions collectives :** 
Une CC a été mise en ligne en décembre et est devenue la CC la plus visitée au mois de janvier, or elle n'apparait pas dans le top 10 des CC sur Kibana

**Top 10 des CC sur kibana :** 

![image](https://user-images.githubusercontent.com/84397271/153263809-21dcddaf-2e37-4ec4-bb07-b59686689b66.png)

https://cdtn-logs-kibana.fabrique.social.gouv.fr/app/dashboards#/view/47216e40-1ded-11eb-897c-cde847a9d698?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))

**Top 10 des CC sur Matomo :**

![image](https://user-images.githubusercontent.com/84397271/153264067-9836069b-75cf-4d1a-b6f8-99bc793944b6.png)

https://matomo.fabrique.social.gouv.fr/index.php?module=CoreHome&action=index&idSite=4&period=day&date=yesterday&updated=1#?idSite=4&period=month&date=2022-01-15&segment=&category=General_Actions&subcategory=General_Pages

**Comment by FabienRoussel** [comment]
Hello Romain, la PR qui résout ce problème est la suivante : 
https://github.com/SocialGouv/cdtn-monolog/pull/169
