### ISSUE TITLE
Nb de visites de certains contenus et classement différent entre Matomo et kibana

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4244]
**Problème**
Au delà du fait que les contenus créés recemment (et donc pas présents les 2 mois précédents) n'apparaissent pas dans les contenus populaire sur kibana on observe des contenus qui apparaissent plus populaires que d'autres alors que ce n'est pas le cas (ils bénéficient de visites supplémentaires sur kibana par rapport à Matomo)

**Exemple concret :** 
=> on voit ci dessous que dans kibana le contenu "outils/convention collective" est devant les contenus "contribution/en-cas-darret-maladie-du-salarie-lemployeur-doit-il-assurer-le-maintien-de-salaire" et "modeles-de-courriers/rupture-de-periode-dessai-a-linitiative-de-lemployeur" car 12 491 sont attribuées à "outils/convention collective" sur kibana. Or sur Matomo  "outils/convention collective" n'a que  10 448 visites et se retrouve donc derrière les 2 autres contenus cités en termes de popularité 

**TOP 10 des contenus de janvier sur kibana :**

![image](https://user-images.githubusercontent.com/84397271/153392999-1c7c9e56-e3f8-4382-a431-aac0c70337ab.png)

https://cdtn-logs-kibana.fabrique.social.gouv.fr/app/dashboards#/view/47216e40-1ded-11eb-897c-cde847a9d698?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))

**TOP 10 des contenus de janvier sur matomo :**

![image](https://user-images.githubusercontent.com/84397271/153394605-211cc140-316a-4e4f-bf69-89dce21f11f8.png)

https://matomo.fabrique.social.gouv.fr/index.php?module=CoreHome&action=index&idSite=4&period=day&date=yesterday&updated=1#?idSite=4&period=month&date=2022-01-08&segment=&category=General_Actions&subcategory=General_Pages

**Comment by romain-b13** [comment]
Analysé de Fabien : 
**Sur matomo on distingue** : 
![image](https://user-images.githubusercontent.com/84397271/154311531-f9ad34b2-215b-4ab5-867d-0e5931d4464f.png)

### ET

![image](https://user-images.githubusercontent.com/84397271/154311662-eb62f059-5b36-4674-aa87-bed4d59f4f39.png)

Quand on construit le dash kibana on enlève ce tout ce qu'il y a après le # et donc on additionne les visites des URL https://code.travail.gouv.fr/outils/convention-collective#selection + les visites de l'url https://code.travail.gouv.fr/outils/convention-collective pour donner le nombre de visites de l'outil "trouver sa convention collective"


### Action 1
voir si c'est compté comme 2 visites le faite d'aller d'abord sur https://code.travail.gouv.fr/outils/convention-collective puis sur  https://code.travail.gouv.fr/outils/convention-collective#entreprise 
=> si le fait d'avoir étape sur la page suivante du même outil me compte sur kibana comme 2 visites il faudrait dédupliqué quand il s'agit d'un même visiteur
=> il ne semble pas possible d'arriver directement sur https://code.travail.gouv.fr/outils/convention-collective#entreprise puis 

### Solutions potentielles pour la suite
- Faire une règle spécifique pour outil/convention collective : quand il y a un # le conserver au lieu de l'enlever afin de ne prendre en compte seulement les visites de l'url https://code.travail.gouv.fr/outils/convention-collective

- Potentiellement essayer de comprendre pourquoi on a un diez et non un / dans l'url

**Comment by FabienRoussel** [comment]
Dans src/analysis/popularity.ts, dans la fonction analyse le code qui permet de retirer l'ancre d'un url est réalisé après le groupby. Or, il faudrait retirer l'ancre avant le groupby. 

Problème => ca casse (totalement) le fonctionnement de la méthode qui donne donc des résultats incohérents.

Des tests unitaires et d'intégrations ne permettent pas d'identifier la cause du problème.

Des tests de caractérisations pourraient aider : https://youtu.be/q11gydDAMSo 

Pour le moment on dépriorise l'issue car faible impact pour beaucoup de temps investi
