### ISSUE TITLE
Des recherches n'apparaissent pas dans le top des recherches sur Kibana

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4245]
**Problème**
Des recherches populaires n'apparaissent pas dans le dashboard "recherches populaires" de kibana alors qu'elles ont une fréquence sur Matomo plus élevée que d'autres recherches qui apparaissent dans le dashboard "recherches populaires" de kibana.

**Exemple :** 
Sur Matomo on voit que la recherche "salaire minimum" a été recherchée 681 fois, elle n'apparaît pourtant pas dans les recherches populaires sur kibana alors que dans kibana on voit qu'à partir de la 4eme recherche la plus populaire leur nombre est inférieur à 681.
On peut faire le même constat pour les recherches "3239" et "assistante maternelle".

**Recherches populaires du mois de janvier sur Kibana** 

![image](https://user-images.githubusercontent.com/84397271/153396338-a1a54420-ff8b-4a2e-9aa4-a5f9d810516e.png)

https://cdtn-logs-kibana.fabrique.social.gouv.fr/app/dashboards#/view/47216e40-1ded-11eb-897c-cde847a9d698?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))

**Recherches populaires du mois de janvier sur Matomo**

![image](https://user-images.githubusercontent.com/84397271/153397407-549c25b2-22df-4c90-b203-24ae43fd366d.png)

https://matomo.fabrique.social.gouv.fr/index.php?module=CoreHome&action=index&idSite=4&period=day&date=yesterday&updated=1#?idSite=4&period=month&date=2022-01-08&segment=&category=General_Actions&subcategory=Actions_SubmenuSitesearch

**Comment by FabienRoussel** [comment]
Correction faite :)

<img width="882" alt="Capture d’écran 2022-02-21 à 14 48 58" src="https://user-images.githubusercontent.com/25366608/154967568-dde0daf4-9771-4f8d-af91-4fbd0df7c82f.png">

On observe toujours que "assistante maternelle" n'est pas présent dans le top dans la capture d'écran
La raison est qu'elle est regroupée sous l'item 3239 car ces deux éléments traitent du même sujet.

**Comment by romain-b13** [comment]
1- Pour le mois de février on observe également que la requête "congés payés" n'est pas présente dans le top des recherches sur kibana alors que sur matomo on voit que cette recherche est plus sollicité que la 3eme dans le classement kibana, donc elle devrait bien apparaître dans le top des recherches sur kibana

Lien du dashboard kibana (il s'agit du graph "Top Recherches 3 derniers Mois") : https://cdtn-logs-kibana.fabrique.social.gouv.fr/app/dashboards#/view/47216e40-1ded-11eb-897c-cde847a9d698?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))

Lien sur matomo : https://matomo.fabrique.social.gouv.fr/index.php?module=CoreHome&action=index&idSite=4&period=day&date=yesterday&updated=1#?idSite=4&period=month&date=2022-02-09&segment=&category=General_Actions&subcategory=Actions_SubmenuSitesearch

![image](https://user-images.githubusercontent.com/84397271/159453826-b38a7aa4-f35d-4b60-b44b-61656d50737e.png)


2- on observe également des requêtes pour lesquels il n'y a aucune visite pour l'un des 2 mois précédent (ce qui paraît étrange) 
Ex : requête "préavis" n'a aucune visite pour janvier d'après Kibana

![image](https://user-images.githubusercontent.com/84397271/159453291-a75c3e28-ce07-486a-b4e3-fc92e27d8593.png)

**Comment by FabienRoussel** [comment]
Résolution 1 - Pour le "congés payés" n'apparaissant dans le top des recherches, j'ai eu un peu de mal à reproduire, mais c'était finalement assez simple d'un point de vue code. En gros, si c'était la première recherche qui avait été réalisée dans le mois, alors elle avait pour index 0 dans le cache des requêtes. Dans le code on vérifiait que l'indexe était toujours strictement supérieur à 0


Résolution 2 - En solution j'ai fait une sorte de dictionnaire des synonymes de requête basé sur le premier mois, du coup si pour le premier mois la requete durée de préavis est plus fréquente que préavis alors on mettra durée de préavis pour les 2 mois suivants

Donc le seul impact que j'ai identifié c'est que d'un mois à l'autre, le titre d'un contenu populaire (par exemple "préavis") peut varier

Mais en général ce sera facile à se dire que c'est la même chose
