### ISSUE TITLE
Refacto du handler

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4247]
**Description**
En fonction de la discussion sur la state globale voir si refacto du handler ou autre tâches

**Comment by maxgfr** [comment]
La mise en place de zustand est trop énergivore à cause de la réécriture de certains composants (pour enlever l'oriented dependances faites par final-form) et rajoute de la complexité entre les anciens simulateurs et les nouveaux

**Comment by maxgfr** [comment]
Ce qui est à creuser néanmoins, est la division des tâches entre la partie UI et la partie métier (interprété par le frontend)

**Comment by maxgfr** [comment]
A la base, le nom de l'issue était Refacto du Handler, je remets le titre initial sur cette tâche

**Comment by maxgfr** [comment]
Mettre en place un store global ou un provider au sein des simulateurs est assez similaire.

En fait, le Provider est utilisé par les store globaux aussi. Le but étant de wrapper les composants métiers et d'y appliquer les modifications métiers à l'extérieur.

C'est ce qu'on fait avec le PublicodesContext, du coup on peut rester sur l'api de base de React de Context sans nécessairement passer par un state global a la redux ou zustand. La valeur ajoutée est assez marginale, et cela nous permet d'éviter d'avoir trop de dépendances.

En revanche, je suis toujours convaincu que passer par `react-final-form` est une limite du système. Mais cela ne vaut pas coup de le traiter dans cette issue
