### ISSUE TITLE
Gérer le cas des questions déclinables par branche

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#425]
comment éviter d'avoir des doublons lors de la remontée de resultats dans elasticsearch 

Ex: 50 déclinées sur 50 branches pros...

**Comment by revolunet** [comment]
ça implique :

 - d'afficher une seule fois la question dans les résultats
 - une fois la question sélectionnée, l'usager doit préciser les tags permettant de discriminer vers la bonne réponse (ex: préciser la branche ou autre critère discriminant)

**Comment by revolunet** [comment]
pris en charge dans la page "contribution"
