### ISSUE TITLE
On n'affiche pas le message d'erreur dans les simulateurs

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#4253]
**Description**

On n'affiche pas de message d'erreur sur les steps dynamiques des simulateurs.

**Reproduction**
Etapes à suivre pour reproduire le bug

1. Se rendre sur un simulateur avec CC (préavis de retraite, préavis de licenciement...)
2. Choisir la CC 3239
3. Sur la page information,ne rien sélectionner et faire suivant

Le bouton suivant est grisée

**Comportement attendu**

Un message indiquant que le champ est obligatoire devrait être affiché.

**Screenshots**

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/992514/154284702-1728e8b9-8395-4877-9e12-bf0d1be092e5.png">

Si on répond à la question, on affiche la suivante mais le bouton reste grisée et aucun message n'apparait. On devrait réactiver le bouton.

**Comment by m-maillot** [comment]
Je pense qu'il manque juste la balise erreur sur les questions :) ça devrait être plutôt simple à corriger.

**Comment by carolineBda** [comment]
Une fois corrigé, il y a ce test à décommenter ou supprimé (si on a écrit un test avec react testing library) : https://github.com/SocialGouv/code-du-travail-numerique/blob/dev/packages/code-du-travail-frontend-e2e/codecept/features/outils/preavis-retraite.feature#L120

**Comment by maxgfr** [comment]
Pour info, sur l'indemnité de licenciement, on affiche bien un message d'erreur

**Comment by maxgfr** [comment]
Egalement pour l'indemnité de précarité 🤪
