### ISSUE TITLE
URL en 404 vers laquelle on renvoi dans l'outil indemnité de licenciement

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4274]
### Contexte
Dans l'outil "indemnité de licenciement" lorsque l'on arrive à l'étape "contrat de travail" si à la première question on coche la réponse 
"Contrat à durée determiné (CDD) ou contrat d’intérim" lorsque l'on clique ensuite sur suivant, le message suivant s'affiche :
![image](https://user-images.githubusercontent.com/84397271/156325799-3ead74aa-8e9e-40bb-85ff-1680db39abaa.png)

### Problème

L'URL sous "indemnité de précarité (nouvelle fenêtre)" est en 404

### Solution
Remplacer le lien actuel par le lien ci-dessous : 
https://code.travail.gouv.fr/fiche-service-public/le-salarie-touche-t-il-la-prime-de-precarite-a-la-fin-dun-contrat-de-travail

**Comment by carolineBda** [comment]
EN profiter pour corriger l'attribut "rel" de l'anchor aujourd'hui il y a :
`el="noopener noreferrer"`
