### ISSUE TITLE
BUG:FAQ: remontée étrange des suggestions à la saisie sur le site

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#428]
![image](https://user-images.githubusercontent.com/37538697/51249923-33b78f00-1995-11e9-9780-e79ab3ef38fc.png)
 remontée visibles par les users des tags sur une faq

**Comment by jrduscher** [comment]
autre exemple du même type : https://codedutravail-dev.num.social.gouv.fr/question/je-souhaite-embaucher-des-salaries-pour-la-saison-quelles-sont-les-formalites-dembauche-a-accomplir?q=cout%20embauche&search=0

![image](https://user-images.githubusercontent.com/37538697/51831366-3cdc2080-22f2-11e9-91f7-4ebcf8177670.png)

**Comment by lionelB** [comment]
je ferme car on ne cherche plus dans les tags suite au modification faite dans elasticsearch 
cf PR #461
