### ISSUE TITLE
Mettre en place les tooltip dans les outils

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4282]
**Contexte**
Les tooltip ne sont pas gérer dans les simulateurs

**Problème**
Quand des termes "juridiques" tels que "indemnité légale" apparaissent aucune info ne permet de guider l'utilisateur.

**Solution**
Gérer les tooltips dans les simulateurs 

1) on va faire au plus simple dans un premier temps : c'est à dire mettre les tooltip partout (pas de distinction que le mot soit présent dans l'intro, dans une question etc.)
2) question : est-on capable facilement de n'afficher qu'une seule fois le tooltip lorsque dans une même page le mot est présent plusieurs fois ?

**Comment by romain-b13** [comment]
Par la même occasion on peut voir pour : 
- ajouter les tooltip dans les fiches SP
- voir si tooltip présents dans contrib sur "indemnités" mais non présent dans les pages CC est réglé

**Comment by m-maillot** [comment]
C'est une tâche complexe car aujourd'hui les simulateurs ne sont pas dans l'admin. On ne possède pas de solution pour faire du tooltip sur le client. 
Il faudrait procéder d'abord à une étude.

Pour les tooltips des fiches SP on peut les laisser dans la même issue je pense. Par contre, le bug sur indémnités est à placer dans une autre issue car c'est un bug.
