### ISSUE TITLE
Préciser le résultat donné lors du calcul d'un préavis

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4283]
**US**
En tant que salarié
Je souhaite savoir ce qui lance officiellement la préavis donné en résulat et quel jour se termine cette durée

**Solution**
Pour les simulateurs "préavis de licenciement" / "préavis de démission" / "préavis de départ ou de mise à la retraite" ajouté un astérisque au résultat pour préciser quand débute cette durée et donner un exemple permettant de comprendre quel jour se termine cette durée.

/!\ dans l'exemple donné, les dates doivent être adaptées en fonction du résultat donné. Ex : si l'utilisateur a obtenu un préavis de licenciement de 2 mois lors de la simulation alors l'exemple doit être : "Si le salarié reçoit le courrier recommandé le 22 avril alors il effectuera son dernier jour dans l’entreprise le **22 juin**" 
alors que si l'utilisateur a obtenu un préavis de licenciement de 1 mois lors de la simulation alors l'exemple doit être : "Si le salarié reçoit le courrier recommandé le 22 avril alors il effectuera son dernier jour dans l’entreprise le **22 mai**"

Les phrases à afficher sont dans le doc ci-joint :

[Precision.duree.preavis.3 (2).docx](https://github.com/SocialGouv/code-du-travail-numerique/files/8343982/Precision.duree.preavis.3.2.docx)

**Comment by m-maillot** [comment]
/!\ Certaines CC peuvent avoir ce genre d'information. Exemple la CC 2941 où l'on ajoute une notification indiquant `1 mois de date à date`. Du coup le calcul n'est peut être pas le même 🤔

**Comment by romain-b13** [comment]
[Precision.duree.preavis.3.2 - Version 14 avril 2022.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/8488390/Precision.duree.preavis.3.2.-.Version.14.avril.2022.docx)

**Comment by romain-b13** [comment]
### Les retours :

- Il manque un "s" à "travaillé" dans la phrase ci-dessous : 
"Les jours ouvrés sont les jours effectivement **travaillé** dans une entreprise ou une administration. On en compte 5 par semaine."
- Enlever l'exemple dès que le résultat est 1 jour  ou 1 jour ouvré que ce soit dans l'outil du préavis de démission ou du préavis de licenciement. Dans le cas de l'outil du préavis de licenciement il faut aussi la 2ème phrase : "Si le 23 avril tombe un samedi, un dimanche, un jour férié ou un jour qui n’est habituellement pas travaillé dans l’entreprise, le salarié effectuera son dernier jour dans l’entreprise le jour ouvrable suivant."
- Quand le résultat est "2 jours ouvrés" => ajouter un exemple : "_Exemple : si les jours travaillés dans l'entreprise sont du lundi au vendredi et que l’employeur reçoit le courrier recommandé le mardi alors le salarié effectuera son dernier jour dans l’entreprise le mercredi_
- Il manque le nom des jours "lundi" "mardi" etc dans les exemples où le résultat est en "semaines" ou en "en jours" ou en "jours calendaires" => par ex si le résultat est "15 jours" pour le préavis de démission, l'exemple doit être : _Exemple : si l’employeur reçoit le courrier recommandé le **lundi** 22 avril alors le salarié effectuera son dernier jour dans l’entreprise le **lundi** 6 mai._ 
- Dans le cas où le résultat est "1 mois et demi" l'exemple n'est pas bon : il est indiqué "il effectuera son dernier jour dans l’entreprise le 23 avril" alors que ça devrait être "il effectuera son dernier jour dans l’entreprise le 7 juin"

**Comment by romain-b13** [comment]
cf commentaire ci dessous

**Comment by romain-b13** [comment]
**MAJ du 11/05/2022** : 
- que ce soit pour le préavis de démisison ou le préavis de licenciement : enlever les jours "lundi", "mardi" etc. => à aucun moment on ne doit voir des jours
- Pour le préavis de démission ajouter à la suite de l'exemple en italique (ça fait partie de l'exemple) : "Si le _9 août_ tombe un samedi, un dimanche, un jour férié ou un jour qui n’est habituellement pas travaillé dans l’entreprise, le salarié effectuera son dernier jour dans l’entreprise le jour ouvré précédent"
- que ce soit pour le préavis de démisison ou le préavis de licenciement prendre le 5 avril en date de départ
- Quand le résultat est "X jours ouvrés" dans le préavis de démission, il ne faut pas mettre la phrase "Si le _9 août_ tombe un samedi, un dimanche, un jour férié ou un jour qui n’est habituellement pas travaillé dans l’entreprise, le salarié effectuera son dernier jour dans l’entreprise le jour ouvré précédent"
-  Quand le résultat est "X jours ouvrés" enlever pa phrase "_si les jours travaillés dans l'entreprise sont du lundi au vendredi et que l’employeur reçoit le courrier recommandé le mardi alors le salarié effectuera son dernier jour dans l’entreprise le mercredi._"
- Quand le résultat est "1 jour" ou "1 jour ouvré" on ne doit pas avoir d'exemple

**Comment by romain-b13** [comment]
### Préavis de démission

1) Il faut juste enlever le jour partout : 

![image](https://user-images.githubusercontent.com/84397271/168231786-f71be497-f785-4e8c-a8c9-7657e00c8397.png)

2) Pour les résultats en jours ouvrés (à l'exclusion de 1 jour ouvré pour lequel on ne met pas d'exemple) il faut ajouter la première phrase de l'exemple. Dans ce cas-ci, ce serait "_Exemple : si l’employeur reçoit le courrier recommandé le 5 avril alors le salarié effectuera son dernier jour dans l’entreprise le 6 avril._"

![image](https://user-images.githubusercontent.com/84397271/168232417-7206b128-9dcf-4e82-b6dd-e9fe9aaa052e.png)

### Préavis de licenciement

1)  Il faut juste enlever le jour partout : 

![image](https://user-images.githubusercontent.com/84397271/168240854-d7bff5d6-9e93-4ca4-9dd4-8a60b2aafff7.png)

2) Dans le cas où le résultat est "1.5 mois" la 2ème date de l'exemple n'est pas bonne => il faut remplacer 19 mai par 20 mai

![image](https://user-images.githubusercontent.com/84397271/168237542-06af40ca-1784-4d18-b8b4-62d5ebcb07f4.png)

3) Pour les résultats en jours ouvrés (à l'exclusion de 1 jour ouvré pour lequel on ne met pas d'exemple) il faut ajouter la première phrase de l'exemple. Par ex : "_Exemple : si le salarié reçoit le courrier recommandé le 5 avril alors il effectuera son dernier jour dans l’entreprise le 6 avril._"

**Comment by romain-b13** [comment]
Dans le cas ci-dessous au niveau du résultat ça ne doit pas être une "*" mais être "(1) (2)"

![image](https://user-images.githubusercontent.com/84397271/169348507-b7da3ea6-8e99-4cf2-9bf6-07defef9564f.png)
