### ISSUE TITLE
Renommer l'outil "heures pour recherche d'emploi"

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4284]
Nouveau titre pour l'outil : "Heures d'absence pour rechercher un emploi"
Description de la tuile : "Calculez le nombre d'heures d'absence autorisée pour rechercher un emploi pendant un préavis"

**Comment by m-maillot** [comment]
/!\ Attention, cela va impacter les events sur matomo  car on utilise le titre de l'outil.
