### ISSUE TITLE
[new parcours étape CC des outils] Modifier message "attention" et "Convention collective non traitée"

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4285]
### Contexte
Pour les outils "heures pour recherche d'emploi" et "préavis démission" le code du travail ne prévoit rien, donc si l'utilisateur passe l'étape de sélection de CC ou sélectionne une CC non traitée il n'aura pas de résultat
Pour ces deux outils il faut donc modifier :
- le message quadn l'utilisateur coche "je ne souhaite pas renseigner ma convention collective"
- le message quand l'utilisateur sélectionne une CC non traitée 

![image](https://user-images.githubusercontent.com/84397271/156879330-153e7c0c-d7cb-437a-bb10-c51dc7c84e2f.png)

![image](https://user-images.githubusercontent.com/84397271/156879334-2ccdd030-c944-40e2-9c62-701b5650d72f.png)

### Solution

- **Message quand l'utilisateur coche le parcours "je ne souhaite pas renseigner ma convention collective"**
"Le code du travail ne prévoit pas de durée de préavis de démission, nous vous recommandons de renseigner votre convention collective pour obtenir un résultat"

- **Message quand l'utilisateur sélectionne une CC non traitée**
"La convention collective sélectionnée n'est pas traitée par nos services. Nous vous invitons à consulter votre convention collective pour obtenir votre durée de préavis. En effet, pour votre information, la convention collective peut définir la durée du préavis de démission, le code du travail ne prévoit rien sur ce sujet."

**Comment by m-maillot** [comment]
C'est étrange de laisser le choix de passer cette étape ? Autant ne pas l'autoriser non ?
Si on a une CC non supporté, est ce que l'utilisateur peut aller sur l'écran de résultat ? Dans ce cas le message n'est peut être pas pertinent ici car on le répète sur Result.

**Comment by romain-b13** [comment]
### 1) Du coup : on enlève l'option du P3 pour les outils "préavis de démission" et "heures pour recherche d'emploi" mais on affiche une phrase à cette étape pour dire que la CC est nécessaire car il n'y a rien de prévu par le code du travail

**Préavis démisison :** 

![image](https://user-images.githubusercontent.com/84397271/159276327-5bb03e6a-1169-4b7e-8b70-7223a18a3a2a.png)


**Heures d'absence pour rechercher un emploi**

![image](https://user-images.githubusercontent.com/84397271/159276116-a4c09910-a30e-4af0-8698-02b78d96caeb.png)




### 2) quand un utilisateur sélectionne une CC non traitée : 

**a) messages à afficher**

- pour "préavis démission" : 

"La convention collective sélectionnée n'est pas traitée par nos services. Nous vous invitons à consulter votre convention collective pour obtenir votre durée de préavis. En effet, pour votre information, la convention collective peut définir la durée du préavis de démission, le code du travail ne prévoit rien sur ce sujet. Vous pouvez consulter votre convention collective ici"

=> sous le mot "ici" un lien vers la page de la convention collective sur legifrance. (sans recherche de mots clés => uniquement la page de la CC globale)


- pour "heures d'absence pour rechercher un emploi" : 

"La convention collective sélectionnée n'est pas traitée par nos services. Nous vous invitons à consulter votre convention collective pour voir si elle prévoit un nombre d'heures d'absence autorisée pour recharcher un emploi pendant un préavis.
En effet, pour votre information, la convention collective peut définir ce nombre d'heures, le code du travail ne prévoit rien sur ce sujet. Vous pouvez consulter votre convention collective ici"

=> sous le mot "ici" un lien vers la page de la convention collective sur legifrance. (sans recherche de mots clés => uniquement la page de la CC globale)

**b) on bloque le passage à l'étape suivante**

**c) on affiche le bloc bleu "attention" que l'on trouve habituellement à l'étape résultat**

- Préavis de démission :

![image](https://user-images.githubusercontent.com/84397271/159282851-d0dfe103-0b3f-4600-a436-7563d45c048a.png)

- heures d'absence pour recherche d'emploi :

![image](https://user-images.githubusercontent.com/84397271/159283046-28a51812-e577-40f3-a0b5-551260b03f38.png)

**Comment by romain-b13** [comment]
Si pas de page legifrance on enlève la phrase "Vous pouvez consulter votre convention collective ici"

**Comment by romain-b13** [comment]
### Mise à jour suite à la daily du 14/04 :

On affiche pas le bloc bleu "attention" tel qu'il est dans la page résultat.

On ajoute juste une phrase supplémentaire dans l'encadré "convention collective non traitée" : 

**Pour le préavis de démission**
L’existence ou la durée du préavis de démission peut également être prévue par un accord d’entreprise ou à défaut, par un usage dans l’entreprise.


**Heures d'absence pour recherche d'emploi**
Un accord d’entreprise ou à défaut un usage dans la profession ou l’entreprise peut également prévoir que le salarié bénéficie d’heures d’absence autorisée pour rechercher un emploi pendant le préavis.

**Comment by romain-b13** [comment]
### Modification du message dans l'encadré "Convention collective non traité"
**- pour "heures d'absence pour rechercher un emploi" :**
La convention collective sélectionnée n'est pas traitée par nos services. Nous vous invitons à consulter votre convention collective qui peut prévoir un nombre d'heures d'absence autorisée pour rechercher un emploi pendant un préavis. Vous pouvez consulter votre convention collective ici.
Un accord d’entreprise ou à défaut un usage dans la profession ou l’entreprise peut également prévoir que le salarié bénéficie d’heures d’absence autorisée pour rechercher un emploi pendant le préavis.

**- pour "préavis démission" :**
La convention collective sélectionnée n'est pas traitée par nos services. Nous vous invitons à consulter votre convention collective pour obtenir votre durée de préavis. Vous pouvez consulter votre convention collective ici.
L’existence ou la durée du préavis de démission peut également être prévue par un accord d’entreprise ou à défaut, par un usage dans l’entreprise.

**Comment by romain-b13** [comment]
### Pour le message d'erreur

Mettre : "La simulation ne peut pas se poursuivre avec cette convention collective"
