### ISSUE TITLE
Manque données de janvier dashboard kibana

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4289]
**Problème**
Dans le dashboard "Aggregated Monthly Reports" on voit que la data de janvier a disparu, notamment le nombre de visites mensuelles !

![image](https://user-images.githubusercontent.com/84397271/157092643-af028ee1-0bb9-42eb-9b11-b8a7405d19d2.png)

**Comment by romain-b13** [comment]
Je vois également ici que c'est le nombre de visites de décembre qui est indiqué ici, alors que ça devrait être celui de février : 
![image](https://user-images.githubusercontent.com/84397271/158029584-7f407170-03df-4c2c-a33a-3e358d683649.png)

**Comment by FabienRoussel** [comment]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/25366608/162209392-26e4cc33-e5da-4e0d-87d0-a92b0dd64a21.png">
rattrapage réalisé @romain-b13 je veux bien que tu valides le nombre moyen
