### ISSUE TITLE
Ajouter la date des commentaires utilisateurs

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4290]
**Fonctionnalité**
Dans le dashboard "Satisfaction Utilisateurs" : https://cdtn-logs-kibana.fabrique.social.gouv.fr/app/dashboards#/view/00c45a90-abe9-11eb-897c-cde847a9d698?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now)) nous avons un dash "Satisfaction - Commentaires utilisateurs (filter sur un contenu)" dans lequel nous souhaitons avoir une colonne supplémentaire avce la date à laquelle le commentaire a été laissé

**Comment by FabienRoussel** [comment]
Analyse : 
la date des commentaires n'est pas présente dans l'index elastic search, il faut repasser par une phase de développement

Je lève un petit drapeau jaune car je vois que si le job de satisfaction fail pour un mois, et qu'on s'en aperçoit pas avant le mois suivant, et bah on ne peut pas le relancer facilement à cause d'un filtre

**Comment by FabienRoussel** [comment]
La colonne qui comptait le nombre de commentaires qui étaient exactement le même a été remplacée par la dernière date (arrondi au dernier jours du mois) de publication du commentaire 

https://cdtn-logs-kibana.fabrique.social.gouv.fr/app/dashboards#/view/00c45a90-abe9-11eb-897c-cde847a9d698?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))

**Comment by romain-b13** [comment]
@FabienRoussel J'ai l'impression qu'il y a plusieurs soucis dans le dashboard "Satisfaction utilisateurs"

- date des commentaires ne fonctionne pas car j'ai les mêmes en février et mars
- les contenus sont classés par popularité mais les autres classement (top 10 des contenus dans le dashboard " ne sont pas les mêmes) => est-ce que le filtre par période fonctionne ?
