### ISSUE TITLE
Reduire l'espacement new parcours étape CC des outils

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4293]
**Problème**
Dans le parcours P2 (Je ne sais pas quelle est ma convention collective (je la recherche)) de l'étape "convention collective" des outils les epacements entre 2 "rubriques" sont les mêmes que les espacements entre le titre de la "rubrique" et son contenu : 
![image](https://user-images.githubusercontent.com/84397271/157435549-d8220b16-c46b-4e23-9aad-6e58c3b24584.png)

Ici la taille de l'espacement 1 est le même que l'espacement 2 alors que dans un cas (N°1) c'est l'espace qui sépare 2 composants différents de l'interface et dans l'autre cas (N°2) c'est l'espace entre 2 éléments du même composant

**Solution**
Je suggère donc de réduire l'espace N°2 (le passer à 10 px) afin que que l'espace N°2 soit < à l'espace N°1

**Comment by m-maillot** [comment]
Je crois qu'il y a un travail de clean sur les marges ici. On a par moment un titre avec un espace de 16 puis après 10. Cela casse le design system.
