### ISSUE TITLE
Erreur Hn dans les tabs

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#4296]
Si le tab n'est pas situé sous un Hn alors il démarre à H1. Il faut au minimum démarrer au H2.
![Screenshot from 2022-03-10 10-21-15](https://user-images.githubusercontent.com/4971715/157633288-fa43d82c-8822-4a8d-94fd-e19a04025ad4.png)

- https://code.travail.gouv.fr/fiche-service-public/periode-dessai-pour-un-salarie
- https://code.travail.gouv.fr/fiche-service-public/travail-et-covid-19-quelles-sont-les-regles
- https://code.travail.gouv.fr/contribution/a-quelles-indemnites-peut-pretendre-un-salarie-qui-part-a-la-retraite

**Comment by carolineBda** [comment]
C'est ici que ça se passe : https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/react-fiche-service-public/src/components/Tabulator.js#L17

**Comment by romain-b13** [comment]
ajouter des tests unitaires
