### ISSUE TITLE
R&D pour implémenter la partie salaire sur l'indemnité de licenciement

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#4297]
Suite au dernier point concernant le salaire, on a identifié des approches pour demander les salaires à l'utilisateur selon les CCs.

L'idée est d'effectuer une R&D sur publicodes afin de voir la faisabilité vs rester sur du code JS.

Voici les use cases à valider:

### Cas 1

* L'utilisateur renseigne ses 12 derniers salaires. 
* On lui pose la question si il a un préavis ou non.
* Si il n'a pas de préavis, on prend les 3 derniers mois sur les 12 derniers salaires
* Si il a un préavis, on va avoir de 1 à 3 salaires renseignés et on va devoir récupérer 1 à 2 salaires dans les 12 derniers.

Info: On va prendre le max des 3 derniers dans ce cas ci

### Cas 2

* Demander une information complémentaire sans relation avec le reste (comme le salaire de ref sur son contrat)

### Cas 3 

* Demander les 6 meilleurs salaires consécutives et avoir une option permettant de renseigner cette info à partir des 12 derniers salaires saisies

D'autres cas vont arriver rapidement avec la prochaine session.

**Comment by romain-b13** [comment]
- Quelle est la formule de calcul du Sref pour le légal ?
- Comment les primes sont prises en compte ?
- est-ce que le préavis est toujours de maximum 4 mois ?
- est-ce que pour une CC données on connait le maximum de mois que peut être le préavis ?

**Comment by m-maillot** [comment]
Salaire ref

1/ Pour chaque CC avec un salaire ref spécifique 
On va avoir une règle dans publicode:

```
contrat salarié . convention collective . boulangerie patisserie . indemnité de licenciement:
  remplace: contrat salarié . indemnité de licenciement collective
  valeur: salaire de référence * 3

contrat salarié . convention collective . boulangerie patisserie . salaire de référence:
  titre: Salaire de référence collective du salarié
  unité: €
  cdtn:
    step: salaire 
    front_rules: salaire_reference_boulangerie
```

Ici, on a un salaire de référence spécifique pour la boulangerie. 

2/ Ajouter la règle de calcul lié dans les modèles mais en TS

Dans `rules/indemnite-licenciement/salaire-references`, ajouter un fichier TS contenant la règle. On peut ainsi faire des tests unitaires sur la règle métier.

3/ Partie UI

Il faut maintenant gérer l’affichage pour demander les informations souhaitées à l’utilisateur.

On a 2 choses distinctes :

* Le légal
* La convention 

Dans le cas du légal, le code est en dur car c’est à toujours demander.

Dans le cas de la CC. On va lié la partie UI et les règles publicodes via l’attribut `front_rules` dans `cdtn`.

Sur la step salaire, on va récupérer dans les règles manquantes, les règles ayant la step salaire. 

On va avoir un composant UI pour chaque step salaire qui va avoir en charge le calcul du salaire de référence pour la convention. Elle va s’appuyer sur le fichier de règle dans la couche modèle.

Les questions seront posées à la suite.  

Etape pour ajouter le salaire de référence:
* Ecrire la règle publicode (cdtn -> front_rules)
* Ecrire le calcul en TS (méthode permettant de récup la règle via son cdtn -> front_rules)
* Créer le composant UI permettant de récupérer les infos supplémentaires voulues. Ce dernier va calculer le salaire conventionnel de référence et alimenter la variable dans le formulaire pour cette info.
* Lier le front_rules au composant UI
