### ISSUE TITLE
Améliorer l'intégration des nvx contenus dans le sitemap

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4304]
**Contexte**

### Cas Global : problème d'indexation des nouveaux contenus sur les moteurs de recherche (cas de Google)
On s'aperçoit à chaque création de nouveau contenu que les pages créée ne sont pas indéxées sur Google au bout de plusieurs jours voire plusieurs semaines tant que nous n'effectuons pas de demande d'indexation manuelle depuis la Google search console

### Cas n°1 : l'URL est indéxée mais n'est pas envoyée via un sitemap
On a vu avec l'outil "préavis de retraite" mis en ligne en novembre, qu'il n'était au départ pas du tout indexé sur Google (ce qui explique le très faible nombre de visites). Nous avons donc fait une demande d'indexation amnuelle depuis la Google search console.

Cependant, 3 mois après on voit que l'outil n'est pas envoyé par le sitemap (ce qui peut expliquer le nombre encore très faible de visites de l'outil) : 

![image](https://user-images.githubusercontent.com/84397271/158013995-711bd8e6-e09e-4bb1-9f4d-0d6e735ddd3a.png)

**A titre de comparaison voici les infos renvoyées par la google search console pour l'outil "préavis de démission" :** 

![image](https://user-images.githubusercontent.com/84397271/158014061-7bfa395b-367f-4de6-ad2a-0ea8ffc3f5fd.png)

### Cas n°2 : l'URL est indexée et envoyée mais aucune page d'origine n'est détectée
En prenant l'exemple de la page https://code.travail.gouv.fr/information/particuliers-employeurs-et-emploi-a-domicile-lessentiel-de-la-nouvelle-convention-collective mise en ligne en 2022, on voit qu'elle est indexée et envoyé mais dans la rubrique "page d'origine" on aperçoit "Aucune page d'origine détectée" =>

![image](https://user-images.githubusercontent.com/84397271/158014136-35327a3c-abc2-477f-9d92-57ae2fc721b5.png)

### Problèmes / Questionnement

1) L'intégration des nouveaux contenus dans le sitemap semble "défaillante"
2) Le point n°1 est-il la cause de la non indexation des nouveaux contenus sur Google ? 
3) En dehors de l'intégration des nouveaux contenus dans le sitemap, a-t-on d'autres leviers d'actions permettant d'indexer plus rapidement et automatiquement les nouveaux contenus (nouvelles pages) sur les moteurs de recherche ?

**Comment by romain-b13** [comment]
- Ajouter "outil préavis de retraite" sur l'admin

- Pour info dernier contenu éditorial mis en ligne le 22/03 : https://code.travail.gouv.fr/information/covid-19-reagir-en-cas-de-contamination-dans-lentreprise-infographies

**Comment by romain-b13** [comment]
- [x] Ajouter préavis retraite dans le sitemap
- [x] retirer la redirectyion sitemap.xml
- [x] après étude voir pour mettre une prio plus élevé pour nos contenus éditoriaux
- [x] passer pages glossaire en 0.5 prio
- [x] regarder s'il y a un call api

**Comment by carolineBda** [comment]
Je n'ai pas vu d'appel à l'API Google Search Console dans le code
