### ISSUE TITLE
Affichage du détails du calcul avec la CC avec publicodes

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#4317]
Dans le nouveau simulateur d’indemnité de licenciement, on utilise publicode pour afficher le détails du calcul

**Comment by romain-b13** [comment]
**Dans la rubrique "les éléments saisis", il y aura en plus les informations liées à la CC une fois que les CC seront implémentées :** 
Convention collective : 
Catégorie professionnelle : 
Échelon/Groupe : 
âge : 
....

**Il faudra ajouter une rubrique "Le résultat décrypté" :** 

Montant prévu par le code du travail (montant légal) : 1200€ brut
Montant prévu par la convention collective (montant conventionnel) : 1791,66€ brut

Le montant à verser au salarié est donc celui prévu par la convention collective, celui-ci étant plus favorable que le montant légal, c’est-à-dire plus élevé.

**Dans la rubique "Formule" (qui devidra "Formules") on ajoutera :** 
Formule utilisée pour calculer le montant prévu par le code du travail : 1/4×Sref×A
Formule utilisée pour calculer le montant prévu par la convention collective : 1/4×Sref×A   

![image](https://user-images.githubusercontent.com/84397271/159760277-fc9ef211-1304-47ba-bf64-f92434834b10.png)

**Comment by romain-b13** [comment]
Cette issue est liée aussi à https://github.com/SocialGouv/code-du-travail-numerique/issues/4314
=> à discuter ensemble au sprint planning

**Comment by romain-b13** [comment]
1) Dans les éléments saisis on souhaite ajouter tous les éléments saisis : 
- type de contrat
- le licenciement n'est pas dû/est dû à une faute grave (ou lourde)
- le licenciement n'est pas dû/est dû à une inaptitude suite à un accident du travail ou maladie professionnelle reconnue
- la convention collective
- la catégorie professionnelle
- l'échelon / le groupe / le niveau / la classe ...
- type de licenciement (pour certaines CC)
- type de contrat (pour certaines CC)
- entreprise adhérente/non-adhérente (pour certaines CC) => voir si on pose vraiment cette question à l'utilisateur (si oui où peut-il trouver cette info ?)
- âge du salarié (pour certaines CC)
- tous les éléments saisis à l'étape ancienneté
- tous les éléments saisis à l'étape salaire

=> à valider avec le métier / dépendra si on pose ou non certaines questions un peu difficile pour l'utilisateur (nécessaire pour la calcul mais risque de perdre l'utilisateur)

2) On ajoute une rubrique "Résultat décrypté" et "formule" dans laquelle on affiche uniquement la formule appliquée (soit celle de la CC soit celle du CDT)

**Visuel**

![image](https://user-images.githubusercontent.com/84397271/178299984-5f50ac2b-fd45-445d-8188-501aa1785315.png)

**Comment by romain-b13** [comment]
Vu avec le métier : pour se prémunir d'un éventuel contentieu il faudrait afficher dans "les éléments saisis" toutes les données saisies y compris pour le salaire et l'ancienneté, ce qui pourrait dans certains cas donner ça : 

![Frame 1](https://user-images.githubusercontent.com/84397271/170027276-27153490-00b0-47c0-a8c4-f2aa6d9015ed.png)

**Comment by romain-b13** [comment]
### Phrase à afficher dans l'encadré bleu "attention" 

il faudra penser à l'étape résultat à retirer les mots "convention collective"  de l'encadré "attention" **si et seulement si l'utilisateur a sélectionner une CC traitée** (s'il ne sélectionne pas de CC ou qu'il sélectionne une CC non traitée on conserve les mots "convention collective") : 

![image](https://user-images.githubusercontent.com/84397271/174307341-77c8115a-8fe9-4d28-9d1d-e9afa1778e4b.png)

**Message si l'utilisateur n'a pas sélectionné de CC ou a selectionné une CC non traitée :**
Une convention collective, un accord d’entreprise, le contrat de travail ou un usage peut prévoir un montant plus favorable pour le salarié. Dans ce cas, c’est ce montant plus favorable qui s’applique au salarié.

**Message si l'utilisateur a selectionné une CC traitée :**
Un accord d’entreprise, le contrat de travail ou un usage peut prévoir un montant plus favorable pour le salarié. Dans ce cas, c’est ce montant plus favorable qui s’applique au salarié.

**Comment by romain-b13** [comment]
### Phrases à afficher dans "Résultat décrypté"

**1- Si l'indemnité conventionnelle est supérieure à l'indemnité légale**

Montant prévu par le code du travail : XXXX €

Montant prévu par la convention collective : XXXX€

Le montant à retenir pour le salarié est celui prévu par la convention collective, celui-ci étant plus favorable que le montant prévu par le code du travail.

**2- Si l'indemnité légale est supérieure à l'indemnité conventionnelle**

Montant prévu par le code du travail : XXXX €

Montant prévu par la convention collective : XXXX€

Le montant à retenir pour le salarié est celui prévu par le code du travail, celui-ci étant plus favorable que le montant prévu par la convention collective.

**3- Si l'indemnité légale est égale à l'indemnité conventionnelle**

Montant prévu par le code du travail : XXXX €

Montant prévu par la convention collective : XXXX€

Le montant prévu par le code du travail est le même que celui prévu par la convention collective.

**4- Si l'utilisateur n'a pas sélectionné de CC**  

Montant prévu par le code du travail : XXXX €

Montant prévu par la convention collective : Convention collective non renseignée 

La convention collective n’ayant pas été renseignée, le montant de l’indemnité de licenciement affiché correspond au montant prévu par le code du travail. 

**5- Si l'utilisateur a sélectionné une CC non traitée**

Montant prévu par le code du travail : XXXX €

Montant prévu par la convention collective : Convention collective non traitée

La convention collective n’ayant pas été traitée par nos services, le montant de l’indemnité de licenciement affiché correspond au montant prévu par le code du travail.

**6- Si la CC sélectionné ne prevoit d'indemnité de licenciement**

Montant prévu par le code du travail : XXXX €

Montant prévu par la convention collective : 0 €

En l’absence de montant prévu par la convention collective, le montant de l’indemnité de licenciement à appliquer pour le salarié est donc le montant prévu par le code du travail. 

**7- Si le code du travail ne prévoit d'indemnité car ancienneté trop faible mais la CC prévoit une indemnité pour cette ancienneté**

Montant prévu par le code du travail : 0€

Montant prévu par la convention collective : XXXX  €

En l’absence de montant prévu par le code du travail, le montant de l’indemnité de licenciement à appliquer pour le salarié est donc le montant prévu par la convention collective.

**Comment by romain-b13** [comment]
### Cas du licenciement dû à une inaptitude suite à un accident du travail ou une maladie professionnelle reconnue  

Voici ce qu'il faut ajouter dans les éléments saisi si l'utilisateur a répondu "oui" à la question "Le licenciement est-il dû à une inaptitude suite à un accident du travail ou maladie professionnelle reconnue ?" : 

![image](https://user-images.githubusercontent.com/84397271/178317756-eca9a673-afdd-4876-9c25-d5a9ebe5cfd5.png)

**Comment by romain-b13** [comment]
### Les sources à afficher 

Les sources à afficher à l'étape résultats sont indiquer dans la colonne AC de cet excel (le lien de la source est indiqué dans la conne AD) : https://docs.google.com/spreadsheets/d/1A9ceptjkBtMJx-BqOVXPAayoid-IJlh9en49ru8qKg0/edit#gid=0

Règle d'affichage des sources : afficher uniquement les sources qui correspondent au résultat donné : si le résultat est le résultat de la CC alors on affiche les articles de la CC, par contre si le résultat donné est celui du code du travail il faut afficher uniquement les articles du code du travail et pas ceux de la CC qui avait été séelctionnée

PS : les sources du code du travail affichées aujourd'hui en prod ne sont pas les bonnes, donc il faudrait en profiter pour mettre les bonnes sources qui sont indiquées dans l'excel pour le code du travail (IDCC n°0)

**Comment by maxgfr** [comment]
Je ne pense pas que ça soit utile de préciser l'alternance `mi-temps` car par défaut on ne peut pas continuer si la personne a selectionné : `Non` à cette question

> à remettre car dans le futur on en aura besoin

**Comment by maxgfr** [comment]
Le montant de l'indemnité de licenciemnt **LEGAL** a été doublé

Pour le message lié aux éléments saisies par l'utilisateur. Car si c'est une CC on ne double pas.

T'en penses quoi Romain ?

> pas d'astérix si le resultat affiché est conventionnel et que la cc ne prend pas en compte ce use case

**Comment by maxgfr** [comment]
Pour la formule, on ferait comment pour le salaire conventionnel de reference. On devrait créer un nouveau paramètre dans la formule. Dans les champs saisies on parle de `Sref`

> non on affiche toujours les infos saisies par l'utilisateur, puis après on peut injecter des cas spécifique en terme d'infos

**Comment by maxgfr** [comment]
Est-ce qu'on rajouterait pas l'ancienneté légale et conventionnelle calculée ? Car là, on met que les inputs et pas les resultats qu'on process. Pareil pour le salaire de réféférence

> mettre ancienneté et salaire de référence utilisée par la formule en dessous. mettre la formule sur publicodes, et detecter la formule qu'on prendrait la plus bénéfique

**Comment by romain-b13** [comment]
Mes retours : 

1) le nom de l’étape « Conditions d'applications » doit devenir « contrat de travail » comme le nom réel de l’étape dans l’outil actuel

2) « Licenciement dû à une inaptitude : Non » => à mettre dans l’étape « contrat de travail » et pas dans l’étape « informations »

3) L’encadré bleu « Attention il peut exister un montant plus favorable » doit être affiché en dehors de l’accordéon « voir le détail du calcul » (pareil pour la petite phrase qui est sous l’encadré bleu)

4) « Absence de plus d’un mois dans le contrat de travail » doit devenir « Absence de plus d’un mois **durant** le contrat de travail »

5) Passer à la ligne ce qui est en jaune et avec une police plus petite s’il faut => on doit pouvoir réduire la largeur des colonnes « salaires » et « dont primes » afin d’augmenter la colonne « mois » 
+  Bug quand je mets « 0 » il apparait 2 fois
 
![image](https://user-images.githubusercontent.com/84397271/180269610-f0b817f2-ef6d-4fbe-abaa-2d92725baa64.png)


6) Remplacer « le licenciement » par « le salarié » + ajouter un « e » à la fin de « légal »
 
![image](https://user-images.githubusercontent.com/84397271/180269688-4f53366e-53d5-4bb1-b8d7-490ede73c5de.png)


7) Remplacer « non sélectionné » par « La convention collective n’a pas été renseignée » :
 
![image](https://user-images.githubusercontent.com/84397271/180269753-c56af564-7656-4190-b31f-053ea18ebc49.png)


8) Arrondir visuellement l’année et le sref
 
![image](https://user-images.githubusercontent.com/84397271/180269794-ccb1ba14-1707-4590-bb5b-5066d867043c.png)

![image](https://user-images.githubusercontent.com/84397271/180269830-91d3f1d3-ee25-4934-a242-1355b0b5242e.png)

9) ancienneté de la 2511
Sur la branche la CC semble bien de pas exclure les périodes d’absence pour « congé paternité » et « accident de travail » (ce qui fait que le résultat de la CC va être meilleur) cependant à l’étape résultat ce n’est pas le meilleur résultat qui est affiché (ça devrait être le résultat conventionnel d’affiché)
Pour ce même cas on observe qu’il n’y a pas de formule affiché (ça devrait être la formule conventionnelle d’affichée)

**Comment by romain-b13** [comment]
Reste à faire sur l'étape résultat : 

### 1) dans le cas ci- dessous j'ai mis une ancenneté totale de 19,17 ans (date entrée : 25/11/2002 et date de sortie : 18/02/2022) mais on affiche "A1 : ancienneté totale (19,17 ans)" alors que ça devrait être "A1 : de 10 ans ou moins (10 ans)" et le A2 affiché n'est pas bon non plus car du coup ici le A2 devrait être 9,17 ans et non "4,17 ans"

![image](https://user-images.githubusercontent.com/84397271/180826222-62ef7c7c-d100-4b93-bc3a-e3afa317ab94.png)

**Dates saisies pour ce cas :** 

![image](https://user-images.githubusercontent.com/84397271/180826314-98dad696-50c2-4b05-931a-369beddb3a2c.png)

### 2) L'arrondi du résultat total de l'indemnité, de l'ancienneté et du Sref ne semble pas être le même que ce qu'on a en prod actuellement car avec les mêmes données saisies on obtient pour le légal sur la branche le résultat arrondi au supérieur 

**Données saisies :**

![image](https://user-images.githubusercontent.com/84397271/180828004-4295da9f-4b0a-4152-9e7a-84a3f6b5dcf5.png)


**Résultats sur la branche :** 

![image](https://user-images.githubusercontent.com/84397271/180826786-4273f880-fbc7-4231-b45c-336c574e4314.png)

![image](https://user-images.githubusercontent.com/84397271/180827828-cd6caa04-4cc5-46bb-9d7b-ff4827620db6.png)

**Résultats en preprod :** 

![image](https://user-images.githubusercontent.com/84397271/180828204-a6af2c03-a676-4154-bfaf-2b1c02164bcf.png)

### 3) Mettre une virgule et non un point dans le résultat 

![image](https://user-images.githubusercontent.com/84397271/180829683-545a674b-cb71-4b3d-a28c-15b180815e94.png)


### 4) Mettre un "s" aux 2 mots "salaires" : 

![image](https://user-images.githubusercontent.com/84397271/180731451-b66184e1-9783-44f0-af65-7ac13fe38916.png)

### 5) arrondis à 3 chiffres pour la CC au lieu de 2 (ce qui donne un résultat conventionnelle plus favorable)

![image](https://user-images.githubusercontent.com/84397271/180733480-03a4b136-60a8-4cf3-9c73-ef59c06884f2.png)

### 6) Dans les différents messages qui sont dans l'encadré bleu il faut mettre "peut" au lieu de "peuvent"

![image](https://user-images.githubusercontent.com/84397271/180829894-f86656c6-c054-4d63-9745-4f8f2570b185.png)

### 7) ajouter "(ou lourde)" entre parenthèses à la fin

![image](https://user-images.githubusercontent.com/84397271/180829971-0993d268-d649-4507-8c1b-a374f5bab1b9.png)


### 8) ajouter un "s" à absence"

![image](https://user-images.githubusercontent.com/84397271/180818524-0aa62fe1-290d-41f2-96fb-a38026ae3e70.png)

### 9) Remplacer "Salaire des 12 derniers mois précédant la date de notification de licenciement" par "Salaires mensuels bruts perçus au cours des 12 mois précédents la notification du licenciement"

![image](https://user-images.githubusercontent.com/84397271/180830157-a5c35242-d74f-4cdd-8f4d-efebe65ee621.png)

### 10) Résultat affiché pour la CC 2511
Sur la branche, la CC semble bien de pas exclure les périodes d’absence pour « congé paternité » et « accident de travail » (ce qui fait que le résultat de la CC va être meilleur) cependant à l’étape résultat ce n’est pas le meilleur résultat qui est affiché (ça devrait être le résultat conventionnel d’affiché)
Pour ce même cas on observe qu’il n’y a pas de formule affiché (ça devrait être la formule conventionnelle d’affichée)

![image](https://user-images.githubusercontent.com/84397271/180831626-5ea41139-dd7a-497e-95d7-aa00b5b5ace7.png)

![image](https://user-images.githubusercontent.com/84397271/180831716-5ea73a1b-4c4e-4cf6-8c61-d6b3a2eccec7.png)

### 11) quand l'utilisateur ne sélectionne pas de CC il n'y a pas de message à l'étape résultat : 
=> il faut indiquer "Convention collective non renseignée"

![image](https://user-images.githubusercontent.com/84397271/182582646-99bd701a-5a18-4777-8b94-b39dc0a584e2.png)

### 12) à l'inverse j'ai sélectionné une CC est on me dit que la convention collective n'a pas été renseignée

![image](https://user-images.githubusercontent.com/84397271/182583450-aae37054-10f6-4cae-81fe-9ba86fada0fb.png)

**Comment by maxgfr** [comment]
Enlever les apostrophe sur l'étape resultat au niveau de l'étape info
