### ISSUE TITLE
Check matomo error on theme page (viewable on preprod)

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#4330]
On peut voir ici dans la console : https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/themes/travailleurs-et-secteurs-specifiques

**Comment by m-maillot** [comment]
Le soucis vient d'une PR qui passe les arguments de 2 à 1 pour les thèmes : https://github.com/SocialGouv/code-du-travail-numerique/commit/3bdc12ed1cd693401b5b856538837395ff95787a#diff-197bd52c64a3e9afed0c7d5d3508506e79e1ed2f911f8bf7c99c82b4b12e5c97R20

A voir avec @rmelisson

**Comment by rmelisson** [comment]
oui donc il faudrait juste ajouter un param query `""` au mato push si je comprends bien ?
