### ISSUE TITLE
Etudier l'intégration du calcul de l'ancienneté CC

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#4370]
L'étape "ancienneté" implique de gérer des listes => voir comment gérer ces étapes avec publicode

**Etape ancienneté** 

![image](https://user-images.githubusercontent.com/84397271/151408535-9b7a4f3a-8dfd-4a76-8884-5bbaac2e631f.png)

**Comment by romain-b13** [comment]
### Excel (attention des filtres sont peut-être actifs) : https://docs.google.com/spreadsheets/d/1ZuKopydhLY90sTLNu0BOgNBawNSlWLr-CeMGG5WeiG8/edit#gid=0
### Klaxoon : https://app.klaxoon.com/join/5V72CMH

**Comment by maxgfr** [comment]
Problématique avec Publicodes :

Ils utilisent un système de calcul de date basé sur l'API `Date` de `node` : https://github.com/betagouv/publicodes/blob/b4fd80e0df1da719b192d301b53208fb8cefb0cc/packages/core/source/date.ts

Ce qui fait que celle-ci se base sur le timestamp. Les jours des années bisextiles sont donc pris en compte de manière diluée.

Pour des petites ancienneté, il n'y a aucun soucis, en revanche pour des anciennetés supérieurs à 20 ans, le résultat est problématique.

Au début, j'ai fait une fonction qui permet de corriger ce résultat côté frontend, malheureusement elle n'est pas pris en compte dans le calcul de publicodes au niveau de l'ancienneté.

La conséquence sur de longues périodes est qu'on a une ancienneté qui varie de quelques dizaines d'euros dû à une ancienneté basé sur les timestamp

Pour une date d'entrée le `01/01/1979` et une date de fin le `01/01/2021`, soit 42 ans (540 mois), ça utilise au sein de publicodes 42.03 ans

J'ai essayé de tout passé en mois mais on a le même soucis (pour l'example, nous avons 540,36 mois car 11 jours supplémentaires dûes aux années bisextiles)

Le problème philosophique est que l'utilisateur ne pourra jamais retrouver cette ancienneté si c'est lui même qui fait le calcul a la main. De plus, le resultat est au dessus de ce que lui peut attendre (c'est aux euros prêts mais bon)

**Comment by maxgfr** [comment]
Voici le lien du commit qui supprime ce que j'ai fait sur publicodes et qui le remplace par la partie `ts` : [`1fc5e45` (#4468)](https://github.com/SocialGouv/code-du-travail-numerique/pull/4468/commits/1fc5e45efd67659a83625f2a3fc6c0147a9ffda9)
