### ISSUE TITLE
Intégrer le calcul de l'ancienneté légale dans publicodes

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#4374]
TBD après étude de l'ancienneté CC

**Comment by m-maillot** [comment]
- [ ] Revoir à partir de la liste des cas spécifiques pour savoir si on doit faire le même travaille que pour le salaire de réf.

**Comment by romain-b13** [comment]
Il faudrait ajouter pour tous les cas (y compris le légal) cette phrase : 
![image](https://user-images.githubusercontent.com/84397271/177164771-917871ed-24ad-452f-bb11-b17940c0b0db.png)
