### ISSUE TITLE
Réecrire les balises title, metadescriptions et H1 pour nos simulateurs

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4391]
### Nouvelles balises title
Simulateur - Calcul du préavis de démission - Code du travail numérique
Simulateur - Calcul du salaire brut/net - Code du travail numérique
Simulateur - Calcul de l'indemnité de licenciement - Code du travail numérique
Simulateur - Calcul de l'indemnité de précarité - Code du travail numérique
Simulateur - Calcul du préavis de licenciement - Code du travail numérique
Simulateur - Calcul du nombre d’heures d'absence pour rechercher un emploi - Code du travail numérique
Simulateur - Calcul du préavis de départ ou mise à la retraite - Code du travail numérique

### Nouvelles meta-descriptions

**Outil trouver sa convention collective**
Vous recherchez des informations traitées par votre convention collective ? Notre outil de recherche vous apporte une réponse en saisissant le nom de votre entreprise (ou siret) ou de votre convention collective (ou numéro IDCC).

**Outil préavis de démission**
Vous souhaitez connaître la durée du préavis à respecter en cas de démission ? Notre simulateur vous apporte une réponse personnalisée.

**Outil salaire brut/net**
Réalisez vos conversions et calculs de salaire (brut en net, net en brut, net après impôt, heures supplémentaires et coût total employeur) avec notre simulateur.

**Outil indemnité de licenciement**
Vous souhaitez calculer le montant de l'indemnité de licenciement ? Notre simulateur vous apporte une réponse personnalisée.

**Outil indemnité de précarité**
Vous souhaitez calculer le montant de l'indemnité de précarité ? Notre simulateur vous apporte une réponse personnalisée.

**Outil préavis de licenciement**
Vous souhaitez connaître la durée du préavis à respecter en cas de licenciement ? Notre simulateur vous apporte une réponse personnalisée.

**Outil heures pour recherche d'emploi**
Vous souhaitez connaître le nombre d’heures d’absence autorisée pendant un préavis pour rechercher un emploi ? Notre simulateur vous apporte une réponse personnalisée.

**Outil préavis de retraite**
Vous souhaitez connaître la durée du préavis à respecter en cas de départ ou de mise à la retraite ? Notre simulateur vous apporte une réponse personnalisée.

### Nouvelles balises H1

**Outil préavis de démission**
Calculer le préavis de démission

**Outil salaire brut/net**
Calculer le salaire brut/net

**Outil indemnité de licenciement**
Calculer l'indemnité de licenciement

**Outil indemnité de précarité**
Calculer l'indemnité de précarité

**Outil préavis de licenciement**
Calculer le préavis de licenciement

**Outil heures pour recherche d'emploi**
Calculer le nombre d'heures d'absence pour rechercher un emploi

**Outil préavis de retraite**
Calculer le préavis de départ ou de mise à la retraite

**Comment by carolineBda** [comment]
@romain-b13 "trouver sa CC", on change pas le `title` ni le `H1` ?

**Comment by romain-b13** [comment]
@carolineBda non on garde le même title et le même H1
