### ISSUE TITLE
Title missing in Fiche service public

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#4395]
Sur certaines section il manque un titre et le titre "Ou s'adresser" est répété :

https://code.travail.gouv.fr/fiche-service-public/artiste-auteur-affiliation-et-regime-social

![Screenshot from 2022-04-21 16-45-47](https://user-images.githubusercontent.com/4971715/164484200-531d2371-72c2-468b-ad01-e0c116d2c62d.png)

![Screenshot from 2022-04-21 16-45-21](https://user-images.githubusercontent.com/4971715/164484207-27305373-85b0-49b7-9dd5-06da31561337.png)

**Comment by romain-b13** [comment]
J'ajouterais uen erreur de balise Hn lors d'une recherche sur le site à corriger :  

![image](https://user-images.githubusercontent.com/84397271/164759029-390be8b5-e747-4f97-9f97-c838a1bd2c7a.png)

@romain-b13 celui la est déjà fixed

**Comment by romain-b13** [comment]
Je vois d'autres erreurs sur des pages qui ne doivent pas être crawlées : 

- Boîte à outils 

![image](https://user-images.githubusercontent.com/84397271/165262688-80df88b8-ef39-4a82-95cf-4cd6fc7e120b.png)
fixed :heavy_check_mark: 

- Le droit du travail 

![image](https://user-images.githubusercontent.com/84397271/165262903-8704ea8c-57e4-47b3-be62-e6bbe027123b.png)

- modale contact 1

![image](https://user-images.githubusercontent.com/84397271/165263188-f4f97301-d6bc-4475-b7c3-bf70b1c543e4.png)

- modale contact 2

![image](https://user-images.githubusercontent.com/84397271/165263300-e00bb48e-e9e0-407d-bb3f-acdeece47080.png)

- modale accessibilité 

![image](https://user-images.githubusercontent.com/84397271/165263481-14022e01-6474-40cb-ad42-759024ca662f.png)
