### ISSUE TITLE
Pas de résultat CC 44 heures pour recherche d'emploi

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4397]
**Description**
Pour la CC 44, quand on sélectionne en type de rupture "Démission" OU "Licenciement" puis les catégories "Ouvriers, employés" OU "Techniciens" OU "Ingénieurs et cadres" on obtient en résultat "Aucun résultat : la convention collective n'a pas été traitée par nos services"

Par contre cela fonctionne si on sélectionne en type de rupture "Rupture de la période d'essai"

![image](https://user-images.githubusercontent.com/84397271/164753676-c4f7c881-e9ee-4424-80cd-601a707623ae.png)

**Reproduction**
Etapes à suivre pour reproduire le bug

1. Aller sur l'outil "heures d'absence pour rechercher un emploi"
2. Sélectionner la CC 44
3. Sélectionner "Démission" OU "Licenciement"
4. Sélectionner "Ouvriers, employés" OU "Techniciens" OU "Ingénieurs et cadres"
5. Sélectionner n'imorte quelle réponse si d'autres questions sont posées à l'étape "Informations"
6. Observer le résultat

**Comportement attendu**
Résultat correspondant aux infos entrées étant donné que la CC est bien traitée

Le bug ne semble pas présent sur d'autres CC mais peut-on tout de même vérifier si le comportement ne se produirait pas dans d'autres cas ?

**Comment by carolineBda** [comment]
Autre cas d'erreur :
- CC 86
- Licenciement 	
- Agents de maîtrise et Techniciens
