### ISSUE TITLE
tags eposeidons La rupture conventionnelle 1700

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#44]
proposition.

1700 | Contrat de travail > Rupture de contrat   à durée Indéterminée (CDI) > Rupture conventionnelle > Rupture   conventionnelle | R1237-3;   L1237-16; L1237-13; L1237-12; L1237-14; L1237-11; L1237-15
-- | -- | --
1710 | Contrat de travail > Rupture de contrat à durée Indéterminée (CDI)   > Rupture conventionnelle > Rupture conventionnelle> Principe | L1237-11 |   |  
1720 | Contrat de travail > Rupture de contrat à durée Indéterminée (CDI)   > Rupture conventionnelle > Rupture conventionnelle>Procédure>   entretiens | L1237-12 |   |  
1730 | Contrat de travail > Rupture de contrat à durée Indéterminée (CDI)   > Rupture conventionnelle > Rupture conventionnelle>Procédure>   indemnité de rupture | L1237-13 |   |  
1740 | Contrat de travail > Rupture de contrat à durée Indéterminée (CDI)   > Rupture conventionnelle > Rupture conventionnelle>Procédure>   homologation | L1237-14; R1237-3 |  
1750 | Contrat de travail > Rupture de contrat à durée Indéterminée (CDI)   > Rupture conventionnelle > Rupture conventionnelle>Procédure>   salariés protégés | L1237-15 |   |  
1760 | Contrat de travail > Rupture de contrat à durée Indéterminée (CDI)   > Rupture conventionnelle > Rupture conventionnelle>Procédure>   exceptions | L1237-16; |   |  
1770 | Contrat de travail > Rupture de contrat à durée Indéterminée (CDI)   > Rupture conventionnelle > Rupture conventionnelle>procédure | R1237-3; L1237-16; L1237-13;   L1237-12; L1237-14; L1237-16

**Comment by jrduscher** [comment]
versée dans une issue globale sur la màj eposeidon

**Comment by revolunet** [comment]
cf #59
