### ISSUE TITLE
Modifier des résultats outils pour la CC 3239

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4419]
### Mise à la retraite (et non pas départ à la retraite)

La mise à la retraite n'est pas possible pour les assistants maternels

Si l'utilisateur a sélectionné "L'employeur décide de mettre le salarié à la retraite" lors de l'étape sur l'origine du départ + la CC 3239
Alors si l'utilisateur sélectionne la catégorie pro "Assistants maternels du particulier employeur" à l'étape "informations" il faut afficher le message "A noter" suivant :
"Les règles concernant la rupture du contrat de travail par le particulier employeur sont prévues par la convention collective et le Code de l’action sociale et des familles. Ces textes n’envisagent pas la mise à la retraite. Pour obtenir une durée de préavis, il doit s'agir d'un départ volontaire du salarié à la retraite (étape n°2 du simulateur)."

Il faudra aussi empêcher la poursuite de la simulation à cet endroit

### Départ à la retraite
Quand la catégorie pro "assistants maternels" est sélectionné => Retirer la comparaison du résultat prévu par la CC et le résultat prévu par le CDT => on affichera toujours uniquement le résultta prévu par la CC 

ceci implique de supprimer la rubrique "le résultat décrypté" pour cette CC : 

![image](https://user-images.githubusercontent.com/84397271/172823891-1a2489c4-ecba-4bd2-86a1-ddb628853ce7.png)

### Préavis de licenciement

Lorsque la CC 3239 est séléctionnée + la catégorie pro "Assistants maternels du particulier employeur" :
Il ne faut pas comparer le résultat du code du travail et le résultat de la CC => il faut toujours mettre le résultat prévu par la CC

**Conséquences :**
Dans ce cas les questions posées sur l'ancienneté du salarié et le travailleur handicapé à l'étape "situation du salarié" ne sont pas à prendre compte (les réponses données par l'utilisateur n'auront aucun effet sur le résultat)

A l'étape résultat :

Pour ce cas il faut supprimer la partie encadrée en rouge sur l'image : 

![image](https://user-images.githubusercontent.com/84397271/169266352-78cd260c-633b-49b5-af55-0f0bf9a8fb5b.png)

Rappel des résultats que l'on doit donc obtenir pour cette CC avec la catégorie pro "Assistants maternels du particulier employeur" : 
- si l'enfant est accueilli depuis moins de 3 mois : 8 jours calendaires
- si l'enfant est accueilli entre 3 mois et moins de 1 ans : 15 jours calendaires
- si l'enfant est accueilli depuis 1 ans et plus : 1 mois

### Préavis de démisison
Si la CC sélectionnée est 3239 + la cétégorie pro est "Assistants maternels du particulier employeur" : 

Quand l’ancienneté est "l'enfant est accueilli depuis moins de 3 mois" alors le résultat doit être « il n’y a pas de préavis à effectuer ».

Changer la source : remplacer l'article Article L.1237-1 du code du travail par l'Article 423-26 du code de l'action sociale et des familles : https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006798054

Ajouter un astérisque au résultat pour afficher cette phrase : "Il s’agit de la durée la plus courte entre celle prévue par le Code de l’action sociale et des familles et celle prévue par la convention collective."

**Comment by m-maillot** [comment]
@romain-b13 
Pour le préavis de licenciement, on garde le texte d'information actuel même s'il parle de code du travail ?

<img width="867" alt="image" src="https://user-images.githubusercontent.com/992514/174061288-ff10f6f9-24f1-45fc-b1a5-c31d74ea7576.png">

**Comment by romain-b13** [comment]
> @romain-b13 Pour le préavis de licenciement, on garde le texte d'information actuel même s'il parle de code du travail ?
> 
> <img alt="image" width="867" src="https://user-images.githubusercontent.com/992514/174061288-ff10f6f9-24f1-45fc-b1a5-c31d74ea7576.png">

Voici les messages à indiquer pour la 3239 dans les encadrés "attention il peut exister une durée plus favorable" : 

**Préavis de départ à la retraite**
Le contrat de travail ou un usage peut prévoir une durée de préavis* ou une condition d’ancienneté* plus favorable pour le salarié. Dans ce cas, c’est cette durée ou cette ancienneté plus favorable qui s’applique au salarié.
*durée de préavis plus favorable pour le salarié = durée plus courte.
*condition d’ancienneté plus favorable pour le salarié = condition d’ancienneté moins restrictive et conduisant à une durée de préavis plus courte.

**Préavis de licenciement** 
Le contrat de travail ou un usage peut prévoir une durée de préavis ou une condition d’ancienneté plus favorable pour le salarié. Dans ce cas, c’est cette durée ou cette ancienneté plus favorable qui s’applique au salarié.

**Préavis de démission**
Ne pas mettre de message = supprimer totalement l'encadré bleu

**Comment by romain-b13** [comment]
MAJ concernant le préavis de départ à la retraite pour les "assistants maternels" => on conserve la comparaison du résultat du CDT avec le résultat conventionnel
