### ISSUE TITLE
Changement des noms de catégorie pour la CC 1505 dans les outils

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4420]
Pour la CC 1505

**Modification des noms de catégories pro**

Dans les outils il faut modifier le nom des catégories professionnelles, il faut remplacer :

- Ouvriers, Employés (niveaux I, II, III, IV) par => Employés (E1 à E7)
- Agents de maîtrise (niveau V) par => Agents de maîtrise (AM1 et AM2)
- Cadres (niveau VI) par => Cadres (C1 et C2)

**Modification de sources juridiques de la convention collective**

1. Heures d'absence pour rechercher un emploi quand le motif de rupture est une démission

→ Article 20.1 au lieu de 3.7.1

https://www.legifrance.gouv.fr/conv_coll/article/KALIARTI000043562750#KALIARTI000043562750

2. Heures d'absence pour rechercher un emploi quand le motif de rupture est une rupture de la période d'essai

→ Article 16 au lieu de 3.3

https://www.legifrance.gouv.fr/conv_coll/article/KALIARTI000043562743#KALIARTI000043562743

3. Heures d'absence pour rechercher un emploi quand le motif de rupture est un licenciement 

→ Article 20.1 au lieu de 3.7.1

https://www.legifrance.gouv.fr/conv_coll/article/KALIARTI000043562750#KALIARTI000043562750

4. Préavis de Démission 

→ Article 20 au lieu de 3.7

https://www.legifrance.gouv.fr/conv_coll/article/KALIARTI000043562749#KALIARTI000043562749

5. Préavis de licenciement

→ Article 20 au lieu de 3.7

https://www.legifrance.gouv.fr/conv_coll/article/KALIARTI000043562749#KALIARTI000043562749

6. Préavis de départ et de mise à la retraite

→ Article 23.3 au lieu de 3.10.3

https://www.legifrance.gouv.fr/conv_coll/article/KALIARTI000043562759#KALIARTI000043562759

**Comment by carolineBda** [comment]
@romain-b13 pour les catégories, dans le préavis de retraite on a :
      Ouvriers, Employés (Niveaux N1 à N4)
      Agents de maîtrise (Niveaux N5 et N6)
      Cadres (Niveaux N7 et N8)

Je modifie avec les nouveaux noms

**Comment by romain-b13** [comment]
> @romain-b13 pour les catégories, dans le préavis de retraite on a : Ouvriers, Employés (Niveaux N1 à N4) Agents de maîtrise (Niveaux N5 et N6) Cadres (Niveaux N7 et N8)
> 
> Je modifie avec les nouveaux noms

yes c'est ça merci
