### ISSUE TITLE
Mise à jour des contrib différente entre page personnalisable et page CC

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4422]
Pour les contrib qui ont été mises à jour la semaine du 16/05/2022 on s'aperçoit que le contenu est bien à jour dans la page personnalisable mais pas dans la page CC.

**Voici un exemple :** 

-la dernière version modifiée est bien visible en preprod dans la page personnalisable "Quelle est la durée de préavis en cas de mise à la retraite ?" quand on personnalise avec la 3239
-mais dans la page de la CC 3239 pour cette question c'est l'ancienne version qui apparait

version sur la page personnalisable (https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/contribution/quelle-est-la-duree-de-preavis-en-cas-de-mise-a-la-retraite) : 

![image](https://user-images.githubusercontent.com/84397271/169294394-d92fae2e-bc6e-40cd-bb9c-9b9359098716.png)

version pour la même question mais dans la page CC (https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/convention-collective/3239-particuliers-employeurs-et-emploi-a-domicile) :

![image](https://user-images.githubusercontent.com/84397271/169294589-fb8b3dad-e935-4e5d-86fd-3c9446fa93bb.png)

PS : ce n'est pas la seule contrib concernée

**Comment by maxgfr** [comment]
Ce problème on l'avait déjà eu il me semble

**Comment by maxgfr** [comment]
C'était dû à des histoire de CRON. Peut-être que suite au changement d'infra (gitlab -> github), je sais qu'on avait eu des soucis

**Comment by maxgfr** [comment]
La liste des crons est établie ici : https://github.com/SocialGouv/code-du-travail-numerique/wiki#cron-jobs

Le problème semble venir de l'API cdtn (hébergé sur la vm), je propose de merge cette PR : https://github.com/SocialGouv/contributions-data/pull/89/files

**Comment by maxgfr** [comment]
Pour info, les deux pages, font des call via les `getServerSideProps`.

Pour les CC, le call se fait : 
```ts
...
fetch(`${API_URL}/conventions/${slug}`);
...
```

Ce qui donne cela côté API :

```ts
return {
    query: {
      bool: {
        filter: [
          { term: { slug } },
          { term: { source: SOURCES.CCN } },
          { term: { isPublished: true } },
        ],
      },
    },
    size: 1,
  };
```

Pour les contributions, le call se fait : 
```ts
...
fetch(`${API_URL}/items/contributions/${slug}`);
...
fetch(`${API_URL}/items?url=${contentUrl}`);
...
```

**Conclusion** : Les deux calls se font côtés API et donc ça viendrait possiblement de l'ingestion

**Comment by m-maillot** [comment]
Petite étude rapide suite aux problèmes reproduit sur la CC 16:

Il y a 2 données sur elastic search : 
* Une pour le slug de la contribution : `contribution/en-cas-de-perte-de-marche-par-lemployeur-quelles-sont-les-conditions-dun-transfert-des-contrats-de-travail`
* Une pour le slug de la convention collective : `convention-collective/16-transports-routiers-et-activites-auxiliaires-du-transport`

La donnée pour le convention collective n'est pas à jour dans elasticsearch.

Si on remonte d'un cran, la donnée est disponible dans hasura où la fonction export transforme les données pour les mettre sur elasticsearch. 

Sur hasura, la donnée pour la convention collective n'est pas à jour non plus.

On continue notre ascension. La donnée d'Hasura est alimenté via l'outil de contribution et plus spécifiquement par le dépôt git contributions-data.

Sur le repo git, la donnée est unique et elle est bien à jour.

Le problème se situe donc au niveau de l'ingester qui se charge de récupérer la donnée dans le dépôt github et de mettre à jour la BDD Hasura. Il semble ne mettre à jour qu'une seule donnée sur les 2 présentes.
