### ISSUE TITLE
Résoudre le problème des génération des co-visites via Machine Learning

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4423]
**Contexte**
On a du ML (machine learning) qui s'appuie sur les données de matomo pour détecter les articles liés sur nos pages. Cela permet de proposé des liens vers d'autres articles qui pourrait intéresser l'utilisateur basé sur les comportements des autres utilisateurs.

**Problème**
Les articles liés ne sont plus générés via le ML depuis juillet 2021 (c'est un autre fonctionnement qui est alors utilisé : articles qui apparaissent dans la recherche)

**Comment by rmelisson** [comment]
quid de la pertinence ? exemples d'eventuels problèmes

**Comment by romain-b13** [comment]
![image](https://user-images.githubusercontent.com/84397271/193778936-77ea3f59-26de-43a8-8361-515b3d224bdb.png)

=>L'article surligné parle de la suspension temporaire du contrat de travail (arrêt maladie, congé de maternité ou d'adoption, par exemple)

![image](https://user-images.githubusercontent.com/84397271/193780058-4eeffe3e-68ea-4fdf-9196-a5290778e16b.png)

=> par exemple dans ce cas là on s'attend plutôt à avoir en outil lié l'outil de calcul du préavis de démission plutôt qu'une lettre de licenciement pour inaptitude

![image](https://user-images.githubusercontent.com/84397271/193781357-920dc7d2-c8d2-4845-904c-5c556b01fb47.png)

=> ce contenu concerne la durée du préavis de licenciement et en articles liés on a un contenu sur la durée du congé maternité et un contenu qui concerne la démission


![image](https://user-images.githubusercontent.com/84397271/193779530-d3706b5e-ca2d-4e90-81b1-1ceb2c3d754a.png)

=>Sur l'outil de calcul du préavis de licenciement on a 2 contenus liés qui concernent la démission

![image](https://user-images.githubusercontent.com/84397271/193779795-5164e9c7-24dd-459f-aba8-1cc3afe176ed.png)


![image](https://user-images.githubusercontent.com/84397271/193779962-e3452608-bbb3-4e07-9175-8f963def8950.png)

**Comment by rmelisson** [comment]
ok on va regarder d'ou viennent ces reco : covisites OU recherche standard

**Comment by rmelisson** [comment]
Ok, il s'agit à chaque fois de contenu "search" et non pas des covisites générées via l'analyse des logs/
On tente de generer les covisites pour ces contenus, pour comparer.

**Comment by romain-b13** [comment]
**On constate une amélioration de la pertinence des articles liés mais certains des articles "non-pertinents" identifiés précédemment sont toujours présents  :** 

Ex : 

![image](https://user-images.githubusercontent.com/84397271/194816125-e7821d96-f25e-4dcf-bec1-e115037b2f6a.png)


![image](https://user-images.githubusercontent.com/84397271/194825667-0ae6b592-5b54-49a9-accd-6240f1747f9c.png)

![image](https://user-images.githubusercontent.com/84397271/194825930-4307c890-3bf7-4ea7-a973-c1c074822940.png)

![image](https://user-images.githubusercontent.com/84397271/194828870-16375036-8688-460e-b4d0-e945af687309.png)

**Comment by romain-b13** [comment]
Le problème est de nouveau présent => on retrouve les mêmes co-visites qu'avant l'intervention de Remi au mois d'octobre 2022

**Comment by romain-b13** [comment]
Suite au travail de Victor du 06/01/23 on retrouve bien des artiles liés plus pertinents

**Exemples**

**Lettre de démisison** 

![image](https://user-images.githubusercontent.com/84397271/211024827-8a016aad-e4c8-4d35-bbf4-0d42f5aa362d.png)


**Contrib durée préavis de licenciement**

![image](https://user-images.githubusercontent.com/84397271/211025965-da4f5cbe-4b20-4a96-9397-b1cb50d10a81.png)

**Lettre de réclammation des documents de fin de contrat**

![image](https://user-images.githubusercontent.com/84397271/211026451-5cdc9461-ef13-49cc-aeeb-8c2ec0ef8bc8.png)
