### ISSUE TITLE
Dossier licenciement

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4435]
**Problème**
Les procédures de licenciement diffèrent selon le type de licenciement (économique, personnel etc.), le nombre de salariés concernés par le licenciement, la taille de l'entreprise, l'appartenance de l'entreprise à un groupe de plus de 1000 salariés ou non, la présence d'un CSE dans l'entreprise etc.
Il est donc diffcile pour l'usager d'identifier la procédure qui s'applique à sa situation/celle de son entreprise

**User story**
En tant que salarié/employeur concerné par un licenciement
Je souhaite obtenir des informations sur la procédure de licenciement qui s'applique à la situation de mon entreprise

**Solution**
1) Proposer à l'utilisateur de répondre à quelques question afin de lui présenter uniquement la procédure qui correspond à sa situation
2) Une fois arriver sur la page de la procédure qui correspond à sa situation l'usager pourra accéder : 
- aux étapes de la procédure de licenciement sous la forme d'une inforgraphie*
- aux étapes de la procédure de licenciement au format textuel*
- à des liens vers les simulateurs utiles en cas de licenciement (calcul du préavis de licenciement, de l'indemnité de licenciement etc.)
- à des liens vers d'autres ressources utiles en cas de licenciement (modèle de courrier de réclammation des documents de fin de contrat etc.)

*sous la procédure (que ce soit l'infographie ou le format textuel) on retrouve les modèles de courrier liés à la procédure (modèle de convocation à l'entretien préalable au licenciement et modèle de lettre de licenciement).

### 1) Le parcours de questions permettant d'accéder à la procédure

**Voici un prototype de l'enchainement des différentes questions** (attention : l'UI souhaitée n'est pas celle présentée dans ce proto). Dans ce proto seul le parcours "salarié" est disponible : 

https://www.figma.com/proto/CmF2w5QuZpxc6VKOywgeXf/Dossiers-du-CDTN?node-id=877%3A10064&scaling=scale-down-width&page-id=701%3A1037&starting-point-node-id=877%3A10064

**Présentation de l'enchainement des questions sous la forme d'un "arbre de décision" :**

https://www.figma.com/file/CmF2w5QuZpxc6VKOywgeXf/Dossiers-du-CDTN?node-id=1405%3A5312

**Présentation du parcours de questions au format word :** cf commentaire plus bas

**UI attendue pour le parcours de questions**
Ici est prototypé le parcours salarié > liceniement éco > seulement vous ...

https://www.figma.com/proto/CmF2w5QuZpxc6VKOywgeXf/Dossiers-du-CDTN?node-id=1238%3A5134&scaling=scale-down-width&page-id=1235%3A4866&starting-point-node-id=1238%3A5134

### 2) La page de la procédure (appelée "feuille finale")

**Prototype de "feuille finale" (ici pour la procédure "licenciement pour motif personnel non dsciplinaire") :** 

https://www.figma.com/proto/CmF2w5QuZpxc6VKOywgeXf/Dossiers-du-CDTN?node-id=1385%3A5008&scaling=scale-down-width&page-id=1235%3A4866&starting-point-node-id=1385%3A5008

**Document word présentant les contenus/liens à présenter sur chaque "feuille finale" :**

**Comment by m-maillot** [comment]
### Affichage en onglet des pages info

- [x] Sur Admin, ajouter le switch pour passer d'accordéon à onglet sur les pages informations sur l'UI
- [x] Sur Admin, valider que le flag est bien passé à elastic search (via l'export)
- [x] Sur CDTN, ajouter le support des onglets sur les pages informations


### Affichage des boîtes à outils dans un onglet

- [x] Sur Admin, ajouter un type boite à outils dans l'admin 
- [x] Sur admin, ajouter des boites à outils via une recherche
- [x] Sur Admin, valider que le flag est bien passé à elastic search (via l'export)
- [x] Sur CDTN, ajouter le support du type boite à outil (afficher sous forme de tuiles, réutiliser l'existant si possible)


### Affichage des ressources utiles et modèles de courrier dans un onglet 

- [x] Sur Admin, ajouter un type ressources dans l'admin 
- [x] Sur admin, ajouter des ressources via une recherche (voir la liste des types avec @romain-b13 )
- [x] Sur Admin, valider que le flag est bien passé à elastic search (via l'export)
- [x] Sur CDTN, ajouter le support des ressources (afficher sous forme de tuiles de la recherche, réutiliser l'existant si possible)
- [x] Afficher les modèles de courrier sous forme de tuiles

### Mixer les blocs (boite à outils, ressource, info, markdown...) dans les sections 

- [x] Sur admin, gérer la possibilité d'avoir plusieurs blocs dans un section
- [x] Sur Admin, valider que les infos sont bien passées à elastic search (via l'export) /!\ Changement d'un object json en array
- [x] Sur CDTN, ajouter le support de cette liste de blocs

### Implémentation des Q&R basés sur un arbre de chemin

- [x] Basé sur un fichier json l'arbre (à définir)
- [x] Création d'un store
- [x] Implémenter l'outil dans React

### Affichage du récap des Q&R sur la page info

- [x] Remonté via le json le parcours pour l'afficher
- [x] Composant React qui afficher les questions/réponses du parcours

### Tracking

- [x] Ajouter les events tracking (voir avec @romain-b13)

**A revoir ensemble car Romain a modifié quelques events :**

**1- Pages procédure**

Tacking nombre de clics sur les différents onglets  :
•	Category : page_information
•	Action : procédures_licenciement
•	Name : clik_onglet_procedure_infographie / clik_onglet_procedure_texte / clik_onglet_simulateurs / clik_onglet_autres ressources

/!\ L'utilisateur qui arrive sur la page est déjà par défaut sur l'onglet "procedure_infographie", il faut donc être en mesure d'envoyer l'event correspondant sans qu'il y ait de clic sur l'onglet

/!\ Ajouter dans l'admin le choix ou non de mettre un event au clic sur un onglet/accordéon lors de la création d'une page info ? (case à cocher)

**2- Outil trouver ma procédure de licenciement**

/?\ Il faut créer un event aussi pour avoir le nb de visites sur l'outil ? /?\

Tracking clics sur le bouton « afficher les infos personnalisées »
•	Category : outil
•	Action : comprendre ma procédure de licenciement
•	Name : clik_afficher_les_infos_personnalisées

Tracking sortie de l’outil :
•	Category : outil
•	Action : comprendre ma procédure de licenciement
•	Name : exit_question à laquelle l’user a quitté l’outil (ex : exit_question_CSE / exit_question_typedelicenciement…)

Tracking parcours les plus sollicités :
•	Category : outil
•	Action : comprendre ma procédure de licenciement
•	Name : select_salarié / select_licenciement_éco / etc.

Tracking clics sur les aides (en fonction des cas l’aide peut-être au niveau de la question ou de la proposition) :
•	Category : outil
•	Action : comprendre ma procédure de licenciement
•	Name : clik_help_CSE / clik_help_licenciement_éco

**Interrogations**

Lors de la journée CDTN nous avions identifié les events un peu différement que ce qui est décrit au dessus

1- Par exemple pour les clics sur le bouton "afficher les infos personnalisées" :  

•	Category : outil
•	Action : afficher_les_infos_comprendre ma procédure de licenciement

2- Par exemple pour les clics sur les différents onglets :

•	Category : page_information
•	Action : click_onglet
•	Name : procedure_infographie / procedure_texte / simulateurs / autres ressources

### Implémentation du questionnaire de satisfaction dédié

Reprendre le code du questionnnaire qu'on avait jusqu'à juin 2021 qui consisté à en savoir plus sur le profil des usagers => un questionnaire qui apparaît sur la droite au bout de quelques secondes

**Comment by romain-b13** [comment]
icone svg pour l'outil "comprendre ma procédure de question"

![Dossier licenciement](https://user-images.githubusercontent.com/84397271/178672959-6083dee8-ddf3-496b-8955-fbcbde5dc4dd.svg)

**Comment by romain-b13** [comment]
@ViCode Parcours de question au format word actualisé pour les messages d'aide : 

[Parcours.de.questions (2).docx](https://github.com/SocialGouv/code-du-travail-numerique/files/9315806/Parcours.de.questions.2.docx)
