### ISSUE TITLE
[Outil de contrib] Message d'erreur JWT au bout de 15 min

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4437]
Message d'erreur JWT quand on reste sur la même page depuis plus de 15 minutes. Il faut rafraichir la page pour enlever le message.

![image](https://user-images.githubusercontent.com/84397271/174022326-334b1eff-4250-496f-a455-47d2f237bdf7.png)

**Comment by m-maillot** [comment]
Steps: 

- [ ] Ajouter le support de typescript au projet
- [ ] Correctif avec un interceptor sur la partie cliente pour les requêtes GraphQL
