### ISSUE TITLE
certains synonymes définis dans kali data ne fonctionnent pas

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4442]
Malgré la correction récente de la non prise en compte des synonymes définis dans Kali-data,  il y a quelques synonymes qui ne fonctionnent toujours pas (pourquoi que ceux là ?) : 

- FEHAP / 1951 /51 => ne font pas remonter la CC "Hospitalisation privée : établissements privés d'hospitalisation, de soins, de cure et de garde à but non lucratif (FEHAP)"
- nounou / nourrice => ne font pas remonter la CC "Particuliers employeurs et emploi à domicile" (alors que les autres synonymes définis comme "assistants maternels" etc fonctionnent)
- 1809 => ne fait pas remonter la CC "Convention collective territoriale de la métallurgie du Jura"
- 1375 => ne fait pas remonter la CC "Convention collective Métallurgie Doubs"

**Comment by rmelisson** [comment]
c'est à cause du champs "effectif" qui n'est pas défini pour ces CC.
Ajouter lors de l'ingestion des CCs `if (!doc.effectif) {doc.effectif = 1}`

**Comment by romain-b13** [comment]
Les synonymes listés dans cette carte fonctionnent bien sauf : 
- nounou / nourrice => ne font pas remonter la CC "Particuliers employeurs et emploi à domicile" => par contre "nourice" avec un seul "r" fait bien remonter la page CC

**Comment by m-maillot** [comment]
ça semble être bon maintenant @romain-b13. On peut clôturer ?

**Comment by m-maillot** [comment]
Après essai, nounou et nourrice font correctement remonter la CC "Particuliers employeurs et emploi à domicile"
