### ISSUE TITLE
Nouvel event pour préavis de démission et heure pour recherche d'emploi

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4458]
**Contexte**
A l'étape "convention collective" des outils les events "CC_select_P1", "entreprise_select" et "CC_select_P2" sont envoyés uniquement au clic sur le bouton "suivant"
Désormais dans les outils "préavis de démission" et "heures d'absence pour rechercher un emploi" il est impossible de passer à l'étape suivante si la CC sélectionnée n'est pas une CC qui est traitée sur le CDTN donc les event "CC_select_P1" , "entreprise_select" et "CC_select_P2" sont envoyés que lorsque c'est une CC traitée qui est sélectionnée

**Solution**
Pour connaître la proportion d'utilisateur qui ont selctionné une CC dans ces 2 outils là mais qui n'ont pas pu poursuivre la simulation car la CC qu'ils ont sélectionné était une CC non traitée il faudrait créer un nouvel event :

**user_blocked_info_cc**

- Cet event est envoyé quelque soit le parcours utilisé (P1 ou P2)
- Cet event doit être envoyé au même moment que lorsque le message ci-dessous apparaît : 

![image](https://user-images.githubusercontent.com/84397271/176455482-3bac8dd1-9fab-4e6d-8022-f89360c6b859.png)

- On doit pouvoir savoir le nombre d'event envoyé pour chacun des 2 outils séparément

**Comment by romain-b13** [comment]
category : outil
action : view_step_Préavis de démission ou view_step_Heures d'absence pour rechercher un emploi
name : user_blocked_info_cc

**Comment by maxgfr** [comment]
J'ai MAJ le wiki : https://github.com/SocialGouv/code-du-travail-numerique/wiki/Event-de-tracking
