### ISSUE TITLE
Supprimer un motif d'absence de la lisste dans l'outil indemnité de licenciement

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4481]
**Description**
Dans l'outil de calcul de l'indemnité de licenciement, à la question "Quels sont le motif et la durée de ces absences prolongées ?", dans la liste des motifs proposés on retrouve 2 motifs qui correspondent en fait à un unique motif. Il faut supprimer le motif "maladie d'origine non professionnelle" : 

![image](https://user-images.githubusercontent.com/84397271/178430477-53f2dce9-6af5-4b92-861f-19ea6ac94522.png)

**Comment by maxgfr** [comment]
Il faut faire cela, lorsque la CC ne compte pas l'absence, c'est ça ?
