### ISSUE TITLE
Modifier le nom de la CC 1517

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4490]
**ancien nom** : Commerces de détail non alimentaires antiquités, brocante, galeries d'art (œuvres d'art), arts de la table, coutellerie, droguerie, équipement du foyer, bazars, commerces ménagers, modélisme, jeux, jouets, périnatalité et maroquinerie

**nouveau nom** : Commerces de détail non alimentaires : antiquités, brocante, galeries d'art (œuvres d'art), arts de la table, coutellerie, droguerie, équipement du foyer, bazars, commerces ménagers, modélisme, jeux, jouets, puérinatalité, maroquinerie, presse et jeux de hasard ou pronostics, produits de la vape

Normalement il faut juste changer le nom au niveau du repo kali pour que le changement soit effectif partout : 
- [ ] Changer le nom dans la page de la CC (https://code.travail.gouv.fr/convention-collective/1517-commerces-de-detail-non-alimentaires-antiquites-brocante-galeries-dart)

- [ ] Mettre une redirection en place de l'ancienne URL vers la nouvelle de la page CC 

- [ ] Changer le nom de la CC dans la tuile résultat du moteur global

- [ ]  Changer le nom de la CC dans le moteur de recherche des CC + lorsque l'on fait une recherche par entreprise (que ce soit dans les contrib, à l'étape CC des outils ou dans l'outil "trouver sa CC)

**Comment by carolineBda** [comment]
@romain-b13  t'as une typo sur "puérinatalité"
