### ISSUE TITLE
Mettre en place le tracking dossier licenciement

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4536]
### Tacking nombre de clics sur les différents onglets :
•    Category : page_information
•    Action : procédures_licenciement
•    Name : click_onglet_procedure_infographie / click_onglet_procedure_texte / click_onglet_simulateurs / click_onglet_autres_ressources

### Tracking clics sur le bouton « afficher les infos personnalisées » :
•    Category : outil
•    Action : comprendre sa procédure de licenciement
•    Name : click_afficher_les_infos_personnalisées

### Tracking des questions "vues"** (pour identifier les questions qui générent des abandons)
•    Category : outil
•    Action : comprendre sa procédure de licenciement
•    Name : view_question_nom de la question : 
- view_question_profil
- view_question_type de licenciement
- view_question_motif de licenciement
- view_question_nombre de salariés licenciés
- view_question_nombre de salariés dans l'entreprise
- view_question_appartenance à un groupe
- view_question_CSE

### Tracking parcours les plus sollicités :
•    Category : outil
•    Action : comprendre sa procédure de licenciement
•    Name : select_Réponse sélectionnée : 

_Q° : Vous êtes :_
- select_salarié 
- select_employeur

_Q° : Par quel type de licenciement êtes-vous concerné ? :_
- select_licenciement_personnel
- select_licenciement_économique
- select_licenciement_APC

_Q° : Quel est le motif de ce licenciement ? :_
- select_licenciement_disciplinaire
- select_licenciement_non_disciplinaire
- select_licenciement_inaptitude

_Q° : Combien de salariés sont concernés par ce licenciement ? :_
- select_1_seul_salarié
- select_entre_2_et_9_salariés
- select_au_minimum_10_salariés

_Q° : Votre entreprise emploie :_
- select_moins_de_1000_salariés
- select_plus_de_1000_salariés

_Q° : Votre entreprise dispose-t-elle d’un Comité Social et Economique (CSE) ? :_
- select_CSE
- select_pas_de_CSE

_Q° : Votre entreprise appartient-elle à un groupe européen d’au moins 1000 salariés ? :_
- select_appartenance_groupe
- select_pas_d'appartence_groupe

_Q° : Votre entreprise emploie :_
- select_moins_de_50_salariés
- select_entre_50_et_999_salariés
- select_1000_salariés-ou_plus

### Tracking clics sur les aides** (en fonction des cas, l’aide peut-être au niveau de la question ou de la proposition) :
•    Category : outil
•    Action : comprendre sa procédure de licenciement
•    Name : clik_help_nom de la question ou réponse : 

_Q° : Par quel type de licenciement êtes-vous concerné ? :_ _=> sur toutes les réponses_
- click_help_licenciement_personnel
- click_help_licenciement_économique
- click_help_licenciement_APC

_Q° : Quel est le motif de ce licenciement ? :_  _=> sur la réponse "Vous n'êtes concerné par aucun de ces cas (motif non disciplinaire)" OU "Aucun de ces cas (motif non disciplinaire)" selon le parcours "salarié" ou "employeur"_
- click_help_licenciement_non_disciplinaire

_Q° : Votre entreprise appartient-elle à un groupe européen d’au moins 1000 salariés ? :_ _=> sur la question_
- click_help_groupe

_Q° : Votre entreprise dispose-t-elle d’un Comité Social et Economique (CSE) ? :_ _=> sur la question_
- click_help_CSE

**Comment by m-maillot** [comment]
Résultat des tests:

### Tacking nombre de clics sur les différents onglets :
•    Category : page_information
•    Action : procédures_licenciement
•    Name : click_onglet_procedure_infographie / click_onglet_procedure_texte / click_onglet_simulateurs / click_onglet_autres_ressources

**--> OK**

### Tracking clics sur le bouton « afficher les infos personnalisées » :
•    Category : outil
•    Action : comprendre sa procédure de licenciement
•    Name : click_afficher_les_infos_personnalisées

**--> OK**

### Tracking des questions "vues"** (pour identifier les questions qui générent des abandons)
•    Category : outil
•    Action : comprendre sa procédure de licenciement
•    Name : view_question_nom de la question : 
- view_question_profil
- view_question_type de licenciement
- view_question_motif de licenciement
- view_question_nombre de salariés licenciés
- view_question_nombre de salariés dans l'entreprise
- view_question_appartenance à un groupe
- view_question_CSE

**--> OK**

### Tracking parcours les plus sollicités :
•    Category : outil
•    Action : comprendre sa procédure de licenciement
•    Name : select_Réponse sélectionnée : 

_Q° : Vous êtes :_
- select_salarié 
- select_employeur

_Q° : Par quel type de licenciement êtes-vous concerné ? :_
- select_licenciement_personnel
- select_licenciement_économique
- select_licenciement_APC

_Q° : Quel est le motif de ce licenciement ? :_
- select_licenciement_disciplinaire
- select_licenciement_non_disciplinaire
- select_licenciement_inaptitude

_Q° : Combien de salariés sont concernés par ce licenciement ? :_
- select_1_seul_salarié
- select_entre_2_et_9_salariés
- select_au_minimum_10_salariés

_Q° : Votre entreprise emploie :_
- select_moins_de_1000_salariés
- select_plus_de_1000_salariés

_Q° : Votre entreprise dispose-t-elle d’un Comité Social et Economique (CSE) ? :_
- select_CSE
- select_pas_de_CSE

_Q° : Votre entreprise appartient-elle à un groupe européen d’au moins 1000 salariés ? :_
- select_appartenance_groupe
- select_pas_d'appartence_groupe

_Q° : Votre entreprise emploie :_
- select_moins_de_50_salariés
- select_entre_50_et_999_salariés
- select_1000_salariés-ou_plus

**--> OK**

### Tracking clics sur les aides** (en fonction des cas, l’aide peut-être au niveau de la question ou de la proposition) :
•    Category : outil
•    Action : comprendre sa procédure de licenciement
•    Name : clik_help_nom de la question ou réponse : 

_Q° : Par quel type de licenciement êtes-vous concerné ? :_ _=> sur toutes les réponses_
- click_help_licenciement_personnel
- click_help_licenciement_économique
- click_help_licenciement_APC

_Q° : Quel est le motif de ce licenciement ? :_  _=> sur la réponse "Vous n'êtes concerné par aucun de ces cas (motif non disciplinaire)" OU "Aucun de ces cas (motif non disciplinaire)" selon le parcours "salarié" ou "employeur"_
- click_help_licenciement_non_disciplinaire

_Q° : Votre entreprise appartient-elle à un groupe européen d’au moins 1000 salariés ? :_ _=> sur la question_
- click_help_groupe

_Q° : Votre entreprise dispose-t-elle d’un Comité Social et Economique (CSE) ? :_ _=> sur la question_
- click_help_CSE

**--> OK**


Evènements supplémentaires détectées :

### Quand on arrive sur l'outil

•    Category : outil
•    Action : view_step_Comprendre sa procédure de licenciement
•    Name : start

### Quand on clic sur un simulateur depuis la page info

•    Category : selectResult
•    Action : {"url":"/outils/indemnite-licenciement"}

### Note

Dès qu'on revient sur l'outil, on renvoit les events view_step et view page. Idem si on modifie une réponse. Dans le parcours, cela va engendrer du bruit sur les events d'affichage de l'outil.
