### ISSUE TITLE
bug affichage du champ ( chrome)

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#454]
![image](https://user-images.githubusercontent.com/37538697/51534842-33ad0880-1e47-11e9-9724-21d1cf0f2f72.png)
affichage de la bordure du champ dans chrome. Selon le niveau de zoom, la bordure disparait: ce qui peut expliquer en partie certains retours de tests utilisateurs d'hier:
-> difficulté à trouve le champ de saisie
-> essayer d'effacer l'exemple dans le champ, pour saisir sa requête

**Comment by revolunet** [comment]
navigateur ?

**Comment by jrduscher** [comment]
CHROME, Version 71.0.3578.98 (Build officiel) (64 bits)

**Comment by lionelB** [comment]
fixed by #472
