### ISSUE TITLE
[Analyse] Changement de H1 d'une contribution

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4540]
Ici l'idée est seulement d'voir une première idée pour répondre aux questions ci-dessous, si une tâche trop couteuse est nécessaire pour modifier un H1 on laissera cette tâche de côté

1) Si on change le title d'un contenu (notamment pages contribution et modèles de courrier), est-ce que le H1 est automatiquement modifié en se basant sur le title ?

2) Comment modifier le H1 d'un contenu ?

**Comment by Viczei** [comment]
1. oui le title (indiqué pour la page info dans l'admin) est utilisé en tant que meta_title pour la page
2. on peut rajouter un champs meta_title dans le formulaire de l'admin afin de pouvoir mettre autre chose que le title
