### ISSUE TITLE
Intégrer le message "Convention collective prochainement traitée"

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4575]
Lorsque l'usager sélectionne une CC qui n'est pas encore intégrée mais qui fait partie des lots de CC à intégrer on affiche : 

![image](https://user-images.githubusercontent.com/84397271/192987899-88a05f5c-5682-45b7-b37b-c7365929b480.png)

**Comment by carolineBda** [comment]
Pour moi c'est déjà fait :
![Screenshot from 2022-10-13 14-49-20](https://user-images.githubusercontent.com/4971715/195600787-c8170d8f-9ea5-4281-b0c8-d30ae05e2447.png)
C'est affiché pour toutes les CC implémentés pour le préavis de retraite qui ne sont pas encore implémentées pour l'indémnité de licenciement
