### ISSUE TITLE
pouces hauts / pouces bas UX

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#458]
suite au GT du 21/01
il apparaît que le système de pouces haut pouces bas n'est pas compris par l'usager( pas compréhensible, pas explicite).
Cela ne concerne pas à première vue le contenu de la modal qui suit l'appui sur le pouce bas.

**Comment by lionelB** [comment]
- ajouter une affordance bouton sur les pouces
- faire remonter la query dans event value

**Comment by jeremiecook** [comment]
Deux remarques : Il y avait sur les wireframes un infobulle au survol de ces deux boutons pour indiquer le sens de l'action. Ce serait surement plus clair pour les usagers (ne pas oublier que sur mobile on n'a pas de survol, donc il faudrait imaginer une présentation différente)
Le curseur ne change pas lorsque passe sur ces boutons, donc il n'est pas très clair qu'ils sont cliquables.
