### ISSUE TITLE
Préparer environnement de test pour les pages procédures de licenciement + le questionnaire

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4580]
Il faudrait pouvoir donner accès à des personnes externes à l'équipe CDTN à une "branche" sur laquelle on aurait les pages information procédures de licenciement et le questionnaire "comprendre sa procédure de licenciement" pendant 15 jours par exemple.

Par contre les pages information et le questionnaire ne devront pas être publiés en preprod ou en prod pendant cette période

**Comment by m-maillot** [comment]
Attendre la décision de réaliser les tests directement en prod ou pas.
