### ISSUE TITLE
Bug balises dans les contrib

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4596]
Dans les 2 exemples ci-dessous on ne voit pas d'erreur de rédaction de la balise dans loutil de contrib pourtant la balise apparrement etxtuellement à la place de créer l'accordéon :

https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/contribution/en-cas-de-maladie-le-salarie-a-t-il-droit-a-une-garantie-demploi

![image](https://user-images.githubusercontent.com/84397271/195401931-6670285d-95cf-4bc5-b637-3fc432f9adad.png)

https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/contribution/dans-le-cadre-dun-cdd-quel-est-le-montant-de-lindemnite-de-fin-de-contrat 

![image](https://user-images.githubusercontent.com/84397271/195401603-ee65151b-0be4-421f-8d2f-bc859b79ce68.png)

**Comment by carolineBda** [comment]
Le problème provient du fait qu'un tooltip a été ajouté dans le title du TAB

**Comment by romain-b13** [comment]
Sprint 23 Analyser :
- la gestion des tooltips
