### ISSUE TITLE
Retirer messages de transition CC 3239

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4604]
On peut désormais désactiver les messages qui avait été rédigés au moment de la fusion entre les CC 2111 te 2395 pour former la CC 3239. Ci-dessous la liste des contenus où on retrouve le message à retirer : 

### 1- Page CC de la 3239
https://code.travail.gouv.fr/convention-collective/3239-particuliers-employeurs-et-emploi-a-domicile

![image](https://user-images.githubusercontent.com/84397271/196126918-7e0fab90-8879-41b9-8737-733bf279ef06.png)

### 2- Toutes les pages personnalisables lorsqu'on sélectionne la CC 3239 (contributions)

Ex de page personnalisable : https://code.travail.gouv.fr/contribution/les-conges-pour-evenements-familiaux

![image](https://user-images.githubusercontent.com/84397271/196127582-71a2721b-6b59-4961-a4e8-684ecbb3e5d1.png)

### 3- Les simulateurs 

- **Préavis de démission (que pour la catégorie professionnelle "assistants maternels")**

https://code.travail.gouv.fr/outils/preavis-demission

![image](https://user-images.githubusercontent.com/84397271/196155829-dc427d35-c87b-4c4c-966a-432ac7183ef9.png)

- **Préavis de départ à la retraite (que pour la catégorie professionnelle "assistants maternels")**

https://code.travail.gouv.fr/outils/preavis-retraite

![image](https://user-images.githubusercontent.com/84397271/196157870-21bb30b3-49a0-4d92-89bd-a363cdbb1613.png)

### 4- Moteur de recherche des CC

Enlever le message sous le nom de la CC qui se trouve dans le moteur de recherche de CC (que ce soit sur une page personnalisable, un simulateur ou sur l'outil "trouver sa CC")

Par contre on conserve bien les synonymes utilisés dans le moteur de recherche de CC => ex : si je tape "assistante maternelle" je dois avoir la CC 3239 en résultat proposé

![image](https://user-images.githubusercontent.com/84397271/196158349-56f907b2-ef95-485d-99c5-34ef3c04adef.png)

### 5- Tuile de résultat du moteur de recehrche interne

Par contre on conserve bien les synonymes utilisés dans le moteur de recherche du CDTN => ex : si je tape "assistante maternelle" je dois avoir la page de la CC 3239 en résultat proposé

![image](https://user-images.githubusercontent.com/84397271/196158605-3b9309dd-48dd-44bd-b7bf-94ef584cc2f1.png)

### Question concernant le SEO

Sur la page CC de la CC 3239 on n'aura plus dans le chapeau introductif de la page les expressions "assistants maternels" et "salariés du particulier employeur" => est-ce qu'on risque de ne plus apparaître lors d'une recherche "Google" avce ces mots clés ? 

On retrouve ces expressions clés quand même dans la page si on déplie les accordéons pour la plupart des questions

Même questions pour les pages personnalisables déjà personnalisées avec la CC 3239 depuis une recherche sur un moteur externe => pour la plupart des questions on aura dans la réponse les mots clés "assistants maternels" et "salariés du particulier employeur" mais on n'aura plus le chapeau introductif avec ces mots clés et qui était présent pour toutes les questions

**Comment by m-maillot** [comment]
Tâches à réaliser :
 - [ ] Retirer le highlight sur la CC 3239 dans l'admin
 
 ```json
 "highlight": {
    "title": "À noter : les informations données sur cette page sont applicables depuis le 01/01/2022",
    "content": "Cette convention collective est entrée en vigueur au 01/01/2022 suite à la fusion des conventions collectives “Salariés du particulier employeur (IDCC 2111)” et “Assistants maternels du particulier employeur (IDCC 2395)” qui étaient applicables jusqu’au 31/12/2021.",
    "searchInfo": "(anciennement conventions collectives “Assistants maternels du particulier employeur” IDCC 2395 et “Salariés du particulier employeur” IDCC 2111)."
  },
```

 - [ ] Supprimer la note pour la CC 3239 dans le fichier json `preavis-demission.data.json`
 
  - [ ] Supprimer la note pour la CC 3239 dans le modèle de préavis de retraite
