### ISSUE TITLE
Préparation campagne SEA

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4608]
Lors de la 2eme semaine du sprint vous serez sollicité pour :
- l'intégration des tags (google tags etc)
- la mise en place du bandeau cookies
- permettre d'avoir la data dans l'onglet campagne de matomo : il me semble avoir compris qu'il faut utiliser [l'url builder tool](https://matomo.org/docs/tracking-campaigns/) de matomo, qui permet à matomo d'identifier les visites et les mettre dans l'onglet campagne

**Comment by maxgfr** [comment]
Ce que j'ai dit sur mattermost :

Pour résumer, il faut impérativement passer des paramètres à l'URL. Les deux paramètres obligatoires sont les mots clés et le nom de la campagne. L'exemple est ici: [https://code.travail.gouv.fr?mtm_campaign=NOM_CAMPAGNE_SEA&mtm_kwd=MON_MOT_CLE](https://code.travail.gouv.fr/?mtm_campaign=NOM_CAMPAGNE_SEA&mtm_kwd=MON_MOT_CLE)

Le premier lien liste les paramètres qu'on peut passer à l'url pour l'identifier : https://matomo.org/faq/reports/what-is-campaign-tracking-and-why-it-is-important/

Le second lien permet de générer cet url via un outil qu'ils ont développé et que je vous conseille d'utiliser : https://matomo.org/faq/tracking-campaigns-url-builder/
