### ISSUE TITLE
Des visites issues de sites externes sont comptabilisées comme des entrées directes

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4616]
**Problème**
Il semble que bcp d'entrées en provenance de sites externes ne soient pas comptabilisées comme telles mais sûrement comme des entrées directes.
Si on se focalise sur l'exemple du site service-public.fr on voit qu'on reçoit seulement 52 visites de leur site sur toute l'année 2022 alors qu'ils référencent pas mal de nos simulateurs et modèles sur des sujets sollicités

![image](https://user-images.githubusercontent.com/84397271/197992663-eaeaa677-0bf5-4cfd-97d6-f9aa14fcc555.png)

**Comment by m-maillot** [comment]
Avec les nouvelles règles du nofollow, il est compliqué de suivre cette indication. On a déjà le src_url que l'on peut indiquer à nos partenaires. 
A voir s'il n'existe pas d'autres moyens et ce que dit matomo sur le sujet ?

**Comment by carolineBda** [comment]
Pour moi le seul moyen est de demander aux sites externes que l'ont connaît d'ajouter un param `src_url` dans leur backlinks
