### ISSUE TITLE
[ GT suites] Suggestions: amélioratoin annuaire

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#464]
1)	Annuaires :
-	[x] CICAS: questions retraite complémentaire. Wording à ajouter.
-	[x] Ajouter le lien dans les numéros de téléphone : renvoi vers interface type Google Map ?
-	[x] Chambres consulaires : à faire descendre dans les propositions d'annuaires
-	[x] Ajouter de nouveaux contacts : comme les Maisons de la justice et du droit
-	[ ] L’utilisateur cherche à cliquer sur la tuile et attend une action (renvoi direct vers le contact, affichage détails ?)-->UX/SPEC, dev in 1.10?

**Comment by lionelB** [comment]
>  L’utilisateur cherche à cliquer sur la tuile et attend une action (renvoi direct vers le contact, affichage détails ?)-->UX/SPEC, dev in 1.10?

@jrduscher pour le dernier point on fait quoi ?
