### ISSUE TITLE
Entreprises manquantes sur la recherche via l'API mon-entreprise

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#4655]
Actuellement si l'on recherche "CARREFOUR HYPERMARCHES" ou le siret "82161143100015" on ne trouve pas les résultats correspondant.
Hors cette recherche fontionnait il y a quelques jours.

L'appel fait à l'API est le suivant :
`https://api.recherche-entreprises.fabrique.social.gouv.fr/api/v1/search?ranked=true&query=CARREFOUR%20HYPERMARCHES&convention=true&employer=true&open=true`

Si l'on retire le param `employer`, l'API retourne bien les résultats attendus.

**Comment by m-maillot** [comment]
Pour info, depuis la [demo du site](https://recherche-entreprises.fabrique.social.gouv.fr/), j'ai bien le résultat `CARREFOUR HYPERMARCHES` qui remontent assez haut dans la liste (4ème position)

**Comment by m-maillot** [comment]
J'ai remarqué que la réponse disparaissait dès que je cochais Uniquement les entreprises avec des employés. 
Je suis allé voir sur le repo et je n'ai pas vu de nouvelle version récemment pouvant expliquer cela. Idem pour la maj des données. Il y en a eu une il y a 1 mois mais elle n'est pas passée. Je l'ai relancé du coup.

Rien n'explique ce changement soudain. Je vais regarder dans le code s'il y a une source de données externes qui peut changer.

**Comment by m-maillot** [comment]
Il y a bien eu un changement des données sur l'entreprise `CARREFOUR HYPERMARCHES`, le 1er novembre 2022.

L'API recherche-entreprise, utilise le fichier https://files.data.gouv.fr/insee-sirene/StockUniteLegale_utf8.zip (cf: https://github.com/SocialGouv/recherche-entreprises/blob/7c82e70e33af0427b0fb2883cf65bf9060a7c34d/index/sqlite/build.sh#L63) pour les données de l'entreprise. 

La donnée utilisée par l'API pour le flag `Uniquement les entreprises avec des employés` est `caractereEmployeurUniteLegale`. Ce dernier est passé de `O` à `N` le 1er novembre 2022 quand on compare les 2 versions :

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/992514/201643701-3650f140-cb29-43ca-9dfe-d4a533ba758c.png">

Il y a également le flag `societeMissionUniteLegale` qui est passé de `N` à `O`.

Du coup, la disparition de l'entreprise `CARREFOUR HYPERMARCHES` est normal selon les paramètres. Reste à valider si c'est logique.

Si on regarde la documentation de ces deux flags (dispo ici : https://www.data.gouv.fr/fr/datasets/base-sirene-des-entreprises-et-de-leurs-etablissements-siren-siret/#description), on a :

<img width="883" alt="image" src="https://user-images.githubusercontent.com/992514/201644141-30a5a75b-0c92-439c-a120-7cc290e3a70b.png">

<img width="863" alt="image" src="https://user-images.githubusercontent.com/992514/201644267-942854cd-3694-4534-9131-47693a66c6aa.png">

Ce qui me semble bon aussi. Cela signifie que la société `CARREFOUR HYPERMARCHES` n'est plus employeuse.

Peut être un soucis dans la mise à jour des données ? Voir peut être avec le métier.

**Comment by maxgfr** [comment]
Go repasser sur michelin 💛💙

**Comment by m-maillot** [comment]
Le flag `employer` a été désactivé en attendant un correctif des données ou de l'API recherche-entreprise.

**Comment by m-maillot** [comment]
Il faut réacitver le flag, les données ont été corrigées
