### ISSUE TITLE
[Bug?] affichage de trois résultats identiques à la suite

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#468]
![image](https://user-images.githubusercontent.com/37538697/51761957-b5629780-20ce-11e9-87d7-4c41954d204f.png)

un bug ou une réminiscence d'un problème déjà constaté?

**Comment by ClementChapalain** [comment]
Le bug est en prod (c'est le même contenu derrière les 3 résultats) mais pas sur la version dev, est-ce que c'est un bug qu'on a corrigé @lionelB ?

**Comment by lionelB** [comment]
corrigé suite au modif ES
