### ISSUE TITLE
Intégration de nouveaux modèles de courriers

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4688]
### Modèle déjà existant, juste une modif du contenu : 

https://code.travail.gouv.fr/modeles-de-courriers/releve-dheures-supplementaires

[tableau_recap_des_heures_supplementaires.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/10043535/tableau_recap_des_heures_supplementaires.docx)

### Promesse d'embauche

**Description**
La promesse d’embauche est un acte par lequel l’employeur donne la possibilité à un candidat de conclure un contrat de travail avec lui. 
Elle doit faire apparaître avec suffisamment de précision :
- le poste 
- la rémunération 
- la date d’entrée en fonction
Le contrat de travail sera définitivement formé quand le bénéficiaire de cette offre aura donné son consentement, c’est-à-dire quand il aura accepté la promesse d’embauche qui lui a été faite. Ce dernier dispose d’un certain délai pour faire connaître sa décision. 
À noter : 
•	La rédaction d’une promesse d’embauche ne dispense pas l’employeur de son obligation éventuelle d’établir un contrat de travail.
- L’employeur, dès lors qu’il a émis la promesse d’embauche, s'engage à recruter le candidat. Seule une réponse négative du candidat ou son silence à l'issue du délai de réflexion le libère de son engagement. Toute rétractation de sa part en dehors de ces cas entraînera les effets d’un licenciement sans cause réelle et sérieuse.
- Le salarié, dès lors qu’il a accepté la promesse d’embauche, ne peut plus se rétracter librement. Son désengagement sera assimilé à une démission.

**Références juridiques** 

[Article 1124 du Code civil](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000032040818/)
[Cour de cassation, chambre sociale, 10 mars 2004, n° 01-45.518](https://www.legifrance.gouv.fr/juri/id/JURITEXT000007468617)
[Cour de cassation, chambre sociale, 6 juillet 2016, n° 15-11.138](https://www.legifrance.gouv.fr/juri/id/JURITEXT000032868133/)
[Cour de cassation, chambre sociale, 21 septembre 2017, n° 16-20.103](https://www.legifrance.gouv.fr/juri/id/JURITEXT000035616989/)
[Cour de cassation, chambre sociale, 21 septembre 2017, n° 16-20.104](https://www.legifrance.gouv.fr/juri/id/JURITEXT000035617009/)

[Promesse _d_embauche.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/10043538/Promesse._d_embauche.docx)

### Lettre de licenciement économique envoyée à titre conservatoire - CSP

**Desciption**
Lorsqu’un licenciement pour motif économique est envisagé dans une entreprise de moins de 1000 salariés, l’employeur a l’obligation de proposer au salarié concerné un contrat de sécurisation professionnelle. À compter du moment où il reçoit la proposition, celui-ci dispose de 21 jours pour accepter ou refuser d’adhérer à un tel dispositif. En cas de refus ou d’absence de réponse à l’expiration du délai, l’employeur procède à son licenciement pour motif économique.

Dans certains cas, les règles régissant les délais en matière de licenciement permettent à l’employeur d’envoyer une lettre de licenciement avant même que ne se soient écoulés les 21 jours de réflexion. 
Il s’agit alors d’un licenciement à titre conservatoire, qui sera possible dans les situations suivantes : 

-	Licenciement d’un seul salarié pour motif économique 
L’employeur doit attendre 7 jours ouvrables après la date de l’entretien préalable (15 jours si le salarié est cadre et 2 jours en cas de redressement ou liquidation judiciaire) pour pouvoir envoyer la lettre de licenciement (articles L.1233-15 et L.1233-59 du Code du travail).

-	Licenciements de 2 à 9 salariés pour motif économique 
L’employeur doit attendre 7 jours ouvrables après la date de l’entretien préalable (2 jours en cas de redressement ou liquidation judiciaire) pour pouvoir envoyer la lettre de licenciement (articles L.1233-15 et L.1233-59 du Code du travail).

-	Licenciements d’au moins 10 salariés lorsque l’entreprise compte plus de 50 salariés, qu’elle est pourvue d’un CSE et que le projet a déjà obtenu la validation ou l’homologation par l’administration. 
L’employeur ne peut envoyer la lettre de licenciement qu’une fois qu’il a reçu la réponse positive de l’administration ou, si celle-ci garde le silence, après l’écoulement d’un délai de 15 jours pour la demande de validation et 21 jours pour la demande d’homologation (article L.1233-39 du Code du travail).

-	Licenciement économique d’au moins 10 salariés sur une période de 30 jours, dans une entreprise de plus de 50 salariés et sans CSE, dès lors que l’administration a homologué le projet avant que le délai de réflexion du salarié ne soit écoulé. 
L’employeur ne peut envoyer la lettre de licenciement qu’après avoir obtenu la réponse positive de la DREETS ou, si celle-ci ne s’est pas prononcée, après un délai de 21 jours (article L.1233-39 du Code du travail).

À noter : Le licenciement à titre conservatoire n’est pas possible dans le cas d’un licenciement économique d’au moins 10 salariés, dans une entreprise de 50 salariés maximum. Si vous êtes concerné par cette hypothèse : voir le modèle [Lettre de licenciement économique envoyée à titre définitif - CSP](https://code.travail.gouv.fr/modeles-de-courriers/lettre-de-licenciement-economique-envoyee-a-titre-definitif-csp) 

**Références juridiques** 

- Article L.1233-15 du Code du travail
https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000032344944

- Article L.1233-59 du Code du travail 
https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000006072050/LEGISCTA000006189440

[Lettre_de_licenciement_economique_envoyee_a_titre_conservatoire _CSP.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/10043542/Lettre_de_licenciement_economique_envoyee_a_titre_conservatoire._CSP.docx)

### Lettre de licenciement économique envoyée à titre définitif - CSP

**Description**
Lorsqu’un licenciement pour motif économique est envisagé dans une entreprise de moins de 1000 salariés, l’employeur a l’obligation de proposer au salarié concerné un contrat de sécurisation professionnelle. À compter du moment où il reçoit la proposition, celui-ci dispose de 21 jours pour accepter ou refuser d’adhérer à un tel dispositif. En cas de refus ou d’absence de réponse à l’expiration du délai, l’employeur procède à son licenciement pour motif économique.

À noter : ce modèle de lettre ne concerne que les hypothèses où l’employeur notifie le licenciement après que se soient écoulés les 21 jours de réflexion du salarié. 
Dans certains cas, les règles régissant les délais en matière de licenciement permettent à l’employeur d’envoyer une lettre de licenciement avant même que ne se soient écoulés les 21 jours de réflexion. La lettre de licenciement est alors envoyée à titre conservatoire, voir le modèle : [Lettre de licenciement économique envoyée à titre conservatoire - CSP](https://code.travail.gouv.fr/modeles-de-courriers/lettre-de-licenciement-economique-envoyee-a-titre-conservatoire-csp) .

Le modèle de lettre suivant concerne :

- Les licenciements pour motif économique de 10 salariés ou plus, dans une entreprise comptant moins de 50 salariés (avec ou sans CSE).
L’employeur doit alors attendre 30 jours après le dépôt du projet auprès de la DREETS pour pouvoir envoyer la lettre de licenciement (article L.1233-39 du Code du travail).

- Les licenciements pour motif économique de 10 salariés ou plus, dans une entreprise de plus de 50 salariés dès lors que l’homologation ou la validation du projet par la DREETS intervient après la fin du délai de réflexion de 21 jours accordé au salarié.
L’employeur ne peut envoyer la lettre de licenciement qu’après validation ou homologation du projet par la DREETS (article L.1233-39 du Code du travail).

- Plus généralement, toutes les lettres de licenciement qui auront vocation à être envoyées par l’employeur alors que le délai de réflexion de 21 jours du salarié se sera entièrement écoulé.

**Références juridiques** 

Article L.1233-39 du Code du travail 
https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000027566048

[Lettre_de_licenciement_economique_envoyee_a_titre_definitif_csp.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/10056138/Lettre_de_licenciement_economique_envoyee_a_titre_definitif_csp.docx)

**Comment by m-maillot** [comment]
### Promesse d'embauche

meta description :

> La promesse d’embauche est un acte par lequel l’employeur donne la possibilité à un candidat de conclure un contrat de travail avec lui. Elle doit faire ap

### Lettre de licenciement économique envoyée à titre définitif - CSP

meta description : 
> Lorsqu’un licenciement pour motif économique est envisagé dans une entreprise de moins de 1000 salariés, l’employeur a l’obligation de proposer au salarié

### Lettre de licenciement économique envoyée à titre conservatoire - CSP

meta description :
> Lorsqu’un licenciement pour motif économique est envisagé dans une entreprise de moins de 1000 salariés, l’employeur a l’obligation de proposer au salarié 

Voici la liste des meta descriptions, il pourrait être intéressant de revoir leur formulation ?
