### ISSUE TITLE
Gestion des erreurs

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#471]
Définir les messages d'erreurs à afficher
 - [ ] prévoir les cas ou l'API est down
 - [ ] prévoir les cas ou Elastic est down
 - [ ] définir les messages quand aucun résultat
 - [ ] ensure we always get errors sent to sentry
 - [ ] message quand connexion HS

**Comment by UnbearableBear** [comment]
On pourrait afficher un toast quand on detecte que l'user est offline !

**Comment by revolunet** [comment]
Idéalement le build statique (outils...) devrait fonctionner et les autres contenus se dégrader "progressivement". ex: home et outils fonctionnels

**Comment by lionelB** [comment]
j'ai deja fait ces tests (elastic off, api off) ca renvoi des erreur 400 / 500 en fonction, on pourrait définir des code custom pour identifier les pannes  (elastic off, api off, nlp off,...)
