### ISSUE TITLE
Le moteur de recherche ne fait pas apparaitre le calculateur

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#474]
Le calculateur n'apparaitpas dans les réponses possibles relatives aux paramètres de calcul particuliers qu'il embarque: 

 inaptitude origine professionnelle temps plein temps partiel 
ajouter dans la description du calculateur le smots clés en quetsion suffiraient?: histoire que ça matche un peu quand on tape des querys comme " inaptitude professionnelle ayant 18 ans [d'ancienneté]".

**Comment by lionelB** [comment]
> ajouter dans la description du calculateur le smots clés en quetsion suffiraient?:

on peut essayer, dans ce cas, est ce que tu peux fournir une premiere liste de phrase / mot cle qu'on pourrait indexer ?

**Comment by jrduscher** [comment]
#495
