### ISSUE TITLE
[indemnité de licenciement] Correctif à apporter pour la CC 650

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4742]
Suite à un retour des op de la CC 650 il va falloir ajouter une question à l'étape "information" pour cette CC après la question sur l'âge du salarié.

Si l’usager répond 61, 62, 63, ou 64 à la question "Quel est l'âge du salarié ?" il faut poser la question suivante :

Le salarié remplit-il les conditions pour partir à la retraite ? (obligatoire)

S’il rep « non » => il ne faut pas appliquer la minoration

**Comment by maxgfr** [comment]
Il faudrait mettre un `i` pour que l'utilisateur comprenne cette question je pense

**Comment by romain-b13** [comment]
Bérengère regarde quelle formule on doit appliquer si l'usager indique 65 ans ou plus

**Comment by romain-b13** [comment]
@maxgfr 
1) Ajouter un point d'aide à la question : « Le salarié remplit-il les conditions pour partir à la retraite ? » :

"Répondre oui si le salarié a les trimestres suffisants pour bénéficier d’une retraite à taux plein et s’il peut bénéficier d’une retraite complémentaire sans abattement"

2) Pour la CC 650, si c'est le résultat conventionnel qui est affiché (c-a-d s'il est plus favorable que le légal) alors on ajoute un astérisque au niveau du résulat :

Le montant de l'indemnité pourrait être plus important si, avant le CDI, sous certaines conditions, le salarié a été lié à l’employeur par d'autres contrats
