### ISSUE TITLE
[indemnité de licenciement] Faire une passe sur 2 cas pour la CC 650

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4743]
Les OP de la CC 650 nous on fait une retour sur 2 cas pour lesquels ils n'obtiennnent pas le même résultat (écart de 6- 7€)
Quand on refait les calculs à la main on obtient en effet le même résultat que les OP
=> regarder si pour ce cas là on utilise bien la même formule que ci-dessous
=> regarder si pour ce cas là on utilise bien 3,92 pour l'ancienneté
=> est-ce un pb d'arrondi ?
=> est-ce qu'on peut avoir le même type d'écart sur d'autres CC ?

**Cas 1 : 62 ans ; 10 ans et 11 mois d’ancienneté ; Sref = 3500€** 
o	Résultat obtenu par l’OP : 11 818, 8€

o	Résultat obtenu à la main :
[ (1/5)Sref * 7] + [(3/5)Sref * 3.92] – {1/10*[ (1/5)Sref * 7] *0.9
= 13 132 – [(1/10)*13 132] 
= 13 132 – 1 313.2 
= 11 818.8 €

o	Résultat obtenu par le simulateur : 
= 11 812, 5 €

**Cas 2 : 45 ans ; 10 ans et 11 mois d’ancienneté ; Sref = 3 500€**
o	Résultat obtenu par l’OP : 13 132 €

o	Résultat obtenu à la main, selon la formule suivante : 
[(1/5)* Sref * 7] + [(3/5)* Sref * 3.92]
= 4 900 + 8 238 
= 13 132 €

o	Résultat obtenu par le simulateur : 13 125 €

**Comment by m-maillot** [comment]
Pour le premier cas, on a une ancienneté de 10 ans + 11 mois, soit 10 + 11/12 => 11.916666666666666

Comme on ne fait pas d'arrondi, on utilisera cette valeur dans la formule, ce qui nous donne :

`((1/5) * Sref * 7) + ((3/5) * Sref * 3.916666666666666) – (1/10*((1/5) * Sref * 7) *0.9) = 11812,5 €`

Le soucis vient de l'ancienneté où l'on ne fait pas l'arrondi.

**Comment by m-maillot** [comment]
C'est idem pour le cas 2 :)
