### ISSUE TITLE
[Indemnité de licenciement] Modifier la question sur l'âge du salarié

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4766]
1) Sortir la liste des CC déjà implémentées qui ont une question sur l'âge du salarié

2) Le métier vérifie pour chacune de ces CC à quelle date doit-on prendre en compte l'âge du salarié (date du fin du préavis, date de la notification...)

3) On reformule chaque question selon ce que dit la CC

Exemples (à voir si on garde ce wording, notamment l'emploi du futur) : 
- Quel sera l'âge du salarié à la fin du préavis ?
- Quel est l'âge du salarié à la date de notification du licenciement ?

Du coup il n'y a plus de déclenchement d'une 2ème question du type "le salarié aura-t-il 56 avant la fin de son préavis ?"

**Comment by romain-b13** [comment]
Point d'avancé au 07/12/22 :

**a) La question**

Pour les CC qui ne précisent pas à quel moment on prend en compte l’âge du salarié => on ne fait rien pour le moment tant qu’on n’a pas demandé aux branches
Pour les CC qui précisent que l’âge est à prendre à la fin du préavis => on change la question en « Quel est l’âge du salarié à la date de fin du préavis (exécuté ou non) ? » 
Pour les CC qui précisent que l’âge est à prendre à la date de notification => on change la question en « Quel est l’âge du salarié à la date de notification de son licenciement ? »

/!\ est-ce que les précisions sont bien toutes dans l’excel ? (ex : la 1501 qui semble préciser que l’âge est à prendre à la date de notification) => Bérengère regarde

**b) Le message d’aide** **=> ne pas créer de message d'aide pour le moment mais voici une piste :** 
Etant donné qu’il y a pour une même CC plusieurs valeurs « limites » et qui vont dépendre de l’ancienneté etc. => pour toutes les CC où on pose une question sur l’âge on met le même message d’aide pour attirer l’attention sur « à partir de 50 ans » (sous réserve qu’aucune CC ne prévoit une majoration minoration en dessous de 50 ans ? => Bérengère regarde) :

Message à afficher :
Attention : à partir de 50 ans des minorations ou des majorations peuvent être appliquées au montant de l’indemnité

**Comment by romain-b13** [comment]
Ce que l'on peut faire à l'heure actuelle :

- CC 1702 => on change la question sur l'âge par : "Quel est l’âge du salarié à la fin de son préavis (exécuté ou non) ?"
- CC 1501 => on modifie la question en "Quel est l’âge du salarié à la date de notification de son licenciement ?"
- CC 1596 => on modifie la question en "Quel est l’âge du salarié à la fin de son préavis (exécuté ou non) ?"
- CC 1597 => on modifie la question en "Quel est l’âge du salarié à la fin de son préavis (exécuté ou non) ?"
- CC 650 => on modifie la question en "Quel est l’âge du salarié à la fin de son préavis (exécuté ou non) ?"
- CC 2609 => on modifie la question en "Quel est l’âge du salarié à la fin de son préavis (exécuté ou non) ?"

Du coup on ne déclenche plus de question supplémentaire telle que "Le salarié aura-t-il 56 ans avant la fin de son préavis ?"

A revoir => pour chaque CC revoir la valeur qui permet de passer à une autre formule car sur bcp de CC on avait interprété > 55 comme étant 56 ans or on doit interpréter > 55 comme 55 ans + 1 jour du coup dès qu'il entre la valeur 55 pour cette CC on applique la formule qui est dans la ligne > 55

**Comment by romain-b13** [comment]
Pour les CC suivantes est-ce que vous pouvez me dire svp dans le code quelle est la valeur qui entraine le changement de formule (apllication d'une minoration ou d'une majoration) ? Est-ce que c'est 45 vs 46, est-ce que c'est 50 vs 51, est-ce que c'est 55 vs 56 etc. ?

•	16
•	44
•	573
•	650
•	1501
•	1596
•	1597
•	2098
•	2216
•	1702
•	2609

**Comment by maxgfr** [comment]
CC 1501 : On applique la majoration à > 50 ans donc à 51 ans
CC 573 : On applique la majoration à >= 55 ans donc à 55 ans et >= 50 ans donc à 50 ans dans d'autres cas
CC 1596 : C'est appliqué à > 55 ans donc a 56 ans
CC 1597 : C'est appliqué à > 55 ans donc à 56 ans
CC 2098 : La majoration est appliquée à > 50 ans donc à 51 ans
CC 2216 : La majoration est appliquée à > 50 ans donc à 51 ans
CC 650 : >= 50 ans ; >= 55 ans ;  La majoration est appliquée à 50 ans et à 55 ans
:warning: CC 16 : >= 60 ans -> le salarié remplit il les conditions pour la retraite ; >= 61 ans -> majoration ou minoration. Après ça dépend, la CC est assez complexe pour le coup, mais globalement ça dépend vraiment des uses case....
CC 44 : >= 55 ans et >= 50 ans, donc à 50 ans et 55 ans


La 1702 et la 2609 je ne les ai pas trouvé

**Note** :  Les CCs où faut faire attention sont : 1501 ; 1596 ; 1597 : 2098 ; 2216

**Comment by romain-b13** [comment]
Cette tâche consite juste à modifier la question initiale "quel est l'âge du salarié ?" pour les CC qui avait cette question, voici la formulation à adopter selon la CC : 

- CC 16 : "Quel est l'âge du salarié à la date de notification de son licenciement ?"
- CC 44 : "Quel est l'âge du salarié à la date de notification de son licenciement ?"
- CC 573 : "Quel est l'âge du salarié à  la date de notification de son licenciement ?"
- CC 650 : "Quel est l'âge du salarié à la fin de son préavis (exécuté ou non) ?"
- CC 1501 : "Quel est l'âge du salarié à la date de notification de son licenciement ?"
- CC 1596 : "Quel est l'âge du salarié à la fin de son préavis (exécuté ou non) ?"
- CC 1597 :  "Quel est l'âge du salarié à la fin de son préavis (exécuté ou non) ?"
- CC 2098 : "Quel est l'âge du salarié à la date de notification de son licenciement ?"
- CC 2216 : "Quel est l'âge du salarié à la date de notification de son licenciement ?"
- CC 1702: "Quel est l'âge du salarié à la fin de son préavis (exécuté ou non) ?"
- CC 2609 : "Quel est l'âge du salarié à la fin de son préavis (exécuté ou non) ?"

Pour les CC où on déclenchait une 2eme question "Le salarié aura-t-il X ans avant la fin de son préavis ?" => il ne faut plus déclencher cette 2eme question car avec la reformulation de la question sur l'âge on connaitra déjà l'âge à la fin du préavis

Concernant la valeur qui déclenche le changement de formule (application d'une minoration ou majortaion) j'ai crée une carte à part : https://github.com/SocialGouv/code-du-travail-numerique/issues/4788

**Comment by maxgfr** [comment]
⚠️  1702 et 2609 ne sont pas encore mergé
