### ISSUE TITLE
[Indemnité de licenciement] Ajouter une notif au niveau du résultat conventionnel pour la CC 650

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4786]
**Fonctionnalité**
Pour la CC 650, si c'est le résultat conventionnel qui est affiché (c-a-d s'il est plus favorable que le légal) alors on ajoute un astérisque au niveau du résulat : 

Le montant de l'indemnité pourrait être plus important si, avant le CDI, sous certaines conditions, le salarié a été lié à l’employeur par d'autres contrats

**Comment by maxgfr** [comment]
Voir : https://github.com/SocialGouv/code-du-travail-numerique/issues/4742
