### ISSUE TITLE
[Indemnité de licenciement] Correctifs CC 413

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4790]
**II-Plafond à appliquer pour le total de l'indemnité en tant que Cadres et l'indemnité en tant que non-cadres** 
1) Quand le salarié est "Cadres" et a été "non-cadres" avant : on doit calculer l'indemnité en tant que "cadre" et l'indemnité en tant que "non-cadre", ensuite on ondditionne les 2 mais le résultat de cette addition est plafonné à **12*Sref**

2) Quand le salarié est "cadres directeurs généraux, directeurs de centre de formation en travail social et directeurs d'établissement ou de service" et a été "non-cadres" avant : on doit calculer l'indemnité en tant que "cadres directeurs généraux, directeurs de centre de formation en travail social et directeurs d'établissement ou de service" et l'indemnité en tant que "non-cadre", ensuite on additionne les 2 mais le résultat de cette addition est plafonné à **18*Sref**

**III-Plafond à appliquer** 
les plafonds séparement pour l'indemnité en tant que cadres et l'indemnité en tant que non-cadres ne semblent pas être appliqués :  

- Non cadres : Maximum de 6 mois
- Cadres : Maximum de 12 mois

Quand le salarié est cadres et a été non cadres avant il faut appliquer le plafond individuellement pour chaque indemnité (celle en tant que cadre et celle en tant que non-cadres)  et ensuite il y a un plafond pour la somme des 2 indemnités (point précédent)

Pour cas (calcul de l'indemnité pour le non cadre) : **il y a une source juridique qui n'est pas bonne** : il faut mettre les articles 17 et 10 (de l’annexe 6) => retirer l'article 47

**IV- Calculer l'ancienenté en tant que cadres et en tant que non-cadres**

Pour cette CC , lorsque l'usager est "cadres" ou "cadres directeurs généraux, directeurs de centre de formation en travail social et directeurs d'établissement ou de service" et qu'il a été "non-cadres" avant il faut pouvoir calculer l'ancienneté en tant que "cadres" et l'ancienneté en tant que "non cadres".

Ajd si l'usager dit qu'il est "cadres" ou "cadres directeurs généraux, directeurs de centre de formation en travail social et directeurs d'établissement ou de service" et répond "oui" à la question suivante qui est "Le salarié a-t-il précédemment occupé des fonctions non-cadres durant le contrat de travail ?" on pose la question : "Pendant combien de temps a-t-il occupé des fonctions non-cadres durant le contrat de travail ?" (cf imag cidessous) 

![image](https://user-images.githubusercontent.com/84397271/207360997-56e651c8-92f4-40aa-9a69-564df5a51958.png)

Il faut remplacer cette question par la question et le champ que l'on a mis pour la CC 16 (cf image ci-dessous) : 

![image](https://user-images.githubusercontent.com/84397271/207361195-a47b7be2-ff11-4004-a414-65372f4f6d57.png)

A l'étape "ancienneté", il faudra également faire comme pour la CC 16, c'est à dire demander à l'usager de renseigner la date de l'absence s'il a eu des absences : 

![image](https://user-images.githubusercontent.com/84397271/207361825-838fd5d8-5056-47d2-a5be-17ea8c1058ee.png)

**Comment by maxgfr** [comment]
Afficher la formule des plafonds aussi #4798

**Comment by maxgfr** [comment]
C'est quoi la source juridique fausse ?

**Comment by romain-b13** [comment]
> C'est quoi la source juridique fausse ?

c'est l'article 47
