### ISSUE TITLE
[Indemnité de licenciement] Afficher la formule du plafond/plancher lorsqu'il s'applique

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4798]
Pour les CC ci-dessous, lorsque c'est le plafond ou le plancher qui s'applique il faut que ce soit la formule de ce plafond ou plancher qui soit affichée à l'étape "résultat" du simulateur :  

- 1486
- 2098
- 2264

**Comment by maxgfr** [comment]
Pour la 413, on le fera dans l'issue directement de la 413

**Comment by maxgfr** [comment]
La 1486 a déjà été implémentée

**Comment by maxgfr** [comment]
@romain-b13  Il y a aussi : 
- 573 
- 650

**Comment by maxgfr** [comment]
La 2216 est traitée là : https://github.com/SocialGouv/code-du-travail-numerique/pull/4797

**Comment by maxgfr** [comment]
La 2609 a été traitée
