### ISSUE TITLE
Déterminer les dispositions spécifiques de chaque CCN par data-mining

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#48]
serait il possible techniquement de faire émerger de la compraison des CCN, des notions: alinéas, intitulé qui permettrait d'isoler des dipositions conventionnelles particulières qui ne font pas échos à un article du code du travail ( indemnité chou-blanc en boulangerie, classfication, heures pour recherche d'emploi)
L'idée est dans un premier temps de pouvoir révéler ce type de dispositions, et les intégrer au corpus de tags. une premièe étape pourrait être de faire émerger les thèmes principaux évoqués dans les CCN ( ce qui serait déjà top)

**Comment by revolunet** [comment]
Si je comprends bien la question, oui, on pourra classifier le contenu des textes des CCNs.
Pour ca il nous faut des données d'apprentissage, donc un certain nombre de CCNs dont le contenu est taggué manuellement. 

En additionnant les données de BDCC, des brochures, de KALI, on doit pouvoir faire remonter un peu d'infos aussi
