### ISSUE TITLE
[indemnité de licenciement] Revoir calcul ancienneté légale VS conventionnelle

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4804]
Exemple du fonctionnement actuel :

L'usager met 8 mois entre la date d'entrée et date de notif mais il met une absence pour maladie non pro => on le bloque car on enlève les 2 mois d'absence de l'ancienneté du salarié 
Cependant certaines CC ne décomptent pas l'absence pour maladie non pro de l'ancienneté du salarié donc s'il sélectionne ce type de CC il faut le laisser poursuivre la simulation même s'il n'aura rien pour le légal (car ancienneté inférieure à 8 mois pour le légal)

=> selon moi on gère déjà correctement ce cas

**Comment by romain-b13** [comment]
à voir avec @m-maillot car selon moi on gère ce cas

**Comment by m-maillot** [comment]
Exposer le fonctionnement actuel
