### ISSUE TITLE
[indemnité de licenciement] Bug sélection de CC

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4823]
Il y a un bug sur la branche feat indemnité de licenciement :
1- je sélectionne une CC 
2- je vais à l'étape suivante
3- je reviens sur l'étape CC 
4- je coche "Je ne souhaite pas renseigner ma convention collective (je passe l'étape)"
5- je vais à l'étape suivante
6- je reviens sur l'étape CC et je constate qu'une CC est sélectionnée (celle que j'avais sélectionnée la 1ere fois)
=> du coup ça me fait faire la simulation pour la CC en question alors que j'ai mis "Je ne souhaite pas renseigner ma convention collective

**Comment by maxgfr** [comment]
Problème résolu dans cette PR : https://github.com/SocialGouv/code-du-travail-numerique/pull/4826
