### ISSUE TITLE
[GT suites] Corrections calculateur indé_lict : sélection période vide alt tps plein/partiel

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#483]
bug du calculateur:  
 sur le formulaire de saisie des périodes d'Alternance temps plein, temps partiel: il est possible de créer une ou plusieurs périodes sans les remplir, sans que cela ne bloque l'avancée de l'users ( si ces périodes saisies ne sont pas remplies, le calcul et son résultat n'ont pas de sens)

**Comment by lionelB** [comment]
fixed by  #486
