### ISSUE TITLE
[Indemnité de licenciement] Mettre à la ligne le resultat en affichage mobile

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4830]
![Screenshot_2022-12-28-08-51-34-014_com android chrome](https://user-images.githubusercontent.com/84397271/209784393-0a78b75e-0df1-439f-9a1c-ccad3a8f827a.png)

**Comment by romain-b13** [comment]
Regarder affichage titre en mobile sur safari

**Comment by maxgfr** [comment]
Il y a le bug sur safari a corriger aussi

![image](https://user-images.githubusercontent.com/25312957/217832273-1a635edd-6d6f-4d83-ab66-a723ded6db02.png)
