### ISSUE TITLE
Créer fonction custom pour tracker les visiteurs en provenance de SP

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4835]
Toutes les URL des contenus CDTN intégrés sur les sites **service-public.fr** et **entreprendre.service-public.fr** intègre désormais : 
« _**?src_url=url de la fiche SP**_ » par ex : 

https://code.travail.gouv.fr/outils/indemnite-licenciement?src_url=https://service-public.fr/particuliers/vosdroits/F987

L'idée est donc de pouvoir voir ces visites dans la rubrique "site web" de Matomo

**Comment by romain-b13** [comment]
@maxgfr 
Pour info pour le moment on retrouve ces visites dans la rubrique "comportement" :

![image](https://user-images.githubusercontent.com/84397271/210822973-82f7a395-9e45-4cee-9db3-7c09c646eb50.png)


Mais dans l'idéal il les faudrait dans "Acquisition" -> "website"

**Comment by maxgfr** [comment]
https://github.com/SocialGouv/matomo-next/pull/88

**Comment by romain-b13** [comment]
Il faudrait voir le total des visites provenant du site SP ici : 

![image](https://user-images.githubusercontent.com/84397271/212278216-be92abfe-fb13-4b8c-b43b-861104eb2b13.png)
