### ISSUE TITLE
Annuaires: nouvelle passe enrichissement via annuaire sp-fr

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#484]
Integrer de nouveaux contacts.
par thème?

**santé sécurité et Conditions de travail**
- bureau d'aide aux victimes
- carsat
- CPAM
- CIDFF
- MDPH

- URSSAF

**Contentieux**
- conseil des prud'hommes
-Cour d'appel
- Tribunal adminsitratif.

**aide juridique**
-maison de justice et du droit
- DIRECCTE ( à défaut d'une granularité plus précise à venir)
- "permanence juridique" à explorer, je ne vois pas ce que c'est et surtout si ça recouvre notre champs

**chambres consulaires**
-chambre d'agriculture
- CCI
- chambre des métiers

**Formation**
- Fongecif

**Emploi**
- Missions locales
- pole emploi

**Comment by ClementChapalain** [comment]
Besoin de :
1. prioriser les contacts à intégrer
2. revoir l'ux en fonction du nombre de résultats et des infos à afficher
3. récupérer la liste des contacts

**Comment by revolunet** [comment]
A propos des services de renseignement, on a des données HS sur le site, il faut voir si on peut normaliser (côté ORGA) ces informations : adresses, heures d'ouverture, contacts... ou scrapper ?

Eventuellement un 1er scrap par nos soins puis transmission du fichier à la DIRECCTE pour maintenance/corrections ?

Ce [lien](http://bourgogne-franche-comte.direccte.gouv.fr/sites/bourgogne-franche-comte.direccte.gouv.fr/IMG/xlsx/copie_de_coordonnees_des_uc_bfc-1.xlsx) n'est plus valide par exemple :

<img width="645" alt="Capture d’écran 2019-04-01 à 11 03 30" src="https://user-images.githubusercontent.com/124937/55316068-e748ff00-546d-11e9-847e-841989edfec7.png">

Les données sont actuellement ici : https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-frontend/src/data/services-de-renseignement.json

**Comment by revolunet** [comment]
standby sur le sujet annuaire

pour la liste des SDR, on a ajouté un check sur les urls fournies
