### ISSUE TITLE
Les urls canoniques fiche service publique ne devraient pas être dans le sitemap ?

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#4845]
Pour toutes nos urls crawlées depuis `service-public.fr` nous déclarons la page origin comme url canonical

Par exemple :
https://code.travail.gouv.fr/fiche-service-public/aide-a-la-reconnaissance-de-la-lourdeur-du-handicap-rlh-quelles-sont-les-regles

a pour canonical :
https://www.service-public.fr/particuliers/vosdroits/F1658

Ceci a pour effet de faire apparaitre ces urls dans la GSC comme "non indéxées" > "Autre page avec balise canonique correcte"
GSC précise : "Ces pages ne sont pas indexées ni diffusées sur Google"

Question : devons-nous les garder dans le sitemap ? Elles utilisent du temps de crawl pour rien non ?
@Jonathan2051 

Idem pour les fiche ministère travail :
https://code.travail.gouv.fr/fiche-ministere-travail/le-conge-sabbatique

Question annexe :
Ces pages la aussi devraient avoir une canonique sur la page legifrance :
https://code.travail.gouv.fr/code-du-travail/l6222-22

**Comment by Jonathan2051** [comment]
C'est une problématique qui avait déjà été mise sur la table : désindexer ou non les pages qui présentent une URL non self canonical. A l’époque, le trafic n’était pas celui d’aujourd’hui et cela revenait à renoncer à un certain % de trafic non négligeable (certaines pages SP et MT génèrent du trafic via Google).

Je suis d’accord, les pages SP et MT pourraient être exclues des résultats de Google pour plus de cohérence.

Toutefois, les **supprimer du sitemap ne suffirait pas**. Il faudra :

- les renseigner dans le fichier robots.txt
- supprimer les pages indésirables de l'index de Google
- revoir la distribution des liens internes vers ces pages désindexées (liens nofollow).

Est-ce que cela aiderait Google à mieux crawler et indexer le CDTN ? Oui.

Toutefois, la notion de sauvegarde du « budget crawl » ne dépend que du nombre de pages indexées d'un site. Parmi les autres critères : 

- la profondeur des pages
- la pertinence du maillage interne

C'est le travail qui est en cours.

En résumé, c’est une somme d’actions qui affectera le budget crawl, pas la seule suppression des URL du sitemap.

Je vous propose un point sur le sujet 😊

**Comment by carolineBda** [comment]
Après discussion avec l'équipe nous allons laisser comme ça car certaines pages sont indexées dans google et amènent du traffic
