### ISSUE TITLE
[Simulation sans résultat] Bug : non prise en compte des absences inclues dans l'ancienneté par les CC

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4850]
il y a un cas qu'on a pas du tout pris en compte, ex :

- la CC nécessite minimum 2 ans d'ancienneté pour avoir le droit à l'indemnité
- le code du travail nécessite minimum 8 mois d'ancienneté pour avoir le droit à l'indemnité
Je mets pile 8 mois entre la date d'entrée et la date de notification + je mets une absence de 2 mois pour maladie non pro

=> je ne suis pas envoyé à l'étape résultat dircetement pour me dire qu'il n'y a pas d'indemnité dans cette situation, je peux donc poursuivre ma simulation normalement sauf qu'à la fin j'obtiens logiquement : 

![image](https://user-images.githubusercontent.com/84397271/210573549-02ef97eb-db83-4cd5-a596-197890c4540a.png)

![image](https://user-images.githubusercontent.com/84397271/210573601-55cf275c-7534-4cf5-8ecd-478b75754f10.png)

**Comment by m-maillot** [comment]
A tester car je crois que c'est corrigé

**Comment by m-maillot** [comment]
C'est corrigé. Je cloture.
