### ISSUE TITLE
Supprimer le composant A11yLink

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#4851]
Ce composant ajoute un attribut `aria-label` à nos liens qui reprend le texte du lien et ajoute "(nouvelle fenêtre)".
Ceci n'est pas une recommandation, de plus le fait de répéter le le même texte alourdi la lecture pour les utilisateurs qui utilisent un screen reader : https://www.24joursdeweb.fr/2022/laccessibilite-cest-comme-la-patisserie-il-faut-savoir-doser/

**Comment by maxgfr** [comment]
On peut la faire après le merge de la PR sur next 13, car je modifie plusieurs link dessus....

**Comment by carolineBda** [comment]
oui
