### ISSUE TITLE
[Simulation sans résultat] gérer le cas inaptitude + CC3239 avec moins de 8 mois d'ancieenneté

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4856]
Dans le cas suivant je ne devrais pas obtenir 0€ mais avoir le message qui dit qu'il n'y a pas d'indemnité quand l'ancienneté de l'ass mat est inférieure à 9 mois OU que l'ancienneté min est de 8 mois si c'est pour le salarié du particulier employeur

En fait, c'est le fait d'avoir  mis "oui" à inaptitude qui fait que j'ai pu pu aller au résultat car en principe dans ce cas il n'y a pas de minimum d'ancienneté requis et on calcul le montant légal
SAUF QUE pour la CC 3239 il n'y a pas de comparaison au légal à faire
DONC si je n'ai pas l'ancienneté minimum requise par la CC3239 (9 mois pour les asst mat et 8 mois pour les salariés du particulier employeur) => je ne dois pas avoir d'indemnité ni de détail du calcul mais "il n'y a pas d'indemnité de licenciement dans cette situation" avec l'explication qui correspond en dessous

![image](https://user-images.githubusercontent.com/84397271/210585739-9d36fd42-7a9f-45b1-9078-d3d030711960.png)

**Comment by m-maillot** [comment]
Duplica de https://github.com/SocialGouv/code-du-travail-numerique/issues/4859
