### ISSUE TITLE
[Bug] réparer la fonctionnalité de pré-ouverture des accordéon avec un anchor tag

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#4865]
Si un utilisateur entre l'url 
https://code-du-travail-numerique-preprod.ovh.fabrique.social.gouv.fr/fiche-ministere-travail/la-demission#Comment-presenter-une-demission
alors la page devrait Ouvrir l'accordéon "Comment présenter une démission ?" et scroller pour que cette accordéon soit en faut de la page

Note : cette fonctionnalité a existé, rechercher `preExpanded` dans le code base

**Comment by m-maillot** [comment]
Il faudrait reprendre la logique du découpage des fiches MT et voir l'intérêt de le faire. Je pense que ça doit être lié au contenu des fiches MT qui est parfois assez gros. Du coup ça aide notre recherche. Mais par contre, niveau SEO, ça ne doit pas être terrible ?

**Comment by carolineBda** [comment]
Je ne penses pas que ce soit un pb niveau SEO, on fait plusieurs lien vers une même page avec possiblement un texte différent c'est même bien en fait

**Comment by carolineBda** [comment]
Une fois réparée, nous utiliserons cette fonctionnalité pour ajouter un lien sur la page résultat du simulateur de rupture co vers l'accordéon "L'indemnité de rupture conventionnelle est-elle imposable ?" de la page : https://code.travail.gouv.fr/fiche-service-public/comment-calculer-lindemnite-specifique-de-rupture-conventionnelle
