### ISSUE TITLE
[indemnité de licenciement] changer le nom du motif d'absence CC1090

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4867]
Pour la CC 1090 il faudrait changer le nom du motif d'absence "congé parental d'éducation total" par "congé parental d'éducation à temps plein"

/!\ il faut toujours qu'une notif apparaisse au niveau du résultat si l'utilisateur sélectionne la CC 1090 + sélectionne une absence pour "congé parental d'éducation à temps plein"

**Comment by carolineBda** [comment]
J'ai fait le rename. concernant la notification il faut que le résultat conventionnel soit plus avantageux pour que la notification s'affiche. Est-ce possible avec cette CC ?

**Comment by romain-b13** [comment]
> J'ai fait le rename. concernant la notification il faut que le résultat conventionnel soit plus avantageux pour que la notification s'affiche. Est-ce possible avec cette CC ?

Oui c'est ça il faut que le résultat conventionnel soit plus avantageux pour que la notification s'affiche et oui c'ets possible par exemple si tu mets plusieurs absbences (qui sont inclues dans l'ancienneté pour cette CC mais qui sont exclues pour le légal)

**Comment by carolineBda** [comment]
Ah oui donc c'est bon elle s'affiche bien :

![Image](https://user-images.githubusercontent.com/4971715/212088496-bc73547e-5666-4de6-b3a1-32eabfc96c6d.png)
