### ISSUE TITLE
Bug dans la navigation par thème dans le thème "Rupture de contrat"

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#492]
Lorsque l'on navigue par thème à partir de la page d'accueil dans le thème "Rupture de contrat", l'accès aux sous-thèmes ne fonctionne pas, on arrive sur une page blanche puis sur une erreur 500 lorsqu'on recharge la page.
![image](https://user-images.githubusercontent.com/5337489/52066202-60b09800-2578-11e9-8673-036a9f179923.png)
![image](https://user-images.githubusercontent.com/5337489/52066380-b5541300-2578-11e9-8f5f-507525383562.png)

**Comment by lionelB** [comment]
@ClementChapalain le problème à été fixé (https://github.com/SocialGouv/code-du-travail-numerique/pull/376), il faut qu'on déploie une version plus récente sur la prod. Bien vu!

- https://codedutravail-dev.num.social.gouv.fr/themes/rupture-de-contrat
- https://codedutravail-dev.num.social.gouv.fr/themes/rupture-de-contrat/la-demission

@revolunet est ce qu'on peut redéployé une version de prod

**Comment by ClementChapalain** [comment]
la correction de bug la plus rapide du monde :)

**Comment by ClementChapalain** [comment]
j'ai l'impression que ce truc date de mi-décembre c'est ça (cf. la date de la PR) ? il y a un truc qui bloque la mise en prod de la version de dev ? si vous avez besoin de recette hésitez pas :)

**Comment by lionelB** [comment]
je relance julien pour le déploiement sur le serveur "prod"

**Comment by ClementChapalain** [comment]
corrigé en prod 🙌
