### ISSUE TITLE
Bug affichage mois sur CC 44

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#4928]
sur la CC 44 parfois le mois est vide et parfois il est bien renseigné c'est bizarre

![Image](https://user-images.githubusercontent.com/992514/216069141-38b1ea8c-7c54-4f2a-aff4-065e0135394e.png)

**Comment by romain-b13** [comment]
Si le mois est vide on remplit avec le date au format numérique

**Comment by carolineBda** [comment]
On est jamais arrivé à le reproduire, on close ? @romain-b13 @m-maillot

**Comment by m-maillot** [comment]
En effet, je ne reproduis plus. Je cloture.
