### ISSUE TITLE
Mise à jour des fiches service-public.fr

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#493]
Notamment le SMIC n'est plus à jour

@jrduscher doit redonner une liste à jour des thèmes liés au droit du travail pour faire une mise à jour globale avec toutes les fiches qui nous interessent

**Comment by ClementChapalain** [comment]
Les fiches SP ne sont plus à jour ou notre scrap n'est plus à jour ?

**Comment by lionelB** [comment]
les données (un jeux de fichiers xml) provienent de data.gouv, le workflow est manuel 
- récupération du dataset
- export / génération des données au format json
- import dans ES

**Comment by lionelB** [comment]
donc il faudrait mettre à jour le jeux de données

**Comment by ClementChapalain** [comment]
ok merci pour les explications !

**Comment by jrduscher** [comment]
done par mail @lionelB

**Comment by lionelB** [comment]
## dossiers à inclure 

- Accueil particuliers >Social - Santé >Complémentaire santé et couverture maladie universelle complémentaire
https://www.service-public.fr/particuliers/vosdroits/N20286

- Accueil particuliers >Social - Santé >Prime d'activité
https://www.service-public.fr/particuliers/vosdroits/N31477

- Accueil particuliers >Étranger >Travail d'un étranger en France
https://www.service-public.fr/particuliers/vosdroits/N107

- Accueil professionnels >Création - Modification - Cessation >Modification d'une entreprise
https://www.service-public.fr/professionnels-entreprises/vosdroits/N31143

- Accueil professionnels >Création - Modification - Cessation >Cessation, transmission et reprise d'entreprise
https://www.service-public.fr/professionnels-entreprises/vosdroits/N16594

- Accueil professionnels >Ressources humaines
https://www.service-public.fr/professionnels-entreprises/vosdroits/N24267

- Accueil professionnels >Ressources humaines >Formalités d'embauche
https://www.service-public.fr/professionnels-entreprises/vosdroits/N31775

- Accueil professionnels >Ressources humaines >Formalités d'embauche
https://www.service-public.fr/professionnels-entreprises/vosdroits/N22781

- Accueil professionnels >Gestion - Finances >Prévention des difficultés
https://www.service-public.fr/professionnels-entreprises/vosdroits/N31391

- Accueil professionnels >Gestion - Finances >Traitement des difficultés
https://www.service-public.fr/professionnels-entreprises/vosdroits/N31392

## fiches à inclure 

- Accueil particuliers >Papiers - Citoyenneté >Protection de l'image >Vidéosurveillance de la voie publique et des lieux ouverts au public
https://www.service-public.fr/particuliers/vosdroits/F2517

- Accueil particuliers >Justice >Discrimination >Discrimination au travail
https://www.service-public.fr/particuliers/vosdroits/F1642

- Accueil particuliers >Justice >Harcèlement >Harcèlement moral au travail
https://www.service-public.fr/particuliers/vosdroits/F2354

- Accueil particuliers >Justice >Harcèlement >Harcèlement sexuel
https://www.service-public.fr/particuliers/vosdroits/F1043

- Accueil particuliers >Justice >Condamnations et peines >Quel est le délai de prescription d'une peine pénale ?
https://www.service-public.fr/particuliers/vosdroits/F34705

- Accueil particuliers >Justice >Affaire pénale >Justice pénale : quels délais de prescription ?
https://www.service-public.fr/particuliers/vosdroits/F31982

- Accueil professionnels >Création - Modification - Cessation >Formalités de la création d'entreprise >Comment se procurer un extrait K ou Kbis ?
https://www.service-public.fr/professionnels-entreprises/vosdroits/F21000

- Accueil professionnels >Création - Modification - Cessation >Formalités de la création d'entreprise >Création d'un organisme de services à la personne (agrément, autorisation de déclaration)
https://www.service-public.fr/professionnels-entreprises/vosdroits/F23633

- Accueil professionnels >Création - Modification - Cessation >Formalités de la création d'entreprise >Déclaration d'activité des formateurs ou organismes de formation
https://www.service-public.fr/professionnels-entreprises/vosdroits/F19087

- Accueil professionnels >Ressources humaines >Cotisations et contributions sociales de l'employeur >Déclaration sociale nominative (DSN)
https://www.service-public.fr/professionnels-entreprises/vosdroits/F34059

- Accueil professionnels >Ressources humaines >Droits syndicaux >Quelles sont les obligations d'affichage dans une entreprise ?
https://www.service-public.fr/professionnels-entreprises/vosdroits/F23106

- Accueil professionnels >Gestion - Finances >Règles comptables >Quels sont les délais de conservation des documents pour les entreprises ?
https://www.service-public.fr/professionnels-entreprises/vosdroits/F10029

- Accueil professionnels >Gestion - Finances >Règles comptables >À quoi correspond le code APE ?
https://www.service-public.fr/professionnels-entreprises/vosdroits/F33050

- Accueil professionnels >Gestion - Finances >Traitement des difficultés >Fermeture d'un établissement : obligation de rechercher un repreneur
https://www.service-public.fr/professionnels-entreprises/vosdroits/F32329

- Accueil associations >Fonctionnement d'une association >Bénévoles, volontaires et salariés d'une association >Un employeur associatif doit-il appliquer une convention collective ?
https://www.service-public.fr/associations/vosdroits/F2607

- Accueil associations >Fonctionnement d'une association >Bénévoles, volontaires et salariés d'une association >Adhésion d'une association à un groupement d'employeurs
https://www.service-public.fr/associations/vosdroits/F153

## dossiers à exclure 

- Accueil particuliers >Travail >Recrutement dans la fonction publique
https://www.service-public.fr/particuliers/vosdroits/N500

- Accueil particuliers >Travail >Rémunération dans la fonction publique
https://www.service-public.fr/particuliers/vosdroits/N511

- Accueil particuliers >Travail >Carrière dans la fonction publique
https://www.service-public.fr/particuliers/vosdroits/N505

- Accueil particuliers >Travail >Mobilité dans la fonction publique
https://www.service-public.fr/particuliers/vosdroits/N31057

- Accueil particuliers >Travail >Congés dans la fonction publique
https://www.service-public.fr/particuliers/vosdroits/N19978

- Accueil particuliers >Travail >Formation professionnelle dans la fonction publique
https://www.service-public.fr/particuliers/vosdroits/N186

- Accueil particuliers >Travail >Conditions de travail dans la fonction publique
https://www.service-public.fr/particuliers/vosdroits/N431

- Accueil particuliers >Travail >Maladie ou accident du travail dans la fonction publique
https://www.service-public.fr/particuliers/vosdroits/N512

- Accueil particuliers >Travail >Représentants du personnel dans la fonction publique
https://www.service-public.fr/particuliers/vosdroits/N503

- Accueil particuliers >Travail >Conflits du travail dans la fonction publique
https://www.service-public.fr/particuliers/vosdroits/N102

- Accueil particuliers >Travail >Temps de travail dans la fonction publique
https://www.service-public.fr/particuliers/vosdroits/N20276

- Accueil particuliers >Travail >Quitter la fonction publique
https://www.service-public.fr/particuliers/vosdroits/N515

- Accueil particuliers >Travail >Retraite d'un agent de la fonction publique (titulaire et non titulaire)
https://www.service-public.fr/particuliers/vosdroits/N379

## Theme à inclure 
- Accueil particuliers >Travail
https://www.service-public.fr/particuliers/vosdroits/N19806
