### ISSUE TITLE
Header HTTP

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4938]
Nous demandons à chaque équipe de bien vouloir :

- vérifier les headers HTTP de son frontend sur [Mozilla HTTP Observatory](https://observatory.mozilla.org/) ou [DashLord](https://dashlord-full.fabrique.social.gouv.fr/)
- faire le point sur les éventuels iframes/sites/urls externes utilisés dans vos frontends pour définir une [content-security-policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) adaptée
- ajouter les headers manquants sur son ingress ou son application, [petit tuto ici](https://socialgouv.github.io/support/docs/standards/securite#mettre-%C3%A0-jour-les-headers-http-de-mes-applications).
Si vous n'avez pas de scripts, fonts, appels externes, alors vous pouvez appliquer une CSP standard;

**Comment by carolineBda** [comment]
faudra qu'on test sur le site de @m-maillot j'ai un doute sur les widgets dans les iframe : on load plein de fichiers est-ce qu'ils vont être bloqués ?
