### ISSUE TITLE
Annuaire: integrer la compétence territoriale des organismes

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#494]
voir PDF sur data.gouv.fr https://www.data.gouv.fr/fr/datasets/service-public-fr-annuaire-de-l-administration-base-de-donnees-locales/#_

Le pdf renseigne les compétences géographiques des organismes.
Ajouter cette donnée pour chaque type d’organisme indexés à l'annuaire
Tenir compte de la compétence géographique dans la requete user:
ne renseigner que le ou les organismes du département quand le champ de compétence géographique  de ce type d'organisme est le département. ( etc.)
ex: mon adresse est dans le var, la compétence géorgaphique de la chambre d’agriculture est départementale, je n'affiche que le structures correspondant à cette entité dans le département,et pas cell des autres départements voisins.

**Comment by ClementChapalain** [comment]
Besoin de prioriser entre les différents organismes et de revoir le design de l'annuaire avant. Vérifier la mise à jour de ce fichier également, pour ne pas avoir à le faire régulièrement (API ?).

**Comment by lionelB** [comment]
je ne pense pas qu'une api qui décrivent les compétences géographique existent  car elles n'évolue pas dans le temps
