### ISSUE TITLE
Améliorer intro et message automatique de 10 modèles

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4945]
cf commentaire ci-dessous

**Comment by romain-b13** [comment]
### 1) Dans le H1 des modèles : remplacer la marque automatique "Modèle -" par "Modèle de lettre -" sauf pour les modèles listés ci-dessous : 

- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/modeles-de-courriers/document-dinformation-sur-le-conge-de-reclassement
- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/modeles-de-courriers/certificat-de-travail
- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/modeles-de-courriers/rupture-dun-commun-accord-conge-de-mobilite
- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/modeles-de-courriers/rupture-dun-commun-accord-rupture-conventionnelle-collective
- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/modeles-de-courriers/rupture-dun-contrat-de-travail-a-duree-determinee-dun-commun-accord
- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/modeles-de-courriers/releve-dheures-supplementaires
- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/modeles-de-courriers/rupture-dun-contrat-dapprentissage-dun-commun-accord
- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/modeles-de-courriers/promesse-dembauche
- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/modeles-de-courriers/affichage-obligatoire-relatif-au-harcelement-sexuel
### 
### 2) Dans le message générique affiché sous l'aperçu de chaque modèle, remplacé "document" par "lettre" sauf pour les url ci-dessous 

![image](https://user-images.githubusercontent.com/84397271/219695063-0e676964-5961-442c-ace9-20d6f0eb9461.png)

- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/modeles-de-courriers/document-dinformation-sur-le-conge-de-reclassement
- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/modeles-de-courriers/certificat-de-travail
- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/modeles-de-courriers/rupture-dun-commun-accord-conge-de-mobilite
- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/modeles-de-courriers/rupture-dun-commun-accord-rupture-conventionnelle-collective
- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/modeles-de-courriers/rupture-dun-contrat-de-travail-a-duree-determinee-dun-commun-accord
- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/modeles-de-courriers/releve-dheures-supplementaires
- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/modeles-de-courriers/rupture-dun-contrat-dapprentissage-dun-commun-accord
- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/modeles-de-courriers/promesse-dembauche
- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/modeles-de-courriers/affichage-obligatoire-relatif-au-harcelement-sexuel

### 3) Modification de l'intro de certains modèles

- https://code.travail.gouv.fr/modeles-de-courriers/signalement-de-faits-pouvant-relever-du-harcelement-moral-ou-sexuel

Ce modèle permet au salarié victime ou témoin de faits de harcèlement moral ou sexuel au travail d’avertir l’employeur.

- https://code.travail.gouv.fr/modeles-de-courriers/demande-de-paiement-de-salaire

Tout salarié doit percevoir son salaire au moins une fois par mois. Ce modèle de lettre de demande de régularisation du salaire permet au salarié de demander le paiement de son salaire en cas de non-paiement. Le salarié doit garder une copie de ce courrier.

- https://code.travail.gouv.fr/modeles-de-courriers/lettre-de-licenciement-pour-motif-disciplinaire

Ce modèle de lettre peut être utilisé pour notifier le licenciement d'un salarié ayant eu un comportement fautif (faute simple, grave ou lourde, selon la qualification retenue par l’employeur). Elle doit être envoyée au salarié par LRAR, après un délai minimum de 2 jours ouvrables et avant un délai d’un mois suivant la date prévue de l’entretien préalable au licenciement. En cas de remise en mains propres, la lettre doit être établie en double exemplaire et celui de l’employeur doit être accompagné de la mention “Reçu le…” avec la signature du salarié. La lettre de licenciement comporte l’énoncé précis des motifs invoqués par l’employeur. Enfin, il convient de vérifier si la convention collective applicable prévoit des mesures particulières en cas de licenciement.

- https://code.travail.gouv.fr/modeles-de-courriers/rupture-du-contrat-en-periode-dessai-par-le-salarie

Pendant la période d’essai, le contrat de travail peut être rompu librement par le salarié. Le salarié devra informer l’employeur et respecter un délai de prévenance avant de quitter ses fonctions. Cette lettre de rupture de la période d'essai permet au salarié d’avertir l’employeur de son intention de mettre fin à la période d’essai.

- https://code.travail.gouv.fr/modeles-de-courriers/rupture-dun-contrat-de-travail-a-duree-determinee-dun-commun-accord

La rupture anticipée du contrat de travail à durée déterminée par le salarié ou l’employeur, en dehors de la période d’essai, est limitée à un certain nombre de cas (ex : embauche en CDI). Une rupture d’un commun accord entre le salarié et l’employeur est cependant possible. Il est à noter que la rupture conventionnelle individuelle est une modalité de rupture spécifique du CDI, qui ne s’applique pas aux CDD.

**Comment by maxgfr** [comment]
On a décorrellé les descriptions des méta descriptions. Exemple : 

```json
    "description": "Ce modèle permet au salarié victime ou témoin de faits de harcèlement moral ou sexuel au travail d’avertir l’employeur.",
    "meta_description": "Vous êtes victime ou témoin de faits de harcèlement moral ou sexuel au travail ? Téléchargez et personnalisez notre modèle de lettre pour informer l'employeur.",
```

ou 

```json
    "description": "Ce modèle de lettre peut être utilisé pour notifier le licenciement d'un salarié ayant eu un comportement fautif (faute simple, grave ou lourde, selon la qualification retenue par l’employeur). Elle doit être envoyée au salarié par LRAR, après un délai minimum de 2 jours ouvrables et avant un délai d’un mois suivant la date prévue de l’entretien préalable au licenciement. En cas de remise en mains propres, la lettre doit être établie en double exemplaire et celui de l’employeur doit être accompagné de la mention “Reçu le…” avec la signature du salarié. La lettre de licenciement comporte l’énoncé précis des motifs invoqués par l’employeur. Enfin, il convient de vérifier si la convention collective applicable prévoit des mesures particulières en cas de licenciement.",
    "meta_description": "Téléchargez et personnalisez notre modèle de lettre de licenciement pour motif disciplinaire.",
```

Je n'ai pas touché la méta description, car je la trouvais bien plus pertinente
