### ISSUE TITLE
Restructuration de la BDD dans les modèles

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4949]

**Comment by Viczei** [comment]
- [ ] Créer les tables
- [ ] Faire les migrations des données
- [ ] Mettre à jour la query graphql pour l'export
- [ ] Mettre à jour la query pour la liste dans l'admin
- [ ] Mettre à jour le README de cdtn-to-docx

source: https://drive.google.com/file/d/111BAh8QiQYl9Tfc7SDfKlMQJBVkqNgBr/view?usp=sharing
