### ISSUE TITLE
Ajouter des liens directs vers les outils et modèles

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#495]
## Retour utilisateur :
> ETQ user, je veux pouvoir voir tous les contenus disponibles par sources.
> En réalité je veux pouvoir consulter plus particulièrement les modèles et courriers, peu nombreux quand je ne mets rien dans le champ ( aucun sens pour le code ou les fiches: trop nombreuses)
> Je veux pouvoir consulter tous les modèles , et outils voire annuaire présents sur le site

## Proposition d'intégration

On peut tenter un truc comme ça en première approximation pour mettre en avant nos outils :

![image](https://user-images.githubusercontent.com/5337489/52729840-4637df00-2fba-11e9-8258-6e31296147ce.png)

## Détails

outils à intégrer dans cette liste :

**calculateur d'indemnités de licenciements**
- icône du bloc : on peut reprendre celle de "rémunération" dans la liste des thèmes, mais s'il existe une librairie plus fournie, il y a peut-être une icône plus adaptée
- titre du bloc : "Calculateur d'indemnités de licenciements"
- description du bloc : "Calculez simplement le montant d'une indemnité de licenciement en fonction de votre situation"
- lien du bloc : https://codedutravail.num.social.gouv.fr/outils/indemnite-licenciement

**modèles de courriers**
- icône du bloc : on peut reprendre celle de "rupture de contrat" dans la liste des thèmes, mais s'il existe une librairie plus fournie, il y a peut-être une icône plus adaptée
- titre du bloc : "Modèles de courriers"
- description du bloc : "Utilisez des modèles pré-remplis pour vos courriers liés au droit du travail"
- lien du bloc : créer une nouvelle page listant [tous les modèles de courrier](https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-data/dataset/courrier-type/courriers.json) avec le design suivant :
![image](https://user-images.githubusercontent.com/5337489/53325302-4f427d80-38e3-11e9-941f-8dd1f0ea3dd6.png)

**simulateur d'embauche**
- icône du bloc : on peut reprendre celle de "rémunération" dans la liste des thèmes, mais s'il existe une librairie plus fournie, il y a peut-être une icône plus adaptée
- titre du bloc : "Simulateur d'embauche"
- description du bloc : "Estimez le salaire lors d'une embauche : total employeur, brut, net"
- lien du bloc : nouvelle page chez nous qui héberge une version embed du simulateur d'embauche https://embauche.beta.gouv.fr/

**convention collective**
- icône du bloc : on peut reprendre celle de "maladie et inaptitude" dans la liste des thèmes, mais s'il existe une librairie plus fournie, il y a peut-être une icône plus adaptée
- titre du bloc : "Votre convention collective"
- description du bloc : "Trouvez simplement la convention collective dont vous dépendez"
- lien du bloc : modal qui est aujourd'hui lancée par le lien dans le footer sur la convention collective, on peut en profiter pour supprimer ce lien d'ailleurs

**Comment by ClementChapalain** [comment]
Je me disais qu'on pouvait tenter un truc comme ça en première approximation pour mettre en avant nos outils. On peut aussi imaginer avoir un menu déroulant dans un header. À discuter !

![image](https://user-images.githubusercontent.com/5337489/52729840-4637df00-2fba-11e9-8258-6e31296147ce.png)

**Comment by lionelB** [comment]
@ClementChapalain ca me va!  je pense qu'on peut partir la dessus pour une première version et itérer ensuite

**Comment by ClementChapalain** [comment]
outils à intégrer dans cette liste :

**calculateur d'indemnités de licenciements**
- icône du bloc : on peut reprendre celle de "rémunération" dans la liste des thèmes, mais s'il existe une librairie plus fournie, il y a peut-être une icône plus adaptée
- titre du bloc : "Calculateur d'indemnités de licenciements"
- description du bloc : "Calculez simplement le montant d'une indemnité de licenciement en fonction de votre situation"
- lien du bloc : https://codedutravail.num.social.gouv.fr/outils/indemnite-licenciement

**modèles de courriers**
- icône du bloc : on peut reprendre celle de "rupture de contrat" dans la liste des thèmes, mais s'il existe une librairie plus fournie, il y a peut-être une icône plus adaptée
- titre du bloc : "Modèles de courriers"
- description du bloc : "Utilisez des modèles pré-remplis pour vos courriers liés au droit du travail"
- lien du bloc : créer une nouvelle page listant [tous les modèles de courrier](https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-data/dataset/courrier-type/courriers.json) avec le design suivant :
![image](https://user-images.githubusercontent.com/5337489/53325302-4f427d80-38e3-11e9-941f-8dd1f0ea3dd6.png)

**simulateur d'embauche**
- icône du bloc : on peut reprendre celle de "rémunération" dans la liste des thèmes, mais s'il existe une librairie plus fournie, il y a peut-être une icône plus adaptée
- titre du bloc : "Simulateur d'embauche"
- description du bloc : "Estimez le salaire lors d'une embauche : total employeur, brut, net"
- lien du bloc : nouvelle page chez nous qui héberge une version embed du simulateur d'embauche https://embauche.beta.gouv.fr/

**convention collective**
- icône du bloc : on peut reprendre celle de "maladie et inaptitude" dans la liste des thèmes, mais s'il existe une librairie plus fournie, il y a peut-être une icône plus adaptée
- titre du bloc : "Votre convention collective"
- description du bloc : "Trouvez simplement la convention collective dont vous dépendez"
- lien du bloc : modal qui est aujourd'hui lancée par le lien dans le footer sur la convention collective, on peut en profiter pour supprimer ce lien d'ailleurs

**Comment by revolunet** [comment]
Proposer également un lien vers simulateur d'embauche ?  https://embauche.beta.gouv.fr/

**Comment by revolunet** [comment]
exemples de requêtes pour simulateur d'embauche : 

```
comment calculer mon salaire
calculer mon salaire
calcul salaire
montant de mon salaire
montant du salaire
montant salaire
montant salaire net
montant salaire brut
calcul du salaire net
net en brut
brut en net
calcul net en brut
calcul brut en net
montant net en brut
montant brut en net
```

**Comment by ClementChapalain** [comment]
> Proposer également un lien vers simulateur d'embauche ? https://embauche.beta.gouv.fr/

carrément ! ce serait même top si on pouvait l'héberger dans une page chez nous

**Comment by lionelB** [comment]
c'est tout à fait possible, il existe une version embed. 
\ping @laem

**Comment by ClementChapalain** [comment]
@lionelB il y a deux petits soucis :)
- il manque une majuscule à `Calculateur` dans le premier outil
- l'icône du dernier outil n'est pas de la même taille que les autres
![image](https://user-images.githubusercontent.com/5337489/54812237-f15b4880-4c8a-11e9-9dd3-f37981530b21.png)

**Comment by lionelB** [comment]
je regarde ça aussi
