### ISSUE TITLE
Remontées users dans le piwik

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#496]
- Step1: pusher en prod la fonctionnalité configurée dans piwik sur la version dév!
- Step 2 : possibilités pour thumbs up /thumbs down de pouvoir connaitre dans le piwik: dans les différents scénario ( si up ou down donc): la requête user, et le lien vers le contenu de la page réponse qui a suscité la réaction.

(Des modifications peuvent etre apporté à la fonctionnalité côté user ( une issue à ce sujet), si prête adpater les remontée piwik concernés  en conséquence. si pas prête, l'issue peut être close"

**Comment by jrduscher** [comment]
close:  voir #458. done in  PR #501

**Comment by lionelB** [comment]
closed by #501
