### ISSUE TITLE
Bug "0 convention collective trouvée"

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#4970]
à voir si on ne fait pas une url différente pour chaque parcours

![image](https://user-images.githubusercontent.com/84397271/220861237-8b3bdba1-efb3-48d5-b020-d5594b63c570.png)

**Comment by m-maillot** [comment]
Une URL a été crée pour chaque parcours. Ce bug n'existe plus, on redirige vers la recherche par entreprise : https://code.travail.gouv.fr/outils/convention-collective/selection
