### ISSUE TITLE
[Bug ES] rechercher un article du code du travail par son code/ format de saisie/pertinence

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#498]
test L. 1242-8.
- L1242-8 : pas de réponse
- L.1242-8: L'article correspondant ne matche pas.
- L 1242-8 : pas de réponse

Résultat attendu https://codedutravail-dev.num.social.gouv.fr/code-du-travail/article-l1242-8?q=La%20dur%C3%A9e%20totale%20du%20contrat%20%C3%A0%20dur%C3%A9e%20d%C3%A9termin%C3%A9e&search=0

> étendre la recherche aux titres des contenus

**Comment by lionelB** [comment]
effectivement, pour l'instant on ne cherche que dans le texte et pas ~plus~ dans le titre, ce qui fait qu'on ne remonte aucun article
Fix: remplacer le `match {text { query }}` par un multimatch text/title

**Comment by revolunet** [comment]
nb: ca marchait avait le retrait du fuzzy

**Comment by lionelB** [comment]
oui ce que je voulais dire c'est que çà correspondait au modifs qu'on a fait sur ES. Il faudrait rajouter un cas dans les TU

**Comment by ClementChapalain** [comment]
J'ai vu que tu l'avais montré à la démo @lionelB est-ce qu'on peut clore cette tâche ?

**Comment by lionelB** [comment]
yep closed by #566
