### ISSUE TITLE
Affichage des notes des articles du CDT

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#499]
https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000035643967&cidTexte=LEGITEXT000006072050

https://code.travail.gouv.fr/code-du-travail/l1242-8?q=L1242-8

La partie "Note" n'est pas le texte en lui même,ce contenu additionnel aussi important soit-il por l'usager doit être différencié du corps de l'article. ( mise en italique, cadre à part et en dessous dans le cadre de article )

la partie Note qui figure dans l’article est elle balisée de façon particulière dans Legi?

**Comment by revolunet** [comment]
Dans LEGI c'est NOTA

Issue a traiter après l'étude API DILA
