### ISSUE TITLE
base ACCO

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#5]
verif contenu base ACCO : https://www.data.gouv.fr/fr/datasets/acco-accords-dentreprise/

**Comment by ClementChapalain** [comment]
relatif aux accords d'entreprise, si j'ai bien compris pas dans le scope 1.1.2020 a priori donc je me permets de fermer et de commencer une page dans le wiki :
https://github.com/SocialGouv/code-du-travail-numerique/wiki/%5BProduit%5D%C2%A0%5BAE%5D-Liste-des-ressources
