### ISSUE TITLE
fiche de travail: CCN industrie chimique

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#50]
1) liste des entreprises adhérentes à l'UIC: http://www.uic.fr/Industrie-chimique/Entreprises-adherentes
2)

**Comment by jrduscher** [comment]
si un texte de CCN n'est pas en vigueur dans la CCN chimie, il sera malgré tout opposable aux entreprises figurant dans la liste.

**Comment by ClementChapalain** [comment]
est-ce que tu pourrais détailler stp @jrduscher ? quel est le problème / besoin auquel on doit répondre ici ?
