### ISSUE TITLE
Widgétiser indemnité de licenciement

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5013]
**Titre de la tuile** : Indemnité de licenciement

**Description sur la tuile** : Estimer le montant de l’indemnité à verser au salarié en cas de licenciement

**Titre de la page** : Intégrer l’outil de calcul de l'indemnité de licenciement du Code du travail numérique

**Intro de la page** : 
Vous pouvez intégrer l’outil de calcul de l'indemnité de licenciement du Code du travail numérique sur votre site grâce à un module (widget). Ce module permettra à l’utilisateur de calculer le montant de l'indemnité à verser au salarié en cas de licenciement. Afin de personnaliser le résultat, l’utilisateur pourra, s’il le souhaite, renseigner ou rechercher (à partir du nom de l’entreprise) sa convention collective.

**Comment by m-maillot** [comment]
Widget en place
