### ISSUE TITLE
Bulletin de salaire: outil

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#502]
rappels et visuels autour le fiche de paie: mentions. à creuser.

**Comment by ClementChapalain** [comment]
pas une tâche aujourd'hui, il faut le noter autre part, je mets une page vide dans le wiki pour l'instant.

**Comment by jrduscher** [comment]
https://trello.com/c/iBUYPFx5/350-fiche-comprendre-son-bulletin-de-salaire
