### ISSUE TITLE
[indemnité de licenciement] ajouter une notif pour tout le monde

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5027]
**/!\ Attention : à mettre en prod en même temps que la PR 5017 de Caro** 

Ajouter une notif pour expliquer que les congé paternité pris avant le 11 mars doivent être exclus de l'ancienneté donc le résultat peut être moins favorable que celui donné  : 

_Depuis le 11 mars 2023 les périodes d'absence pour congé paternité ne sont plus retirées de l'ancienneté du salarié. Si le salarié a pris un congé paternité avant cette date, il peut être décompté de son ancienneté et de ce fait, donner lieu à un montant d'indemnité moins favorable que celui de notre simulateur._

**Comment by carolineBda** [comment]
On l'ajoute sur tout le temps ? sur la page résultat ?
