### ISSUE TITLE
Envoyer des messages pour tracking du widget search + erreur

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5044]
- Intégrer des messages pour que PE puisse tracker les clics sur la loupe et sur le logo du widget recherche
- Voir l'erreur cors liée au rezise dans la console => pour tous les widgets
- Voir si on ajoute de tests

/!\ ne pas faire des messages trop spécifiques

**Comment by carolineBda** [comment]
Erreur ici : https://entreprise.pole-emploi.fr/accueil/description/droit-travail
