### ISSUE TITLE
Créer events tracking clics rubriques header

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5084]
1-**Catégorie de l'événement** : Header
**Action de l'événement** : 
- Click_boite_a_outils
- Click_modeles_de_documents
- Click_vos_fiches_pratiques
- Click_votre_convention_collective
- Click_themes

2-**Catégorie de l'événement** : Home
**Action de l'événement** :
- Click_voir_tous_les_outils
- Click_voir_tous_modeles_de_documents
- Click_voir_toutes_les_fiches_pratiques
- Click_voir_toutes_les_convention_collective
- Click_voir_tous_les_themes

**Comment by carolineBda** [comment]
on mettrais pas "header" dans le nom des event du header pour faciliter la lecture ?
