### ISSUE TITLE
Suggestion de résultats au fil de la saisie: modifications à envisager

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#509]
* L'usager qui voit les suggestions, ne repart pas sur la page résultat:
  1) la requête n’apparaît pas dans piwik
  2) les propositions sont similaires
  3)  la boite reste affichée

* l'outil de suggestion affiche les mêmes résultats que la page de résultats
* l'outil de suggestion shunte la page de résultats
*l'utilisateur peut ne pas voir le résultat

>  peut on suggérer des termes, plus que des contenus? 
**need atelier équipe projet.**

**Comment by ClementChapalain** [comment]
fixé, le point sur matomo reste à fixer mais est détaillé dans #531
