### ISSUE TITLE
Modélisation. Période d'essai. 

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#51]
**CDI**
Objectif: afficher les principes, durées maximales, 
Code du Travail. art. L1221-19 à 23:https://www.legifrance.gouv.fr/affichCode.do;jsessionid=C3BB88846F68BE6145677F5EAB5D6764.tplgfr36s_3?idSectionTA=LEGISCTA000019071115&cidTexte=LEGITEXT000006072050&dateTexte=20180614

* qu'est ce qu'une période d'essai: citer le corps de l'article L1221-20
* Pour qu'il y ait période d'essai, cela doit être prévu au contrat de travail

Principe L.1221-19: Durée max **sans renouvellement**.

"Le **contrat de travail à durée indéterminée** peut comporter une période d'essai dont la **durée maximale** est :

1° Pour les **ouvriers** et les **employés, de deux mois ;

2° Pour les **agents de maîtrise** et les techniciens, de trois mois ;

3° Pour les **cadres**, de quatre mois"

* Pour que la période d'essai puisse être renouvelée: elle doit être prévue au contrat de travail + dans la CCN ( mentions+conditions), et sur accord accord exprès(jurisprudence, rien d'écrit.à.

L'article L1221-21 prévoit la durée de la période d'essai, renouvellement compris:

La période d'essai peut être **renouvelée une fois** _**si**_ un accord de branche étendu le prévoit. Cet accord fixe les **conditions et les durées de renouvellement**.

La durée de la période d'essai, renouvellement compris, ne peut pas dépasser :

1° Quatre mois pour les ouvriers et employés ;

2° Six mois pour les agents de maîtrise et techniciens ;

3° Huit mois pour les cadres. 

OBJECTIF=> **On peut donc afficher simplement: une durée maximum légale.**, les conditions et possibilités du renouvellement.

=> Etape 1: recueillir l'info: ouvrier, agent de maîtrise, cadre;
=> Etape 2: renvoyer à une condition branche au delà de la condition contrat de travail.
=>Etape 3 : enrichir la condition branche, avec les conditions de l'article L1221-22.

**Comment by jrduscher** [comment]
_**Conditions de l'article L.1221-22 du code du travail.**

Les durées des périodes d'essai fixées par les articles L. 1221-19 et L. 1221-21 ont un caractère impératif, à l'exception :

- de durées plus longues fixées par les accords de branche conclus avant la date de publication de la loi n° 2008-596 du 25 juin 2008 portant modernisation du marché du travail ;

- de durées plus courtes fixées par des accords collectifs conclus après la date de publication de la loi n° 2008-596 du 25 juin 2008 précitée ;

- de **durées plus courte**s fixées dans la lettre d'engagement ou le contrat de travail._

(/!\ toutes les colonnes ne sont pas affichées/!\)

Quelle est la durée de ma période d'essai? |   |  
-- | -- | --
Durée   impérative max sans renouvellement |   |  
Catégorie | durée légale impérative | Si contrat | si accord(>25/06/2008) | si accord de branche/CCN<25/06/2008
ouvrier | 2 | durée<2 | durée<2 | durée>2
ETAM | 3 | durée<3 | durée<3 | durée>3
CADRE | 4 | durée<4 | durée<4 | durée>4
Durée max   avec renouvellement |   |   |  
Renouvellement,   si CCN le prévoit: choisir CCN, checker si renouvellement=oui. Afficher   " Le rneouvellement n'est pas possible si votr contrat ne le prévoit pas   ou contre votre gré"
  |   | Si contrat | si accord(>25/06/2008) | si accord de branche CCN<25/06/2008
ouvrier | 4 | durée<4 | durée<4 | durée>4
ETAM | 6 | durée<6 | durée<6 | durée>6
CADRE | 8 | durée<8 | durée<8 | durée>8

**Comment by jrduscher** [comment]
Test avec la convention de branche: Chimie, industrie chimique.

Industrie Chimique. 
Article généréal 9.2 CCN: 
**Renouvellement**=non
catégorie: ouvrier
référence texte: Avenant n°1, du 11 févreier 1971
réf_art:Article 3
date_texte:1992

 //[3. Période d'essai - Les modalités et la durée de la période d'essai sont définies dans les différents avenants. **La période d'essai n'est pas renouvelable**.]

    **Avenant n° 1 du 11 février 1971 relatif aux ouvriers et collaborateurs**
        Période d'essai

Article 3
En vigueur étendu
Dernière modification: Modifié par Accord du 22 mai 1979 étendu par arrêté du 3 janvier 1992 JORF 11 janvier 1992
Créé par Avenant n° 1 1971-02-11 étendu par arrêté du 18 novembre 1971 JONC 12 janvier 1972

1. La durée de la période d'essai ne pourra excéder :

- 15 jours pour les salariés dont le coefficient hiérarchique est inférieur à 160 ;

- 1 mois pour les salariés dont le coefficient hiérarchique est égal ou supérieur à 160 et inférieur à 190 ;

- 2 mois pour les salariés dont le coefficient hiérarchique est égal ou supérieur à 190. "

2. Pendant la période d'essai d'une durée maxima de 15 jours, les parties peuvent résilier le contrat de travail avec préavis de 2 heures.

Pour les périodes d'essai de durée supérieure et lorsque la moitié de la période sera écoulée, le délai de préavis réciproque sera de 6 jours pour les périodes d'essai maxima de 1 mois et 15 jours pour les autres.

Pour rechercher un emploi les salariés pourront s'absenter pendant 12 heures si le préavis est de 6 jours, ou pendant 30 heures si le préavis est de 15 jours. Ces heures d'absence, choisies à la convenance du salarié, ne donneront pas lieu à réduction d'appointements.

Le préavis pourra être donné jusqu'au dernier jour de la période d'essai.

3. Lorsque après avoir reçu son préavis, le salarié en période d'essai a trouvé un nouvel emploi, toutes facilités lui seront accordées pour lui permettre d'occuper ce nouvel emploi. Dans ce cas, il n'aura à verser aucune indemnité pour inobservation du préavis.

4. Lorsqu'un salarié, dont le contrat aura été résilié avant le terme de sa période d'essai, aura pendant cette période effectué des travaux présentant un caractère de création originale, l'employeur ne pourra utiliser la création originale résultant de ces travaux.
Rattaché par convention collective nationale du 30 décembre 1952 


catégorie: ETAM
date_texte: 1992

  ** Avenant n° 2 du 14 mars 1955 relatifs aux agents de maîtrise et certains techniciens**
        Agents de maîtrise et certains techniciens
            Période d'essai

Article 3
En vigueur étendu
Dernière modification: Modifié par Accord du 22 mai 1979 étendu par arrêté du 3 janvier 1992 JORF 11 janvier 1992.
Modifié par Avenant 1973-12-12 (non étendu)
Créé par Avenant n° 2 1955-03-14 étendu par arrêté du 13 novembre 1956 JONC 12 décembre 1956

1. La durée de la période d'essai des agents de maîtrise et techniciens ne pourra excéder 2 mois, à l'exception de ceux dont le coefficient hiérarchique est égal ou supérieur à 275 pour lesquels la période d'essai ne pourra excéder 3 mois.

2. Lorsque la moitié de la période d'essai est écoulée, le délai de préavis réciproque sera de 15 jours avec possibilité d'absence de 30 heures payées pour recherche d'emploi à la convenance de l'intéressé, ce préavis pouvant être donné jusqu'au dernier jour de la période d'essai.

3. Lorsque, après avoir reçu son préavis, l'agent de maîtrise ou le technicien en période d'essai a trouvé un nouvel emploi, toutes facilités lui seront accordées pour lui permettre d'occuper ce nouvel emploi. Dans ce cas, il n'aura à verser aucune indemnité pour inobservation du préavis.

4. Lorsqu'un agent de maîtrise ou un technicien, qui n'aura pas été engagé à l'expiration de sa période d'essai, aura pendant cette période effectué des travaux présentant un caractère de création originale, l'employeur ne pourra utiliser la création originale résultant de ces travaux.



    **Avenant n° 3 du 16 juin 1955 relatif aux ingénieurs et cadres**
        Période d'essai

Article 3
En vigueur étendu
Créé par Avenant n° 3 1955-06-16 en vigueur le 1er juillet 1955 étendu par arrêté du 13 novembre 1956 JONC 12 décembre 1956

**1. La période d'essai ne peut durer plus de trois mois de travail effectif.**

2. Lorsqu'un cadre, qui n'aura pas été engagé à l'expiration de sa période d'essai, aura pendant cette période effectué des travaux personnels susceptibles de donner lieu à prise de brevet, dépôt de marque ou de modèle, l'employeur ne pourra utiliser ces travaux sons l'accord écrit de l'intéressé.




Textes en présence : plus ancien que le 25 juin 2008. période plus courtes. La loi a caractère impératif: renvoi loi, selon catégorie.

**Comment by jrduscher** [comment]
**Période d'essai en boulangerie**
Renouvellement= non
date=1978
Durée: 30 jours
catégorie: null/all

IDCC 843
Texte de base
**Convention collective nationale de la boulangerie-pâtisserie du 19 mars 1976.** 
Etendue par arrêté du 21 juin **1978 JONC 28 juillet 1978.**
Période d'essai

Article 17 En savoir plus sur cet article...
En vigueur étendu
Le contrat de travail n'est considéré comme définitivement conclu qu'à la fin de la période d'essai dont **la durée est de 30 jours.**

Pendant la période d'essai, chacune des parties a le droit de reprendre sa liberté sans préavis.

Si le salarié est toujours occupé dans l'entreprise après 5 jours de travail, il aura le droit dans l'hypothèse où une rupture intervient du fait de l'employeur avant qu'il ait effectué 1 mois de travail effectif à une indemnité de congés payés égale à celle perçue par un salarié engagé en qualité d'extra.

Il sera remis dès le début du travail à tout salarié engagé à l'essai une fiche d'embauche précisant le nom du salarié concerné, le début de la période d'essai et le coefficient professionnel auquel le salarié est engagé.

**Comment by jrduscher** [comment]
Période d'essai en Hôtels, Café, Restaurant
Renouvellement: oui, **sauf** salariés de niveau I, échelon 1.
Renouvellement:" un accord écrit devra être établi entre les parties."
Date 1997
Ouvrier: 1 mois
ETAM:2 mois
Cadre: 3 mois;
"cadre sup acrd de gré à gré"
"Champs d'applicaiton géographique":


IDCC 1979

    Texte de base

    Convention collective nationale des hôtels, cafés restaurants (HCR) du 30 avril 1997
    Etendue par arrêté du 3 décembre 1997 JORF 6 décembre 1997
        Titre IV. Contrat de travail

Contrat à durée indéterminée

Article 13 En savoir plus sur cet article...
En vigueur étendu

Période d'essai :

Au cours de la période d'essai ou de son renouvellement, l'une ou l'autre des parties peut rompre le contrat de travail sans préavis ni indemnités de rupture. La période d'essai terminée, l'engagement est réputé conclu ferme.

La période d'essai, ainsi que sa durée, devra obligatoirement être prévue dans le contrat de travail ou la lettre d'embauche.

La durée de la période d'essai est de :

- cadres supérieurs : accord de gré à gré ;

- cadres : 3 mois pouvant être renouvelée une fois ;

- agents de maîtrise : 2 mois pouvant être renouvelée une fois ;

- autres salariés : 1 mois pouvant être renouvelée une fois. Le renouvellement n'est pas applicable aux salariés de niveau I, échelon 1.

En cas de renouvellement de la période d'essai, un accord écrit devra être établi entre les parties.




CCN: Hôtels
Renouvellement: oui
Renouvellement:" un accord écrit devra être établi entre les parties."
Date 1997
Ouvrier: 1 mois
ETAM:2 mois
Cadre: 3 mois;
"cadre sup acrd de gré à gré"
"Champs d'applicaiton géographique":

Article 24

Période d'essai

Au point de vue professionnel, le contrôle de l'aptitude à l'emploi se fera par des examens ou essais.

**La durée de la période d'essai est fixée à un mois pour les employés, deux mois pour la maîtrise. A défaut de stipulation du contrat d'embauche, elle est fixée à trois mois pour le personnel cadre**, à l'exclusion des directeurs qui verront leur cas réglé de gré à gré.

Durant cette période d'essai, il est garanti au salarié le salaire minimum de sa catégorie.

Dans tous les cas, si la période d'essai n'est pas satisfaisante, elle pourra être **renouvelée une seule fois pour une même durée.**

Lors du renouvellement, le contrat pourra être résilié à tout moment pour les employés, sans préavis ni indemnité de part et d'autre.

Pour les agents de maîtrise, un préavis réciproque de quinze jours devra être observé après le premier mois.

Pour les cadres, un préavis réciproque de quinze jours devra être observé après le deuxième mois.

Pour les contrats à durée déterminée, la période d'essai suivra les règles de la législation en vigueur.

S'il n'a pas été possible de connaître le résultat de la visite médicale d'embauche avant la fin de la période d'essai, l'employeur devra aviser le salarié qu'au cas où cette visite conclurait à son inaptitude il ne pourrait être engagé définitivement."

**Comment by jrduscher** [comment]
voir CCN.xls

**Comment by ClementChapalain** [comment]
repris ici car ce ticket représente une nouvelle fonctionnalité ou un nouvel outil trop gros pour être détaillé en 1 seul ticket github : https://github.com/SocialGouv/code-du-travail-numerique/wiki/%5BOutils%5D-P%C3%A9riode-d'essai
