### ISSUE TITLE
[Kibana] Vérifier la fiabilité de 3 graphes kibana

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5148]
- Regarder comment sont construits ces graphes pur vérifier la fiabilité de l'info

#### 1- Graph "Ratio de feedback positif par type de document"
- comment est calculé ce taux ?
- est-ce que le graphe est fiable quand je filtre sur un type de contenu un particulier (dans l'image ci-dessous j'ai filtré sur "contribution")
- est-ce que le graphe est fiable quand je change de période ? 

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/02fe225c-8987-4ccf-936b-a4f8281da8c9)

#### 2- Graph "Satisfaction - Taux de feedback Positifs (#positifs / #feedbacks)"
- comment est calculé ce taux ?
- est-ce que le graphe est fiable quand je filtre sur un type de contenu un particulier (ex : contribution)
- est-ce que le graphe est fiable quand je change de période ? 

#### 3- Graph "Satisfaction - raisons par parc contenu"
- comment sont calculés les résultats
- est-ce que le graphe est fiable quand je filtre sur un type de contenu un particulier (ex : contribution)
- est-ce que le graphe est fiable quand je change de période ? 

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/6092c0cb-aaea-4128-9d12-991694291fe1)

#### 1- Graph "Pourcentage de personnes qui sélectionnent une CC dans les pages contribution"
- comment est calculé ce taux ?
- est-ce que le graphe est fiable quand je change de période ? 

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/ad140a93-a0eb-4f49-9368-e131cd86c6af)

#### 2- Graph "Pourcentage de personnes qui obtiennent un résultat conventionnel dans les pages personnalisables"
- comment est calculé ce taux ?
- est-ce que le graphe est fiable quand je change de période ? 

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/26189139-dd3e-4fe5-bf52-13f07e33f5a0)

**Comment by m-maillot** [comment]
# I- Dashboard Satisfaction Utilisateurs

## 1- Graph "Ratio de feedback positif par type de document"

* comment est calculé ce taux ?

Ce taux est calculé en prenant le `nombre de feedbacks positifs / nombre total de feedbacks`.

Un feedback positif étant un click sur Oui à la question `Avez-vous trouvé la réponse à votre question ?`

* est-ce que le graphe est fiable quand je filtre sur un type de contenu un particulier (dans l'image ci-dessous j'ai filtré sur "contribution")

Oui, il va bien groupé par type de contenu qu'il récupère depuis l'URL.

* est-ce que le graphe est fiable quand je change de période ?

Non, les données sont calculés pour la mois complet au dernier jour du mois. Du coup, il n'est capable de donner des résultats précis sur des périodes. Cependant, si on sélectionne du 1er Janvier au 1er Mai, il va retourner les données pour le mois de janvier, février, mars et Avril. Par contre, si on sélectionne du 1er Janvier au 15 Avril, il va retourner les données pour le mois de janvier, février et mars (Avril ne sera pas du tout inclus). Idem si on met sur 15 janvier au 15 février, il va retourner les données sur mois de janvier (de 1er au 31) et non la période souhaitée.

## 2- Graph "Satisfaction - Taux de feedback Positifs (#positifs / #feedbacks)"

* comment est calculé ce taux ?

Idem que pour le graph précédents : `nombre de feedbacks positifs / nombre total de feedbacks`

* est-ce que le graphe est fiable quand je filtre sur un type de contenu un particulier (ex : contribution)

Il n'est pas impacté par le type de contenu, c'est un ratio global à l'ensemble du site. On peut cependant filtrer par URL.

* est-ce que le graphe est fiable quand je change de période ?

Idem, il est calculé pour le mois entier donc pas fiable.

## 3- Graph "Satisfaction - raisons par parc contenu"

* comment sont calculés les résultats

Il va calculer nombre de chaque raison (lorsque l'on clique sur non, on va demander la raison à l'utilisation) puis faire le ratio de chaque réponse. Il retirer les réponses sans raison.

* est-ce que le graphe est fiable quand je filtre sur un type de contenu un particulier (ex : contribution)

Il n'est pas impacté par le type de contenu, c'est un ratio global à l'ensemble du site. On peut cependant filtrer par URL.

* est-ce que le graphe est fiable quand je change de période ?

Idem, il est calculé pour le mois entier donc pas fiable.

**Comment by m-maillot** [comment]
# II- Dashboard KPI mensuels

Pour info, les données sur les contributions sont par visites uniques. On va également retiré les duplicats tel que si l'utilisateur a visité 2 fois la même page au cours de la même visite.

## 1- Graph "Pourcentage de personnes qui sélectionnent une CC dans les pages contribution"

* comment est calculé ce taux ?

On va prendre le nombre total de visite unique des pages de contribution générique0. Puis on va regarder le nombre de `cc_select` (l'utilisateur a choisi une convention collective depuis la recherche de sa CC) sur ces visites. 
On va ensuite faire le ratio : nombre de `cc_select` / nombre de pages contributions visitées

Il y a des petits trous dans la raquette car si un utilisateur sélectionne plusieurs CC en restant sur la même page, on ne devrait le comptabilisé qu'une fois. Si l'utilisateur a déjà sélectionné sa CC depuis un outil ou une précédente visite, on pré-selectionne la CC et du coup on n'a pas de `cc_select`. On déduit à tord qu'il n'a pas personnalisé sa CC. Ca reste des cas je pense très faible.

* est-ce que le graphe est fiable quand je change de période ?

Non, il est calculé sur le mois à la date du 1er de chaque mois. Il n'est donc pas possible de choisir au jour. Par contre, on peut sélectionner sur plusieurs mois mais il faut bien mettre de 1er du mois au dernier jour du mois voulu. 

## 2- Graph "Pourcentage de personnes qui obtiennent un résultat conventionnel dans les pages personnalisables"

* comment est calculé ce taux ?

On va prendre le nombre total de visite unique sur une page contribution (générique ou personnalisé). On va ensuite faire le ratio entre : nombre total de visite / (nombre total de `cc_select` + nombre total de page personnalisé).
On a donc le ratio de visites où l'utilisateur a vu s'afficher une réponse lié à sa convention collective.
Il y a les mêmes petits trous dans la raquette que dans le graph précédent.

* est-ce que le graphe est fiable quand je change de période ?

Idem, la donnée est calculée sur le mois donc pas fiable.
