### ISSUE TITLE
[indemnité de licenciement] Bug CC 44 à vérifier

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5149]
Il faudrait vérifier dans le code la facçon dont on calcule le salaire de référence dans les 2 cas suivants pour les catégories pro "Ouvriers et collaborateurs (Groupes I à III) " ainsi que "Agents de maîtrise et techniciens (Groupe IV)" : 

- le salarié n'a pas de préavis (les dates de notif et de fin du contrat sont les mêmes) + il répond "non" à la question "Le salaire mensuel brut a-t-il été le même durant les 12 derniers mois précédant la notification du licenciement ?" + il répond "non" à la question "Les salaires indiqués comportent-ils une partie variable ?"

- la salarié à un préavis (les dates de notif et de fin du contrat sont différentes) +  il répond "non" à la question "Le salaire mensuel brut a-t-il été le même durant les 12 derniers mois précédant la notification du licenciement ?" + il répond "non" à la question "Les salaires indiqués comportent-ils une partie variable ?" + il répond "non" à "Connaissez-vous le montant du dernier salaire perçu (préavis inclus) ?"

Intuition : on retient toujours la moyenne des 12 mois de salaires

**Comment by maxgfr** [comment]
On prend le maximum entre le salaire moyen et le dernier salaire sans les primes en y ajoutant la prime de manière proratisé dans le cas d'un ingé ou alors lorsque l'usager répond non a la question sur le salaire variable

Or dans le cas d'un ouvrier ou technicien qui a un salaire variable, on prend le salaire moyen
