### ISSUE TITLE
Modèles de courrier

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#515]
Integration de 5 modèles de courriers suggérés en openlab sur la base des modèles de courriers précdemment intégrés: ci après intitulés, wordng et ficher docx correspondant ( sur demande)

titre:**- Modèle de courrier :contestation du solde de tout compte incomplet,**
-  préambule à intégrer:  "**Le solde de tout compte** fait l’inventaire des sommes dues au salariés à la rupture du contrat de travail. Attention, le reçu pour solde de tout compte ne peut être dénoncé que dans un délai de **6 mois**: au delà de ce délai, le document devient libératoire pour l’employeur, c'est à dire qu'on ne peut plus le modifier le document ou revenir sur les montants qui y figurent.
Le document ci-après peut être utilisé pour réclamer les montants dues en cas d'erreur ou de sommes manquantes":
ficher : RECU POUR SOLDE DE TTCOMPTEdénociation solde incomplet.docx.
tags:
themes: 200
thème:[ "rupture de contrat", "documents de fin de contrat", "solde de tout compte"]
reference:
"titre": "article L1234-20 du code du travail"
"profil":salarié"

**titre :"Modèle de lettre : Contestation d’un licenciement injustifié auprès de l’employeur"**

préambule: " Tout licenciement doit être motivé par une cause réelle et sérieuse. Le licenciement appartient au pouvoir de l'employeur. Le modèle de courrier ci-après permet d'apporter une réponse au courrier de notification de licenciement, en vue d'apporter à l'employeur des éléments sur le bien fondé de cette décision; elle permet également de proposer à l'employeur une porte de sortie non contentieuse"
fichier" Modèle de courrier contestation licenciement.docx"

   
**titre: "Modèle de contestation de la sanction"**
préambule: " Ce courrier fait suite à la réception d'une notification de sanction au salarié par l'employeur, et permet d'y apporter une réponse,  en vue d'apporter des éléments factuels permettant de contester cette sanction : injustifiée ou disproportionnée  et solliciter une modification de la décision. Il est important de contester ces éléments à ce stade, notamment en vue de constituer  un dossier dans le cas où le tout déboucherait sur 'une contestation contentieuse".
fichier:"modèle de lettre de contestation de sanction.docx"

titre: " Modèle de courrier contestation de l'avertissement"
"L'avertissement est le niveau le plus faible des sanctions actionnables par l’employeur dans l’échelle des sanctions. L’avertissement n'a pas de conséquence sur le contrat de travail.
 Pour autant, un avertissement s'il est infondé ou disproportionné, voire discriminatoire ( c'est à dire fondé sur des critères de discrimination) peut  être contesté. Ce modèle permet de vous aider à formaliser cette contestation."
contestation avertissement.docx

- contestation de l'évaluation du salarié**

**Comment by ClementChapalain** [comment]
outdated, liste des modèles revue récemment
