### ISSUE TITLE
Bug affichage vidéos fiches MT

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5168]
**1) Actuellement les vidéos des fiches MT ne peuvent pas être visionnées chez nous + la balise apparaît :**

Cleaner la balise de notre côté + contacter MT car vidéos ne fonctionnent pas chez eux

Cleaner de manière globale les balises stript

Laisser l'image et afficher un texte pour dire que pb technique

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/97bcdb08-dcc3-4090-8a02-aa15d81eac30)

**2) Nous avons des alertes dans l'admin à chaque fois qu'un élément change dans la balise des vidéos**

**Liste de fiches contenant des vidéos (il faut ouvrir les accordéons) :** 

- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/fiche-ministere-travail/emploi-et-handicap-les-entreprises-adaptees-ea
- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/fiche-ministere-travail/titres-professionnels
- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/fiche-ministere-travail/le-travail-a-temps-partiel-contrat-et-statut-du-salarie
- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/fiche-ministere-travail/les-creches-a-vocation-dinsertion-professionnelle-vip-en-quoi-cela-consiste
- https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/fiche-ministere-travail/5-questions-reponses-sur-le-passage-a-temps-partiel

**Comment by romain-b13** [comment]
Dans ces 6 fiches MT le pb de la vidéo a été corrigé le 5 juin :

•	https://travail-emploi.gouv.fr/droit-du-travail/les-contrats-de-travail/article/le-travail-a-temps-partiel-contrat-et-statut-du-salarie
•	https://travail-emploi.gouv.fr/actualites/l-actualite-du-ministere/article/5-questions-reponses-sur-le-passage-a-temps-partiel 
•	https://travail-emploi.gouv.fr/emploi-et-insertion/emploi-et-handicap/article/emploi-et-handicap-les-entreprises-adaptees-ea
•	https://travail-emploi.gouv.fr/formation-professionnelle/certification-competences-pro/titres-professionnels-373014
•	https://travail-emploi.gouv.fr/archives/archives-courantes/article/les-creches-a-vocation-d-insertion-professionnelle-vip-en-quoi-cela-consiste
•	https://travail-emploi.gouv.fr/droit-du-travail/egalite-professionnelle-discrimination-et-harcelement/indexegapro

Pour ces 6 fiches :
-  on n'a plus l'alerte dans l'admin lié au player depuis l'alerte du 7 juin.
- dans nos fiches, on n'a plus la balise qui s'affiche, la vidéo ne s'affiche pas du tout, on a juste le lien vers la vidéo sur youtube 
=> du coup pas d'action à faire de notre côté


Par contre le problème n'a été traité que sur ces 6 fiches, pour les autres ce ne sera pas traité dans l'immédiat

Il reste 3 fiches "connues" sur lesquelles on a encore le pb : 
- https://travail-emploi.gouv.fr/le-ministere-en-action/relance-activite/plan-1jeune-1solution/faciliter-l-entree-dans-la-vie-professionnelle-10878/cie-employeurs
- https://travail-emploi.gouv.fr/le-ministere-en-action/relance-activite/plan-1jeune-1solution/faciliter-l-entree-dans-la-vie-professionnelle-10878/aide-embauche-pec-jeunes
- https://travail-emploi.gouv.fr/le-ministere-en-action/relance-activite/plan-1jeune-1solution/faciliter-l-entree-dans-la-vie-professionnelle-10878/article/aide-volontariat-territorial-en-entreprise-vert-vte-vert

L'ensemble de ces fiches ont été identifiées comme contenant des vidéos grâce aux alertes qu'on avait dans l'admin lié aux changements dans les balises de ces vidéos. Du coup si MT corrige les 3 fiches restantes, est-ce qu'on a un moyen de vérifier que l'on intégre pas d'autres fiches MT contenant des vidéos ?

**Comment by m-maillot** [comment]
Les 3 dernières fiches ont été corrigées.
