### ISSUE TITLE
[RGAA] Ne jamais disable les boutons sur nos simulateurs

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5212]

**Comment by carolineBda** [comment]
ça a l'air de faire consensus qu'il est mieux de ne pas désactiver les boutons pour que les personnes qui utilisent des readers ne les loupent pas. Mais comme nous ils ne sont pas désactivés avant qu'on ne click une 1er fois dessus, pour l'instant on peut laisser comme ça
