### ISSUE TITLE
[Fiche SP] Image non récupérée + fiche vide

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5225]
**Image non récupérée dans le dernier accordéon**
https://code.travail.gouv.fr/fiche-service-public/jour-ouvrable-jour-ouvre-jour-franc-jour-calendaire-quelles-differences?

**Fiche vide**
https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/fiche-service-public/peut-on-percevoir-lallocation-chomage-en-cas-de-demission

**Comment by carolineBda** [comment]
La 2ème fiche a été dépublié
