### ISSUE TITLE
Première version du formulaire pour l'outil de contribution

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#524]
En tant que V1 de l'outil de contribution, on souhaite construire un formulaire d'ajout de contenu basé sur les specs de ce document (p19-20) : https://docs.google.com/document/d/1aj-tBYfvfMKWaDRLJZ0G83cl7zTFRmzDz_n3d_ekawU/edit?usp=sharing

Ce formulaire sera accessible via login / mdp et pourra être communiqué dès mars aux contributeurs.

**Comment by ivangabriele** [comment]
@ClementChapalain J'ai créé un [nouveau repo](https://github.com/SocialGouv/code-du-travail-backoffice) pour cette partie-là et l'ensemble du back-office. Peut-être que les issues et boards (projects) devraient être créés plutôt là-bas, non?

cc @lionelB

**Comment by ClementChapalain** [comment]
yes c'est déplacé ici : https://github.com/SocialGouv/code-du-travail-backoffice/issues/1 !
