### ISSUE TITLE
Traiter bugs sentry (voir création d'issue si plus de X events)

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5245]
Dans la liste ci après (cf commentaire) identifier les bugs les plus critiques et demandant le moins d'effort afin de les traiter en prio

**Comment by maxgfr** [comment]
Voici la liste des principales erreurs critiques : 

- https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/103342/?environment=production&project=5&referrer=release-issue-stream *Handle le resultat publicodes, et ces inputs non controllés*
- https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/103347/?environment=production&project=5&referrer=release-issue-stream 
- https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/103526/?environment=production&project=5&referrer=release-issue-stream
- https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/109849/?environment=production&project=5&referrer=release-issue-stream *Voir si on modifie la configuration csp pour modifier cette erreur*
- https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/109377/?environment=production&project=5&referrer=release-issue-stream *Voir si on modifie la configuration csp pour modifier cette erreur*
- https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/107837/?environment=production&project=5&referrer=release-issue-stream
- https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/105334/?environment=production&project=5&referrer=release-issue-stream *Comprendre pourquoi on a ce load d'url*
- https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/110144/?environment=production&project=5&referrer=release-issue-stream
- https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/103341/?environment=production&project=5&referrer=release-issue-stream
- https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/110015/?environment=production&project=5&referrer=release-issue-stream *Voir si on modifie la configuration csp pour modifier cette erreur*
- https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/109123/?environment=production&project=5&referrer=release-issue-stream *Voir si on modifie la configuration csp pour modifier cette erreur*

**Comment by maxgfr** [comment]
On a mis en place un filtre pour remonter les erreurs pertinentes (1000 events / days) 👀
