### ISSUE TITLE
Ajouter un bouton de retour à l'accueil

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#526]
Lest tests utilisateurs (cf. [recap Dijon](https://github.com/SocialGouv/code-du-travail-numerique/wiki/%5BTests-utilisateur%5D-2019.02.07-Dijon)) ont montré que les utilisateurs se trouvaient "bloqués" lors de leur navigation sur le site sans moyen simple de revenir à l'accueil, notamment pour explorer les thèmes.

Solution : ajouter un bouton de retour à l'accueil dans le header de l'application.

Problème d'UX : en mobile le bouton et le bandeau "beta" vont se superposer. Potentiellement revoir le design complet du header.

**Comment by ClementChapalain** [comment]
le header a été revu en prenant en compte cette tâche
