### ISSUE TITLE
Récupérer les commentaires du new questionnaire dans kibana

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5288]
pour le questionnaire qui est actullement en prod sur toutes les pages du site on récupère les commentaires dans kibana, pourrait-on récupérer également les commentaires laissés dans le nouveau questionnaire (spécifique à l'indemnité de licenciement => pas encore en prod) dans la même table : 

 https://cdtn-logs-kibana.fabrique.social.gouv.fr/app/dashboards#/view/00c45a90-abe9-11eb-897c-cde847a9d698?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/5597d2b1-38ca-4209-bcf9-a69a22c90fc7)

**Comment by maxgfr** [comment]
Vu qu'on a la même structure au niveau de l'event (action_name, type, etc.), ça arrivera directement sur le même dashboard
