### ISSUE TITLE
Améliorer la recherche entreprise v2

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5289]
1. ajouter des params dans les urls de résultats de recherche après avoir sélectionné une entreprise
2. à corriger : Quand on reload les pages suivantes, on voit apparaître l'étape d'avant pendant quelques secondes : 
  - https://code.travail.gouv.fr/outils/convention-collective/entreprise
  - https://code.travail.gouv.fr/outils/convention-collective/convention
3. à corriger : Quand on clique sur "précédent" dans les 2 mêmes pages listées au point précédent on a quelques secondes l'étape d'avant sans scoll puis ensuite avec le scroll automatique en haut de page
4. normalement sera géré avec l'ajout des params : si je vais jusqu'à la page de la CC et que je fais "précédent" sur le navigateur je n'arrive pas sur la page d'avant (page où on a les résultats des Cc pour l'entreprise sélectionnée) mais sur le moteur de recherche d'entreprise sans avoir conservé ma recherche

**Comment by carolineBda** [comment]
pour le point 2 et 3 je penses qu'il faut éclater en plusieurs fichiers distinct (agreement, selection, ...) le fichierc [slug.tsx](https://github.com/SocialGouv/code-du-travail-numerique/tree/dev/packages/code-du-travail-frontend/pages/outils/convention-collective) pour laisser gérer par next la logique de savoir quel composant afficher en fonction de l'url et ne plus le faire ici : https://github.com/SocialGouv/code-du-travail-numerique/blob/dev/packages/code-du-travail-frontend/src/outils/ConventionCollective/index.tsx#L39

**Comment by m-maillot** [comment]
Corrigé
