### ISSUE TITLE
Améliorer la page de résultats de recherche

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#529]
Une fois la séparation des pages terminée (#465) nous travaillerons sur l'UX de cette page en se basant sur les maquettes de Jérémie :

https://projects.invisionapp.com/share/DBMWXF74F2G/#/screens/309143808

![image](https://user-images.githubusercontent.com/5337489/52804914-b0698600-3085-11e9-8bbe-74ca0edeec0f.png)

**Comment by ClementChapalain** [comment]
depends on #465

**Comment by ClementChapalain** [comment]
needs #465

**Comment by ClementChapalain** [comment]
V1 : 
- [x] mettre le filtre sur le type de réponses sur la gauche
- [ ] reprendre le design de Jérémie sur l'intégration des réponse (respecter la hiérarchie de l'information sur titre / type / source)

Pour plus tard : 
- intégration du filtre sur le secteur d'activité (aujourd'hui on ne peut pas le faire)
- intégration du fil d'ariane (nécessite reflexions sur comment on le construit)

**Comment by lionelB** [comment]
closed by  #579

**Comment by ClementChapalain** [comment]
@lionelB le nouveau design des réponses n'est pas intégré je crois ? je ne le vois pas sur la version de dev en tout cas.
![image](https://user-images.githubusercontent.com/5337489/54124444-b8a5ae80-4402-11e9-88ff-585849c74b50.png)

Si tu préfères que je fasse une nouvelle tâche dis moi !

**Comment by lionelB** [comment]
Ah oui j'ai zappé :(  on re-ouvre l'issue ?

**Comment by ClementChapalain** [comment]
est-ce qu'on peut également virer le bloc "Voir aussi" dans la page de résultats please :)
![image](https://user-images.githubusercontent.com/5337489/55079974-90be7800-509d-11e9-9af2-ebdd9d5f4022.png)
