### ISSUE TITLE
Fiche MT non indexée sur Google ? 

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5293]
La fiche MT suivante est très consultée chez nous mais j'ai l'impression qu'elle a eu quelques problème d'indexation sur Google au vu des résultats de la Google search Console : 

https://code.travail.gouv.fr/fiche-ministere-travail/les-jours-feries-et-les-ponts

Depuis début mai on a plusieurs jours avec 0 impression et 0 clic (on n'avait pas fait une modif su les canoniques ?)

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/c8d847e3-dc95-4922-9e7c-848d911ee183)

**Comment by maxgfr** [comment]
![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/25312957/b6618bfd-375c-4beb-b5ae-8f2a35d443cf)

**Comment by romain-b13** [comment]
### Graphes pour d'autres fiches MT (les plus consultées)

https://code.travail.gouv.fr/fiche-ministere-travail/la-demission

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/27a5abac-77dd-4863-b9df-adb401dc32dc)

https://code.travail.gouv.fr/fiche-ministere-travail/les-conges-pour-evenements-familiaux-et-le-conge-de-deuil

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/b4c0c79b-5933-4e9a-a844-8097dd64672a)


https://code.travail.gouv.fr/fiche-ministere-travail/la-rupture-conventionnelle-du-contrat-de-travail-a-duree-indeterminee

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/61cc3578-0762-429c-a293-a12627cd4686)


https://code.travail.gouv.fr/fiche-ministere-travail/les-conges-payes

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/fdf1750f-26fc-49d6-90eb-f5981528ce0b)

https://code.travail.gouv.fr/fiche-ministere-travail/la-periode-dessai

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/1cc0d84d-5cc9-4747-baba-b6bfdf5a97b5)


### Graphes pour les fiches SP les plus consultées

https://code.travail.gouv.fr/fiche-service-public/convention-collective

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/a6735f2b-1102-4a1c-a716-6e3f57b34ae5)

https://code.travail.gouv.fr/fiche-service-public/le-salarie-peut-il-prendre-des-conges-payes-pendant-son-preavis

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/c41eea91-6fd9-4d36-80b8-66f31879073a)


https://code.travail.gouv.fr/fiche-service-public/indemnite-de-licenciement-du-salarie-en-cdi

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/693c118d-f156-4cc1-9d87-4cb866aae1c0)


https://code.travail.gouv.fr/fiche-service-public/comment-calculer-lindemnite-specifique-de-rupture-conventionnelle

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/cdd947a9-e60e-4176-8cde-c47b72bcbb4b)


https://code.travail.gouv.fr/fiche-service-public/indemnite-compensatrice-de-preavis-licenciement-demission

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/81cdc9ff-f5e4-4b13-8408-4ca5435ba9eb)


### Conclusion

On ne remarque pas de chute à partir de la même date que pour https://code.travail.gouv.fr/fiche-ministere-travail/les-jours-feries-et-les-ponts mais cette fiche semble bien avoir été désindéxée

**Comment by romain-b13** [comment]
pour la fiche MT jours fériés et ponts qui aurait été "désindexée" sur la google search console c'est écrit "erreur de traitement temporaire" pour le sitemap 

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/dee90605-ead1-43cd-b7ff-0d8397e7aeab)

**Comment by romain-b13** [comment]
Cette fiche MT a été modifiée le 6 mai soit 2 jours avant la chute des impressiosn et clics
