### ISSUE TITLE
Problème envoi de l'event "entreprise_select"

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5297]
On doit avoir un problème d'envoi de cet event depuis le mois de juillet car on  a moins de "entreprise_select" que de "CC_select_p2" ou de "click_p2" alors qu’on doit avoir le même nombre pour ces 3 events dans les simulateurs car les 3 sont envoyés au clci sur "suivant.

CC_select_p2 envoyés en juillet (mois non fini) : 

![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/05ab3bdf-bfd4-473a-91fe-202a21b1f379)

entreprise_select envoyés en juillet (mois non fini) : 

![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/020d13e7-448f-4bb6-b9a2-5284d4a679df)

**Comment by romain-b13** [comment]
Vérifier par la même occasion si l'event "entreprise_select" n'est pas parfois dupliqué (envoyé plusieurs fois à la place d'une fois) **en juillet dans l'outil "trouver sa CC"**

Car depuis qu'on a ajouté un bouton de recherche (le 12/06) pour l'accessibilité dans le moteur de recherche d'entrerise il y a beaucoup plus de "entreprise_select" envoyés dans l'outil "trouver sa CC"

**Comment by maxgfr** [comment]
Okay, je pense avoir compris la raison pour laquelle `enterprise_select` et `click_p2` sont différents.

**Il n'y a pas de soucis au niveau de l'envoi de l'event**. Le problème vient du simulateur Trouver sa Convention Collective. Celui-ci, lance les deux events de manière asynchrones`select_p2`.

Le processus se fait en deux étapes : 

1. Envoi de l'event `enterprise_select` au moment où l'utilsateur clique sur l'entreprise

<img width="905" alt="Screenshot 2023-07-31 at 18 32 02" src="https://github.com/SocialGouv/code-du-travail-numerique/assets/25312957/87bcb770-d6b9-4393-ac3b-1ee157a5335f">

<img width="902" alt="Screenshot 2023-07-31 at 18 25 49" src="https://github.com/SocialGouv/code-du-travail-numerique/assets/25312957/d754bdb0-325b-44d0-95f2-f5f4201a4b64">

2. Envoi de l'event `select_p2` lorsqu'il choisit sa convention collective parmi la liste

<img width="856" alt="Screenshot 2023-07-31 at 18 32 18" src="https://github.com/SocialGouv/code-du-travail-numerique/assets/25312957/166c4852-a97f-4d0e-8c04-c438050b888b">
<img width="784" alt="Screenshot 2023-07-31 at 18 32 49" src="https://github.com/SocialGouv/code-du-travail-numerique/assets/25312957/f0168f42-7c60-46ae-8ef1-1d4c2b71ca96">



**Conclusion** : si l'utilisateur ne clique pas sur la convention collective par la suite, `enterprise_select` et `select_p2` seront différents.

Je tiens aussi à préciser que nous disposons d'un autre event qui apparait lorsque l'utilisateur click sur précédent après qu'il ait clicker sur son entreprise où on envoie un event `view_step_cc_search_p2`

<img width="1051" alt="Screenshot 2023-07-31 at 18 27 29" src="https://github.com/SocialGouv/code-du-travail-numerique/assets/25312957/d3b0de2d-2b68-40f9-a06d-7157d5edcdbb">



**Proposition d'amélioration**

1. Une manière de gérer ce soucis serait d'envoyer au même moment le `enterprise_select` et le `select_p2`. Personnelement, je ne trouve pas que cette approche soit pertinente... Car l'event `select_p2` perd de son sens
2. On peut tout simplement créer un nouveau event d'event différent de `select_p2`
3. Laisser tel quel, car en soit, les deux events ont des noms différents, donc, ça me choque pas que leurs métriques ne soient pas correlés

Source :
<https://matomo.fabrique.social.gouv.fr/index.php?module=CoreHome&action=index&idSite=4&period=day&date=yesterday#?idSite=4&period=month&date=2023-07-30&category=General_Actions&subcategory=Events_Events>

**Comment by maxgfr** [comment]
Concernant les autres simulateurs, le problème vient du fait qu'on a une case a cocher `Je n'ai pas d'entreprise`, qui permet d'envoyer un `select_p2` sans `enterprise_select`

**Comment by romain-b13** [comment]
Il n'y a en fait aucun problème. La différence entre le nombre de "entreprise_select" et "cc-select_p2" à partir du 04/07/2023 est logique car à cette date nous avons ajouté la case à cocher "je n'ai pas d'entreprise". Quand l'utilisaetur coche cette case et clique sur "suivant" il envoie un "cc_select_p2" et un "click_p2" **mais pas** d'"entreprise_select".

Donc maintenanant : "entreprise_select" + "select_je_n_ai_pas_d_entreprise" = "cc_select_p2" = "click_p2"
