### ISSUE TITLE
Améliorer la suggestion de résultats pour la rendre plus lisible

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#530]
Actuellement la suggestion de résultats lorsque l'utilisateur tape une recherche dans la barre se confond avec la page de résultats, ce qui rend l'expérience confuse pour l'utilisateur (cf. tests Dijon).

L'objectif est de simplifier les informations disponibles afin de recentrer l'attention sur le champs de recherche : 
![image](https://user-images.githubusercontent.com/5337489/52805365-b7dd5f00-3086-11e9-9784-12ea632b8835.png)

Pour information, l'inspiration est cette ux :
![image](https://user-images.githubusercontent.com/5337489/52805415-cd528900-3086-11e9-97d0-6f5e3a258d30.png)

**Comment by UnbearableBear** [comment]
Bonjour Clément,

Est-ce que tu préconises aussi d'avoir une graisse standard et de ne mettre en gras que les mots renseignés par l'utilisateur dans la recherche ?

**Comment by ClementChapalain** [comment]
Salut ! Effectivement ça rend assez bien dans l'exemple de zendesk, mieux que notre version avec le surlignage jaune en tout cas. OK pour partir là desus :)
