### ISSUE TITLE
Quick win accessibilité 2023

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5301]
**2- Quand on change d'étape sur les simulateurs le focus se fait sur les boutons partage de l'étape suivante => il faut faire le focus tout en haut de la page pour pouvoir utiliser els liens d'accès rapide**

**3- Dans le simulateur de l'IL si erreur dans le champ de saisie de date => le focus doit être sur le champ en question**

**4-  Dans le simulateur de l'IL, sur le tableau où on demande les salaires** 
    - a) les mois doivent être des "th" avec un "scope row"
    - b) sur les en-têtes de colonnes ("Mois", "Salaire mensuel brut et "Primes") on doit avoir des "th scope call"
    - c) faire les mêmes corrections sur ce tableau dans le récap des éléments saisis + ajouter un "caption" sur le tableau du récap des éléments saisis

cf https://www.w3.org/WAI/tutorials/tables/two-headers/
    
**5- Enlever le h2 sur "étapes" dans les simulateurs (colonne de gauche du simulateur) (on peut utiliser un "paragraphe)**

**6- Les boutons de partage n'ont pas d'intitulé quand on enlève le CSS => on peut ajouter un libellé avec un "SR only" par exemple**

7- Boîte à outils : enlever le bouton "estimer"/"calculer" (on peut le laisser visuellement) sur les tuiles mais laisser le lien sur le titre (ex "indemnité de licenciement") et l'étendre sur toute la tuile (garder l'effet au survol + l'ombre)

8- outil "trouver sa CC" => recherche entreprise => afficher "X résultats trouvés" => voir si ça peut être fait juste à la synthèse vocale sans l'afficher 

9- outil "trouver sa CC" => recherche de CC => une fois que j'ai tapé mon idcc ou mot clé et qu'il y a des résultats la synthèse vocale doit dire qu'il y a "X résultats trouvés" pour que l'utilisateur comprenne qu'il peut naviguer dans les résultats => voir si ça peut être fait juste à la synthèse vocale sans l'afficher 

10- outil "trouver sa CC" => recherche de CC => pb au niveau de l'intitulé "Nom de la CC..." => faire un "for"

11- voir le contraste de notre bleu clair et du orange

1- Ajouter une bordure de couleur autour des champs texte qui ne sont pas assez visibles (peut-être même autour des boutons radios)

Outils qu'on peut utiliser pour le contraste : WCAG contrast color / autre outil général : assistant RGAA

**Comment by maxgfr** [comment]
Au niveaux de mes notes j'avais ça (qui reprennent pas mal de tes points) :

- Modifier le comportement avec la tabulation sur les simulateurs, en le faisant focus en haut
- Focus sur les champs en cas d'erreur au suivant au niveau des formuler
- Modifier la structure au niveau de l'étape salaire en mettant le mois dans un `th`
- Au niveau de la page liste des outils, il faut que la selection via la tabulation soit présente sur tout le composant
- Pour l'étape d'auto-completion sur la recherche, il faut dire binder l'input avec un `for`, également dire le nombre de résultats trouvés

Tricks : 
- utiliser la synthèse vocal pour faciliter les tests d'accessibilité
- https://chrome.google.com/webstore/detail/wcag-color-contrast-check/plnahcmalebffmaghcpcmpaciebdhgdf/related
- https://chrome.google.com/webstore/detail/assistant-rgaa/cgpmofepeeiaaljkcclfldhaalfpcand/related?hl=fr
