### ISSUE TITLE
[analyses data] 2 analyses : taux de selection entreprise + provenance visites pages CC

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5303]
1- je voudrais comparer le taux de sélection d'entreprise dans le parcours P2 de l'outil "trouver sa Cc" avant et après l'ajour du bouton de recherche pour le RGAA. Avant pour calculer ce taux de sélection je faisais (entreprise_select/click_P2) car les utilisateurs passaient forcément par un click_p2 (clic sur la tuile "je ne connais pas ma CC) avant de sélectionner une entrprise. Le problème  est que maintenant nous avons une url différente pour chaque étape de l'outil "trouver sa CC" donc les utilisateurs ne passent plus forcémeent uniquement par le clic sur la tuile "je ne connais pas ma CC" pour rechercher une entreprise, ils peuvent arriver directement sur https://code.travail.gouv.fr/outils/convention-collective/entreprise

Comparer la période jusqu'au 11/06 et la période à partir du 13/06

Idée : filter les entreprise_search unique (si 4 entreprise

Pour info, on ne peut pas utiliser le ratio entreprise_select/entreprise_search car on envoie bcp moins d'events "entreprise_search" depuis cette refonte (fin de l'auto-complétion)

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/2dd17e56-f49a-4b5b-9850-a7b7880e4981)

2- voir pour analyser clicks sur les liens dans les contribs personnalisées qui vont vers les pages CC

Le lien vers les pages CC ont été ajoutés dans les contrib personnalisé le 12/06 : 

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/551b4992-a07f-4ee4-9ea2-67d051fc896c)

L'objectif est de voir d'où venaient les visites des pages CC avant l'ajout du lien et d'où elles viennent depuis la'jour du lien 

**Exemple de résultat attendu**

Provenance des visites sur les pages CC du X jusqu'au 11/06 : 
- 10% home
- 10% outil/convention-collective/convention
- 10% moteurs recherche externes
- etc

Provenance des visites sur les pages CC du 13/06 au X :
- 80% /contribution
- 10 outil/convention-collective/convention
- etc

**Comment by maxgfr** [comment]
Il faudrait comparer le 

view_page (après modif) : https://code.travail.gouv.fr/outils/convention-collective/entreprise
view_page (avant modif) : https://code.travail.gouv.fr/outils/convention-collective#entreprise

Normalement ces deux events sont équivalent puis le comparer non pas avec `#selection` ou `/selection`, car on peut arriver dessus directement sans forcement passer par un event.

Donc il faut directement le comparer avec l'event `enterprise_select` qui s'envoit dans les deux cas sur la page `enterprise` lorsque l'utilisateur valide
