### ISSUE TITLE
Liste des conventions collectives et des IDCC en vigueur : suivi

### ISSUE THREAD

**Issue by CaptainConan** [SocialGouv/code-du-travail-numerique#5308]
**Plusieurs outils permettent d’identifier la convention collective applicable et son identifiant (IDCC)** : 
- le moteur de recherche proposé sur le CDTN : notre API (à retrouver [ici](https://api.gouv.fr/les-api/api-conventions-collectives) ) est basée sur le jeu de données des conventions collectives déclarées par entreprises, issues de la DSN (à retrouver [ici](https://travail-emploi.gouv.fr/dialogue-social/negociation-collective/article/table-de-correspondance-entre-secteur-d-activite-et-convention-collective) ). 
- la liste des conventions collectives et de leur IDCC proposée sur le site du ministère du travail : cet outil est notamment utilisé pour compléter la déclaration sociale nominative (DSN) que doit remplir l'employeur ;
- la table de passage entre secteur d’activité économique et convention collective ;
- le moteur de recherche proposé sur le site dédié aux élections professionnelles : cet outil est notamment destiné à renseigner correctement le formulaire utilisé pour établir le procès-verbal des élections professionnelles ;

Ces outils ont pour seul objectif l’identification de la convention collective.

**Comment by CaptainConan** [comment]
**Août 2023**

Le **fichier** des IDCC en vigueur vient d'être **mis à jour** :
[dares_donnes_identifiant_convention_collective_aout23.xlsx](https://github.com/SocialGouv/code-du-travail-numerique/files/12266496/dares_donnes_identifiant_convention_collective_aout23.xlsx)

- Entrée en vigueur le 01/08  d'une nouvelle CCN (hors scope CDTN) : 
Convention collective nationale des commerces de quincaillerie, fournitures industrielles, fers, métaux et équipement de la maison (**IDCC 3243**).
Elle remplace: 
    - la convention collective nationale des commerces de quincaillerie, fournitures industrielles, fers, métaux et équipement de la maison, cadre (**IDCC 0731**)
    - la convention collective nationale des commerces de quincaillerie, fournitures industrielles, fers, métaux et équipement de la maison, employés et personnels de maîtrise (**IDCC 1383**).
	
    Impact sur l'outil "Recherche CC" et sur le moteur : proposer l'**IDCC 3243** lorsque l'utilisateur recherche les **IDCC 0731** et **1383**. Pas de changement de nom.
    Il faudrait aussi désactiver les pages CC des **IDCC 0731** et **1383** pour rediriger vers la page CC de la **3243**.
    La CC **3243** est disponible ici sur Légifrance : https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000047839180 

- Modification de nom d'une CC (hors scope CDTN) :
    - la convention collective régionale de la couture parisienne (**IDCC 0303**) modifie son nom en convention collective régionale de la couture parisienne et des autres métiers de la mode (**IDCC 0303**).

**Comment by CaptainConan** [comment]
**Novembre 2023**
[dares_donnes_identifiant_convention_collective_novembre23.xlsx](https://github.com/SocialGouv/code-du-travail-numerique/files/13425177/dares_donnes_identifiant_convention_collective_novembre23.xlsx)

Entrée en vigueur le  01/11 et 01/10 de deux nouvelles CCN (hors scope CDTN) :

1. Convention collective nationale des professions réglementées auprès des juridictions (**IDCC 3244**).
Elle remplace :
- la convention collective nationale du personnel des greffes des tribunaux de commerce (**IDCC 240**)
l’accord professionnel national de travail entre les avocats au Conseil d'Etat et à la Cour de Cassation et leur personnel salarié -non avocat- (**IDCC 2329**)
- la convention collective nationale du personnel des administrateurs et des mandataires judiciaires) (**IDCC 2706**).

2. Convention collective nationale des commissaires de justice et sociétés de ventes (**IDCC 3250**).
Elle remplace : 
- la convention collective nationale des huissiers de justice (**IDCC 1921**)
- la convention collective nationale des sociétés de ventes volontaires de meubles aux enchères publiques et des offices de commissaires-priseurs judiciaires (**IDCC 2785**)
**Attention :** ces deux IDCC (1921 et 2785) ne sont pas désactivés sur BD3C et pas supprimés de la liste DARES alors qu’ils auraient dû l’être. 

Impact sur l'outil "Recherche CC" et sur le moteur : proposer l'**IDCC 3244**  lorsque l'utilisateur recherche les **IDCC 240, 2329 et 2706** (à noter : lorsque la correction sera faite, proposer **l'IDCC 3250**  lorsque l'utilisateur recherchera  **les IDCC 1921 et 2785**).


La **CC 3244** est disponible ici sur Légifrance : [Convention collective nationale du 26 janvier 2022 des professions réglementées auprès des juridictions - Légifrance (legifrance.gouv.fr)](https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000048202801?origin=list&facetteEtat=VIGUEUR_ETEN&facetteEtat=VIGUEUR_NON_ETEN&facetteTexteBase=TEXTE_BASE&idcc_suggest=3244&page=1&pageSize=50&sortValue=DATE_UPDATE&tab_selection=all)


La **CC 3250**  est disponible ici sur Légifrance : [Convention collective nationale des commissaires de justice et sociétés de ventes volontaires du 16 novembre 2022 - Légifrance (legifrance.gouv.fr)](https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000047802239) 




Modification de nom d'une CC (hors scope CDTN) :
la convention collective régionale de la couture parisienne et des autres métiers de la mode (**IDCC 0303**)  modifie son nom et devient la convention collective nationale de la couture parisienne et des autres métiers de la mode (**IDCC 0303**)

**Comment by m-maillot** [comment]
@CaptainConan avec la mise en place du fichier DARES dans l'admin, peut on clôturer cette issue ?
