### ISSUE TITLE
Améliorer la remontée des termes de recherche dans Matomo

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#531]
Aujourd'hui uniquement les recherches pour lesquelles l'utilisateur a cliqué sur la loupe ou a tapé sur entrée remontent dans matomo, ce qui nous coupe de la majeure partie des recherches utilisateur (celles pour lesquelles un utilisateur a cliqué sur un résultat depuis la suggestion de la barre de recherche).

A priori cette tâche de revue de l'UX du champs de recherche va aider : #530 

Specs en cours

**Comment by revolunet** [comment]
je viens de tester et d'après moi ça fonctionne aussi quand on utilise la touche "entrée" ?

**Comment by ClementChapalain** [comment]
oui a priori ça fonctionne bien, mais du coup on a pas les recherches pour lesquelles l'utilisateur a cliqué directement sur un résultat à partir de la suggestion.

je modifie la description pour préciser 👍

**Comment by revolunet** [comment]
(je vois bien une requete piwik partir à l'ouverture d'un des résultats)

**Comment by ClementChapalain** [comment]
je vois aussi qqchose mais j'ai l'impression que c'est plus un événement de vue d'une page qu'un événement qui remonte la recherche :
![image](https://user-images.githubusercontent.com/5337489/53022590-c7302400-345b-11e9-95e2-90794399bedd.png)

j'ai fait des tests avec des mots clés spécifiques et effectivement je confirme que :
- cliquer sur la loupe ou appuyer sur entrée remonte bien dans matomo
- cliquer directement sur un article depuis la suggestion de résultats ne remonte pas de recherche dans matomo

**Comment by revolunet** [comment]
oui tout à fait, en l'état, ce que tu vas récupérer par défaut ça devrait être l'url de la page ouverte (pageview), pas le mot clé tapé.

**Comment by lionelB** [comment]
J'avais en tête de faire crée un évènement `search` qui collecte les infos du champ de recherche
- envoi d'un évènement lorsqu'on appuie sur `Enter`
- envoi d'un évènement lorsqu'on clique sur un résultat (a terme cet event ne sera plus utile si on propose des requêtes plutôt que des résultats)

**Comment by ClementChapalain** [comment]
D'ailleurs, Jean-René m'avait parlé d'une instance Kibana, ça pourrait peut-être résoudre notre problème à court-terme de visibilité sur les termes de recherche ? Elle est encore disponible ?

**Comment by revolunet** [comment]
https://incubateur-mas.slack.com/archives/C8375SG9X/p1535645837000100

**Comment by revolunet** [comment]
ne fonctionne plus visiblement

**Comment by ClementChapalain** [comment]
je n'arrive pas à accéder à ce lien sur slack

**Comment by ClementChapalain** [comment]
done
