### ISSUE TITLE
Mettre à jour notre stock de CC avec les CC ayant une page légifrance

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5311]
## I- Mettre à jour notre base de CC

Toutes les CC qui se trouvent dans le fichier ci-dessous et qui ont une page sur Légifrance doivent être ajoutées sur le CDTN : 

[IDCC_legifrance_aout23_liens.xlsx](https://github.com/SocialGouv/code-du-travail-numerique/files/12371693/IDCC_legifrance_aout23_liens.xlsx)

### Lorsque la CC  a une page sur Légifrance => on doit avoir une page pour cette CC chez nous. Il s'agit de ce type de page (page pour une CC qu'on ne traite pas) : 

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/88e7be45-1f3f-4b65-bb40-4c428da32fa8)

## Question 

Quand une CC est dans notre stock, comment fait-on le lien sur la Page Légifrance, est-ce entré manuellement ? 

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/dc591804-d02c-4e79-906e-b9327d837f56)

**Comment by romain-b13** [comment]
Dans ce fichier il est précisé pour chaque CC si elle a une page légifrance ou pas : 

/!\ ne pas toucher aux pages CC des CC départementales de la métallurgie car même si elles n'ont pas de pages sur légifrance ce sont des CC qu'on traite chez nous (nous affichons des Q/R)

[IDCC_legifrance_aout23.xlsx](https://github.com/SocialGouv/code-du-travail-numerique/files/12312600/IDCC_legifrance_aout23.xlsx)

**Comment by romain-b13** [comment]
On va traiter cette tâche en 2 :
- d'abord on ajoute les CC qui ont une page légifrance
- ensuite on ajoutera celles qui n'ont pas de page légifrance

**Comment by maxgfr** [comment]
> https://github.com/SocialGouv/code-du-travail-numerique/issues/5285

**Comment by maxgfr** [comment]
Note : Pour l'API de la DILA, certaines CCs sont trouvables via la route `consult/kaliContIdcc` tel que la cc 1261, en revanche pour d'autres ccs tel que la 0045 ne sont pas trouvable même si une page légifrance est rattachée 

ex d'erreur : 

```json
{"timestamp":1692638439461,"error":500,"status":"Internal Server Error","message":"Une exception non gérée est survenue, veuillez contacter l'administrateur","errorCode":null,"exceptionDetails":null}
```
