### ISSUE TITLE
Activer la CC3248 à partir du 01/01/2024

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5316]
La CC 3248 doit être "trouvable" et "sélectionnable" en tant que CC traitée dans : 
- les outils suivants : Indemnité de licenciement / Préavis de démission / Préavis de licenciement / Préavis de retraite / Indemnité de précarité / Heures pour recherche d'emploi / Trouver sa convention collective
- les contributions (pages personnalisables)
- elle doit avoir sa page CC (avec les 42 Q/R)

Il faudrait pouvoir continuer à calculer les règles de la CC 650 dans l'indemnité de licenciement car ce sont ces règles qui s'appliquent pour les ingénieurs et cadres si la notif du licenciement a lieu avant le 01/01/2024. 2 solutions envisagées :
- pouvoir continuer à sélectionner la 650 uniquement dans **l'indemnité de licenciement** alors qu'elle n'existera nulle part ailleurs
- mettre la question sur la de notif du licenciement plus tôt dans le simulateur + pour pouvoir lui demander les bonnes catégories pro etc.

**Comment by m-maillot** [comment]
> les outils suivants : Indemnité de licenciement / Préavis de démission / Préavis de licenciement / Préavis de retraite / Indemnité de précarité / Heures pour recherche d'emploi / Trouver sa convention collective

On peut implémenter l'ensemble des outils et les mettre directement en prod. Comme la CC n'est pas trouvable, personne ne tombera dessus avec que la CC ne soit trouvable sur le site.

**Comment by m-maillot** [comment]
> les contributions (pages personnalisables)

Fortement dépendant du nouvel outil de contribution. Pas de tâches particulière de notre coté à ce niveau là.

**Comment by m-maillot** [comment]
> elle doit avoir sa page CC (avec les 42 Q/R)

Idem, dépendant du nouvel outil de contribution. Pas de tâches particulières de notre coté.

**Comment by m-maillot** [comment]
> Il faudrait pouvoir continuer à calculer les règles de la CC 650 dans l'indemnité de licenciement car ce sont ces règles qui s'appliquent pour les ingénieurs et cadres si la notif du licenciement a lieu avant le 01/01/2024. 2 solutions envisagées :
> 
> * pouvoir continuer à sélectionner la 650 uniquement dans l'indemnité de licenciement alors qu'elle n'existera nulle part ailleurs
> * mettre la question sur la de notif du licenciement plus tôt dans le simulateur + pour pouvoir lui demander les bonnes catégories pro etc.

### Indemnité de licenciement : 

On a deux parcours : 

 * Recherche via `je connais ma CC` : On permet à l'utilisateur de trouver la CC 650 même si elle n'existe plus dans la BDD.

 * Recherche via `je ne connais pas ma CC` : On remplace toutes les CCs métallurgie par la nouvelle 3248 pour n'afficher à l'utilisateur que la 3248. (comportement iso aux autres simulateurs)

Sur l'étape `Ancienneté ` :
 * si CC 650 sélectionnée :  si l'utilisateur renseigne une date de notification supérieure ou égale au 01/01/2024 -> on affiche un message bloquant? l'invitant à sélectionner la CC 3248 pour continuer la simulation. Le mieux serait d'avoir la possibilité pour l'utilisateur de basculer sur la CC 3248 via un lien.
 * Si CC 3248 sélectionnée : si l'utilisateur renseigne une date de notification inférieure au 01/01/2024 -> on affiche un message à l'utilisateur indiquant que la CC n'était pas encore en vigueur et que si il faisait partie de la 650, il peut la sélectionner (voir si on place un lien pour sélectionner directement la CC 650). Si il continue, il n'aura que la réponse du code du travail (ajouté une mention sur la page de résultat)
