### ISSUE TITLE
Message à afficher à l'étape résultat des outils CC3248 à partir du 01/01/2024

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5317]
à partir du 01/01/2024, si la CC 3248 est sélectionnée dans les simulateurs les messages suivant doivent être affichés :  

## 1) Préavis de licenciement
Si la lettre de licenciement a été présentée avant le 01/01/2024, la durée de préavis peut ne pas correspondre au résultat donné. En effet, jusqu’au 31/12/2023, ce sont les conventions locales de la métallurgie ainsi que la convention spécifique aux ingénieurs et cadres de la métallurgie qui s’appliquaient. Toutes ces conventions ont été regroupées pour former la convention collective nationale de la métallurgie (IDCC 3248) applicable depuis le 01/01/2024.

## 2) Préavis de démission
Si la lettre de démission a été présentée avant le 01/01/2024, la durée de préavis peut ne pas correspondre au résultat donné. En effet, jusqu’au 31/12/2023, ce sont les conventions locales de la métallurgie ainsi que la convention spécifique aux ingénieurs et cadres de la métallurgie qui s’appliquaient. Toutes ces conventions ont été regroupées pour former la convention collective nationale de la métallurgie (IDCC 3248) applicable depuis le 01/01/2024.

## 3) Préavis de départ (volontaire) à la retraite
Si la lettre de départ à la retraite a été présentée avant le 01/01/2024, la durée de préavis peut ne pas correspondre au résultat donné. En effet, jusqu’au 31/12/2023, ce sont les conventions locales de la métallurgie ainsi que la convention spécifique aux ingénieurs et cadres de la métallurgie qui s’appliquaient. Toutes ces conventions ont été regroupées pour former la convention collective nationale de la métallurgie (IDCC 3248) applicable depuis le 01/01/2024.

## 4) Préavis de mise à la retraite
Si la lettre de mise à la retraite a été présentée avant le 01/01/2024, la durée de préavis peut ne pas correspondre au résultat donné. En effet, jusqu’au 31/12/2023, ce sont les conventions locales de la métallurgie ainsi que la convention spécifique aux ingénieurs et cadres de la métallurgie qui s’appliquaient. Toutes ces conventions ont été regroupées pour former la convention collective nationale de la métallurgie (IDCC 3248) applicable depuis le 01/01/2024.

## 5) Heures d'absence pour rechercher un emploi
Si la lettre de démission, de licenciement ou de rupture de la période d'essai a été présentée avant le 01/01/2024, le résultat peut ne pas correspondre au résultat donné. En effet, jusqu’au 31/12/2023, ce sont les conventions locales de la métallurgie ainsi que la convention spécifique aux ingénieurs et cadres de la métallurgie qui s’appliquaient. Toutes ces conventions ont été regroupées pour former la convention collective nationale de la métallurgie (IDCC 3248) applicable depuis le 01/01/2024.

### Si on décide de laisser la CC 650 dispo dans l'outil après le 01/01/2024 :

**a) Si la CC 650 est sélectionnée et que la date de notification est < au 01/01/2024 alors on calcule l'indemnité avec les règles de la CC 650**

 **b) Si la CC 650 est sélectionnée et que la date de notification est > au 01/01/2024 alors on calcule l'indemnité avec les règles de la CC 3248 et on affiche le message suivant au résultat :** 

Le montant de l'indemnité a été calculé avec les règles de la nouvelle convention collective nationale de la métallurgie (IDCC 3248) applicable depuis le 01/01/2024. En effet, les conventions locales de la métallurgie ainsi que la convention spécifique aux ingénieurs et cadres de la métallurgie qui s’appliquaient jusqu'au 31/12/2023 ont été regroupées pour former la convention collective nationale de la métallurgie (IDCC 3248).

### Dans tous les cas

**c) Si la CC 3248 est sélectionnée et que la date de notification est < au 01/01/2024 alors au résultat on affiche le message suivant :** 

Comme le licenciement a été notifié avant le 01/01/2024, le montant de l'indemnité peut ne pas correspondre au résultat donné. En effet, jusqu’au 31/12/2023, ce sont les conventions locales de la métallurgie ainsi que la convention spécifique aux ingénieurs et cadres de la métallurgie qui s’appliquaient. Toutes ces conventions ont été regroupées pour former la convention collective nationale de la métallurgie (IDCC 3248) applicable à partir du 01/01/2024.

**Comment by m-maillot** [comment]
On va utiliser la même méthodologie que pour la 3239, voici la PR associée (préavis de démission, preavis licenciement et depart/mise à la retraite): 
https://github.com/SocialGouv/code-du-travail-numerique/pull/4148/files

### Pour heures absence recherche emploi : 

Il faut implémenter le fait que l'on a une notre disponible dans le json et l'afficher.

### Indemnité de licenciement : 

On a deux parcours : 

 * Recherche via `je connais ma CC` : On permet à l'utilisateur de trouver la CC 650 même si elle n'existe plus dans la BDD.

 * Recherche via `je ne connais pas ma CC` : On remplace toutes les CCs métallurgie par la nouvelle 3248 pour n'afficher à l'utilisateur que la 3248. (comportement iso aux autres simulateurs)

Sur l'étape `Ancienneté ` :
 * si CC 650 sélectionnée :  si l'utilisateur renseigne une date de notification supérieure ou égale au 01/01/2024 -> on affiche un message bloquant? l'invitant à sélectionner la CC 3248 pour continuer la simulation. Le mieux serait d'avoir la possibilité pour l'utilisateur de basculer sur la CC 3248 via un lien.
 * Si CC 3248 sélectionnée : si l'utilisateur renseigne une date de notification inférieure au 01/01/2024 -> on affiche un message à l'utilisateur indiquant que la CC n'était pas encore en vigueur et que si il faisait partie de la 650, il peut la sélectionner (voir si on place un lien pour sélectionner directement la CC 650). Si il continue, il n'aura que la réponse du code du travail (ajouté une mention sur la page de résultat)
