### ISSUE TITLE
Message spécifique page CC 3248 à partir du 01/01/2024

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5318]
**User story** : En tant que salarié/employeur rattaché à la CC3248, à partir du 01/01/24, je souhaite être informé que les infos que je consulte n'étaient pas valables avant le 01/01/24

**Sur la page de la CC 3234, à partir du 01/01/2024 il faudra afficher le message suivant :** 

A noter : les informations données sur cette page sont applicables depuis le 01/01/2024
Cette convention collective est entrée en vigueur le 01/01/2024 suite au regroupement des conventions locales de la métallurgie ainsi que de la convention spécifique aux ingénieurs et cadres qui étaient applicables jusqu’au 31/12/2023.

**Design**
Reprendre ec qu'on avait fait pour la 3239 : 

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/3f241782-daf4-4bf0-8928-e233e3937871)

**Comment by m-maillot** [comment]
Ce message s'affiche automatiquement en ajoutant dans le document le highlight : 
```json
"highlight": {
	"title": "A noter : les informations données sur cette page sont applicables depuis le 01/01/2024",
	"content": "Cette convention collective est entrée en vigueur le 01/01/2024 suite au regroupement des conventions locales de la métallurgie ainsi que de la convention spécifique aux ingénieurs et cadres qui étaient applicables jusqu’au 31/12/2023."
},
```
