### ISSUE TITLE
Message spécifique contrib avec CC3248 à partir du 01/01/2024

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5319]
**User story** : En tant que salarié/employeur rattaché à la CC3248, à partir du 01/01/24, lorsque je sélectionne la nouvelle CC dans une page personnalisable, je souhaite être informé que les infos que je consulte n'étaient pas valables avant le 01/01/24

**Contrib (pages personnalisables) personnalisées avec la CC3248**
A partir du 01/01/2024 le message suivant devra être affiché lorsque l'utilisateur sélectionnera la CC3248 dans une contrib :

A noter : les informations données sur cette page sont applicables depuis le 01/01/2024
Cette convention collective est entrée en vigueur le 01/01/2024 suite au regroupement des conventions locales de la métallurgie ainsi que de la convention spécifique aux ingénieurs et cadres qui étaient applicables jusqu’au 31/12/2023.

**Design**
Reprendre ce que l'on avait fait pour la CC 3239 à partir du 01/01/2022

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/be80cf8a-5eb4-4248-ade3-2e66c5640c5c)

**Comment by m-maillot** [comment]
Actuellement, on affiche un message en dessous de la convention collective. Il est cependant possible d'afficher le même message que celui affiché sur la page de la convention collective.

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/992514/df0e8efb-e747-41cd-8c16-53897d417244)
