### ISSUE TITLE
bug: modèle qui ne correspond pas à la FAQ

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#532]
![image](https://user-images.githubusercontent.com/37538697/52873183-b5ded300-314e-11e9-86b8-210153aa653b.png)

![image](https://user-images.githubusercontent.com/37538697/52873204-c000d180-314e-11e9-84e2-6e338a4457d2.png)

le modèle ne colle pas au contenu certificat de travail sur un thème période d'essai. 
modèle certiicat de travail (200) alors que renew  période d'essai (3760).

**Comment by lionelB** [comment]
après investigations,

ce la vient du fait que le formatage du contenu de certaine faq ne correspond pas à ce qu'on attend

ex: 
```
  {
    "question": "Ma période d'essai peut elle être renouvelée ? (Boulangerie)",
    "reponse": "La convention collective de la boulangerie ne prévoit pas que la période d'essai soit renouvelée.",
    "themes": [3760],
    "tags": {
      "theme": "période d'essai",
      "branche": "boulangerie"
    },
    "date": "13/07/2018",
    "source": "CDTN",
    "redacteur": "CDTN"
  },
```
ici la clé `themes` devrait se trouvait à l'intérieur de la clé `tags`

cela me fait dire qu'il faut absolument que je merge la PR #202 avec un outils de validation des contenus en attendant d'avoir mieux

**Comment by lionelB** [comment]
closed by #768
