### ISSUE TITLE
Redirections de toutes les contrib personnalisées avec une CC méta locale ou CC650 vers la contrib personnalisée avec la CC 3248

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5321]
A partir du 01/01/2024, les url des contrib (pages personnalisables) personnalisées avec les anciennes CC de la méta (contenant un des n° listés ci-dessous dans l'url) doivent être redirigées vers la même contrib mais personnalisée avec la CC3248 (3248 dans l'url) : 

<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">
<style>

</style>
</head>

<body>

IDCC | Intitulé
-- | --
54 | METALLURGIE   OETAM REGION PARISIENNE
650 | METALLURGIE INGENIEURS ET CADRES
714 | METALLURGIE   MOSELLE
822 | METALLURGIE SAVOIE
827 | METALLURGIE ARDENNES
828 | METALLURGIE MANCHE
829 | METALLURGIE VAUCLUSE
836 | METALLURGIE HAUTE-SAVOIE
860 | METALLURGIE FINISTERE
863 | METALLURGIE MORBIHAN   ILLE-ET-VILAINE
878 | METALLURGIE RHONE
887 | METALLURGIE EURE
898 | METALLURGIE ALLIER
899 | METALLURGIE MARNE
911 | METALLURGIE SEINE-ET-MARNE
914 | METALLURGIE AIN
920 | METALLURGIE VIENNE
923 | METALLURGIE CHARENTE-MARITIME
930 | METALLURGIE SARTHE
934 | METALLURGIE INDRE
937 | METALLURGIE HAUTE-VIENNE ET   CREUSE
943 | METALLURGIE CALVADOS
948 | METALLURGIE ORNE
965 | METALLURGIE VAR
979 | METALLURGIE LE HAVRE   (SEINE-MARITIME)
984 | METALLURGIE EURE-ET-LOIR
1007 | METALLURGIE THIERS (PUY-DE-DOME)
1059 | METALLURGIE MIDI-PYRENEES
1159 | METALLURGIE NIEVRE
1164 | METALLURGIE SOMME VIMEU
1274 | METALLURGIE CORREZE
1315 | METALLURGIE HAUTE-MARNE ET MEUSE
1353 | METALLURGIE DORDOGNE
1365 | METALLURGIE MEURTHE-ET-MOSELLE
1369 | METALLURGIE LOIRE-ATLANTIQUE
3209 | METALLURGIE DOUBS
1387 | METALLURGIE FLANDRES DOUAISIS
1472 | METALLURGIE PAS-DE-CALAIS
1525 | METALLURGIE DUNKERQUE (NORD)
1560 | METALLURGIE ALPES-MARITIMES
1564 | METALLURGIE SAONE-ET-LOIRE
1572 | METALLURGIE CHARENTE
1576 | METALLURGIE CHER
1577 | METALLURGIE HERAULT AUDE   PYRENEES-ORIENTALES
1578 | METALLURGIE LOIRE ET   ARRONDISSEMENT D'YSSINGEAUX
1592 | METALLURGIE VALENCIENNOIS   CAMBRESIS (NORD)
1604 | METALLURGIE ROUEN DIEPPE   (SEINE-MARITIME)
1626 | METALLURGIE HAUTES-PYRENEES
1627 | METALLURGIE CLERMONT-FERRAND   PUY-DE-DOME
1628 | METALLURGIE DEUX-SEVRES
1634 | METALLURGIE COTES-D'ARMOR
1635 | METALLURGIE GIRONDE LANDES
1732 | METALLURGIE YONNE
3231 | METALLURGIE JURA
1813 | METALLURGIE MAUBEUGE (NORD)
1867 | METALLURGIE DROME-ARDECHE
1885 | METALLURGIE COTE-D'OR
1902 | METALLURGIE MAINE-ET-LOIRE
1912 | METALLURGIE HAUT-RHIN
1960 | METALLURGIE LOT-ET-GARONNE
1966 | METALLURGIE LOIRET
1967 | METALLURGIE BAS-RHIN
2003 | METALLURGIE VOSGES
2126 | METALLURGIE GARD ET LOZERE
2221 | METALLURGIE ISERE HAUTES-ALPES   (MENSUELS)
2266 | METALLURGIE MAYENNE
2294 | METALLURGIE AUBE
2489 | METALLURGIE VENDEE
2542 | METALLURGIE AISNE
2579 | METALLURGIE LOIR-ET-CHER
2615 | METALLURGIE PYRENEES-ATLANTIQUES   ET DU SEIGNANX
2630 | METALLURGIE BOUCHES-DU-RHONE   ALPES-HAUTE-PROVENCE
2700 | METALLURGIE DE L'OISE
2755 | METALLURGIE BELFORT MONTBELIARD
2980 | METALLURGIE SOMME
2992 | METALLURGIE INDRE-ET-LOIRE
3053 | METALLURGIE HAUTE-SAONE

</body>

</html>

**Comment by m-maillot** [comment]
On peut utiliser l'api redirect de Next.js : https://nextjs.org/docs/pages/api-reference/next-config-js/redirects

**Comment by maxgfr** [comment]
J'ai compté 66 redirections
