### ISSUE TITLE
[Prépa méta] Intégrer un message accompagnant le résultat de la nouvelle CC 3248

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5322]
**User Story :** En tant que salarié/employeur anciennement rattaché aux CC locales ou à la CC des ingénieurs et cadres de la métallurgie, à partir du 01/01/24, lorsque j'effectue une recherche avec les mots clés/idcc de mon "ancienne" CC, je souhaite comprendre pourquoi on me renvoie en résultat la CC 3248

**Fonctionnalité**
Le résultat de la CC 3248 doit être accompagné de la mention suivante lorsque j'ai le résultat 3248 dans le parcours "je connais ma CC" de l'outil "trouver sa CC", des simulateurs, des contrib et dans les résultats du moteur de recherche du site : 

**Message**
"Nouvelle convention collective en vigueur issue du regroupement des conventions locales de la métallurgie ainsi que de la convention spécifique aux ingénieurs et cadres"

**Design**
Reprendre ce que l'on avait fait pour la 3239 : 

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/b2136a27-d7ba-482d-ab1e-1e2f1b47680c)

**Comment by m-maillot** [comment]
Cette fonctionnalité a sauté suite à la mise en place du composant autosuggest pour l'accessibilité. Il est donc à remettre en place.

C'est assez simple à remettre. C'est dans le render de la suggestion : https://github.com/SocialGouv/code-du-travail-numerique/blob/605a0f9fc8ebb12a5c621675e563779d1ab58da5/packages/code-du-travail-frontend/src/outils/common/Agreement/AgreementSearch/AgreementInput/SearchAgreementInput.tsx#L121
