### ISSUE TITLE
Intégration de la CC 1391 dans la CC 275

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5329]
**Contexte :** la CC 1391 (que nous ne traitons pas) va être intégrée dans la CC 275 (que nous traitons) à partir du 31/01/2024

- [x] 1) Retirer la CC 1391 de notre base kali : on ne doit plus pouvoir trouver cette CC sur le site

- [x] 2) Mettre en place des redirections 

  L'url : https://code.travail.gouv.fr/convention-collective/1391-manutention-et-nettoyage-sur-les-aeroports-region-parisienne doit être redirigé vers l'url https://code.travail.gouv.fr/convention-collective/275-transport-aerien-personnel-au-sol
  
- [x] 3) Définir des synonymes pour le moteur de recherche de CC et le moteur de recherche global du CDTN

	- si je cherche "1391" je dois avoir en résultat la CC 275
	- si je cherche "Manutention aéroport" je dois avoir en résultat la CC 275
	- si je cherche "Nettoyage aéroport" je dois avoir en résultat la CC 275

- [x] 4) Recheche de CC via l'entreprise : remplacer le résultat 1391 par 275 pour les entreprises qui ont toujours la CC 1391 en résutat dans siret2idcc
	
	=> aucune entreprise ne devra avoir en résultat la CC 1391, si on identfiie cette CC on la remplace par la CC 275 dans les résultats
		
	cf ce qu'on a fait pour la CC 1740

- [x] 5) Modification du calcul de l'Indemnité de licenciement pour la CC275

	En effet avec cette entrée en vigueur il va y avoir quelques modifications dans la façon de calculer l'indemnité de licenciement
	
	On peut 
	- calculer avec les "anciennes" règles si on détecte que la date de notification du licenciement est antérieure au 31/01/2024
	- calculer avec les "nouvelles" règles si on détecte que la date de notification du licenciement est à partir du 31/01/2024

	Dans le tableau 
	- les nouvelles règles en violet => à appliquer si on détecte que la date de notif du licenciement est à partir du 31/01/2024
	- les anciennes règles à continuer à appliquer pour tous les licenciement dont la date de notification est jusqu'au 30/01/2024

**Comment by maxgfr** [comment]
@romain-b13 Mes observations sont :
1) l'ancienneté n'a pas bougé entre les anciennes et nouvelles regles
2) le salaire de ref, il ne bouge pas, c'est comme avant, à savoir identique au CDT 
3) Seulement les règles ci-dessous ont bougé, et doivent uniquement être prises en compte à partir du 1 er fevrier:

![Screenshot 2024-01-12 at 15 56 02](https://github.com/SocialGouv/code-du-travail-numerique/assets/25312957/a686dfc7-a724-44ab-a7af-5502ecbddf6e)

4) Cela sinfie qu'on applique les anciennes règles pour les licenciement précedant cette règle
5) Ajouter une notification pour informer l'utilisateur finale de cela

**Comment by maxgfr** [comment]
⚠️ On avait auparavant des plafonds à 20 * Sref ; 19 * Sref

Or aujourd'hui, je vois juste un plafond à 18 * Sref, que ce soit sur l'avant 01/02/2024 et sur l'après aussi (mais ça a la rigueur c'est pas grave)

**Comment by maxgfr** [comment]
De plus, j'ai corrigé un soucis sur l'anciennté requise de 1 an sur l'ancienne version
