### ISSUE TITLE
Modification de l'intro d'un modèle

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5330]
**Modifier l'intro du modèle ci dessous**

https://code.travail.gouv.fr/modeles-de-courriers/rupture-dun-contrat-de-travail-a-duree-determinee-dun-commun-accord

Voici la nouvelle intro :  

La rupture anticipée du contrat de travail à durée déterminée par le salarié ou l’employeur, en dehors de la période d’essai, est limitée à un certain nombre de cas (ex : embauche en CDI). Une rupture d’un commun accord entre le salarié et l’employeur est cependant possible. Elle ouvre droit en principe à une indemnité de fin de contrat (certains CDD tels que les contrats saisonniers ou d’usage n’ouvrent cependant pas droit à cette indemnité). Il est à noter que la rupture conventionnelle individuelle est une modalité de rupture spécifique du CDI, qui ne s’applique pas aux CDD.

**Comment by m-maillot** [comment]
Autre modification : 


![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/992514/1452771c-1fc1-4e0e-aab4-1b512fa11197)
