### ISSUE TITLE
Supprimer les H2 présents sur toutes les pages ? 

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5336]
**Doit-on supprimer les H2 cideesous présents sur toutes les pages du site (au moins les 2 premiers, car après ce sont les titres des rubriques dans le footer) :** 

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/a496ef71-f640-4423-b7f0-9f7cba9e808a)

**Par contre si on fait ça certaines pages n'auront plusd e H2 du tout :** 

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/3a6a953c-641d-4a1c-85f9-caa58aeacf6e)

**Comment by carolineBda** [comment]
Tous ces titres ont été ajouté pour des raisons d’accessibilité :

- Mettre « Besoin de plus d’informations ? » en titre `<h2>` 
- Bas de page : mettre en titre `<h2>` « Code du travail numérique » « Aidez-nous à améliorer cet outil » «En collaboration avec» 
- Modale questionnaire : mettre « QUESTION 3 SUR 1/2/3» comme titre `<h2>`
