### ISSUE TITLE
[SEO - Analyse] Pages non pertinentes remontent sur Google

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5350]
### Problème n°1 : des contrib personnalisées remontent à la place de la générique 

Une action a déjà été effectuée mais pour l'instant sans impact (passage de 0,5 à 0,7 en priority dans le sitemap pour les contrib générique)

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/ef61bbf4-7929-48c7-97d4-ec81a06a5183)

**Explication du pb :** 

Google propose parfois des contrib personnalisées avec une CC alors que ma requête est égénrale et ne contient aucun mots ou numéro liés à une CC

Pb : l'usager se retrouve à lire la réponse pour une CC qui n'est pas la sienne

Exemple 1 : je recherche "Congé pour mariage" => nous sommes en 3ème position mais Google propose la contrib personnalisé avec une CC départementale de la métallurgie : https://code.travail.gouv.fr/contribution/1813-les-conges-pour-evenements-familiaux

Exemple 2 : je recherche "Congés décès grand parent" => nous sommes en 2ème position mais Google propose la contrib personnalisé avec une CC départementale de la métallurgie :
https://code.travail.gouv.fr/contribution/1902-les-conges-pour-evenements-familiaux

### Problème n°2 : des pages thèmes remontent à la place d'un contenu

Sur Google, quand on recherche par exemple "Congé naissance" on a en résultat n°6 l'url d'un thème au lieu d'avoir la contrib sur les congés pour événements familiaux par exemple : https://code.travail.gouv.fr/themes/conges-lies-a-la-naissance-et-a-lenfance

**Comment by m-maillot** [comment]
Problème n°1 : corrigé
Problème n°2 : Voir avec Jonathan

**Comment by romain-b13** [comment]
Le problème n°1 n'est pas résolu dans tous les cas, ex : 

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/1ff8d9fd-0c7f-4a63-ab3d-774684ca26c6)

**Comment by romain-b13** [comment]
On voit d'ailleurs que sur la période du lendemain de la modif à ajd (12/09 au 28/09) la contrib personnalisée avec la CC de la méta est toujours devant la générique : 

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/f5fd6d02-5f5f-45e4-8044-554c7b26d05d)

**Comment by romain-b13** [comment]
Avant de mettre en prod la nouvelle version de la page personnalisable "congés pour év familiaux" la générique était toujours plus consultée que les personnalisées : 

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/fd3a77a8-2a4c-424e-b077-4ed892b0aee1)

**Comment by m-maillot** [comment]
Cela semble être bon maintenant @romain-b13 

![CleanShot 2024-02-14 at 15 49 22@2x](https://github.com/SocialGouv/code-du-travail-numerique/assets/992514/85ec72eb-ff2d-41b4-8ad8-9623d4b263cf)

On fait encore actuellement des modifications SEO pour améliorer encore plus la remonté du générique à la place du spécifique.
