### ISSUE TITLE
Construire un set de recherches populaires

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5355]
L'idée est de pouvoir comparer différents modèles avec un même set de questiosn/requêtes et évaluer pour chaque modèle les contenus remontés en résultats. Pour cela, il faudrait préparer : 
- un set de requêtes effectuées sur notre moteur de recherche
- un set de requêtes effectuées sur Google (qui amènent à une visite sur le CDTN)
- un set de questions formulées en langage naturel 

Prendre du 01/01/2023 au 31/08/2023

**Comment by Viczei** [comment]
[searchConsoleRecherchePop - Requêtes.csv](https://github.com/SocialGouv/code-du-travail-numerique/files/12496175/searchConsoleRecherchePop.-.Requetes.csv)

**Comment by Viczei** [comment]
[Uploading MatomoRecherchePop - Résultats de la requête.csv…]()

**Comment by Viczei** [comment]
[MatomoRecherchePop - Résultats de la requête.csv](https://github.com/SocialGouv/code-du-travail-numerique/files/12497948/MatomoRecherchePop.-.Resultats.de.la.requete.csv)

**Comment by romain-b13** [comment]
Des écarts avec ce que j'ai dans Matomo : 

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/8d8f61a6-3885-4b02-9fc4-e6128f2fd21e)

**Comment by romain-b13** [comment]
Voici les recherches faites sur le site (export de Matomo du 01/01/23 au 31/08/23)

[Export recherches site du 01-01-23 au 31-08-23.xlsx](https://github.com/SocialGouv/code-du-travail-numerique/files/12520575/Export.recherches.site.du.01-01-23.au.31-08-23.xlsx)

**Comment by romain-b13** [comment]
Set de recherches en langage naturel :

[Set de recherches en langage naturel.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/12857201/Set.de.recherches.en.langage.naturel.docx)
