### ISSUE TITLE
Faire un diff entre kali-data et les CC du fichier Dares qui ont une page Légifrance V2

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5363]
Nouvelle version corrigée de l'Excel :

[Liste CC ayant un page Légifrance.xlsx](https://github.com/SocialGouv/code-du-travail-numerique/files/12495819/Liste.CC.ayant.un.page.Legifrance.xlsx)

Du coup, il faut faire un diff entre les Cc kali-data et celles qui sont dans cet Excel

**Comment by romain-b13** [comment]
Nouvelle version corrigée de l'Excel :



[IDCC_legifrance_aout23_liens (4).xlsx](https://github.com/SocialGouv/code-du-travail-numerique/files/12495602/IDCC_legifrance_aout23_liens.4.xlsx)

**Comment by maxgfr** [comment]
Il faut faire attention l'excel a un soucis pour la CC 405 et 2357, que je corrige ci-dessous.

Pour les prochaines fois, il faudra partir de cet excel.

Le nouveau lien pour la 405 que j'ai mis : https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000026950865

Et le nouveau lien pour la 2357 : https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000005635472


[idcc_liens.xlsx](https://github.com/SocialGouv/code-du-travail-numerique/files/12498181/idcc_liens.xlsx)

**Comment by maxgfr** [comment]
@romain-b13 Via ce nouveau modèle, la seule CC que j'ai ajouté est la 804
