### ISSUE TITLE
[Discussion - étude d'impact] Modification des page CC à prévoir suite à la réécriture des contrib

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5365]
La réécriture des contrib entrainera des modifications dans les pages CC (ex d'une page CC : https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/convention-collective/2120-banque) : 

- **[Pas de dév spécifique à faire]** Contrairement à aujourd'hui, pour chaque question dont la réponse de la CC était partielle : la réponse affichée ne sera plus celle de la CC uniquement, mais la nouvelle réponse issue de la fusion code du travail et CC

- **[Dév à faire pour ajouter une phrase d'intro]** Pour les questions pour lesquelles la CC ne prévoit rien ou pour lesquelles la réponse de la CC n'est pas publiée => on affichera dans la page CC la réponse du code du travail (alors qu'aujourd'hui on n'affiche pas les questions des cas cités dans la page CC) => il faudra ajouter en amont de la réponse une phrase qui explique que la réponse donné provient du cdt (à voir si on distingue celles CC ne prévoit rien et réponse dépubliée)

- **[Pas de dév spécifique à faire]** Dans chaque réponse (chaque accordéon) de la page : il faudra ajouter le message "texte applicable" (bloc 3 etc.) correspondant sous la réponse

- **[Dév à faire]** Dans chaque réponse (chaque accordéon) de la page : il faudra supprimer le message affiché actullement qui renvoie vers la page personnalisable de la question consultée : 
![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/fc837c3a-cc5d-478f-9256-06df34035d60)

- **[Dév à faire]** Modifier le message d'intro identique sur toutes les pages CC (et également à modifier dans les tuiles des pages CC : résultat de recherche sur le site etc.) : 
![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/3e062dd3-7520-4ee2-8316-62526635adff)

**Comment by carolineBda** [comment]
Penser à regarder comment les données sont généré pour une CC (dans l'ingester ?)

**Comment by m-maillot** [comment]
C'est traité du coup ce ticket @romain-b13 ? On pourrait le cloturer.
