### ISSUE TITLE
Une fois qu'on aura jouter les CC sans page légifrance : faire un diff entre nos CC et les CC du fichier Dares

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5367]
Fichier de la Dares à utiliser pour faire le diff avec nos CC : 

[dares_donnes_identifiant_convention_collective_aout23 (4).xlsx](https://github.com/SocialGouv/code-du-travail-numerique/files/12535306/dares_donnes_identifiant_convention_collective_aout23.4.xlsx)

Une fois qu'on aura bien dans notre base de CC toutes les CC qui se trouvent dans l'excel de la Dares (même celles qui n'ont pas de page légifrance) alors il faudra faire un diff : 

- on est censé avoir dans kali-data toutes les Cc qui se trouvent dans l'Excel de la Dares => si ce n'est pas le cas il faut les ajouter mais attention : voir si elle existe sur Légifrance avant ou non pour savoir le comportement qu'elle doit avoir chez nous

- Pour les CC qu'on a "en plus" (c-a-d qu'elles sont dans kali-data mais pas dans le fichier de la Dres) => transmettre la liste des CC "en plus" au métier pour être sûr qu'on les supprime chez nous (car ne sont plus en vigueur)

**Comment by maxgfr** [comment]
Normalement cette PR est lié à cette issue  : https://github.com/SocialGouv/cdtn-admin/commit/530043d68ce7def89555ae696d0ac2d6f9aa346b
