### ISSUE TITLE
[Outil trouver sa CC] Amélioration retour arrière parcours de recherche entreprise

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5370]
quand on est dans le parcours "je ne connais pas ma CC" de l'outil "trouver sa CC" puis qu'on sélectionne une entreprise et qu'on clique sur un des résultats (tuile) le précédent du navigateur fonctionne pour revenir jusqu'au moteur de recherche d'entreprise mais ne permet pas de passe de /outils/convention-collective/entreprise à /outils/convention-collective

**Comment by m-maillot** [comment]
Corrigé avec la nouvelle navigation. On peut revenir en arrière jusqu'à /outils/convention-collective
