### ISSUE TITLE
[RGAA] Corrections accessibilité 2023 v2

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5377]
### Simulateur de l'indemnité de licenciement
A faire dans les autres simulateurs aussi (pour certains correctifs) dans un 2eme temps 

- [x] 1) enlever le "tab index 1" dans les simulateurs

- [x] 2) permettre la fermeture du questionnaire de statisfaction dans l'outil d'indemnité de licenciement
- [x] 3) quand on coche une réponse ou entre des dates qui font qu'on passe direct à l'étape "résultat" car il n'y a pas d'indemnité pour ce cas :
   a)  ajouter un "rôle alert" sur la phrase en rouge
   b) mettre le paragraphe du dessous dans un` <p>`

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/e7c43b11-7b8e-4181-b9b2-236baa95b5f4)
- [x] 4) ajouter un "rôle alert" sur tous les messages d'erreurs (ex : "vous devez répondre à cette question")
- [x] 5) Signe € à l'étape salaire => ajouter "en €" dans les 2 titres des colonnes (dans le th)
=> j'ai ajouté un title au field plutot
- [x] 6) mettre "en texte" la formule de calcul de l'étape "résultat" dans un aria label
- [x] 7) mettre les intitulés de questions devraient être dans des éléments legend. Ex : `<legend>Quel est le type du contrat de travail ? <span>(obligatoire)</span></legend>`
- [x] 8) enlever la taille fix sur la date pour permettre le zoom
![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/4971715/28fa67f2-b8ab-48c2-9457-bf285c7defd3)

### Tuiles de la boîte à outils

- [x] Soit : enlever le bouton sur les "estimer" / "calculer" et les mettre dans un <p>
      Soit : ajouter un aria label "calculer l'indemnité de licenciement"
- [x] enlever la taille fixe du header pour permettre le zoom
![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/4971715/c9c4581a-7eec-4f6f-bfa0-5eeb734a0939)
- [x] En mobile, pas de carroussel mais des boites les unes sous les autres

### Partout
- [x] Le 1er Tab doit faire apparaître un lien "Contenu"

### Outil "trouver sa CC"

**Je connais ma CC** 
1) agreement search label => à remplacer par "Nom de la convention collective ou son numéro d’identification IDCC (champ obligatoire)" + enlever le aria label
2) mettre plus de contraste sur les résultats quand on les survole
3) l'icone pour vider le champ ne prend jamais le focus
4) la synthèse vocale ne lit pas les résultats sur lesquels on passe => voir ici http://pidila.gitlab.io/select-a11y/ 

 **Je ne connais pas ma CC** 
1) afficher "X résultats"
2) Dans les résultats : mettre un seul lien sur le premier élément de la tuile et l'étendre sur toute la tuile avec le CSS
3) le title de la page doit être différent selon la recherche effectuée

### Dates indemnité licenciement
Revoir avec benoit : Pour les champs date, c'est quand mieux d'utiliser les attributs natifs HTML tel que `<input type="date" />`, c'est p-ê moins conforme à la charte mais ça marche vraiment beaucoup mieux

### DSFR
bordure des champs pas assez contrastée
couleurs rouge et bleu

### Dossiers IL
- [ ] Impossible de naviguer dans les tab avec le clavier
![Screenshot from 2023-10-16 17-04-51](https://github.com/SocialGouv/code-du-travail-numerique/assets/4971715/6b1c757e-31ae-4164-b9a8-329407b591b8)
@carolineBda: *Je trouve ces Tab différentes et difficiles à naviguer en mobile, je me demande si on devrait pas mettre des accordéon comme sur les autres pages de contenus ?*

**Comment by carolineBda** [comment]
A faire sur les autres simulateurs

**Comment by carolineBda** [comment]
= > enlever "Voir plus de résultats" sur les pages thèmes : https://code.travail.gouv.fr/themes/contrat-de-travail
 ce n'est pas utilisable au clavier + n'optimise pas le load

=> Lancer une recherche juste au clavier : Au tabulation clavier, après le clic sur lancer ma recherche (au milieu de la page) la zone en dessous se met a jour par rapport au mot saisie et on repassant la tabulation le focus est placé en haut de page →  normalement je dois etre repositionné sur la zone mis à jour."

=> sélection CC avec le clavier non visible
![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/4971715/94c04fef-cb30-42d6-8c19-1edc18c8422d)
