### ISSUE TITLE
Remplacer les identifiants « oauth » des repos kali-data et legi-data sur GitHub

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5378]
utiliser l'api légifrance avec le compte codedutravailnumerique@travail.gouv.fr à la place du compte julien.bouquillon@sg.social.gouv.fr

**Comment by maxgfr** [comment]
Ok, ça a été fait sur : `kali-data`, `legi-data` et sur l'`alert-cli` de l'admin
