### ISSUE TITLE
[Data analyse] note de satisfaction sur toutes les contrib personnalisées + génériques

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5385]
- 1) regarder sur matomo
- 2) kibana
- 3) notebook

Besoin
- Pourcentage de réponses oui/non par url générique
- Pourcentage de réponses oui/non par url avec n°idcc

**Comment by maxgfr** [comment]
Voici le resultat de l'analyse pour la période du 01/09/23 au 01/10/2023 : 

[satisfaction.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/12916377/small.pdf)
