### ISSUE TITLE
Remettre à jour déclaration d'accessibilité suite à nos correctifs

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5387]

**Comment by carolineBda** [comment]
= > enlever "Voir plus de résultatsé sur les pages thèmes : https://code.travail.gouv.fr/themes/contrat-de-travail
 ce n'est pas utilisable au clavier + n'optimise pas le load

=> Lancer une recherche juste au clavier : Au tabulation clavier, après le clic sur lancer ma recherche (au milieu de la page) la zone en dessous se met a jour par rapport au mot saisie et on repassant la tabulation le focus est placé en haut de page →  normalement je dois etre repositionné sur la zone mis à jour."

=> sélection CC avec le clavier non visible
![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/4971715/94c04fef-cb30-42d6-8c19-1edc18c8422d)
