### ISSUE TITLE
[contrib congé pour év familiaux] ajouter bouton "afficher les infos" dès le début + event

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5395]
1) Ajout du bouton "afficher les informations" dès le début (cf image ci après)

2) ajouter un event au clic sur le bouton quand le clic est fait sans rien avoir sélectionner : 
e_c: contribution
e_a: click_afficher_les_informations_start
e_n: url de la page sur laquelle les events sont fait

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/8a250cce-886e-4641-96d6-9aaaf02ad31b)

**Comment by carolineBda** [comment]
Je trouve que "click_afficher_les_informations_sans_CC" est plus parlant comme nom d'event, t'en pense quoi ?
