### ISSUE TITLE
Pouvoir suivre la campagne sur Matomo (pour nous)

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5411]
- permettre d'avoir la data dans l'onglet campagne de matomo : il me semble avoir compris qu'il faut utiliser [l'url builder tool](https://matomo.org/docs/tracking-campaigns/) de matomo, qui permet à matomo d'identifier les visites et les mettre dans l'onglet campagne => on l'avait déjà fait l'année dernière

Voici ce que Max avait dit l'année dernière :

Pour résumer, il faut impérativement passer des paramètres à l'URL. Les deux paramètres obligatoires sont les mots clés et le nom de la campagne. L'exemple est ici: [https://code.travail.gouv.fr?mtm_campaign=NOM_CAMPAGNE_SEA&mtm_kwd=MON_MOT_CLE](https://code.travail.gouv.fr/?mtm_campaign=NOM_CAMPAGNE_SEA&mtm_kwd=MON_MOT_CLE)

Le premier lien liste les paramètres qu'on peut passer à l'url pour l'identifier : https://matomo.org/faq/reports/what-is-campaign-tracking-and-why-it-is-important/

Le second lien permet de générer cet url via un outil qu'ils ont développé et que je vous conseille d'utiliser : https://matomo.org/faq/tracking-campaigns-url-builder/

**Comment by romain-b13** [comment]
Carte de l'année dernière : https://github.com/SocialGouv/code-du-travail-numerique/issues/4608

**Comment by maxgfr** [comment]
Oui, en conclusion, il faut que tu génères pour chaque URL de la campagne, une url qui dispose d'un query parametre `mtm_campaign`. En paramètre **non optionnel**, tu peux rajouter `mtm_kwd` et/ou `mtm_source`

Par example : 
- `URL_A_TRACKER?mtm_campaign=campagne2023` 
- `URL_A_TRACKER?mtm_campaign=campagne2023&mtm_kwd=mot_cle&mtm_source=google`
