### ISSUE TITLE
[admin] gestion des blocs "texte applicable"

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5431]
Au niveau de chaque question il faudra 4 boutons radio :
- Bloc 2
- Bloc 3
- Domaine exclusif de la branche
- Message personnalisé

Pour chaque bouton radio (c-a-d chaque bloc) il y a 3 variantes de message possibles. La variante à afficher dépendra de ce que sélectionne l'utilisateur sur le font (une CC traitée, une CC qui ne prévoit rien, une CC non traitée)
-> variante 1
-> variante 2
-> variante 3

Ex : Le métier choisit juste "bloc 2" dans l'admin pour une question et la variante va varier selon ce que sélectionne l'utilisateur sur le font (une CC traitée, une CC qui ne prévoit rien, une CC non traitée)

**Voici le fichier avec les différentes variantes pour chaque bloc :** 

[Messages blocs - 14-11-2023 (3).docx](https://github.com/SocialGouv/code-du-travail-numerique/files/13349605/Messages.blocs.-.14-11-2023.3.docx)

**Comment by carolineBda** [comment]
@romain-b13 https://github.com/SocialGouv/cdtn-admin/issues/996
