### ISSUE TITLE
[Front] Dév du parcours des new contrib

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5432]
- [x] ecrire des tests sur le front (react testing librairy + cypress)
- [x] tester les 2 branches
- [x] style tableau
- [x] mettre un h2 sur "Votre réponse pour la convention [....]
- [x] faire fonctionner la page : /contribution
- [ ] tester la recherche par CC : CC de la metallurgie
- [ ] tester la page CC (avec les anciennes contribs ?)

Erreur accordéon: https://code-du-travail-numerique-carolinebda-test-branch-on-divxvlnj.dev.fabrique.social.gouv.fr/contribution/1516-quelle-est-la-duree-de-preavis-en-cas-de-licenciement

**Message bloc**
- [ ] Générique : bloc CC non traité (pétrol)
- [ ] Générique - fiche SP : on affiche le message bloc "Texte applicable si la convention collective est non traitée" : https://code-du-travail-numerique-carolinebda-test-branch-on-divxvlnj.dev.fabrique.social.gouv.fr/contribution/quelles-sont-les-conditions-de-la-clause-de-non-concurrence
- [ ] idem pour Perso : https://code-du-travail-numerique-carolinebda-test-branch-on-divxvlnj.dev.fabrique.social.gouv.fr/contribution/1517-quelles-sont-les-conditions-de-la-clause-de-non-concurrence
- [ ] si la CC renvoie au Code du Travail, on affiche le message bloc "Texte applicable si la convention collective est non traitée" au lieu de "Texte applicable si la convention collective ne prévoit rien" : https://code-du-travail-numerique-carolinebda-test-branch-on-divxvlnj.dev.fabrique.social.gouv.fr/contribution/1351-faut-il-respecter-un-delai-de-carence-entre-deux-contrats-de-mission-interim

**Fiches pratiques**
- [x] retirer le html des descriptions des contrib dans les tuiles 
- [ ] Ordre tuiles "Fiches pratiques"
- [x] Contribs personnalisées remontent dans "Fiches pratiques"

** Tuiles**
Gérer les thèmes dans les tuiles "pour aller plus loin"

![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/4971715/2952fdcd-4206-4fb1-b373-10f1f8bf7087)

**Comment by carolineBda** [comment]
Cas de test

- [ ] Générique Answer | 4 et 17
- [ ] Générique SP | 10
- [ ] Perso - Afficher la réponse | 4/0016, 0029, 0044
- [ ] Perso - La convention collective ne prévoit rien | 17/0016
- [ ] Perso - La convention collective renvoie au Code du Travail
- [ ] Perso - La convention collective intégralement moins favorable que le CDT | 17/3127
- [ ] Perso - Nous n'avons pas la réponse | 17/0573
- [ ] Perso - La convention collective ne prévoit rien - SP | 10/1517
- [ ] Générique Answer with tab | 15
- [ ] Perso Answer with tab | 4 /1043
