### ISSUE TITLE
[meta] Intégration phase 2 hiérarchie des normes

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#545]
méta-tâche sur l'intégration de la hiérarchie des normes dans le CDTN

**lier les contenus MT et SP aux articles de lois**
- [x] #549 

**lier les articles de lois aux différents blocs de hiérarchie des normes**
- [ ] #586 

**revoir le bloc articles de loi correspondants pour en faire un bloc "sources de droit" dans lequel on explique bien quelle est la hiérarchie**
- [x] #587
- [x] #628 
- [ ] #684 

présentation sur la hiérarchie des normes dans le CDTN :
https://docs.google.com/presentation/d/1ISw5eMorXr9g8mTZeQUVo1l2qNK3j-uUX75Rq5jIBgU/edit#slide=id.g5280f819b2_0_45

**Comment by ClementChapalain** [comment]
document de travail : https://docs.google.com/document/d/1Hm0kwTFirhnXaDjhOJmMd37dCEEelKqvylZKuNmsirE/edit#

**Comment by lionelB** [comment]
Est ce que ca pourrait être utile d'ajouter un champ dans les themes impacté par la hirarchie des normes (ou dit autrement, la vérité est dans la ccn ?)

**Comment by ClementChapalain** [comment]
je comprends pas bien, un champs pour faire quoi ?

**Comment by lionelB** [comment]
un champ avec un boolean (oui / non) voir la liste des bloc qui pourrait impacter un theme 
l'idée etant d'avoir l'info pour pouvoir via l'ui dans le cas ou on affiche un theme de pouvoir de demander la ccn

**Comment by ClementChapalain** [comment]
ah oui carrément ça pourrait être interessant !

**Comment by ClementChapalain** [comment]
je close car on a validé la solution de traiter la HDN dans les contenus (outils, articles, questions / réponses des SR) et de ne pas créer un moteur qui associe le texte applicable pour chaque contenu ou requête

cf. le doc de travail pour tout le contexte :
https://docs.google.com/document/d/1Hm0kwTFirhnXaDjhOJmMd37dCEEelKqvylZKuNmsirE/edit#
