### ISSUE TITLE
Gérer les cas où "nous n'avons pas de réponse" dans les nouvelles contrib

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5467]
Dans les 2 cas suivants le comportement sur le front doit être le même que quand un utilisateur sélectionne une CC non traitée :

- dès que la réponse n'est pas en statut "publié" quelque soit le bouton radio qui est coché pour cette réponse
- quand la réponse est "publiée" mais que le bouton radio "Nous n'avons pas la réponse" est coché

**Comment by carolineBda** [comment]
si document déjà créer : il faut le supprimer quand on publie
