### ISSUE TITLE
broken CCNdata.json

### ISSUE THREAD

**Issue by adipasquale** [SocialGouv/code-du-travail-numerique#547]
the file packages/code-du-travail-data/CCNdata.json is broken and unused. can we remove it altogether?

@douglasduteil you're the one who merged that commit, do you remember where does this file come from and whether it's safe to delete it or not? 

I think it's the same contents as the file `packages/code-du-travail-data/dataset/faq-conventions-collectives.json`

https://github.com/SocialGouv/code-du-travail-numerique/blob/b4cb274d50393f37c8eb64aa966b5a50f8ea4421/packages/code-du-travail-data/CCNdata.json#L2

**Comment by revolunet** [comment]
removed
