### ISSUE TITLE
Tester le lot n°2 de contrib new format à mettre en prod

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5476]
Question suivantes à tester avec les différents cas (CC ne prévoit rien etc.) : 
- 50
- 20
- 45
- 39
- 42
- 26
- 7
- 51
- 36
- 53

**Comment by romain-b13** [comment]
@Viczei dans la liste donnée juste au dessus voici celles quin sont totalement validées : 

•    20
•    39 (sauf 3248 donc bientôt complètement validée)
•    42
•    26 (sauf 3248 donc même chose)
•    7
•    51
•    36

**Comment by maxgfr** [comment]
> @Viczei dans la liste donnée juste au dessus voici celles quin sont totalement validées :
> 
> • 20 • 39 (sauf 3248 donc bientôt complètement validée) • 42 • 26 (sauf 3248 donc même chose) • 7 • 51 • 36

Je confirme que pour cette liste, tout est bon au niveau du testing, au jour du 19/12/2023
