### ISSUE TITLE
Lier les contenus SP aux articles de lois

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#549]
*Première partie de l'intégration de la hiérarchie des normes, cf. #545*

----

L'objectif final est de pouvoir indiquer pour chaque contenu comment s'applique la hiérarchie des normes sur les textes applicables. Pour cela nous avons de pouvoir relier nos contenus aux articles du code du travail qui sont concernés.

Dans un premier temps, pour service-public.fr. Le contenu de service-public.fr est issu d'un fichier xml récupéré depuis [data.gouv](https://www.data.gouv.fr/fr/datasets/service-public-fr-guide-vos-droits-et-demarches-particuliers/#_). Dans ce contenu on peut récupérer les articles liés au code du travail dans la partie suivante :
```
<dc:source>
	http://www.legifrance.gouv.fr/affichCodeArticle.do;?idArticle=LEGIARTI000006278886&cidTexte=LEGITEXT000006069414,
	https://www.legifrance.gouv.fr/affichCode.do?idSectionTA=LEGISCTA000006161638&cidTexte=LEGITEXT000006069414,
	http://www.legifrance.gouv.fr/affichCode.do?idSectionTA=LEGISCTA000006161690&cidTexte=LEGITEXT000006069414,
	https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000006688992&cidTexte=LEGITEXT000006072665
</dc:source>
```

Pour repérer le contenu lié au code du travail il faut se fier à l'id `cidTexte=LEGITEXT000006072050`

Il y a deux ensuite deux types de liens : 
- des liens vers des articles au format `http://www.legifrance.gouv.fr/affichCodeArticle.do;?idArticle=LEGIARTI000006278886&cidTexte=LEGITEXT000006069414`
- des liens vers des sections au format `https://www.legifrance.gouv.fr/affichCode.do?idSectionTA=LEGISCTA000006161638&cidTexte=LEGITEXT000006069414`

À partir de l'id d'article `idArticle` ou de l'id de la section `idSectionTA` il faut que l'on puisse récupérer le (dans le cas d'un `idArticle`) ou les (dans le cas d'un `idSectionTA`) articles de loi correspondant via la base de données LEGI et les afficher sur le code du travail numérique, de la même manière que pour les FAQ aujourd'hui :
![image](https://user-images.githubusercontent.com/5337489/53328213-c7ac3d00-38e9-11e9-8fc9-bbd704affd40.png)

**Comment by revolunet** [comment]
Les extraits SP et MT incluent bien des références, vers des articles, sections, eu autres textes (ex: JORF) mais actuellement ces données ne son pas indexées dans ES.

Il faudrait : 

 - [ ] indexer ces "références" dans ES (dans le script d'indexation)
 - [ ] côté API, a la consultation d'un contenu SP ou MT, remonter les infos complètes de ces références (par exemple avec une API du type https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-api/src/server/routes/items/relatedDocument.elastic.js)
 - [ ] Gérer ces contenus associés à l'affichage

Il va falloir faire une petite fonction qui prend une URL "legifrance" et nous la "resolve" dans notre index ES. ceci nous permettra : 
 - de proposer un lien vers un contenu interne
 - de lister les numéros d'article d'une section
 - de résolver le numéro d'article depuis le lien pour pouvoir déduire la hierarchie ds normes à appliquer

Je fais une proposition dans ce sens rapidement

**Comment by revolunet** [comment]
Pour le listing des articles pour les fiches SP/MT :

 - J'ai du mettre à jour le fichier du code du travail au 2019-01-01. pour l'instant c'est généré (en attendant la DILA) avec une version expérimentale de legi.py mais @adipasquale et moi allons solidifier ça rapidement 🙏 ✨

 - fonctionnement prévu : lorsqu'une fiche cite un lien Légifrance, on peut le faire passer dans notre fonction qui renvoie le ou les articles associés (en se basant sur le fichier JSON code du travail). On pourra faire de même pour les CC. l'intérêt est assez limité mais ca permettra de linker des contenus internes et de faire des filtres si besoin pour la "hierarchie des normes". on peut mettre ces informations au moment de la génération du fichier JSON des fiches (manuellement à chaque nouvelle livraison sur data.gouv atm).

Ensuite ces données seront indéxées ces données dans ES avec une clé... `related` ? Je pensais à quelque chose comme ça qui devrait suffire pour gérer affichage + lien ?

```js
{
  related: [{
    type: 'article',
    num: 'D2341-2',
    title: 'Article D2341-2 du code du travail',
    cid: 'LEGITEXT000023234',
    id: 'LEGIARTI980242432',
    url: 'url-originale'
  },{
    type: 'convention-collective',
    id: 'KALICONT000005635807',
    idcc: '843',
    title: 'Convention collective nationale de la boulangerie-pâtisserie du 19 mars 1976.',
    url: 'url-originale'
  }]
}
```

Une fois ces données dans ES, ca permettra de les remonter au client pour gérer l'affichage. (dans la page "détail" de contenu)

Questions :

 - dans le cas où le lien Legifrance est un lien vers une section (SCTA), on est d'accord qu'on ne veut que les articles de 1er niveau, pas ceux des éventuelles sous(-sous)-sections ?

 - parfois les articles cités sont abrogés, et ils ne sont actuellement pas inclus dans notre index ElasticSearch. il faudra statuer sur ce qu'on fait pour ces cas-là. actuellement ils sont simplement skippés donc ca restera un lien Légifrance "classique". 35 liens sont dans ce cas pour le dataset "vosdroits-particuliers" de la DILA. (ex: LEGISCTA000018525040, LEGISCTA000018534962, LEGISCTA000018525908)

**Comment by ClementChapalain** [comment]
> dans le cas où le lien Legifrance est un lien vers une section (SCTA), on est d'accord qu'on ne veut que les articles de 1er niveau, pas ceux des éventuelles sous(-sous)-sections ?

tu as un exemple ? j'ai l'impression en ayant regardé rapidement qu'une section contient soit des articles soit d'autres sections mais pas les deux

> parfois les articles cités sont abrogés, et ils ne sont actuellement pas inclus dans notre index ElasticSearch. il faudra statuer sur ce qu'on fait pour ces cas-là. actuellement ils sont simplement skippés donc ca restera un lien Légifrance "classique". 35 liens sont dans ce cas pour le dataset "vosdroits-particuliers" de la DILA. (ex: LEGISCTA000018525040, LEGISCTA000018534962, LEGISCTA000018525908)

je suis pour ne pas les inclure aussi

**Comment by revolunet** [comment]
Les sections avec des "sous-sections", par exemple https://www.legifrance.gouv.fr/affichCode.do;?idSectionTA=LEGISCTA000035623934&cidTexte=LEGITEXT000006072050&dateTexte=20180208

**Comment by revolunet** [comment]
Pour les fiches MT, la qualité des données est moins bonne, les articles ne sont pas forcément bien référencés. ex : https://travail-emploi.gouv.fr/droit-du-travail/les-conges-payes-et-les-conges-pour-projets-pro-et-perso/article/les-conges-payes

Les liens dans la colonne de droite n'ont pas de `href` et dans le texte lui-même, tous les articles cités n'ont pas forcément de lien. donc je vais récupérer le maximum "manuellement", ça demandera un peu plus de travail pour aller plus loin :/

**Comment by ClementChapalain** [comment]
> Les sections avec des "sous-sections", par exemple https://www.legifrance.gouv.fr/affichCode.do;?idSectionTA=LEGISCTA000035623934&cidTexte=LEGITEXT000006072050&dateTexte=20180208

merci ! effectivement on peut ne pas les prendre pour ne pas surcharger de contenu je pense 👍

**Comment by ClementChapalain** [comment]
> Les liens dans la colonne de droite n'ont pas de `href` et dans le texte lui-même, tous les articles cités n'ont pas forcément de lien. donc je vais récupérer le maximum "manuellement", ça demandera un peu plus de travail pour aller plus loin :/

ok tu es capable d'estimer à peu près quel % des articles on peut récupérer ?

**Comment by revolunet** [comment]
Deux questions pour aller plus loin : 

  - comment faudrait-il afficher les articles quand on en a beaucoup ? 
  - ne devrait-on pas afficher le texte de l'article directement au lieu d'un lien vers une page avec le détil de l'article (les articles sont souvent très courts)

 ex: /fiche-service-public/contrat-de-travail-du-salarie-a-domicile-services-a-la-personne?q=contrat%20de%20travail%20du%20salarié%20à%20domicile

**Comment by ClementChapalain** [comment]
> comment faudrait-il afficher les articles quand on en a beaucoup ?

Ils seront groupés par bloc de hiérarchie des normes, avec un affichage plus compact qu'aujourd'hui

> ne devrait-on pas afficher le texte de l'article directement au lieu d'un lien vers une page avec le détil de l'article (les articles sont souvent très courts)

Je suis d'accord, on peut imaginer du contenu qui apparait au clic aussi mais sans changer de page

**Comment by ClementChapalain** [comment]
Est-ce que ça te va @revolunet si on clot cette tâche ? Je vais expliciter qu'on fait pour l'instant le travail sur les fiches SP et qu'on verra ensuite pour les fiches MP

**Comment by ClementChapalain** [comment]
up 👆 @revolunet je peux fermer ?

**Comment by revolunet** [comment]
Yes merci
