### ISSUE TITLE
MàJ automatique de certains contenus

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#550]
*suite de #409*

----

https://www.legifrance.gouv.fr/eli/decret/2018/12/19/MTRX1833925D/jo/texte

- Il faudrait détecter les contenus "maison" impactés par le décret
- le décret de revalorisation a toujours le même intitulé, peut on créer une règle de maj avec les données legifrance?

Cela devrait a priori être géré coté outils de contrib avec un systême d'alerte qui tourne en tache de fond

**Comment by m-maillot** [comment]
Ticket flou, manque de détail sur la demande.
