### ISSUE TITLE
Utilisation de Link et du router next.js dans le subrepo UI

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#552]
Actuellement, nous avons des components (e.g. Category) qui comportent des liens (<a> tags) dans l'UI, alors que nous devons utiliser les outils fournis par Next.js pour gérer le routing dans le repo frontend.
Ce qui fait que le component UI Category est actuellement "dupliqué" dans le repo front qui lui utilise la balise <Link> fournies par Next.js

Que faire ?

Liée à https://github.com/SocialGouv/code-du-travail-numerique/issues/495

**Comment by revolunet** [comment]
A propos de ce composant Category : c'est à titre de démo pour l'instant car nous n'avons pas défini comment ce contenu va être défini ou géré (automatiquement, manuellement...)

**Comment by UnbearableBear** [comment]
fixed by @lionelB
