### ISSUE TITLE
Différences preprod/prod observée suite à la release du 28/12 en preprod

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5523]
1) artciles liés varient entre preprod et prod 

preprod  : 

![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/e6c0f5c9-9e32-405a-9ee7-4c1e400d50b7)

prod : 

![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/be9d1106-f1a8-4863-a587-ffc21bc59314)

2) résultat plus petit dans les simulateurs en preprod par rapport à la prod 

![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/c0dd1cde-4b6c-453e-a86f-d8a5964f0194)

3) écart dans les résulats du moteur de recherche globale

en preprod : 

![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/552cd8dd-7b4f-4f59-a2c3-8f9853b33b79)

en prod : 

![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/b571cd98-76cd-4928-ba2a-321a37d46003)

Ecarts observées aussi pour les requêtes suivantes :
- A quelle date l’employeur doit-il me remettre mes documents de fin de contrat ?
- A quelle date l’employeur doit-il régler mon salaire ?

4) la contrib "Faut-il respecter un délai de carence entre deux CDD ? Si oui, quelle est sa durée ?" n'est pas rataché au même thème entre preprod et prod (il faut savoir que cette contrib est thémé dans 2 thèmes différent)

Preprod : 

![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/9ea747b6-454f-4c21-a0aa-17ecb8228316)

Prod : 

![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/ce84281d-7ecf-45e4-b491-18f97c157c02)

**Comment by maxgfr** [comment]
**Pour le point 3** 

J'ai regardé si nous avons fait des itérations sur la partie frontend, et si celle-ci posait soucis.

Il semble que non. Le problème ne provient du frontend, ni du backend.

Entre la version en production et celle de la preproduction, le seul paramètre ayant changé est le nombre de contributions (de 4500 à 2000 environ), et le nombre de convention collective (de 700 à 600 environ)

Ma supposition me pousse à dire que les résultats ont changé suite à la diminution du nombre de documents ingérés

Pour information, aucun snapshot a bougé sur la recherche au niveau de l'API.

**Pour le point 1** 

Les articles liés sont générés à partir des covisites et de la recherche.

Concernant les covisites, elles ne sont pas fonctionnelles.

En sachant que nous avons la partie recherche qui a bougé, le fait que les articles liés bougent également prouvent que le soucis provient de la donnée et non des requêtes.

Ce soucis touche tout type de contenu et non exclusivement les contributions et les conventions collectives

**Pour le point 2** 

C'est une regression qu'on a ajouté dans la PR sur la fusion des méta. J'ai corrigé ce soucis ici : https://github.com/SocialGouv/code-du-travail-numerique/pull/5522

**Pour le point 4** 

J'ai vérifié que ce problème ne proviennent pas du front en logguant l'objet qu'on reçoit. Ce qui prouve, que cela provient de l'admin.

Nous avons récemment traité ce soucis ici : https://github.com/SocialGouv/cdtn-admin/pull/1204

Il faut creuser sur cette partie et voire pourquoi cela ne fonctionne pas
