### ISSUE TITLE
Etat des lieux des Hn sur le lot de 8 contrib à MEP

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5527]
- 7
- 20
- 26
- 36
- 39
- 42
- 50
- 51

**Comment by m-maillot** [comment]
Je n'ai détecté qu'une seule erreur sur le contenu 👍 

Sur la question 42, pour la CC 16, j'ai une balise h4 vide détectée.

![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/992514/30f405de-465a-4abf-97ef-d50717eedcea)

Il faudrait supprimer la ligne et c'est tout bon :)
