### ISSUE TITLE
Futur de @socialgouv/next-routes

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#554]
Je trouve le cout d'entrée de cette lib assez élévé. Elle n'est plus maintenue et next avance vite. Il faudra revenir dessus tôt ou tard

**Comment by revolunet** [comment]
Pourrait être remplacé par un hook dès que c'est sec :) https://twitter.com/timneutkens/status/1057053195044823040

**Comment by UnbearableBear** [comment]
https://github.com/zeit/next.js/issues/7329 ? Je propose de continuer à regarder ça de près. Mais quoiqu'il en soit, la refacto sera plus facile si on n'a pas d'utilitaire qui wrap Link et Router

**Comment by UnbearableBear** [comment]
https://nextjs.org/blog/next-9#dynamic-route-segments ?????

**Comment by UnbearableBear** [comment]
Ca pourrait suffire ça ?

**Comment by revolunet** [comment]
a priori oui :)

**Comment by revolunet** [comment]
fixed
