### ISSUE TITLE
version mobile -> problèmes bloquants

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#556]
parce que c'est pas glorieux 
![image](https://user-images.githubusercontent.com/160320/53422846-8cd90080-39e0-11e9-871c-ec0d9da11c34.png)

**Comment by revolunet** [comment]
un mot par ligne c'est accessible ça :)

**Comment by ClementChapalain** [comment]
Problèmes bloquants :
- [ ] champs de recherche -> enlever le facetting + mettre le bouton "rechercher" en desssous ?
![image](https://user-images.githubusercontent.com/5337489/55713101-453a9100-59f0-11e9-81df-a7a5e8f93e12.png)
- [ ] affichage des réponses -> enlever la colonne des filtres ?
![image](https://user-images.githubusercontent.com/5337489/55713171-6602e680-59f0-11e9-9a71-b36dfe079c60.png)
- [ ] marges sur l'affichage d'un contenu -> enlever l'icône ?
![image](https://user-images.githubusercontent.com/5337489/55713261-99457580-59f0-11e9-98e3-819643dd8b11.png)

J'ai fait quelques propositions sur les problèmes qui sont réellement bloquants, je suis dispo pour faire une session de travail avec un développeur sur le sujet pour trouver des solutions les plus élégantes possibles je pense que ce sera le plus simple :)

**Comment by lionelB** [comment]
Oki je peux proposer des trucs dans l’issue dans un premier temps aussi

**Comment by lionelB** [comment]
pour la page de recherche, on peut sortir le faceting de l'input et le placer en dessous  ce qui permettrai de remplacer la colonne avec les filtres.
