### ISSUE TITLE
[Analyse] Préparer le simulateur indemnité de rupture conventionnelle

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5562]
Formules : https://docs.google.com/spreadsheets/d/1Aex-nSMKuat5JlXFeATrdkclTlq83ifgVoXebHoPqGE/edit#gid=0

Ancienneté : https://docs.google.com/spreadsheets/d/1sBBG11yW_1aa-gcQ7SAziPX1n9wEjP1R96dtgdV-oeg/edit#gid=0

Sref : https://docs.google.com/spreadsheets/d/1OgAEJCblTK1Tppx7gUXA3G_Muwv9azfxKZ2sfiBKUyE/edit#gid=0

**Comment by Viczei** [comment]
TODO:
pour la refacto:
- Import des questions manquante -> publicode (gestion des cas sans indemnité)
- Rendre les étapes génériques
- Import des validations de l'ui -> modeles
- Driver l'affichage des composants en fonction des missings var publicode
- Appeler le calcul ancienneté ou salaire directement depuis le modele en fonction des missings var publicode

pour les ruptures conventionnelles:
- gestion des Hors ANI et ANI à formule unique
- gestion des ANI à formule multiple

**Comment by romain-b13** [comment]
@Viczei Sprint 52 : découper en tâches

**Comment by m-maillot** [comment]
## ANI à formules multiples

### 1501

- Non-cadres / Cadres

Majoration si c'est une licenciement économique. 
**Proposition :** Utiliser autres licenciements pour avoir le résultat le moins avantageux.

Plafond: Non
Plancher: Non

### 1996

Seulement les cadres concernés. Il y a une majoration si licenciement économique. 
**Proposition :** Utiliser autres licenciements pour avoir le résultat le moins avantageux.

Plafond: Non
Plancher: Non

### 2216

- Employés et ouvriers, personnel de livraison / Agents de maitrise et techniciens

Majoration si c'est une licenciement économique. 
**Proposition :** Utiliser autres licenciements pour avoir le résultat le moins avantageux.

Plafond: Non
Plancher: Non

- Cadres

Il y a deux formules qu'il faut comparer pour voir si une version est moins favorable qu'une autre : 
```
Autres licenciements : 
(3/10*Sref*A1)+(4/10*Sref*A2)+(5/10*Sref*A3)+ (1/3*Sref*A4)
A1: Années de présence, pour la tranche jusqu'à 10 ans 
A2: Années de présence, pour la tranche de 10 à 20 ans 
A3: Années de présence, pour la tranche au-delà de 20 ans
A4 : Années de présence, pour la tranche au-delà de 40 ans

Licenciement pour motif économique :
(3/10*Sref*A1)+(4/10*Sref*A2)+(5/10*Sref*A3)+(20%*(((3/10*Sref*A1)+(4/10*Sref*A2)+(5/10*Sref*A3)))
A1: Années de présence, pour la tranche jusqu'à 10 ans 
A2: Années de présence, pour la tranche de 10 à 20 ans 
A3: Années de présence, pour la tranche au-delà de 20 ans
```

Après calcul, la moins avantageuse reste la formule pour autres licenciements jusqu'à 55 ans d'ancienneté. A partir de 55 ans d'ancienneté, c'est celle pour motif économique qui devient plus favorable. Est ce un cas qui peut arriver et à gérer ?

Feuille de calcul : https://docs.google.com/spreadsheets/d/1NTnym7myxc4wjGMmPoMKUY6GCRfxE7ZWUQutPbJba7Q/edit?usp=sharing

**Proposition :** Utiliser autres licenciements pour avoir le résultat le moins avantageux.

Plafond: Oui moins avantageux sur les autres licenciements
Plancher: Non

### 1702

Majoration si c'est une licenciement économique. 
**Proposition :** Utiliser autres licenciements pour avoir le résultat le moins avantageux.

Plafond: Non
Plancher: Non

### 675

**Proposition :** Utiliser Licenciements collectifs à la suite de difficultés économiques caractérisées pour avoir le résultat le moins avantageux.

Plafond: Oui mais plus bas dans le cas du Licenciements collectifs à la suite de difficultés économiques caractérisées
Plancher: Non

### 2120

Complexe ne se base pas sur les mêmes Sref. Beaucoup de variables...

### 16

- Ouvrier 

le licenciement pour `Incapacité temporaire à la conduite` semble le plus défavorable à partir de 5 ans d'ancienneté (1*Sref) mais il ne se base pas sur le même calcul du Sref... Il est donc impossible de dire quelle formule est la moins avantageuse pour les ouvriers.

- Autres

Il n'y a qu'un seul type de licenciement pour les autres catégories professionnelles.

###  44

 **Proposition :** Utiliser autres licenciements pour avoir le résultat le moins avantageux.

Plafond: Oui mais identique
Plancher: Non

### 573

Impossible d'identifié car le licenciement économique même si plus avantageux car majoration, base son calcul sur un sref qui peut être différent (pas même calcul pour le sref).

### 3248

Identifié sur le fichier comme ANI avec des types multuples mais pas de types de licenciement multiples sur cette CC.
 
### 1486

Impossible d'indentifié, le salaire de ref n'est pas sur la même base de calcul.

### 2098

Impossible d'indentifié, le salaire de ref n'est pas sur la même base de calcul.

**Comment by m-maillot** [comment]
Liste des CCs demandant un comportement spécifique : 

2120 / 16 / 573 / 1486 / 2098

**Comment by m-maillot** [comment]
2 cas à discuter:

Lorsque le minimum d'ancienneté change entre 2 type de licenciement. Par exemple, on a pour le type A un minimum de 3 ans et le type B un minimum de 2 ans. Dans le cas où il y a 2 ans d'ancienneté, le type B est moins favorable, doit on le prendre ?

**Comment by m-maillot** [comment]
Cas à valider:

Dans le calcul du minimum d'ancienneté pour la CC, on utilise la date de notification. Il faut voir comment gérer le cas de la rupture où il n'y a pas de minimum.
