### ISSUE TITLE
Valider qu'il ne manque pas d'url de contrib en prod

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5583]
Suite à l'incident rencontré le 23/01 l'idée serait de mettre en place un système sur le long terme qui compare le nombre de réponses en statut "publié" et le nombre d'url en prod

**Comment by m-maillot** [comment]
* [x] Ajouter un champ info contenant le nombre de documents exportés (on va indiquer pour chaque type de document)
* [x] Sur l'UI, ajouter une colonne pour afficher cette info + ajouter le delta avec la dernière mise à jour
* [x] Envoyer un message sur mattermost indiquant le démarrage d'une mise à jour de la prod/preprod (avec l'auteur)
* [x] Envoyer un message sur mattermost indiquant la fin de la mise à jour et le nb de document avec le delta (comme sur l'UI)

**Comment by maxgfr** [comment]
~~Je mettrai pas en place le delta sur l'envoi du message à mattermost, car je pense faire la diff côté frontend, ça demande moins de travail~~

**Comment by maxgfr** [comment]
~~Actuellement, nous avons que le `userId` comme élément identifiant l'utilsateur. Est-ce que ça vaut le coup de faire une autre requête à graphql pour avoir le nom de l'utilisateur ?~~

On récupère le user au moment de la création de l'export
