### ISSUE TITLE
Mise en place d'un test cypress pour valider le HTML qui tourne sur la preprod

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#5590]
Mise en place d'une suite de test qui tourne sur la preprod.
A choisir quand :
- après un merge sur dev ?
- après une release ?
- ou toute les nuits ?

A noter, le test cypress footer qui test la page "Statistiques du Code du travail numérique" fail régulièrement à cause de matomo. Nous pourrions aussi bouger ce test dans cette suite

**Comment by maxgfr** [comment]
Lancer automatiquement à la prerelease ou a la mano
