### ISSUE TITLE
[SEO] Mettre en prod le nom de la CC dans le H1 des contrib personnalisées (que pour les CC courtes)

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5592]
Si le nom de la CC fait moins de 15 caractères => on l'ajoute dans le H1 de la contrib personnalisée

**Comment by carolineBda** [comment]
Liste des questions qui font moins de 50 caractères :

order | content | length
-- |-- |-- |
50 | Les congés pour événements familiaux | 36
15 | Embauche en contrat d'extra (CDD d'usage) | 41
55 | Qu’est-ce qu’une rupture conventionnelle ? | 42
52 | Jours fériés et ponts dans le secteur privé | 43
44 | Quelle est la durée du congé de maternité ? | 43
53 | Travail du dimanche : quelle contrepartie ? | 43
38 | Comment déterminer l'ancienneté du salarié ? | 44
12 | Quelle peut être la durée maximale d'un CDD ? | 45
4 | La période d’essai peut-elle être renouvelée ? | 46
19 | Quelles sont les conditions de cumul d'emplois ? | 48

Liste des CC dont le nom court fait moins de 15 caractères

idcc | nom
-- |-- |
2511 | Sport
2609 | Bâtiment ETAM
2120 | Banque
1480 | Journalistes
0292 | Plasturgie
3248 | Métallurgie
