### ISSUE TITLE
Sigles [WIP]

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#56]
Signification | Sigle
-- | --
accident de travail | AT
actions de sociétés d'investissement à capital variable| SICAV
activité principale exercée | APE
Agence nationale pour l'amélioration des conditions de travail | ANACT
aide au chômeur créant ou reprenant une entreprise | ACCRE/ACRE
application de gestion des dossiers des ressortissants étrangers en france | AGDREF
Bâtiment et Travaux Publics | BTP
cancérogènes, mutagènes ou toxiques pour la reproduction | CMR
Centre de Formation des apprentis | CFA
Chiffre d'affaire | CA
Chèque Emploi Service Universel | CESU
Comité Central d'Entreprise | CCE
comité d'entreprise | CE
comité d'hygiène de sécurité et de conditions de travail | CHSCT
Comité français d'accréditation | COFRAC
comité inter-entreprises de santé et de sécurité au travail | CISSCT
Comité social et économique | CSE
Comités régionaux prévention des risques professionnels | CRPRP
Communauté Economique Européenne | CEE
Compte personnel activité | CPA
compte personnel formation | CPF
Congé individuel de formation | CIF
congés payés | CP
Conseil d'administration | CA
Conseil de prud'hommes | CPH
Conseil de prud'hommes | PDH
contrat d'insertion professionnelle | CIP
Contrat de travail temporaire | CTT
contrat de travail à Durée Déterminée | CDD
contrat de travail à Durée Indéterminée | CDI
Contrat unique d'embauche - Contrat d'accompagnement dans l'emploi | CUI-CAE
Contrat unique d'embauche - Contrat Initiative Emploi | CUI - CIE
Contrat unique d'embauche | CUI
Contrôleur du Travail | CT
Convention collective | CC
Coordonnateur Sécurité et Protection de la Santé | CSPS
Coordonnateur Sécurité et Protection de la Santé | CSPS
Courant basse tension de type A | BTA
Courant basse tension de type B | BTB
courant Haute Tension de type A | HTA
courant Haute Tension de type B | HTB
courant Haute Tension | HT
direction de l’animation de la recherche, des études et des statistiques | DARES
directions régionales des entreprises, de la concurrence, de la consommation du travail et de l'emploi | DIRECCTE
document unique d'évaluation des risques professionnels | DUERP
droit individuel de la formation | DIF
Déclaration annuelle des données sociales | DADS
Déclaration préalable à l'embauche | DPAE
Déclaration sociale nominative | DSN
Déclaration unique d'embauche | DUE
Délégation unique du personnel | DUP
Délégué du personnel | DP
Emploi d'avenir | EAV
entreprise travail temporaire | ETT
équipement de protection individuelle | EPI
Etablissement public à Caractère Industriel et commercial | EPIC
Hôtellerie, café et restauration | HCR
indemnités de congés payés | ICP
indemnités journalières de sécurité | IJSS
Inspecteur du Travail | IT
installation classée pour la protection de l'environnement | ICPE
institutions représentatives du personnel | IRP
journal officiel république française | JORF
journal officiel | JO
Licenciement de salariés protégés | LSP
Liquidation judiciaire | LJ
maladie professionnelle | MP
Maître d'ouvrage | MOA
Maître d'œuvre | MOE
microscopie électronique à transmission analytique | META
Mise en demeure | MED
Mouvement des entreprises de France | MEDEF
Médecin du Travail | MT
Médecin Inspecteur du travail | MIT
Nomenclature des activités françaises | NAF
Organisation Internationale du Travail | OIT
Organisme Professionnel de Prévention bâtiment et Travaux Publics | OPPBTP
Plan de Sauvegarde de l'Emploi | PSE
Plan Général de Coordination | PGC
Plan particulier de sécurité et de prévention de la santé | PPSPS
Principes généraux de prévention | PGP
Procès verbal | PV
Rayonnement ultraviolet de type A | UVA
Rayonnement ultraviolet de type B | UVB
Rayonnement ultraviolet de type C | UVC
Redressement judiciaire | RJ
Redressement judiciaire/ Liquidation judiciaire | RJ/LJ
Registre Unique du Personnel | RUP
registre unique du personnel | RUP
représentant de section syndicale | RSS
représentant syndical au comité d'entreprise | RSCE
Rupture conventionnelle de salariés protégés | RCSP
Règlement REACH ) No. 1907/2006 :Enregistrement, évaluation, autorisation et restriction des substances chimiques | REACH
réglementation sociale européenne | RSE
Salaire Minimum Interprofessionnel de Croissance | SMIC
Société coopérative européenne | SCE
Société Nationale des Chemins de fer Français | SNCF
suivi individuel renforcé | SIR
Syndicat Confédération française de l'encadrement - Confédération générale des cadres (CFE-CGC) | CFE
Syndicat Confédération française de l'encadrement - Confédération générale des cadres (CFE-CGC) | CGC
Syndicat Confédération française des travailleurs Chrétiens | CFTC
syndicat Confédération française démocratique du travail | CFDT
Syndicat Confédération Générale du Travail | CGT
Syndicat: Force Ouvrière | FO
Système d'identification du répertoire des ENTREPRISES | SIRET
Système d'identification du répertoire des établissements | SIREN
système d'information des prestations de service internationale | SIPSI
Système d'Inspection du Travail | SIT
Titre Emploi Service Entreprise | TESE
Titre emploi simplifié | TES
travailleurs handicapés | TH
Travaux Publics | TP
Très Basse Tension de Sécurité | TBTS
Très Basse Tension | TBT
Union européenne | UE
Unions de Recouvrement des cotisations de Sécurité Sociale et d’Allocations Familiales | URSSAF
Valeur limite d'exposition | VLE
Validation des acquis de l'expérience | VAE
visite d'information et de prévention | VIP
voyageur, représentant et placier | VRP
vérifications générales périodiques | VGP
Zone de revitalisation rurale | ZRR
Zone touristique internationale | ZTI
Zone touristique | ZT
Zone urbaine sensible | ZUS

**Comment by jrduscher** [comment]
Tenir compte de la structure des sigles X.X.X. XXX X-X-X

**Comment by kemar** [comment]
Je ferme cette issue.

Les synonymes sont pris en compte.

Voir le dépôt de code consacré aux données et à Elasticsearch https://github.com/SocialGouv/code-du-travail-data/blob/master/dataset/synonyms.json
