### ISSUE TITLE
[Indemnité de rupture conventionnelle] Implémenter hors ANI dans le modèle

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5627]
**Ne pas attaquer la partie catégorie pro**

**Les règles métiers :** 

*dans ce schéma IL signifie "indemnité légale"

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/b3aa2df8-d0dd-4adf-be7b-61808a84779d)

**Comment by carolineBda** [comment]
- Voir avec le metier pour l'affichage de résultat
- on ajoute un yml qui renvoi 0 pour la conventionel
