### ISSUE TITLE
[analyse IL 3248] Pb calcul de l'ancienneté + application plancher CC 3248

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5634]
### Analyse 1

Dans la simulation ci-joint on devrait trouver 14 ans d'ancienneté et non 13,92 => comprendre pourquoi on trouve 13,92 car normalement : 

- l'ancienneté totale est de 12ans + 11 mois
- l'ancienneté au forfait jour est de 2 ans + 2 mois
- on doit majorer de 50% l'ancienneté au forfait jour ce qui donne 13 mois supplémentaire (26 mois*0,5)
- ce qui donne en ancienneté totale : 12 ans + 11 mois + 13 mois = 14 ans 

[Pb ancienneté IL 3248.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/14358019/Pb.anciennete.IL.3248.pdf)

### Analyse 2

Il semblerait que pour certains cas nous n'appliquons pas le plancher de 6*Sref alors qu'on devrait l'appliquer

exemple de situation :
- Convention metallurgie
- Catégorie  F
- âge : 57 ans
- pas de licenciement pour "absence prolongée ou absences répétées justifiées perturbant le fonctionnement de l'entreprise""
- debut du contrat 02/01/2013
- fin du contrat 26/02/24

Le résultat donné est inférieur au plancher de 6*Sref

Par contre si on entre une date de début le 02/01/2018 (donc moins d'ancienneté), là on a bien l'application du plancher de 6*Sref.

**Comment by m-maillot** [comment]
Analyse 1 :

On a une erreur dans notre algo. Car on prend l'ancienneté avant le contrat jour (10 ans et 8 mois) et ensuite l'ancienneté après (2 ans et 2 mois). On additionne ensuite les deux, ce qui nous donne 12 ans et 10 mois.
J'ai fait un correctif pour calculer la majoration d'abord (donc 13 mois) et ensuite je les ajoute à l'ancienneté totale (moins les absences).

**Comment by m-maillot** [comment]
Analyse 2 :

On a bien une erreur sur le plancher qui est paramétré à 3 * sref au lieu de 6 * sref. J'ai également fait un correctif.

**Comment by romain-b13** [comment]
> Analyse 2 :
> 
> On a bien une erreur sur le plancher qui est paramétré à 3 * sref au lieu de 6 * sref. J'ai également fait un correctif.

Merci @m-maillot est-ce que tu peux identifier facilement si ce cas est présent ailleurs ?

**Comment by m-maillot** [comment]
Je n'ai pas identifié d'autres cas où le plancher est mal renseigné.
