### ISSUE TITLE
[indemnité de licenciement] Correctifs pour la CC 3248

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5635]
### 1er correctif
Pour ceux qui étaient cadres dans l'ancienne CC de la méta et qui sont devenus non-cadre dans la nouvelle CC il faut majorer uniquement l'ancienneté de la période en tant que "non-cadre" alors qu'actuellement on majore l'ancienneté totale.

Ex : si le salarié est entré dans l'entreprise le 01/01/2018 en tant que cadre et qu'il devenu "non-cadre" le 01/01/2024 suite à l'entrée en vigueur de la nouvelle CC et qu'il quitte l'entreprise le 01/07/2024 alors on majore seulement la période du 01/01/2024 au 01/07/2024.

### 2ème correctif
Lorsque l'utilisateur répond **"oui" à la question "Le salarié est-il en arrêt de travail au moment du licenciement ?"** alors il faut ajouter une notif au niveau du résultat **uniquement pour la CC 3248** qui est : 

"Le montant de l’indemnité de licenciement calculé pour la convention collective de la métallurgie pourrait être différent. En effet, les salaires pris en compte dans cette simulation sont ceux que le salarié a perçu avant l'arrêt de travail. Or, la convention collective indique que la rémunération à retenir est celle que le salarié aurait perçue s'il avait travaillé pendant la période d’absence pour maladie."

**Comment by m-maillot** [comment]
> Pour ceux qui étaient cadres dans l'ancienne CC de la méta et qui sont devenus non-cadre dans la nouvelle CC il faut majorer uniquement l'ancienneté de la période en tant que "non-cadre" alors qu'actuellement on majore l'ancienneté totale.

Il n'y a actuellement aucune majoration sur l'ancienneté s'il était cadre. La seule particularité quand il était cadre, c'est que l'on ne prend pas en compte les absences.

**Comment by m-maillot** [comment]
En fait c'est parce que dans la description du correctif à fait j'ai omis de dire que c'était pour les salariés au forfait jour 

Ex :

il entre le 01/01/2018
il était cadre mais il devient non cadres (suite à la nouvelle CC) depuis le 01/01/2024
il quite l'entreprise le 01/03/2024
il a toujours été au forfait jour (du 01/01/2018 au 01/03/2024)
tu majores seulement la période du 01/01/2024 au 01/03/2024 car la majoration s'applique que pour les non cadres
