### ISSUE TITLE
Comment on remonte nos erreurs

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5638]
- s'assurer d'avoir une alerte quand on a une erreur 500 sur le site (ex : toutes les pages du dossier licenciement qui étaient toutes en erreur 500 sans avoir pu l'identifier)

**Comment by maxgfr** [comment]
Je pense que lancer les tests e2e reliés à mattermost suffient pour atteindre l'objectif de tracker à chaque fois que nos pages en preprod déconnent.

En soit faudrait faire ça aussi sur Sentry, on le maitrise pas assez bien pour remonter intelligement juste ce genre d'erreur. D'autant plus que ça oblige d'aller sur Sentry pour vérifier le problème

**Comment by carolineBda** [comment]
J'ai créé 2 nouvelles alertes dans Sentry (et supprimé celle qu'il y avait qui nous spammait). On va monitorer quelles alertes elles envoient puis on verra pour les brancher sur mattermost

**Comment by m-maillot** [comment]
En regardant sur Sentry, je vois les 2 alertes mais elles ne se sont pas déclenchées.

**Comment by romain-b13** [comment]
**To do sprint 54**
- vérifie si les erreurs 500 remontent dans Sentry
- corriger les erreurs simples/visuelles remontées sur Sentry
