### ISSUE TITLE
Page "A propos" : ajouter contact

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#564]
éventuellement contact dans le footer aussi

**Comment by ClementChapalain** [comment]
je propose de l'ajouter seulement dans le footer pour l'instant ça répond au besoin

**Comment by ClementChapalain** [comment]
![image](https://user-images.githubusercontent.com/5337489/54114787-745ae400-43eb-11e9-9165-a8743c9b21f4.png)
le lien `contact` renvoie vers `mailto:contact@code-du-travail.beta.gouv.fr`
