### ISSUE TITLE
[Indemnité licenciement] Modifier le message lors de la sélection de la CC 1480

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5663]
Cette CC fait bien partie des CC traitées sur le CDTN mais elle ne sera jamais développée dans le simulateur de l'indemnité de licenciement, il faut donc mettre le même message que pour les CC qu'on ne traite pas.

Msg actuel : 

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/4c587dc7-0ec5-489d-8369-40dc213c4b69)

**Comment by m-maillot** [comment]
Gérer directement dans le front fichier. `getSupportedCc`

Et supprimer la liste INDEMNITE_LICENCIEMENT_PRODUCTION_READY_CC en validant en amont que l'on a pas de CC en plus dans le json.
