### ISSUE TITLE
Correctifs préavis licenciement CC 176

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5669]
### Outil préavis de licenciement

**1) Situation 1**
- contrat à partir du 1er juillet 2009
- groupes 6 et suivants 
- action à faire : supprimer ce qu'il y a entre parenthèses au niveau du résultat

**2) Situation 2**
- contrat avant le 1er juillet 2009
- groupes 1 à 3
- actions à faire : 
   - supprimer la question sur l'ancienneté
   - modifier le résultat => 2 mois
   
  
**3) Remplacer l'article 32.2 par 35.2** 
=> https://www.legifrance.gouv.fr/conv_coll/article/KALIARTI000039117109?idConteneur=KALICONT000005635184&origin=list#KALIARTI000039117109

**Comment by maxgfr** [comment]
Pour info, il y a toujours entre paranthèse : 

```json
{
      "criteria": {
        "conclusion contrat travail": "2| Contrat de travail conclu après le 1er juillet 2009",
        "groupe": "28| 4 à 6 "
      },
      "type": "préavis de Licenciement",
      "idcc": 176,
      "typeRupture": null,
      "answer": "3 mois (si les salariés ne bénéficient pas des dispositions de l'article 4 de la convention collective nationale de retraite et de prévoyance des cadres du 14/3/1947)",
      "answer2": null,
      "answer3": "90",
      "ref": "Article 32, 2°",
      "refUrl": "https://www.legifrance.gouv.fr/affichIDCCArticle.do;jsessionid=D95886BC7232B7E17E29C15F66690F00.tplgfr24s_2?idArticle=KALIARTI000022189662&cidTexte=KALITEXT000005682476&dateTexte=29990101&categorieLien=id"
    },
```
