### ISSUE TITLE
Modifier le message affiché dans les outils et contrib quand on sélectionne une entrprise qui n'a pas de CC associée

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5674]
### Description du problème
Lorsque l'utilisateur sélectionne une entreprise qui n'a pas de CC (ou une idcc en 9999) dans un outil ou une contrib le message suivant est affiché : 

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/cd851307-c29a-466c-829e-6fec4dda2432)

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/076a034b-5924-4330-bc9e-7b9bb828d24b)

Je pense que ce comportement existe seulement depuis que nous avons permis de trouver les entreprises qui étaient rattachées à un idcc 9999 car avant ces entreprises n'étaient pas trouvables dans la recherche

### Action

**Pour 38 contrib (cas classique)**

Dans ces cas là il faudrait faire apparaître un encadré :

Titre : Aucune convention collective n'a été déclarée pour cette entreprise
Message dans l'encadré : Vous pouvez tout de même poursuivre pour obtenir les informations générales

Et afficher le bouton "Afficher les informations générales"

**Pour les 4 contrib qui n'ont pas de réponse géénrique (le code du travail ne prévoit rien)**

Remplacer la phrase "0 conventions collectives ont été trouvées pour cette entreprise, sélectionnez la vôtre" par un message en rouge  : 

Aucune convention collective n'a été déclarée pour l'entreprise « STEF TRANSPORT ». Rapprochez vous ...

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/21fd22cc-eb0b-4570-b4a4-4a199a75b70c)

**Comment by maxgfr** [comment]
Voici le résultat :

Avec le SIREN 722 003 936 (mc do france),

1) Pour les simulateurs, j'ai ce message partout. Malgré ce message, l'utilisateur peut continuer la simulation, comme s'il n'avait pas selectionné d'entreprise. 
![Screenshot 2024-03-08 at 20 11 28](https://github.com/SocialGouv/code-du-travail-numerique/assets/25312957/ceb74ef9-ac09-43e3-80f8-1c1289ebcc8c)

2) Pour les contributions qui ont une générique
![Screenshot 2024-03-08 at 20 07 18](https://github.com/SocialGouv/code-du-travail-numerique/assets/25312957/572b366a-2da7-4ca0-89a7-a7c37c9fed8d)

3) Pour les contributions qui n'ont pas de générique
![Screenshot 2024-03-08 at 20 07 08](https://github.com/SocialGouv/code-du-travail-numerique/assets/25312957/2476a65a-1548-44a3-8d70-d1e40a067902)


J'ai deux retours : 
- Peut-être que ça serait pas mal sur les simulateurs de dire à l'utilisateur qu'il peut continuer dans le message ?
- Est-ce que ça serait pas mal d'harmoniser (titre + message) sur les alerts côtés contributions ?
