### ISSUE TITLE
Utiliser le slug des documents comme id elasticsearch

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#568]
et mettre à jour le spreadsheet des tests unitaires

**Comment by revolunet** [comment]
Dans #549, lors du parsing des fiches SP/MT, je pensais lier à des ID ElasticSearch pour les références de types "article du code" et "convention collective". du coup ça voudrait dire avoir des id prédictibles pour ces deux cas. normalisation ?

 - `cdt-[NUM]` ou `NUM` serait un truc style `L2243-1` tel que fourni dans LEGI
 - `ccn-[IDCC]` ou `IDCC` est l'id unique de la CC dans KALI

Avec ça, lorsqu'on ouvre une fiche SP/MT dans l'UI, on pourrait remonter en liens internes vers articles/CCNs concernés

**Comment by ClementChapalain** [comment]
toujours d'actualité ?

**Comment by revolunet** [comment]
a priori non. question a reexplorer quand on fera un point sur la MAJ des datas (asap) :)

**Comment by ClementChapalain** [comment]
ok je te laisse fermer si tu veux :)
