### ISSUE TITLE
[Indemnité de rupture conventionnelle] Implémenter les cas ANI avec plusieurs types de rupture

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#5692]
Il y a les cas de rupture où l'on doit calculer quand il y a plusieurs type de licenciement.
Il faut donc implémenter la logique qui liste les types de rupture dans le modèle.

Voici la liste des CCs identifiées :

- [x] 1501 @maxgfr
- [x] 1996 @maxgfr
- [x] 2216 @carolineBda 
- [x] 1702 @carolineBda 
- [x] 2120 @carolineBda 
- [x] 16 @m-maillot 
- [x] 44 @maxgfr 
- [x] 573 @m-maillot
- [x] 3248 @m-maillot
- [x] 1486 @maxgfr
- [x] 2098 @maxgfr
- [x] 675 @Viczei

A valider avec Perrine les cas où l'on a un type de rupture assez spécifique comme sur la 2120 ou encore la 16 où l'on a des types de licenciement assez particulier (perte du permis, justice...)

**Comment by m-maillot** [comment]
**1501**
Non-cadres / Cadres
Majoration si c'est une licenciement économique.
Proposition : Utiliser autres licenciements pour avoir le résultat le moins avantageux.

Plafond: Non
Plancher: Non

**1996**
Seulement les cadres concernés. Il y a une majoration si licenciement économique.
Proposition : Utiliser autres licenciements pour avoir le résultat le moins avantageux.

Plafond: Non
Plancher: Non

**2216**
Employés et ouvriers, personnel de livraison / Agents de maitrise et techniciens
Majoration si c'est une licenciement économique.
Proposition : Utiliser autres licenciements pour avoir le résultat le moins avantageux.

Plafond: Non
Plancher: Non

Cadres
Il y a deux formules qu'il faut comparer pour voir si une version est moins favorable qu'une autre :

Autres licenciements : 
(3/10*Sref*A1)+(4/10*Sref*A2)+(5/10*Sref*A3)+ (1/3*Sref*A4)
A1: Années de présence, pour la tranche jusqu'à 10 ans 
A2: Années de présence, pour la tranche de 10 à 20 ans 
A3: Années de présence, pour la tranche au-delà de 20 ans
A4 : Années de présence, pour la tranche au-delà de 40 ans

Licenciement pour motif économique :
(3/10*Sref*A1)+(4/10*Sref*A2)+(5/10*Sref*A3)+(20%*(((3/10*Sref*A1)+(4/10*Sref*A2)+(5/10*Sref*A3)))
A1: Années de présence, pour la tranche jusqu'à 10 ans 
A2: Années de présence, pour la tranche de 10 à 20 ans 
A3: Années de présence, pour la tranche au-delà de 20 ans
Après calcul, la moins avantageuse reste la formule pour autres licenciements jusqu'à 55 ans d'ancienneté. A partir de 55 ans d'ancienneté, c'est celle pour motif économique qui devient plus favorable. Est ce un cas qui peut arriver et à gérer ?

Feuille de calcul : https://docs.google.com/spreadsheets/d/1NTnym7myxc4wjGMmPoMKUY6GCRfxE7ZWUQutPbJba7Q/edit?usp=sharing

Proposition : calculer chaque possibilité

Plafond: Oui moins avantageux sur les autres licenciements
Plancher: Non

**1702**
Majoration si c'est une licenciement économique.
Proposition : Utiliser autres licenciements pour avoir le résultat le moins avantageux.

Plafond: Non
Plancher: Non

**675**
Proposition : Utiliser Licenciements collectifs à la suite de difficultés économiques caractérisées pour avoir le résultat le moins avantageux.

Plafond: Oui mais plus bas dans le cas du Licenciements collectifs à la suite de difficultés économiques caractérisées
Plancher: Non

**2120**
Complexe ne se base pas sur les mêmes Sref. Beaucoup de variables...

Types spéciales

**16**
Ouvrier
le licenciement pour Incapacité temporaire à la conduite semble le plus défavorable à partir de 5 ans d'ancienneté (1*Sref) mais il ne se base pas sur le même calcul du Sref... Il est donc impossible de dire quelle formule est la moins avantageuse pour les ouvriers.

Types spéciales (Incapacité temporaire à la conduite)

Autres
Il n'y a qu'un seul type de licenciement pour les autres catégories professionnelles.

**44**
Proposition : Utiliser autres licenciements pour avoir le résultat le moins avantageux.

Plafond: Oui mais identique
Plancher: Non

**573**
Impossible d'identifié car le licenciement économique même si plus avantageux car majoration, base son calcul sur un sref qui peut être différent (pas même calcul pour le sref).

**3248**
Identifié sur le fichier comme ANI avec des types multiples mais pas de types de licenciement multiples sur cette CC.

**1486**
Impossible d'indentifié, le salaire de ref n'est pas sur la même base de calcul.

Type spécial : Licenciement en raison d'un refus de respecter une clause de mobilité 

**2098**
Impossible d'indentifié, le salaire de ref n'est pas sur la même base de calcul.

Type spécial : Licenciement pour inaptitude totale et définitive non consécutive à un accident du travail

**Comment by carolineBda** [comment]
Juste le fichier enum avec les types de licenciement + tests
