### ISSUE TITLE
[Indemnité rupture conventionnelle] Gestion des minimums d'ancienneté requise conventionnelle

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#5695]
Dans le cas où il y a plusieurs types de rupture, on peut avoir un minimum d'ancienneté différent. 

Par exemple dans la CC 44, on a : 

 * Autres licenciements -> Ouvriers et collaborateurs (Groupes I à III) -> >= 2 ans d'ancienneté
 * Licenciements pour raisons économiques -> Ouvriers et collaborateurs (Groupes I à III) -> >= 1 an d'ancienneté et < 2 ans d'ancienneté

Dans ce cas là, si l'employé à 1,5 ans d'ancienneté. On va avoir le premier calcul qui va nous retourner 0 et le second un montant. Comme on doit prendre le moins avantageux, cela signifie que l'on doit prendre 0 ici ?

**Comment by m-maillot** [comment]
On écarte ceux qui n'ont pas les conditions requises.

**Comment by carolineBda** [comment]
A revalider avec le métier

**Comment by m-maillot** [comment]
Relance métier faite sur mattermost https://mattermost.fabrique.social.gouv.fr/default/pl/xjkrjgpmninh3q5mstf3epwjsh

**Comment by m-maillot** [comment]
Réponse du métier : 

> Dans ce cas précis on ne va calculer que la formule de licenciement qui s'applique à la situation de la personne, c'est à dire le licenciement pour motif éco. Dans mes tableaux je mets 0€ mais c'est plus "non applicable"
