### ISSUE TITLE
Supprimer les 404 internes du plan du site

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5697]
Cf les 4 pages en erreur interne en mars : https://docs.google.com/spreadsheets/d/1UD5PaFRQ0SGVzxeL0xz_ASou0l8M2Gnn/edit#gid=1847021439

**Comment by m-maillot** [comment]
duplicat de l'issue : https://github.com/SocialGouv/code-du-travail-numerique/issues/5739
