### ISSUE TITLE
gestion des données

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#570]
Aujourd'hui les contenus utilisés par ElasticSearch (ES) sont versionnés dans le monorepo.

voici la liste des contenus et comment on génère les fichiers json qui sont ensuite indexer dans ES.

|Source |  remarque |
|------|----------|
| kali   |          son généré depuis la liste des CCN legifrance,  externalisation prochaine (base KALI) |
| idcc + tags|  probablement plus utilisé   |   
| code du travail | ajout des tag e-poseidon via un script python,  externalisation prochaine (base LEGI) |
| fiches ministère | scrap de https://travail-emploi.gouv.fr puis transfo en json. Un script python  reformule le titre |
| fiches service-public | les données proviennent de datagouv, un script python enrichit des tags |  
| themes |     liste à compléter |  
| faq-* |       externalisation prochaine via l'outil de contribution |  
| outils-* |       externalisation possible via l'outil de contribution |  
| courriers |    externalisation probable via l'outil de contribution |  
| annuaire |   données provenant de datagouv |  

L'avantage d'avoir ces données en json, permet une indexation / re-indexation rapide par ES car on la creation du jeu de donnée est dissocier de leur indexation. Par contre, cela pose des problèmes de poids sur le dépôt de code.
 

solutions: 
- avoir un script qui recrée les jeux de donnée prêt à être indexer par ES et stocke le résultat sur datagouv
- avoir un script qui nourrit ES avec les données datagouv

**Comment by lionelB** [comment]
poke @douglasduteil @adipasquale  @UnbearableBear @revolunet @ivangabriele

**Comment by UnbearableBear** [comment]
Je suis plus partant pour la solution "all inclusive" (j'ai des gouts de luxe), tu lances une commande et tout est fait, donc le fetch des données sur datagouv. J'aime bien quand l'ordi fait tout lui même !

**Comment by UnbearableBear** [comment]
Par contre dans très peu de temps le script python ne fera plus rien à par indexer dans ES concernant les fiches du service publique

**Comment by lionelB** [comment]
> Je suis plus partant pour la solution "all inclusive" (j'ai des gouts de luxe), tu lances une commande et tout est fait, donc le fetch des données sur datagouv. J'aime bien quand l'ordi fait tout lui même !

l'un n'empêche pas l'autre, on peut avoir un alias qui lance les 2 l'une à la suite de l'autre mais il faut garder en tete qu'un script qui fait la transfo de ~500 fiches xml en json + scrap de ~200 fiche + un export de la base LEGI + un export de kali + un export des contrib risque de prendre du temps 

d'ou l'idée d'avoir un endroit avec les données prête à l'indexation. 

On pourrait aussi imaginer une image docker avec un volume qui contient les données ?

**Comment by revolunet** [comment]
Je suis en phase avec @lionel sur "avoir un endroit avec les données prêtes à l'indexation." et une "re-indexation rapide par ES "

Je rajoute quelques idées à discuter :

Idéalement il faudrait qu'on puisse avoir un historique des données utilisées, et la possibilité de régénérer l'index à n'importe quelle date rapidement. 

Cela voudrait dire avoir dans GIT les fichiers JSON statiques générés par nos scripts de fetch, etc... 

Une commande docker pourrait permettre d'extraire directement un dump ES des indexes nécessaires ?

Pour le sujet de dumper sur "datagouv", ça pourrait se faire, mais dans un 2eme temps imho, il y a un sujet "legal" & maintenance.

**Comment by revolunet** [comment]
petite maj :
 - doc des données utilisées ici : https://github.com/SocialGouv/code-du-travail-numerique/tree/master/packages/code-du-travail-data/
 - un dump en JSON est produit dans la CI

**Comment by revolunet** [comment]
on peut close ?
