### ISSUE TITLE
Error message in server log "Cannot vectorize empty query."

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#5707]
Ce message apparait tout le temps dans les logs server => "Cannot vectorize empty query."
il ne faudrait pas appeler la fonction `vectorizeQuery` si la query est empty

**Comment by m-maillot** [comment]
Je ne vois pas où on l'appelle avec une query à null... normalement c'est protégé depuis le front pour la recherche et dans le cas des covisit on utilise le titre du contenu qui ne peut être vide 🤔
