### ISSUE TITLE
Texte application pour les CC non étendue

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#5736]
**Contexte**

Pour certaines questions Bérengère "désactive" le bloc texte applicable "auto" au niveau de la question car ce sont des questions spécifiques où elle entre à la main des textes applicables différents dans les différents accordéons de la réponse

**Problème**

Du coup quand on sélectionne une des 3 CC non étendues, il n'y a plus le message spécifique "auto" qui s'affiche en bas pour dire qu'on donne la rép du code du travail car les dispositions de la CC ne sont pas étendues

**Besoin**

Même si aucun texte applicable n'est défini au niveau de la question, le texte applicable spécifique des 3 CC non  étendue doit être affiché comme d'habitude

Cas: 
Question 11 / CC 29 (ou autre CC non étendu)
https://code-du-travail-numerique-preprod.ovh.fabrique.social.gouv.fr/contribution/29-combien-de-fois-le-contrat-de-travail-peut-il-etre-renouvele

**Comment by carolineBda** [comment]
On attends le prochain déploiement de l'admin pour valider le fix

**Comment by carolineBda** [comment]
C'est bon c'est validé ✅
