### ISSUE TITLE
outil externe egapro non dispo

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#5743]
L'outil externe egapro n'est plus disponible sur le site :

https://code.travail.gouv.fr/outils/external/index-egapro?q=egapro

**Comment by maxgfr** [comment]
En fait, il faut pas afficher cette URL dans le sitemap et dans le plan du site, car les outils externes sont des liens vers du contenu externe

**Comment by maxgfr** [comment]
Je confirme que l'url n'est ni présente dans le sitemap ni dans le plan du site

Ensuite, au niveau de la recherche,

En prod : https://code.travail.gouv.fr/recherche?q=egapro => tout est ok
En preprod : https://code-du-travail-numerique-preprod.ovh.fabrique.social.gouv.fr/recherche?q=egapro => y'a un soucis 😅

**Comment by maxgfr** [comment]
En loggant sur l'api de preprod, nous avons ça : 

```js
 {
       id: '84377d4a-7c1b-421b-a9be-efadead39e12',
       cdtnId: '2f4766c545',
       slug: 'index-egapro',
       title: 'Index Egapro',
       source: 'external',
       description: 'L’outil de calcul de votre index égalité professionnelle femmes-hommes',
       breadcrumbs: [],
       url: '',
       algo: 'pre-qualified'
     },
```

Aucune url n'est disponible.

Sur la production, dans la base de donnée, nous avons cela : 

![Screenshot 2024-04-03 at 14 15 37](https://github.com/SocialGouv/code-du-travail-numerique/assets/25312957/c3e5316c-8965-4e27-a21e-225ba4d46acd)

**Comment by maxgfr** [comment]
Récemment, nous avons mis à jour les préqualifiés, ce qui me semble être fortement lié
