### ISSUE TITLE
Liste des IDCC DARES-DGT : impact de la MAJ d'avril 2024 + regression

### ISSUE THREAD

**Issue by CaptainConan** [SocialGouv/code-du-travail-numerique#5757]
Dans la liste des IDCC d’avril, pas mal de mises à jour d’IDCC qui vont nécessiter des redirections et modifications de l'outil rechercher sa CC. 
[dares_donnes_identifiant_convention_collective_avril24.xlsx](https://github.com/SocialGouv/code-du-travail-numerique/files/14902956/dares_donnes_identifiant_convention_collective_avril24.xlsx)

Voici la liste des modifications  : 

- L’IDCC 172 est supprimé et est remplacé par l’IDCC 158
Cette page [Convention collective Industrie du bois de pin maritime en forêt de Gascogne - Code du travail numérique](https://code.travail.gouv.fr/convention-collective/172-industrie-du-bois-de-pin-maritime-en-foret-de-gascogne) doit renvoyer sur cette page : [Convention collective Travail mécanique du bois, des scieries, du négoce et de l'importation des bois - Code du travail numérique](https://code.travail.gouv.fr/convention-collective/158-travail-mecanique-du-bois-des-scieries-du-negoce-et-de-limportation-des-b)
Recherche de CC via l'entreprise : remplacer le résultat 172 par 158 pour les entreprises qui ont toujours la CC 172 en résutat dans siret2idcc
=> aucune entreprise ne devra avoir en résultat la CC 172, si on identifie cette CC on la remplace par la CC 158 dans les résultats

- L’IDCC 207 est supprimé et est remplacé par l’IDCC 2528
Cette page [Convention collective Industrie des cuirs et peaux - Code du travail numérique](https://code.travail.gouv.fr/convention-collective/207-industrie-des-cuirs-et-peaux) doit renvoyer sur cette page [Convention collective Maroquinerie, articles de voyage, chasse sellerie, gainerie, bracelets en cuir : industries - Code du travail numérique](https://code.travail.gouv.fr/convention-collective/2528-maroquinerie-articles-de-voyage-chasse-sellerie-gainerie-bracelets-en-c)
Recherche de CC via l'entreprise : remplacer le résultat 207 par 2528 pour les entreprises qui ont toujours la CC 207 en résutat dans siret2idcc
=> aucune entreprise ne devra avoir en résultat la CC 207, si on identifie cette CC on la remplace par la CC 2528 dans les résultats

- L’IDCC 673 est supprimé et est remplacé par l’IDCC 303
Cette page [Convention collective Fourrure - Code du travail numérique](https://code.travail.gouv.fr/convention-collective/673-fourrure) doit renvoyer sur cette page [Convention collective Couture parisienne - Code du travail numérique](https://code.travail.gouv.fr/convention-collective/303-couture-parisienne)
Recherche de CC via l'entreprise : remplacer le résultat 673 par 303 pour les entreprises qui ont toujours la CC 673 en résutat dans siret2idcc
=> aucune entreprise ne devra avoir en résultat la CC 673, si on identifie cette CC on la remplace par la CC 303 dans les résultats

- L’IDCC 715 est supprimé et est remplacé par l’IDCC 489
Cette page [Convention collective Instruments à écrire et industries connexes - Code du travail numérique](https://code.travail.gouv.fr/convention-collective/715-instruments-a-ecrire-et-industries-connexes) doit renvoyer sur cette page [Convention collective Industries du cartonnage - Code du travail numérique](https://code.travail.gouv.fr/convention-collective/489-industries-du-cartonnage)
Recherche de CC via l'entreprise : remplacer le résultat 715 par 489 pour les entreprises qui ont toujours la CC 489 en résutat dans siret2idcc
=> aucune entreprise ne devra avoir en résultat la CC 715, si on identifie cette CC on la remplace par la CC 489 dans les résultats

- L’IDCC 1001 est supprimé et est remplacé par l’IDCC 413
Cette page doit renvoyer sur cette page [Convention collective Handicapés : établissements et services pour les personnes inadaptées et handicapées - Code du travail numérique](https://code.travail.gouv.fr/convention-collective/1001-handicapes-etablissements-et-services-pour-les-personnes-inadaptees-et-ha) doit renvoyer sur cette page [Convention collective Handicapés : établissements et services pour les personnes inadaptées et handicapées - Code du travail numérique](https://code.travail.gouv.fr/convention-collective/413-handicapes-etablissements-et-services-pour-les-personnes-inadaptees-et-han)
Recherche de CC via l'entreprise : remplacer le résultat 1001 par 413 pour les entreprises qui ont toujours la CC 413 en résutat dans siret2idcc
=> aucune entreprise ne devra avoir en résultat la CC 1001, si on identifie cette CC on la remplace par la CC 413 dans les résultats

- L’IDCC 1618 est supprimé et est remplacé par l’IDCC 1557
Cette page [Convention collective Camping (industries) - Code du travail numérique](https://code.travail.gouv.fr/convention-collective/1618-camping-industries) doit renvoyer sur cette page [Convention collective Commerce des articles de sport et équipements de loisirs - Code du travail numérique](https://code.travail.gouv.fr/convention-collective/1557-commerce-des-articles-de-sport-et-equipements-de-loisirs)
Recherche de CC via l'entreprise : remplacer le résultat 1618 par 1557 pour les entreprises qui ont toujours la CC 1618 en résutat dans siret2idcc
=> aucune entreprise ne devra avoir en résultat la CC 1618, si on identifie cette CC on la remplace par la CC 1557 dans les résultats

- L’IDCC 1942 est supprimé et est remplacé par l’IDCC 18
Cette page [Convention collective Textiles artificiels et synthétiques et produits assimilés - Code du travail numérique](https://code.travail.gouv.fr/convention-collective/1942-textiles-artificiels-et-synthetiques-et-produits-assimiles) doit renvoyer sur cette page [Convention collective Industrie textile - Code du travail numérique](https://code.travail.gouv.fr/convention-collective/18-industrie-textile)
Recherche de CC via l'entreprise : remplacer le résultat 1942 par 18 pour les entreprises qui ont toujours la CC en résutat dans siret2idcc
=> aucune entreprise ne devra avoir en résultat la CC 1942 , si on identifie cette CC on la remplace par la CC 18 dans les résultats

- L’IDCC 3160 est supprimé et est remplacé par l’IDCC 787
Cette page [Convention collective Associations de gestion et de comptabilité - Code du travail numérique](https://code.travail.gouv.fr/convention-collective/3160-associations-de-gestion-et-de-comptabilite) doit renvoyer sur cette page [Convention collective Personnel des cabinets d'experts-comptables et de commissaires aux comptes - Code du travail numérique](https://code.travail.gouv.fr/convention-collective/787-personnel-des-cabinets-dexperts-comptables-et-de-commissaires-aux-comptes)
Recherche de CC via l'entreprise : remplacer le résultat 3160 par 787 pour les entreprises qui ont toujours la CC 787 en résutat dans siret2idcc
=> aucune entreprise ne devra avoir en résultat la CC 3160, si on identifie cette CC on la remplace par la CC 787 dans les résultats

- L’IDCC 418 est supprimé et est remplacé par l’IDCC 303
Pas de redirection car l’IDCC 418 n’a de page dédiée.
Recherche de CC via l'entreprise : remplacer le résultat 418 par 303 pour les entreprises qui ont toujours la CC 303 en résutat dans siret2idcc
=> aucune entreprise ne devra avoir en résultat la CC 418, si on identifie cette CC on la remplace par la CC 303 dans les résultats

- L’IDCC 780 est supprimé et est remplacé par l’IDCC 303
Pas de redirection car l’IDCC 780 n’a de page dédiée.
Recherche de CC via l'entreprise : remplacer le résultat 780 par 303 pour les entreprises qui ont toujours la CC 303 en résutat dans siret2idcc
=> aucune entreprise ne devra avoir en résultat la CC 780, si on identifie cette CC on la remplace par la CC 303 dans les résultats

**Comment by CaptainConan** [comment]
Autre sujet : dans l’alerting, pas mal d’IDCC désactivés sont remontés dont 13 vont nécessiter des redirections. CC @maxgfr 
Voici la liste des modifications :

| IDCC supprimés  | IDCC de redirection  |
| ------------ | ------------ |
|1237   | 787 |
|1710   |  3245 |
|  1492 |  3238 |
|  2411 |  3241 |
| 1761  |573   |
| 1974  |3229   |
|  412 |  3245 |
|1495   |  3238 |
| 700  |  3238 |
|1423   | 3236  |
| 2174  | 3229  |
|707   |  3238 |
| 1624 |573   |

**Comment by maxgfr** [comment]
⚠️ Une redirection n'a pas été prise en compte  : 

| IDCC supprimés  | IDCC de redirection  |
| ------------ | ------------ |
|1237   | 2316  |
