### ISSUE TITLE
[indemnité de rupture conventionnelle] définir le message ineligibilité à afficher dans le front

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#5766]
On a deux cas où il ne peut y avoir de rupture co : 

- 3239 => les assistants maternels
~~- 1404 => CDI d'opérations~~

Message à afficher dans ce cas sur la page de résultat

![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/4971715/bca95edc-e7d6-4350-ada4-0f786bff484a)

**Comment by m-maillot** [comment]
On met directement dans la phrase en rouge en reformulant la phrase. En attente de la reformulation des textes.

**Comment by carolineBda** [comment]
- 1404 => on ne pose pas la question du CDI d'opération (on met non tout le temps)

**Comment by carolineBda** [comment]
3 cartes corresopndantes :
- [indemnité de rupture conventionnelle] message d'inégibilité en cas de CDD
[#5788](https://github.com/SocialGouv/code-du-travail-numerique/issues/5788)
- [indemnité de rupture conventionnelle] message d'inégibilité pour les assistantes maternelles (3239)
[#5789](https://github.com/SocialGouv/code-du-travail-numerique/issues/5789)
- [indemnité de rupture conventionnelle] exclure les CDI d'opérations de la simulation pour la 1404
[#5790](https://github.com/SocialGouv/code-du-travail-numerique/issues/5790)
