### ISSUE TITLE
améliorer l'affichage des résultats FAQ: indiquer les tags

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#577]
Problème illustré ici:
 https://codedutravail-dev.num.social.gouv.fr/question/quelle-est-la-duree-maximale-de-la-periode-dessai?q=dur%C3%A9e%20maximale%20de%20la%20p%C3%A9riode%20d%27essai%20&search=0
Les indications figurant seules dans le corps du texte ne suffisent pas à répondre à l'usager.
La FAQ en exemple contient des éléments taggués:

 {
    "question": "Quelle est la durée maximale de la période d'essai ?",
    "reponse": "La durée de la période d'essai est de trois mois. Celle-ci peut êre renouvelée une fois, soit une durée maximale totale de six mois.",
    "tags": {
      "themes": ["3710"],
      "theme": ["Embauche", "Période d'essai", "Contrat de travail"],
      "categorie": "Cadres",
      "coefficient": ["niveau IV"],
      "branche": "HCR",
      "profil": ["employeur", "salarié"],
      "type_contrat": "CDI"
    },

Parmi ces éléments il faudrait afficher:
- la branche, le type de contrat et ici la catégorie et le niveau, 
- la branche : afficher la dénomination comme ici, à terme prévoir l'affiache de l'intitulé via l'inscriptin de l'idcc
- afficher le type de contrat comme tel,
afficher les catgories et coefficient , comme suit catégorie: Cadres, coefficient : niveau IV ( nom du tag+ tag)

m

**Comment by revolunet** [comment]
plus de faq :)
