### ISSUE TITLE
[Indemnité rupture conventionnelle] Test UI

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#5783]
- [ ] Tester les CC ANI avec plusieurs types de ruptures (juste 1 cas par CC)
- [ ] Tester une CC classique
- [ ] vérifier qu'il y a bien un test hors ANI
- [ ] Tester 3239
- [ ] Tester 1404

**Comment by m-maillot** [comment]
Bien valider le cas présent : https://github.com/SocialGouv/code-du-travail-numerique/blob/e4b168480a1bcb678a87e0542db8d0891ba5cfaf/packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/agreements/2120-banques/Component.tsx#L33 sur la 2120
