### ISSUE TITLE
[indemnité de rupture conventionnelle] message d'inégibilité en cas de CDD

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#5788]
Sur la page résultat:

**La rupture conventionnelle ne concerne pas les salariés en CDD ou en contrat d'intérim.** _(en rouge)_

Il n'y a donc pas d'indemnité de rupture conventionnelle dans cette situation. Sous certaines conditions, le salarié peut avoir le droit à une [indemnité de précarité](https://code.travail.gouv.fr/outils/indemnite-precarite).

**Comment by m-maillot** [comment]
Le wording n'est pas bon. 
On a : 
> La rupture conventionnelle ne concerne pas les salariés en CDD ou en contrat de travail temporaire. Sous certaines conditions, le salarié peut avoir le droit à une [indemnité de précarité](https://code-du-travail-numerique-preprod.ovh.fabrique.social.gouv.fr/outils/indemnite-precarite).

et on attend : 

> La rupture conventionnelle ne concerne pas les salariés en CDD  ou en contrat d'intérim. Sous certaines conditions, le salarié peut avoir le droit à une [indemnité de précarité](https://code-du-travail-numerique-preprod.ovh.fabrique.social.gouv.fr/outils/indemnite-precarite).
