### ISSUE TITLE
[indemnité de rupture conventionnelle] 3248 : on ne gère pas la 650

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#5796]
Pour la 3248, à l'étape information, on ne doit pas poser la question "Le salarié était-il cadre dans l'ancienne convention collective de la métallurgie (avant le 01/01/2024)" et faire comme si l'utilisateur avait répondu non

⚠ @m-maillot a déjà commencé une branch il faut partir de celle-ci

**Comment by m-maillot** [comment]
Il n'y a pas de fallback sur la 650 pour finir. Par contre, on affiche ce message si c'est un licenciement avant le 01/01/2024 :


> (2) Attention, comme le licenciement a été notifié avant le 01/01/2024, le montant de l'indemnité peut ne pas correspondre au résultat donné. En effet, jusqu'au 31/12/2023 ce sont les conventions locales de la métallurgie ainsi que la convention spécifique aux ingénieurs et cadres de la métallurgie (IDCC 650) qui s’appliquaient. Toutes ces conventions ont disparu au profit d’une nouvelle convention collective nationale applicable depuis le 01/01/2024. Si le licenciement a été notifié avant le 01/01/2024 et que le salarié dépendait de la convention spécifique aux ingénieurs et cadres de la métallurgie (IDCC 650) il faut sélectionner cette convention collective à l'étape n°3 du simulateur pour obtenir le résultat correspondant.

**Comment by m-maillot** [comment]
Par contre, il y a cette question : 

> Le salarié est licencié pour le motif suivant : "absence prolongée ou absences répétées justifiées perturbant le fonctionnement de l'entreprise"

Dans le Excel, il est noté que l'on ne traite pas ce cas pour la RC.

**Comment by m-maillot** [comment]
Il reste la notification à gérer.
![CleanShot 2024-05-02 at 16 36 10@2x](https://github.com/SocialGouv/code-du-travail-numerique/assets/992514/026412e7-23ee-40ef-84ac-aba27828bc0a)

**Comment by m-maillot** [comment]
On supprime la notification (numéro 2) dans le cas de rupture conventionnelle.

**Comment by carolineBda** [comment]
Je comprends pas comment cette notification peut apparaitre alors qu'on a pas de date de notif dans la RC ? On la set à la date du jour non ?
