### ISSUE TITLE
Comprendre pourquoi cette contrib n'est pas visible en prod alors qu'elle est publiée

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#5807]
https://code.travail.gouv.fr/contribution/3248-jours-feries-et-ponts-dans-le-secteur-prive

https://mattermost.fabrique.social.gouv.fr/default/pl/xtsq8pysmidr3fzpayw83pzenr

QUERY pour récupérer les contribs concernées 
```
SELECT DISTINCT a.*
FROM contribution.answers a
JOIN contribution.answer_statuses AS status
ON a.id = status.answer_id
WHERE status.status = 'PUBLISHED'
and a.content_type != 'UNKNOWN'
AND NOT EXISTS (
    SELECT 1
    FROM public.documents d
    WHERE d.initial_id = CAST(a.id AS TEXT)
)
;
```

**Comment by m-maillot** [comment]
Après mise à jour dans l'admin, on regarde la liste : 

0029    35 -> OK en prod. Pas de document car non étendu
0086    18 -> OK en prod 
0573    51 -> OK en prod
1043    52 -> KO
1486    15 -> OK en prod
1516    18 -> KO
3248    52 -> OK en prod

Q52 / CC 1043: on a une réponse sur l'admin et on affiche que l'on a pas de réponse sur le frontend. Le document est toujours absent en BDD

Q18 / CC 1516: la CC ne prévoit rien. Cependant, nous n'avons pas de document associé.
