### ISSUE TITLE
Clean de la dépendance du package modèles

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#5820]
* Supprimer les dossiers autres que lib
 * Supprimer les dossiers \_\_tests__
 * Clean des fichiers à la racine

![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/25312957/5752222b-ff61-4630-96d9-b47d8c14c937)

**Comment by maxgfr** [comment]
Le résultat : 

<img width="290" alt="Screenshot 2024-04-24 at 17 31 01" src="https://github.com/SocialGouv/code-du-travail-numerique/assets/25312957/d414b04e-24f6-432e-8d80-102e29b6705c">

**Comment by maxgfr** [comment]
68% de gagné 🥇
