### ISSUE TITLE
[rupture-co + licenciement] Bug sur la page contrat

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#5843]
https://github.com/SocialGouv/code-du-travail-numerique/assets/992514/ba1ec73c-e8b3-4837-badf-4c80392a286c

https://github.com/SocialGouv/code-du-travail-numerique/assets/992514/d247c389-7253-4692-ab14-7b30f7eb1d60

**Comment by carolineBda** [comment]
Pour moi le bug n'est présent que sur la rupture co non ?
