### ISSUE TITLE
Erreur sur indemnité de licenciement

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#5848]
"Le calcul sur l'écran de résultat retourne un missing-args"

https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/153159/?environment=production&project=5&query=is%3Aunresolved&referrer=issue-stream&stream_index=10

**Comment by m-maillot** [comment]
Et activer les replays

**Comment by carolineBda** [comment]
On attends de voir ce que vont donner les nouveaux logs

**Comment by carolineBda** [comment]
On a les nouveaux logs :
https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/153742/?environment=production&project=5&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=3

**Comment by m-maillot** [comment]
Bug identifié grâce aux nouveaux logs :

On peut sélectionner une `date d'entrée` identique à la `date de notification`.

Scénario : 

Contrat : `{"typeContratTravail":"cdi","licenciementFauteGrave":"non","licenciementInaptitude":"oui"}`
CC : 29
Ancienneté : `{"absencePeriods":[{"motif":{"key":"absenceAccidentTrajet","label":"Arrêt maladie lié à un accident de trajet","value":1},"durationInMonth":2,"key":"bffgmvksoed"}],"dateEntree":"15/05/2024","dateNotification":"15/05/2024","dateSortie":"31/05/2024","hasAbsenceProlonge":"oui"}`
Salaire : `{"showHasTempsPartiel":true,"salaryPeriods":[],"hasTempsPartiel":"non","hasSameSalary":"oui","salary":"10003"}`

On a une erreur à la page résultat en forme de missing args car on a un salaire de ref vide.

**Comment by m-maillot** [comment]
Autre cas : 

On peut renseigner un salaire à 0. Du coup, on n'a pas de salaire de ref également.

Exemple de saisie avec salaire à 0 et qui plante :

```
{"salaryPeriods":"[{\"month\":\"mai 2024\",\"value\":0},{\"month\":\"avril 2024\",\"value\":0},{\"month\":\"mars 2024\",\"value\":0},{\"month\":\"février 2024\",\"value\":0},{\"month\":\"janvier 2024\",\"value\":0},{\"month\":\"décembre 2023\",\"value\":0},{\"month\":\"novembre 2023\",\"value\":0},{\"month\":\"octobre 2023\",\"value\":0},{\"month\":\"septembre 2023\",\"value\":0},{\"month\":\"août 2023\",\"value\":0},{\"month\":\"juillet 2023\",\"value\":0},{\"month\":\"juin 2023\",\"value\":0}]","contrat salarié . indemnité de licenciement . date de notification":"31/05/2024","contrat salarié . indemnité de licenciement . date d'entrée":"01/02/2021","contrat salarié . indemnité de licenciement . date de sortie":"31/05/2024","contrat salarié . indemnité de licenciement . inaptitude suite à un accident ou maladie professionnelle":"oui","contrat salarié . indemnité de licenciement . arrêt de travail":"non","contrat salarié . convention collective":"'IDCC1411'","absencePeriods":"[{\"motif\":{\"key\":\"absenceMaladieNonPro\",\"label\":\"Absence pour maladie non professionnelle\",\"value\":1},\"durationInMonth\":28,\"key\":\"efiobx422j\"}]","typeContratTravail":"cdi","licenciementFauteGrave":"non"}
```

Ce problème se reproduit souvent sur la possibilité de saisir plusieurs salaires. Peut être à cause du scroll ?

**Comment by m-maillot** [comment]
Cas étrange indiquant qu'il manque la convention collective : 
 * https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/153742/events/c7d327df67d84b5a8476203f658ab483/?environment=production&project=5&query=release%3Av4.137.0&referrer=previous-event

* https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/153742/events/3a4b91edd2a3422cb65607fa24f91378/?environment=production&project=5&query=release%3Av4.137.0&referrer=previous-event

J'ai une piste pour ce cas là. Dans la console, on voit qu'il recherche par entreprise. J'ai fait une recherche sur une entreprise et sélectionné l'entreprise `ASS TOROS PARA TODOS` qui n'a pas de convention collective déclarée. Je peux faire suivant et aller jusqu'au bout et je tombe sur une erreur à la fin. 
D'ailleurs, on peut voir dans la console le call vers l'API de recherche de l'entreprise. Quand on clique dessus, on voit bien que l'entreprise à chaque fois n'a pas d'IDCCs.

**Comment by m-maillot** [comment]
Cas où l'erreur semble venir du front. Les infos dans l'étape salaire semblent bonnes. Mais dans la situation, on n'a pas de salaire de renseigné : 
 * https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/153742/events/fd38785704294f6a900cf2ef17be3fa7/?environment=production&project=5&query=release%3Av4.137.0&referrer=previous-event
 * https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/153742/events/8f4e3625ee55430db2ba201fc1137347/?environment=production&project=5&query=release%3Av4.137.0&referrer=previous-event

**Comment by m-maillot** [comment]
Etude réalisée jusqu'à `May 15, 9:54 AM` seulement sur la dernière version en prod.

**Comment by carolineBda** [comment]
Je regarde cette erreur : https://github.com/SocialGouv/code-du-travail-numerique/issues/5848#issuecomment-2112041309

**Comment by m-maillot** [comment]
J'ai créé les issues pour chaque type d'erreur. Je ferme cette issue du coup.
