### ISSUE TITLE
Implémenter la 3248

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#5850]
Revoir l'implémentation de la 3248 sur la rupture co. Il manque les tests et le code est étrange.

**Comment by carolineBda** [comment]
Pour @m-maillot : préciser quel parti du code est à refacto ?

⚠ dans les retours métier, nous avons eu le retour suivant : [CC 3248 - Manque deux questions](https://docs.google.com/document/d/1KzN-c4T4Iw3eAti2a1PHezwpJhRw8sUSBloTt3tHxYY/edit)

**Comment by m-maillot** [comment]
Retour de Perrine : 
> J'ai tout testé et il y a un seul petit problème c'est pour le cas d'un salarié du groupe E avec 3,5 années d'ancienneté au forfait jour (ligne 15 du doc [Test intégration IDCC - IRC - Google Sheets](https://docs.google.com/spreadsheets/d/1Skeal7If9pAUdkgH9j993gbTGM1udr5SpX9CcAFRSyI/edit#gid=1367488243))
> 
> Mais sinon pour le reste tout est bon 


De mon coté, j'obtiens le bon résultat chez moi, voici ce que j'ai saisi :

[resultat - 3248.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/15340090/resultat.-.3248.pdf)
