### ISSUE TITLE
Intégration du bloc 1.1.a de la hiérarchie des normes

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#587]
Le matching est disponible ici : https://docs.google.com/spreadsheets/d/1mQ81azG7weE0Jw3vjOatMQbHi8JUFy9HwR4ZDAEABmk/edit#gid=311261636

Le design pour l'intégration du premier bloc est disponible ici :
![bloc 1 1 a](https://user-images.githubusercontent.com/5337489/54121458-c1928200-43fa-11e9-90b2-16cfbe94236c.png)

**Comment by UnbearableBear** [comment]
Ca m'intéresse beaucoup ça !

**Comment by lionelB** [comment]
closed by #625 
@UnbearableBear si tu rajoutes `Fix #xxx`  dans le message de commit ou dans le message de la PR, l'issue va se fermer automatique et plus cela permet de faire des liens entre les deux. C'est assez pratique.
