### ISSUE TITLE
Test de non regression des widgets

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#5881]
Le but est de tester les widgets sur un nom de domaine différent pour s'assurer de leur non régression en prod.

- [x] créer une page sur github.io avec tous nos widgets installés (ne pas oublier le widget Trouver sa CC" avec le param `noRedirect`)
- [x] ajouter un test dans la suite heavy qui va tester tous les widgets de cette page

**Comment by maxgfr** [comment]
Le lien de la page est : https://socialgouv.github.io/cdtn-admin/
