### ISSUE TITLE
Date de début égale à date de notification

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#5893]
On peut sélectionner une date d'entrée identique à la date de notification.

Scénario :

Contrat : {"typeContratTravail":"cdi","licenciementFauteGrave":"non","licenciementInaptitude":"oui"}
CC : 29
Ancienneté : {"absencePeriods":[{"motif":{"key":"absenceAccidentTrajet","label":"Arrêt maladie lié à un accident de trajet","value":1},"durationInMonth":2,"key":"bffgmvksoed"}],"dateEntree":"15/05/2024","dateNotification":"15/05/2024","dateSortie":"31/05/2024","hasAbsenceProlonge":"oui"}
Salaire : {"showHasTempsPartiel":true,"salaryPeriods":[],"hasTempsPartiel":"non","hasSameSalary":"oui","salary":"10003"}

On a une erreur à la page résultat en forme de missing args car on a un salaire de ref vide.

**Comment by carolineBda** [comment]
A voir avec le métier ce qu'on doit faire

**Comment by carolineBda** [comment]
On va implémenter ce cas la : #5907
