### ISSUE TITLE
Salaire à 0 dans l'indemnite

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#5894]
On peut renseigner un salaire à 0. Du coup, on n'a pas de salaire de ref également.

Exemple de saisie avec salaire à 0 et qui plante :
```
{"salaryPeriods":"[{\"month\":\"mai 2024\",\"value\":0},{\"month\":\"avril 2024\",\"value\":0},{\"month\":\"mars 2024\",\"value\":0},{\"month\":\"février 2024\",\"value\":0},{\"month\":\"janvier 2024\",\"value\":0},{\"month\":\"décembre 2023\",\"value\":0},{\"month\":\"novembre 2023\",\"value\":0},{\"month\":\"octobre 2023\",\"value\":0},{\"month\":\"septembre 2023\",\"value\":0},{\"month\":\"août 2023\",\"value\":0},{\"month\":\"juillet 2023\",\"value\":0},{\"month\":\"juin 2023\",\"value\":0}]","contrat salarié . indemnité de licenciement . date de notification":"31/05/2024","contrat salarié . indemnité de licenciement . date d'entrée":"01/02/2021","contrat salarié . indemnité de licenciement . date de sortie":"31/05/2024","contrat salarié . indemnité de licenciement . inaptitude suite à un accident ou maladie professionnelle":"oui","contrat salarié . indemnité de licenciement . arrêt de travail":"non","contrat salarié . convention collective":"'IDCC1411'","absencePeriods":"[{\"motif\":{\"key\":\"absenceMaladieNonPro\",\"label\":\"Absence pour maladie non professionnelle\",\"value\":1},\"durationInMonth\":28,\"key\":\"efiobx422j\"}]","typeContratTravail":"cdi","licenciementFauteGrave":"non"}
```
Ce problème se reproduit souvent sur la possibilité de saisir plusieurs salaires. Peut être à cause du scroll ?

**Comment by carolineBda** [comment]
Ici il faut forcer au moins une valeur positive dans les salaire. 
Sinon on affiche 
"**Vous devez répondre à cette question**"

Si salaire différent sur les 12 derniers mois, il faut au moins une case avec une valeur positive.
Attention, les valeurs négative sont interdites mais il est possible de mettre 0 sur un ou plusieurs mois

**Comment by maxgfr** [comment]
@carolineBda pour les valeurs négatives on a vu avec le métier que c'était possible donc je pense on peut laisser cette possibilité ainsi

**Comment by maxgfr** [comment]
D'ailleurs, j'ai mis ce message : `"Vous devez saisir un salaire annuel supérieur à 0"` qui est plus clair. Car en soit il répond à la question mais c'est juste qu'il saisie un salaire annuel supérieur à 0
