### ISSUE TITLE
Bug sur la page résultat

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#5896]
Cas où l'erreur semble venir du front. Les infos dans l'étape salaire semblent bonnes. Mais dans la situation, on n'a pas de salaire de renseigné :

https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/153742/events/fd38785704294f6a900cf2ef17be3fa7/?environment=production&project=5&query=release%3Av4.137.0&referrer=previous-event
https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/153742/events/8f4e3625ee55430db2ba201fc1137347/?environment=production&project=5&query=release%3Av4.137.0&referrer=previous-event

**Comment by carolineBda** [comment]
On reproduit bien cette erreur : https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/153742/?environment=production&project=5&query=is%3Aunresolved+contrat&referrer=issue-stream&sort=freq&statsPeriod=14d&stream_index=0

Il faut chercher l'entreprise **BRICOMAN** dans le **59650**,

![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/4971715/3ca408d9-bf9f-467e-9ff9-2bc7a4a87c24)


 Ensuite 4ans d'ancienneté + même salaire à 2100€

![Image](https://github.com/SocialGouv/code-du-travail-numerique/assets/4971715/7fbd4602-6040-41b6-b2ce-f3b069589dc6)

**Comment by m-maillot** [comment]
Pour reproduire :

Se rendre sur le simu, chercher BRICOMAN, sélectionnez le premier qui a une CC. Supprimer et choisir le second, qui n'a pas de CC. Allez au bout de la simu et ça plante.

**Comment by carolineBda** [comment]
Toujours des erreurs sur les dates, les utilisateurs arrivent à saisir des dates avec ce format : `"23/05/272024"`
Il faut ajouter un peu de validation supplémentaire 


https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/157564/?environment=production&project=107&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+my_teams%2C+none%5D&referrer=issue-stream&statsPeriod=30d&stream_index=19

**Comment by carolineBda** [comment]
Toujours des erreurs :

https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/157528/events/749186d711b84d858d0855fd83494383/?environment=production&project=107&query=is%3Aunresolved&referrer=next-event&statsPeriod=30d&stream_index=16

https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/157528/events/fb6211c5e19b48c3a1feed7febb66ed3/?environment=production&project=107&query=is%3Aunresolved&referrer=previous-event&statsPeriod=30d&stream_index=16

"La durée de l'absence doit être inférieure ou égale à l'ancienneté"

**Comment by carolineBda** [comment]
Certains arrivent à entrer une date de notification vide : https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/157528/?environment=production&project=107&query=is%3Aunresolved+http.url%3Ahttps%3A%2F%2Fcode.travail.gouv.fr%2Foutils%2Findemnite-licenciement&referrer=issue-stream&statsPeriod=30d&stream_index=2

**Comment by maxgfr** [comment]
Je n'arrive pas à réaliser ce bug, je suis pas sûr de l'avoir bien compris. Pour moi ça semble venir du nombre de mois minimum, mais on a corrigé ce bug

**Comment by maxgfr** [comment]
Je close l'issue pour ne pas créer la confusion. Dans le cas où on veut suivre les bugs, on a sentry, sinon on crée des tickets en drafts
