### ISSUE TITLE
[WIP] déploiement tags  personnlaisés depuis eposeidon màj juillet 2018

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#59]
164400	Santé Sécurité > Sécurité: Généralités > Principes généraux de prévention (PGP)> Obligations de l'employeur > Mesures d eprévention L4121-1;
164400	Santé Sécurité > Sécurité: Généralités > Principes généraux de prévention > Obligations de sécurité l'employeur > PGP L4121-2; 
164400	Santé Sécurité > Sécurité: Généralités > Principes généraux de prévention > Obligations de sécurité de l'employeur > Evaluation des risques L4121-3; 
164400	Santé Sécurité > Sécurité: Généralités > Principes généraux de prévention > Obligations de sécurité de l'employeur > L4121-4;
164400	Santé Sécurité > Sécurité: Généralités > Principes généraux de prévention > Obligations de sécurité de l'employeur > coactivité L4121-5; 
164400	Santé Sécurité > Sécurité: Généralités > Principes généraux de prévention > Obligations de sécurité de l'employeur > Document Unique d'Evaluation des Risques  Professionnels (DUERP) R4121-1; R4121-1-1; R4121-2; R4121-3; R4121-4; R4741-1-1;

___

73400 | Emploi - Formation > Formation   professionnelle Continue > Contrat de professionnalisation | L6325-2-1;   L6325-3-1; L6325-14-1; L6325-6-2
-- | -- | --
73500 | Emploi - Formation > Formation professionnelle Continue > Contrat   de professionnalisation > Convention entreprise accueil | D6325-30; D6325-31; D6325-32
73600 | Emploi - Formation > Formation professionnelle Continue > Contrat   de professionnalisation > Durée, Mise en œuvre | L6325-14; L6325-4-1; L6325-11;   L6325-12; L6325-13; L6325-15
73700 | Emploi - Formation > Formation professionnelle Continue > Contrat   de professionnalisation > Entreprise de travail temporaire | L6325-23; L6325-24
73800 | Emploi - Formation > Formation professionnelle Continue > Contrat   de professionnalisation > Exonérations | D6325-19; D6325-19-1
73900 | Emploi - Formation > Formation professionnelle Continue > Contrat   de professionnalisation > Exonérations de charges | L6325-16; L6325-17; L6325-18;   L6325-19; L6325-20; L6325-21; L6325-22
74000 | Emploi - Formation > Formation professionnelle Continue > Contrat   de professionnalisation > Formation, enregistrement. Rupture | D6325-1; D6325-4; D6325-5; D6325-2
74100 | Emploi - Formation > Formation professionnelle Continue > Contrat   de professionnalisation > Formation, exécution du contrat | L6325-7; L6325-5; L6325-6
74200 | Emploi - Formation > Formation professionnelle Continue > Contrat   de professionnalisation > Groupements employeurs | L6325-6-1 |  
74300 | Emploi - Formation > Formation professionnelle Continue > Contrat   de professionnalisation > Objet, conditions d'ouverture | L6325-1-1; L6325-2; L6325-3;   L6325-4; L6325-1
74400 | Emploi - Formation > Formation professionnelle Continue > Contrat   de professionnalisation > Organisation de la formation | D6325-11; D6325-12; D6325-13
74500 | Emploi - Formation > Formation professionnelle Continue > Contrat   de professionnalisation > Salaire | D6325-14; D6325-15; D6325-16;   D6325-17; D6325-18
74600 | Emploi - Formation > Formation professionnelle Continue > Contrat   de professionnalisation > Salaire,Durée du Travail | L6325-10; L6325-8; L6325-9
74700 | Emploi - Formation > Formation professionnelle Continue > Contrat   de professionnalisation > Tutorat | D6325-6; D6325-7; D6325-8; D6325-9;   D6325-10

1700 | Contrat de travail > Rupture de contrat   à durée Indéterminée (CDI) > Rupture conventionnelle > Rupture   conventionnelle | R1237-3;   L1237-16; L1237-13; L1237-12; L1237-14; L1237-11; L1237-15
-- | -- | --
1710 | Contrat de travail > Rupture de contrat à durée Indéterminée (CDI)   > Rupture conventionnelle > Rupture conventionnelle> Principe | L1237-11 |   |  
1720 | Contrat de travail > Rupture de contrat à durée Indéterminée (CDI)   > Rupture conventionnelle > Rupture conventionnelle>Procédure>   entretiens | L1237-12 |   |  
1730 | Contrat de travail > Rupture de contrat à durée Indéterminée (CDI)   > Rupture conventionnelle > Rupture conventionnelle>Procédure>   indemnité de rupture | L1237-13 |   |  
1740 | Contrat de travail > Rupture de contrat à durée Indéterminée (CDI)   > Rupture conventionnelle > Rupture conventionnelle>Procédure>   homologation | L1237-14; R1237-3 |  
1750 | Contrat de travail > Rupture de contrat à durée Indéterminée (CDI)   > Rupture conventionnelle > Rupture conventionnelle>Procédure>   salariés protégés | L1237-15 |   |  
1760 | Contrat de travail > Rupture de contrat à durée Indéterminée (CDI)   > Rupture conventionnelle > Rupture conventionnelle>Procédure>   exceptions | L1237-16; |   |  
1770 | Contrat de travail > Rupture de contrat à durée Indéterminée (CDI)   > Rupture conventionnelle > Rupture conventionnelle>procédure | R1237-3; L1237-16; L1237-13;   L1237-12; L1237-14; L1237-16

**Comment by ClementChapalain** [comment]
@jrduscher est-ce cette tâche est prête à être développée ou a-t-on besoin de plus de détails ?
