### ISSUE TITLE
Identifier pourquoi dans le sitemap nous avons des pages avec des redirect

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#5901]
Dans le sitemap nous avons les pages suivantes, alors qu'elles redirigent vers une autre page. Il faudrait mettre directement le bonne url

url |date
-- | --
https://code.travail.gouv.fr/convention-collective/2075-oeufs-et-industries-en-produits-doeufs-centres-de-conditionnement-de-comme | May 17, 2024
https://code.travail.gouv.fr/convention-collective/7002-cooperatives-agricoles-de-cereales-de-meunerie-dapprovisionnement-dali | May 17, 2024
https://code.travail.gouv.fr/convention-collective/7003-conserveries-cooperatives-et-sica | May 17, 2024
https://code.travail.gouv.fr/convention-collective/7004-cooperatives-agricoles-laitieres | May 17, 2024
https://code.travail.gouv.fr/convention-collective/7005-caves-cooperatives-vinicoles-et-leurs-unions | May 17, 2024
https://code.travail.gouv.fr/convention-collective/7006-cooperatives-agricoles-unions-de-cooperatives-agricoles-et-sica-de-fleurs | May 17, 2024
https://code.travail.gouv.fr/convention-collective/7007-cooperatives-agricoles-de-teillage-du-lin | May 17, 2024
https://code.travail.gouv.fr/convention-collective/7009-entreprises-daccouvage-et-de-selection-avicoles | May 17, 2024
https://code.travail.gouv.fr/convention-collective/7001-cooperatives-et-societes-dinteret-collectif-agricole-betail-et-viande | May 10, 2024
https://code.travail.gouv.fr/convention-collective/7008-personnel-des-organismes-de-controle-laitier

</span></span>

**Comment by m-maillot** [comment]
Revoir les regex sur les redirections. 

Le premier lien : https://code.travail.gouv.fr/convention-collective/2075-oeufs-et-industries-en-produits-doeufs-centres-de-conditionnement-de-comme ne devrait pas rediriger.
