### ISSUE TITLE
Ne pas crasher avec sur les urls invalides

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#5904]
Par exemple : [celle-ci](https://code-du-travail-numerique-preprod.ovh.fabrique.social.gouv.fr/droit-du-travail#:~:text=Le%20droit%20du%20travail%20est)

https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/153740/?environment=production&project=5&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+my_teams%2C+none%5D&referrer=issue-stream&sort=freq&statsPeriod=90d&stream_index=1

**Comment by m-maillot** [comment]
Se reproduit facilement sur firefox
