### ISSUE TITLE
Erreur sur les widgets : ne pas setter de cookie quand on séléctionne sa CC dans un widget

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#5913]
Désactiver les cookies de matomo quand on est dans un widget.

Ces cookies proviennent de matomo. 
[désactiver les cookie](https://matomo.org/faq/general/faq_157/) quand on est sur [une url qu'on exclue](https://github.com/SocialGouv/matomo-next/blob/master/src/index.ts#L110)

Attention, une fois qu'on a créé la branch il faudra valider qu'on peut toujours suivre une session même sans les cookies

```
SecurityError
The operation is insecure.

There was an error setting cookie `_pk_ses.4.ef54`. Please check domain and path.
```

https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/153225/?environment=production&project=5&query=is%3Aunresolved&referrer=issue-stream&stream_index=19

https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/153160/?environment=production&project=5&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=6

**Comment by m-maillot** [comment]
Pourquoi une erreur de cookie alors que l'on stocke dans le local storage ?

**Comment by carolineBda** [comment]
Effectivement ! Ces cookies proviennent de matomo. Je me demande si on devrait ne pas [disable les cookie](https://matomo.org/faq/general/faq_157/) quand on est sur [une url qu'on exclue](https://github.com/SocialGouv/matomo-next/blob/master/src/index.ts#L110)

En attendant j'ai même fait une PR pour la 2ème erreur
