### ISSUE TITLE
Fix l'environement de dev

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#5953]
- point avec les SRE : @carolineBda 
    - voir pourquoi le fix de Jo à régresser => NLP est fixed ✅ 
    -  voir avec eux pour l'export : export sur `cdtn-admin-linked-byebye-nlp/export-c849f9447-dwxfm:app` => _ils regardent_ mais ça a l'air fixed par les annotations ajoutées par @maxgfr ✅ 
- ~~désactiver temporairement serving ml en dev @m-maillot~~
- suppression de serving-ml :
    - fixer le code @maxgfr  ✅ 
    - tester la recherche et les articles liés pour voir les diff @Viczei ✅

**Comment by m-maillot** [comment]
Tout est ok en dev.
