### ISSUE TITLE
Fix page Stats

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#5954]
Faire au plus simple pour l'instant :
- est-ce qu'on peut remplacer par un autre endpoint de l'API ?
- sinon peut-on découper en plusieurs call par année

**Comment by Viczei** [comment]
- [ ] Rajouter dans table document (valeur + date)
- [ ] Calculer le diff de visit dans l'ingester
- [ ] Stocker dans ES à l'export
- [ ] Brancher sur le front

**Comment by carolineBda** [comment]
Empreinte Digitale (qui administre notre instance de matomo) investigue pourquoi la requete a arrêté de fonctionner : https://mattermost.fabrique.social.gouv.fr/default/pl/a9ybt9yd7pf43f9k574hzxgksy
