### ISSUE TITLE
Archiver le dépôt `serving-ml`

### ISSUE THREAD

**Issue by devthejo** [SocialGouv/code-du-travail-numerique#5986]
- [x] archiver le dépôt `serving-ml`
- [x] supprimer le namespace

(next week ?)
see: https://mattermost.fabrique.social.gouv.fr/default/pl/f6cb6tci4p8sbbfj67xu6ndh4a

**Comment by gary-van-woerkens** [comment]
Une PR a été ouverte dans Gitlab pour supprimer les ressources liées à `serving-ml`:
https://gitlab.fabrique.social.gouv.fr/infra/infra-startup/-/merge_requests/420
