### ISSUE TITLE
Déplacer les déploiements vers les noeuds dédiés en DEV

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/code-du-travail-numerique#5991]
Les OPS ont créé des noeuds dédiés pour CDTN sur le cluster de dev.
Il faudrait faire pointer tous les déploiements de CDTN en dev vers les noeuds teintés à cet effet.

Différentes options:
1. Regle Kyverno
2. Kontinuous

**Comment by matmut7** [comment]
J'ai opté pour Kontinuous
https://github.com/SocialGouv/code-du-travail-numerique/pull/5987
https://github.com/SocialGouv/cdtn-admin/pull/1434
