### ISSUE TITLE
[Analyse] query ES

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#6019]
- checker les warning sur les recherches
- analyser la query ES pour voir si on peut l'optimiser et/ou la cleaner
- Il faut absolument qu'on optimise la partie sur les `relatedItems`, car en soit à priori les covisites ne fonctionnent pas. D'autant plus qu'on utilise pas le title avec le paramètre `settings`

Max 1 journée

**Comment by maxgfr** [comment]
Pour les warning, je n'ai pas trouvé la source du problème.

Pour l'optimisation de la query, je ne vois pas trop comment on peut améliorer, faudrait définir ce qu'on veut vraiment ressortir dans notre recherche

Pour la dernière partie, je le clean dans ma PR les covisits

**Comment by m-maillot** [comment]
On cloture cette carte. On ouvrira une nouvelle si besoin.
