### ISSUE TITLE
les suggestions de contenu dans feedback ne remonte plus

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#604]
Apres le split des pages home et recherche, l'affichage de résultats qui matche la requete ne s'affiche plus dans la popup de feedback (cf la maquette)

**Comment by ClementChapalain** [comment]
j'ai l'impression que ça fonctionne chez moi :
![image](https://user-images.githubusercontent.com/5337489/54883630-eb6e8e80-4e67-11e9-8975-6c541e110d6e.png)

tu peux me dire comment reproduire stp ?

**Comment by ClementChapalain** [comment]
plus pertinent avec la nouvelle intégration du module de feedback :)
