### ISSUE TITLE
Problème au niveau de la synchronisation des dates sur le sitemaps et des contributions

### ISSUE THREAD

**Issue by maxgfr** [SocialGouv/code-du-travail-numerique#6042]
![Screenshot 2024-07-18 at 16 28 29](https://github.com/user-attachments/assets/426bb75f-4d5d-46ee-9d19-22cec8789424)
![Screenshot 2024-07-18 at 16 28 46](https://github.com/user-attachments/assets/b907fc66-8a53-4d8c-8a7b-e486e977d16f)

**Comment by m-maillot** [comment]
Le métier aimerait avoir la main sur la date : https://mattermost.fabrique.social.gouv.fr/default/pl/hbgwzb48h3gnmnkbwpws6t613h
