### ISSUE TITLE
Catégories pro différentes sur la 2216

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#6068]
Sur l'outil de préavis retraite,

Pour la convention collective 2216, selon le type de départ à la retraite, on n'a pas la même liste de catégorie pro.

Pour le départ à la retraite : 
 * Non-cadres
 * Cadres

Pour la mise à la retraite : 

* Employés et ouvriers
* Techniciens et agents de maîtrise
* Cadres

Pourquoi a-t-on des listes différentes ?

**Comment by maxgfr** [comment]
@m-maillot ça c'est une problématique métier

**Comment by maxgfr** [comment]
Dans le code, ça,a été fait exprès

**Comment by maxgfr** [comment]
[Correctifs sur le simulateur Préavis de départ ou de mise à la retraite.docx](https://github.com/user-attachments/files/17039588/Correctifs.sur.le.simulateur.Preavis.de.depart.ou.de.mise.a.la.retraite.docx)
