### ISSUE TITLE
[Contributions] Gestion des conventions collectives 9999

### ISSUE THREAD

**Issue by maxgfr** [SocialGouv/code-du-travail-numerique#6073]
On renvoie un event matomo lorsque la CC est 9999. Or techniquement, ça biaise pas mal le truc

De plus, il faudrait voir là aussi si on peut optimiser l'UX

Le numéro de SIRET à tester est celui-ci  : `55203253400646`

![image](https://github.com/user-attachments/assets/70fe8d67-6ace-4c03-ada1-5b9c5cf08c3a)

**Comment by m-maillot** [comment]
![Image](https://github.com/user-attachments/assets/c1e6bb1b-eacf-4bb0-b58b-be7a7434daba)

https://code.travail.gouv.fr/contribution/2609-les-conges-pour-evenements-familiaux



![Image](https://github.com/user-attachments/assets/80f6207d-a5ee-40d4-9fd2-313980553968)

**Comment by carolineBda** [comment]
Quel comportement avoir dans les cas suivants :
- quand on sélectionne une entreprise avec une CC inconnue
    - est-ce qu'on l'affiche ?
![Image](https://github.com/user-attachments/assets/dfa9e002-1924-4bf3-a6ac-18e592ac47e2)
    - est-ce qu'on envoit l'event : `cc_select_p2 / Indemnité de rupture conventionnelle / idcc9999` ?
    - est-ce qu'on garde en mémoire cette CC 
    

![Image](https://github.com/user-attachments/assets/b01c67d1-bafd-4099-9931-8ee1ca7d01ce)

**Comment by maxgfr** [comment]
@carolineBda J'ai mis en place le fix qui permet de ne pas sauvegarder les CCs 9999

**Comment by carolineBda** [comment]
Après discussion avec @virginielastisneres :

- on continue de tracker toutes les CC même inconnues comme 9999
- on set bien le cookie quand on sélectionne une entreprise avec une de ces CC (le but étant d'éviter à l'utilisateur qui fais plusieurs simulation d'avoir à chaque fois à retrouver son entreprise

Dans une autre carte nous mettrons à jour les message affichés quand on sélectionne une entreprise avec une CC inconnue pour afficher "Pas de convention collective connue"
