### ISSUE TITLE
[Simulateur Indemnité précarité] Ecran d'erreur au résultat CC 3127

### ISSUE THREAD

**Issue by Viczei** [SocialGouv/code-du-travail-numerique#6109]
**Description**
La page résultat affiche une erreur

**Reproduction**
Etapes à suivre pour reproduire le bug

1. Prendre la CC 3127
2. Sélectionner "CCD"
3. Sélectionner "CDD dit de « mission ponctuelle ou occasionnelle »"
4. Ensuite sélectionner "Oui"
5. Indiquer un salaire

**Comportement attendu**
 ~~On arrive à la page résultat~~
On bloque l'utilisateur avec le message 
"Ce type de contrat ne permet pas au salarié d’avoir droit à une prime de précarité."

![Image](https://github.com/user-attachments/assets/04170ef5-85c8-4630-b734-ffa12d211942)

- [x] 1486 : Contrat d'intervention dans le secteur d'activité d'organisation des foires, salons et congrès / proposition CDI : OUI
- [x] 1516 : CDD d'usage / proposition CDI : OUI
- [x] 2511 : CDD d'usage appelé contrat «d'intervention» / proposition CDI : OUI 	
- [x] 3127 : CDD dit de « mission ponctuelle ou occasionnelle » / proposition CDI : OUI 	
- [x] Ajouter un test unitaire ui pour chaque CC

https://mattermost.fabrique.social.gouv.fr/default/pl/4wbieema47rd7ksnsr4r4ughnc

**Comment by carolineBda** [comment]
Il y a le même pb pour :
- 1486 / CDD /	Contrat d'intervention dans le secteur d'activité d'organisation des foires, salons et congrès / proposition CDI : OUI
- 2511 / CDD/ CDD d'usage appelé contrat «d'intervention» / proposition CDI : OUI
