### ISSUE TITLE
[DSFR] enlever la config CSP unsafe-inline

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#6125]
Même une fois la [code react DSFR désactivé](https://github.com/codegouvfr/react-dsfr/issues/303), on a encore une erreur CSP du au app router.

Il faut essayer de faire fonctionner le [nonce](https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy#nonces) pour corriger cette erreur.

**Comment by maxgfr** [comment]
Documentation : 
- https://github.com/vercel/next.js/discussions/49648
- https://github.com/vercel/next.js/pull/54601

**Comment by maxgfr** [comment]
Le problème c'est que ça desactive le statique :(
