### ISSUE TITLE
[Fiche MT] intégrer leur nouvelle page sur la branch DSFR

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#6129]
Environnement accessible ici : https://mattermost.fabrique.social.gouv.fr/default/pl/74n4yq39t78wpkkof79izearge

- tester les nouvelles pages avec le site actuel
- revoir tous les cas de tests du scrapping
- créer un env de test avec une branch admin qui récupère les nouvelles pages (`linked branch`)
- regarder comment gérer les nouvelles images
-

**Comment by m-maillot** [comment]
Il faut récupérer le html contenu entre les balises `<article>`

**Comment by m-maillot** [comment]
1) en mobile sur le design la date mise à jour s'affiche à la ligne (tu peux mettre un `<Br />` qui s'affiche qu'en mobile). A faire sur toutes les pages ?
2) en bas de cette [page](https://code-du-travail-numerique-linked-feat-fiches-mt-dsfr-qefoqjfs.ovh.fabrique.social.gouv.fr/fiche-ministere-travail/projet-de-transition-professionnelle) il y a une section vide
![Image](https://github.com/user-attachments/assets/3367f2f8-da82-4c3a-822c-93bbc5b29f0e)

3) dans les card la date ne s'affiche pas bien on voit du html https://code-du-travail-numerique-linked-feat-fiches-mt-dsfr-qefoqjfs.ovh.fabrique.social.gouv.fr/fiche-ministere-travail/la-liste-des-postes-a-risques

![Image](https://github.com/user-attachments/assets/174219e1-bb21-405e-ac57-2424c146bbcc)

4) en mobile il faut ajouter de l'espace entre "avez-vous trouvé la réponse..." et articles liées.  _à corriger dans tous les "Rich Container" ?_

5) - icone information de la mise en exergue cassés : https://code-du-travail-numerique-linked-feat-fiches-mt-dsfr-qefoqjfs.ovh.fabrique.social.gouv.fr/fiche-ministere-travail/projet-de-transition-professionnelle
![Image](https://github.com/user-attachments/assets/aa06970f-da84-4b8b-8b18-77b145f393a7)

6) Plusieurs soucis sur cette page : https://code-du-travail-numerique-linked-feat-fiches-mt-dsfr-qefoqjfs.ovh.fabrique.social.gouv.fr/fiche-ministere-travail/plans-sante-au-travail-pst

* on repete en bas 2 fois les même accordéons mais vides
* les accordéons avec des H3 n'ont pas le bon style
* image avec un lien, on a l'icone qui s'affiche dessous

![Image](https://github.com/user-attachments/assets/00866cfb-6cb3-41f6-8c4a-f8a40f147443)

 7) Remplacer "Mise à jour" par "Mis à jour"

**Comment by m-maillot** [comment]
1) demande faite sur figma pour voir si on uniformise -> issue #6228 

2) Section vie lié au code dans la page MT d'origine. Avec le découpage en accordéon, on la section qui englobe le téléchargement normalement qui est resté présente mais on a de notre coté mis le téléchargement dans un nouvel accordéon. C'est lié à la structure HTML cassé de leur coté. Il faudrait ne plus transformer leur page. 
Comme il n'y a pas de perte de données, on va laisser comme ça pour le moment.

3) Exclure le flag time dans xss ou remplacer par un élement vide (valider que ça ne pose pas de soucis)

4) il faut 48px de marge

5) Classe de l'icone à vérifier

7) 
 -> Supprimer les accordéons vides
 -> les h3 sont inclus dans la pages fiches MT. On n'a pas la main dessus
 -> voir le css qui génère cette icone

**Comment by m-maillot** [comment]
6. les accordéons avec des H3 n'ont pas le bon style

Voici les explications.

On attend cette structure sur un accordéon : 

![Image](https://github.com/user-attachments/assets/4378a7d9-412b-4daf-a920-2e0eefa1c9c4)

Or dans le contenu de la page fiche MT, on a ça :

![Image](https://github.com/user-attachments/assets/7aca25c0-6ebc-4490-b7b6-f0d4444d4773)

Ils ont un soucis de leur coté trop complexe à corriger de notre coté.

**Comment by m-maillot** [comment]
Pour les icones, je vais ajouter l'icone dans le CallOut car sinon react-dsfr n'aime pas on dirait.
