### ISSUE TITLE
Mettre en bleu les icones de partage

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#6153]
![Image](https://github.com/user-attachments/assets/ce5a7563-17e7-4dd6-8a85-a6a293096a85)

https://www.figma.com/design/DSfSIVNOCNHi76JeVuSo5T?node-id=569-12989#955543505

**Comment by carolineBda** [comment]
Est-ce qu'on est sur ? https://www.figma.com/design/DSfSIVNOCNHi76JeVuSo5T?node-id=569-12989#955543505
