### ISSUE TITLE
Bug 3239 sur la page résultat

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#6180]
Éléments saisis :
-    Ancienneté selon le code du travail : Plus de 2 ans
-    Licenciement pour faute grave : Non
-    Reconnu en tant que travailleur handicapé : Non
-    Catégorie professionnelle : Salariés du particulier employeur
-    Ancienneté selon la convention collective : 2 ans ou plus
-    Convention collective : Particuliers employeurs et emploi à domicile

Ici on affiche "Il s’agit de la durée la plus longue entre la durée légale prévue par le Code du travail et la durée conventionnelle prévue par la convention collective :" alors qu'on devrait avoir "La durée prévue par le code du travail est le même que celle prévue par la convention collective :"
![Image](https://github.com/user-attachments/assets/c93ab20e-f036-48cd-b927-f07ef02b4b69)

Ajouter un TU

**Comment by m-maillot** [comment]
Ce n'est pas un bug mais une feature. Aujourd'hui, on affiche la phrase à titre indicatif. Peut être tourner la phrase autrement ? Ou alors il faut le gérer mais je ne sais pas si ça vaut le coup de le faire avant le passage en DSFR.
