### ISSUE TITLE
Bug - Quand je clique sur une suggestion, cela ne met pas à jour le champs de recherche

### ISSUE THREAD

**Issue by yfmadaule** [SocialGouv/code-du-travail-numerique#619]
A vérifier si mise à jour des résultats quand clic sur une autre suggestion

Testé ce matin sur la dev 2.1.0

**Comment by lionelB** [comment]
bien vu !

**Comment by ClementChapalain** [comment]
j'ajoute au sprint 13 et je ferme la tâche #597 du coup, merci

**Comment by lionelB** [comment]
fixed by #617
