### ISSUE TITLE
[WIP] nouvelle passe articulation des sources hiérarchie des normes

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#62]
n°texte |   | CHAMP | dixit | principe syn
-- | -- | -- | -- | --
L2251-1 |   | accord de branche/loi     CCN/ Loi     Accord d'entreprise/loi     Convention d'entreprise/loi | Une convention ou un accord peut   comporter des stipulations plus favorables aux salariés que les dispositions   légales en vigueur. Ils ne peuvent déroger aux dispositions qui revêtent un   caractère d'ordre public. | principe de faveur: Conventions   collectives, accords de branche, convention d'entreprise, accord d'entreprise   peuvent prévoir des dipositions plus favorables que la loi en vigueur.
L2252-1   alinéa 1 | règles générales accords   conventions branche entreprise | principe de spécialité,   négociation collective | Une convention de branche ou un accord   professionnel ou interprofessionnel peut comporter des stipulations moins   favorables aux salariés que celles qui leur sont applicables en vertu d'une   convention ou d'un accord couvrant un champ territorial ou professionnel plus   large, sauf si cette convention ou cet accord stipule expressément qu'on ne   peut y déroger en tout ou partie. | un accord/convention territorial   ou catégoriel peut être moins favorable qu'un accord/convention plus général   ou moins spécial.
L2252-1   alinéa 2 | règles générales accords   conventions branche entreprise | principe de spécialité,   négociation collective | Lorsqu'une convention ou un   accord de niveau supérieur à la convention ou à l'accord intervenu est   conclu, les parties adaptent les stipulations de la convention ou accord   antérieur moins favorables aux salariés si une   stipulation de la convention ou de l'accord de niveau supérieur le prévoit   expressément. | L'accord/conveniton   spérieurl'accord antérieur, inférieur et moins favorable est adapté
L2253-1 | bloc1 | articulation branche/entreprise |   | Primauté branche
L2253-2 | bloc2 | articulation branche/entreprise |   | Primauté de l'entrepsie sauf   clause de verrouillage
L2253-3 | bloc3 | articulation branche/entreprise |   | Primauté entreprise
L2253-4 | salaire | articulation branche/entreprise | Sans préjudice des dispositions   de l'article L. 2253-3, les clauses salariales d'une convention ou d'un   accord d'entreprise ou d'établissement peuvent prévoir des modalités   particulières d'application des majorations de salaires décidées par les   conventions de branche ou les accords professionnels ou interprofessionnels   applicables dans l'entreprise.     Toutefois, d'une part, l'augmentation de la masse salariale totale doit   être au moins égale à l'augmentation qui résulterait de l'application des majorations   accordées par les conventions ou accords précités pour les salariés   concernés, d'autre part, les salaires minima hiérarchiques doivent être   respectés. |  
L2253-5 |   | articulation accords de groupe,   entreprise, établissements. Même objet | Lorsqu’un accord le prévoit   expressément des dispositions, ayant le même objet     Des accords conclus au niveau :     Se substituent en tout ou partie à ceux conclus au niveau   (antérieurement/postérieuremen):      Du groupe     De l’entreprise     Art. L2253-5     D’entreprise     De l’établissement     Art. L2253-6     de plusieurs entreprises     Des entreprises et établissement compris dans le périmètre de   l’accord     Art. L2253-7 | En principe: l'accord   d'entreprise > accord de groupe; sauf clause de verrouillage dans l'accord   de groupe. Si accord de groupe verrouille : l'accord de groupe > accord   d'entreprise     si et seulement si : l'entreprise comprise dans le périmètre de l'accord
L2253-6 |   | articulation accords de groupe,   entreprise, établissements. Même objet | Lorsqu’un accord le prévoit   expressément des dispositions, ayant le même objet     Des accords conclus au niveau :     Se substituent en tout ou partie à ceux conclus au niveau:      Du groupe     De l’entreprise     Art. L2253-5     D’entreprise     De l’établissement     Art. L2253-6     de plusieurs entreprises     Des entreprises et établissement compris dans le périmètre de   l’accord     Art. L2253-7 | en principe: l'accord   d'établissement> accord d'entreprise.     Sauf clause de verrouillage dans l'accord d'entreprise.     Si et seulement si: l'établissement compris dans le périmètre de l'accord.
L2253-7 |   | articulation accords de groupe,   entreprise, établissements. Même objet | Lorsqu’un accord le prévoit   expressément des dispositions, ayant le même objet     Des accords conclus au niveau :     Se substituent en tout ou partie à ceux conclus au niveau:      Du groupe     De l’entreprise     Art. L2253-5     D’entreprise     De l’établissement     Art. L2253-6     de plusieurs entreprises     Des entreprises et établissement compris dans le périmètre de   l’accord     Art. L2253-7 | En principe: l'accord   d'entreprise et accord d'établissment> accord interentrprise; sauf clause   de verrouillage dans l'accord interentreprise. Si accord de groupe verrouille
L2254-1 |   | ACCORD COLLECTIF et le Contrat de   travail | Lorsqu'un employeur est lié par   les clauses d'une convention ou d'un accord, ces clauses s'appliquent aux   contrats de travail conclus avec lui, sauf stipulations plus favorables. | La convention ou l'accord moins   favorable que le contrat de travail n'est pas opposable au salarié.
L2254-2 |   | ACCORD COLLECTIF et le Contrat de   travail |   | Accord "emploi":   l'accord peut déroger au contrat de travail et peut être opposable même moins   favorablement
L2254-3 |   | ACCORD COLLECTIF et le Contrat de   travail |   |  
L2254-4 |   | ACCORD COLLECTIF et le Contrat de   travail |   |  
L2254-5 |   | ACCORD COLLECTIF et le Contrat de   travail |   |

**Comment by jrduscher** [comment]
> Bloc 1: il n'existe pas de moyen juridique pour détecter des "garanties au moins équivalentes" qui peuvent exister dans un accord d'entreprise.(in fine savoir si ce dernier prime sur la ccn.
> Certains thèmes du bloc 1 pourraient relever de l’exclusivité de la branche plutôt que de la primauté de l'accord ou la convention de branche.

>Bloc 2:  clauses de verrouillage : pas de possibilité d'identifier les clauses de verrouillages dans un accord. (de savoir si une branche a verrouillé un/des/les thèmes du bloc 2). précisions: les clauses de verrouillages anciennes ne subsistent pas avec l'ordonnance.

>bloc 3: L'accord d'entreprise prime sur les accords et conventions de branche; sauf ordre public absolu, sauf partie 4 du code du travail? 
* **Exclure les dispositions d'ordre public de la maquette qui ont été identifiées depuis la loi trav.( archi OP,CDC, DS)**
*** exclure provisoirement la partie 4 du code du travail
*** prévoir un disclaimer sur le contenu de l'accord d'entreprise***

> Prévoir un mécanisme permettant le renvoi systématique vers les SR dès lors que la réponse personnalisée renvoie aux accords d'entreprise ou selon la difficulté des contrats de travail.

**Comment by jrduscher** [comment]
/!\ BLOC 1 ( CCN>AE sauf si AE "garanties au moins équivalentes") - L2253-1.
Pour certains thèmes, CCN>AE, **uniquement si "étendu".

BLOC 1 : 

Il s’agit des 13 domaines listés à l’article L. 2253-1:

6° Les mesures suivantes relatives à la durée du travail, à la répartition et à l’aménagement des horaires : 

- régime d’équivalence (*), 

- nombre d'heures entraînant la qualification de travailleur de nuit (*),

- en matière de temps partiel :
            durée minimale de travail (*), 
              Majoration des heures complémentaires (*), 
              complément d’heures par avenant (*);
7° Les mesures suivantes relatives aux contrats de travail à durée déterminés et aux contrats de travail temporaire : 
durée total du contrat (*),

nombre maximal de renouvellement (*), 

délai de carence (*); 
8° Les mesures relatives au contrat à durée indéterminée de chantier ou d’opération (*);

10° Les conditions et les durées de renouvellement de la période d’essai (*) ;


12° Les cas de mise à disposition d’un salarié temporaire auprès d’une entreprise utilisatrice lorsque la mise à disposition vise à favoriser le recrutement de personnes sans emploi rencontrant des difficultés sociales et professionnelles particulières ou lorsque l’ETT et l’EU s’engage à assurer un complément de formation professionnelle (*);

13° portage salariale :
- La rémunération minimale du salarié porté 
- Le montant de l’indemnité d’apport d’affaire (*) ;

**Comment by jrduscher** [comment]
BLOC 1:
CCN> AE. Primauté absolue de l'accord de branche dans plusieurs domaines du bloc 1?
-les points du bloc 1 sur la dure du travail
- les points qui concernent CDD et CTT. 
-CDI de chantier

**Comment by jrduscher** [comment]
Constat: les champs telles que le transfert de contrat de travail ou le télétravail n'apparaissent que dans la partie générique du contrat de travail, ces dispositions tendent donc à s'appliquer quel que soit le type de contrat. L'application de la règle "Le particulier prime sur le général" pourrait servir à améliorer la pertinence des recherches effectués, et des questions posées.

En matières de contrat de travail par exemple, les dispositions relatives à chaque types de contrats se substituent à celles prévues pour le CDI à concurrence.
Pour chaque type de contrat, on va donc retrouver:
-> des dispositions spécifiques qui se substituent aux dispositions générales du contrat 
-> des dispositions particulières propres au contrat spécifiques ( ex: motifs de recours au CDD...)
-> des dispositions génériques du contrat de trvaail qui s'appliquent en l'absence de dispositions particulières. ( dispositions sur le télétravail, le transfert du contrat....)

Une approche pertinente pourrait être contruite comme suit:
-> ciblages des parties du code du trvail et des articles propres à chaque types de contrat de travail. ( CDD, CTT, contrat d'apprentissage, CUI-CAE, CUI-CIE ( règles applicables du cdd ou cdi sauf là  enocre en casd de dispositons particulière), contrat saisonnier, contrat de chantier, contrat de professionnalisationà
-> ciblage des parties relatives au contrat de travail en général.

contrat de travail appelle type de contrat. L'user choisit le contrat de travail dont il dépend.

Le terme recherché par l’utilisateur est recherché dans les textes propores u contrat de travail  spécifique et au contrat de travail particulier. Si le terme est retrouvé dans les deux blocs ( ex: période d'essai règles génériques du contrat de travail et CDD période d'essai): ne seront proposés que les termes relevant du contrat spécifique.( ex CDD).

**Comment by jrduscher** [comment]
Contrat de professionnalisation.
principe peut être en cdi ou cdd.
principe: les dispositions du code du travail sont applicables aux salariés en contrat de professionnalisation, sauf si elles sont incompatibles  avec les exigences de formation. (qui l'apprécie?)

Si CDD: articles CDD applicables sauf articles spécifiques: renouvellement du cdd article L6325-7 >(articles CDD : L1243-5; L1243-9;   L1243-8; L1243-10; L1243-7; L1243-6)
donc: en CONTRAT DE PROFESSIONNALISATION: CDD. 
dispositions spé contrat pro dispositions CDD, dispositions code du travail sur les autres thèmes.

CUI-CAE et CUI- CIE:
même principe.
CDi ou CDD: les règles du CDI ou du CDD s'appliquent, sauf précisions spé pour dnas les articles CUI-CIE ou CUI- CAE, les autres dipositions du cdtl s'appliquent.

**Comment by jrduscher** [comment]
Dispositions jeunes travailleurs: principe de spécialité
Dipositions jeunes travailleurs, si rien: code du travail

**Comment by jrduscher** [comment]
ajouter la liste des travaux danegreux : https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=LEGITEXT000006081686
liste des travaux inslabures : https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=LEGITEXT000006081686

**Comment by jrduscher** [comment]
Article 1162 CODE CIVIL 
Le contrat ne peut déroger à l'ordre public ni par ses stipulations, ni par son but, que ce dernier ait été connu ou non par toutes les parties.

**Comment by jrduscher** [comment]
Articulation accord de branche et d'entreprise:
**Bloc1** L2253-1: Convention collectives et accords de branche > accords d'éts, d'entreprise ou de groupe; sauf "garanties au moins équivalentes". La DGT confirme la primauté des CCN dans le sens du texte et va au delà en sacralisant parmi ces thèmes ceux où l’accord d’entreprise ne peut pas intervenir:

"1° Les salaires minima hiérarchiques ;": [ pas d'article dans le code du travail, mais le terme existe dans les CCN],  

2° Les classifications ; [ pas d'article dans le code du travail, mais le terme existe dans les CCN]

3° La mutualisation des fonds de financement du paritarisme ; l’accord d’entreprise ne peut pas intervenir

4° La mutualisation des fonds de la formation professionnelle ;l’accord d’entreprise ne peut pas intervenir

5° Les garanties collectives complémentaires mentionnées à l'article L. 912-1 du code de la sécurité sociale ;**[ L912 code de  la sécurité sociale: , ou terme "complémentaire santé obligatoire" dans la CCN]**

6° Les mesures énoncées à l'article L. 3121-14: _équivalences_  [20505] l'accord entreprise ne peut pas intervenir
 au 1° de l'article L. 3121-44: période supérieure à la semaine [19600], champ de la négociation collective) l’accord d’entreprise ne peut pas intervenir
_Position DGT: caractère impértif de la convention ou l'accord de branche_Ce que dit le texte:
 "En application de l'article L3121-41(aménagement  du temps de travail supérieur à la semaine, ordre public),un accord d'entreprise ou d'établissement ou à défaut une convention ou un accord de branche, " sauf pour le 1° concernant La période de référence, qui ne peut excéder un an ou 3 avec un accord de branche".  période de référence, aménagement supérieur à la semaine."



à l'article L. 3122-16: qualification du travailleur de nuit, (champs de la négociation) [21642], l’accord d’entreprise ne peut pas intervenir

 au premier alinéa de l'article L. 3123-19 (champs de la négociation collective) [21548] défintiion de la durée du travail minimale pour un, travail à temps partiel, garanties si inf à 24 heures et cumul d'activité ( dispo supp) l’accord d’entreprise ne peut pas intervenir
 aux articles L. 3123-21: majoration des heures complémentaires [21552] l’accord d’entreprise ne peut pas intervenir
 et L. 3123-22 du présent code et relatives à la durée du travail, à la répartition et à l'aménagement des horaires ; [21556] possibilité d'allonger temporairement la durée du travail par avenant/ l’accord d’entreprise ne peut pas intervenir

7° Les mesures relatives aux contrats de travail à durée déterminée et aux contrats de travail temporaire énoncées aux articles L. 1242-8, [49501]l’accord d’entreprise ne peut pas intervenir
L. 1243-13,  nombre maximal de renouvellements du CDD, [50400]l’accord d’entreprise ne peut pas intervenir
 L. 1244-3, [50900] l’accord d’entreprise ne peut pas intervenir
 L. 1244-4, [50902] l’accord d’entreprise ne peut pas intervenir
L. 1251-12,durée totale du contrat de mission, [51901] l’accord d’entreprise ne peut pas intervenir
 L. 1251-35, renouvellement du contrat de mission ( travail temporaire) [52200] l’accord d’entreprise ne peut pas intervenir
L. 1251-36 contrat de mission, successions, délai de carence [52600]
et L. 1251-37  contrat de mission, successions, délai de carence cas ou il est inapplicable [52602]  l’accord d’entreprise ne peut pas intervenir

8° Les mesures relatives au contrat à durée indéterminée de chantier ou d'opération énoncées aux articles
 L. 1223-8 et L. 1223-9 : contrat à durée indéterminée de chantier ou d'opération [12800] l’accord d’entreprise ne peut pas intervenir
9° L'égalité professionnelle entre les femmes et les hommes ; [ art....]

10° i mentionnées à l'article L. 1221-21 du code du travail ; Les conditions et les durées de renouvellement de la période d'essai [3760] l’accord d’entreprise ne peut pas intervenir

11° Les modalités selon lesquelles la poursuite des contrats de travail est organisée entre deux entreprises lorsque les conditions d'application de l'article L. 1224-1 ne sont pas réunies ; l’accord d’entreprise ne peut pas intervenir

12° article  L. 1251-7, cas de recours contrat de mission; du présent code ;[51400] l’accord d’entreprise ne peut pas intervenir

13° La rémunération minimale du salarié porté, ainsi que le montant de l'indemnité d'apport d'affaire, mentionnée aux
articles L. 1254-2 :[51235] l’accord d’entreprise ne peut pas intervenir
 et L. 1254-9 du présent code ;[ 51210] l’accord d’entreprise ne peut pas intervenir


**BLOC 2:**  Clauses de verrouillage: CCN>AE sur 4 thèmes :si la ccn le décide explicitement et si AE plus récent que CCN.

1° La prévention des effets de l'exposition aux facteurs de risques professionnels énumérés à l'article L. 4161-1 ; ( 162100)

2° L'insertion professionnelle et le maintien dans l'emploi des travailleurs handicapés ;

3° L'effectif à partir duquel les délégués syndicaux peuvent être désignés, leur nombre et la valorisation de leurs parcours syndical ;

4° Les primes pour travaux dangereux ou insalubres.


**BLOC 3 :** 

dans les autres matières que celles des blocs 1 et des blocs 2: 
Les accords d'entreprises quelle que soit leurs dates de conclcusion  prévalent sur les conventions collectives.
A défaut d'accord d'entreprise , les disposition issues de accords et convetions collecitves trouvent pleinement à s'appliquer de pleijn d roit

**Comment by ClementChapalain** [comment]
Tout le contenu est disponible ici : https://github.com/SocialGouv/code-du-travail-numerique/wiki/%5BProduit%5D-%5BHi%C3%A9rarchie-des-normes%5D-Articulation-des-sources

Je ferme car il faudra a priori redécouper le sujet.
