### ISSUE TITLE
fix ES stemming

### ISSUE THREAD

**Issue by adipasquale** [SocialGouv/code-du-travail-numerique#622]
![](http://g.recordit.co/as9ukYgVrp.gif)

frigori -> aucun resultats
frigorif -> ca matche
frigorifi -> aucun resultats (edited)

**Comment by ClementChapalain** [comment]
avec le remplacement par le moteur d'autosuggest, est-ce que c'est toujours un problème ?

**Comment by ClementChapalain** [comment]
ah en fait je viens de vérifier je pense que dans la recherche de convention collective on a toujours le souci en revanche

**Comment by adipasquale** [comment]
Exactement


On 24 March 2019 at 19:32:20, Clément Chapalain (notifications@github.com) wrote:

ah en fait je viens de vérifier je pense que dans la recherche de convention collective on a toujours le souci en revanche
