### ISSUE TITLE
Module Trouver sa CC

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#6231]
Développer le module trouver sa CC sur la page des conventions collectives

**Comment by Viczei** [comment]
Afficher "pas de résultat" en blue lorsque la recherche comporte uniquement 2 caractères

**Comment by Viczei** [comment]
- Ajout dans le hint de l'input siren/siret: Présent dans la fiche de paie
- Gérer les erreurs si nombre de chiffre siren/siret pas bon

**Comment by Viczei** [comment]
- [x] Accessibilité Autocomplete
- [x] performance changement de page recherche CC
- [x] Le bouton Rechercher par entreprise apparait à ce moment. Puis il ne disparait plus jamais
- [x] j'ai le bouton Rechercher par entreprise qui apparait. Si je clique dessus et que je fais précédent, je reviens sur la page principale de l'outil
- [ ] En mobile sur recherche par CC : Quand je clique sur le champ pour chercher, le clavier cache à moitié le champ et les résultats.
- [x] De plus, on a l'icone loupe sur le clavier qui indique l'action de rechercher mais quand on clique dessus rien ne se passe.
- [ ] Sur la recherche CC, on a les mêmes erreurs HTML que sur la recherche.
- [x] Sur rechercher par entreprise Quand je saisie un code postal invalide, je n'ai pas de retour
- [x] Sur le recherche par entreprise Appuyer sur le bouton rechercher sans rien saisir, rien ne se passe
- [x] Recherche par entreprise: Gérer le pluriel sur les résultats
- [x] Recherche par entreprise : Quand je sélectionne une entreprise après une recherche et que je fais précédent, j'ai perdu ma recherche
- [x] Recherche par entreprise : En utilisant le clavier seulement, quand je sélectionne une ville, je valide avec Entrée. Si je refais Entrée, elle s'efface
- [x] Recherche par entreprise : Lors de la sélection de la CC, si elle est disponible sur le site, avec un lien legifrance mais pas traité (pas de contribs, kali-bloc...), on doit afficher un message différent
- [x] Recherche par entreprise : Lors de la sélection de la CC, si la CC est désactivée, on peut quand même cliquer dessus
- [ ] Recherche par entreprise sur mobile : Par contre, je reste sur le champ code postal. Je devrais arriver sur les résultats plus bas.
- [x] Recherche par entreprise sur mobile (mode landscape) : Le design a quelques bugs
- [x] Recherche par entreprise : Petit soucis sur l'ordre des headings
- [x] Modifié l'url en /outils/convention-collective/entreprise/[SLUG]
- [x] Mettre en no-index
- [x] gérer 404 selection entreprise
