### ISSUE TITLE
Fiche service-public

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/code-du-travail-numerique#6232]
Urls de tests

https://code-du-travail-numerique-carolinebda-dsfr-fiche-sp-mhm42bu2.ovh.fabrique.social.gouv.fr/fiche-service-public/arret-maladie-pendant-le-preavis-quelles-consequences

**Tableaux + Service en ligne**
https://code-du-travail-numerique-carolinebda-dsfr-fiche-sp-mhm42bu2.ovh.fabrique.social.gouv.fr/fiche-service-public/combien-de-trimestres-un-salarie-doit-il-avoir-pour-avoir-sa-retraite-a-taux-plein

**Ou s'adresser**
https://code-du-travail-numerique-carolinebda-dsfr-fiche-sp-mhm42bu2.ovh.fabrique.social.gouv.fr/fiche-service-public/victime-de-lamiante-comment-etre-indemnise

**Images**
https://code-du-travail-numerique-carolinebda-dsfr-fiche-sp-mhm42bu2.ovh.fabrique.social.gouv.fr/fiche-service-public/jour-ouvrable-jour-ouvre-jour-franc-jour-calendaire-quelles-differences

**Bloc Cas + Tabs**
https://code-du-travail-numerique-carolinebda-dsfr-fiche-sp-mhm42bu2.ovh.fabrique.social.gouv.fr/fiche-service-public/contrat-dapprentissage#quel-est-le-salaire-de-lapprenti

**Bloc cas avec des titres dupliqués**
 "Jour férié habituellement chômé" https://code-du-travail-numerique-carolinebda-dsfr-fiche-sp-mhm42bu2.ovh.fabrique.social.gouv.fr/fiche-service-public/jour-ouvrable-jour-ouvre-jour-franc-jour-calendaire-quelles-differences

**Complément**

Accordéon :  Comment calculer la réduction générale des cotisations patronales ? 
Section : Calcul du coefficient de réduction appliqué à la rémunération

https://code-du-travail-numerique-carolinebda-dsfr-fiche-sp-mhm42bu2.ovh.fabrique.social.gouv.fr/fiche-service-public/reduction-generale-des-cotisations-patronales-ex-reduction-fillon

**Exemple**

Accordéon : Comment se calcule l'indemnité de licenciement ?
Section : Ancienneté inférieure à 10 ans

https://code-du-travail-numerique-carolinebda-dsfr-fiche-sp-mhm42bu2.ovh.fabrique.social.gouv.fr/fiche-service-public/indemnite-de-licenciement-du-salarie-en-cdi

**Comment by carolineBda** [comment]
Après l'update de l'API :
- revoir l'affichage des services en ligne + PourEnSavoirPlus : https://code-du-travail-numerique-preprod.ovh.fabrique.social.gouv.fr/fiche-service-public/contrat-dapprentissage#quelle-est-la-duree-du-contrat-dapprentissage

![Image](https://github.com/user-attachments/assets/342991c6-b82d-41f3-aaa7-3b455f6368f1)

- Vérifier pourquoi l'Avertissement est affiché en haut (alors qu'il est en abs sur service-public): https://code-du-travail-numerique-preprod.ovh.fabrique.social.gouv.fr/fiche-service-public/contrat-dapprentissage
- Enlever les accordéons des encarts Ou s'adresser?

**Comment by carolineBda** [comment]
Elements de bas de page. On garde seulement les refs juridiques. Le filtre ce fait dans l'admin.

| Encart Fiche SP | JSON | CDTN
| -- | -- | -- |
| Textes de loi et références | `Reference` | Références juridiques concernées
| Service en ligne est formulaire | `ServiceEnLigne` | _exclue volontairement_
| Questions ? Réponses ! | `QuestionReponse` | _jamais implémenté_
| Voir aussi | `VoirAussi` | _jamais implémenté_
| Voir aussi | `PourEnSavoirPlus` | affiché en bas de page

**Comment by m-maillot** [comment]
Page : https://code-du-travail-numerique-carolinebda-dsfr-fiche-sp-mhm42bu2.ovh.fabrique.social.gouv.fr/fiche-service-public/indemnite-de-licenciement-du-salarie-en-cdi

Onglet : Quelles sont les conditions d'attribution de l'indemnité de licenciement ?

Il manque un espace après un texte en gras : 
![Image](https://github.com/user-attachments/assets/33301788-2e72-4710-af80-c077a3f93c1b)

Bug déjà présent en prod.

=> Sur toutes les autres fiches ils ajoutent un espace eux même dans le texte et sur celle la ils ne l'ont pas fait. Je propose de laisser tel quel

**Comment by m-maillot** [comment]
Les headings sont très étranges avec le composant tab de DSFR : 

![Image](https://github.com/user-attachments/assets/63fe71e9-3179-4483-8d01-6748a26a0ee3)

sur service-public.fr, ça fonctionne

![Image](https://github.com/user-attachments/assets/af857b38-7694-4909-8ca2-abeac3e4152b)


Il semble qui manque des tags aria-labelledby avec des id chez nous

**Comment by m-maillot** [comment]
Sur cette page : https://code-du-travail-numerique-carolinebda-dsfr-fiche-sp-mhm42bu2.ovh.fabrique.social.gouv.fr/fiche-service-public/rupture-conventionnelle

Dans les références juridiques, il y a des références vers le site travail emploi mais les liens ne s'ouvrent pas dans une nouvelle fenêtre et il manque le logo pour dire que l'on quitte le site.

**Comment by m-maillot** [comment]
Sur cette page : https://code-du-travail-numerique-carolinebda-dsfr-fiche-sp-mhm42bu2.ovh.fabrique.social.gouv.fr/fiche-service-public/comment-sinformer-sur-sa-retraite

Dans l'accordéon : Connaissez-vous Info-retraite, le site officiel public commun à tous les régimes de retraite ?

Il y a normalement une vidéo. L'info est maintenant dispo avec la nouvelle version des données. Cela pourrait être sympa d'ajouter un lien vers la vidéo.

**Comment by m-maillot** [comment]
Sur cette page : https://code-du-travail-numerique-carolinebda-dsfr-fiche-sp-mhm42bu2.ovh.fabrique.social.gouv.fr/fiche-service-public/labsence-du-salarie-est-elle-prise-en-compte-pour-le-calcul-de-ses-conges

Dans la page DSFR, dans le caption, il préfixe avec `Tableau - `. Je ne sais pas si c'est important mais comme ils sont full compliant, ça peut valoir le coup de demander à Marie. Perso, je n'ai rien trouvé sur le sujet.

Il y a également les listes en bas qui ont un espace important. Ce serait bien de le retirer comme sur service public.
