### ISSUE TITLE
Créer un système de classification du contenu

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#626]
Première étape de la classification des contenus (cf. tâche #xxx)

L'objectif est de créer un système de classification des contenus par thème propre au CDTN. Ces thèmes seront utilisés pour proposer une navigation thématique et pour proposer du contenu pertinent relatif à un thème rattaché à une requête.

La classification WIP est disponible ici :
https://docs.google.com/spreadsheets/d/1CVRrR45QIlSzVeO_9V1TUXSqI1U9Bt5_KYWlcH9K2jI/edit#gid=1783422693

Le document récapitulant le travail sur la classification est disponible ici :
https://docs.google.com/presentation/d/1jCcJi3mCnl7A7fnSlu17oXT73cOgEbL5YNHrxbTpY-Q/edit#slide=id.g5466f0762e_0_0

**Comment by lionelB** [comment]
Est ce qu'on peut mettre un lien vers la classification ? 

@ClementChapalain n'hésite pas à mettre un petit mot quand tu fermes une issue pour aider à savoir la cause de la fermeture

**Comment by ClementChapalain** [comment]
oui tu as raison désolé !
https://docs.google.com/spreadsheets/d/1CVRrR45QIlSzVeO_9V1TUXSqI1U9Bt5_KYWlcH9K2jI/edit#gid=1783422693
