### ISSUE TITLE
Dossier d'architecture pour la certification RGS

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#629]
Nous allons commencer un dossier d'architecture pour la DSI afin de connaitre le process pour la validation RGS.

**Comment by ClementChapalain** [comment]
Hello @revolunet vous avez pu avancer sur ce sujet ?

**Comment by lionelB** [comment]
@revolunet on voit lionel d'elastic vendredi, est ce qu'on prépare ça jeudi ? ou plutôt dans le semaine ?

**Comment by revolunet** [comment]
Une première version du dossier "DSI" est bientôt prête.

Pour aller vers le RGS, je propose qu'on fasse asap un 1er atelier en suivant le [guide de sécurité numérique agile](https://www.ssi.gouv.fr/uploads/2018/11/guide-securite-numerique-agile-anssi-pa-v1.pdf)

**Comment by lionelB** [comment]
on ferme l'issue une fois l'atelier fait ?

**Comment by ClementChapalain** [comment]
je prends l'orga de cette tâche, la semaine prochaine pour l'atelier je pense
