### ISSUE TITLE
Filtrer dans les fiches les éléments fonction publique

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#63]
Filtrer les éléments fonction publique pour gagner  -un peu- en pertinence. 

'Accident du travail',//FP
'Allocation de soutien familial (ASF)',
'Allocations',
'Allocations versées à partir du 1er enfant',
'Allocations versées à partir du 2e enfant',
'Aménagement du temps de travail',
'Arrêt maladie',
'Astreintes et permanences',
"Autorisations d'absence pour événement familial",
'Autorisations provisoires de séjour (1, 3 ou 6 mois)',
'Autres motifs de départ',
'Autres types de recrutement',
'Avant la retraite',
'Capital décès',
'Carte de résident (10 ans)',
'Carte de séjour pluriannuelle',
'Carte de séjour pour Européen',
'Carte de séjour temporaire/pluriannuelle (1 à 4 ans)',
'Certificat de résidence pour Algérien',
'Compte épargne-temps (CET)',
'Conditions de travail : informations diverses',
'Congés et absence pour formation',
"Congés liés à l'arrivée d'un enfant",
"Congés pour maladie, handicap ou dépendance d'un membre de la famille",
'Congés spécifiques',
"Conseil de prud'hommes",
'Contrat temporaire',
'Contrat à durée déterminée (CDD)',
'Contrat à durée indéterminée (CDI)',
'Cotisations salariales',
'Disponibilité',
'Dispositifs',
"Dispositifs d'accès à la formation",
'Document de circulation pour mineur étranger',
'Documents à remettre au salarié',
'Droit des fonctionnaires',
'Durée du travail',
"Déclaration de revenus : mode d'emploi",
'Départ à la retraite anticipé',
'Déroulement',
'Déroulement de carrière',
'Détachement',
'Enfant gardé par un parent',
'Enfant gardé par un tiers',
"Exercice d'une autre activité",
"Fonction publique d'État (FPE)",//FP
'Fonction publique hospitalière (FPH)',//FP
'Fonction publique territoriale (FPT)',//FP
"Fonctionnement de l'établissement",
'Formes de rupture',
'Garde nationale et volontariat dans les armées',
'Heures supplémentaires',
'Heures supplémentaires, équivalence et astreintes',
'Horaires et programmes',
'Hygiène, sécurité et conditions de travail',
'Indemnité de départ volontaire',
'Indemnités',
'Inscription au collège et au lycée',
'Intéressement et participation',
'Jours non travaillés',
'Licenciement',
'Maladie professionnelle',
"Maladie, handicap ou dépendance d'un membre de la famille",
"Mesures d'accompagnement",
'Mise à disposition',
"Mobilité en position d'activité",
'Notation - Évaluation',
'Obligations des fonctionnaires',//FP
'Parcours scolaire et orientation',
'Participation des parents à la vie scolaire',
'Participation des élèves à la vie scolaire',
'Participation à la sécurité civile',
'Pension de retraite',
'Pension de retraite complémentaire',
'Pension de retraite de base',
'Pension du secteur privé',
'Pension du secteur public',//FP
'Pensions, retraites et rentes imposables',
"Plans d'épargne salariale",
'Pour un contractuel',
'Pour un fonctionnaire',//FP
'Prise en charge des frais de transport',
'Procédure de licenciement',
'Protection fonctionnelle',//FP
'Protections spécifiques',
'Prévention des licenciements',
'Quotient familial selon la situation personnelle',
'Quotient familial selon les personnes à charge',
"Recrutement d'un agent contractuel",//FP
"Recrutement d'un fonctionnaire",//FP
'Rentes',
'Repos',
'Retraite à taux plein',
'Revenus fonciers et mobiliers',
'Rémunération fixe',
'Rémunération soumise à conditions',
'Réserve civique',
'Salaires et éléments du salaire',
'Service civique',
'Situation des agents contractuels',
'Travail de nuit',
'Travail à temps partiel',
'Trimestres de retraite',
'Vie quotidienne',
'Âge de départ à la retraite',
'Étudiant / Stagiaire étranger'

**Comment by revolunet** [comment]
intention : déprioriser les résultats contenant "service public" si ce terme n'est pas dans la requête

**Comment by lionelB** [comment]
@UnbearableBear Est ce que tu peux préciser pourquoi tu as fermé l'issue ?
