### ISSUE TITLE
Modifications formulaire feedback

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#631]
Problèmes rencontrés avec le système de feedback actuel :
- Les derniers tests utilisateurs nous ont appris que le bouton " 👍/ 👎" n'était pas très clair ("on peut liker des articles ?")
- Il a été décidé au dernier COPIL que les questions de droit devaient être redirigées vers les services de renseignement
- Il y a une confusion actuellement sur le formulaire de feedback qui propose à l'usager de "poser sa question" puis ensuite lui demande un retour sur le contenu et le service

Propositions :

### 1. changement du formulaire de feedback
Réponse par oui ou non avec potentiellement ajout de commentaires libres et redirection vers les services de renseignement si la réponse est non.

voir https://www.figma.com/proto/UGkd7UFF3gJSb3a35ClTtPKW/maquette?node-id=67%3A0&viewport=550%2C-209%2C0.31681&scaling=min-zoom

1. question initiale :
![image](https://user-images.githubusercontent.com/5337489/54938380-89c12980-4f26-11e9-91e5-6c4a63994caf.png)
2. oui
![image](https://user-images.githubusercontent.com/5337489/54938397-934a9180-4f26-11e9-90f0-9b4ac818fb3b.png)
3. oui + commentaire envoyé
![image](https://user-images.githubusercontent.com/5337489/54939022-d822f800-4f27-11e9-9ca8-53776495bbc9.png)
4. non
![image](https://user-images.githubusercontent.com/5337489/54938784-5df27380-4f27-11e9-8696-4116ba087210.png)
5. non + commentaire envoyé
![image](https://user-images.githubusercontent.com/5337489/54939006-cb060900-4f27-11e9-98f2-6970b35410b3.png)

Pour le fonctionnement du formulaire, a priori on part sur le fait d'avoir deux questionnaires distincts :
- un questionnaire lorsque l'utilisateur répond oui ou non
- un questionnaire lorsque l'utilisateur envoie un commentaire spécifique

Ça va nous permettre de récupérer les informations même si l'utilisateur répond oui / non et n'envoie pas de commentaires.

On peut continuer avec formspree en termes d'outil, on fera un branchement avec spreadsheet pour pouvoir analyser les données. Comme dans l'ancienne version, il faudrait avoir requête utilisateur + ressource en train d'être consulté pour chaque envoi de formulaire.

### 2. suppression du module " 👍/ 👎"
Si nous recueillons la satisfaction sur le contenu grâce au formulaire, nous n'avons plus besoin de ce module

**Comment by lionelB** [comment]
> Comme dans l'ancienne version, il faudrait avoir requête utilisateur + ressource en train d'être consulté pour chaque envoi de formulaire.

l'ancienne version permettait aussi d'accéder au formulaire de feeedback depuis la page de résultats de recherche (en cas de "Pas de résultats")

On supprime ?

**Comment by ClementChapalain** [comment]
je pense que ce formulaire de feedback doit être vraiment spécifique au contenu pour qu'on sahe quels contenus sont ok ou non, après c'est vrai qu'un rebond pour une requête sans résultats serait interessant aussi, mais ce sera surement un rebond plus du style : "contacter les services de renseignement / utilisez la navigation par thèmes"

du coup on peut le virer dans la page de résultats je pense, tu es d'accord ?

**Comment by lionelB** [comment]
ca marche !

**Comment by lionelB** [comment]
@ClementChapalain est ce que ca t'irait si je laisse les 2 boutons (peut être légerement grisé) pour avoir laisser le choix visible avant d'afficher le reste du formulaire ?

**Comment by ClementChapalain** [comment]
oui carrément ! ce serait bien de les disable du coup pour éviter qu'un utilisateur clique plusieurs fois sur les boutons sur la même page et pourrisse les stats.

**Comment by lionelB** [comment]
Ah bien vu ! 
il manque un bouton `annuler` au niveau formulaire pour revenir à l'état initial

**Comment by lionelB** [comment]
@ClementChapalain le lien sur "joindre les services de renseignement", il pointe ou ?

**Comment by ClementChapalain** [comment]
vers cette pop-up :
![image](https://user-images.githubusercontent.com/5337489/55573214-c0a6f480-5709-11e9-9fcc-cbd6a30928fe.png)

**Comment by ClementChapalain** [comment]
J'ai testé ce matin c'est cool :) J'ai quelques questions :
- est-ce qu’on pourrait avoir un autre formulaire formspree qui est envoyé au moment où l’usager clique sur oui / non ? ça permettrait de faire des stats sur les contenus et voir lesquels sont bons / mauvais
- dans le formulaire qui est envoyé quand l’utilisateur écrit un commentaire optionnel, est-ce qu’on pourrait ajouter en champs caché le titre de la réponse qu’il est en train de regarder ? ce serait plus simple que de devoir le cherche dans l’url
- dans le formulaire qui est envoyé quand l’utilisateur écrit un commentaire optionnel, on ne voit pas si l’utilisateur a cliqué sur oui / non avant, ce serait bien de l’ajouter je pense
- je me dis que ce serait mieux si les boutons oui / non disparaissaient carrément une fois qu'on a cliqué dessus, là ça donne l'impression qu'on peut encore les utiliser (p-e le statut "disabled" qui n'est pas très visible aussi). on perd la possibilité de revenir en arrière si l'utilisateur a fait une erreur mais bon c'est pas trop grave on va juste faire des stats dessus on ne va pas regarder réponse par réponse
- la formulation du bouton pour le commentaire optionnel devrait être "envoyer" et non "envoyer ma question" car on a pas prévu de répondre à ces messages c'est juste du feedback sur les contenus
- augmenter un peu la largeur du bloc (cf. design)

**Comment by ClementChapalain** [comment]
je peux faire une / plusieurs issues pour ça si besoin redis moi !

**Comment by lionelB** [comment]
refait une issue avec les modifs, et je ferme celle-là
