### ISSUE TITLE
Remove code-du-travail-css

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#634]
L'idéal serait de le remplacer par un utilitaire en styled-components dans code-du-travail-ui

**Comment by UnbearableBear** [comment]
Roadmap:

- Mettre le fichier themes.js dans un package à part, hors du monorepo.
- Prendre chaque CSS spécifique à un component UI et le rendre "standalone" (Une PR par component)
- Remplacer le mécanisme "flavors" par un utilitaire styled-component ou quelque chose de plus intuitif  (A voir: comment simplifier ce qui a été fait dans le `ToggleButton`).
- Remplacer tous les  `Button` par des  `ToggleButton` (et renommer  `ToggleButton` en  `Button`)
- Ajouter les styles génériques via ce mécanisme ? https://www.styled-components.com/docs/api#createglobalstyle

**Comment by lionelB** [comment]
Pour chaque composant UI,  
- passer les styled en js
- virer le fichier css associé 

pour les flavors, on peut passer par un attribut `variant` <Button variant="primary" />

**Comment by lionelB** [comment]
composant ui 
- [ ] alert
- [ ] badges
- [ ] breadcrumbs
- [ ] button
- [ ] cards
- [ ] categories
- [ ] tags
- [ ] block2cols (utilisé dans `src/components/SeeAlso.js`)
- [ ] layout pour les composant section / container / wrapper 

Global
- [ ] layout
- [ ] conf plus ou moins deja fait avec theme
- [ ] classes

elements (a transformer en composant dans le UIKit
- [ ] forms
- [ ] link
- [ ] table
- [ ] embeded
- [ ] text-level

**Comment by UnbearableBear** [comment]
closed by #948
