### ISSUE TITLE
Composant "Réponse à votre question" - non - message d'erreur non relié à son champ

### ISSUE THREAD

**Issue by Marie-a11y** [SocialGouv/code-du-travail-numerique#6347]
**Description**
Les messages d'erreurs doivent être reliés au champ en le reliant via un attribut aria-describedby 

**Reproduction**
Etapes à suivre pour reproduire le bug

1. Aller à sur toutes les pages contenant le composant "Avez-vous trouvé la réponse à votre question ?", exemple : https://code.travail.gouv.fr/fiche-ministere-travail/la-duree-legale-du-travail
2. Cliquer sur non
3. appuyer sur "envoyer" 
4. inspecter les input des cases à cocher et leur message d'erreur

**Comportement attendu**
ajouter un attribut aria-describedby="xxx" sur les <input type="checkbox"> où "xxx" est la valeur de l'id du message d'erreur. pour avoir : <input type="checkbox" arai-describedby="id="fr-fieldset-checkbox-:r0:-messages"">
soit les deux :)

**Screenshots**
![image](https://github.com/user-attachments/assets/9b8a7351-ee76-4bfe-9e73-4ddeb5417f6b)

**Comment by Viczei** [comment]
Hello @Marie-a11y , sur la documentation dsfr on a un cas de checkbox décrit:
https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/case-a-cocher
Si on suit leur exemple, on a un aria-labelledby avec la valeur "fr-fieldset-checkbox-:r0:-messages" sur le fieldset qui englobe les checkboxs. Est-ce que du coup la doc dsfr n'est pas accessible ?

**Comment by Marie-a11y** [comment]
Hello @Viczei 
Tu as tout à fait raison, je pense être passée à côté de la mise à jour du aria-labelledby lors de la mise en erreur des champs. Désolé pour ce ticket non valable. Je confirme que la methode du DSFR est bonne, tant que la valeur du aria-labelledby contient aussi l'id de la legend (ce qui est bien le cas sur cdn
