### ISSUE TITLE
fiche ministère du travail - liens non pertinent

### ISSUE THREAD

**Issue by Marie-a11y** [SocialGouv/code-du-travail-numerique#6350]
**Description**
un lien peut être pertinent si le texte qui l'entoure ou si le titre précédent associé au nom du lien permet d'en comprendre sa fonction et destination

**Reproduction**
Etapes à suivre pour reproduire le bug

1. Aller à https://code.travail.gouv.fr/fiche-ministere-travail/la-duree-legale-du-travail
2. ouvrir le premier accordéon
3. inspecter les liens "cliquez ici pour voir la vidéo"

**Comportement attendu**

ajouter un attribut title sur les liens des vidéos pour ajouter le nom de la vidéo : 
- title="Cliquez ici pour voir la vidéo La durée du travail - nouvelle fenêtre" (pour la première vidéo)
- title="Cliquez ici pour voir la vidéo Le travail effectif - nouvelle fenêtre" (pour la seconde vidéo)

**Screenshots**
![image](https://github.com/user-attachments/assets/cb9f6523-860b-4ebc-8704-3192fbe2e991)

**Comment by m-maillot** [comment]
L'ajout du nouvelle fenêtre dans le title est planifié dans le ticket : [#6297](https://github.com/SocialGouv/code-du-travail-numerique/issues/6297)

**Comment by carolineBda** [comment]
Bonjour @Marie-a11y j'avais l'impression que répéter l'info dans les `title` des liens pouvait être contre productif : https://www.24joursdeweb.fr/2022/laccessibilite-cest-comme-la-patisserie-il-faut-savoir-doser/

Est-ce que dans ton cas c'est parce qu'on ajoute "nouvelle fenêtre" que c'est intéressant ? Est-ce que les readers ne le détectent pas ?

**Comment by Marie-a11y** [comment]
Bonjour @carolineBda, 
Ma demande est liée à la conformité au RGAA. 
Le nom accessible (créé par l'attribut title) doit reprendre le nom visible (le texte qui est visible) car certaines configuration de lecteurs d'écrans écrase le nom visible par le nom accessible. Si seules les infos additionnelles sont dans le title, il y a un risque que certaines personnes se retrouves avec cela comme seule info pour intitulé de lien. 
tu peux voir cette précision dans la note 2 du glossaire du RGAA pour [intitulé (ou nom accessible) de lien](https://accessibilite.numerique.gouv.fr/methode/glossaire/#intitule-ou-nom-accessible-de-lien)

Une autre solution, la plus robuste en terme d'accessibilité, c'est d'ajouter les informations supplémentaire pour préciser le lien en texte caché avec une class="sr-only" (class CSS permettant d'avoir un texte lu qui n'est pas affiché visuellement). 
ce texte est à ce moment là du texte brut dans le code et fonctionne forcément avec toutes technologies d'assistances. 

Dans le cas de ce ticket, c'est surtout le nom de la vidéo qui m'intéresse d'être ajouté, pour que les liens soient plus clairs. je propose l'utilisation du title, car c'est ce qui est utilisé comme solution sur d'autres liens du site. 
mais ça serait avec plaisir de modifier cela pour mettre en place des textes cachés pour préciser les liens. 

L'ajout du "nouvelle fenêtre" est nécessaire car c'est une info fournie par le pictogramme et donc il faut qu'elle puisse être comprise par tout le monde.

**Comment by carolineBda** [comment]
Merci beaucoup pour ces précisions c'est très claire !

**Comment by Marie-a11y** [comment]
issue fixed
