### ISSUE TITLE
bug taux horaire du smic

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#637]
https://github.com/SocialGouv/code-du-travail-numerique/pull/518
constat: le message direct portant sur le SMIC à Mayotte s'affiche quand on cherche SMIC. Le texte générique ne s'affiche pas.

1: résolution du bug par réglage de ES.

2: à défaut création d'un texte direct SMIC unique. 

texte à ajouter
> [
>   {
>     "question": "Quel est le montant du SMIC ?",
>     "reponse": "<p>Au 1er janvier 2019, le montant du <accronym title='Salaire minimum interprofessionnel de croissance' lang='fr'>SMIC</accronym> brut horaire s'établit:<li>
à <b>10,03&nbsp;€</b> en métropole, en Guadeloupe, en Guyane, en Martinique, à La Réunion, à Saint-Barthélemy, à Saint-Martin et à Saint-Pierre-et-Miquelon.<br/> Soit <b>1521,22&nbsp;€</b> mensuels sur la base de la durée légale du travail de 35 heures hebdomadaires</p></li><li>à <b>7,57&nbsp;€</b> à Mayotte, soit <b>1148,12&nbsp;€</b> mensuel sur la base de la durée légale du travail de 35 heures hebdomadaires.</li></p>",
>     "source": "CDTN",
>     "redacteur": ["JR"],
>     "date": "01/01/2019",
>     "tags": {
>       "themes": [44300],
>       "theme": ["SMIC", "salaire minimum", "rémunération", "salaire"]
>     },
>     "references": [
>       {
>         "url": "https://www.legifrance.gouv.fr/eli/decret/2018/12/19/MTRX1833925D/jo/texte",
>         "titre": "Décret n° 2018-1173 du 19 décembre 2018 portant relèvement du salaire minimum de croissance "
>       }
>     ]
>   },

texte à supprimer
> [
>   {
>     "question": "Quel est le montant du SMIC ?",
>     "reponse": "<p>Au 1er janvier 2019, le montant du <accronym title='Salaire minimum interprofessionnel de croissance' lang='fr'>SMIC</accronym> brut horaire s'établit à <b>10,03&nbsp;€</b> en métropole, en Guadeloupe, en Guyane, en Martinique, à La Réunion, à Saint-Barthélemy, à Saint-Martin et à Saint-Pierre-et-Miquelon.<br/> Soit <b>1521,22&nbsp;€</b> mensuels sur la base de la durée légale du travail de 35 heures hebdomadaires</p>",
>     "source": "CDTN",
>     "redacteur": ["JR"],
>     "date": "01/01/2019",
>     "tags": {
>       "themes": [44300],
>       "theme": ["SMIC", "salaire minimum", "rémunération", "salaire"]
>     },
>     "references": [
>       {
>         "url": "https://www.legifrance.gouv.fr/eli/decret/2018/12/19/MTRX1833925D/jo/texte",
>         "titre": "Décret n° 2018-1173 du 19 décembre 2018 portant relèvement du salaire minimum de croissance "
>       }
>     ]
>   },
>   {
>     "question": "Quel est le montant du SMIC à Mayotte ?",
>     "reponse": "<p>Au 1er janvier 2019, le montant du <accronym title='Salaire minimum interprofessionnel de croissance' lang='fr'>SMIC</accronym> s'établit à <b>7,57&nbsp;€</b> à Mayotte, soit <b>1148,12&nbsp;€</b> mensuel sur la base de la durée légale du travail de 35 heures hebdomadaires.</p>",
>     "themes": [44300],
>     "source": "CDTN",
>     "redacteur": ["JR"],
>     "date": "01/01/2019",
>     "tags": {
>       "theme": ["SMIC", "salaire minimum", "rémunération", "salaire"],
>       "particularisme": "Mayotte"
>     },
>     "references": [
>       {
>         "url": "https://www.legifrance.gouv.fr/eli/decret/2018/12/19/MTRX1833925D/jo/texte",
>         "titre": "Décret n° 2018-1173 du 19 décembre 2018 portant relèvement du salaire minimum de croissance "
>       }
>     ]
>   },
>   {

Texte à maintenir en l'état ( matche bien)
>     "question": "Quel est le montant du minimum garanti ?",
>     "reponse": "<p>Le minimum garanti s'établit à <b>3,62&nbsp;€</b> en métropole, dans les collectivités régies par l'article 73 de la Constitution, à Saint-Barthélemy, à Saint-Martin et à Saint-Pierre-et-Miquelon.</p>",
>     "themes": [],
>     "source": "CDTN",
>     "redacteur": ["JR"],
>     "date": "01/01/2019",
>     "tags": {
>       "themes": [44400],
>       "theme": ["SMIC", "salaire minimum", "rémunération", "salaire"]
>     },
>     "references": [
>       {
>         "url": "https://www.legifrance.gouv.fr/eli/decret/2018/12/19/MTRX1833925D/jo/texte",
>         "titre": "Décret n° 2018-1173 du 19 décembre 2018 portant relèvement du salaire minimum de croissance "
>       }
>     ]
>   }
> ]

**Comment by jrduscher** [comment]
autre bug : la réponse rapide apparait en hors sujet total aussi, exemple ici:
![image](https://user-images.githubusercontent.com/37538697/55080130-d8dd9a80-509d-11e9-9ea8-1292758a113d.pg)
L'idée serait de faire en sorte de faire matcher la réponse avec certains mots uniqument : SMIC, salaire minimum, taux horaire)

**Comment by ClementChapalain** [comment]
je suis plus pour le texte direct smic unique, c'est plus sur je pense

**Comment by lionelB** [comment]
yep, et je vais aussi essayer d'en profiter pour un peu plus forcer un haut score  pour qu'on puisse l'afficher seulement si c'est très pertinent.
Et si ca marche pas, on fera autrement

**Comment by lionelB** [comment]
ne doit pas s'afficher sur 
- contrat de travail
- heures supplémentarires
- travail le dimanche
- ctt 
- cdd
- repos hebdomadaire

doit s'afficher sur les recherches 
> https://www.google.com/search?hl=fr&q=smic+2019
