### ISSUE TITLE
Tests unitaires

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#64]
**> Question : Solde de tout compte, paiement, versement en plusieurs fois imposé par l'employeur contre mon gré? :**
1) en posant toute la question ( un mail complet): FAQ: aucune bonne réponse , SP-FR: 1er résultat correct ( "Reçu pour solde de tout compte" la réponse est dans la fiche). fiches ministères dans les choux. Code du Travail ( à l'ouest)

 **> Réponse attendue:** (Article L1234-20, Article D1234-8,Article D1234-7 ) solde de tout compte versée à larupture du contrat. Le solde de tout compte n'obéit pas aux règles de paiement du salaire: Paiement en plusieurs fois envisageable mais pas sans votre consentement.  possibilité de contestation dans les 6 mois. Contestation possible aux prudhommes.

a) FAQ: - aucune-
b) fiches s-p : fiche 
c) fiches ministère
d) code du travail: 

>**Question (Stockmail) : Ecoute et enregistrement des appels sur le lieu de travail?**
**>Réponse attendue ou acceptée** : Article L. 1121-1 - Code du Travail. justifié proportionnée.CNIL. Les personnes écoutées et/ou enregistrées doivent **être informées** avant le début de l’écoute et de l’enregistrement et doivent disposer d’un **droit d’accès et de rectification** dont elles doivent être clairement informées de la mise en œuvre.
Les enregistrements ne peuvent être **conservés au-delà de 6 moi**s ni faire l’objet d’une utilisation différente de leur objet. L’accès interne aux écoutes et aux enregistrement est strictement réservé aux personnes habilitées à traiter leur objet. 
> test sur CDTN: aucune réponse, aucun début de réponse. avec les mots clés "écoute enregistrement et liberté", on matche une fiche ministère en rapport avec le sujet (http://travail-emploi.gouv.fr/droit-du-travail/relations-au-travail/pouvoir-de-direction/article/les-limites-au-pouvoir-de-surveillance-de-l-employeur) -il faut rajouter liberté pour que la fiche, qui matche en queue de liste émerge, elle matche sur enregistrement-. Le test sur le mot voisin vidéosurveillance fonctionne très bien, la fiche émerge en top 5 des résultats tout azimut!

**Question: Congés sabbatique, comment y prétendre, 6 mois d’expérience/ancienneté**
Réponse attendue ou acceptée: congé sabbatique, six années d'activité professionnelle et conditions
nse attendue ou acceptée: congé sabbatique, six années d'activité professionnelle et conditions d'ancienneté prévu par accord d'entreprise ou de branche, ou à défaut dispositions supplétives:   à la date de départ en congé,  ancienneté dans l'entreprise d'au moins trente-six mois, consécutifs ou non, et n'ayant pas bénéficié dans l'entreprise,du congé sabbatique au cours des six années précédentes. Article L3142-28, L3142-34 32. ( ordre public: pas avant 6 ans d'XP pro et une certaine ancienneté- principe-, négo, l'accord de brnche ou d'entreprise peut définir l'ancienneé, dispo supp: 36 mois à défaut d'accord)
Résultat dans CDTN : phrase complète,  Les premiers résultats de chaque liste marchent bien, il manque deux articles qui n'y sont pas.

a) FAQ: 
b) fiches s-p : congé sabbatique dans le privé ( la réponse est au début du paragraphe " conditions")
c) fiches ministère : le congé sabbatique
d) code du travail: L3142-28; D3142-20
// toutes les sources ont été trouvées dans les résultats

**Question: je suis apprenti, est ce que je peux quand même travailler chez mon employeur dès le mois de juillet, si au CFA ma formation ne commence pas avant le mois de septembre?
**Réponse attendue:  Oui, l'apprenti peut travailler à temps plein au mois de juillet, si son contrat le prévoit et si la formation démarre plus tard. Art L.6221-1 " L'apprenti s'oblige, en retour, en vue de sa formation, à travailler pour cet employeur, pendant la durée du contrat, et à suivre cette formation." (premier résultat articles du code du travail). le premier résultats fiches ministères le contrat d'apprentissage est correct ( mais plus complexe).

a) FAQ: 
b) fiches s-p : congé sabbatique dans le privé ( la réponse est au début du paragraphe " conditions")
c) fiches ministère : le congé sabbatique
d) code du travail: L6221-1 du code du travail
// toutes les sources ont été trouvées dans les résultat

** Question: Je suis revenu d'un CIF  et mon travail a changé. Le directeur promeut à ma place mon remplaçant en CDI et m'a retiré des tâches, en a t'il le droit ? 
** Réponse : Le CDTN renvoie sur la partie code du travail au L1152-1 sur le harcèlement moral. Toutes nos réponses affinées tapent à côté.
 =>Nous pouvons créer une fiche spécifique sur ces cas là, suffisamment pondéré pour la faire matcher, sur la base des synthèses sur la question, donnant quelques conseils de base à la personne ( qui voir, quelques conseils pour agir, etc - les fiches ne manquent pas sur la question: notre meilleure réponse étant le renvoi vers l'humain compétent: Médecin du travail, inspecteur du Travail.

**Question: Mon employeur et moi sommes en litige sur des sommes dues pour un voyage d'entreprise auquel je n'ai pas participé, pourra-t-il retenir ces sommes sur mon salaire?
** Réponse: non. retenues sur salaire, sanction pécuniaire interdites.  Seule réponse pertinente du CDTN, l'article L3251-1 du code du travail, qui n’apparaît pas en tête de liste.

**Comment by jrduscher** [comment]
existe-t-il une prime d'ancienneté dans la convention collective du commerce de gros?

réponses  obtenues:
> Démission d'un salarié
> délai de préavis fixé en fonction de votre ancienneté, dans les … délai de préavis fixé en fonction de votre ancienneté, dans les … du salarié Ancienneté du salarié Durée minimale
> Service Public
> CDD : l’embauche sous contrat à durée déterminée
> convention (par exemple, les conditions d’ancienneté).Par
> Ministère du Travail

réponse attendue:

en l'état de nos contenus: deux options:
à minima: https://codedutravail-dev.num.social.gouv.fr/fiche-service-public/salaire-du-secteur-prive-la-prime-danciennete-est-elle-obligatoire?q=prime%20d%27anciennet%C3%A9&search=0
au pire : Il n'existe pas encore de réponse...

Paradise: une FAQ sur la question
            https://www.legifrance.gouv.fr/affichIDCCArticle.do?idArticle=KALIARTI000005836444&cidTexte=KALITEXT000005673621&dateTexte=20181123
=> Il n'existe plus de prime d'ancienneté dans la convention collective du commerce de gros, depuis 1992, pour autant, un accord d'entreprise pourrait prévoir la mise en place d'une telle prime.


thème rémunération / salaire

**Comment by jrduscher** [comment]
Je travaille dans la métallurgie et mon employeur ne respecte pas les accords?

contenus obtenus:
Je travaille dans la métallurgie et mon employeur ne respecte pas les accords?

contenus attendus:
 // pas de contenu en ligne
=> Renvoi vers le SR


NEED PRECISION de l'utilisateur sur le détail du non repsct: champs...

**Comment by ClementChapalain** [comment]
J'ai commencé une liste des tests unitaires en reprenant le contenu de cette issue :
https://github.com/SocialGouv/code-du-travail-numerique/wiki/%5BProduit%5D-%5BRecherche%5D-Tests-unitaires

À retravailler avant de mettre en dev je pense.

**Comment by lionelB** [comment]
@ClementChapalain je pense que toutes les issues type "test unitaire" devrait, à terme, être ajouter au spreadsheet. J'ai crée une feuille "à valider" pour recueillir ces tests qu'il faudra ensuite qualifié avec les résultats attendus, identifiés par @jrduscher

**Comment by ClementChapalain** [comment]
Ah oui merci ! Je n'étais pas au courant de ce fichier, Julien me l'a envoyé hier du coup :) Je le remets là pour référence : https://docs.google.com/spreadsheets/d/1o6hf-Tm3rb5qMXRBId3aGuSt9tNalvxMsOkrbkHSbB4/edit#gid=0
