### ISSUE TITLE
amélioration affichage page de réponse FAQ

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#641]
https://codedutravail-dev.num.social.gouv.fr/question/je-suis-en-arret-maladie-ai-je-le-droit-au-maintien-de-salaire-par-mon-employeur-luhixk568bysfa?q=arr%C3%AAt%20de%20travail

on décovre dans le texte qu'il est question de la branche HCR qui est traitée.

afficher le tag lié à la branche ( aujourd'hui le tag le plus présent)
sous le titre à droite en gras, afficher branche: "xxx", lorsque le le tag branche est renseigné et différent de 0. A ce stade harmonisation n'a pas eu lieu, l'idcc ou l’intitulé peuvent avoir été renseignés ( plus rarement l’intitulé complet)

tache additionnelle rapide: une balise a du sauté dans le tableau existant dans cette réponse (https://codedutravail-dev.num.social.gouv.fr/question/je-suis-en-arret-maladie-ai-je-le-droit-au-maintien-de-salaire-par-mon-employeur-luhixk568bysfa?q=arr%C3%AAt%20de%20travail
on décovre dans le texte qu'il est question de la branche HCR qui est traitée.)

**Comment by lionelB** [comment]
ca ressemble à un doublons de #577 poke @jrduscher

**Comment by revolunet** [comment]
plus de faq :)
