### ISSUE TITLE
Integration des 250 questions-réponses faq quotidiennes

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#642]
https://github.com/SocialGouv/code-du-travail-numerique/pull/337

un stock de questions réponse existe sur un csv et dans des mails: comment les integrer et les mettre à disposition du public avant qu'ils ne soient obsolètes.

une première vague existe dans un json ( voir pr 337), automatiser est il envisgeable?

**Comment by jrduscher** [comment]
les e-mails ont été integrés à la mains dans des fichiers excel reprenant les champs ci après:

REDACTEUR* | DIRECCTE/ UD* | DIRECCTE/ UD* | DATE* | Date d’expiration du contenu : | Commentaire * | QUESTION DE L’USAGER* | REPONSE* | REFERENCES ET SOURCES* | Branche / CCN | Intitulé ou IDCC *: | Catégorie : | Thème de la question (thème attribué et sous   thèmes) | Salaire / Rémunération. | Type de contrat concerné | Travailleur particulier | Particularismes locaux ( ex : Maintien   de salaire en Alsace Moselle) | Autre information importante   caractérisant la question | Profil du public concerné (Employeur/salarié)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

les fichier doivent venir alimenter faq.json, ou un json dédié ( un début ici https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-data/dataset/faq-contributions.json). 



- integrer les données des deux tableaux xls vers le json, (script?) - demander les deux fichiers xls-
- prévoir aller retours avec le métier pour corrections)
-les données sont des réponses FAQ, - même contenu  exactement


> {
>     "question": "Je me suis aperçu que mon taux horaire actuel est inférieur à celui du Smic. Je perçois par ailleurs une prime de polyvalence ainsi qu’une prime d’ancienneté.  Suis-je en droit de demander un rappel de salaire ?",
>     "reponse": "Votre employeur est tenu de respecter le Smic. Cependant, dans votre cas, le seul taux horaire n’est pas à lui seul déterminant. Vous devez, pour vérifier si le Smic est respecté, ajouter au salaire de base l’ensemble des primes versées chaque mois en contrepartie du travail.<p>C’est le cas pour votre prime de polyvalence, compensant votre formation à plusieurs postes et versée régulièrement en contrepartie de votre travail.</p><p>Ce n’est pas le cas, en revanche, de votre prime d’ancienneté, qui récompense votre stabilité dans l’entreprise, mais n’est pas pour autant la contrepartie d’un travail fourni.</p><p>Le smic sera respecté si, après avoir additionné votre salaire de base et votre prime de polyvalence puis divisé par le nombre d’heures mensualisées figurant sur votre bulletin de salaire, vous obtenez un montant au moins égal à celui du taux horaire du Smic.</p><p>Dans le cas contraire, et seulement dans le cas contraire, vous seriez en droit de demander à votre employeur un rappel de salaire pour la somme manquante.</p><p>Cette réclamation ne pourrait être faite que dans un délai de trois ans.</p>",
>     "date_redaction": "27/11/2018",
>     "date_expiration": "27/11/2019",
>     "redacteur": "Jean-Paul GUILLE (UD038)",
>     "source": "contributions quotidiennes",
>     "tags": {
>       "themes": [44600, 44800, 45100],
>       "theme": [
>         "SMIC",
>         "salaire minimum",
>         "rémunération",
>         "salaire",
>         "prime de polyvalence",
>         "prime d'ancienneté"
>       ],
>       "branche": "Métallurgie",
>       "categorie": [],
>       "type_contrat": "CDI",
>       "travailleur_particulier": "apprenti",
>       "duree_travail": "temps plein",
>       "effectif": "> 11 salariés",
>       "particularisme": "Isère",
>       "profil": ""
>     },
>     "references": [
>       {
>         "url": "https://www.legifrance.gouv.fr/affichCode.do;jsessionid=F604538DBBCC872ADB667D1A2901DE37.tplgfr27s_3?idSectionTA=LEGISCTA000006178024&cidTexte=LEGITEXT000006072050&dateTexte=20181130",
>         "titre": "Articles L3231-1 et suivants du code du travail"
>       }

- si le choix de rester sur une faq unique est retenue:  les différentes occurrences de ce fonds doivent être identifiables pour faciliter l’administration des données par l'équipe : ajout d'un commentaire " contribution quotidienne 1ère vague" pour chaque ocurence.
/!\ en l'état relecture métier des contenus

**Comment by revolunet** [comment]
ce serait pas l'occasion de les injecter dans l'outil de contribution (via un script) et commencer à y puiser pour nourrir le CDTN ?

**Comment by lionelB** [comment]
Est ce que genre de contributions ne devrait pas plutôt se retrouver (via un import ?) dans l'outils de contribution ?

**Comment by lionelB** [comment]
ahah julien ;)

**Comment by revolunet** [comment]
@ivangabriele qu'en penses-tu ?

**Comment by revolunet** [comment]
Par la même occasion, il faudrait qu'on réintère les ~70 FAQ dans l'outil ? 

https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-data/dataset/faq.json

**Comment by ivangabriele** [comment]
Pardon pour le retard ici. Du coup je crois qu'on est tous d'accord qu'il y a 3 étapes:

1. Intégrer les réponses dans la base de données de prod du backoffice
2. Exposer les réponses via l'API du backoffice (une ligne de SQL suffira)
3. Intégrer ça côté frontoffice

@revolunet ? (je ne ping pas Lionel puisqu'il est en vacances)

**Comment by virginielastisneres** [comment]
@jrduscher Etant donné que les 250 questions sont en cours de validation par la DGT, ne faudrait-il pas attendre leurs retours avant d'intégrer les réponses dans l'outil de contribution ?

**Comment by jrduscher** [comment]
Pour cette issue: il faut avoir la solution technique pour intégrer les données des fichiers xlsx, mais il faut effectivement attendre le retour de validation des bureaux techniques.

**Comment by revolunet** [comment]
intégration directe depuis API contributions
