### ISSUE TITLE
ajouter le service nlp dans k8s

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#648]
car pour l'instant la suggestion  de requêtes n'est plus accessible :(

**Comment by ClementChapalain** [comment]
fixé j'ai l'impression :) ?

**Comment by lionelB** [comment]
nope, c'est fixé sur le serveur de dev par contre, le container nlp n'est pas déployé sur le cluster de dev (celui ou les branche sont déployées)
