### ISSUE TITLE
procédure de licenciement

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#66]
calcul des délais et explications.
comment faire? legal design? donner l'info ou une info personnalisé avec les délais en présence?

Calcul des délais.
-prise en compte des particuliarités de procédure en fonction du motif
- procédure spécifique si salarié protégé:
-sanction disciplinaire: date de la faute(*règle)
- procédure: (le phasage+ les délais]

  
- contestation
  Motivation de la lettre de licenciement (15j)

**Comment by ClementChapalain** [comment]
Repris ici : https://github.com/SocialGouv/code-du-travail-numerique/wiki/%5BOutils%5D%C2%A0%5BD%C3%A9lai-licenciement%5D-G%C3%A9n%C3%A9ral

Je ferme car pas de specs produit dans cette tâche.
