### ISSUE TITLE
Mettre à jour les fiches Ministère du travail

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#661]

**Comment by ClementChapalain** [comment]
est-ce que tu peux donner du détail sur le pb stp @virginielastisneres :) ?

-> est-ce qu'il manque des fiches ? est-ce qu'on a une fiche plus à jour ? etc.

**Comment by virginielastisneres** [comment]
Oui Oui :) Désolé Lionel me l'avait demandé en plus, j'ai zappé.. faut juste que je retrouve les fiches dont je parlais...

**Comment by virginielastisneres** [comment]
Certaines fiches ne sont pas encore mises dans le code du travail numérique. Elles sont très récentes. 
Exemples : 
- fiche sur l'index égalité hommes-femmes comment le calculer ? https://travail-emploi.gouv.fr/actualites/l-actualite-du-ministere/article/index-de-l-egalite-femmes-hommes-comment-le-calculer
- fiche Comment agir face au harcèlement sexuel au travail ? https://travail-emploi.gouv.fr/actualites/l-actualite-du-ministere/article/comment-agir-face-au-harcelement-sexuel-au-travail

**Comment by revolunet** [comment]
Il y a une liste d'urls ici : https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-data/dataset/fiches_ministere_travail/ministere-travail-liste-fiches.json

Et le scrapping est fait à partir de cette liste

**Comment by lionelB** [comment]
duplicate #753
