### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#678]
specs here

**Comment by revolunet** [comment]
Quelques suggestions côté technique : Le partie "thèmes" (8 blocs) peut nous aider à bien référencer nos contenus, hiérarchisés par thèmes.

 - Vérifier qu'on a a des href fonctionnels
 - Dans chaque thème, ajouter des liens vers les "questions les plus fréquemment posés" pour le theme/sous-theme question

**Comment by lionelB** [comment]
Vérifier aussi qu'on a pas de malus sur les contenus dupliqués 
(meta à rajouté ?)

**Comment by revolunet** [comment]
⚠forcer le noindex sur les urls noprod :)
soit avec une meta, soit un robots.txt

**Comment by ClementChapalain** [comment]
je ferme, on va faire des tâches spécifiques comme celle ci : #737

**Comment by revolunet** [comment]
on a oublié l'issue pour le noindex :) cf #985
