### ISSUE TITLE
Termes juridiques complexes non remplaçables par un synonyme exact

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#679]
**problème**: la vulgarisation s'arrête à l'approximation et aux erreurs de droit qu'elle induit. La fiabilité juridique suppose de garder des termes juridiques non substituables par un autre terme.. Exemples "un accord de branche étendu", une prise d'acte, la cour de cassation, jurisprudence. 

**L'idée** est de proposer une explication ou une définition de ces termes et notions à l'utilisateur. Exemple "un accord de branche étendu": "un accord négocié dans branche qui s'applique à toutes les entreprises prévus dans son périmètre, après qu'un arrêté du ministère travail l'ait étendu au delà des seuls signataires et employeurs affiliées". 
La manière de proposer la définition à l'user est double, au roll over du terme dans un texte, ou en tant que réponse à part entière en page de résultat

Step 0: récupérer le dump des données de lexique service-public.fr 

Step 1: constituer et alimente le fonds de définitions au fil de l'eau. Réutiliser le json :https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-data/dataset/definitions ?

Step 1a: comment alimenter cette base? 
début alimentation direct json.?
Step 1b: saisie simplifiée par un autre biais ( page dédiée?)
/ définir au niveau dev et métier la solution la plus efficiente: la base sera enrichie au niveau de l'équipe

Step 2:  Dans les textes d'explication de la hiérarchie des normes, les termes juridiques non substituables sont enrichi d'une définition brève au roll over.  
Step 3: lorsque les termes précisés dans la base de définitions sont saisies dans le champs de recherche génériques: la définition apparaît comme un contenu de réponse direct en page de résultat ( en complément des autres réponses à l'instar du tx horaire du SMIC).

Step 4 ou idéal:  le terme juridique non substituable et défini dans une base est détectée dans le texte dans tous nos contenus ( FAQ, fiches voire )
Step 5 ( or never) : l'usager et le contributeur peut suggérer un terme dont la définition serait utile à ajouter. Le contributeur et le valideur peuvent proposer un terme et sa définition
step 6 : La détection des termes avec définition qui s'affiche au roll over est étendu  tous les contenus du site

// faut il découper cette issue?

**Comment by ClementChapalain** [comment]
done !
