### ISSUE TITLE
Améliorer l'affichage de la hiérarchie des normes (wording, design, etc.)

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#684]
Après avoir fait quelques tests utilisateurs rapides sur la compréhension de notre nouveau bloc sur les références juridiques, il faudrait faire quelques modifications pour apporter plus de clarté :
- ajouter le texte : "Cette réponse est liée à **n** articles du code du travail. Le texte applicable à votre situation (code du travail, accord de branche, accord d'entreprise) est différent en fonction des articles." en dessous du titre "Références juridiques"
- nouveaux wordings blocs :
   - bloc 1.1.a : "Pour ces articles, si les accords négociés et étendus dans votre branche prévoient des mesures plus favorables que le Code du travail, alors ces mesures s'appliquent. Votre entreprise ne peut pas conclure d'accord sur ces thèmes."
   - bloc 1.1.b : "Pour ces articles, si les accords négociés dans votre branche prévoient des mesures plus favorables que le Code du travail, alors ces mesures s'appliquent. Votre entreprise ne peut pas conclure d'accord sur ces thèmes."
- nouveaux wordings titres :
   - bloc 1.1.a : "L'accord de branche étendu s'applique"
   - bloc 1.1.b : "L'accord de branche s'applique"
- changer l'emplacement de l'accordéon avec les articles du code du travail afin d'apporter de la cohérence avec le texte explicatif :
![image](https://user-images.githubusercontent.com/5337489/55717113-e6c5e080-59f8-11e9-87ce-69e2afe54d56.png)

**Comment by UnbearableBear** [comment]
Mon doigt à couper qu'un jour on aura un retour utilisateur disant qu'on ne voit pas le texte sous l'accordéon (surtout si un jour on gère le no-js et qu'il est déplié par défaut) !
