### ISSUE TITLE
Remplir le data filler

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#685]
WIP

**Comment by revolunet** [comment]
A faire avant de commencer : un dernier tour "UX" pour vérifier que tout est ok

**Comment by lionelB** [comment]
il faudrait aussi pouvoir brancher le script de TU sur l'appli  le code est dispo où ?

**Comment by revolunet** [comment]
Le code est là : https://github.com/SocialGouv/datafiller

Je vais ajouter une route pour extraire les données en bloc

**Comment by ClementChapalain** [comment]
🎉
