### ISSUE TITLE
Ajouter les thèmes CDTN aux fiches SP et MT

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#686]
Cf. la tâche #626 nous avons désormais une arborescence de thèmes spécifiques au CDTN 🙌 
https://docs.google.com/spreadsheets/d/1CVRrR45QIlSzVeO_9V1TUXSqI1U9Bt5_KYWlcH9K2jI/edit#gid=1783422693

L'objectif de cette tâche est d'associer un thème CDTN à chacun de nos contenus SP et MT afin de permettre à l'usager de naviguer par thèmes dans le CDTN.

L'idée est de faire correspondre les thèmes des fiches SP et MT aux thèmes du CDTN. Les tableaux de correspondance ont déjà été créés et sont disponibles sur le même fichier excel :
- [tableau de correspondance SP <-> CDTN](https://docs.google.com/spreadsheets/d/1CVRrR45QIlSzVeO_9V1TUXSqI1U9Bt5_KYWlcH9K2jI/edit#gid=1528278028)
- [tableau de correspondance MT <-> CDTN](https://docs.google.com/spreadsheets/d/1CVRrR45QIlSzVeO_9V1TUXSqI1U9Bt5_KYWlcH9K2jI/edit#gid=564965322)

To do :
- récupérer les thèmes SP des fiches SP et les thèmes MT des fiches MT
- stocker les thèmes CDTN et les tableaux de matching CDTN <-> SP / CDTN <-> MT
- remplacer la navigation par thèmes de la homepage du CDTN par une nouvelle navigation par thème qui permet de naviguer dans les thèmes et d'afficher les contenus associés à un thème (le design actuel peut être conservé)

**Comment by ClementChapalain** [comment]
recap à la fin du sprint 14 :
- toutes les fiches MT ont été tagguées :
https://docs.google.com/spreadsheets/d/1CVRrR45QIlSzVeO_9V1TUXSqI1U9Bt5_KYWlcH9K2jI/edit#gid=314865367
- définition du mvp : on affiche un fil d'ariane (pour l'instant non cliquable) sur les fiches SP et MT avec les thèmes parents de chaque fiche

@lionelB est-ce que tu peux compléter stp ? je ne sais plus trop où on en était sur les fiches SP notamment

**Comment by lionelB** [comment]
@ClementChapalain c'est en cours, je reprend le fil de ce que j'avais fais
- pour les fiches mt: cool
- pour les fiche sp: il me manque des infos notamment pour la partie entreprises / professionnels

**Comment by jrduscher** [comment]
@lionelB  @ClementChapalain 
n°16 : en cours construire l'API de récupération des thèmes

**Comment by lionelB** [comment]
en todo pour avoir la navigation par themes
- [ ] créer un endpoint pour récupérer les items par theme
- [ ] indexer les nouveaux themes 
- [ ] supprimer theme-front.json

**Comment by ClementChapalain** [comment]
on peut fermer du coup @lionelB :) ?

**Comment by ClementChapalain** [comment]
modulo les fiches sans thèmes qu'on gérera quand on fera une v2 de nos thèmes
