### ISSUE TITLE
Modifications nouveau formulaire feedback

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#691]
Retours sur le nouveau formulaire de feedback (suite #631)

- est-ce qu’on pourrait avoir un autre formulaire formspree qui est envoyé au moment où l’usager clique sur oui / non ? ça permettrait de faire des stats sur les contenus et voir lesquels sont bons / mauvais
- dans le formulaire qui est envoyé quand l’utilisateur écrit un commentaire optionnel, est-ce qu’on pourrait ajouter en champs caché le titre de la réponse qu’il est en train de regarder ? ce serait plus simple que de devoir le cherche dans l’url
- dans le formulaire qui est envoyé quand l’utilisateur écrit un commentaire optionnel, on ne voit pas si l’utilisateur a cliqué sur oui / non avant, ce serait bien de l’ajouter je pense
- je me dis que ce serait mieux si les boutons oui / non disparaissaient carrément une fois qu'on a cliqué dessus, là ça donne l'impression qu'on peut encore les utiliser (p-e le statut "disabled" qui n'est pas très visible aussi). on perd la possibilité de revenir en arrière si l'utilisateur a fait une erreur mais bon c'est pas trop grave on va juste faire des stats dessus on ne va pas regarder réponse par réponse
- la formulation du bouton pour le commentaire optionnel devrait être "envoyer" et non "envoyer ma question" car on a pas prévu de répondre à ces messages c'est juste du feedback sur les contenus
- augmenter un peu la largeur du bloc (cf. design : https://www.figma.com/proto/UGkd7UFF3gJSb3a35ClTtPKW/maquette?node-id=67%3A0&viewport=550%2C-209%2C0.31681&scaling=min-zoom)

**Comment by lionelB** [comment]
> * la formulation du bouton pour le commentaire optionnel devrait être "envoyer" et non "envoyer ma question" car on a pas prévu de répondre à ces messages c'est juste du feedback sur les contenus

c'est en général conseillé de mettre un label descriptif plutôt que générique. 
Qu'est ce que tu penses de 
- Envoyer mon commentaire 
- Transmettre mon commentaire

**Comment by ClementChapalain** [comment]
ok ! du coup "envoyer mon commentaire" je pense que c'est plus clair

**Comment by ClementChapalain** [comment]
ajout de deux autres modifications via @jrduscher :
- souhaitez-vous nous donner plus de précisions -> "nous sommes à votre écoute si vous souhaitez nous faire un commentaire pour nous aider à améliorer le Code du travail numérique :"
- "nous sommes à votre écoute" -> supprimer
- "vous pouvez également joindre les services de renseignement [...]" -> "pour obtenir une réponse à votre question de droit du travail, nous vous invitons à joindre les services de renseignement."

**Comment by jrduscher** [comment]
Catherine L. suggère d'ajouter aussi le mail de contact dans cette modal pour les sers interessés par le projet

**Comment by ClementChapalain** [comment]
il est déjà dans le footer donc je ne suis pas trop pour, je pense que c'est deux cas d'usage différents :
- poser une question générale sur le projet -> usuellement c'est un lien dans le footer, on l'a déjà donc on est bon
- demander un retour spécifique sur un contenu -> on le met de manière contextuelle au niveau du contenu avec notre module de feedback donc on est bon aussi

il faut qu'on fasse attention à ne pas trop mélanger les fonctionnalités, c'est pour cette raison qu'on a changé le module de feedback pour le recentrer sur le retour sur les contenus (et pas les questions de droit du travail) et qu'on est en train de changer le module sur l'annuaire (pour n'avoir que le contact des services de renseignement et pas tout l'annuaire)

**Comment by ClementChapalain** [comment]
après discussion avec Catherine, JR et Virginie, 1 modification en plus :
- mettre le sélecteur de raison au-dessus du champs de commentaire

**Comment by lionelB** [comment]
> * est-ce qu’on pourrait avoir un autre formulaire formspree qui est envoyé au moment où l’usager clique sur oui / non ? ça permettrait de faire des stats sur les contenus et voir lesquels sont bons / mauvais

Je pense qu'on doit pouvoir faire cela, je ne vois pas de limitation sur l'offre de formspree
