### ISSUE TITLE
[bugs] d'affichages et actualisation rapide

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#692]
remontées de ~@catherine~  Catherine L.

-  redondance découvrez nos outils et "liens et outils dans le footer". Ce ne sont pas non plus les mêmes contenus. 
=> Supprimer liens et outils du footer

- découvrez nos outils: "votre convention collective" diffère des autres cases. espace plus important entre la bordure haute et le picto, police ou taille de police du wording sous le titre différente des autres bulles.
![image](https://user-images.githubusercontent.com/37538697/55737700-fb6c9d80-5a25-11e9-9ee7-00a729873ca9.png)

**Comment by lionelB** [comment]
D'acc !

> * découvrez nos outils: "votre convention collective" diffère des autres cases. espace plus important entre la bordure haute et le picto, police ou taille de police du wording sous le titre différente des autres bulles.

c'est déja fait !

**Comment by catherine** [comment]
Je pense que vous vous êtes trompés de @catherine - bon courage!
![homer_disappear](https://user-images.githubusercontent.com/3717039/55742278-2209e480-59e4-11e9-8422-70835b659b95.gif)

**Comment by lionelB** [comment]
ahah magnifique 
@catherine désolé pour le ping
