### ISSUE TITLE
Encart de feedback ( petite modif wordings)

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#695]
![image](https://user-images.githubusercontent.com/37538697/55745765-47284280-5a38-11e9-8802-fa5773a03ba3.png)
1) Merci pour votre réponse !
Souhaitez-vous donner plus de précisions ?
Votre retour va nous aider à construire et améliorer le code du travail numérique

2) envoyer votre question => envoyer
3) Dans votre DIRECCTE, des services gratuits sont chargés de renseigner le public sur le droit du Travail: contacter les (+lien)

**Comment by ClementChapalain** [comment]
merci pour l'issue je vais la merger avec #691 !

**Comment by lionelB** [comment]
j'etais en train de répondre :)
