### ISSUE TITLE
Ajouter des informations complémentaires générales sur le droit du travail

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#70]
Qu'est ce que le code du travail numérique?
Qu'est ce qu'une convention collective?
Comment trouver ma convention collective?
Combien d'article dans le code du travail?
Qui est la ministre du travail?
Qui est le Directeur général du Travail?
Qu'est ce qu'une DIRECCTE?

Comemnt fonctionne la hierarchie des normes
Qu'est ce que la loi Travail?
Les ordonnances Macron, c'est quoi?

qu'est ce que le salaire minima hiérarchique?

**Comment by revolunet** [comment]
-> produire ces informations sous forme d'une FAQ dédiée qui pourra être intégrée dans le moteur

**Comment by jrduscher** [comment]
https://github.com/SocialGouv/code-du-travail-explorer/issues/46

**Comment by revolunet** [comment]
fixé avec la page "le droit du travail, qu'est-ce que c'est"
