### ISSUE TITLE
Intégrer le tag hotjar sur le site

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#700]
Afin de tirer parti de la conférence de presse de vendredi, on voudrait intégrer un widget permettant de récupérer les adresses email des personnes intéressées par le projet.

Hotjar fait ça très bien, cf. le test réalisé sur mon navigateur :
![image](https://user-images.githubusercontent.com/5337489/55811549-94b0b800-5ae9-11e9-92ee-c3f424c90f5a.png)

On va uniquement l'intégrer sur la page d'accueil pour ne pas être trop agressif.

Pour que ça fonctionne, voici le tag à intégrer dans le head de chaque page (on configure dans hotjar les pages sur lesquelles on veut que ça apparaisse ensuite) :
```
<!-- Hotjar Tracking Code for https://codedutravail.num.social.gouv.fr -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:1244076,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
```

**Comment by lionelB** [comment]
> On va uniquement l'intégrer sur la page d'accueil pour ne pas être trop agressif.
> 
> Pour que ça fonctionne, voici le tag à intégrer dans le head de chaque page

on le met dans chaque page ou que dans la home?

**Comment by ClementChapalain** [comment]
on le met partout, on gérera le fait que ça apparaisse que sur la home avec une configuration de hotjar, comme ça on peut ajouter d'autres pages si besoin simplement (sans besoin de modifier le tag et de redéployer) ensuite

**Comment by UnbearableBear** [comment]
Suuuuper !
