### ISSUE TITLE
[BUG] contenu FAQ et articles de référence ne correspondent pas. 

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#703]
Mon employeur peut -il m'imposer de travailler le samedi? Je suis ouvrier dans la métallurgie et travaille à temps plein habituellement du lundi au vendredi

{
    "reponse": "<p>L'employeur peut procéder à des changements d'horaires dans l'entreprise sans obtenir l'accord préalable du comité d'entreprise si cette modification n'est que ponctuelle ou ne concerne qu'un salarié, et n'affecte pas les conditions générales de travail dans l'entreprise.\nAinsi, si les horaires individualisés appliqués dans l'entreprise sont aménagés du lundi au vendredi, l'employeur peut aménager les horaires d'un salarié du mardi au samedi si celui-ci est affecté à des tâches d'entretien et de réparation dont certaines ne peuvent s'effectuer que le samedi : arrêt de la Cour de Cassation, chambre sociale, du 1er juill. 1997, n° 95-12.000, n° 2871 P + B.</p><p>Il peut, dans les mêmes conditions, modifier l'horaire initial, si cela ne change pas les horaires définis par votre contrat de travail ou ne modifie pas la durée du travail hebdomadaire ou le salaire.</p><p>En l'espèce, votre contrat de travail joint en copie à vos questions, prévoit bien que votre horaire peut être modifié afin de répondre à la charge de travail fluctuante sans que cela puisse être considéré comme une modification du contrat de travail, laquelle supposerait alors votre accord.</p><p>Si l'horaire est collectif, l'employeur doit l'afficher dans les lieux de travail où il s'applique, l'employeur établissant un décompte de la durée du travail, des repos compensateurs acquis et de leur prise effective, pour chacun des salariés concernés. Les délégués du personnel peuvent consulter ces documents : article L. 3171-2 du code du travail.</p><p>L'article suivant du même code indique aussi que l'employeur tient à la disposition de l'agent de contrôle de l'inspection du travail compétent pour l'entreprise, les documents permettant de comptabiliser le temps de travail accompli par chaque salarié. En cas d'horaire collectif, un double est transmis à l'inspecteur du travail avant l'affichage sur les lieux de travail : il en est de même en cas de modification de celui-ci : article D. 3171-3 et D. 3171-4 du code déjà cité.</p>",
    "question": "Mon employeur peut -il m'imposer de travailler le samedi? Je suis ouvrier dans la métallurgie et travaille à temps plein habituellement du lundi au vendredi",
    "tags": {
      "theme": "durée du travail",
      "branche": "métallurgie"
    },
    "date": "01/12/2017",
    "source": "DIRECCTE",
    "redacteur": "non précisé"
  },

les articles ou le thème de l'ancienne claissification dérivée de eposedion n'est pas précisée.
la page résultat est la suivante:

https://codedutravail-dev.num.social.gouv.fr/question/mon-employeur-peut-il-mimposer-de-travailler-le-samedi-je-suis-ouvrier-dans-la-metallurgie-et-travaille-a-temps-plein-habituellement-du-lundi-au-vendredi-y3eiqyo7nksvsq?q=travailler%20le%20samedi

les articles proposées pour la question du travail le samedi traitée dans la FAQ concernent le risque pyrotechnique. le terme de hors sujet est plutôt flagrant.
> pourquoi ces articles ?

> ajout de l'article L3132-1 éloigné mais le plus proche.
> ajout du tag eposeidon: 21002

**Comment by ClementChapalain** [comment]
je ne comprends pas le pb ni la solution proposée, je ne vois pas où on parle de risque pyrotechnique ? j'ai regardé les articles du CDT liés dans la page réponse et dans la page résultat de recherche et ça parait ok.

**Comment by ClementChapalain** [comment]
fiche plus intégrée -> tâche outdated
