### ISSUE TITLE
Créer une page introductive au droit du travail

### ISSUE THREAD

**Issue by adipasquale** [SocialGouv/code-du-travail-numerique#717]
l'idée serait de faire une page introductive ou où on explique succintement comment fonctionne le droit du travail, qu'il y a un code, des conventions, des accords d'entreprise, qu'il y a une notion de hierarchie des droits etc ...

cc @ClementChapalain

**Comment by jrduscher** [comment]
bien vu!

**Comment by virginielastisneres** [comment]
Hey :D 
Si cela vous va, je me lance dans cette page et je reviens vers vous pour vous proposer quelque chose ;)

**Comment by adipasquale** [comment]
🙇  au top, merci Virginie

**Comment by ClementChapalain** [comment]
pour info @virginielastisneres je viens de retrouver ça #70 il y a p-e des idées pour étoffer (même si je pense qu'il ne faut pas que ce soit trop lourd) cette page d'intro au droit du travail

**Comment by virginielastisneres** [comment]
intégrer : 
- page 1 : https://www.figma.com/file/dd5K7nrvEsMQnXzEJ5DqiX5u/V2-Page-pr%C3%A9sentation-droit-du-travail?node-id=12%3A344
- page 2 : https://www.figma.com/file/dd5K7nrvEsMQnXzEJ5DqiX5u/V2-Page-pr%C3%A9sentation-droit-du-travail?node-id=12%3A2
                - Dans la page 2, il y a pour certains accordéons, il y a d'autres accordéons à intégrer (c'est indiqué dans le figma via une flèche qui amène à l'accordéon développé) 
                - Pour les 3 petits rectangles blanc, il s'agit d'une description des termes associés via une flèche  


Où l'intégrer dans le code du travail numérique : 
- Un petit lien en haut à droite du site (il est mis dans la 1ère page du figma). Ce lien ouvre une nouvelle fenêtre.
![image](https://user-images.githubusercontent.com/48682104/59606061-821db500-9110-11e9-9b1e-697a8bf18c46.png)

**Comment by UnbearableBear** [comment]
![merci](https://user-images.githubusercontent.com/705453/59855706-c067de00-9375-11e9-8e5a-a94a0d29dd37.png)

**Comment by virginielastisneres** [comment]
![image](https://user-images.githubusercontent.com/48682104/60170228-55e8ef00-9808-11e9-8c03-ddb65d3a3149.png)
changer articulation par hiérarchie (on m'a fait la remarque que l'on utilisait pas le terme articulation avant et que ca faisait bizarre, ce qui est pas faux...)

**Comment by virginielastisneres** [comment]
![image](https://user-images.githubusercontent.com/48682104/60170691-44ecad80-9809-11e9-9b12-1fe5c985b21c.png)
est-il possible de rajouter en bas de ce paragraphe des exemples en italique: 
"Exemples : 
- Le taux de majoration des heures supplémentaires : un accord collectif peut prévoir dans une certaine limite un taux inférieur à 25% (règle prévue par le Code du travail). 
- Le congé sabbatique : un accord collectif peut prévoir une durée minimale et une durée maximale du congé sabbatique différente de ce que prévoit le code du travail. 
- Les négociations obligatoires en entreprise : un accord d'entreprise peut prévoir une périodicité des négociations plus longue que ce que prévoit le Code du travail qui est principalement d'un an.

**Comment by virginielastisneres** [comment]
![image](https://user-images.githubusercontent.com/48682104/60171851-bded0480-980b-11e9-943a-2c8d0bcdbb2f.png)
idem : est il possible de mettre après le texte des exemples : 
"Exemples 
- Congés exceptionnels : en l'absence d'accord collectif sur les congés exceptionnels, ce que prévoit le code du travail s'applique (4 jours pour mariage, 1 jour pour mariage d'un enfant, 5 jours pour le décès d'un enfant...)
- Taux de majoration des heures supplémentaires : en l'absence d'accord collectif sur le taux de majoration des heures supplémentaires s'applique le code du travail (25% de majoration pour les 8 premières heures et 50% pour les suivantes). 
- Aménagement du temps de travail sur une période supérieure à la semaine: en l'absence d'accord collectif sur l'aménagement du temps de travail, le code du travail s'applique. L'employeur peut aménager le temps de travail sur une période de 9 semaines pour les entreprises de moins de 50 salariés.

**Comment by lionelB** [comment]
@virginielastisneres tu peux mettre tes commentaires dans la PR si tu veux https://github.com/SocialGouv/code-du-travail-numerique/pull/963

**Comment by UnbearableBear** [comment]
C'est ok je les ai vus

**Comment by virginielastisneres** [comment]
sorry sorry ... j'ai tout mis dans la PR :)
