### ISSUE TITLE
bugs+ enhancements : trouver ma ccn avec  mon siret

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#720]
Lorsque l'outil me propose un lien vers ma CCN.

2) Certaines CCN ex: Air France CC 0275 : La CCN est proposé, mais l'action n'aboutit pas:
 - 780.129.987: Renaut Choisy
- 420 495 178: Air France

3) Quand je tape "entrée" à la fin  ( ou en cours si je veux)de ma saisie de SIRET, je suis ejecté de la modal et me retrouve sur la page d'accueil

4) enhancemenet : Quand je tape les 9 premiers chiffres de mon SIRET, en fait je suis en train de saisir mon SIREN ( n° entreprise) : on peut donc en changeant juste le wording proposer à l'user de retrouver la ccn applicbale à son établissement en saisissant son SIREN/SIRET
=> les recherches fonctionnement parfaitement en saisissant les 9 premiers chiffres, le filtre ne me propose que des établissement liés au SIREN saisi.

5)Enhancement:  La raison sociale de l'entreprise s'affiche dans es propositions, serait il possible de chercher mon établissement avec son enseigne ou sa raison sociale?

**Comment by lionelB** [comment]
> 1. Quand je tape "entrée" à la fin  ( ou en cours si je veux)de ma saisie de SIRET, je suis ejecté de la modal et me retrouve sur la page d'accueil

ajouter un `event.preventDefault()` dans `onSubmit` du formulaire

**Comment by adipasquale** [comment]
@jrduscher en effet pour les premiers points que tu mentionnes, ca pointe vers des IDCC soit inactives, soit qui sont parmi les ~150 absentes de legifrance. je ne peux pas faire grand chose de mieux. ex http://localhost:3000/kali-idcc/0054 IDCC 0054 ça doit être bien vieux et abrogé

**Comment by adipasquale** [comment]
ah non pardon j'ai répondu trop vite, c'est effectivement un bug, je l'ai stockée comme '54' au lieu de '0054' et du coup il y a "mismatch" entre les deux. je vais corriger ça. good catch @jrduscher

**Comment by adipasquale** [comment]
pour le 4 j'ai changé le wording : 

# Recherche par SIREN ou SIRET
> Saisissez le numéro de SIREN ou SIRET de votre entreprise afin d'obtenir votre convention collective: 

Pour la 5 oui c'est possible et relativement facile à faire mais ça ne scalera pas trop, on est sur une infrastucture très temporaire pour ce mapping SIRET > IDCC. On ne veut probablement pas réimplémenter la recherche d'entreprise mais réutiliser celle de https://entreprise.data.gouv.fr/ plutôt. si tu veux je peux le mettre en place "rapidement pour voir" mais si on veut réfléchir à une solution plus pérenne il faudra prendre un poil plus le temps.
