### ISSUE TITLE
Correction de modèle signalement de harcèlement sur proposition de l'UD17

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#721]
le modèle en cause:
https://codedutravail.num.social.gouv.fr/modeles-de-courriers/signalement-de-harcelement-et-maltraitance-au-travail?q=harc%C3

**Intégration du wording dans le header du modèle**

Avant d'envoyer ce courrier, nous vous invitons à prendre contact avec ll'agent de contrôle de l'inspection du travail qui suit votre entreprise avant l’envoi de ce courrier.

Modification dans le modèle:

(facultatif)
Je vous informe que copie de ce courrier est transmise à l’Inspection du Travail, « adresse de l’inspection du travail ».

devient:

(facultatif : Si vous souhaitez une intervention de l'inspection du travail auprès de votre employeur, il faut l'évoquer explicitement dans le courrier adressé à l'employeur.)
Je vous informe que copie de ce courrier est transmise à l’Inspection du Travail, « adresse de l’inspection du travail ».
 

Modif du titre et de l'objet du modèle actuel:
remplacer: Signalement de maltraitance au travail par Signalement de faits pouvant relever du harcèlement moral.

Modification du contenu du courrier

Header ici. [projet Lettre dénonciation harcèlement moral UD 17.docx](https://github.com/SocialGouv/code-du-travail-numerique/files/3072580/projet.Lettre.denonciation.harcelement.moral.UD.17.docx)

> on intègre pas le modèle ci dessus au cours du sprint

**Comment by lionelB** [comment]
une fois l'issue fermé, il faudra penser à faire un mail pour remercier et dire que c'est intégrer !

**Comment by jrduscher** [comment]
yep c'est prévu

**Comment by jrduscher** [comment]
1) Integration du wording da,s le header du modèle

Tout d'abord, **Nous vous invitons à contacter l'agent de contrôle de l'inspection du travail qui suit votre entreprise avant l’envoi d'un courrier basé sur ce modèle.** 

Pour obtenir l'intervention de  l'agent de contrôle  l'employeur dans votre affaire, il faut votre accord ( il faut lever l'obligation de confidentialité à laquelle l'agent est tenue). Concrètement, l'employeur doit être informé que l’inspection du travail est au courant de l'affaire:  Vous devrez donc mettre en copie l'inspection du travail et demander expressément l’intervention de l'inspection du travail.

2) Modification du docx ( WIP)





2) Modification du contenu du courrier

**Comment by jrduscher** [comment]
> **Modif du titre et de l'objet du modèle actuel:**
remplacer: Signalement de maltraitance au travail par Signalement de faits pouvant relever du harcèlement moral.
