### ISSUE TITLE
matomo: dynamic action_name

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#722]
Matomo utilise le titre de la 1ère page chargée en tant que `action_name` pour les évènements ultérieurs. ceci doit être dû au mode SSR/[SPA](https://fr.wikipedia.org/wiki/Application_web_monopage)

Voir si on doit utiliser [l'API JS](https://developer.matomo.org/api-reference/tracking-javascript) pour fixer ça, ex `setDocumentTitle`

**Comment by UnbearableBear** [comment]
@revolunet Tu es dessus ou je prends ?

**Comment by revolunet** [comment]
yes you can :)
