### ISSUE TITLE
Find a way to enforce css property order of styled-components

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#735]
Something like that:
https://webdesign.tutsplus.com/articles/outside-in-ordering-css-properties-by-importance--cms-21685
 or:
1- Tout ce qui est display et positionnement (display: flex, z-index, position absolute etc.)
2 - Marges / padding
3 - Tout ce qui est typo
4 - Tout ce qui est visuel (background first, then borders, then box shadows etc)
5 - d'éventuels trucs restants

**Comment by ClementChapalain** [comment]
c'est faisable dans le sprint 14 @UnbearableBear ?

**Comment by ClementChapalain** [comment]
a priori non pas pour le sprint 14

**Comment by lionelB** [comment]
je suis pas sur qu'il soit nécessaire de faire une issue pour ça (l'ordre des regle css n'est pas un "problême" mais plutot un confort pour le dev), sinon on risque de se retrouver avec beaucoup d'issues "pense-bête"

**Comment by UnbearableBear** [comment]
Oui je suis d'accord sur le fait que le terme `issue` n'est pas adapté ici, c'est juste un pense bête mais ou le mettre si ce n'est pas là ?

**Comment by revolunet** [comment]
toujours utile ?

**Comment by UnbearableBear** [comment]
Hummm je pense que ça peut être utile ! Il faut que je regarde rapido si c'est faisable facilement
