### ISSUE TITLE
Ne pas oublier le droit conventionnel

### ISSUE THREAD

**Issue by Piermat** [SocialGouv/code-du-travail-numerique#747]
Bonjour, 

Attention avec vos modèles qui devraient le plus souvent être précédés d'une mention alerte sur la possibilité de norme conventionnelle contraire (période d'essai, maintien de salaire, indemnité de licenciement, ancienneté, etc... )

Ah bon, le droit du travail n'est pas harmonisé....

**Comment by ClementChapalain** [comment]
Merci pour votre collaboration :)

**Comment by ClementChapalain** [comment]
Fait sur les différents contenus du site
