### ISSUE TITLE
Divers - Fiches SP

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#748]
+ Problème affichage de la fiche de service public F2918 (cause inconnue)
+ problème avec la fiche F22549 qui a un élément qui n'est traité qui fait qu'elle ne s'affiche pas non plus.
+ Pareil pour la fiche F32471
+ ajout d'une fiches SP https://www.service-public.fr/particuliers/vosdroits/F2309 ( fiche planquée dans le thème loisirs)
+ F2406 (licenciement protection du représentant personnel) Dans la partie "Durée" remplacer l'élément par un accordéon.

**Comment by UnbearableBear** [comment]
+ problème avec la fiche F22549 qui a un élément qui n'est traité qui fait qu'elle ne s'affiche pas non plus.
 + ajout d'une fiches SP https://www.service-public.fr/particuliers/vosdroits/F2309 ( fiche planquée dans le thème loisirs)
+ F2406 (licenciement protection du représentant personnel) Dans la partie "Durée" remplacer l'élément pas un accordéon.

**Comment by UnbearableBear** [comment]
RAF :
+ problème avec la fiche F22549 qui a un élément qui n'est traité qui fait qu'elle ne s'affiche pas non plus.
+ F2406 (licenciement protection du représentant personnel) Dans la partie "Durée" remplacer l'élément par un accordéon.

**Comment by virginielastisneres** [comment]
- ajouter la fiche SP suivante : https://www.service-public.fr/professionnels-entreprises/vosdroits/F1691 => Comment se distingue le travailleur indépendant du salarié ?

**Comment by virginielastisneres** [comment]
- ajouter la fiche SP suivante : https://www.service-public.fr/professionnels-entreprises/vosdroits/F2742 => Création d'entreprise : levée provisoire des clauses d'exclusivité

**Comment by lionelB** [comment]
@virginielastisneres tu peux créer un nouvelle issue avec les nouvelles fiches à rajouter, ce n'est pas nécessaire de ré-ouvrir l'ancienne issue

**Comment by virginielastisneres** [comment]
@lionelB d'acc :D
