### ISSUE TITLE
10 résultats seulement affichés mais le faceting indique qu'il y en a des centaines

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#751]
Est-ce que ce n'est pas un peu frustrant pour l'utilisateur ?

**Comment by ClementChapalain** [comment]
besoin d'une refonte de la page d'affichage des résultats a priori

**Comment by lionelB** [comment]
> besoin d'une refonte de la page d'affichage des résultats a priori

refonte carrément ?

**Comment by ClementChapalain** [comment]
c'était plutôt une note à moi-même pardon :) pas forcément pour cette tâche, c'est juste qu'on a de plus en plus de trucs qui nous bloquent sur cette page :
- affichage au même niveau de résultats juridiques (cdt, ccns) et de résultats français facile alors que généralement l'usager va chercher soit l'un soit l'autre, et le mode d'affichage devrait être différent (pour le cdt par exemple on devrait surement afficher un extrait du texte, mais pas pour les réponses en français facile)
- besoin de plus mettre en avant les outils et les modèles qui vont aider l'usager à vraiment appliquer le droit
- intégration de plus de facetting (CCN notamment)
- ce bug

mais à détailler dans une autre tâche, pas un chantier pour tout de suite

**Comment by UnbearableBear** [comment]
new design à venir
