### ISSUE TITLE
Ajout de nouvelles fiches du ministère du travail (l'apprentissage, égalité FH, harcelement)

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#753]
ci-dessous les liens de fiches du Ministère du travail : 
- https://travail-emploi.gouv.fr/formation-professionnelle/formation-en-alternance-10751/contrat-apprentissage
- https://travail-emploi.gouv.fr/formation-professionnelle/formation-en-alternance-10751/article/l-aide-au-financement-du-permis-de-conduire-pour-les-apprentis
- https://travail-emploi.gouv.fr/formation-professionnelle/formation-en-alternance-10751/l-apprentissage-160/etre-apprenti/
- https://travail-emploi.gouv.fr/formation-professionnelle/formation-en-alternance-10751/l-apprentissage-160/etre-apprenti/article/les-5-etapes-a-suivre-pour-entrer-en-apprentissage
- https://travail-emploi.gouv.fr/formation-professionnelle/formation-en-alternance-10751/l-apprentissage-160/etre-apprenti/article/comment-decrocher-un-contrat-en-apprentissage
- https://travail-emploi.gouv.fr/formation-professionnelle/formation-en-alternance-10751/l-apprentissage-160/etre-apprenti/article/les-services-proposes-par-le-portail-de-l-alternance

**Comment by ClementChapalain** [comment]
est-ce que c'est le même travail que sur #661 ?

**Comment by ClementChapalain** [comment]
poke @revolunet ☝️

**Comment by lionelB** [comment]
meme combat ;) je ferme l'ancienne issue et rajoute les liens a celle-ci

**Comment by lionelB** [comment]
from https://github.com/SocialGouv/code-du-travail-numerique/issues/661#issuecomment-480731087
> Certaines fiches ne sont pas encore mises dans le code du travail numérique. Elles sont très récentes.
> Exemples :
>
> - fiche sur l'index égalité hommes-femmes comment le calculer ? https://travail-emploi.gouv.fr/actualites/l-actualite-du-ministere/article/index-de-l-egalite-femmes-hommes-comment-le-calculer
> - fiche Comment agir face au harcèlement sexuel au travail ? https://travail-emploi.gouv.fr/actualites/l-actualite-du-ministere/article/comment-agir-face-au-harcelement-sexuel-au-travail

**Comment by ClementChapalain** [comment]
merci !

**Comment by virginielastisneres** [comment]
merci beaucoup :D excusez moi je viens de voir vos messages que maintenant...

**Comment by virginielastisneres** [comment]
nouvelle fiche du ministère à rajouter :) : https://travail-emploi.gouv.fr/formation-professionnelle/droits-a-la-formation-et-orientation/compte-personnel-formation
