### ISSUE TITLE
Refaire l'UI des questions (références juridiques + pour aller plus loin)

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#755]
C'est un peu bizarre le rendu en dessous de la réponse ici non ? 
https://codedutravail.num.social.gouv.fr/question/dans-les-hcr-quel-est-le-preavis-de-demission-6-smnr0oyizfvq

**Comment by ClementChapalain** [comment]
je comprends pas ce que tu veux dire, tu peux préciser stp ? et les liens localhost on peut pas y accéder nous :)

**Comment by UnbearableBear** [comment]
Ah oui pardon ! j'édite le lien !

**Comment by UnbearableBear** [comment]
Je ne trouve ça pas clair; est-ce lié à la hiérarchie des normes ? Aussi l'interface fait un peu "fourre tout" mais c'est très subjectif. Tu peux close l'issue si tu n'es pas d'accord 
<img width="1093" alt="Screenshot 2019-04-23 at 10 33 12" src="https://user-images.githubusercontent.com/705453/56566591-5a4c1e00-65b3-11e9-9752-49461c7f7526.png">

**Comment by ClementChapalain** [comment]
C'est vrai, en fait c'est la première version de la hiérarchie des normes qui avait été implémenté il y a longtemps. Je suis d'accord avec toi, mais pas prio pour tout de suite je pense !

**Comment by lionelB** [comment]
je pense que c'est complémentaire à la hiérarchie des normes.
Ce sont des contenus complémentaires qui sont liés au même thème.

**Comment by UnbearableBear** [comment]
New design incoming
