### ISSUE TITLE
Calculateur d'indemnité de licenciement : amélioration calcul + nouveau design

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#756]
## Contexte

Nous souhaitons retravailler le calculateur d'indemnité de licenciement afin d'améliorer l'expérience utilisateur et de corriger quelques bugs dans les formules de calcul.

## Design

https://www.figma.com/proto/UGkd7UFF3gJSb3a35ClTtPKW/Code-du-travail-num%C3%A9rique?node-id=297%3A0&viewport=47%2C66%2C0.323337&scaling=min-zoom

## Spécifications

Se référer au Figma + aux spécifications ci-dessous.

### Etape 1 - Informations générales

Si l'utilisateur clique sur CDD ou contrat d'intérim dans la première question ou sur faute grave ou lourde dans la deuxième, le bouton "suivant" doit être désactivé et le disclaimer doit être affiché.

Si l’utilisateur a été licencié pour inaptitude suite à accident du travail ou maladie professionnelle reconnue, alors il faudra multiplier par 2 son IDL.

### Etape 2 - Ancienneté

Les champs doivent être des sélecteurs calendrier pour simplifier la saisie à l'utilisateur.

Pour les absences prolongées de plus d'un mois, voici la liste des absences à proposer dans le dropdown et la manière de les comptabiliser dans l'ancienneté :
- Absence  pour maladie non professionnelle : 100% du temps d'absence
- Grève : 100% du temps d’absence
- Mise à pied : 100% du temps d’absence
- Congé sabbatique : 100% du temps d’absence
- Congé pour création d'entreprise : 100% du temps d’absence
- Congé de solidarité familiale : 100% du temps d’absence
- Congé de solidarité internationale : 100% du temps d’absence
- Congé parental d'éducation : 50% du temps d’absence

Ensuite on calcule 2 anciennetés différentes :
- A1 = date de notification du licenciement - date d’entrée - absences prolongées renseignées (selon le pourcentage à intégrer)
- A2 = date de sortie - date d’entrée - absences prolongées renseignées (selon le pourcentage à intégrer)

A1 va nous permettre de savoir si l’indemnité est due.

A2 va nous permettre de calculer le montant de l’indemnité. À partir d’A2, on calcule également A2_inf_10 = le nombre d’années pendant les 10 premières années (10e année incluse) et A2_sup_10 = le nombre d’années pendant les années après les 10 premières. Par exemple si A2 = 15,4 alors A2_inf_10 = 10 et A2_sup_10 = 5,4.

### Etape 3 - Alternance temps plein / temps partiel

Si l’utilisateur clique sur non, on ne fait rien.

Si l’utilisateur clique sur oui, alors on calcule son salaire de référence et on passe directement à l’étape 5.

Le bouton radio mois / année change uniquement la formulation des champs et du tableau suivant (cf. Figea).

On calcule S_ref de la manière suivante :
S_ref = Somme((i,1,nombre_de_périodes), salaire_brut_de_la_période * nombre_de_mois_ou_années_de_la_période) / nombre_total_de mois_ou_années

### Etape 4 - Salaire

À cette étape on va calculer le salaire de référence (S_ref) utilisé pour calculer l’indemnité.

- S_ref_1 = moyenne du brut (avec les primes mensuelles) des 12 derniers mois
- S_ref_2 = moyenne du brut (avec les primes mensuelles) des 3 derniers mois

Si l'utilisateur choisit de remplir ses 12 salaires, on présente 12 champs avec des libéllés des 12 derniers mois en prenant 1er mois = dernier mois complet avant le licenciement effectif (date de sortie). Par exemple si la date de sortie est le 15 avril 2019, alors 1er mois = mars 2019 et on affiche tous les mois dans l'ordre chronologique inverse de mars 2019 à avril 2018.

### Etape 4 bis - primes

On intègre ici les primes annuelles et exceptionnelles au salaire de référence :
- S_ref_1_primes = S_ref_1 + somme de toutes les primes annuelles et exceptionnelles des 12 derniers mois / 12
- S_ref_2_primes = S_ref_2 + somme de toutes les primes annuelles et exceptionnelles des 3 derniers mois / 12

Voici la liste des types de primes à proposer à l’utilisateur :
- Prime annuelle (versée 1 fois par an)
- Prime exceptionnelle

Ensuite on calcule S_ref = max(S_ref_1, S_ref_2)

### Etape 5

Le calcul de l’IDL est ensuite :

- Si la date de notification du licenciement <= 26.09.17
   - Si A1 < 1 an alors IDL = 0
   - Si A1 >= 1 an, alors IDL = 1/5 * A_inf_10 * S_ref + (1/5+2/15) * A_sup_10 * S_ref
- Si la date de notification du licenciement >= 27.09.17
   - Si A1 < 8 mois alors IDL = 0
   - Si A1 >= 8 mois, alors IDL = 1/4 * A_inf_10 * S_ref + 1/3 * A_sup_10 * S_ref

Si l’utilisateur a été licencié pour inaptitude suite à accident du travail ou maladie professionnelle reconnue (cf. étape 1), alors l’IDL est multiplié par 2.
[voir commentaire Indemnité spéciale de licenciement pour inaptitude)

## Next steps

Définir les textes d'aide à ajouter sur les `i` pour chaque question.

Définir le plan de tagage Matomo.

Retravailler la chimie et intégrer d'autres conventions collectives.

**Comment by jrduscher** [comment]
CORRECTION DE LA PRIME EXCEPTIONNELLE
**EXISTANT**:

> 3) Recueillir salaire brut mensuel**
> Afficher un formulaire comprenant 12 champs à remplir (4-10 caractères numériques type €)
> -> labelliser les champs mois 1 à 12
> -> détacher visuellement les 3 derniers et afficher " trois derniers mois de salaire"
> valider : si le nb de champs remplis <12; fin. afficher principe: "l'indemnité de licenciement est due au delà d'un an d'ancienneté "
> 
> Primes dont 13ème mois?
> 
> 
> 
> recueillir "sommeprime": prévoir soit un champ global, soit plusieurs
> afficher: indiquer le montant des primes exceptionnelles, et/ou 13ème mois
> (Prime)= (somme primes/12)
> a) moyenne des douze derniers mois
> s'il n'y a pas de prime ; (a)=moyenne(montants mois 1 à 12)
> si prime: (a)=moyenne((mois1+prime)+(mois2+prime)... (mois 12+prime))
> b) moyenne des 3 derniers mois
> s'il n'y a pas de prime ; (b)=moyenne(montants mois 10 à 12)
> si prime: (b)=moyenne((mois10+prime)+(mois11+prime)... (mois 12+prime))
> c) - si b>a, (c)=(b) sinon (c)=a

**A CORRIGER**
la variable prime est split en deux variables, prime_3mois,prime 9 mois
> (prime_3mois)= (somme primes/12) // prime perçu dans les trois derniers mois (saisie par l'user dans un champ)
> (prime_9mois,)= (somme primes/12) / prime perçu dans les trois derniers mois (saisie par l'user dans un champ)


**Interface**: WIP ( en cours de réfection voir le figma
"Gratification ou prime de caractère annuelle ou exceptionnelle, (aléatoire ou temporaire) "

**CALCUL**
**I) La prime exceptionnelle a lieu dans les 9 premiers mois.**
récupérr

a) moyenne des 3 derniers mois

= moyenne (mois10:mois 12) // la prime si percçu dans les mois 1 à 9 compris n'intervient pas dans le calcul

b)  moyenne des douze derniers mois
s'il n'y a pas de prime ; (a)=moyenne(montants mois 1 à 12)
si prime: (a)=moyenne((mois1+prime_9mois)+(mois2+prime_9mois)... (mois 12+prime_9mois))

II) La prime exceptionnelle a lieu dans les 3 derniers mois.
Récupérer prime 3 mois:  Notre calcul d'aujourd'hui cité au dessus.

**Comment by jrduscher** [comment]
**Calculateur de licenciement**
Historique des issues:
#131: Calcul indemnité temps plein temps partiel
#344 : pistes d'améioraiton
#308 : détection OPE 
#284 Ajouter la CCN métallurgie
#39 : issue d'origine, calcul indé légale+ CCn chimie+specs Metallurgie: accords nationaux.+ bureaux détudes techniques, commerce de gros, bouangerie artisanale, HCR, FEHAP, proporeté

corrections de bugs 
#281 
#239

**Comment by lionelB** [comment]
@ClementChapalain à l'etape 3 (salaire temps partiel 


> Si l’utilisateur clique sur oui, alors on calcule son salaire de référence et on passe directement à l’étape 5.

on doit pas passer à l'etape 4 pour la saisie des primes plutôt ?

**Comment by lionelB** [comment]
est ce qu'on peut d'ailleurs afficher l'étape des mois de salaire sur l'étape Temps partiel lorsque l'utilisateur repond `non` comme c'etait le cas avant ?

**Comment by ClementChapalain** [comment]
> on doit pas passer à l'etape 4 pour la saisie des primes plutôt ?

non en fait on ne prend pas en compte les primes dans ce cas là, on regarde juste le salaire brut global (avec les primes non-exceptionnelles) pondéré par les périodes temps plein / temps partiel, les primes c'est pour le calcul classique du salaire de référence

> est ce qu'on peut d'ailleurs afficher l'étape des mois de salaire sur l'étape Temps partiel lorsque l'utilisateur repond non comme c'etait le cas avant ?

oui c'est p-e plus logique de faire comme ça tu as raison

**Comment by lionelB** [comment]
closed by #853
