### ISSUE TITLE
SEO : alt text

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#757]
~mettre un alt text sur toutes nos images~

mettre alt="symbole de la Marianne, site public officiel" sur la marianne
mettre alt="" sur toutes les autres images

**Comment by lionelB** [comment]
alors c'est pas du tout obligé, surtout si l'image n'apporte rien au contenu

**Comment by ClementChapalain** [comment]
ok au temps pour moi, j'ai l'impression que la bonne pratique c'est de les mettre lorsque ça apporte qqchose pour l'accessibilité, du coup : 
- mettre un alt="" pour les icones
- mettre un vrai alt sur la mariane

cf. https://www.practicalecommerce.com/6-SEO-Myths-about-Alt-Tags

tu en penses quoi @lionelB ?

**Comment by UnbearableBear** [comment]
Ca apporte quoi en termes d'accessibilité de mettre un alt sur l'image de la marianne ? (qui est d'ailleurs la seule image du site je crois). Quelqu'un qui est mal voyant s'en tape je pense d'entendre son screen reader lui dire "tête de marianne".
La seule raison pour laquelle les alt sont importants pour le référencement, c'est parce que les moteurs de recherchent veulent que ton site soit accessible.
Rendre le lien de retour à la home accessible avec les bon wai-aria ça c'est une bonne valeur ajoutée !

**Comment by ClementChapalain** [comment]
la marianne est le symbole de tous les sites officiels donc c'est hyper important je pense, sans ça tu ne sais pas que tu es sur un site du gouvernement (à part en déchiffrant l'url).

c'est effectivement la seule image du site je confirme.

c'est quoi un wai-aria ?

**Comment by UnbearableBear** [comment]
Oui mais pour un mal voyant ce symbole n'a peut-être pas de sens
https://developer.mozilla.org/fr/docs/Accessibilit%C3%A9/ARIA ;)

**Comment by ClementChapalain** [comment]
d'où le besoin de mettre un alt qui dit un truc du genre : "symbole de la marianne, site officiel du gouvernement" :)

**Comment by UnbearableBear** [comment]
Fair enough :)

**Comment by lionelB** [comment]
on peut regarder aussi sur d'autre site de SE ou poser la question à romy

**Comment by ClementChapalain** [comment]
On vient d'assister à la présentation de Romy sur le styleguide et elle disait qu'il faut mettre alt="" sur toutes les icones qui ne servent à rien et un alt descriptif quand l'image porte du sens qui n'est pas retranscrit autrement dans l'interface
