### ISSUE TITLE
Failing tests when running from mono repo root

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#760]
Tout est dans le titre !

**Comment by lionelB** [comment]
t'as fait `yarn build` sur `@socialcouv/react-fiche-service-public`, `@cdt/ui` `@cdt/css` ?

**Comment by UnbearableBear** [comment]
En fait je trouve ça horrible de devoir faire un yarn jest -u dans chaque repo utilisant l'ui pour mettre à jour les snapshot quand j'update button par exemple et les tests fails quand on les run à la racine c'est surtout pour ça. Je suis dessus !

**Comment by lionelB** [comment]
faut éviter de faire  `jest -u` de manière auto. 
il vaut mieux faire un `jest --watch` et mettre à jour APR7S avoir vérifier que les fiff correspondent bien au modifs

**Comment by UnbearableBear** [comment]
Juste pour pouvoir faire un `yarn jest` global alors ! Tout comme on fait `yarn build`
