### ISSUE TITLE
BUG Fiche Service public F32471 Peut-on encore avoir un Dif dans le secteur privé ?

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#761]
![Capture](https://user-images.githubusercontent.com/48682104/56578343-c3408f80-65cd-11e9-9397-ecbe112cce95.PNG)
Ecran vide quand l'on clique sur la fiche dans le code du travail numérique

**Comment by UnbearableBear** [comment]
J'ajoute à la tache existante sur les fiches du service public

**Comment by virginielastisneres** [comment]
Merci Manu, je me suis rendu compte trop tard qu'il y avait déjà une issue…
