### ISSUE TITLE
IE11/FF regression

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#764]
Il semblerait que `object-assign`, `classnames` soient bundlés sans être transpilés pour notre ami IE11 :) du coup il reste des "fat arrows"... qui n'existent pas en ES3 👹

cdt-ui semble aussi non transpilé :)

**Comment by revolunet** [comment]
Et Firefox 52

**Comment by adipasquale** [comment]
https://app.lambdatest.com est pratique et le plan gratuit bien mieux que browserstack.com
