### ISSUE TITLE
Ministère du Travail: revoir la mise en forme

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#767]
L'affichage des extraits des fiches ministères n'est pas très user friendly.
>changement de taille des polices dans certines fiches au coeur du texte.

Aujourd'hui, Le paragraphe de la fiche ministère du travail est reconstitué dans une nouvelle fiche, qui reprend aussi l'entête et l'encart."A savoir " de la fiche ministère.

![image](https://user-images.githubusercontent.com/37538697/56678535-38da5780-66c3-11e9-86bc-2b39c1a1a981.png)

Le début du paragraphe se noie dans le à savoir. ( cf image)
Le corps du texte du paragraphe doit ressortir du reste
Modifs
TITRE : RAS
> Créer un espace entre le à savoir et le texte pour le mettre en valeur.
> Le style du chapeau introductif doit être différent du corps du texte (fond différent)
> L'encart à savoir doit être matérialisé ( c'est déjà le cas dans certaines de nos fiches curieusement) : ligne haut et bas

L'entête et le à savoir sont gérés comme suit sur la fiche ministère
![image](https://user-images.githubusercontent.com/37538697/56678761-c5851580-66c3-11e9-97e5-38544ec86d27.png)

**Comment by ClementChapalain** [comment]
je ne sais pas si c'est envisageable mais on pourrait aussi essayer d'utiliser les nouveaux composants créés par @UnbearableBear pour améliorer leur affichage comme les fiches de SP

**Comment by UnbearableBear** [comment]
Ca va être assez compliqué même si c'est n'est pas impossible: les composants s'attendent à avoir un input en JSON qui provient lui même d'un parsing du XML des fiches SP. On est sur quelque chose de très très très spécifique.

**Comment by ClementChapalain** [comment]
on ne peut pas utiliser ces composants à d'autres endroits du site simplement du coup ?

**Comment by UnbearableBear** [comment]
A moins de vraiment se mettre à faire un librairie UI et les mettre dedans, non.

**Comment by lionelB** [comment]
Ca pourrait pratique que les composants de fiche SP puisse se basé sur des props standard type children.
