### ISSUE TITLE
Nouvelle UI : Indiquer visuellement le focus sur le champ de recherche

### ISSUE THREAD

**Issue by jeremiecook** [SocialGouv/code-du-travail-numerique#78]
Pour l'accessibilité (notamment lors de la navigation par tabulation), il serait bien d'indiquer visuellement le champ en état "focus"

Cf : https://jeremiecook.github.io/code-du-travail-html/

**Comment by kemar** [comment]
Oui merci mais c'est déjà le cas et c'est le `focus` par défaut du navigateur qui fait le job.

C.f. https://www.tjvantoll.com/2013/01/28/stop-messing-with-the-browsers-default-focus-outline/

**Comment by jeremiecook** [comment]
Perso, je n’ai aucun changement au focus sur Firefox...

**Comment by kemar** [comment]
Oui c'est vrai ! Je ré-ouvre pour creuser ce point. Un contre avis ici notamment http://adrianroselli.com/2017/02/avoid-default-browser-focus-styles.html

**Comment by kemar** [comment]
Donc, je constate que ma stratégie de laisser la gestion du `focus` au navigateur ne marche pas bien 😢 

Le focus par défaut de Firefox :

- est très peu visible [bug 251198](https://bugzilla.mozilla.org/show_bug.cgi?id=251198) (vieux de presque 15 ans)
- a un comportement très inconsistent [bug 1112717](https://bugzilla.mozilla.org/show_bug.cgi?id=1112717)

Les power users peuvent configurer la taille dans les préférences avec [`focus_ring_width`](http://kb.mozillazine.org/Browser.display.focus_ring_width).

Je me suis rendu compte qu'il y a aussi des problèmes sous Edge.

Du coup je commence par adopter une stratégie intermédiaire https://github.com/SocialGouv/code-du-travail-html/commit/e7b5b3cbda088f6ff930bdf42470636b158d518d

Note que le commit ci-dessus fait partie du dépôt de code de l'intégration HTML/CSS du Ministère des Affaires Sociales https://github.com/SocialGouv/code-du-travail-html

Je ferme cette issue, ce point sera fixé lors du prochain déploiement !
