### ISSUE TITLE
Ajout metas social sharing

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#79]

**Comment by ClementChapalain** [comment]
Tu entends quoi par "metas" @revolunet ?

**Comment by lionelB** [comment]
j'imagine les meta github cards / facebook opengraph ?
pour que ça s'affiche bien quand tu partages un lien sur twitter / facebook

**Comment by revolunet** [comment]
Oui et les balises classiques type titre/description
