### ISSUE TITLE
Fiches du service public liées aux associations ?

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#799]
https://www.service-public.fr/associations/
Il y a pas mal de choses liées au code du travail dedans, il faudrait peut-etre les intégrer au CDTN ?
Par exemple, mon père travail via le GUSO et apparement il y a pas mal d'infos là dessus dans les fiches SP liées aux associations

https://www.service-public.fr/associations/vosdroits/F766
https://www.service-public.fr/associations/vosdroits/F153
https://www.service-public.fr/associations/vosdroits/F1928

**Comment by virginielastisneres** [comment]
1 de + 
https://www.service-public.fr/associations/vosdroits/F2607

**Comment by virginielastisneres** [comment]
1 de + 
https://www.service-public.fr/associations/vosdroits/F34030

**Comment by jrduscher** [comment]
RECAP @UnbearableBear @virginielastisneres 

// Fiches déjà documentées dans le excel:
- [x] F34030 88 - Emploi et formation - Formation - Dispositifs d'accès à la formation
- [ ] F2607 36 - Représentation du personnel et négociation collective - Négociations de branche
- [ ] F766 52 - Recrutement et contrat de travail - Recrutement - Formalités d'embauche
- [ ] F153 10 - Recrutement et contrat de travail - Contrat de travail (approx)
- [ ] F1928 : 32 - Santé, sécurité et conditions de travail - Travailleurs et secteurs spécifiques
- [ ] F1125 : 14 - Salaire et Rémunération - Remboursement des frais de transport
- [ ] F1927 : 15 - Salaire et Rémunération - Salaire, primes et avantages
- [ ] F1926 : 49 - Conflits au travail et contrôle de la réglementation - Travail illégal
- [ ] F2335 : 20 - Temps de travail et congés - Congés
- [ ] F32081 8 - Conflits au travail et contrôle de la réglementation
- [ ] F34105 : 20 - Temps de travail et congés - Congés

**Comment by UnbearableBear** [comment]
Merci top @jrduscher
