### ISSUE TITLE
Problèmes de requêtes ES 

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#80]
https://trello.com/c/MnRD2NjX/12-cas-a-traiter

**Comment by jrduscher** [comment]
en attente de traitement pas Onogone, affinage elastic search

**Comment by revolunet** [comment]
quand la recherche ne donne pas de resultats, remonter petit à petit en enlevant des mots bien choisis.

ex : si "remboursement de frais mettalurgie" ne donne pas de résultat, chercher "remboursement de frais"

**Comment by lionelB** [comment]
est ce que ici le nlp pourrait pas nous aidé ? je suis tombé sur le cas 
[je suis employé à domicile, est il obligatoire d'avoir un contrat de travail](https://codedutravail-dev.num.social.gouv.fr/?q=je%20suis%20employ%C3%A9%20%C3%A0%20domicile%2C%20est%20il%20obligatoire%20d%27avoir%20un%20contrat%20de%20travail) donne une résultat mais si on enlève "d'avoir" (=> [lien](https://codedutravail-dev.num.social.gouv.fr/?q=je%20suis%20employ%C3%A9%20%C3%A0%20domicile%2C%20est%20il%20obligatoire%20%20un%20contrat%20de%20travail&facet=)) la requête remonte plus de résultat

Je pense aussi que c'est un bon cas ou le theme travail à domicile apparait indirectement

poke @mhavel et armand

**Comment by revolunet** [comment]
outdated
