### ISSUE TITLE
formule non disponible dans le calculateur d'indemnité

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#802]
La librarie Mathjax dans le calculateur d'indemnité ne se charge plus... 
C'est déjà la deuxième fois que le problème se pose. 

A réfléchir si on conserve le widget

**Comment by jrduscher** [comment]
@lionelB @ClementChapalain est en train de voir tout le design du calculateur, je ne crois pas que cette formule soit encore au programme

**Comment by jrduscher** [comment]
@lionelB @ClementChapalain @revolunet 

Issue fermée: la formule n'est plus utilisée avec la refonte du calculateur. ( à rouvrir par la suite au besoin)
