### ISSUE TITLE
Intégrer la liste des conseillers du salarié

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#81]
thème:  accompagnemnt des salariés/ entretien de licenciement.

Bas Rhin (067)
http://grand-est.direccte.gouv.fr/sites/grand-est.direccte.gouv.fr/IMG/pdf/arrete_du_02_03_2018.pdf

Haut-Rhin (068)
**http://grand-est.direccte.gouv.fr/Les-conseillers-du-salaries-18337**
http://grand-est.direccte.gouv.fr/sites/grand-est.direccte.gouv.fr/IMG/pdf/liste_des_conseillers_du_salarie_haut-rhin_avec_mise_a_jour_mel.pdf

Vosges (088)
http://grand-est.direccte.gouv.fr/sites/grand-est.direccte.gouv.fr/IMG/pdf/liste_conseillers_du_salarie_2017.pdf

Moselle (057)
http://grand-est.direccte.gouv.fr/sites/grand-est.direccte.gouv.fr/IMG/pdf/57-cs_arrete_raa20180504.pdf

Meuse (055)
http://grand-est.direccte.gouv.fr/sites/grand-est.direccte.gouv.fr/IMG/pdf/arrete_no2017-22_du_5_janvier_2017-2.pdf

Meurthe-et-Moselle (054)
http://grand-est.direccte.gouv.fr/sites/grand-est.direccte.gouv.fr/IMG/pdf/ud_54_liste_conseillers_du_salarie_au_15_septembre_2016.pdf

Haute Marne (052)
http://grand-est.direccte.gouv.fr/sites/grand-est.direccte.gouv.fr/IMG/pdf/52-arrete_avenant1_conseillers_2018.pdf

Marne (051)
http://grand-est.direccte.gouv.fr/sites/grand-est.direccte.gouv.fr/IMG/pdf/cs51_2018-2021.pdf

Aube (010)
http://grand-est.direccte.gouv.fr/sites/grand-est.direccte.gouv.fr/IMG/pdf/cs_ud10_arrete-mod2018.pdf

Ardennes (008)
http://grand-est.direccte.gouv.fr/sites/grand-est.direccte.gouv.fr/IMG/pdf/ardennes_liste_conseiller_10-08-2017-2.pdf

Doubs ( 025)
http://bourgogne-franche-comte.direccte.gouv.fr/sites/bourgogne-franche-comte.direccte.gouv.fr/IMG/pdf/ud_25_arrete_liste_departementale_conseillers_2017-2020.pdf

Territoire de Belfort ( 090)
http://bourgogne-franche-comte.direccte.gouv.fr/sites/bourgogne-franche-comte.direccte.gouv.fr/IMG/pdf/arrete_modificatif_conseillers_du_salarie_signe_internet.pdf

Haute Saône (070)
http://bourgogne-franche-comte.direccte.gouv.fr/sites/bourgogne-franche-comte.direccte.gouv.fr/IMG/pdf/diffusion_liste_conseiller_version_14.03.18.pdf

Nièvre (058)
http://bourgogne-franche-comte.direccte.gouv.fr/sites/bourgogne-franche-comte.direccte.gouv.fr/IMG/pdf/arrete_conseillers_du_salarie_ud_58_du_27.07.2018.pdf

Côte d'Or (021)
http://bourgogne-franche-comte.direccte.gouv.fr/sites/bourgogne-franche-comte.direccte.gouv.fr/IMG/pdf/arrete_prefectoral_no_804_du_26_octobre_2015.pdf

Jura (039)
http://bourgogne-franche-comte.direccte.gouv.fr/sites/bourgogne-franche-comte.direccte.gouv.fr/IMG/docx/liste_cs_par_circonscription_prud_homale.docx

Saône et Loire (071)
http://bourgogne-franche-comte.direccte.gouv.fr/sites/bourgogne-franche-comte.direccte.gouv.fr/IMG/pdf/liste_des_conseillers_du_salarie.pdf

Yonne (089)
http://bourgogne-franche-comte.direccte.gouv.fr/sites/bourgogne-franche-comte.direccte.gouv.fr/IMG/doc/conseillers_du_salarie__liste_2017_-3.doc

Ain (001)
http://auvergne-rhone-alpes.direccte.gouv.fr/sites/auvergne-rhone-alpes.direccte.gouv.fr/IMG/pdf/liste_des_conseillers_du_departement_de_l_ain_en_2017_pour_diffusion_mj_28_03_2018__.pdf

Savoie (073)
http://auvergne-rhone-alpes.direccte.gouv.fr/Liste-des-conseillers-du-salarie-17811

Haute - Savoie (074)
http://auvergne-rhone-alpes.direccte.gouv.fr/sites/auvergne-rhone-alpes.direccte.gouv.fr/IMG/pdf/liste_des_cs_maj_15_01_2018.pdf

Drôme (026)
http://auvergne-rhone-alpes.direccte.gouv.fr/sites/auvergne-rhone-alpes.direccte.gouv.fr/IMG/pdf/arrete_2017_conseillers_du_salarie_de_la_drome.pdf

Isère (038)
http://auvergne-rhone-alpes.direccte.gouv.fr/sites/auvergne-rhone-alpes.direccte.gouv.fr/IMG/pdf/arrete_paru_au_raa_le_1-3-2018_liste_conseillers_des_salaries_.pdf

Rhône (069)
http://auvergne-rhone-alpes.direccte.gouv.fr/sites/auvergne-rhone-alpes.direccte.gouv.fr/IMG/pdf/cs_-_liste_2015-2018.pdf
http://auvergne-rhone-alpes.direccte.gouv.fr/sites/auvergne-rhone-alpes.direccte.gouv.fr/IMG/pdf/cs_-_arrete_prefectoral_2015-2018.pdf

Loire (042)
http://auvergne-rhone-alpes.direccte.gouv.fr/sites/auvergne-rhone-alpes.direccte.gouv.fr/IMG/pdf/arrete_signe_21_aout_2017.pdf

Ardèche (007)
http://auvergne-rhone-alpes.direccte.gouv.fr/sites/auvergne-rhone-alpes.direccte.gouv.fr/IMG/pdf/arrete_conseillers_du_salarie_2017_2020-2.pdf

Allier (003)
http://auvergne-rhone-alpes.direccte.gouv.fr/sites/auvergne-rhone-alpes.direccte.gouv.fr/IMG/pdf/liste_conseiller_du_salarie_2017du_07-09-2017.pdf

Puy-de-Dôme (063)
http://auvergne-rhone-alpes.direccte.gouv.fr/sites/auvergne-rhone-alpes.direccte.gouv.fr/IMG/pdf/conseiller_du_salarie_arrete_26-02-2o16.pdf

Haute  Loire (043)
http://auvergne-rhone-alpes.direccte.gouv.fr/sites/auvergne-rhone-alpes.direccte.gouv.fr/IMG/pdf/liste_des_conseillers_du_salarie_2018.pdf

Cantal (015)
http://auvergne-rhone-alpes.direccte.gouv.fr/sites/auvergne-rhone-alpes.direccte.gouv.fr/IMG/pdf/liste_des_conseillers_2016_-2018_modifiee_le_20_mars_2018.pdf

Hautes Alpes (005)
http://paca.direccte.gouv.fr/sites/paca.direccte.gouv.fr/IMG/pdf/arrete_prefectoral_07-08-2018_-_assistance_du_salarie_lors_de_l_entretien_prealable_au_licenciement.pdf

Alpes-de-Haute-Provence (004)
http://paca.direccte.gouv.fr/sites/paca.direccte.gouv.fr/IMG/pdf/ap_2018.019.011_du_19.01.18_fixant_la_liste_des_conseillers_du_salarie.pdf

Vaucluse (084)
http://paca.direccte.gouv.fr/sites/paca.direccte.gouv.fr/IMG/pdf/arrete_du_22_fevrier_2018_signe_et_liste.pdf

Var (083)
http://paca.direccte.gouv.fr/sites/paca.direccte.gouv.fr/IMG/pdf/2018_02_23_ap_fixant_la_liste_des_conseillers_du_salarie.pdf

Bouches du Rhone (013)
http://paca.direccte.gouv.fr/sites/paca.direccte.gouv.fr/IMG/pdf/arrete_conseillers_salaries_du_11_juin_2018.pdf

Alpes Maritimes (006)
http://paca.direccte.gouv.fr/sites/paca.direccte.gouv.fr/IMG/pdf/arrete_2015-744_du_06-08-2015_original.pdf

Haute Corse (02B)
http://corse.direccte.gouv.fr/sites/corse.direccte.gouv.fr/IMG/pdf/arrete_du_12_juillet_2018_conseillers_du_salarie_2b.pdf

Corse du Sud (02A)
http://corse.direccte.gouv.fr/sites/corse.direccte.gouv.fr/IMG/pdf/arrete_r20-2018-05-18-001_du_18_mai_2018.pdf

Aisne (02)
http://hauts-de-france.direccte.gouv.fr/sites/hauts-de-france.direccte.gouv.fr/IMG/pdf/liste_conseillers_du_salarie_aisne.pdf

Nord (059)
Nord (Lille)
http://hauts-de-france.direccte.gouv.fr/sites/hauts-de-france.direccte.gouv.fr/IMG/pdf/raa_prefecture_-_arrete_cs_04-10-2016.pdf

Nord (Valencienne) 
http://hauts-de-france.direccte.gouv.fr/sites/hauts-de-france.direccte.gouv.fr/IMG/pdf/arrete_conseillers_du_salarie_3_.pdf

Oise (060)
http://hauts-de-france.direccte.gouv.fr/sites/hauts-de-france.direccte.gouv.fr/IMG/pdf/arrete_conseillersalarie_2018.pdf

Pas de Calais (062)
// on a des listes plus précises par canton sur ce département : ici http://hauts-de-france.direccte.gouv.fr/Les-conseillers-du-salarie-en-Hauts-de-France

http://hauts-de-france.direccte.gouv.fr/sites/hauts-de-france.direccte.gouv.fr/IMG/pdf/arrete_modificatif_du_8_mai_2018_liste_des_conseillers_du_salarie.docx.pdf

Somme (80)
//liste et avenants 2016 et 2017
http://hauts-de-france.direccte.gouv.fr/sites/hauts-de-france.direccte.gouv.fr/IMG/pdf/arrete_scanne_du_08-07-2016.pdf
http://hauts-de-france.direccte.gouv.fr/sites/hauts-de-france.direccte.gouv.fr/IMG/pdf/additif_du_20_janvier_2017_.pdf
http://hauts-de-france.direccte.gouv.fr/sites/hauts-de-france.direccte.gouv.fr/IMG/pdf/avenant_du_25-10-2017_.pdf

//IDF

Paris (075)
http://idf.direccte.gouv.fr/sites/idf.direccte.gouv.fr/IMG/pdf/liste_des_conseillers_2016.modifiee.fevrier_2018.pdf

Seine-et-Marne (077)
http://idf.direccte.gouv.fr/sites/idf.direccte.gouv.fr/IMG/pdf/arrete_2017_signe.pdf

Yvelines (078)
http://idf.direccte.gouv.fr/sites/idf.direccte.gouv.fr/IMG/pdf/20180514_112414.pdf

Essonne (091)
http://idf.direccte.gouv.fr/sites/idf.direccte.gouv.fr/IMG/pdf/arrete_modificatif_du_021117_liste_des_conseillers_du_salarie_de_l_essonne.pdf

Hauts-de-Seine (092)
http://idf.direccte.gouv.fr/sites/idf.direccte.gouv.fr/IMG/pdf/nouvel_arrete_2018.pdf

Seine-Saint-Denis (093)
http://idf.direccte.gouv.fr/sites/idf.direccte.gouv.fr/IMG/pdf/conseillers_du_salarie_-arrete_2015-2226_du_1er-09-2015.pdf

Val-de-Marne (094)
http://idf.direccte.gouv.fr/sites/idf.direccte.gouv.fr/IMG/pdf/liste_conseillers_du_salarie_94_-_raa_no18-2017.pdf

Val-d’Oise (095)
http://idf.direccte.gouv.fr/sites/idf.direccte.gouv.fr/IMG/pdf/ud95_liste_cs_2016-2019__modifie_le_30-01-2017-.pdf

Loiret (045)
http://centre-val-de-loire.direccte.gouv.fr/sites/centre-val-de-loire.direccte.gouv.fr/IMG/pdf/conseillers_du_salarie_au_25_02_2016_ud45.pdf

Eure-et-Loire (028)
http://centre-val-de-loire.direccte.gouv.fr/sites/centre-val-de-loire.direccte.gouv.fr/IMG/pdf/arrete_n_73_2017_du_29_mai_2017-_entretien_prealable_au_licenciement_.pdf

Indre-et-Loire (037)
http://centre-val-de-loire.direccte.gouv.fr/sites/centre-val-de-loire.direccte.gouv.fr/IMG/pdf/liste_des_cs_au_20180323.pdf

Indre (036)
http://centre-val-de-loire.direccte.gouv.fr/sites/centre-val-de-loire.direccte.gouv.fr/IMG/pdf/liste_conseillers_du_salarie_ud36_2018-2020.pdf

Cher (018)
http://centre-val-de-loire.direccte.gouv.fr/sites/centre-val-de-loire.direccte.gouv.fr/IMG/pdf/ud_18_arrete_prefectoral_2017-1-1500_conseillers_du_salarie_du_departement_du_cher.pdf

Loir et Cher (041)
http://centre-val-de-loire.direccte.gouv.fr/sites/centre-val-de-loire.direccte.gouv.fr/IMG/pdf/arrete_du_2_juillet_2018_renouvelant_la_liste_departementale_des_conseillers_des_salaries.pdf

Deux-Sèvres (079)
http://nouvelle-aquitaine.direccte.gouv.fr/sites/nouvelle-aquitaine.direccte.gouv.fr/IMG/pdf/ud79_liste_des_conseillers_du_salarie_arrete_prefectoral_2018.pdf

Creuse (023)
http://nouvelle-aquitaine.direccte.gouv.fr/sites/nouvelle-aquitaine.direccte.gouv.fr/IMG/pdf/arrete_prefectoral_2014_doc.pdf

Corrèze(019)
http://nouvelle-aquitaine.direccte.gouv.fr/sites/nouvelle-aquitaine.direccte.gouv.fr/IMG/pdf/2017-2020_liste_des_conseillers_du_salarie_modificative.pdf

Haute-Vienne (087)
http://nouvelle-aquitaine.direccte.gouv.fr/sites/nouvelle-aquitaine.direccte.gouv.fr/IMG/pdf/arrete_modificatif_du_18-04-2018.pdf

Charente (016)
http://nouvelle-aquitaine.direccte.gouv.fr/sites/nouvelle-aquitaine.direccte.gouv.fr/IMG/pdf/conseillers_salarie-arrete_20.03.18-avenant_4_liste_05.05.17.pdf

Charente-Maritime (017)
http://nouvelle-aquitaine.direccte.gouv.fr/sites/nouvelle-aquitaine.direccte.gouv.fr/IMG/pdf/avenant_1_du_28_fevrier_2018_a_l_arrete_du_20_octobre_2017.pdf

Vienne (086)
http://nouvelle-aquitaine.direccte.gouv.fr/sites/nouvelle-aquitaine.direccte.gouv.fr/IMG/pdf/avenant_no1_a_l_arrete_cs_du_6.11.2015.pdf

Gironde (033)
http://nouvelle-aquitaine.direccte.gouv.fr/sites/nouvelle-aquitaine.direccte.gouv.fr/IMG/pdf/liste_conseillers_du_salarie_2018-2021.pdf

Dordogne (024)
http://nouvelle-aquitaine.direccte.gouv.fr/sites/nouvelle-aquitaine.direccte.gouv.fr/IMG/pdf/arrete_liste_conseillers_du_salaire_2016-2019.pdf

Pyrénées-Atlantiques (064)
http://nouvelle-aquitaine.direccte.gouv.fr/sites/nouvelle-aquitaine.direccte.gouv.fr/IMG/pdf/liste_conseillers_2017.pdf

Lot-et-Garonne (047)
http://nouvelle-aquitaine.direccte.gouv.fr/sites/nouvelle-aquitaine.direccte.gouv.fr/IMG/pdf/liste_conseillers_du_salarie_2017_01_17.pdf

Landes (040)
http://nouvelle-aquitaine.direccte.gouv.fr/sites/nouvelle-aquitaine.direccte.gouv.fr/IMG/pdf/liste_des_conseillers_landes_2018_2019.pdf

Dordogne (024)
http://nouvelle-aquitaine.direccte.gouv.fr/sites/nouvelle-aquitaine.direccte.gouv.fr/IMG/pdf/arrete_liste_conseillers_du_salaire_2016-2019.pdf

Ariège (009)
http://occitanie.direccte.gouv.fr/sites/occitanie.direccte.gouv.fr/IMG/pdf/liste_conseillers_du_salarie_09.pdf

Aude (011)
http://occitanie.direccte.gouv.fr/sites/occitanie.direccte.gouv.fr/IMG/pdf/ud11arrete_conseiller_du_salarie_2018.pdf

Aveyron (012)
http://occitanie.direccte.gouv.fr/sites/occitanie.direccte.gouv.fr/IMG/pdf/liste_conseillers_du_salarie_de_l_aveyron_2014.pdf

Gard (030)
http://occitanie.direccte.gouv.fr/sites/occitanie.direccte.gouv.fr/IMG/pdf/ud30_liste_sonseillers_du_salarie_24-04-2018.pdf

Haute-Garonne (031)
http://occitanie.direccte.gouv.fr/sites/occitanie.direccte.gouv.fr/IMG/pdf/liste_cs_alpha_1ojuillet18_.pdfhttp://occitanie.direccte.gouv.fr/sites/occitanie.direccte.gouv.fr/IMG/pdf/liste_cs_par_os.pdf

Gers (032)
http://occitanie.direccte.gouv.fr/sites/occitanie.direccte.gouv.fr/IMG/pdf/arrete_no_32-2017-09-05-002_fixant_la_liste_des_conseillers_des_salaries_pour_le_departement_du_gers.pdf

Hérault (034)
http://occitanie.direccte.gouv.fr/sites/occitanie.direccte.gouv.fr/IMG/pdf/liste-cs-herault_2016-2019-au-16_mai_2018.pdf

Lot (046)
http://occitanie.direccte.gouv.fr/sites/occitanie.direccte.gouv.fr/IMG/pdf/listedesconseillers_salaries-_lot-2.pdf

Lozère (048)
http://occitanie.direccte.gouv.fr/sites/occitanie.direccte.gouv.fr/IMG/pdf/arrete_prefectoral_noud48direccte-2016-179-001_du_27_juin_2016.pdf

Hautes-Pyrénées (065)
http://occitanie.direccte.gouv.fr/sites/occitanie.direccte.gouv.fr/IMG/pdf/direccte_ud65_liste_des_conseillers_du_salarie_mise_a_jour_au_06_02_2018.pdf

Pyrénées-Orientales (066)
http://occitanie.direccte.gouv.fr/sites/occitanie.direccte.gouv.fr/IMG/pdf/arrete-conseillers-salaries-66.pdf

Tarn (081)
http://occitanie.direccte.gouv.fr/sites/occitanie.direccte.gouv.fr/IMG/pdf/liste_modificative_du_14_fevrier_2017.pdf

Tarn-et-Garonne (082)
http://occitanie.direccte.gouv.fr/sites/occitanie.direccte.gouv.fr/IMG/pdf/tarn-et-garonne-liste_cs_2013_maj_08-15_.pdf

Seine-Maritime (076)
http://normandie.direccte.gouv.fr/sites/normandie.direccte.gouv.fr/IMG/pdf/2017_12_18_liste_76_conseillers_du_salarie_2017-2020.pdf

Eure (027)
http://normandie.direccte.gouv.fr/sites/normandie.direccte.gouv.fr/IMG/pdf/2017_11_03_arrete_du_5_novembre_2017.pdf

Orne (061)
http://normandie.direccte.gouv.fr/sites/normandie.direccte.gouv.fr/IMG/pdf/2018_04_26_arrete_20_avril_2018_conseillers_salrie_orne.pdf

Manche (050)
http://normandie.direccte.gouv.fr/sites/normandie.direccte.gouv.fr/IMG/pdf/14_liste_des_conseillers_du_salarie_fevrier_2018.pdf

Calvados (014)
http://normandie.direccte.gouv.fr/sites/normandie.direccte.gouv.fr/IMG/pdf/liste_des_conseillers_du_salarie_du_calvados_modifiee_par_arrete_prefectoral_du_20_novembre_2017_.pdf

Loire-Atlantique (044)
http://pays-de-la-loire.direccte.gouv.fr/sites/pays-de-la-loire.direccte.gouv.fr/IMG/pdf/liste_conseillers_du_salarie_-maj_02_03_2018.pdf

Maine-et-Loire (049)
http://pays-de-la-loire.direccte.gouv.fr/sites/pays-de-la-loire.direccte.gouv.fr/IMG/pdf/liste_cons.salaries_2017.pdf

Mayenne (053)
http://pays-de-la-loire.direccte.gouv.fr/sites/pays-de-la-loire.direccte.gouv.fr/IMG/pdf/liste-conseiller-du-salarie-2016.pdf

Sarthe (072)
http://pays-de-la-loire.direccte.gouv.fr/sites/pays-de-la-loire.direccte.gouv.fr/IMG/pdf/conseillers_salaries_sarthe.pdf

Vendée (085)
http://pays-de-la-loire.direccte.gouv.fr/sites/pays-de-la-loire.direccte.gouv.fr/IMG/pdf/arrete_2017-31_-_annexe_liste_conseillers_du_salarie_actualisee_-_03.10.2017.pdf

Côtes d’Armor (022)
http://bretagne.direccte.gouv.fr/sites/bretagne.direccte.gouv.fr/IMG/pdf/arrete_cs_2016-2019_v3.pdf

Finistère (029)
http://bretagne.direccte.gouv.fr/sites/bretagne.direccte.gouv.fr/IMG/pdf/liste_sct_cs-pour_site_direccte-05-2017.pdf

Ille-et-Vilaine (035)
http://raa.bretagne.sit.gouv.fr/sit_1_ALK/upload/raa_35_ALK/acte/23189/update_word23189.pdf

Morbihan (056)
http://bretagne.direccte.gouv.fr/sites/bretagne.direccte.gouv.fr/IMG/pdf/liste_des_conseillers_du_salarie_-_morbihan_-_2018.pdf

Guadeloupe (971)
http://guadeloupe.dieccte.gouv.fr/sites/guadeloupe.dieccte.gouv.fr/IMG/pdf/conseillers_du_salarie_27062014.pdf

Martinique (972)
http://martinique.dieccte.gouv.fr/sites/martinique.dieccte.gouv.fr/IMG/pdf/liste_des_conseillers_au_27_072_018.pdf

Guyane (973)
http://guyane.dieccte.gouv.fr/sites/guyane.dieccte.gouv.fr/IMG/pdf/arrete_cs_2015308-0008_04_11_15.pdf

La Réunion (974)
http://reunion.dieccte.gouv.fr/sites/reunion.dieccte.gouv.fr/IMG/pdf/liste_conseillers_du_salarie_janvier_2018.pdf

Mayotte
?

**Comment by revolunet** [comment]
doit apparaitre sur les thèmes :
 - rupture du contrat / licenciement...

**Comment by jrduscher** [comment]
Fait. amélioration à prévoir: date du fichier en lien, normalisation des fichiers mises en ligne avec la MAESIC, regler la question Mayotte.

**Comment by jrduscher** [comment]
Autre point qui serait cool: 
ajouter quelques explication à destination du salarié:


"Le conseiller du salarié est chargé d'assister le salarié lors de **l'entretien préalable au licenciement** dans les **entreprises dépourvues d'institutions représentatives du personnel**"
"en savoir plus sur le rôle du conseiller du salarié : https://codedutravail-dev.num.social.gouv.fr/fiche-ministere-travail/le-conseiller-du-salarie-comment-se-faire-assister-par-un-conseiller-du-salarie

**Comment by revolunet** [comment]
A voir avec MAESIC : 
 - consolidation des données (crowdsourcing)
 - convention de nommage du fichier sur le site

**Comment by revolunet** [comment]
idem défenseurs syndicaux : #82

**Comment by ClementChapalain** [comment]
Je ne l'ai pas trouvé sur le site, est-ce que ces documents ont été intégrés ?

Pour info en regardant juste les 10 premiers lien j'ai eu 3 404, du coup il faut se poser la question de la validité de ces infos (+ sachant que ces conseillers sont renouvelés tous les 3 ans). Un lien vers le site du département qui héberge ce document serait p-e mieux.

**Comment by jrduscher** [comment]
Problème identifié et connu; déjà abordé avec la hieraarchie locale.Cela va supposer de l’organisationnel avec les services déconcentrés des DIRECCTE. Pour faire simple, dans chaque Direccte une personne est en charge de mettre à jour le fichier, il n'y a pas non plus de normes de nommages des fichiers, ni d'aliasage qui permettrait d'éviter le 404. Chaque fichier est hébergé dans une direccte.
