### ISSUE TITLE
Crée un component Table pour gérer le mobile ?

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#812]
Actuellement les tables ne rendent pas bien du tout sur mobile !

**Comment by lionelB** [comment]
est ce qu'on peut réaliser un quick fix pour l'instant avec wrapper scrollable pour limiter les dégats ?

**Comment by UnbearableBear** [comment]
C'est l'idée ! Mais comme il y a des tables un peu partout je me disais qu'on pourrait faire un component dans l'UI qui serait ce wrapper justement

**Comment by UnbearableBear** [comment]
done
