### ISSUE TITLE
Make a better distinction between h1 and h2 and so

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#817]
Currently the distinction is too hard to make 
<img width="776" alt="Screenshot 2019-05-09 at 11 57 38" src="https://user-images.githubusercontent.com/705453/57445148-ff245780-7251-11e9-8291-33a36078b519.png">

hints: slightly underline them ? Or increase difference in size-font. I think font-weight should stay the same

**Comment by lionelB** [comment]
not a big fan to underlining title, I would increase a bit h1

**Comment by ClementChapalain** [comment]
same, i prefer not to underline anything other than links, I would add some font-weight to h1 maybe

**Comment by ClementChapalain** [comment]
quelques références :
- https://polaris.shopify.com/design/typography#navigation
- https://designsystem.digital.gov/components/typography/
- http://codeforamerica.clearleft.com/

**Comment by UnbearableBear** [comment]
Thanks @ClementChapalain. I will probably make them more different with font-size rather than font weight

**Comment by UnbearableBear** [comment]
closed by #948

**Comment by ClementChapalain** [comment]
quelques remarques : 

### 1. le titre de la home devrait être un h1 non ?
![image](https://user-images.githubusercontent.com/5337489/60433394-0722c700-9c05-11e9-9c52-cf3aa733ef14.png)

### 2. il faudrait plus de marge ou padding sur les titres, c'est particulièrement visible dans le calculateur d'indemnités de licenciement sur le titre de l'outil et sur les questions :
![image](https://user-images.githubusercontent.com/5337489/60433531-5963e800-9c05-11e9-86e6-1f8b4febda77.png)
on peut le voir sur la page d'intro au droit du travail aussi :
https://codedutravail-dev.num.social.gouv.fr/droit-du-travail

**Comment by ClementChapalain** [comment]
je fais une nouvelle issue @UnbearableBear ou on le fait dans celle ci ? on peut faire les modifs ensemble sur ton ordi aussi, ça ira plus vite :)
