### ISSUE TITLE
Intégrer la liste des défenseurs syndicaux

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#82]
Puy de Dôme ( 063)
http://auvergne-rhone-alpes.direccte.gouv.fr/sites/auvergne-rhone-alpes.direccte.gouv.fr/IMG/pdf/liste_defenseurs_syndicaux_puy-de-dome_au_08-06-2018.pdf

ARA page dédiée:
http://auvergne-rhone-alpes.direccte.gouv.fr/Defenseurs-syndicaux-en-Auvergne-Rhone-Alpes

**Comment by revolunet** [comment]
doit apparaitre sur les thèmes : contestation
