### ISSUE TITLE
inclure annuaire des Organisations Syndicales et des Organisations Patronales

### ISSUE THREAD

**Issue by adipasquale** [SocialGouv/code-du-travail-numerique#826]
Le droit conventionnel (accords d'entreprises et conventions collectives) est conclu entre ces deux parties, ça serait important qu'ils soient présents d'une manière ou d'une autre sur le site.

**Comment by adipasquale** [comment]
@virginielastisneres je crois que tu as dit que tu savais où trouver une liste des OS ?

**Comment by jrduscher** [comment]
je pense que c'est ça: https://travail-emploi.gouv.fr/dialogue-social/la-representativite-syndicale-et-patronale/article/coordonnees-des-organisations-syndicales-de-salaries

**Comment by jrduscher** [comment]
synthèse du fil slack: Standbye, les contenus en ligne sont obsolète. A suivre

**Comment by revolunet** [comment]
plus d'annuaire sur le site pour le moment
