### ISSUE TITLE
Ajouter icônes pour les thèmes de niveau 1

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#835]
Librairies utilisées :
- https://www.flaticon.com/packs/strategy-and-management-4
- https://www.flaticon.com/packs/interview-5
- https://www.flaticon.com/packs/miscellaneous-elements
- https://www.flaticon.com/packs/startups-16
- https://www.flaticon.com/packs/money-37
- https://www.flaticon.com/packs/time-59
- https://www.flaticon.com/packs/medical-hospital-3

Icônes : 
- Recrutement et contrat de travail
https://www.flaticon.com/free-icon/handshake_944052
- Salaire et Rémunération
https://www.flaticon.com/free-icon/invoice_940954
- Temps de travail et congés
https://www.flaticon.com/free-icon/back-in-time_1584808
- Emploi et formation
https://www.flaticon.com/free-icon/communications_944049
- Santé, sécurité et conditions de travail
https://www.flaticon.com/free-icon/first-aid-kit_530416
- Représentation du personnel et négociation collective
https://www.flaticon.com/free-icon/organization_944034
- Départ de l'entreprise
https://www.flaticon.com/free-icon/interview_942841
- Conflits au travail et contrôle de la réglementation
https://www.flaticon.com/free-icon/hired_942812

Pour l'attribution, il faut ajouter la phrase suivante dans le footer :
> icônes réalisées par Freepik depuis www.flaticon.com

cf. https://support.flaticon.com/hc/en-us/articles/207248209-How-I-must-insert-the-attribution-
Je n'ai pas trop d'idée pour une intégration réussie, je veux bien en discuter avec celui qui s'occupera de cette tâche

**Comment by ClementChapalain** [comment]
j'avais commencé un fichier pour mettre une icône par thème, même pour les thèmes de niveau inférieur, mais c'est beaucoup de travail vu qu'on a presque 300 thèmes et j'ai peur que ce soit plus compliqué qu'autre chose : https://docs.google.com/spreadsheets/d/1DlzPzXelWMBa9bVzLZO7isd8NIxXpXKY6f8sw--RTfE/edit#gid=1619924493

**Comment by UnbearableBear** [comment]
On utilise un set d'icones bien spécifique aussi, il serait judicieux d'utiliser celui-ci:
https://feathericons.com/

**Comment by ClementChapalain** [comment]
ah ok @lionelB m'avait indiqué qu'on utilisait flaticons, cf. https://github.com/SocialGouv/code-du-travail-css#ic%C3%B4nes du coup je me suis basé là-dessus, avec feather on va être limité pour des trucs un peu compliqués genre représentation du personnel

**Comment by jrduscher** [comment]
Réutilisation possible de pictos précédents: https://github.com/SocialGouv/code-du-travail-numerique/tree/master/packages/code-du-travail-frontend/static/assets/icons

- départ de l'entreprise: https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-frontend/static/assets/icons/file-3.svg
- salaire et rémunération: https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-frontend/static/assets/icons/coins.svg
- temps de travail et congés:  https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-frontend/static/assets/icons/time.svg
- recrutement et contrat de travail : https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-frontend/static/assets/icons/hiring-1.svg
- emploi et formation: https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-frontend/static/assets/icons/certificate.svg
- représentation du personnel et négociation collective: https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-frontend/static/assets/icons/handshake.svg
- santé, sécurité et conditions de travail: https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-frontend/static/assets/icons/shield.svg
- conflit au travail et inspection du travail: https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-frontend/static/assets/icons/book_web.svg
