### ISSUE TITLE
BUG Fiche SP n°F21006 - écriture en gras

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#836]
Dans une fiche SP sur le CDTN une partie du texte de la fiche est écrite en gras alors que dans l'originale sur service public.fr le texte n'est pas en gras.

**Comment by virginielastisneres** [comment]
![pec](https://user-images.githubusercontent.com/48682104/58012155-1f76d080-7af4-11e9-95b8-4e8aa02354bb.PNG)

**Comment by ClementChapalain** [comment]
est-ce que tu peux mettre le lien vers la fiche stp ? :)

**Comment by virginielastisneres** [comment]
Yes :) => https://www.service-public.fr/particuliers/vosdroits/F21006

**Comment by virginielastisneres** [comment]
autre fiche dans laquelle j'ai trouvé le bug => https://www.service-public.fr/particuliers/vosdroits/F15478
![W](https://user-images.githubusercontent.com/48682104/58107470-34359000-7bea-11e9-8015-d3a3d384f044.PNG)

**Comment by virginielastisneres** [comment]
idem pour celle là => https://www.service-public.fr/particuliers/vosdroits/F2327
![image](https://user-images.githubusercontent.com/48682104/58167420-37815800-7c8c-11e9-87ec-fd6d10db43ca.png)

**Comment by virginielastisneres** [comment]
autre fiche => https://www.service-public.fr/particuliers/vosdroits/F592
![image](https://user-images.githubusercontent.com/48682104/58261087-f1092780-7d77-11e9-83a7-4a2494fed9bd.png)
