### ISSUE TITLE
Navigation thématique

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#837]
Amélioration du design de la navigation thématique :
https://www.figma.com/proto/UGkd7UFF3gJSb3a35ClTtPKW/Code-du-travail-num%C3%A9rique?node-id=577%3A0&viewport=2560%2C563%2C0.6629151701927185&scaling=min-zoom&redirected=1

L'objectif est de simplifier la séparation entre la navigation et les résultats

**Comment by ClementChapalain** [comment]
j'ai mis à jour le proto vous en pensez quoi ? @lionelB @virginielastisneres @jrduscher
https://www.figma.com/proto/UGkd7UFF3gJSb3a35ClTtPKW/Code-du-travail-num%C3%A9rique?node-id=845%3A0&viewport=406%2C272%2C0.06031305715441704&scaling=min-zoom
![image](https://user-images.githubusercontent.com/5337489/58086948-e015b600-7bbf-11e9-8ca3-dae568a84e63.png)
![image](https://user-images.githubusercontent.com/5337489/58086957-e5730080-7bbf-11e9-802f-160a4f929bf4.png)

**Comment by virginielastisneres** [comment]
Est-ce que c'est possible de décaler un peu plus les sous-thèmes dans la 2ème image. Cela permettrait de voir un peu mieux que c'est des sous-thèmes voire des sous sous-thèmes ?

**Comment by ClementChapalain** [comment]
J'ai un peu modifié (cf. le figma) je pense que c'est mieux tu as raison

**Comment by lionelB** [comment]
Est ce que c'est possible d'avoir le champ de recherche comme il est actuellement pour avoir une idée qui se rapproche un peu plus de ce que ca va donné ?

**Comment by lionelB** [comment]
au fait, c'est super propre !!

**Comment by lionelB** [comment]
je me demande si il faudrait pas commencer à intégrer une pagination par contre

**Comment by ClementChapalain** [comment]
pour la navigation il faut voir si ça charge lentement mais j'ai l'impression qu'on aura pas beaucoup de contenu par thème au début si ?

j'ai testé avec le header actuel ça donne ça :
![image](https://user-images.githubusercontent.com/5337489/58105814-61cd0a00-7be7-11e9-9d10-44b5051e835f.png)

**Comment by jrduscher** [comment]
+1 d'une ca fait plus propre avec une marge avec des trucs dedans, de l'autre niveau navi c'est pas mal du tout comme ça.

**Comment by jrduscher** [comment]
par contre ce serait bien de pouvoir garder/proposer le facetting d'une manière ou d'une autre n complément, non?

**Comment by lionelB** [comment]
@ClementChapalain question "responsive" niveau largeur de page / alignement, tu voyais ca évoluer comment  ?  car initialement on a un contenu qui est centré avec une largeur max d'environ 
 ~1200px

**Comment by ClementChapalain** [comment]
on peut imaginer un bouton pour sélectionner le thème qui serait en haut de la page et ouvre l'arborescence je pense.

j'imagine qqchose comme ça en version mobile :
https://laruchequiditoui.fr/fr/assemblies/6434/products

**Comment by ClementChapalain** [comment]
@lionelB vu avec aurélie elle va faire une passe sur le design elle a quelques idées pour rendre le truc plus compréhensible et accessible :) on met en pause donc

**Comment by lionelB** [comment]
@ClementChapalain est ce qu'on pourrait avoir quelques mockup histoire de pouvoir attaquer ?

**Comment by ClementChapalain** [comment]
on fait le point avec @auremie cette après-midi je te tiens au courant, désolé pour le délai

**Comment by revolunet** [comment]
intégré depuis
