### ISSUE TITLE
Feedbacks en environnement de test

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#840]
Aujourd'hui les formulaires du module de feedback sont envoyés sur tous les environnements ce qui fausse les stats quand on fait des tests. On peut envisager 2 possibilités :
- soit on envoie un paramètre supplémentaire qui permet de distinguer les environnements et on filtre dans l'étude
- soit on envoie les formulaires que lorsqu'on est sur la version de prod

**Comment by revolunet** [comment]
Ajouter le hostname dans les infos envoyées, comme ca on peut toujours tester ?

**Comment by UnbearableBear** [comment]
Si je file le node_env c'est bon ? (ce sera ptete plus facile de filter par pertinence comme ça)

**Comment by lionelB** [comment]
je pense que cdtn-dev et prod sont avec un NODE_ENV=production

**Comment by UnbearableBear** [comment]
Ah flute ! ok ok
