### ISSUE TITLE
Compréhension orthographique du suggesteur

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#841]
# Suggester

Donc dans le site, actuellement, on a un "suggester" qui permet à l'usager d'avoir des propositions de requêtes.

Le fonctionnement actuel est assez simple mais la fonction est critique car elle permet de préqualifier la question usager. De plus c'est la première interaction avec l'usager donc il faut qu'on soit très performants en terme de qualité des suggestions.

<img width="860" alt="Capture d’écran 2019-05-15 à 11 01 59" src="https://user-images.githubusercontent.com/124937/57763230-4488cf00-7701-11e9-8e71-35e11e7ff5ee.png">

### Fonctionnement actuel :

 - Le suggester est une API, tu peux voir un exemple ici : https://cdtn-nlp.num.social.gouv.fr/api/suggest?q=pr%C3%A9avis
 - Le code est dispo sur https://github.com/ArmandGiraud/autosuggest
 - Dans ce repo tu as des données d'exemple (dans autosuggest/data).
 - Le suggester va proposer les requetes les plus approchantes, avec quelques traitements textuels

Les données viennent de divers scrappings faits par les EIG sur les questions les plus fréaquemment posées et on ne veut PAS diffuser ces données pour l'instant (attention à ne pas les commit).

Armand pourra te détailler les algos mis en oeuvre sur le suggester

Principal défaut actuel : pas de gestion faute d'orthographe/approximations + données à affiner

### Pistes à explorer :

On pense qu'en s'appuyant sur les données récoltées et le moteur d'ElasticSearch (ES) on pourrait gérer ce problème et avoir un comportement plus "flexible" pour "tuner" les résultats grâce au query language d'ElasticSearch. 

 - indexer les requetes et leur probabilité dans ElasticSearch pour pouvoir requeter dessus avec ES. ceci nous permettrait de gérer les fautes d'orthographe.
 - L'usager doit voir en premier les requêtes les plus fréquentes qui correspondent

Pour commencer à travailler sur le sujet, je te conseille de faire un projet "a part" avec un ElasticSearch dédié (avec Docker) dans lequel tu injecterais les données de prod. 

Pour simplifier, il y a 2 scripts à faire : 
 - un qui transforme et injecte les données dans un index ES dédié
 - un qui requête ES pour récupérer des suggestions

Idéalement on aimerait que le code soit en JavaScript pour mieux s'intégrer au reste du projet, et l'équipe sera à même de t'aider, mais si c'est un problème pour toi on accepte aussi le Python :)

Pour tester, tu peux soit créer deux scripts (ex: indexer.js et query.js) qui vont indexer et requêter, ou utiliser kibana, une UI pour Elastic qui permet d'interroger via l'interface web. Lionel pourra t'aider sur la mise en place d'un kibana de test.

Quelques pointeurs :

 - Exemple de script JS pour indexer des données dans Es : https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-api/tests/create_indexes.js
 - Doc officielle ES/suggester : https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html
 - Doc officielle ES/phonétique : https://www.elastic.co/guide/en/elasticsearch/plugins/7.0/analysis-phonetic.html

### Objectifs :

 - Valider la pertinence d'ES pour le suggester
 - Trouver une solution pour pouvoir affiner "manuellement" les résultats (supprimer les doublons et fautes d'ORTH des résultats proposés)
 - Définir le process de MAJ de ces données de suggestion
 - Supprimer des suggestions les résultats qui ne mènent à rien ou incohérents
 - Extraire les données de MATOMO (analytics) pour les réinjecter dans le suggester
 - Audit/mesures performances

**Comment by maxgfr** [comment]
@romain-b13 https://github.com/SocialGouv/code-du-travail-numerique/pull/4741#issuecomment-1325676759
