### ISSUE TITLE
Gestion des liens internes de contenus externes

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#842]
Lorsqu'une fiche SP ou MT ou CDT contient un lien "relatif" dans son texte, l'utilisateur est redirigé vers une url interne qui n'existe pas, donc une 404.

L'erreur nous est remontée dans sentry et est assez fréquente (plusieurs fois par jour)

**Comment by revolunet** [comment]
Exemple de lien en question sur [cette fiche](https://codedutravail-dev.num.social.gouv.fr/fiche-ministere-travail/licenciement-pour-motif-economique-comment-est-notifie-le-licenciement?q=La%20proc%C3%A9dure%20de%20licenciement%20%C3%A9conomique%20de%202%20%C3%A0%209%20salari%C3%A9s) dans "en cas de licenciement dépourvu de cause réelle et sérieuse."

**Comment by lionelB** [comment]
normalement les liens sont censés etre modifié lors du scrap pour pointer sur le site externe, je regarde pourquoi ce n'est pas le cas
