### ISSUE TITLE
Outil indemnité de licenciement : le cas de l'indemnité de  rupture des assistantes et assistants maternels

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#849]
from JR cf https://github.com/SocialGouv/code-du-travail-numerique/issues/39#issuecomment-486336278

branche Assistante maternelle du particulier employeur:

Explication: L'indemnité légale de licenciement est prévue par le code du travail. Le statut des assistatns maternels du Particulier employeur est régit par dispositions du code de l'action sociale et des familles et du code du travail, pour les matières expressément cités dans le CASF qui renvoient au CDTL. L423-24 CASF.
=> L'indemnité légale de licenciement telle que prévue dans le code du travail ne s'applique pas pour une assistante maternelle; ( le juge confirme ce point).

Donc, pour calculer l'indemnité de rupture ( on ne parle pas d’indemnité de licinciment) d'un(e) assistant(e) maternel(le) du particulier employeur, seule la CCN doit être utilisée.

**CALCUL**
Si CCN= 2395; convention collective des assistants maternels du particulier employeur,

garder les variables suivantes:
En page résultat n'afficher que le résultat issu du calcul de l’indemnité de licenciement prévue par la convention collective.

Prévoir un wording particulier pour l'expliquer en page résultat: " L'indemnité légale de licenciement prévue par le code du travail n'est pas applicable pour une assistante maternelle".
S'affiche ensuite le résultat issu du calcul convention collective ( voir modif interface).

///WIP

**Comment by jrduscher** [comment]
**C'est un cas particulier** : l’indemnité légale n'est pas applicable, il n'est pas question non plus d'indemnité de licenciement mais de rupture. 
- soit on l’intègre et il faut prévoir un parcours qui détecte plus tôt la CCN et replace l'état du droit en page résultat.
- soit on considère qu'il ne s’agit pas de licenciement, et qu'on le shoot de cet outil pour l'instant.
-il faudra à terme regrouper les chantiers d’indemnité de rupture derrière une interface commune ( vu qu'il y a beaucoup de cas particuliers)
