### ISSUE TITLE
Test unitaire période d'essai boulangerie. Tests unitaires Sprint 17-28 septembre 2018

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#85]
### question : "précisez le thème svp"

 - durée initiale ?
 - renouvellement ?
 - durée max ?
 - rupture ?

### résultats pour "durée initiale"
 - réponse FAQ (aucune actuellement)
 - fiche MIN.T : cas général durée periode d'essai
 - fiche SP : cas général periode d'essai
 - disclaimer hierarchie des normes CDT + CCN + AE - L2253-3 (sauf renouvellement -> L2253-1)
 - Réponse personnalisée
    - choix catégorie (employé, etam, cadre) 
    - CCN a été traitée par nous  -> éléments CCN :
        - afficher valeur dans la CCN et expliquer que le CDT s'applique (ou non) et la règle

Période   d'essai - Durée initiale | CDT ( Code du travail)  |Règles de priorité   | Boulangerie pâtisserie artisanale   |/ |/   |Industries chimiques   | HCR  | Bureau d'Etude Technique
-- | -- | -- | -- | -- | -- | -- | -- | --
ouvriers,   employés | 2 mois | si CCN < CDT, CDT. | 30 jours |   |   | * coef<160: 15 jours     *190>Coef>160: 1 mois     * coef>190: 2 mois | 1 mois | /
spécificifités   ETAM | 3 mois | si CCN < CDT, CDT. | 30 jours |   |   | * 275>coef: 2 mois     * coef>275: 3 mois | 2 mois | * 1 mois (200 à 355)     * 2 mois ( 400 à 500)
spécificités   cadre | 4 mois | si CCN < CDT, CDT. | 4 mois |   |   | * 3 mois | 3 mois | * 3 mois

- règle générale du CDT : L1221-19 L1221-21
 - contacts SDR ou Inspection selon le thème
 - contacts Syndicats / IRP selon le thème
 - contacts / cerfa prudhommes selon le thème
 - bloc feedback

**Comment by jrduscher** [comment]
test unitaire: indemnisation en cas de licenciement sans cause réelle et sérieuse.
Test:  indemnisation licenciement sans crs
test : indemnisation licenciement abusif

mêmes résultats: renvoi vers la fiche https://www.service-public.fr/particuliers/vosdroits/F33999.

Attendu:
fiche service public: la grille figure dans la fiche. ( voir ci dessus)
fiche ministère:  http://travail-emploi.gouv.fr/droit-du-travail/rupture-de-contrats/licenciement/article/le-licenciement-pour-motif-personnel-les-causes-possibles-les-sanctions#Qu-est-ce-qu-une-cause-reelle-et-serieuse
Outil: barémisation.

Annuaires: 
conseillers du salarié ( on peut imaginer se retrouver avant l'entretien de licenciement)
défenseur syndical
cerfa prudhommes:
 saisine prud'homal par le salarié , https://www.formulaires.modernisation.gouv.fr/gf/cerfa_15586.do
saisine prud'homal par employeur: https://www.formulaires.modernisation.gouv.fr/gf/cerfa_15587.do
cerfa aide juridictionnelle.: https://www.formulaires.modernisation.gouv.fr/gf/cerfa_15626.do
Article du code du travail: L1235-1 à L1235-6
bloc feedback

**Comment by jrduscher** [comment]
**Mon contrat de travail prend fin. Quels documents mon employeur doit me remettre ?**
= documents de fin de contrat, documents obligatoires
= rupture du contrat
= certificat de travail, solde de tout compte, attestation pole emploi

Suggestions :
I) Principe/cas général : 
1)	FAQ | Mon contrat de travail prend fin. Quels documents mon employeur doit me remettre ?
2)	Fiche Service- Public.fr |Quels sont les documents remis au salarié à la fin de son contrat ?
3)	Code BFC | "Rupture du contrat : Quels documents donner au salarié à l'issue du contrat ?",
II) Cas particuliers :
•	Licenciement économique ?
1)	Fiche Service public | Licenciement économique : préavis de licenciement et fin du contrat de travail

•	Démission ? 
1)	Démission d'une assistante maternelle
2)	Démission du salarié à domicile employé par un particulier

•	Résiliation judiciaire ?
1)	Fiche Service public | Résiliation judiciaire du contrat de travail


•	Particulier employeur ?
1)	Fiche Ministère du travail | Les droits et obligations des salariés du particulier employeur : bénéficier d’un certain nombre de garanties en cas de rupture du contrat de travail

•	Intérim ?
1)	Fiche Service public | Contrat de travail temporaire (intérim)
Attestation pôle emploi : article R1234-11, article R1234-12




réponse du site actuellement.
•	Question | Mon contrat de travail prend fin. Quels documents mon employeur doit me remettre ?
•	// traite de la question (3ème point) de manière plus ciblée pour licenciement économique :
o	Fiche Service public | Licenciement économique : préavis de licenciement et fin du contrat de travail
Remise des documents de fin de contrat CDI L'employeur doit remettre au salarié les documents suivants : Certificat de travail Attestation Pôle emploi Solde de tout compte État récapitulatif de l'ensemble
•	Fiche Ministère du travail | Les droits et obligations des salariés du particulier employeur : bénéficier d’un certain nombre de garanties en cas de rupture du contrat de travail
Bien que ces dispositions stipulent que le contrat de travail prend fin du fait du décès de l’employeur, elles n’exonèrent toutefois pas les héritiers de l’obligation de notifier le licenciement (arrêt
•	Fiche Service public | Résiliation judiciaire du contrat de travail
L'employeur doit également remettre au salarié les documents de fin de contrat auxquels il a droit.
•	Fiche Service public | Contrat de travail temporaire (intérim)
L'employeur doit remettre au salarié les documents suivants : Certificat de travail Attestation Pôle emploi Solde de tout compte
Réponse complémentaire
Code du travail : //tag epos [200], « documents à remettre au salarié »
•	Certificat de travail : L1234-19, D1234-6
•	Reçu pour solde de tout compte : L.1234-20 ; D1234-7, D1234-8
•	Attestation d’assurance chômage : R1234-9, R1234-10
o	Intérim : Attestation d’assurance chômage : R1234-9, R1234-10
Annuaire :
(raisonnement : il s’agit d’un cas individuel, d’une personne qui a quitté l’entreprise)
•	Services de renseignement
•	défenseur syndical
Formulaires :
•	Cerfa prudhommes: saisine prud'homal par le salarié : https://www.formulaires.modernisation.gouv.fr/gf/cerfa_15586.do
•	Cerfa aide juridictionnelle.: https://www.formulaires.modernisation.gouv.fr/gf/cerfa_15626.do

**Comment by jrduscher** [comment]
https://github.com/SocialGouv/code-du-travail-explorer/issues/93

"question": "A quelle date mon salaire doit être versé ?"

"question": " Mon contrat de travail prend fin. Quels documents mon employeur doit me remettre ?"

"question": "Comment sont payées les heures supplémentaires ?"

"question": "Est-ce que mon employeur peut m’obliger à faire des heures supplémentaires ?"

"question": "Mon employeur m’a licencié verbalement, que faire ?"

"question": "Mon employeur ne me donne plus de travail, que faire ?"

"question": "Avec le rachat de mon entreprise mon employeur change. Ai-je l'obligation de travailler avec la nouvelle entreprise ?"
   "question": "A quel moment mon employeur doit-il me fournir mon solde tout compte ?"

**Comment by jrduscher** [comment]
"question": "A quelle date mon salaire doit être versé ?"

Question | A quelle date mon salaire doit être versé ?
A quelle date mon salaire doit être versé ?
La loi ne prévoit pas de date précise mais impose un versement une fois par mois.

Fiche Ministère du travail | Le versement du salaire : quand et comment est-il versé ?
• Le salaire doit être versé une fois par mois, à date fixe. • La rémunération des salariés est mensuelle et indépendante, pour un horaire de travail effectif déterminé, du nombre de jours travaillés dans
Fiche Service public | Paiement du salaire
L'employeur doit respecter la périodicité du versement (le plus souvent, par mensualisation). Le salaire doit être versé


La réponse apporté par notre service est *** satisfaisante***

suggestions:
** retard de salaire?** ( proposer une suggestion) https://codedutravail-dev.num.social.gouv.fr/fiche-service-public/paiement-du-salaire
**pour aller plus loin?**
**code du travail**

Annuaire
-sr
-it
-

Contenu complémentaire

**Comment by jrduscher** [comment]
**Mon contrat de travail prend fin. Quels documents mon employeur doit me remettre **?****
= documents de fin de contrat, documents obligatoires
= rupture du contrat
= certificat de travail, solde de tout compte, attestation pole emploi

**Suggestions :
I) Principe/cas général :**

FAQ | Mon contrat de travail prend fin. Quels documents mon employeur doit me remettre ?
Fiche Service- Public.fr |Quels sont les documents remis au salarié à la fin de son contrat ?
Code BFC | "Rupture du contrat : Quels documents donner au salarié à l'issue du contrat ?",
**II) Cas particuliers :**
•	Licenciement économique ?
Fiche Service public | Licenciement économique : préavis de licenciement et fin du contrat de travail
•	Démission ?

Démission d'une assistante maternelle
Démission du salarié à domicile employé par un particulier
•	Résiliation judiciaire ?

Fiche Service public | Résiliation judiciaire du contrat de travail
•	Particulier employeur ?

Fiche Ministère du travail | Les droits et obligations des salariés du particulier employeur : bénéficier d’un certain nombre de garanties en cas de rupture du contrat de travail
•	Intérim ?

Fiche Service public | Contrat de travail temporaire (intérim)
Attestation pôle emploi : article R1234-11, article R1234-12
réponse du site actuellement.
•	Question | Mon contrat de travail prend fin. Quels documents mon employeur doit me remettre ?
•	// traite de la question (3ème point) de manière plus ciblée pour licenciement économique :
o	Fiche Service public | Licenciement économique : préavis de licenciement et fin du contrat de travail
Remise des documents de fin de contrat CDI L'employeur doit remettre au salarié les documents suivants : Certificat de travail Attestation Pôle emploi Solde de tout compte État récapitulatif de l'ensemble
•	Fiche Ministère du travail | Les droits et obligations des salariés du particulier employeur : bénéficier d’un certain nombre de garanties en cas de rupture du contrat de travail
Bien que ces dispositions stipulent que le contrat de travail prend fin du fait du décès de l’employeur, elles n’exonèrent toutefois pas les héritiers de l’obligation de notifier le licenciement (arrêt
•	Fiche Service public | Résiliation judiciaire du contrat de travail
L'employeur doit également remettre au salarié les documents de fin de contrat auxquels il a droit.
•	Fiche Service public | Contrat de travail temporaire (intérim)
L'employeur doit remettre au salarié les documents suivants : Certificat de travail Attestation Pôle emploi Solde de tout compte

**Réponse complémentaire**
**Code du travail** : //tag epos [200], « documents à remettre au salarié »
•	Certificat de travail : L1234-19, D1234-6
•	Reçu pour solde de tout compte : L.1234-20 ; D1234-7, D1234-8
•	Attestation d’assurance chômage : R1234-9, R1234-10
o	Intérim : Attestation d’assurance chômage : R1234-9, R1234-10
**Annuaire :**
(raisonnement : il s’agit d’un cas individuel, d’une personne qui a quitté l’entreprise)
•	Services de renseignement
•	défenseur syndical
**Formulaires :**
•	Cerfa prudhommes: saisine prud'homal par le salarié : https://www.formulaires.modernisation.gouv.fr/gf/cerfa_15586.do
•	Cerfa aide juridictionnelle.: https://www.formulaires.modernisation.gouv.fr/gf/cerfa_15626.do

**Comment by jrduscher** [comment]
indemnisation en cas de licenciement sans cause réelle et sérieuse.
Test: indemnisation licenciement sans crs
test : indemnisation licenciement abusif

mêmes résultats: renvoi vers la fiche https://www.service-public.fr/particuliers/vosdroits/F33999.

Attendu:
fiche service public: la grille figure dans la fiche. ( voir ci dessus)
fiche ministère: http://travail-emploi.gouv.fr/droit-du-travail/rupture-de-contrats/licenciement/article/le-licenciement-pour-motif-personnel-les-causes-possibles-les-sanctions#Qu-est-ce-qu-une-cause-reelle-et-serieuse
Outil: barémisation.

Annuaires:
conseillers du salarié ( on peut imaginer se retrouver avant l'entretien de licenciement)
défenseur syndical
cerfa prudhommes:
saisine prud'homal par le salarié , https://www.formulaires.modernisation.gouv.fr/gf/cerfa_15586.do
saisine prud'homal par employeur: https://www.formulaires.modernisation.gouv.fr/gf/cerfa_15587.do
cerfa aide juridictionnelle.: https://www.formulaires.modernisation.gouv.fr/gf/cerfa_15626.do
Article du code du travail: L1235-1 à L1235-6
bloc feedback

**Comment by jrduscher** [comment]
"question": "Comment sont payées les heures supplémentaires ?"

Pour aller plus loin:
Fiche ministère: https://travail-emploi.gouv.fr/archives/archives-courantes/archives-des-articles-de-la-rubrique-droit-du-travail/article/les-heures-supplementaires-contreparties#



code du travail

Majoration des heures supplémentaires: 
ordre public: L3121-28, 
majorations en cas d'accord: L3121-33, 
Majorations prévues en cas d'absence d'accord: L3121-36, L3121-37,L3121-38

Sanctions : R3124-7




Formulaire:
cerfa prudhommes:
saisine prud'homal par le salarié , https://www.formulaires.modernisation.gouv.fr/gf/cerfa_15586.do
saisine prud'homal par employeur: https://www.formulaires.modernisation.gouv.fr/gf/cerfa_15587.do
cerfa aide juridictionnelle.: https://www.formulaires.modernisation.gouv.fr/gf/cerfa_15626.do


résultats pour "durée initiale"
réponse FAQ (aucune actuellement)
fiche MIN.T : cas général durée periode d'essai
fiche SP : cas général periode d'essai
disclaimer hierarchie des normes " bloc 3" 
Réponse personnalisée
choix catégorie (temps partiel, temps complet)
si temps partiel: suggérer: " contrepartie et heures complémentares
si temps plein: suggérer réponses "Comment sont payées les heures supplémentaires ?""
CCN a été traitée par nous -> éléments CCN :
afficher réponse (si ETAM -> 3 mois)
afficher valeur dans la CCN et expliquer que le CDT s'applique (ou non) et la règle
lien vers CCN

Industrie Chimique:  sauf accord d'entreprise récent, en disposant autrement, la CCn des industrie chimique, prévoit que les contreparties peuvent être rémunérées au sens du code du travail ou être remplacées par un repos compensateur.

Boulangerie artisanale: sauf accord d'entreprise récent en disposant autrement, les majorations des heures supplémeantiares prvues et priaeqtiqeués dans les entrprisessont au mois égales  aux dispositions légales.

HCR: 

Métallurgie.

Annuaire:
En savoir plus
- SR
Agir en cas de non respect de ces dispositions
-IT
- défenseur des droits
- prud'hommes
bloc feedback

**Comment by jrduscher** [comment]
"question": "Est-ce que mon employeur peut m’obliger à faire des heures supplémentaires ?"

suggestions
Heures


résultats pour "durée initiale"
réponse FAQ (aucune actuellement)
fiche MIN.T : cas général durée periode d'essai
fiche SP : cas général periode d'essai
disclaimer hierarchie des normes CDT + CCN + AE - L2253-3 (sauf renouvellement -> L2253-1)
Réponse personnalisée
durée du travail: temps plein, temps partiel
si temps partiel " Votre employeur ne peut pas vous contraindre à faire des heures supplémentaires: les heures supplémentaires sont les heures effectuées au delà de la durée légale du travail. A temps partiel, la question n'est pas censé se poser." suggérer " heures complémentaires"
choix catégorie (employé, etam, cadre)
CCN a été traitée par nous -> éléments CCN :
afficher réponse (si ETAM -> 3 mois)
afficher valeur dans la CCN et expliquer que le CDT s'applique (ou non) et la règle
lien vers CCN
règle générale du CDT : L1221-19 L1221-21
contacts SDR ou Inspection
contacts Syndicats / IRP selon le thème
contacts / cerfa prudhommes selon le thème
bloc feedback

**Comment by jrduscher** [comment]
"question": "Mon employeur ne me donne plus de travail, que faire ?"

// explication: le contrat de travail est un contrat bien particulier( déséquilibré du fait du lien de subordination), mais reste par nature un contrat. La réponse à cette question trouve son issue dans les textes propres à la relation contractuelle de droit commun. Chaque partie s'engage à respecter sa part du contrat, pour l'employeur il s'agit du paiement du salaire, du travail et des moyens permettant de travailler. L'employeur a l'obligation de fournir du travail. A côté de cela, le fait de ne pas donner du travail à son salarié, peut aussi relever d"une stratégie intentionnelle  visant à décourager le salarié et l'inciter à démissionner (langage courant:  la mise au placard). Deux aspects à traiter: les conséquences du non respect d'une obligation contractuelle, les conséquences en terme de RPS.

_Réponse:_ FAQ "mon employeur ne me donne plus de travail que faire" // réponse activité partielle, mais élément de réponse sur l'obligation de rémunération.https://codedutravail-dev.num.social.gouv.fr/question/mon-employeur-ne-me-donne-plus-de-travail-que-faire
FAQ( complète bien la première réponse)
https://codedutravail-dev.num.social.gouv.fr/fiche-ministere-travail/contrat-de-travail-quelles-obligations-decoulent-du-contrat-de-travail

filtres:
type de contrat peut être utile ( des contenus spécifiques existent dans la base sur le contrat de professionnalisation). 
Si rien, afficher les réponses sans filtre. ( pertinent ici)


Suggestion:
- la baisse d'activité est collective,  et conjoncturelle? (activité partielle)
- la baisse d'activité est collective structurelle?
- la baisse d'activité a des conséquences sur la rémunération?
- je ne suis plus payé depuis plus de 30 jours
- je travaille en boulangerie et mon patron m'a dit que je pouvais rentrer aujourd'hui, parce qu"il nyavait pas de travail aujourd'hui pour moi
- la baisse d'activité s'accompagne de la privation des moyens de production?
- je suis seul à subir une baisse de charge de travail ?
- mon travail ne correspond pas à ce que prévoit mon contrat de travail?
- mon travail se résume à des taches subalternes et j'ai moins de responsabilités que ce qui est prévu dans mon contrat de travail ou ma qualification
- mon travail au quotidien comporte en réalité  une part de responsabilité plus importante que celle prévue dans mon contrat et ma convention collective pour mon coefficient?
- non respect du contrat de travail


en savoir plus: 
Code du travail
- contrat de travail : [3400] L1221-1 " le contrat de travail est soumis aux règles de droit commun" ( càd règles du contrat dans le code civil)

 - activité partielle ( FAQ) : [55100]

R5122-2; R5122-4;   R5122-5; R5122-1; R5122-3; R5122-6; R5122-7; R5122-8; R5122-9; R5122-10;   R5122-11; R5122-12; D5122-13; R5122-14; R5122-16; R5122-17; R5122-18;   R5122-19; D5221-2-1; L5122-1; L5122-2; L5122-4; L5122-5; R5122-20; R5122-21;   R5122-22; R5122-23; R5122-24; R5122-25; R5122-26
--

Code civil
- caducité du contrat : 1186
-nullité: 1178 à 1185 
- validité 1128, 1163



Annuaire: 
- SR/IT ( l’usager a besoin de conseils sur la stratégie et la méthode)
- IRP
- syndicats

- avocat
- MT

**Comment by jrduscher** [comment]
"question": "Avec le rachat de mon entreprise mon employeur change. Ai-je l'obligation de travailler avec la nouvelle entreprise ?"

code du travail : L1224-1. https://codedutravail-dev.num.social.gouv.fr/code-du-travail/article-l1224-1

Interlocuteurs: 
- représentants du personnel dans l'entreprise.
- services de renseignements,
- IT compétent ( + pertiennt que SR sur ce sujet en principe)

**Comment by jrduscher** [comment]
"question": "A quel moment mon employeur doit-il me fournir mon solde tout compte ?"

**Comment by jrduscher** [comment]
"question": "A quel moment mon employeur doit-il me fournir mon solde tout compte ?"
profil " salarié"

type de contrat tous
Tag [200]
CCN: rare...

suggestions: 
documents de fin de contrat:
 https://codedutravail.num.social.gouv.fr/questions/jBCs02UBVGj4b-Nr5qYi
https://www.service-public.fr/particuliers/vosdroits/F31896
https://travail-emploi.gouv.fr/droit-du-travail/la-rupture-du-contrat-de-travail/article/les-documents-remis-aux-salaries-lors-de-la-rupture-du-contrat-de-travail#Et-l-attestation-pour-Pole-Emploi

Code du travail : Article L1234-20, Article D1234-8, Article D1234-7


**Annuaires:**
- SR
- conseillers du salarié 
- défenseurs syndicaux

**Formulaires:**

cerfa prudhommes:
saisine prud'homal par le salarié , https://www.formulaires.modernisation.gouv.fr/gf/cerfa_15586.do
saisine prud'homal par employeur: https://www.formulaires.modernisation.gouv.fr/gf/cerfa_15587.do
cerfa aide juridictionnelle.: https://www.formulaires.modernisation.gouv.fr/gf/cerfa_15626.do

**Comment by jrduscher** [comment]
"question": "Mon employeur m’a licencié verbalement, que faire ?"

type de contrat ( Important)
si CDD : 
suggestion : rupture abusive du CDD ?

si CTT: 

si CDI: 
"L'employeur doit respecter la procédure de licenciement, sous peine de sanctions, qui varient en fonction du motif et selon que le salarié est protégé ou non."
FAQ : https://codedutravail-dev.num.social.gouv.fr/question/mon-employeur-ma-licencie-verbalement-que-faire

suggestion:

Formulaires:
cerfa prudhommes:
saisine prud'homal par le salarié , https://www.formulaires.modernisation.gouv.fr/gf/cerfa_15586.do
saisine prud'homal par employeur: https://www.formulaires.modernisation.gouv.fr/gf/cerfa_15587.do
cerfa aide juridictionnelle.: https://www.formulaires.modernisation.gouv.fr/gf/cerfa_15626.do

Interlocuteurs:
 - vos DP
- IT/SR
- défensurs syndicaux.

**Comment by jrduscher** [comment]
4 questions types sur 4 CCN :
- renouvellement de période d'essai 
- indemnités de licenciement
- préavis de démission
- rupture conventionnelle

Quels types de réponses afficher ?
- les réponses rédigées ;
- les liens utiles ;
- les outils ;

Prévoir le cas où la CCN n'est pas traité => Orienter vers le bloc de la hiérarchie des normes.

Soit (4 x 4) + 1 = 17 tests unitaires

**Comment by jrduscher** [comment]
"Renouvellement période d'essai: boulangerie"

réponse: FAQ https://codedutravail-dev.num.social.gouv.fr/?q=renouvellement%20p%C3%A9riode%20d%27essai%20boulangerie

(ça tombe juste et en une seule réponse: !!)

> si on part avec en tête le CDD, le CDTN nous envoie dans le mur.
> si CDI. on a la réponse;

Cde du travail: L1221-19...

**Comment by jrduscher** [comment]
**Renouvellement période d'essai HCR, renouvellement période d'essai hôtel, café, restaurant:**
 réponse: aucun résultat
réponse attendue:
ouvriers,   employés | | oui, sauf ech1,N1
etam |  | oui
cadres |  oui, sauf cadre supérieur


FAQ à créer

**Renouvellement période d'essai syntec/ bureau d'étude technique**
aucun résultat
résultat attendu:

ouvriers,   employés |  non
etam |  | oui ( une fois)
cadres |  oui ( une fois)

**Comment by HelaG** [comment]
query = indemnités de licenciement soumises à charge sociale

Résultat attendu = 
https://www.service-public.fr/particuliers/vosdroits/F987
section "Exonération de cotisations sociales" 

(retour UD92)

**Comment by HelaG** [comment]
query = indemnités de licenciement imposable

Résultat attendu =
https://www.service-public.fr/particuliers/vosdroits/F987
section "Exonération impôt sur le revenu"

(retour UD92)

**Comment by HelaG** [comment]
query = quand doit être remis le solde tout compte

Résultat attendu

```json
  {
    "reponse": "<p>Le solde de tout compte est remis avec le bulletin de salaire suivant la rupture du contrat de travail. Le solde de tout compte est donc remis dans le mois ou au début du mois suivant selon les habitudes de l’entreprise.</p><p>Le solde de tout compte liste l’ensemble des sommes versés au salarié lors de la rupture du contrat de travail. Il est établi par l’employeur.</p><p>Le salarié signe un reçu de ce solde de tout compte, en double exemplaire. Il en conserve un exemplaire.</p><p>Le salarié peut contester ce document par lettre recommandée dans les six mois suivant la signature du reçu.</p>",
    "theme": " RUPTURE DU CONTRAT",
    "branche": null,
    "themes": [],
    "question": "A quel moment mon employeur doit-il me fournir mon solde tout compte ?"
}
```

(retour UD92)

**Comment by ClementChapalain** [comment]
Cette tâche est encore pertinente ou tout est stocké dans :
https://docs.google.com/spreadsheets/d/1o6hf-Tm3rb5qMXRBId3aGuSt9tNalvxMsOkrbkHSbB4/edit#gid=0 ?

**Comment by lionelB** [comment]
J'ai transféré la plupart des questions vers le spreadsheet (onglet `à valider` , mais il reste à compléter les résultats attendus ping @jrduscher

**Comment by revolunet** [comment]
outdated
