### ISSUE TITLE
Intégration des QR de la FAQ dans les résultats de navigation par thèmes

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#851]
La navigation par thèmes se base sur une classification d'environs 250 items. Cette classif et 
Chaque QR est taggé avec une (ou plusieurs) tags numéroté dits "eposeidon modifiés", qui permet l'association des QR avec une arbo thématique proche de la structure code du travail, et des articles du code du travail qui sont liés.

L'integration des QR est possible en associant l'ancien tag d'un QR à la classification à l'aide du fichier excel suivant:
https://docs.google.com/spreadsheets/d/1KI49qpe5DyuYyKBWWRc-knUoxBJJYCMRoXsrUPd0ufg/edit#gid=1870679476

**Comment by ClementChapalain** [comment]
outdated avec le nouveau système de gestion des thèmes dans le data filler
