### ISSUE TITLE
[Modèles de courrier]Format de modèles de courrier téléchargeable: passer en format libre

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#856]
Aujourd'hui le format utilisé pour les modèles de courrier  téléchargeables est le format propriétaire *.docx. 

**objectif:** Envisager la faisabilité de passer sous un format libre

- déterminer le meilleur format ( le plus compatible)
- reuploader le fichier avec la nouvelle extension
- vérifier et corriger les impacts de ce changement sur le code ( notamment sur la partie affichage des modèles)

**Comment by lionelB** [comment]
Je suis pas complètement sûr mais il me semble que le format docx est un format ouvert.
https://fr.wikipedia.org/wiki/Office_Open_XML

**Comment by ClementChapalain** [comment]
merci pour l'article :) après lecture ce que j'ai compris :
- open office xml (dont fait partie le format .docx) n'est pas ouvert au sens strict du terme mais dans les faits tout le monde l'utilise et microsoft donne le droit à tout le monde de l'utiliser et de le modifier
- open office xml est désormais une norme iso (ce qui a fait un peu débat en europe notamment, du fait du caractère pas totalement ouvert)
- il y a une rivalité avec le format .odt de la norme opendocument qui est également une norme iso et parait plus ouvert

Bon c'est pas hyper clair pour moi, mais le format .docx ne me parait pas être une gros problème en tout cas.

**Comment by ClementChapalain** [comment]
on garde docx :)
