### ISSUE TITLE
[Simulateur d’embauche] explications et intégration

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#857]
L’utilisateur n'a pas forcément conscience que l'outil est extérieur au CDTN.
En cas d’indisponibilité du widget, imaginer une solution de réorientation de l'user pour limiter l'expérience déceptive.

**1) Amélioration de l'affichage et transparence**
Le simulateur d'embauche n'appariait pas clairement comme l'oeuvre d'une autre start-up d'Etat tierse.

Aujourd'hui, l'information est en filigrane avec l'invitation à aller consulter mon-entreprise.fr
![image](https://user-images.githubusercontent.com/37538697/58314783-835d0a00-7e10-11e9-8c05-7cd6ceadfc33.png)

"Dirigeants de société, travailleurs indépendants, ou auto-entrepreneurs : calculez vos revenus à l'euro près avec les nouveaux simulateurs officiels sur mon-entreprise.fr" => Visiblement  ce wording est inhérent au widger et ne peut pas être rempacé
En revanche, les structures qui l'ont integrés sur leurs sites ont parfois fait le choix d'ajouter une ligne ou deux d'explications:

**Exemple de  wording de préambule sur les-aides.fr**: Grâce à l'outil "simulateur d'embauche" développé par le SGMAP (Secrétariat Général pour la Modernisation de l'Action Publique), calculez rapidement le coût de l'embauche pour votre entreprise, et l'estimation de la rémunération nette de votre futur salarié.

L'APEC a préféré le format note de bas de page avec asterisque: "*Développé par le SGMAP (secrétariat général pour la modernisation de l'action publique)

Ce simulateur propose une première estimation du coût d'embauche. Certaines situations particulières ne sont pas prises en compte."

**Proposition**: d'ajout en header ( sous le titre Simulateur d’embauche) " Le simulateur d'embauche est un outil développé par une start-up d'Etat (mon-entreprise.fr) portée par la DINSIC" 

**2) Prévoir un n comportement en terme de parcours utilisateur en cas d'indisponibilité du widget.**

**Optimal:**
Détecter indisponibilité du widget, ne pas proposer le widget s'il est indisponible.
 
**proposition minimaliste:**
 afficher message "Le simulateur d'embauche ( mon-entreprise.fr) n'est pas disponible. v"+ retour page d'accueil. 

Autre solution? @ClementChapalain @revolunet @lionelB @UnbearableBear @adipasquale

**Comment by ClementChapalain** [comment]
2/ done

**Comment by lionelB** [comment]
l'ideal serait de le traiter comme un outils externes et de ne plus gérer une intégration spécifique chez nous.
