### ISSUE TITLE
[Bug+enhancement] modal Trouver sa convention collective SIRET/IDCC

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#858]
@ClementChapalain @adipasquale (remontée de bug peut-être déjà hors sujet/obsolète)
Le lien de la CCN avec la nouvelle interface se fait avec brio dans la partie  " Recherche par nom ou par identifiant". 

Les liens vers la CCN sont aujourd'hui via le champ SIRET/IDCC  sont morts. Actualiser/harmoniser les liens pour les faire pointer vers la nouvelle interface de lecture des CCN.

**Comment by adipasquale** [comment]
bien vu @jrduscher je corrige tout de suite
