### ISSUE TITLE
Disclaimer fonction publique

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#87]
Si la question a un rapport avec la fonction publique, afficher un disclaimer + les résultats SP

**Comment by jrduscher** [comment]
* L'utilisateur doit choisir secteur privé ou secteur public.
* L’utilisateur "secteur privé" doit se voir proposer uniquement des résultats secteurs privé.
* L’utilisateur "secteur public" est invité à poser sa question, il est également informé que le site n'a pas vocation première à traiter du secteur public.

=> Kemar avait mis en place un système de filtres des termes fonction public dans ES, la liste est réutilisable ( et doit être complétée en passant).

**Comment by revolunet** [comment]
un wording à proposer pour le texte à afficher ?

**Comment by jrduscher** [comment]
Le code du travail numérique,  n'a pas vocation à traiter des problématiques des agents publics des trois fonctions publics. En effet, il ne dépendent pas du droit du travail, mais de textes spécifiques. (Les agents publics ne pourront se prévaloir des réponses trouvées sur le code du travail numérique).

En tant qu'agent public, quelques réponses sont malgré tout à votre disposition sur l'onglet :"secteur public".
