### ISSUE TITLE
le filtre par type "themes" provoque une 404

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#871]
exemple à cette url en cliquant sur un des thèmes proposés: 
https://codedutravail-dev.num.social.gouv.fr/recherche?q=Conflits%20au%20travail%20et%20contr%C3%B4le%20de%20la%20r%C3%A9glementation&source=themes

**Comment by ClementChapalain** [comment]
duplicate #859 ?

**Comment by lionelB** [comment]
@UnbearableBear  le lien que tu as donné me renvoie 4 résultats de themes
![image](https://user-images.githubusercontent.com/160320/58857559-e28b0c00-86a5-11e9-9273-f924aed0b02d.png)

**Comment by UnbearableBear** [comment]
Yes, je crois qu'il suffit de cliquer sur l'un d'entre eux (n'importe lequel) pour avoir l'erreur

**Comment by ClementChapalain** [comment]
duplicate #859
