### ISSUE TITLE
Créer un dashboard avec les données à suivre

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#873]
Données à intégrer :
- nombre de contenus référencés
- nombre de visites
- nombre de consultations de contenus
- taux de conversion (consultations / visites)
- taux de satisfaction (via module de feedback)

**Comment by revolunet** [comment]
On peut déjà faire une 1er page basique avec les données fournies manuellement et on automatisera par la suite ?

<img width="955" alt="Capture d’écran 2019-06-05 à 15 16 44" src="https://user-images.githubusercontent.com/124937/58959246-f6696780-87a4-11e9-9048-28757c08f06e.png">

**Comment by lionelB** [comment]
Visite ca pourrait etre bien de l'avoir par jour / semaine ou mois
