### ISSUE TITLE
Ajouter Boulangerie au calculateur IDL

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#876]
from #39

----

"branche", "boulangerie"
avenant n°67, en vigueur et étendu.

récupérer inaptitude {oui,non} (afficher " Votre licenciement fait il suite à une décision d'inaptitude?"), {oui,non}

si inaptitude =non: "indemnité légale de licenciement,w".
( on affiche le résultat indemnité légal de licenciement, "votre branche ne prévoit pas de calcul spécifique, en dehors de l’indemnité légale de licenciement")

si inaptitude = oui,
récupérer "age,ag" ( ou date de naissance ?)
si age,ag <55: "indemnité légale de licenciement,w".
( on affiche le résultat indemnité légal de licenciement, "votre branche ne prévoit pas de calcul spécifique, en dehors de l’indemnité légale de licenciement")
si age,ag >55: "Indemnité légale de licenciement, w"+ "Indemnité complémentaire,IC"
("vous avez droit dans votre branche à une indemnité complémentaire à l’indemnité de licenciement du fait de votre inaptitude)

" Indemnité complémentaire, IC," (//différence entre l’indemnité de départ à la retraite et l'indemnité de licenciement)
récupérer: travail à temps plein/temps partiel ( sans incidence sur le calcul, mais l'usager peut se poser la question) (// définir ce qui est le mieux entre poser la question et afficher le chiffre de l'IC ou afficher un disclaimer ou les deux mon capitaine?)

indemnité de départ à la retraite, IR,
récupérer "salaire brut mensuel, s" ( calcul au 1/12 ou au 1/3 comme pour l'indmenité légale de licenciement: récupérer la variable salarie brut mensuel, de l'indmenité légale de licenciement)
"salaire brut mensuel,s"
récupérer "ancienneté,a"

si a<10, IR=0
si a>10, a<15, IR=s
si a>15, a<20, IR=1,5s
si a>20 a<25, IR=2s
si a>25 a<30, IR=2,5s
si a>30 a<35, IR=3s
si a>35 a<40, IR=3,5s
si a >40 IR=4s

IC=IR-w

**Comment by ClementChapalain** [comment]
on close car pour cette branche l'IDL conventionnelle est forcément < à l'IDL légale cf. #886

**Comment by jrduscher** [comment]
REOPEN: après relecture de la spec. totalement intégrable, la spec intègre déjà le fait que l'IDL est plus favorable, par contre la Valeur ajoutée réside dans le calcul de l’indemnité spécifique de licenciement ** en cas d'inaptitude**.

**Comment by ClementChapalain** [comment]
tu peux préciser stp ? on doit faire quoi en cas d'inaptitude ?
