### ISSUE TITLE
Ajouter Services de l'automobile au calculateur IDL

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#879]
from #39 

_** Moins favorable que l'indemnité légale**_

- -

branche: services de l'automobile IDCC 1090

Textes en présence: 
Article 2.13, modifié par avenant : indé ouvrirer et employés
article 4.11, modifié par avenant : maitrise et cadres
=> dans les deux cas coexistence d'un article VNE

article 4.11, en vigueur, étendu Indemnité de licenciement: maitrises et cadres
****
https://www.legifrance.gouv.fr/affichIDCCArticle.do?cidTexte=KALITEXT000005685156&idArticle=KALIARTI000005865239&categorieLien=cid

art. 2.13,  en vigueur, étendu Indemnité de licenciement: ouvriers et employés.
https://codedutravail.num.social.gouv.fr/kali/1090-convention-collective-nationale-du-commerce-et-de-la-reparation-de-l%27automo#KALISCTA000005755382
https://www.legifrance.gouv.fr/affichIDCCArticle.do;jsessionid=E17DBEEC30AB4B2690D6E3E54D36C779.tplgfr33s_1?cidTexte=KALITEXT000021237315&idArticle=KALIARTI000021237342&dateTexte=20091105

https://www.legifrance.gouv.fr/affichIDCCArticle.do;jsessionid=E17DBEEC30AB4B2690D6E3E54D36C779.tplgfr33s_1?cidTexte=KALITEXT000021237315&idArticle=KALIARTI000021237346&dateTexte=20091105
arrêté d'extension de l’avenant 55
https://www.legifrance.gouv.fr/affichTexte.do;jsessionid=E17DBEEC30AB4B2690D6E3E54D36C779.tplgfr33s_1?cidTexte=JORFTEXT000021990702&dateTexte=20091105&categorieLien=id#JORFTEXT000021990702

/!\ Ces mêmes textes coexistente avec des dipositions non étendues

SPECS: ouvriers
check faute grave ou lourde=non
récupérer inaptitude {oui,non} (afficher " Votre licenciement fait il suite à une décision d'inaptitude?"), {oui,non}
récupérer age : {années}

récupérer ancienneté,a
récupérer salaire de base mensuel, s ( même base de calcul que l'indemnité légale)
si a>10, récupérer oui, non ( "êtes vous mensualisé?", oui/non)

si age<60, si inaptitude=non.

indemnité de licenciement, z
si a>1 et si a <10: z=s/102 a
si a>10 z=s/152a + (a-10)* (s/15*2)

comparer z et l’indemnité légale, afficher les deux. afficher le montant le plus favorable et sa provenance. ( selon vos indications, et sauf stipulation d'un accord d'entreprise, l'indemnité de licenciement auquel vous avez droit correspond à l'indemnité {légale,conventionnelle} dont le montant est le suivant: "")
si inaptitude= non, si age>60
(afficher "vous avez droit à une indemnité complémentaire prévue dans la CCN")
si inaptitude= oui, si age =< 50
IR=z

si inaptitude = oui. si age >50
(afficher "vous avez droit à une indemnité complémentaire prévue dans la CCN")

**Comment by lionelB** [comment]
@jrduscher est ce que tu peux rajouter un commentaire sur la raison de de la fermeture d'une issue.
