### ISSUE TITLE
internet explorer version MAS Affichage tuiles

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#88]
non prioritaire.

les liens URL des PC en interne renvoient systématiquement vers une ouverture d'internet explorer dans une version 11.0.80. 
La page principale s'affiche, mais les premières requêtes renvoient vers l'erreur suivante:
"An unexpected error has occurred."

L'idée à mon sens serait de détecter la version de l'utilisateur, et de proposer à minima un disclaimer invitant l’utilisateur d'ouvrir la page dans un autre navigateur à jour. 
A moins qu'on puisse proposer mieux?

**Comment by revolunet** [comment]
Oui, on va faire en sorte que cela fonctionne aussi dans IE 😃

**Comment by revolunet** [comment]
Problème flex IE

![46290119-3b405d00-c58b-11e8-878c-9e6fe8880f54](https://user-images.githubusercontent.com/124937/46603041-33843980-caf2-11e8-8e88-e939dd46bdee.png)

**Comment by lionelB** [comment]
le pb de flex vient du support css-variable. Le polyfill fait mal sont boulot sur `--flex-gutter-size`
