### ISSUE TITLE
Ajouter HCR au calculateur IDL

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#880]
from #39 

----

branche HCR
art 32 CC, en vigueur, étendu. "https://www.legifrance.gouv.fr/affichIDCC.do;jsessionid=76445D7E289FB3CA5914033397B20C6F.tplgfr30s_2?idSectionTA=KALISCTA000005747401&cidTexte=KALITEXT000005670044&idConvention=KALICONT000005635534"

> > Article 32
> 
> Indemnisation de licenciement
(edit: MONTANT)

> Une indemnité distincte du préavis sera accordée, en dehors du cas de faute grave ou lourde, aux salariés licenciés ayant au moins deux ans d'«ancienneté » ininterrompue dans l'entreprise.
> 
> Cette indemnité sera calculée comme suit :
> -  moins de 10 ans d'«ancienneté » : 1/10e de mois de salaire mensuel brut par année d'«ancienneté »,
> -  au-delà de 10 ans d'«ancienneté » : 1/10e de mois par année d'«ancienneté» plus 1/15e de mois par année d'«ancienneté » au-delà de 10 ans, si le salarié peut bénéficier de la loi sur la mensualisation.
> 
(edit: BASE DE CALCUL)
> Le salaire à prendre en considération pour le calcul de l'indemnité est le 1/12e de la rémunération brute des douze derniers mois précédant le licenciement, ou selon la formule la plus avantageuse pour l'intéressé, le tiers des trois derniers mois, étant entendu que, dans ce dernier cas, toute prime ou gratification de caractère annuel ou exceptionnel qui aurait été versée au salarié pendant cette période ne sera prise en compte qu'au prorata temporis.
> 
> Cette indemnité de licenciement ne peut se cumuler avec aucune autre indemnité de même nature.
> 

récupérer ancienneté,a
récupérer salaire de base mensuel, s ( **même base de calcul que l'indemnité légale)**
si a>10, récupérer oui, non ( "êtes vous mensualisé?", oui/non)

indemnité de licenciement, z
si a>2 et si a <10: z=s/10* a
si a>10 z=s/10a + (a-10) (s/15)

comparer z et l’indemnité légale, afficher les deux. afficher le montant le plus favorable et sa provenance. ( selon vos indications, et sauf stipulation d'un accord d'entreprise, l'indemnité de licenciement auquel vous avez droit correspond à l'indemnité {légale,conventionnelle} dont le montant est le suivant: "")

calcul de l'ancienneté:

**Comment by jrduscher** [comment]
checked. pas de modalité de calcul spécifique de l'ancienneté dans la CCN, tu confirmes @virginielastisneres ?

**Comment by virginielastisneres** [comment]
Yes je confirme !
