### ISSUE TITLE
Ajouter Hospitalisation à but non lucratif au calculateur IDL

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#882]
from #39 

----

HOSPITALISATION A BUT NON LUCRATIF FEHAP
en vigueur ou pas? étendue ou pas???

"branche",""
assistant familial,af: (afficher êtes assistant(e) familial(e)?"{oui, non})
("afficher: médecin, pharmacien ou biologiste: en cas de faute médicale reconnue ou de faite administrative grave, l'indemnité de licenciement n'est pas due")
(afficher: attention, en cas de licenciement lié à la perturbation dans le fonctionnement de l' entreprise due à des absences, l’indemnité de licenciement due ne peut vous priver des indemnités complémentaire en cas de maladie")

récupérer faute grave ou lourde,
si faute grave ou lourde= non:
si af=0

IR=IRL

si af=1
// modalité de calcul
// to be continued

**Comment by lionelB** [comment]
@jrduscher un petit mot pour préciser le motif de la fermeture de l'issue est bien pour les gens qui ne participe pas à la discussion
