### ISSUE TITLE
Ajouter Propreté en entreprise au calculateur IDL (IDCC:3043)

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#883]
from #39 

----

## CCN

PROPRETE ENTREPRISES ET SERVICES ASSOCIES

IDCC: 3043

### ancienneté

on peut calculer l'ancienneté avec les infos remplies pour l'IDL légale (pas besoin de demander plus d'infos).

soit ancienneté = date de sortie - date d'entrée (sans prendre en compte les absences prolongées).

l'ancienneté est exprimée en années (décimal : 2 an et demi = 2.5 années)

### salaire

idem IDL légal

### calcul du montant

si moins de deux ans d'ancienneté, c'est l'IDL légale qui s'applique.

si plus de deux ans d'ancienneté :
```
1/10 * salaire référence * ancienneté <= 5
+ 1/6 * salaire référence * ancienneté > 5 et <= 10 
+ 1/5 * salaire référence * ancienneté > 10
```

## Source convention collective 

> **4.11.3 - Indemnité de licenciement**
> 
> Tout salarié licencié bénéficiera, sauf cas de faute grave ou lourde, d'une indemnité conventionnelle de licenciement égale à :
> 
> De 2 ans à 5 ans révolus d'ancienneté :
> 
> • 1/10ème de mois par année d'ancienneté ;
> 
> De 6 ans à 10 ans révolus d'ancienneté :
> •  1/10ème de mois par année d'ancienneté pour la fraction des 5 premières années ;
> •  1/6ème de mois par année d'ancienneté pour la fraction de 6 ans à 10 ans révolus ;
> 
> 
> À partir de 11 ans d'ancienneté :
> •  1/10ème de mois par année d'ancienneté pour la fraction des 5 premières années ;
> •  1/6ème de mois par année d'ancienneté pour la fraction de 6 ans à 10 ans révolus ;
> •  1/5ème de mois pour chaque année au-delà de 10 ans révolus.
> 
> 
> L'ancienneté du salarié, permettant le calcul de l'indemnité conventionnelle de licenciement selon les modalités présentées ci-dessus, s'apprécie dans les conditions définies par la présente convention.
> 
> Ces dispositions sont applicables sous réserve d'application plus favorable de l'indemnité légale de licenciement, ouverte au salarié justifiant d'une année d'ancienneté ininterrompue et calculée dans les conditions déterminées par la loi, c'est-à-dire :
> •  1/5ème de mois de salaire par année d'ancienneté,
> •  montant auquel il faut ajouter 2/15ème de mois de salaire par année d'ancienneté au-delà de 10 ans.
>
> 
> 
> Il est rappelé que l'ancienneté permettant l'attribution et le calcul de l'indemnité légale de licenciement s'apprécie selon les modalités définies par la loi.
> 
> La rémunération moyenne des 12 derniers mois de travail effectif ou selon la formule la plus avantageuse des 3 derniers mois sera prise en considération pour le calcul de cette indemnité (étant entendu que toute prime ou gratification de caractère annuel qui aurait été versée au salarié pendant cette période de 3 mois ne sera prise en compte que prorata temporis).
>
> Article 4.2 -
>
> 
> **Ancienneté**
> 
> Pour la détermination de l'ancienneté ouvrant droit aux avantages prévus par la présente convention, il sera tenu compte de la présence continue, c'est-à-dire du temps écoulé depuis la date d'entrée en fonction en vertu du contrat de travail en cours, sans que soient exclues les périodes pendant lesquelles le contrat a été suspendu.
> 
> Il sera également tenu compte de la durée des contrats antérieurs et cela quels qu'aient été la cause et l'auteur de la rupture, pourvu qu'ils aient été conclus avec le même employeur. Pour l'application des articles 4.7.6 , 4.9 , 4.11.2 , 4.11.3 et 5.1 , il sera tenu compte de l'ancienneté acquise au titre du contrat de travail en cours.
>

**Comment by jrduscher** [comment]
checked

**Comment by lionelB** [comment]
@jrduscher si checked veut dire que la formule est ok, tu peux aussi enlever le label `draft` et le remplacer par `pret-pour-dev`

**Comment by revolunet** [comment]
Question "UX" : Pour les CCNs qui ne nécessitent pas d'informations supplémentaires, on peut afficher le résultat directement dans le même écran une fois la CCN sélectionnée.

Faut-il prévoir quand même un écran supplémentaire de "recap" ? (comparaison IDL/CCN) ou affiche-t-on tout dans le même écran ?

**Comment by ClementChapalain** [comment]
côté fonctionnel, je me me dis que c'est plus simple si on a toujours le même fonctionnement, i.e. cliquer sur le bouton "suivant" et ensuite le résultat est affiché, c'est plus simple si on a besoin de changer aussi

**Comment by revolunet** [comment]
Même comportement souhaité pour #866 ?

- la personne sélectionne sa ccn
- on affiche un onglet supp et on active le btn suivant
- il doit cliquer sur suivant pour avoir le résultat ?

**Comment by ClementChapalain** [comment]
oui c'est ok pour moi

**Comment by revolunet** [comment]
Quelqu'un pourrait svp faire une passe sur le wording/présentation de l'écran final où on affiche l'indemnité conventionnelle et expliquons l'articulation avec la légale .

je ne comprends pas la phrase "Le montant de l’indemnité est XXX € sur la base du calcul de l’indemnité légale"

<img width="634" alt="Capture d’écran 2019-06-14 à 17 26 44" src="https://user-images.githubusercontent.com/124937/59520246-d08d4280-8ec9-11e9-93b0-331eaa3ded19.png">

<img width="641" alt="Capture d’écran 2019-06-14 à 17 27 13" src="https://user-images.githubusercontent.com/124937/59520281-e0a52200-8ec9-11e9-9155-8b1cef41c3cd.png">
