### ISSUE TITLE
Ajouter toutes les branches pour lesquelles l'indemnité conventionnelle est calquée sur l'IDL

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#886]
Données de janvier 2019

CCNs pour lesquelles, tout motif confondu, et toute catégorie il n'est pas nécessaire de renvoyer au calcul de l’indemnité conventionnelle de licenciement (d'emblée l'Indemnité légale est plus favorable)

IDCC | Titre abrégé
-- | -- 
1518 | Animation 
843 | Boulangerie-pâtisserie   artisanale
1351 | Prévention   et sécurité 
1534 | Viandes   industries commerces en gros 
992 | Boucherie   boucherie-charcuterie triperie
2344 | Sidérurgie 

Pour ces conventions indiquez à l'utilisateur sans lui demander plus d'informations que l'IDC légale est l'IDC qui s'applique

**Comment by jrduscher** [comment]
peuvent être ajoutées également :

IDCC | Titre abrégé
-- | -- 
29 | Etablissements privés d'hospitalisation ( FEHAP)
1596 | ouvriers du bâtiment (entreprises jusqu'à 10 salariés)
1597 | ouvriers du bâtiment (entreprises de plus 10 salariés)

**Comment by jrduscher** [comment]
[liste_ccnlegal.xlsx](https://github.com/SocialGouv/code-du-travail-numerique/files/3418398/liste_ccnlegal.xlsx)
Justificatif de procédé

**Comment by jrduscher** [comment]
ADD IDCC n°1090

**Comment by revolunet** [comment]
il reste es choses à faire @jrduscher  ?
