### ISSUE TITLE
Ajouter bureau d'étude technique (syntec), IDCC 1486 au calculateur IDL

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#890]
## CCN
[Convention collective nationale des bureaux d'études techniques, des cabinets d'ingénieurs-conseils et des sociétés de conseils du 15 décembre 1987.
](https://codedutravail.num.social.gouv.fr/kali/1486-convention-collective-nationale-des-bureaux-d%27etudes-techniques-des-cabine)
IDCC: 1486

Opportunité de traitement: 
-  Le calcul de l'indemnité conventionnel apparaît moins favorable que l'indmenité légale pour les ETAM, et plus favorables pour les ingénieurs et cadres ( sauf au delà de 38 ans d'ancienneté)

(FRONT)Succession des questions à saisir à partir de la page convention collective:
catégorie: ETAM, Ingénieur Cadres, chargé d'enquête

## Calcul de l'indemnité
_Explication :Il s'agit de récupérer plusieurs facteurs utiles au calcul de l'indémnité (ancienneté, rémunération de référence) et procéder au calcul lui même._ 

### Ancienneté 

1. #### ancienneté du contrat de travail (si catégrorie = ETAM/Inénieur et cadres)

( comprend la période du contrat et les périodes des contrats précédents sauf démission ou faute grave)
l'ancienneté est exprimée en années (décimal : 2 an et demi = 2.5 années): pour obtenir des mois par années d'anciennetés dans le calcul)
"wording: ce qui est inclut et exclut de ancienneté
ancienneté en intégralité. ( date de début, date de fin( date d'envoi de la lettre de licenciement ) // renseignés dans la partie "indemnité légale"

> Périodes d'incapacité de trvaail
   wordingDurant la période saisie, avez vous eu des périodes d'incapacité de travail de plus de 6 mois?
dérouler accordéon: 
saisir les périodes ( date début, date de fin ou durée de la période). possibilité d'ajouter des périodes
(si date d'entrée et date de fin >0, prévoir test, date de fin -date de début > 6 mois. si false, ne pas prendre en compte le résultat dans les période à déduire)

2. #### Contrat successifs: (si ETAM et Ingénieurs et cadres
Après avoir déterminé l’ancienneté du contrat de travail concerné par cette rupture ( le point 1.)

L'ancienneté acquise dans un ou plusieurs contrat précédents s'ajoute à l'ancienneté.
comment procéder?

- wording "En cas d'engagements successifs, il est tenu compte de l'ancienneté accumulée au cours des contrats précédents"
- avez vous eu des contrats de travail successifs 
- demander: "Ajouter un contrat précédent". 
- type de  rupture: 
         -  licenciement
                       (redemander faute grave oui/non pour chaque contrat).
                            +si faute grave (non)
                                    Récupérer indemnité de licenciement ( utile pour le calcul du montant)
                                    Récupérer (date de sortie - date d'entrée ou période d'ancienneté.
                            +faute grave (oui): wording " en cas de licenciement pour faute grave, dans un contrat précédent, l'ancienneté ne peut pas être prise en compte.
       - démission: "la durée du contrat ne peut pas être prise en compte dans l'ancienneté en cas de démission". demander "
- prévoir la possibilité d'ajouter plusieurs contrats
- calculer l'ancienneté globale ( somme ancienneté contrat successif+ ancienneté du contrat de travail)
- restituer l'ancienneté.

#### Chargés d'enquête:  (si catégorie= chargé d'enquête), l’ancienneté se détermine comme suit)

1) saisir période de référence, une d'activité régulière et exclusive auprès de l'employeur
wording "saisir la période de référence: une période  d'activité régulière et exclusive.
 ancienneté= date de fin.  date de début;

2) Ajouter d'autres périodes:
 wording " ajouter les autres périodes de travail auprès de cet employeurs qui remplissent les conditions suivantes:
- Durée d'au moins 2 années à la suite, durant laquelle la rémunération est au moins éale au minimum annuel garanti

- années durant lesquelles, l'enquêteur perçoit au moins 11 bulletins de salaires sur 12, et au moins 3 fois la valeur du SMIC"

ajouter date de début, date de fin ou période en mois.

valider

faire la somme de l'ancienneté,

### salaire de référence ( base de calcul)

moyenne des salaires des 12 derniers mois.
/!\ La moyenne des 12 derniers mois peut être reprise des données de l'indemnité légale. ATTENTION: il n'est pas question de la moyenne des 3 derniers mois pour cette base de calcul.

> présenter une grille de remplissage des salaires des douze derniers mois. (la grille est identique pour les ETAM et les cadres:
> ajouter un énoncé d'avertissement:
" Saisir la rémunération mensuelle brute:
* en incluant:les primes prévues au contrat de travail, 
* en excluant les heures supplémentaires au delà de l'heure normale de l'entreprise
*en excluant: les majoration/indemnités liées à un déplacement ou un détachement;"
> faire la moyenne des 12 cases saisies
> Résultat " selon vos indications votre rémunération mensuelle brute de référence est de (moyenne(mois1,...,mois 12)"

### calcul du montant
( deux paramètres : l'ancienneté en deux tranches,et la catégorie)

> préalable: 
* si faute grave=non (voir information dans le formulaire d'indemnité légale)
* Indemnité conventionnelle à partir de 2 ans d'ancienneté. Si ancienneté<2 ans: indemnité légale due. (min 8 mois )

Années incomplètes proratisées au nombre de mois:

1. Catégorie: ETAM et  Ancienneté <20 ans :
     0,25*salaire de référence* ancienneté 

2. Catégorie: ETAM et  Ancienneté >20 ans: 
    0,30*salaire de référence* ancienneté . limite max (salaire de référence*10) 

3. Catégorie: Ingénieurs et cadres et  Ancienneté <20 ans: 
     1/3 *salaire de référence* ancienneté . Limite max: salaire de référence*12

4. Catégorie :Ingénieurs et cadres et  Ancienneté >20 ans:
     1/3 *salaire de référence* ancienneté . Limite max: salaire de référence*12

5. Catégorie: Chargé d'enquête intermittent et Ancienneté <20 ans:   
     1/5 *salaire de référence* ancienneté . Limite max: salaire de référence*7

6. Catégorie: Chargé d'enquête intermittent et Ancienneté- Ancienneté <20 ans 
     1/5 *salaire de référence* ancienneté . Limite max: salaire de référence*7

7.Contrats successifs: Déduire du résultat, les montants perçus précédemment au titre l'indemnité légale de licenciement  (dans la partie contrat successifs)

#### 

### cas particuliers prévues dans la convention collective

* licenciement pour refus de mobilité
* Réduction d'un tiers de l'IL si le salarié a accepté un emploi dans une autre entreprise.
  

## Textes de référence
Indemnité de licenciement: [article 19](https://codedutravail.num.social.gouv.fr/kali/1486-convention-collective-nationale-des-bureaux-d%27etudes-techniques-des-cabine#KALIARTI000005851447) 

ancienneté: [Article 12] (https://codedutravail.num.social.gouv.fr/kali/1486-convention-collective-nationale-des-bureaux-d%27etudes-techniques-des-cabine#KALIARTI000005851428)

**Comment by revolunet** [comment]
A propos des "contrats successifs" : 
 - S'agit-il uniquement de contrats également soumis à SYNTEC ?
 - Qu'entend-on par successif ? faut-il que les contrats se suivent exactement sans mission ou chômage intermédiaire ?

**Comment by jrduscher** [comment]
**Ancienneté du chargé d'enquête.**

1. Définition de l'ancienneté du chargé d'enquête

saisir période  une d'activité régulière et exclusive auprès de l'employeur en tant que CE
wording "saisir la période de référence: une période d'activité régulière et exclusive.
ancienneté= date de fin. date de début;


2. Ajouter l'ancienneté en tant **qu'enquêteur** sous conditions.
**Période de référence**
   Wording, "si vous avez été enquêteur, cette ancienneté peut être également prise en compte sous conditions:
- Vous pouvez faire la preuve de votre aptitude à effectuer de manière satisfaisante tous types d'enquêtes dans toutes les catégories de la population
- vous avez perçus en tant qu'enquêteur, pendant deux ans, une rémunération au moins équivalente au minimum annuel garanti"
OUI/NON: ajouter deux ans.

**ajouter d'autres périodes en tant qu’enquêteurs:** :
wording "Ajouter les années en tant qu'enquêteur, durant lesquelles, l'enquêteur perçoit au moins 11 bulletins de salaires sur 12, et au moins 3 fois la valeur du SMIC: "champs de saisie récupérer la période globale

**Comment by UnbearableBear** [comment]
Je crois que je comprends rien à ce que je dois faire pour le CE en fait 😅
