### ISSUE TITLE
Enlever du CDTN la fiche SP n°F31263 ?

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#898]
@jrduscher es-tu ok pour que nous enlevions la fiche de SP n°F31263 qui traite de l'accompagnement au départ à la retraite (ADR) des travailleurs indépendants ? 

=> https://www.service-public.fr/professionnels-entreprises/vosdroits/F31263

à mon sens elle ne concerne pas le code du travail, elle s'adresse uniquement aux travailleurs indépendants qui sont en difficulté financière.

**Comment by jrduscher** [comment]
oui c'est clairement hors sujet
