### ISSUE TITLE
Ajouter les sanctions prévues par le CDT

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#90]
objectif: enrichir les données de réponse, et en particulier côté employeur avec les sanctions rpévues par le code du trvail selon le camo correzpondnat à la question posée.
-  lier les tags epos entre eux, pour faire ressortir une table de correspondance entre les articles du code et les sanctions qui peuvent s'y rapporter. 
- faire ressortir : proposer l'affichage de  la peine encouru en fonction de la disposition citée, SANS allourdir le contenu proposé qui sera déjà assez riche.

**Comment by jrduscher** [comment]
amendes admininistrative : champs

DGT Page 1 sur 7
Service de l’animation territoriale, de la politique du travail et de l’action de l’inspection du travail –
Département de l’appui au système d’inspection du travail - Bureau des outils méthodologiques et de la
légalité du cadre d’intervention du système d’inspection du travail – DASIT 1
Amendes administratives
Objet
Cette fiche a pour objet de présenter en un même document
l’ensemble des manquements pouvant désormais donner lieu à une
amende administrative sur rapport d’un agent de l’inspection du
travail.
Références juridiques
 Détachement : articles L. 1262-2-1, L. 1262-4-1, L. 1262-4-4, L. 1262-4-5, L. 1263-4,
L. 1263-4-1, L. 1263-7, L. 1264-1, L. 1264-2 et L. 1263-6 du code du travail, R. 1331-1 à
R. 1331-3 du code des transports
 Durée du travail : articles L. 3121-18, L. 3121-19, L. 3121-20 à 25, L. 3131-1 à 3, L. 3132-2,
L. 3171-2 et L. 8115-1 du code du travail
 SMIC et minimum conventionnel : articles L. 3231-1 à 11et L. 8115-1 du code du travail
 Jeunes : articles L. 4153-8 et 9, L. 4733-2 et 3 et L. 4753-2 du code du travail
 Repérage avant travaux de l’amiante : articles L. 4412-2 et L. 4754-1 du code du travail
 Installations sanitaires, hébergement, restauration : Chapitre VIII du titre II du livre II de la 4e
partie, chapitre IV du titre III du livre V de la 4e partie et article L. 8115-1 du code du travail
 Arrêt de travaux et d’activité : articles L. 4731-1, L. 4731-2 et L. 4752-1 du code du travail
 Demande de vérification, de mesure ou d’analyse : articles L. 4722-1 et L. 4752-2 du code du
travail
 Travail illégal : articles L. 8291-1 et L. 8291-2 du code du travail
 Stagiaires : articles L. 124-8, L. 124-9, L. 124-14 et L. 124-17 du code de l’éducation
 Durées du travail et de conduite, et temps de repos dans le secteur des transports : articles
L. 1325-1, L. 3312-6, L. 4511-1, L. 2161-1, L. 2161-2, L. 1311-2, L. 1321-2, L. 1321-4 à 5 du
code des transports ; articles L. 8115-1, L. 3121-13 à L. 3121-15 et L. 3121-67 du code du
travail, articles 4, 6, 7, 8 et 9 du Règlement (CE) n° 561/2006 du 15 mars 2006 relatif à
l’harmonisation de certaines dispositions de la législation sociale dans le domaine des
transports par route
 Durée du travail dans l’agriculture : articles L. 719-10 1° à 3°, L. 713-13, L. 714-1, L. 713-20
du code rural et de la pêche maritime (CRPM) et L. 8115-1 du code du travail
 Conditions d’hébergement dans l’agriculture : articles L. 719-10, 4°, L. 716-1 du code rural
et de la pêche maritime (CRPM) et L. 8115-1du code du travail

 Ordonnance n° 2016-413 du 7 avril 2016 relative au contrôle de l’application du droit du
travail
 Loi n° 2016-1088 du 8 août 2016 relative au travail, à la modernisation du dialogue social et
à la sécurisation des parcours professionnels (articles 107 à 113)
 Ordonnance n° 2017-1718 du 20 décembre 2017 visant à compléter et mettre en cohérence
les dispositions prises en application de la loi n° 2017-1340 du 15 septembre 2017
d’habilitation à prendre par ordonnances les mesures pour le renforcement du dialogue social
(article 2)
Numéro
2016-03
Date création
08-04-2016
Classement
DASIT 1
Mise à jour
 15-02-2018
17-01-2018
DGT Page 2 sur 7
Service de l’animation territoriale, de la politique du travail et de l’action de l’inspection du travail –
Département de l’appui au système d’inspection du travail - Bureau des outils méthodologiques et de la
légalité du cadre d’intervention du système d’inspection du travail – DASIT 1
 Instruction DGT/RT1/2015/207 du 8 juin 2015 concernant les principales dispositions de la
loi du 10 juillet 2014 relative à la lutte concurrence sociale déloyale, ainsi que de son décret
d'application du 30 mars 2015
 Instruction n° 2017-02 du 23 janvier 2017 sur la mise en œuvre du décret n° 2015-1359 du
26 octobre 2015 relatif à l’encadrement du recours aux stagiaires par les organismes d’accueil
Résumé
Les trois tableaux ci-après listent les différents manquements prévus par le code du travail, le
code des transports (pour les manquements spécifiques au secteur des transports) ainsi que
par le code rural et de la pêche maritime (pour les manquements spécifiques au secteur
agricole) qui peuvent donner lieu à des amendes administratives1
, prononcées par le
DI(R)ECCTE. Ils indiquent pour chacun d’eux le montant de l’amende, la personne concernée
ainsi que la voie de recours prévue. Ils précisent les cas où une sanction pénale est également
prévue.
Cas des manquements qui font l’objet d’une amende administrative et d’une sanction
pénale :
Ces manquements (cf. lignées grisées du tableau ci-après) sont réprimés, selon le choix de
l’agent de contrôle de l’inspection du travail, par une sanction pénale ou une amende
administrative (article L. 8113-7 du code du travail).
Attention : les manquements relatifs à la durée du travail, la rémunération, l’hygiène,
l’hébergement et la restauration, ne peuvent faire l’objet d’une amende administrative que si le
parquet n’engage pas de poursuites pénales (article L. 8115-1). L’instruction DGT du 12 juillet
20162
 prévoit des modalités concrètes d’échanges d’informations entre les parquets et les
unités départementales afin de garantir l’absence de poursuites pénales.
1- Tableau récapitulatif des manquements pouvant donner lieu à une amende administrative
Les lignes grisées indiquent les manquements pour lesquels l’agent de contrôle peut choisir entre les
voies de sanction administrative ou pénale.
Les lignes en italique indiquent les textes dont l’application, à la date de la présente fiche, est
conditionnée à la parution d’un décret.
Manquement Texte
prévoyant
l’obligation
Texte de sanction
Montant de l’amende
Sanction pénale
Personne
concernée
Recours
possibles
Défaut de déclaration de
détachement
L. 1262-2-1(I) L. 1264-1
2000 € par salarié
détaché
4000 € si réitération
500.000 € maximum
Employeur qui
détache des salariés
(prestataire
étranger)
Gracieux et
Contentieux
Défaut de désignation
d’un représentant en
France (détachement)
L. 1262-2-1 (II) L. 1264-1
2000 € par salarié
détaché
4000 € si réitération
500.000 € maximum
Employeur qui
détache des salariés
(prestataire
étranger)
Gracieux
Contentieux
Défaut de déclaration
par une entreprise
étrangère utilisatrice
attestant de la
connaissance par l’ETT
étrangère du
détachement de ses
salariés (au 1er juillet
2017)
L. 1262-2-1(IV) L. 1264-2 (II)
2000 € par salarié
détaché
4000 € si réitération
500.000 € maximum
Enterprise
utilisatrice étrangère
Gracieux
Contentieux

1
Les articles cités sont issus du code du travail, sauf précision contraire (lorsque les manquements font l’objet d’une
amende administrative par application du code rural, du code des transports ou du code de l’éducation).
2
Instruction DGT n° 2016/03 du 12 juillet 2016 sur la mise en œuvre de l’ordonnance n°2016-413 du 7 avril 2016
relative au contrôle de l’application du droit du travail
DGT Page 3 sur 7
Service de l’animation territoriale, de la politique du travail et de l’action de l’inspection du travail –
Département de l’appui au système d’inspection du travail - Bureau des outils méthodologiques et de la
légalité du cadre d’intervention du système d’inspection du travail – DASIT 1
Manquement Texte
prévoyant
l’obligation
Texte de sanction
Montant de l’amende
Sanction pénale
Personne
concernée
Recours
possibles
Défaut de présentation
des documents utiles au
contrôle en langue
française
L. 1263-7 L. 1264-1
2000 € par salarié
détaché
4000 € si réitération
500.000 € maximum
Employeur qui
détache des salariés
(prestataire
étranger)
Gracieux et
Contentieux
Défaut de vérification de
déclaration de
détachement (si le
prestataire n’a pas luimême
réalisé la
déclaration de
détachement)
« Obligation de
vigilance »
L. 1262-4-1 (I) L. 1264-2 (I)
2000 € par salarié
détaché
4000 € si réitération
500.000 € maximum
Maître d’ouvrage ou
donneur d’ordre
Gracieux et
Contentieux
Défaut de vérification de
la désignation d’un
représentant de
l’entreprise en France (si
le prestataire n’a pas luimême
effectué cette
désignation)
« Obligation de
vigilance »
L. 1262-4-1(I) L. 1264-2 (I)
2000 € par salarié
détaché
4000 € si réitération
500.000 € maximum
Maître d’ouvrage ou
donneur d’ordre
Gracieux et
Contentieux
Défaut de déclaration de
détachement en cas de
défaut de transmission
de la déclaration de
détachement par le
prestataire étranger
L. 1262-4-1 (I)
D. 1263-13 et
14
L. 1264-2 (I)
2000 € par salarié
détaché
4000 € si réitération
500.000 € maximum
Maître d’ouvrage ou
donneur d’ordre
Gracieux et
Contentieux
Défaut de vérification de
déclaration de
détachement des soustraitants
de ses
cocontractants (au 1er
juillet 2017)
L. 1262-4-1 (II) L. 1264-2 (II)
2000 € par salarié
détaché
4000 € si réitération
500.000 € maximum
Maître d’ouvrage Gracieux et
Contentieux
Défaut de déclaration
d’un accident du travail
(au 1er juillet 2017)
L. 1262-4-4 1° L. 1264-1
2000 € par salarié
détaché
4000 € si réitération
500.000 € maximum
Employeur qui
détache des salariés
(prestataire
étranger)
Gracieux et
Contentieux
Défaut de déclaration
d’un accident du travail
(au 1er juillet 2017)
L. 1262-4-4 2° L. 1264-2 (I)
2000 € par salarié
détaché
4000 € si réitération
500.000 € maximum
Maître d’ouvrage ou
donneur d’ordre
Gracieux et
Contentieux
Défaut d’affichage
spécifique aux salariés
détachés sur le chantier
(au 1er juillet 2017)
L. 1262-4-5 L. 1264-2 (I)
2000 € par salarié
détaché
4000 € si réitération
500.000 € maximum
Maître d’ouvrage Gracieux et
Contentieux
Non-respect de la
décision de suspension
de la prestation de
service
L. 1263-4 et
L. 1263-4-1
R. 1263-11-1 à
7
L. 1263-6
10.000 € par salarié
concerné
Employeur qui
détache des salariés
(prestataire
étranger)
Gracieux et
Contentieux 
DGT Page 4 sur 7
Service de l’animation territoriale, de la politique du travail et de l’action de l’inspection du travail –
Département de l’appui au système d’inspection du travail - Bureau des outils méthodologiques et de la
légalité du cadre d’intervention du système d’inspection du travail – DASIT 1
Manquement Texte
prévoyant
l’obligation
Texte de sanction
Montant de l’amende
Sanction pénale
Personne
concernée
Recours
possibles
Manquement aux durées
maximales de travail,
repos et décompte
durée du travail
L. 3121-18 et
L. 3121-19
L. 3121-20 à
L. 3121-25
L. 3131-1 à 3
L. 3132-2
L. 3171-2
L. 8115-1, 1°, 2° et 3°
2000 € par travailleur
concerné
4000 € si réitération
Sanction pénale
prévue (R. 3124-3,
R. 3124-11,
R. 3135-1, R. 3135-2
et R. 3173-2)
Employeur Gracieux et
Contentieux
Non-respect SMIC ou
minimum conventionnel
L. 3231-1 à 11 L. 8115-1, 4°
2000 € par travailleur
concerné
4000 € si réitération
Sanction pénale
prévue (R. 3233-1 et
R. 2263-3)
Employeur Gracieux et
Contentieux
Emploi d’un travailleur
mineur à des travaux
interdits ou réglementés
sans respect des
conditions
L. 4153-8 et 9 L. 4753-2
2000 € par travailleur
concerné
Sanction pénale
prévue (L. 4741-1 1°)
Quiconque Gracieux et
Contentieux
Non-respect décision IT
de retrait d’un jeune
affecté à des travaux
interdits ou réglementés
(dans l’attente d’un
décret)
L. 4733-2 et 3 L. 4753-1
10.000 € par jeune
concerné
Sanction pénale
prévue (L. 4743-3)
Quiconque Gracieux et
Contentieux
Défaut de repérage
avant travaux de
l’amiante
(dans l’attente
d’arrêtés)
L. 4412-2 L. 4754-1
9.000 €
Sanction pénale
prévue (L. 4741-9)
Donneur d’ordre,
maître d’ouvrage,
propriétaire
Gracieux et
Contentieux
Non-respect règles
applicables aux
installations sanitaires,
hébergement et
restauration
Chapitre VIII du
titre II du livre
II de la 4e
partie
Chapitre IV du
titre III du livre
V de la 4e
partie (BTP)
L. 8115-1, 5°
2000 € par travailleur
concerné
4000 € si réitération
Sanction pénale
prévue (L. 4741-1 2°
et 5°)
Employeur Gracieux et
Contentieux
Non-respect arrêt de
travaux ou d’activité
L. 4731-1 et 2 L. 4752-1
10.000 € par
travailleur concerné
Sanction pénale
prévue (L. 4741-3-1)
Employeur Gracieux et
Contentieux
Non-respect demande de
vérification, de mesure
ou d’analyse
(dans l’attente d’un
décret)
L. 4722-1 L. 4752-2
10.000 €
Sanction pénale
prévue (L. 4741-1 6e)
Employeur Gracieux et
Contentieux 
DGT Page 5 sur 7
Service de l’animation territoriale, de la politique du travail et de l’action de l’inspection du travail –
Département de l’appui au système d’inspection du travail - Bureau des outils méthodologiques et de la
légalité du cadre d’intervention du système d’inspection du travail – DASIT 1
Manquement Texte
prévoyant
l’obligation
Texte de sanction
Montant de l’amende
Sanction pénale
Personne
concernée
Recours
possibles
Défaut de déclaration en
vue de la délivrance de
la carte d’identification
professionnelle dans le
BTP
L. 8291-1
D. 8291-1 et
suivants
L. 8291-2
2000 € par salarié
4000 € si récidive
500.000 € maximum
Employeur
Entreprise
utilisatrice
Gracieux et
Contentieux
Dépassement du
plafond autorisé de
stagiaires
L. 124-8 du
code éducation
L. 124-17
2000 € par stagiaire
concerné
4000 € si réitération
Organisme d’accueil Gracieux,
hiérarchique
et
contentieux
Défaut de désignation
d’un tuteur pour le
stagiaire
L. 124-9, 1e
phrase du 1er
alinéa, code
éducation
L. 124-17
2000 € par stagiaire
concerné
4000 € si réitération
Organisme d’accueil Gracieux,
hiérarchique
et
contentieux
Non-respect des durées
de présence du stagiaire
L. 124-14 du
code éducation
L. 124-17
2000 € par stagiaire
concerné
4000 € si réitération
Organisme d’accueil Gracieux,
hiérarchique
et
contentieux
2- Tableau récapitulatif des manquements spécifiques à certains secteurs des transports
pouvant donner lieu à une amende administrative
Les lignes grisées indiquent les manquements pour lesquels l’agent de contrôle peut choisir entre les
voies de sanction administrative ou pénale.
Manquement Texte
prévoyant
l’obligation
Texte de sanction
Montant de l’amende
Sanction pénale
Personne
concernée
Recours
possibles
Défaut d’attestation de
détachement (transport
routier et navigation
intérieure, pour les
personnels naviguant et
de conduite)
L. 1262-2-1(I)
du code du
travail
R. 1331-2 (I et
IV) du code des
transports
L. 1264-1 du code du
travail
2000 € par salarié
détaché
4000 € si réitération
500.000 € maximum
Employeur qui
détache des salariés
(prestataire
étranger)
Gracieux et
Contentieux
Défaut de désignation
d’un représentant en
France (détachement)
L. 1262-2-1 (II)
du code du
travail
R. 1331-1 (II)
du code des
transports
L. 1264-1 du code du
travail
2000 € par salarié
détaché
4000 € si réitération
500.000 € maximum
Employeur qui
détache des salariés
(prestataire
étranger)
Gracieux
Contentieux
Défaut de déclaration
par une entreprise
étrangère utilisatrice
attestant de la
connaissance par l’ETT
étrangère du
détachement de ses
salariés (au 1er juillet
2017)
L. 1262-2-1(IV)
du code du
travail
R. 1331-6 (III)
du code des
transports
L. 1264-2 (II) du code
du travail
2000 € par salarié
détaché
4000 € si réitération
500.000 € maximum
Enterprise
utilisatrice étrangère
Gracieux
Contentieux 
DGT Page 6 sur 7
Service de l’animation territoriale, de la politique du travail et de l’action de l’inspection du travail –
Département de l’appui au système d’inspection du travail - Bureau des outils méthodologiques et de la
légalité du cadre d’intervention du système d’inspection du travail – DASIT 1
Manquement Texte
prévoyant
l’obligation
Texte de sanction
Montant de l’amende
Sanction pénale
Personne
concernée
Recours
possibles
Défaut de vérification de
l’attestation de
détachement (si le
prestataire n’a pas luimême
réalisé
l’attestation de
détachement)
« Obligation de
vigilance »
L. 1262-4-1 (I)
du code du
travail
R. 1331-6 (I) du
code des
transports
L. 1264-2 (I) du code
du travail
2000 € par salarié
détaché
4000 € si réitération
500.000 € maximum
Donneur d’ordre Gracieux et
Contentieux
Défaut d’attestation de
détachement (transport
routier et navigation
intérieure pour les
personnels naviguant et
de conduite) en cas de
défaut de transmission
de la déclaration de
détachement par le
prestataire étranger

L. 1262-4-1 (I)
D. 1263-13 et
14
du code du
travail
R. 1331-6 (II)
du code des
transports
L. 1264-2 (I) du code
du travail
2000 € par salarié
détaché
4000 € si réitération
500.000 € maximum
Chef d’entreprise
dans laquelle le
salarié est détaché
Gracieux et
Contentieux
Manquement aux durées
des temps d’activité
dans le secteur des
transports
(à compter du 22
décembre 2017)
Tous les modes de
transports sont visés, à
l’exception des secteurs
maritime et aérien.
Code du
travail :
L. 3121-13 à
L. 3121-15
L. 3121-67
Code des
transports :
L. 3312-6
L. 4511-1
L. 2161-1
L. 2161-2
L. 1311-2
L. 1321-2
L. 1321-4
L. 1321-5
Règlement (CE)
n° 561/2006
du 15 mars
2006 relatif à
l’harmonisation
de certaines
dispositions de
la législation
sociale dans le
domaine des
transports par
route : articles
4, 6, 7, 8 et 9
L. 1325-1 du code des
transports qui renvoie
à l’article L. 8115-1
du code du travail
2000 € par travailleur
concerné
4000 € si réitération
Sanction pénale
prévue (R. 3315-4,
R. 3315-10, R. 3315-
11, R. 4512-1, 1°,
R. 4512-2, 1° du code
des transports)
Employeur Gracieux et
Contentieux 
DGT Page 7 sur 7
Service de l’animation territoriale, de la politique du travail et de l’action de l’inspection du travail –
Département de l’appui au système d’inspection du travail - Bureau des outils méthodologiques et de la
légalité du cadre d’intervention du système d’inspection du travail – DASIT 1
3- Tableau récapitulatif des manquements spécifiques au secteur agricole pouvant donner
lieu à une amende administrative
Les lignes grisées indiquent les manquements pour lesquels l’agent de contrôle peut choisir entre les
voies de sanction administrative ou pénale.
Manquement Texte
prévoyant
l’obligation
Texte de sanction
Montant de l’amende
Sanction pénale
Personne
concernée
Recours
possibles
Manquement aux durées
maximales de travail,
repos et décompte dans
l’agriculture
L. 713-13,
L. 714-1 et
L. 713-20 du
code rural et
de la pêche
maritime
(CRPM)
L. 719-10 1°, 2°, 3° du
CRPM qui renvoie à
l’article L. 8115-1 du
code du travail
2000 € par travailleur
concerné
4000 € si réitération
Sanction pénale
prévue (R. 719-3 et
R. 719-4 du CRPM)

Employeur Gracieux et
Contentieux
Manquement aux
conditions
d’hébergement dans
l’agriculture
L. 716-1 du
CRPM
L. 719-10 4° du CRPM
qui renvoie à l’article
L. 8115-1 du code du
travail
2000 € par travailleur
concerné
4000 € si réitération
Sanction pénale
prévue (R. 719-7 et
R.719-8 du CRPM)

Employeur Gracieux et
Contentieux

**Comment by jrduscher** [comment]
Amende administrative ( intranet sitere): tableau, champ concernés et indications amendes administratives.
http://sitere.travail.gouv.fr/systra/ComptenceEtMoyensIntervention/Pouvoirs%20et%20moyens/Ordonnance/Sanction%20administrative/Fiche%20DGT%202016%2003%20Amendes%20administratives_V4_150218.docx.pdf

**Comment by ClementChapalain** [comment]
Pourrait p-e faire l'objet d'un outil dédié : "quelles sont les sanctions prévues pour telle infraction ?"
