### ISSUE TITLE
[UI] Create form components

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#901]
This is quite a big one.
Currently, we use form components but we need them to be in the UI library for accessibility purposes. It will also allow us to remove the form.css file in the css folder

**Comment by UnbearableBear** [comment]
@nkrmr Tu peux te l'assigner elle si tu veux :)

**Comment by nkrmr** [comment]
Done

**Comment by ClementChapalain** [comment]
done du coup :)

👏 👏 niko !
