### ISSUE TITLE
CDTN version dév postée par revolunet le 19/09

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#91]
_"Livraison d’une instance de dev : https://codedutravail-dev.num.social.gouv.fr

- ajout d’urls fixes pour les faq+fiches
- contenu directement intégré sur faq+fiches
- intégration des thèmes de Jeremie sur “rupture de contrat” (la navigation est là mais pas (encore) le contenu)
- intégration pour tests d’un champ de suggestions sur les FAQ+fiches

Les pages de résultats (Faq, fiche) sont encore basiques mais ca va s’améliorer les les articles du code seront intégrés bientôt.
Le contenu des thèmes : je vois rapidement avec JR comment remplir ces pages
On se cale avec Jeremie semaine prochaine pour améliorer le rendu

Une fois que cette version vous convient (après prise en compte de vos retours), JR donne le signal pour l’envoyer en “prod” sur l’adresse officielle"_

**Comment by jrduscher** [comment]
feedback JR: 
- thèmes et sous thèmes:  Je crois que cela pourra parler à nos utilisateurs. la navigation est fluide. Problème constaté, on est pas exhaustif, on ne gagnerait pas en lisibilité à l'être, mais il faut une porte de sortie pour l'utilisateur. dans les exemples données on a  pas la prise d'acte de rupture pour l'instant par exemple. 
- suggestions à la saisie: je valide carrément, ca a l'air de bien marcher // cela fonctionnerait comment quand va rebrancher le code BFC, et ajouter le code du travail?
- contenu integré: cela fonctionne. problèmes constatés: mise en page des contenus integrés. (fiches sp et mintrav).
- contenu saucissonné et intégré des fiches min trav: pour être complet on devra prévoir de rajouter l'url vers la fiche complète "pour aller plus loin" cette fois dans un nouvel onglet.
- l’ensemble contribue à ce qu'"on n’ait plus qu'une seule page réponse !!! c'est top!!

C'est beau tout ça en tout cas!!

la suite à imaginer pour le prochain sprint: test de facetting?

**Comment by revolunet** [comment]
Je réponds dans la foulée : merci :)

 - thèmes / sous-thèmes : on peut remplir le thème rupture pour voir ce que cela donne. dans chaque "question" on pourra ajouter des suggestions vers autres sujets connexes.

 - suggestions : on peut intégrer le contenu que l'on souhaite; j'ai limité à FAQ+fiches pour l'instant

 - contenu intégré : oui travail de mise en forme à prévoir; il faudra peut-être aussi que ce contenu puisse s'ouvrir directement, et pas dans une page séparée ? -> #92

Oui des qu'on a un peu d'attributs on pourra tester le facetting

**Comment by Loze-Faelens** [comment]
Bonjour

-La version a du changer depuis car je lorsque je saisis une question la recherche ne se lance pas. Du coup je n'ai pas accès au FAQ etc ...
-Sur la navigation par thème, pouvez-vous m'expliquer pourquoi les "boites n'ont pas toutes la m^me taille" ? On dirait que la boite du dessous comme elle est plus grosse ne contient pas le m^me type d'information 

Cordialement

**Comment by revolunet** [comment]
Hello Catherine, oui il y a un bug sur la version de dev :/ fix imminent...

Pour la taille des blocs actuellement ils s'adaptent à la taille disponible mais je vais les fixer pour qu'ils aient tous la meme taille

**Comment by Loze-Faelens** [comment]
On a perdu les "pour aller plus loin" sous la Fiche de réponse affichée

**Comment by Loze-Faelens** [comment]
Remarque générale: si le contenu est grand, le pouce levé ou baissé et en haut de page et on ne les voit plus forcément si on a "scrollé"... mettre les pouces en bas de contenu ?

**Comment by revolunet** [comment]
ok on pourra essayer de les bloquer quand ca scroll, j'ai fait une issue : https://github.com/SocialGouv/code-du-travail-explorer/issues/101

pb "pour aller plus loin" corrigé

**Comment by Loze-Faelens** [comment]
Ne marche pas sur IE (celui de prod nom plus ne marche plus visiblement)

**Comment by Loze-Faelens** [comment]
* Si je pose une question, même si je choisis un contenu proposé je veux pouvoir lire ma question initiale  (ex  : "rôle du CHSCT" je prends le premier contenu proposé .... et j'arrive sur le contenu mais je n'ai plus l'enoncé de ma question initiale !

* le contenu proposé :"Élections professionnelles : les obligations de l'employeur" de service public me renvoie une erreur 404

**Comment by Loze-Faelens** [comment]
* si j'affiche un resultat Article, j'ai le code de l'article comme titre, et comme je n'ai plus l'enoncé de ma question, je ne comprends pas de quoi parle ce qui s'affiche (titre de l'article ? ou/et rappel de ma question 
 ?)

**Comment by jrduscher** [comment]
https://github.com/SocialGouv/code-du-travail-explorer/issues/115
