### ISSUE TITLE
Modifier la preview d'un document

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#911]
Suite à cette PR https://github.com/SocialGouv/code-du-travail-numerique/pull/894, le document a bien été changé mais pas la preview dans le navigateur.

## Version word
![image](https://user-images.githubusercontent.com/5337489/59186991-9a239080-8b74-11e9-89ba-dde776b15fa1.png)

## Version navigateur
![image](https://user-images.githubusercontent.com/5337489/59187020-aad40680-8b74-11e9-87cb-c27323e80607.png)

**Comment by lionelB** [comment]
bien vu ! je m'en occupe !

**Comment by ClementChapalain** [comment]
Merci !

**Comment by jrduscher** [comment]
https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-data/dataset/courrier-type/docx/signalement-harcelement.docx déjà modifié logiuement non?

**Comment by ClementChapalain** [comment]
@lionelB possible de faire un déploiement en prod pour répondre à la direccte qui nous a remonté le souci stp :) ?

**Comment by lionelB** [comment]
oui je regarde ca dans la journée et je te dit

**Comment by lionelB** [comment]
poke @ClementChapalain  https://codedutravail.num.social.gouv.fr/modeles-de-courriers/signalement-de-faits-pouvant-relever-du-harcelement-moral

**Comment by ClementChapalain** [comment]
merci beaucoup !
