### ISSUE TITLE
Petites améliorations dans l'affichage des CCNs

### ISSUE THREAD

**Issue by adipasquale** [SocialGouv/code-du-travail-numerique#912]
suite à #750

- [x] Différencier les styles des titres (titres, sections, articles)
- [x] Enlever l’icône qui est à gauche du titre
- [x] Enlever l’indication “convention collective” sous le titre
- [x] Pour chaque article enlever la mention “en vigueur” sachant qu'on a que des articles en vigueur. Afficher "Article étendu" ou "Article non-étendu" tout court à la place.

**Comment by adipasquale** [comment]
@ClementChapalain est-ce qu'on enleve complement la mention "étendu / non-étendu" en même temps que la mention "en vigueur" ?

**Comment by ClementChapalain** [comment]
pour l'instant on peut la garder car c'est une info importante mais il faudra qu'on change la manière dont on présente cette notion, ce sera pour une autre tâche

**Comment by adipasquale** [comment]
done in #941
