### ISSUE TITLE
Améliorer la précision des liens vers les conventions collectives

### ISSUE THREAD

**Issue by adipasquale** [SocialGouv/code-du-travail-numerique#913]
les liens devraient permettre d'accéder directement à : 

- [ ] chacune des tabs
- [ ] chacun des textes
- [ ] chacune des sections (?)
- [ ] chacun des articles

**Comment by lionelB** [comment]
tu parles de quels liens ?

**Comment by adipasquale** [comment]
je parle des URLs vers le site Code Du Travail Numérique. on voudrait des liens directs vers un article précis d'un texte précis d'une convention précise. 

aujourd'hui on a uniquement : 

https://codedutravail.num.social.gouv.fr/kali/44-convention-collective-nationale-des-industries-chimiques-et-connexes-du-30-de

on voudrait par exemple : 
https://codedutravail.num.social.gouv.fr/kali/44-convention-collective-nationale-des-industries-chimiques-et-connexes-du-30-de/KALITEXT0004/KALIARTI00096

cf discussion technique avec Manu sur https://incubateur-mas.slack.com/archives/CD8HVHK97/p1560245364020100

**Comment by adipasquale** [comment]
j'ai mis cette issue en pause en attendant de decider quelle direction est prise sur l'affichage des conventions dans le code du travail numerique @jeremiecook

**Comment by ClementChapalain** [comment]
outdated avec la nouvelle page convention collective
