### ISSUE TITLE
Ajouter 2 fiches SP n°R19231 et n°F22606

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#919]
Il faudrait ajouter ces 2 fiches de Service-Public.fr : 
- Déclaration d'accident du travail ou de trajet (DAT) en ligne => https://www.service-public.fr/particuliers/vosdroits/R19231
- Ouverture des commerces le dimanche => https://www.service-public.fr/professionnels-entreprises/vosdroits/F22606
Thanks

**Comment by UnbearableBear** [comment]
Nous n'indexons pas les fiches "resources" (celles qui commencent par un "R"). Elle sont référencées dans les fiches (Celle qui commencent par "F").
Je rajoute uniquement la F22606 donc !
