### ISSUE TITLE
[ok pour mise en prod]contenu intégré : mise en forme

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#92]
- Améliorer le rendu des contenu intégré pour se rapprocher de la présentation chez les fournisseurs (service-public...)
 - ajout info sur la date de publication/validité
 - lien vers la source

**Comment by revolunet** [comment]
cf mockups https://projects.invisionapp.com/share/DBMWXF74F2G#/screens/308308614

#95 #96 #97 #98 

<img width="1427" alt="capture d ecran 2018-09-20 a 09 16 52" src="https://user-images.githubusercontent.com/124937/45802103-22e06080-bcb6-11e8-90f8-c0371a5b2002.png">

**Comment by revolunet** [comment]
MAJ icones
[Archive 3.zip](https://github.com/SocialGouv/code-du-travail-explorer/files/2411523/Archive.3.zip)

**Comment by jrduscher** [comment]
Review:  ok sauf 
date qui ne s'affiche pas.
 https://github.com/SocialGouv/code-du-travail-numerique/issues/143
Mise en forme fiche intégrées service public: #209
