### ISSUE TITLE
[BUG] Enlever l'ancien footer qui apparaît sur certains outils

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/code-du-travail-numerique#920]
Dès que l'on clique sur l'outil de calcul de l'indemnité de licenciement, sur les modèles ou sur le simulateur d'embauche apparaît l'ancien footer en plus du footer actuel. 
**Il faudrait supprimer l'ancien footer** 

![image](https://user-images.githubusercontent.com/48682104/59290690-71d18a00-8c79-11e9-86db-e25c3a4f241e.png)

**Comment by virginielastisneres** [comment]
![image](https://user-images.githubusercontent.com/48682104/60610328-e94f9080-9dc3-11e9-87cb-cfe48afa111d.png)
l'ancien footer est toujours présent sur les outils

**Comment by lionelB** [comment]
ahhhh merci je ne le trouvais plus :)

**Comment by lionelB** [comment]
ahhhh mais en dev ca fait un moment qu'il y est plus :)

**Comment by lionelB** [comment]
closed by #921
