### ISSUE TITLE
Fiche SP.fr sur la participation F2141

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#924]
https://www.service-public.fr/particuliers/vosdroits/F2141

Il s'agit du corollaire de la fiche https://www.service-public.fr/particuliers/vosdroits/F2140 sur intéressement.

La fiche participation n’apparaît pas avoir été indexé au code du travail numérique ( ne remonte pas quand on recherche dans le moteur de recherche, n'apparait pas non plus en recherche via le datafiller).

Cette fiche est citée ici https://raw.githubusercontent.com/SocialGouv/code-du-travail-numerique/master/packages/code-du-travail-data/dataset/fiches_service_public/fiches-sp-travail.json
\":[{\"type\":\"element\",\"name\":\"Paragraphe\",\"$\":[{\"type\":\"text\",\"$\":\"Oui, sous conditions. Lorsque l'entreprise est tenue de verser une prime de \"},{\"type\":\"element\",\"name\":\"LienInterne\",\"_\":{\"LienPublication\":\"F2141\",\"type\":\"Fiche d'information\",\"audience\":\"Particuliers\"},\"$\":[{\"type\":\"text\",\"$\":\"participation\"}]}

=> Ajouter  la fiche F2141 sur la participation au corpus de fiches proposables aux users.

**Comment by lionelB** [comment]
accessible ici mais pas à jour à priori
https://codedutravail.num.social.gouv.fr/fiche-service-public/interessement?q=interressement

**Comment by lionelB** [comment]
pardon j'ai confondu -_-

**Comment by UnbearableBear** [comment]
Effectivement, elle n'est pas indexée encore, j'ajoute !

**Comment by lionelB** [comment]
@UnbearableBear dommage j'avais une PR en attente pour ca ( je m'etais assigné justement)
