### ISSUE TITLE
Ajouter la CCN des sociétés d'assurance au calculateur d'IDL

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#930]
# STES D'ASSURANCE

# préalable

### Information préalables (étapes antérieures)
- inaptitude (oui/ non)

si non: cas général 
si oui : cas général + inaptitude 

### Demander catégorie  : cadre/non-cadre/ne sais pas 
( catégorie:non-cadre"/"cadre)
"Préciser votre catégorie professionnelle"
choix : cadre/non-cadre/je ne sais pas
( si je ne sais pas retenir: non -cadre)
Wording, si je ne sais pas: " Dans la suite du calcul, nous avons retenu la catégorie non-cadre".

 
### calcul de l'ancienneté:
Trois articles de CCN impliqués, en cas de doute: ne pas agir seul :).

L'ancienneté se calcule en présence effective, définie comme présence continue en années révolues, liée au contrat de travail en cours:

Récupérer la donnée ancienneté brute depuis le calculateur d'indemnité légale ( c'est à dire: date de fin de contrat- date de début en mois.)

Récupérer les années complètes d'un côté, les mois des années incomplètes de l'autre.

### Droit à l'indemnité
Ancienneté 2
Récupérer date de sortie et date de début du contrat (IDLL)
Ancienneté2=date de sortie-date de signature du contrat

si ancienneté < 3 an
renvoi à l'indemnité légale,(mécanique logiquement)
wording possible en page résultat: "la convention collective prévoit une indemnité conventionnelle à partir de 3 ans d'ancienneté"

Si faute grave ou lourde in indemnité de licenciement = vrai;
Information/ wording: " Dans votre branche, en cas de licenciement pour faute grave ou lourde, le salarié ne pourra pas prétendre à l'indemnité conventionnelle de licenciement"

## base de calcul de l'indemnité du montant de l'indemnité de licenciemenent

salaire_de_reference= somme des salaires des 12 derniers mois - primes_hors_période + maintien de salaire maladie

1. Récupérer la rémunération annuelle
 
somme des 12 derniers mois de salaire avec prime depuis les données saisies avec l'indemnité légale de licenciemenent

2. Défalquer élement de rémunéraiton hors période

Wording: la CCN prévoit que "Dans le cas où des éléments de salaire perçus au cours des douze derniers mois sont afférents à d'autres périodes d'activité, ils ne sont pas pris en compte dans le calcul."

Afficher le détail précédemment saisi ( mois1->12  et salaires mensuels afférents),
Modifier ces élements. ( possibilité de modifier les salaires saisis.)
ou

"Montant global des primes à défalquer" label et champ numérique type €
"en cas d'arrêt maladie au cours de la période, indiquez s'il ya lieu les montants perçus au titre du maintien de salaire "

## montant de l'indemnité

ancienneté_en_années (décimal mois) *Pour le calcul de l'indemnité de licenciement, les années incomplètes sont retenues au prorata du nombre de mois de présence.*

a. catégorie=non-cadres, 3 < ancienneté < 10; age <50

indemnité_licenciement= 2,5%*salaire_de_reference*ancienneté en années  

b. catégorie=cadres, 3 < ancienneté < 10; age <50

indemnité_licenciement= 4%*salaire_de_reference*ancienneté en années

c. catégorie=non-cadres, 10=< ancienneté <20; age <50

indemnité_licenciement= 3%*salaire_de_reference*ancienneté en années

d. catégorie=cadres,10=< ancienneté <20; age <50

indemnité_licenciement= 4,5%*salaire_de_reference*ancienneté en années

e. catégorie=non-cadres, 20=< ancienneté <30; age <50

indemnité_licenciement= 3,5%*salaire_de_reference*ancienneté en années

f. catégorie=cadres,20=< ancienneté <30; age <50

indemnité_licenciement= 5%*salaire_de_reference*ancienneté en années

g. catégorie=non-cadres, ancienneté>=30; age <50

indemnité_licenciement= 4%*salaire_de_reference*ancienneté en années

h. catégorie=cadres, ancienneté >=30; age <50

indemnité_licenciement= 5,5%*salaire_de_reference*ancienneté en années

i. catégorie=non-cadres, 3 < ancienneté < 10; age >=50

indemnité_licenciement= 3%*salaire_de_reference*ancienneté en années

j. catégorie=cadres, 3 < ancienneté < 10; age >=50

indemnité_licenciement= 4,75%*salaire_de_reference*ancienneté en années

k. catégorie=non-cadres, 10=< ancienneté <20; age >=50

indemnité_licenciement= 3,5%*salaire_de_reference*ancienneté en années

l. catégorie=cadres,10=< ancienneté <20; age >=50

indemnité_licenciement= 5,25%*salaire_de_reference*ancienneté en années

m. catégorie=non-cadres, 20=< ancienneté <30; age >=50

indemnité_licenciement= 4%*salaire_de_reference*ancienneté en années

n. catégorie=cadres,20=< ancienneté <30; age >=50

indemnité_licenciement= 5,75%*salaire_de_reference*ancienneté en années

o. catégorie=non-cadres, ancienneté>=30; age >=50

indemnité_licenciement= 4,5%*salaire_de_reference*ancienneté en années

p. catégorie=cadres, ancienneté >=30; age >=50

indemnité_licenciement= 6,25%*salaire_de_reference*ancienneté en années

# Page résultat
## Si inaptitude=oui: page résultat spéciale

Récupérer ancienneté ( ancienneté convention collective)
Si ancienneté <15 ans et inaptitude = oui
Page résultat:
Afficher Indemnité légale de licenciement

Wording explicatif: " En cas de licenciement faisant suite au prononcé d'une inaptitude, avec une  ancienneté de moins de 15 ans, le salarié  droit à une indmenité spéciale équivalent à l'indmenité léglae de licenciement comme suit:"
Afficher résultat de l’indemnité légale de licenciement

Si ancienneté >=15 ans et inaptitude = oui
Page résultat:
Afficher Indemnité légale de licenciement

Wording explicatif: " En cas de licenciement faisant suite au prononcé d'une inaptitude, avec une  ancienneté de moins de 15 ans, le salarié  droit à une indemnité spéciale équivalent à l’indemnité conventionnelle de licenciement comme suit:"

Afficher résultat de l’indemnité conventionnelle de licenciement

L'user a le droit de connaitre **le détail** de l'indemnité retenue uniquement.

# références
**article 92.**
https://codedutravail.num.social.gouv.fr/kali/1672-convention-collective-nationale-des-societes-d%27assurances-du-27-mai-1992#KALIARTI000005792103
"Indemnité de licenciement.
Article 92
En vigueur étendu
Le collaborateur licencié alors qu'il compte plus de 3 ans de présence effective dans l'entreprise reçoit, sauf le cas de faute grave ou lourde (2), une indemnité calculée sur la base du total des salaires bruts correspondant à ses douze derniers mois d'activité (y compris, s'il y a lieu, le plein salaire maintenu par l'employeur pendant les trois premiers mois d'arrêt de travail pour maladie). Dans le cas où des éléments de salaire perçus au cours des douze derniers mois sont afférents à d'autres périodes d'activité, ils ne sont pas pris en compte dans le calcul.

Pour l'application du présent article, les années de présence dans l'entreprise s'entendent comme indiqué au b 4 de l'article 35.

L'indemnité est déterminée à raison de :

- 2,5 % de la rémunération annuelle, définie à l'alinéa ci-dessus, par année de présence dans l'entreprise si le nombre de ces années est inférieur à 10 ;

- 3 % par année si leur nombre est égal ou supérieur à 10 mais inférieur à 20 ;

- 3,5 % pour un nombre d'années égal ou supérieur à 20 mais inférieur à 30 ;

- 4 % au-delà.

Si le licenciement intervient alors que le salarié a au moins cinquante ans révolus, l'indemnité ci-dessus est majorée de 0,5 % de la rémunération annuelle par année de présence.

L'indemnité prévue au présent article ne se cumule pas avec l'indemnité légale.

Pour le calcul de l'indemnité de licenciement, les années incomplètes sont retenues au prorata du nombre de mois de présence.

(1) Article étendu sous réserve de l'application de la loi n° 78-49 du 19 janvier 1978 (art. 5 de l'accord annexé) (arrêté du 12 juillet 1993, art. 1er).

(2) Celle-ci étant, conformément à la jurisprudence, privative d'indemnité."
**article 75** 
https://codedutravail.num.social.gouv.fr/kali/1672-convention-collective-nationale-des-societes-d%27assurances-du-27-mai-1992#KALIARTI000005792078
**article 75** 
https://codedutravail.num.social.gouv.fr/kali/1672-convention-collective-nationale-des-societes-d%27assurances-du-27-mai-1992#KALIARTI000005792078
"Titularisation

La titularisation, c'est-à-dire l'accès à un certain nombre de garanties et avantages prévus par la présente convention, intervient, sauf dispositions plus favorables pratiquées au sein de l'entreprise, après douze mois de présence effective dans l'entreprise. Cela concerne les garanties suivantes : maladie et accident (art. 82 c), cure thermale (art. 85 ), maternité et adoption (art. 86 a, b, c et d), service national et périodes de réserve (art. 87 a et b), absences liées aux charges de famille (art. 88 a, 2e alinéa, et art. 88 b), licenciement pour faute ou insuffisance professionnelle (art. 90 a).

La durée de douze mois est ramenée à trois mois pour les salariés ayant au moins douze mois de présence chez un autre employeur (au sens de l'art. 1 ) au cours des cinq dernières années précédant leur embauche dans l'entreprise.

N.B. - Le règlement du régime professionnel de prévoyance sera modifié afin que l'affiliation des employés, agents de maîtrise et cadres puisse intervenir après trois mois de présence effective chez un même employeur (au lieu de douze mois).
"

**article 35 b4:**
_"b 4. Par année de présence effective dans l'entreprise, il faut entendre une année révolue de présence continue dans l'entreprise au titre du même contrat de travail. Pour l'application du présent article, sont assimilées à du temps de présence continue, si le salarié remplissait la condition de présence effective dans l'entreprise fixée à l'article 75 lorsqu'elles ont débuté, les périodes de suspension du contrat pour :

- maladie ou accident donnant lieu à indemnisation complémentaire par l'employeur, dans la limite d'un an ;

- cure thermale agréée par la sécurité sociale donnant lieu à indemnisation complémentaire par l'employeur ;

- maternité (1)et adoption ;

- ainsi que périodes de réserve obligatoires."_

**article 75** 
https://codedutravail.num.social.gouv.fr/kali/1672-convention-collective-nationale-des-societes-d%27assurances-du-27-mai-1992#KALIARTI000005792078
"Titularisation

La titularisation, c'est-à-dire l'accès à un certain nombre de garanties et avantages prévus par la présente convention, intervient, sauf dispositions plus favorables pratiquées au sein de l'entreprise, après douze mois de présence effective dans l'entreprise. Cela concerne les garanties suivantes : maladie et accident (art. 82 c), cure thermale (art. 85 ), maternité et adoption (art. 86 a, b, c et d), service national et périodes de réserve (art. 87 a et b), absences liées aux charges de famille (art. 88 a, 2e alinéa, et art. 88 b), licenciement pour faute ou insuffisance professionnelle (art. 90 a).

La durée de douze mois est ramenée à trois mois pour les salariés ayant au moins douze mois de présence chez un autre employeur (au sens de l'art. 1 ) au cours des cinq dernières années précédant leur embauche dans l'entreprise.

N.B. - Le règlement du régime professionnel de prévoyance sera modifié afin que l'affiliation des employés, agents de maîtrise et cadres puisse intervenir après trois mois de présence effective chez un même employeur (au lieu de douze mois).
"

**Comment by lionelB** [comment]
@jrduscher on dirait un copié coller de celle des transport (idcc 0016)

**Comment by jrduscher** [comment]
@lionelB c'était bien un copier coller de la 16. ce n'est plus le cas, mais c'est encore WIP
