### ISSUE TITLE
Ajouter la convention collective des banques à l'IDL (IDCC 2120 )

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#931]
# CCN

Convention collective nationale des banques

IDCC: 2120
BANQUE

# Demandes préalable: 

 si inaptitude dans l'indemnité de licenciement: renvoi à l'indemnité légale. 
sinon:

1. Demander le motif du licenciement parmi les motifs suivants:
" Préciser le motif du licenciement parmi les motifs suivants"
- Motif disciplinaire
- Motif non disciplinaire
- Motif économique

2. Demander catégorie  : cadre/non-cadre/ne sais pas 
( catégorie:non-cadre"/"cadre)
"Préciser votre catégorie professionnelle"
choix : cadre/non-cadre/je ne sais pas
( si je ne sais pas retenir: non -cadre)

# Motif disciplinaire
Afficher: "La convention collective prévoit le droit à l’indemnité légale en cas de licenciement pour motif disciplinaire, sauf pour faute grave ou lourde"
Afficher l'indemnité légale
	
# Motif non disciplinaire
### Base de calcul

*salaire de référence*= 1/13è *(12 derniers mois de salaire + prime de 13ème mois)*

- Récupérer la somme des salaires saisis sur les 12 derniers mois avec l'indmenité légale

- Récupérer et ajouter prime de 13ème mois
		Demander : si prime de 13ème mois. 
	 Afficher " Une prime de 13ème mois a t-elle été versée au cours de l'année?"
                   Afficher les salaires saisis précédemment et les primes.
		 		 "ajouter une prime de 13ème mois": label + champ 

			
				
### Ancienneté et date d'embauche 

1. Déterminer les périodes d'ancienneté nécessaires aux calculs.

- **ancienneté globale**

**ancienneté_globale**: récupérer l'ancienneté de l'indemnité légale

si ancienneté_globale inférieure à 1 an : renvoi à l'indemnité légale. " La convention collective prévoit une indemnité conventionnelle de licenciement à partir d'un an d'ancienneté"
		

- **Retenir l'ancienneté avant le 1/1/2002 en semestre complets:**

**ancienneté_inf_1jan2002**= 1/1/2002- date d'entrée dans l'entreprise saisie avec l'indé légale

Affiner l'ancienneté globale pour le calcul de l'indemnité:sont pris en compte années complètes, semestres complets (année/2) ( ex: si ancienneté: 1 an et 7 mois, ancienneté retenue 1an et 6 mois, l'ancienneté en nombre de semestre :3)
		

- **Retenir l'ancienneté >= le 1/1/2002 en semestre complets:**		
		
**ancienneté_supégale_1jan2002**= date de sortie- 1/1/2002
		
Affiner l'ancienneté globale pour le calcul de l'indemnité:sont pris en compte années complètes, semestres complets (année/2) ( ex: si ancienneté: 1 an et 7 mois, ancienneté retenue 1an et 6 mois, l'ancienneté en nombre de semestre :3)
		
2. Déterminer conditions date d'embauche pour maximum embauche
_important pour le calcul du montant__
date_entree= si (date d'entrée > 31/12/1999; "max_2000";"max_99")
					
		
### Montant de l'indemnité
		
1. Indemnité brute
			
Indemnité_brute= 1/2*salaire_de_référence*13/14,5*(*ancienneté_inf_1jan2002*)+1/5*salaire de référence*(*ancienneté_supégale_1jan2002*)
			
2. Indemnité totale et plafonnée
			
**a) si date_entrée="max99" et "non-cadre"**
				
indemnité_plafond_99= 18*salaire_de_référence*13/14,5
					
Indemnité totale=(si(indemnité_brut>indemnité plafond; indemnité_plafond; indemnité_brute))

				
**b) si date_entrée="max99" et "cadre"**
				
indemnité_plafond_99= 24*salaire_de_référence*13/14,5
					
Indemnité totale=(si(indemnité_brut>indemnité plafond_99; indemnité_plafond_99; indemnité_brute))
				
				
**c) si date_entrée="max2000"** 	
				
indemnité_plafond_2000= 15*salaire_de_référence
					
Indemnité totale=(si(indemnité_brut>indemnité plafond_2000; indemnité_plafond; indemnité_brute))
				
		
# Motif économique
### Base de calcul

*salaire de référence*= 1/13è *(12 derniers mois de salaire + prime de 13ème mois)*

- Récupérer la somme des salaires saisis sur les 12 derniers mois avec l'indmenité légale

- Récupérer et ajouter prime de 13ème mois
		Demander : si prime de 13ème mois. 
	 Afficher " Une prime de 13ème mois a t-elle été versée au cours de l'année?"
                   Afficher les salaires saisis précédemment et les primes.
		 		 "ajouter une prime de 13ème mois": label + champ 

			
				
### Ancienneté et date d'embauche 

1. Déterminer les périodes d'ancienneté nécessaires aux calculs.

- **ancienneté globale**

**ancienneté_globale**: récupérer l'ancienneté de l'indemnité légale

si ancienneté_globale inférieure à 1 an : renvoi à l'indemnité légale. " La convention collective prévoit une indemnité conventionnelle de licenciement à partir d'un an d'ancienneté"
		

- **Retenir l'ancienneté avant le 1/1/2002 en semestre complets:**

**ancienneté_inf_1jan2002**= 1/1/2002- date d'entrée dans l'entreprise saisie avec l'indé légale

Affiner l'ancienneté globale pour le calcul de l'indemnité:sont pris en compte années complètes, semestres complets (année/2) ( ex: si ancienneté: 1 an et 7 mois, ancienneté retenue 1an et 6 mois, l'ancienneté en nombre de semestre :3)
		

- **Retenir l'ancienneté >= le 1/1/2002 en semestre complets:**		
		
**ancienneté_supégale_1jan2002**= date de sortie- 1/1/2002
		
Affiner l'ancienneté globale pour le calcul de l'indemnité:sont pris en compte années complètes, semestres complets (année/2) ( ex: si ancienneté: 1 an et 7 mois, ancienneté retenue 1an et 6 mois, l'ancienneté en nombre de semestre :3)
		
2. Déterminer conditions date d'embauche pour maximum embauche
_important pour le calcul du montant__
date_entree= si (date d'entrée > 31/12/1999; "max_2000";"max_99")
# Montant de l'indemnité conventionnelle de licenciement
	
**1. Indemnité brute**
			
Indemnité_brute= 1/2*salaire_de_référence*(*ancienneté_inf_1jan2002*)+1/4*salaire de référence*(*ancienneté_supégale_1jan2002*)
			
**2. Indemnité totale et plafonnée**
			
**a) si date_entrée="max99" et "non-cadre"**

indemnité_plafond_99= 18*salaire_de_référence*13/14,5
					
Indemnité totale=(si(indemnité_brut>indemnité plafond; indemnité_plafond; indemnité_brute))

				
b) si date_entrée="max99" et "cadre"
				
indemnité_plafond_99= 24*salaire_de_référence*13/14,5
				
Indemnité totale=(si(indemnité_brut>indemnité plafond_99; indemnité_plafond_99; indemnité_brute))							

c) si date_entrée="max2000" 
				
indemnité_plafond_2000= 18*salaire_de_référence
					
Indemnité totale=(si(indemnité_brut>indemnité plafond_2000; indemnité_plafond; indemnité_brute))

				
# alternance Temps plein temps/partiel dans la même entreprise ( peu importe le motif)
				
récupérer les données permettant de proratiser le calcul de l'indemnité légale en fonction des périodes de temps plein et temps partiel. 

appliquer la proratisation au montant de l'indemnité de licenciement conventionnel.
		
					
# Références

*art. 26 CCN*:
	https://codedutravail.num.social.gouv.fr/kali/2120-convention-collective-nationale-de-la-banque-du-10-janvier-2000.-etendue-p#KALIARTI000005779933

*art. 29 CCN*:
	https://codedutravail.num.social.gouv.fr/kali/2120-convention-collective-nationale-de-la-banque-du-10-janvier-2000.-etendue-p#KALIARTI000005783374

**Comment by lionelB** [comment]
attention, le calcul ne tiens pas compte des période d'absence prolongée pour l'instant car nous ne demandons pas les dates debut ou de fin. Il faudrait prévoir de rajouter ca prochainement

**Comment by jrduscher** [comment]
![image](https://user-images.githubusercontent.com/37538697/62057411-e8254e00-b21f-11e9-929d-bbc923f35f44.png)

![image](https://user-images.githubusercontent.com/37538697/62057444-f7a49700-b21f-11e9-9f50-8deab02e10cd.png)


En cas de licenciement disciplinaire: 
le salarié a droit au versement de lindmeinté légale de licenciement. Aujourd'hui, le calculateur renvoie uniquement le wording.
-> Afficher une page résultat avec:
Indemnité légale de licenciement + détails ( conformes à la page de résultat actuelle)
-Afficher le titre indemnité conventionnelle.
Afficher en dessous le wording "La convention collective prévoit le droit à l’indemnité légale en cas de licenciement pour motif disciplinaire, sauf pour faute grave ou lourde"
