### ISSUE TITLE
Calculateur indemnité de précarité CDD

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#933]

**Comment by virginielastisneres** [comment]
## Introduction sur la prime de précarité CDD et CTT

* **CDD**
 
Si à la fin d’un CDD le salarié ne poursuit pas en CDI dans l’entreprise, il a droit à une indemnité de fin de contrat (prime de précarité). Cette indemnité est égale à 10 % de la rémunération totale brute versée au salarié.
 
Exceptions sur le droit à l’indemnité :
Certains types de CDD n’ont pas le droit à cette indemnité.
Dans certaines situations liées à la rupture du CDD, les salariés n’ont pas le droit à cette indemnité.
 
Exception sur le montant de l'indemnité :
Dans un cas spécifique, une convention ou un accord collectif de branche étendu ou une convention ou un accord d'entreprise ou d'établissement peut également prévoir de limiter le montant de l'indemnité de fin de contrat à hauteur de 6 %.
 
* **CTT**

Idem que le CDD : Si à la fin d’un CTT le salarié ne poursuit pas en CDI dans l’entreprise utilisatrice, il a droit à une indemnité de fin de mission (prime de précarité).
Cette indemnité est égale à 10 % de la rémunération totale brute versée au salarié.
 
Exceptions sur le droit à l’indemnité :
Certains types de CTT n’ont pas le droit à cette indemnité.
Dans certaines situations liées à la rupture du CTT, les salariés n’ont pas le droit à cette indemnité.
Attention ce ne sont pas forcément les mêmes types de contrat ou les mêmes situations que le CDD. 
 
**Vision version 1 de l'outil : Les paramètres à prendre en compte pour le calcul légal sont donc :**
- Le type de CDD/CTT
- La situation exacte de la rupture du CDD/CTT
- La rémunération totale brute
 
**Vison version 2 de l'outil :**
Prise en compte du conventionnel pour 2 raisons :
-  Soit baisse du taux du montant à 6%
-  Soit dispositions plus favorables (ex, inclure des types de CDD qui ne devraient pas y avoir droit)
Rajouter des définitions explications pour certains termes employés ?

## Specs de l'outil 

=> **pour le visuel** : reprise du design de l'outil de calcul de l'indemnité de licenciement

### 1) Page home de l'outil

Le salarié en CDD ou en contrat de travail temporaire (contrat d’intérim) peut bénéficier à la fin de son contrat d’une prime de précarité également appelée [indemnité de fin de CDD](https://www.service-public.fr/particuliers/vosdroits/F40) ou [indemnité de fin de mission](https://www.service-public.fr/particuliers/vosdroits/F11215). Cette prime de précarité est égale au minimum à 10 % de la rémunération brute totale versée au salarié durant le contrat.

Le simulateur de la prime de précarité est un outil qui permet de calculer la prime de précarité d’un salarié.

Cette simulation nécessite environ 5 minutes. Afin de pouvoir remplir les renseignements demandés, munissez-vous des informations relatives à votre contrat de travail (CDD ou contrat de travail temporaire (contrat d’intérim), derniers bulletins de salaire, etc.).

Pour commencer le simulateur cliquez sur "Suivant". 

### 2) Etape 1 – Informations sur votre contrat de travail

1ère question : demander à l’utilisateur s’il est en CDD ou en Contrat temporaire « intérim ».

**« Quel est votre type de contrat de travail ?**
* **Contrat à durée déterminée (CDD)**
* **Contrat de travail temporaire (Contrat d’intérim)**

2ème question :

* Si l'utilisateur a cliqué sur CDD apparaît une sous question

**« Votre type de CDD fait-il partie de la liste suivante :** 
* **CDD saisonnier ou [CDD d’usage](https://www.service-public.fr/particuliers/vosdroits/F32476)**
* **Contrat unique d’insertion (CUI) ou Parcours emploi compétences (PEC)**
* **Contrat de professionnalisation ou Contrat d’apprentissage**
* **CDD conclu avec un jeune (mineur ou majeur) pendant ses vacances scolaires ou universitaires**
* **Contrat pour lequel l’employeur s’est engagé à assurer un complément de formation professionnelle au salarié**
* **CCD dans le cadre d’un congé de mobilité**
                   **Oui**
                   **Non”**

Si l’utilisateur clique sur non il passe à l’étape suivante. 

Si l’utilisateur clique sur OUI s’affiche le wording suivant :
**« Votre type de contrat ne vous permet pas d’avoir droit à une prime de précarité. »**
    
 
* Si l'utilisateur a cliqué sur CTT apparaît une sous question 

**« Avez-vous un contrat de mission-formation ?** 
                   **Oui**
                   **Non”**

Si clique sur oui : **« Votre type de contrat ne vous permet pas d’avoir droit à une prime de précarité. »**

Si non, petit warning : **Attention : si vous avez un contrat de travail temporaire (contrat d'intérim) saisonnier ou d'usage, un accord d’entreprise ou d’établissement peut dispenser votre entreprise de travail temporaire (l'entreprise d'intérim) de vous verser une indemnité de précarité.**
puis l’utilisateur passe à l’étape suivante. 

 
### Etape 2 – Situations spécifiques

* Si l'utilisateur a cliqué sur CDD 

3ème question :
**“Votre CDD a-t-il été rompu pendant votre période d’essai ?**
* **Oui**
* **Non”**

Si l’utilisateur clique sur non on passe à l’étape suivante
Si l’utilisateur clique sur oui s’affiche le wording suivant : **« Lorsque le CDD a été rompu pendant la période d’essai, le salarié en CDD n’a pas le droit à une indemnité de précarité. »**
 
4ème question :
**“A la fin de votre CDD, avez-vous été immédiatement embauché en CDI, sans interruption, sur un même poste ou sur un poste différent ?**
* **Oui**
* **Non”**

Si l’utilisateur clique sur non on passe à l’étape suivante.
Si l’utilisateur clique sur oui s’affiche le wording suivant : **« Le salarié en CDD qui est immédiatement embauché dans l’entreprise en CDI, sans interruption, sur un même poste ou sur un poste différent, n’a pas le droit à une indemnité de précarité. »**
 
5ème question :
**“A la fin de votre CDD, avez-vous refusé un CDI pour occuper le même emploi ou un emploi similaire dans l’entreprise avec une rémunération au moins équivalente ?**
* **Oui**
* **Non”**

Si l’utilisateur clique sur non on passe à l’étape suivante.
Si l’utilisateur clique sur oui s’affiche le wording suivant : **« Le salarié en CDD qui refuse un CDI pour occuper le même emploi ou un emploi similaire dans l’entreprise avec une rémunération au moins équivalente, n’a pas le droit à une indemnité de précarité. »**
 
6ème question :
**“Votre CDD a-t-il été rompu avant la fin prévue pour une des raisons suivantes : votre propre initiative, votre faute grave ou faute lourde, en cas de force majeure ?**
* **Oui**
* **Non”**

Si l’utilisateur clique sur non on passe à l’étape suivante
Si l’utilisateur clique sur oui s’affiche le wording suivant : **« Lorsque le CDD est rompu de manière anticipée à l’initiative du salarié, pour faute grave, pour faute lourde ou en cas de force majeure, le salarié en CDD n’a pas le droit à une indemnité de précarité. »**
 
7ème question :
**“Avez-vous refusé de renouveler votre CDD alors que votre CDD comportait une clause de renouvellement automatique ?**
* **Oui**
* **Non”**

Si l’utilisateur clique sur non on passe à l’étape suivante
Si l’utilisateur clique sur oui s’affiche le wording suivant : **« Le salarié en CDD qui refuse le renouvellement de son CDD alors qu’était prévu dans son contrat prévoyait son renouvellement automatique n’a pas le droit à une indemnité de précarité. »**
 

* Si l'utilisateur a cliqué sur CTT 

3ème question
**“Votre contrat de travail temporaire (contrat d'intérim) a-t-il été rompu avant la fin prévue pour une des raisons suivantes : votre propre initiative, votre faute grave ou en cas de force majeure ?**
* **Oui**
* **Non”**

Si l’utilisateur clique sur non on passe à l’étape suivante
Si l’utilisateur clique sur oui s’affiche le wording suivant : **« Lorsque le contrat de travail temporaire (contrat d'intérim) est rompu de manière anticipée à l’initiative du salarié, pour faute grave ou en cas de force majeure, le salarié n’a pas le droit à une indemnité de précarité. »**

4ème question 
**“A la fin de votre contrat de travail temporaire (contrat d'intérim), avez-vous été immédiatement embauché en CDI au sein de l'entreprise dans laquelle vous effectuiez votre mission ?**
* **Oui**
* **Non”**

Si l’utilisateur clique sur non on passe à l’étape suivante.
Si l’utilisateur clique sur oui s’affiche le wording suivant : **« Le salarié en contrat de travail temporaire (contrat d'intérim) qui est immédiatement embauché en CDI au sein de l'entreprise dans laquelle il effectuait sa mission n’a pas le droit à une indemnité de précarité. »**

5ème question 
**“Avez-vous refusé la mise en œuvre de la souplesse prévue dans votre contrat de travail temporaire (contrat d'intérim) ?**
* **Oui**
* **Non”**

Si l’utilisateur clique sur non on passe à l’étape suivante
Si l’utilisateur clique sur oui s’affiche le wording suivant : **« Le salarié en intérim qui refuse la mise en œuvre de la souplesse prévue dans son contrat de travail temporaire n’a pas le droit à une indemnité de précarité. »**


### Etape 3 – Rémunération
8ème question ou 6ème question : 2 options pour l’utilisateur

**Indiquez votre rémunération totale brute* perçue pendant votre contrat :**   
*Majorations, indemnités, primes et accessoires compris sauf les remboursements de frais et l’indemnité de congés payés. 
        
**Ou**

**Indiquez vos salaires bruts* perçus pendant votre contrat :**
*Majorations, indemnités, primes et accessoires compris sauf les remboursements de frais et l’indemnité de congés payés. 
=>Possibilité pour l’utilisateur de mettre autant que mois de salaire qu’il le souhaite (reprise du principe de l'indication par mois du calculateur de l'indemnité de licenciement. 
 
Si option 1 alors (RTB*100)/10
Si option 2 [(SB1 + SB2 + SB3 + SB4…)*100]/10

l'utilisateur passe à l'étape suivante une fois la rémunération indiquée. 

### Etape 4 – Montant de la prime de précarité

Afficher le résultat avec la formule en détail avec les éléments renseignés par l'utilisateur et le wording suivant : 

* Si l'utilisateur a cliqué sur CDD 

**Votre prime de précarité (appelée également indemnité de fin de CDD) est estimée à XX €.** 

Attention warning : **Attention : l'estimation est basée sur le montant de la prime de précarité prévu par le code du travail qui est de 10% de la rémunération totale brute perçue par le salarié. Une convention ou un accord collectif de branche étendu ou une convention ou un accord d'entreprise ou d'établissement peut prévoir de limiter le montant de l'indemnité de fin de contrat à hauteur de 6 %, dès lors que des contreparties sont offertes à ces salariés, notamment sous la forme d'un accès privilégié à la formation professionnelle*.** (à améliorer ?)
*L'employeur doit faire une proposition précise de formation au salarié.

**En savoir plus sur la prime de précarité (également appelée indemnité de fin de CDD) d'un [salarié en CDD](https://www.service-public.fr/particuliers/vosdroits/F40).** 

* Si l'utilisateur a cliqué sur CTT

**Votre prime de précarité (appelée également indemnité de fin de mission) est estimée à XX €.** 
**En savoir plus sur la prime de précarité (également appelée indemnité de fin de mission) d'un [salarié en contrat de travail temporaire (contrat d'intérim)](https://www.service-public.fr/particuliers/vosdroits/F11215).**

**Comment by ClementChapalain** [comment]
trop bien ! juste un doute sur les `*` c'est pas hyper lisible je trouve et ça fait un peu conditions de vente en petits caractères :) on peut p-e insérer les informations dans les paragraphes directement ?

**Comment by virginielastisneres** [comment]
Mes remarques : 
![image](https://user-images.githubusercontent.com/48682104/61117246-60f17f80-a496-11e9-81d1-17fc23b07dcb.png)
- serait-il possible de mettre après contrat "de travail" 

![image](https://user-images.githubusercontent.com/48682104/61117363-a6ae4800-a496-11e9-9577-a8e0d9cd83e7.png)
remplacer par "Simulateur de l'indemnité de précarité" pas de pluriel

**Comment by lionelB** [comment]
![no-problemo](https://user-images.githubusercontent.com/160320/61117531-03116780-a497-11e9-88c9-e69b9698cd8a.jpg)

**Comment by virginielastisneres** [comment]
![image](https://user-images.githubusercontent.com/48682104/61117537-06a4ee80-a497-11e9-943f-3385264f0026.png) 
Attention la phrase qui dit que l'on a pas le droit à l'indemnité de précarité doit apparaitre pour la réponse oui et non la réponse non. 

Autre proposition faite par JR qui est très bien je trouve : regroupe les deux questions en ne faisant apparaître la 2ème question que si l'usager a cliqué sur non à la première question. 

Exemple : À la fin de votre CDD, avez-vous été immédiatement embauché en CDI, sans interruption, sur un même poste ou sur un poste différent ? 
- Oui : vous avez pas le droit
- Non : sous question qui apparaît : avez-vous refusé un CDI pour occuper le même emploi ou un emploi similaire dans l’entreprise avec une rémunération au moins équivalente ?
- Oui : pas le droit 
- Non : question suivante
:)

**Comment by virginielastisneres** [comment]
merci @lionelB

**Comment by virginielastisneres** [comment]
![image](https://user-images.githubusercontent.com/48682104/61118390-eece6a00-a498-11e9-9e48-2eed6f57de1d.png)
oups j'ai oublié des mots dans la phrase... ahah :)
"Le salarié en CDD qui refuse le renouvellement de son CDD alors que son contrat prévoyait son renouvellement automatique n’a pas le droit à une indemnité de précarité".

**Comment by lionelB** [comment]
@virginielastisneres j’avoue j’ai lu en diagonale et j’ai copié / coller comme un cochon

**Comment by virginielastisneres** [comment]
Pour les écrans de fin, il manque un écran : normalement en fonction du type de contrat de l'utilisateur l'écran de fin est différent. 

* Si l'utilisateur a cliqué sur CDD: 

Votre prime de précarité (appelée également indemnité de fin de CDD) est estimée à XX €.

Warning : Attention : l'estimation est basée sur le montant de la prime de précarité prévu par le code du travail qui est de 10% de la rémunération totale brute perçue par le salarié. Une convention ou un accord collectif de branche étendu ou une convention ou un accord d'entreprise ou d'établissement peut prévoir de limiter le montant de l'indemnité à hauteur de 6 %, dès lors que des contreparties sont offertes à ces salariés, notamment sous la forme d'un accès privilégié à la formation professionnelle. 

En savoir plus sur la prime de précarité d'un salarié en CDD.

* Si l'utilisateur a cliqué sur CTT

Votre prime de précarité (appelée également indemnité de fin de mission) est estimée à XX €.
En savoir plus sur la prime de précarité d'un salarié en contrat de travail temporaire (contrat d'intérim).


La j'ai fais le parcours salarié en CDD et CTT et j'ai qu'un type d'écran qui s'affiche ![image](https://user-images.githubusercontent.com/48682104/61119005-37d2ee00-a49a-11e9-85c1-332907153002.png)
il faudrait ajouter l'écran de fin pour le salarié en CDD

**Comment by virginielastisneres** [comment]
@lionelB tkt j'ai moi même été confuse dans ma phrase :)

**Comment by virginielastisneres** [comment]
![image](https://user-images.githubusercontent.com/48682104/61119661-9cdb1380-a49b-11e9-9972-209c5df8fed7.png)
peut être que l'on peut supprimer temporaire (contrat d'intérim), la personne a déjà cliqué sur contrat de travail temporaire (intérim) donc bon, ca enlève un peu de texte qui n'est pas trop utile...

**Comment by virginielastisneres** [comment]
![image](https://user-images.githubusercontent.com/48682104/61119738-cb58ee80-a49b-11e9-9eea-93a874a99311.png)

Je chipote un peu : il manque le point d'interrogation...

**Comment by virginielastisneres** [comment]
![image](https://user-images.githubusercontent.com/48682104/61120059-5fc35100-a49c-11e9-879b-48bc0514b111.png)
avec les statistiques demandées par Nadia on a vu que les personnes utilisent pas vraiment le terme contrat de travail temporaire mais plutôt contrat d'intérim ; je me dis qu'en ayant déjà indiqué dans la première page contrat de travail temporaire on pourrait enlever ce terme pour les autres questions et laisser uniquement "contrat d'intérim" ca fait gagner de la place et ca réduit un peu les phrases :)

**Comment by virginielastisneres** [comment]
![image](https://user-images.githubusercontent.com/48682104/61120331-09a2dd80-a49d-11e9-9712-108e5801c0a4.png)
Désolé j'ai mal rédigé cette phrase.... est ce que c'est possible de la modifier par celle là : 
Le salarié en contrat d'intérim qui refuse la mise en œuvre de la souplesse prévue dans son contrat n’a pas le droit à une indemnité de précarité.
Mercii :)

**Comment by virginielastisneres** [comment]
dernière petite modification @lionelB :) :) 
Vu que le terme le plus employé par les usagers est "prime de précarité". est ce qu'il est possible de changer le titre de l'outil par "Simulateur de la prime de précarité".

**Comment by lionelB** [comment]
pour les changement de noms, j’ai fait les modifs mais je suis complément convaincu :)
par contre qu’on utilise les synonyms pour pouvoir trouver le contenu, pas de soucis

**Comment by virginielastisneres** [comment]
Tu vas me détester... cette correction est ma faute j'ai utilisé le terme indemnité de précarité et prime de précarité à différents endroits. J'aimerais l'utilisation d'un seul et meme terme afin d'éviter toute confusions... Du coup il faudrait remplacer "indemnité de précarité" par "prime de précarité". On retrouve principalement le terme "indemnité de précarité" dans l'étape 3 à la fois en cas de CDD ou de contrat d'intérim. 
Ci-dessous les endroits où il faudrait remplacer le terme :) merciiii
![image](https://user-images.githubusercontent.com/48682104/61208638-2ab33a80-a6f8-11e9-9e53-cdda44178dd7.png)
![image](https://user-images.githubusercontent.com/48682104/61208701-4f0f1700-a6f8-11e9-84ad-15faddc25e39.png)
![image](https://user-images.githubusercontent.com/48682104/61208735-5d5d3300-a6f8-11e9-9cc8-e88167fd72d0.png)
![image](https://user-images.githubusercontent.com/48682104/61208785-7239c680-a6f8-11e9-955a-564f4ea90774.png)
![image](https://user-images.githubusercontent.com/48682104/61208823-88e01d80-a6f8-11e9-8434-9990294ded44.png)
![image](https://user-images.githubusercontent.com/48682104/61209030-fb50fd80-a6f8-11e9-9d45-47dfef3280d2.png)
![image](https://user-images.githubusercontent.com/48682104/61209075-1459ae80-a6f9-11e9-90bf-f7ba1e87f02e.png)
![image](https://user-images.githubusercontent.com/48682104/61209112-289dab80-a6f9-11e9-82d4-977ffc39ad42.png)

**Comment by virginielastisneres** [comment]
à la page de fin de la prime de précarité du contrat d'intérim il faut enlever l'alerte qui ne vaut que pour les CDD 
![image](https://user-images.githubusercontent.com/48682104/61209345-cabd9380-a6f9-11e9-8b07-c65872d5a4c7.png)

**Comment by virginielastisneres** [comment]
dernière remarque mais c'est vraiment pour chipoter... est ce que c'est possible de rajouter "mensuels" pour éviter toute erreur : **salaires mensuels bruts**
![image](https://user-images.githubusercontent.com/48682104/61209461-196b2d80-a6fa-11e9-84c6-0f2e5df2d682.png)

**Comment by virginielastisneres** [comment]
### **UN GROS MERCI** @lionelB  👍 👍

**Comment by virginielastisneres** [comment]
NB ( à ne pas oublier) : il faudra intégrer également dans l'outil les références juridiques liées au code du travail afin de permettre la mise à jour de l'outil en cas de modification juridique. 
a voir avec Aurélie et Clément comment ces dernières seront intégrées.  
les références juridiques ci-dessous : 
pour les CDD : Article L 1243-8, Article L 1243-9 et Article L 1243-10 du code du travail
pour les CTT : Article L 1251-32 et Article L 1251-33

**Comment by lionelB** [comment]
@virginielastisneres  j’ai rajouté les ref dans les meta, Mis à part ca, est-ce que c’est l’outil est ok pour toi ?

**Comment by virginielastisneres** [comment]
@lionelB NIKEL 👍 👍 merci lionel :)
