### ISSUE TITLE
Utiliser l'API DILA pour les conventions collectives

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#935]

**Comment by revolunet** [comment]
- [ ] vérifier le listing KALI actuel
 - [x] produire des JSONs des CCNs via API DILA
 - [ ] tests de validité des textes
 - [ ] intégration dans ES
 - [ ] intégration dans frontend

**Comment by lionelB** [comment]
peut etre utiliser le snapshot testing ?

**Comment by revolunet** [comment]
(je pars du principe qu'on suit le meme fonctionnement que les autres sources de données : on récupère et fournit la donnée (CCN) directement (pas d'API tierce pour la consultation) )

**Comment by revolunet** [comment]
Exemples d'extraction des CCNs : https://github.com/SocialGouv/dila-api-client

**Comment by revolunet** [comment]
Exemple de fichier produit [KALICONT000005635810.json.zip](https://github.com/SocialGouv/code-du-travail-numerique/files/3422745/KALICONT000005635810.json.zip)

equivalent Legifrance : https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635810

**Comment by revolunet** [comment]
Quelques cas particuliers détectés : 

 - IDCC 207, 1596, 1597 : plusieurs textes de base publiés sur légifrance

Il faut s'assurer qu'on les récupère bien aussi

**Comment by revolunet** [comment]
Suite à discussion hier et nécessité de partager des données notamment des CCNs avec l'outil de contrib, je propose :

création d'un repo/package `@socialgouv/kali-data` qui contiendrait :
 - scripts d'extraction des CCNs ([fetch-ccn](https://github.com/SocialGouv/dila-api-client/blob/master/examples/fetch-ccn.js)) + tests
 - versionning fichiers générés dans GIT
 - un fichier de recap des chgts dans les CCNS (changelog data)
 - avec publication sur npm :
      - `data/index.json`: liste des ccns
      - `data/[idconteneur].json` : json ccns
      - `updates.json` : historique des dernieres modifs (veille)
 - automisable via CI par la suite

Ceci nous permettra de récupérer via npm/renovate le listing des CCs à jour ainsi que les datas minimales pour chacune (version strippée des données de l'API).

**Comment by revolunet** [comment]
cc @UnbearableBear @lionelB @ivangabriele

**Comment by UnbearableBear** [comment]
Ok je regarde comment combiner ça avec la partie indexation des CCN dans ES

**Comment by lionelB** [comment]
> Ok je regarde comment combiner ça avec la partie indexation des CCN dans ES

on peut le faire ensemble, j'avais prévue de faire la partie indexatio :)

**Comment by UnbearableBear** [comment]
Oui pourquoi pas ! Je débroussaille et quand j'arrive à la partie indexation on se fait un call ?

**Comment by revolunet** [comment]
si on peut extraire notre référentiel ici : https://github.com/SocialGouv/kali-data

peut-être utilisé ensuite pour ingestion ES ou autre :)
