### ISSUE TITLE
MAJ données ePoseidon

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#94]
- [ ] Mettre à jour les données des tags 
 - [ ] Utiliser comme source principale pour le CDT

**Comment by revolunet** [comment]
Problèmes : 

 - perte de mise en forme du contenu
 - comment faire le lien avec l'url legifrance ?
 - récupérer la structure du CDT

**Comment by jrduscher** [comment]
Récupérer la structure du CDT : Il y a peut être quelquechose à faire de ça : https://github.com/SocialGouv/code-du-travail-data/blob/master/dataset/code_du_travail/TESTstructure.json

**Comment by revolunet** [comment]
Attente dump ePoseidon pour verifier qu'on peut récéuprer le HTML

**Comment by jrduscher** [comment]
Pourquoi l'issue apparaît dans la 1.3? Il me semble pas que quelque chose ait été là dessus à ce moment là.

**Comment by revolunet** [comment]
au vu de l'historique, elle était en 1.2 puis passée en 1.3... et ça doit être à ce moment là qu'on avait vu qu'on avait pas de HTML dans le fichier ePoseidon ?
