### ISSUE TITLE
[UX] Prévoir écran fin simulation IDL

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#949]
**Fonctionnalité**
A la fin du parcours IDL , afficher la différence entre IDL légale et conventionnelle.
Reprendre les éventuels paramètres clé du calcul

**Problème**
Actuellement le wording n'est pas forcément très clair et il manque d'infos pédagogiques

**Solution**
Définir les écrans et textes à afficher à l'utilisateur pour qu'il soit mieux informé sur son IDL
Créer une page résultat finale au calculateur, qui marque bien la dernière étape finale.

***fil***
Le fil est enrichi d'un 7 ème point:  Indemnité de licenciement applicable

***wording: résultat***
"Pour déterminer l'indemnité de licenciement,  le montant le plus favorable est retenu entre l'indemnité légale et l'indemnité conventionnelle."

Au regard des éléments saisis, 

le montant brut de l'indemnité de licenciement applicable correspond à l’indemnité légale 
/le montant brut de l'indemnité applicable correspond à l’indemnité conventionnelle.
Ce dernier s'élève à XXXXXXXX.XX€

***Voir le détail du calcul***
 
- Indemnité légale: 
- indemnité conventionnelle:
- Montant de l’indemnité retenue

- ancienneté retenue:  xxxx,xx années d'ancienneté
 + de précisions sur l'ancienneté?

- salaire de référence: retenu, montant des moyennes en jeu (3 dernriers mois, 12 derniers mois...)

Etat actuel : 

<img width="939" alt="Capture d’écran 2019-06-17 à 16 10 25" src="https://user-images.githubusercontent.com/124937/59665115-8ef2e500-91b2-11e9-80f0-866cae9b3e25.png">

*** ajouter le montant brut

**Comment by lionelB** [comment]
proposition : 

![image](https://user-images.githubusercontent.com/160320/60009826-d677e600-9676-11e9-9a57-347596332038.png)

**Comment by ClementChapalain** [comment]
je trouve ça trop bien ! quelques remarques :
- le noir sur bleu n'est pas très lisible, on peut essayer un gris très clair je pense
- le gris du cadre avec le montant minimum est un peu foncé je trouve, avec un gris plus clair le contraste serait meilleur
- à chaque fois, indiquer "montant brut minimum" et non uniquement "montant" afin de bien faire comprendre qu'on peut avoir plus en négociant et que c'est un montant brut (sauf dans la parenthèse à la fin sinon ça risque d'être lourd)
- en mobile, il faudrait revoir la présentation sinon j'ai peur que ce soit difficilement compréhensible

**Comment by virginielastisneres** [comment]
Proposition vue avec Clément et Aurélie :) 
https://www.figma.com/file/bTTqIa4qH3OdRMx5JULywV2P/Untitled?node-id=0%3A1
Pour le détail dans l'indemnité conventionnelle : il faudra adapter les éléments saisis en fonction des CCN :)
A ta dispo @lionelB pour tout besoin :)

**Comment by lionelB** [comment]
Je suis pas super emballé part le bar chart sans aucune échelle / info. Le but initial était de mettre en avant un élément plus que l'autre pas de les comparé sous forme de dataviz qui me parait pas vraiment adapté au propos (on veut mettre en avant une info (l'indemnité de licenciement) plus que comparer 2 résultats)

**Comment by virginielastisneres** [comment]
Je comprends @lionelB 
Ce n'est pas une bar chart mais je peux comprendre que vu comme ca, cela pourrait le faire croire. Nous avons fait ce choix pour deux raisons : avec les carrés c'était compliqué de mettre le détail du calcul qui est assez conséquent... et pour la version mobile c'est pas top... tu peux voir ce que cela donnerait dans cette page https://www.figma.com/file/bTTqIa4qH3OdRMx5JULywV2P/Untitled?node-id=31%3A17
Ce que je te propose c'est de réduire la largeur des rectangles pour éviter cet effet bar chart : 
![image](https://user-images.githubusercontent.com/48682104/61034493-ad20bf00-a3c5-11e9-9ea5-3226479b8613.png)

**Comment by lionelB** [comment]
Et un truc comme ça ca le ferait ?
![image](https://user-images.githubusercontent.com/160320/61114454-a57a1c80-a490-11e9-9d19-72fd72f083fd.png)

**Comment by lionelB** [comment]
poke @virginielastisneres @ClementChapalain @jrduscher  (j’ai pas le handle d’aurélie)

**Comment by virginielastisneres** [comment]
@lionelB pour moi les seules choses qui doivent absolument apparaître c'est la phrase d'explication suivante : **il s'agit du montant le plus favorable entre l'indemnité légale et l'indemnité conventionnelle**. **le détail** comme indiqué dans le figma et la **phrase de fin d'alerte** sur accord collectif contrat de travail etc... 
Après pour la forme d'un carré, rectangle, rond je te laisse voir ca avec clément et aurélie :)

**Comment by lionelB** [comment]
pour le détails du calcul, je suis pas sur de pouvoir généraliser ça à tout les calculs car c’est souvent plus compliqué que une phrase

**Comment by Auremie** [comment]
ici !

**Comment by ClementChapalain** [comment]
J'aime bien ta proposition aussi @lionelB :) Effectivement ça évite l'effet bar chart sans échelle.

En revanche il manque la phrase d'alerte sur l'accord d'entreprise qu'avait ajouté Virginie :
![image](https://user-images.githubusercontent.com/5337489/61202411-bbcde580-a6e7-11e9-82e1-5dbe59343ed8.png)

Pour le détail du calcul pourquoi on ne pourrait pas généraliser ? C'est une formule et pas une phrase 🤔
