### ISSUE TITLE
[search regression] Enter Key + Firefox

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#951]
**Description**
Lorsque l'usager utilise la touche entrée pour rechercher dans Firefox, il y a un "double submit" qui redirige vers une page HS.

Constaté dans Firefox 67, non reproduit sous Chrome

Probablement lié à #829 

**Reproduction**

 - Aller sur l'accueil dans FF67
 - Saisir un mot clé de recherche
 - Valider avec "entrée"

**Comportement attendu**
Affichage des résultats

**Screenshots**

![ff-enter](https://user-images.githubusercontent.com/124937/59680931-f15bdd80-91d2-11e9-93a5-e302fdb9c4b9.gif)

**Comment by lionelB** [comment]
le bug a disparu suite au fix #958
