### ISSUE TITLE
Faire une passe sur les css pour l'impression

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/code-du-travail-numerique#952]
Voir page par page, les optimisations  de style à faire lors de l'impression. Actuellement, nous supprimons la rechercher et le footer mais il y a surement moyen de faire mieux

**Comment by ClementChapalain** [comment]
fait pour les pages de résultat d'outil

**Comment by lionelB** [comment]
@UnbearableBear on peut fermer l'issue ou tu penses qu'il reste encore des choses à faire

**Comment by UnbearableBear** [comment]
Je ne sais pas, il faudra que je fasse un tour de toutes les pages ça me donnera surement des idées
