### ISSUE TITLE
Bug report "lien mort" et footer obsolèten harminsation avec les réponses in IDL

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#955]
**Description**
Suppression d'un lien mort résiduel, sur demande récente de la région à l'origine de ce lien.  il anque des fonctionnalités par raport aux paes de résultat.

**Reproduction**
Le  footer de de l'outil de calcul de l'indmenité de licenciement, est une relique du footer de la page résultat d'une ancienne vrsion, dans les liens proposés, certains dont le code BFC sont morts..

**Comportement attendu**
Supprimer le footer ou à minima le lien mort.
ajouter le lien de "retoure en haut à gauche

**Screenshots**
[image](https://user-images.githubusercontent.com/37538697/59843316-9ce26a80-9358-11e9-8a6c-24391024a847.png)
**Configuration**
_optionnel_ Si nécessaire, ajoutez le navigateur sur lequel vous avez repéré le problème
  - Device: _ex: iPhone_
  - Navigateur: _ex: Chrome_
  - Version du navigateur : _ex: 74.0.3729.169_

**Comment by lionelB** [comment]
il me semble que cela a deja fait l'objet d'une PR qui a était mergée,  je n'arrive pas a retrouvé la page 
poke @revolunet

**Comment by revolunet** [comment]
un exemple d'url @jrduscher ?

**Comment by lionelB** [comment]
fait dans la pr #921 
il faut qu'on release depuis travis et mette à jour la prod dans que la PR #1001 est mergée
