### ISSUE TITLE
Bug report : Fil d'ariane, calculateur IDL

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-numerique#957]
**Description**
ETQ utilisateur, dans le fil du calclateur, dans les premières pages, je ne sais pas que mon indemnité conventionnelle sera calculée.

**Comportement attendu**
Le fil s'afficha au complet ( L'IDLL est visivible l'ICL en grisé)

wording is needed, précision sur la définition du licenciement aussi.

**Comment by lionelB** [comment]
j'ai modifié en amélioration car ce n'est pas un bug à mon sens.

**Comment by ClementChapalain** [comment]
plus vraiment d'actualité vu qu'on souhaite changer le fonctionnement du calculateur
