### ISSUE TITLE
meta are undefined

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/code-du-travail-numerique#981]
**Description**
Description claire et concise du bug

**Reproduction**
Etapes à suivre pour reproduire le bug
1. go Home
2. Click on links
3. Inspect head>meta 
4. og:xxxx meta are undefined

**Comportement attendu**
_optionnel_ Si nécessaire, explications du comportement attendu

**Screenshots**
![Capture d’écran 2019-06-28 à 17 57 15](https://user-images.githubusercontent.com/160320/60355351-74004c00-99ce-11e9-8092-96dc3a16a74b.png)

**Comment by UnbearableBear** [comment]
Ahhh pas bien, ca doit être moi ça, je prends !
