### ISSUE TITLE
Google indexe les résultats de la version -dev du CDTN

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#985]
**Description**
Google indexe les résultats de la version -dev, par exemple https://codedutravail-dev.num.social.gouv.fr/fiche-ministere-travail/csp-quelle-est-la-procedure?q=Contrat%20de%20s%C3%A9curisation%20professionnelle%20(CSP)

**Reproduction**
Etapes à suivre pour reproduire le bug
1. chercher "envoi dossier csp pole emploi" sur google
2. aller à la page 2

**Comportement attendu**
On devrait avoir
```
https://codedutravail.num.social.gouv.fr/fiche-ministere-travail/csp-quelle-est-la-procedure?q=Contrat%20de%20s%C3%A9curisation%20professionnelle%20(CSP)
```

et même (je suis moins sur pour ça mais ça me parait bizarre d'avoir un paramètre dans l'url canonique)
```
https://codedutravail-dev.num.social.gouv.fr/fiche-ministere-travail/csp-quelle-est-la-procedure
```

Google appelle ça des urls canoniques je crois, j'ai trouvé ça en me baladant dans la search console de google, on peut regarder ensemble si vous voulez.

**Screenshots**
![image](https://user-images.githubusercontent.com/5337489/60432859-9fb84780-9c03-11e9-9902-e39c572658a8.png)

**Comment by lionelB** [comment]
yep il faudrait mettre robot.txt sur le dev

**Comment by lionelB** [comment]
https://www.webrankinfo.com/dossiers/techniques/url-canonique

**Comment by revolunet** [comment]
si besoin pour robots.txt https://github.com/zeit/next.js/tree/canary/examples/with-sitemap-and-robots-express-server
