### ISSUE TITLE
[IDL] : indemnité légale non reprise dans l'écran final

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#986]
<img width="942" alt="Capture d’écran 2019-07-01 à 14 20 43" src="https://user-images.githubusercontent.com/124937/60436142-bb275080-9c0b-11e9-800a-a74b90e662f3.png">

**Comment by lionelB** [comment]
Est ce que tu pourrais rajouter les paramètres qui ont mené à cet écran ?

**Comment by revolunet** [comment]
une des CCNs issue de #893 par exemple "Animation"

**Comment by lionelB** [comment]
oki merci !
