### ISSUE TITLE
Ajouter une page d'intro au calculateur d'indemnité de licenciement

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-numerique#987]
Retour utilisateur : lorsqu'on arrive sur le calculateur d'indemnité de licenciement est lancé, on se retrouve direct avec des questions sans info sur ce que l'on va y trouver et l'effort qui va m'être demandé.

Proposition : ajouter une page d'introduction avec les éléments suivants :

**fil d'ariane**
tous les éléments sont grisés

**texte**
> Cet outil permet de calculer l'indemnité minimale de licenciement d'un salarié.
> 
> Vous pourrez calculer simplement le montant de l'indemnité légale (définie par le Code du travail) et de l'indemnité conventionnelle (si votre branche d'activité prévoit un montant supérieur au Code du travail).
> 
> Cette simulation nécessite entre 5 et 10 minutes pour être complétée. Afin de pouvoir remplir les renseignements demandés, munissez-vous des informations relatives à votre licenciement (dates d'entrée et de sortie de l'entreprise, courrier de licenciement, derniers bulletins de salaire, etc.).
> 
> Pour en savoir plus sur l'indemnité de licenciement et son mode de calcul, consultez cet article (lien vers la fiche SP sur l'IDL). Pour commencer la simulation cliquez sur "Débuter la simulation".

**bouton**
Un bouton "Débuter la simulation" qui lance l'écran avec les premières questions.

**Comment by ClementChapalain** [comment]
ping @virginielastisneres je veux bien ton avis stp :)

**Comment by virginielastisneres** [comment]
@ClementChapalain 
Désolé du retard... 
Ci-dessous ma proposition : j'utiliserai plutôt le terme **"simulateur de l'indemnité de licenciement"** que calculateur. 

"Ce simulateur est un outil qui permet d'estimer le montant de l'indemnité minimale de licenciement d'un salarié.

Vous pourrez simuler simplement le montant de l'indemnité légale définie par le Code du travail et le montant de l'indemnité conventionnelle de licenciement si votre branche d'activité prévoit un montant supérieur au Code du travail.

Cette simulation nécessite entre 5 et 10 minutes. Afin de pouvoir remplir les renseignements demandés, munissez-vous des informations relatives à votre licenciement (dates d'entrée et de sortie de l'entreprise, courrier de licenciement, derniers bulletins de salaire, etc.).

Pour en savoir plus sur l'indemnité de licenciement et son mode de calcul, consultez cet article (lien vers la fiche SP sur l'IDL). 

Pour commencer la simulation cliquez sur "Suivant".

**Comment by lionelB** [comment]
simulateur se retrouve aussi pas mal sur le web, ca pourrait etre une bonne chose de le renomé

**Comment by ClementChapalain** [comment]
complètement d'accord pour simulateur

**Comment by UnbearableBear** [comment]
C'est modifié, j'ai pris le wording de virginie !
