### ISSUE TITLE
Intégrer outil choix CCN

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-numerique#99]
Proposer l'outil lorsque l'on recherche sa convention collective

**Comment by revolunet** [comment]
Pourquoi ne pas chercher la CCN dans la barre de recherche directement ?
(= intégrer nos références legifrance dans ElasticSearch)

**Comment by revolunet** [comment]
-> intégrer dans la recherche directement

**Comment by jrduscher** [comment]
REVUE CLF+JR:

je recherche le texte de la ccn, je tapes le numéro idcc ou l'intitulé:  je tombe sur un menu de filtres; celui ci me propose soit les thèmes de la FAQ soit les départements, soit un "autres "qui n'est pas bien explicite. en tant qu'utilisateur je ne sais pas vers quoi va me guider ces filtres de manière plus exacte
Un correctif doit être mené dans une nouvelle issue: https://github.com/SocialGouv/code-du-travail-numerique/issues/207

**Comment by jrduscher** [comment]
Autre point: réintégration de l'aide dans la modal+ amélioration de la navigation: ok sur le front.
Par contre : la recherche " boulangerie industrielle est déceptive": le premier résultat n'est pas la boulangerie, le surligneur ne fait pas apparaître en premier la bonne convention collective.
